ALTER TABLE DEF_CHARGE_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_CHARGE_TYPE CASCADE CONSTRAINTS;

CREATE TABLE DEF_CHARGE_TYPE
(
  DC_TYPE              CHAR(1 BYTE),
  DC_DESC              VARCHAR2(50 BYTE),
  DC_CREATE_TIMESTAMP  DATE,
  DC_CREATE_USER       VARCHAR2(20 BYTE),
  DC_UPDATE_TIMESTAMP  DATE,
  DC_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEF_CHARGE__TYPE_PK ON DEF_CHARGE_TYPE
(DC_TYPE)
LOGGING
TABLESPACE USER_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_CHARGE_TYPE ADD (
  CONSTRAINT DEF_CHARGE__TYPE_PK
  PRIMARY KEY
  (DC_TYPE)
  USING INDEX DEF_CHARGE__TYPE_PK);

