OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/RuleTxnLimit
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBRuleTxnLimit.so
SOOBJS =  RuleTxnLimit.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
