OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLAutoUploadJobTmp
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLAutoUploadJobTmp.so
SOOBJS =  OLAutoUploadJobTmp.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
