OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/CrrJnl
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBCrrJnl.so
SOOBJS =  CrrJnl.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
