OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLTxnRequestRef
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLTxnRequestRef.so
SOOBJS =  OLTxnRequestRef.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
