OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnMgtByUsVWB
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnMgtByUsVWB.so
SOOBJS = TxnMgtByUsVWB.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
