OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MapTxnElement
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMapTxnElement.so
SOOBJS =  MapTxnElement.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
