OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MiEntityRsp
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMiEntityRsp.so
SOOBJS =  MiEntityRsp.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
