OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/EmailSetting
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBEmailSetting.so
SOOBJS =  EmailSetting.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
