OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/TxnRptUrl
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBTxnRptUrl.so
SOOBJS =  TxnRptUrl.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
