OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/PspPayMethod
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBPspPayMethod.so
SOOBJS =  PspPayMethod.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
