ALTER TABLE MMS_REVERSE_RETRY
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_REVERSE_RETRY CASCADE CONSTRAINTS;

CREATE TABLE MMS_REVERSE_RETRY
(
  MV_TXN_ID      VARCHAR2(16 BYTE),
  MV_DTL_TXN_ID     VARCHAR2(16 BYTE),
  MV_STATUS            CHAR(1 BYTE),
  MV_LOCAL_TM_DATE     VARCHAR2(8 BYTE),
  MV_LOCAL_TM_TIME     VARCHAR2(6 BYTE),
  MV_NEXT_TRY          DATE,
  MV_CREATE_USER       VARCHAR2(20 BYTE),
  MV_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  MV_UPDATE_USER       VARCHAR2(20 BYTE),
  MV_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  MV_RESEND_COUNT      INTEGER                  DEFAULT 0,
  MV_RESET_CNT_TIMESTAMP  DATE
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN MMS_REVERSE_RETRY.MV_STATUS IS '''F'' First try, ''R'' - Retry, ''C- Complete';



CREATE INDEX MMS_REVERSE_RETRY_IDX01 ON MMS_REVERSE_RETRY
(MV_TXN_ID,MV_DTL_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX MMS_REVERSE_RETRY_IDX02 ON MMS_REVERSE_RETRY
(MV_NEXT_TRY)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_REVERSE_RETRY ADD (
  CONSTRAINT MMS_REVERSE_RETRY_PK
  PRIMARY KEY
  (MV_TXN_ID,MV_DTL_TXN_ID)
  USING INDEX MMS_REVERSE_RETRY_IDX01
  ENABLE VALIDATE);

