ALTER TABLE OL_MERCHANT_BALANCE
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_MERCHANT_BALANCE CASCADE CONSTRAINTS;

CREATE TABLE OL_MERCHANT_BALANCE
(
  OM_MERCHANT_ID             VARCHAR2(15 BYTE),
  OM_CURRENCY_ID             VARCHAR2(3 BYTE),
  OM_COUNTRY_ID              CHAR(2 BYTE),
  OM_SERVICE_CODE            CHAR(3 BYTE),
  OM_CURRENT_BAL             NUMBER(14,2)        DEFAULT 0,
  OM_CURRENT_BAL_SETTLEMENT  NUMBER(14,2)        DEFAULT 0,
  OM_TOTAL_FLOAT_AFTER_PAYOUT  NUMBER(14,2)        DEFAULT 0,
  OM_TOTAL_FLOAT_SETTLEMENT  NUMBER(14,2)        DEFAULT 0,
  OM_TOTAL_RESERVED_AMOUNT   NUMBER(14,2)        DEFAULT 0,
  OM_FUNDIN_PAYOUT           NUMBER(14,2)        DEFAULT 0,
  OM_RESERVED_PAYOUT         NUMBER(14,2)        DEFAULT 0,
  OM_TOTAL_HOLD              NUMBER(14,2)        DEFAULT 0,
  OM_TOTAL_HOLD_SETTLEMENT   NUMBER(14,2)        DEFAULT 0,
  OM_SETTLEMENT_IN_TRANSIT   NUMBER(14,2)        DEFAULT 0,
  OM_CREATE_TIMESTAMP        DATE                DEFAULT sysdate,
  OM_UPDATE_TIMESTAMP        DATE                DEFAULT sysdate,
  OM_CREATE_USER             VARCHAR2(20 BYTE),
  OM_UPDATE_USER             VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_MERCHANT_BALANCE_PK ON OL_MERCHANT_BALANCE
(OM_MERCHANT_ID, OM_CURRENCY_ID, OM_COUNTRY_ID, OM_SERVICE_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_MERCHANT_BALANCE ADD (
  CONSTRAINT OL_MERCHANT_BALANCE_PK
  PRIMARY KEY
  (OM_MERCHANT_ID, OM_CURRENCY_ID, OM_COUNTRY_ID, OM_SERVICE_CODE)
  USING INDEX OL_MERCHANT_BALANCE_PK
  ENABLE VALIDATE);

ALTER TABLE OL_MERCHANT_BALANCE ADD (
  CONSTRAINT OL_MERCHANT_BALANCE_F03 
  FOREIGN KEY (OM_SERVICE_CODE) 
  REFERENCES DEF_SERVICE_CODE (SC_CODE)
  ENABLE VALIDATE,
  CONSTRAINT OL_MERCHANT_BALANCE_FK01 
  FOREIGN KEY (OM_MERCHANT_ID) 
  REFERENCES OL_MERCH_DETAIL (MD_MERCHANT_ID)
  ENABLE VALIDATE,
  CONSTRAINT OL_MERCHANT_BALANCE_FK02 
  FOREIGN KEY (OM_CURRENCY_ID) 
  REFERENCES DEF_CURRENCY (DC_CCY_ID)
  ENABLE VALIDATE,
  CONSTRAINT OL_MERCHANT_BALANCE_FK04 
  FOREIGN KEY (OM_COUNTRY_ID) 
  REFERENCES COUNTRY (COUNTRY_CODE)
  ENABLE VALIDATE);

