ALTER TABLE OL_PSP_COSTS
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_PSP_COSTS CASCADE CONSTRAINTS;

CREATE TABLE OL_PSP_COSTS
(
  OPC_RULE_ID             INTEGER,
  OPC_PARTY_TYPE          VARCHAR2(6 BYTE),
  OPC_PARTY_ID            VARCHAR2(20 BYTE),
  OPC_CAT_ID              VARCHAR2(25 BYTE),
  OPC_EFFECT_DATE         DATE,
  OPC_CAL_METHOD          CHAR(1 BYTE),
  OPC_CHARGE_PERIOD_TYPE  CHAR(1 BYTE),
  OPC_GROUPING_TYPE       CHAR(1 BYTE),
  OPC_COSTING_METHOD      CHAR(1 BYTE),
  OPC_VALUE               NUMBER(12,5),
  OPC_ADDITIONAL_VALUE    NUMBER(12,2),
  OPC_MIN_VALUE           NUMBER(12,2),
  OPC_MAX_VALUE           NUMBER(12,2),
  OPC_VALUE_TYPE          CHAR(1 BYTE),
  OPC_SCALE               INTEGER,
  OPC_DISABLED            INTEGER,
  OPC_CREATE_TIMESTAMP    DATE                  DEFAULT sysdate,
  OPC_UPDATE_TIMESTAMP    DATE                  DEFAULT sysdate,
  OPC_CREATE_USER         VARCHAR2(20 BYTE),
  OPC_UPDATE_USER         VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX OL_PSP_COSTS_IDX01 ON OL_PSP_COSTS
(OPC_PARTY_TYPE, OPC_PARTY_ID, OPC_CAT_ID, OPC_EFFECT_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX OL_PSP_COSTS_PK ON OL_PSP_COSTS
(OPC_RULE_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_PSP_COSTS ADD (
  CONSTRAINT OL_PSP_COSTS_PK
  PRIMARY KEY
  (OPC_RULE_ID)
  USING INDEX OL_PSP_COSTS_PK
  ENABLE VALIDATE);

ALTER TABLE OL_PSP_COSTS ADD (
  CONSTRAINT OL_PSP_COSTS_FK01 
  FOREIGN KEY (OPC_PARTY_TYPE) 
  REFERENCES OL_DEF_PARTY_TYPE (OPT_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OL_PSP_COSTS_FK02 
  FOREIGN KEY (OPC_VALUE_TYPE) 
  REFERENCES DEF_ROUNDING (DR_TYPE)
  ENABLE VALIDATE);

