CREATE OR REPLACE FUNCTION sp_ol_psp_costs_find (
  in_provider_id	ol_psp_costs.opc_party_id%type,
  in_psp_id		ol_psp_costs.opc_party_id%type,
  in_baid		ol_psp_costs.opc_party_id%type,
  in_txn_code		ol_psp_costs_category.opcc_txn_code%type,
  out_cursor		out sys_refcursor)

RETURN NUMBER Is
	iCnt	integer := 0;
Begin
	SELECT	COUNT(*)
	INTO	iCnt
	FROM	OL_PSP_COSTS,
		OL_PSP_COSTS_CATEGORY,
		OL_BANK_ACCT_ID
	WHERE	OPC_EFFECT_DATE =
		(SELECT	MAX(OPC_EFFECT_DATE)
		 FROM	OL_PSP_COSTS
		 WHERE	OPC_EFFECT_DATE<SYSDATE
		 AND	OPC_PARTY_TYPE = 'BAID'
		 AND	OPC_PARTY_ID = in_baid
		 AND	OPCC_TXN_CODE = in_txn_code
		 AND	OPC_DISABLED = 0
		)
	AND	OPC_PARTY_TYPE = 'BAID'
	AND	OPC_PARTY_ID = in_baid
	AND	OPCC_TXN_CODE = in_txn_code
	AND	OPC_DISABLED = 0
	AND	OPC_CAT_ID = OPCC_CAT_ID
	AND	OBAI_BAID = OPC_PARTY_ID
	AND	OBAI_CATEGORY NOT IN	(SELECT	OPCE_EXCLUDE_ACCT_TYPE
					 FROM	OL_PSP_COSTS_EXCLUDE
					 WHERE	OPC_RULE_ID = OPCE_RULE_ID);

	if iCnt > 0 then
		open out_cursor for
		SELECT	OPC_RULE_ID,
			OPC_PARTY_TYPE,
			OPC_PARTY_ID,
			OPC_CAT_ID,
			OPCC_TXN_CODE,
			OPCC_GEN_TXN_CODE,
			OPCC_AMT_TYPE,
			OPC_CAL_METHOD,
			OPC_CHARGE_PERIOD_TYPE,
			OPC_GROUPING_TYPE,
			OPC_COSTING_METHOD,
			OPC_VALUE,
			OPC_ADDITIONAL_VALUE,
			OPC_MIN_VALUE,
			OPC_MAX_VALUE,
			OPC_VALUE_TYPE,
			OPC_SCALE
		FROM	OL_PSP_COSTS,
			OL_PSP_COSTS_CATEGORY
		WHERE	OPC_EFFECT_DATE =
			(SELECT	MAX(OPC_EFFECT_DATE)
			 FROM	OL_PSP_COSTS
			 WHERE	OPC_EFFECT_DATE<SYSDATE
			 AND	OPC_PARTY_TYPE = 'BAID'
			 AND	OPC_PARTY_ID = in_baid
			 AND	OPCC_TXN_CODE = in_txn_code
			 AND	OPC_DISABLED = 0
			)
		AND	OPC_PARTY_TYPE = 'BAID'
		AND	OPC_PARTY_ID = in_baid
		AND	OPCC_TXN_CODE = in_txn_code
		AND	OPC_DISABLED = 0
		AND	OPC_CAT_ID = OPCC_CAT_ID;

		RETURN 1;
	else
		SELECT	COUNT(*)
		INTO	iCnt
		FROM	OL_PSP_COSTS,
			OL_PSP_COSTS_CATEGORY
		WHERE	OPC_EFFECT_DATE =
			(SELECT	MAX(OPC_EFFECT_DATE)
			 FROM	OL_PSP_COSTS
			 WHERE	OPC_EFFECT_DATE<SYSDATE
			 AND	OPC_PARTY_TYPE = 'PID'
			 AND	OPC_PARTY_ID = in_psp_id
			 AND	OPCC_TXN_CODE = in_txn_code
			 AND	OPC_DISABLED = 0
			)
		AND	OPC_PARTY_TYPE = 'PID'
		AND	OPC_PARTY_ID = in_psp_id
		AND	OPCC_TXN_CODE = in_txn_code
		AND	OPC_DISABLED = 0
		AND	OPC_CAT_ID = OPCC_CAT_ID
		AND	(SELECT	COUNT(*) 
			 FROM	OL_BANK_ACCT_ID
			 WHERE	OBAI_BAID = in_baid
			 AND	OBAI_CATEGORY NOT IN	(SELECT	OPCE_EXCLUDE_ACCT_TYPE
							 FROM	OL_PSP_COSTS_EXCLUDE
							 WHERE	OPCE_RULE_ID = OPC_RULE_ID)) > 0;

		if iCnt > 0  then
			OPEN out_cursor for
			SELECT	OPC_RULE_ID,
				OPC_PARTY_TYPE,
				OPC_PARTY_ID,
				OPC_CAT_ID,
				OPCC_TXN_CODE,
				OPCC_GEN_TXN_CODE,
				OPCC_AMT_TYPE,
				OPC_CAL_METHOD,
				OPC_CHARGE_PERIOD_TYPE,
				OPC_GROUPING_TYPE,
				OPC_COSTING_METHOD,
				OPC_VALUE,
				OPC_ADDITIONAL_VALUE,
				OPC_MIN_VALUE,
				OPC_MAX_VALUE,
				OPC_VALUE_TYPE,
				OPC_SCALE
			FROM	OL_PSP_COSTS,
				OL_PSP_COSTS_CATEGORY
			WHERE	OPC_EFFECT_DATE =
				(SELECT	MAX(OPC_EFFECT_DATE)
				 FROM	OL_PSP_COSTS
				 WHERE	OPC_EFFECT_DATE<SYSDATE
				 AND	OPC_PARTY_TYPE = 'PID'
				 AND	OPC_PARTY_ID = in_psp_id
				 AND	OPCC_TXN_CODE = in_txn_code
				 AND	OPC_DISABLED = 0
				)
			AND	OPC_PARTY_TYPE = 'PID'
			AND	OPC_PARTY_ID = in_psp_id
			AND	OPCC_TXN_CODE = in_txn_code
			AND	OPC_DISABLED = 0
			AND	OPC_CAT_ID = OPCC_CAT_ID;

			RETURN 1;
		else
			SELECT	COUNT(*)
			INTO	iCnt
			FROM	OL_PSP_COSTS,
				OL_PSP_COSTS_CATEGORY
			WHERE	OPC_EFFECT_DATE =
				(SELECT	MAX(OPC_EFFECT_DATE)
				 FROM	OL_PSP_COSTS
				 WHERE	OPC_EFFECT_DATE<SYSDATE
				 AND	OPC_PARTY_TYPE = 'PROV'
				 AND	OPC_PARTY_ID = in_provider_id
				 AND	OPCC_TXN_CODE = in_txn_code
				 AND	OPC_DISABLED = 0
				)
			AND	OPC_PARTY_TYPE = 'PROV'
			AND	OPC_PARTY_ID = in_provider_id
			AND	OPCC_TXN_CODE = in_txn_code
			AND	OPC_DISABLED = 0
			AND	OPC_CAT_ID = OPCC_CAT_ID
			AND	(SELECT	COUNT(*)
				 FROM	OL_BANK_ACCT_ID
				 WHERE	OBAI_BAID = in_baid
				 AND	OBAI_CATEGORY NOT IN	(SELECT	OPCE_EXCLUDE_ACCT_TYPE
								 FROM	OL_PSP_COSTS_EXCLUDE
								 WHERE	OPCE_RULE_ID = OPC_RULE_ID)) > 0;

			if iCnt > 0  then
				OPEN out_cursor for
				SELECT	OPC_RULE_ID,
					OPC_PARTY_TYPE,
					OPC_PARTY_ID,
					OPC_CAT_ID,
					OPCC_TXN_CODE,
					OPCC_GEN_TXN_CODE,
					OPCC_AMT_TYPE,
					OPC_CAL_METHOD,
					OPC_CHARGE_PERIOD_TYPE,
					OPC_GROUPING_TYPE,
					OPC_COSTING_METHOD,
					OPC_VALUE,
					OPC_ADDITIONAL_VALUE,
					OPC_MIN_VALUE,
					OPC_MAX_VALUE,
					OPC_VALUE_TYPE,
					OPC_SCALE
				FROM	OL_PSP_COSTS,
					OL_PSP_COSTS_CATEGORY
				WHERE	OPC_EFFECT_DATE =
					(SELECT	MAX(OPC_EFFECT_DATE)
					 FROM	OL_PSP_COSTS
					 WHERE	OPC_EFFECT_DATE<SYSDATE
					 AND	OPC_PARTY_TYPE = 'PROV'
					 AND	OPC_PARTY_ID = in_provider_id
					 AND	OPCC_TXN_CODE = in_txn_code
					 AND	OPC_DISABLED = 0
					)
				AND	OPC_PARTY_TYPE = 'PROV'
				AND	OPC_PARTY_ID = in_provider_id
				AND	OPCC_TXN_CODE = in_txn_code
				AND	OPC_DISABLED = 0
				AND	OPC_CAT_ID = OPCC_CAT_ID;

				RETURN 1;
			else
				SELECT	COUNT(*)
				INTO	iCnt
				FROM	OL_PSP_COSTS,
					OL_PSP_COSTS_CATEGORY
				WHERE	OPC_EFFECT_DATE =
					(SELECT	MAX(OPC_EFFECT_DATE)
					 FROM	OL_PSP_COSTS
					 WHERE	OPC_EFFECT_DATE<SYSDATE
					 AND	OPC_PARTY_TYPE = 'GLOBAL'
					 AND	OPC_PARTY_ID = in_psp_id
					 AND	OPCC_TXN_CODE = in_txn_code
					 AND	OPC_DISABLED = 0
					)
				AND	OPC_PARTY_TYPE = 'GLOBAL'
				AND	OPCC_TXN_CODE = in_txn_code
				AND	OPC_DISABLED = 0
				AND	OPC_CAT_ID = OPCC_CAT_ID
				AND	(SELECT	COUNT(*)
					 FROM	OL_BANK_ACCT_ID
					 WHERE	OBAI_BAID = in_baid
					 AND	OBAI_CATEGORY NOT IN	(SELECT	OPCE_EXCLUDE_ACCT_TYPE
									 FROM	OL_PSP_COSTS_EXCLUDE
									 WHERE	OPCE_RULE_ID = OPC_RULE_ID)) > 0;

				if iCnt > 0  then
					OPEN out_cursor for
					SELECT	OPC_RULE_ID,
						OPC_PARTY_TYPE,
						OPC_PARTY_ID,
						OPC_CAT_ID,
						OPCC_TXN_CODE,
						OPCC_GEN_TXN_CODE,
						OPCC_AMT_TYPE,
						OPC_CAL_METHOD,
						OPC_CHARGE_PERIOD_TYPE,
						OPC_GROUPING_TYPE,
						OPC_COSTING_METHOD,
						OPC_VALUE,
						OPC_ADDITIONAL_VALUE,
						OPC_MIN_VALUE,
						OPC_MAX_VALUE,
						OPC_VALUE_TYPE,
						OPC_SCALE
					FROM	OL_PSP_COSTS,
						OL_PSP_COSTS_CATEGORY
					WHERE	OPC_EFFECT_DATE =
						(SELECT	MAX(OPC_EFFECT_DATE)
						 FROM	OL_PSP_COSTS
						 WHERE	OPC_EFFECT_DATE<SYSDATE
						 AND	OPC_PARTY_TYPE = 'GLOBAL'
						 AND	OPCC_TXN_CODE = in_txn_code
						 AND	OPC_DISABLED = 0
						)
					AND	OPC_PARTY_TYPE = 'GLOBAL'
					AND	OPCC_TXN_CODE = in_txn_code
					AND	OPC_DISABLED = 0
					AND	OPC_CAT_ID = OPCC_CAT_ID;

					RETURN 1;
				else
					RETURN 0;
				end if;
			end if;
                end if;
	end if;


	RETURN 0;


 exception
   WHEN OTHERS THEN
     RETURN 0;
END sp_ol_psp_costs_find;
/

