OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/ServiceUIRelease
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBServiceUIRelease.so
SOOBJS =  ServiceUIRelease.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
