OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/CustomerTxnHist
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBCustomerTxnHist.so
SOOBJS =  CustomerTxnHist.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
