OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MerchCurrency
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMerchCurrency.so
SOOBJS =  MerchCurrency.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
