OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/CrrExtJnlLog
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBCrrExtJnlLog.so
SOOBJS =  CrrExtJnlLog.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
