ALTER TABLE OL_STMT_FORMAT_KEYWORDS_OVER
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_STMT_FORMAT_KEYWORDS_OVER CASCADE CONSTRAINTS;

CREATE TABLE OL_STMT_FORMAT_KEYWORDS_OVER
(
  OFKO_INT_BANK_CODE     VARCHAR2(10 BYTE)      NOT NULL,
  OFKO_BANK_ACCT_TYPE    CHAR(3 BYTE)           NOT NULL,
  OFKO_BAID_TXN_CODE     CHAR(3 BYTE)           NOT NULL,
  OFKO_IS_DEFAULT        INTEGER                NOT NULL,
  OFKO_DISABLED          INTEGER                DEFAULT 0,
  OFKO_CREATE_TIMESTAMP  DATE                   DEFAULT SYSDATE,
  OFKO_UPDATE_TIMESTAMP  DATE                   DEFAULT SYSDATE,
  OFKO_CREATE_USER       VARCHAR2(25 BYTE),
  OFKO_UPDATE_USER       VARCHAR2(25 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_STMT_FORMAT_KW_OVER_PK ON OL_STMT_FORMAT_KEYWORDS_OVER
(OFKO_INT_BANK_CODE, OFKO_BANK_ACCT_TYPE, OFKO_BAID_TXN_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_STMT_FORMAT_KEYWORDS_OVER ADD (
  CONSTRAINT OL_STMT_FORMAT_KW_OVER_PK
  PRIMARY KEY
  (OFKO_INT_BANK_CODE, OFKO_BANK_ACCT_TYPE, OFKO_BAID_TXN_CODE)
  USING INDEX OL_STMT_FORMAT_KW_OVER_PK
  ENABLE VALIDATE);

