OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/PspMaster
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBPspMaster.so
SOOBJS = PspMaster.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
