


CREATE TABLE OL_DEF_TRIGGER_STATUS
(
  DTS_STATUS            CHAR(1 BYTE),
  DTS_DESC              VARCHAR2(50 BYTE),
  DTS_CREATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  DTS_CREATE_USER       VARCHAR2(20 BYTE),
  DTS_UPDATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  DTS_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX OL_DEF_TRIGGER_STATUS_PK ON OL_DEF_TRIGGER_STATUS
(DTS_STATUS)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE OL_DEF_TRIGGER_STATUS ADD (
  CONSTRAINT OL_DEF_TRIGGER_STATUS_PK
  PRIMARY KEY
  (DTS_STATUS)
  USING INDEX OL_DEF_TRIGGER_STATUS_PK
  ENABLE VALIDATE);

