ALTER TABLE OL_EMAIL_FUNCT_SERVICE
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_EMAIL_FUNCT_SERVICE CASCADE CONSTRAINTS;

CREATE TABLE OL_EMAIL_FUNCT_SERVICE
(
  EFS_FUNCT             VARCHAR2(10 BYTE),
  EFS_SERVICE_CODE      CHAR(3 BYTE),
  EFS_DISABLED          INTEGER,
  EFS_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  EFS_CREATE_USER       VARCHAR2(20 BYTE),
  EFS_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  EFS_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_EMAIL_FUNCT_SERVICE_PK ON OL_EMAIL_FUNCT_SERVICE
(EFS_FUNCT, EFS_SERVICE_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_EMAIL_FUNCT_SERVICE ADD (
  CONSTRAINT OL_EMAIL_FUNCT_SERVICE_PK
  PRIMARY KEY
  (EFS_FUNCT, EFS_SERVICE_CODE)
  USING INDEX OL_EMAIL_FUNCT_SERVICE_PK
  ENABLE VALIDATE);

ALTER TABLE OL_EMAIL_FUNCT_SERVICE ADD (
  CONSTRAINT OL_EMAIL_FUNCT_SERVICE_FK01 
  FOREIGN KEY (EFS_FUNCT) 
  REFERENCES OL_DEF_EMAIL_NOTIFY_FUNCT (OEF_FUNCT)
  ENABLE VALIDATE,
  CONSTRAINT OL_EMAIL_FUNCT_SERVICE_FK02 
  FOREIGN KEY (EFS_SERVICE_CODE) 
  REFERENCES DEF_SERVICE_CODE (SC_CODE)
  ENABLE VALIDATE);

