DROP TABLE FUNDS_IN_HISTORY CASCADE CONSTRAINTS;

CREATE TABLE FUNDS_IN_HISTORY
(
  FI_FUNDS_IN_ID	INTEGER,
  FI_FUNDS_IN_DATE     VARCHAR2(8 BYTE),
  FI_FUNDS_IN_CCY      VARCHAR2(3 BYTE),
  FI_FUNDS_IN_AMT      NUMBER(14,2),
  FI_BANK_CCY          VARCHAR2(3 BYTE),
  FI_BANK_AMT          NUMBER(14,2),
  FI_OLD_RATE          NUMBER(14,5),
  FI_NEW_RATE          NUMBER(14,5),
  FI_OLD_RATIO         NUMBER(14,5),
  FI_NEW_RATIO         NUMBER(14,5),
  FI_BANK_BAL          NUMBER(14,2),
  FI_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  FI_CREATE_USER       VARCHAR2(20 BYTE),
  FI_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  FI_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX FUNDS_IN_HISTORY_IDX01 ON FUNDS_IN_HISTORY
(FI_FUNDS_IN_ID, FI_FUNDS_IN_CCY, FI_BANK_CCY)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


