OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOCommChk
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOCommChk.so
SOOBJS = BOCommChk.o

include $(HOME)/config/Make.rules

LDLIBS += 
CPPFLAGS += 
all	: $(COMPSO)
