ALTER TABLE PAYOUT_GENERATED_FILE_HD
 DROP PRIMARY KEY CASCADE;

DROP TABLE PAYOUT_GENERATED_FILE_HD CASCADE CONSTRAINTS;

CREATE TABLE PAYOUT_GENERATED_FILE_HD
(
  FH_FILE_ID           NUMBER(16),
  FH_FILE_DATE         VARCHAR2(8 BYTE),
  FH_FILE_PID          VARCHAR2(10 BYTE),
  FH_SEQ_NUM           INTEGER,
  FH_FILENAME          VARCHAR2(50 BYTE),
  FH_STATUS            INTEGER,
  FH_TXN_COUNT         INTEGER,
  FH_TOTAL_TXN_AMT     NUMBER(14,2),
  FH_CCY_ID            VARCHAR2(3 BYTE),
  FH_CREATE_USER       VARCHAR2(20 BYTE),
  FH_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  FH_UPDATE_USER       VARCHAR2(20 BYTE),
  FH_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  FH_TXN_ID            VARCHAR2(16 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX PAYOUT_GENERATED_FILE_HD_IDX01 ON PAYOUT_GENERATED_FILE_HD
(FH_FILE_ID, FH_STATUS)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX PAYOUT_GENERATED_FILE_HD_IDX02 ON PAYOUT_GENERATED_FILE_HD
(FH_STATUS)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX PAYOUT_GENERATED_FILE_HD_IDX03 ON PAYOUT_GENERATED_FILE_HD
(FH_FILE_DATE, FH_FILE_PID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PAYOUT_GENERATED_FILE_HD_PK ON PAYOUT_GENERATED_FILE_HD
(FH_FILE_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PAYOUT_GENERATED_FILE_HD ADD (
  CONSTRAINT PAYOUT_GENERATED_FILE_HD_PK
  PRIMARY KEY
  (FH_FILE_ID)
  USING INDEX PAYOUT_GENERATED_FILE_HD_PK
  ENABLE VALIDATE);

