OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MiTxnLog
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMiTxnLog.so
SOOBJS = MiTxnLog.o

include $(HOME)/config/Make.rules

LDLIBS +=

all : $(COMPSO)
