OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/PayoutRecord
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBPayoutRecord.so
SOOBJS =  PayoutRecord.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
