OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/Currency
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBCurrency.so
SOOBJS =  Currency.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
