ALTER TABLE OL_TXN_REQUEST_REF
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_TXN_REQUEST_REF CASCADE CONSTRAINTS;

CREATE TABLE OL_TXN_REQUEST_REF
(
  OTRR_REQ_TXN_ID        VARCHAR2(16 BYTE),
  OTRR_CHANNEL_CODE      VARCHAR2(3 BYTE),
  OTRR_REQ_TXN_CODE      VARCHAR2(3 BYTE),
  OTRR_REQ_TXN_REF       VARCHAR2(50 BYTE),
  OTRR_VERSION           VARCHAR2(5 BYTE),
  OTRR_T1_TXN_ID         VARCHAR2(16 BYTE),
  OTRR_T2_TXN_ID         VARCHAR2(16 BYTE),
  OTRR_STATUS            CHAR(1 BYTE),
  OTRR_RET_CODE          NUMBER(8),
  OTRR_CREATE_USER       VARCHAR2(20 BYTE),
  OTRR_CREATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  OTRR_UPDATE_USER       VARCHAR2(20 BYTE),
  OTRR_UPDATE_TIMESTAMP  DATE                   DEFAULT sysdate
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE INDEX OL_TXN_REQUEST_REF_IDX01 ON OL_TXN_REQUEST_REF
(OTRR_REQ_TXN_REF, OTRR_CHANNEL_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX OL_TXN_REQUEST_REF_IDX02 ON OL_TXN_REQUEST_REF
(OTRR_REQ_TXN_CODE, OTRR_CHANNEL_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX OL_TXN_REQUEST_REF_IDX03 ON OL_TXN_REQUEST_REF
(OTRR_T1_TXN_ID, OTRR_T2_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX OL_TXN_REQUEST_REF_IDX04 ON OL_TXN_REQUEST_REF
(OTRR_T2_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX OL_TXN_REQUEST_REF_IDX05 ON OL_TXN_REQUEST_REF
(OTRR_CREATE_TIMESTAMP)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX OL_TXN_REQUEST_REF_IDX06 ON OL_TXN_REQUEST_REF
(OTRR_UPDATE_TIMESTAMP)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX OL_TXN_REQUEST_REF_PK ON OL_TXN_REQUEST_REF
(OTRR_REQ_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE OL_TXN_REQUEST_REF ADD (
  CONSTRAINT OL_TXN_REQUEST_REF_PK
  PRIMARY KEY
  (OTRR_REQ_TXN_ID)
  USING INDEX OL_TXN_REQUEST_REF_PK
  ENABLE VALIDATE);

