OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/TxnCode
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBTxnCode.so
SOOBJS =  TxnCode.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
