OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/PspCognosMap
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBPspCognosMap.so
SOOBJS =  PspCognosMap.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
