OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/PregenDailyReport
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBPregenDailyReport.so
SOOBJS =  PregenDailyReport.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
