ALTER TABLE MMX_NODES
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMX_NODES CASCADE CONSTRAINTS;

CREATE TABLE MMX_NODES
(
  MN_NODE_ID           VARCHAR2(5 BYTE),
  MN_NODE_TYPE         CHAR(1 BYTE),
  MN_DESC              VARCHAR2(50 BYTE),
  MN_REQUEST_Q         VARCHAR2(15 BYTE)        NOT NULL,
  MN_RESPONSE_Q        VARCHAR2(15 BYTE)        NOT NULL,
  MN_ENC_KEY           VARCHAR2(3 BYTE)         NOT NULL,
  MN_DISABLED          INTEGER                  DEFAULT 0,
  MN_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  MN_CREATE_USER       VARCHAR2(20 BYTE),
  MN_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  MN_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN MMX_NODES.MN_NODE_TYPE IS 'S - server , C - Cleint';



CREATE INDEX MMX_NODES_IDX01 ON MMX_NODES
(MN_NODE_ID, MN_NODE_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX MMX_NODES_PK ON MMX_NODES
(MN_NODE_ID)
LOGGING
TABLESPACE USER_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMX_NODES ADD (
  CONSTRAINT MMX_NODES_PK
  PRIMARY KEY
  (MN_NODE_ID)
  USING INDEX MMX_NODES_PK
  ENABLE VALIDATE);

