ALTER TABLE PAR_PO_REVERSED_DT
 DROP PRIMARY KEY CASCADE;

DROP TABLE PAR_PO_REVERSED_DT CASCADE CONSTRAINTS;

CREATE TABLE PAR_PO_REVERSED_DT
(
  PRD_FILE_DETAIL_ID     INTEGER,
  PRD_PO_TXN_NMB         VARCHAR2(50 BYTE),
  PRD_PSP_FILE_ID        INTEGER,
  PRD_PO_FILE_ID         INTEGER,
  PRD_PO_FILE_NAME       VARCHAR2(50 BYTE),
  PRD_SEQ_NMB            INTEGER,
  PRD_AMOUNT_CCY         VARCHAR2(3 BYTE),
  PRD_DEST_CCY           VARCHAR2(3 BYTE),
  PRD_COUNTRY            VARCHAR2(2 BYTE),
  PRD_AMOUNT             NUMBER(14,2),
  PRD_TXN_SEQ_NMB        INTEGER,
  PRD_MERCH_REF_NMB      VARCHAR2(50 BYTE),
  PRD_BANK_ACCOUNT_NMB   VARCHAR2(25 BYTE),
  PRD_BANK_ACCOUNT_NAME  VARCHAR2(100 BYTE),
  PRD_BANK_NAME          VARCHAR2(50 BYTE),
  PRD_BRANCH_NAME        VARCHAR2(100 BYTE),
  PRD_BANK_PROVINCE      VARCHAR2(50 BYTE),
  PRD_BANK_CITY          VARCHAR2(100 BYTE),
  PRD_ID_NMB             VARCHAR2(30 BYTE),
  PRD_PHONE_NMB          VARCHAR2(30 BYTE),
  PRD_BANK_CODE          VARCHAR2(5 BYTE),
  PRD_FUND_PURPOSE       VARCHAR2(30 BYTE),
  PRD_POST_DATE          DATE,
  PRD_UPDATE_DATE        DATE,
  PRD_UPLOAD_FILE_NAME   VARCHAR2(50 BYTE),
  PRD_CREATE_TIMESTAMP   DATE                   DEFAULT sysdate,
  PRD_CREATE_USER        VARCHAR2(20 BYTE),
  PRD_UPDATE_TIMESTAMP   DATE                   DEFAULT sysdate,
  PRD_UPDATE_USER        VARCHAR2(20 BYTE),
  PRD_UPLOAD_STATUS      VARCHAR2(10 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PAR_PO_REVERSED_DT_IDX01 ON PAR_PO_REVERSED_DT
(PRD_PO_FILE_ID, PRD_SEQ_NMB)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PAR_PO_REVERSED_DT_PK ON PAR_PO_REVERSED_DT
(PRD_FILE_DETAIL_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PAR_PO_REVERSED_DT ADD (
  CONSTRAINT PAR_PO_REVERSED_DT_PK
  PRIMARY KEY
  (PRD_FILE_DETAIL_ID)
  USING INDEX PAR_PO_REVERSED_DT_PK
  ENABLE VALIDATE,
  CONSTRAINT PAR_PO_REVERSED_DT_IDX01
  UNIQUE (PRD_PO_FILE_ID, PRD_SEQ_NMB)
  USING INDEX PAR_PO_REVERSED_DT_IDX01
  ENABLE VALIDATE);

