OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnMgtByUsVPS
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnMgtByUsVPS.so
SOOBJS = TxnMgtByUsVPS.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
