OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/PayoutApproveTmp
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBPayoutApproveTmp.so
SOOBJS =  PayoutApproveTmp.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
