OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/TxnQrRequestLog
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBTxnQrRequestLog.so
SOOBJS =  TxnQrRequestLog.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
