ALTER TABLE CLIENTS
 DROP PRIMARY KEY CASCADE;

DROP TABLE CLIENTS CASCADE CONSTRAINTS;

CREATE TABLE CLIENTS
(
  CLIENT_ID         VARCHAR2(10 BYTE),
  CREATE_TIMESTAMP  DATE,
  UPDATE_TIMESTAMP  DATE,
  CREATE_USER       VARCHAR2(20 BYTE),
  UPDATE_USER       VARCHAR2(20 BYTE),
  CLIENT_NAME       VARCHAR2(50 BYTE),
  STATUS            VARCHAR2(2 BYTE),
  BUSINESS_TYPE     CHAR(1 BYTE),
  COMPANY_NAME      VARCHAR2(100 BYTE),
  COMPANY_ADDR      VARCHAR2(200 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CLIENTS_PK ON CLIENTS
(CLIENT_ID)
LOGGING
TABLESPACE USER_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE CLIENTS ADD (
  CONSTRAINT CLIENTS_PK
  PRIMARY KEY
  (CLIENT_ID)
  USING INDEX CLIENTS_PK
  ENABLE VALIDATE);

ALTER TABLE CLIENTS ADD (
  CONSTRAINT CLIENTS_FK01 
  FOREIGN KEY (STATUS) 
  REFERENCES DEF_STATUS (DS_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT CLIENTS_FK02 
  FOREIGN KEY (BUSINESS_TYPE) 
  REFERENCES DEF_BUSINESS_TYPE (BT_TYPE)
  ENABLE VALIDATE);

