OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLBankAcctId
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLBankAcctId.so
SOOBJS =  OLBankAcctId.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
