ALTER TABLE CRR_EXT_TXN_DATA
 DROP PRIMARY KEY CASCADE;

DROP TABLE CRR_EXT_TXN_DATA CASCADE CONSTRAINTS;

CREATE TABLE CRR_EXT_TXN_DATA
(
  ETD_FILE_NAME         VARCHAR2(50 BYTE)       NOT NULL,
  ETD_LINE_NO           INTEGER,
  ETD_TXN_TYPE          VARCHAR2(10 BYTE)       NOT NULL,
  ETD_COUNTRY_CODE      VARCHAR2(2 BYTE),
  ETD_TXN_DATE          VARCHAR2(8 BYTE),
  ETD_TXN_ID            VARCHAR2(50 BYTE),
  ETD_MERCHANT          VARCHAR2(50 BYTE),
  ETD_PROVIDER          VARCHAR2(50 BYTE),
  ETD_TXN_CCY           VARCHAR2(3 BYTE),
  ETD_TXN_AMOUNT        NUMBER(19,2),
  ETD_TXN_FEE_CCY       VARCHAR2(3 BYTE),
  ETD_TXN_FEE_AMOUNT    NUMBER(19,2),
  ETD_NET_CCY       	VARCHAR2(3 BYTE),
  ETD_NET_AMOUNT    	NUMBER(19,2),
  ETD_MARKUP_CCY        VARCHAR2(3 BYTE),
  ETD_MARKUP_AMOUNT     NUMBER(19,2),
  ETD_PSP_CCY    	VARCHAR2(3 BYTE),
  ETD_PSP_AMOUNT   	NUMBER(19,2),
  ETD_TXN_STATUS        VARCHAR2(1 BYTE),
  ETD_MERCH_TXN_REF     VARCHAR2(50 BYTE),
  ETD_CHECKSUM          VARCHAR2(50 BYTE),
  ETD_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  ETD_CREATE_USER       VARCHAR2(20 BYTE),
  ETD_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  ETD_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CRR_EXT_TXN_DATA_PK ON CRR_EXT_TXN_DATA
(ETD_FILE_NAME, ETD_LINE_NO)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE CRR_EXT_TXN_DATA ADD (
  CONSTRAINT CRR_EXT_TXN_DATA_PK
  PRIMARY KEY
  (ETD_FILE_NAME, ETD_LINE_NO)
  USING INDEX CRR_EXT_TXN_DATA_PK
  ENABLE VALIDATE);

