ALTER TABLE MAP_TXN_ELEMENT
 DROP PRIMARY KEY CASCADE;

DROP TABLE MAP_TXN_ELEMENT CASCADE CONSTRAINTS;

CREATE TABLE MAP_TXN_ELEMENT
(
  MT_TXN_CODE          CHAR(3 BYTE),
  MT_ELEMENT           CHAR(4 BYTE),
  MT_DESC              VARCHAR2(50 BYTE),
  MT_CREATE_TIMESTAMP  DATE,
  MT_CREATE_USER       VARCHAR2(20 BYTE),
  MT_UPDATE_TIMESTAMP  DATE,
  MT_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MAP_TXN_ELEMENT_PK ON MAP_TXN_ELEMENT
(MT_TXN_CODE, MT_ELEMENT)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MAP_TXN_ELEMENT ADD (
  CONSTRAINT MAP_TXN_ELEMENT_PK
  PRIMARY KEY
  (MT_TXN_CODE, MT_ELEMENT)
  USING INDEX MAP_TXN_ELEMENT_PK
  ENABLE VALIDATE);

ALTER TABLE MAP_TXN_ELEMENT ADD (
  CONSTRAINT MAP_TXN_ELEMENT_FK01 
  FOREIGN KEY (MT_TXN_CODE) 
  REFERENCES TXN_CODE (TC_CODE)
  ENABLE VALIDATE,
  CONSTRAINT MAP_TXN_ELEMENT_FK02 
  FOREIGN KEY (MT_ELEMENT) 
  REFERENCES DEF_ELEMENT_TYPE (DT_TYPE)
  ENABLE VALIDATE);

