OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOOLTxnElements
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOOLTxnElements.so
SOOBJS = BOOLTxnElements.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
