OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOOffset
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOOffset.so
SOOBJS = BOOffset.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
