CREATE OR REPLACE FUNCTION SP_MID_BAL_COLLECT(
    IN_END_DATE IN DATE )
RETURN NUMBER IS
	EXP_ERR  EXCEPTION;
	EXP_ERR2 EXCEPTION;
	DATE_ERR EXCEPTION;
	V_NEW_BATCH_ID MID_HIST_BAL_BATCH.MB_BATCH_ID%type;
	V_PREV_BATCH_ID MID_HIST_BAL_BATCH.MB_BATCH_ID%type;
	V_START_DATE DATE;
	V_ADD_RANGE_END_DATE DATE;
BEGIN
-- DBMS_OUTPUT.PUT_LINE('>>> START [MID_BAL_COLLECT] <<<');
-- DBMS_OUTPUT.PUT_LINE('--> Input Date: '|| TO_CHAR(IN_END_DATE, 'YYYY-MM-DD HH24:MI') );
-- Find Prev Batch ID and current batch start date/time
	SELECT MB_BATCH_ID,
	       MB_END_DATE
	INTO V_PREV_BATCH_ID,
	     V_START_DATE
	FROM
	(SELECT MB_BATCH_ID,
	        MB_END_DATE,
	        ROW_NUMBER() OVER (PARTITION BY MB_DISABLED ORDER BY MB_END_DATE DESC) RN
	FROM MID_HIST_BAL_BATCH
	WHERE MB_DISABLED = 0
	)
	WHERE RN = 1;
	
	IF SQL % ROWCOUNT != 1 THEN
		raise EXP_ERR2;
	END IF;
	
	V_START_DATE := V_START_DATE + 1/24/60;
-- DBMS_OUTPUT.PUT_LINE('--> Start Date: '|| V_START_DATE );
-- DBMS_OUTPUT.PUT_LINE('--> End Date: '|| IN_END_DATE );

-- only look forward
	IF IN_END_DATE < V_START_DATE THEN
		raise DATE_ERR;
	END IF;

-- New Batch ID
	SELECT MAX(MB_BATCH_ID) + 1
	INTO V_NEW_BATCH_ID
	FROM MID_HIST_BAL_BATCH;
-- DBMS_OUTPUT.PUT_LINE('--> New Batch ID: ' || V_NEW_BATCH_ID );
-- DBMS_OUTPUT.PUT_LINE('--> Previous Batch ID: ' || V_PREV_BATCH_ID );

-- Add 1 mins to end times
	V_ADD_RANGE_END_DATE := IN_END_DATE + 1/24/60;
-- DBMS_OUTPUT.PUT_LINE('--> Add 1 mins end date: ' || V_ADD_RANGE_END_DATE );

-- Insert New Batch
	INSERT
	INTO MID_HIST_BAL_BATCH
	(
		MB_BATCH_ID,
		MB_START_DATE,
		MB_END_DATE,
		MB_DISABLED,
		MB_CREATE_TIMESTAMP,
		MB_CREATE_USER
	)
	VALUES
	(
		V_NEW_BATCH_ID,
		V_START_DATE,
		IN_END_DATE,
		0,
		SYSDATE,
		'SYSTEM'
	);
	
	IF SQL % ROWCOUNT != 1 THEN
		raise EXP_ERR;
	END IF ;

-- DBMS_OUTPUT.PUT_LINE('--> Insert New Batch: OK');
-- Find PSP Last Txn from start times to end times
	FOR X IN
	(
		SELECT TXN_ID,
		       MID_ID,
		       TXN_CCY,
		       SERVICE_CODE,
		       TXN_COUNTRY,
		       APPROVAL_TIMESTAMP
		FROM
		(
			SELECT TXN_ID,
			       MID_ID,
			       TXN_CCY,
			       SERVICE_CODE,
			       TXN_COUNTRY,
			       APPROVAL_TIMESTAMP,
			       ROW_NUMBER() OVER ( PARTITION BY MID_ID , TXN_CCY , SERVICE_CODE, TXN_COUNTRY ORDER BY APPROVAL_TIMESTAMP DESC ) RN
			FROM
			(
				SELECT TXN_ID,
				       MID_ID,
				       TXN_CCY,
				       SERVICE_CODE,
				       TXN_COUNTRY,
				       APPROVAL_TIMESTAMP
				FROM
				(
					SELECT TH_TXN_ID             AS TXN_ID,
					       TH_MERCHANT_ID        AS MID_ID,
					       TH_NET_CCY            AS TXN_CCY,
					       TH_SERVICE_CODE       AS SERVICE_CODE,
					       TD_TXN_COUNTRY        AS TXN_COUNTRY,
					       TH_APPROVAL_TIMESTAMP AS APPROVAL_TIMESTAMP,
					       ROW_NUMBER() OVER ( PARTITION BY TH_MERCHANT_ID, TH_NET_CCY, TH_SERVICE_CODE, TD_TXN_COUNTRY ORDER BY TH_APPROVAL_TIMESTAMP DESC ) RN
					FROM TXN_DETAIL,
					     TXN_HEADER
					WHERE TH_TXN_ID            = TD_TXN_ID
					AND TH_AR_IND              = 'A'
					AND TH_TXN_CODE NOT IN ('RLS','RLA')
					AND TH_APPROVAL_TIMESTAMP >= CAST(V_START_DATE AS TIMESTAMP)
					AND TH_APPROVAL_TIMESTAMP  < CAST(V_ADD_RANGE_END_DATE AS TIMESTAMP)
					AND TD_CURRENT_BAL        IS NOT NULL
					AND TH_MERCHANT_ID        IS NOT NULL
					AND TH_NET_CCY            IS NOT NULL
					ORDER BY TH_APPROVAL_TIMESTAMP DESC
				)
				WHERE RN = 1
				UNION
				SELECT MBD_TXN_ID            AS TXN_ID,
				       MBD_MID_ID            AS MID_ID,
				       MBD_CCY               AS TXN_CCY,
				       MBD_SERVICE_CODE      AS SERVICE_CODE,
				       MBD_COUNTRY           AS TXN_COUNTRY,
				       TH_APPROVAL_TIMESTAMP AS APPROVAL_TIMESTAMP
				FROM MID_HIST_BAL_DETAIL,
				     TXN_HEADER
				WHERE TH_TXN_ID  = MBD_TXN_ID
				AND MBD_BATCH_ID = V_PREV_BATCH_ID
			)
			ORDER BY APPROVAL_TIMESTAMP DESC
		)
		WHERE RN = 1
	)
	LOOP
-- DBMS_OUTPUT.PUT_LINE('--> MID_ID: [' || X.MID_ID || '] TXN_CCY: [' || X.TXN_CCY || ']  SERVICE_CODE: [' || X.SERVICE_CODE || ']  TXN_ID : [' || X.TXN_ID||']');
		IF X.TXN_ID IS NOT NULL THEN
-- DBMS_OUTPUT.PUT_LINE('--> MBD_BATCH_ID: [' || V_NEW_BATCH_ID || '] MID_ID : [' || X.MID_ID || '] TXN_CCY: [' || X.TXN_CCY || ']  SERVICE_CODE: [' || X.SERVICE_CODE || ']   TXN_COUNTRY: [' || X.TXN_COUNTRY || ']  TXN_ID : [' || X.TXN_ID||']');
			INSERT
			INTO MID_HIST_BAL_DETAIL
			(
				MBD_BATCH_ID,
				MBD_MID_ID,
				MBD_CCY,
				MBD_SERVICE_CODE,
				MBD_COUNTRY,
				MBD_TXN_ID
			)
			VALUES
			(
				V_NEW_BATCH_ID,
				X.MID_ID,
				X.TXN_CCY,
				X.SERVICE_CODE,
				X.TXN_COUNTRY,
				X.TXN_ID
			);

			IF SQL % ROWCOUNT != 1 THEN
				raise EXP_ERR;
			END IF;
    		END IF;
	END LOOP;

	COMMIT;
-- DBMS_OUTPUT.PUT_LINE('>>> END [MID_BAL_COLLECT] <<<');

	RETURN 0;

EXCEPTION
WHEN EXP_ERR THEN
	ROLLBACK;
--DBMS_OUTPUT.PUT_LINE('Error: Insert last txn error!');
	RETURN 1;
WHEN DATE_ERR THEN
	ROLLBACK;
--DBMS_OUTPUT.PUT_LINE('Error: The latest batch end date larger than input date!');
--RAISE_APPLICATION_ERROR( -20101, 'The latest batch end date larger than input date!');
	RETURN 1;
WHEN EXP_ERR2 THEN
	ROLLBACK;
--DBMS_OUTPUT.PUT_LINE('Error: no record!');
	RETURN 1;
WHEN OTHERS THEN
	ROLLBACK;
--DBMS_OUTPUT.PUT_LINE('Error: Other error!');
--DBMS_OUTPUT.PUT_LINE('Error code ' || SQLCODE|| ': ' || SUBSTR(SQLERRM, 1 , 64));
--RAISE_APPLICATION_ERROR( -20102, 'Error code ' || SQLCODE|| ': ' || SUBSTR(SQLERRM, 1 , 64) );
	RETURN 9;
END SP_MID_BAL_COLLECT;
/

