ALTER TABLE MERCH_BLACKLIST_CTL
 DROP PRIMARY KEY CASCADE;

DROP TABLE MERCH_BLACKLIST_CTL CASCADE CONSTRAINTS;

CREATE TABLE MERCH_BLACKLIST_CTL
(
  UR_MERCHANT_ID       VARCHAR2(15 BYTE),
  UR_CHECK_BLACKLIST   INTEGER                  DEFAULT 0,
  UR_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  UR_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  UR_CREATE_USER       VARCHAR2(20 BYTE),
  UR_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MERCH_BLACKLIST_CTL_PK ON MERCH_BLACKLIST_CTL
(UR_MERCHANT_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MERCH_BLACKLIST_CTL ADD (
  CONSTRAINT MERCH_BLACKLIST_CTL_PK
  PRIMARY KEY
  (UR_MERCHANT_ID)
  USING INDEX MERCH_BLACKLIST_CTL_PK
  ENABLE VALIDATE);

