ALTER TABLE CRR_MI_TXN_DATA
 DROP PRIMARY KEY CASCADE;

DROP TABLE CRR_MI_TXN_DATA CASCADE CONSTRAINTS;

CREATE TABLE CRR_MI_TXN_DATA
(
  CMTD_TXN_ID            VARCHAR2(16 BYTE),
  CMTD_TXN_CODE          VARCHAR2(3 BYTE)       NOT NULL,
  CMTD_APPROVAL_DATE     VARCHAR2(8 BYTE)       NOT NULL,
  CMTD_ENTITY_ID         VARCHAR2(10 BYTE)      NOT NULL,
  CMTD_PARTY_TYPE        VARCHAR2(3 BYTE)       NOT NULL,
  CMTD_PARTY_ID          VARCHAR2(10 BYTE)      NOT NULL,
  CMTD_TXN_PRODUCT       VARCHAR2(3 BYTE)       NOT NULL,
  CMTD_COUNTRY           CHAR(2 BYTE)           NOT NULL,
  CMTD_CCY               CHAR(3 BYTE)           NOT NULL,
  CMTD_TXN_AMT           NUMBER(12,2)           DEFAULT 0,
  CMTD_NET_CCY           CHAR(3 BYTE)           NOT NULL,
  CMTD_NET_AMT           NUMBER(12,2)           DEFAULT 0,
  CMTD_INTR_AMT          NUMBER(12,2)           DEFAULT 0,
  CMTD_OVPA_AMT          NUMBER(12,2)           DEFAULT 0,
  CMTD_UDPA_AMT          NUMBER(12,2)           DEFAULT 0,
  CMTD_FEE_CCY           CHAR(3 BYTE)           NOT NULL,
  CMTD_FEE_AMT           NUMBER(12,2)           DEFAULT 0,
  CMTD_CREATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  CMTD_CREATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CRR_MI_TXN_DATA_PK ON CRR_MI_TXN_DATA
(CMTD_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE CRR_MI_TXN_DATA ADD (
  CONSTRAINT CRR_MI_TXN_DATA_PK
  PRIMARY KEY
  (CMTD_TXN_ID)
  USING INDEX CRR_MI_TXN_DATA_PK
  ENABLE VALIDATE);

