ALTER TABLE BANK_SERVICE_MAPPING
 DROP PRIMARY KEY CASCADE;

DROP TABLE BANK_SERVICE_MAPPING CASCADE CONSTRAINTS;

CREATE TABLE BANK_SERVICE_MAPPING
(
  BS_SERVICE_CODE	 CHAR(3 BYTE),
  BS_INT_BANK_CODE	 VARCHAR2(10 BYTE),
  BS_EFFECT_DATE         DATE			   DEFAULT SYSDATE,
  BS_DISABLED            VARCHAR2(1 BYTE)	   DEFAULT 0,
  BS_CREATE_TIMESTAMP    DATE                      DEFAULT SYSDATE,
  BS_UPDATE_TIMESTAMP    DATE                      DEFAULT SYSDATE,
  BS_CREATE_USER         VARCHAR2(25 BYTE),
  BS_UPDATE_USER         VARCHAR2(25 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX BANK_SERVICE_MAPPING_PK ON BANK_SERVICE_MAPPING
(BS_SERVICE_CODE,BS_INT_BANK_CODE,BS_EFFECT_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE BANK_SERVICE_MAPPING ADD (
  CONSTRAINT BANK_SERVICE_MAPPING_PK
  PRIMARY KEY
  (BS_SERVICE_CODE, BS_INT_BANK_CODE, BS_EFFECT_DATE)
  USING INDEX BANK_SERVICE_MAPPING_PK);


