OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLStmtTxnRelation
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLStmtTxnRelation.so
SOOBJS =  OLStmtTxnRelation.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
