OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/BankCodeMap
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBBankCodeMap.so
SOOBJS =  BankCodeMap.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
