ALTER TABLE RULE_OUTAGE_NOTE
 DROP PRIMARY KEY CASCADE;

DROP TABLE RULE_OUTAGE_NOTE CASCADE CONSTRAINTS;

CREATE TABLE RULE_OUTAGE_NOTE
(
  RON_NOTE_ID           INTEGER,
  RON_LANGUAGE          CHAR(2 BYTE),
  RON_NOTE              VARCHAR2(2000 BYTE),
  RON_CREATE_USER       VARCHAR2(20 BYTE),
  RON_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  RON_UPDATE_USER       VARCHAR2(20 BYTE),
  RON_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX RULE_OUTAGE_NOTE_PK ON RULE_OUTAGE_NOTE
(RON_NOTE_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE RULE_OUTAGE_NOTE ADD (
  CONSTRAINT RULE_OUTAGE_NOTE_PK
  PRIMARY KEY
  (RON_NOTE_ID)
  USING INDEX RULE_OUTAGE_NOTE_PK
  ENABLE VALIDATE);

