OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BODepositTrace
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBODepositTrace.so
SOOBJS = BODepositTrace.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
