OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/ParMerchProfile
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBParMerchProfile.so
SOOBJS =  ParMerchProfile.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
