ALTER TABLE OL_AUTO_MATCH_POOLS
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_AUTO_MATCH_POOLS CASCADE CONSTRAINTS;

CREATE TABLE OL_AUTO_MATCH_POOLS
(
  AMP_POOL_ID           INTEGER,
  AMP_MATCH_RULE_TYPE   VARCHAR2(10 BYTE),
  AMP_DISABLED          INTEGER                 DEFAULT 0,
  AMP_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  AMP_CREATE_USER       VARCHAR2(20 BYTE),
  AMP_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  AMP_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_AUTO_MATCH_POOLS_PK ON OL_AUTO_MATCH_POOLS
(AMP_POOL_ID, AMP_MATCH_RULE_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_AUTO_MATCH_POOLS ADD (
  CONSTRAINT OL_AUTO_MATCH_POOLS_PK
  PRIMARY KEY
  (AMP_POOL_ID, AMP_MATCH_RULE_TYPE)
  USING INDEX OL_AUTO_MATCH_POOLS_PK
  ENABLE VALIDATE);

ALTER TABLE OL_AUTO_MATCH_POOLS ADD (
  CONSTRAINT OL_AUTO_MATCH_POOLS_FK 
  FOREIGN KEY (AMP_MATCH_RULE_TYPE) 
  REFERENCES OL_DEF_AUTO_MATCH_RULE (AMR_TYPE)
  ENABLE VALIDATE);

