ALTER TABLE EMAIL_NOTIFY_LIST
 DROP PRIMARY KEY CASCADE;

DROP TABLE EMAIL_NOTIFY_LIST CASCADE CONSTRAINTS;

CREATE TABLE EMAIL_NOTIFY_LIST
(
  EL_ID                INTEGER,
  EL_EMAIL             VARCHAR2(100 BYTE),
  EL_CREATE_USER       VARCHAR2(20 BYTE),
  EL_UPDATE_USER       VARCHAR2(20 BYTE),
  EL_CREATE_TIMESTAMP  DATE,
  EL_UPDATE_TIMESTAMP  DATE
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX EMAIL_NOTIFY_LIST_IDX01 ON EMAIL_NOTIFY_LIST
(EL_EMAIL)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX EMAIL_NOTIFY_LIST_PK ON EMAIL_NOTIFY_LIST
(EL_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE EMAIL_NOTIFY_LIST ADD (
  CONSTRAINT EMAIL_NOTIFY_LIST_PK
  PRIMARY KEY
  (EL_ID)
  USING INDEX EMAIL_NOTIFY_LIST_PK
  ENABLE VALIDATE);

