ALTER TABLE MMS_DEF_AMT_DIFF_REASON
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_DEF_AMT_DIFF_REASON CASCADE CONSTRAINTS;

CREATE TABLE MMS_DEF_AMT_DIFF_REASON
(
  MDR_CODE              VARCHAR2(10 BYTE),
  MDR_DESC              VARCHAR2(50 BYTE),
  MDR_AMT_TYPE          CHAR(2 BYTE),
  MDR_ELEMENT_TYPE      CHAR(4 BYTE),
  MDR_DISABLED          INTEGER                 DEFAULT 0,
  MDR_CREATE_TIMESTAMP  DATE,
  MDR_CREATE_USER       VARCHAR2(20 BYTE),
  MDR_UPDATE_TIMESTAMP  DATE,
  MDR_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MMS_DEF_AMT_DIFF_REASON_PK ON MMS_DEF_AMT_DIFF_REASON
(MDR_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_DEF_AMT_DIFF_REASON ADD (
  CONSTRAINT MMS_DEF_AMT_DIFF_REASON_PK
  PRIMARY KEY
  (MDR_CODE)
  USING INDEX MMS_DEF_AMT_DIFF_REASON_PK
  ENABLE VALIDATE);

ALTER TABLE MMS_DEF_AMT_DIFF_REASON ADD (
  CONSTRAINT MMS_DEF_AMT_DIFF_REASON_FK01 
  FOREIGN KEY (MDR_AMT_TYPE) 
  REFERENCES DEF_AMT_TYPE (DA_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT MMS_DEF_AMT_DIFF_REASON_FK02 
  FOREIGN KEY (MDR_ELEMENT_TYPE) 
  REFERENCES MMS_DEF_ELEMENT_TYPE (MET_TYPE)
  ENABLE VALIDATE);

