ALTER TABLE CPHUSER.PSP_RESPONSE_TXN_URL
 DROP PRIMARY KEY CASCADE;

DROP TABLE CPHUSER.PSP_RESPONSE_TXN_URL CASCADE CONSTRAINTS;

CREATE TABLE CPHUSER.PSP_RESPONSE_TXN_URL
(
  PSP_ID             VARCHAR2(10 BYTE),
  TXN_CODE           CHAR(3 BYTE),
  RESPONSE_FUNCTION  VARCHAR2(50 BYTE),
  EFFECT_DATE        VARCHAR2(8 BYTE),
  CREATE_TIMESTAMP   DATE,
  UPDATE_TIMESTAMP   DATE,
  CREATE_USER        VARCHAR2(20 BYTE),
  UPDATE_USER        VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CPHUSER.PSP_RESPONSE_TXN_URL_PK ON CPHUSER.PSP_RESPONSE_TXN_URL
(PSP_ID, TXN_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE CPHUSER.PSP_RESPONSE_TXN_URL ADD (
  CONSTRAINT PSP_RESPONSE_TXN_URL_PK
  PRIMARY KEY
  (PSP_ID, TXN_CODE)
  USING INDEX CPHUSER.PSP_RESPONSE_TXN_URL_PK);

