ALTER TABLE CRR_OFL_TXN_DATA_PSP_DETAIL
 DROP PRIMARY KEY CASCADE;

DROP TABLE CRR_OFL_TXN_DATA_PSP_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE CRR_OFL_TXN_DATA_PSP_DETAIL
(
  COTP_TXN_ID            VARCHAR2(16 BYTE),
  COTP_CLIENT_ID         VARCHAR2(10 BYTE),
  COTP_PSP_ID            VARCHAR2(10 BYTE),
  COTP_BAID              VARCHAR2(20 BYTE),
  COTP_BAID_CATEGORY     VARCHAR2(10 BYTE),
  COTP_PSP_CCY           CHAR(3 BYTE),
  COTP_PSP_AMT           NUMBER(12,2)           DEFAULT 0,
  COTP_CREATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  COTP_CREATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CRR_OFL_TXN_DATA_PSP_DETAIL_PK ON CRR_OFL_TXN_DATA_PSP_DETAIL
(COTP_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE CRR_OFL_TXN_DATA_PSP_DETAIL ADD (
  CONSTRAINT CRR_OFL_TXN_DATA_PSP_DETAIL_PK
  PRIMARY KEY
  (COTP_TXN_ID)
  USING INDEX CRR_OFL_TXN_DATA_PSP_DETAIL_PK
  ENABLE VALIDATE);

