ALTER TABLE CRR_OFL_TXN_DATA_HEADER
 DROP PRIMARY KEY CASCADE;

DROP TABLE CRR_OFL_TXN_DATA_HEADER CASCADE CONSTRAINTS;

CREATE TABLE CRR_OFL_TXN_DATA_HEADER
(
  COTH_TXN_ID            VARCHAR2(16 BYTE),
  COTH_TXN_CODE          VARCHAR2(3 BYTE)       NOT NULL,
  COTH_APPROVAL_DATE     VARCHAR2(8 BYTE)       NOT NULL,
  COTH_COUNTRY           CHAR(2 BYTE)           NOT NULL,
  COTH_CCY               CHAR(3 BYTE)           NOT NULL,
  COTH_TXN_AMT           NUMBER(12,2)           DEFAULT 0,
  COTH_FEE_CCY           CHAR(3 BYTE),
  COTH_FEE               NUMBER(12,2)           DEFAULT 0,
  COTH_NET_CCY           CHAR(3 BYTE),
  COTH_NET_AMT           NUMBER(12,2)           DEFAULT 0,
  COTH_MARKUP_CCY        CHAR(3 BYTE),
  COTH_MARKUP_AMT        NUMBER(12,2),
  COTH_DELI_CCY          CHAR(3 BYTE),
  COTH_DELI_AMT          NUMBER(12,2),
  COTH_RELATED_TXN_ID    VARCHAR2(16 BYTE),
  COTH_CREATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  COTH_CREATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX CRR_OFL_TXN_DATA_HEADER_IDX01 ON CRR_OFL_TXN_DATA_HEADER
(COTH_APPROVAL_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX CRR_OFL_TXN_DATA_HEADER_PK ON CRR_OFL_TXN_DATA_HEADER
(COTH_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE CRR_OFL_TXN_DATA_HEADER ADD (
  CONSTRAINT CRR_OFL_TXN_DATA_HEADER_PK
  PRIMARY KEY
  (COTH_TXN_ID)
  USING INDEX CRR_OFL_TXN_DATA_HEADER_PK
  ENABLE VALIDATE);

