ALTER TABLE CRR_OFL_TXN_DATA_DETAIL
 DROP PRIMARY KEY CASCADE;

DROP TABLE CRR_OFL_TXN_DATA_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE CRR_OFL_TXN_DATA_DETAIL
(
  COTD_TXN_ID            VARCHAR2(16 BYTE),
  COTD_MERCHANT_REF      VARCHAR2(50 BYTE)      NOT NULL,
  COTD_CLIENT_ID         VARCHAR2(10 BYTE)      NOT NULL,
  COTD_MERCHANT_ID       VARCHAR2(15 BYTE)      NOT NULL,
  COTD_SERVICE_CODE      VARCHAR2(3 BYTE)       NOT NULL,
  COTD_CREATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  COTD_CREATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CRR_OFL_TXN_DATA_DETAIL_PK ON CRR_OFL_TXN_DATA_DETAIL
(COTD_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE CRR_OFL_TXN_DATA_DETAIL ADD (
  CONSTRAINT CRR_OFL_TXN_DATA_DETAIL_PK
  PRIMARY KEY
  (COTD_TXN_ID)
  USING INDEX CRR_OFL_TXN_DATA_DETAIL_PK
  ENABLE VALIDATE);

