OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLStmtMatchAction
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLStmtMatchAction.so
SOOBJS =  OLStmtMatchAction.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
