OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLDefBaidCategory
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLDefBaidCategory.so
SOOBJS =  OLDefBaidCategory.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
