OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLRuleAMSchedulerHd
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLRuleAMSchedulerHd.so
SOOBJS =  OLRuleAMSchedulerHd.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
