


CREATE TABLE DEF_KEY_GROUP
(
  DKG_TYPE              VARCHAR2(3 BYTE),
  DKG_DESC              VARCHAR2(50 BYTE),
  DKG_CREATE_USER       VARCHAR2(20 BYTE),
  DKG_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  DKG_UPDATE_USER       VARCHAR2(20 BYTE),
  DKG_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DEF_KEY_GROUP_PK ON DEF_KEY_GROUP
(DKG_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DEF_KEY_GROUP ADD (
  CONSTRAINT DEF_KEY_GROUP_PK
  PRIMARY KEY
  (DKG_TYPE)
  USING INDEX DEF_KEY_GROUP_PK
  ENABLE VALIDATE);
