ALTER TABLE RULE_PSP_LB_MAPPING
 DROP PRIMARY KEY CASCADE;

DROP TABLE RULE_PSP_LB_MAPPING CASCADE CONSTRAINTS;

CREATE TABLE RULE_PSP_LB_MAPPING
(
  RM_POOL_ID           INTEGER,
  RM_PSP_ID            VARCHAR2(10 BYTE),
  RM_DISABLED          INTEGER                  DEFAULT 0,
  RM_PRIORITY          INTEGER                  DEFAULT 0                     NOT NULL,
  RM_RATIO             INTEGER                  DEFAULT 0                     NOT NULL,
  RM_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  RM_CREATE_USER       VARCHAR2(20 BYTE),
  RM_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  RM_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX RULE_PSP_LB_MAPPING_PK ON RULE_PSP_LB_MAPPING
(RM_POOL_ID, RM_PSP_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE RULE_PSP_LB_MAPPING ADD (
  CONSTRAINT RULE_PSP_LB_MAPPING_PK
  PRIMARY KEY
  (RM_POOL_ID, RM_PSP_ID)
  USING INDEX RULE_PSP_LB_MAPPING_PK
  ENABLE VALIDATE);

ALTER TABLE RULE_PSP_LB_MAPPING ADD (
  CONSTRAINT RULE_PSP_LB_MAPPING_FK01 
  FOREIGN KEY (RM_PSP_ID) 
  REFERENCES RULE_PSP_LB_PSP (RPP_PSP_ID)
  ENABLE VALIDATE);

