ALTER TABLE PSP_BALANCE
 DROP PRIMARY KEY CASCADE;

DROP TABLE PSP_BALANCE CASCADE CONSTRAINTS;

CREATE TABLE PSP_BALANCE
(
  PB_PSP_ID            VARCHAR2(10 BYTE),
  PB_COUNTRY_ID        VARCHAR2(3 BYTE),
  PB_CURRENCY_ID       VARCHAR2(3 BYTE),
  PB_BAL               NUMBER(14,2)             DEFAULT 0,
  PB_TOTAL_FLOAT       NUMBER(14,2)             DEFAULT 0,
  PB_TOTAL_HOLD        NUMBER(14,2)             DEFAULT 0,
  PB_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  PB_CREATE_USER       VARCHAR2(20 BYTE),
  PB_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  PB_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PSP_BALANCE_PK ON PSP_BALANCE
(PB_PSP_ID, PB_COUNTRY_ID, PB_CURRENCY_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE PSP_BALANCE ADD (
  CONSTRAINT PSP_BALANCE_PK
  PRIMARY KEY
  (PB_PSP_ID, PB_COUNTRY_ID, PB_CURRENCY_ID)
  USING INDEX PSP_BALANCE_PK);


