ALTER TABLE CRR_SL_MAPPING
 DROP PRIMARY KEY CASCADE;

DROP TABLE CRR_SL_MAPPING CASCADE CONSTRAINTS;

CREATE TABLE CRR_SL_MAPPING
(
  SM_GL_ID              INTEGER                 NOT NULL,
  SM_PARTY_TYPE         CHAR(1 BYTE)            NOT NULL,
  SM_PARTY_ID           VARCHAR2(15 BYTE)       NOT NULL,
  SM_CURRENCY_ID        VARCHAR2(3 BYTE)        NOT NULL,
  SM_CREATE_TIMESTAMP   DATE                    DEFAULT SYSDATE,
  SM_CREATE_USER        VARCHAR2(20 BYTE),
  SM_UPDATE_TIMESTAMP   DATE                    DEFAULT SYSDATE,
  SM_UPDATE_USER        VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX CRR_SL_MAPPING_PK ON CRR_SL_MAPPING
(SM_GL_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE CRR_SL_MAPPING ADD (
  CONSTRAINT CRR_SL_MAPPING_PK
  PRIMARY KEY
  (SM_GL_ID)
  USING INDEX CRR_SL_MAPPING_PK);

ALTER TABLE CRR_SL_MAPPING ADD (
  CONSTRAINT CRR_SL_MAPPING_FK01
  FOREIGN KEY (SM_GL_ID)
  REFERENCES CRR_GL_CODE (GL_ID));

