INSERT INTO CRR_SL_MAPPING (
    SM_GL_ID, SM_PARTY_TYPE, SM_PARTY_ID, SM_CURRENCY_ID,
    SM_CREATE_TIMESTAMP, SM_CREATE_USER, SM_UPDATE_TIMESTAMP, SM_UPDATE_USER
)
SELECT GL_ID, CR_PARTY_TYPE, CR_PARTY_ID, CR_CURRENCY_ID, SYSDATE, 'SYSTEM', SYSDATE, 'SYSDATE' FROM
(
    SELECT DECODE(CR_CREDIT_GL_ID, 0, CR_DEBIT_GL_ID, CR_CREDIT_GL_ID) GL_ID, CR_PARTY_TYPE, CR_PARTY_ID, CR_CURRENCY_ID, COUNT(1)
    FROM CRR_RULE_POSTING
    GROUP BY DECODE(CR_CREDIT_GL_ID, 0, CR_DEBIT_GL_ID, CR_CREDIT_GL_ID), CR_PARTY_TYPE, CR_PARTY_ID, CR_CURRENCY_ID
)
;

COMMIT;

