ALTER TABLE OL_TC_BAL_TRF_MAP
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_TC_BAL_TRF_MAP CASCADE CONSTRAINTS;

CREATE TABLE OL_TC_BAL_TRF_MAP
(
  BTM_BAL_TRF_TYPE      VARCHAR2(10 BYTE),
  BTM_FR_ACCT_TYPE      CHAR(3 BYTE),
  BTM_TO_ACCT_TYPE      CHAR(3 BYTE),
  BTM_TO_BAID_CAT_ID    INTEGER,
  BTM_TXN_CODE_TYPE     VARCHAR2(20 BYTE),
  BTM_TXN_CODE          CHAR(3 BYTE),
  BTM_CREATE_TIMESTAMP  DATE,
  BTM_UPDATE_TIMESTAMP  DATE,
  BTM_CREATE_USER       VARCHAR2(20 BYTE),
  BTM_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_TC_BAL_TRF_MAP_PK ON OL_TC_BAL_TRF_MAP
(BTM_BAL_TRF_TYPE, BTM_FR_ACCT_TYPE, BTM_TO_ACCT_TYPE, BTM_TXN_CODE_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_TC_BAL_TRF_MAP ADD (
  CONSTRAINT OL_TC_BAL_TRF_MAP_PK
  PRIMARY KEY
  (BTM_BAL_TRF_TYPE, BTM_FR_ACCT_TYPE, BTM_TO_ACCT_TYPE, BTM_TXN_CODE_TYPE)
  USING INDEX OL_TC_BAL_TRF_MAP_PK
  ENABLE VALIDATE);

ALTER TABLE OL_TC_BAL_TRF_MAP ADD (
  CONSTRAINT OL_TC_BAL_TRF_MAP_FK01 
  FOREIGN KEY (BTM_BAL_TRF_TYPE) 
  REFERENCES OL_DEF_BAL_TRF_TYPE (BTT_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OL_TC_BAL_TRF_MAP_FK02 
  FOREIGN KEY (BTM_TXN_CODE_TYPE) 
  REFERENCES OL_DEF_TC_BAL_TRF_TYPE (BTTT_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OL_TC_BAL_TRF_MAP_FK03 
  FOREIGN KEY (BTM_FR_ACCT_TYPE) 
  REFERENCES OL_DEF_BANK_ACCT_TYPE (OBC_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OL_TC_BAL_TRF_MAP_FK04 
  FOREIGN KEY (BTM_TO_ACCT_TYPE) 
  REFERENCES OL_DEF_BANK_ACCT_TYPE (OBC_TYPE)
  ENABLE VALIDATE);

