OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnMgtByUsVTO
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnMgtByUsVTO.so
SOOBJS = TxnMgtByUsVTO.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
