ALTER TABLE OL_SMS_FORMAT
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_SMS_FORMAT CASCADE CONSTRAINTS;

CREATE TABLE OL_SMS_FORMAT
(
  OSMF_INT_BANK_CODE     VARCHAR2(10 BYTE),
  OSMF_TRUST_SENDER      VARCHAR2(20 BYTE),
  OSMF_KEY_WORD          VARCHAR2(40 BYTE),
  OSMF_FORMAT_ID         VARCHAR2(20 BYTE),
  OSMF_EFFECT_TIMESTAMP  DATE                   DEFAULT sysdate,
  OSMF_DISABLED          INTEGER                DEFAULT 0,
  OSMF_ALERT             INTEGER                DEFAULT 0,
  OSMF_CREATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  OSMF_CREATE_USER       VARCHAR2(20 BYTE),
  OSMF_UPDATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  OSMF_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_SMS_FORMAT_PK ON OL_SMS_FORMAT
(OSMF_INT_BANK_CODE, OSMF_TRUST_SENDER, OSMF_KEY_WORD, OSMF_FORMAT_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_SMS_FORMAT ADD (
  CONSTRAINT OL_SMS_FORMAT_PK
  PRIMARY KEY
  (OSMF_INT_BANK_CODE, OSMF_TRUST_SENDER, OSMF_KEY_WORD, OSMF_FORMAT_ID)
  USING INDEX OL_SMS_FORMAT_PK
  ENABLE VALIDATE);

ALTER TABLE OL_SMS_FORMAT ADD (
  CONSTRAINT OL_SMS_FORMAT_FK01 
  FOREIGN KEY (OSMF_INT_BANK_CODE) 
  REFERENCES DEF_BANK (DB_INT_BANK_CODE)
  ENABLE VALIDATE);

