CREATE TABLE OL_SMS_FIELD_CHECK
(
  OSFC_FORMAT_ID          VARCHAR2(20 BYTE),
  OSFC_FIELD_TAG          VARCHAR2(50 BYTE),
  OSFC_ONLY_DIGIT         INTEGER                 DEFAULT 0,
  OSFC_LEN                INTEGER                 DEFAULT 0,
  OSFC_CREATE_TIMESTAMP   DATE                    DEFAULT sysdate,
  OSFC_CREATE_USER        VARCHAR2(20 BYTE),
  OSFC_UPDATE_TIMESTAMP   DATE                    DEFAULT sysdate,
  OSFC_UPDATE_USER        VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE INDEX OL_SMS_FIELD_CHECK_IDX01 ON OL_SMS_FIELD_CHECK
(OSFC_FORMAT_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
  

CREATE UNIQUE INDEX OL_SMS_FIELD_CHECK_PK ON OL_SMS_FIELD_CHECK
(OSFC_FORMAT_ID, OSFC_FIELD_TAG)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE OL_SMS_FIELD_CHECK ADD (
  CONSTRAINT OL_SMS_FIELD_CHECK_PK
  PRIMARY KEY
  (OSFC_FORMAT_ID, OSFC_FIELD_TAG)
  USING INDEX OL_SMS_FIELD_CHECK_PK
  ENABLE VALIDATE);