ALTER TABLE OL_SMS_FORMAT_TEMPLATE
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_SMS_FORMAT_TEMPLATE CASCADE CONSTRAINTS;

CREATE TABLE OL_SMS_FORMAT_TEMPLATE
(
  OSMT_FORMAT_ID         VARCHAR2(20 BYTE),
  OSMT_FORMAT_TYPE       VARCHAR2(20 BYTE),
  OSMT_FORMAT_VALUE      INTEGER,
  OSMT_FORMAT_DESC       VARCHAR2(50 BYTE),
  OSMT_DELIMITER         VARCHAR2(500 BYTE),
  OSMT_DELIMITER_DESC    VARCHAR2(50 BYTE),
  OSMT_IS_GENERIC        INTEGER                DEFAULT 0,
  OSMT_CREATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  OSMT_CREATE_USER       VARCHAR2(20 BYTE),
  OSMT_UPDATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  OSMT_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX OL_SMS_FORMAT_TEMPLATE_IDX01 ON OL_SMS_FORMAT_TEMPLATE
(OSMT_FORMAT_ID)
LOGGING
TABLESPACE USER_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX OL_SMS_FORMAT_TEMPLATE_PK ON OL_SMS_FORMAT_TEMPLATE
(OSMT_FORMAT_ID, OSMT_FORMAT_TYPE, OSMT_FORMAT_VALUE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_SMS_FORMAT_TEMPLATE ADD (
  CONSTRAINT OL_SMS_FORMAT_TEMPLATE_PK
  PRIMARY KEY
  (OSMT_FORMAT_ID, OSMT_FORMAT_TYPE, OSMT_FORMAT_VALUE)
  USING INDEX OL_SMS_FORMAT_TEMPLATE_PK
  ENABLE VALIDATE);

ALTER TABLE OL_SMS_FORMAT_TEMPLATE ADD (
  CONSTRAINT OL_SMS_FORMAT_TEMPLATE_FK01 
  FOREIGN KEY (OSMT_FORMAT_TYPE) 
  REFERENCES OL_DEF_FORMAT_TYPE (DT_NAME)
  ENABLE VALIDATE,
  CONSTRAINT OL_SMS_FORMAT_TEMPLATE_FK02 
  FOREIGN KEY (OSMT_FORMAT_DESC) 
  REFERENCES OL_DEF_FORMAT_CONT (DFC_NAME)
  ENABLE VALIDATE);

