OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/TxnFieldCheck
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBTxnFieldCheck.so
SOOBJS =  TxnFieldCheck.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
