OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLMerchantBalanceSnap
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLMerchantBalanceSnap.so
SOOBJS =  OLMerchantBalanceSnap.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
