OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnP2xOnUsCOM
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnP2xOnUsCOM.so
SOOBJS = TxnP2xOnUsCOM.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
