ALTER TABLE OL_STMT_MATCH_ACTION
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_STMT_MATCH_ACTION CASCADE CONSTRAINTS;

CREATE TABLE OL_STMT_MATCH_ACTION
(
  OSMA_ACTION_TYPE       VARCHAR2(50 BYTE),
  OSMA_ACTION_DESC       VARCHAR2(100 BYTE),
  OSMA_FIRST_PARTY       VARCHAR2(10 BYTE),
  OSMA_SECOND_PARTY      VARCHAR2(10 BYTE),
  OSMA_DISABLED          INTEGER                DEFAULT 0,
  OSMA_CREATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  OSMA_CREATE_USER       VARCHAR2(20 BYTE),
  OSMA_UPDATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  OSMA_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_STMT_MATCH_RULE_MAP_PK ON OL_STMT_MATCH_ACTION
(OSMA_ACTION_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_STMT_MATCH_ACTION ADD (
  CONSTRAINT OL_STMT_MATCH_ACTION_PK
  PRIMARY KEY
  (OSMA_ACTION_TYPE)
  USING INDEX OL_STMT_MATCH_RULE_MAP_PK
  ENABLE VALIDATE);

