OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/ClientMagicGpStatus
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBClientMagicGpStatus.so
SOOBJS =  ClientMagicGpStatus.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
