ALTER TABLE RULE_SERVICE_RELEASE_PERIOD
 DROP PRIMARY KEY CASCADE;

DROP TABLE RULE_SERVICE_RELEASE_PERIOD CASCADE CONSTRAINTS;

CREATE TABLE RULE_SERVICE_RELEASE_PERIOD
(
  RS_SERVICE_CODE      CHAR(3 BYTE),
  RS_DISABLED          INTEGER                  DEFAULT 0,
  RS_RELEASE_TYPE      VARCHAR2(10 BYTE),
  RS_RELEASE_PERIOD    INTEGER                  NOT NULL,
  RS_CREATE_USER       VARCHAR2(20 BYTE),
  RS_UPDATE_USER       VARCHAR2(20 BYTE),
  RS_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  RS_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX RULE_SERVICE_RELEASE_PERIOD_PK ON RULE_SERVICE_RELEASE_PERIOD
(RS_SERVICE_CODE, RS_RELEASE_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE RULE_SERVICE_RELEASE_PERIOD ADD (
  CONSTRAINT RULE_SERVICE_RELEASE_PERIOD_PK
  PRIMARY KEY
  (RS_SERVICE_CODE, RS_RELEASE_TYPE)
  USING INDEX RULE_SERVICE_RELEASE_PERIOD_PK
  ENABLE VALIDATE);

ALTER TABLE RULE_SERVICE_RELEASE_PERIOD ADD (
  CONSTRAINT RULE_SERVICE_RLS_PERIOD_FK01 
  FOREIGN KEY (RS_SERVICE_CODE) 
  REFERENCES DEF_SERVICE_CODE (SC_CODE)
  ENABLE VALIDATE,
  CONSTRAINT RULE_SERVICE_RLS_PERIOD_FK02 
  FOREIGN KEY (RS_RELEASE_TYPE) 
  REFERENCES DEF_RELEASE_PERIOD_TYPE (RP_TYPE)
  ENABLE VALIDATE);

