/* soapC.c
   Generated by gSOAP 2.8.0 from haipay.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   The generated code is released under one of the following licenses:
   GPL OR Genivia's license for commercial use.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif

#include "soapH.h"

#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapC.c ver 2.8.0 2011-03-04 03:36:18 GMT")


#ifndef WITH_NOGLOBAL

SOAP_FMAC3 void SOAP_FMAC4 soap_serializeheader(struct soap *soap)
{
	if (soap->header)
		soap_serialize_SOAP_ENV__Header(soap, soap->header);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_putheader(struct soap *soap)
{
	if (soap->header)
	{	soap->part = SOAP_IN_HEADER;
		if (soap_out_SOAP_ENV__Header(soap, "SOAP-ENV:Header", 0, soap->header, NULL))
			return soap->error;
		soap->part = SOAP_END_HEADER;
	}
	return SOAP_OK;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_getheader(struct soap *soap)
{
	soap->part = SOAP_IN_HEADER;
	soap->header = soap_in_SOAP_ENV__Header(soap, "SOAP-ENV:Header", NULL, NULL);
	soap->part = SOAP_END_HEADER;
	return soap->header == NULL;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_header(struct soap *soap)
{
	if (!soap->header)
	{	if ((soap->header = (struct SOAP_ENV__Header*)soap_malloc(soap, sizeof(struct SOAP_ENV__Header))))
			soap_default_SOAP_ENV__Header(soap, soap->header);
	}
}

SOAP_FMAC3 void SOAP_FMAC4 soap_fault(struct soap *soap)
{
	if (!soap->fault)
	{	soap->fault = (struct SOAP_ENV__Fault*)soap_malloc(soap, sizeof(struct SOAP_ENV__Fault));
		if (!soap->fault)
			return;
		soap_default_SOAP_ENV__Fault(soap, soap->fault);
	}
	if (soap->version == 2 && !soap->fault->SOAP_ENV__Code)
	{	soap->fault->SOAP_ENV__Code = (struct SOAP_ENV__Code*)soap_malloc(soap, sizeof(struct SOAP_ENV__Code));
		soap_default_SOAP_ENV__Code(soap, soap->fault->SOAP_ENV__Code);
	}
	if (soap->version == 2 && !soap->fault->SOAP_ENV__Reason)
	{	soap->fault->SOAP_ENV__Reason = (struct SOAP_ENV__Reason*)soap_malloc(soap, sizeof(struct SOAP_ENV__Reason));
		soap_default_SOAP_ENV__Reason(soap, soap->fault->SOAP_ENV__Reason);
	}
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serializefault(struct soap *soap)
{
	if (soap->fault)
		soap_serialize_SOAP_ENV__Fault(soap, soap->fault);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_putfault(struct soap *soap)
{
	if (soap->fault)
		return soap_put_SOAP_ENV__Fault(soap, soap->fault, "SOAP-ENV:Fault", NULL);
	return SOAP_OK;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_getfault(struct soap *soap)
{
	return (soap->fault = soap_get_SOAP_ENV__Fault(soap, NULL, "SOAP-ENV:Fault", NULL)) == NULL;
}

SOAP_FMAC3 const char ** SOAP_FMAC4 soap_faultcode(struct soap *soap)
{
	soap_fault(soap);
	if (soap->version == 2)
		return (const char**)&soap->fault->SOAP_ENV__Code->SOAP_ENV__Value;
	return (const char**)&soap->fault->faultcode;
}

SOAP_FMAC3 const char ** SOAP_FMAC4 soap_faultsubcode(struct soap *soap)
{
	soap_fault(soap);
	if (soap->version == 2)
	{	if (!soap->fault->SOAP_ENV__Code->SOAP_ENV__Subcode)
		{	soap->fault->SOAP_ENV__Code->SOAP_ENV__Subcode = (struct SOAP_ENV__Code*)soap_malloc(soap, sizeof(struct SOAP_ENV__Code));
			soap_default_SOAP_ENV__Code(soap, soap->fault->SOAP_ENV__Code->SOAP_ENV__Subcode);
		}
		return (const char**)&soap->fault->SOAP_ENV__Code->SOAP_ENV__Subcode->SOAP_ENV__Value;
	}
	return (const char**)&soap->fault->faultcode;
}

SOAP_FMAC3 const char ** SOAP_FMAC4 soap_faultstring(struct soap *soap)
{
	soap_fault(soap);
	if (soap->version == 2)
		return (const char**)&soap->fault->SOAP_ENV__Reason->SOAP_ENV__Text;
	return (const char**)&soap->fault->faultstring;
}

SOAP_FMAC3 const char ** SOAP_FMAC4 soap_faultdetail(struct soap *soap)
{
	soap_fault(soap);
	if (soap->version == 1)
	{	if (!soap->fault->detail)
		{	soap->fault->detail = (struct SOAP_ENV__Detail*)soap_malloc(soap, sizeof(struct SOAP_ENV__Detail));
			soap_default_SOAP_ENV__Detail(soap, soap->fault->detail);
		}
		return (const char**)&soap->fault->detail->__any;
	}
	if (!soap->fault->SOAP_ENV__Detail)
	{	soap->fault->SOAP_ENV__Detail = (struct SOAP_ENV__Detail*)soap_malloc(soap, sizeof(struct SOAP_ENV__Detail));
		soap_default_SOAP_ENV__Detail(soap, soap->fault->SOAP_ENV__Detail);
	}
	return (const char**)&soap->fault->SOAP_ENV__Detail->__any;
}

#endif

#ifndef WITH_NOIDREF
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap *soap)
{
	int t;
	if (soap->version == 1)
	{	for (;;)
		{	if (!soap_getelement(soap, &t))
				if (soap->error || soap_ignore_element(soap))
					break;
		}
	}
	if (soap->error == SOAP_NO_TAG || soap->error == SOAP_EOF)
		soap->error = SOAP_OK;
	return soap->error;
}
#endif

#ifndef WITH_NOIDREF
SOAP_FMAC3 void * SOAP_FMAC4 soap_getelement(struct soap *soap, int *type)
{
	if (soap_peek_element(soap))
		return NULL;
	if (!*soap->id || !(*type = soap_lookup_type(soap, soap->id)))
		*type = soap_lookup_type(soap, soap->href);
	switch (*type)
	{
	case SOAP_TYPE_byte:
		return soap_in_byte(soap, NULL, NULL, "xsd:byte");
	case SOAP_TYPE_int:
		return soap_in_int(soap, NULL, NULL, "xsd:int");
	case SOAP_TYPE_LONG64:
		return soap_in_LONG64(soap, NULL, NULL, "xsd:long");
	case SOAP_TYPE_ns1__ReturnRecordSub:
		return soap_in_ns1__ReturnRecordSub(soap, NULL, NULL, "ns1:ReturnRecordSub");
	case SOAP_TYPE_ns1__ReturnRecord:
		return soap_in_ns1__ReturnRecord(soap, NULL, NULL, "ns1:ReturnRecord");
	case SOAP_TYPE_ns1__ArrayOfReturnRecordSub:
		return soap_in_ns1__ArrayOfReturnRecordSub(soap, NULL, NULL, "ns1:ArrayOfReturnRecordSub");
	case SOAP_TYPE_ns1__ArrayOfReturnRecord:
		return soap_in_ns1__ArrayOfReturnRecord(soap, NULL, NULL, "ns1:ArrayOfReturnRecord");
	case SOAP_TYPE_ns1__DetailMsg:
		return soap_in_ns1__DetailMsg(soap, NULL, NULL, "ns1:DetailMsg");
	case SOAP_TYPE_PointerTo_ns1__BatchInResponse:
		return soap_in_PointerTo_ns1__BatchInResponse(soap, NULL, NULL, "ns1:BatchInResponse");
	case SOAP_TYPE_PointerTo_ns1__BatchIn:
		return soap_in_PointerTo_ns1__BatchIn(soap, NULL, NULL, "ns1:BatchIn");
	case SOAP_TYPE_PointerTons1__DetailMsg:
		return soap_in_PointerTons1__DetailMsg(soap, NULL, NULL, "ns1:DetailMsg");
	case SOAP_TYPE_PointerTons1__ReturnRecordSub:
		return soap_in_PointerTons1__ReturnRecordSub(soap, NULL, NULL, "ns1:ReturnRecordSub");
	case SOAP_TYPE_PointerTons1__ReturnRecord:
		return soap_in_PointerTons1__ReturnRecord(soap, NULL, NULL, "ns1:ReturnRecord");
	case SOAP_TYPE_PointerTons1__ArrayOfReturnRecordSub:
		return soap_in_PointerTons1__ArrayOfReturnRecordSub(soap, NULL, NULL, "ns1:ArrayOfReturnRecordSub");
	case SOAP_TYPE_PointerTons1__ArrayOfReturnRecord:
		return soap_in_PointerTons1__ArrayOfReturnRecord(soap, NULL, NULL, "ns1:ArrayOfReturnRecord");
	case SOAP_TYPE__QName:
	{	char **s;
		s = soap_in__QName(soap, NULL, NULL, "xsd:QName");
		return s ? *s : NULL;
	}
	case SOAP_TYPE_string:
	{	char **s;
		s = soap_in_string(soap, NULL, NULL, "xsd:string");
		return s ? *s : NULL;
	}
	default:
	{	const char *t = soap->type;
		if (!*t)
			t = soap->tag;
		if (!soap_match_tag(soap, t, "xsd:byte"))
		{	*type = SOAP_TYPE_byte;
			return soap_in_byte(soap, NULL, NULL, NULL);
		}
		if (!soap_match_tag(soap, t, "xsd:int"))
		{	*type = SOAP_TYPE_int;
			return soap_in_int(soap, NULL, NULL, NULL);
		}
		if (!soap_match_tag(soap, t, "xsd:long"))
		{	*type = SOAP_TYPE_LONG64;
			return soap_in_LONG64(soap, NULL, NULL, NULL);
		}
		if (!soap_match_tag(soap, t, "ns1:ReturnRecordSub"))
		{	*type = SOAP_TYPE_ns1__ReturnRecordSub;
			return soap_in_ns1__ReturnRecordSub(soap, NULL, NULL, NULL);
		}
		if (!soap_match_tag(soap, t, "ns1:ReturnRecord"))
		{	*type = SOAP_TYPE_ns1__ReturnRecord;
			return soap_in_ns1__ReturnRecord(soap, NULL, NULL, NULL);
		}
		if (!soap_match_tag(soap, t, "ns1:ArrayOfReturnRecordSub"))
		{	*type = SOAP_TYPE_ns1__ArrayOfReturnRecordSub;
			return soap_in_ns1__ArrayOfReturnRecordSub(soap, NULL, NULL, NULL);
		}
		if (!soap_match_tag(soap, t, "ns1:ArrayOfReturnRecord"))
		{	*type = SOAP_TYPE_ns1__ArrayOfReturnRecord;
			return soap_in_ns1__ArrayOfReturnRecord(soap, NULL, NULL, NULL);
		}
		if (!soap_match_tag(soap, t, "ns1:DetailMsg"))
		{	*type = SOAP_TYPE_ns1__DetailMsg;
			return soap_in_ns1__DetailMsg(soap, NULL, NULL, NULL);
		}
		if (!soap_match_tag(soap, t, "xsd:QName"))
		{	char **s;
			*type = SOAP_TYPE__QName;
			s = soap_in__QName(soap, NULL, NULL, NULL);
			return s ? *s : NULL;
		}
		if (!soap_match_tag(soap, t, "xsd:string"))
		{	char **s;
			*type = SOAP_TYPE_string;
			s = soap_in_string(soap, NULL, NULL, NULL);
			return s ? *s : NULL;
		}
		t = soap->tag;
		if (!soap_match_tag(soap, t, "ns1:BatchInResponse"))
		{	*type = SOAP_TYPE__ns1__BatchInResponse;
			return soap_in__ns1__BatchInResponse(soap, NULL, NULL, NULL);
		}
		if (!soap_match_tag(soap, t, "ns1:BatchIn"))
		{	*type = SOAP_TYPE__ns1__BatchIn;
			return soap_in__ns1__BatchIn(soap, NULL, NULL, NULL);
		}
	}
	}
	soap->error = SOAP_TAG_MISMATCH;
	return NULL;
}
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap *soap)
{
	if (!soap_peek_element(soap))
	{	int t;
		DBGLOG(TEST, SOAP_MESSAGE(fdebug, "Unexpected element '%s' in input (level=%u, %d)\n", soap->tag, soap->level, soap->body));
		if (soap->mustUnderstand && !soap->other)
			return soap->error = SOAP_MUSTUNDERSTAND;
		if (((soap->mode & SOAP_XML_STRICT) && soap->part != SOAP_IN_HEADER) || !soap_match_tag(soap, soap->tag, "SOAP-ENV:"))
		{	DBGLOG(TEST, SOAP_MESSAGE(fdebug, "REJECTING element '%s'\n", soap->tag));
			return soap->error = SOAP_TAG_MISMATCH;
		}
		if (!*soap->id || !soap_getelement(soap, &t))
		{	soap->peeked = 0;
			if (soap->fignore)
				soap->error = soap->fignore(soap, soap->tag);
			else
				soap->error = SOAP_OK;
			DBGLOG(TEST, if (!soap->error) SOAP_MESSAGE(fdebug, "IGNORING element '%s'\n", soap->tag));
			if (!soap->error && soap->body)
			{	soap->level++;
				while (!soap_ignore_element(soap))
					;
				if (soap->error == SOAP_NO_TAG)
					soap->error = soap_element_end_in(soap, NULL);
			}
		}
	}
	return soap->error;
}

#ifndef WITH_NOIDREF
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap *soap)
{
	int i;
	struct soap_plist *pp;
	if (soap->version == 1 && soap->encodingStyle && !(soap->mode & (SOAP_XML_TREE | SOAP_XML_GRAPH)))
		for (i = 0; i < SOAP_PTRHASH; i++)
			for (pp = soap->pht[i]; pp; pp = pp->next)
				if (pp->mark1 == 2 || pp->mark2 == 2)
					if (soap_putelement(soap, pp->ptr, "id", pp->id, pp->type))
						return soap->error;
	return SOAP_OK;
}
#endif

#ifndef WITH_NOIDREF
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap *soap, const void *ptr, const char *tag, int id, int type)
{
	switch (type)
	{
	case SOAP_TYPE_byte:
		return soap_out_byte(soap, tag, id, (const char *)ptr, "xsd:byte");
	case SOAP_TYPE_int:
		return soap_out_int(soap, tag, id, (const int *)ptr, "xsd:int");
	case SOAP_TYPE_LONG64:
		return soap_out_LONG64(soap, tag, id, (const LONG64 *)ptr, "xsd:long");
	case SOAP_TYPE__ns1__BatchInResponse:
		return soap_out__ns1__BatchInResponse(soap, "ns1:BatchInResponse", id, (const struct _ns1__BatchInResponse *)ptr, NULL);
	case SOAP_TYPE__ns1__BatchIn:
		return soap_out__ns1__BatchIn(soap, "ns1:BatchIn", id, (const struct _ns1__BatchIn *)ptr, NULL);
	case SOAP_TYPE_ns1__ReturnRecordSub:
		return soap_out_ns1__ReturnRecordSub(soap, tag, id, (const struct ns1__ReturnRecordSub *)ptr, "ns1:ReturnRecordSub");
	case SOAP_TYPE_ns1__ReturnRecord:
		return soap_out_ns1__ReturnRecord(soap, tag, id, (const struct ns1__ReturnRecord *)ptr, "ns1:ReturnRecord");
	case SOAP_TYPE_ns1__ArrayOfReturnRecordSub:
		return soap_out_ns1__ArrayOfReturnRecordSub(soap, tag, id, (const struct ns1__ArrayOfReturnRecordSub *)ptr, "ns1:ArrayOfReturnRecordSub");
	case SOAP_TYPE_ns1__ArrayOfReturnRecord:
		return soap_out_ns1__ArrayOfReturnRecord(soap, tag, id, (const struct ns1__ArrayOfReturnRecord *)ptr, "ns1:ArrayOfReturnRecord");
	case SOAP_TYPE_ns1__DetailMsg:
		return soap_out_ns1__DetailMsg(soap, tag, id, (const struct ns1__DetailMsg *)ptr, "ns1:DetailMsg");
	case SOAP_TYPE_PointerTo_ns1__BatchInResponse:
		return soap_out_PointerTo_ns1__BatchInResponse(soap, tag, id, (struct _ns1__BatchInResponse *const*)ptr, "ns1:BatchInResponse");
	case SOAP_TYPE_PointerTo_ns1__BatchIn:
		return soap_out_PointerTo_ns1__BatchIn(soap, tag, id, (struct _ns1__BatchIn *const*)ptr, "ns1:BatchIn");
	case SOAP_TYPE_PointerTons1__DetailMsg:
		return soap_out_PointerTons1__DetailMsg(soap, tag, id, (struct ns1__DetailMsg *const*)ptr, "ns1:DetailMsg");
	case SOAP_TYPE_PointerTons1__ReturnRecordSub:
		return soap_out_PointerTons1__ReturnRecordSub(soap, tag, id, (struct ns1__ReturnRecordSub *const*)ptr, "ns1:ReturnRecordSub");
	case SOAP_TYPE_PointerTons1__ReturnRecord:
		return soap_out_PointerTons1__ReturnRecord(soap, tag, id, (struct ns1__ReturnRecord *const*)ptr, "ns1:ReturnRecord");
	case SOAP_TYPE_PointerTons1__ArrayOfReturnRecordSub:
		return soap_out_PointerTons1__ArrayOfReturnRecordSub(soap, tag, id, (struct ns1__ArrayOfReturnRecordSub *const*)ptr, "ns1:ArrayOfReturnRecordSub");
	case SOAP_TYPE_PointerTons1__ArrayOfReturnRecord:
		return soap_out_PointerTons1__ArrayOfReturnRecord(soap, tag, id, (struct ns1__ArrayOfReturnRecord *const*)ptr, "ns1:ArrayOfReturnRecord");
	case SOAP_TYPE__QName:
		return soap_out_string(soap, tag, id, (char*const*)&ptr, "xsd:QName");
	case SOAP_TYPE_string:
		return soap_out_string(soap, tag, id, (char*const*)&ptr, "xsd:string");
	}
	return SOAP_OK;
}
#endif

#ifndef WITH_NOIDREF
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap *soap, const void *ptr, int type)
{
	(void)soap; (void)ptr; (void)type; /* appease -Wall -Werror */
	switch (type)
	{
	case SOAP_TYPE___ns3__BatchIn:
		soap_serialize___ns3__BatchIn(soap, (const struct __ns3__BatchIn *)ptr);
		break;
	case SOAP_TYPE___ns2__BatchIn:
		soap_serialize___ns2__BatchIn(soap, (const struct __ns2__BatchIn *)ptr);
		break;
	case SOAP_TYPE__ns1__BatchInResponse:
		soap_serialize__ns1__BatchInResponse(soap, (const struct _ns1__BatchInResponse *)ptr);
		break;
	case SOAP_TYPE__ns1__BatchIn:
		soap_serialize__ns1__BatchIn(soap, (const struct _ns1__BatchIn *)ptr);
		break;
	case SOAP_TYPE_ns1__ReturnRecordSub:
		soap_serialize_ns1__ReturnRecordSub(soap, (const struct ns1__ReturnRecordSub *)ptr);
		break;
	case SOAP_TYPE_ns1__ReturnRecord:
		soap_serialize_ns1__ReturnRecord(soap, (const struct ns1__ReturnRecord *)ptr);
		break;
	case SOAP_TYPE_ns1__ArrayOfReturnRecordSub:
		soap_serialize_ns1__ArrayOfReturnRecordSub(soap, (const struct ns1__ArrayOfReturnRecordSub *)ptr);
		break;
	case SOAP_TYPE_ns1__ArrayOfReturnRecord:
		soap_serialize_ns1__ArrayOfReturnRecord(soap, (const struct ns1__ArrayOfReturnRecord *)ptr);
		break;
	case SOAP_TYPE_ns1__DetailMsg:
		soap_serialize_ns1__DetailMsg(soap, (const struct ns1__DetailMsg *)ptr);
		break;
	case SOAP_TYPE_PointerTo_ns1__BatchInResponse:
		soap_serialize_PointerTo_ns1__BatchInResponse(soap, (struct _ns1__BatchInResponse *const*)ptr);
		break;
	case SOAP_TYPE_PointerTo_ns1__BatchIn:
		soap_serialize_PointerTo_ns1__BatchIn(soap, (struct _ns1__BatchIn *const*)ptr);
		break;
	case SOAP_TYPE_PointerTons1__DetailMsg:
		soap_serialize_PointerTons1__DetailMsg(soap, (struct ns1__DetailMsg *const*)ptr);
		break;
	case SOAP_TYPE_PointerTons1__ReturnRecordSub:
		soap_serialize_PointerTons1__ReturnRecordSub(soap, (struct ns1__ReturnRecordSub *const*)ptr);
		break;
	case SOAP_TYPE_PointerTons1__ReturnRecord:
		soap_serialize_PointerTons1__ReturnRecord(soap, (struct ns1__ReturnRecord *const*)ptr);
		break;
	case SOAP_TYPE_PointerTons1__ArrayOfReturnRecordSub:
		soap_serialize_PointerTons1__ArrayOfReturnRecordSub(soap, (struct ns1__ArrayOfReturnRecordSub *const*)ptr);
		break;
	case SOAP_TYPE_PointerTons1__ArrayOfReturnRecord:
		soap_serialize_PointerTons1__ArrayOfReturnRecord(soap, (struct ns1__ArrayOfReturnRecord *const*)ptr);
		break;
	case SOAP_TYPE__QName:
		soap_serialize_string(soap, (char*const*)&ptr);
		break;
	case SOAP_TYPE_string:
		soap_serialize_string(soap, (char*const*)&ptr);
		break;
	}
}
#endif

SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap *soap, char *a)
{
	(void)soap; /* appease -Wall -Werror */
#ifdef SOAP_DEFAULT_byte
	*a = SOAP_DEFAULT_byte;
#else
	*a = (char)0;
#endif
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap *soap, const char *tag, int id, const char *a, const char *type)
{
	return soap_outbyte(soap, tag, id, a, type, SOAP_TYPE_byte);
}

SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap *soap, const char *tag, char *a, const char *type)
{	char *p;
	p = soap_inbyte(soap, tag, a, type, SOAP_TYPE_byte);
	return p;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap *soap, const char *a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_byte);
	if (soap_out_byte(soap, tag?tag:"byte", id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap *soap, char *p, const char *tag, const char *type)
{
	if ((p = soap_in_byte(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap *soap, int *a)
{
	(void)soap; /* appease -Wall -Werror */
#ifdef SOAP_DEFAULT_int
	*a = SOAP_DEFAULT_int;
#else
	*a = (int)0;
#endif
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap *soap, const char *tag, int id, const int *a, const char *type)
{
	return soap_outint(soap, tag, id, a, type, SOAP_TYPE_int);
}

SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap *soap, const char *tag, int *a, const char *type)
{	int *p;
	p = soap_inint(soap, tag, a, type, SOAP_TYPE_int);
	return p;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap *soap, const int *a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_int);
	if (soap_out_int(soap, tag?tag:"int", id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap *soap, int *p, const char *tag, const char *type)
{
	if ((p = soap_in_int(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_default_LONG64(struct soap *soap, LONG64 *a)
{
	(void)soap; /* appease -Wall -Werror */
#ifdef SOAP_DEFAULT_LONG64
	*a = SOAP_DEFAULT_LONG64;
#else
	*a = (LONG64)0;
#endif
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_LONG64(struct soap *soap, const char *tag, int id, const LONG64 *a, const char *type)
{
	return soap_outLONG64(soap, tag, id, a, type, SOAP_TYPE_LONG64);
}

SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_in_LONG64(struct soap *soap, const char *tag, LONG64 *a, const char *type)
{	LONG64 *p;
	p = soap_inLONG64(soap, tag, a, type, SOAP_TYPE_LONG64);
	return p;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_LONG64(struct soap *soap, const LONG64 *a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_LONG64);
	if (soap_out_LONG64(soap, tag?tag:"long", id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_get_LONG64(struct soap *soap, LONG64 *p, const char *tag, const char *type)
{
	if ((p = soap_in_LONG64(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

#ifndef WITH_NOGLOBAL

SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap *soap, struct SOAP_ENV__Fault *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	soap_default__QName(soap, &a->faultcode);
	soap_default_string(soap, &a->faultstring);
	soap_default_string(soap, &a->faultactor);
	a->detail = NULL;
	a->SOAP_ENV__Code = NULL;
	a->SOAP_ENV__Reason = NULL;
	soap_default_string(soap, &a->SOAP_ENV__Node);
	soap_default_string(soap, &a->SOAP_ENV__Role);
	a->SOAP_ENV__Detail = NULL;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap *soap, const struct SOAP_ENV__Fault *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	soap_serialize__QName(soap, &a->faultcode);
	soap_serialize_string(soap, &a->faultstring);
	soap_serialize_string(soap, &a->faultactor);
	soap_serialize_PointerToSOAP_ENV__Detail(soap, &a->detail);
	soap_serialize_PointerToSOAP_ENV__Code(soap, &a->SOAP_ENV__Code);
	soap_serialize_PointerToSOAP_ENV__Reason(soap, &a->SOAP_ENV__Reason);
	soap_serialize_string(soap, &a->SOAP_ENV__Node);
	soap_serialize_string(soap, &a->SOAP_ENV__Role);
	soap_serialize_PointerToSOAP_ENV__Detail(soap, &a->SOAP_ENV__Detail);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap *soap, const char *tag, int id, const struct SOAP_ENV__Fault *a, const char *type)
{
	const char *soap_tmp_faultcode = soap_QName2s(soap, a->faultcode);
	if (soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_SOAP_ENV__Fault), type))
		return soap->error;
	if (soap_out__QName(soap, "faultcode", -1, (char*const*)&soap_tmp_faultcode, ""))
		return soap->error;
	if (soap_out_string(soap, "faultstring", -1, &a->faultstring, ""))
		return soap->error;
	if (soap_out_string(soap, "faultactor", -1, &a->faultactor, ""))
		return soap->error;
	if (soap_out_PointerToSOAP_ENV__Detail(soap, "detail", -1, &a->detail, ""))
		return soap->error;
	if (soap_out_PointerToSOAP_ENV__Code(soap, "SOAP-ENV:Code", -1, &a->SOAP_ENV__Code, ""))
		return soap->error;
	if (soap_out_PointerToSOAP_ENV__Reason(soap, "SOAP-ENV:Reason", -1, &a->SOAP_ENV__Reason, ""))
		return soap->error;
	if (soap_out_string(soap, "SOAP-ENV:Node", -1, &a->SOAP_ENV__Node, ""))
		return soap->error;
	if (soap_out_string(soap, "SOAP-ENV:Role", -1, &a->SOAP_ENV__Role, ""))
		return soap->error;
	if (soap_out_PointerToSOAP_ENV__Detail(soap, "SOAP-ENV:Detail", -1, &a->SOAP_ENV__Detail, ""))
		return soap->error;
	return soap_element_end_out(soap, tag);
}

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap *soap, const char *tag, struct SOAP_ENV__Fault *a, const char *type)
{
	size_t soap_flag_faultcode = 1;
	size_t soap_flag_faultstring = 1;
	size_t soap_flag_faultactor = 1;
	size_t soap_flag_detail = 1;
	size_t soap_flag_SOAP_ENV__Code = 1;
	size_t soap_flag_SOAP_ENV__Reason = 1;
	size_t soap_flag_SOAP_ENV__Node = 1;
	size_t soap_flag_SOAP_ENV__Role = 1;
	size_t soap_flag_SOAP_ENV__Detail = 1;
	if (soap_element_begin_in(soap, tag, 0, type))
		return NULL;
	a = (struct SOAP_ENV__Fault *)soap_id_enter(soap, soap->id, a, SOAP_TYPE_SOAP_ENV__Fault, sizeof(struct SOAP_ENV__Fault), 0, NULL, NULL, NULL);
	if (!a)
		return NULL;
	soap_default_SOAP_ENV__Fault(soap, a);
	if (soap->body && !*soap->href)
	{
		for (;;)
		{	soap->error = SOAP_TAG_MISMATCH;
			if (soap_flag_faultcode && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
				if (soap_in__QName(soap, "faultcode", &a->faultcode, ""))
				{	soap_flag_faultcode--;
					continue;
				}
			if (soap_flag_faultstring && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
				if (soap_in_string(soap, "faultstring", &a->faultstring, "xsd:string"))
				{	soap_flag_faultstring--;
					continue;
				}
			if (soap_flag_faultactor && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
				if (soap_in_string(soap, "faultactor", &a->faultactor, "xsd:string"))
				{	soap_flag_faultactor--;
					continue;
				}
			if (soap_flag_detail && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_PointerToSOAP_ENV__Detail(soap, "detail", &a->detail, ""))
				{	soap_flag_detail--;
					continue;
				}
			if (soap_flag_SOAP_ENV__Code && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_PointerToSOAP_ENV__Code(soap, "SOAP-ENV:Code", &a->SOAP_ENV__Code, ""))
				{	soap_flag_SOAP_ENV__Code--;
					continue;
				}
			if (soap_flag_SOAP_ENV__Reason && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_PointerToSOAP_ENV__Reason(soap, "SOAP-ENV:Reason", &a->SOAP_ENV__Reason, ""))
				{	soap_flag_SOAP_ENV__Reason--;
					continue;
				}
			if (soap_flag_SOAP_ENV__Node && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
				if (soap_in_string(soap, "SOAP-ENV:Node", &a->SOAP_ENV__Node, "xsd:string"))
				{	soap_flag_SOAP_ENV__Node--;
					continue;
				}
			if (soap_flag_SOAP_ENV__Role && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
				if (soap_in_string(soap, "SOAP-ENV:Role", &a->SOAP_ENV__Role, "xsd:string"))
				{	soap_flag_SOAP_ENV__Role--;
					continue;
				}
			if (soap_flag_SOAP_ENV__Detail && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_PointerToSOAP_ENV__Detail(soap, "SOAP-ENV:Detail", &a->SOAP_ENV__Detail, ""))
				{	soap_flag_SOAP_ENV__Detail--;
					continue;
				}
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
				return NULL;
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
	}
	else
	{	a = (struct SOAP_ENV__Fault *)soap_id_forward(soap, soap->href, (void*)a, 0, SOAP_TYPE_SOAP_ENV__Fault, 0, sizeof(struct SOAP_ENV__Fault), 0, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap *soap, const struct SOAP_ENV__Fault *a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_SOAP_ENV__Fault);
	if (soap_out_SOAP_ENV__Fault(soap, tag?tag:"SOAP-ENV:Fault", id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap *soap, struct SOAP_ENV__Fault *p, const char *tag, const char *type)
{
	if ((p = soap_in_SOAP_ENV__Fault(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

#endif

#ifndef WITH_NOGLOBAL

SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap *soap, struct SOAP_ENV__Reason *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	soap_default_string(soap, &a->SOAP_ENV__Text);
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap *soap, const struct SOAP_ENV__Reason *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	soap_serialize_string(soap, &a->SOAP_ENV__Text);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap *soap, const char *tag, int id, const struct SOAP_ENV__Reason *a, const char *type)
{
	if (soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_SOAP_ENV__Reason), type))
		return soap->error;
	if (soap->lang)
		soap_set_attr(soap, "xml:lang", soap->lang, 1);
	if (soap_out_string(soap, "SOAP-ENV:Text", -1, &a->SOAP_ENV__Text, ""))
		return soap->error;
	return soap_element_end_out(soap, tag);
}

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap *soap, const char *tag, struct SOAP_ENV__Reason *a, const char *type)
{
	size_t soap_flag_SOAP_ENV__Text = 1;
	if (soap_element_begin_in(soap, tag, 0, type))
		return NULL;
	a = (struct SOAP_ENV__Reason *)soap_id_enter(soap, soap->id, a, SOAP_TYPE_SOAP_ENV__Reason, sizeof(struct SOAP_ENV__Reason), 0, NULL, NULL, NULL);
	if (!a)
		return NULL;
	soap_default_SOAP_ENV__Reason(soap, a);
	if (soap->body && !*soap->href)
	{
		for (;;)
		{	soap->error = SOAP_TAG_MISMATCH;
			if (soap_flag_SOAP_ENV__Text && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
				if (soap_in_string(soap, "SOAP-ENV:Text", &a->SOAP_ENV__Text, "xsd:string"))
				{	soap_flag_SOAP_ENV__Text--;
					continue;
				}
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
				return NULL;
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
	}
	else
	{	a = (struct SOAP_ENV__Reason *)soap_id_forward(soap, soap->href, (void*)a, 0, SOAP_TYPE_SOAP_ENV__Reason, 0, sizeof(struct SOAP_ENV__Reason), 0, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap *soap, const struct SOAP_ENV__Reason *a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_SOAP_ENV__Reason);
	if (soap_out_SOAP_ENV__Reason(soap, tag?tag:"SOAP-ENV:Reason", id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap *soap, struct SOAP_ENV__Reason *p, const char *tag, const char *type)
{
	if ((p = soap_in_SOAP_ENV__Reason(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

#endif

#ifndef WITH_NOGLOBAL

SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap *soap, struct SOAP_ENV__Detail *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	a->__type = 0;
	a->fault = NULL;
	a->__any = NULL;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap *soap, const struct SOAP_ENV__Detail *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	soap_markelement(soap, a->fault, a->__type);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap *soap, const char *tag, int id, const struct SOAP_ENV__Detail *a, const char *type)
{
	if (soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_SOAP_ENV__Detail), type))
		return soap->error;
	if (soap_putelement(soap, a->fault, "fault", -1, a->__type))
		return soap->error;
	soap_outliteral(soap, "-any", &a->__any, NULL);
	return soap_element_end_out(soap, tag);
}

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap *soap, const char *tag, struct SOAP_ENV__Detail *a, const char *type)
{
	size_t soap_flag_fault = 1;
	size_t soap_flag___any = 1;
	if (soap_element_begin_in(soap, tag, 0, type))
		return NULL;
	a = (struct SOAP_ENV__Detail *)soap_id_enter(soap, soap->id, a, SOAP_TYPE_SOAP_ENV__Detail, sizeof(struct SOAP_ENV__Detail), 0, NULL, NULL, NULL);
	if (!a)
		return NULL;
	soap_default_SOAP_ENV__Detail(soap, a);
	if (soap->body && !*soap->href)
	{
		for (;;)
		{	soap->error = SOAP_TAG_MISMATCH;
			if (soap_flag_fault && soap->error == SOAP_TAG_MISMATCH)
				if ((a->fault = soap_getelement(soap, &a->__type)))
				{	soap_flag_fault = 0;
					continue;
				}
			if (soap_flag___any && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
				if (soap_inliteral(soap, "-any", &a->__any))
				{	soap_flag___any--;
					continue;
				}
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
				return NULL;
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
	}
	else
	{	a = (struct SOAP_ENV__Detail *)soap_id_forward(soap, soap->href, (void*)a, 0, SOAP_TYPE_SOAP_ENV__Detail, 0, sizeof(struct SOAP_ENV__Detail), 0, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap *soap, const struct SOAP_ENV__Detail *a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_SOAP_ENV__Detail);
	if (soap_out_SOAP_ENV__Detail(soap, tag?tag:"SOAP-ENV:Detail", id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap *soap, struct SOAP_ENV__Detail *p, const char *tag, const char *type)
{
	if ((p = soap_in_SOAP_ENV__Detail(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

#endif

#ifndef WITH_NOGLOBAL

SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap *soap, struct SOAP_ENV__Code *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	soap_default__QName(soap, &a->SOAP_ENV__Value);
	a->SOAP_ENV__Subcode = NULL;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap *soap, const struct SOAP_ENV__Code *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	soap_serialize__QName(soap, &a->SOAP_ENV__Value);
	soap_serialize_PointerToSOAP_ENV__Code(soap, &a->SOAP_ENV__Subcode);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap *soap, const char *tag, int id, const struct SOAP_ENV__Code *a, const char *type)
{
	const char *soap_tmp_SOAP_ENV__Value = soap_QName2s(soap, a->SOAP_ENV__Value);
	if (soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_SOAP_ENV__Code), type))
		return soap->error;
	if (soap_out__QName(soap, "SOAP-ENV:Value", -1, (char*const*)&soap_tmp_SOAP_ENV__Value, ""))
		return soap->error;
	if (soap_out_PointerToSOAP_ENV__Code(soap, "SOAP-ENV:Subcode", -1, &a->SOAP_ENV__Subcode, ""))
		return soap->error;
	return soap_element_end_out(soap, tag);
}

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap *soap, const char *tag, struct SOAP_ENV__Code *a, const char *type)
{
	size_t soap_flag_SOAP_ENV__Value = 1;
	size_t soap_flag_SOAP_ENV__Subcode = 1;
	if (soap_element_begin_in(soap, tag, 0, type))
		return NULL;
	a = (struct SOAP_ENV__Code *)soap_id_enter(soap, soap->id, a, SOAP_TYPE_SOAP_ENV__Code, sizeof(struct SOAP_ENV__Code), 0, NULL, NULL, NULL);
	if (!a)
		return NULL;
	soap_default_SOAP_ENV__Code(soap, a);
	if (soap->body && !*soap->href)
	{
		for (;;)
		{	soap->error = SOAP_TAG_MISMATCH;
			if (soap_flag_SOAP_ENV__Value && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
				if (soap_in__QName(soap, "SOAP-ENV:Value", &a->SOAP_ENV__Value, ""))
				{	soap_flag_SOAP_ENV__Value--;
					continue;
				}
			if (soap_flag_SOAP_ENV__Subcode && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_PointerToSOAP_ENV__Code(soap, "SOAP-ENV:Subcode", &a->SOAP_ENV__Subcode, ""))
				{	soap_flag_SOAP_ENV__Subcode--;
					continue;
				}
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
				return NULL;
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
	}
	else
	{	a = (struct SOAP_ENV__Code *)soap_id_forward(soap, soap->href, (void*)a, 0, SOAP_TYPE_SOAP_ENV__Code, 0, sizeof(struct SOAP_ENV__Code), 0, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap *soap, const struct SOAP_ENV__Code *a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_SOAP_ENV__Code);
	if (soap_out_SOAP_ENV__Code(soap, tag?tag:"SOAP-ENV:Code", id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap *soap, struct SOAP_ENV__Code *p, const char *tag, const char *type)
{
	if ((p = soap_in_SOAP_ENV__Code(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

#endif

#ifndef WITH_NOGLOBAL

SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap *soap, struct SOAP_ENV__Header *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap *soap, const struct SOAP_ENV__Header *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap *soap, const char *tag, int id, const struct SOAP_ENV__Header *a, const char *type)
{
	if (soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_SOAP_ENV__Header), type))
		return soap->error;
	return soap_element_end_out(soap, tag);
}

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap *soap, const char *tag, struct SOAP_ENV__Header *a, const char *type)
{
	if (soap_element_begin_in(soap, tag, 0, type))
		return NULL;
	a = (struct SOAP_ENV__Header *)soap_id_enter(soap, soap->id, a, SOAP_TYPE_SOAP_ENV__Header, sizeof(struct SOAP_ENV__Header), 0, NULL, NULL, NULL);
	if (!a)
		return NULL;
	soap_default_SOAP_ENV__Header(soap, a);
	if (soap->body && !*soap->href)
	{
		for (;;)
		{	soap->error = SOAP_TAG_MISMATCH;
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
				return NULL;
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
	}
	else
	{	a = (struct SOAP_ENV__Header *)soap_id_forward(soap, soap->href, (void*)a, 0, SOAP_TYPE_SOAP_ENV__Header, 0, sizeof(struct SOAP_ENV__Header), 0, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap *soap, const struct SOAP_ENV__Header *a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_SOAP_ENV__Header);
	if (soap_out_SOAP_ENV__Header(soap, tag?tag:"SOAP-ENV:Header", id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap *soap, struct SOAP_ENV__Header *p, const char *tag, const char *type)
{
	if ((p = soap_in_SOAP_ENV__Header(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

#endif

SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns3__BatchIn(struct soap *soap, struct __ns3__BatchIn *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	a->ns1__BatchIn = NULL;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns3__BatchIn(struct soap *soap, const struct __ns3__BatchIn *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	soap_serialize_PointerTo_ns1__BatchIn(soap, &a->ns1__BatchIn);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns3__BatchIn(struct soap *soap, const char *tag, int id, const struct __ns3__BatchIn *a, const char *type)
{
	if (soap_out_PointerTo_ns1__BatchIn(soap, "ns1:BatchIn", -1, &a->ns1__BatchIn, ""))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC3 struct __ns3__BatchIn * SOAP_FMAC4 soap_in___ns3__BatchIn(struct soap *soap, const char *tag, struct __ns3__BatchIn *a, const char *type)
{
	size_t soap_flag_ns1__BatchIn = 1;
	short soap_flag;
	a = (struct __ns3__BatchIn *)soap_id_enter(soap, "", a, SOAP_TYPE___ns3__BatchIn, sizeof(struct __ns3__BatchIn), 0, NULL, NULL, NULL);
	if (!a)
		return NULL;
	soap_default___ns3__BatchIn(soap, a);
		for (soap_flag = 0;; soap_flag = 1)
		{	soap->error = SOAP_TAG_MISMATCH;
			if (soap_flag_ns1__BatchIn && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_PointerTo_ns1__BatchIn(soap, "ns1:BatchIn", &a->ns1__BatchIn, ""))
				{	soap_flag_ns1__BatchIn--;
					continue;
				}
			if (soap->error == SOAP_TAG_MISMATCH)
				if (soap_flag)
				{	soap->error = SOAP_OK;
					break;
				}
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
				return NULL;
		}
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns3__BatchIn(struct soap *soap, const struct __ns3__BatchIn *a, const char *tag, const char *type)
{
	register int id = 0;
	if (soap_out___ns3__BatchIn(soap, tag?tag:"-ns3:BatchIn", id, a, type))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC3 struct __ns3__BatchIn * SOAP_FMAC4 soap_get___ns3__BatchIn(struct soap *soap, struct __ns3__BatchIn *p, const char *tag, const char *type)
{
	if ((p = soap_in___ns3__BatchIn(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns2__BatchIn(struct soap *soap, struct __ns2__BatchIn *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	a->ns1__BatchIn = NULL;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns2__BatchIn(struct soap *soap, const struct __ns2__BatchIn *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	soap_serialize_PointerTo_ns1__BatchIn(soap, &a->ns1__BatchIn);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns2__BatchIn(struct soap *soap, const char *tag, int id, const struct __ns2__BatchIn *a, const char *type)
{
	if (soap_out_PointerTo_ns1__BatchIn(soap, "ns1:BatchIn", -1, &a->ns1__BatchIn, ""))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC3 struct __ns2__BatchIn * SOAP_FMAC4 soap_in___ns2__BatchIn(struct soap *soap, const char *tag, struct __ns2__BatchIn *a, const char *type)
{
	size_t soap_flag_ns1__BatchIn = 1;
	short soap_flag;
	a = (struct __ns2__BatchIn *)soap_id_enter(soap, "", a, SOAP_TYPE___ns2__BatchIn, sizeof(struct __ns2__BatchIn), 0, NULL, NULL, NULL);
	if (!a)
		return NULL;
	soap_default___ns2__BatchIn(soap, a);
		for (soap_flag = 0;; soap_flag = 1)
		{	soap->error = SOAP_TAG_MISMATCH;
			if (soap_flag_ns1__BatchIn && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_PointerTo_ns1__BatchIn(soap, "ns1:BatchIn", &a->ns1__BatchIn, ""))
				{	soap_flag_ns1__BatchIn--;
					continue;
				}
			if (soap->error == SOAP_TAG_MISMATCH)
				if (soap_flag)
				{	soap->error = SOAP_OK;
					break;
				}
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
				return NULL;
		}
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns2__BatchIn(struct soap *soap, const struct __ns2__BatchIn *a, const char *tag, const char *type)
{
	register int id = 0;
	if (soap_out___ns2__BatchIn(soap, tag?tag:"-ns2:BatchIn", id, a, type))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC3 struct __ns2__BatchIn * SOAP_FMAC4 soap_get___ns2__BatchIn(struct soap *soap, struct __ns2__BatchIn *p, const char *tag, const char *type)
{
	if ((p = soap_in___ns2__BatchIn(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__BatchInResponse(struct soap *soap, struct _ns1__BatchInResponse *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	a->BatchInResult = NULL;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__BatchInResponse(struct soap *soap, const struct _ns1__BatchInResponse *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	soap_serialize_PointerTons1__DetailMsg(soap, &a->BatchInResult);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__BatchInResponse(struct soap *soap, const char *tag, int id, const struct _ns1__BatchInResponse *a, const char *type)
{
	if (soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE__ns1__BatchInResponse), type))
		return soap->error;
	if (a->BatchInResult)
		soap_element_result(soap, "ns1:BatchInResult");
	if (a->BatchInResult)
	{	if (soap_out_PointerTons1__DetailMsg(soap, "ns1:BatchInResult", -1, &a->BatchInResult, ""))
			return soap->error;
	}
	else if (soap_element_nil(soap, "ns1:BatchInResult"))
		return soap->error;
	return soap_element_end_out(soap, tag);
}

SOAP_FMAC3 struct _ns1__BatchInResponse * SOAP_FMAC4 soap_in__ns1__BatchInResponse(struct soap *soap, const char *tag, struct _ns1__BatchInResponse *a, const char *type)
{
	size_t soap_flag_BatchInResult = 1;
	if (soap_element_begin_in(soap, tag, 0, type))
		return NULL;
	a = (struct _ns1__BatchInResponse *)soap_id_enter(soap, soap->id, a, SOAP_TYPE__ns1__BatchInResponse, sizeof(struct _ns1__BatchInResponse), 0, NULL, NULL, NULL);
	if (!a)
		return NULL;
	soap_default__ns1__BatchInResponse(soap, a);
	if (soap->body && !*soap->href)
	{
		for (;;)
		{	soap->error = SOAP_TAG_MISMATCH;
			if (soap_flag_BatchInResult && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_PointerTons1__DetailMsg(soap, "ns1:BatchInResult", &a->BatchInResult, "ns1:DetailMsg"))
				{	soap_flag_BatchInResult--;
					continue;
				}
			soap_check_result(soap, "ns1:BatchInResult");
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
				return NULL;
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
	}
	else
	{	a = (struct _ns1__BatchInResponse *)soap_id_forward(soap, soap->href, (void*)a, 0, SOAP_TYPE__ns1__BatchInResponse, 0, sizeof(struct _ns1__BatchInResponse), 0, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	if ((soap->mode & SOAP_XML_STRICT) && (soap_flag_BatchInResult > 0))
	{	soap->error = SOAP_OCCURS;
		return NULL;
	}
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__BatchInResponse(struct soap *soap, const struct _ns1__BatchInResponse *a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE__ns1__BatchInResponse);
	if (soap_out__ns1__BatchInResponse(soap, tag?tag:"ns1:BatchInResponse", id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 struct _ns1__BatchInResponse * SOAP_FMAC4 soap_get__ns1__BatchInResponse(struct soap *soap, struct _ns1__BatchInResponse *p, const char *tag, const char *type)
{
	if ((p = soap_in__ns1__BatchInResponse(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__BatchIn(struct soap *soap, struct _ns1__BatchIn *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	soap_default_string(soap, &a->MERCODE);
	soap_default_string(soap, &a->DETAILSID);
	soap_default_int(soap, &a->FLAG);
	soap_default_string(soap, &a->NAME);
	soap_default_string(soap, &a->IDCARD);
	soap_default_string(soap, &a->MOBILEPHONE);
	soap_default_string(soap, &a->BANKNAME);
	soap_default_string(soap, &a->BRANCHBANKNAME);
	soap_default_string(soap, &a->ACCOUNT);
	soap_default_string(soap, &a->AMOUNT);
	soap_default_string(soap, &a->DCREATETIME);
	soap_default_string(soap, &a->PROVINCENAME);
	soap_default_string(soap, &a->CITYNAME);
	soap_default_string(soap, &a->SIGN);
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__BatchIn(struct soap *soap, const struct _ns1__BatchIn *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	soap_serialize_string(soap, &a->MERCODE);
	soap_serialize_string(soap, &a->DETAILSID);
	soap_serialize_string(soap, &a->NAME);
	soap_serialize_string(soap, &a->IDCARD);
	soap_serialize_string(soap, &a->MOBILEPHONE);
	soap_serialize_string(soap, &a->BANKNAME);
	soap_serialize_string(soap, &a->BRANCHBANKNAME);
	soap_serialize_string(soap, &a->ACCOUNT);
	soap_serialize_string(soap, &a->AMOUNT);
	soap_serialize_string(soap, &a->DCREATETIME);
	soap_serialize_string(soap, &a->PROVINCENAME);
	soap_serialize_string(soap, &a->CITYNAME);
	soap_serialize_string(soap, &a->SIGN);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__BatchIn(struct soap *soap, const char *tag, int id, const struct _ns1__BatchIn *a, const char *type)
{
	if (soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE__ns1__BatchIn), type))
		return soap->error;
	if (soap_out_string(soap, "ns1:MERCODE", -1, &a->MERCODE, ""))
		return soap->error;
	if (soap_out_string(soap, "ns1:DETAILSID", -1, &a->DETAILSID, ""))
		return soap->error;
	if (soap_out_int(soap, "ns1:FLAG", -1, &a->FLAG, ""))
		return soap->error;
	if (soap_out_string(soap, "ns1:NAME", -1, &a->NAME, ""))
		return soap->error;
	if (soap_out_string(soap, "ns1:IDCARD", -1, &a->IDCARD, ""))
		return soap->error;
	if (soap_out_string(soap, "ns1:MOBILEPHONE", -1, &a->MOBILEPHONE, ""))
		return soap->error;
	if (soap_out_string(soap, "ns1:BANKNAME", -1, &a->BANKNAME, ""))
		return soap->error;
	if (soap_out_string(soap, "ns1:BRANCHBANKNAME", -1, &a->BRANCHBANKNAME, ""))
		return soap->error;
	if (soap_out_string(soap, "ns1:ACCOUNT", -1, &a->ACCOUNT, ""))
		return soap->error;
	if (soap_out_string(soap, "ns1:AMOUNT", -1, &a->AMOUNT, ""))
		return soap->error;
	if (soap_out_string(soap, "ns1:DCREATETIME", -1, &a->DCREATETIME, ""))
		return soap->error;
	if (soap_out_string(soap, "ns1:PROVINCENAME", -1, &a->PROVINCENAME, ""))
		return soap->error;
	if (soap_out_string(soap, "ns1:CITYNAME", -1, &a->CITYNAME, ""))
		return soap->error;
	if (soap_out_string(soap, "ns1:SIGN", -1, &a->SIGN, ""))
		return soap->error;
	return soap_element_end_out(soap, tag);
}

SOAP_FMAC3 struct _ns1__BatchIn * SOAP_FMAC4 soap_in__ns1__BatchIn(struct soap *soap, const char *tag, struct _ns1__BatchIn *a, const char *type)
{
	size_t soap_flag_MERCODE = 1;
	size_t soap_flag_DETAILSID = 1;
	size_t soap_flag_FLAG = 1;
	size_t soap_flag_NAME = 1;
	size_t soap_flag_IDCARD = 1;
	size_t soap_flag_MOBILEPHONE = 1;
	size_t soap_flag_BANKNAME = 1;
	size_t soap_flag_BRANCHBANKNAME = 1;
	size_t soap_flag_ACCOUNT = 1;
	size_t soap_flag_AMOUNT = 1;
	size_t soap_flag_DCREATETIME = 1;
	size_t soap_flag_PROVINCENAME = 1;
	size_t soap_flag_CITYNAME = 1;
	size_t soap_flag_SIGN = 1;
	if (soap_element_begin_in(soap, tag, 0, type))
		return NULL;
	a = (struct _ns1__BatchIn *)soap_id_enter(soap, soap->id, a, SOAP_TYPE__ns1__BatchIn, sizeof(struct _ns1__BatchIn), 0, NULL, NULL, NULL);
	if (!a)
		return NULL;
	soap_default__ns1__BatchIn(soap, a);
	if (soap->body && !*soap->href)
	{
		for (;;)
		{	soap->error = SOAP_TAG_MISMATCH;
			if (soap_flag_MERCODE && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
				if (soap_in_string(soap, "ns1:MERCODE", &a->MERCODE, "xsd:string"))
				{	soap_flag_MERCODE--;
					continue;
				}
			if (soap_flag_DETAILSID && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
				if (soap_in_string(soap, "ns1:DETAILSID", &a->DETAILSID, "xsd:string"))
				{	soap_flag_DETAILSID--;
					continue;
				}
			if (soap_flag_FLAG && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_int(soap, "ns1:FLAG", &a->FLAG, "xsd:int"))
				{	soap_flag_FLAG--;
					continue;
				}
			if (soap_flag_NAME && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
				if (soap_in_string(soap, "ns1:NAME", &a->NAME, "xsd:string"))
				{	soap_flag_NAME--;
					continue;
				}
			if (soap_flag_IDCARD && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
				if (soap_in_string(soap, "ns1:IDCARD", &a->IDCARD, "xsd:string"))
				{	soap_flag_IDCARD--;
					continue;
				}
			if (soap_flag_MOBILEPHONE && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
				if (soap_in_string(soap, "ns1:MOBILEPHONE", &a->MOBILEPHONE, "xsd:string"))
				{	soap_flag_MOBILEPHONE--;
					continue;
				}
			if (soap_flag_BANKNAME && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
				if (soap_in_string(soap, "ns1:BANKNAME", &a->BANKNAME, "xsd:string"))
				{	soap_flag_BANKNAME--;
					continue;
				}
			if (soap_flag_BRANCHBANKNAME && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
				if (soap_in_string(soap, "ns1:BRANCHBANKNAME", &a->BRANCHBANKNAME, "xsd:string"))
				{	soap_flag_BRANCHBANKNAME--;
					continue;
				}
			if (soap_flag_ACCOUNT && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
				if (soap_in_string(soap, "ns1:ACCOUNT", &a->ACCOUNT, "xsd:string"))
				{	soap_flag_ACCOUNT--;
					continue;
				}
			if (soap_flag_AMOUNT && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
				if (soap_in_string(soap, "ns1:AMOUNT", &a->AMOUNT, "xsd:string"))
				{	soap_flag_AMOUNT--;
					continue;
				}
			if (soap_flag_DCREATETIME && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
				if (soap_in_string(soap, "ns1:DCREATETIME", &a->DCREATETIME, "xsd:string"))
				{	soap_flag_DCREATETIME--;
					continue;
				}
			if (soap_flag_PROVINCENAME && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
				if (soap_in_string(soap, "ns1:PROVINCENAME", &a->PROVINCENAME, "xsd:string"))
				{	soap_flag_PROVINCENAME--;
					continue;
				}
			if (soap_flag_CITYNAME && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
				if (soap_in_string(soap, "ns1:CITYNAME", &a->CITYNAME, "xsd:string"))
				{	soap_flag_CITYNAME--;
					continue;
				}
			if (soap_flag_SIGN && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
				if (soap_in_string(soap, "ns1:SIGN", &a->SIGN, "xsd:string"))
				{	soap_flag_SIGN--;
					continue;
				}
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
				return NULL;
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
	}
	else
	{	a = (struct _ns1__BatchIn *)soap_id_forward(soap, soap->href, (void*)a, 0, SOAP_TYPE__ns1__BatchIn, 0, sizeof(struct _ns1__BatchIn), 0, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	if ((soap->mode & SOAP_XML_STRICT) && (soap_flag_FLAG > 0))
	{	soap->error = SOAP_OCCURS;
		return NULL;
	}
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__BatchIn(struct soap *soap, const struct _ns1__BatchIn *a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE__ns1__BatchIn);
	if (soap_out__ns1__BatchIn(soap, tag?tag:"ns1:BatchIn", id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 struct _ns1__BatchIn * SOAP_FMAC4 soap_get__ns1__BatchIn(struct soap *soap, struct _ns1__BatchIn *p, const char *tag, const char *type)
{
	if ((p = soap_in__ns1__BatchIn(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__ReturnRecordSub(struct soap *soap, struct ns1__ReturnRecordSub *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	soap_default_string(soap, &a->DetailsNew);
	soap_default_LONG64(soap, &a->AmountsNew);
	soap_default_LONG64(soap, &a->PayAmountNew);
	soap_default_LONG64(soap, &a->ReceiveAmountNew);
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__ReturnRecordSub(struct soap *soap, const struct ns1__ReturnRecordSub *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	soap_serialize_string(soap, &a->DetailsNew);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ReturnRecordSub(struct soap *soap, const char *tag, int id, const struct ns1__ReturnRecordSub *a, const char *type)
{
	if (soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_ns1__ReturnRecordSub), type))
		return soap->error;
	if (soap_out_string(soap, "ns1:DetailsNew", -1, &a->DetailsNew, ""))
		return soap->error;
	if (soap_out_LONG64(soap, "ns1:AmountsNew", -1, &a->AmountsNew, ""))
		return soap->error;
	if (soap_out_LONG64(soap, "ns1:PayAmountNew", -1, &a->PayAmountNew, ""))
		return soap->error;
	if (soap_out_LONG64(soap, "ns1:ReceiveAmountNew", -1, &a->ReceiveAmountNew, ""))
		return soap->error;
	return soap_element_end_out(soap, tag);
}

SOAP_FMAC3 struct ns1__ReturnRecordSub * SOAP_FMAC4 soap_in_ns1__ReturnRecordSub(struct soap *soap, const char *tag, struct ns1__ReturnRecordSub *a, const char *type)
{
	size_t soap_flag_DetailsNew = 1;
	size_t soap_flag_AmountsNew = 1;
	size_t soap_flag_PayAmountNew = 1;
	size_t soap_flag_ReceiveAmountNew = 1;
	if (soap_element_begin_in(soap, tag, 0, type))
		return NULL;
	a = (struct ns1__ReturnRecordSub *)soap_id_enter(soap, soap->id, a, SOAP_TYPE_ns1__ReturnRecordSub, sizeof(struct ns1__ReturnRecordSub), 0, NULL, NULL, NULL);
	if (!a)
		return NULL;
	soap_default_ns1__ReturnRecordSub(soap, a);
	if (soap->body && !*soap->href)
	{
		for (;;)
		{	soap->error = SOAP_TAG_MISMATCH;
			if (soap_flag_DetailsNew && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
				if (soap_in_string(soap, "ns1:DetailsNew", &a->DetailsNew, "xsd:string"))
				{	soap_flag_DetailsNew--;
					continue;
				}
			if (soap_flag_AmountsNew && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_LONG64(soap, "ns1:AmountsNew", &a->AmountsNew, "xsd:long"))
				{	soap_flag_AmountsNew--;
					continue;
				}
			if (soap_flag_PayAmountNew && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_LONG64(soap, "ns1:PayAmountNew", &a->PayAmountNew, "xsd:long"))
				{	soap_flag_PayAmountNew--;
					continue;
				}
			if (soap_flag_ReceiveAmountNew && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_LONG64(soap, "ns1:ReceiveAmountNew", &a->ReceiveAmountNew, "xsd:long"))
				{	soap_flag_ReceiveAmountNew--;
					continue;
				}
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
				return NULL;
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
	}
	else
	{	a = (struct ns1__ReturnRecordSub *)soap_id_forward(soap, soap->href, (void*)a, 0, SOAP_TYPE_ns1__ReturnRecordSub, 0, sizeof(struct ns1__ReturnRecordSub), 0, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	if ((soap->mode & SOAP_XML_STRICT) && (soap_flag_AmountsNew > 0 || soap_flag_PayAmountNew > 0 || soap_flag_ReceiveAmountNew > 0))
	{	soap->error = SOAP_OCCURS;
		return NULL;
	}
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__ReturnRecordSub(struct soap *soap, const struct ns1__ReturnRecordSub *a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_ns1__ReturnRecordSub);
	if (soap_out_ns1__ReturnRecordSub(soap, tag?tag:"ns1:ReturnRecordSub", id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 struct ns1__ReturnRecordSub * SOAP_FMAC4 soap_get_ns1__ReturnRecordSub(struct soap *soap, struct ns1__ReturnRecordSub *p, const char *tag, const char *type)
{
	if ((p = soap_in_ns1__ReturnRecordSub(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__ReturnRecord(struct soap *soap, struct ns1__ReturnRecord *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	soap_default_string(soap, &a->ProjectId);
	soap_default_string(soap, &a->BatchId);
	soap_default_string(soap, &a->BatchName);
	soap_default_string(soap, &a->Cr_USCORECode);
	soap_default_LONG64(soap, &a->Amounts);
	soap_default_LONG64(soap, &a->PayAmount);
	soap_default_LONG64(soap, &a->ReceiveAmount);
	soap_default_string(soap, &a->Flag);
	soap_default_string(soap, &a->Sign);
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__ReturnRecord(struct soap *soap, const struct ns1__ReturnRecord *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	soap_serialize_string(soap, &a->ProjectId);
	soap_serialize_string(soap, &a->BatchId);
	soap_serialize_string(soap, &a->BatchName);
	soap_serialize_string(soap, &a->Cr_USCORECode);
	soap_serialize_string(soap, &a->Flag);
	soap_serialize_string(soap, &a->Sign);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ReturnRecord(struct soap *soap, const char *tag, int id, const struct ns1__ReturnRecord *a, const char *type)
{
	if (soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_ns1__ReturnRecord), type))
		return soap->error;
	if (soap_out_string(soap, "ns1:ProjectId", -1, &a->ProjectId, ""))
		return soap->error;
	if (soap_out_string(soap, "ns1:BatchId", -1, &a->BatchId, ""))
		return soap->error;
	if (soap_out_string(soap, "ns1:BatchName", -1, &a->BatchName, ""))
		return soap->error;
	if (soap_out_string(soap, "ns1:Cr_Code", -1, &a->Cr_USCORECode, ""))
		return soap->error;
	if (soap_out_LONG64(soap, "ns1:Amounts", -1, &a->Amounts, ""))
		return soap->error;
	if (soap_out_LONG64(soap, "ns1:PayAmount", -1, &a->PayAmount, ""))
		return soap->error;
	if (soap_out_LONG64(soap, "ns1:ReceiveAmount", -1, &a->ReceiveAmount, ""))
		return soap->error;
	if (soap_out_string(soap, "ns1:Flag", -1, &a->Flag, ""))
		return soap->error;
	if (soap_out_string(soap, "ns1:Sign", -1, &a->Sign, ""))
		return soap->error;
	return soap_element_end_out(soap, tag);
}

SOAP_FMAC3 struct ns1__ReturnRecord * SOAP_FMAC4 soap_in_ns1__ReturnRecord(struct soap *soap, const char *tag, struct ns1__ReturnRecord *a, const char *type)
{
	size_t soap_flag_ProjectId = 1;
	size_t soap_flag_BatchId = 1;
	size_t soap_flag_BatchName = 1;
	size_t soap_flag_Cr_USCORECode = 1;
	size_t soap_flag_Amounts = 1;
	size_t soap_flag_PayAmount = 1;
	size_t soap_flag_ReceiveAmount = 1;
	size_t soap_flag_Flag = 1;
	size_t soap_flag_Sign = 1;
	if (soap_element_begin_in(soap, tag, 0, type))
		return NULL;
	a = (struct ns1__ReturnRecord *)soap_id_enter(soap, soap->id, a, SOAP_TYPE_ns1__ReturnRecord, sizeof(struct ns1__ReturnRecord), 0, NULL, NULL, NULL);
	if (!a)
		return NULL;
	soap_default_ns1__ReturnRecord(soap, a);
	if (soap->body && !*soap->href)
	{
		for (;;)
		{	soap->error = SOAP_TAG_MISMATCH;
			if (soap_flag_ProjectId && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
				if (soap_in_string(soap, "ns1:ProjectId", &a->ProjectId, "xsd:string"))
				{	soap_flag_ProjectId--;
					continue;
				}
			if (soap_flag_BatchId && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
				if (soap_in_string(soap, "ns1:BatchId", &a->BatchId, "xsd:string"))
				{	soap_flag_BatchId--;
					continue;
				}
			if (soap_flag_BatchName && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
				if (soap_in_string(soap, "ns1:BatchName", &a->BatchName, "xsd:string"))
				{	soap_flag_BatchName--;
					continue;
				}
			if (soap_flag_Cr_USCORECode && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
				if (soap_in_string(soap, "ns1:Cr_Code", &a->Cr_USCORECode, "xsd:string"))
				{	soap_flag_Cr_USCORECode--;
					continue;
				}
			if (soap_flag_Amounts && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_LONG64(soap, "ns1:Amounts", &a->Amounts, "xsd:long"))
				{	soap_flag_Amounts--;
					continue;
				}
			if (soap_flag_PayAmount && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_LONG64(soap, "ns1:PayAmount", &a->PayAmount, "xsd:long"))
				{	soap_flag_PayAmount--;
					continue;
				}
			if (soap_flag_ReceiveAmount && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_LONG64(soap, "ns1:ReceiveAmount", &a->ReceiveAmount, "xsd:long"))
				{	soap_flag_ReceiveAmount--;
					continue;
				}
			if (soap_flag_Flag && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
				if (soap_in_string(soap, "ns1:Flag", &a->Flag, "xsd:string"))
				{	soap_flag_Flag--;
					continue;
				}
			if (soap_flag_Sign && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
				if (soap_in_string(soap, "ns1:Sign", &a->Sign, "xsd:string"))
				{	soap_flag_Sign--;
					continue;
				}
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
				return NULL;
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
	}
	else
	{	a = (struct ns1__ReturnRecord *)soap_id_forward(soap, soap->href, (void*)a, 0, SOAP_TYPE_ns1__ReturnRecord, 0, sizeof(struct ns1__ReturnRecord), 0, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	if ((soap->mode & SOAP_XML_STRICT) && (soap_flag_Amounts > 0 || soap_flag_PayAmount > 0 || soap_flag_ReceiveAmount > 0))
	{	soap->error = SOAP_OCCURS;
		return NULL;
	}
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__ReturnRecord(struct soap *soap, const struct ns1__ReturnRecord *a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_ns1__ReturnRecord);
	if (soap_out_ns1__ReturnRecord(soap, tag?tag:"ns1:ReturnRecord", id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 struct ns1__ReturnRecord * SOAP_FMAC4 soap_get_ns1__ReturnRecord(struct soap *soap, struct ns1__ReturnRecord *p, const char *tag, const char *type)
{
	if ((p = soap_in_ns1__ReturnRecord(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__ArrayOfReturnRecordSub(struct soap *soap, struct ns1__ArrayOfReturnRecordSub *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	a->__sizeReturnRecordSub = 0;
	a->ReturnRecordSub = NULL;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__ArrayOfReturnRecordSub(struct soap *soap, const struct ns1__ArrayOfReturnRecordSub *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	if (a->ReturnRecordSub)
	{	int i;
		for (i = 0; i < a->__sizeReturnRecordSub; i++)
		{
			soap_embedded(soap, a->ReturnRecordSub + i, SOAP_TYPE_ns1__ReturnRecordSub);
			soap_serialize_ns1__ReturnRecordSub(soap, a->ReturnRecordSub + i);
		}
	}
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ArrayOfReturnRecordSub(struct soap *soap, const char *tag, int id, const struct ns1__ArrayOfReturnRecordSub *a, const char *type)
{
	if (soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_ns1__ArrayOfReturnRecordSub), type))
		return soap->error;
	if (a->ReturnRecordSub)
	{	int i;
		for (i = 0; i < a->__sizeReturnRecordSub; i++)
			if (soap_out_ns1__ReturnRecordSub(soap, "ns1:ReturnRecordSub", -1, a->ReturnRecordSub + i, ""))
				return soap->error;
	}
	return soap_element_end_out(soap, tag);
}

SOAP_FMAC3 struct ns1__ArrayOfReturnRecordSub * SOAP_FMAC4 soap_in_ns1__ArrayOfReturnRecordSub(struct soap *soap, const char *tag, struct ns1__ArrayOfReturnRecordSub *a, const char *type)
{
	struct soap_blist *soap_blist_ReturnRecordSub = NULL;
	if (soap_element_begin_in(soap, tag, 0, type))
		return NULL;
	a = (struct ns1__ArrayOfReturnRecordSub *)soap_id_enter(soap, soap->id, a, SOAP_TYPE_ns1__ArrayOfReturnRecordSub, sizeof(struct ns1__ArrayOfReturnRecordSub), 0, NULL, NULL, NULL);
	if (!a)
		return NULL;
	soap_default_ns1__ArrayOfReturnRecordSub(soap, a);
	if (soap->body && !*soap->href)
	{
		for (;;)
		{	soap->error = SOAP_TAG_MISMATCH;
			if (soap->error == SOAP_TAG_MISMATCH && !soap_element_begin_in(soap, "ns1:ReturnRecordSub", 1, NULL))
			{	if (a->ReturnRecordSub == NULL)
				{	if (soap_blist_ReturnRecordSub == NULL)
						soap_blist_ReturnRecordSub = soap_new_block(soap);
					a->ReturnRecordSub = (struct ns1__ReturnRecordSub *)soap_push_block(soap, soap_blist_ReturnRecordSub, sizeof(struct ns1__ReturnRecordSub));
					if (a->ReturnRecordSub == NULL)
						return NULL;
					soap_default_ns1__ReturnRecordSub(soap, a->ReturnRecordSub);
				}
				soap_revert(soap);
				if (soap_in_ns1__ReturnRecordSub(soap, "ns1:ReturnRecordSub", a->ReturnRecordSub, "ns1:ReturnRecordSub"))
				{	a->__sizeReturnRecordSub++;
					a->ReturnRecordSub = NULL;
					continue;
				}
			}
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
				return NULL;
		}
		if (a->ReturnRecordSub)
			soap_pop_block(soap, soap_blist_ReturnRecordSub);
		if (a->__sizeReturnRecordSub)
			a->ReturnRecordSub = (struct ns1__ReturnRecordSub *)soap_save_block(soap, soap_blist_ReturnRecordSub, NULL, 1);
		else
		{	a->ReturnRecordSub = NULL;
			if (soap_blist_ReturnRecordSub)
				soap_end_block(soap, soap_blist_ReturnRecordSub);
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
	}
	else
	{	a = (struct ns1__ArrayOfReturnRecordSub *)soap_id_forward(soap, soap->href, (void*)a, 0, SOAP_TYPE_ns1__ArrayOfReturnRecordSub, 0, sizeof(struct ns1__ArrayOfReturnRecordSub), 0, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__ArrayOfReturnRecordSub(struct soap *soap, const struct ns1__ArrayOfReturnRecordSub *a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_ns1__ArrayOfReturnRecordSub);
	if (soap_out_ns1__ArrayOfReturnRecordSub(soap, tag?tag:"ns1:ArrayOfReturnRecordSub", id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 struct ns1__ArrayOfReturnRecordSub * SOAP_FMAC4 soap_get_ns1__ArrayOfReturnRecordSub(struct soap *soap, struct ns1__ArrayOfReturnRecordSub *p, const char *tag, const char *type)
{
	if ((p = soap_in_ns1__ArrayOfReturnRecordSub(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__ArrayOfReturnRecord(struct soap *soap, struct ns1__ArrayOfReturnRecord *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	a->__sizeReturnRecord = 0;
	a->ReturnRecord = NULL;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__ArrayOfReturnRecord(struct soap *soap, const struct ns1__ArrayOfReturnRecord *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	if (a->ReturnRecord)
	{	int i;
		for (i = 0; i < a->__sizeReturnRecord; i++)
		{
			soap_embedded(soap, a->ReturnRecord + i, SOAP_TYPE_ns1__ReturnRecord);
			soap_serialize_ns1__ReturnRecord(soap, a->ReturnRecord + i);
		}
	}
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ArrayOfReturnRecord(struct soap *soap, const char *tag, int id, const struct ns1__ArrayOfReturnRecord *a, const char *type)
{
	if (soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_ns1__ArrayOfReturnRecord), type))
		return soap->error;
	if (a->ReturnRecord)
	{	int i;
		for (i = 0; i < a->__sizeReturnRecord; i++)
			if (soap_out_ns1__ReturnRecord(soap, "ns1:ReturnRecord", -1, a->ReturnRecord + i, ""))
				return soap->error;
	}
	return soap_element_end_out(soap, tag);
}

SOAP_FMAC3 struct ns1__ArrayOfReturnRecord * SOAP_FMAC4 soap_in_ns1__ArrayOfReturnRecord(struct soap *soap, const char *tag, struct ns1__ArrayOfReturnRecord *a, const char *type)
{
	struct soap_blist *soap_blist_ReturnRecord = NULL;
	if (soap_element_begin_in(soap, tag, 0, type))
		return NULL;
	a = (struct ns1__ArrayOfReturnRecord *)soap_id_enter(soap, soap->id, a, SOAP_TYPE_ns1__ArrayOfReturnRecord, sizeof(struct ns1__ArrayOfReturnRecord), 0, NULL, NULL, NULL);
	if (!a)
		return NULL;
	soap_default_ns1__ArrayOfReturnRecord(soap, a);
	if (soap->body && !*soap->href)
	{
		for (;;)
		{	soap->error = SOAP_TAG_MISMATCH;
			if (soap->error == SOAP_TAG_MISMATCH && !soap_element_begin_in(soap, "ns1:ReturnRecord", 1, NULL))
			{	if (a->ReturnRecord == NULL)
				{	if (soap_blist_ReturnRecord == NULL)
						soap_blist_ReturnRecord = soap_new_block(soap);
					a->ReturnRecord = (struct ns1__ReturnRecord *)soap_push_block(soap, soap_blist_ReturnRecord, sizeof(struct ns1__ReturnRecord));
					if (a->ReturnRecord == NULL)
						return NULL;
					soap_default_ns1__ReturnRecord(soap, a->ReturnRecord);
				}
				soap_revert(soap);
				if (soap_in_ns1__ReturnRecord(soap, "ns1:ReturnRecord", a->ReturnRecord, "ns1:ReturnRecord"))
				{	a->__sizeReturnRecord++;
					a->ReturnRecord = NULL;
					continue;
				}
			}
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
				return NULL;
		}
		if (a->ReturnRecord)
			soap_pop_block(soap, soap_blist_ReturnRecord);
		if (a->__sizeReturnRecord)
			a->ReturnRecord = (struct ns1__ReturnRecord *)soap_save_block(soap, soap_blist_ReturnRecord, NULL, 1);
		else
		{	a->ReturnRecord = NULL;
			if (soap_blist_ReturnRecord)
				soap_end_block(soap, soap_blist_ReturnRecord);
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
	}
	else
	{	a = (struct ns1__ArrayOfReturnRecord *)soap_id_forward(soap, soap->href, (void*)a, 0, SOAP_TYPE_ns1__ArrayOfReturnRecord, 0, sizeof(struct ns1__ArrayOfReturnRecord), 0, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__ArrayOfReturnRecord(struct soap *soap, const struct ns1__ArrayOfReturnRecord *a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_ns1__ArrayOfReturnRecord);
	if (soap_out_ns1__ArrayOfReturnRecord(soap, tag?tag:"ns1:ArrayOfReturnRecord", id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 struct ns1__ArrayOfReturnRecord * SOAP_FMAC4 soap_get_ns1__ArrayOfReturnRecord(struct soap *soap, struct ns1__ArrayOfReturnRecord *p, const char *tag, const char *type)
{
	if ((p = soap_in_ns1__ArrayOfReturnRecord(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__DetailMsg(struct soap *soap, struct ns1__DetailMsg *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	soap_default_int(soap, &a->Count);
	soap_default_string(soap, &a->ErrCode);
	a->ReturnRecords = NULL;
	a->ReturnRecordSubs = NULL;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__DetailMsg(struct soap *soap, const struct ns1__DetailMsg *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	soap_serialize_string(soap, &a->ErrCode);
	soap_serialize_PointerTons1__ArrayOfReturnRecord(soap, &a->ReturnRecords);
	soap_serialize_PointerTons1__ArrayOfReturnRecordSub(soap, &a->ReturnRecordSubs);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__DetailMsg(struct soap *soap, const char *tag, int id, const struct ns1__DetailMsg *a, const char *type)
{
	if (soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_ns1__DetailMsg), type))
		return soap->error;
	if (soap_out_int(soap, "ns1:Count", -1, &a->Count, ""))
		return soap->error;
	if (soap_out_string(soap, "ns1:ErrCode", -1, &a->ErrCode, ""))
		return soap->error;
	if (soap_out_PointerTons1__ArrayOfReturnRecord(soap, "ns1:ReturnRecords", -1, &a->ReturnRecords, ""))
		return soap->error;
	if (soap_out_PointerTons1__ArrayOfReturnRecordSub(soap, "ns1:ReturnRecordSubs", -1, &a->ReturnRecordSubs, ""))
		return soap->error;
	return soap_element_end_out(soap, tag);
}

SOAP_FMAC3 struct ns1__DetailMsg * SOAP_FMAC4 soap_in_ns1__DetailMsg(struct soap *soap, const char *tag, struct ns1__DetailMsg *a, const char *type)
{
	size_t soap_flag_Count = 1;
	size_t soap_flag_ErrCode = 1;
	size_t soap_flag_ReturnRecords = 1;
	size_t soap_flag_ReturnRecordSubs = 1;
	if (soap_element_begin_in(soap, tag, 0, type))
		return NULL;
	a = (struct ns1__DetailMsg *)soap_id_enter(soap, soap->id, a, SOAP_TYPE_ns1__DetailMsg, sizeof(struct ns1__DetailMsg), 0, NULL, NULL, NULL);
	if (!a)
		return NULL;
	soap_default_ns1__DetailMsg(soap, a);
	if (soap->body && !*soap->href)
	{
		for (;;)
		{	soap->error = SOAP_TAG_MISMATCH;
			if (soap_flag_Count && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_int(soap, "ns1:Count", &a->Count, "xsd:int"))
				{	soap_flag_Count--;
					continue;
				}
			if (soap_flag_ErrCode && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
				if (soap_in_string(soap, "ns1:ErrCode", &a->ErrCode, "xsd:string"))
				{	soap_flag_ErrCode--;
					continue;
				}
			if (soap_flag_ReturnRecords && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_PointerTons1__ArrayOfReturnRecord(soap, "ns1:ReturnRecords", &a->ReturnRecords, "ns1:ArrayOfReturnRecord"))
				{	soap_flag_ReturnRecords--;
					continue;
				}
			if (soap_flag_ReturnRecordSubs && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_PointerTons1__ArrayOfReturnRecordSub(soap, "ns1:ReturnRecordSubs", &a->ReturnRecordSubs, "ns1:ArrayOfReturnRecordSub"))
				{	soap_flag_ReturnRecordSubs--;
					continue;
				}
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
				return NULL;
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
	}
	else
	{	a = (struct ns1__DetailMsg *)soap_id_forward(soap, soap->href, (void*)a, 0, SOAP_TYPE_ns1__DetailMsg, 0, sizeof(struct ns1__DetailMsg), 0, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	if ((soap->mode & SOAP_XML_STRICT) && (soap_flag_Count > 0))
	{	soap->error = SOAP_OCCURS;
		return NULL;
	}
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__DetailMsg(struct soap *soap, const struct ns1__DetailMsg *a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_ns1__DetailMsg);
	if (soap_out_ns1__DetailMsg(soap, tag?tag:"ns1:DetailMsg", id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 struct ns1__DetailMsg * SOAP_FMAC4 soap_get_ns1__DetailMsg(struct soap *soap, struct ns1__DetailMsg *p, const char *tag, const char *type)
{
	if ((p = soap_in_ns1__DetailMsg(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

#ifndef WITH_NOGLOBAL

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap *soap, struct SOAP_ENV__Reason *const*a)
{
	if (!soap_reference(soap, *a, SOAP_TYPE_SOAP_ENV__Reason))
		soap_serialize_SOAP_ENV__Reason(soap, *a);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap *soap, const char *tag, int id, struct SOAP_ENV__Reason *const*a, const char *type)
{
	id = soap_element_id(soap, tag, id, *a, NULL, 0, type, SOAP_TYPE_SOAP_ENV__Reason);
	if (id < 0)
		return soap->error;
	return soap_out_SOAP_ENV__Reason(soap, tag, id, *a, type);
}

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap *soap, const char *tag, struct SOAP_ENV__Reason **a, const char *type)
{
	if (soap_element_begin_in(soap, tag, 1, NULL))
		return NULL;
	if (!a)
		if (!(a = (struct SOAP_ENV__Reason **)soap_malloc(soap, sizeof(struct SOAP_ENV__Reason *))))
			return NULL;
	*a = NULL;
	if (!soap->null && *soap->href != '#')
	{	soap_revert(soap);
		if (!(*a = soap_in_SOAP_ENV__Reason(soap, tag, *a, type)))
			return NULL;
	}
	else
	{	a = (struct SOAP_ENV__Reason **)soap_id_lookup(soap, soap->href, (void**)a, SOAP_TYPE_SOAP_ENV__Reason, sizeof(struct SOAP_ENV__Reason), 0);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap *soap, struct SOAP_ENV__Reason *const*a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_PointerToSOAP_ENV__Reason);
	if (soap_out_PointerToSOAP_ENV__Reason(soap, tag?tag:"SOAP-ENV:Reason", id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap *soap, struct SOAP_ENV__Reason **p, const char *tag, const char *type)
{
	if ((p = soap_in_PointerToSOAP_ENV__Reason(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

#endif

#ifndef WITH_NOGLOBAL

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap *soap, struct SOAP_ENV__Detail *const*a)
{
	if (!soap_reference(soap, *a, SOAP_TYPE_SOAP_ENV__Detail))
		soap_serialize_SOAP_ENV__Detail(soap, *a);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap *soap, const char *tag, int id, struct SOAP_ENV__Detail *const*a, const char *type)
{
	id = soap_element_id(soap, tag, id, *a, NULL, 0, type, SOAP_TYPE_SOAP_ENV__Detail);
	if (id < 0)
		return soap->error;
	return soap_out_SOAP_ENV__Detail(soap, tag, id, *a, type);
}

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap *soap, const char *tag, struct SOAP_ENV__Detail **a, const char *type)
{
	if (soap_element_begin_in(soap, tag, 1, NULL))
		return NULL;
	if (!a)
		if (!(a = (struct SOAP_ENV__Detail **)soap_malloc(soap, sizeof(struct SOAP_ENV__Detail *))))
			return NULL;
	*a = NULL;
	if (!soap->null && *soap->href != '#')
	{	soap_revert(soap);
		if (!(*a = soap_in_SOAP_ENV__Detail(soap, tag, *a, type)))
			return NULL;
	}
	else
	{	a = (struct SOAP_ENV__Detail **)soap_id_lookup(soap, soap->href, (void**)a, SOAP_TYPE_SOAP_ENV__Detail, sizeof(struct SOAP_ENV__Detail), 0);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap *soap, struct SOAP_ENV__Detail *const*a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_PointerToSOAP_ENV__Detail);
	if (soap_out_PointerToSOAP_ENV__Detail(soap, tag?tag:"SOAP-ENV:Detail", id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap *soap, struct SOAP_ENV__Detail **p, const char *tag, const char *type)
{
	if ((p = soap_in_PointerToSOAP_ENV__Detail(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

#endif

#ifndef WITH_NOGLOBAL

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap *soap, struct SOAP_ENV__Code *const*a)
{
	if (!soap_reference(soap, *a, SOAP_TYPE_SOAP_ENV__Code))
		soap_serialize_SOAP_ENV__Code(soap, *a);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap *soap, const char *tag, int id, struct SOAP_ENV__Code *const*a, const char *type)
{
	id = soap_element_id(soap, tag, id, *a, NULL, 0, type, SOAP_TYPE_SOAP_ENV__Code);
	if (id < 0)
		return soap->error;
	return soap_out_SOAP_ENV__Code(soap, tag, id, *a, type);
}

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap *soap, const char *tag, struct SOAP_ENV__Code **a, const char *type)
{
	if (soap_element_begin_in(soap, tag, 1, NULL))
		return NULL;
	if (!a)
		if (!(a = (struct SOAP_ENV__Code **)soap_malloc(soap, sizeof(struct SOAP_ENV__Code *))))
			return NULL;
	*a = NULL;
	if (!soap->null && *soap->href != '#')
	{	soap_revert(soap);
		if (!(*a = soap_in_SOAP_ENV__Code(soap, tag, *a, type)))
			return NULL;
	}
	else
	{	a = (struct SOAP_ENV__Code **)soap_id_lookup(soap, soap->href, (void**)a, SOAP_TYPE_SOAP_ENV__Code, sizeof(struct SOAP_ENV__Code), 0);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap *soap, struct SOAP_ENV__Code *const*a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_PointerToSOAP_ENV__Code);
	if (soap_out_PointerToSOAP_ENV__Code(soap, tag?tag:"SOAP-ENV:Code", id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap *soap, struct SOAP_ENV__Code **p, const char *tag, const char *type)
{
	if ((p = soap_in_PointerToSOAP_ENV__Code(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

#endif

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__BatchInResponse(struct soap *soap, struct _ns1__BatchInResponse *const*a)
{
	if (!soap_reference(soap, *a, SOAP_TYPE__ns1__BatchInResponse))
		soap_serialize__ns1__BatchInResponse(soap, *a);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__BatchInResponse(struct soap *soap, const char *tag, int id, struct _ns1__BatchInResponse *const*a, const char *type)
{
	id = soap_element_id(soap, tag, id, *a, NULL, 0, type, SOAP_TYPE__ns1__BatchInResponse);
	if (id < 0)
		return soap->error;
	return soap_out__ns1__BatchInResponse(soap, tag, id, *a, type);
}

SOAP_FMAC3 struct _ns1__BatchInResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__BatchInResponse(struct soap *soap, const char *tag, struct _ns1__BatchInResponse **a, const char *type)
{
	if (soap_element_begin_in(soap, tag, 1, NULL))
		return NULL;
	if (!a)
		if (!(a = (struct _ns1__BatchInResponse **)soap_malloc(soap, sizeof(struct _ns1__BatchInResponse *))))
			return NULL;
	*a = NULL;
	if (!soap->null && *soap->href != '#')
	{	soap_revert(soap);
		if (!(*a = soap_in__ns1__BatchInResponse(soap, tag, *a, type)))
			return NULL;
	}
	else
	{	a = (struct _ns1__BatchInResponse **)soap_id_lookup(soap, soap->href, (void**)a, SOAP_TYPE__ns1__BatchInResponse, sizeof(struct _ns1__BatchInResponse), 0);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__BatchInResponse(struct soap *soap, struct _ns1__BatchInResponse *const*a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_PointerTo_ns1__BatchInResponse);
	if (soap_out_PointerTo_ns1__BatchInResponse(soap, tag?tag:"ns1:BatchInResponse", id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 struct _ns1__BatchInResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__BatchInResponse(struct soap *soap, struct _ns1__BatchInResponse **p, const char *tag, const char *type)
{
	if ((p = soap_in_PointerTo_ns1__BatchInResponse(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__BatchIn(struct soap *soap, struct _ns1__BatchIn *const*a)
{
	if (!soap_reference(soap, *a, SOAP_TYPE__ns1__BatchIn))
		soap_serialize__ns1__BatchIn(soap, *a);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__BatchIn(struct soap *soap, const char *tag, int id, struct _ns1__BatchIn *const*a, const char *type)
{
	id = soap_element_id(soap, tag, id, *a, NULL, 0, type, SOAP_TYPE__ns1__BatchIn);
	if (id < 0)
		return soap->error;
	return soap_out__ns1__BatchIn(soap, tag, id, *a, type);
}

SOAP_FMAC3 struct _ns1__BatchIn ** SOAP_FMAC4 soap_in_PointerTo_ns1__BatchIn(struct soap *soap, const char *tag, struct _ns1__BatchIn **a, const char *type)
{
	if (soap_element_begin_in(soap, tag, 1, NULL))
		return NULL;
	if (!a)
		if (!(a = (struct _ns1__BatchIn **)soap_malloc(soap, sizeof(struct _ns1__BatchIn *))))
			return NULL;
	*a = NULL;
	if (!soap->null && *soap->href != '#')
	{	soap_revert(soap);
		if (!(*a = soap_in__ns1__BatchIn(soap, tag, *a, type)))
			return NULL;
	}
	else
	{	a = (struct _ns1__BatchIn **)soap_id_lookup(soap, soap->href, (void**)a, SOAP_TYPE__ns1__BatchIn, sizeof(struct _ns1__BatchIn), 0);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__BatchIn(struct soap *soap, struct _ns1__BatchIn *const*a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_PointerTo_ns1__BatchIn);
	if (soap_out_PointerTo_ns1__BatchIn(soap, tag?tag:"ns1:BatchIn", id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 struct _ns1__BatchIn ** SOAP_FMAC4 soap_get_PointerTo_ns1__BatchIn(struct soap *soap, struct _ns1__BatchIn **p, const char *tag, const char *type)
{
	if ((p = soap_in_PointerTo_ns1__BatchIn(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__DetailMsg(struct soap *soap, struct ns1__DetailMsg *const*a)
{
	if (!soap_reference(soap, *a, SOAP_TYPE_ns1__DetailMsg))
		soap_serialize_ns1__DetailMsg(soap, *a);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__DetailMsg(struct soap *soap, const char *tag, int id, struct ns1__DetailMsg *const*a, const char *type)
{
	id = soap_element_id(soap, tag, id, *a, NULL, 0, type, SOAP_TYPE_ns1__DetailMsg);
	if (id < 0)
		return soap->error;
	return soap_out_ns1__DetailMsg(soap, tag, id, *a, type);
}

SOAP_FMAC3 struct ns1__DetailMsg ** SOAP_FMAC4 soap_in_PointerTons1__DetailMsg(struct soap *soap, const char *tag, struct ns1__DetailMsg **a, const char *type)
{
	if (soap_element_begin_in(soap, tag, 1, NULL))
		return NULL;
	if (!a)
		if (!(a = (struct ns1__DetailMsg **)soap_malloc(soap, sizeof(struct ns1__DetailMsg *))))
			return NULL;
	*a = NULL;
	if (!soap->null && *soap->href != '#')
	{	soap_revert(soap);
		if (!(*a = soap_in_ns1__DetailMsg(soap, tag, *a, type)))
			return NULL;
	}
	else
	{	a = (struct ns1__DetailMsg **)soap_id_lookup(soap, soap->href, (void**)a, SOAP_TYPE_ns1__DetailMsg, sizeof(struct ns1__DetailMsg), 0);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__DetailMsg(struct soap *soap, struct ns1__DetailMsg *const*a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_PointerTons1__DetailMsg);
	if (soap_out_PointerTons1__DetailMsg(soap, tag?tag:"ns1:DetailMsg", id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 struct ns1__DetailMsg ** SOAP_FMAC4 soap_get_PointerTons1__DetailMsg(struct soap *soap, struct ns1__DetailMsg **p, const char *tag, const char *type)
{
	if ((p = soap_in_PointerTons1__DetailMsg(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ReturnRecordSub(struct soap *soap, struct ns1__ReturnRecordSub *const*a)
{
	if (!soap_reference(soap, *a, SOAP_TYPE_ns1__ReturnRecordSub))
		soap_serialize_ns1__ReturnRecordSub(soap, *a);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ReturnRecordSub(struct soap *soap, const char *tag, int id, struct ns1__ReturnRecordSub *const*a, const char *type)
{
	id = soap_element_id(soap, tag, id, *a, NULL, 0, type, SOAP_TYPE_ns1__ReturnRecordSub);
	if (id < 0)
		return soap->error;
	return soap_out_ns1__ReturnRecordSub(soap, tag, id, *a, type);
}

SOAP_FMAC3 struct ns1__ReturnRecordSub ** SOAP_FMAC4 soap_in_PointerTons1__ReturnRecordSub(struct soap *soap, const char *tag, struct ns1__ReturnRecordSub **a, const char *type)
{
	if (soap_element_begin_in(soap, tag, 1, NULL))
		return NULL;
	if (!a)
		if (!(a = (struct ns1__ReturnRecordSub **)soap_malloc(soap, sizeof(struct ns1__ReturnRecordSub *))))
			return NULL;
	*a = NULL;
	if (!soap->null && *soap->href != '#')
	{	soap_revert(soap);
		if (!(*a = soap_in_ns1__ReturnRecordSub(soap, tag, *a, type)))
			return NULL;
	}
	else
	{	a = (struct ns1__ReturnRecordSub **)soap_id_lookup(soap, soap->href, (void**)a, SOAP_TYPE_ns1__ReturnRecordSub, sizeof(struct ns1__ReturnRecordSub), 0);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ReturnRecordSub(struct soap *soap, struct ns1__ReturnRecordSub *const*a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_PointerTons1__ReturnRecordSub);
	if (soap_out_PointerTons1__ReturnRecordSub(soap, tag?tag:"ns1:ReturnRecordSub", id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 struct ns1__ReturnRecordSub ** SOAP_FMAC4 soap_get_PointerTons1__ReturnRecordSub(struct soap *soap, struct ns1__ReturnRecordSub **p, const char *tag, const char *type)
{
	if ((p = soap_in_PointerTons1__ReturnRecordSub(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ReturnRecord(struct soap *soap, struct ns1__ReturnRecord *const*a)
{
	if (!soap_reference(soap, *a, SOAP_TYPE_ns1__ReturnRecord))
		soap_serialize_ns1__ReturnRecord(soap, *a);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ReturnRecord(struct soap *soap, const char *tag, int id, struct ns1__ReturnRecord *const*a, const char *type)
{
	id = soap_element_id(soap, tag, id, *a, NULL, 0, type, SOAP_TYPE_ns1__ReturnRecord);
	if (id < 0)
		return soap->error;
	return soap_out_ns1__ReturnRecord(soap, tag, id, *a, type);
}

SOAP_FMAC3 struct ns1__ReturnRecord ** SOAP_FMAC4 soap_in_PointerTons1__ReturnRecord(struct soap *soap, const char *tag, struct ns1__ReturnRecord **a, const char *type)
{
	if (soap_element_begin_in(soap, tag, 1, NULL))
		return NULL;
	if (!a)
		if (!(a = (struct ns1__ReturnRecord **)soap_malloc(soap, sizeof(struct ns1__ReturnRecord *))))
			return NULL;
	*a = NULL;
	if (!soap->null && *soap->href != '#')
	{	soap_revert(soap);
		if (!(*a = soap_in_ns1__ReturnRecord(soap, tag, *a, type)))
			return NULL;
	}
	else
	{	a = (struct ns1__ReturnRecord **)soap_id_lookup(soap, soap->href, (void**)a, SOAP_TYPE_ns1__ReturnRecord, sizeof(struct ns1__ReturnRecord), 0);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ReturnRecord(struct soap *soap, struct ns1__ReturnRecord *const*a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_PointerTons1__ReturnRecord);
	if (soap_out_PointerTons1__ReturnRecord(soap, tag?tag:"ns1:ReturnRecord", id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 struct ns1__ReturnRecord ** SOAP_FMAC4 soap_get_PointerTons1__ReturnRecord(struct soap *soap, struct ns1__ReturnRecord **p, const char *tag, const char *type)
{
	if ((p = soap_in_PointerTons1__ReturnRecord(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ArrayOfReturnRecordSub(struct soap *soap, struct ns1__ArrayOfReturnRecordSub *const*a)
{
	if (!soap_reference(soap, *a, SOAP_TYPE_ns1__ArrayOfReturnRecordSub))
		soap_serialize_ns1__ArrayOfReturnRecordSub(soap, *a);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ArrayOfReturnRecordSub(struct soap *soap, const char *tag, int id, struct ns1__ArrayOfReturnRecordSub *const*a, const char *type)
{
	id = soap_element_id(soap, tag, id, *a, NULL, 0, type, SOAP_TYPE_ns1__ArrayOfReturnRecordSub);
	if (id < 0)
		return soap->error;
	return soap_out_ns1__ArrayOfReturnRecordSub(soap, tag, id, *a, type);
}

SOAP_FMAC3 struct ns1__ArrayOfReturnRecordSub ** SOAP_FMAC4 soap_in_PointerTons1__ArrayOfReturnRecordSub(struct soap *soap, const char *tag, struct ns1__ArrayOfReturnRecordSub **a, const char *type)
{
	if (soap_element_begin_in(soap, tag, 1, NULL))
		return NULL;
	if (!a)
		if (!(a = (struct ns1__ArrayOfReturnRecordSub **)soap_malloc(soap, sizeof(struct ns1__ArrayOfReturnRecordSub *))))
			return NULL;
	*a = NULL;
	if (!soap->null && *soap->href != '#')
	{	soap_revert(soap);
		if (!(*a = soap_in_ns1__ArrayOfReturnRecordSub(soap, tag, *a, type)))
			return NULL;
	}
	else
	{	a = (struct ns1__ArrayOfReturnRecordSub **)soap_id_lookup(soap, soap->href, (void**)a, SOAP_TYPE_ns1__ArrayOfReturnRecordSub, sizeof(struct ns1__ArrayOfReturnRecordSub), 0);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ArrayOfReturnRecordSub(struct soap *soap, struct ns1__ArrayOfReturnRecordSub *const*a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_PointerTons1__ArrayOfReturnRecordSub);
	if (soap_out_PointerTons1__ArrayOfReturnRecordSub(soap, tag?tag:"ns1:ArrayOfReturnRecordSub", id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 struct ns1__ArrayOfReturnRecordSub ** SOAP_FMAC4 soap_get_PointerTons1__ArrayOfReturnRecordSub(struct soap *soap, struct ns1__ArrayOfReturnRecordSub **p, const char *tag, const char *type)
{
	if ((p = soap_in_PointerTons1__ArrayOfReturnRecordSub(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ArrayOfReturnRecord(struct soap *soap, struct ns1__ArrayOfReturnRecord *const*a)
{
	if (!soap_reference(soap, *a, SOAP_TYPE_ns1__ArrayOfReturnRecord))
		soap_serialize_ns1__ArrayOfReturnRecord(soap, *a);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ArrayOfReturnRecord(struct soap *soap, const char *tag, int id, struct ns1__ArrayOfReturnRecord *const*a, const char *type)
{
	id = soap_element_id(soap, tag, id, *a, NULL, 0, type, SOAP_TYPE_ns1__ArrayOfReturnRecord);
	if (id < 0)
		return soap->error;
	return soap_out_ns1__ArrayOfReturnRecord(soap, tag, id, *a, type);
}

SOAP_FMAC3 struct ns1__ArrayOfReturnRecord ** SOAP_FMAC4 soap_in_PointerTons1__ArrayOfReturnRecord(struct soap *soap, const char *tag, struct ns1__ArrayOfReturnRecord **a, const char *type)
{
	if (soap_element_begin_in(soap, tag, 1, NULL))
		return NULL;
	if (!a)
		if (!(a = (struct ns1__ArrayOfReturnRecord **)soap_malloc(soap, sizeof(struct ns1__ArrayOfReturnRecord *))))
			return NULL;
	*a = NULL;
	if (!soap->null && *soap->href != '#')
	{	soap_revert(soap);
		if (!(*a = soap_in_ns1__ArrayOfReturnRecord(soap, tag, *a, type)))
			return NULL;
	}
	else
	{	a = (struct ns1__ArrayOfReturnRecord **)soap_id_lookup(soap, soap->href, (void**)a, SOAP_TYPE_ns1__ArrayOfReturnRecord, sizeof(struct ns1__ArrayOfReturnRecord), 0);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ArrayOfReturnRecord(struct soap *soap, struct ns1__ArrayOfReturnRecord *const*a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_PointerTons1__ArrayOfReturnRecord);
	if (soap_out_PointerTons1__ArrayOfReturnRecord(soap, tag?tag:"ns1:ArrayOfReturnRecord", id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 struct ns1__ArrayOfReturnRecord ** SOAP_FMAC4 soap_get_PointerTons1__ArrayOfReturnRecord(struct soap *soap, struct ns1__ArrayOfReturnRecord **p, const char *tag, const char *type)
{
	if ((p = soap_in_PointerTons1__ArrayOfReturnRecord(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap *soap, const char *tag, int id, char *const*a, const char *type)
{
	return soap_outstring(soap, tag, id, a, type, SOAP_TYPE__QName);
}

SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap *soap, const char *tag, char **a, const char *type)
{	char **p;
	p = soap_instring(soap, tag, a, type, SOAP_TYPE__QName, 2, -1, -1);
	return p;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap *soap, char *const*a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE__QName);
	if (soap_out__QName(soap, tag?tag:"byte", id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap *soap, char **p, const char *tag, const char *type)
{
	if ((p = soap_in__QName(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap *soap, char **a)
{
	(void)soap; /* appease -Wall -Werror */
#ifdef SOAP_DEFAULT_string
	*a = SOAP_DEFAULT_string;
#else
	*a = (char *)0;
#endif
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap *soap, char *const*a)
{
	soap_reference(soap, *a, SOAP_TYPE_string);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap *soap, const char *tag, int id, char *const*a, const char *type)
{
	return soap_outstring(soap, tag, id, a, type, SOAP_TYPE_string);
}

SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap *soap, const char *tag, char **a, const char *type)
{	char **p;
	p = soap_instring(soap, tag, a, type, SOAP_TYPE_string, 1, -1, -1);
	return p;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap *soap, char *const*a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_string);
	if (soap_out_string(soap, tag?tag:"byte", id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap *soap, char **p, const char *tag, const char *type)
{
	if ((p = soap_in_string(soap, tag, p, type)))
		if (soap_getindependent(soap))
			return NULL;
	return p;
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapC.c */
