ALTER TABLE MMM_TXN_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMM_TXN_TYPE CASCADE CONSTRAINTS;

CREATE TABLE MMM_TXN_TYPE
(
  MTT_TYPE             CHAR(6 BYTE),
  MTT_DESC             VARCHAR2(50 BYTE),
  MTT_CREATE_DATETIME  DATE                     DEFAULT sysdate,
  MTT_CREATE_USER      VARCHAR2(20 BYTE),
  MTT_UPDATE_DATETIME  DATE                     DEFAULT sysdate,
  MTT_UPDATE_USER      VARCHAR2(1 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MMM_TXN_TYPE_PK ON MMM_TXN_TYPE
(MTT_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMM_TXN_TYPE ADD (
  CONSTRAINT MMM_TXN_TYPE_PK
  PRIMARY KEY
  (MTT_TYPE)
  USING INDEX MMM_TXN_TYPE_PK
  ENABLE VALIDATE);

