ALTER TABLE COUNTRY_SERVICE_MAP
 DROP PRIMARY KEY CASCADE;

DROP TABLE COUNTRY_SERVICE_MAP CASCADE CONSTRAINTS;

CREATE TABLE COUNTRY_SERVICE_MAP
(
  CS_COUNTRY           CHAR(2 BYTE),
  CS_SERVICE_CODE      CHAR(3 BYTE),
  CS_CREATE_USER       VARCHAR2(20 BYTE),
  CS_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  CS_UPDATE_USER       VARCHAR2(20 BYTE),
  CS_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX COUNTRY_SERVICE_MAP_PK ON COUNTRY_SERVICE_MAP
(CS_COUNTRY, CS_SERVICE_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE COUNTRY_SERVICE_MAP ADD (
  CONSTRAINT COUNTRY_SERVICE_MAP_PK
  PRIMARY KEY
  (CS_COUNTRY, CS_SERVICE_CODE)
  USING INDEX COUNTRY_SERVICE_MAP_PK
  ENABLE VALIDATE);

ALTER TABLE COUNTRY_SERVICE_MAP ADD (
  CONSTRAINT COUNTRY_SERVICE_MAP_FK01 
  FOREIGN KEY (CS_COUNTRY) 
  REFERENCES COUNTRY (COUNTRY_CODE)
  ENABLE VALIDATE,
  CONSTRAINT COUNTRY_SERVICE_MAP_FK02 
  FOREIGN KEY (CS_SERVICE_CODE) 
  REFERENCES DEF_SERVICE_CODE (SC_CODE)
  ENABLE VALIDATE);

