OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MiAcrBal
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMiAcrBal.so
SOOBJS =  MiAcrBal.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
