ALTER TABLE EXCHANGE_RATE_TMP
 DROP PRIMARY KEY CASCADE;

DROP TABLE EXCHANGE_RATE_TMP CASCADE CONSTRAINTS;

CREATE TABLE EXCHANGE_RATE_TMP
(
  EX_FROM_CCY_ID         CHAR(3 BYTE)           NOT NULL,
  EX_TO_CCY_ID           CHAR(3 BYTE)           NOT NULL,
  EX_RATE                NUMBER(13,5)           NOT NULL,
  EX_BID                 NUMBER(12,6),
  EX_MAX_ASK             NUMBER(13,5),
  EX_MED_ASK             NUMBER(13,5),
  EX_MIN_ASK             NUMBER(13,5),
  EX_MAX_BID             NUMBER(13,5),
  EX_MED_BID             NUMBER(13,5),
  EX_MIN_BID             NUMBER(13,5),
  EX_MEANMINMAX_SRC2DST  NUMBER(12,6),
  EX_MINMAX_SRC2DST      NUMBER(12,6),
  EX_EFFECT_DATE         DATE                   NOT NULL,
  EX_CREATE_DATE         DATE                   NOT NULL,
  EX_CREATE_USER         VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX EXCHANGE_RATE_TMP_PK ON EXCHANGE_RATE_TMP
(EX_FROM_CCY_ID, EX_TO_CCY_ID, EX_EFFECT_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE EXCHANGE_RATE_TMP ADD (
  CONSTRAINT EXCHANGE_RATE_TMP_PK
  PRIMARY KEY
  (EX_FROM_CCY_ID, EX_TO_CCY_ID, EX_EFFECT_DATE)
  USING INDEX EXCHANGE_RATE_TMP_PK);

