OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/ParChannelCodeMap
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBParChannelCodeMap.so
SOOBJS =  ParChannelCodeMap.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
