OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/PspRedirectSetting
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBPspRedirectSetting.so
SOOBJS =  PspRedirectSetting.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
