ALTER TABLE MMS_ENTITY_BALANCE
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_ENTITY_BALANCE CASCADE CONSTRAINTS;

CREATE TABLE MMS_ENTITY_BALANCE
(
  MEB_ENTITY_ID         VARCHAR2(20 BYTE),
  MEB_CCY               VARCHAR2(3 BYTE),
  MEB_NATURE_ID         VARCHAR2(20 BYTE),
  MEB_ACCT_BAL          NUMBER(14,2)            DEFAULT 0,
  MEB_PREPAID           NUMBER(14,2)            DEFAULT 0,
  MEB_INTRANSIT         NUMBER(14,2)            DEFAULT 0,
  MEB_LIEN              NUMBER(14,2)            DEFAULT 0,
  MEB_CREATE_TIMESTAMP  DATE,
  MEB_CREATE_USER       VARCHAR2(20 BYTE),
  MEB_UPDATE_TIMESTAMP  DATE,
  MEB_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MMS_ENTITY_BALANCE_PK ON MMS_ENTITY_BALANCE
(MEB_ENTITY_ID, MEB_CCY, MEB_NATURE_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_ENTITY_BALANCE ADD (
  CONSTRAINT MMS_ENTITY_BALANCE_PK
  PRIMARY KEY
  (MEB_ENTITY_ID,MEB_CCY, MEB_NATURE_ID)
  USING INDEX MMS_ENTITY_BALANCE_PK
  ENABLE VALIDATE);

ALTER TABLE MMS_ENTITY_BALANCE ADD (
  CONSTRAINT MMS_ENTITY_BALANCE_FK01 
  FOREIGN KEY (MEB_NATURE_ID) 
  REFERENCES MMS_ENTITY_NATURE (MEN_NATURE_ID)
  ENABLE VALIDATE);

ALTER TABLE PHUSER.MMS_ENTITY_BALANCE
 ADD CONSTRAINT MMS_ENTITY_BALANCE_FK02 
  FOREIGN KEY (MEB_ENTITY_ID) 
  REFERENCES PHUSER.MMS_ENTITY (ME_ID)
  ENABLE VALIDATE;
