DROP TABLE OL_TXN_ENGINE_BAID_NATURE CASCADE CONSTRAINTS;

CREATE TABLE OL_TXN_ENGINE_BAID_NATURE
(
  OTE_ACTIVITY          VARCHAR2(50 BYTE),
  OTE_BANK_STMT_TYPE    VARCHAR2(50 BYTE),
  OTE_CHANNEL           CHAR(3 BYTE),
  OTE_TRIGGER_TYPE      VARCHAR2(10 BYTE),
  OTE_BAID_NATURE       CHAR(3 BYTE),
  OTE_BAID_CATEGORY     VARCHAR2(10 BYTE),
  OTE_PARTY_TYPE        VARCHAR2(10 BYTE),
  OTE_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  OTE_CREATE_USER       VARCHAR2(20 BYTE),
  OTE_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  OTE_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX OL_TXN_ENG_BAID_NATURE_IDX01 ON OL_TXN_ENGINE_BAID_NATURE
(OTE_ACTIVITY, OTE_BANK_STMT_TYPE, OTE_CHANNEL, OTE_TRIGGER_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_TXN_ENGINE_BAID_NATURE ADD (
  CONSTRAINT OL_TXN_ENGINE_BAID_NATURE_FK01 
  FOREIGN KEY (OTE_TRIGGER_TYPE) 
  REFERENCES OL_DEF_ENGINE_TRIGGER_TYPE (ETT_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OL_TXN_ENGINE_BAID_NATURE_FK02 
  FOREIGN KEY (OTE_BAID_NATURE) 
  REFERENCES OL_DEF_BANK_ACCT_TYPE (OBC_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OL_TXN_ENGINE_BAID_NATURE_FK03 
  FOREIGN KEY (OTE_BAID_CATEGORY) 
  REFERENCES OL_DEF_BAID_CATEGORY (BC_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OL_TXN_ENGINE_BAID_NATURE_FK04 
  FOREIGN KEY (OTE_ACTIVITY) 
  REFERENCES OL_DEF_ENGINE_ACTIVITY (DEA_TYPE)
  ENABLE VALIDATE);

