CREATE TABLE RESTRICT_IP_REGION
(
  RIR_REGION_CODE      	CHAR(2 BYTE)                NOT NULL,
  RIR_REGION_NAME      	VARCHAR2(50 BYTE),
  RIR_PSP_SUPPORT	INTEGER,
  RIR_DISABLED          INTEGER                     DEFAULT 0,
  RIR_CREATE_TIMESTAMP  DATE                        DEFAULT SYSDATE,
  RIR_UPDATE_TIMESTAMP  DATE                        DEFAULT SYSDATE,
  RIR_CREATE_USER       VARCHAR2(25 BYTE),
  RIR_UPDATE_USER       VARCHAR2(25 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE INDEX RESTRICT_IP_REGION_IDX01 ON RESTRICT_IP_REGION
(RIR_REGION_CODE, RIR_DISABLED)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX RESTRICT_IP_REGION_PK ON RESTRICT_IP_REGION
(RIR_REGION_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


ALTER TABLE RESTRICT_IP_REGION ADD (
  CONSTRAINT RESTRICT_IP_REGION_PK
  PRIMARY KEY
  (RIR_REGION_CODE)
  USING INDEX RESTRICT_IP_REGION_PK
  ENABLE VALIDATE);
