ALTER TABLE DEF_ELEMENT_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_ELEMENT_TYPE CASCADE CONSTRAINTS;

CREATE TABLE DEF_ELEMENT_TYPE
(
  DT_TYPE              CHAR(4 BYTE),
  DT_DESC              VARCHAR2(50 BYTE),
  DT_CREATE_TIMESTAMP  DATE,
  DT_CREATE_USER       VARCHAR2(20 BYTE),
  DT_UPDATE_TIMESTAMP  DATE,
  DT_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEF_ELEMENT_TYPE_PK ON DEF_ELEMENT_TYPE
(DT_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_ELEMENT_TYPE ADD (
  CONSTRAINT DEF_ELEMENT_TYPE_PK
  PRIMARY KEY
  (DT_TYPE)
  USING INDEX DEF_ELEMENT_TYPE_PK
  ENABLE VALIDATE);

