OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOOLRecon
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOOLRecon.so
SOOBJS = BOOLRecon.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
