ALTER TABLE OL_RESOURCE_LOCK
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_RESOURCE_LOCK CASCADE CONSTRAINTS;

CREATE TABLE OL_RESOURCE_LOCK
(
  ORL_INT_BANK_CODE     VARCHAR2(10 BYTE),
  ORL_BANK_ACCT_NUM     VARCHAR2(50 BYTE),
  ORL_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  ORL_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  ORL_CREATE_USER       VARCHAR2(20 BYTE),
  ORL_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_RESOURCE_LOCK_PK ON OL_RESOURCE_LOCK
(ORL_INT_BANK_CODE, ORL_BANK_ACCT_NUM)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_RESOURCE_LOCK ADD (
  CONSTRAINT OL_RESOURCE_LOCK_PK
  PRIMARY KEY
  (ORL_INT_BANK_CODE, ORL_BANK_ACCT_NUM)
  USING INDEX OL_RESOURCE_LOCK_PK
  ENABLE VALIDATE);

ALTER TABLE OL_RESOURCE_LOCK ADD (
  CONSTRAINT OL_RESOURCE_LOCK_FK01 
  FOREIGN KEY (ORL_INT_BANK_CODE, ORL_BANK_ACCT_NUM) 
  REFERENCES OL_BANK_ACCTS (OB_INT_BANK_CODE,OB_BANK_ACCT_NUM)
  ENABLE VALIDATE);

