OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/EmailFunctExclude
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBEmailFunctExclude.so
SOOBJS =  EmailFunctExclude.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
