OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOPsp
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOPsp.so
SOOBJS = BOPsp.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
