OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLSemiAutoReconTriggerLog
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLSemiAutoReconTriggerLog.so
SOOBJS = OLSemiAutoReconTriggerLog.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
