OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnOplOnUsOPI
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnOplOnUsOPI.so
SOOBJS = TxnOplOnUsOPI.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
