OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/RulePayoutExcludeBankAcct
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBRulePayoutExcludeBankAcct.so
SOOBJS =  RulePayoutExcludeBankAcct.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
