


CREATE TABLE OL_PAYOUT_REQUEST
(
  OPR_TXN_ID               VARCHAR2(16 BYTE),
  OPR_AUX_TXN_ID           VARCHAR2(16 BYTE),
  OPR_MERCHANT_PAYOUT_GRP  VARCHAR2(2 BYTE),
  OPR_PSP_PAYOUT_GRP       VARCHAR2(2 BYTE),
  OPR_REQUEST_CURRENCY     VARCHAR2(3 BYTE),
  OPR_REQUEST_AMOUNT       NUMBER(12,2)         DEFAULT 0,
  OPR_PAYOUT_CURRENCY      VARCHAR2(3 BYTE),
  OPR_PAYOUT_AMOUNT        NUMBER(12,2)         DEFAULT 0,
  OPR_MEMBER_FEE_CCY       VARCHAR2(3 BYTE),
  OPR_MEMBER_FEE           NUMBER(12,2)         DEFAULT 0,
  OPR_MERCHANT_FEE_CCY     VARCHAR2(3 BYTE),
  OPR_MERCHANT_FEE         NUMBER(12,2)         DEFAULT 0,
  OPR_MARKUP_CCY           VARCHAR2(3 BYTE),
  OPR_MARKUP_AMT           NUMBER(12,2)         DEFAULT 0,
  OPR_STATUS               INTEGER,
  OPR_GENERATED_FILE_ID    NUMBER(16),
  OPR_PSP_ID               VARCHAR2(10 BYTE),
  OPR_CREATE_TIMESTAMP     DATE                 DEFAULT sysdate               NOT NULL,
  OPR_CREATE_USER          VARCHAR2(20 BYTE),
  OPR_UPDATE_TIMESTAMP     DATE                 DEFAULT sysdate               NOT NULL,
  OPR_UPDATE_USER          VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE INDEX OL_PAYOUT_REQUEST_IDX01 ON OL_PAYOUT_REQUEST
(OPR_CREATE_TIMESTAMP, OPR_UPDATE_TIMESTAMP)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX OL_PAYOUT_REQUEST_IDX02 ON OL_PAYOUT_REQUEST
(OPR_AUX_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX OL_PAYOUT_REQUEST_IDX03 ON OL_PAYOUT_REQUEST
(OPR_GENERATED_FILE_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX OL_PAYOUT_REQUEST_IDX04 ON OL_PAYOUT_REQUEST
(OPR_PSP_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX OL_PAYOUT_REQUEST_PK ON OL_PAYOUT_REQUEST
(OPR_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE OL_PAYOUT_REQUEST ADD (
  CONSTRAINT OL_PAYOUT_REQUEST_PK
  PRIMARY KEY
  (OPR_TXN_ID)
  USING INDEX OL_PAYOUT_REQUEST_PK
  ENABLE VALIDATE);
