ALTER TABLE MMS_MB_DETAIL
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_MB_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE MMS_MB_DETAIL
(
  MD_MB_ID                   VARCHAR2(15 BYTE),
  MD_MB_NAME                 VARCHAR2(50 BYTE),
  MD_DISABLED                 INTEGER              DEFAULT 0,
  MD_CREATE_TIMESTAMP         DATE                 DEFAULT sysdate,
  MD_UPDATE_TIMESTAMP         DATE                 DEFAULT sysdate,
  MD_CREATE_USER              VARCHAR2(20 BYTE),
  MD_UPDATE_USER              VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX MMS_MB_DETAIL_IDX01 ON MMS_MB_DETAIL
(MD_DISABLED)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX MMS_MB_DETAIL_PK ON MMS_MB_DETAIL
(MD_MB_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_MB_DETAIL ADD (
  CONSTRAINT MMS_MB_DETAIL_PK
  PRIMARY KEY
  (MD_MB_ID)
  USING INDEX MMS_MB_DETAIL_PK
  ENABLE VALIDATE);
