ALTER TABLE SYSTEM_CONTROL
 DROP PRIMARY KEY CASCADE;

DROP TABLE SYSTEM_CONTROL CASCADE CONSTRAINTS;

CREATE TABLE SYSTEM_CONTROL
(
  SYS_CODE              VARCHAR2(10 BYTE)       NOT NULL,
  SYS_DESC              VARCHAR2(50 BYTE),
  SYS_VAL               VARCHAR2(20 BYTE)       NOT NULL,
  SYS_CREATE_USER       VARCHAR2(20 BYTE),
  SYS_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  SYS_UPDATE_USER       VARCHAR2(20 BYTE),
  SYS_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX SYSTEM_CONTROL_PK ON SYSTEM_CONTROL
(SYS_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE SYSTEM_CONTROL ADD (
  CONSTRAINT SYSTEM_CONTROL_PK
  PRIMARY KEY
  (SYS_CODE)
  USING INDEX SYSTEM_CONTROL_PK);
