CREATE OR REPLACE FUNCTION SP_HIST_OL_MID_BAL_COLLECT(
    IN_END_DATE IN DATE )
RETURN NUMBER IS
	EXP_ERR  EXCEPTION;
	EXP_ERR2 EXCEPTION;
	DATE_ERR EXCEPTION;

	V_CUTOFF_DATE DATE;

	V_NEW_BATCH_ID HIST_OL_MID_BAL_BATCH.HB_BATCH_ID%type;
	V_PREV_BATCH_ID HIST_OL_MID_BAL_BATCH.HB_BATCH_ID%type;
	V_START_DATE         DATE;
	V_ADD_RANGE_END_DATE DATE;

	V_CURRENT_BAL OL_TXN_DETAIL.OTD_CURRENT_BAL%type;
	V_HOLD_BAL OL_TXN_DETAIL.OTD_TOTAL_RESERVED_AMOUNT%type;
	V_LIEN OL_TXN_DETAIL.OTD_TOTAL_HOLD%type;
	V_MERCHANT_BAL OL_TXN_DETAIL.OTD_CURRENT_BAL%type;

	V_CURRENT_BAL_PREV OL_TXN_DETAIL.OTD_CURRENT_BAL%type;
	V_HOLD_BAL_PREV OL_TXN_DETAIL.OTD_TOTAL_RESERVED_AMOUNT%type;
	V_LIEN_PREV OL_TXN_DETAIL.OTD_TOTAL_HOLD%type;
	V_MERCHANT_BAL_PREV OL_TXN_DETAIL.OTD_CURRENT_BAL%type;

	V_HD_CURRENT_BAL HIST_OL_MID_BAL_DETAIL.HD_CURRENT_BAL%type;
	V_HD_HOLD_BAL HIST_OL_MID_BAL_DETAIL.HD_HOLD_BAL%type;
	V_HD_LIEN HIST_OL_MID_BAL_DETAIL.HD_LIEN%type;
	V_HD_MERCHANT_BAL HIST_OL_MID_BAL_DETAIL.HD_MERCHANT_BAL%type;

	V_NET_BAL HIST_OL_MID_BAL_DETAIL.HD_BAL%type;
	V_HD_BAL HIST_OL_MID_BAL_DETAIL.HD_BAL%type;
	V_HD_BAL_HKD HIST_OL_MID_BAL_DETAIL.HD_BAL_HKD%type;
	V_HD_BAL_USD HIST_OL_MID_BAL_DETAIL.HD_BAL_USD%type;
	V_HD_TXN_ID HIST_OL_MID_BAL_DETAIL.HD_TXN_ID%type;

	V_HKD_RATE EXCHANGE_RATE.EX_MED_ASK%type;
	V_USD_RATE EXCHANGE_RATE.EX_MED_ASK%type;
	V_COUNT_NO number;
	V_COUNT_NO2 number;

BEGIN
-- DBMS_OUTPUT.PUT_LINE('>>> START [HIST_OL_MID_BAL_COLLECT] <<<');
-- DBMS_OUTPUT.PUT_LINE('--> Input Date: '|| TO_CHAR(IN_END_DATE, 'YYYY-MM-DD HH24:MI') );
	SELECT
		count(*)
	INTO
		V_COUNT_NO2
	FROM HIST_RPT_CONFIG
	WHERE HR_RPT_CODE = 'OL_MID_BAL';

	IF SQL % ROWCOUNT != 1 THEN
		raise EXP_ERR2;
	END IF;


	IF V_COUNT_NO2 > 0 THEN
		SELECT
			HR_CUTOFF_DATE
		INTO
			V_CUTOFF_DATE
		FROM HIST_RPT_CONFIG
		WHERE HR_RPT_CODE = 'OL_MID_BAL';

		IF SQL % ROWCOUNT != 1 THEN
			raise EXP_ERR2;
		END IF ;
	ELSE
	       V_CUTOFF_DATE :=  IN_END_DATE - 1 ;
	END IF ;


-- Find Prev Batch ID and current batch start date/time
	SELECT HB_BATCH_ID,
	       HB_END_DATE
	INTO V_PREV_BATCH_ID,
	     V_START_DATE
	FROM
	(SELECT HB_BATCH_ID,
	        HB_END_DATE,
	        ROW_NUMBER() OVER (PARTITION BY HB_DISABLED ORDER BY HB_END_DATE DESC) RN
	 FROM HIST_OL_MID_BAL_BATCH
	 WHERE HB_DISABLED = 0
	)
	WHERE RN = 1;

	IF SQL % ROWCOUNT != 1 THEN
		raise EXP_ERR2;
	END IF ;
	
	V_START_DATE := V_START_DATE + 1/24/60;
-- DBMS_OUTPUT.PUT_LINE('--> Start Date: '|| V_START_DATE );
-- DBMS_OUTPUT.PUT_LINE('--> End Date: '|| IN_END_DATE );

-- only look forward
	IF IN_END_DATE < V_START_DATE THEN
		raise DATE_ERR;
	END IF;
-- DBMS_OUTPUT.PUT_LINE('xxxx');

-- New Batch ID
	SELECT MAX(HB_BATCH_ID) + 1
	INTO V_NEW_BATCH_ID
	FROM HIST_OL_MID_BAL_BATCH;
-- DBMS_OUTPUT.PUT_LINE('--> New Batch ID: ' || V_NEW_BATCH_ID );
-- DBMS_OUTPUT.PUT_LINE('--> Previous Batch ID: ' || V_PREV_BATCH_ID );

-- Add 1 mins to end times
	V_ADD_RANGE_END_DATE := IN_END_DATE + 1/24/60;
-- DBMS_OUTPUT.PUT_LINE('--> Add 1 mins end date: ' || V_ADD_RANGE_END_DATE );
-- Insert New Batch
	INSERT
	INTO HIST_OL_MID_BAL_BATCH
	(
	 	HB_BATCH_ID,
	 	HB_START_DATE,
	 	HB_END_DATE,
	 	HB_DISABLED,
	 	HB_CREATE_TIMESTAMP,
	 	HB_CREATE_USER
	)
	VALUES
	(
	 	V_NEW_BATCH_ID,
	 	V_START_DATE,
	 	IN_END_DATE,
	 	0,
	 	SYSDATE,
	 	'SYSTEM'
	);

	IF SQL % ROWCOUNT != 1 THEN
		raise EXP_ERR;
	END IF ;
-- DBMS_OUTPUT.PUT_LINE('--> Insert New Batch : OK');

-- Find PSP Last Txn from start times to end times
	FOR X IN
	(
		SELECT
		      	TXN_ID ,
		      	CLIENT_ID ,
		      	MID_ID ,
		      	SERVICE_CODE ,
		      	TXN_CCY ,
		      	COUNTRY ,
		      	APPROVAL_TIMESTAMP
		FROM (
		        SELECT
		      		TXN_ID ,
		      		CLIENT_ID ,
		      		MID_ID ,
		      		SERVICE_CODE ,
		      		TXN_CCY ,
		      		COUNTRY ,
		      		APPROVAL_TIMESTAMP ,
		      		ROW_NUMBER() OVER ( PARTITION BY CLIENT_ID , MID_ID , COUNTRY , SERVICE_CODE, TXN_CCY ORDER BY APPROVAL_TIMESTAMP DESC ) RN
		      	FROM (
		      		SELECT
		      			TXN_ID ,
		      			CLIENT_ID ,
		      			MID_ID ,
		      			SERVICE_CODE ,
		      			TXN_CCY ,
		      			COUNTRY ,
		      			APPROVAL_TIMESTAMP
		      		FROM (
		      			  SELECT
		      				OTH_TXN_ID       	AS TXN_ID ,
		      				MD_CLIENT_ID		AS CLIENT_ID ,
		      				OTH_MERCHANT_ID		AS MID_ID ,
		      				OTH_SERVICE_CODE	AS SERVICE_CODE ,
		      				OTH_NET_CCY		AS TXN_CCY ,
		      				OTD_TXN_COUNTRY		AS COUNTRY ,
		      				OTH_APPROVAL_TIMESTAMP AS APPROVAL_TIMESTAMP ,
		      				ROW_NUMBER() OVER ( PARTITION BY MD_CLIENT_ID , OTH_MERCHANT_ID , OTD_TXN_COUNTRY , OTH_SERVICE_CODE , OTH_NET_CCY ORDER BY OTH_APPROVAL_TIMESTAMP DESC ) RN
		      			  FROM
		      				OL_TXN_DETAIL ,
		      				OL_TXN_HEADER,
		      				OL_MERCH_DETAIL
		      			  WHERE OTH_TXN_ID = OTD_TXN_ID
		      			  AND OTH_MERCHANT_ID = MD_MERCHANT_ID 
		      			  AND OTH_AR_IND	= 'A'
		      			  AND OTH_APPROVAL_TIMESTAMP >= CAST(V_START_DATE AS TIMESTAMP)
		      			  AND OTH_APPROVAL_TIMESTAMP  < CAST(V_ADD_RANGE_END_DATE AS TIMESTAMP)
		      			  AND OTH_TXN_CODE NOT IN ('RLS','RLA')
		      			  AND OTH_SERVICE_CODE IS NOT NULL
		      			  AND OTD_CURRENT_BAL IS NOT NULL
		      			  AND OTH_NET_CCY IS NOT NULL
		      			  AND OTD_TXN_COUNTRY IS NOT NULL
		      			  AND OTH_MERCHANT_ID IS NOT NULL
		      			  AND MD_CLIENT_ID IS NOT NULL
		      			  ORDER BY OTH_APPROVAL_TIMESTAMP DESC
		      		)
		      		WHERE RN = 1
		      		UNION
		      		SELECT
		      			HD_TXN_ID				AS TXN_ID ,
		      			HD_CLIENT_ID			AS CLIENT_ID ,
		      			HD_MID_ID				AS MID_ID ,
		      			HD_SERVICE_CODE			AS SERVICE_CODE ,
		      			HD_CCY					AS TXN_CCY ,
		      			HD_COUNTRY				AS COUNTRY ,
		      			OTH_APPROVAL_TIMESTAMP 	AS APPROVAL_TIMESTAMP
		      		FROM
		      			HIST_OL_MID_BAL_DETAIL ,
		      			OL_TXN_HEADER
		      		WHERE OTH_TXN_ID  = HD_TXN_ID
		      		AND HD_BATCH_ID = V_PREV_BATCH_ID
			)
			ORDER BY APPROVAL_TIMESTAMP DESC
		)
		WHERE RN = 1
	)
	LOOP
-- DBMS_OUTPUT.PUT_LINE('--> MID_ID: [' || X.MID_ID || '] SERVICE_CODE: [' || X.SERVICE_CODE || ']  TXN_CCY: [' || X.TXN_CCY || '] TXN_ID : [' || X.TXN_ID||'] COUNTRY : [' || X.COUNTRY||'] ');

		IF X.TXN_ID IS NOT NULL THEN
-- DBMS_OUTPUT.PUT_LINE('--> Txn Bal');
--  Txn Bal
			SELECT
				NVL(
					NVL(OTD_CURRENT_BAL, 0.00)
					+ NVL(OTD_CURRENT_BAL_SETTLEMENT, 0.00)
					- NVL(OTD_TOTAL_RESERVED_AMOUNT, 0.00)
					- NVL(OTD_TOTAL_HOLD, 0.00)
					- NVL(OTD_TOTAL_HOLD_SETTLEMENT, 0.00)
				, 0.00 ) CURRENT_BAL,
				NVL(OTD_TOTAL_RESERVED_AMOUNT, 0.00) HOLD_BAL ,
				NVL(OTD_TOTAL_HOLD, 0.00) + NVL(OTD_TOTAL_HOLD_SETTLEMENT, 0.00) LIEN ,
				NVL(OTD_CURRENT_BAL, 0.00) + NVL(OTD_CURRENT_BAL_SETTLEMENT, 0.00) MERCHANT_BAL
			 INTO
				V_CURRENT_BAL ,
				V_HOLD_BAL ,
				V_LIEN ,
				V_MERCHANT_BAL
			FROM OL_TXN_DETAIL
			WHERE OTD_TXN_ID = X.TXN_ID;

-- DBMS_OUTPUT.PUT_LINE('--> V_CURRENT_BAL: [' || V_CURRENT_BAL || '] V_HOLD_BAL: [' || V_HOLD_BAL ||'] V_LIEN: [' || V_LIEN ||'] V_MERCHANT_BAL: [' || V_MERCHANT_BAL ||']');

-- DBMS_OUTPUT.PUT_LINE('--> Find last BATCH ID : [' ||V_PREV_BATCH_ID || ']');

			SELECT count(*) AS COUNT_NO INTO V_COUNT_NO
			FROM HIST_OL_MID_BAL_DETAIL
			WHERE HD_MID_ID = X.MID_ID
			AND HD_COUNTRY = X.COUNTRY
			AND HD_SERVICE_CODE = X.SERVICE_CODE
			AND HD_CCY = X.TXN_CCY
		        AND HD_BATCH_ID = V_PREV_BATCH_ID;

-- DBMS_OUTPUT.PUT_LINE('--> V_COUNT_NO : [' ||V_COUNT_NO || ']');

			IF V_COUNT_NO > 0 THEN
-- Prev Batch Bal
				SELECT
					HD_TXN_ID ,
					NVL(HD_CURRENT_BAL, 0.00) AS HD_CURRENT_BAL ,
					NVL(HD_HOLD_BAL, 0.00) AS HD_HOLD_BAL ,
					NVL(HD_LIEN, 0.00) AS HD_LIEN ,
					NVL(HD_MERCHANT_BAL, 0.00) AS HD_MERCHANT_BAL ,
					NVL(HD_BAL, 0.00) AS HD_BAL ,
					NVL(HD_BAL_HKD, 0.00) AS HD_BAL_HKD ,
					NVL(HD_BAL_USD, 0.00) AS HD_BAL_USD
				INTO
					V_HD_TXN_ID,
					V_HD_CURRENT_BAL ,
					V_HD_HOLD_BAL ,
					V_HD_LIEN ,
					V_HD_MERCHANT_BAL ,
					V_HD_BAL,
					V_HD_BAL_HKD,
					V_HD_BAL_USD
				FROM HIST_OL_MID_BAL_DETAIL
				WHERE HD_MID_ID = X.MID_ID
				AND HD_COUNTRY = X.COUNTRY
				AND HD_SERVICE_CODE = X.SERVICE_CODE
				AND HD_CCY = X.TXN_CCY
				AND HD_BATCH_ID = V_PREV_BATCH_ID;
		
				IF V_HD_TXN_ID IS NOT NULL THEN
					SELECT
						NVL(
							NVL(OTD_CURRENT_BAL, 0.00)
							+ NVL(OTD_CURRENT_BAL_SETTLEMENT, 0.00)
							- NVL(OTD_TOTAL_RESERVED_AMOUNT, 0.00)
							- NVL(OTD_TOTAL_HOLD, 0.00)
							- NVL(OTD_TOTAL_HOLD_SETTLEMENT, 0.00)
						,  0.00 ) CURRENT_BAL,
						NVL(OTD_TOTAL_RESERVED_AMOUNT, 0.00) HOLD_BAL ,
						NVL(OTD_TOTAL_HOLD, 0.00) + NVL(OTD_TOTAL_HOLD_SETTLEMENT, 0.00) LIEN ,
						NVL(OTD_CURRENT_BAL, 0.00) + NVL(OTD_CURRENT_BAL_SETTLEMENT, 0.00) MERCHANT_BAL
					 INTO
						V_CURRENT_BAL_PREV ,
						V_HOLD_BAL_PREV ,
						V_LIEN_PREV ,
						V_MERCHANT_BAL_PREV
					FROM OL_TXN_DETAIL
					WHERE OTD_TXN_ID = V_HD_TXN_ID;
				ELSE
					V_CURRENT_BAL_PREV := 0.00;
					V_HOLD_BAL_PREV := 0.00;
					V_LIEN_PREV := 0.00;
					V_MERCHANT_BAL_PREV := 0.00;
				END IF ;
		
			ELSE
-- DBMS_OUTPUT.PUT_LINE('--> No HIST Detail ');
				V_CURRENT_BAL_PREV := 0.00;
				V_HOLD_BAL_PREV := 0.00;
				V_LIEN_PREV := 0.00;
				V_MERCHANT_BAL_PREV := 0.00;
				V_HD_CURRENT_BAL := 0.00;
				V_HD_HOLD_BAL := 0.00;
				V_HD_LIEN := 0.00;
				V_HD_MERCHANT_BAL := 0.00;
				V_HD_TXN_ID := 0;
				V_HD_BAL := 0.00;
				V_HD_BAL_HKD := 0.00;
				V_HD_BAL_USD := 0.00;
			END IF ;

-- DBMS_OUTPUT.PUT_LINE('--> V_CURRENT_BAL_PREV: [' || V_CURRENT_BAL_PREV || '] V_HOLD_BAL_PREV: [' || V_HOLD_BAL_PREV ||'] V_LIEN_PREV: [' || V_LIEN_PREV ||'] V_MERCHANT_BAL_PREV: [' || V_MERCHANT_BAL_PREV ||']');

-- DBMS_OUTPUT.PUT_LINE('--> GET Rate');
-- HKD Rate , USD Rate
			SELECT
				RATE_HKD_TBL.RATE AS HKD_RATE,
				RATE_USD_TBL.RATE AS USD_RATE
			INTO
				V_HKD_RATE,
				V_USD_RATE
			FROM
			(
				SELECT
					EX_MED_ASK AS RATE ,
					EX_TO_CCY_ID
				FROM (
					SELECT EX_FROM_CCY_ID
						,EX_TO_CCY_ID
						,EX_MED_ASK
						,ROW_NUMBER() OVER (
							PARTITION BY EX_FROM_CCY_ID
							,EX_TO_CCY_ID ORDER BY EX_EFFECT_DATE DESC
						) XX
					FROM EXCHANGE_RATE
					WHERE EX_EFFECT_DATE < CAST(V_ADD_RANGE_END_DATE AS TIMESTAMP)
				)
				WHERE XX = 1
				AND EX_TO_CCY_ID = 'HKD'
				AND EX_FROM_CCY_ID = X.TXN_CCY
			) RATE_HKD_TBL
			INNER JOIN (
				SELECT
					EX_MED_ASK AS RATE ,
					EX_FROM_CCY_ID
				FROM (
					SELECT EX_FROM_CCY_ID
						,EX_TO_CCY_ID
						,EX_MED_ASK
						,ROW_NUMBER() OVER (
							PARTITION BY EX_FROM_CCY_ID
							,EX_TO_CCY_ID ORDER BY EX_EFFECT_DATE DESC
						) XX
					FROM EXCHANGE_RATE
					WHERE EX_EFFECT_DATE < CAST(V_ADD_RANGE_END_DATE AS TIMESTAMP)
				)
				WHERE XX = 1
				AND EX_FROM_CCY_ID = 'HKD'
				AND EX_TO_CCY_ID = 'USD'
			) RATE_USD_TBL ON RATE_HKD_TBL.EX_TO_CCY_ID = RATE_USD_TBL.EX_FROM_CCY_ID;
		
		
			IF X.TXN_ID != V_HD_TXN_ID THEN
				V_NET_BAL := V_MERCHANT_BAL - V_MERCHANT_BAL_PREV ;
			ELSE
				V_NET_BAL := 0.00;
			END IF ;

-- DBMS_OUTPUT.PUT_LINE('--> HKD_RATE: [' || V_HKD_RATE || '] USD_RATE: [' || V_USD_RATE ||']');

-- DBMS_OUTPUT.PUT_LINE('--> INSERT ');


-- Check Cut off Time
			IF V_CUTOFF_DATE >= V_ADD_RANGE_END_DATE THEN
				V_CURRENT_BAL:= 0.00;
				V_HOLD_BAL := 0.00;
				V_LIEN := 0.00;
				V_MERCHANT_BAL := 0.00;
				V_HD_CURRENT_BAL := 0.00;
				V_HD_HOLD_BAL := 0.00;
				V_HD_LIEN := 0.00;
				V_HD_MERCHANT_BAL := 0.00;
				V_HD_BAL := 0.00;
				V_HD_BAL_HKD := 0.00;
				V_HKD_RATE := 0.00;
				V_HD_BAL_USD := 0.00;
				V_USD_RATE := 0.00;
				V_NET_BAL := 0.00;
				V_CURRENT_BAL_PREV := 0.00;
				V_HOLD_BAL_PREV := 0.00;
				V_LIEN_PREV := 0.00;
				V_MERCHANT_BAL_PREV := 0.00;
			END IF;

			INSERT INTO HIST_OL_MID_BAL_DETAIL (
				HD_BATCH_ID,
				HD_CLIENT_ID,
				HD_MID_ID,
				HD_SERVICE_CODE,
				HD_CCY,
				HD_COUNTRY,
				HD_TXN_ID,
				HD_CURRENT_BAL ,
				HD_HOLD_BAL ,
				HD_LIEN ,
				HD_MERCHANT_BAL ,
				HD_BAL ,
				HD_BAL_HKD ,
				HD_BAL_HKD_RATE ,
				HD_BAL_USD ,
				HD_BAL_USD_RATE
			) VALUES (
				V_NEW_BATCH_ID,
				X.CLIENT_ID,
				X.MID_ID,
				X.SERVICE_CODE,
				X.TXN_CCY,
				X.COUNTRY,
				X.TXN_ID,
				NVL(V_HD_CURRENT_BAL + (V_CURRENT_BAL - V_CURRENT_BAL_PREV) ,0.00) ,
				NVL(V_HD_HOLD_BAL + (V_HOLD_BAL - V_HOLD_BAL_PREV) ,0.00) ,
				NVL(V_HD_LIEN + (V_LIEN - V_LIEN_PREV) ,0.00) ,
				NVL(V_HD_MERCHANT_BAL + (V_MERCHANT_BAL - V_MERCHANT_BAL_PREV) ,0.00) ,
				NVL(V_HD_BAL + V_NET_BAL,0.00),
				NVL(V_HD_BAL_HKD + (V_NET_BAL * V_HKD_RATE),0.00),
				V_HKD_RATE,
				NVL(V_HD_BAL_USD + (V_NET_BAL * V_HKD_RATE * V_USD_RATE),0.00),
				V_USD_RATE
			);

			IF SQL % ROWCOUNT != 1 THEN
		        	raise EXP_ERR;
			END IF;
-- DBMS_OUTPUT.PUT_LINE('--> END INSERT ');

		END IF;

	END LOOP;

	COMMIT;

-- DBMS_OUTPUT.PUT_LINE('>>> END [HIST_OL_MID_BAL_COLLECT] <<<');

	RETURN 0;

EXCEPTION
WHEN EXP_ERR THEN
	ROLLBACK;
--DBMS_OUTPUT.PUT_LINE('Error: Insert last txn error!...');
	RETURN 1;
WHEN DATE_ERR THEN
	ROLLBACK;
--DBMS_OUTPUT.PUT_LINE('Error: The latest batch end date larger than input date!');
	RETURN 1;
WHEN EXP_ERR2 THEN
	ROLLBACK;
--DBMS_OUTPUT.PUT_LINE('Error: no record!...');
	RETURN 1;
WHEN OTHERS THEN
	ROLLBACK;
--DBMS_OUTPUT.PUT_LINE('Error: Other error!...');
--DBMS_OUTPUT.PUT_LINE('Error code ' || SQLCODE|| ': ' || SUBSTR(SQLERRM, 1 , 64));
--RAISE_APPLICATION_ERROR( -20201, 'Error code ' || SQLCODE|| ': ' || SUBSTR(SQLERRM, 1 , 64) );
	RETURN 9;
END SP_HIST_OL_MID_BAL_COLLECT;
/
