OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/DepositTrace
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBDepositTrace.so
SOOBJS =  DepositTrace.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
