OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/DepositMatchStat
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBDepositMatchStat.so
SOOBJS =  DepositMatchStat.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
