ALTER TABLE MI_DEF_BATCH_REL_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE MI_DEF_BATCH_REL_TYPE CASCADE CONSTRAINTS;

CREATE TABLE MI_DEF_BATCH_REL_TYPE
(
  BRT_TYPE              CHAR(1 BYTE),
  BRT_DESC              VARCHAR2(50 BYTE),
  BRT_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  BRT_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  BRT_CREATE_USER       VARCHAR2(20 BYTE),
  BRT_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MI_DEF_BATCH_REL_TYPE_PK ON MI_DEF_BATCH_REL_TYPE
(BRT_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MI_DEF_BATCH_REL_TYPE ADD (
  CONSTRAINT MI_DEF_BATCH_REL_TYPE_PK
  PRIMARY KEY
  (BRT_TYPE)
  USING INDEX MI_DEF_BATCH_REL_TYPE_PK
  ENABLE VALIDATE);

