ALTER TABLE MMS_RULE_CREDIT_LIMIT
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_RULE_CREDIT_LIMIT CASCADE CONSTRAINTS;

CREATE TABLE MMS_RULE_CREDIT_LIMIT
(
  MCL_CREDIT_LIMIT_MODE  CHAR(1 BYTE),
  MCL_ENTITY_ID          VARCHAR2(20 BYTE),
  MCL_CCY                VARCHAR2(3 BYTE),
  MCL_TXN_CODE           CHAR(3 BYTE)		DEFAULT 000,
  MCL_EFFECT_DATE        DATE,
  MCL_IS_POSITIVE        INTEGER                DEFAULT 1,
  MCL_DISABLED           INTEGER,
  MCL_AMOUNT_ID          INTEGER,
  MCL_CREATE_TIMESTAMP   DATE                   DEFAULT sysdate,
  MCL_CREATE_USER        VARCHAR2(20 BYTE),
  MCL_UPDATE_TIMESTAMP   DATE                   DEFAULT sysdate,
  MCL_UPDATE_USER        VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MMS_RULE_CREDIT_LIMIT_PK ON MMS_RULE_CREDIT_LIMIT
(MCL_CREDIT_LIMIT_MODE, MCL_ENTITY_ID, MCL_CCY, MCL_TXN_CODE, 
MCL_EFFECT_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_RULE_CREDIT_LIMIT ADD (
  CONSTRAINT MMS_RULE_CREDIT_LIMIT_PK
  PRIMARY KEY
  (MCL_CREDIT_LIMIT_MODE, MCL_ENTITY_ID, MCL_CCY, MCL_TXN_CODE, MCL_EFFECT_DATE)
  USING INDEX MMS_RULE_CREDIT_LIMIT_PK
  ENABLE VALIDATE);

ALTER TABLE MMS_RULE_CREDIT_LIMIT ADD (
  CONSTRAINT MMS_RULE_CREDIT_LIMIT_FK01 
  FOREIGN KEY (MCL_CREDIT_LIMIT_MODE) 
  REFERENCES MMS_DEF_CREDIT_LIMIT_MODE (MCR_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT MMS_RULE_CREDIT_LIMIT_FK02 
  FOREIGN KEY (MCL_ENTITY_ID) 
  REFERENCES MMS_ENTITY (ME_ID)
  ENABLE VALIDATE,
  CONSTRAINT MMS_RULE_CREDIT_LIMIT_FK03 
  FOREIGN KEY (MCL_AMOUNT_ID) 
  REFERENCES MMS_RULE_AMOUNT (MRA_ID)
  ENABLE VALIDATE);

