ALTER TABLE EOD_JOB_DEPENDENCE
 DROP PRIMARY KEY CASCADE;

DROP TABLE EOD_JOB_DEPENDENCE CASCADE CONSTRAINTS;

CREATE TABLE EOD_JOB_DEPENDENCE
(
  ED_JOB_ID            VARCHAR2(10 BYTE)        NOT NULL,
  ED_WAIT_FOR          VARCHAR2(10 BYTE)        NOT NULL,
  ED_CREATE_USER       VARCHAR2(20 BYTE),
  ED_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  ED_UPDATE_USER       VARCHAR2(20 BYTE),
  ED_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PK_EOD_JOB_DEPENDENCE ON EOD_JOB_DEPENDENCE
(ED_JOB_ID, ED_WAIT_FOR)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE EOD_JOB_DEPENDENCE ADD (
  CONSTRAINT PK_EOD_JOB_DEPENDENCE
  PRIMARY KEY
  (ED_JOB_ID, ED_WAIT_FOR)
  USING INDEX PK_EOD_JOB_DEPENDENCE);

