ALTER TABLE EOD_JOBS_STATUS
 DROP PRIMARY KEY CASCADE;

DROP TABLE EOD_JOBS_STATUS CASCADE CONSTRAINTS;

CREATE TABLE EOD_JOBS_STATUS
(
  ES_JOB_ID                     VARCHAR2(10 BYTE) NOT NULL,
  ES_STATUS                     VARCHAR2(1 BYTE) DEFAULT 'N',
  ES_RUN_DATE                   VARCHAR2(8 BYTE),
  ES_RUN_TIMESTAMP              DATE            DEFAULT sysdate,
  ES_RUN_COMPLETED_TIMESTAMP    DATE,
  ES_RERUN_DATE                 VARCHAR2(8 BYTE),
  ES_RERUN_TIMESTAMP            DATE,
  ES_RERUN_COMPLETED_TIMESTAMP  DATE,
  ES_CREATE_USER                VARCHAR2(20 BYTE),
  ES_CREATE_TIMESTAMP           DATE            DEFAULT sysdate,
  ES_UPDATE_USER                VARCHAR2(8 BYTE),
  ES_UPDATE_TIMESTAMP           DATE            DEFAULT sysdate,
  ES_REMARKS                    VARCHAR2(150 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN EOD_JOBS_STATUS.ES_STATUS IS '''N'' for New Cycle ,''C'' For Complete, ''P'' for Processing,''F'' for Failed';

COMMENT ON COLUMN EOD_JOBS_STATUS.ES_RUN_DATE IS 'Application Run Date';

COMMENT ON COLUMN EOD_JOBS_STATUS.ES_RUN_TIMESTAMP IS 'System Run Date';


CREATE UNIQUE INDEX PK_EOD_JOBS_STATUS ON EOD_JOBS_STATUS
(ES_JOB_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE EOD_JOBS_STATUS ADD (
  CONSTRAINT PK_EOD_JOBS_STATUS
  PRIMARY KEY
  (ES_JOB_ID)
  USING INDEX PK_EOD_JOBS_STATUS);

