OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOParPayout
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOParPayout.so
SOOBJS = BOParPayout.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
