ALTER TABLE DEF_AMOUNT
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_AMOUNT CASCADE CONSTRAINTS;

CREATE TABLE DEF_AMOUNT
(
  DA_TYPE              CHAR(1 BYTE),
  DA_DESC              VARCHAR2(50 BYTE),
  DA_CREATE_TIMESTAMP  DATE,
  DA_CREATE_USER       VARCHAR2(20 BYTE),
  DA_UPDATE_TIMESTAMP  DATE,
  DA_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEF_AMOUNT_PK ON DEF_AMOUNT
(DA_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_AMOUNT ADD (
  CONSTRAINT DEF_AMOUNT_PK
  PRIMARY KEY
  (DA_TYPE)
  USING INDEX DEF_AMOUNT_PK);


