OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmsRelatedTxn
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmsRelatedTxn.so
SOOBJS =  MmsRelatedTxn.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
