ALTER TABLE OL_DEF_INTRA_LOG_GEN_STATUS 
 DROP PRIMARY KEY CASCADE;

CREATE TABLE OL_DEF_INTRA_LOG_GEN_STATUS 
(
  ODAS_STATUS		CHAR(1 BYTE), 
  ODAS_DESC		VARCHAR2(50 BYTE), 
  ODAS_FE_DISPLAY	VARCHAR2(50 BYTE), 
  ODAS_CREATE_TIMESTAMP	DATE			DEFAULT sysdate, 
  ODAS_CREATE_USER	VARCHAR2(20 BYTE), 
  ODAS_UPDATE_TIMESTAMP	DATE			DEFAULT sysdate, 
  ODAS_UPDATE_USER	VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA 
PCTUSED     0 
PCTFREE     10 
INITRANS    1 
MAXTRANS    255 
STORAGE     (
             INITIAL          64K 
             NEXT             1M 
             MINEXTENTS       1 
             MAXEXTENTS       UNLIMITED 
             PCTINCREASE      0 
             BUFFER_POOL      DEFAULT
            ) 
LOGGING 
NOCOMPRESS 
NOCACHE 
MONITORING;

CREATE UNIQUE INDEX OL_DEF_INTRA_LOG_GEN_STATUS_PK ON OL_DEF_INTRA_LOG_GEN_STATUS 
(ODAS_STATUS) 
LOGGING 
TABLESPACE USER_IDX 
PCTFREE     10 
INITRANS    2 
MAXTRANS    255 
STORAGE     (
             INITIAL          64K 
             NEXT             1M 
             MINEXTENTS       1 
             MAXEXTENTS       UNLIMITED 
             PCTINCREASE      0 
             BUFFER_POOL      DEFAULT
            );

ALTER TABLE OL_DEF_INTRA_LOG_GEN_STATUS ADD (
 CONSTRAINT OL_DEF_INTRA_LOG_GEN_STATUS_PK 
 PRIMARY KEY 
 (ODAS_STATUS) 
 USING INDEX OL_DEF_INTRA_LOG_GEN_STATUS_PK 
 ENABLE VALIDATE);
