OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmsStlBankDetail
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmsStlBankDetail.so
SOOBJS =  MmsStlBankDetail.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
