OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOUniqueNumber
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOUniqueNumber.so
SOOBJS = BOUniqueNumber.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
