OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/ClientKeys
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBClientKeys.so
SOOBJS =  ClientKeys.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
