OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLBankAccts
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLBankAccts.so
SOOBJS =  OLBankAccts.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
