ALTER TABLE MMS_RULE_COST_DETAIL
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_RULE_COST_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE MMS_RULE_COST_DETAIL
(
  MCD_COST_ID           INTEGER,
  MCD_CAL_METHOD        CHAR(1 BYTE),
  MCD_TYPE              CHAR(1 BYTE),
  MCD_VALUE             NUMBER(12,5),
  MCD_ADD_VALUE         NUMBER(12,2),
  MCD_MIN_VALUE         NUMBER(12,2),
  MCD_MAX_VALUE         NUMBER(12,2),
  MCD_DISABLED          INTEGER,
  MCD_CREATE_TIMESTAMP  DATE,
  MCD_CREATE_USER       VARCHAR2(20 BYTE),
  MCD_UPDATE_TIMESTAMP  DATE,
  MCD_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MMS_RULE_COST_DETAIL_PK ON MMS_RULE_COST_DETAIL
(MCD_COST_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_RULE_COST_DETAIL ADD (
  CONSTRAINT MMS_RULE_COST_DETAIL_PK
  PRIMARY KEY
  (MCD_COST_ID)
  USING INDEX MMS_RULE_COST_DETAIL_PK
  ENABLE VALIDATE);

ALTER TABLE MMS_RULE_COST_DETAIL ADD (
  CONSTRAINT MMS_RULE_COST_DETAIL_FK01 
  FOREIGN KEY (MCD_CAL_METHOD) 
  REFERENCES MMS_DEF_COST_CAL_METOHD (MCC_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT MMS_RULE_COST_DETAIL_FK02 
  FOREIGN KEY (MCD_TYPE) 
  REFERENCES DEF_AMOUNT (DA_TYPE)
  ENABLE VALIDATE);

