ALTER TABLE DEF_VOID_TXN_CONFIG
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_VOID_TXN_CONFIG CASCADE CONSTRAINTS;

CREATE TABLE DEF_VOID_TXN_CONFIG
(
  VC_TXN_CODE          VARCHAR2(3 BYTE)         NOT NULL,
  VC_CODE              VARCHAR2(50 BYTE)        NOT NULL,
  VC_DESC              VARCHAR2(240 BYTE)       NOT NULL,
  VC_VAL               VARCHAR2(1024 BYTE)      NOT NULL,
  VC_DISABLED          INTEGER                  DEFAULT 0,
  VC_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  VC_CREATE_USER       VARCHAR2(20 BYTE),
  VC_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  VC_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX DEF_VOID_TXN_CONFIG_PK ON DEF_VOID_TXN_CONFIG
(VC_TXN_CODE, VC_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

ALTER TABLE DEF_VOID_TXN_CONFIG ADD (
  CONSTRAINT DEF_VOID_TXN_CONFIG_PK
  PRIMARY KEY
  (VC_TXN_CODE, VC_CODE)
  USING INDEX DEF_VOID_TXN_CONFIG_PK
  ENABLE VALIDATE);

