OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/CrrGlCode
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBCrrGlCode.so
SOOBJS =  CrrGlCode.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
