OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnMgtByUsJLU
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnMgtByUsJLU.so
SOOBJS = TxnMgtByUsJLU.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
