OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmsAcrBalHistory
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmsAcrBalHistory.so
SOOBJS =  MmsAcrBalHistory.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
