OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLDefPayoutGroup
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLDefPayoutGroup.so
SOOBJS =  OLDefPayoutGroup.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
