ALTER TABLE CLIENT_MAGIC
 DROP PRIMARY KEY CASCADE;

DROP TABLE CLIENT_MAGIC CASCADE CONSTRAINTS;

CREATE TABLE CLIENT_MAGIC
(
  CM_CLIENT_ID         VARCHAR2(10 BYTE),
  CM_NUM               VARCHAR2(20 BYTE),
  CM_WORD              VARCHAR2(150 BYTE),
  CM_CUST_ID           VARCHAR2(50 BYTE),
  CM_TXN_GP_ID         INTEGER,
  CM_DISABLED          INTEGER                  DEFAULT 0,
  CM_CREATE_USER       VARCHAR2(20 BYTE),
  CM_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  CM_UPDATE_USER       VARCHAR2(20 BYTE),
  CM_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CLIENT_MAGIC_IDX01 ON CLIENT_MAGIC
(CM_CLIENT_ID, CM_CUST_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX CLIENT_MAGIC_IDX02 ON CLIENT_MAGIC
(CM_CLIENT_ID, CM_NUM, CM_WORD)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX CLIENT_MAGIC_IDX03 ON CLIENT_MAGIC
(CM_CLIENT_ID, CM_NUM, CM_CUST_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX CLIENT_MAGIC_IDX04 ON CLIENT_MAGIC
(CM_CLIENT_ID, CM_TXN_GP_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX CLIENT_MAGIC_PK ON CLIENT_MAGIC
(CM_CLIENT_ID, CM_NUM)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE CLIENT_MAGIC ADD (
  CONSTRAINT CLIENT_MAGIC_PK
  PRIMARY KEY
  (CM_CLIENT_ID, CM_NUM)
  USING INDEX CLIENT_MAGIC_PK
  ENABLE VALIDATE);

ALTER TABLE CLIENT_MAGIC ADD (
  CONSTRAINT CLIENT_MAGIC_FK01 
  FOREIGN KEY (CM_CLIENT_ID) 
  REFERENCES CLIENTS (CLIENT_ID)
  ENABLE VALIDATE);

ALTER TABLE CLIENT_MAGIC ADD (
  CONSTRAINT CLIENT_MAGIC_FK02 
  FOREIGN KEY (CM_CLIENT_ID, CM_TXN_GP_ID) 
  REFERENCES CLIENT_MAGIC_GP_STATUS (GS_CLIENT_ID,GS_TXN_GP_ID)
  ENABLE VALIDATE);


