OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnOiaOnUsCOM
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnOiaOnUsCOM.so
SOOBJS = TxnOiaOnUsCOM.o

include $(HOME)/config/Make.rules

LDLIBS += 
CPPFLAGS += 
all	: $(COMPSO)
