OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/TxnAlertLog
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBTxnAlertLog.so
SOOBJS =  TxnAlertLog.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
