OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/PidBankGroupMapping
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBPidBankGroupMapping.so
SOOBJS =  PidBankGroupMapping.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
