OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLBatchRelation/elvis
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLBatchRelation.so
SOOBJS =  OLBatchRelation.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
