OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MobileBankUrl
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMobileBankUrl.so
SOOBJS = MobileBankUrl.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
