


ALTER TABLE DEF_KEY_TYPE
 ADD (DK_KEY_GROUP  VARCHAR2(3 BYTE));

ALTER TABLE DEF_KEY_TYPE
 ADD CONSTRAINT DEF_KEY_TYPE_FK01 
  FOREIGN KEY (DK_KEY_GROUP) 
  REFERENCES DEF_KEY_GROUP (DKG_TYPE)
  ENABLE VALIDATE;
  