ALTER TABLE DEF_KEY_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_KEY_TYPE CASCADE CONSTRAINTS;

CREATE TABLE DEF_KEY_TYPE
(
  DK_TYPE              VARCHAR2(3 BYTE),
  DK_DESC              VARCHAR2(50 BYTE),
  DK_CREATE_USER       VARCHAR2(20 BYTE),
  DK_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  DK_UPDATE_USER       VARCHAR2(20 BYTE),
  DK_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEF_KEY_TYPE_PK ON DEF_KEY_TYPE
(DK_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_KEY_TYPE ADD (
  CONSTRAINT DEF_KEY_TYPE_PK
  PRIMARY KEY
  (DK_TYPE)
  USING INDEX DEF_KEY_TYPE_PK);
