ALTER TABLE CUSTOMER_BLACK_LIST
 DROP PRIMARY KEY CASCADE;

DROP TABLE CUSTOMER_BLACK_LIST CASCADE CONSTRAINTS;

CREATE TABLE CUSTOMER_BLACK_LIST
(
  CBL_MERCHANT_ID       VARCHAR2(15 BYTE),
  CBL_CUST_ID           VARCHAR2(10 BYTE),
  CBL_DISABLED		INTEGER DEFAULT 0,
  CBL_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  CBL_CREATE_USER       VARCHAR2(20 BYTE),
  CBL_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  CBL_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX CUSTOMER_BLACK_LIST_IDX01 ON CUSTOMER_BLACK_LIST
(CBL_CUST_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX CUSTOMER_BLACK_LIST_PK ON CUSTOMER_BLACK_LIST
(CBL_MERCHANT_ID,CBL_CUST_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE CUSTOMER_BLACK_LIST ADD (
  CONSTRAINT CUSTOMER_BLACK_LIST_PK
  PRIMARY KEY
  (CBL_MERCHANT_ID,CBL_CUST_ID)
  USING INDEX CUSTOMER_BLACK_LIST_PK
  ENABLE VALIDATE);



ALTER TABLE CUSTOMER_BLACK_LIST ADD (
  CONSTRAINT CUSTOMER_BLACK_LIST_FK01 
  FOREIGN KEY (CBL_MERCHANT_ID) 
  REFERENCES MERCH_DETAIL (MERCHANT_ID)
  ENABLE VALIDATE);

