ALTER TABLE RULE_TXN_RESERVE
 DROP PRIMARY KEY CASCADE;

DROP TABLE RULE_TXN_RESERVE CASCADE CONSTRAINTS;

CREATE TABLE RULE_TXN_RESERVE
(
  RS_PARTY_TYPE        CHAR(1 BYTE),
  RS_PARTY_ID          VARCHAR2(15 BYTE),
  RS_AMOUNT_ID         INTEGER,
  RS_DISABLED          INTEGER                  DEFAULT 0,
  RS_CREATE_TIMESTAMP  DATE,
  RS_CREATE_USER       VARCHAR2(20 BYTE),
  RS_UPDATE_TIMESTAMP  DATE,
  RS_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX RULE_TXN_RESERVE_IDX01 ON RULE_TXN_RESERVE
(RS_PARTY_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RULE_TXN_RESERVE_IDX02 ON RULE_TXN_RESERVE
(RS_PARTY_TYPE, RS_PARTY_ID, RS_DISABLED)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RULE_TXN_RESERVE_IDX03 ON RULE_TXN_RESERVE
(RS_PARTY_TYPE, RS_DISABLED)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RULE_TXN_RESERVE_PK ON RULE_TXN_RESERVE
(RS_PARTY_TYPE, RS_PARTY_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE RULE_TXN_RESERVE ADD (
  CONSTRAINT RULE_TXN_RESERVE_PK
  PRIMARY KEY
  (RS_PARTY_TYPE, RS_PARTY_ID)
  USING INDEX RULE_TXN_RESERVE_PK);

ALTER TABLE RULE_TXN_RESERVE ADD (
  CONSTRAINT RULE_TXN_RESERVE_FK01
  FOREIGN KEY (RS_PARTY_TYPE) 
  REFERENCES DEF_PARTY_TYPE (DP_TYPE),
  CONSTRAINT RULE_TXN_RESERVE_FK02
  FOREIGN KEY (RS_AMOUNT_ID) 
  REFERENCES RULE_AMOUNT (RA_ID));
