OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/CrrJnlHeaderSeq
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBCrrJnlHeaderSeq.so
SOOBJS =  CrrJnlHeaderSeq.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
