OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/PspRedirectLog
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBPspRedirectLog.so
SOOBJS =  PspRedirectLog.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
