OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnTlgOnUsCOM
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnTlgOnUsCOM.so
SOOBJS = TxnTlgOnUsCOM.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
