OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmsManualVoidLog
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmsManualVoidLog.so
SOOBJS =  MmsManualVoidLog.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
