OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnWebOnUsACK
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnWebOnUsACK.so
SOOBJS = TxnWebOnUsACK.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
