OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnWebOnUsEGP
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnWebOnUsEGP.so
SOOBJS = TxnWebOnUsEGP.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
