OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/TxnCardTypeLog
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBTxnCardTypeLog.so
SOOBJS = TxnCardTypeLog.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
