OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MerchantApproveQueueHd
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMerchantApproveQueueHd.so
SOOBJS =  MerchantApproveQueueHd.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
