OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/RuleExMarkup
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBRuleExMarkup.so
SOOBJS =  RuleExMarkup.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
