OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLPayoutApiPregenHD
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLPayoutApiPregenHD.so
SOOBJS =  OLPayoutApiPregenHD.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
