OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmsAffectFXDT
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmsAffectFXDT.so
SOOBJS =  MmsAffectFXDT.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
