OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLSemiAutoReconTxncodeMap
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLSemiAutoReconTxncodeMap.so
SOOBJS =  OLSemiAutoReconTxncodeMap.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
