

ALTER TABLE RULE_PSP_LB_CRITERIA
 ADD (RC_CARD_TYPE_OPT  CHAR(1 BYTE)                    DEFAULT 'D');

----Drop constraint
ALTER TABLE RULE_PSP_LB_CRITERIA
DROP CONSTRAINT RULE_PSP_LB_CRITERIA_PK;

----Ensure the index have been dropped
DECLARE
  COUNT_INDEXES INTEGER;
BEGIN
    select count(*) INTO COUNT_INDEXES from dba_indexes 
    where table_name='RULE_PSP_LB_CRITERIA'
    and owner='PHUSER'
    and index_name = 'RULE_PSP_LB_CRITERIA_PK';

  IF COUNT_INDEXES > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX RULE_PSP_LB_CRITERIA_PK';
  END IF;
END;
/


----Create constraint (together with index)
ALTER TABLE RULE_PSP_LB_CRITERIA ADD 
  CONSTRAINT RULE_PSP_LB_CRITERIA_PK
  PRIMARY KEY
  (RC_CHANNEL_CODE, RC_SERVICE_CODE, RC_PAYMENT_METHOD, RC_COUNTRY, RC_CCY,
   RC_SCHEDULER_ID, RC_PARTY_TYPE, RC_PARTY_ID, RC_BUSINESS_TYPE, RC_CRITERIA_POOL_ID,
   RC_MIN_TRANSACTION_AMOUNT, RC_CARD_TYPE_OPT)
  USING INDEX
  tablespace user_idx;
