OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnWebOnUs2YPY
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnWebOnUs2YPY.so
SOOBJS = TxnWebOnUs2YPY.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
