ALTER TABLE PHUSER.PSP_FUNDS_HOLD
 DROP PRIMARY KEY CASCADE;

DROP TABLE PHUSER.PSP_FUNDS_HOLD CASCADE CONSTRAINTS;

CREATE TABLE PHUSER.PSP_FUNDS_HOLD
(
  P_PSP_ID          VARCHAR2(10 BYTE),
  P_MERCHANT_ID     VARCHAR2(15 BYTE),
  P_CURRENCY_ID     VARCHAR(3 BYTE),
  P_PSP_HOLD_TYPE   CHAR(2 BYTE),
  P_AMT             NUMBER(14,2)                DEFAULT 0,
  CREATE_TIMESTAMP  DATE                        DEFAULT sysdate,
  CREATE_USER       VARCHAR2(20 BYTE),
  UPDATE_TIMESTAMP  DATE                        DEFAULT sysdate,
  UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN PHUSER.PSP_FUNDS_HOLD.P_PSP_HOLD_TYPE IS 'FT- Float, PO - Payout, SM - Settlement';



CREATE UNIQUE INDEX PHUSER.PSP_FUNDS_HOLD_PK ON PHUSER.PSP_FUNDS_HOLD
(P_PSP_ID, P_MERCHANT_ID, P_CURRENCY_ID, P_PSP_HOLD_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE PHUSER.PSP_FUNDS_HOLD ADD (
  CONSTRAINT PSP_FUNDS_HOLD_PK
  PRIMARY KEY
  (P_PSP_ID, P_MERCHANT_ID, P_CURRENCY_ID, P_PSP_HOLD_TYPE)
  USING INDEX PHUSER.PSP_FUNDS_HOLD_PK);


