OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MerchantBucket
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMerchantBucket.so
SOOBJS =  MerchantBucket.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
