OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/PayoutGeneratedTmp
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBPayoutGeneratedTmp.so
SOOBJS =  PayoutGeneratedTmp.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
