OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLPIDBal
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLPIDBal.so
SOOBJS =  OLPIDBal.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
