OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=import_pay_selection.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o import_pay_selection.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
