OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=match_hhp_dsp.exec
BATCHOBJS=$(OBJHOME)/batchcommon.o match_hhp_dsp.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=   -lObjPtr
all: $(BATCHEXE)
