OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=hhp_to_cms_report.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o hhp_to_cms_report.o
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
