OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/TxnExDetail
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBTxnExDetail.so
SOOBJS =  TxnExDetail.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
