OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/PspParamCheck
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBPspParamCheck.so
SOOBJS = PspParamCheck.o

include $(HOME)/config/Make.rules

LDLIBS +=

all : $(COMPSO)
