


CREATE TABLE TXN_SUPP_INFO
(
  TS_TXN_ID            VARCHAR2(16 BYTE),
  TS_INFO_TYPE         VARCHAR2(64 BYTE),
  TS_EXEC_SEQ          INTEGER,
  TS_INFO_VALUE        VARCHAR2(2048 BYTE),
  TS_CREATE_TIMESTAMP  DATE,
  TS_CREATE_USER       VARCHAR2(20 BYTE),
  TS_UPDATE_TIMESTAMP  DATE,
  TS_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE INDEX TXN_SUPP_INFO_IDX01 ON TXN_SUPP_INFO
(TS_TXN_ID, TS_INFO_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX TXN_SUPP_INFO_PK ON TXN_SUPP_INFO
(TS_TXN_ID, TS_INFO_TYPE, TS_EXEC_SEQ)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE TXN_SUPP_INFO ADD (
  CONSTRAINT TXN_SUPP_INFO_PK
  PRIMARY KEY
  (TS_TXN_ID, TS_INFO_TYPE, TS_EXEC_SEQ)
  USING INDEX TXN_SUPP_INFO_PK
  ENABLE VALIDATE);

