ALTER TABLE PAR_TXN_DATA_1115
 DROP PRIMARY KEY CASCADE;

DROP TABLE PAR_TXN_DATA_1115 CASCADE CONSTRAINTS;

CREATE TABLE PAR_TXN_DATA_1115
(
  PTD_TXN_SEQ           NUMBER(10),
  PTD_POST_DATE         DATE			NOT NULL,
  PTD_TXN_DATE          DATE			NOT NULL,
  PTD_TXN_MERCH_NMB     VARCHAR2(50 BYTE)	NOT NULL,
  PTD_TXN_NMB           VARCHAR2(16 BYTE)	NOT NULL,
  PTD_MERCH_REF         VARCHAR2(50 BYTE),
  PTD_TXN_TYPE          VARCHAR2(50 BYTE)	NOT NULL,
  PTD_TXN_STATUS        VARCHAR2(50 BYTE)	NOT NULL,
  PTD_TXN_STATUS_GROUP  VARCHAR2(50 BYTE)	NOT NULL,
  PTD_TO_CCY            VARCHAR2(3 BYTE),
  PTD_TO_AMOUNT         NUMBER(12,2),
  PTD_CCY               VARCHAR2(3 BYTE)	NOT NULL,
  PTD_AMOUNT            NUMBER(12,2)		NOT NULL,
  PTD_FEE               NUMBER(12,2)		NOT NULL,
  PTD_EX_RATE           NUMBER(14,5)		NOT NULL,
  PTD_MARKUP_AMT        NUMBER(12,2)		NOT NULL,
  --PTD_BALANCE           NUMBER(12,2),
  PTD_PSP_TYPE_CODE     VARCHAR2(50 BYTE),
  PTD_ORDER_ID          VARCHAR2(50 BYTE),
  PTD_GATE_ID           VARCHAR2(50 BYTE),
  PTD_CLIENT_IP         VARCHAR2(15 BYTE),
  PTD_TXN_NOTE          VARCHAR2(400 BYTE),
  PTD_PSP_TXN_ID        VARCHAR2(30 BYTE),
  PTD_PSP_TXN_DATE      VARCHAR2(14 BYTE),
  PTD_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  PTD_CREATE_USER       VARCHAR2(20 BYTE),
  PTD_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  PTD_UPDATE_USER       VARCHAR2(20 BYTE),
  PTD_FILE_NAME         VARCHAR2(50 BYTE),
  PTD_PROC_STATUS       VARCHAR2(10 BYTE),
  PTD_PO_PSP_STATUS     VARCHAR2(10 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX PAR_TXN_DATA_1115_IDX01 ON PAR_TXN_DATA_1115
(PTD_TXN_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX PAR_TXN_DATA_1115_IDX02 ON PAR_TXN_DATA_1115
(PTD_TXN_MERCH_NMB)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX PAR_TXN_DATA_1115_IDX03 ON PAR_TXN_DATA_1115
(PTD_TXN_NMB)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX PAR_TXN_DATA_1115_IDX04 ON PAR_TXN_DATA_1115
(PTD_TXN_TYPE, PTD_TXN_STATUS)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX PAR_TXN_DATA_1115_IDX05 ON PAR_TXN_DATA_1115
(PTD_PSP_TYPE_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

CREATE INDEX PAR_TXN_DATA_1115_IDX06 ON PAR_TXN_DATA_1115
(PTD_FILE_NAME)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

CREATE INDEX PAR_TXN_DATA_1115_IDX07 ON PAR_TXN_DATA_1115
(PTD_PROC_STATUS)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PAR_TXN_DATA_1115_PK ON PAR_TXN_DATA_1115
(PTD_TXN_SEQ)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PAR_TXN_DATA_1115 ADD (
  CONSTRAINT PAR_TXN_DATA_1115_PK
  PRIMARY KEY
  (PTD_TXN_SEQ)
  USING INDEX PAR_TXN_DATA_1115_PK
  ENABLE VALIDATE);

