OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnOlnOnUsCOM
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnOlnOnUsCOM.so
SOOBJS = TxnOlnOnUsCOM.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
