OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLTransaction
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLTransaction.so
SOOBJS =  OLTransaction.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
