ALTER TABLE RULE_OPERATOR_TYPE_DETAIL
 DROP PRIMARY KEY CASCADE;

DROP TABLE RULE_OPERATOR_TYPE_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE RULE_OPERATOR_TYPE_DETAIL
(
  ROD_TYPE              CHAR(2 BYTE)            NOT NULL,
  ROD_TIER_ID           INTEGER                 NOT NULL,
  ROD_AMT_PCT           NUMBER(12,2)            DEFAULT 1,
  ROD_AMT_MIN           NUMBER(12,2)            NOT NULL,
  ROD_AMT_MAX           NUMBER(12,2)            NOT NULL,
  ROD_REMARK            VARCHAR2(255 BYTE),
  ROD_DISABLED          INTEGER                 DEFAULT 0,
  ROD_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  ROD_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  ROD_CREATE_USER       VARCHAR2(20 BYTE),
  ROD_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX RULE_OPERATOR_TYPE_DETAIL_PK ON RULE_OPERATOR_TYPE_DETAIL
(ROD_TYPE, ROD_TIER_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE RULE_OPERATOR_TYPE_DETAIL ADD (
  CONSTRAINT RULE_OPERATOR_TYPE_DETAIL_PK
  PRIMARY KEY
  (ROD_TYPE, ROD_TIER_ID)
  USING INDEX RULE_OPERATOR_TYPE_DETAIL_PK
  ENABLE VALIDATE);

