OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOCrrMonthEnd
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOCrrMonthEnd.so
SOOBJS = BOCrrMonthEnd.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
