ALTER TABLE OL_DEF_SIM_CARD_STATUS
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_DEF_SIM_CARD_STATUS CASCADE CONSTRAINTS;

CREATE TABLE OL_DEF_SIM_CARD_STATUS
(
  DSCS_STATUS_CODE       CHAR(1 BYTE),
  DSCS_STATUS_DESC       VARCHAR2(50 BYTE),
  DSCS_CREATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  DSCS_CREATE_USER       VARCHAR2(20 BYTE),
  DSCS_UPDATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  DSCS_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_DEF_SIM_CARD_STATUS_PK ON OL_DEF_SIM_CARD_STATUS
(DSCS_STATUS_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_DEF_SIM_CARD_STATUS ADD (
  CONSTRAINT OL_DEF_SIM_CARD_STATUS_PK
  PRIMARY KEY
  (DSCS_STATUS_CODE)
  USING INDEX OL_DEF_SIM_CARD_STATUS_PK
  ENABLE VALIDATE);

