OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MobBankSelect
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMobBankSelect.so
SOOBJS =  MobBankSelect.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
