ALTER TABLE PAR_PO_REV_TXN_SEQ_MAP
 DROP PRIMARY KEY CASCADE;

DROP TABLE PAR_PO_REV_TXN_SEQ_MAP CASCADE CONSTRAINTS;

CREATE TABLE PAR_PO_REV_TXN_SEQ_MAP
(
  PR_VNC_REF_NUM       VARCHAR2(16 BYTE),
  PR_VOA_TXN_CODE      VARCHAR2(16 BYTE),
  PR_CREATE_TIMESTAMP  DATE,
  PR_CREATE_USER       VARCHAR2(20 BYTE),
  PR_UPDATE_TIMESTAMP  DATE,
  PR_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX PAR_PO_REV_TXN_SEQ_MAP_IDX01 ON PAR_PO_REV_TXN_SEQ_MAP
(PR_VOA_TXN_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PAR_PO_REV_TXN_SEQ_MAP_PK ON PAR_PO_REV_TXN_SEQ_MAP
(PR_VNC_REF_NUM)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PAR_PO_REV_TXN_SEQ_MAP ADD (
  CONSTRAINT PAR_PO_REV_TXN_SEQ_MAP_PK
  PRIMARY KEY
  (PR_VNC_REF_NUM)
  USING INDEX PAR_PO_REV_TXN_SEQ_MAP_PK
  ENABLE VALIDATE);

