OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOOLDepositMatch
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOOLDepositMatch.so
SOOBJS = BOOLDepositMatch.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
