ALTER TABLE OL_DEPOSIT_REQUEST_BANK
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_DEPOSIT_REQUEST_BANK CASCADE CONSTRAINTS;

CREATE TABLE OL_DEPOSIT_REQUEST_BANK
(
  DB_BANK_NAME         VARCHAR2(150 BYTE),
  DB_BANK_CODE         VARCHAR2(10 BYTE),
  DB_CREATE_USER       VARCHAR2(20 BYTE),
  DB_UPDATE_USER       VARCHAR2(20 BYTE),
  DB_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  DB_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_DEPOSIT_REQUEST_BANK_PK ON OL_DEPOSIT_REQUEST_BANK
(DB_BANK_NAME)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_DEPOSIT_REQUEST_BANK ADD (
  CONSTRAINT OL_DEPOSIT_REQUEST_BANK_PK
  PRIMARY KEY
  (DB_BANK_NAME)
  USING INDEX OL_DEPOSIT_REQUEST_BANK_PK
  ENABLE VALIDATE);

ALTER TABLE OL_DEPOSIT_REQUEST_BANK ADD (
  CONSTRAINT OL_DEPOSIT_REQUEST_BANK_FK01
  FOREIGN KEY (DB_BANK_CODE)
  REFERENCES DEF_BANK (DB_INT_BANK_CODE)
  ENABLE VALIDATE);
