ALTER TABLE OL_DEPOSIT_REQUEST_DETAIL
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_DEPOSIT_REQUEST_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE OL_DEPOSIT_REQUEST_DETAIL
(
  OLDD_FILE_ID               NUMBER(16),
  OLDD_DEPOSIT_SEQ           INTEGER,
  OLDD_TXN_ID                VARCHAR2(16 BYTE),
  OLDD_INT_BANK_CODE         VARCHAR2(10 BYTE),
  OLDD_BANK_ACCT_NUM         VARCHAR2(50 BYTE),
  OLDD_SERVICE_CODE          CHAR(3 BYTE),
  OLDD_COUNTRY               CHAR(2 BYTE),
  OLDD_MERCHANT_REF          VARCHAR2(25 BYTE),
  OLDD_CUST_DEPOSIT_DATETIME VARCHAR2(14 BYTE),
  OLDD_DEPOSIT_BANK          VARCHAR2(150 BYTE),
  OLDD_DEPOSIT_REF           VARCHAR2(150 BYTE),
  OLDD_DEPOSIT_AMOUNT        NUMBER(12,2),
  OLDD_DEPOSIT_CCY           VARCHAR2(3 BYTE),
  OLDD_DEPOSIT_FLOW          CHAR(1 BYTE),
  OLDD_CUST_DEPOSIT_DT_PROV  INTEGER,
  OLDD_CREATE_TIMESTAMP      DATE,
  OLDD_CREATE_USER           VARCHAR2(20 BYTE),
  OLDD_UPDATE_TIMESTAMP      DATE,
  OLDD_UPDATE_USER           VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX OL_DEPOSIT_REQUEST_DETAIL_PK ON OL_DEPOSIT_REQUEST_DETAIL
(OLDD_FILE_ID, OLDD_DEPOSIT_SEQ)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

CREATE UNIQUE INDEX OL_DEPOSIT_REQ_DETAIL_IDX01 ON OL_DEPOSIT_REQUEST_DETAIL
(OLDD_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

CREATE INDEX OL_DEPOSIT_REQ_DETAIL_IDX02 ON OL_DEPOSIT_REQUEST_DETAIL
(OLDD_INT_BANK_CODE, OLDD_BANK_ACCT_NUM)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

CREATE INDEX OL_DEPOSIT_REQ_DETAIL_IDX03 ON OL_DEPOSIT_REQUEST_DETAIL
(OLDD_MERCHANT_REF)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_DEPOSIT_REQUEST_DETAIL ADD (
  CONSTRAINT OL_DEPOSIT_REQUEST_DETAIL_PK
  PRIMARY KEY
  (OLDD_FILE_ID, OLDD_DEPOSIT_SEQ)
  USING INDEX OL_DEPOSIT_REQUEST_DETAIL_PK
  ENABLE VALIDATE);

ALTER TABLE OL_DEPOSIT_REQUEST_DETAIL ADD (
  CONSTRAINT OL_DEPOSIT_REQUEST_DETAIL_FK01 
  FOREIGN KEY (OLDD_FILE_ID) 
  REFERENCES OL_DEPOSIT_REQUEST_HEADER (OLDH_FILE_ID)
  ENABLE VALIDATE,
  CONSTRAINT OL_DEPOSIT_REQUEST_DETAIL_FK02
  FOREIGN KEY (OLDD_TXN_ID) 
  REFERENCES OL_TXN_HEADER (OTH_TXN_ID)
  ENABLE VALIDATE,
  CONSTRAINT OL_DEPOSIT_REQUEST_DETAIL_FK03
  FOREIGN KEY (OLDD_INT_BANK_CODE, OLDD_BANK_ACCT_NUM)
  REFERENCES OL_BANK_ACCTS (OB_INT_BANK_CODE, OB_BANK_ACCT_NUM)
  ENABLE VALIDATE,
  CONSTRAINT OL_DEPOSIT_REQUEST_DETAIL_FK04
  FOREIGN KEY (OLDD_SERVICE_CODE)
  REFERENCES DEF_SERVICE_CODE (SC_CODE)
  ENABLE VALIDATE,
  CONSTRAINT OL_DEPOSIT_REQUEST_DETAIL_FK05
  FOREIGN KEY (OLDD_COUNTRY)
  REFERENCES COUNTRY (COUNTRY_CODE)
  ENABLE VALIDATE,
  CONSTRAINT OL_DEPOSIT_REQUEST_DETAIL_FK06
  FOREIGN KEY (OLDD_DEPOSIT_CCY)
  REFERENCES DEF_CURRENCY (DC_CCY_ID)
  ENABLE VALIDATE);

