ALTER TABLE MMS_AFFECT_FX_DT
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_AFFECT_FX_DT CASCADE CONSTRAINTS;

CREATE TABLE MMS_AFFECT_FX_DT
(
  MAF_FX_ID             VARCHAR2(16 BYTE),
  MAF_FX_SEQ            INTEGER,
  MAF_DIRECTION         CHAR(1 BYTE),
  MAF_ENTITY_ID         VARCHAR2(20 BYTE),
  MAF_ACR_IND           INTEGER,
  MAF_ORG_CCY           VARCHAR2(3 BYTE)        DEFAULT 000,
  MAF_ORG_AMOUNT        NUMBER(14,2)            DEFAULT 0,
  MAF_CCY               VARCHAR2(3 BYTE),
  MAF_AMOUNT            NUMBER(14,2)            DEFAULT 0,
  MAF_CALCULATE_IND     INTEGER                 DEFAULT 0,
  MAF_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  MAF_CREATE_USER       VARCHAR2(20 BYTE),
  MAF_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  MAF_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX MMS_AFFECT_FX_DT_IDX01 ON MMS_AFFECT_FX_DT
(MAF_FX_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX MMS_AFFECT_FX_DT_PK ON MMS_AFFECT_FX_DT
(MAF_FX_ID, MAF_FX_SEQ)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_AFFECT_FX_DT ADD (
  CONSTRAINT MMS_AFFECT_FX_DT_PK
  PRIMARY KEY
  (MAF_FX_ID, MAF_FX_SEQ)
  USING INDEX MMS_AFFECT_FX_DT_PK
  ENABLE VALIDATE);

ALTER TABLE MMS_AFFECT_FX_DT ADD (
  CONSTRAINT MMS_AFFECT_FX_DT_FK01 
  FOREIGN KEY (MAF_FX_ID) 
  REFERENCES MMS_TXN_HEADER (MTH_TXN_ID)
  ENABLE VALIDATE,
  CONSTRAINT MMS_AFFECT_FX_DT_FK02 
  FOREIGN KEY (MAF_DIRECTION) 
  REFERENCES MMS_DEF_FUNDS_DIRECTION (MFD_TYPE)
  ENABLE VALIDATE);

