OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLTxnEngineActionList
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLTxnEngineActionList.so
SOOBJS =  OLTxnEngineActionList.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
