ALTER TABLE OL_MATCH_TIME_INTERVAL
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_MATCH_TIME_INTERVAL CASCADE CONSTRAINTS;

CREATE TABLE OL_MATCH_TIME_INTERVAL
(
  OMTI_BANK_CODE         VARCHAR2(20 BYTE),
  OMTI_LEVEL             CHAR(1 BYTE),
  OMTI_SERVICE_CODE      CHAR(3 BYTE),
  OMTI_PARTY_ID          VARCHAR2(50 BYTE),
  OMTI_ONUS_GRP_ID       INTEGER,
  OMTI_OFFUS_GRP_ID      INTEGER,
  OMTI_DISABLED          INTEGER                DEFAULT 0,
  OMTI_CREATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  OMTI_UPDATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  OMTI_CREATE_USER       VARCHAR2(20 BYTE),
  OMTI_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_MATCH_TIME_INTERVAL_PK ON OL_MATCH_TIME_INTERVAL
(OMTI_BANK_CODE, OMTI_SERVICE_CODE, OMTI_LEVEL, OMTI_PARTY_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_MATCH_TIME_INTERVAL ADD (
  CONSTRAINT OL_MATCH_TIME_INTERVAL_PK
  PRIMARY KEY
  (OMTI_BANK_CODE, OMTI_SERVICE_CODE, OMTI_LEVEL, OMTI_PARTY_ID)
  USING INDEX OL_MATCH_TIME_INTERVAL_PK
  ENABLE VALIDATE);

ALTER TABLE OL_MATCH_TIME_INTERVAL ADD (
  CONSTRAINT OL_MATCH_TIME_INTERVAL_FK01 
  FOREIGN KEY (OMTI_BANK_CODE) 
  REFERENCES DEF_BANK (DB_INT_BANK_CODE)
  ENABLE VALIDATE);

ALTER TABLE OL_MATCH_TIME_INTERVAL ADD (
  CONSTRAINT OL_MATCH_TIME_INTERVAL_FK02
  FOREIGN KEY (OMTI_SERVICE_CODE)
  REFERENCES DEF_SERVICE_CODE (SC_CODE)
  ENABLE VALIDATE);

