ALTER TABLE OL_DEF_MATCH_DAY
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_DEF_MATCH_DAY CASCADE CONSTRAINTS;

CREATE TABLE OL_DEF_MATCH_DAY
(
  OMD_TYPE              VARCHAR2(20 BYTE),
  OMD_DESC              VARCHAR2(100 BYTE),
  OMD_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  OMD_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  OMD_CREATE_USER       VARCHAR2(20 BYTE),
  OMD_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_DEF_MATCH_DAY_PK ON OL_DEF_MATCH_DAY
(OMD_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_DEF_MATCH_DAY ADD (
  CONSTRAINT OL_DEF_MATCH_DAY_PK
  PRIMARY KEY
  (OMD_TYPE)
  USING INDEX OL_DEF_MATCH_DAY_PK
  ENABLE VALIDATE);

