ALTER TABLE OL_DEF_MATCH_TIME
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_DEF_MATCH_TIME CASCADE CONSTRAINTS;

CREATE TABLE OL_DEF_MATCH_TIME
(
  OMT_ID                INTEGER,
  OMT_DESC              VARCHAR2(100 BYTE),
  OMT_START_TIME        VARCHAR2(6 BYTE),
  OMT_END_TIME          VARCHAR2(6 BYTE),
  OMT_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  OMT_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  OMT_CREATE_USER       VARCHAR2(20 BYTE),
  OMT_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_DEF_MATCH_TIME_PK ON OL_DEF_MATCH_TIME
(OMT_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_DEF_MATCH_TIME ADD (
  CONSTRAINT OL_DEF_MATCH_TIME_PK
  PRIMARY KEY
  (OMT_ID)
  USING INDEX OL_DEF_MATCH_TIME_PK
  ENABLE VALIDATE);

