ALTER TABLE OL_MATCH_DAY_TIME_GROUP
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_MATCH_DAY_TIME_GROUP CASCADE CONSTRAINTS;

CREATE TABLE OL_MATCH_DAY_TIME_GROUP
(
  ODTG_GRP_ID            INTEGER,
  ODTG_DAY_TYPE          VARCHAR2(20 BYTE),
  ODTG_TIME_ID           INTEGER,
  ODTG_BF_MINS           INTEGER,
  ODTG_AF_MINS           INTEGER,
  ODTG_CREATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  ODTG_UPDATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  ODTG_CREATE_USER       VARCHAR2(20 BYTE),
  ODTG_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_MATCH_DAY_TIME_GROUP_PK ON OL_MATCH_DAY_TIME_GROUP
(ODTG_GRP_ID, ODTG_DAY_TYPE, ODTG_TIME_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_MATCH_DAY_TIME_GROUP ADD (
  CONSTRAINT OL_MATCH_DAY_TIME_GROUP_PK
  PRIMARY KEY
  (ODTG_GRP_ID, ODTG_DAY_TYPE, ODTG_TIME_ID)
  USING INDEX OL_MATCH_DAY_TIME_GROUP_PK
  ENABLE VALIDATE);

ALTER TABLE OL_MATCH_DAY_TIME_GROUP ADD (
  CONSTRAINT OL_MATCH_DAY_TIME_GROUP_FK01 
  FOREIGN KEY (ODTG_DAY_TYPE) 
  REFERENCES OL_DEF_MATCH_DAY (OMD_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OL_MATCH_DAY_TIME_GROUP_FK02 
  FOREIGN KEY (ODTG_TIME_ID) 
  REFERENCES OL_DEF_MATCH_TIME (OMT_ID)
  ENABLE VALIDATE);

