CREATE TABLE PSP_TXN_CHECK_RPT_LOG
(
  PL_RPT_GEN_ID        INTEGER                  NOT NULL,
  PL_RPT_GEN_DATETIME  VARCHAR2(14 BYTE)        NOT NULL,
  PL_RPT_TYPE          VARCHAR2(50 BYTE)        NOT NULL,
  PL_SEQ               INTEGER                  NOT NULL,
  PL_PARTY_TYPE        CHAR(1 BYTE),
  PL_PARTY_ID          VARCHAR2(10 BYTE),
  PL_PARTY_NAME        VARCHAR2(50 BYTE),
  PL_BANK_CODE         VARCHAR2(10 BYTE),
  PL_BANK_NAME         VARCHAR2(50 BYTE),
  PL_DUR_START         DATE,
  PL_DUR_END           DATE,
  PL_SUCC_CNT          INTEGER,
  PL_PEND_CNT          INTEGER,
  PL_TOTAL_CNT         INTEGER,
  PL_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  PL_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  PL_CREATE_USER       VARCHAR2(20 BYTE),
  PL_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PSP_TXN_CHECK_RPT_LOG_PK ON PSP_TXN_CHECK_RPT_LOG
(PL_RPT_GEN_ID, PL_RPT_GEN_DATETIME, PL_RPT_TYPE, PL_SEQ)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PSP_TXN_CHECK_RPT_LOG ADD (
  CONSTRAINT PSP_TXN_CHECK_RPT_LOG_PK
  PRIMARY KEY
  (PL_RPT_GEN_ID, PL_RPT_GEN_DATETIME, PL_RPT_TYPE, PL_SEQ)
  USING INDEX PSP_TXN_CHECK_RPT_LOG_PK
  ENABLE VALIDATE);

