OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLPspTxnEngine
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLPspTxnEngine.so
SOOBJS =  OLPspTxnEngine.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
