OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/ParClients
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBParClients.so
SOOBJS =  ParClients.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
