OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/CustomerBlackList
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBCustomerBlackList.so
SOOBJS =  CustomerBlackList.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
