OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLMatchTimeInterval
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLMatchTimeInterval.so
SOOBJS =  OLMatchTimeInterval.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
