OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/DefVoidTxnConfig
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBDefVoidTxnConfig.so
SOOBJS = DefVoidTxnConfig.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
