ALTER TABLE TXN_FEE_CHARGE
 DROP PRIMARY KEY CASCADE;

DROP TABLE TXN_FEE_CHARGE CASCADE CONSTRAINTS;

CREATE TABLE TXN_FEE_CHARGE
(
  TF_TXN_ID            VARCHAR2(16 BYTE),
  TF_CHG_TYPE          CHAR(2 BYTE),
  TF_PARTY_TYPE        CHAR(1 BYTE),
  TF_CCY               CHAR(3 BYTE),
  TF_FEE               NUMBER(14,2),
  TF_CREATE_TIMESTAMP  DATE,
  TF_CREATE_USER       VARCHAR2(20 BYTE),
  TF_UPDATE_TIMESTAMP  DATE,
  TF_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX TXN_FEE_CHANGE_IDX01 ON TXN_FEE_CHARGE
(TF_TXN_ID)
LOGGING
TABLESPACE USER_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX TXN_FEE_CHARGE_IDX02 ON TXN_FEE_CHARGE
(TF_TXN_ID, TF_PARTY_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX TXN_FEE_CHARGE_PK ON TXN_FEE_CHARGE
(TF_TXN_ID, TF_CHG_TYPE, TF_PARTY_TYPE, TF_CCY)
LOGGING
TABLESPACE USER_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE TXN_FEE_CHARGE ADD (
  CONSTRAINT TXN_FEE_CHARGE_PK
  PRIMARY KEY
  (TF_TXN_ID, TF_CHG_TYPE, TF_PARTY_TYPE, TF_CCY)
  USING INDEX TXN_FEE_CHARGE_PK);

