OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/NonPostingDateResp
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBNonPostingDateResp.so
SOOBJS =  NonPostingDateResp.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
