


ALTER TABLE OL_STATEMENT_TMP ADD OLST_TXN_LOCATION VARCHAR2(640 BYTE);

ALTER TABLE OL_STATEMENT_TMP ADD OLST_TXN_TYPE VARCHAR2(640 BYTE);

ALTER TABLE OL_STATEMENT_TMP ADD OLST_TXN_REFERENCE VARCHAR2(640 BYTE);

