ALTER TABLE OL_STATEMENT_TMP_ERROR
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_STATEMENT_TMP_ERROR CASCADE CONSTRAINTS;

CREATE TABLE OL_STATEMENT_TMP_ERROR
(
  SE_ERROR_ID         NUMBER(16),
  SE_FILE_ID          NUMBER(16),
  SE_SEQ              INTEGER,
  SE_VER              INTEGER,
  SE_RESULT           VARCHAR2(255 BYTE),
  SE_CREATE_USER      VARCHAR2(20 BYTE),
  SE_CREATE_TIMESTAMP DATE                     DEFAULT SYSDATE
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX OL_STATEMENT_TMP_ERROR_IDX01 ON OL_STATEMENT_TMP_ERROR
(SE_FILE_ID, SE_SEQ, SE_VER)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

CREATE UNIQUE INDEX OL_STATEMENT_TMP_ERROR_PK ON OL_STATEMENT_TMP_ERROR
(SE_ERROR_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_STATEMENT_TMP_ERROR ADD (
  CONSTRAINT OL_STATEMENT_TMP_ERROR_PK
  PRIMARY KEY
  (SE_ERROR_ID)
  USING INDEX OL_STATEMENT_TMP_ERROR_PK
  ENABLE VALIDATE);

