DROP TABLE OL_STATEMENT_TMP_SPLIT CASCADE CONSTRAINTS;

CREATE TABLE OL_STATEMENT_TMP_SPLIT
(
  OLSS_FILE_ID             NUMBER(16),
  OLSS_SEQ                 INTEGER,
  OLSS_VER                 INTEGER,
  OLSS_STATEMENT_REF       VARCHAR2(16 BYTE),
  OLSS_CREATE_TIMESTAMP    DATE                  DEFAULT sysdate,
  OLSS_CREATE_USER         VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_STATEMENT_TMP_SPLIT_IDX01 ON OL_STATEMENT_TMP_SPLIT
(OLSS_STATEMENT_REF)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

CREATE UNIQUE INDEX OL_STATEMENT_TMP_SPLIT_PK ON OL_STATEMENT_TMP_SPLIT
(OLSS_FILE_ID, OLSS_SEQ, OLSS_VER, OLSS_STATEMENT_REF)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          256K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_STATEMENT_TMP_SPLIT ADD (
  CONSTRAINT OL_STATEMENT_TMP_SPLIT_PK
  PRIMARY KEY
  (OLSS_FILE_ID, OLSS_SEQ, OLSS_VER, OLSS_STATEMENT_REF)
  USING INDEX OL_STATEMENT_TMP_SPLIT_PK
  ENABLE VALIDATE);

