ALTER TABLE MMS_TXN_DETAIL
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_TXN_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE MMS_TXN_DETAIL
(
  MTD_TXN_ID                 VARCHAR2(16 BYTE),
  MTD_DTL_TXN_ID             INTEGER,
  MTD_ORG_DTL_TXN_ID         INTEGER,
  MTD_INIT_CHANNEL           VARCHAR2(3 BYTE),
  MTD_TXN_CODE               VARCHAR2(3 BYTE),
  MTD_ISD_IND                CHAR(1 BYTE),
  MTD_MERCHANT_ID            VARCHAR2(15 BYTE),
  MTD_PSP_ID                 VARCHAR2(10 BYTE),
  MTD_MB_ID                  VARCHAR2(15 BYTE),
  MTD_BANK_ID                VARCHAR2(15 BYTE),
  MTD_STL_BANK_ID            VARCHAR2(15 BYTE),
  MTD_PARTY_NODE_ID          VARCHAR2(5 BYTE),
  MTD_SERVICE_CODE           CHAR(3 BYTE),
  MTD_SRC_PARTY_TYPE         VARCHAR2(5 BYTE),
  MTD_DST_PARTY_TYPE         VARCHAR2(5 BYTE),
  MTD_CARRY_FORWARD_IND      INTEGER            DEFAULT 0,
  MTD_DC_TYPE                CHAR(2 BYTE),
  MTD_STATUS                 CHAR(1 BYTE),
  MTD_TRANSMISSION_DATETIME  VARCHAR2(14 BYTE),
  MTD_TXN_AMT                NUMBER(14,2)       DEFAULT 0,
  MTD_TXN_CCY                CHAR(3 BYTE),
  MTD_ADJUSTMENT             NUMBER(14,2)       DEFAULT 0,
  MTD_EXCHANGE_RATE          NUMBER(13,5)       DEFAULT 1,
  MTD_PROCESSING_COST        NUMBER(14,2)       DEFAULT 0,
  MTD_BANK_CHARGE            NUMBER(14,2)       DEFAULT 0,
  MTD_BANK_CHARGE_REFUND     NUMBER(14,2)       DEFAULT 0,
  MTD_FILING_NUMBER          VARCHAR2(50 BYTE),
  MTD_COUNTRY                VARCHAR2(3 BYTE),
  MTD_VERSION_NO             VARCHAR2(2 BYTE),
  MTD_ENCRYPT_TYPE           CHAR(1 BYTE),
  MTD_INTERNAL_CODE          NUMBER(8),
  MTD_RESPONSE_CODE          VARCHAR2(6 BYTE),
  MTD_PREV_DTL_TXN_ID        INTEGER,
  MTD_CREATE_TIMESTAMP       DATE               DEFAULT sysdate,
  MTD_CREATE_USER            VARCHAR2(20 BYTE),
  MTD_UPDATE_TIMESTAMP       DATE               DEFAULT sysdate,
  MTD_UPDATE_USER            VARCHAR2(20 BYTE),
  MTD_BATCH_ID               INTEGER
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN MMS_TXN_DETAIL.MTD_ISD_IND IS 'I: init; S: Source; D: Destination';

COMMENT ON COLUMN MMS_TXN_DETAIL.MTD_CARRY_FORWARD_IND IS '1: balance carry forward from init_channel (no need handle balance)';

COMMENT ON COLUMN MMS_TXN_DETAIL.MTD_DC_TYPE IS 'DR: Debit; CR: Credit';

COMMENT ON COLUMN MMS_TXN_DETAIL.MTD_STATUS IS 'W: Waiting to Approve; A: Approve and Complete';



CREATE INDEX MMS_TXN_DETAIL_IDX01 ON MMS_TXN_DETAIL
(MTD_TXN_ID, MTD_BATCH_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX MMS_TXN_DETAIL_PK ON MMS_TXN_DETAIL
(MTD_TXN_ID, MTD_DTL_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_TXN_DETAIL ADD (
  CONSTRAINT MMS_TXN_DETAIL_PK
  PRIMARY KEY
  (MTD_TXN_ID, MTD_DTL_TXN_ID)
  USING INDEX MMS_TXN_DETAIL_PK
  ENABLE VALIDATE);

ALTER TABLE MMS_TXN_DETAIL ADD (
  CONSTRAINT MMS_TXN_DETAIL_FK01 
  FOREIGN KEY (MTD_STL_BANK_ID) 
  REFERENCES MMS_STL_BANK_DETAIL (SBD_STL_BANK_ID)
  ENABLE VALIDATE,
  CONSTRAINT MMS_TXN_DETAIL_FK02 
  FOREIGN KEY (MTD_PARTY_NODE_ID) 
  REFERENCES MMX_NODES (MN_NODE_ID)
  ENABLE VALIDATE,
  CONSTRAINT MMS_TXN_DETAIL_FK03 
  FOREIGN KEY (MTD_STATUS) 
  REFERENCES MMS_DEF_STATUS (MS_STATUS)
  ENABLE VALIDATE);

