OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/TmpFrozenTxnAlert
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBTmpFrozenTxnAlert.so
SOOBJS =  TmpFrozenTxnAlert.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
