ALTER TABLE MI_ENTITY_DETAIL
 DROP PRIMARY KEY CASCADE;

DROP TABLE MI_ENTITY_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE MI_ENTITY_DETAIL
(
  ED_ENTITY_ID         VARCHAR2(10 BYTE)        NOT NULL,
  ED_ENTITY_TYPE       CHAR(3 BYTE),
  ED_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  ED_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  ED_CREATE_USER       VARCHAR2(20 BYTE),
  ED_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MI_ENTITY_DETAIL_PK ON MI_ENTITY_DETAIL
(ED_ENTITY_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MI_ENTITY_DETAIL ADD (
  CONSTRAINT MI_ENTITY_DETAIL_PK
  PRIMARY KEY
  (ED_ENTITY_ID)
  USING INDEX MI_ENTITY_DETAIL_PK
  ENABLE VALIDATE);

ALTER TABLE MI_ENTITY_DETAIL ADD (
  CONSTRAINT MI_ENTITY_DETAIL_FK01 
  FOREIGN KEY (ED_ENTITY_TYPE) 
  REFERENCES MI_DEF_ENTITY_TYPE (ET_TYPE_CODE)
  ENABLE VALIDATE);

