OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLAutoUploadStmtSetting
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLAutoUploadStmtSetting.so
SOOBJS =  OLAutoUploadStmtSetting.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
