ALTER TABLE RULE_PSP_LB_POOLS
 DROP PRIMARY KEY CASCADE;

DROP TABLE RULE_PSP_LB_POOLS CASCADE CONSTRAINTS;

CREATE TABLE RULE_PSP_LB_POOLS
(
  RP_CRITERIA_POOL_ID  INTEGER,
  RP_POOL_ID           INTEGER,
  RP_DESC              VARCHAR2(50 BYTE)        NOT NULL,
  RP_DISABLED          INTEGER                  DEFAULT 0                     NOT NULL,
  RP_POOL_LIMIT        NUMBER(14,2)             DEFAULT 0                     NOT NULL,
  RP_RATIO             INTEGER                  NOT NULL,
  RP_PRIORITY          INTEGER                  NOT NULL,
  RP_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  RP_CREATE_USER       VARCHAR2(20 BYTE),
  RP_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  RP_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN RULE_PSP_LB_POOLS.RP_POOL_LIMIT IS '0 - unlimited';

COMMENT ON COLUMN RULE_PSP_LB_POOLS.RP_PRIORITY IS '0 - Lowest 9999 - Highest';



CREATE INDEX RULE_PSP_LB_POOLS_IDX01 ON RULE_PSP_LB_POOLS
(RP_POOL_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RULE_PSP_LB_POOLS_PK ON RULE_PSP_LB_POOLS
(RP_CRITERIA_POOL_ID, RP_POOL_ID)
LOGGING
TABLESPACE USER_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE RULE_PSP_LB_POOLS ADD (
  CONSTRAINT RULE_PSP_LB_POOLS_PK
  PRIMARY KEY
  (RP_CRITERIA_POOL_ID, RP_POOL_ID)
  USING INDEX RULE_PSP_LB_POOLS_PK
  ENABLE VALIDATE);

