ALTER TABLE MMS_ACR_BAL_HISTORY
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_ACR_BAL_HISTORY CASCADE CONSTRAINTS;

CREATE TABLE MMS_ACR_BAL_HISTORY
(
  MAH_FX_ID            VARCHAR2(16 BYTE),
  MAH_FX_SEQ            INTEGER,
  MAH_FUNDS_DIRECTION    CHAR(1 BYTE),
  MAH_ENTITY_ID         VARCHAR2(20 BYTE),
  MAH_ORG_CCY           VARCHAR2(3 BYTE),
  MAH_CCY               VARCHAR2(3 BYTE),
  MAH_OLD_BAL           NUMBER(14,2),
  MAH_NEW_BAL           NUMBER(14,2),
  MAH_OLD_RATE          NUMBER(14,5),
  MAH_NEW_RATE          NUMBER(14,5),
  MAH_OLD_RATIO         NUMBER(6,5),
  MAH_NEW_RATIO         NUMBER(6,5),
  MAH_CREATE_TIMESTAMP  DATE,
  MAH_CREATE_USER       VARCHAR2(20 BYTE),
  MAH_UPDATE_TIMESTAMP  DATE,
  MAH_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX MMS_ACR_BAL_HISTORY_IDX01 ON MMS_ACR_BAL_HISTORY
(MAH_ENTITY_ID, MAH_FUNDS_DIRECTION)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX MMS_ACR_BAL_HISTORY_IDX02 ON MMS_ACR_BAL_HISTORY
(MAH_FX_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX MMS_ACR_BAL_HISTORY_PK ON MMS_ACR_BAL_HISTORY
(MAH_FX_ID,MAH_FX_SEQ)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_ACR_BAL_HISTORY ADD (
  CONSTRAINT MMS_ACR_BAL_HISTORY_PK
  PRIMARY KEY
  (MAH_FX_ID,MAH_FX_SEQ)
  USING INDEX MMS_ACR_BAL_HISTORY_PK
  ENABLE VALIDATE);

ALTER TABLE MMS_ACR_BAL_HISTORY ADD (
  CONSTRAINT MMS_ACR_BAL_HISTORY_FK01 
  FOREIGN KEY (MAH_FUNDS_DIRECTION) 
  REFERENCES MMS_DEF_FUNDS_DIRECTION (MFD_TYPE)
  ENABLE VALIDATE);

