OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLPayoutRequest
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLPayoutRequest.so
SOOBJS =  OLPayoutRequest.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
