OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/PayoutHeader
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBPayoutHeader.so
SOOBJS =  PayoutHeader.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
