ALTER TABLE DEF_FEE_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_FEE_TYPE CASCADE CONSTRAINTS;

CREATE TABLE DEF_FEE_TYPE
(
  DF_TYPE              CHAR(2 BYTE),
  DF_DESC              VARCHAR2(20 BYTE),
  DF_CREATE_TIMESTAMP  DATE,
  DF_CREATE_USER       VARCHAR2(20 BYTE),
  DF_UPDATE_TIMESTAMP  DATE,
  DF_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEF_FEE_TYPE_PK ON DEF_FEE_TYPE
(DF_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_FEE_TYPE ADD (
  CONSTRAINT DEF_FEE_TYPE_PK
  PRIMARY KEY
  (DF_TYPE)
  USING INDEX DEF_FEE_TYPE_PK);

