OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/ServiceUIReleaseCtl
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBServiceUIReleaseCtl.so
SOOBJS =  ServiceUIReleaseCtl.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
