#!/bin/bash

#Partnerdelight (c)2010. All rights reserved. No part of this software may be reproduced in any form without written permission
#of an authorized representative of Partnerdelight.
#
#Change Description                                 Change Date             Change By
#-------------------------------                    ------------            --------------
#Init Version                                       2011/05/11                LokMan Chow


. /home/php3dev/.setenv

msg_file="warning_email.txt"

if [[ $# == 1 ]]
then
	file_name=$1

	echo "******************WARNING*****************"  > $msg_file
	echo ""  >> $msg_file
	echo "Payout File [$file_name] not found"  >> $msg_file
	echo ""  >> $msg_file
	echo "****This message is generated by system****"  >> $msg_file

	cat /home/php3dev/.warning_email_list | while read mailaddr
	do
		echo $mailaddr
		mail -s "[PH Auto Alert Message]" $mailaddr < $msg_file
	done

else
	echo "Not enough Argument"
	echo "Usage: $0 file name"
fi

rm $msg_file > /dev/null 2>&1
