OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLTxnElements
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLTxnElements.so
SOOBJS =  OLTxnElements.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
