CREATE TABLE SERVICE_FEE_MAPPING
(
  SF_SERVICE_CODE      		VARCHAR2(3 BYTE),
  SF_INT_BANK_CODE     		VARCHAR2(10 BYTE),
  SF_FEE_TYPE          		CHAR(2 BYTE),
  SF_DISABLED          		INTEGER                  DEFAULT 0,
  SF_CREATE_TIMESTAMP  		DATE                     DEFAULT sysdate,
  SF_UPDATE_TIMESTAMP  		DATE                     DEFAULT sysdate,
  SF_CREATE_USER       		VARCHAR2(20 BYTE),
  SF_UPDATE_USER       		VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX SERVICE_FEE_MAPPING_PK ON SERVICE_FEE_MAPPING
(SF_SERVICE_CODE, SF_INT_BANK_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE SERVICE_FEE_MAPPING ADD (
  CONSTRAINT SERVICE_FEE_MAPPING_PK
  PRIMARY KEY
  (SF_SERVICE_CODE, SF_INT_BANK_CODE)
  USING INDEX SERVICE_FEE_MAPPING_PK
  ENABLE VALIDATE);
