CREATE TABLE OL_BULK_DETAIL
(
  OBD_BATCH_ID              NUMBER(16)          NOT NULL,
  OBD_SEQ                   INTEGER             NOT NULL,
  OBD_INT_BANK_CODE         VARCHAR2(10 BYTE),
  OBD_BANK_ACCT_NUM         VARCHAR2(50 BYTE),
  OBD_BANK_ACCT_ORG_STATUS  VARCHAR2(2 BYTE),
  OBD_BANK_ACCT_NEW_STATUS  VARCHAR2(2 BYTE),
  OBD_BAID                  VARCHAR2(20 BYTE),
  OBD_BAID_ORG_STATUS       VARCHAR2(2 BYTE),
  OBD_BAID_NEW_STATUS       VARCHAR2(2 BYTE),
  OBD_ADJ_TXN_CODE          VARCHAR2(3 BYTE),
  OBD_ADJ_RPT_DATE          VARCHAR2(8 BYTE),
  OBD_ADJ_REMARK            VARCHAR2(255 BYTE),
  OBD_RET_CODE              NUMBER(8),
  OBD_CREATE_USER           VARCHAR2(20 BYTE),
  OBD_CREATE_TIMESTAMP      DATE                DEFAULT SYSDATE,
  OBD_UPDATE_USER           VARCHAR2(20 BYTE),
  OBD_UPDATE_TIMESTAMP      DATE                DEFAULT SYSDATE
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE INDEX OL_BULK_DETAIL_IDX01 ON OL_BULK_DETAIL
(OBD_CREATE_TIMESTAMP, OBD_UPDATE_TIMESTAMP)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX OL_BULK_DETAIL_IDX02 ON OL_BULK_DETAIL
(OBD_INT_BANK_CODE, OBD_BANK_ACCT_NUM)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX OL_BULK_DETAIL_IDX03 ON OL_BULK_DETAIL
(OBD_BAID, OBD_ADJ_TXN_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX OL_BULK_DETAIL_PK ON OL_BULK_DETAIL
(OBD_BATCH_ID, OBD_SEQ)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE OL_BULK_DETAIL ADD (
  CONSTRAINT OL_BULK_DETAIL_PK
  PRIMARY KEY
  (OBD_BATCH_ID, OBD_SEQ)
  USING INDEX OL_BULK_DETAIL_PK
  ENABLE VALIDATE);

ALTER TABLE OL_BULK_DETAIL ADD (
  CONSTRAINT OL_BULK_DETAIL_FK01 
  FOREIGN KEY (OBD_BATCH_ID) 
  REFERENCES OL_BULK_HEADER (OBH_BATCH_ID)
  ENABLE VALIDATE);
