ALTER TABLE TXN_CCT_ACK_RETRY
 DROP PRIMARY KEY CASCADE;

DROP TABLE TXN_CCT_ACK_RETRY CASCADE CONSTRAINTS;

CREATE TABLE TXN_CCT_ACK_RETRY
(
  TA_MERCHANT_ID       VARCHAR2(15 BYTE),
  TA_MERCHANT_REF      VARCHAR2(50 BYTE),
  TA_STATUS            CHAR(1 BYTE),
  TA_LOCAL_TM_DATE     VARCHAR2(8 BYTE),
  TA_LOCAL_TM_TIME     VARCHAR2(6 BYTE),
  TA_NEXT_TRY          DATE,
  TA_CREATE_USER       VARCHAR2(20 BYTE),
  TA_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  TA_UPDATE_USER       VARCHAR2(20 BYTE),
  TA_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  TA_RESEND_COUNT      INTEGER                  DEFAULT 0
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN TXN_CCT_ACK_RETRY.TA_STATUS IS '''F'' First try, ''R'' - Retry, ''C- Complete';


CREATE INDEX TXN_CCT_ACK_RETRY_IDX01 ON TXN_CCT_ACK_RETRY
(TA_MERCHANT_ID,TA_MERCHANT_REF)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX TXN_CCT_ACK_RETRY_IDX02 ON TXN_CCT_ACK_RETRY
(TA_NEXT_TRY)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE TXN_CCT_ACK_RETRY ADD (
  CONSTRAINT TXN_CCT_ACK_RETRY_PK
  PRIMARY KEY
  (TA_MERCHANT_ID,TA_MERCHANT_REF)
  USING INDEX TXN_CCT_ACK_RETRY_IDX01);

