ALTER TABLE OL_STMT_FORMAT_RANGE
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_STMT_FORMAT_RANGE CASCADE CONSTRAINTS;

CREATE TABLE OL_STMT_FORMAT_RANGE
(
  OLFC_INT_BANK_CODE     VARCHAR(10 BYTE),
  OLFC_CODE              CHAR(3 BYTE),
  OLFC_CCY               CHAR(3 BYTE),
  OLFC_MIN_AMT           NUMBER(12,2),
  OLFC_MAX_AMT           NUMBER(12,2),
  OLFC_MIN_DP            INTEGER,
  OLFC_MAX_DP            INTEGER,
  OLFC_DISABLED          INTEGER                   DEFAULT 0,
  OLFC_CREATE_TIMESTAMP  DATE                      DEFAULT sysdate,
  OLFC_CREATE_USER       VARCHAR2(20 BYTE),
  OLFC_UPDATE_TIMESTAMP  DATE                      DEFAULT sysdate,
  OLFC_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_STMT_FORMAT_RANGE_PK ON OL_STMT_FORMAT_RANGE
(OLFC_INT_BANK_CODE, OLFC_CODE, OLFC_CCY)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_STMT_FORMAT_RANGE ADD (
  CONSTRAINT OL_STMT_FORMAT_RANGE_PK
  PRIMARY KEY
  (OLFC_INT_BANK_CODE, OLFC_CODE, OLFC_CCY)
  USING INDEX OL_STMT_FORMAT_RANGE_PK
  ENABLE VALIDATE);

ALTER TABLE OL_STMT_FORMAT_RANGE ADD (
  CONSTRAINT OL_STMT_FORMAT_RANGE_FK02
  FOREIGN KEY (OLFC_CODE) 
  REFERENCES OL_BAID_TXN_CODE (OBTC_CODE)
  ENABLE VALIDATE);

