ALTER TABLE TXN_BALANCE_LOG
 DROP PRIMARY KEY CASCADE;

DROP TABLE TXN_BALANCE_LOG CASCADE CONSTRAINTS;

CREATE TABLE TXN_BALANCE_LOG
(
  TB_TXN_APRV_DATE        VARCHAR2(8 BYTE),
  TB_PARTY_TYPE		  CHAR(1 BYTE),
  TB_IS_COMPLETED         INTEGER                  DEFAULT 0,
  TB_CREATE_TIMESTAMP     DATE                     DEFAULT sysdate,
  TB_CREATE_USER          VARCHAR2(20 BYTE),
  TB_UPDATE_TIMESTAMP     DATE                     DEFAULT sysdate,
  TB_UPDATE_USER          VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX TXN_BALANCE_LOG_PK ON TXN_BALANCE_LOG
(TB_TXN_APRV_DATE,TB_PARTY_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE TXN_BALANCE_LOG ADD (
  CONSTRAINT TXN_BALANCE_LOG_PK
  PRIMARY KEY
  (TB_TXN_APRV_DATE,TB_PARTY_TYPE)
  USING INDEX TXN_BALANCE_LOG_PK
  ENABLE VALIDATE);

