ALTER TABLE PAR_MERCH_PROFILE
 DROP PRIMARY KEY CASCADE;

DROP TABLE PAR_MERCH_PROFILE CASCADE CONSTRAINTS;

CREATE TABLE PAR_MERCH_PROFILE
(
  MP_MERCH_ACCT_NMB             VARCHAR2(50 BYTE) NOT NULL,
  MP_USERNAME                   VARCHAR2(100 BYTE) NOT NULL,
  MP_COMPANY_NAME               VARCHAR2(400 BYTE) NOT NULL,
  MP_API_MERCH_ID               VARCHAR2(30 BYTE) NOT NULL,
  MP_FILE_PREFIX                VARCHAR2(13 BYTE),
  MP_IS_BACKEND_ACK             INTEGER         NOT NULL,
  MP_BACKEND_ACK_URL            VARCHAR2(200 BYTE),
  MP_MERCH_TYPE_ID              INTEGER         NOT NULL,
  MP_DEPOSIT_PSP_TYPE_ID        INTEGER         NOT NULL,
  MP_PAYOUT_ENABLE              INTEGER         NOT NULL,
  MP_PAYOUT_FILE_UPLOAD_ENABLE  INTEGER         NOT NULL,
  MP_PAYOUT_FILE_TYPE_ID        INTEGER         NOT NULL,
  MP_PSP_PROFILE_ID             INTEGER         NOT NULL,
  MP_APPLY_MERCHANT_RESERVE     INTEGER         NOT NULL,
  MP_RESERVE_FREQUENCY          INTEGER         NOT NULL,
  MP_FILE_POST_DATE             DATE            NOT NULL,
  MP_FILE_UPDATE_DATE           DATE            NOT NULL,
  MP_SERVICE                    VARCHAR2(3 BYTE),
  MP_CONVERTED                  INTEGER,
  MP_CREATE_TIMESTAMP           DATE            DEFAULT sysdate,
  MP_CREATE_USER                VARCHAR2(20 BYTE),
  MP_UPDATE_TIMESTAMP           DATE            DEFAULT sysdate,
  MP_UPDATE_USER                VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN PAR_MERCH_PROFILE.MP_MERCH_TYPE_ID IS '1: Normal; 2: Non-game; 3- New Game; 4- Offline';



CREATE UNIQUE INDEX PAR_MERCH_PROFILE_PK ON PAR_MERCH_PROFILE
(MP_MERCH_ACCT_NMB)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

ALTER TABLE PAR_MERCH_PROFILE ADD (
  CONSTRAINT PAR_MERCH_PROFILE_PK
  PRIMARY KEY
  (MP_MERCH_ACCT_NMB)
  USING INDEX PAR_MERCH_PROFILE_PK
  ENABLE VALIDATE);

