OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/SystemTplFmt
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBSystemTplFmt.so
SOOBJS =  SystemTplFmt.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
