OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnWebOnUs2CCT
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnWebOnUs2CCT.so
SOOBJS = TxnWebOnUs2CCT.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
