OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmcTransaction
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmcTransaction.so
SOOBJS =  MmcTransaction.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
