CREATE TABLE EXCHANGE_RATE_ERS
(
  EXE_FROM_CCY_ID         CHAR(3 BYTE)           NOT NULL,
  EXE_TO_CCY_ID           CHAR(3 BYTE)           NOT NULL,
  EXE_RATE                NUMBER(13,5)           NOT NULL,
  EXE_BID                 NUMBER(12,6),
  EXE_MAX_ASK             NUMBER(13,5),
  EXE_MED_ASK             NUMBER(13,5),
  EXE_MIN_ASK             NUMBER(13,5),
  EXE_MAX_BID             NUMBER(13,5),
  EXE_MED_BID             NUMBER(13,5),
  EXE_MIN_BID             NUMBER(13,5),
  EXE_MEANMINMAX_SRC2DST  NUMBER(12,6),
  EXE_MINMAX_SRC2DST      NUMBER(12,6),
  EXE_EFFECT_DATE         DATE                   NOT NULL,
  EXE_CREATE_DATE         DATE                   NOT NULL,
  EXE_CREATE_USER         VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          192K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX EXCHANGE_RATE_ERS_PK ON EXCHANGE_RATE_ERS
(EXE_FROM_CCY_ID, EXE_TO_CCY_ID, EXE_EFFECT_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE OR REPLACE SYNONYM DEV.EXCHANGE_RATE_ERS FOR EXCHANGE_RATE_ERS;


ALTER TABLE EXCHANGE_RATE_ERS ADD (
  CONSTRAINT EXCHANGE_RATE_ERS_PK
  PRIMARY KEY
  (EXE_FROM_CCY_ID, EXE_TO_CCY_ID, EXE_EFFECT_DATE)
  USING INDEX EXCHANGE_RATE_ERS_PK
  ENABLE VALIDATE);

