OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/ExchangeLimitRate
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBExchangeLimitRate.so
SOOBJS =  ExchangeLimitRate.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
