OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOMMSEntity
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOMMSEntity.so
SOOBJS = BOMMSEntity.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
