OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnMgtByUsRDS
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnMgtByUsRDS.so
SOOBJS = TxnMgtByUsRDS.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
