ALTER TABLE OL_PAYOUT_GEN_FILE_DT_MAP
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_PAYOUT_GEN_FILE_DT_MAP CASCADE CONSTRAINTS;

CREATE TABLE OL_PAYOUT_GEN_FILE_DT_MAP
(
  ODM_ACTION_TYPE       CHAR(1 BYTE),
  ODM_ORG_TXN_ID        VARCHAR2(16 BYTE),
  ODM_NEW_TXN_ID        VARCHAR2(16 BYTE),
  ODM_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  ODM_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  ODM_CREATE_USER       VARCHAR2(20 BYTE),
  ODM_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_PAYOUT_GEN_FILE_DT_MAP_PK ON OL_PAYOUT_GEN_FILE_DT_MAP
(ODM_ACTION_TYPE, ODM_ORG_TXN_ID, ODM_NEW_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_PAYOUT_GEN_FILE_DT_MAP ADD (
  CONSTRAINT OL_PAYOUT_GEN_FILE_DT_MAP_PK
  PRIMARY KEY
  (ODM_ACTION_TYPE, ODM_ORG_TXN_ID, ODM_NEW_TXN_ID)
  USING INDEX OL_PAYOUT_GEN_FILE_DT_MAP_PK
  ENABLE VALIDATE);

