ALTER TABLE MMS_DEF_STATUS
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_DEF_STATUS CASCADE CONSTRAINTS;

CREATE TABLE MMS_DEF_STATUS
(
  MS_STATUS            CHAR(1 BYTE),
  MS_NAME              VARCHAR2(50 BYTE),
  MS_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  MS_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  MS_CREATE_USER       VARCHAR2(20 BYTE),
  MS_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MMS_DEF_STATUS_PK ON MMS_DEF_STATUS
(MS_STATUS)
LOGGING
TABLESPACE USER_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_DEF_STATUS ADD (
  CONSTRAINT MMS_DEF_STATUS_PK
  PRIMARY KEY
  (MS_STATUS)
  USING INDEX MMS_DEF_STATUS_PK
  ENABLE VALIDATE);

