OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmsInstantTxnInqDt
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmsInstantTxnInqDt.so
SOOBJS =  MmsInstantTxnInqDt.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
