CREATE TABLE OL_AUTO_UPLOAD_BANK_DETAIL
(
  OAUBD_INT_BANK_CODE		VARCHAR2(10 Byte),
  OAUBD_BANK_ACCT_NUM        	VARCHAR2(50 BYTE),
  OAUBD_DISABLED		INTEGER                 DEFAULT 0,
  OAUBD_CREATE_TIMESTAMP  	DATE                   	DEFAULT sysdate,
  OAUBD_CREATE_USER       	VARCHAR2(20 BYTE),
  OAUBD_UPDATE_TIMESTAMP  	DATE                 	DEFAULT sysdate,
  OAUBD_UPDATE_USER       	VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX OL_AUTO_UPLOAD_BANK_DETAIL_PK ON OL_AUTO_UPLOAD_BANK_DETAIL
(OAUBD_INT_BANK_CODE, OAUBD_BANK_ACCT_NUM)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE OL_AUTO_UPLOAD_BANK_DETAIL ADD (
  CONSTRAINT OL_AUTO_UPLOAD_BANK_DETAIL_PK
  PRIMARY KEY
  (OAUBD_INT_BANK_CODE, OAUBD_BANK_ACCT_NUM)
  USING INDEX OL_AUTO_UPLOAD_BANK_DETAIL_PK
  ENABLE VALIDATE);
