ALTER TABLE DEF_MODE_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_MODE_TYPE CASCADE CONSTRAINTS;

CREATE TABLE DEF_MODE_TYPE
(
  MT_TYPE              VARCHAR2(3 BYTE),
  MT_DESC              VARCHAR2(50 BYTE),
  MT_CREATE_USER       VARCHAR2(20 BYTE),
  MT_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  MT_UPDATE_USER       VARCHAR2(20 BYTE),
  MT_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEF_MODE_TYPE_PK ON DEF_MODE_TYPE
(MT_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_MODE_TYPE ADD (
  CONSTRAINT DEF_MODE_TYPE_PK
  PRIMARY KEY
  (MT_TYPE)
  USING INDEX DEF_MODE_TYPE_PK
  ENABLE VALIDATE);
