OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnWebOnUsCIU
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnWebOnUsCIU.so
SOOBJS = TxnWebOnUsCIU.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
