ALTER TABLE MMS_DEF_CHARGE_PERIOD
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_DEF_CHARGE_PERIOD CASCADE CONSTRAINTS;

CREATE TABLE MMS_DEF_CHARGE_PERIOD
(
  MCP_TYPE              CHAR(1 BYTE),
  MCP_DESC              VARCHAR2(50 BYTE),
  MCP_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  MCP_CREATE_USER       VARCHAR2(20 BYTE),
  MCP_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  MCP_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MMS_DEF_CHARGE_PERIOD_PK ON MMS_DEF_CHARGE_PERIOD
(MCP_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_DEF_CHARGE_PERIOD ADD (
  CONSTRAINT MMS_DEF_CHARGE_PERIOD_PK
  PRIMARY KEY
  (MCP_TYPE)
  USING INDEX MMS_DEF_CHARGE_PERIOD_PK
  ENABLE VALIDATE);

