CREATE TABLE OL_AUTO_UPLOAD_JOB_TMP
(
  OAUJT_JOB_SEQ           NUMBER,
  OAUJT_STATUS            CHAR(1 BYTE),
  OAUJT_CREATE_TIMESTAMP  DATE,
  OAUJT_CREATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX OL_AUTO_UPLOAD_JOB_TMP_PK ON OL_AUTO_UPLOAD_JOB_TMP
(OAUJT_JOB_SEQ)
LOGGING
TABLESPACE USER_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE OL_AUTO_UPLOAD_JOB_TMP ADD (
  CONSTRAINT OL_AUTO_UPLOAD_JOB_TMP_PK
  PRIMARY KEY
  (OAUJT_JOB_SEQ)
  USING INDEX OL_AUTO_UPLOAD_JOB_TMP_PK
  ENABLE VALIDATE);

