OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnParByUsVOG
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnParByUsVOG.so
SOOBJS = TxnParByUsVOG.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
