

CREATE TABLE TEST_MIC_BAL
(
  M_MERCHANT_ID               VARCHAR2(15 BYTE),
  M_CURRENCY_ID               VARCHAR2(3 BYTE),
  M_COUNTRY_ID                CHAR(2 BYTE),
  M_SERVICE_CODE              CHAR(3 BYTE),
  M_CURRENT_BAL               NUMBER(14,2)      DEFAULT 0,
  M_CURRENT_BAL_SETTLEMENT    NUMBER(14,2)      DEFAULT 0,
  M_TOTAL_FLOAT               NUMBER(14,2)      DEFAULT 0,
  M_TOTAL_FLOAT_AFTER_PAYOUT  NUMBER(14,2)      DEFAULT 0,
  M_TOTAL_FLOAT_SETTLEMENT    NUMBER(14,2)      DEFAULT 0,
  M_TOTAL_RESERVED_AMOUNT     NUMBER(14,2)      DEFAULT 0,
  M_FUNDIN_PAYOUT             NUMBER(14,2)      DEFAULT 0,
  M_RESERVED_PAYOUT           NUMBER(14,2)      DEFAULT 0,
  M_TOTAL_HOLD                NUMBER(14,2)      DEFAULT 0,
  M_TOTAL_HOLD_SETTLEMENT     NUMBER(14,2)      DEFAULT 0,
  M_CREATE_TIMESTAMP          DATE              DEFAULT sysdate,
  M_UPDATE_TIMESTAMP          DATE              DEFAULT sysdate,
  M_CREATE_USER               VARCHAR2(20 BYTE),
  M_UPDATE_USER               VARCHAR2(20 BYTE),
  M_SETTLEMENT_IN_TRANSIT     NUMBER(14,2)      DEFAULT 0
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX TEST_MIC_BAL_PK ON TEST_MIC_BAL
(M_MERCHANT_ID, M_CURRENCY_ID, M_COUNTRY_ID, M_SERVICE_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE TEST_MIC_BAL ADD (
  CONSTRAINT TEST_MIC_BAL_PK
  PRIMARY KEY
  (M_MERCHANT_ID, M_CURRENCY_ID, M_COUNTRY_ID, M_SERVICE_CODE)
  USING INDEX TEST_MIC_BAL_PK
  ENABLE VALIDATE);

ALTER TABLE TEST_MIC_BAL ADD (
  CONSTRAINT TEST_MIC_BAL_F03 
  FOREIGN KEY (M_SERVICE_CODE) 
  REFERENCES DEF_SERVICE_CODE (SC_CODE)
  ENABLE VALIDATE,
  CONSTRAINT TEST_MIC_BAL_FK01 
  FOREIGN KEY (M_MERCHANT_ID) 
  REFERENCES MERCH_DETAIL (MERCHANT_ID)
  ENABLE VALIDATE,
  CONSTRAINT TEST_MIC_BAL_FK02 
  FOREIGN KEY (M_CURRENCY_ID) 
  REFERENCES DEF_CURRENCY (DC_CCY_ID)
  ENABLE VALIDATE,
  CONSTRAINT TEST_MIC_BAL_FK04 
  FOREIGN KEY (M_COUNTRY_ID) 
  REFERENCES COUNTRY (COUNTRY_CODE)
  ENABLE VALIDATE);

  
  
