CREATE OR REPLACE FUNCTION SP_HIST_OL_COST_SUM_COL_BY_DAY
RETURN NUMBER IS
	EXP_ERR EXCEPTION;
	V_RETURN_NO NUMBER;
BEGIN
  /*
  Anonymous block for initiate
  DECLARE
  V_INPUT_DATE DATE;
  BEGIN
  FOR X IN 1..2 LOOP
  SELECT MAX(HB_END_DATE) + 1
  INTO V_INPUT_DATE
  FROM HIST_OL_COST_SUM_BATCH
  WHERE HB_DISABLED = 0;
  -- Run Batch Function
  HIST_OL_COST_SUM_COLLECT(V_INPUT_DATE);
  END LOOP;
  END;
  */
  -- DBMS_OUTPUT.PUT_LINE('>>> START [HIST_OL_COST_SUM_COL_BY_DAY] <<<');
  -- Run Batch Function
	V_RETURN_NO := SP_HIST_OL_COST_SUM_COLLECT(TRUNC(sysdate) - 1/24/60);
  -- DBMS_OUTPUT.PUT_LINE('>>> END [HIST_OL_COST_SUM_COL_BY_DAY] <<<');

	RETURN V_RETURN_NO;

EXCEPTION
WHEN EXP_ERR THEN
	ROLLBACK;
--DBMS_OUTPUT.PUT_LINE('Error : no record!...');
	 RETURN 1;
WHEN OTHERS THEN
	ROLLBACK;
--DBMS_OUTPUT.PUT_LINE('Error : Other error!...');
--RAISE_APPLICATION_ERROR( -20202, 'Error code ' || SQLCODE|| ': ' || SUBSTR(SQLERRM, 1 , 64) );
	RETURN 9;
END SP_HIST_OL_COST_SUM_COL_BY_DAY;
/
