OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MerchantPayMethod
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMerchantPayMethod.so
SOOBJS =  MerchantPayMethod.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
