ALTER TABLE OL_TXN_ENGINE_TXNCODE_GRP
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_TXN_ENGINE_TXNCODE_GRP CASCADE CONSTRAINTS;

CREATE TABLE OL_TXN_ENGINE_TXNCODE_GRP
(
  ETG_TXN_GRP       VARCHAR2(50 BYTE),
  ETG_TXN_CODE      CHAR(3 BYTE),
  ETG_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  ETG_CREATE_USER       VARCHAR2(20 BYTE),
  ETG_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  ETG_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_TXN_ENGINE_TXNCODE_GRP_PK ON OL_TXN_ENGINE_TXNCODE_GRP
(ETG_TXN_GRP, ETG_TXN_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_TXN_ENGINE_TXNCODE_GRP ADD (
  CONSTRAINT OL_TXN_ENGINE_TXNCODE_GRP_PK
  PRIMARY KEY
  (ETG_TXN_GRP, ETG_TXN_CODE)
  USING INDEX OL_TXN_ENGINE_TXNCODE_GRP_PK
  ENABLE VALIDATE);

ALTER TABLE OL_TXN_ENGINE_TXNCODE_GRP ADD (
  CONSTRAINT OL_TXN_ENGINE_TXNCODE_GRP_FK01 
  FOREIGN KEY (ETG_TXN_CODE) 
  REFERENCES TXN_CODE (TC_CODE)
  ENABLE VALIDATE);
