OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/DefACRPool
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBDefACRPool.so
SOOBJS =  DefACRPool.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
