OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOOLBaid
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOOLBaid.so
SOOBJS = BOOLBaid.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
