ALTER TABLE DEF_BUCKET_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_BUCKET_TYPE CASCADE CONSTRAINTS;

CREATE TABLE DEF_BUCKET_TYPE
(
  B_TYPE              VARCHAR2(2 BYTE)          NOT NULL,
  B_DESC              VARCHAR2(50 BYTE),
  B_CREATE_USER       VARCHAR2(20 BYTE),
  B_CREATE_TIMESTAMP  DATE                      DEFAULT sysdate,
  B_UPDATE_USER       VARCHAR2(20 BYTE),
  B_UPDATE_TIMESTAMP  DATE                      DEFAULT sysdate
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEF_BUCKET_TYPE_PK ON DEF_BUCKET_TYPE
(B_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_BUCKET_TYPE ADD (
  CONSTRAINT DEF_BUCKET_TYPE_PK
  PRIMARY KEY
  (B_TYPE)
  USING INDEX DEF_BUCKET_TYPE_PK);


