ALTER TABLE PAR_CLIENTS
 DROP PRIMARY KEY CASCADE;

DROP TABLE PAR_CLIENTS CASCADE CONSTRAINTS;

CREATE TABLE PAR_CLIENTS
(
  PC_COMPANY_NAME	 VARCHAR2(400 BYTE),
  PC_CLIENT_ID           VARCHAR2(10 BYTE),
  PC_DEF_CLIENT_GROUP	 VARCHAR2(5 BYTE),
  PC_CREATE_TIMESTAMP	 DATE	DEFAULT sysdate,
  PC_CREATE_USER	 VARCHAR2(20 BYTE),
  PC_UPDATE_TIMESTAMP	 DATE	DEFAULT sysdate,
  PC_UPDATE_USEr	 VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PAR_CLIENTS_PK ON PAR_CLIENTS
(PC_COMPANY_NAME)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PAR_CLIENTS ADD (
  CONSTRAINT PAR_CLIENTS_PK
  PRIMARY KEY
  (PC_COMPANY_NAME)
  USING INDEX PAR_CLIENTS_PK
  ENABLE VALIDATE);

