ALTER TABLE DEF_MMS_BANK
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_MMS_BANK CASCADE CONSTRAINTS;

CREATE TABLE DEF_MMS_BANK
(
  DMB_INT_BANK_CODE     VARCHAR2(10 BYTE),
  DMB_EXT_BANK_CODE     VARCHAR2(20 BYTE),
  DMB_COUNTRY           CHAR(2 BYTE),
  DMB_CURRENCY          VARCHAR2(3 BYTE),
  DMB_CREATE_USER       VARCHAR2(20 BYTE),
  DMB_UPDATE_USER       VARCHAR2(20 BYTE),
  DMB_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  DMB_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEF_MMS_BANK_PK ON DEF_MMS_BANK
(DMB_INT_BANK_CODE, DMB_COUNTRY, DMB_CURRENCY)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_MMS_BANK ADD (
  CONSTRAINT DEF_MMS_BANK_PK
  PRIMARY KEY
  (DMB_INT_BANK_CODE, DMB_COUNTRY, DMB_CURRENCY)
  USING INDEX DEF_MMS_BANK_PK
  ENABLE VALIDATE);

ALTER TABLE DEF_MMS_BANK ADD (
  CONSTRAINT DEF_MMS_BANK_FK01 
  FOREIGN KEY (DMB_COUNTRY) 
  REFERENCES COUNTRY (COUNTRY_CODE)
  ENABLE VALIDATE);

