ALTER TABLE MMS_DEF_BALANCE_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_DEF_BALANCE_TYPE CASCADE CONSTRAINTS;

CREATE TABLE MMS_DEF_BALANCE_TYPE
(
  MBT_TYPE              CHAR(1 BYTE),
  MBT_DESC              VARCHAR2(50 BYTE),
  MBT_ADJ_ELEMENT_TYPE  CHAR(4 BYTE),
  MBT_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  MBT_CREATE_USER       VARCHAR2(20 BYTE),
  MBT_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  MBT_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MMS_DEF_BALANCE_TYPE_PK ON MMS_DEF_BALANCE_TYPE
(MBT_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_DEF_BALANCE_TYPE ADD (
  CONSTRAINT MMS_DEF_BALANCE_TYPE_PK
  PRIMARY KEY
  (MBT_TYPE)
  USING INDEX MMS_DEF_BALANCE_TYPE_PK
  ENABLE VALIDATE);

