ALTER TABLE MI_DEF_ACR_DIRECTION
 DROP PRIMARY KEY CASCADE;

DROP TABLE MI_DEF_ACR_DIRECTION CASCADE CONSTRAINTS;

CREATE TABLE MI_DEF_ACR_DIRECTION
(
  MAD_TYPE              CHAR(1 BYTE),
  MAD_DESC              VARCHAR2(50 BYTE),
  MAD_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  MAD_CREATE_USER       VARCHAR2(20 BYTE),
  MAD_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  MAD_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MI_DEF_ACR_DIRECTION_PK ON MI_DEF_ACR_DIRECTION
(MAD_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MI_DEF_ACR_DIRECTION ADD (
  CONSTRAINT MI_DEF_ACR_DIRECTION_PK
  PRIMARY KEY
  (MAD_TYPE)
  USING INDEX MI_DEF_ACR_DIRECTION_PK
  ENABLE VALIDATE);

