OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/CustomerGroupPromoList
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBCustomerGroupPromoList.so
SOOBJS =  CustomerGroupPromoList.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
