ALTER TABLE MMS_DEF_CURRENCY_PAIR
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_DEF_CURRENCY_PAIR CASCADE CONSTRAINTS;

CREATE TABLE MMS_DEF_CURRENCY_PAIR
(
  MCP_REMIT_CCY         VARCHAR2(3 BYTE),
  MCP_RECEIVE_CCY       VARCHAR2(3 BYTE),
  MCP_DISABLED          INTEGER                 DEFAULT 0,
  MCP_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  MCP_CREATE_USER       VARCHAR2(20 BYTE),
  MCP_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  MCP_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MMS_DEF_CURRENCY_PAIR_PK ON MMS_DEF_CURRENCY_PAIR
(MCP_REMIT_CCY, MCP_RECEIVE_CCY)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_DEF_CURRENCY_PAIR ADD (
  CONSTRAINT MMS_DEF_CURRENCY_PAIR_PK
  PRIMARY KEY
  (MCP_REMIT_CCY, MCP_RECEIVE_CCY)
  USING INDEX MMS_DEF_CURRENCY_PAIR_PK
  ENABLE VALIDATE);

