CREATE TABLE OL_AUTO_UPLOAD_JOB_STATUS
(
  OAUJS_JOB_SEQ           INTEGER,
  OAUJS_NATURE_PATH       VARCHAR2(50 BYTE),
  OAUJS_PROVIDER_PATH     VARCHAR2(50 BYTE),
  OAUJS_PROCESS_BANK      VARCHAR2(100 BYTE),
  OAUJS_STATUS            CHAR(1 BYTE),
  OAUJS_CREATE_TIMESTAMP  DATE,
  OAUJS_CREATE_USER       VARCHAR2(20 BYTE),
  OAUJS_UPDATE_TIMESTAMP  DATE,
  OAUJS_UPDATE_USER       VARCHAR2(20 BYTE),
  OAUJS_EXCLUDE_MODE      INTEGER
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE INDEX OL_AUTO_UPLOAD_JOB_STATUS_IX01 ON OL_AUTO_UPLOAD_JOB_STATUS
(OAUJS_JOB_SEQ, OAUJS_STATUS)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX OL_AUTO_UPLOAD_JOB_STATUS_PK ON OL_AUTO_UPLOAD_JOB_STATUS
(OAUJS_NATURE_PATH, OAUJS_PROVIDER_PATH, OAUJS_PROCESS_BANK, OAUJS_EXCLUDE_MODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE OL_AUTO_UPLOAD_JOB_STATUS ADD (
  CONSTRAINT OL_AUTO_UPLOAD_JOB_STATUS_PK
  PRIMARY KEY
  (OAUJS_NATURE_PATH, OAUJS_PROVIDER_PATH, OAUJS_PROCESS_BANK, OAUJS_EXCLUDE_MODE)
  USING INDEX OL_AUTO_UPLOAD_JOB_STATUS_PK
  ENABLE VALIDATE);

