ALTER TABLE MI_ENTITY_OPB
 DROP PRIMARY KEY CASCADE;

DROP TABLE MI_ENTITY_OPB CASCADE CONSTRAINTS;

CREATE TABLE MI_ENTITY_OPB
(
  EO_ENTITY_ID         VARCHAR2(10 BYTE),
  EO_OPB_ID            VARCHAR2(10 BYTE)        NOT NULL,
  EO_OPB_NAME          VARCHAR2(50 BYTE),
  EO_IS_ACR_BANK       INTEGER,
  EO_OPB_STATUS        VARCHAR2(2 BYTE),
  EO_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  EO_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  EO_CREATE_USER       VARCHAR2(20 BYTE),
  EO_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MI_ENTITY_OPB_PK ON MI_ENTITY_OPB
(EO_OPB_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX MI_ENTITY_OPB_UK ON MI_ENTITY_OPB
(EO_ENTITY_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MI_ENTITY_OPB ADD (
  CONSTRAINT MI_ENTITY_OPB_PK
  PRIMARY KEY
  (EO_OPB_ID)
  USING INDEX MI_ENTITY_OPB_PK
  ENABLE VALIDATE,
  CONSTRAINT MI_ENTITY_OPB_UK
  UNIQUE (EO_ENTITY_ID)
  USING INDEX MI_ENTITY_OPB_UK
  ENABLE VALIDATE);

ALTER TABLE MI_ENTITY_OPB ADD (
  CONSTRAINT MI_ENTITY_OPB_FK01 
  FOREIGN KEY (EO_ENTITY_ID) 
  REFERENCES MI_ENTITY_DETAIL (ED_ENTITY_ID)
  ENABLE VALIDATE,
  CONSTRAINT MI_ENTITY_OPB_FK02 
  FOREIGN KEY (EO_OPB_STATUS) 
  REFERENCES DEF_STATUS (DS_TYPE)
  ENABLE VALIDATE);

