OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLTxnAckRetry
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLTxnAckRetry.so
SOOBJS =  OLTxnAckRetry.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
