ALTER TABLE MI_OL_ADJUSTMENT_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE MI_OL_ADJUSTMENT_TYPE CASCADE CONSTRAINTS;

CREATE TABLE MI_OL_ADJUSTMENT_TYPE
(
  MOAT_ENTITY_TYPE       CHAR(3 BYTE),
  MOAT_CODE              VARCHAR2(3 BYTE),
  MOAT_CODE_IN_NUM       NUMBER(3),
  MOAT_DESC              VARCHAR2(50 BYTE),
  MOAT_AMT_TYPE          CHAR(2 BYTE),
  MOAT_BAL_TYPE          CHAR(1 BYTE),
  MOAT_NATURE            CHAR(1 BYTE),
  MOAT_IS_PRORATA        INTEGER                DEFAULT 0,
  MOAT_DISABLED          INTEGER                DEFAULT 0,
  MOAT_CREATE_TIMESTAMP  DATE,
  MOAT_UPDATE_TIMESTAMP  DATE,
  MOAT_CREATE_USER       VARCHAR2(20 BYTE),
  MOAT_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MI_OL_ADJUSTMENT_TYPE_PK ON MI_OL_ADJUSTMENT_TYPE
(MOAT_ENTITY_TYPE, MOAT_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MI_OL_ADJUSTMENT_TYPE ADD (
  CONSTRAINT MI_OL_ADJUSTMENT_TYPE_PK
  PRIMARY KEY
  (MOAT_ENTITY_TYPE, MOAT_CODE)
  USING INDEX MI_OL_ADJUSTMENT_TYPE_PK
  ENABLE VALIDATE);

ALTER TABLE MI_OL_ADJUSTMENT_TYPE ADD (
  CONSTRAINT MI_OL_ADJUSTMENT_TYPE_FK01 
  FOREIGN KEY (MOAT_ENTITY_TYPE) 
  REFERENCES MI_DEF_ENTITY_TYPE (ET_TYPE_CODE)
  ENABLE VALIDATE,
  CONSTRAINT MI_OL_ADJUSTMENT_TYPE_FK02 
  FOREIGN KEY (MOAT_AMT_TYPE) 
  REFERENCES DEF_AMT_TYPE (DA_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT MI_OL_ADJUSTMENT_TYPE_FK03 
  FOREIGN KEY (MOAT_BAL_TYPE) 
  REFERENCES MI_DEF_BALANCE_TYPE (BT_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT MI_OL_ADJUSTMENT_TYPE_FK04 
  FOREIGN KEY (MOAT_NATURE) 
  REFERENCES DEF_ADJUSTMENT_NATURE (DN_CODE)
  ENABLE VALIDATE);

