OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/ACRThreshold
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBACRThreshold.so
SOOBJS =  ACRThreshold.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
