ALTER TABLE MMS_TXN_RETRY
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_TXN_RETRY CASCADE CONSTRAINTS;

CREATE TABLE MMS_TXN_RETRY
(
  MT_TXN_ID            VARCHAR2(16 BYTE),
  MT_PROCESS_TYPE      VARCHAR2(4 BYTE),
  MT_PROCESS_CODE      VARCHAR2(6 BYTE),
  MT_NODE_ID	       VARCHAR2(5),
  MT_TXN_AMOUNT        NUMBER(14,2),
  MT_TXN_CCY           CHAR(3 BYTE),
  MT_PSP_ID            VARCHAR2(10 BYTE),
  MT_MERCHANT_ID       VARCHAR2(15 BYTE),
  MT_TXN_DATETIME      VARCHAR2(14 BYTE),
  MT_RESEND_COUNT      INTEGER,
  MT_STATUS            CHAR(1 BYTE),
  MT_NEXT_TRY	       DATE,
  MT_CREATE_TIMESTAMP  DATE,
  MT_UPDATE_TIMESTAMP  DATE,
  MT_CREATE_USER       VARCHAR2(20 BYTE),
  MT_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX MMS_TXN_RETRY_IDX01 ON MMS_TXN_RETRY
(MT_STATUS,MT_NEXT_TRY)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX MMS_TXN_RETRY_PK ON MMS_TXN_RETRY
(MT_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_TXN_RETRY ADD (
  CONSTRAINT MMS_TXN_RETRY_PK
  PRIMARY KEY
  (MT_TXN_ID)
  USING INDEX MMS_TXN_RETRY_PK
  ENABLE VALIDATE);

