ALTER TABLE OL_PAYOUT_GENERATED_TMP
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_PAYOUT_GENERATED_TMP CASCADE CONSTRAINTS;

CREATE TABLE OL_PAYOUT_GENERATED_TMP
(
  OPT_ID                INTEGER,
  OPT_TXN_ID            VARCHAR2(16 BYTE),
  OPT_PSP_ID	       VARCHAR2(10 BYTE),
  OPT_BANK_CODE	       VARCHAR2(10 BYTE),
  OPT_DISABLED	       INTEGER 			DEFAULT 0,
  OPT_CREATE_USER       VARCHAR2(20 BYTE),
  OPT_UPDATE_USER       VARCHAR2(20 BYTE),
  OPT_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  OPT_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_PAYOUT_GENERATED_TMP_PK ON OL_PAYOUT_GENERATED_TMP
(OPT_ID, OPT_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_PAYOUT_GENERATED_TMP ADD (
  CONSTRAINT OL_PAYOUT_GENERATED_TMP_PK
  PRIMARY KEY
  (OPT_ID, OPT_TXN_ID)
  USING INDEX OL_PAYOUT_GENERATED_TMP_PK
  ENABLE VALIDATE);

