ALTER TABLE RULE_SCHEDULE_RECUR
 DROP PRIMARY KEY CASCADE;

DROP TABLE RULE_SCHEDULE_RECUR CASCADE CONSTRAINTS;

CREATE TABLE RULE_SCHEDULE_RECUR
(
  RR_SCHEDULER_ID      INTEGER,
  RR_DISABLED          INTEGER                  DEFAULT 0,
  RR_RECURRING_ID      INTEGER,
  RR_CREATE_USER       VARCHAR2(20 BYTE),
  RR_UPDATE_USER       VARCHAR2(20 BYTE),
  RR_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  RR_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX RULE_SCHEDULE_RECUR_PK ON RULE_SCHEDULE_RECUR
(RR_SCHEDULER_ID, RR_RECURRING_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE RULE_SCHEDULE_RECUR ADD (
  CONSTRAINT RULE_SCHEDULE_RECUR_PK
  PRIMARY KEY
  (RR_SCHEDULER_ID, RR_RECURRING_ID)
  USING INDEX RULE_SCHEDULE_RECUR_PK
  ENABLE VALIDATE);

ALTER TABLE RULE_SCHEDULE_RECUR ADD (
  CONSTRAINT RULE_SCHEDULE_RECUR_FK01 
  FOREIGN KEY (RR_SCHEDULER_ID) 
  REFERENCES RULE_SCHEDULER_HEADER (RS_SCHEDULER_ID)
  ENABLE VALIDATE);

