ALTER TABLE DEF_BANK
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_BANK CASCADE CONSTRAINTS;

CREATE TABLE DEF_BANK
(
  DB_INT_BANK_CODE     VARCHAR2(10 BYTE)        NOT NULL,
  DB_COUNTRY           VARCHAR2(2 BYTE)         NOT NULL,
  DB_CREATE_TIMESTAMP  DATE                     DEFAULT SYSDATE,
  DB_UPDATE_TIMESTAMP  DATE                     DEFAULT SYSDATE,
  DB_CREATE_USER       VARCHAR2(25 BYTE),
  DB_UPDATE_USER       VARCHAR2(25 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX DEF_BANK_IDX01 ON DEF_BANK
(DB_COUNTRY)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX DEF_BANK_PK ON DEF_BANK
(DB_INT_BANK_CODE)
LOGGING
TABLESPACE USER_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_BANK ADD (
  CONSTRAINT DEF_BANK_PK
  PRIMARY KEY
  (DB_INT_BANK_CODE)
  USING INDEX DEF_BANK_PK
  ENABLE VALIDATE);

