ALTER TABLE CUSTOMER_GROUP_PROMO_RULE
 DROP PRIMARY KEY CASCADE;

DROP TABLE CUSTOMER_GROUP_PROMO_RULE CASCADE CONSTRAINTS;

CREATE TABLE CUSTOMER_GROUP_PROMO_RULE
(
  CPR_MERCHANT_ID          VARCHAR2(15 BYTE),
  CPR_MIN_COUNT            INTEGER,
  CPR_MIN_AMOUNT           NUMBER(16,2),
  CPR_MIN_DAY		   INTEGER,
  CPR_DISABLED             INTEGER              DEFAULT 0,
  CPR_CREATE_USER          VARCHAR2(20 BYTE),
  CPR_UPDATE_USER          VARCHAR2(20 BYTE),
  CPR_CREATE_TIMESTAMP     DATE                 DEFAULT sysdate,
  CPR_UPDATE_TIMESTAMP     DATE                 DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CUSTOMER_GROUP_PROMO_RULE_PK ON CUSTOMER_GROUP_PROMO_RULE
(CPR_MERCHANT_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

ALTER TABLE CUSTOMER_GROUP_PROMO_RULE ADD (
  CONSTRAINT CUSTOMER_GROUP_PROMO_RULE_PK
  PRIMARY KEY
  (CPR_MERCHANT_ID)
  USING INDEX CUSTOMER_GROUP_PROMO_RULE_PK
  ENABLE VALIDATE);

