ALTER TABLE MMS_ENTITY_MASTER
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_ENTITY_MASTER CASCADE CONSTRAINTS;

CREATE TABLE MMS_ENTITY_MASTER
(
  MEM_CLIENT_ID         VARCHAR2(10 BYTE),
  MEM_CLIENT_NAME       VARCHAR2(50 BYTE),
  MEM_CREATE_TIMESTAMP  DATE,
  MEM_CREATE_USER       VARCHAR2(20 BYTE),
  MEM_UPDATE_TIMESTAMP  DATE,
  MEM_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MMS_BANK_MASTER_PK ON MMS_ENTITY_MASTER
(MEM_CLIENT_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


