ALTER TABLE RULE_CHECK_HAND_SHAKE
 DROP PRIMARY KEY CASCADE;

DROP TABLE RULE_CHECK_HAND_SHAKE CASCADE CONSTRAINTS;

CREATE TABLE RULE_CHECK_HAND_SHAKE
(
  RCHS_BUSINESS_TYPE        CHAR(1 BYTE),
  RCHS_CHECK_COUNT          INTEGER,
  RCHS_MAX_HANDSHAKE_COUNT  INTEGER,
  RCHS_START_BUFFER_PERIOD  INTEGER,
  RCHS_MIN_TOTAL            INTEGER,
  RCHS_MAX_INIT_COUNT       INTEGER,
  RCHS_CREATE_TIMESTAMP     DATE,
  RCHS_UPDATE_TIMESTAMP     DATE,
  RCHS_CREATE_USER          VARCHAR2(20 BYTE),
  RCHS_UPDATE_USER          VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX RULE_CHECK_HAND_SHAKE_PK ON RULE_CHECK_HAND_SHAKE
(RCHS_BUSINESS_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE RULE_CHECK_HAND_SHAKE ADD (
  CONSTRAINT RULE_CHECK_HAND_SHAKE_PK
  PRIMARY KEY
  (RCHS_BUSINESS_TYPE)
  USING INDEX RULE_CHECK_HAND_SHAKE_PK
  ENABLE VALIDATE);

