OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnMgtByUsJLD
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnMgtByUsJLD.so
SOOBJS = TxnMgtByUsJLD.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
