ALTER TABLE OL_DEF_FORMAT_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_DEF_FORMAT_TYPE CASCADE CONSTRAINTS;

CREATE TABLE OL_DEF_FORMAT_TYPE
(
  DT_NAME              VARCHAR2(20 BYTE),
  DT_DESC              VARCHAR2(50 BYTE),
  DT_FE_DISPLAY        INTEGER                   DEFAULT 0,
  DT_CREATE_TIMESTAMP  DATE                      DEFAULT sysdate,
  DT_CREATE_USER       VARCHAR2(20 BYTE),
  DT_UPDATE_TIMESTAMP  DATE                      DEFAULT sysdate,
  DT_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_DEF_FORMAT_TYPE_PK ON OL_DEF_FORMAT_TYPE
(DT_NAME)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_DEF_FORMAT_TYPE ADD (
  CONSTRAINT OL_DEF_FORMAT_TYPE_PK
  PRIMARY KEY
  (DT_NAME)
  USING INDEX OL_DEF_FORMAT_TYPE_PK
  ENABLE VALIDATE);

