ALTER TABLE OL_DEF_FORMAT_COL_NAME
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_DEF_FORMAT_COL_NAME CASCADE CONSTRAINTS;

CREATE TABLE OL_DEF_FORMAT_COL_NAME
(
  DC_INT_BANK_CODE     VARCHAR2(10 BYTE),
  DC_COL_NAME          VARCHAR2(50 BYTE),
  DC_DISABLED          INTEGER                   DEFAULT 0,
  DC_CREATE_TIMESTAMP  DATE                      DEFAULT sysdate,
  DC_CREATE_USER       VARCHAR2(20 BYTE),
  DC_UPDATE_TIMESTAMP  DATE                      DEFAULT sysdate,
  DC_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_DEF_FORMAT_COL_NAME_PK ON OL_DEF_FORMAT_COL_NAME
(DC_INT_BANK_CODE, DC_COL_NAME)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_DEF_FORMAT_COL_NAME ADD (
  CONSTRAINT OL_DEF_FORMAT_COL_NAME_PK
  PRIMARY KEY
  (DC_INT_BANK_CODE, DC_COL_NAME)
  USING INDEX OL_DEF_FORMAT_COL_NAME_PK
  ENABLE VALIDATE);

