OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/ParPspClientMap
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBParPspClientMap.so
SOOBJS =  ParPspClientMap.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
