ALTER TABLE PAYOUT_QUEUE_HD
 ADD (PQ_QUEUE_SEQ  INTEGER  default 1);
ALTER TABLE PAYOUT_QUEUE_HD
MODIFY(PQ_QUEUE_SEQ  DEFAULT NULL);

ALTER TABLE PAYOUT_QUEUE_HD
DROP CONSTRAINT;

DROP PAYOUT_QUEUE_HD_PK ON PAYOUT_QUEUE_HD;

CREATE UNIQUE INDEX PAYOUT_QUEUE_HD_PK ON PAYOUT_QUEUE_HD
(PQ_BATCH_ID, PQ_QUEUE_SEQ)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PAYOUT_QUEUE_HD ADD (
  CONSTRAINT PAYOUT_QUEUE_HD_PK
  PRIMARY KEY
  (PQ_BATCH_ID, PQ_QUEUE_SEQ)
  USING INDEX PAYOUT_QUEUE_HD_PK
  ENABLE VALIDATE);
