OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/PayoutQueueDt
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBPayoutQueueDt.so
SOOBJS =  PayoutQueueDt.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
