OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLEmailFunctService
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLEmailFunctService.so
SOOBJS =  OLEmailFunctService.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
