ALTER TABLE TMP_CAL_AMOUNT
 DROP PRIMARY KEY CASCADE;

DROP TABLE TMP_CAL_AMOUNT CASCADE CONSTRAINTS;

CREATE TABLE TMP_CAL_AMOUNT
(
  TC_TXN_ID       VARCHAR2(16 BYTE),
  TC_SRC_CCY      VARCHAR2(3 BYTE)              NOT NULL,
  TC_SRC_NET_AMT  NUMBER(14,2)                  DEFAULT 0                     NOT NULL,
  TC_SRC_FEE      NUMBER(14,2)                  DEFAULT 0,
  TC_DST_CCY      VARCHAR2(3 BYTE)              NOT NULL,
  TC_DST_NET_AMT  NUMBER(14,2)                  DEFAULT 0                     NOT NULL,
  TC_DST_FEE      NUMBER(14,2)                  DEFAULT 0,
  TC_EX_PARTY     CHAR(1 BYTE)                  NOT NULL,
  TC_EX_RATE      NUMBER(12,5)                  DEFAULT 0                     NOT NULL,
  TC_MARKUP_CCY   VARCHAR2(3 BYTE),
  TC_MARKUP_RATE  NUMBER(12,5)                  DEFAULT 0,
  TC_MARKUP_AMT   NUMBER(14,2)                  DEFAULT 0,
  TC_INTER_CCY    VARCHAR2(3 BYTE),
  TC_INTER_RATE   NUMBER(12,5)                  DEFAULT 0,
  TC_CREATE_TIMESTAMP	DATE	DEFAULT SYSDATE,
  TC_UPDATE_TIMESTAMP	DATE	DEFAULT SYSDATE,
  TC_CREATE_USER	VARCHAR2(20 BYTE),
  TC_UPDATE_USER	VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX TMP_CAL_AMOUNT_PK ON TMP_CAL_AMOUNT
(TC_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE TMP_CAL_AMOUNT ADD (
  CONSTRAINT TMP_CAL_AMOUNT_PK
  PRIMARY KEY
  (TC_TXN_ID)
  USING INDEX TMP_CAL_AMOUNT_PK
  ENABLE VALIDATE);

