ALTER TABLE PHUSER.OL_TXN_HEADER
 ADD (OTH_RECON_STATUS  CHAR(1 BYTE));

ALTER TABLE PHUSER.OL_TXN_HEADER
 ADD (OTH_RECON_DATE  VARCHAR2(8 BYTE));

ALTER TABLE PHUSER.OL_TXN_HEADER
 ADD (OTH_RECON_TIME  VARCHAR2(6 BYTE));

ALTER TABLE PHUSER.OL_TXN_HEADER
 ADD CONSTRAINT OL_TXN_HEADER_FK02 
  FOREIGN KEY (OTH_RECON_STATUS) 
  REFERENCES PHUSER.OL_DEF_RECON_STATUS (RS_TYPE)
  ENABLE VALIDATE;

