ALTER TABLE OL_MERCHANT_RESERVED_AMT
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_MERCHANT_RESERVED_AMT CASCADE CONSTRAINTS;

CREATE TABLE OL_MERCHANT_RESERVED_AMT
(
  OMR_MERCHANT_ID            VARCHAR2(15 BYTE),
  OMR_CURRENCY_ID            VARCHAR2(3 BYTE),
  OMR_COUNTRY_ID             CHAR(2 BYTE),
  OMR_SERVICE_CODE           CHAR(3 BYTE),
  OMR_DAY_OF_WEEK            INTEGER,
  OMR_TYPE                   CHAR(1 BYTE),
  OMR_RESERVED_AMOUNT	    NUMBER(14,2)         DEFAULT 0,
  OMR_REMAIN_RESERVED_AMOUNT NUMBER(14,2)	 DEFAULT 0,
  OMR_STATUS		    CHAR(1 BYTE),
  OMR_EFFECT_DATE	    DATE		DEFAULT sysdate,
  OMR_APPROVE_USER           VARCHAR2(20 BYTE),
  OMR_APPROVE_TIMESTAMP      DATE,
  OMR_CREATE_TIMESTAMP       DATE                 DEFAULT sysdate,
  OMR_UPDATE_TIMESTAMP       DATE                 DEFAULT sysdate,
  OMR_CREATE_USER            VARCHAR2(20 BYTE),
  OMR_UPDATE_USER            VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN OL_MERCHANT_RESERVED_AMT.OMR_TYPE IS '''D'' - Daily Capacity; ''R'' - Reserved Amount';

COMMENT ON COLUMN OL_MERCHANT_RESERVED_AMT.OMR_STATUS IS '''P'' - Pending; ''A'' - Approve';


CREATE UNIQUE INDEX OL_MERCHANT_RESERVED_AMT_PK ON OL_MERCHANT_RESERVED_AMT
(OMR_MERCHANT_ID, OMR_CURRENCY_ID, OMR_COUNTRY_ID, OMR_SERVICE_CODE, OMR_DAY_OF_WEEK, OMR_TYPE, OMR_STATUS, OMR_EFFECT_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_MERCHANT_RESERVED_AMT ADD (
  CONSTRAINT OL_MERCHANT_RESERVED_AMT_PK
  PRIMARY KEY
  (OMR_MERCHANT_ID, OMR_CURRENCY_ID, OMR_COUNTRY_ID, OMR_SERVICE_CODE, OMR_DAY_OF_WEEK, OMR_TYPE, OMR_STATUS, OMR_EFFECT_DATE)
  USING INDEX OL_MERCHANT_RESERVED_AMT_PK);

ALTER TABLE OL_MERCHANT_RESERVED_AMT ADD (
  CONSTRAINT OL_MERCHANT_RESERVED_AMT_FK03 
  FOREIGN KEY (OMR_SERVICE_CODE) 
  REFERENCES DEF_SERVICE_CODE (SC_CODE),
  CONSTRAINT OL_MERCHANT_RESERVED_AMT_FK01 
  FOREIGN KEY (OMR_MERCHANT_ID) 
  REFERENCES OL_MERCH_DETAIL (MD_MERCHANT_ID),
  CONSTRAINT OL_MERCHANT_RESERVED_AMT_FK02 
  FOREIGN KEY (OMR_CURRENCY_ID) 
  REFERENCES DEF_CURRENCY (DC_CCY_ID),
  CONSTRAINT OL_MERCHANT_RESERVED_AMT_FK04 
  FOREIGN KEY (OMR_COUNTRY_ID) 
  REFERENCES COUNTRY (COUNTRY_CODE));

