OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/BankTxnCheck
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBBankTxnCheck.so
SOOBJS =  BankTxnCheck.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
