OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLPayoutGeneratedTmp
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLPayoutGeneratedTmp.so
SOOBJS =  OLPayoutGeneratedTmp.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
