ALTER TABLE RULE_RECUR_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE RULE_RECUR_TYPE CASCADE CONSTRAINTS;

CREATE TABLE RULE_RECUR_TYPE
(
  RT_ID                INTEGER,
  RT_DAY               INTEGER,
  RT_START_TIME        VARCHAR2(6 BYTE)         NOT NULL,
  RT_END_TIME          VARCHAR2(6 BYTE),
  RT_DESC              VARCHAR2(50 BYTE),
  RT_DISABLED          INTEGER                  DEFAULT 0,
  RT_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  RT_CREATE_USER       VARCHAR2(20 BYTE),
  RT_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  RT_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX RULE_RECUR_TYPE_PK ON RULE_RECUR_TYPE
(RT_ID, RT_DAY, RT_START_TIME)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE RULE_RECUR_TYPE ADD (
  CONSTRAINT RULE_RECUR_TYPE_PK
  PRIMARY KEY
  (RT_ID, RT_DAY, RT_START_TIME)
  USING INDEX RULE_RECUR_TYPE_PK
  ENABLE VALIDATE);

