ALTER TABLE PAR_PRE_PO_REVERSED_DT
 DROP PRIMARY KEY CASCADE;

DROP TABLE PAR_PRE_PO_REVERSED_DT CASCADE CONSTRAINTS;

CREATE TABLE PAR_PRE_PO_REVERSED_DT
(
  PPD_FILE_DETAIL_ID     INTEGER,
  PPD_PO_TXN_NMB         VARCHAR2(50 BYTE),
  PPD_PSP_FILE_ID        INTEGER,
  PPD_PO_FILE_ID         INTEGER,
  PPD_PO_FILE_NAME       VARCHAR2(50 BYTE),
  PPD_SEQ_NMB            INTEGER,
  PPD_AMOUNT_CCY         VARCHAR2(3 BYTE),
  PPD_DEST_CCY           VARCHAR2(3 BYTE),
  PPD_COUNTRY            VARCHAR2(2 BYTE),
  PPD_AMOUNT             NUMBER(14,2),
  PPD_TXN_SEQ_NMB        INTEGER,
  PPD_MERCH_REF_NMB      VARCHAR2(50 BYTE),
  PPD_BANK_ACCOUNT_NMB   VARCHAR2(25 BYTE),
  PPD_BANK_ACCOUNT_NAME  VARCHAR2(100 BYTE),
  PPD_BANK_NAME          VARCHAR2(50 BYTE),
  PPD_BRANCH_NAME        VARCHAR2(100 BYTE),
  PPD_BANK_PROVINCE      VARCHAR2(50 BYTE),
  PPD_BANK_CITY          VARCHAR2(100 BYTE),
  PPD_ID_NMB             VARCHAR2(30 BYTE),
  PPD_PHONE_NMB          VARCHAR2(30 BYTE),
  PPD_BANK_CODE          VARCHAR2(5 BYTE),
  PPD_FUND_PURPOSE       VARCHAR2(30 BYTE),
  PPD_POST_DATE          DATE,
  PPD_UPDATE_DATE        DATE,
  PPD_UPLOAD_FILE_NAME   VARCHAR2(50 BYTE),
  PPD_CREATE_TIMESTAMP   DATE                   DEFAULT sysdate,
  PPD_CREATE_USER        VARCHAR2(20 BYTE),
  PPD_UPDATE_TIMESTAMP   DATE                   DEFAULT sysdate,
  PPD_UPDATE_USER        VARCHAR2(20 BYTE),
  PPD_UPLOAD_STATUS      VARCHAR2(10 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX PAR_PRE_PO_REVERSED_DT_IDX01 ON PAR_PRE_PO_REVERSED_DT
(PPD_PO_FILE_ID, PPD_SEQ_NMB)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

