ALTER TABLE DEPOSIT_TRACE
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEPOSIT_TRACE CASCADE CONSTRAINTS;

CREATE TABLE DEPOSIT_TRACE
(
  DTR_TXN_ID                VARCHAR2(16 BYTE)   NOT NULL,
  DTR_PARTY_TYPE            CHAR(1 BYTE)        NOT NULL,
  DTR_SEQ                   NUMBER(38)          NOT NULL,
  DTR_MERCHANT_ID           VARCHAR2(15 BYTE)   NOT NULL,
  DTR_CREATE_TIMESTAMP      DATE                DEFAULT sysdate               NOT NULL,
  DTR_CREATE_USER           VARCHAR2(20 BYTE),
  DTR_UPDATE_TIMESTAMP      DATE                DEFAULT sysdate               NOT NULL,
  DTR_UPDATE_USER           VARCHAR2(20 BYTE),
  DTR_SEND_EMAIL_TIMESTAMP  DATE,
  DTR_ENQUIRY_STATUS        CHAR(1 BYTE),
  DTR_FAIL_REASON           VARCHAR2(255 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE INDEX DEPOSIT_TRACE_IDX01 ON DEPOSIT_TRACE
(DTR_CREATE_TIMESTAMP)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX DEPOSIT_TRACE_PK ON DEPOSIT_TRACE
(DTR_TXN_ID, DTR_PARTY_TYPE, DTR_SEQ)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DEPOSIT_TRACE ADD (
  CONSTRAINT DEPOSIT_TRACE_PK
  PRIMARY KEY
  (DTR_TXN_ID, DTR_PARTY_TYPE, DTR_SEQ)
  USING INDEX DEPOSIT_TRACE_PK
  ENABLE VALIDATE);

ALTER TABLE DEPOSIT_TRACE ADD (
  CONSTRAINT DEPOSIT_TRACE_FK01 
  FOREIGN KEY (DTR_ENQUIRY_STATUS) 
  REFERENCES DEF_ENQUIRY_STATUS (DE_CODE)
  ENABLE VALIDATE);

