OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOMMSEntityPSP
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOMMSEntityPSP.so
SOOBJS = BOMMSEntityPSP.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
