ALTER TABLE MERCHANT_BALANCE
 DROP PRIMARY KEY CASCADE;

DROP TABLE MERCHANT_BALANCE CASCADE CONSTRAINTS;

CREATE TABLE MERCHANT_BALANCE
(
  M_MERCHANT_ID            VARCHAR2(10 BYTE),
  M_CURRENCY_ID            VARCHAR2(3 BYTE),
  M_COUNTRY_ID             CHAR(2 BYTE),
  M_SERVICE_CODE           CHAR(3 BYTE),
  M_CURRENT_BAL               NUMBER(14,2)         DEFAULT 0,
  M_TOTAL_FLOAT            NUMBER(14,2)         DEFAULT 0,
  M_TOTAL_RESERVED_AMOUNT  NUMBER(14,2)         DEFAULT 0,
  M_TOTAL_HOLD		   NUMBER(14,2)         DEFAULT 0,
  M_SETTLEMENT_IN_TRANSIT  NUMBER(14,2)         DEFAULT 0,
  M_CREATE_TIMESTAMP       DATE                 DEFAULT sysdate,
  M_UPDATE_TIMESTAMP       DATE                 DEFAULT sysdate,
  M_CREATE_USER            VARCHAR2(20 BYTE),
  M_UPDATE_USER            VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MERCHANT_BALANCE_PK ON MERCHANT_BALANCE
(M_MERCHANT_ID, M_CURRENCY_ID, M_COUNTRY_ID, M_SERVICE_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE MERCHANT_BALANCE ADD (
  CONSTRAINT MERCHANT_BALANCE_PK
  PRIMARY KEY
  (M_MERCHANT_ID, M_CURRENCY_ID, M_COUNTRY_ID, M_SERVICE_CODE)
  USING INDEX MERCHANT_BALANCE_PK);

ALTER TABLE MERCHANT_BALANCE ADD (
  CONSTRAINT MERCHANT_BALANCE_FK03 
  FOREIGN KEY (M_SERVICE_CODE) 
  REFERENCES DEF_SERVICE_CODE (SC_CODE),
  CONSTRAINT MERCHANT_BALANCE_FK01 
  FOREIGN KEY (M_MERCHANT_ID) 
  REFERENCES MERCH_DETAIL (MERCHANT_ID),
  CONSTRAINT MERCHANT_BALANCE_FK02 
  FOREIGN KEY (M_CURRENCY_ID) 
  REFERENCES DEF_CURRENCY (DC_CCY_ID),
  CONSTRAINT MERCHANT_BALANCE_FK04 
  FOREIGN KEY (M_COUNTRY_ID) 
  REFERENCES COUNTRY (COUNTRY_CODE));


CREATE INDEX MERCHANT_BALANCE_IDX01 ON MERCHANT_BALANCE
(M_MERCHANT_ID, M_CURRENCY_ID, M_COUNTRY_ID, M_SERVICE_CODE, M_DISABLED)
LOGGING
TABLESPACE USER_IDX
NOPARALLEL;
