OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLOtherBankMapping
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLOtherBankMapping.so
SOOBJS =  OLOtherBankMapping.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
