OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/TestCreate
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBTestCreate.so
SOOBJS =  TestCreate.o

include $(HOME)/config/Make.rules

LDLIBS +=

all : $(COMPSO)
