CREATE TABLE DEF_SERVICE_BRAND_NAME
(
  SCB_CODE              CHAR(3 BYTE),
  SCB_BRAND_NAME        VARCHAR2(100 BYTE),
  SCB_CREATE_USER       VARCHAR2(20 BYTE),
  SCB_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  SCB_UPDATE_USER       VARCHAR2(20 BYTE),
  SCB_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DEF_SERVICE_BRAND_NAME_PK ON DEF_SERVICE_BRAND_NAME
(SCB_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DEF_SERVICE_BRAND_NAME ADD (
  CONSTRAINT DEF_SERVICE_BRAND_NAME_PK
  PRIMARY KEY
  (SCB_CODE)
  USING INDEX DEF_SERVICE_BRAND_NAME_PK
  ENABLE VALIDATE);

