OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOSettlement
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOSettlement.so
SOOBJS = BOSettlement.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
