ALTER TABLE SYSTEM_EX_RULES
 ADD (SR_FR_TO_REVERSE  CHAR(1 BYTE));

COMMENT ON COLUMN SYSTEM_EX_RULES.SR_FR_TO_REVERSE IS 'Y - Yes; N - No';

update SYSTEM_EX_RULES set SR_FR_TO_REVERSE = 'N';
commit;

