ALTER TABLE SYSTEM_EX_RULES
 DROP PRIMARY KEY CASCADE;

DROP TABLE SYSTEM_EX_RULES CASCADE CONSTRAINTS;

CREATE TABLE SYSTEM_EX_RULES
(
  SR_TXN_CODE          CHAR(3 BYTE),
  SR_NONE_RESTRICTED   CHAR(6 BYTE)             NOT NULL,
  SR_RESTRICTED_1      CHAR(6 BYTE)             NOT NULL,
  SR_RESTRICTED_2      CHAR(6 BYTE),
  SR_RES1_RES2_OPR     VARCHAR2(6 BYTE)         NOT NULL,
  SR_MARKUP_AMT_OPR    CHAR(1 BYTE)             NOT NULL,
  SR_FR_TO_REVERSE     CHAR(1 BYTE)
  SR_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  SR_UPDATE_TIMESTAMP  DATE,
  SR_CREATE_USER       VARCHAR2(20 BYTE),
  SR_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN SYSTEM_EX_RULES.SR_RESTRICTED_2 IS 'Parameter + Avg Rate';
COMMENT ON COLUMN SYSTEM_EX_RULES.SR_FR_TO_REVERSE IS 'Y - Yes; N - No';



CREATE UNIQUE INDEX SYSTEM_EX_RULES_PK ON SYSTEM_EX_RULES
(SR_TXN_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE SYSTEM_EX_RULES ADD (
  CONSTRAINT SYSTEM_EX_RULES_PK
  PRIMARY KEY
  (SR_TXN_CODE)
  USING INDEX SYSTEM_EX_RULES_PK
  ENABLE VALIDATE);

ALTER TABLE SYSTEM_EX_RULES ADD (
  CONSTRAINT SYSTEM_EX_RULES_FK01 
  FOREIGN KEY (SR_TXN_CODE) 
  REFERENCES TXN_CODE (TC_CODE)
  ENABLE VALIDATE);

