ALTER TABLE ACR_TOLERANCE
 DROP PRIMARY KEY CASCADE;

DROP TABLE ACR_TOLERANCE CASCADE CONSTRAINTS;

CREATE TABLE ACR_TOLERANCE
(
  AT_COMPARE_WITH      VARCHAR2(10 BYTE),
  AT_BANK_CCY          VARCHAR2(3 BYTE),
  AT_TOLERANCE         NUMBER(14,2) NOT NULL,
  AT_CREATE_USER       VARCHAR2(20 BYTE),
  AT_CREATE_TIMESTAMP  DATE default sysdate,
  AT_UPDATE_USER       VARCHAR2(20 BYTE),
  AT_UPDATE_TIMESTAMP  DATE default sysdate
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ACR_TOLERANCE_PK ON ACR_TOLERANCE
(AT_COMPARE_WITH, AT_BANK_CCY)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE ACR_TOLERANCE ADD (
  CONSTRAINT ACR_TOLERANCE_PK
  PRIMARY KEY
  (AT_COMPARE_WITH, AT_BANK_CCY)
  USING INDEX ACR_TOLERANCE_PK);

