OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOOLPayout
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOOLPayout.so
SOOBJS = BOOLPayout.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
