OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLPayoutReconTriggerLog
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLPayoutReconTriggerLog.so
SOOBJS =  OLPayoutReconTriggerLog.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
