ALTER TABLE RULE_PSP_LB_PSP
 DROP PRIMARY KEY CASCADE;

DROP TABLE RULE_PSP_LB_PSP CASCADE CONSTRAINTS;

CREATE TABLE RULE_PSP_LB_PSP
(
  RPP_PSP_ID            VARCHAR2(10 BYTE),
  RPP_LIMIT             NUMBER(14,2)            DEFAULT 0                     NOT NULL,
  RPP_RATIO             INTEGER                 NOT NULL,
  RPP_PRIORITY          INTEGER                 NOT NULL,
  RPP_GUARANTEE_VOLUME  NUMBER(14,2)            DEFAULT 0                     NOT NULL,
  RPP_SCHEDULER_ID      INTEGER                 NOT NULL,
  RPP_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  RPP_CREATE_USER       VARCHAR2(20 BYTE),
  RPP_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  RPP_UPDATE_USER       VARCHAR2(20 BYTE),
  RPP_DISABLED          INTEGER                 DEFAULT 0
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN RULE_PSP_LB_PSP.RPP_LIMIT IS '0 - unlimited';

COMMENT ON COLUMN RULE_PSP_LB_PSP.RPP_GUARANTEE_VOLUME IS '0 - no guarantee';

CREATE INDEX PHUSER.RULE_PSP_LB_PSP_IDX01 ON PHUSER.RULE_PSP_LB_PSP
(RPP_PSP_ID, RPP_DISABLED)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RULE_PSP_LB_PSP_PK ON RULE_PSP_LB_PSP
(RPP_PSP_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE RULE_PSP_LB_PSP ADD (
  CONSTRAINT RULE_PSP_LB_PSP_PK
  PRIMARY KEY
  (RPP_PSP_ID)
  USING INDEX RULE_PSP_LB_PSP_PK
  ENABLE VALIDATE);

ALTER TABLE RULE_PSP_LB_PSP ADD (
  CONSTRAINT RULE_PSP_LB_PSP_FK01 
  FOREIGN KEY (RPP_PSP_ID) 
  REFERENCES PSP_DETAIL (PSP_ID)
  ENABLE VALIDATE,
  CONSTRAINT RULE_PSP_LB_PSP_FK02 
  FOREIGN KEY (RPP_SCHEDULER_ID) 
  REFERENCES RULE_SCHEDULER_HEADER (RS_SCHEDULER_ID)
  ENABLE VALIDATE);

