ALTER TABLE NON_HOLIDAY
 DROP PRIMARY KEY CASCADE;

DROP TABLE NON_HOLIDAY CASCADE CONSTRAINTS;

CREATE TABLE NON_HOLIDAY
(
  NH_COUNTRY           VARCHAR2(2 BYTE),
  NH_DATE              VARCHAR2(8 BYTE),
  NH_DESC              VARCHAR2(50 BYTE),
  NH_CREATE_USER       VARCHAR2(25 BYTE),
  NH_UPDATE_USER       VARCHAR2(25 BYTE),
  NH_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  NH_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX NON_HOLIDAY_PK ON NON_HOLIDAY
(NH_COUNTRY, NH_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE NON_HOLIDAY ADD (
  CONSTRAINT NON_HOLIDAY_PK
  PRIMARY KEY
  (NH_COUNTRY, NH_DATE)
  USING INDEX NON_HOLIDAY_PK
  ENABLE VALIDATE);

