ALTER TABLE DEF_SCHEDULE_MODE
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_SCHEDULE_MODE CASCADE CONSTRAINTS;

CREATE TABLE DEF_SCHEDULE_MODE
(
  DS_MODE              CHAR(1 BYTE),
  DS_DESC              VARCHAR2(50 BYTE),
  DS_CREATE_TIMESTAMP  DATE DEFAULT sysdate,
  DS_CREATE_USER       VARCHAR2(20 BYTE),
  DS_UPDATE_TIMESTAMP  DATE DEFAULT sysdate,
  DS_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEF_SCHEDULE_MODE_PK ON DEF_SCHEDULE_MODE
(DS_MODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_SCHEDULE_MODE ADD (
  CONSTRAINT DEF_SCHEDULE_MODE_PK
  PRIMARY KEY
  (DS_MODE)
  USING INDEX DEF_SCHEDULE_MODE_PK);

