OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLStmtMatchRuleGroup
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLStmtMatchRuleGroup.so
SOOBJS =  OLStmtMatchRuleGroup.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
