ALTER TABLE PAYPAGE_QR_TIME_PARAM
 DROP PRIMARY KEY CASCADE;

DROP TABLE PAYPAGE_QR_TIME_PARAM CASCADE CONSTRAINTS;

CREATE TABLE PAYPAGE_QR_TIME_PARAM
(
  PQTP_SERVICE_CODE           CHAR(3 BYTE)      NOT NULL,
  PQTP_PARTY_TYPE             CHAR(1 BYTE)      NOT NULL,
  PQTP_PARTY_ID               VARCHAR2(15 BYTE) NOT NULL,
  PQTP_EXPIRY                 NUMBER(38),
  PQTP_ENABLE_BUTTON          NUMBER(38),
  PQTP_AUTO_CHECK_TXN_STATUS  NUMBER(38),
  PQTP_REDIRECT               NUMBER(38),
  PQTP_DISABLED               NUMBER(1)         DEFAULT 0,
  PQTP_CREATE_TIMESTAMP       DATE              DEFAULT sysdate               NOT NULL,
  PQTP_CREATE_USER            VARCHAR2(20 BYTE),
  PQTP_UPDATE_TIMESTAMP       DATE              DEFAULT sysdate               NOT NULL,
  PQTP_UPDATE_USER            VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PAYPAGE_QR_TIME_PARAM_PK ON PAYPAGE_QR_TIME_PARAM
(PQTP_SERVICE_CODE, PQTP_PARTY_TYPE, PQTP_PARTY_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PAYPAGE_QR_TIME_PARAM ADD (
  CONSTRAINT PAYPAGE_QR_TIME_PARAM_PK
  PRIMARY KEY
  (PQTP_SERVICE_CODE, PQTP_PARTY_TYPE, PQTP_PARTY_ID)
  USING INDEX PAYPAGE_QR_TIME_PARAM_PK
  ENABLE VALIDATE);

