OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Msg
COMPLIBHOME = $(HOME)/lib/Msg
COMPOBJHOME = $(COMPHOME)/obj
BIN_PATH=$(HOME)/bin
LIB_PATH=/usr/lib
COMPSO = libmsg.so
SOOBJS = msg.o 
include $(HOME)/config/Make.rules

CPPFLAGS += -ljson-c
BIN =

all	: $(COMPSO) $(BIN)
