OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLPspTxnStatusRule
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLPspTxnStatusRule.so
SOOBJS =  OLPspTxnStatusRule.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
