ALTER TABLE EMAIL_SETTING
 DROP PRIMARY KEY CASCADE;

DROP TABLE EMAIL_SETTING CASCADE CONSTRAINTS;

CREATE TABLE EMAIL_SETTING
(
  ES_EMAIL_ID          INTEGER,
  ES_PARTY_TYPE        CHAR(1 BYTE),
  ES_PARTY_ID          VARCHAR2(15 BYTE),
  ES_FUNCT             VARCHAR2(15 BYTE),
  ES_DEFAULT           INTEGER            DEFAULT 1,
  ES_DISABLED          INTEGER            DEFAULT 0,
  ES_CREATE_USER       VARCHAR2(20 BYTE),
  ES_UPDATE_USER       VARCHAR2(20 BYTE),
  ES_CREATE_TIMESTAMP  DATE               DEFAULT SYSDATE,
  ES_UPDATE_TIMESTAMP  DATE               DEFAULT SYSDATE
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX EMAIL_SETTING_IDX01 ON EMAIL_SETTING
(ES_FUNCT, ES_PARTY_TYPE, ES_PARTY_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX EMAIL_SETTING_PK ON EMAIL_SETTING
(ES_EMAIL_ID, ES_PARTY_TYPE, ES_PARTY_ID, ES_FUNCT)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE EMAIL_SETTING ADD (
  CONSTRAINT EMAIL_SETTING_PK
  PRIMARY KEY
  (ES_EMAIL_ID, ES_PARTY_TYPE, ES_PARTY_ID, ES_FUNCT)
  USING INDEX EMAIL_SETTING_PK
  ENABLE VALIDATE);

ALTER TABLE EMAIL_SETTING ADD (
  CONSTRAINT EMAIL_SETTING_FK01
  FOREIGN KEY (ES_EMAIL_ID) 
  REFERENCES EMAIL_NOTIFY_LIST (EL_ID)
  ENABLE VALIDATE,
  CONSTRAINT EMAIL_SETTING_FK02
  FOREIGN KEY (ES_PARTY_TYPE) 
  REFERENCES DEF_PARTY_TYPE (DP_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT EMAIL_SETTING_FK03
  FOREIGN KEY (ES_FUNCT) 
  REFERENCES EMAIL_FUNCT (EF_FUNCT)
  ENABLE VALIDATE);

