ALTER TABLE CRR_OFL_PSP_PRODUCT_CODE_MAP
 DROP PRIMARY KEY CASCADE;

DROP TABLE CRR_OFL_PSP_PRODUCT_CODE_MAP CASCADE CONSTRAINTS;

CREATE TABLE CRR_OFL_PSP_PRODUCT_CODE_MAP
(
  OPPM_PSP_ID           VARCHAR2(10 BYTE),
  OPPM_BUSINESS_TYPE     CHAR(1 BYTE),
  OPPM_EFFECTIVE_DATE       VARCHAR2(8 BYTE),
  OPPM_PRODUCT_CODE      VARCHAR2(3 BYTE),
  OPPM_CREATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  OPPM_UPDATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  OPPM_CREATE_USER       VARCHAR2(20 BYTE),
  OPPM_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CRR_OFL_PSP_PRODUCT_CODE_M_PK ON CRR_OFL_PSP_PRODUCT_CODE_MAP
(OPPM_PSP_ID, OPPM_BUSINESS_TYPE, OPPM_EFFECTIVE_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE CRR_OFL_PSP_PRODUCT_CODE_MAP ADD (
  CONSTRAINT CRR_OFL_PSP_PRODUCT_CODE_M_PK
  PRIMARY KEY
  (OPPM_PSP_ID, OPPM_BUSINESS_TYPE, OPPM_EFFECTIVE_DATE)
  USING INDEX CRR_OFL_PSP_PRODUCT_CODE_M_PK
  ENABLE VALIDATE);

