OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/testing
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
//COMPSO = libDBTesting.so
SOOBJS =  Testing.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
