ALTER TABLE CRR_JNL_ENTRY_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE CRR_JNL_ENTRY_TYPE CASCADE CONSTRAINTS;

CREATE TABLE CRR_JNL_ENTRY_TYPE
(
	JNL_TYPE_ID		INT	NOT NULL,
	ENTRY_TYPE_ID		VARCHAR2(20)	NOT NULL,
	COL_ID				NUMBER(3)	NOT NULL,
	DESCRIPTION		VARCHAR2(100)	NULL,
	DISABLED	NUMBER(1)	DEFAULT 0,
	CREATE_TIMESTAMP	DATE	DEFAULT SYSDATE,
	UPDATE_TIMESTAMP	DATE	DEFAULT SYSDATE,
	CREATE_USER	VARCHAR2(20),
	UPDATE_USER	VARCHAR2(20)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX CRR_JNL_ENTRY_TYPE_PK ON CRR_JNL_ENTRY_TYPE
(JNL_TYPE_ID, ENTRY_TYPE_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE CRR_JNL_ENTRY_TYPE ADD (
  CONSTRAINT CRR_JNL_ENTRY_TYPE_PK
  PRIMARY KEY
  (JNL_TYPE_ID, ENTRY_TYPE_ID)
  USING INDEX CRR_JNL_ENTRY_TYPE_PK);
  
ALTER TABLE CRR_JNL_ENTRY_TYPE ADD (
  CONSTRAINT CRR_JNL_ENTRY_TYPE_FK01
  FOREIGN KEY (JNL_TYPE_ID) 
  REFERENCES CRR_JNL_TYPE (JNL_TYPE_ID));      

