ALTER TABLE OL_PSP_COSTS_EXCLUDE
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_PSP_COSTS_EXCLUDE CASCADE CONSTRAINTS;

CREATE TABLE OL_PSP_COSTS_EXCLUDE
(
  OPCE_RULE_ID            INTEGER,
  OPCE_EXCLUDE_ACCT_TYPE    VARCHAR2(10 BYTE),
  OPCE_CREATE_TIMESTAMP   DATE                  DEFAULT sysdate,
  OPCE_UPDATE_TIMESTAMP   DATE                  DEFAULT sysdate,
  OPCE_CREATE_USER        VARCHAR2(20 BYTE),
  OPCE_UPDATE_USER        VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_PSP_COSTS_EXCLUDE_PK ON OL_PSP_COSTS_EXCLUDE
(OPCE_RULE_ID,OPCE_EXCLUDE_ACCT_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_PSP_COSTS_EXCLUDE ADD (
  CONSTRAINT OL_PSP_COSTS_EXCLUDE_PK
  PRIMARY KEY
  (OPCE_RULE_ID,OPCE_EXCLUDE_ACCT_TYPE)
  USING INDEX OL_PSP_COSTS_EXCLUDE_PK
  ENABLE VALIDATE);

