CREATE TABLE OL_MERCH_PSP_BATCH_TYPE
(
  OMPBT_BATCH_ID    	  VARCHAR2(16 BYTE)	NOT NULL,
  OMPBT_TYPE          	  CHAR(1 BYTE)          NOT NULL,
  OMPBT_CREATE_USER       VARCHAR2(20 BYTE),
  OMPBT_CREATE_TIMESTAMP  DATE                  DEFAULT sysdate,
  OMPBT_UPDATE_USER       VARCHAR2(20 BYTE),
  OMPBT_UPDATE_TIMESTAMP  DATE                  DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_MERCH_PSP_BATCH_TYPE_PK ON OL_MERCH_PSP_BATCH_TYPE
(OMPBT_BATCH_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_MERCH_PSP_BATCH_TYPE ADD (
  CONSTRAINT OL_MERCH_PSP_BATCH_TYPE_PK
  PRIMARY KEY
  (OMPBT_BATCH_ID)
  USING INDEX OL_MERCH_PSP_BATCH_TYPE_PK
  ENABLE VALIDATE);

ALTER TABLE OL_MERCH_PSP_BATCH_TYPE ADD (
  CONSTRAINT OL_MERCH_PSP_BATCH_TYPE_FK01 
  FOREIGN KEY (OMPBT_TYPE) 
  REFERENCES DEF_MERCH_PSP_TYPE (DMPT_TYPE)
  ENABLE VALIDATE);

