OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLRulePaypageBank
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLRulePaypageBank.so
SOOBJS =  OLRulePaypageBank.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
