OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MiBatchHeader
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMiBatchHeader.so
SOOBJS =  MiBatchHeader.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
