ALTER TABLE MMS_TXN_CODE_MAP
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_TXN_CODE_MAP CASCADE CONSTRAINTS;

CREATE TABLE MMS_TXN_CODE_MAP
(
  MM_INT_CODE          CHAR(3 BYTE),
  MM_EXT_CODE          CHAR(3 BYTE),
  MM_DESC              VARCHAR2(50 BYTE),
  MM_UPDATE_USER       VARCHAR2(20 BYTE),
  MM_UPDATE_TIMESTAMP  DATE,
  MM_CREATE_USER       VARCHAR2(20 BYTE),
  MM_CREATE_TIMESTAMP  DATE
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX MMS_TXN_CODE_MAP_IDX01 ON MMS_TXN_CODE_MAP
(MM_INT_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX MMS_TXN_CODE_MAP_IDX02 ON MMS_TXN_CODE_MAP
(MM_EXT_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX MMS_TXN_CODE_MAP_PK ON MMS_TXN_CODE_MAP
(MM_INT_CODE, MM_EXT_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_TXN_CODE_MAP ADD (
  CONSTRAINT MMS_TXN_CODE_MAP_PK
  PRIMARY KEY
  (MM_INT_CODE, MM_EXT_CODE)
  USING INDEX MMS_TXN_CODE_MAP_PK
  ENABLE VALIDATE);

