OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOMMMBalance
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOMMMBalance.so
SOOBJS = BOMMMBalance.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
