OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOEmailSetting
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOEmailSetting.so
SOOBJS = BOEmailSetting.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
