OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/PayoutGeneratedFileDT
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBPayoutGeneratedFileDT.so
SOOBJS =  PayoutGeneratedFileDT.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
