OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/TestNini
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBTestNini.so
SOOBJS =  TestNini.o

include $(HOME)/config/Make.rules

LDLIBS +=

all : $(COMPSO)
