ALTER TABLE TXN_FE_URL
 DROP PRIMARY KEY CASCADE;

DROP TABLE TXN_FE_URL CASCADE CONSTRAINTS;

CREATE TABLE TXN_FE_URL
(
  TXN_CODE          VARCHAR2(3 BYTE),
  SERVICE_CODE      CHAR(3 BYTE),
  DIRECTION         CHAR(1 BYTE),
  METHOD            VARCHAR2(3 BYTE),
  PATH              VARCHAR2(50 BYTE),
  EFFECT_DATE       DATE,
  DISABLED          INTEGER,
  CREATE_TIMESTAMP  DATE                        DEFAULT sysdate,
  UPDATE_TIMESTAMP  DATE                        DEFAULT sysdate,
  CREATE_USER       VARCHAR2(20 BYTE),
  UPDATE_USER       VARCHAR2(20 BYTE),
  LANGUAGE          CHAR(2 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN TXN_FE_URL.DIRECTION IS 'r - Request R - Response';

COMMENT ON COLUMN TXN_FE_URL.METHOD IS 'TXT - CLEAR TXT, B64 Base64, SHA - SHA Encoding, MD5 - MD5 Encoding';



CREATE INDEX TXN_FE_URL_IDX01 ON TXN_FE_URL
(DISABLED)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX TXN_FE_URL_PK ON TXN_FE_URL
(TXN_CODE, SERVICE_CODE, DIRECTION, EFFECT_DATE, LANGUAGE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE TXN_FE_URL ADD (
  CONSTRAINT TXN_FE_URL_PK
  PRIMARY KEY
  (TXN_CODE, SERVICE_CODE, DIRECTION, EFFECT_DATE, LANGUAGE)
  USING INDEX TXN_FE_URL_PK
  ENABLE VALIDATE);

