OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLMerchantSettlementDetail
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLMerchantSettlementDetail.so
SOOBJS =  OLMerchantSettlementDetail.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
