ALTER TABLE TEST_ZALE
 DROP PRIMARY KEY CASCADE;

DROP TABLE TEST_ZALE CASCADE CONSTRAINTS;

CREATE TABLE TEST_ZALE
(
	TZ_TXN_CODE			CHAR(3 BYTE),
	TZ_GROUP			CHAR(1 BYTE)			NOT NULL,
	TZ_FLAG				INTEGER				DEFAULT 0,
	TZ_VALUE			NUMBER(14,2)			DEFAULT 0.0,
	TZ_REMARK			VARCHAR2(255 BYTE),
	TZ_CREATE_USER			VARCHAR2(20 BYTE),
	TZ_CREATE_TIMESTAMP		DATE				DEFAULT sysdate,
	TZ_UPDATE_USER			VARCHAR2(20 BYTE),
	TZ_UPDATE_TIMESTAMP		DATE				DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED		0
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE		(
			INITIAL			64K
			NEXT			1M
			MINEXTENTS		1
			MAXEXTENTS		UNLIMITED
			PCTINCREASE		0
			BUFFER_POOL		DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;

CREATE UNIQUE INDEX TEST_ZALE_PK ON TEST_ZALE
(TZ_TXN_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE		10
INITRANS	2
MAXTRANS	255
STORAGE		(
			INITIAL			64K
			NEXT			1M
			MINEXTENTS		1
			MAXEXTENTS		UNLIMITED
			PCTINCREASE		0
			BUFFER_POOL		DEFAULT
		);

ALTER TABLE TEST_ZALE ADD (
	CONSTRAINT TEST_ZALE_PK
	PRIMARY KEY
	(TZ_TXN_CODE)
	USING INDEX TEST_ZALE_PK
	ENABLE VALIDATE
);
