ALTER TABLE TEST_ZALE DROP CONSTRAINT TEST_ZALE_PK;

DROP INDEX TEST_ZALE_PK;

CREATE UNIQUE INDEX TEST_ZALE_PK ON TEST_ZALE
(TZ_TXN_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL     64K
            NEXT        1M
            MINEXTENTS  1
            MAXEXTENTS  UNLIMITED
            PCTINCREASE 0
            BUFFER_POOL DEFAULT
           );

ALTER TABLE TEST_ZALE ADD (
  CONSTRAINT TEST_ZALE_PK
  PRIMARY KEY
  (TZ_TXN_CODE)
  USING INDEX TEST_ZALE_PK
  ENABLE VALIDATE);
