OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLStmtMatchFilter
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLStmtMatchFilter.so
SOOBJS =  OLStmtMatchFilter.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
