ALTER TABLE MI_ENTITY_BAL_MAP
 DROP PRIMARY KEY CASCADE;

DROP TABLE MI_ENTITY_BAL_MAP CASCADE CONSTRAINTS;

CREATE TABLE MI_ENTITY_BAL_MAP
(
  EBM_ENTITY_TYPE       CHAR(3 BYTE),
  EBM_BAL_TYPE          CHAR(1 BYTE),
  EBM_ALLOW_BAL_NEGATIVE INTEGER	DEFAULT 0,
  EBM_DISABLED          INTEGER		DEFAULT 0,
  EBM_CREATE_TIMESTAMP  DATE,
  EBM_UPDATE_TIMESTAMP  DATE,
  EBM_CREATE_USER       VARCHAR2(20 BYTE),
  EBM_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MI_ENTITY_BAL_MAP_PK ON MI_ENTITY_BAL_MAP
(EBM_ENTITY_TYPE, EBM_BAL_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MI_ENTITY_BAL_MAP ADD (
  CONSTRAINT MI_ENTITY_BAL_MAP_PK
  PRIMARY KEY
  (EBM_ENTITY_TYPE, EBM_BAL_TYPE)
  USING INDEX MI_ENTITY_BAL_MAP_PK
  ENABLE VALIDATE);

ALTER TABLE MI_ENTITY_BAL_MAP ADD (
  CONSTRAINT MI_ENTITY_BAL_MAP_FK01 
  FOREIGN KEY (EBM_ENTITY_TYPE) 
  REFERENCES MI_DEF_ENTITY_TYPE (ET_TYPE_CODE)
  ENABLE VALIDATE,
  CONSTRAINT MI_ENTITY_BAL_MAP_FK02 
  FOREIGN KEY (EBM_BAL_TYPE) 
  REFERENCES MI_DEF_BALANCE_TYPE (BT_TYPE)
  ENABLE VALIDATE);

