ALTER TABLE MI_DEF_ENTITY_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE MI_DEF_ENTITY_TYPE CASCADE CONSTRAINTS;

CREATE TABLE MI_DEF_ENTITY_TYPE
(
  ET_TYPE_CODE            CHAR(3 BYTE)          NOT NULL,
  ET_TYPE_DESC            VARCHAR2(50 BYTE),
  ET_ADJ_BAL_POOL_OPTION  INTEGER,
  ET_FE_DISPLAY           INTEGER,
  ET_OFL_FE_DISPLAY       INTEGER,
  ET_CREATE_TIMESTAMP     DATE                  DEFAULT sysdate,
  ET_UPDATE_TIMESTAMP     DATE                  DEFAULT sysdate,
  ET_CREATE_USER          VARCHAR2(20 BYTE),
  ET_UPDATE_USER          VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MI_DEF_ENTITY_TYPE_PK ON MI_DEF_ENTITY_TYPE
(ET_TYPE_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MI_DEF_ENTITY_TYPE ADD (
  CONSTRAINT MI_DEF_ENTITY_TYPE_PK
  PRIMARY KEY
  (ET_TYPE_CODE)
  USING INDEX MI_DEF_ENTITY_TYPE_PK
  ENABLE VALIDATE);

