ALTER TABLE OL_TXN_BROWSER_INFO
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_TXN_BROWSER_INFO CASCADE CONSTRAINTS;

CREATE TABLE OL_TXN_BROWSER_INFO
(
  OTB_TXN_ID            VARCHAR2(16 BYTE),
  OTB_CLIENT_IP         VARCHAR2(25 BYTE),
  OTB_USER_AGENT        VARCHAR2(255 BYTE),
  OTB_CREATE_USER       VARCHAR2(20 BYTE),
  OTB_UPDATE_USER       VARCHAR2(20 BYTE),
  OTB_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  OTB_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX OL_TXN_BROWSER_INFO_IDX01 ON OL_TXN_BROWSER_INFO
(OTB_TXN_ID, OTB_CLIENT_IP)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX OL_TXN_BROWSER_INFO_IDX02 ON OL_TXN_BROWSER_INFO
(OTB_TXN_ID, OTB_USER_AGENT)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX OL_TXN_BROWSER_INFO_PK ON OL_TXN_BROWSER_INFO
(OTB_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_TXN_BROWSER_INFO ADD (
  CONSTRAINT OL_TXN_BROWSER_INFO_PK
  PRIMARY KEY
  (OTB_TXN_ID)
  USING INDEX OL_TXN_BROWSER_INFO_PK
  ENABLE VALIDATE);

ALTER TABLE OL_TXN_BROWSER_INFO ADD (
  CONSTRAINT OL_TXN_BROWSER_INFO_FK01 
  FOREIGN KEY (OTB_TXN_ID) 
  REFERENCES OL_TXN_HEADER (OTH_TXN_ID)
  ENABLE VALIDATE);

