ALTER TABLE PAR_PAYOUT_STATUS
 DROP PRIMARY KEY CASCADE;

DROP TABLE PAR_PAYOUT_STATUS CASCADE CONSTRAINTS;

CREATE TABLE PAR_PAYOUT_STATUS
(
  PS_TYPE              VARCHAR2(2 BYTE),
  PS_STATUS            VARCHAR2(50 BYTE),
  PS_STATUS_ID         INTEGER,
  PS_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  PS_CREATE_USER       VARCHAR2(20 BYTE),
  PS_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  PS_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PAR_PAYOUT_STATUS_PK ON PAR_PAYOUT_STATUS
(PS_TYPE, PS_STATUS)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PAR_PAYOUT_STATUS ADD (
  CONSTRAINT PAR_PAYOUT_STATUS_PK
  PRIMARY KEY
  (PS_TYPE, PS_STATUS)
  USING INDEX PAR_PAYOUT_STATUS_PK
  ENABLE VALIDATE);

