ALTER TABLE OL_STATEMENT_DETAIL
MODIFY(OLSD_TFR_TYPE VARCHAR2(640 BYTE));

ALTER TABLE OL_STATEMENT_DETAIL
MODIFY(OLSD_TFR_CHANNEL VARCHAR2(640 BYTE));

ALTER TABLE OL_STATEMENT_DETAIL
MODIFY(OLSD_TFR_CUSTOMER_TEXT VARCHAR2(640 BYTE));
