


ALTER TABLE OL_STATEMENT_DETAIL ADD OLSD_TXN_LOCATION VARCHAR2(640 BYTE);

ALTER TABLE OL_STATEMENT_DETAIL ADD OLSD_TXN_TYPE VARCHAR2(640 BYTE);

ALTER TABLE OL_STATEMENT_DETAIL ADD OLSD_TXN_REFERENCE VARCHAR2(640 BYTE);

