


ALTER TABLE OL_STATEMENT_HEADER
 ADD (OLSH_ACCT_TYPE  VARCHAR2(3));

ALTER TABLE OL_STATEMENT_HEADER
 ADD (OLSH_AUTO_UPLOAD  INTEGER);

CREATE INDEX OL_STATEMENT_HEADER_IDX04 ON OL_STATEMENT_HEADER
(OLSH_ACCT_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
