OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLUploadError
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLUploadError.so
SOOBJS =  OLUploadError.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
