CREATE TABLE DEF_AMT_DIFF_SIGN
(
	DS_CODE					CHAR(1 BYTE),
	DS_SIGN					VARCHAR2(5 BYTE),
	DS_DESC					VARCHAR2(50 BYTE),
	DS_CREATE_TIMESTAMP		DATE				DEFAULT sysdate,
	DS_CREATE_USER			VARCHAR2(20 BYTE),
	DS_UPDATE_TIMESTAMP		DATE				DEFAULT sysdate,
	DS_UPDATE_USER			VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE INDEX DEF_AMT_DIFF_SIGN_PK ON DEF_AMT_DIFF_SIGN
(DS_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DEF_AMT_DIFF_SIGN ADD (
  CONSTRAINT DEF_AMT_DIFF_SIGN_PK
  PRIMARY KEY
  (DS_CODE)
  USING INDEX DEF_AMT_DIFF_SIGN_PK
  ENABLE VALIDATE);