OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/RuleLB
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBRuleLB.so
SOOBJS =  RuleLB.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
