ALTER TABLE RULE_TXN_BANK_CHARGE
 DROP PRIMARY KEY CASCADE;

DROP TABLE RULE_TXN_BANK_CHARGE CASCADE CONSTRAINTS;

CREATE TABLE RULE_TXN_BANK_CHARGE
(
  RTBC_BANK_CODE         VARCHAR2(10 BYTE)      NOT NULL,
  RTBC_COUNTRY           CHAR(2 BYTE)           NOT NULL,
  RTBC_CCY               VARCHAR2(3 BYTE)       NOT NULL,
  RTBC_CHANNEL_CODE      VARCHAR2(3 BYTE)       NOT NULL,
  RTBC_TXN_CODE          VARCHAR2(3 BYTE)       NOT NULL,
  RTBC_AMOUNT_ID         INTEGER                NOT NULL,
  RTBC_MIN_VALUE         NUMBER(14,2)           NOT NULL,
  RTBC_MAX_VALUE         NUMBER(14,2),
  RTBC_EFFECT_DATE       DATE                   DEFAULT sysdate               NOT NULL,
  RTBC_DISABLED          INTEGER                DEFAULT 0,
  RTBC_CREATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  RTBC_UPDATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  RTBC_CREATE_USER       VARCHAR2(20 BYTE),
  RTBC_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX RULE_TXN_BANK_CHARGE_PK ON RULE_TXN_BANK_CHARGE
(RTBC_BANK_CODE, RTBC_COUNTRY, RTBC_CCY, 
RTBC_CHANNEL_CODE, RTBC_TXN_CODE, RTBC_AMOUNT_ID, RTBC_MIN_VALUE, RTBC_EFFECT_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE RULE_TXN_BANK_CHARGE ADD (
  CONSTRAINT RULE_TXN_BANK_CHARGE_PK
  PRIMARY KEY
  (RTBC_BANK_CODE, RTBC_COUNTRY, RTBC_CCY, RTBC_CHANNEL_CODE, RTBC_TXN_CODE, RTBC_AMOUNT_ID, RTBC_MIN_VALUE, RTBC_EFFECT_DATE)
  USING INDEX RULE_TXN_BANK_CHARGE_PK
  ENABLE VALIDATE);

ALTER TABLE RULE_TXN_BANK_CHARGE ADD (
  CONSTRAINT RULE_TXN_BANK_CHARGE_FK01 
  FOREIGN KEY (RTBC_COUNTRY) 
  REFERENCES COUNTRY (COUNTRY_CODE)
  ENABLE VALIDATE,
  CONSTRAINT RULE_TXN_BANK_CHARGE_FK02 
  FOREIGN KEY (RTBC_CCY) 
  REFERENCES DEF_CURRENCY (DC_CCY_ID)
  ENABLE VALIDATE);

