OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLTxnBrowserInfo
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLTxnBrowserInfo.so
SOOBJS =  OLTxnBrowserInfo.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
