ALTER TABLE MMS_DEF_ADJ_TXN_CODE_PREFIX
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_DEF_ADJ_TXN_CODE_PREFIX CASCADE CONSTRAINTS;

CREATE TABLE MMS_DEF_ADJ_TXN_CODE_PREFIX
(
  MATCP_PREFIX            CHAR(1 BYTE)          NOT NULL,
  MATCP_DESC              VARCHAR2(50 BYTE),
  MATCP_CREATE_TIMESTAMP  DATE                  DEFAULT sysdate,
  MATCP_CREATE_USER       VARCHAR2(20 BYTE),
  MATCP_UPDATE_TIMESTAMP  DATE                  DEFAULT sysdate,
  MATCP_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MMS_DEF_ADJ_TXN_CODE_PREFIX_PK ON MMS_DEF_ADJ_TXN_CODE_PREFIX
(MATCP_PREFIX)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_DEF_ADJ_TXN_CODE_PREFIX ADD (
  CONSTRAINT MMS_DEF_ADJ_TXN_CODE_PREFIX_PK
  PRIMARY KEY
  (MATCP_PREFIX)
  USING INDEX MMS_DEF_ADJ_TXN_CODE_PREFIX_PK
  ENABLE VALIDATE);

