OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLPayoutApiBatchDT
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLPayoutApiBatchDT.so
SOOBJS =  OLPayoutApiBatchDT.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
