OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmsInstantPMAcctDt
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmsInstantPMAcctDt.so
SOOBJS =  MmsInstantPMAcctDt.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
