ALTER TABLE OL_PID_BAL
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_PID_BAL CASCADE CONSTRAINTS;

CREATE TABLE OL_PID_BAL
(
  OPB_PID               VARCHAR2(20 BYTE),
  OPB_COUNTRY_ID        VARCHAR2(3 BYTE)        NOT NULL,
  OPB_CURRENCY_ID       VARCHAR2(3 BYTE)        NOT NULL,
  OPB_BAL               NUMBER(14,2)            DEFAULT 0,
  OPB_TOTAL_HOLD        NUMBER(14,2)            DEFAULT 0,
  OPB_CREATE_USER       VARCHAR2(20 BYTE)       NOT NULL,
  OPB_CREATE_TIMESTAMP  DATE                    NOT NULL,
  OPB_UPDATE_USER       VARCHAR2(20 BYTE),
  OPB_UPDATE_TIMESTAMP  DATE                    NOT NULL
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_PID_BAL_PK ON OL_PID_BAL
(OPB_PID,OPB_COUNTRY_ID,OPB_CURRENCY_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_PID_BAL ADD (
  CONSTRAINT OL_PID_BAL_PK
  PRIMARY KEY
  (OPB_PID,OPB_COUNTRY_ID,OPB_CURRENCY_ID)
  USING INDEX OL_PID_BAL_PK
  ENABLE VALIDATE);

ALTER TABLE OL_PID_BAL ADD (
  CONSTRAINT OL_PID_BAL_FK01 
  FOREIGN KEY (OPB_PID) 
  REFERENCES OL_PSP_DETAIL (OPD_PSP_ID)
  ENABLE VALIDATE);

