OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOCrrJnl
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOCrrJnl.so
SOOBJS = BOCrrJnl.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
