OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOReport
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOReport.so
SOOBJS = BOReport.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
