OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOExchange/mantis1104
COMPLIBHOME = $(HOME)/lib/BO/mantis1104
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOExchange.so
SOOBJS = BOExchange.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
