ALTER TABLE MERCHANT_UPLOAD_FILE_DETAIL
 DROP PRIMARY KEY CASCADE;

DROP TABLE MERCHANT_UPLOAD_FILE_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE MERCHANT_UPLOAD_FILE_DETAIL
(
  UD_BATCH_ID             NUMBER(16)            NOT NULL,
  UD_TXN_ID               VARCHAR2(16 BYTE),
  UD_AUX_TXN_ID           VARCHAR2(16 BYTE),
  UD_SEQ_NUM              INTEGER               NOT NULL,
  UD_MERCHANT_REF         VARCHAR2(25 BYTE)     NOT NULL,
  UD_COUNTRY              VARCHAR2(2 BYTE)      NOT NULL,
  UD_IDENTITY_ID          VARCHAR2(25 BYTE),
  UD_ACCOUNT_NUM          VARCHAR2(25 BYTE)     NOT NULL,
  UD_ACCOUNT_NAME         VARCHAR2(100 BYTE)     NOT NULL,
  UD_BANK_NAME            VARCHAR2(50 BYTE)     NOT NULL,
  UD_BANK_CODE            VARCHAR2(25 BYTE),
  UD_BRANCH               VARCHAR2(100 BYTE)    NOT NULL,
  UD_PHONE_NUM            VARCHAR2(25 BYTE),
  UD_PROVINCE             VARCHAR2(50 BYTE),
  UD_CITY                 VARCHAR2(100 BYTE),
  UD_PAYOUT_AMOUNT        NUMBER(12,2)          DEFAULT 0,
  UD_REQUEST_AMOUNT       NUMBER(12,2)          DEFAULT 0,
  UD_PAYOUT_CURRENCY      VARCHAR2(3 BYTE),
  UD_REQUEST_CURRENCY     VARCHAR2(3 BYTE),
  UD_MEMBER_FEE_CCY       VARCHAR2(3 BYTE),
  UD_MEMBER_FEE           NUMBER(12,2)          DEFAULT 0,
  UD_MERCHANT_FEE_CCY     VARCHAR2(3 BYTE),
  UD_MERCHANT_FEE         NUMBER(12,2)          DEFAULT 0,
  UD_MARKUP_CCY           VARCHAR2(3 BYTE),
  UD_MARKUP_AMT           NUMBER(12,2)          DEFAULT 0,
  UD_EXCHANGE_RATE        NUMBER(14,5)          DEFAULT 1,
  UD_PAYOUT_TXN_NUM       VARCHAR2(50 BYTE),
  UD_STATUS               INTEGER,
  UD_RESPONSE_CODE        VARCHAR2(6 BYTE),
  UD_REMARK               VARCHAR2(255 BYTE),
  UD_DISABLED             INTEGER               DEFAULT 0,
  UD_BATCH_MODE           CHAR(1 BYTE),
  UD_GENERATED_FILE_ID    NUMBER(16),
  UD_GENERATED_FILE_NAME  VARCHAR2(50 BYTE),
  UD_PSP_BATCH_ID         VARCHAR2(16 BYTE),
  UD_FUNDOUT_DATE         VARCHAR2(14 BYTE),
  UD_SERVICE_FEE          NUMBER(12,2),
  UD_TID                  VARCHAR2(20 BYTE),
  UD_PSP_ID               VARCHAR2(10 BYTE),
  UD_APPROVE_ID           INTEGER,
  UD_CREATE_TIMESTAMP     DATE                  DEFAULT sysdate,
  UD_UPDATE_TIMESTAMP     DATE                  DEFAULT sysdate,
  UD_UPDATE_USER          VARCHAR2(20 BYTE),
  UD_CREATE_USER          VARCHAR2(20 BYTE),
  UD_VNC_REF_NUM          VARCHAR2(16 BYTE),
  UD_PREGEN_PSP_ID        VARCHAR2(10 BYTE),
  UD_PREGEN_FILE_ID       NUMBER(16),
  UD_PREAPPROVE_ID	  INTEGER
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN MERCHANT_UPLOAD_FILE_DETAIL.UD_BATCH_MODE IS '''O'' - Online, ''F'' - Offline';



CREATE UNIQUE INDEX MERCHANT_UPLOAD_FILE_DETAIL_PK ON MERCHANT_UPLOAD_FILE_DETAIL
(UD_BATCH_ID, UD_SEQ_NUM)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX MERCHANT_UPLOAD_FILE_DT_IDX01 ON MERCHANT_UPLOAD_FILE_DETAIL
(UD_BATCH_ID, UD_STATUS)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX MERCHANT_UPLOAD_FILE_DT_IDX02 ON MERCHANT_UPLOAD_FILE_DETAIL
(UD_APPROVE_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX MERCHANT_UPLOAD_FILE_DT_IDX03 ON MERCHANT_UPLOAD_FILE_DETAIL
(UD_BATCH_ID, UD_BANK_NAME)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX MERCHANT_UPLOAD_FILE_DT_IDX04 ON MERCHANT_UPLOAD_FILE_DETAIL
(UD_BATCH_ID, UD_REQUEST_AMOUNT)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX MERCHANT_UPLOAD_FILE_DT_IDX05 ON MERCHANT_UPLOAD_FILE_DETAIL
(UD_GENERATED_FILE_ID, UD_STATUS)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX MERCHANT_UPLOAD_FILE_DT_IDX06 ON MERCHANT_UPLOAD_FILE_DETAIL
(UD_BATCH_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX MERCHANT_UPLOAD_FILE_DT_IDX07 ON MERCHANT_UPLOAD_FILE_DETAIL
(UD_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX MERCHANT_UPLOAD_FILE_DT_IDX08 ON MERCHANT_UPLOAD_FILE_DETAIL
(UD_BATCH_ID, UD_STATUS, UD_BATCH_MODE, UD_PSP_ID, UD_DISABLED)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX MERCHANT_UPLOAD_FILE_DT_IDX09 ON MERCHANT_UPLOAD_FILE_DETAIL
(UD_STATUS, UD_BATCH_MODE, UD_PSP_ID, UD_DISABLED)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX MERCHANT_UPLOAD_FILE_DT_IDX10 ON MERCHANT_UPLOAD_FILE_DETAIL
(UD_BATCH_ID, UD_STATUS, UD_DISABLED, UD_BATCH_MODE, UD_PREGEN_PSP_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX MERCHANT_UPLOAD_FILE_DT_IDX11 ON MERCHANT_UPLOAD_FILE_DETAIL
(UD_STATUS, UD_BATCH_MODE, UD_DISABLED, UD_PREGEN_PSP_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX MERCHANT_UPLOAD_FILE_DT_IDX12 ON MERCHANT_UPLOAD_FILE_DETAIL
(UD_BATCH_ID, UD_STATUS, UD_DISABLED, UD_BATCH_MODE, UD_PREGEN_FILE_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX MERCHANT_UPLOAD_FILE_DT_IDX13 ON MERCHANT_UPLOAD_FILE_DETAIL
(UD_STATUS, UD_DISABLED, UD_BATCH_MODE, UD_PREGEN_FILE_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX MERCHANT_UPLOAD_FILE_DT_IDX14 ON MERCHANT_UPLOAD_FILE_DETAIL
(UD_BATCH_ID, UD_BANK_NAME, UD_STATUS, UD_BATCH_MODE, UD_DISABLED, 
UD_PSP_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX MERCHANT_UPLOAD_FILE_DT_IDX15 ON MERCHANT_UPLOAD_FILE_DETAIL
(UD_PREGEN_FILE_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX MERCHANT_UPLOAD_FILE_DT_IDX16 ON MERCHANT_UPLOAD_FILE_DETAIL
(UD_MERCHANT_REF, UD_STATUS, UD_DISABLED)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX MERCHANT_UPLOAD_FILE_DT_IDX17 ON MERCHANT_UPLOAD_FILE_DETAIL
(UD_TXN_ID, UD_STATUS, UD_DISABLED)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MERCHANT_UPLOAD_FILE_DETAIL ADD (
  CONSTRAINT MERCHANT_UPLOAD_FILE_DETAIL_PK
  PRIMARY KEY
  (UD_BATCH_ID, UD_SEQ_NUM)
  USING INDEX MERCHANT_UPLOAD_FILE_DETAIL_PK
  ENABLE VALIDATE);

