OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLAutoUploadStmtSettLog
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLAutoUploadStmtSettLog.so
SOOBJS = OLAutoUploadStmtSettLog.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
