OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLNonTxnMsgDetail
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLNonTxnMsgDetail.so
SOOBJS =  OLNonTxnMsgDetail.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
