OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOOLBalance
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOOLBalance.so
SOOBJS = BOOLBalance.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
