OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/SkipAcrRule
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBSkipAcrRule.so
SOOBJS =  SkipAcrRule.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
