OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=offline_auto_match.exec
BATCHOBJS=$(OBJHOME)/batchcommon.o offline_auto_match.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS += -lexpat -lcurl -lc -lm -lmyhash -lObjPtr -lmyrecordset
all: $(BATCHEXE)
