ALTER TABLE PAYOUT_OPERATOR_TYPE_DETAIL
 DROP PRIMARY KEY CASCADE;

DROP TABLE PAYOUT_OPERATOR_TYPE_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE PAYOUT_OPERATOR_TYPE_DETAIL
(
  OD_TYPE              CHAR(2 BYTE)             NOT NULL,
  OD_TIER_ID	       INTEGER             	NOT NULL,
  OD_AMT_PCT	       NUMBER(12,2)		DEFAULT 1,
  OD_AMT_MIN	       NUMBER(12,2)		NOT NULL,
  OD_AMT_MAX	       NUMBER(12,2)		NOT NULL,
  OD_REMARK            VARCHAR2(255 BYTE),
  OD_DISABLED          INTEGER                  DEFAULT 0,
  OD_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  OD_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  OD_CREATE_USER       VARCHAR2(20 BYTE),
  OD_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PAYOUT_OPERATOR_TYPE_DETAIL_PK ON PAYOUT_OPERATOR_TYPE_DETAIL
(OD_TYPE, OD_TIER_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE PAYOUT_OPERATOR_TYPE_DETAIL ADD (
  CONSTRAINT PAYOUT_OPERATOR_TYPE_DETAIL_PK
  PRIMARY KEY
  (OD_TYPE, OD_TIER_ID)
  USING INDEX PAYOUT_OPERATOR_TYPE_DETAIL_PK);

