


ALTER TABLE DEF_SETTLEMENT_PERIOD_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_SETTLEMENT_PERIOD_TYPE CASCADE CONSTRAINTS;

CREATE TABLE DEF_SETTLEMENT_PERIOD_TYPE
(
  SP_CODE              VARCHAR2(5 BYTE)         NOT NULL,
  SP_DESC              VARCHAR2(50 BYTE),
  SP_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  SP_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  SP_CREATE_USER       VARCHAR2(20 BYTE),
  SP_UPDATE_USER       VARCHAR2(20 BYTE),
  SP_ORDER             INTEGER
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DEF_SETTLEMENT_PERIOD_TYPE_PK ON DEF_SETTLEMENT_PERIOD_TYPE
(SP_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DEF_SETTLEMENT_PERIOD_TYPE ADD (
  CONSTRAINT DEF_SETTLEMENT_PERIOD_TYPE_PK
  PRIMARY KEY
  (SP_CODE)
  USING INDEX DEF_SETTLEMENT_PERIOD_TYPE_PK
  ENABLE VALIDATE);
