ALTER TABLE SYSTEM_PARAMETER
 DROP PRIMARY KEY CASCADE;

DROP TABLE SYSTEM_PARAMETER CASCADE CONSTRAINTS;

CREATE TABLE SYSTEM_PARAMETER
(
  SP_CODE              VARCHAR2(50 BYTE)        NOT NULL,
  SP_DESC              VARCHAR2(240 BYTE)       NOT NULL,
  SP_VAL               VARCHAR2(50 BYTE)        NOT NULL,
  SP_DELETABLE         INTEGER                  DEFAULT 0,
  SP_CREATE_USER       VARCHAR2(20 BYTE),
  SP_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  SP_UPDATE_USER       VARCHAR2(20 BYTE),
  SP_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN SYSTEM_PARAMETER.SP_DELETABLE IS '1-yes, 0-no';



CREATE UNIQUE INDEX SYSTEM_PARAMETER_PK ON SYSTEM_PARAMETER
(SP_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE SYSTEM_PARAMETER ADD (
  CONSTRAINT PK_SYSTEM_PARAMETER_PK
  PRIMARY KEY
  (SP_CODE)
  USING INDEX SYSTEM_PARAMETER_PK
  ENABLE VALIDATE);

