OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLPayoutReturn
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLPayoutReturn.so
SOOBJS =  OLPayoutReturn.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
