OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLMerchantBankAcct
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLMerchantBankAcct.so
SOOBJS =  OLMerchantBankAcct.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
