ALTER TABLE DEF_EXCHANGE_SUPPLIER
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_EXCHANGE_SUPPLIER CASCADE CONSTRAINTS;

CREATE TABLE DEF_EXCHANGE_SUPPLIER
(
  ES_TYPE              CHAR(1 BYTE)             NOT NULL,
  ES_DESC              VARCHAR2(50 BYTE),
  ES_CREATE_USER       VARCHAR2(20 BYTE),
  ES_CREATE_TIMESTAMP  DATE			DEFAULT SYSDATE,
  ES_UPDATE_USER       VARCHAR2(20 BYTE),
  ES_UPDATE_TIMESTAMP  DATE			DEFAULT SYSDATE
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEF_EXCHANGE_SUPPLIER_PK ON DEF_EXCHANGE_SUPPLIER
(ES_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_EXCHANGE_SUPPLIER ADD (
  CONSTRAINT DEF_EXCHANGE_SUPPLIER_PK
  PRIMARY KEY
  (ES_TYPE)
  USING INDEX DEF_EXCHANGE_SUPPLIER_PK);
