OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnMgtByUsRLR
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnMgtByUsRLR.so
SOOBJS = TxnMgtByUsRLR.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
