OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=OfflineWTB.exec
SOAPCPP=/usr/local/bin/soapcpp2
#
#
# Include the Common Rules
#
#

include ../Make.rules


CPPFLAGS += -I$(HOME)/src/MQ -I$(HOME)/src/Tools/Ndbm -I../ -I.
LDLIBS +=   /usr/local/lib/libgsoapssl.a  -lObjPtr -lmyrecordset -lgsoap -lssl -lcrypto -lz  -DWITH_OPENSSL -DWITH_GZIP   -Wall -Werror

PROCPPFLAGS += INCLUDE=.

all: $(BATCHEXE)
OfflineWTB.exec        : OfflineWTB.o  soapC.o soapClient.o
	$(CPP) $(OBJHOME)/OfflineWTB.o $(OBJHOME)/soapC.o $(OBJHOME)/soapClient.o $(SHARED_LIB_OBJS) $(LDFLAGS) $(LDLIBS) -o $@

OfflineWTB.o : OfflineWTB.pc

clean:
	rm -f OfflineWTB.exec
	rm -f *.xml
	rm -f soap*
	rm -f *.nsmap

s2c     :
	$(SOAPCPP) -c twv.h
