/* soapClient.c
   Generated by gSOAP 2.8.9 from twv.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.8.9 2012-11-13 08:30:15 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__DepositOnlineInit(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *access_USCOREkey, char *order_USCOREnum, int amount, char *description, char *return_USCOREurl, struct ns2__DepositOnlineInitResponse *_param_1)
{	struct ns2__DepositOnlineInit soap_tmp_ns2__DepositOnlineInit;
	if (!soap_endpoint)
		soap_endpoint = "https://www.twv.com.tw:443/gps.new/sys/server_HK101001.php";
	if (!soap_action)
		soap_action = "https://www.twv.com.tw/gps.new/sys/server_ntl#DepositOnlineInit";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns2__DepositOnlineInit.access_USCOREkey = access_USCOREkey;
	soap_tmp_ns2__DepositOnlineInit.order_USCOREnum = order_USCOREnum;
	soap_tmp_ns2__DepositOnlineInit.amount = amount;
	soap_tmp_ns2__DepositOnlineInit.description = description;
	soap_tmp_ns2__DepositOnlineInit.return_USCOREurl = return_USCOREurl;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns2__DepositOnlineInit(soap, &soap_tmp_ns2__DepositOnlineInit);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__DepositOnlineInit(soap, &soap_tmp_ns2__DepositOnlineInit, "ns2:DepositOnlineInit", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__DepositOnlineInit(soap, &soap_tmp_ns2__DepositOnlineInit, "ns2:DepositOnlineInit", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_1)
		return soap_closesock(soap);
	soap_default_ns2__DepositOnlineInitResponse(soap, _param_1);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns2__DepositOnlineInitResponse(soap, _param_1, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__DepositIbonInit(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *access_USCOREkey, char *order_USCOREnum, char *owner_USCOREid, int amount, char *description, struct ns2__DepositIbonInitResponse *_param_2)
{	struct ns2__DepositIbonInit soap_tmp_ns2__DepositIbonInit;
	if (!soap_endpoint)
		soap_endpoint = "https://www.twv.com.tw:443/gps.new/sys/server_HK101001.php";
	if (!soap_action)
		soap_action = "https://www.twv.com.tw/gps.new/sys/server_ntl#DepositIbonInit";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns2__DepositIbonInit.access_USCOREkey = access_USCOREkey;
	soap_tmp_ns2__DepositIbonInit.order_USCOREnum = order_USCOREnum;
	soap_tmp_ns2__DepositIbonInit.owner_USCOREid = owner_USCOREid;
	soap_tmp_ns2__DepositIbonInit.amount = amount;
	soap_tmp_ns2__DepositIbonInit.description = description;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns2__DepositIbonInit(soap, &soap_tmp_ns2__DepositIbonInit);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__DepositIbonInit(soap, &soap_tmp_ns2__DepositIbonInit, "ns2:DepositIbonInit", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__DepositIbonInit(soap, &soap_tmp_ns2__DepositIbonInit, "ns2:DepositIbonInit", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_2)
		return soap_closesock(soap);
	soap_default_ns2__DepositIbonInitResponse(soap, _param_2);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns2__DepositIbonInitResponse(soap, _param_2, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__WithdrawInit(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *access_USCOREkey, struct WithdrawInitInfoArray *withdraw_USCORElist, struct ns2__WithdrawInitResponse *_param_3)
{	struct ns2__WithdrawInit soap_tmp_ns2__WithdrawInit;
	if (!soap_endpoint)
		soap_endpoint = "https://www.twv.com.tw:443/gps.new/sys/server_HK101001.php";
	if (!soap_action)
		soap_action = "https://www.twv.com.tw/gps.new/sys/server_ntl#WithdrawInit";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns2__WithdrawInit.access_USCOREkey = access_USCOREkey;
	soap_tmp_ns2__WithdrawInit.withdraw_USCORElist = withdraw_USCORElist;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns2__WithdrawInit(soap, &soap_tmp_ns2__WithdrawInit);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__WithdrawInit(soap, &soap_tmp_ns2__WithdrawInit, "ns2:WithdrawInit", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__WithdrawInit(soap, &soap_tmp_ns2__WithdrawInit, "ns2:WithdrawInit", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_3)
		return soap_closesock(soap);
	soap_default_ns2__WithdrawInitResponse(soap, _param_3);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns2__WithdrawInitResponse(soap, _param_3, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__DepositInquiry(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *access_USCOREkey, char *tid, struct ns2__DepositInquiryResponse *_param_4)
{	struct ns2__DepositInquiry soap_tmp_ns2__DepositInquiry;
	if (!soap_endpoint)
		soap_endpoint = "https://www.twv.com.tw:443/gps.new/sys/server_HK101001.php";
	if (!soap_action)
		soap_action = "https://www.twv.com.tw/gps.new/sys/server_ntl#DepositInquiry";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns2__DepositInquiry.access_USCOREkey = access_USCOREkey;
	soap_tmp_ns2__DepositInquiry.tid = tid;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns2__DepositInquiry(soap, &soap_tmp_ns2__DepositInquiry);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__DepositInquiry(soap, &soap_tmp_ns2__DepositInquiry, "ns2:DepositInquiry", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__DepositInquiry(soap, &soap_tmp_ns2__DepositInquiry, "ns2:DepositInquiry", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_4)
		return soap_closesock(soap);
	soap_default_ns2__DepositInquiryResponse(soap, _param_4);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns2__DepositInquiryResponse(soap, _param_4, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__WithdrawInquiry(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *access_USCOREkey, char *tid, struct ns2__WithdrawInquiryResponse *_param_5)
{	struct ns2__WithdrawInquiry soap_tmp_ns2__WithdrawInquiry;
	if (!soap_endpoint)
		soap_endpoint = "https://www.twv.com.tw:443/gps.new/sys/server_HK101001.php";
	if (!soap_action)
		soap_action = "https://www.twv.com.tw/gps.new/sys/server_ntl#WithdrawInquiry";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns2__WithdrawInquiry.access_USCOREkey = access_USCOREkey;
	soap_tmp_ns2__WithdrawInquiry.tid = tid;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns2__WithdrawInquiry(soap, &soap_tmp_ns2__WithdrawInquiry);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__WithdrawInquiry(soap, &soap_tmp_ns2__WithdrawInquiry, "ns2:WithdrawInquiry", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__WithdrawInquiry(soap, &soap_tmp_ns2__WithdrawInquiry, "ns2:WithdrawInquiry", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_5)
		return soap_closesock(soap);
	soap_default_ns2__WithdrawInquiryResponse(soap, _param_5);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns2__WithdrawInquiryResponse(soap, _param_5, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__PingAlive(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *access_USCOREkey, int *status)
{	struct ns2__PingAlive soap_tmp_ns2__PingAlive;
	struct ns2__PingAliveResponse *soap_tmp_ns2__PingAliveResponse;
	if (!soap_endpoint)
		soap_endpoint = "https://www.twv.com.tw:443/gps.new/sys/server_HK101001.php";
	if (!soap_action)
		soap_action = "https://www.twv.com.tw/gps.new/sys/server_ntl#PingAlive";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns2__PingAlive.access_USCOREkey = access_USCOREkey;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns2__PingAlive(soap, &soap_tmp_ns2__PingAlive);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__PingAlive(soap, &soap_tmp_ns2__PingAlive, "ns2:PingAlive", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__PingAlive(soap, &soap_tmp_ns2__PingAlive, "ns2:PingAlive", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!status)
		return soap_closesock(soap);
	soap_default_int(soap, status);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns2__PingAliveResponse = soap_get_ns2__PingAliveResponse(soap, NULL, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (status && soap_tmp_ns2__PingAliveResponse->status)
		*status = *soap_tmp_ns2__PingAliveResponse->status;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
