/* twv.h
   Generated by wsdl2h 2.8.0 from https://www.twv.com.tw/gps.new/sys/server_HK101001.php?wsdl and typemap.dat
   2011-03-04 02:06:25 GMT

   DO NOT INCLUDE THIS FILE DIRECTLY INTO YOUR PROJECT BUILDS
   USE THE soapcpp2-GENERATED SOURCE CODE FILES FOR YOUR PROJECT BUILDS

   gSOAP XML Web services tools.
   Copyright (C) 2001-2010 Robert van Engelen, Genivia Inc. All Rights Reserved.
   Part of this software is released under one of the following licenses:
   GPL or Genivia's license for commercial use.
*/

/** @page page_notes Usage Notes

NOTE:

 - Run soapcpp2 on twv.h to generate the SOAP/XML processing logic.
   Use soapcpp2 option -I to specify paths for #import
   To build with STL, 'stlvector.h' is imported from 'import' dir in package.
   Use soapcpp2 option -i to generate improved proxy and server classes.
 - Use wsdl2h options -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Use Doxygen (www.doxygen.org) on this file to generate documentation.
 - Use wsdl2h options -nname and -Nname to globally rename the prefix 'ns'.
 - Use wsdl2h option -d to enable DOM support for xsd:anyType.
 - Use wsdl2h option -g to auto-generate readers and writers for root elements.
 - Struct/class members serialized as XML attributes are annotated with a '@'.
 - Struct/class members that have a special role are annotated with a '$'.

WARNING:

   DO NOT INCLUDE THIS FILE DIRECTLY INTO YOUR PROJECT BUILDS.
   USE THE SOURCE CODE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT BUILDS:
   THE soapStub.h FILE CONTAINS THIS CONTENT WITHOUT ANNOTATIONS.

LICENSE:

@verbatim
--------------------------------------------------------------------------------
gSOAP XML Web services tools
Copyright (C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.

This software is released under one of the following two licenses:
1) GPL or 2) Genivia's license for commercial use.
--------------------------------------------------------------------------------
1) GPL license.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place, Suite 330, Boston, MA 02111-1307 USA

Author contact information:
engelen@genivia.com / engelen@acm.org
--------------------------------------------------------------------------------
2) A commercial-use license is available from Genivia, Inc., contact@genivia.com
--------------------------------------------------------------------------------
@endverbatim

*/


//gsoapopt cw

/******************************************************************************\
 *                                                                            *
 * Definitions                                                                *
 *   https://www.twv.com.tw/gps.new/sys/server_HK101001.php?wsdl              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

ns1 = "https://www.twv.com.tw/gps.new/sys/server_HK101001.php?wsdl"

*/

#define SOAP_NAMESPACE_OF_ns1	"https://www.twv.com.tw/gps.new/sys/server_HK101001.php?wsdl"
//gsoap ns1   schema namespace:	https://www.twv.com.tw/gps.new/sys/server_HK101001.php?wsdl
//gsoap ns1   schema form:	unqualified

/******************************************************************************\
 *                                                                            *
 * Built-in Schema Types and Top-Level Elements and Attributes                *
 *                                                                            *
\******************************************************************************/



/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   https://www.twv.com.tw/gps.new/sys/server_HK101001.php?wsdl              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   https://www.twv.com.tw/gps.new/sys/server_HK101001.php?wsdl              *
 *                                                                            *
\******************************************************************************/


/// "https://www.twv.com.tw/gps.new/sys/server_HK101001.php?wsdl":DepositType is a complexType.
struct ns1__DepositType
{
/// Element tid of type xs:string.
    char*                                tid                            1;	///< Required element.
/// Element req_time of type xs:dateTime.
    time_t                               req_USCOREtime                 1;	///< Required element.
/// Element status of type xs:int.
    int                                  status                         1;	///< Required element.
/// Element order_num of type xs:string.
    char*                                order_USCOREnum                1;	///< Required element.
/// Element pay_type of type xs:int.
    int                                  pay_USCOREtype                 1;	///< Required element.
/// Element amount of type xs:int.
    int                                  amount                         1;	///< Required element.
/// Element bank_code of type xs:string.
    char*                                bank_USCOREcode               ;	///< Nullable pointer.
/// Element bank_branch of type xs:string.
    char*                                bank_USCOREbranch             ;	///< Nullable pointer.
/// Element account_name of type xs:string.
    char*                                account_USCOREname            ;	///< Nullable pointer.
/// Element account_no of type xs:string.
    char*                                account_USCOREno              ;	///< Nullable pointer.
/// Element owner_id of type xs:string.
    char*                                owner_USCOREid                 1;	///< Required element.
/// Element description of type xs:string.
    char*                                description                    1;	///< Required element.
/// Element error_code of type xs:int.
    int                                  error_USCOREcode               1;	///< Required element.
/// Element batch_id of type xs:int.
    int                                  batch_USCOREid                 1;	///< Required element.
/// Element fundin_date of type xs:dateTime.
    time_t*                              fundin_USCOREdate             ;	///< Nullable pointer.
/// Element service_fee of type xs:int.
    int*                                 service_USCOREfee             ;	///< Nullable pointer.
};

/// "https://www.twv.com.tw/gps.new/sys/server_HK101001.php?wsdl":WithdrawType is a complexType.
struct ns1__WithdrawType
{
/// Element tid of type xs:string.
    char*                                tid                            1;	///< Required element.
/// Element req_time of type xs:dateTime.
    time_t                               req_USCOREtime                 1;	///< Required element.
/// Element status of type xs:int.
    int                                  status                         1;	///< Required element.
/// Element batch_id of type xs:int.
    int                                  batch_USCOREid                 1;	///< Required element.
/// Element order_num of type xs:string.
    char*                                order_USCOREnum                1;	///< Required element.
/// Element amount of type xs:int.
    int                                  amount                         1;	///< Required element.
/// Element bank_code of type xs:string.
    char*                                bank_USCOREcode                1;	///< Required element.
/// Element bank_branch of type xs:string.
    char*                                bank_USCOREbranch              1;	///< Required element.
/// Element account_id of type xs:string.
    char*                                account_USCOREid               1;	///< Required element.
/// Element account_name of type xs:string.
    char*                                account_USCOREname             1;	///< Required element.
/// Element account_no of type xs:string.
    char*                                account_USCOREno               1;	///< Required element.
/// Element error_code of type xs:int.
    int*                                 error_USCOREcode              ;	///< Nullable pointer.
/// Element fundout_date of type xs:dateTime.
    time_t*                              fundout_USCOREdate            ;	///< Nullable pointer.
/// Element service_fee of type xs:int.
    int*                                 service_USCOREfee             ;	///< Nullable pointer.
};

/// "https://www.twv.com.tw/gps.new/sys/server_HK101001.php?wsdl":WithdrawInitInfo is a complexType.
struct ns1__WithdrawInitInfo
{
/// Element order_num of type xs:string.
    char*                                order_USCOREnum                1;	///< Required element.
/// Element bank_code of type xs:string.
    char*                                bank_USCOREcode                1;	///< Required element.
/// Element bank_branch of type xs:string.
    char*                                bank_USCOREbranch              1;	///< Required element.
/// Element account_id of type xs:string.
    char*                                account_USCOREid               1;	///< Required element.
/// Element account_name of type xs:string.
    char*                                account_USCOREname             1;	///< Required element.
/// Element account_no of type xs:string.
    char*                                account_USCOREno               1;	///< Required element.
/// Element amount of type xs:int.
    int                                  amount                         1;	///< Required element.
};

/// "https://www.twv.com.tw/gps.new/sys/server_HK101001.php?wsdl":WithdrawInitResult is a complexType.
struct ns1__WithdrawInitResult
{
/// Element tid of type xs:string.
    char*                                tid                            1;	///< Required element.
/// Element order_num of type xs:string.
    char*                                order_USCOREnum                1;	///< Required element.
/// Element status of type xs:int.
    int                                  status                         1;	///< Required element.
};

/// "https://www.twv.com.tw/gps.new/sys/server_HK101001.php?wsdl":DepositTypeArray is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of "https://www.twv.com.tw/gps.new/sys/server_HK101001.php?wsdl":DepositType
struct DepositTypeArray
{
/// Pointer to array of struct ns1__DepositType*.
    struct ns1__DepositType*            *__ptr                         ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};

/// "https://www.twv.com.tw/gps.new/sys/server_HK101001.php?wsdl":WithdrawTypeArray is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of "https://www.twv.com.tw/gps.new/sys/server_HK101001.php?wsdl":WithdrawType
struct WithdrawTypeArray
{
/// Pointer to array of struct ns1__WithdrawType*.
    struct ns1__WithdrawType*           *__ptr                         ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};

/// "https://www.twv.com.tw/gps.new/sys/server_HK101001.php?wsdl":WithdrawInitInfoArray is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of "https://www.twv.com.tw/gps.new/sys/server_HK101001.php?wsdl":WithdrawInitInfo
struct WithdrawInitInfoArray
{
/// Pointer to array of struct ns1__WithdrawInitInfo*.
    struct ns1__WithdrawInitInfo*       *__ptr                         ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};

/// "https://www.twv.com.tw/gps.new/sys/server_HK101001.php?wsdl":WithdrawInitResultArray is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of "https://www.twv.com.tw/gps.new/sys/server_HK101001.php?wsdl":WithdrawInitResult
struct WithdrawInitResultArray
{
/// Pointer to array of struct ns1__WithdrawInitResult*.
    struct ns1__WithdrawInitResult*     *__ptr                         ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};

/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   https://www.twv.com.tw/gps.new/sys/server_HK101001.php?wsdl              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   https://www.twv.com.tw/gps.new/sys/server_HK101001.php?wsdl              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/


//gsoap ns2  service name:	ntlHelperBinding 
//gsoap ns2  service type:	ntlHelperPortType 
//gsoap ns2  service port:	https://www.twv.com.tw:443/gps.new/sys/server_HK101001.php 
//gsoap ns2  service namespace:	https://www.twv.com.tw/gps.new/sys/server 
//gsoap ns2  service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage Service Definitions

@section Service_bindings Service Bindings

  - @ref ntlHelperBinding

@section Service_more More Information

  - @ref page_notes "Usage Notes"

  - @ref page_XMLDataBinding "XML Data Binding"

  - @ref SOAP_ENV__Header "SOAP Header Content" (when applicable)

  - @ref SOAP_ENV__Detail "SOAP Fault Detail Content" (when applicable)


*/

/**

@page ntlHelperBinding Binding "ntlHelperBinding"

@section ntlHelperBinding_operations Operations of Binding  "ntlHelperBinding"

  - @ref ns2__DepositOnlineInit

  - @ref ns2__DepositIbonInit

  - @ref ns2__WithdrawInit

  - @ref ns2__DepositInquiry

  - @ref ns2__WithdrawInquiry

  - @ref ns2__PingAlive

@section ntlHelperBinding_ports Endpoints of Binding  "ntlHelperBinding"

  - https://www.twv.com.tw:443/gps.new/sys/server_HK101001.php

Note: use wsdl2h option -N to change the service binding prefix name

*/

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   ntlHelperBinding                                                         *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   ns2__DepositOnlineInit                                                   *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "ns2__DepositOnlineInitResponse" of service binding "ntlHelperBinding" operation "ns2__DepositOnlineInit"
struct ns2__DepositOnlineInitResponse
{
    int                                 status;
    char*                               tid;
    char*                               deposit_USCOREurl;
};

/// Operation "ns2__DepositOnlineInit" of service binding "ntlHelperBinding"

/**

Operation details:


  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

  - SOAP action="https://www.twv.com.tw/gps.new/sys/server_ntl#DepositOnlineInit"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns2__DepositOnlineInit(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               access_USCOREkey,
    char*                               order_USCOREnum,
    int                                 amount,
    char*                               description,
    char*                               return_USCOREurl,
    // response parameters:
    struct ns2__DepositOnlineInitResponse*
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns2__DepositOnlineInit(
    struct soap *soap,
    // request parameters:
    char*                               access_USCOREkey,
    char*                               order_USCOREnum,
    int                                 amount,
    char*                               description,
    char*                               return_USCOREurl,
    // response parameters:
    struct ns2__DepositOnlineInitResponse*
  );
@endcode

*/

//gsoap ns2  service method-style:	DepositOnlineInit rpc
//gsoap ns2  service method-encoding:	DepositOnlineInit http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns2  service method-action:	DepositOnlineInit https://www.twv.com.tw/gps.new/sys/server_ntl#DepositOnlineInit
int ns2__DepositOnlineInit(
    char*                               access_USCOREkey,	///< Request parameter
    char*                               order_USCOREnum,	///< Request parameter
    int                                 amount,	///< Request parameter
    char*                               description,	///< Request parameter
    char*                               return_USCOREurl,	///< Request parameter
    struct ns2__DepositOnlineInitResponse*	///< Response struct parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   ns2__DepositIbonInit                                                     *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "ns2__DepositIbonInitResponse" of service binding "ntlHelperBinding" operation "ns2__DepositIbonInit"
struct ns2__DepositIbonInitResponse
{
    int                                 status;
    struct ns1__DepositType*            deposit;
};

/// Operation "ns2__DepositIbonInit" of service binding "ntlHelperBinding"

/**

Operation details:


  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

  - SOAP action="https://www.twv.com.tw/gps.new/sys/server_ntl#DepositIbonInit"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns2__DepositIbonInit(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               access_USCOREkey,
    char*                               order_USCOREnum,
    char*                               owner_USCOREid,
    int                                 amount,
    char*                               description,
    // response parameters:
    struct ns2__DepositIbonInitResponse*
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns2__DepositIbonInit(
    struct soap *soap,
    // request parameters:
    char*                               access_USCOREkey,
    char*                               order_USCOREnum,
    char*                               owner_USCOREid,
    int                                 amount,
    char*                               description,
    // response parameters:
    struct ns2__DepositIbonInitResponse*
  );
@endcode

*/

//gsoap ns2  service method-style:	DepositIbonInit rpc
//gsoap ns2  service method-encoding:	DepositIbonInit http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns2  service method-action:	DepositIbonInit https://www.twv.com.tw/gps.new/sys/server_ntl#DepositIbonInit
int ns2__DepositIbonInit(
    char*                               access_USCOREkey,	///< Request parameter
    char*                               order_USCOREnum,	///< Request parameter
    char*                               owner_USCOREid,	///< Request parameter
    int                                 amount,	///< Request parameter
    char*                               description,	///< Request parameter
    struct ns2__DepositIbonInitResponse*	///< Response struct parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   ns2__WithdrawInit                                                        *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "ns2__WithdrawInitResponse" of service binding "ntlHelperBinding" operation "ns2__WithdrawInit"
struct ns2__WithdrawInitResponse
{
    int                                 status;
    int                                 batch_USCOREid;
    struct WithdrawInitResultArray*     result_USCORElist;
};

/// Operation "ns2__WithdrawInit" of service binding "ntlHelperBinding"

/**

Operation details:


  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

  - SOAP action="https://www.twv.com.tw/gps.new/sys/server_ntl#WithdrawInit"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns2__WithdrawInit(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               access_USCOREkey,
    struct WithdrawInitInfoArray*       withdraw_USCORElist,
    // response parameters:
    struct ns2__WithdrawInitResponse*
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns2__WithdrawInit(
    struct soap *soap,
    // request parameters:
    char*                               access_USCOREkey,
    struct WithdrawInitInfoArray*       withdraw_USCORElist,
    // response parameters:
    struct ns2__WithdrawInitResponse*
  );
@endcode

*/

//gsoap ns2  service method-style:	WithdrawInit rpc
//gsoap ns2  service method-encoding:	WithdrawInit http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns2  service method-action:	WithdrawInit https://www.twv.com.tw/gps.new/sys/server_ntl#WithdrawInit
int ns2__WithdrawInit(
    char*                               access_USCOREkey,	///< Request parameter
    struct WithdrawInitInfoArray*       withdraw_USCORElist,	///< Request parameter
    struct ns2__WithdrawInitResponse   *	///< Response struct parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   ns2__DepositInquiry                                                      *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "ns2__DepositInquiryResponse" of service binding "ntlHelperBinding" operation "ns2__DepositInquiry"
struct ns2__DepositInquiryResponse
{
    int                                 status;
    struct ns1__DepositType*            deposit;
};

/// Operation "ns2__DepositInquiry" of service binding "ntlHelperBinding"

/**

Operation details:


  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

  - SOAP action="https://www.twv.com.tw/gps.new/sys/server_ntl#DepositInquiry"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns2__DepositInquiry(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               access_USCOREkey,
    char*                               tid,
    // response parameters:
    struct ns2__DepositInquiryResponse*
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns2__DepositInquiry(
    struct soap *soap,
    // request parameters:
    char*                               access_USCOREkey,
    char*                               tid,
    // response parameters:
    struct ns2__DepositInquiryResponse*
  );
@endcode

*/

//gsoap ns2  service method-style:	DepositInquiry rpc
//gsoap ns2  service method-encoding:	DepositInquiry http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns2  service method-action:	DepositInquiry https://www.twv.com.tw/gps.new/sys/server_ntl#DepositInquiry
int ns2__DepositInquiry(
    char*                               access_USCOREkey,	///< Request parameter
    char*                               tid,	///< Request parameter
    struct ns2__DepositInquiryResponse *	///< Response struct parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   ns2__WithdrawInquiry                                                     *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "ns2__WithdrawInquiryResponse" of service binding "ntlHelperBinding" operation "ns2__WithdrawInquiry"
struct ns2__WithdrawInquiryResponse
{
    int                                 status;
    struct ns1__WithdrawType*           withdraw;
};

/// Operation "ns2__WithdrawInquiry" of service binding "ntlHelperBinding"

/**

Operation details:


  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

  - SOAP action="https://www.twv.com.tw/gps.new/sys/server_ntl#WithdrawInquiry"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns2__WithdrawInquiry(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               access_USCOREkey,
    char*                               tid,
    // response parameters:
    struct ns2__WithdrawInquiryResponse*
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns2__WithdrawInquiry(
    struct soap *soap,
    // request parameters:
    char*                               access_USCOREkey,
    char*                               tid,
    // response parameters:
    struct ns2__WithdrawInquiryResponse*
  );
@endcode

*/

//gsoap ns2  service method-style:	WithdrawInquiry rpc
//gsoap ns2  service method-encoding:	WithdrawInquiry http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns2  service method-action:	WithdrawInquiry https://www.twv.com.tw/gps.new/sys/server_ntl#WithdrawInquiry
int ns2__WithdrawInquiry(
    char*                               access_USCOREkey,	///< Request parameter
    char*                               tid,	///< Request parameter
    struct ns2__WithdrawInquiryResponse*	///< Response struct parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   ns2__PingAlive                                                           *
 *                                                                            *
\******************************************************************************/


/// Operation "ns2__PingAlive" of service binding "ntlHelperBinding"

/**

Operation details:


  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

  - SOAP action="https://www.twv.com.tw/gps.new/sys/server_ntl#PingAlive"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns2__PingAlive(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               access_USCOREkey,
    // response parameters:
    int                                *status
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns2__PingAlive(
    struct soap *soap,
    // request parameters:
    char*                               access_USCOREkey,
    // response parameters:
    int                                *status
  );
@endcode

*/

//gsoap ns2  service method-style:	PingAlive rpc
//gsoap ns2  service method-encoding:	PingAlive http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns2  service method-action:	PingAlive https://www.twv.com.tw/gps.new/sys/server_ntl#PingAlive
int ns2__PingAlive(
    char*                               access_USCOREkey,	///< Request parameter
    int                                *status	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * XML Data Binding                                                           *
 *                                                                            *
\******************************************************************************/


/**

@page page_XMLDataBinding XML Data Binding

SOAP/XML services use data bindings contractually bound by WSDL and auto-
generated by wsdl2h and soapcpp2 (see Service Bindings). Plain data bindings
are adopted from XML schemas as part of the WSDL types section or when running
wsdl2h on a set of schemas to produce non-SOAP-based XML data bindings.

The following readers and writers are C/C++ data type (de)serializers auto-
generated by wsdl2h and soapcpp2. Run soapcpp2 on this file to generate the
(de)serialization code, which is stored in soapC.c[pp]. Include "soapH.h" in
your code to import these data type and function declarations. Only use the
soapcpp2-generated files in your project build. Do not include the wsdl2h-
generated .h file in your code.

XML content can be retrieved from:
  - a file descriptor, using soap->recvfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->is = ...
  - a buffer, using the soap->frecv() callback

XML content can be stored to:
  - a file descriptor, using soap->sendfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->os = ...
  - a buffer, using the soap->fsend() callback


@section ns1 Top-level root elements of schema "https://www.twv.com.tw/gps.new/sys/server_HK101001.php?wsdl"

*/

/* End of twv.h */
