OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLAcctLedgerDailyReport
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLAcctLedgerDailyReport.so
SOOBJS =  OLAcctLedgerDailyReport.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
