CREATE TABLE DEF_NBXA_PID_GROUP
(
  DNG_CODE              VARCHAR2(20 BYTE),
  DNG_DESC              VARCHAR2(50 BYTE),
  DNG_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  DNG_CREATE_USER       VARCHAR2(20 BYTE),
  DNG_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  DNG_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DEF_NBXA_PID_GROUP_PK ON DEF_NBXA_PID_GROUP
(DNG_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DEF_NBXA_PID_GROUP ADD (
  CONSTRAINT DEF_NBXA_PID_GROUP_PK
  PRIMARY KEY
  (DNG_CODE)
  USING INDEX DEF_NBXA_PID_GROUP_PK
  ENABLE VALIDATE);
