OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=test_oam.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o test_oam.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
