ALTER TABLE EXCHANGE_LIMIT_RATE
 DROP PRIMARY KEY CASCADE;

DROP TABLE EXCHANGE_LIMIT_RATE CASCADE CONSTRAINTS;

CREATE TABLE EXCHANGE_LIMIT_RATE
(
  EL_FROM_CCY_ID       CHAR(3 BYTE)             NOT NULL,
  EL_TO_CCY_ID         CHAR(3 BYTE)             NOT NULL,
  EL_RATE              NUMBER(13,5)             NOT NULL,
  EL_CREATE_USER       VARCHAR2(50 BYTE),
  EL_CREATE_TIMESTAMP  DATE                     DEFAULT SYSDATE,
  EL_UPDATE_USER       VARCHAR2(50 BYTE),
  EL_UPDATE_TIMESTAMP  DATE                     DEFAULT SYSDATE
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX EXCHANGE_LIMIT_RATE_PK ON EXCHANGE_LIMIT_RATE
(EL_FROM_CCY_ID, EL_TO_CCY_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE EXCHANGE_LIMIT_RATE ADD (
  CONSTRAINT EXCHANGE_LIMIT_RATE_PK
  PRIMARY KEY
  (EL_FROM_CCY_ID, EL_TO_CCY_ID)
  USING INDEX EXCHANGE_LIMIT_RATE_PK);

