ALTER TABLE PHUSER.OL_DEF_ENGINE_PARTY
 DROP PRIMARY KEY CASCADE;

DROP TABLE PHUSER.OL_DEF_ENGINE_PARTY CASCADE CONSTRAINTS;

CREATE TABLE PHUSER.OL_DEF_ENGINE_PARTY
(
  EP_TYPE              VARCHAR2(10 BYTE),
  EP_DESC              VARCHAR2(50 BYTE),
  EP_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  EP_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  EP_CREATE_USER       VARCHAR2(20 BYTE),
  EP_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PHUSER.OL_DEF_ENGINE_PARTY_PK ON PHUSER.OL_DEF_ENGINE_PARTY
(EP_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PHUSER.OL_DEF_ENGINE_PARTY ADD (
  CONSTRAINT OL_DEF_ENGINE_PARTY_PK
  PRIMARY KEY
  (EP_TYPE)
  USING INDEX PHUSER.OL_DEF_ENGINE_PARTY_PK
  ENABLE VALIDATE);

