OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOStat
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOStat.so
SOOBJS = BOStat.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
