ALTER TABLE OL_DEF_UNKNOWN_TXNCODE
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_DEF_UNKNOWN_TXNCODE CASCADE CONSTRAINTS;

CREATE TABLE OL_DEF_UNKNOWN_TXNCODE
(
  OUC_CODE              CHAR(3 BYTE),
  OUC_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  OUC_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  OUC_CREATE_USER       VARCHAR2(20 BYTE),
  OUC_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_DEF_UNKNOWN_TXNCODE_PK ON OL_DEF_UNKNOWN_TXNCODE
(OUC_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_DEF_UNKNOWN_TXNCODE ADD (
  CONSTRAINT OL_DEF_UNKNOWN_TXNCODE_PK
  PRIMARY KEY
  (OUC_CODE)
  USING INDEX OL_DEF_UNKNOWN_TXNCODE_PK
  ENABLE VALIDATE);

ALTER TABLE OL_DEF_UNKNOWN_TXNCODE ADD (
  CONSTRAINT OL_DEF_UNKNOWN_TXNCODE_FK01 
  FOREIGN KEY (OUC_CODE) 
  REFERENCES OL_BAID_TXN_CODE (OBTC_CODE)
  ENABLE VALIDATE);
