ALTER TABLE CUSTOMER_TXN_HIST
 DROP PRIMARY KEY CASCADE;

DROP TABLE CUSTOMER_TXN_HIST CASCADE CONSTRAINTS;

CREATE TABLE CUSTOMER_TXN_HIST
(
  CTH_DATE              VARCHAR2(8 BYTE),
  CTH_MERCHANT_ID       VARCHAR2(15 BYTE),
  CTH_CUST_ID           VARCHAR2(10 BYTE),
  CTH_CODE              VARCHAR2(10 BYTE),
  CTH_AMOUNT            NUMBER(14,2)            DEFAULT 0,
  CTH_COUNTER           NUMBER(14,2)            DEFAULT 0,
  CTH_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  CTH_CREATE_USER       VARCHAR2(20 BYTE),
  CTH_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  CTH_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX CUSTOMER_TXN_HIST_IDX01 ON CUSTOMER_TXN_HIST
(CTH_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX CUSTOMER_TXN_HIST_IDX02 ON CUSTOMER_TXN_HIST
(CTH_MERCHANT_ID, CTH_CUST_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX CUSTOMER_TXN_HIST_IDX03 ON CUSTOMER_TXN_HIST
(CTH_DATE, CTH_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX CUSTOMER_TXN_HIST_PK ON CUSTOMER_TXN_HIST
(CTH_DATE, CTH_MERCHANT_ID, CTH_CUST_ID, CTH_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE CUSTOMER_TXN_HIST ADD (
  CONSTRAINT CUSTOMER_TXN_HIST_PK
  PRIMARY KEY
  (CTH_DATE, CTH_MERCHANT_ID, CTH_CUST_ID, CTH_CODE)
  USING INDEX CUSTOMER_TXN_HIST_PK
  ENABLE VALIDATE);

