ALTER TABLE DEF_ADJUSTMENT_NATURE
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_ADJUSTMENT_NATURE CASCADE CONSTRAINTS;

CREATE TABLE DEF_ADJUSTMENT_NATURE
(
  DN_CODE              CHAR(1 BYTE),
  DN_DESC              VARCHAR2(50 BYTE),
  DN_ORDER             INTEGER,
  DN_CREATE_USER       VARCHAR2(20 BYTE),
  DN_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  DN_UPDATE_USER       VARCHAR2(20 BYTE),
  DN_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEF_ADJUSTMENT_NATURE_PK ON DEF_ADJUSTMENT_NATURE
(DN_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_ADJUSTMENT_NATURE ADD (
  CONSTRAINT DEF_ADJUSTMENT_NATURE_PK
  PRIMARY KEY
  (DN_CODE)
  USING INDEX DEF_ADJUSTMENT_NATURE_PK
  ENABLE VALIDATE);

