ALTER TABLE OL_MERCHANT_SETTLEMENT_DETAIL
 ADD (OSD_COUNTRY_SUBDIVISION  VARCHAR2(100 BYTE));

ALTER TABLE OL_MERCHANT_SETTLEMENT_DETAIL
 ADD (OSD_CITY  VARCHAR2(100 BYTE));

ALTER TABLE OL_MERCHANT_SETTLEMENT_DETAIL
 ADD (OSD_COUNTRY  VARCHAR2(50 BYTE));

