OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOOLBankStmtMatch/uat
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOOLBankStmtMatch.so
SOOBJS = BOOLBankStmtMatch.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
