ALTER TABLE DEF_HOLD_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_HOLD_TYPE CASCADE CONSTRAINTS;

CREATE TABLE DEF_HOLD_TYPE
(
  DH_TYPE              CHAR(2 BYTE)              NOT NULL,
  DH_DESC              VARCHAR2(50 BYTE),
  DH_CREATE_USER       VARCHAR2(20 BYTE),
  DH_CREATE_TIMESTAMP  DATE                      DEFAULT sysdate,
  DH_UPDATE_USER       VARCHAR2(20 BYTE),
  DH_UPDATE_TIMESTAMP  DATE                      DEFAULT sysdate
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEF_HOLD_TYPE_PK ON DEF_HOLD_TYPE
(DH_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_HOLD_TYPE ADD (
  CONSTRAINT DEF_HOLD_TYPE_PK
  PRIMARY KEY
  (DH_TYPE)
  USING INDEX DEF_HOLD_TYPE_PK);
