ALTER TABLE RULE_SCHEDULE_ONCE
 DROP PRIMARY KEY CASCADE;

DROP TABLE RULE_SCHEDULE_ONCE CASCADE CONSTRAINTS;

CREATE TABLE RULE_SCHEDULE_ONCE
(
  RO_SCHEDULER_ID      INTEGER,
  RO_DISABLED	       INTEGER                  DEFAULT 0,
  RO_START_DATETIME    CHAR(14 BYTE),
  RO_END_DATETIME      CHAR(14 BYTE),
  RO_CREATE_USER       VARCHAR2(20 BYTE),
  RO_UPDATE_USER       VARCHAR2(20 BYTE),
  RO_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  RO_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX PHUSER.RULE_SCHEDULE_ONCE_IDX01 ON PHUSER.RULE_SCHEDULE_ONCE
(RO_SCHEDULER_ID, RO_DISABLED, RO_START_DATETIME, RO_END_DATETIME)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

CREATE UNIQUE INDEX RULE_SCHEDULE_ONCE_PK ON RULE_SCHEDULE_ONCE
(RO_SCHEDULER_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE RULE_SCHEDULE_ONCE ADD (
  CONSTRAINT RULE_SCHEDULE_ONCE_PK
  PRIMARY KEY
  (RO_SCHEDULER_ID)
  USING INDEX RULE_SCHEDULE_ONCE_PK);

ALTER TABLE RULE_SCHEDULE_ONCE ADD (
  CONSTRAINT RULE_SCHEDULE_ONCE_FK01 
  FOREIGN KEY (RO_SCHEDULER_ID) 
  REFERENCES RULE_SCHEDULER_HEADER (RS_SCHEDULER_ID)
  ENABLE VALIDATE);
