
CREATE TABLE OL_AUTO_UPLOAD_STMT_SETT_LOG 
(
  OAUL_LOG_ID				INTEGER,
  OAUL_JOB_ID				INTEGER,
  OAUL_SERVER_ID			VARCHAR2(3 BYTE),
  OAUL_PROVIDER_PATHNAME_FR		VARCHAR2(50 BYTE),
  OAUL_PROVIDER_PATHNAME_TO		VARCHAR2(50 BYTE),
  OAUL_NATURE				VARCHAR2(10 BYTE),
  OAUL_LEVEL				INTEGER,
  OAUL_CREATE_TIMESTAMP			DATE                  DEFAULT sysdate,
  OAUL_CREATE_USER			VARCHAR2(20 BYTE),
  OAUL_UPDATE_TIMESTAMP			DATE                  DEFAULT sysdate,
  OAUL_UPDATE_USER			VARCHAR2(20 BYTE),
  OAUL_DISABLED				INTEGER,
  OAUL_PROVIDER_ID			VARCHAR2(10 BYTE),
  OAUL_NATURE_PATH			VARCHAR2(50 BYTE),
  OAUL_PROCESS_BANK_CODE		VARCHAR2(10 BYTE)
) 
TABLESPACE USER_DATA 
PCTUSED    0 
PCTFREE    10 
INITRANS   1 
MAXTRANS   255 
STORAGE    (
            INITIAL     64K 
            NEXT        1M 
            MINEXTENTS  1 
            MAXEXTENTS  UNLIMITED 
            PCTINCREASE 0 
            BUFFER_POOL DEFAULT
           ) 
LOGGING 
NOCOMPRESS 
NOCACHE 
MONITORING;

CREATE UNIQUE INDEX OL_AUTO_UPL_STMT_SETT_LOG_PK ON OL_AUTO_UPLOAD_STMT_SETT_LOG 
(OAUL_LOG_ID) 
LOGGING 
TABLESPACE USER_IDX 
PCTFREE    10 
INITRANS   2 
MAXTRANS   255 
STORAGE    (
            INITIAL     64K 
            NEXT        1M 
            MINEXTENTS  1 
            MAXEXTENTS  UNLIMITED 
            PCTINCREASE 0 
            BUFFER_POOL DEFAULT
           );

CREATE INDEX OL_AUTO_UPL_STMT_SETT_LOG_IDX1 ON OL_AUTO_UPLOAD_STMT_SETT_LOG 
(OAUL_NATURE,OAUL_PROVIDER_ID) 
LOGGING 
TABLESPACE USER_IDX 
PCTFREE    10 
INITRANS   2 
MAXTRANS   255 
STORAGE    (
            INITIAL          64K 
            NEXT             1M 
            MINEXTENTS       1 
            MAXEXTENTS       UNLIMITED 
            PCTINCREASE      0 
            BUFFER_POOL      DEFAULT 
            FLASH_CACHE      DEFAULT 
            CELL_FLASH_CACHE DEFAULT
           ) 
NOPARALLEL;



ALTER TABLE OL_AUTO_UPLOAD_STMT_SETT_LOG ADD 
(
  CONSTRAINT OL_AUTO_UPL_STMT_SETT_LOG_PK 
  PRIMARY KEY 
  (OAUL_LOG_ID) 
  USING INDEX OL_AUTO_UPL_STMT_SETT_LOG_PK 
  ENABLE VALIDATE
);


