


CREATE TABLE OL_PAYOUT_API_BATCH_SUPPORT
(
  OAS_TXN_CODE                CHAR(1 BYTE),
  OAS_SUPPORT                 NUMBER(1)         DEFAULT 0                     NOT NULL,
  OAS_SUPPORT_BATCH_RET_CODE  NUMBER(1)         DEFAULT 0                     NOT NULL,
  OAS_SUPPORT_MULTI_RET_CODE  NUMBER(1)         DEFAULT 0                     NOT NULL,
  OAS_CREATE_TIMESTAMP        DATE              DEFAULT sysdate               NOT NULL,
  OAS_CREATE_USER             VARCHAR2(20 BYTE),
  OAS_UPDATE_TIMESTAMP        DATE              DEFAULT sysdate               NOT NULL,
  OAS_UPDATE_USER             VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX OL_PAYOUT_API_BATCH_SUPPORT_PK ON OL_PAYOUT_API_BATCH_SUPPORT
(OAS_TXN_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE OL_PAYOUT_API_BATCH_SUPPORT ADD (
  CONSTRAINT OL_PAYOUT_API_BATCH_SUPPORT_PK
  PRIMARY KEY
  (OAS_TXN_CODE)
  USING INDEX OL_PAYOUT_API_BATCH_SUPPORT_PK
  ENABLE VALIDATE);
