OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLBaidTxnRelation
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLBaidTxnRelation.so
SOOBJS =  OLBaidTxnRelation.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
