ALTER TABLE MMS_DEF_FUNDS_DIRECTION
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_DEF_FUNDS_DIRECTION CASCADE CONSTRAINTS;

CREATE TABLE MMS_DEF_FUNDS_DIRECTION
(
  MFD_TYPE              CHAR(1 BYTE),
  MFD_DESC              VARCHAR2(50 BYTE),
  MFD_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  MFD_CREATE_USER       VARCHAR2(20 BYTE),
  MFD_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  MFD_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MMS_DEF_FUNDS_DIRECTION_PK ON MMS_DEF_FUNDS_DIRECTION
(MFD_TYPE)
LOGGING
TABLESPACE USER_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_DEF_FUNDS_DIRECTION ADD (
  CONSTRAINT MMS_DEF_FUNDS_DIRECTION_PK
  PRIMARY KEY
  (MFD_TYPE)
  USING INDEX MMS_DEF_FUNDS_DIRECTION_PK
  ENABLE VALIDATE);

