ALTER TABLE MMS_DEF_CREDIT_LIMIT_MODE
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_DEF_CREDIT_LIMIT_MODE CASCADE CONSTRAINTS;

CREATE TABLE MMS_DEF_CREDIT_LIMIT_MODE
(
  MCR_TYPE              CHAR(1 BYTE),
  MCR_DESC              VARCHAR2(50 BYTE),
  MCR_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  MCR_CREATE_USER       VARCHAR2(20 BYTE),
  MCR_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  MCR_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MMS_DEF_CREDIT_LIMIT_MODE_PK ON MMS_DEF_CREDIT_LIMIT_MODE
(MCR_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_DEF_CREDIT_LIMIT_MODE ADD (
  CONSTRAINT MMS_DEF_CREDIT_LIMIT_MODE_PK
  PRIMARY KEY
  (MCR_TYPE)
  USING INDEX MMS_DEF_CREDIT_LIMIT_MODE_PK
  ENABLE VALIDATE);

