OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnWebOnUs2GPY
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnWebOnUs2GPY.so
SOOBJS = TxnWebOnUs2GPY.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
