OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmsInstantTxnInqHd
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmsInstantTxnInqHd.so
SOOBJS =  MmsInstantTxnInqHd.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
