OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOCrrPost
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOCrrPost.so
SOOBJS = BOCrrPost.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
