ALTER TABLE CUSTOMER_GROUP
 DROP PRIMARY KEY CASCADE;

DROP TABLE CUSTOMER_GROUP CASCADE CONSTRAINTS;

CREATE TABLE CUSTOMER_GROUP
(
  CG_CODE              VARCHAR2(10 BYTE),
  CG_DESC              VARCHAR2(50 BYTE),
  CG_IN_STATUS_REPORT  INTEGER			DEFAULT 0,
  CG_BACKUP_BY_OVERFLOW	INTEGER			DEFAULT 1,
  CG_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  CG_CREATE_USER       VARCHAR2(20 BYTE),
  CG_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  CG_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CUSTOMER_GROUP_PK ON CUSTOMER_GROUP
(CG_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE CUSTOMER_GROUP ADD (
  CONSTRAINT CUSTOMER_GROUP_PK
  PRIMARY KEY
  (CG_CODE)
  USING INDEX CUSTOMER_GROUP_PK
  ENABLE VALIDATE);

