OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/EmailFunct
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBEmailFunct.so
SOOBJS =  EmailFunct.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
