


CREATE TABLE OL_NONTXN_MSG_HEADER
(
  ONTMH_TXN_ID        	  VARCHAR2(16 BYTE),
  ONTMH_CHANNEL_CODE 	  VARCHAR2(3 BYTE),
  ONTMH_TXN_CODE      	  VARCHAR2(3 BYTE),
  ONTMH_VERSION           VARCHAR2(5 BYTE),
  ONTMH_STATUS            CHAR(1 BYTE),
  ONTMH_RET_CODE          NUMBER(8),
  ONTMH_CREATE_USER       VARCHAR2(20 BYTE),
  ONTMH_CREATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  ONTMH_UPDATE_USER       VARCHAR2(20 BYTE),
  ONTMH_UPDATE_TIMESTAMP  DATE                   DEFAULT sysdate
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE INDEX OL_NONTXN_MSG_HEADER_IDX01 ON OL_NONTXN_MSG_HEADER
(ONTMH_CHANNEL_CODE, ONTMH_TXN_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX OL_NONTXN_MSG_HEADER_IDX02 ON OL_NONTXN_MSG_HEADER
(ONTMH_CREATE_TIMESTAMP)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX OL_NONTXN_MSG_HEADER_IDX03 ON OL_NONTXN_MSG_HEADER
(ONTMH_UPDATE_TIMESTAMP)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX OL_NONTXN_MSG_HEADER_PK ON OL_NONTXN_MSG_HEADER
(ONTMH_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE OL_NONTXN_MSG_HEADER ADD (
  CONSTRAINT OL_NONTXN_MSG_HEADER_PK
  PRIMARY KEY
  (ONTMH_TXN_ID)
  USING INDEX OL_NONTXN_MSG_HEADER_PK
  ENABLE VALIDATE);

