OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnWebOnUs2HHP
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnWebOnUs2HHP.so
SOOBJS = TxnWebOnUs2HHP.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
