OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/TestAndy
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBTestAndy.so
SOOBJS = TestAndy.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
