OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MiEntityBalMap
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMiEntityBalMap.so
SOOBJS =  MiEntityBalMap.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
