OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/SystemAlert
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBSystemAlert.so
SOOBJS =  SystemAlert.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
