DROP TABLE MMS_MANUAL_VOID_LOG CASCADE CONSTRAINTS;

CREATE TABLE MMS_MANUAL_VOID_LOG
(
  MVT_TXN_ID              VARCHAR2(16 BYTE)     NOT NULL,
  MVT_VOID_TXN_ID      VARCHAR2(16 BYTE)     NOT NULL,
  MVT_VOID_DTL_TXN_ID  INTEGER               NOT NULL,
  MVT_CREATE_USER         VARCHAR2(20 BYTE),
  MVT_CREATE_TIMESTAMP    DATE                  DEFAULT sysdate,
  MVT_UPDATE_USER         VARCHAR2(20 BYTE),
  MVT_UPDATE_TIMESTAMP    DATE                  DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX MMS_MANUAL_VOID_LOG_IDX01 ON MMS_MANUAL_VOID_LOG
(MVT_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX MMS_MANUAL_VOID_LOG_IDX02 ON MMS_MANUAL_VOID_LOG
(MVT_VOID_TXN_ID, MVT_VOID_DTL_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

