OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/RuleMerchantTxnCap
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBRuleMerchantTxnCap.so
SOOBJS =  RuleMerchantTxnCap.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
