ALTER TABLE PHUSER.OL_PAYOUT_RECON_TRIGGER_LOG
 DROP PRIMARY KEY CASCADE;

DROP TABLE PHUSER.OL_PAYOUT_RECON_TRIGGER_LOG CASCADE CONSTRAINTS;

CREATE TABLE PHUSER.OL_PAYOUT_RECON_TRIGGER_LOG
(
  PRL_TRIGGER_SEQ       INTEGER,
  PRL_CREATE_TS_FROM    VARCHAR2(20 BYTE),
  PRL_CREATE_TS_TO      VARCHAR2(20 BYTE),
  PRL_PROVIDER_ID       VARCHAR2(10 BYTE),
  PRL_TRIGGER_STATUS    CHAR(1 BYTE),
  PRL_CREATE_USER       VARCHAR2(20 BYTE),
  PRL_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  PRL_UPDATE_USER       VARCHAR2(20 BYTE),
  PRL_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX PHUSER.OL_PAYOUT_RECON_TRIGGER_LOG_PK ON PHUSER.OL_PAYOUT_RECON_TRIGGER_LOG
(PRL_TRIGGER_SEQ)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX PHUSER.OL_PAYOUT_RECON_TRIG_LOG_IDX01 ON PHUSER.OL_PAYOUT_RECON_TRIGGER_LOG
(PRL_CREATE_TIMESTAMP, PRL_UPDATE_TIMESTAMP)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE PHUSER.OL_PAYOUT_RECON_TRIGGER_LOG ADD (
  CONSTRAINT OL_PAYOUT_RECON_TRIGGER_LOG_PK
  PRIMARY KEY
  (PRL_TRIGGER_SEQ)
  USING INDEX PHUSER.OL_PAYOUT_RECON_TRIGGER_LOG_PK
  ENABLE VALIDATE);

ALTER TABLE PHUSER.OL_PAYOUT_RECON_TRIGGER_LOG ADD (
  CONSTRAINT OL_PAYOUT_RECON_TRIG_LOG_FK01 
  FOREIGN KEY (PRL_PROVIDER_ID) 
  REFERENCES PHUSER.PSP_MASTER (PM_CLIENT_ID)
  ENABLE VALIDATE,
  CONSTRAINT OL_PAYOUT_RECON_TRIG_LOG_FK02 
  FOREIGN KEY (PRL_TRIGGER_STATUS) 
  REFERENCES PHUSER.OL_DEF_TRIGGER_STATUS (DTS_STATUS)
  ENABLE VALIDATE);

