OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOMMSEntityRSP
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOMMSEntityRSP.so
SOOBJS = BOMMSEntityRSP.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
