OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/RuleAutoSettlement
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBRuleAutoSettlement.so
SOOBJS =  RuleAutoSettlement.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
