ALTER TABLE RULE_TXN_LIMIT
 DROP PRIMARY KEY CASCADE;

DROP TABLE RULE_TXN_LIMIT CASCADE CONSTRAINTS;

CREATE TABLE RULE_TXN_LIMIT
(
  RL_TXN_CODE          CHAR(3 BYTE)             NOT NULL,
  RL_COUNTRY_ID        CHAR(2 BYTE)             NOT NULL,
  RL_CHANNEL_CODE      CHAR(3 BYTE)             NOT NULL,
  RL_SERVICE_CODE      CHAR(3 BYTE)             NOT NULL,
  RL_PAY_METHOD        VARCHAR2(4 BYTE)         NOT NULL,
  RL_CURRENCY_ID       CHAR(3 BYTE)             NOT NULL,
  RL_PARTY_TYPE        CHAR(1 BYTE)             NOT NULL,
  RL_PARTY_ID          VARCHAR2(15 BYTE)        NOT NULL,
  RL_MIN_VALUE         NUMBER(12,2)             DEFAULT 0,
  RL_MAX_VALUE         NUMBER(12,2)             DEFAULT 0,
  RL_DISABLED          INTEGER                  DEFAULT 0,
  RL_CREATE_USER       VARCHAR2(20 BYTE),
  RL_CREATE_TIMESTAMP  DATE                     DEFAULT SYSDATE,
  RL_UPDATE_USER       VARCHAR2(20 BYTE),
  RL_UPDATE_TIMESTAMP  DATE                     DEFAULT SYSDATE
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX RULE_TXN_LIMIT_PK ON RULE_TXN_LIMIT
(RL_TXN_CODE, RL_COUNTRY_ID, RL_CHANNEL_CODE, RL_SERVICE_CODE, RL_PAY_METHOD, 
RL_CURRENCY_ID, RL_PARTY_TYPE, RL_PARTY_ID)
LOGGING
TABLESPACE USER_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE RULE_TXN_LIMIT ADD (
  CONSTRAINT RULE_TXN_LIMIT_PK
  PRIMARY KEY
  (RL_TXN_CODE, RL_COUNTRY_ID, RL_CHANNEL_CODE, RL_SERVICE_CODE, RL_PAY_METHOD, RL_CURRENCY_ID, RL_PARTY_TYPE, RL_PARTY_ID)
  USING INDEX RULE_TXN_LIMIT_PK);

ALTER TABLE RULE_TXN_LIMIT ADD (
  CONSTRAINT RULE_TXN_LIMIT_FK01 
  FOREIGN KEY (RL_COUNTRY_ID) 
  REFERENCES COUNTRY (COUNTRY_CODE),
  CONSTRAINT RULE_TXN_LIMIT_FK02 
  FOREIGN KEY (RL_SERVICE_CODE) 
  REFERENCES DEF_SERVICE_CODE (SC_CODE),
  CONSTRAINT RULE_TXN_LIMIT_FK03 
  FOREIGN KEY (RL_PARTY_TYPE) 
  REFERENCES DEF_PARTY_TYPE (DP_TYPE));

