OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/PayoutActionLock
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBPayoutActionLock.so
SOOBJS =  PayoutActionLock.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
