ALTER TABLE MMS_IMITATE_PID_MAP
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_IMITATE_PID_MAP CASCADE CONSTRAINTS;

CREATE TABLE MMS_IMITATE_PID_MAP
(
  MPM_IMITATE_PID       VARCHAR2(20 BYTE),
  MPM_ORG_PID           VARCHAR2(10 BYTE),
  MPM_VERSION           INTEGER,
  MPM_COUNTRY           CHAR(2 BYTE),
  MPM_SERVICE_CODE      CHAR(3 BYTE),
  MPM_PRODUCT           VARCHAR2(3 BYTE),
  MPM_NATURE_TYPE       VARCHAR2(4 BYTE),
  MPM_BUSINESS_TYPE     CHAR(1 BYTE),
  MPM_FE_DISPLAY        INTEGER,
  MPM_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  MPM_CREATE_USER       VARCHAR2(20 BYTE),
  MPM_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  MPM_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MMS_IMITATE_PID_MAP_PK ON MMS_IMITATE_PID_MAP
(MPM_IMITATE_PID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_IMITATE_PID_MAP ADD (
  CONSTRAINT MMS_IMITATE_PID_MAP_PK
  PRIMARY KEY
  (MPM_IMITATE_PID)
  USING INDEX MMS_IMITATE_PID_MAP_PK
  ENABLE VALIDATE);

ALTER TABLE MMS_IMITATE_PID_MAP ADD (
  CONSTRAINT MMS_IMITATE_PID_MAP_FK01 
  FOREIGN KEY (MPM_NATURE_TYPE) 
  REFERENCES MMS_DEF_BAL_NATURE (MBN_TYPE)
  ENABLE VALIDATE);

