OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLPayoutGeneratedFileDT
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLPayoutGeneratedFileDT.so
SOOBJS =  OLPayoutGeneratedFileDT.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
