OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLStmtMatchRule
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLStmtMatchRule.so
SOOBJS =  OLStmtMatchRule.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
