OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLSmsFormat
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLSmsFormat.so
SOOBJS =  OLSmsFormat.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
