ALTER TABLE OL_MERCH_DETAIL
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_MERCH_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE OL_MERCH_DETAIL
(
  MD_MERCHANT_ID                 VARCHAR2(15 BYTE),
  MD_NAME                        VARCHAR2(50 BYTE),
  MD_SHORT_NAME                  VARCHAR2(20 BYTE),
  MD_DISABLED                    INTEGER,
  MD_CLIENT_ID                   VARCHAR2(10 BYTE),
  MD_APPROXIMATE_FEE_RATE        NUMBER(12,5)   DEFAULT 0,
  MD_STATUS                      VARCHAR2(2 BYTE),
  MD_ALLOW_PAYOUT_DUP_MERCH_REF  INTEGER,
  MD_SETTLEMENT_PROCESS_PERIOD   INTEGER        DEFAULT 0,
  MD_IGNORE_NACK                 INTEGER        DEFAULT 0,
  MD_PAYOUT_FE_DISPLAY           INTEGER        DEFAULT 0,
  MD_CREATE_TIMESTAMP            DATE,
  MD_UPDATE_TIMESTAMP            DATE,
  MD_CREATE_USER                 VARCHAR2(20 BYTE),
  MD_UPDATE_USER                 VARCHAR2(20 BYTE),
  MD_BRAND_NAME                  VARCHAR2(50 BYTE),
  MD_DEPOSIT_REQUEST_VER         INTEGER,
  MD_DISPLAY_OTHER_BANK          INTEGER        DEFAULT 1,
  MD_IS_MORE_RESTRICTED          INTEGER        DEFAULT 0,
  MD_DSP_API_ALERT               INTEGER        DEFAULT 0,
  MD_DSP_FILE_ALERT              INTEGER        DEFAULT 0,
  MD_TXN_AUTO_EXPIRED_DAYS       INTEGER        DEFAULT 0,
  MD_STMT_AUTO_EXPIRED_DAYS      INTEGER        DEFAULT 0,
  MD_RELEASE_RESERVED_PERIOD     INTEGER        DEFAULT 180,
  MD_ALLOW_RESERVED              INTEGER        DEFAULT 0,
  MD_TXN_AUTO_EXPIRED_MINS       INTEGER        DEFAULT 0,
  MD_STMT_AUTO_EXPIRED_MINS      INTEGER        DEFAULT 0,
  MD_SUPPORT_PAYOUT_GRP          INTEGER        DEFAULT 1,
  MD_PAYOUT_CHECKSUM             INTEGER        DEFAULT 1
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_MERCH_DETAIL_IDX02 ON OL_MERCH_DETAIL
(MD_MERCHANT_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_MERCH_DETAIL ADD (
  CONSTRAINT OL_MERCH_DETAIL_PK
  PRIMARY KEY
  (MD_MERCHANT_ID)
  USING INDEX OL_MERCH_DETAIL_IDX02
  ENABLE VALIDATE);

ALTER TABLE OL_MERCH_DETAIL ADD (
  CONSTRAINT OL_MERCH_DETAIL_FK02 
  FOREIGN KEY (MD_STATUS) 
  REFERENCES DEF_STATUS (DS_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OL_MERCH_DETAIL_FK03 
  FOREIGN KEY (MD_CLIENT_ID) 
  REFERENCES CLIENTS (CLIENT_ID)
  ENABLE VALIDATE,
  CONSTRAINT OL_MERCH_DETAIL_FK04 
  FOREIGN KEY (MD_DEPOSIT_REQUEST_VER) 
  REFERENCES OL_DEF_DEPOSIT_REQ_VER (DD_VERSION)
  ENABLE VALIDATE);

