OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnCctOnUsCOM
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnCctOnUsCOM.so
SOOBJS = TxnCctOnUsCOM.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
