OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/PregenRptParam
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBPregenRptParam.so
SOOBJS =  PregenRptParam.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
