


CREATE TABLE OL_PAYOUT_API_BATCH_HD
(
  OAH_BATCH_ID          NUMBER(16),
  OAH_TXN_CODE          CHAR(3 BYTE),
  OAH_STATUS            CHAR(1 BYTE)            DEFAULT 'W',
  OAH_RET_CODE          NUMBER(8),
  OAH_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate               NOT NULL,
  OAH_CREATE_USER       VARCHAR2(20 BYTE),
  OAH_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate               NOT NULL,
  OAH_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE INDEX OL_PAYOUT_API_BATCH_HD_IDX01 ON OL_PAYOUT_API_BATCH_HD
(OAH_CREATE_TIMESTAMP, OAH_UPDATE_TIMESTAMP)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX OL_PAYOUT_API_BATCH_HD_PK ON OL_PAYOUT_API_BATCH_HD
(OAH_BATCH_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE OL_PAYOUT_API_BATCH_HD ADD (
  CONSTRAINT OL_PAYOUT_API_BATCH_HD_PK
  PRIMARY KEY
  (OAH_BATCH_ID)
  USING INDEX OL_PAYOUT_API_BATCH_HD_PK
  ENABLE VALIDATE);
