ALTER TABLE PSP_COGNOS_MAP
 DROP PRIMARY KEY CASCADE;

DROP TABLE PSP_COGNOS_MAP CASCADE CONSTRAINTS;

CREATE TABLE PSP_COGNOS_MAP
(
  PCM_GROUP             VARCHAR2(50 BYTE),
  PCM_PSP_ID            VARCHAR2(10 BYTE),
  PCM_GROUP_1           VARCHAR2(50 BYTE),
  PCM_CREATE_USER       VARCHAR2(20 BYTE),
  PCM_CREATE_TIMESTAMP  DATE,
  PCM_UPDATE_USER       VARCHAR2(20 BYTE),
  PCM_UPDATE_TIMESTAMP  DATE
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX PSP_COGNOS_MAP_IDX01 ON PSP_COGNOS_MAP
(PCM_GROUP)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX PSP_COGNOS_MAP_IDX02 ON PSP_COGNOS_MAP
(PCM_PSP_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PSP_COGNOS_MAP_PK ON PSP_COGNOS_MAP
(PCM_GROUP, PCM_PSP_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PSP_COGNOS_MAP ADD (
  CONSTRAINT PSP_COGNOS_MAP_PK
  PRIMARY KEY
  (PCM_GROUP, PCM_PSP_ID)
  USING INDEX PSP_COGNOS_MAP_PK
  ENABLE VALIDATE);

