ALTER TABLE TXN_MI_DETAIL
 DROP PRIMARY KEY CASCADE;

DROP TABLE TXN_MI_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE TXN_MI_DETAIL
(
  TM_TXN_ID                VARCHAR2(16 BYTE),
  TM_ENTITY_ID             VARCHAR2(10 BYTE),
  TM_PARTY_TYPE            CHAR(3 BYTE),
  TM_PARTY_ID              VARCHAR2(10 BYTE),
  TM_TXN_CCY               VARCHAR2(3 BYTE),
  TM_TXN_COUNTRY           CHAR(2 BYTE),
  TM_TXN_PRODUCT           CHAR(3 BYTE),
  TM_OPEN_ACCT_BAL         NUMBER(14,2)         DEFAULT 0,
  TM_ACCT_BAL              NUMBER(14,2)         DEFAULT 0,
  TM_OPEN_INTRANSIT        NUMBER(14,2)         DEFAULT 0,
  TM_INTRANSIT             NUMBER(14,2)         DEFAULT 0,
  TM_OPEN_AR_BAL           NUMBER(14,2)         DEFAULT 0,
  TM_AR_BAL                NUMBER(14,2)         DEFAULT 0,
  TM_TXN_DATE              VARCHAR2(8 BYTE),
  TM_REPORT_DATE           VARCHAR2(8 BYTE),
  TM_COST_RATE             NUMBER(12,5),
  TM_ACTUAL_COST           NUMBER(14,2),
  TM_REMITTANCE_SLIP_DATE  VARCHAR2(8 BYTE),
  TM_CONVERTED_CCY         VARCHAR2(3 BYTE),
  TM_CONVERTED_AMOUNT      NUMBER(14,2),
  TM_REMIT_RATE            NUMBER(12,5),
  TM_REMARK                VARCHAR2(255 BYTE),
  TM_PREV_GRP_TXN_ID       VARCHAR2(16 BYTE),
  TM_NEXT_GRP_TXN_ID       VARCHAR2(16 CHAR),
  TM_ACR_PRORATA           INTEGER              DEFAULT 0,
  TM_ENTITY_CCY            VARCHAR2(3 BYTE),
  TM_ENTITY_TXN_AMOUNT     NUMBER(14,2)         DEFAULT 0,
  TM_ENTITY_ACCT_NAME      VARCHAR2(50 BYTE),
  TM_CREATE_TIMESTAMP      DATE,
  TM_UPDATE_TIMESTAMP      DATE,
  TM_CREATE_USER           VARCHAR2(20 BYTE),
  TM_UPDATE_USER           VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX TXN_MI_DETAIL_IDX01 ON TXN_MI_DETAIL
(TM_ENTITY_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX TXN_MI_DETAIL_IDX02 ON TXN_MI_DETAIL
(TM_PARTY_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX TXN_MI_DETAIL_IDX03 ON TXN_MI_DETAIL
(TM_TXN_COUNTRY, TM_TXN_PRODUCT, TM_TXN_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX TXN_MI_DETAIL_IDX04 ON TXN_MI_DETAIL
(TM_CREATE_TIMESTAMP, TM_ENTITY_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX TXN_MI_DETAIL_IDX05 ON TXN_MI_DETAIL
(TM_TXN_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX TXN_MI_DETAIL_IDX06 ON TXN_MI_DETAIL
(TM_PREV_GRP_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX TXN_MI_DETAIL_IDX07 ON TXN_MI_DETAIL
(TM_NEXT_GRP_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX TXN_MI_DETAIL_PK ON TXN_MI_DETAIL
(TM_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE TXN_MI_DETAIL ADD (
  CONSTRAINT TXN_MI_DETAIL_PK
  PRIMARY KEY
  (TM_TXN_ID)
  USING INDEX TXN_MI_DETAIL_PK
  ENABLE VALIDATE);

