create or replace function sp_txn_mi_detail_insert(
       in_txn_id                                txn_mi_detail.tm_txn_id%type,
       in_entity_id                             txn_mi_detail.tm_entity_id%type,
       in_party_type                            txn_mi_detail.tm_party_type%type,
       in_party_id                              txn_mi_detail.tm_party_id%type,
       in_txn_ccy                               txn_mi_detail.tm_txn_ccy%type,
       in_txn_country                           txn_mi_detail.tm_txn_country%type,
       in_txn_product                           txn_mi_detail.tm_txn_product%type,
       in_open_acct_bal                         txn_mi_detail.tm_open_acct_bal%type,
       in_acct_bal                            	txn_mi_detail.tm_acct_bal%type,
       in_open_intransit                        txn_mi_detail.tm_open_intransit%type,
       in_intransit                             txn_mi_detail.tm_intransit%type,
       in_open_ar_bal                          	txn_mi_detail.tm_open_ar_bal%type,
       in_ar_bal                           	txn_mi_detail.tm_ar_bal%type,
       in_txn_date                          	txn_mi_detail.tm_txn_date%type,
       in_report_date                           txn_mi_detail.tm_report_date%type,
       in_cost_rate                             txn_mi_detail.tm_cost_rate%type,
       in_actual_cost                           txn_mi_detail.tm_actual_cost%type,
       in_remittance_slip_date                  txn_mi_detail.tm_remittance_slip_date%type,
       in_converted_ccy                         txn_mi_detail.tm_converted_ccy%type,
       in_converted_amount                      txn_mi_detail.tm_converted_amount%type,
       in_remit_rate				txn_mi_detail.tm_remit_rate%type,
       in_remark                           	txn_mi_detail.tm_remark%type,
       in_prev_grp_txn_id                       txn_mi_detail.tm_prev_grp_txn_id%type,
       in_next_grp_txn_id                       txn_mi_detail.tm_next_grp_txn_id%type,
       in_acr_prorata                           txn_mi_detail.tm_acr_prorata%type,
       in_entity_ccy                            txn_mi_detail.tm_entity_ccy%type,
       in_entity_txn_amount                   	txn_mi_detail.tm_entity_txn_amount%type,
       in_user                          	txn_mi_detail.tm_create_user%type)
  RETURN NUMBER IS
begin
                insert into txn_mi_detail
                        (tm_txn_id,
			tm_entity_id,
			tm_party_type,
			tm_party_id,
			tm_txn_ccy,
			tm_txn_country,
			tm_txn_product,
			tm_open_acct_bal,
			tm_acct_bal,
			tm_open_intransit,
			tm_intransit,
			tm_open_ar_bal,
			tm_ar_bal,
			tm_txn_date,
			tm_report_date,
			tm_cost_rate,
			tm_actual_cost,
			tm_remittance_slip_date,
			tm_converted_ccy,
			tm_converted_amount,
			tm_remit_rate,
			tm_remark,
			tm_prev_grp_txn_id,
			tm_next_grp_txn_id,
			tm_acr_prorata,
                        tm_create_user,
                        tm_create_timestamp,
                        tm_update_user,
                        tm_update_timestamp,
			tm_entity_ccy,
			tm_entity_txn_amount)
                 values(in_txn_id,
			in_entity_id,
			in_party_type,
			in_party_id,
			in_txn_ccy,
			in_txn_country,
			in_txn_product,
			in_open_acct_bal,
			in_acct_bal,
			in_open_intransit,
			in_intransit,
			in_open_ar_bal,
			in_ar_bal,
			in_txn_date,
			in_report_date,
			in_cost_rate,
			in_actual_cost,
			in_remittance_slip_date,
			in_converted_ccy,
			in_converted_amount,
			in_remit_rate,
			in_remark,
			in_prev_grp_txn_id,
			in_next_grp_txn_id,
			in_acr_prorata,		
                        in_user,
                        sysdate,
                        in_user,
                        sysdate,
			in_entity_ccy,
			in_entity_txn_amount);

                IF SQL%ROWCOUNT = 0 THEN
                        RETURN 1;
                ELSE
                        RETURN 0;
                END IF;

EXCEPTION
  WHEN OTHERS THEN
     RETURN 9;
end sp_txn_mi_detail_insert;
/
