OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/PspTxnCheckReportParameter
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBPspTxnCheckReportParameter.so
SOOBJS =  PspTxnCheckReportParameter.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
