ALTER TABLE PAYOUT_RETURN_BATCH_DT
 DROP PRIMARY KEY CASCADE;

DROP TABLE PAYOUT_RETURN_BATCH_DT CASCADE CONSTRAINTS;

CREATE TABLE PAYOUT_RETURN_BATCH_DT
(
  PRD_BATCH_ID          INTEGER                 NOT NULL,
  PRD_SEQ               INTEGER                 NOT NULL,
  PRD_TXN_ID            VARCHAR2(16 BYTE),
  PRD_ACCOUNT_NAME      VARCHAR2(100 BYTE),
  PRD_ACCOUNT_NUM       VARCHAR2(25 BYTE),
  PRD_AMOUNT            NUMBER(12,2),
  PRD_REASON            VARCHAR2(255 BYTE),
  PRD_IS_VALID          INTEGER                 DEFAULT 0,
  PRD_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  PRD_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  PRD_CREATE_USER       VARCHAR2(20 BYTE),
  PRD_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PAYOUT_RETURN_BATCH_DT_PK ON PAYOUT_RETURN_BATCH_DT
(PRD_BATCH_ID, PRD_SEQ)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PAYOUT_RETURN_BATCH_DT ADD (
  CONSTRAINT PAYOUT_RETURN_BATCH_DT_PK
  PRIMARY KEY
  (PRD_BATCH_ID, PRD_SEQ)
  USING INDEX PAYOUT_RETURN_BATCH_DT_PK
  ENABLE VALIDATE);

ALTER TABLE PAYOUT_RETURN_BATCH_DT ADD (
  CONSTRAINT PAYOUT_RETURN_BATCH_DT_FK01 
  FOREIGN KEY (PRD_BATCH_ID) 
  REFERENCES PAYOUT_RETURN_BATCH_HD (PRH_BATCH_ID)
  ENABLE VALIDATE);

