ALTER TABLE OL_DEF_PSP_STL_MERCH_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_DEF_PSP_STL_MERCH_TYPE CASCADE CONSTRAINTS;

CREATE TABLE OL_DEF_PSP_STL_MERCH_TYPE
(
  PSMT_TYPE              INTEGER,
  PSMT_DESC              VARCHAR2(50 BYTE),
  PSMT_IS_DEFAULT        INTEGER                DEFAULT 0,
  PSMT_CREATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  PSMT_UPDATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  PSMT_CREATE_USER       VARCHAR2(20 BYTE),
  PSMT_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_DEF_PSP_STL_MERCH_TYPE_PK ON OL_DEF_PSP_STL_MERCH_TYPE
(PSMT_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_DEF_PSP_STL_MERCH_TYPE ADD (
  CONSTRAINT OL_DEF_PSP_STL_MERCH_TYPE_PK
  PRIMARY KEY
  (PSMT_TYPE)
  USING INDEX OL_DEF_PSP_STL_MERCH_TYPE_PK
  ENABLE VALIDATE);

