ALTER TABLE MMS_ENTITY_OPB
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_ENTITY_OPB CASCADE CONSTRAINTS;

CREATE TABLE MMS_ENTITY_OPB
(
  MEOB_ENTITY_ID         VARCHAR2(20 BYTE),
  MEOB_OPB_ID        VARCHAR2(20 BYTE),
  MEOB_DESC              VARCHAR2(100 BYTE),
  MEOB_CREATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  MEOB_CREATE_USER       VARCHAR2(20 BYTE),
  MEOB_UPDATE_TIMESTAMP  DATE,
  MEOB_UPDATE_USER       VARCHAR2(20 BYTE),
  MEOB_STATUS_REF	 CHAR(1 BYTE),
  MEOB_ACCT_NAME	 VARCHAR2(50 BYTE),
  MEOB_ACCT_NUM		 VARCHAR2(50 BYTE),
  MEOB_ACCT_HOLDER	 VARCHAR2(50 BYTE),
  MEOB_BASE_CCY		 VARCHAR2(3 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX MMS_ENTITY_OPB_IDX01 ON MMS_ENTITY_OPB
(MEOB_ENTITY_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX MMS_ENTITY_OPB_PK ON MMS_ENTITY_OPB
(MEOB_OPB_ID)
LOGGING
TABLESPACE USER_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_ENTITY_OPB ADD (
  CONSTRAINT MMS_ENTITY_OPB_PK
  PRIMARY KEY
  (MEOB_OPB_ID)
  USING INDEX MMS_ENTITY_OPB_PK
  ENABLE VALIDATE);

