DROP TABLE OL_TXN_ACK_LOG CASCADE CONSTRAINTS;

CREATE TABLE OL_TXN_ACK_LOG
(
  OAL_TXN_ID            VARCHAR2(16 BYTE)        NOT NULL,
  OAL_ORG_TXN_ID        VARCHAR2(16 BYTE)        NOT NULL,
  OAL_STATUS            CHAR(1 BYTE)             NOT NULL,
  OAL_INTERNAL_CODE     NUMBER(8),
  OAL_CREATE_USER       VARCHAR2(20 BYTE),
  OAL_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  OAL_UPDATE_USER       VARCHAR2(20 BYTE),
  OAL_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX OL_TXN_ACK_LOG_IDX01 ON OL_TXN_ACK_LOG
(OAL_TXN_ID, OAL_ORG_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

