OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/PspResponseTxnUrl
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBPspResponseTxnUrl.so
SOOBJS =  PspResponseTxnUrl.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
