OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLTxnEngineLinkage
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLTxnEngineLinkage.so
SOOBJS =  OLTxnEngineLinkage.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
