OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnMgtByUsJLP
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnMgtByUsJLP.so
SOOBJS = TxnMgtByUsJLP.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
