CREATE TABLE DEF_MERCH_PSP_TYPE
(
  DMPT_TYPE          	 CHAR(1 BYTE)          NOT NULL,
  DMPT_DESC   		 VARCHAR2(50 BYTE),
  DMPT_CREATE_USER       VARCHAR2(20 BYTE),
  DMPT_CREATE_TIMESTAMP  DATE                  DEFAULT sysdate,
  DMPT_UPDATE_USER       VARCHAR2(20 BYTE),
  DMPT_UPDATE_TIMESTAMP  DATE                  DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEF_MERCH_PSP_TYPE_PK ON DEF_MERCH_PSP_TYPE
(DMPT_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_MERCH_PSP_TYPE ADD (
  CONSTRAINT DEF_MERCH_PSP_TYPE_PK
  PRIMARY KEY
  (DMPT_TYPE)
  USING INDEX DEF_MERCH_PSP_TYPE_PK
  ENABLE VALIDATE);

