ALTER TABLE OL_BAID_BT_FILE_HEADER 
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_BAID_BT_FILE_HEADER CASCADE CONSTRAINTS;

CREATE TABLE OL_BAID_BT_FILE_HEADER 
(
  BBH_FILE_ID		NUMBER(16), 
  BBH_SR_CLIENT_ID	VARCHAR2(10 BYTE), 
  BBH_USE_DUMMY_ACCT	INTEGER, 
  BBH_RT_BAID		VARCHAR2(20 BYTE), 
  BBH_RAW_FILENAME	VARCHAR2(100 BYTE), 
  BBH_CONVERT_FILENAME	VARCHAR2(100 BYTE), 
  BBH_TOTAL_COUNT	INTEGER, 
  BBH_ACCEPT_COUNT	INTEGER, 
  BBH_STATUS		CHAR(1 BYTE), 
  BBH_MSG_CODE		NUMBER(8), 
  BBH_CREATE_TIMESTAMP	DATE			DEFAULT sysdate, 
  BBH_CREATE_USER	VARCHAR2(20 BYTE), 
  BBH_UPDATE_TIMESTAMP	DATE			DEFAULT sysdate, 
  BBH_UPDATE_USER	VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA 
PCTUSED    0 
PCTFREE    10 
INITRANS   1 
MAXTRANS   255 
STORAGE    (
            INITIAL         64K 
            NEXT            1M 
            MINEXTENTS      1 
            MAXEXTENTS      UNLIMITED 
            PCTINCREASE     0 
            BUFFER_POOL     DEFAULT
           ) 
LOGGING 
NOCOMPRESS 
NOCACHE 
MONITORING;

CREATE UNIQUE INDEX OL_BAID_BT_FILE_HEADER_PK ON OL_BAID_BT_FILE_HEADER 
(BBH_FILE_ID) 
LOGGING 
TABLESPACE USER_IDX 
PCTFREE    10 
INITRANS   2 
MAXTRANS   255 
STORAGE    (
            INITIAL          64K 
            NEXT             1M 
            MINEXTENTS       1 
            MAXEXTENTS       UNLIMITED 
            PCTINCREASE      0 
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX OL_BAID_BT_FILE_HEADER_IDX01 ON OL_BAID_BT_FILE_HEADER 
(BBH_RAW_FILENAME) 
LOGGING 
TABLESPACE USER_IDX 
PCTFREE    10 
INITRANS   2 
MAXTRANS   255 
STORAGE    (
            INITIAL          64K 
            NEXT             1M 
            MINEXTENTS       1 
            MAXEXTENTS       UNLIMITED 
            PCTINCREASE      0 
            BUFFER_POOL      DEFAULT 
            FLASH_CACHE      DEFAULT 
            CELL_FLASH_CACHE DEFAULT
           ) 
NOPARALLEL;

CREATE INDEX OL_BAID_BT_FILE_HEADER_IDX02 ON OL_BAID_BT_FILE_HEADER 
(BBH_CONVERT_FILENAME) 
LOGGING 
TABLESPACE USER_IDX 
PCTFREE    10 
INITRANS   2 
MAXTRANS   255 
STORAGE    (
            INITIAL          64K 
            NEXT             1M 
            MINEXTENTS       1 
            MAXEXTENTS       UNLIMITED 
            PCTINCREASE      0 
            BUFFER_POOL      DEFAULT 
            FLASH_CACHE      DEFAULT 
            CELL_FLASH_CACHE DEFAULT
           ) 
NOPARALLEL;

CREATE INDEX OL_BAID_BT_FILE_HEADER_IDX03 ON OL_BAID_BT_FILE_HEADER 
(BBH_CREATE_TIMESTAMP, BBH_UPDATE_TIMESTAMP) 
LOGGING 
TABLESPACE USER_IDX 
PCTFREE    10 
INITRANS   2 
MAXTRANS   255 
STORAGE    (
            INITIAL          64K 
            NEXT             1M 
            MINEXTENTS       1 
            MAXEXTENTS       UNLIMITED 
            PCTINCREASE      0 
            BUFFER_POOL      DEFAULT 
            FLASH_CACHE      DEFAULT 
            CELL_FLASH_CACHE DEFAULT
           ) 
NOPARALLEL;

CREATE INDEX OL_BAID_BT_FILE_HEADER_IDX04 ON OL_BAID_BT_FILE_HEADER 
(BBH_STATUS) 
LOGGING 
TABLESPACE USER_IDX 
PCTFREE    10 
INITRANS   2 
MAXTRANS   255 
STORAGE    (
            INITIAL          64K 
            NEXT             1M 
            MINEXTENTS       1 
            MAXEXTENTS       UNLIMITED 
            PCTINCREASE      0 
            BUFFER_POOL      DEFAULT 
            FLASH_CACHE      DEFAULT 
            CELL_FLASH_CACHE DEFAULT
           ) 
NOPARALLEL;

ALTER TABLE OL_BAID_BT_FILE_HEADER ADD (
  CONSTRAINT OL_BAID_BT_FILE_HEADER_PK 
  PRIMARY KEY 
  (BBH_FILE_ID) 
  USING INDEX OL_BAID_BT_FILE_HEADER_PK 
  ENABLE VALIDATE);

ALTER TABLE OL_BAID_BT_FILE_HEADER ADD (
  CONSTRAINT OL_BAID_BT_FILE_HEADER_FK01 
  FOREIGN KEY (BBH_SR_CLIENT_ID) 
  REFERENCES PSP_MASTER (PM_CLIENT_ID) 
  ENABLE VALIDATE, 
  CONSTRAINT OL_BAID_BT_FILE_HEADER_FK02 
  FOREIGN KEY (BBH_RT_BAID) 
  REFERENCES OL_BANK_ACCT_ID (OBAI_BAID) 
  ENABLE VALIDATE, 
  CONSTRAINT OL_BAID_BT_FILE_HEADER_FK03 
  FOREIGN KEY (BBH_STATUS) 
  REFERENCES OL_DEF_BAID_BT_FILE_STATUS (BBS_TYPE) 
  ENABLE VALIDATE);
