ALTER TABLE OL_BAID_BT_FILE_DETAIL 
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_BAID_BT_FILE_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE OL_BAID_BT_FILE_DETAIL 
(
  BBD_FILE_ID		NUMBER(16), 
  BBD_SEQ		INTEGER, 
  BBD_SR_BANK_NAME	VARCHAR2(50 BYTE), 
  BBD_SR_BANK_ACCT_NUM	VARCHAR2(50 BYTE), 
  BBD_SWEEP_OUT_AMT	NUMBER(14,2), 
  BBD_RT_BANK_NAME	VARCHAR2(50 BYTE), 
  BBD_RT_BANK_ACCT_NUM	VARCHAR2(50 BYTE), 
  BBD_SWEEP_OUT_TXN_ID	VARCHAR2(16 BYTE), 
  BBD_SWEEP_IN_TXN_ID	VARCHAR2(16 BYTE), 
  BBD_CREATE_TIMESTAMP	DATE			DEFAULT sysdate, 
  BBD_CREATE_USER	VARCHAR2(20 BYTE), 
  BBD_UPDATE_TIMESTAMP	DATE			DEFAULT sysdate, 
  BBD_UPDATE_USER	VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA 
PCTUSED    0 
PCTFREE    10 
INITRANS   1 
MAXTRANS   255 
STORAGE    (
            INITIAL          64K 
            NEXT             1M 
            MINEXTENTS       1 
            MAXEXTENTS       UNLIMITED 
            PCTINCREASE      0 
            BUFFER_POOL      DEFAULT
           ) 
LOGGING 
NOCOMPRESS 
NOCACHE 
MONITORING;

CREATE UNIQUE INDEX OL_BAID_BT_FILE_DETAIL_PK ON OL_BAID_BT_FILE_DETAIL 
(BBD_FILE_ID, BBD_SEQ) 
LOGGING 
TABLESPACE USER_IDX 
PCTFREE    10 
INITRANS   2 
MAXTRANS   255 
STORAGE    (
            INITIAL          64K 
            NEXT             1M 
            MINEXTENTS       1 
            MAXEXTENTS       UNLIMITED 
            PCTINCREASE      0 
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX OL_BAID_BT_FILE_DETAIL_IDX01 ON OL_BAID_BT_FILE_DETAIL 
(BBD_CREATE_TIMESTAMP, BBD_UPDATE_TIMESTAMP) 
LOGGING 
TABLESPACE USER_IDX 
PCTFREE    10 
INITRANS   2 
MAXTRANS   255 
STORAGE    (
            INITIAL          64K 
            NEXT             1M 
            MINEXTENTS       1 
            MAXEXTENTS       UNLIMITED 
            PCTINCREASE      0 
            BUFFER_POOL      DEFAULT 
            FLASH_CACHE      DEFAULT 
            CELL_FLASH_CACHE DEFAULT
           ) 
NOPARALLEL;

CREATE INDEX OL_BAID_BT_FILE_DETAIL_IDX02 ON OL_BAID_BT_FILE_DETAIL 
(BBD_SWEEP_OUT_TXN_ID, BBD_SWEEP_IN_TXN_ID) 
LOGGING 
TABLESPACE USER_IDX 
PCTFREE    10 
INITRANS   2 
MAXTRANS   255 
STORAGE    (
            INITIAL          64K 
            NEXT             1M 
            MINEXTENTS       1 
            MAXEXTENTS       UNLIMITED 
            PCTINCREASE      0 
            BUFFER_POOL      DEFAULT 
            FLASH_CACHE      DEFAULT 
            CELL_FLASH_CACHE DEFAULT
           ) 
NOPARALLEL;

ALTER TABLE OL_BAID_BT_FILE_DETAIL ADD (
  CONSTRAINT OL_BAID_BT_FILE_DETAIL_PK 
  PRIMARY KEY 
  (BBD_FILE_ID, BBD_SEQ) 
  USING INDEX OL_BAID_BT_FILE_DETAIL_PK 
  ENABLE VALIDATE);

ALTER TABLE OL_BAID_BT_FILE_DETAIL ADD (
  CONSTRAINT OL_BAID_BT_FILE_DETAIL_FK01 
  FOREIGN KEY (BBD_FILE_ID) 
  REFERENCES OL_BAID_BT_FILE_HEADER (BBH_FILE_ID) 
  ENABLE VALIDATE);
