ALTER TABLE OL_BAID_BT_FILE_ERROR 
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_BAID_BT_FILE_ERROR CASCADE CONSTRAINTS;

CREATE TABLE OL_BAID_BT_FILE_ERROR 
(
  BBE_ERROR_ID		NUMBER(16), 
  BBE_FILE_ID		NUMBER(16), 
  BBE_SEQ		INTEGER, 
  BBE_MSG_CODE		NUMBER(8), 
  BBE_LINE_CONTENT	VARCHAR2(1024 BYTE), 
  BBE_CREATE_TIMESTAMP	DATE			DEFAULT sysdate, 
  BBE_CREATE_USER	VARCHAR2(20 BYTE), 
  BBE_UPDATE_TIMESTAMP	DATE			DEFAULT sysdate, 
  BBE_UPDATE_USER	VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA 
PCTUSED    0 
PCTFREE    10 
INITRANS   1 
MAXTRANS   255 
STORAGE    (
            INITIAL     64K 
            NEXT        1M 
            MINEXTENTS  1 
            MAXEXTENTS  UNLIMITED 
            PCTINCREASE 0 
            BUFFER_POOL DEFAULT
           ) 
LOGGING 
NOCOMPRESS 
NOCACHE 
MONITORING;

CREATE UNIQUE INDEX OL_BAID_BT_FILE_ERROR_PK ON OL_BAID_BT_FILE_ERROR 
(BBE_ERROR_ID) 
LOGGING 
TABLESPACE USER_IDX 
PCTFREE    10 
INITRANS   2 
MAXTRANS   255 
STORAGE    (
            INITIAL          64K 
            NEXT             1M 
            MINEXTENTS       1 
            MAXEXTENTS       UNLIMITED 
            PCTINCREASE      0 
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX OL_BAID_BT_FILE_ERROR_IDX01 ON OL_BAID_BT_FILE_ERROR 
(BBE_CREATE_TIMESTAMP, BBE_UPDATE_TIMESTAMP) 
LOGGING 
TABLESPACE USER_IDX 
PCTFREE    10 
INITRANS   2 
MAXTRANS   255 
STORAGE    (
            INITIAL          64K 
            NEXT             1M 
            MINEXTENTS       1 
            MAXEXTENTS       UNLIMITED 
            PCTINCREASE      0 
            BUFFER_POOL      DEFAULT 
            FLASH_CACHE      DEFAULT 
            CELL_FLASH_CACHE DEFAULT
           ) 
NOPARALLEL;

ALTER TABLE OL_BAID_BT_FILE_ERROR ADD (
  CONSTRAINT OL_BAID_BT_FILE_ERROR_PK 
  PRIMARY KEY 
  (BBE_ERROR_ID) 
  USING INDEX OL_BAID_BT_FILE_ERROR_PK 
  ENABLE VALIDATE);

ALTER TABLE OL_BAID_BT_FILE_ERROR ADD (
  CONSTRAINT OL_BAID_BT_FILE_ERROR_FK01 
  FOREIGN KEY (BBE_FILE_ID) 
  REFERENCES OL_BAID_BT_FILE_HEADER (BBH_FILE_ID) 
  ENABLE VALIDATE);
