DROP TABLE EMAIL_FUNCT_EXCLUDE CASCADE CONSTRAINTS;

CREATE TABLE EMAIL_FUNCT_EXCLUDE
(
  EFE_FUNCT             VARCHAR2(15 BYTE),
  EFE_TAGNAME           VARCHAR2(50 BYTE),
  EFE_TYPE              VARCHAR2(20 BYTE),
  EFE_OPERATOR          VARCHAR2(2 BYTE),
  EFE_VALUE             VARCHAR2(50 BYTE),
  EFE_CREATE_USER       VARCHAR2(20 BYTE),
  EFE_UPDATE_USER       VARCHAR2(20 BYTE),
  EFE_CREATE_TIMESTAMP  DATE               DEFAULT SYSDATE,
  EFE_UPDATE_TIMESTAMP  DATE               DEFAULT SYSDATE
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX EMAIL_FUNCT_EXCLUDE_IDX01 ON EMAIL_FUNCT_EXCLUDE
(EFE_FUNCT)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

ALTER TABLE EMAIL_FUNCT_EXCLUDE ADD (
  CONSTRAINT EMAIL_FUNCT_EXCLUDE_FK01
  FOREIGN KEY (EFE_FUNCT)
  REFERENCES EMAIL_FUNCT (EF_FUNCT)
  ENABLE VALIDATE);

