ALTER TABLE MI_BATCH_HEADER
 DROP PRIMARY KEY CASCADE;

DROP TABLE MI_BATCH_HEADER CASCADE CONSTRAINTS;

CREATE TABLE MI_BATCH_HEADER
(
  BH_BATCH_ID          VARCHAR2(16 BYTE),
  BH_PROCESS_TYPE      VARCHAR2(20 BYTE),
  BH_STATUS            CHAR(1 BYTE),
  BH_CREATE_TIMESTAMP  DATE,
  BH_UPDATE_TIMESTAMP  DATE,
  BH_CREATE_USER       VARCHAR2(20 BYTE),
  BH_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MI_BATCH_HEADER_PK ON MI_BATCH_HEADER
(BH_BATCH_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MI_BATCH_HEADER ADD (
  CONSTRAINT MI_BATCH_HEADER_PK
  PRIMARY KEY
  (BH_BATCH_ID)
  USING INDEX MI_BATCH_HEADER_PK
  ENABLE VALIDATE);

ALTER TABLE MI_BATCH_HEADER ADD (
  CONSTRAINT MI_BATCH_HEADER_FK01 
  FOREIGN KEY (BH_PROCESS_TYPE) 
  REFERENCES MI_DEF_PROCESS_TYPE (PT_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT MI_BATCH_HEADER_FK02 
  FOREIGN KEY (BH_STATUS) 
  REFERENCES MI_DEF_BATCH_STATUS (BS_TYPE)
  ENABLE VALIDATE);

