ALTER TABLE DEF_CLIENT
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_CLIENT CASCADE CONSTRAINTS;

CREATE TABLE DEF_CLIENT
(
  DC_ID  	       VARCHAR2(10 BYTE),
  DC_NAME              VARCHAR2(50 BYTE),
  DC_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  DC_CREATE_USER       VARCHAR2(20 BYTE),
  DC_UPDATE_TIMESTAMP  DATE			DEFAULT sysdate,
  DC_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEF_CLIENT_PK ON DEF_CLIENT
(DC_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_CLIENT ADD (
  CONSTRAINT CLIENT_PK
  PRIMARY KEY
  (DC_ID)
  USING INDEX DEF_CLIENT_PK);


