


CREATE TABLE OL_DEF_REPORT_TYPE
(
  ODRT_TYPE              CHAR(3 BYTE)             NOT NULL,
  ODRT_DESC              VARCHAR2(50 BYTE),
  ODRT_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  ODRT_CREATE_USER       VARCHAR2(20 BYTE),
  ODRT_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  ODRT_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;


CREATE UNIQUE INDEX OL_DEF_REPORT_TYPE_PK ON OL_DEF_REPORT_TYPE
(ODRT_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE OL_DEF_REPORT_TYPE ADD (
  CONSTRAINT OL_DEF_REPORT_TYPE_PK
  PRIMARY KEY
  (ODRT_TYPE)
  USING INDEX OL_DEF_REPORT_TYPE_PK
  ENABLE VALIDATE);
