ALTER TABLE CPHUSER.PAYOUT_HEADER
 DROP PRIMARY KEY CASCADE;

DROP TABLE CPHUSER.PAYOUT_HEADER CASCADE CONSTRAINTS;

CREATE TABLE CPHUSER.PAYOUT_HEADER
(
  BATCH_ID       VARCHAR2(16 BYTE)              NOT NULL,
  TXN_DATE       VARCHAR2(8 BYTE)               NOT NULL,
  MERCHANT_ID    VARCHAR2(15 BYTE)              NOT NULL,
  NUM_OF_RECORD  NUMBER(38)                     NOT NULL,
  CHECKSUM       VARCHAR2(16 BYTE)              NOT NULL,
  STATUS         CHAR(1 BYTE)                   DEFAULT 'I'                   NOT NULL
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CPHUSER.PAYOUT_HEADER_PK ON CPHUSER.PAYOUT_HEADER
(BATCH_ID, TXN_DATE)
LOGGING
TABLESPACE USER_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE CPHUSER.PAYOUT_HEADER ADD (
  CONSTRAINT PAYOUT_HEADER_PK
  PRIMARY KEY
  (BATCH_ID, TXN_DATE)
  USING INDEX CPHUSER.PAYOUT_HEADER_PK);

