ALTER TABLE MOB_BANK_SELECTION
 DROP PRIMARY KEY CASCADE;

DROP TABLE MOB_BANK_SELECTION CASCADE CONSTRAINTS;

CREATE TABLE MOB_BANK_SELECTION
(
  MBS_GROUP             VARCHAR2(10 BYTE),
  MBS_OVERFLOW_GRP      VARCHAR2(10 BYTE),
  MBS_UNION_GRP         VARCHAR2(10 BYTE),
  MBS_DEF_ASSIGN_GRP    INTEGER,
  MBS_DISABLED          INTEGER                 DEFAULT 0,
  MBS_ALLOW_TRF_IN      INTEGER                 DEFAULT 0,
  MBS_ALLOW_TRF_OUT     INTEGER                 DEFAULT 0,
  MBS_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  MBS_CREATE_USER       VARCHAR2(20 BYTE),
  MBS_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  MBS_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MOB_BANK_SELECTION_PK ON MOB_BANK_SELECTION
(MBS_GROUP)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MOB_BANK_SELECTION ADD (
  CONSTRAINT MOB_BANK_SELECTION_PK
  PRIMARY KEY
  (MBS_GROUP)
  USING INDEX MOB_BANK_SELECTION_PK
  ENABLE VALIDATE);

