ALTER TABLE DEF_ACR_POOL
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_ACR_POOL CASCADE CONSTRAINTS;

CREATE TABLE DEF_ACR_POOL
(
  DP_CODE            VARCHAR2(3 BYTE)         NOT NULL,
  DP_DESC              VARCHAR2(50 BYTE),
  DP_CREATE_USER       VARCHAR2(20 BYTE),
  DP_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  DP_UPDATE_USER       VARCHAR2(20 BYTE),
  DP_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEF_ACR_POOL_PK ON DEF_ACR_POOL
(DP_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_ACR_POOL ADD (
  CONSTRAINT DEF_ACR_POOL_PK
  PRIMARY KEY
  (DP_CODE)
  USING INDEX DEF_ACR_POOL_PK
  ENABLE VALIDATE);

