ALTER TABLE CRR_EXT_JNL_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE CRR_EXT_JNL_TYPE CASCADE CONSTRAINTS;

CREATE TABLE CRR_EXT_JNL_TYPE
(
  EJT_JNL_TYPE_ID       INTEGER,
  EJT_JNL_DISABLED      INTEGER                 DEFAULT 0,
  EJT_JNL_REMARK        VARCHAR2(100 BYTE),
  EJT_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  EJT_CREATE_USER       VARCHAR2(20 BYTE),
  EJT_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  EJT_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CRR_EXT_JNL_TYPE_PK ON CRR_EXT_JNL_TYPE
(EJT_JNL_TYPE_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE CRR_EXT_JNL_TYPE ADD (
  CONSTRAINT CRR_EXT_JNL_TYPE_PK
  PRIMARY KEY
  (EJT_JNL_TYPE_ID)
  USING INDEX CRR_EXT_JNL_TYPE_PK
  ENABLE VALIDATE);

