ALTER TABLE TXN_REMARKS
 DROP PRIMARY KEY CASCADE;

DROP TABLE TXN_REMARKS CASCADE CONSTRAINTS;

CREATE TABLE TXN_REMARKS
(
  TR_TXN_ID            VARCHAR2(16 BYTE),
  TR_TXN_CODE          VARCHAR2(3 BYTE),
  TR_STATUS            CHAR(1 BYTE),
  TR_AR_IND            CHAR(1 BYTE),
  TR_SUB_STATUS        CHAR(3 BYTE),
  TR_EXEC_SEQ          INTEGER,
  TR_REMARK            VARCHAR2(255 BYTE),
  TR_CREATE_USER       VARCHAR2(20 BYTE),
  TR_CREATE_TIMESTAMP  DATE,
  TR_UPDATE_USER       VARCHAR2(20 BYTE),
  TR_UPDATE_TIMESTAMP  DATE
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX TXN_REMARKS_PK ON TXN_REMARKS
(TR_TXN_ID, TR_TXN_CODE, TR_STATUS, TR_AR_IND, TR_SUB_STATUS, TR_EXEC_SEQ)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE TXN_REMARKS ADD (
  CONSTRAINT TXN_REMARKS_PK
  PRIMARY KEY
  (TR_TXN_ID, TR_TXN_CODE, TR_STATUS, TR_AR_IND, TR_SUB_STATUS, TR_EXEC_SEQ)
  USING INDEX TXN_REMARKS_PK
  ENABLE VALIDATE);

