/* soapH.h
   Generated by gSOAP 2.8.0 from twv.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   The generated code is released under one of the following licenses:
   GPL OR Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifdef __cplusplus
extern "C" {
#endif
#ifndef WITH_NOIDREF
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_begin_send(soap) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_begin_send(soap) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef SOAP_TYPE_time
#define SOAP_TYPE_time (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_time(struct soap*, time_t *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_time(struct soap*, const char*, int, const time_t *, const char*);
SOAP_FMAC3 time_t * SOAP_FMAC4 soap_in_time(struct soap*, const char*, time_t *, const char*);

#ifndef soap_write_time
#define soap_write_time(soap, data) ( soap_begin_send(soap) || soap_put_time(soap, data, "dateTime", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_time(struct soap*, const time_t *, const char*, const char*);

#ifndef soap_read_time
#define soap_read_time(soap, data) ( soap_begin_recv(soap) || !soap_get_time(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 time_t * SOAP_FMAC4 soap_get_time(struct soap*, time_t *, const char*, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data), 0) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data), 0) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data), 0) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data), 0) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data), 0) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#endif

#ifndef SOAP_TYPE_ns2__PingAlive
#define SOAP_TYPE_ns2__PingAlive (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__PingAlive(struct soap*, struct ns2__PingAlive *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__PingAlive(struct soap*, const struct ns2__PingAlive *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__PingAlive(struct soap*, const char*, int, const struct ns2__PingAlive *, const char*);
SOAP_FMAC3 struct ns2__PingAlive * SOAP_FMAC4 soap_in_ns2__PingAlive(struct soap*, const char*, struct ns2__PingAlive *, const char*);

#ifndef soap_write_ns2__PingAlive
#define soap_write_ns2__PingAlive(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns2__PingAlive(soap, data), 0) || soap_put_ns2__PingAlive(soap, data, "ns2:PingAlive", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__PingAlive(struct soap*, const struct ns2__PingAlive *, const char*, const char*);

#ifndef soap_read_ns2__PingAlive
#define soap_read_ns2__PingAlive(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__PingAlive(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns2__PingAlive * SOAP_FMAC4 soap_get_ns2__PingAlive(struct soap*, struct ns2__PingAlive *, const char*, const char*);

#ifndef SOAP_TYPE_ns2__PingAliveResponse
#define SOAP_TYPE_ns2__PingAliveResponse (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__PingAliveResponse(struct soap*, struct ns2__PingAliveResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__PingAliveResponse(struct soap*, const struct ns2__PingAliveResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__PingAliveResponse(struct soap*, const char*, int, const struct ns2__PingAliveResponse *, const char*);
SOAP_FMAC3 struct ns2__PingAliveResponse * SOAP_FMAC4 soap_in_ns2__PingAliveResponse(struct soap*, const char*, struct ns2__PingAliveResponse *, const char*);

#ifndef soap_write_ns2__PingAliveResponse
#define soap_write_ns2__PingAliveResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns2__PingAliveResponse(soap, data), 0) || soap_put_ns2__PingAliveResponse(soap, data, "ns2:PingAliveResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__PingAliveResponse(struct soap*, const struct ns2__PingAliveResponse *, const char*, const char*);

#ifndef soap_read_ns2__PingAliveResponse
#define soap_read_ns2__PingAliveResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__PingAliveResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns2__PingAliveResponse * SOAP_FMAC4 soap_get_ns2__PingAliveResponse(struct soap*, struct ns2__PingAliveResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ns2__WithdrawInquiry
#define SOAP_TYPE_ns2__WithdrawInquiry (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__WithdrawInquiry(struct soap*, struct ns2__WithdrawInquiry *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__WithdrawInquiry(struct soap*, const struct ns2__WithdrawInquiry *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__WithdrawInquiry(struct soap*, const char*, int, const struct ns2__WithdrawInquiry *, const char*);
SOAP_FMAC3 struct ns2__WithdrawInquiry * SOAP_FMAC4 soap_in_ns2__WithdrawInquiry(struct soap*, const char*, struct ns2__WithdrawInquiry *, const char*);

#ifndef soap_write_ns2__WithdrawInquiry
#define soap_write_ns2__WithdrawInquiry(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns2__WithdrawInquiry(soap, data), 0) || soap_put_ns2__WithdrawInquiry(soap, data, "ns2:WithdrawInquiry", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__WithdrawInquiry(struct soap*, const struct ns2__WithdrawInquiry *, const char*, const char*);

#ifndef soap_read_ns2__WithdrawInquiry
#define soap_read_ns2__WithdrawInquiry(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__WithdrawInquiry(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns2__WithdrawInquiry * SOAP_FMAC4 soap_get_ns2__WithdrawInquiry(struct soap*, struct ns2__WithdrawInquiry *, const char*, const char*);

#ifndef SOAP_TYPE_ns2__WithdrawInquiryResponse
#define SOAP_TYPE_ns2__WithdrawInquiryResponse (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__WithdrawInquiryResponse(struct soap*, struct ns2__WithdrawInquiryResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__WithdrawInquiryResponse(struct soap*, const struct ns2__WithdrawInquiryResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__WithdrawInquiryResponse(struct soap*, const char*, int, const struct ns2__WithdrawInquiryResponse *, const char*);
SOAP_FMAC3 struct ns2__WithdrawInquiryResponse * SOAP_FMAC4 soap_in_ns2__WithdrawInquiryResponse(struct soap*, const char*, struct ns2__WithdrawInquiryResponse *, const char*);

#ifndef soap_write_ns2__WithdrawInquiryResponse
#define soap_write_ns2__WithdrawInquiryResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns2__WithdrawInquiryResponse(soap, data), 0) || soap_put_ns2__WithdrawInquiryResponse(soap, data, "ns2:WithdrawInquiryResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__WithdrawInquiryResponse(struct soap*, const struct ns2__WithdrawInquiryResponse *, const char*, const char*);

#ifndef soap_read_ns2__WithdrawInquiryResponse
#define soap_read_ns2__WithdrawInquiryResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__WithdrawInquiryResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns2__WithdrawInquiryResponse * SOAP_FMAC4 soap_get_ns2__WithdrawInquiryResponse(struct soap*, struct ns2__WithdrawInquiryResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ns2__DepositInquiry
#define SOAP_TYPE_ns2__DepositInquiry (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__DepositInquiry(struct soap*, struct ns2__DepositInquiry *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__DepositInquiry(struct soap*, const struct ns2__DepositInquiry *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__DepositInquiry(struct soap*, const char*, int, const struct ns2__DepositInquiry *, const char*);
SOAP_FMAC3 struct ns2__DepositInquiry * SOAP_FMAC4 soap_in_ns2__DepositInquiry(struct soap*, const char*, struct ns2__DepositInquiry *, const char*);

#ifndef soap_write_ns2__DepositInquiry
#define soap_write_ns2__DepositInquiry(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns2__DepositInquiry(soap, data), 0) || soap_put_ns2__DepositInquiry(soap, data, "ns2:DepositInquiry", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__DepositInquiry(struct soap*, const struct ns2__DepositInquiry *, const char*, const char*);

#ifndef soap_read_ns2__DepositInquiry
#define soap_read_ns2__DepositInquiry(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__DepositInquiry(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns2__DepositInquiry * SOAP_FMAC4 soap_get_ns2__DepositInquiry(struct soap*, struct ns2__DepositInquiry *, const char*, const char*);

#ifndef SOAP_TYPE_ns2__DepositInquiryResponse
#define SOAP_TYPE_ns2__DepositInquiryResponse (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__DepositInquiryResponse(struct soap*, struct ns2__DepositInquiryResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__DepositInquiryResponse(struct soap*, const struct ns2__DepositInquiryResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__DepositInquiryResponse(struct soap*, const char*, int, const struct ns2__DepositInquiryResponse *, const char*);
SOAP_FMAC3 struct ns2__DepositInquiryResponse * SOAP_FMAC4 soap_in_ns2__DepositInquiryResponse(struct soap*, const char*, struct ns2__DepositInquiryResponse *, const char*);

#ifndef soap_write_ns2__DepositInquiryResponse
#define soap_write_ns2__DepositInquiryResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns2__DepositInquiryResponse(soap, data), 0) || soap_put_ns2__DepositInquiryResponse(soap, data, "ns2:DepositInquiryResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__DepositInquiryResponse(struct soap*, const struct ns2__DepositInquiryResponse *, const char*, const char*);

#ifndef soap_read_ns2__DepositInquiryResponse
#define soap_read_ns2__DepositInquiryResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__DepositInquiryResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns2__DepositInquiryResponse * SOAP_FMAC4 soap_get_ns2__DepositInquiryResponse(struct soap*, struct ns2__DepositInquiryResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ns2__WithdrawInit
#define SOAP_TYPE_ns2__WithdrawInit (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__WithdrawInit(struct soap*, struct ns2__WithdrawInit *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__WithdrawInit(struct soap*, const struct ns2__WithdrawInit *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__WithdrawInit(struct soap*, const char*, int, const struct ns2__WithdrawInit *, const char*);
SOAP_FMAC3 struct ns2__WithdrawInit * SOAP_FMAC4 soap_in_ns2__WithdrawInit(struct soap*, const char*, struct ns2__WithdrawInit *, const char*);

#ifndef soap_write_ns2__WithdrawInit
#define soap_write_ns2__WithdrawInit(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns2__WithdrawInit(soap, data), 0) || soap_put_ns2__WithdrawInit(soap, data, "ns2:WithdrawInit", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__WithdrawInit(struct soap*, const struct ns2__WithdrawInit *, const char*, const char*);

#ifndef soap_read_ns2__WithdrawInit
#define soap_read_ns2__WithdrawInit(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__WithdrawInit(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns2__WithdrawInit * SOAP_FMAC4 soap_get_ns2__WithdrawInit(struct soap*, struct ns2__WithdrawInit *, const char*, const char*);

#ifndef SOAP_TYPE_ns2__WithdrawInitResponse
#define SOAP_TYPE_ns2__WithdrawInitResponse (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__WithdrawInitResponse(struct soap*, struct ns2__WithdrawInitResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__WithdrawInitResponse(struct soap*, const struct ns2__WithdrawInitResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__WithdrawInitResponse(struct soap*, const char*, int, const struct ns2__WithdrawInitResponse *, const char*);
SOAP_FMAC3 struct ns2__WithdrawInitResponse * SOAP_FMAC4 soap_in_ns2__WithdrawInitResponse(struct soap*, const char*, struct ns2__WithdrawInitResponse *, const char*);

#ifndef soap_write_ns2__WithdrawInitResponse
#define soap_write_ns2__WithdrawInitResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns2__WithdrawInitResponse(soap, data), 0) || soap_put_ns2__WithdrawInitResponse(soap, data, "ns2:WithdrawInitResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__WithdrawInitResponse(struct soap*, const struct ns2__WithdrawInitResponse *, const char*, const char*);

#ifndef soap_read_ns2__WithdrawInitResponse
#define soap_read_ns2__WithdrawInitResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__WithdrawInitResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns2__WithdrawInitResponse * SOAP_FMAC4 soap_get_ns2__WithdrawInitResponse(struct soap*, struct ns2__WithdrawInitResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ns2__DepositIbonInit
#define SOAP_TYPE_ns2__DepositIbonInit (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__DepositIbonInit(struct soap*, struct ns2__DepositIbonInit *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__DepositIbonInit(struct soap*, const struct ns2__DepositIbonInit *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__DepositIbonInit(struct soap*, const char*, int, const struct ns2__DepositIbonInit *, const char*);
SOAP_FMAC3 struct ns2__DepositIbonInit * SOAP_FMAC4 soap_in_ns2__DepositIbonInit(struct soap*, const char*, struct ns2__DepositIbonInit *, const char*);

#ifndef soap_write_ns2__DepositIbonInit
#define soap_write_ns2__DepositIbonInit(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns2__DepositIbonInit(soap, data), 0) || soap_put_ns2__DepositIbonInit(soap, data, "ns2:DepositIbonInit", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__DepositIbonInit(struct soap*, const struct ns2__DepositIbonInit *, const char*, const char*);

#ifndef soap_read_ns2__DepositIbonInit
#define soap_read_ns2__DepositIbonInit(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__DepositIbonInit(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns2__DepositIbonInit * SOAP_FMAC4 soap_get_ns2__DepositIbonInit(struct soap*, struct ns2__DepositIbonInit *, const char*, const char*);

#ifndef SOAP_TYPE_ns2__DepositIbonInitResponse
#define SOAP_TYPE_ns2__DepositIbonInitResponse (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__DepositIbonInitResponse(struct soap*, struct ns2__DepositIbonInitResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__DepositIbonInitResponse(struct soap*, const struct ns2__DepositIbonInitResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__DepositIbonInitResponse(struct soap*, const char*, int, const struct ns2__DepositIbonInitResponse *, const char*);
SOAP_FMAC3 struct ns2__DepositIbonInitResponse * SOAP_FMAC4 soap_in_ns2__DepositIbonInitResponse(struct soap*, const char*, struct ns2__DepositIbonInitResponse *, const char*);

#ifndef soap_write_ns2__DepositIbonInitResponse
#define soap_write_ns2__DepositIbonInitResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns2__DepositIbonInitResponse(soap, data), 0) || soap_put_ns2__DepositIbonInitResponse(soap, data, "ns2:DepositIbonInitResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__DepositIbonInitResponse(struct soap*, const struct ns2__DepositIbonInitResponse *, const char*, const char*);

#ifndef soap_read_ns2__DepositIbonInitResponse
#define soap_read_ns2__DepositIbonInitResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__DepositIbonInitResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns2__DepositIbonInitResponse * SOAP_FMAC4 soap_get_ns2__DepositIbonInitResponse(struct soap*, struct ns2__DepositIbonInitResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ns2__DepositOnlineInit
#define SOAP_TYPE_ns2__DepositOnlineInit (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__DepositOnlineInit(struct soap*, struct ns2__DepositOnlineInit *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__DepositOnlineInit(struct soap*, const struct ns2__DepositOnlineInit *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__DepositOnlineInit(struct soap*, const char*, int, const struct ns2__DepositOnlineInit *, const char*);
SOAP_FMAC3 struct ns2__DepositOnlineInit * SOAP_FMAC4 soap_in_ns2__DepositOnlineInit(struct soap*, const char*, struct ns2__DepositOnlineInit *, const char*);

#ifndef soap_write_ns2__DepositOnlineInit
#define soap_write_ns2__DepositOnlineInit(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns2__DepositOnlineInit(soap, data), 0) || soap_put_ns2__DepositOnlineInit(soap, data, "ns2:DepositOnlineInit", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__DepositOnlineInit(struct soap*, const struct ns2__DepositOnlineInit *, const char*, const char*);

#ifndef soap_read_ns2__DepositOnlineInit
#define soap_read_ns2__DepositOnlineInit(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__DepositOnlineInit(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns2__DepositOnlineInit * SOAP_FMAC4 soap_get_ns2__DepositOnlineInit(struct soap*, struct ns2__DepositOnlineInit *, const char*, const char*);

#ifndef SOAP_TYPE_ns2__DepositOnlineInitResponse
#define SOAP_TYPE_ns2__DepositOnlineInitResponse (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__DepositOnlineInitResponse(struct soap*, struct ns2__DepositOnlineInitResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__DepositOnlineInitResponse(struct soap*, const struct ns2__DepositOnlineInitResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__DepositOnlineInitResponse(struct soap*, const char*, int, const struct ns2__DepositOnlineInitResponse *, const char*);
SOAP_FMAC3 struct ns2__DepositOnlineInitResponse * SOAP_FMAC4 soap_in_ns2__DepositOnlineInitResponse(struct soap*, const char*, struct ns2__DepositOnlineInitResponse *, const char*);

#ifndef soap_write_ns2__DepositOnlineInitResponse
#define soap_write_ns2__DepositOnlineInitResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns2__DepositOnlineInitResponse(soap, data), 0) || soap_put_ns2__DepositOnlineInitResponse(soap, data, "ns2:DepositOnlineInitResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__DepositOnlineInitResponse(struct soap*, const struct ns2__DepositOnlineInitResponse *, const char*, const char*);

#ifndef soap_read_ns2__DepositOnlineInitResponse
#define soap_read_ns2__DepositOnlineInitResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__DepositOnlineInitResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns2__DepositOnlineInitResponse * SOAP_FMAC4 soap_get_ns2__DepositOnlineInitResponse(struct soap*, struct ns2__DepositOnlineInitResponse *, const char*, const char*);

#ifndef SOAP_TYPE_WithdrawInitResultArray
#define SOAP_TYPE_WithdrawInitResultArray (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_WithdrawInitResultArray(struct soap*, struct WithdrawInitResultArray *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_WithdrawInitResultArray(struct soap*, struct WithdrawInitResultArray const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_WithdrawInitResultArray(struct soap*, const char*, int, const struct WithdrawInitResultArray *, const char*);
SOAP_FMAC3 struct WithdrawInitResultArray * SOAP_FMAC4 soap_in_WithdrawInitResultArray(struct soap*, const char*, struct WithdrawInitResultArray *, const char*);

#ifndef soap_write_WithdrawInitResultArray
#define soap_write_WithdrawInitResultArray(soap, data) ( soap_begin_send(soap) || (soap_serialize_WithdrawInitResultArray(soap, data), 0) || soap_put_WithdrawInitResultArray(soap, data, "SOAP-ENC:Array", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_WithdrawInitResultArray(struct soap*, const struct WithdrawInitResultArray *, const char*, const char*);

#ifndef soap_read_WithdrawInitResultArray
#define soap_read_WithdrawInitResultArray(soap, data) ( soap_begin_recv(soap) || !soap_get_WithdrawInitResultArray(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct WithdrawInitResultArray * SOAP_FMAC4 soap_get_WithdrawInitResultArray(struct soap*, struct WithdrawInitResultArray *, const char*, const char*);

#ifndef SOAP_TYPE_WithdrawInitInfoArray
#define SOAP_TYPE_WithdrawInitInfoArray (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_WithdrawInitInfoArray(struct soap*, struct WithdrawInitInfoArray *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_WithdrawInitInfoArray(struct soap*, struct WithdrawInitInfoArray const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_WithdrawInitInfoArray(struct soap*, const char*, int, const struct WithdrawInitInfoArray *, const char*);
SOAP_FMAC3 struct WithdrawInitInfoArray * SOAP_FMAC4 soap_in_WithdrawInitInfoArray(struct soap*, const char*, struct WithdrawInitInfoArray *, const char*);

#ifndef soap_write_WithdrawInitInfoArray
#define soap_write_WithdrawInitInfoArray(soap, data) ( soap_begin_send(soap) || (soap_serialize_WithdrawInitInfoArray(soap, data), 0) || soap_put_WithdrawInitInfoArray(soap, data, "SOAP-ENC:Array", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_WithdrawInitInfoArray(struct soap*, const struct WithdrawInitInfoArray *, const char*, const char*);

#ifndef soap_read_WithdrawInitInfoArray
#define soap_read_WithdrawInitInfoArray(soap, data) ( soap_begin_recv(soap) || !soap_get_WithdrawInitInfoArray(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct WithdrawInitInfoArray * SOAP_FMAC4 soap_get_WithdrawInitInfoArray(struct soap*, struct WithdrawInitInfoArray *, const char*, const char*);

#ifndef SOAP_TYPE_WithdrawTypeArray
#define SOAP_TYPE_WithdrawTypeArray (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_WithdrawTypeArray(struct soap*, struct WithdrawTypeArray *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_WithdrawTypeArray(struct soap*, struct WithdrawTypeArray const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_WithdrawTypeArray(struct soap*, const char*, int, const struct WithdrawTypeArray *, const char*);
SOAP_FMAC3 struct WithdrawTypeArray * SOAP_FMAC4 soap_in_WithdrawTypeArray(struct soap*, const char*, struct WithdrawTypeArray *, const char*);

#ifndef soap_write_WithdrawTypeArray
#define soap_write_WithdrawTypeArray(soap, data) ( soap_begin_send(soap) || (soap_serialize_WithdrawTypeArray(soap, data), 0) || soap_put_WithdrawTypeArray(soap, data, "SOAP-ENC:Array", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_WithdrawTypeArray(struct soap*, const struct WithdrawTypeArray *, const char*, const char*);

#ifndef soap_read_WithdrawTypeArray
#define soap_read_WithdrawTypeArray(soap, data) ( soap_begin_recv(soap) || !soap_get_WithdrawTypeArray(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct WithdrawTypeArray * SOAP_FMAC4 soap_get_WithdrawTypeArray(struct soap*, struct WithdrawTypeArray *, const char*, const char*);

#ifndef SOAP_TYPE_DepositTypeArray
#define SOAP_TYPE_DepositTypeArray (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_DepositTypeArray(struct soap*, struct DepositTypeArray *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_DepositTypeArray(struct soap*, struct DepositTypeArray const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_DepositTypeArray(struct soap*, const char*, int, const struct DepositTypeArray *, const char*);
SOAP_FMAC3 struct DepositTypeArray * SOAP_FMAC4 soap_in_DepositTypeArray(struct soap*, const char*, struct DepositTypeArray *, const char*);

#ifndef soap_write_DepositTypeArray
#define soap_write_DepositTypeArray(soap, data) ( soap_begin_send(soap) || (soap_serialize_DepositTypeArray(soap, data), 0) || soap_put_DepositTypeArray(soap, data, "SOAP-ENC:Array", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_DepositTypeArray(struct soap*, const struct DepositTypeArray *, const char*, const char*);

#ifndef soap_read_DepositTypeArray
#define soap_read_DepositTypeArray(soap, data) ( soap_begin_recv(soap) || !soap_get_DepositTypeArray(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct DepositTypeArray * SOAP_FMAC4 soap_get_DepositTypeArray(struct soap*, struct DepositTypeArray *, const char*, const char*);

#ifndef SOAP_TYPE_ns1__WithdrawInitResult
#define SOAP_TYPE_ns1__WithdrawInitResult (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__WithdrawInitResult(struct soap*, struct ns1__WithdrawInitResult *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__WithdrawInitResult(struct soap*, const struct ns1__WithdrawInitResult *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__WithdrawInitResult(struct soap*, const char*, int, const struct ns1__WithdrawInitResult *, const char*);
SOAP_FMAC3 struct ns1__WithdrawInitResult * SOAP_FMAC4 soap_in_ns1__WithdrawInitResult(struct soap*, const char*, struct ns1__WithdrawInitResult *, const char*);

#ifndef soap_write_ns1__WithdrawInitResult
#define soap_write_ns1__WithdrawInitResult(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns1__WithdrawInitResult(soap, data), 0) || soap_put_ns1__WithdrawInitResult(soap, data, "ns1:WithdrawInitResult", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__WithdrawInitResult(struct soap*, const struct ns1__WithdrawInitResult *, const char*, const char*);

#ifndef soap_read_ns1__WithdrawInitResult
#define soap_read_ns1__WithdrawInitResult(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__WithdrawInitResult(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__WithdrawInitResult * SOAP_FMAC4 soap_get_ns1__WithdrawInitResult(struct soap*, struct ns1__WithdrawInitResult *, const char*, const char*);

#ifndef SOAP_TYPE_ns1__WithdrawInitInfo
#define SOAP_TYPE_ns1__WithdrawInitInfo (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__WithdrawInitInfo(struct soap*, struct ns1__WithdrawInitInfo *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__WithdrawInitInfo(struct soap*, const struct ns1__WithdrawInitInfo *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__WithdrawInitInfo(struct soap*, const char*, int, const struct ns1__WithdrawInitInfo *, const char*);
SOAP_FMAC3 struct ns1__WithdrawInitInfo * SOAP_FMAC4 soap_in_ns1__WithdrawInitInfo(struct soap*, const char*, struct ns1__WithdrawInitInfo *, const char*);

#ifndef soap_write_ns1__WithdrawInitInfo
#define soap_write_ns1__WithdrawInitInfo(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns1__WithdrawInitInfo(soap, data), 0) || soap_put_ns1__WithdrawInitInfo(soap, data, "ns1:WithdrawInitInfo", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__WithdrawInitInfo(struct soap*, const struct ns1__WithdrawInitInfo *, const char*, const char*);

#ifndef soap_read_ns1__WithdrawInitInfo
#define soap_read_ns1__WithdrawInitInfo(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__WithdrawInitInfo(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__WithdrawInitInfo * SOAP_FMAC4 soap_get_ns1__WithdrawInitInfo(struct soap*, struct ns1__WithdrawInitInfo *, const char*, const char*);

#ifndef SOAP_TYPE_ns1__WithdrawType
#define SOAP_TYPE_ns1__WithdrawType (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__WithdrawType(struct soap*, struct ns1__WithdrawType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__WithdrawType(struct soap*, const struct ns1__WithdrawType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__WithdrawType(struct soap*, const char*, int, const struct ns1__WithdrawType *, const char*);
SOAP_FMAC3 struct ns1__WithdrawType * SOAP_FMAC4 soap_in_ns1__WithdrawType(struct soap*, const char*, struct ns1__WithdrawType *, const char*);

#ifndef soap_write_ns1__WithdrawType
#define soap_write_ns1__WithdrawType(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns1__WithdrawType(soap, data), 0) || soap_put_ns1__WithdrawType(soap, data, "ns1:WithdrawType", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__WithdrawType(struct soap*, const struct ns1__WithdrawType *, const char*, const char*);

#ifndef soap_read_ns1__WithdrawType
#define soap_read_ns1__WithdrawType(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__WithdrawType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__WithdrawType * SOAP_FMAC4 soap_get_ns1__WithdrawType(struct soap*, struct ns1__WithdrawType *, const char*, const char*);

#ifndef SOAP_TYPE_ns1__DepositType
#define SOAP_TYPE_ns1__DepositType (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__DepositType(struct soap*, struct ns1__DepositType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__DepositType(struct soap*, const struct ns1__DepositType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__DepositType(struct soap*, const char*, int, const struct ns1__DepositType *, const char*);
SOAP_FMAC3 struct ns1__DepositType * SOAP_FMAC4 soap_in_ns1__DepositType(struct soap*, const char*, struct ns1__DepositType *, const char*);

#ifndef soap_write_ns1__DepositType
#define soap_write_ns1__DepositType(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns1__DepositType(soap, data), 0) || soap_put_ns1__DepositType(soap, data, "ns1:DepositType", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__DepositType(struct soap*, const struct ns1__DepositType *, const char*, const char*);

#ifndef soap_read_ns1__DepositType
#define soap_read_ns1__DepositType(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__DepositType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__DepositType * SOAP_FMAC4 soap_get_ns1__DepositType(struct soap*, struct ns1__DepositType *, const char*, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (60)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data), 0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (59)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data), 0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data), 0) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#endif

#ifndef SOAP_TYPE_PointerTons2__WithdrawInquiryResponse
#define SOAP_TYPE_PointerTons2__WithdrawInquiryResponse (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__WithdrawInquiryResponse(struct soap*, struct ns2__WithdrawInquiryResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__WithdrawInquiryResponse(struct soap*, const char *, int, struct ns2__WithdrawInquiryResponse *const*, const char *);
SOAP_FMAC3 struct ns2__WithdrawInquiryResponse ** SOAP_FMAC4 soap_in_PointerTons2__WithdrawInquiryResponse(struct soap*, const char*, struct ns2__WithdrawInquiryResponse **, const char*);

#ifndef soap_write_PointerTons2__WithdrawInquiryResponse
#define soap_write_PointerTons2__WithdrawInquiryResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons2__WithdrawInquiryResponse(soap, data), 0) || soap_put_PointerTons2__WithdrawInquiryResponse(soap, data, "ns2:WithdrawInquiryResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__WithdrawInquiryResponse(struct soap*, struct ns2__WithdrawInquiryResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTons2__WithdrawInquiryResponse
#define soap_read_PointerTons2__WithdrawInquiryResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__WithdrawInquiryResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns2__WithdrawInquiryResponse ** SOAP_FMAC4 soap_get_PointerTons2__WithdrawInquiryResponse(struct soap*, struct ns2__WithdrawInquiryResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons2__DepositInquiryResponse
#define SOAP_TYPE_PointerTons2__DepositInquiryResponse (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__DepositInquiryResponse(struct soap*, struct ns2__DepositInquiryResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__DepositInquiryResponse(struct soap*, const char *, int, struct ns2__DepositInquiryResponse *const*, const char *);
SOAP_FMAC3 struct ns2__DepositInquiryResponse ** SOAP_FMAC4 soap_in_PointerTons2__DepositInquiryResponse(struct soap*, const char*, struct ns2__DepositInquiryResponse **, const char*);

#ifndef soap_write_PointerTons2__DepositInquiryResponse
#define soap_write_PointerTons2__DepositInquiryResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons2__DepositInquiryResponse(soap, data), 0) || soap_put_PointerTons2__DepositInquiryResponse(soap, data, "ns2:DepositInquiryResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__DepositInquiryResponse(struct soap*, struct ns2__DepositInquiryResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTons2__DepositInquiryResponse
#define soap_read_PointerTons2__DepositInquiryResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__DepositInquiryResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns2__DepositInquiryResponse ** SOAP_FMAC4 soap_get_PointerTons2__DepositInquiryResponse(struct soap*, struct ns2__DepositInquiryResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons2__WithdrawInitResponse
#define SOAP_TYPE_PointerTons2__WithdrawInitResponse (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__WithdrawInitResponse(struct soap*, struct ns2__WithdrawInitResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__WithdrawInitResponse(struct soap*, const char *, int, struct ns2__WithdrawInitResponse *const*, const char *);
SOAP_FMAC3 struct ns2__WithdrawInitResponse ** SOAP_FMAC4 soap_in_PointerTons2__WithdrawInitResponse(struct soap*, const char*, struct ns2__WithdrawInitResponse **, const char*);

#ifndef soap_write_PointerTons2__WithdrawInitResponse
#define soap_write_PointerTons2__WithdrawInitResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons2__WithdrawInitResponse(soap, data), 0) || soap_put_PointerTons2__WithdrawInitResponse(soap, data, "ns2:WithdrawInitResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__WithdrawInitResponse(struct soap*, struct ns2__WithdrawInitResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTons2__WithdrawInitResponse
#define soap_read_PointerTons2__WithdrawInitResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__WithdrawInitResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns2__WithdrawInitResponse ** SOAP_FMAC4 soap_get_PointerTons2__WithdrawInitResponse(struct soap*, struct ns2__WithdrawInitResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerToWithdrawInitInfoArray
#define SOAP_TYPE_PointerToWithdrawInitInfoArray (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToWithdrawInitInfoArray(struct soap*, struct WithdrawInitInfoArray *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToWithdrawInitInfoArray(struct soap*, const char *, int, struct WithdrawInitInfoArray *const*, const char *);
SOAP_FMAC3 struct WithdrawInitInfoArray ** SOAP_FMAC4 soap_in_PointerToWithdrawInitInfoArray(struct soap*, const char*, struct WithdrawInitInfoArray **, const char*);

#ifndef soap_write_PointerToWithdrawInitInfoArray
#define soap_write_PointerToWithdrawInitInfoArray(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToWithdrawInitInfoArray(soap, data), 0) || soap_put_PointerToWithdrawInitInfoArray(soap, data, "SOAP-ENC:Array", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToWithdrawInitInfoArray(struct soap*, struct WithdrawInitInfoArray *const*, const char*, const char*);

#ifndef soap_read_PointerToWithdrawInitInfoArray
#define soap_read_PointerToWithdrawInitInfoArray(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToWithdrawInitInfoArray(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct WithdrawInitInfoArray ** SOAP_FMAC4 soap_get_PointerToWithdrawInitInfoArray(struct soap*, struct WithdrawInitInfoArray **, const char*, const char*);

#ifndef SOAP_TYPE_PointerToWithdrawInitResultArray
#define SOAP_TYPE_PointerToWithdrawInitResultArray (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToWithdrawInitResultArray(struct soap*, struct WithdrawInitResultArray *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToWithdrawInitResultArray(struct soap*, const char *, int, struct WithdrawInitResultArray *const*, const char *);
SOAP_FMAC3 struct WithdrawInitResultArray ** SOAP_FMAC4 soap_in_PointerToWithdrawInitResultArray(struct soap*, const char*, struct WithdrawInitResultArray **, const char*);

#ifndef soap_write_PointerToWithdrawInitResultArray
#define soap_write_PointerToWithdrawInitResultArray(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToWithdrawInitResultArray(soap, data), 0) || soap_put_PointerToWithdrawInitResultArray(soap, data, "SOAP-ENC:Array", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToWithdrawInitResultArray(struct soap*, struct WithdrawInitResultArray *const*, const char*, const char*);

#ifndef soap_read_PointerToWithdrawInitResultArray
#define soap_read_PointerToWithdrawInitResultArray(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToWithdrawInitResultArray(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct WithdrawInitResultArray ** SOAP_FMAC4 soap_get_PointerToWithdrawInitResultArray(struct soap*, struct WithdrawInitResultArray **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons2__DepositIbonInitResponse
#define SOAP_TYPE_PointerTons2__DepositIbonInitResponse (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__DepositIbonInitResponse(struct soap*, struct ns2__DepositIbonInitResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__DepositIbonInitResponse(struct soap*, const char *, int, struct ns2__DepositIbonInitResponse *const*, const char *);
SOAP_FMAC3 struct ns2__DepositIbonInitResponse ** SOAP_FMAC4 soap_in_PointerTons2__DepositIbonInitResponse(struct soap*, const char*, struct ns2__DepositIbonInitResponse **, const char*);

#ifndef soap_write_PointerTons2__DepositIbonInitResponse
#define soap_write_PointerTons2__DepositIbonInitResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons2__DepositIbonInitResponse(soap, data), 0) || soap_put_PointerTons2__DepositIbonInitResponse(soap, data, "ns2:DepositIbonInitResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__DepositIbonInitResponse(struct soap*, struct ns2__DepositIbonInitResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTons2__DepositIbonInitResponse
#define soap_read_PointerTons2__DepositIbonInitResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__DepositIbonInitResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns2__DepositIbonInitResponse ** SOAP_FMAC4 soap_get_PointerTons2__DepositIbonInitResponse(struct soap*, struct ns2__DepositIbonInitResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons2__DepositOnlineInitResponse
#define SOAP_TYPE_PointerTons2__DepositOnlineInitResponse (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__DepositOnlineInitResponse(struct soap*, struct ns2__DepositOnlineInitResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__DepositOnlineInitResponse(struct soap*, const char *, int, struct ns2__DepositOnlineInitResponse *const*, const char *);
SOAP_FMAC3 struct ns2__DepositOnlineInitResponse ** SOAP_FMAC4 soap_in_PointerTons2__DepositOnlineInitResponse(struct soap*, const char*, struct ns2__DepositOnlineInitResponse **, const char*);

#ifndef soap_write_PointerTons2__DepositOnlineInitResponse
#define soap_write_PointerTons2__DepositOnlineInitResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons2__DepositOnlineInitResponse(soap, data), 0) || soap_put_PointerTons2__DepositOnlineInitResponse(soap, data, "ns2:DepositOnlineInitResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__DepositOnlineInitResponse(struct soap*, struct ns2__DepositOnlineInitResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTons2__DepositOnlineInitResponse
#define soap_read_PointerTons2__DepositOnlineInitResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__DepositOnlineInitResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns2__DepositOnlineInitResponse ** SOAP_FMAC4 soap_get_PointerTons2__DepositOnlineInitResponse(struct soap*, struct ns2__DepositOnlineInitResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerToPointerTons1__WithdrawInitResult
#define SOAP_TYPE_PointerToPointerTons1__WithdrawInitResult (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToPointerTons1__WithdrawInitResult(struct soap*, struct ns1__WithdrawInitResult **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToPointerTons1__WithdrawInitResult(struct soap*, const char *, int, struct ns1__WithdrawInitResult **const*, const char *);
SOAP_FMAC3 struct ns1__WithdrawInitResult *** SOAP_FMAC4 soap_in_PointerToPointerTons1__WithdrawInitResult(struct soap*, const char*, struct ns1__WithdrawInitResult ***, const char*);

#ifndef soap_write_PointerToPointerTons1__WithdrawInitResult
#define soap_write_PointerToPointerTons1__WithdrawInitResult(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToPointerTons1__WithdrawInitResult(soap, data), 0) || soap_put_PointerToPointerTons1__WithdrawInitResult(soap, data, "ns1:WithdrawInitResult", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToPointerTons1__WithdrawInitResult(struct soap*, struct ns1__WithdrawInitResult **const*, const char*, const char*);

#ifndef soap_read_PointerToPointerTons1__WithdrawInitResult
#define soap_read_PointerToPointerTons1__WithdrawInitResult(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToPointerTons1__WithdrawInitResult(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__WithdrawInitResult *** SOAP_FMAC4 soap_get_PointerToPointerTons1__WithdrawInitResult(struct soap*, struct ns1__WithdrawInitResult ***, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons1__WithdrawInitResult
#define SOAP_TYPE_PointerTons1__WithdrawInitResult (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__WithdrawInitResult(struct soap*, struct ns1__WithdrawInitResult *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__WithdrawInitResult(struct soap*, const char *, int, struct ns1__WithdrawInitResult *const*, const char *);
SOAP_FMAC3 struct ns1__WithdrawInitResult ** SOAP_FMAC4 soap_in_PointerTons1__WithdrawInitResult(struct soap*, const char*, struct ns1__WithdrawInitResult **, const char*);

#ifndef soap_write_PointerTons1__WithdrawInitResult
#define soap_write_PointerTons1__WithdrawInitResult(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons1__WithdrawInitResult(soap, data), 0) || soap_put_PointerTons1__WithdrawInitResult(soap, data, "ns1:WithdrawInitResult", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__WithdrawInitResult(struct soap*, struct ns1__WithdrawInitResult *const*, const char*, const char*);

#ifndef soap_read_PointerTons1__WithdrawInitResult
#define soap_read_PointerTons1__WithdrawInitResult(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__WithdrawInitResult(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__WithdrawInitResult ** SOAP_FMAC4 soap_get_PointerTons1__WithdrawInitResult(struct soap*, struct ns1__WithdrawInitResult **, const char*, const char*);

#ifndef SOAP_TYPE_PointerToPointerTons1__WithdrawInitInfo
#define SOAP_TYPE_PointerToPointerTons1__WithdrawInitInfo (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToPointerTons1__WithdrawInitInfo(struct soap*, struct ns1__WithdrawInitInfo **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToPointerTons1__WithdrawInitInfo(struct soap*, const char *, int, struct ns1__WithdrawInitInfo **const*, const char *);
SOAP_FMAC3 struct ns1__WithdrawInitInfo *** SOAP_FMAC4 soap_in_PointerToPointerTons1__WithdrawInitInfo(struct soap*, const char*, struct ns1__WithdrawInitInfo ***, const char*);

#ifndef soap_write_PointerToPointerTons1__WithdrawInitInfo
#define soap_write_PointerToPointerTons1__WithdrawInitInfo(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToPointerTons1__WithdrawInitInfo(soap, data), 0) || soap_put_PointerToPointerTons1__WithdrawInitInfo(soap, data, "ns1:WithdrawInitInfo", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToPointerTons1__WithdrawInitInfo(struct soap*, struct ns1__WithdrawInitInfo **const*, const char*, const char*);

#ifndef soap_read_PointerToPointerTons1__WithdrawInitInfo
#define soap_read_PointerToPointerTons1__WithdrawInitInfo(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToPointerTons1__WithdrawInitInfo(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__WithdrawInitInfo *** SOAP_FMAC4 soap_get_PointerToPointerTons1__WithdrawInitInfo(struct soap*, struct ns1__WithdrawInitInfo ***, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons1__WithdrawInitInfo
#define SOAP_TYPE_PointerTons1__WithdrawInitInfo (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__WithdrawInitInfo(struct soap*, struct ns1__WithdrawInitInfo *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__WithdrawInitInfo(struct soap*, const char *, int, struct ns1__WithdrawInitInfo *const*, const char *);
SOAP_FMAC3 struct ns1__WithdrawInitInfo ** SOAP_FMAC4 soap_in_PointerTons1__WithdrawInitInfo(struct soap*, const char*, struct ns1__WithdrawInitInfo **, const char*);

#ifndef soap_write_PointerTons1__WithdrawInitInfo
#define soap_write_PointerTons1__WithdrawInitInfo(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons1__WithdrawInitInfo(soap, data), 0) || soap_put_PointerTons1__WithdrawInitInfo(soap, data, "ns1:WithdrawInitInfo", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__WithdrawInitInfo(struct soap*, struct ns1__WithdrawInitInfo *const*, const char*, const char*);

#ifndef soap_read_PointerTons1__WithdrawInitInfo
#define soap_read_PointerTons1__WithdrawInitInfo(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__WithdrawInitInfo(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__WithdrawInitInfo ** SOAP_FMAC4 soap_get_PointerTons1__WithdrawInitInfo(struct soap*, struct ns1__WithdrawInitInfo **, const char*, const char*);

#ifndef SOAP_TYPE_PointerToPointerTons1__WithdrawType
#define SOAP_TYPE_PointerToPointerTons1__WithdrawType (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToPointerTons1__WithdrawType(struct soap*, struct ns1__WithdrawType **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToPointerTons1__WithdrawType(struct soap*, const char *, int, struct ns1__WithdrawType **const*, const char *);
SOAP_FMAC3 struct ns1__WithdrawType *** SOAP_FMAC4 soap_in_PointerToPointerTons1__WithdrawType(struct soap*, const char*, struct ns1__WithdrawType ***, const char*);

#ifndef soap_write_PointerToPointerTons1__WithdrawType
#define soap_write_PointerToPointerTons1__WithdrawType(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToPointerTons1__WithdrawType(soap, data), 0) || soap_put_PointerToPointerTons1__WithdrawType(soap, data, "ns1:WithdrawType", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToPointerTons1__WithdrawType(struct soap*, struct ns1__WithdrawType **const*, const char*, const char*);

#ifndef soap_read_PointerToPointerTons1__WithdrawType
#define soap_read_PointerToPointerTons1__WithdrawType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToPointerTons1__WithdrawType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__WithdrawType *** SOAP_FMAC4 soap_get_PointerToPointerTons1__WithdrawType(struct soap*, struct ns1__WithdrawType ***, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons1__WithdrawType
#define SOAP_TYPE_PointerTons1__WithdrawType (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__WithdrawType(struct soap*, struct ns1__WithdrawType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__WithdrawType(struct soap*, const char *, int, struct ns1__WithdrawType *const*, const char *);
SOAP_FMAC3 struct ns1__WithdrawType ** SOAP_FMAC4 soap_in_PointerTons1__WithdrawType(struct soap*, const char*, struct ns1__WithdrawType **, const char*);

#ifndef soap_write_PointerTons1__WithdrawType
#define soap_write_PointerTons1__WithdrawType(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons1__WithdrawType(soap, data), 0) || soap_put_PointerTons1__WithdrawType(soap, data, "ns1:WithdrawType", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__WithdrawType(struct soap*, struct ns1__WithdrawType *const*, const char*, const char*);

#ifndef soap_read_PointerTons1__WithdrawType
#define soap_read_PointerTons1__WithdrawType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__WithdrawType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__WithdrawType ** SOAP_FMAC4 soap_get_PointerTons1__WithdrawType(struct soap*, struct ns1__WithdrawType **, const char*, const char*);

#ifndef SOAP_TYPE_PointerToPointerTons1__DepositType
#define SOAP_TYPE_PointerToPointerTons1__DepositType (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToPointerTons1__DepositType(struct soap*, struct ns1__DepositType **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToPointerTons1__DepositType(struct soap*, const char *, int, struct ns1__DepositType **const*, const char *);
SOAP_FMAC3 struct ns1__DepositType *** SOAP_FMAC4 soap_in_PointerToPointerTons1__DepositType(struct soap*, const char*, struct ns1__DepositType ***, const char*);

#ifndef soap_write_PointerToPointerTons1__DepositType
#define soap_write_PointerToPointerTons1__DepositType(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToPointerTons1__DepositType(soap, data), 0) || soap_put_PointerToPointerTons1__DepositType(soap, data, "ns1:DepositType", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToPointerTons1__DepositType(struct soap*, struct ns1__DepositType **const*, const char*, const char*);

#ifndef soap_read_PointerToPointerTons1__DepositType
#define soap_read_PointerToPointerTons1__DepositType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToPointerTons1__DepositType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__DepositType *** SOAP_FMAC4 soap_get_PointerToPointerTons1__DepositType(struct soap*, struct ns1__DepositType ***, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons1__DepositType
#define SOAP_TYPE_PointerTons1__DepositType (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__DepositType(struct soap*, struct ns1__DepositType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__DepositType(struct soap*, const char *, int, struct ns1__DepositType *const*, const char *);
SOAP_FMAC3 struct ns1__DepositType ** SOAP_FMAC4 soap_in_PointerTons1__DepositType(struct soap*, const char*, struct ns1__DepositType **, const char*);

#ifndef soap_write_PointerTons1__DepositType
#define soap_write_PointerTons1__DepositType(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons1__DepositType(soap, data), 0) || soap_put_PointerTons1__DepositType(soap, data, "ns1:DepositType", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__DepositType(struct soap*, struct ns1__DepositType *const*, const char*, const char*);

#ifndef soap_read_PointerTons1__DepositType
#define soap_read_PointerTons1__DepositType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__DepositType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__DepositType ** SOAP_FMAC4 soap_get_PointerTons1__DepositType(struct soap*, struct ns1__DepositType **, const char*, const char*);

#ifndef SOAP_TYPE_PointerToint
#define SOAP_TYPE_PointerToint (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToint(struct soap*, int *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToint(struct soap*, const char *, int, int *const*, const char *);
SOAP_FMAC3 int ** SOAP_FMAC4 soap_in_PointerToint(struct soap*, const char*, int **, const char*);

#ifndef soap_write_PointerToint
#define soap_write_PointerToint(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToint(soap, data), 0) || soap_put_PointerToint(soap, data, "int", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToint(struct soap*, int *const*, const char*, const char*);

#ifndef soap_read_PointerToint
#define soap_read_PointerToint(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToint(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 int ** SOAP_FMAC4 soap_get_PointerToint(struct soap*, int **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTotime
#define SOAP_TYPE_PointerTotime (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotime(struct soap*, time_t *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotime(struct soap*, const char *, int, time_t *const*, const char *);
SOAP_FMAC3 time_t ** SOAP_FMAC4 soap_in_PointerTotime(struct soap*, const char*, time_t **, const char*);

#ifndef soap_write_PointerTotime
#define soap_write_PointerTotime(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTotime(soap, data), 0) || soap_put_PointerTotime(soap, data, "dateTime", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotime(struct soap*, time_t *const*, const char*, const char*);

#ifndef soap_read_PointerTotime
#define soap_read_PointerTotime(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTotime(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 time_t ** SOAP_FMAC4 soap_get_PointerTotime(struct soap*, time_t **, const char*, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)


#define soap_serialize__QName(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_begin_send(soap) || (soap_serialize__QName(soap, data), 0) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_begin_send(soap) || (soap_serialize_string(soap, data), 0) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapH.h */
