/* soapServer.c
   Generated by gSOAP 2.8.0 from twv.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   The generated code is released under one of the following licenses:
   GPL OR Genivia's license for commercial use.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapServer.c ver 2.8.0 2011-03-04 02:11:35 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif

	do
	{
#ifdef WITH_FASTCGI
		if (FCGI_Accept() < 0)
		{
			soap->error = SOAP_EOF;
			return soap_send_fault(soap);
		}
#endif

		soap_begin(soap);

#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif

		if (soap_begin_recv(soap))
		{	if (soap->error < SOAP_STOP)
			{
#ifdef WITH_FASTCGI
				soap_send_fault(soap);
#else 
				return soap_send_fault(soap);
#endif
			}
			soap_closesock(soap);

			continue;
		}

		if (soap_envelope_begin_in(soap)
		 || soap_recv_header(soap)
		 || soap_body_begin_in(soap)
		 || soap_serve_request(soap)
		 || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "ns2:DepositOnlineInit"))
		return soap_serve_ns2__DepositOnlineInit(soap);
	if (!soap_match_tag(soap, soap->tag, "ns2:DepositIbonInit"))
		return soap_serve_ns2__DepositIbonInit(soap);
	if (!soap_match_tag(soap, soap->tag, "ns2:WithdrawInit"))
		return soap_serve_ns2__WithdrawInit(soap);
	if (!soap_match_tag(soap, soap->tag, "ns2:DepositInquiry"))
		return soap_serve_ns2__DepositInquiry(soap);
	if (!soap_match_tag(soap, soap->tag, "ns2:WithdrawInquiry"))
		return soap_serve_ns2__WithdrawInquiry(soap);
	if (!soap_match_tag(soap, soap->tag, "ns2:PingAlive"))
		return soap_serve_ns2__PingAlive(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__DepositOnlineInit(struct soap *soap)
{	struct ns2__DepositOnlineInit soap_tmp_ns2__DepositOnlineInit;
	struct ns2__DepositOnlineInitResponse _param_1;
	soap_default_ns2__DepositOnlineInitResponse(soap, &_param_1);
	soap_default_ns2__DepositOnlineInit(soap, &soap_tmp_ns2__DepositOnlineInit);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns2__DepositOnlineInit(soap, &soap_tmp_ns2__DepositOnlineInit, "ns2:DepositOnlineInit", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns2__DepositOnlineInit(soap, soap_tmp_ns2__DepositOnlineInit.access_USCOREkey, soap_tmp_ns2__DepositOnlineInit.order_USCOREnum, soap_tmp_ns2__DepositOnlineInit.amount, soap_tmp_ns2__DepositOnlineInit.description, soap_tmp_ns2__DepositOnlineInit.return_USCOREurl, &_param_1);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns2__DepositOnlineInitResponse(soap, &_param_1);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__DepositOnlineInitResponse(soap, &_param_1, "ns2:DepositOnlineInitResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__DepositOnlineInitResponse(soap, &_param_1, "ns2:DepositOnlineInitResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__DepositIbonInit(struct soap *soap)
{	struct ns2__DepositIbonInit soap_tmp_ns2__DepositIbonInit;
	struct ns2__DepositIbonInitResponse _param_2;
	soap_default_ns2__DepositIbonInitResponse(soap, &_param_2);
	soap_default_ns2__DepositIbonInit(soap, &soap_tmp_ns2__DepositIbonInit);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns2__DepositIbonInit(soap, &soap_tmp_ns2__DepositIbonInit, "ns2:DepositIbonInit", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns2__DepositIbonInit(soap, soap_tmp_ns2__DepositIbonInit.access_USCOREkey, soap_tmp_ns2__DepositIbonInit.order_USCOREnum, soap_tmp_ns2__DepositIbonInit.owner_USCOREid, soap_tmp_ns2__DepositIbonInit.amount, soap_tmp_ns2__DepositIbonInit.description, &_param_2);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns2__DepositIbonInitResponse(soap, &_param_2);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__DepositIbonInitResponse(soap, &_param_2, "ns2:DepositIbonInitResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__DepositIbonInitResponse(soap, &_param_2, "ns2:DepositIbonInitResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__WithdrawInit(struct soap *soap)
{	struct ns2__WithdrawInit soap_tmp_ns2__WithdrawInit;
	struct ns2__WithdrawInitResponse _param_3;
	soap_default_ns2__WithdrawInitResponse(soap, &_param_3);
	soap_default_ns2__WithdrawInit(soap, &soap_tmp_ns2__WithdrawInit);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns2__WithdrawInit(soap, &soap_tmp_ns2__WithdrawInit, "ns2:WithdrawInit", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns2__WithdrawInit(soap, soap_tmp_ns2__WithdrawInit.access_USCOREkey, soap_tmp_ns2__WithdrawInit.withdraw_USCORElist, &_param_3);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns2__WithdrawInitResponse(soap, &_param_3);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__WithdrawInitResponse(soap, &_param_3, "ns2:WithdrawInitResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__WithdrawInitResponse(soap, &_param_3, "ns2:WithdrawInitResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__DepositInquiry(struct soap *soap)
{	struct ns2__DepositInquiry soap_tmp_ns2__DepositInquiry;
	struct ns2__DepositInquiryResponse _param_4;
	soap_default_ns2__DepositInquiryResponse(soap, &_param_4);
	soap_default_ns2__DepositInquiry(soap, &soap_tmp_ns2__DepositInquiry);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns2__DepositInquiry(soap, &soap_tmp_ns2__DepositInquiry, "ns2:DepositInquiry", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns2__DepositInquiry(soap, soap_tmp_ns2__DepositInquiry.access_USCOREkey, soap_tmp_ns2__DepositInquiry.tid, &_param_4);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns2__DepositInquiryResponse(soap, &_param_4);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__DepositInquiryResponse(soap, &_param_4, "ns2:DepositInquiryResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__DepositInquiryResponse(soap, &_param_4, "ns2:DepositInquiryResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__WithdrawInquiry(struct soap *soap)
{	struct ns2__WithdrawInquiry soap_tmp_ns2__WithdrawInquiry;
	struct ns2__WithdrawInquiryResponse _param_5;
	soap_default_ns2__WithdrawInquiryResponse(soap, &_param_5);
	soap_default_ns2__WithdrawInquiry(soap, &soap_tmp_ns2__WithdrawInquiry);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns2__WithdrawInquiry(soap, &soap_tmp_ns2__WithdrawInquiry, "ns2:WithdrawInquiry", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns2__WithdrawInquiry(soap, soap_tmp_ns2__WithdrawInquiry.access_USCOREkey, soap_tmp_ns2__WithdrawInquiry.tid, &_param_5);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns2__WithdrawInquiryResponse(soap, &_param_5);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__WithdrawInquiryResponse(soap, &_param_5, "ns2:WithdrawInquiryResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__WithdrawInquiryResponse(soap, &_param_5, "ns2:WithdrawInquiryResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__PingAlive(struct soap *soap)
{	struct ns2__PingAlive soap_tmp_ns2__PingAlive;
	struct ns2__PingAliveResponse soap_tmp_ns2__PingAliveResponse;
	int soap_tmp_int;
	soap_default_ns2__PingAliveResponse(soap, &soap_tmp_ns2__PingAliveResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns2__PingAliveResponse.status = &soap_tmp_int;
	soap_default_ns2__PingAlive(soap, &soap_tmp_ns2__PingAlive);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns2__PingAlive(soap, &soap_tmp_ns2__PingAlive, "ns2:PingAlive", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns2__PingAlive(soap, soap_tmp_ns2__PingAlive.access_USCOREkey, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns2__PingAliveResponse(soap, &soap_tmp_ns2__PingAliveResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__PingAliveResponse(soap, &soap_tmp_ns2__PingAliveResponse, "ns2:PingAliveResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__PingAliveResponse(soap, &soap_tmp_ns2__PingAliveResponse, "ns2:PingAliveResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapServer.c */
