ALTER TABLE CRR_OFL_JNL_ENTRY_TYPE_MAPPING
 DROP PRIMARY KEY CASCADE;

DROP TABLE CRR_OFL_JNL_ENTRY_TYPE_MAPPING CASCADE CONSTRAINTS;

CREATE TABLE CRR_OFL_JNL_ENTRY_TYPE_MAPPING
(
  COM_JNL_TYPE_ID       INTEGER,
  COM_ENTRY_TYPE_ID     VARCHAR2(20 BYTE),
  COM_GROUP_ID          INTEGER                DEFAULT 1,
  COM_TXN_SIDE          CHAR(1 BYTE),
  COM_IS_SINGLE         INTEGER                DEFAULT 1,
  COM_TXN_CODE          VARCHAR2(3 BYTE),
  COM_AMT_FIELD         VARCHAR2(50 BYTE),
  COM_BAID_CATEGORY     VARCHAR2(10 BYTE),
  COM_PARTY_TYPE        CHAR(1 BYTE),
  COM_SIGN              INTEGER                DEFAULT 1,
  COM_DISABLED          INTEGER                DEFAULT 0,
  COM_CREATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  COM_UPDATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  COM_CREATE_USER       VARCHAR2(20 BYTE),
  COM_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CRR_OFL_JNL_ENTRY_TYPE_MAPP_PK ON CRR_OFL_JNL_ENTRY_TYPE_MAPPING
(COM_JNL_TYPE_ID, COM_ENTRY_TYPE_ID, COM_GROUP_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE CRR_OFL_JNL_ENTRY_TYPE_MAPPING ADD (
  CONSTRAINT CRR_OFL_JNL_ENTRY_TYPE_MAPP_PK
  PRIMARY KEY
  (COM_JNL_TYPE_ID, COM_ENTRY_TYPE_ID, COM_GROUP_ID)
  USING INDEX CRR_OFL_JNL_ENTRY_TYPE_MAPP_PK
  ENABLE VALIDATE);

