OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/CrrMonthEnd
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBCrrMonthEnd.so
SOOBJS =  CrrMonthEnd.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
