OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MiAdjustmentType
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMiAdjustmentType.so
SOOBJS =  MiAdjustmentType.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
