OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOMMMAverageCostRate
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOMMMAverageCostRate.so
SOOBJS = BOMMMAverageCostRate.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
