OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MiDefArBal
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMiDefArBal.so
SOOBJS =  MiDefArBal.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
