ALTER TABLE PSP_RECON_HISTORY
 DROP PRIMARY KEY CASCADE;

DROP TABLE PSP_RECON_HISTORY CASCADE CONSTRAINTS;

CREATE TABLE PSP_RECON_HISTORY
(
  PR_ID                VARCHAR2(16 BYTE),
  PR_PSP_ID	       VARCHAR2(10 BYTE),
  PR_TXN_CCY	       VARCHAR2(3 BYTE),
  PR_TXN_COUNTRY       VARCHAR2(3 BYTE),
  PR_TXN_APPROVAL_DATE  VARCHAR2(8 BYTE),
  PR_RECON_DATE        VARCHAR2(8 BYTE),
  PR_TXN_COUNT         INTEGER,
  PR_INPUT_COUNT       INTEGER,
  PR_TXN_AMOUNT        NUMBER(12,2),
  PR_INPUT_AMOUNT      NUMBER(12,2),
  PR_TXN_FEE        NUMBER(12,2),
  PR_INPUT_FEE      NUMBER(12,2),
  PR_CREATE_USER       VARCHAR2(20 BYTE),
  PR_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  PR_UPDATE_USER       VARCHAR2(20 BYTE),
  PR_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX PSP_RECON_HISTORY_IDX01 ON PSP_RECON_HISTORY
(PR_ID, PR_PSP_ID, PR_TXN_CCY,PR_TXN_APPROVAL_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PSP_RECON_HISTORY_PK ON PSP_RECON_HISTORY
(PR_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PSP_RECON_HISTORY ADD (
  CONSTRAINT PSP_RECON_HISTORY_PK
  PRIMARY KEY
  (PR_ID)
  USING INDEX PSP_RECON_HISTORY_PK
  ENABLE VALIDATE);
