ALTER TABLE PAR_TXN_SEQ_MAP
 DROP PRIMARY KEY CASCADE;

DROP TABLE PAR_TXN_SEQ_MAP CASCADE CONSTRAINTS;

CREATE TABLE PAR_TXN_SEQ_MAP
(
  TS_ORDER_ID          VARCHAR2(50 BYTE),
  TS_CONV_TXN_SEQ      VARCHAR2(16 BYTE),
  TS_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  TS_CREATE_USER       VARCHAR2(20 BYTE),
  TS_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  TS_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX PAR_TXN_SEQ_MAP_IDX01 ON PAR_TXN_SEQ_MAP
(TS_CONV_TXN_SEQ)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PAR_TXN_SEQ_MAP_PK ON PAR_TXN_SEQ_MAP
(TS_ORDER_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PAR_TXN_SEQ_MAP ADD (
  CONSTRAINT PAR_TXN_SEQ_MAP_PK
  PRIMARY KEY
  (TS_ORDER_ID)
  USING INDEX PAR_TXN_SEQ_MAP_PK
  ENABLE VALIDATE);

