ALTER TABLE OL_TXN_ENGINE_AMT_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_TXN_ENGINE_AMT_TYPE CASCADE CONSTRAINTS;

CREATE TABLE OL_TXN_ENGINE_AMT_TYPE
(
  OTAT_ACTIVITY          VARCHAR2(50 BYTE),
  OTAT_BANK_STMT_TYPE    VARCHAR2(50 BYTE),
  OTAT_CHANNEL           CHAR(3 BYTE),
  OTAT_TRIGGER_TYPE      VARCHAR2(10 BYTE),
  OTAT_RECON_TYPE        VARCHAR2(10 BYTE),
  OTAT_P1_AMT_TYPE       CHAR(2 BYTE),
  OTAT_P2_AMT_TYPE       CHAR(2 BYTE),
  OTAT_CREATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  OTAT_UPDATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  OTAT_CREATE_USER       VARCHAR2(20 BYTE),
  OTAT_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_TXN_ENGINE_AMT_TYPE_PK ON OL_TXN_ENGINE_AMT_TYPE
(OTAT_ACTIVITY, OTAT_BANK_STMT_TYPE, OTAT_CHANNEL, OTAT_TRIGGER_TYPE, OTAT_RECON_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_TXN_ENGINE_AMT_TYPE ADD (
  CONSTRAINT OL_TXN_ENGINE_AMT_TYPE_PK
  PRIMARY KEY
  (OTAT_ACTIVITY, OTAT_BANK_STMT_TYPE, OTAT_CHANNEL, OTAT_TRIGGER_TYPE, OTAT_RECON_TYPE)
  USING INDEX OL_TXN_ENGINE_AMT_TYPE_PK
  ENABLE VALIDATE);

ALTER TABLE OL_TXN_ENGINE_AMT_TYPE ADD (
  CONSTRAINT OL_TXN_ENGINE_AMT_TYPE_FK01 
  FOREIGN KEY (OTAT_TRIGGER_TYPE) 
  REFERENCES OL_DEF_ENGINE_TRIGGER_TYPE (ETT_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OL_TXN_ENGINE_AMT_TYPE_FK02 
  FOREIGN KEY (OTAT_ACTIVITY) 
  REFERENCES OL_DEF_ENGINE_ACTIVITY (DEA_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OL_TXN_ENGINE_AMT_TYPE_FK03 
  FOREIGN KEY (OTAT_P1_AMT_TYPE) 
  REFERENCES DEF_AMT_TYPE (DA_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OL_TXN_ENGINE_AMT_TYPE_FK04 
  FOREIGN KEY (OTAT_P2_AMT_TYPE) 
  REFERENCES DEF_AMT_TYPE (DA_TYPE)
  ENABLE VALIDATE);

