OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MerchantUploadFileHeader
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMerchantUploadFileHeader.so
SOOBJS =  MerchantUploadFileHeader.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
