ALTER TABLE PHUSER.OL_WAIT_PAYOUT_RECON_CFM_LIST
 DROP PRIMARY KEY CASCADE;

DROP TABLE PHUSER.OL_WAIT_PAYOUT_RECON_CFM_LIST CASCADE CONSTRAINTS;

CREATE TABLE PHUSER.OL_WAIT_PAYOUT_RECON_CFM_LIST
(
  OWPC_PSP_TXN_ID        VARCHAR2(16 BYTE),
  OWPC_BAID_TXN_ID       VARCHAR2(16 BYTE),
  OWPC_CREATE_USER       VARCHAR2(20 BYTE),
  OWPC_CREATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  OWPC_UPDATE_USER       VARCHAR2(20 BYTE),
  OWPC_UPDATE_TIMESTAMP  DATE                   DEFAULT sysdate
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE INDEX PHUSER.OL_WA_POA_RECON_CFM_LIST_IDX01 ON PHUSER.OL_WAIT_PAYOUT_RECON_CFM_LIST
(OWPC_CREATE_TIMESTAMP, OWPC_UPDATE_TIMESTAMP)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX PHUSER.OL_WA_POA_RECON_CFM_LIST_PK ON PHUSER.OL_WAIT_PAYOUT_RECON_CFM_LIST
(OWPC_PSP_TXN_ID, OWPC_BAID_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE PHUSER.OL_WAIT_PAYOUT_RECON_CFM_LIST ADD (
  CONSTRAINT OL_WA_POA_RECON_CFM_LIST_PK
  PRIMARY KEY
  (OWPC_PSP_TXN_ID, OWPC_BAID_TXN_ID)
  USING INDEX PHUSER.OL_WA_POA_RECON_CFM_LIST_PK
  ENABLE VALIDATE);

