ALTER TABLE TMP_OL_ODI_EDIT_RPY
 DROP PRIMARY KEY CASCADE;

DROP TABLE TMP_OL_ODI_EDIT_RPY CASCADE CONSTRAINTS;

CREATE TABLE TMP_OL_ODI_EDIT_RPY
(
  REC_DATE    VARCHAR2(8 BYTE),
  REC_NO      INTEGER,
  TXN_ID      VARCHAR2(16 BYTE),
  ERROR_CODE  VARCHAR2(10 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX TMP_OL_ODI_EDIT_RPY_PK ON TMP_OL_ODI_EDIT_RPY
(REC_DATE, REC_NO)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE TMP_OL_ODI_EDIT_RPY ADD (
  CONSTRAINT TMP_OL_ODI_EDIT_RPY_PK
  PRIMARY KEY
  (REC_DATE, REC_NO)
  USING INDEX TMP_OL_ODI_EDIT_RPY_PK
  ENABLE VALIDATE);

