--ALTER TABLE TMP_OL_ODI_EDIT_REQ
-- DROP PRIMARY KEY CASCADE;

--DROP TABLE TMP_OL_ODI_EDIT_REQ CASCADE CONSTRAINTS;

CREATE TABLE TMP_OL_ODI_EDIT_REQ
(
  REC_DATE               VARCHAR2(8 BYTE),
  REC_NO                 INTEGER,
  REC_TIME               VARCHAR2(50),
  TXN_ID                 VARCHAR2(16 BYTE),
  DEPOSIT_AMT            NUMBER(12,2),
  CUST_DEPOSIT_DATETIME  VARCHAR2(12 BYTE),
  BANK_CODE              VARCHAR2(50 BYTE),
  BANK_ACCT_NUM          VARCHAR2(50 BYTE),
  DEPOSIT_REF            VARCHAR2(150 BYTE),
  DEPOSIT_BANK           VARCHAR2(150 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX TMP_OL_ODI_EDIT_REQ_PK ON TMP_OL_ODI_EDIT_REQ
(REC_DATE, REC_NO)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE TMP_OL_ODI_EDIT_REQ ADD (
  CONSTRAINT TMP_OL_ODI_EDIT_REQ_PK
  PRIMARY KEY
  (REC_DATE, REC_NO)
  USING INDEX TMP_OL_ODI_EDIT_REQ_PK
  ENABLE VALIDATE);

