
ALTER TABLE DEF_ENQUIRY_STATUS
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_ENQUIRY_STATUS CASCADE CONSTRAINTS;

CREATE TABLE DEF_ENQUIRY_STATUS
(
  DE_CODE              CHAR(1 BYTE),
  DE_DESC              VARCHAR2(50 BYTE),
  DE_CREATE_USER       VARCHAR2(20 BYTE),
  DE_UPDATE_USER       VARCHAR2(20 BYTE),
  DE_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  DE_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DEF_ENQUIRY_STATUS_PK ON DEF_ENQUIRY_STATUS
(DE_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DEF_ENQUIRY_STATUS ADD (
  CONSTRAINT DEF_ENQUIRY_STATUS_PK
  PRIMARY KEY
  (DE_CODE)
  USING INDEX DEF_ENQUIRY_STATUS_PK
  ENABLE VALIDATE);

