ALTER TABLE MI_BATCH_RELATION
 DROP PRIMARY KEY CASCADE;

DROP TABLE MI_BATCH_RELATION CASCADE CONSTRAINTS;

CREATE TABLE MI_BATCH_RELATION
(
  BR_BATCH_ID          VARCHAR2(16 BYTE),
  BR_ORG_BATCH_ID      VARCHAR2(16 BYTE),
  BR_RELATION_TYPE     CHAR(1 BYTE),
  BR_CREATE_TIMESTAMP  DATE,
  BR_UPDATE_TIMESTAMP  DATE,
  BR_CREATE_USER       VARCHAR2(20 BYTE),
  BR_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX MI_BATCH_RELATION_IDX01 ON MI_BATCH_RELATION
(BR_ORG_BATCH_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX MI_BATCH_RELATION_PK ON MI_BATCH_RELATION
(BR_BATCH_ID, BR_ORG_BATCH_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MI_BATCH_RELATION ADD (
  CONSTRAINT MI_BATCH_RELATION_PK
  PRIMARY KEY
  (BR_BATCH_ID, BR_ORG_BATCH_ID)
  USING INDEX MI_BATCH_RELATION_PK
  ENABLE VALIDATE);

ALTER TABLE MI_BATCH_RELATION ADD (
  CONSTRAINT MI_BATCH_RELATION_FK01 
  FOREIGN KEY (BR_RELATION_TYPE) 
  REFERENCES MI_DEF_BATCH_REL_TYPE (BRT_TYPE)
  ENABLE VALIDATE);

