OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLStatementTmp
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLStatementTmp.so
SOOBJS =  OLStatementTmp.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
