OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/CustomerPspCounters
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBCustomerPspCounters.so
SOOBJS =  CustomerPspCounters.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
