ALTER TABLE MI_ACR_BAL
 DROP PRIMARY KEY CASCADE;

DROP TABLE MI_ACR_BAL CASCADE CONSTRAINTS;

CREATE TABLE MI_ACR_BAL
(
  MA_FROM_CCY          VARCHAR2(3 BYTE),
  MA_BANK_CCY          VARCHAR2(3 BYTE),
  MA_BANK_BAL          NUMBER(14,2),
  MA_RATE              NUMBER(14,5),
  MA_CREATE_USER       VARCHAR2(20 BYTE),
  MA_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  MA_UPDATE_USER       VARCHAR2(20 BYTE),
  MA_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MI_ACR_BAL_PK ON MI_ACR_BAL
(MA_FROM_CCY, MA_BANK_CCY)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MI_ACR_BAL ADD (
  CONSTRAINT MI_ACR_BAL_PK
  PRIMARY KEY
  (MA_FROM_CCY, MA_BANK_CCY)
  USING INDEX MI_ACR_BAL_PK
  ENABLE VALIDATE);


