OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/PspAmtDiffRange
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBPspAmtDiffRange.so
SOOBJS = PspAmtDiffRange.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
