ALTER TABLE MMS_DEF_BAL_NATURE
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_DEF_BAL_NATURE CASCADE CONSTRAINTS;

CREATE TABLE MMS_DEF_BAL_NATURE
(
  MBN_TYPE              VARCHAR2(4 BYTE),
  MBN_DESC              VARCHAR2(50 BYTE),
  MBN_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  MBN_CREATE_USER       VARCHAR2(20 BYTE),
  MBN_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  MBN_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MMS_DEF_BAL_NATURE_PK ON MMS_DEF_BAL_NATURE
(MBN_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_DEF_BAL_NATURE ADD (
  CONSTRAINT MMS_DEF_BAL_NATURE_PK
  PRIMARY KEY
  (MBN_TYPE)
  USING INDEX MMS_DEF_BAL_NATURE_PK
  ENABLE VALIDATE);

