ALTER TABLE MMS_RULE_TOLERANCE_LEVEL
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_RULE_TOLERANCE_LEVEL CASCADE CONSTRAINTS;

CREATE TABLE MMS_RULE_TOLERANCE_LEVEL
(
  MTL_RULE_ID           INTEGER,
  MTL_TXN_CODE          CHAR(3 BYTE),
  MTL_ENTITY_ID         VARCHAR2(20 BYTE),
  MTL_CCY               VARCHAR2(3 BYTE),
  MTL_COUNTRY           CHAR(2 BYTE),
  MTL_SRC_ENTITY_ID     VARCHAR2(20 BYTE)       DEFAULT '000',
  MTL_EFFECT_DATE       DATE,
  MTL_DISABLED          INTEGER,
  MTL_PL_AMOUNT_ID      INTEGER,
  MTL_NL_AMOUNT_ID      INTEGER,
  MTL_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  MTL_CREATE_USER       VARCHAR2(20 BYTE),
  MTL_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  MTL_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX MMS_RULE_TOLERANCE_LEVEL_IDX01 ON MMS_RULE_TOLERANCE_LEVEL
(MTL_TXN_CODE, MTL_ENTITY_ID, MTL_CCY, MTL_COUNTRY, MTL_SRC_ENTITY_ID, 
MTL_EFFECT_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX MMS_RULE_TOLERANCE_LEVEL_PK ON MMS_RULE_TOLERANCE_LEVEL
(MTL_RULE_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_RULE_TOLERANCE_LEVEL ADD (
  CONSTRAINT MMS_RULE_TOLERANCE_LEVEL_PK
  PRIMARY KEY
  (MTL_RULE_ID)
  USING INDEX MMS_RULE_TOLERANCE_LEVEL_PK
  ENABLE VALIDATE);

ALTER TABLE MMS_RULE_TOLERANCE_LEVEL ADD (
  CONSTRAINT MMS_RULE_TOLERANCE_LEVEL_FK01 
  FOREIGN KEY (MTL_ENTITY_ID) 
  REFERENCES MMS_ENTITY (ME_ID)
  ENABLE VALIDATE,
  CONSTRAINT MMS_RULE_TOLERANCE_LEVEL_FK02 
  FOREIGN KEY (MTL_PL_AMOUNT_ID) 
  REFERENCES MMS_RULE_AMOUNT (MRA_ID)
  ENABLE VALIDATE,
  CONSTRAINT MMS_RULE_TOLERANCE_LEVEL_FK03 
  FOREIGN KEY (MTL_NL_AMOUNT_ID) 
  REFERENCES MMS_RULE_AMOUNT (MRA_ID)
  ENABLE VALIDATE);

