OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLPayoutReturnBatchHd
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLPayoutReturnBatchHd.so
SOOBJS =  OLPayoutReturnBatchHd.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
