OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLSimCards
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLSimCards.so
SOOBJS =  OLSimCards.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
