OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmsEntity
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmsEntity.so
SOOBJS =  MmsEntity.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
