OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmsEntityBalAcct
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmsEntityBalAcct.so
SOOBJS =  MmsEntityBalAcct.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
