OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/Clients
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBClients.so
SOOBJS =  Clients.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
