ALTER TABLE OL_PSP_COSTS_CATEGORY
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_PSP_COSTS_CATEGORY CASCADE CONSTRAINTS;

CREATE TABLE OL_PSP_COSTS_CATEGORY
(
  OPCC_CAT_ID             VARCHAR2(25 BYTE),
  OPCC_TXN_CODE           CHAR(3 BYTE),
  OPCC_GEN_TXN_CODE       CHAR(3 BYTE),
  OPCC_AMT_TYPE           CHAR(2 BYTE),
  OPCC_CREATE_TIMESTAMP   DATE                  DEFAULT sysdate,
  OPCC_UPDATE_TIMESTAMP   DATE                  DEFAULT sysdate,
  OPCC_CREATE_USER        VARCHAR2(20 BYTE),
  OPCC_UPDATE_USER        VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_PSP_COSTS_CATEGORY_PK ON OL_PSP_COSTS_CATEGORY
(OPCC_CAT_ID,OPCC_TXN_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_PSP_COSTS_CATEGORY ADD (
  CONSTRAINT OL_PSP_COSTS_CATEGORY_PK
  PRIMARY KEY
  (OPCC_CAT_ID,OPCC_TXN_CODE)
  USING INDEX OL_PSP_COSTS_CATEGORY_PK
  ENABLE VALIDATE);

