OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnMgtByUsVBF
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnMgtByUsVBF.so
SOOBJS = TxnMgtByUsVBF.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
