OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/SystemExRules
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBSystemExRules.so
SOOBJS =  SystemExRules.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
