ALTER TABLE DEF_CHARGE_PARTY_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_CHARGE_PARTY_TYPE CASCADE CONSTRAINTS;

CREATE TABLE DEF_CHARGE_PARTY_TYPE
(
  DCP_TYPE              CHAR(1 BYTE),
  DCP_DESC              VARCHAR2(50 BYTE),
  DCP_CREATE_TIMESTAMP  DATE,
  DCP_CREATE_USER       VARCHAR2(20 BYTE),
  DCP_UPDATE_TIMESTAMP  DATE,
  DCP_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEF_CHARGE_PARTY_TYPE_PK ON DEF_CHARGE_PARTY_TYPE
(DCP_TYPE)
LOGGING
TABLESPACE USER_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_CHARGE_PARTY_TYPE ADD (
  CONSTRAINT DEF_CHARGE_PARTY_TYPE_PK
  PRIMARY KEY
  (DCP_TYPE)
  USING INDEX DEF_CHARGE_PARTY_TYPE_PK);

