ALTER TABLE CRR_EXT_JNL_LOG
 DROP PRIMARY KEY CASCADE;

DROP TABLE CRR_EXT_JNL_LOG CASCADE CONSTRAINTS;

CREATE TABLE CRR_EXT_JNL_LOG
(
  EJL_JNL_ID            VARCHAR2(16 BYTE),
  EJL_JNL_TYPE_ID       INTEGER,
  EJL_TXN_DATE          VARCHAR2(8 BYTE),
  EJL_JNL_DISABLED      INTEGER                 DEFAULT 0,
  EJL_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  EJL_CREATE_USER       VARCHAR2(20 BYTE),
  EJL_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  EJL_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX CRR_EXT_JNL_LOG_IDX01 ON CRR_EXT_JNL_LOG
(EJL_TXN_DATE, EJL_JNL_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX CRR_EXT_JNL_LOG_PK ON CRR_EXT_JNL_LOG
(EJL_JNL_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE CRR_EXT_JNL_LOG ADD (
  CONSTRAINT CRR_EXT_JNL_LOG_PK
  PRIMARY KEY
  (EJL_JNL_ID)
  USING INDEX CRR_EXT_JNL_LOG_PK
  ENABLE VALIDATE);

