OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/ExchangeRate
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBExchangeRate.so
SOOBJS =  ExchangeRate.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
