ALTER TABLE BANK_PAYOUT_PSP
 DROP PRIMARY KEY CASCADE;

DROP TABLE BANK_PAYOUT_PSP CASCADE CONSTRAINTS;

CREATE TABLE BANK_PAYOUT_PSP
(
  BP_PSP_ID        VARCHAR2(10 BYTE),
  BP_BANK_NAME     VARCHAR2(50 BYTE)        NOT NULL,
  BP_OPERATOR_TYPE     CHAR(2 BYTE),
  BP_TOTAL_AMT         NUMBER(12,2)             DEFAULT 0,
  BP_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  BP_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  BP_CREATE_USER       VARCHAR2(20 BYTE),
  BP_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX BANK_PAYOUT_PSP_PK ON BANK_PAYOUT_PSP
(BP_PSP_ID, BP_BANK_NAME)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE BANK_PAYOUT_PSP ADD (
  CONSTRAINT BANK_PAYOUT_PSP_PK
  PRIMARY KEY
  (BP_PSP_ID, BP_BANK_NAME)
  USING INDEX BANK_PAYOUT_PSP_PK);

