OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/FundsInHistory
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBFundsInHistory.so
SOOBJS =  FundsInHistory.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
