ALTER TABLE MMS_TXN_SUPPORTED
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_TXN_SUPPORTED CASCADE CONSTRAINTS;

CREATE TABLE MMS_TXN_SUPPORTED
(
  MS_TXN_CODE          VARCHAR2(3 BYTE),
  MS_CHANNEL_CODE      VARCHAR2(10 BYTE),
  MS_SUPPORT           INTEGER,
  MS_CREATE_TIMESTAMP  DATE,
  MS_CREATE_USER       VARCHAR2(20 BYTE),
  MS_UPDATE_TIMESTAMP  DATE,
  MS_UPDATE_USER       VARCHAR2(20 BYTE),
  MS_DO_LOGGING        INTEGER                  DEFAULT NULL,
  MS_INIT_TXN          INTEGER                  DEFAULT NULL
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN MMS_TXN_SUPPORTED.MS_DO_LOGGING IS '''1'' - Yes, ''0'' - No, ''2'' - Update only';



CREATE UNIQUE INDEX MMS_TXN_SUPPORTED_PK ON MMS_TXN_SUPPORTED
(MS_TXN_CODE, MS_CHANNEL_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_TXN_SUPPORTED ADD (
  CONSTRAINT MMS_TXN_SUPPORTED_PK
  PRIMARY KEY
  (MS_TXN_CODE, MS_CHANNEL_CODE)
  USING INDEX MMS_TXN_SUPPORTED_PK
  ENABLE VALIDATE);

