OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/CrrJnlType
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBCrrJnlType.so
SOOBJS =  CrrJnlType.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
