OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOBalance
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOBalance.so
SOOBJS = BOBalance.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
