OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnWebOnUs2SPY
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnWebOnUs2SPY.so
SOOBJS = TxnWebOnUs2SPY.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
