ALTER TABLE MI_ENTITY_BALANCE
 DROP PRIMARY KEY CASCADE;

DROP TABLE MI_ENTITY_BALANCE CASCADE CONSTRAINTS;

CREATE TABLE MI_ENTITY_BALANCE
(
  EB_ENTITY_ID         VARCHAR2(10 BYTE)        NOT NULL,
  EB_COUNTRY           CHAR(2 BYTE)             NOT NULL,
  EB_CURRENCY          VARCHAR2(3 BYTE)         NOT NULL,
  EB_ACCT_BAL          NUMBER(14,2)             DEFAULT 0,
  EB_INTRANSIT         NUMBER(14,2)             DEFAULT 0,
  EB_AR_BAL            NUMBER(14,2)             DEFAULT 0,
  EB_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  EB_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  EB_CREATE_USER       VARCHAR2(20 BYTE),
  EB_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MI_ENTITY_BALANCE_PK ON MI_ENTITY_BALANCE
(EB_ENTITY_ID, EB_COUNTRY, EB_CURRENCY)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MI_ENTITY_BALANCE ADD (
  CONSTRAINT MI_ENTITY_BALANCE_PK
  PRIMARY KEY
  (EB_ENTITY_ID, EB_COUNTRY, EB_CURRENCY)
  USING INDEX MI_ENTITY_BALANCE_PK
  ENABLE VALIDATE);

ALTER TABLE MI_ENTITY_BALANCE ADD (
  CONSTRAINT MI_ENTITY_BALANCE_FK01 
  FOREIGN KEY (EB_ENTITY_ID) 
  REFERENCES MI_ENTITY_DETAIL (ED_ENTITY_ID)
  ENABLE VALIDATE,
  CONSTRAINT MI_ENTITY_BALANCE_FK02 
  FOREIGN KEY (EB_COUNTRY) 
  REFERENCES COUNTRY (COUNTRY_CODE)
  ENABLE VALIDATE,
  CONSTRAINT MI_ENTITY_BALANCE_FK03 
  FOREIGN KEY (EB_CURRENCY) 
  REFERENCES DEF_CURRENCY (DC_CCY_ID)
  ENABLE VALIDATE);

