OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/EmailNotifyList
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBEmailNotifyList.so
SOOBJS =  EmailNotifyList.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
