ALTER TABLE CUSTOMER_GROUP_LIMIT_CHECK
 DROP PRIMARY KEY CASCADE;

DROP TABLE CUSTOMER_GROUP_LIMIT_CHECK CASCADE CONSTRAINTS;

CREATE TABLE CUSTOMER_GROUP_LIMIT_CHECK
(
  CLC_GROUP_CODE            VARCHAR2(10 BYTE),
  CLC_ALERT_LEVEL           NUMBER(5,2),
  CLC_ALERT_REMAIN_AMT      NUMBER(14,2)         DEFAULT 0,
  CLC_DISABLED              INTEGER              DEFAULT 0,
  CLC_LAST_CHECKING_TIME    DATE,
  CLC_CREATE_USER           VARCHAR2(20 BYTE),
  CLC_UPDATE_USER           VARCHAR2(20 BYTE),
  CLC_CREATE_TIMESTAMP      DATE                 DEFAULT sysdate,
  CLC_UPDATE_TIMESTAMP      DATE                 DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CUSTOMER_GROUP_LIMIT_CHECK_PK ON CUSTOMER_GROUP_LIMIT_CHECK
(CLC_GROUP_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

ALTER TABLE CUSTOMER_GROUP_LIMIT_CHECK ADD (
  CONSTRAINT CUSTOMER_GROUP_LIMIT_CHECK_PK
  PRIMARY KEY
  (CLC_GROUP_CODE)
  USING INDEX CUSTOMER_GROUP_LIMIT_CHECK_PK
  ENABLE VALIDATE);

