ALTER TABLE CUSTOMER_GROUP_DETAIL
 DROP PRIMARY KEY CASCADE;

DROP TABLE CUSTOMER_GROUP_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE CUSTOMER_GROUP_DETAIL
(
  CGD_MERCHANT_ID       VARCHAR2(15 BYTE),
  CGD_CUST_ID           VARCHAR2(10 BYTE),
  CGD_CODE              VARCHAR2(10 BYTE),
  CGD_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  CGD_CREATE_USER       VARCHAR2(20 BYTE),
  CGD_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  CGD_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX CUSTOMER_GROUP_DETAIL_IDX01 ON CUSTOMER_GROUP_DETAIL
(CGD_CUST_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX CUSTOMER_GROUP_DETAIL_PK ON CUSTOMER_GROUP_DETAIL
(CGD_MERCHANT_ID,CGD_CUST_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE CUSTOMER_GROUP_DETAIL ADD (
  CONSTRAINT CUSTOMER_GROUP_DETAIL_PK
  PRIMARY KEY
  (CGD_MERCHANT_ID,CGD_CUST_ID)
  USING INDEX CUSTOMER_GROUP_DETAIL_PK
  ENABLE VALIDATE);



ALTER TABLE CUSTOMER_GROUP_DETAIL ADD (
  CONSTRAINT CUSTOMER_GROUP_DETAIL_FK01 
  FOREIGN KEY (CGD_MERCHANT_ID) 
  REFERENCES MERCH_DETAIL (MERCHANT_ID)
  ENABLE VALIDATE);

