ALTER TABLE PAR_DEF_MISC
 DROP PRIMARY KEY CASCADE;

DROP TABLE PAR_DEF_MISC CASCADE CONSTRAINTS;

CREATE TABLE PAR_DEF_MISC
(
  PDM_CODE              VARCHAR2(50 BYTE),
  PDM_DESC              VARCHAR2(100 BYTE),
  PDM_VALUE             VARCHAR2(50 BYTE),
  PDM_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  PDM_CREATE_USER       VARCHAR2(20 BYTE),
  PDM_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  PDM_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PAR_DEF_MISC_PK ON PAR_DEF_MISC
(PDM_CODE, PDM_VALUE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PAR_DEF_MISC ADD (
  CONSTRAINT PAR_DEF_MISC_PK
  PRIMARY KEY
  (PDM_CODE, PDM_VALUE)
  USING INDEX PAR_DEF_MISC_PK
  ENABLE VALIDATE);

