ALTER TABLE MI_MODE_TXN_CTL
 DROP PRIMARY KEY CASCADE;

DROP TABLE MI_MODE_TXN_CTL CASCADE CONSTRAINTS;

CREATE TABLE MI_MODE_TXN_CTL
(
  MTC_PROCESS_TYPE        VARCHAR2(20 BYTE),
  MTC_VOID_PROCESS_TYPE   VARCHAR2(20 BYTE),
  MTC_IS_VOID_PROCESS     INTEGER,
  MTC_MI_SUPPORT          INTEGER,
  MTC_EXIT_IF_ORG_NOT_MI  INTEGER,
  MTC_ERR_IF_NOT_MI       INTEGER,
  MTC_CREATE_TIMESTAMP    DATE,
  MTC_UPDATE_TIMESTAMP    DATE,
  MTC_CREATE_USER         VARCHAR2(20 BYTE),
  MTC_UPDATE_USER         VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MI_MODE_TXN_CTL_PK ON MI_MODE_TXN_CTL
(MTC_PROCESS_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MI_MODE_TXN_CTL ADD (
  CONSTRAINT MI_MODE_TXN_CTL_PK
  PRIMARY KEY
  (MTC_PROCESS_TYPE)
  USING INDEX MI_MODE_TXN_CTL_PK
  ENABLE VALIDATE);

ALTER TABLE MI_MODE_TXN_CTL ADD (
  CONSTRAINT MI_MODE_TXN_CTL_FK01 
  FOREIGN KEY (MTC_PROCESS_TYPE) 
  REFERENCES MI_DEF_PROCESS_TYPE (PT_TYPE)
  ENABLE VALIDATE);

