OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOOLPspTxnEngine
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOOLPspTxnEngine.so
SOOBJS = BOOLPspTxnEngine.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
