OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/ServicePspUrl
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBServicePspUrl.so
SOOBJS =  ServicePspUrl.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
