OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MobSegmentCtl
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMobSegmentCtl.so
SOOBJS =  MobSegmentCtl.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
