OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLStatement
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLStatement.so
SOOBJS =  OLStatement.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
