OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLWaitPayoutReconCfmList
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLWaitPayoutReconCfmList.so
SOOBJS =  OLWaitPayoutReconCfmList.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
