CREATE TABLE OL_MERCH_PSP_BATCH_RELATION
(
  OMPBR_BATCH_ID          VARCHAR2(16 BYTE)     NOT NULL,
  OMPBR_PAIR_SEQ          INTEGER               NOT NULL,
  OMPBR_MERCHANT_TXN_ID   VARCHAR2(16 BYTE)     NOT NULL,
  OMPBR_BAID_TXN_ID       VARCHAR2(16 BYTE)     NOT NULL,
  OMPBR_CREATE_USER       VARCHAR2(20 BYTE),
  OMPBR_CREATE_TIMESTAMP  DATE                  DEFAULT sysdate,
  OMPBR_UPDATE_USER       VARCHAR2(20 BYTE),
  OMPBR_UPDATE_TIMESTAMP  DATE                  DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX OL_MERCH_PSP_BAT_REL_IDX01 ON OL_MERCH_PSP_BATCH_RELATION
(OMPBR_MERCHANT_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX OL_MERCH_PSP_BAT_REL_IDX02 ON OL_MERCH_PSP_BATCH_RELATION
(OMPBR_BAID_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX OL_MERCH_PSP_BATCH_RELATION_PK ON OL_MERCH_PSP_BATCH_RELATION
(OMPBR_BATCH_ID, OMPBR_PAIR_SEQ)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_MERCH_PSP_BATCH_RELATION ADD (
  CONSTRAINT OL_MERCH_PSP_BATCH_RELATION_PK
  PRIMARY KEY
  (OMPBR_BATCH_ID, OMPBR_PAIR_SEQ)
  USING INDEX OL_MERCH_PSP_BATCH_RELATION_PK
  ENABLE VALIDATE);

