OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MerchantLoginPolicy
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMerchantLoginPolicy.so
SOOBJS =  MerchantLoginPolicy.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
