ALTER TABLE PAR_MERCH_OPEN_BAL
 DROP PRIMARY KEY CASCADE;

DROP TABLE PAR_MERCH_OPEN_BAL CASCADE CONSTRAINTS;

CREATE TABLE PAR_MERCH_OPEN_BAL
(
  OB_FILE_DATE         VARCHAR2(8 BYTE),
  OB_MERCH_ACCT_NMB    VARCHAR2(50 BYTE),
  OB_CURRENCY          VARCHAR2(3 BYTE),
  OB_BALANCE           NUMBER(14,2),
  OB_HOLDING_FUND      NUMBER(14,2),
  OB_RESERVE_BAL       NUMBER(14,2),
  OB_RESERVE_RATE      NUMBER(14,2),
  OB_ACTIVE_FLAG       NUMBER(1),
  OB_FILE_POST_DATE    DATE,
  OB_FILE_UPDATE_DATE  DATE,
  OB_THRESHOLD         NUMBER(14,2),
  OB_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  OB_CREATE_USER       VARCHAR2(20 BYTE),
  OB_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  OB_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PAR_MERCH_OPEN_BAL_PK ON PAR_MERCH_OPEN_BAL
(OB_FILE_DATE, OB_MERCH_ACCT_NMB, OB_CURRENCY)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PAR_MERCH_OPEN_BAL ADD (
  CONSTRAINT PAR_MERCH_OPEN_BAL_PK
  PRIMARY KEY
  (OB_FILE_DATE, OB_MERCH_ACCT_NMB, OB_CURRENCY)
  USING INDEX PAR_MERCH_OPEN_BAL_PK
  ENABLE VALIDATE);

