OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOOLPspCosts
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOOLPspCosts.so
SOOBJS = BOOLPspCosts.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
