DROP TABLE TMP_CRR_CARRY_OLD_BALANCE CASCADE CONSTRAINTS;

CREATE TABLE TMP_CRR_CARRY_OLD_BALANCE
(
  OB_LINE          NUMBER,
  OB_GL_CODE       VARCHAR2(20 BYTE),
  OB_GL_NAME       VARCHAR2(100 BYTE),
  OB_SL_CODE       VARCHAR2(50 BYTE),
  OB_SL_NAME       VARCHAR2(100 BYTE),
  OB_PRODUCT_CODE  CHAR(3 BYTE),
  OB_COUNTRY_CODE  CHAR(2 BYTE),
  OB_CR_IND        CHAR(1 BYTE),
  OB_CURRENCY_ID   VARCHAR2(3 BYTE),
  OB_CMS_BAL       NUMBER(12,2),
  OB_CMS_BAL_HKD   NUMBER(12,2),
  OB_FX_RATE       NUMBER(12,5),
  OB_FINISHED      CHAR(1 BYTE) DEFAULT 'N'
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX TMP_CRR_COB_INX_1 ON TMP_CRR_CARRY_OLD_BALANCE
(OB_PRODUCT_CODE, OB_COUNTRY_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;
