OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmsPHTransaction
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmsPHTransaction.so
SOOBJS =  MmsPHTransaction.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
