OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLMerchPspBatchRelation
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLMerchPspBatchRelation.so
SOOBJS =  OLMerchPspBatchRelation.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
