ALTER TABLE DEPOSIT_RESPONSE_LOG
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEPOSIT_RESPONSE_LOG CASCADE CONSTRAINTS;

CREATE TABLE DEPOSIT_RESPONSE_LOG
(
  RESPONSE_LOG_ID   INTEGER                  NOT NULL,
  REQUEST_LOG_ID    INTEGER                  NOT NULL,
  PROCESS_CODE      CHAR(6 CHAR)                NOT NULL,
  PROCESS_TYPE      CHAR(4 CHAR)                NOT NULL,
  TXN_STATUS_ID     VARCHAR2(10 BYTE)           NOT NULL,
  TXN_ID            VARCHAR2(20 BYTE)           NOT NULL,
  PAY_AMT           NUMBER(18,2)                NOT NULL,
  CURRENCY          VARCHAR2(3 BYTE)            NOT NULL,
  REFERENCE         VARCHAR2(50 BYTE)           NOT NULL,
  REQUEST_TIME      VARCHAR2(14 BYTE)           NOT NULL,
  MERCHANT_ID       VARCHAR2(10 BYTE)           NOT NULL,
  RESPONSE_TIME     VARCHAR2(14 BYTE)           NOT NULL,
  POST_DATE         VARCHAR2(8 BYTE)            NOT NULL,
  COUNTRY_ID        VARCHAR2(3 BYTE)            NOT NULL,
  CHANNEL_ID        VARCHAR2(10 BYTE)           NOT NULL,
  BANK_CODE         VARCHAR2(10 BYTE)           NOT NULL,
  SERVICE_FEE       NUMBER(18,2)                NOT NULL,
  SERVICE_CURRENCY  VARCHAR2(3 BYTE)            NOT NULL,
  REMARK            VARCHAR2(255 BYTE)          NOT NULL,
  CHECKSUM          VARCHAR2(255 BYTE)          NOT NULL,
  ALGORITHM         VARCHAR2(255 BYTE)          NOT NULL,
  CREATE_DATE       DATE                        NOT NULL,
  UPDATE_DATE       DATE                        NOT NULL,
  DISABLED          SMALLINT                    DEFAULT 0                     NOT NULL,
  CREATED_BY        VARCHAR2(20 BYTE)           NOT NULL
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEPOSIT_RESPONSE_LOG_PK ON DEPOSIT_RESPONSE_LOG
(RESPONSE_LOG_ID)
LOGGING
TABLESPACE USER_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEPOSIT_RESPONSE_LOG ADD (
  CONSTRAINT DEPOSIT_RESPONSE_LOG_PK
  PRIMARY KEY
  (RESPONSE_LOG_ID)
  USING INDEX DEPOSIT_RESPONSE_LOG_PK);

