OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/ExchangeRateERS
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBExchangeRateERS.so
SOOBJS =  ExchangeRateERS.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
