OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnMgtByUsVPD
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnMgtByUsVPD.so
SOOBJS = TxnMgtByUsVPD.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
