OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOMMSTxnEng
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOMMSTxnEng.so
SOOBJS = BOMMSTxnEng.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
