OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLDefAcctStatus
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLDefAcctStatus.so
SOOBJS =  OLDefAcctStatus.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
