ALTER TABLE FUNDS_IN
 DROP PRIMARY KEY CASCADE;

DROP TABLE FUNDS_IN CASCADE CONSTRAINTS;

CREATE TABLE FUNDS_IN
(
  F_ID			   INTEGER,
  F_FUNDIN_DATE            VARCHAR2(8 BYTE),
  F_FUNDIN_CCY             VARCHAR2(3 BYTE),
  F_FUNDIN_AMOUNT          NUMBER(14,2),
  F_BANK_CCY               VARCHAR2(3 BYTE),
  F_BANK_AMOUNT            NUMBER(14,2),
  F_APPROVAL_USER          VARCHAR2(20 BYTE),
  F_APPROVAL_TIMESTAMP     DATE,
  F_CALCULATION_USER       VARCHAR2(20 BYTE),
  F_CALCULATION_TIMESTAMP  DATE,
  F_CREATE_USER            VARCHAR2(20 BYTE),
  F_UPDATE_USER            VARCHAR2(20 BYTE),
  F_CREATE_TIMESTAMP       DATE                 DEFAULT sysdate,
  F_UPDATE_TIMESTAMP       DATE
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX FUNDS_IN_PK ON FUNDS_IN
(F_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE FUNDS_IN ADD (
  CONSTRAINT FUNDS_IN_PK
  PRIMARY KEY
  (F_ID)
  USING INDEX FUNDS_IN_PK);


