CREATE TABLE PAYPAGE_BANK_ORDER_MAPPING
(
  PBOM_BANK_CODE      		VARCHAR2(10 BYTE),
  PBOM_SERVICE_CODE     	CHAR(3 BYTE),
  PBOM_DISPLAY_ORDER         	INTEGER,
  PBOM_DISABLED          	INTEGER                  DEFAULT 0,
  PBOM_CREATE_TIMESTAMP  	DATE                     DEFAULT sysdate,
  PBOM_UPDATE_TIMESTAMP  	DATE                     DEFAULT sysdate,
  PBOM_CREATE_USER       	VARCHAR2(20 BYTE),
  PBOM_UPDATE_USER       	VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX PAYPAGE_BANK_ORDER_MAPPING_PK ON PAYPAGE_BANK_ORDER_MAPPING
(PBOM_BANK_CODE, PBOM_SERVICE_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE PAYPAGE_BANK_ORDER_MAPPING ADD (
  CONSTRAINT PAYPAGE_BANK_ORDER_MAPPING_PK
  PRIMARY KEY
  (PBOM_BANK_CODE, PBOM_SERVICE_CODE)
  USING INDEX PAYPAGE_BANK_ORDER_MAPPING_PK
  ENABLE VALIDATE);
