ALTER TABLE RULE_PAYOUT_ONLINE_MODE
 DROP PRIMARY KEY CASCADE;

DROP TABLE RULE_PAYOUT_ONLINE_MODE CASCADE CONSTRAINTS;

CREATE TABLE RULE_PAYOUT_ONLINE_MODE
(
  RP_MERCHANT_ID       VARCHAR2(15 BYTE),
  RP_SERVICE_CODE      CHAR(3 BYTE),
  RP_PSP_ID	       VARCHAR2(10 BYTE)	NOT NULL,
  RP_DISABLED          INTEGER                  DEFAULT 0,
  RP_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  RP_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  RP_CREATE_USER       VARCHAR2(20 BYTE),
  RP_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX RULE_PAYOUT_ONLINE_MODE_PK ON RULE_PAYOUT_ONLINE_MODE
(RP_MERCHANT_ID, RP_SERVICE_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE RULE_PAYOUT_ONLINE_MODE ADD (
  CONSTRAINT RULE_PAYOUT_ONLINE_MODE_PK
  PRIMARY KEY
  (RP_MERCHANT_ID, RP_SERVICE_CODE)
  USING INDEX RULE_PAYOUT_ONLINE_MODE_PK
  ENABLE VALIDATE);

