CREATE TABLE OFFSET_TXN_TYPE
(
  OTT_PARTY_TYPE      		CHAR(1 BYTE),
  OTT_TXN_CODE        		VARCHAR2(3 BYTE),
  OTT_DESC              	VARCHAR2(50 BYTE),
  OTT_AMT_TYPE          	CHAR(2 BYTE),
  OTT_BAL_TYPE     		CHAR(1 BYTE),
  OTT_ALLOW_MODIFY        	INTEGER                	DEFAULT 1,
  OTT_ALLOW_BAL_NEGATIVE  	INTEGER                	DEFAULT 1,
  OTT_NATURE              	CHAR(1 BYTE),
  OTT_DISABLED          	INTEGER                	DEFAULT 0,
  OTT_CREATE_TIMESTAMP  	DATE,
  OTT_CREATE_USER       	VARCHAR2(20 BYTE),
  OTT_UPDATE_TIMESTAMP  	DATE,
  OTT_UPDATE_USER       	VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OFFSET_TXN_TYPE_PK ON OFFSET_TXN_TYPE
(OTT_PARTY_TYPE, OTT_TXN_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OFFSET_TXN_TYPE ADD (
  CONSTRAINT OFFSET_TXN_TYPE_PK
  PRIMARY KEY
  (OTT_PARTY_TYPE, OTT_TXN_CODE)
  USING INDEX OFFSET_TXN_TYPE_PK
  ENABLE VALIDATE);

ALTER TABLE OFFSET_TXN_TYPE ADD (
  CONSTRAINT OFFSET_TXN_TYPE_FK01
  FOREIGN KEY (OTT_PARTY_TYPE)
  REFERENCES DEF_PARTY_TYPE (DP_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OFFSET_TXN_TYPE_FK02
  FOREIGN KEY (OTT_AMT_TYPE)
  REFERENCES DEF_AMT_TYPE (DA_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OFFSET_TXN_TYPE_FK03
  FOREIGN KEY (OTT_BAL_TYPE)
  REFERENCES DEF_OFFSET_TXN_BAL_TYPE (OTBT_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OFFSET_TXN_TYPE_FK04 
  FOREIGN KEY (OTT_NATURE) 
  REFERENCES DEF_ADJUSTMENT_NATURE (DN_CODE)
  ENABLE VALIDATE);
