OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmsRuleToleranceLevel
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmsRuleToleranceLevel.so
SOOBJS =  MmsRuleToleranceLevel.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
