DROP TABLE MI_ACR_INOUT_HISTORY CASCADE CONSTRAINTS;

CREATE TABLE MI_ACR_INOUT_HISTORY
(
  MAH_BATCH_ID          VARCHAR2(16 BYTE),
  MAH_TXN_DATE          VARCHAR2(8 BYTE),
  MAH_BANK_ID           VARCHAR2(10 BYTE),
  MAH_FROM_CCY          VARCHAR2(3 BYTE),
  MAH_FROM_AMT          NUMBER(14,2),
  MAH_BANK_CCY          VARCHAR2(3 BYTE),
  MAH_BANK_AMT          NUMBER(14,2),
  MAH_OLD_RATE          NUMBER(14,5),
  MAH_NEW_RATE          NUMBER(14,5),
  MAH_ORG_BANK_BAL      NUMBER(14,2),
  MAH_BANK_BAL          NUMBER(14,2),
  MAH_TXN_CODE          CHAR(3 BYTE),
  MAH_FUND_TYPE         CHAR(1 BYTE),
  MAH_TXN_ID            VARCHAR2(16 BYTE),
  MAH_TIME              DATE,
  MAH_ACR_PRORATA       INTEGER,
  MAH_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  MAH_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  MAH_CREATE_USER       VARCHAR2(20 BYTE)       DEFAULT 'SYSTEM',
  MAH_UPDATE_USER       VARCHAR2(20 BYTE)       DEFAULT 'SYSTEM'
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX MI_ACR_INOUT_HISTORY_IDX01 ON MI_ACR_INOUT_HISTORY
(MAH_BATCH_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MI_ACR_INOUT_HISTORY ADD (
  CONSTRAINT MI_ACR_INOUT_HISTORY_FK01 
  FOREIGN KEY (MAH_BANK_ID) 
  REFERENCES MI_ENTITY_OPB (EO_OPB_ID)
  ENABLE VALIDATE,
  CONSTRAINT MI_ACR_INOUT_HISTORY_FK02 
  FOREIGN KEY (MAH_TXN_CODE) 
  REFERENCES TXN_CODE (TC_CODE)
  ENABLE VALIDATE,
  CONSTRAINT MI_ACR_INOUT_HISTORY_FK03 
  FOREIGN KEY (MAH_FUND_TYPE) 
  REFERENCES MI_DEF_ACR_DIRECTION (MAD_TYPE)
  ENABLE VALIDATE);

