OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmsTxnSupported
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmsTxnSupported.so
SOOBJS =  MmsTxnSupported.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
