ALTER TABLE DEF_SUB_STATUS
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_SUB_STATUS CASCADE CONSTRAINTS;

CREATE TABLE DEF_SUB_STATUS
(
  DS_SUB_STATUS        CHAR(3 BYTE),
  DS_NAME              VARCHAR2(50 BYTE),
  DS_CREATE_USER       VARCHAR2(20 BYTE),
  DS_UPDATE_USER       VARCHAR2(20 BYTE),
  DS_CREATE_TIMESTAMP  DATE,
  DS_UPDATE_TIMESTAMP  DATE
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEF_SUB_STATUS_PK ON DEF_SUB_STATUS
(DS_SUB_STATUS)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_SUB_STATUS ADD (
  CONSTRAINT DEF_SUB_STATUS_PK
  PRIMARY KEY
  (DS_SUB_STATUS)
  USING INDEX DEF_SUB_STATUS_PK
  ENABLE VALIDATE);

