ALTER TABLE MERCHANT_UPLOAD_FILE_HEADER
 DROP PRIMARY KEY CASCADE;

DROP TABLE MERCHANT_UPLOAD_FILE_HEADER CASCADE CONSTRAINTS;

CREATE TABLE MERCHANT_UPLOAD_FILE_HEADER
(
  UH_BATCH_ID          NUMBER(16,0),
  UH_MERCHANT_ID       VARCHAR(15 BYTE),
  UH_SERVICE_CODE      VARCHAR(3 BYTE),
  UH_FILENAME	       VARCHAR2(25 BYTE),
  UH_FILENAME_PREFIX   VARCHAR2(12 BYTE),
  UH_TXN_COUNT         INTEGER,
  UH_TOTAL_TXN_AMT     NUMBER(14,2),
  UH_IMPORT_ERROR_CODE VARCHAR(4 BYTE),
  UH_DISABLED          INTEGER                  DEFAULT 0,
  UH_TXN_ID            VARCHAR2(16 BYTE),
  UH_POSTING_DATE       VARCHAR2(8 BYTE),
  UH_STATUS	       INTEGER,
  UH_CREATE_USER       VARCHAR2(20 BYTE),
  UH_UPDATE_USER       VARCHAR2(20 BYTE),
  UH_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  UH_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX MERCHANT_UPLOAD_FILE_HD_IDX01 ON MERCHANT_UPLOAD_FILE_HEADER
(UH_MERCHANT_ID, UH_BATCH_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;



CREATE UNIQUE INDEX MERCHANT_UPLOAD_FILE_HEADER_PK ON MERCHANT_UPLOAD_FILE_HEADER
(UH_BATCH_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE MERCHANT_UPLOAD_FILE_HEADER ADD (
  CONSTRAINT MERCHANT_UPLOAD_FILE_HEADER_PK
  PRIMARY KEY
  (UH_BATCH_ID)
  USING INDEX MERCHANT_UPLOAD_FILE_HEADER_PK);
