OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/AutoSettlementExecLog
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBAutoSettlementExecLog.so
SOOBJS =  AutoSettlementExecLog.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
