OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLSignAuthParam
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLSignAuthParam.so
SOOBJS =  OLSignAuthParam.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
