OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLPspTxnSpcAction
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLPspTxnSpcAction.so
SOOBJS =  OLPspTxnSpcAction.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
