ALTER TABLE RULE_PSP_RELEASE_PERIOD
 DROP PRIMARY KEY CASCADE;

DROP TABLE RULE_PSP_RELEASE_PERIOD CASCADE CONSTRAINTS;

CREATE TABLE RULE_PSP_RELEASE_PERIOD
(
  RP_COUNTRY_ID        VARCHAR2(3 BYTE),
  RP_PSP_ID            VARCHAR2(10 BYTE),
  RP_DISABLED          INTEGER                  DEFAULT 0,
  RP_PERIOD            INTEGER,
  RP_CREATE_TIMESTAMP  DATE,
  RP_CREATE_USER       VARCHAR2(20 BYTE),
  RP_UPDATE_TIMESTAMP  DATE,
  RP_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX RULE_PSP_RELEASE_PERIOD_PK ON RULE_PSP_RELEASE_PERIOD
(RP_COUNTRY_ID, RP_PSP_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE RULE_PSP_RELEASE_PERIOD ADD (
  CONSTRAINT RULE_PSP_RELEASE_PERIOD_PK
  PRIMARY KEY
  (RP_COUNTRY_ID, RP_PSP_ID)
  USING INDEX RULE_PSP_RELEASE_PERIOD_PK);


