OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/CheckHandShake
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBCheckHandShake.so
SOOBJS =  CheckHandShake.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
