OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLAdjustmentType
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLAdjustmentType.so
SOOBJS =  OLAdjustmentType.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
