ALTER TABLE PSP_PAY_METHOD
 DROP PRIMARY KEY CASCADE;

DROP TABLE PSP_PAY_METHOD CASCADE CONSTRAINTS;

CREATE TABLE PSP_PAY_METHOD
(
  PP_COUNTRY           CHAR(2 BYTE),
  PP_PSP_ID            VARCHAR2(10 BYTE),
  PP_PAY_METHOD        VARCHAR2(4 BYTE),
  PP_DISABLED          INTEGER                  DEFAULT 0,
  PP_CREATE_USER       VARCHAR2(20 BYTE),
  PP_UPDATE_USER       VARCHAR2(20 BYTE),
  PP_CREATE_TIMESTAMP  DATE,
  PP_UPDATE_TIMESTAMP  DATE
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX PSP_PAY_METHOD ON PSP_PAY_METHOD
(PP_COUNTRY, PP_PSP_ID, PP_PAY_METHOD, PP_DISABLED)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PSP_PAY_METHOD_PK ON PSP_PAY_METHOD
(PP_COUNTRY, PP_PSP_ID, PP_PAY_METHOD)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE PSP_PAY_METHOD ADD (
  CONSTRAINT PSP_PAY_METHOD_PK
  PRIMARY KEY
  (PP_COUNTRY, PP_PSP_ID, PP_PAY_METHOD)
  USING INDEX PSP_PAY_METHOD_PK);

ALTER TABLE PSP_PAY_METHOD ADD (
  CONSTRAINT PSP_PAY_METHOD_FK01 
  FOREIGN KEY (PP_COUNTRY) 
  REFERENCES COUNTRY (COUNTRY_CODE),
  CONSTRAINT PSP_PAY_METHOD_FK02 
  FOREIGN KEY (PP_PSP_ID) 
  REFERENCES PSP_DETAIL (PSP_ID),
  CONSTRAINT PSP_PAY_METHOD_FK03 
  FOREIGN KEY (PP_PAY_METHOD) 
  REFERENCES DEF_PAY_METHOD (DP_CODE));

