ALTER TABLE MMS_ENTITY_NATURE_GRP
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_ENTITY_NATURE_GRP CASCADE CONSTRAINTS;

CREATE TABLE MMS_ENTITY_NATURE_GRP
(
  MENG_CODE_ID           VARCHAR2(5 BYTE),
  MENG_CODE_DESC         VARCHAR2(100 BYTE),
  MENG_DISPLAY_ORDER     INTEGER                   DEFAULT 0,
  MENG_CREATE_TIMESTAMP  DATE,
  MENG_CREATE_USER       VARCHAR2(20 BYTE),
  MENG_UPDATE_TIMESTAMP  DATE,
  MENG_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MMS_ENTITY_NATURE_GRP_PK ON MMS_ENTITY_NATURE_GRP
(MENG_CODE_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_ENTITY_NATURE_GRP ADD (
  CONSTRAINT MMS_ENTITY_NATURE_GRP_PK
  PRIMARY KEY
  (MENG_CODE_ID)
  USING INDEX MMS_ENTITY_NATURE_GRP_PK
  ENABLE VALIDATE);

