OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/TxnSetContributors
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBTxnSetContributors.so
SOOBJS =  TxnSetContributors.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
