ALTER TABLE PSP_RESTRICT_IP_REGION 
 DROP PRIMARY KEY CASCADE;

DROP TABLE PSP_RESTRICT_IP_REGION CASCADE CONSTRAINTS;

CREATE TABLE PSP_RESTRICT_IP_REGION 
(
  PIR_PSP_ID		VARCHAR2(10 BYTE), 
  PIR_REGION_CODE	VARCHAR2(2 BYTE), 
  PIR_DISABLED		INTEGER			DEFAULT 0, 
  PIR_CREATE_TIMESTAMP	DATE			DEFAULT sysdate, 
  PIR_CREATE_USER	VARCHAR2(20 BYTE), 
  PIR_UPDATE_TIMESTAMP	DATE			DEFAULT sysdate, 
  PIR_UPDATE_USER	VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA 
PCTUSED    0 
PCTFREE    10 
INITRANS   1 
MAXTRANS   255 
STORAGE    (
            INITIAL         64K 
            NEXT            1M 
            MINEXTENTS      1 
            MAXEXTENTS      UNLIMITED 
            PCTINCREASE     0 
            BUFFER_POOL     DEFAULT
           ) 
LOGGING 
NOCOMPRESS 
NOCACHE 
MONITORING;

CREATE UNIQUE INDEX PSP_RESTRICT_IP_REGION_PK ON PSP_RESTRICT_IP_REGION 
(PIR_PSP_ID, PIR_REGION_CODE) 
LOGGING 
TABLESPACE USER_IDX 
PCTFREE    10 
INITRANS   2 
MAXTRANS   255 
STORAGE    (
            INITIAL          64K
            NEXT             1M 
            MINEXTENTS       1 
            MAXEXTENTS       UNLIMITED 
            PCTINCREASE      0 
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE PSP_RESTRICT_IP_REGION ADD (
  CONSTRAINT PSP_RESTRICT_IP_REGION_PK 
  PRIMARY KEY 
  (PIR_PSP_ID, PIR_REGION_CODE) 
  USING INDEX PSP_RESTRICT_IP_REGION_PK 
  ENABLE VALIDATE);

ALTER TABLE PSP_RESTRICT_IP_REGION ADD (
  CONSTRAINT PSP_RESTRICT_IP_REGION_FK01 
  FOREIGN KEY (PIR_PSP_ID) 
  REFERENCES PSP_DETAIL (PSP_ID) 
  ENABLE VALIDATE, 
  CONSTRAINT PSP_RESTRICT_IP_REGION_FK02 
  FOREIGN KEY (PIR_REGION_CODE) 
  REFERENCES DEF_IP_REGION (DIR_REGION_CODE) 
  ENABLE VALIDATE);
