/* soapStub.h
   Generated by gSOAP 2.8.14 from twv.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapStub_H
#define soapStub_H
#define SOAP_NAMESPACE_OF_ns1	"https://www.twv.com.tw/gps.new/sys/server_HK130501.php?wsdl"
#include "stdsoap2.h"
#if GSOAP_VERSION != 20814
# error "GSOAP VERSION MISMATCH IN GENERATED CODE: PLEASE REINSTALL PACKAGE"
#endif

#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE_ns1__DepositType
#define SOAP_TYPE_ns1__DepositType (7)
/* ns1:DepositType */
struct ns1__DepositType
{
	char *tid;	/* required element of type xsd:string */
	time_t req_USCOREtime;	/* required element of type xsd:dateTime */
	int status;	/* required element of type xsd:int */
	char *order_USCOREnum;	/* required element of type xsd:string */
	int pay_USCOREtype;	/* required element of type xsd:int */
	int amount;	/* required element of type xsd:int */
	char *bank_USCOREcode;	/* optional element of type xsd:string */
	char *bank_USCOREbranch;	/* optional element of type xsd:string */
	char *account_USCOREname;	/* optional element of type xsd:string */
	char *account_USCOREno;	/* optional element of type xsd:string */
	char *owner_USCOREid;	/* required element of type xsd:string */
	char *description;	/* required element of type xsd:string */
	int error_USCOREcode;	/* required element of type xsd:int */
	int batch_USCOREid;	/* required element of type xsd:int */
	time_t *fundin_USCOREdate;	/* optional element of type xsd:dateTime */
	int *service_USCOREfee;	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__WithdrawType
#define SOAP_TYPE_ns1__WithdrawType (11)
/* ns1:WithdrawType */
struct ns1__WithdrawType
{
	char *tid;	/* required element of type xsd:string */
	time_t req_USCOREtime;	/* required element of type xsd:dateTime */
	int status;	/* required element of type xsd:int */
	int batch_USCOREid;	/* required element of type xsd:int */
	char *order_USCOREnum;	/* required element of type xsd:string */
	int amount;	/* required element of type xsd:int */
	char *bank_USCOREcode;	/* required element of type xsd:string */
	char *bank_USCOREbranch;	/* required element of type xsd:string */
	char *account_USCOREid;	/* required element of type xsd:string */
	char *account_USCOREname;	/* required element of type xsd:string */
	char *account_USCOREno;	/* required element of type xsd:string */
	int *error_USCOREcode;	/* optional element of type xsd:int */
	time_t *fundout_USCOREdate;	/* optional element of type xsd:dateTime */
	int *service_USCOREfee;	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__WithdrawInitInfo
#define SOAP_TYPE_ns1__WithdrawInitInfo (12)
/* ns1:WithdrawInitInfo */
struct ns1__WithdrawInitInfo
{
	char *order_USCOREnum;	/* required element of type xsd:string */
	char *bank_USCOREcode;	/* required element of type xsd:string */
	char *bank_USCOREbranch;	/* required element of type xsd:string */
	char *account_USCOREid;	/* required element of type xsd:string */
	char *account_USCOREname;	/* required element of type xsd:string */
	char *account_USCOREno;	/* required element of type xsd:string */
	int amount;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__WithdrawInitResult
#define SOAP_TYPE_ns1__WithdrawInitResult (13)
/* ns1:WithdrawInitResult */
struct ns1__WithdrawInitResult
{
	char *tid;	/* required element of type xsd:string */
	char *order_USCOREnum;	/* required element of type xsd:string */
	int status;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_DepositTypeArray
#define SOAP_TYPE_DepositTypeArray (14)
/* SOAP encoded array of ns1:DepositType schema type: */
struct DepositTypeArray
{
	struct ns1__DepositType **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_WithdrawTypeArray
#define SOAP_TYPE_WithdrawTypeArray (17)
/* SOAP encoded array of ns1:WithdrawType schema type: */
struct WithdrawTypeArray
{
	struct ns1__WithdrawType **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_WithdrawInitInfoArray
#define SOAP_TYPE_WithdrawInitInfoArray (20)
/* SOAP encoded array of ns1:WithdrawInitInfo schema type: */
struct WithdrawInitInfoArray
{
	struct ns1__WithdrawInitInfo **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_WithdrawInitResultArray
#define SOAP_TYPE_WithdrawInitResultArray (23)
/* SOAP encoded array of ns1:WithdrawInitResult schema type: */
struct WithdrawInitResultArray
{
	struct ns1__WithdrawInitResult **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_ns2__DepositOnlineInitResponse
#define SOAP_TYPE_ns2__DepositOnlineInitResponse (26)
/* ns2:DepositOnlineInitResponse */
struct ns2__DepositOnlineInitResponse
{
	int status;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
	char *tid;	/* optional element of type xsd:string */
	char *deposit_USCOREurl;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns2__DepositOnlineInit
#define SOAP_TYPE_ns2__DepositOnlineInit (29)
/* ns2:DepositOnlineInit */
struct ns2__DepositOnlineInit
{
	char *access_USCOREkey;	/* optional element of type xsd:string */
	char *order_USCOREnum;	/* optional element of type xsd:string */
	int amount;	/* required element of type xsd:int */
	char *description;	/* optional element of type xsd:string */
	char *return_USCOREurl;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns2__DepositIbonInitResponse
#define SOAP_TYPE_ns2__DepositIbonInitResponse (30)
/* ns2:DepositIbonInitResponse */
struct ns2__DepositIbonInitResponse
{
	int status;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
	struct ns1__DepositType *deposit;	/* optional element of type ns1:DepositType */
};
#endif

#ifndef SOAP_TYPE_ns2__DepositIbonInit
#define SOAP_TYPE_ns2__DepositIbonInit (33)
/* ns2:DepositIbonInit */
struct ns2__DepositIbonInit
{
	char *access_USCOREkey;	/* optional element of type xsd:string */
	char *order_USCOREnum;	/* optional element of type xsd:string */
	char *owner_USCOREid;	/* optional element of type xsd:string */
	int amount;	/* required element of type xsd:int */
	char *description;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns2__WithdrawInitResponse
#define SOAP_TYPE_ns2__WithdrawInitResponse (34)
/* ns2:WithdrawInitResponse */
struct ns2__WithdrawInitResponse
{
	int status;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
	int batch_USCOREid;	/* required element of type xsd:int */
	struct WithdrawInitResultArray *result_USCORElist;	/* optional element of type ArrayOfWithdrawInitResult */
};
#endif

#ifndef SOAP_TYPE_ns2__WithdrawInit
#define SOAP_TYPE_ns2__WithdrawInit (39)
/* ns2:WithdrawInit */
struct ns2__WithdrawInit
{
	char *access_USCOREkey;	/* optional element of type xsd:string */
	struct WithdrawInitInfoArray *withdraw_USCORElist;	/* optional element of type ArrayOfWithdrawInitInfo */
};
#endif

#ifndef SOAP_TYPE_ns2__DepositInquiryResponse
#define SOAP_TYPE_ns2__DepositInquiryResponse (40)
/* ns2:DepositInquiryResponse */
struct ns2__DepositInquiryResponse
{
	int status;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
	struct ns1__DepositType *deposit;	/* optional element of type ns1:DepositType */
};
#endif

#ifndef SOAP_TYPE_ns2__DepositInquiry
#define SOAP_TYPE_ns2__DepositInquiry (43)
/* ns2:DepositInquiry */
struct ns2__DepositInquiry
{
	char *access_USCOREkey;	/* optional element of type xsd:string */
	char *tid;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns2__WithdrawInquiryResponse
#define SOAP_TYPE_ns2__WithdrawInquiryResponse (44)
/* ns2:WithdrawInquiryResponse */
struct ns2__WithdrawInquiryResponse
{
	int status;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
	struct ns1__WithdrawType *withdraw;	/* optional element of type ns1:WithdrawType */
};
#endif

#ifndef SOAP_TYPE_ns2__WithdrawInquiry
#define SOAP_TYPE_ns2__WithdrawInquiry (47)
/* ns2:WithdrawInquiry */
struct ns2__WithdrawInquiry
{
	char *access_USCOREkey;	/* optional element of type xsd:string */
	char *tid;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns2__PingAliveResponse
#define SOAP_TYPE_ns2__PingAliveResponse (49)
/* ns2:PingAliveResponse */
struct ns2__PingAliveResponse
{
	int *status;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns2__PingAlive
#define SOAP_TYPE_ns2__PingAlive (50)
/* ns2:PingAlive */
struct ns2__PingAlive
{
	char *access_USCOREkey;	/* optional element of type xsd:string */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (51)
/* SOAP Header: */
struct SOAP_ENV__Header
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (52)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (54)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
	char *__any;
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (57)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (58)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Server-Side Operations                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 ns2__DepositOnlineInit(struct soap*, char *access_USCOREkey, char *order_USCOREnum, int amount, char *description, char *return_USCOREurl, struct ns2__DepositOnlineInitResponse *_param_1);

SOAP_FMAC5 int SOAP_FMAC6 ns2__DepositIbonInit(struct soap*, char *access_USCOREkey, char *order_USCOREnum, char *owner_USCOREid, int amount, char *description, struct ns2__DepositIbonInitResponse *_param_2);

SOAP_FMAC5 int SOAP_FMAC6 ns2__WithdrawInit(struct soap*, char *access_USCOREkey, struct WithdrawInitInfoArray *withdraw_USCORElist, struct ns2__WithdrawInitResponse *_param_3);

SOAP_FMAC5 int SOAP_FMAC6 ns2__DepositInquiry(struct soap*, char *access_USCOREkey, char *tid, struct ns2__DepositInquiryResponse *_param_4);

SOAP_FMAC5 int SOAP_FMAC6 ns2__WithdrawInquiry(struct soap*, char *access_USCOREkey, char *tid, struct ns2__WithdrawInquiryResponse *_param_5);

SOAP_FMAC5 int SOAP_FMAC6 ns2__PingAlive(struct soap*, char *access_USCOREkey, int *status);

/******************************************************************************\
 *                                                                            *
 * Server-Side Skeletons to Invoke Service Operations                         *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__DepositOnlineInit(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__DepositIbonInit(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__WithdrawInit(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__DepositInquiry(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__WithdrawInquiry(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__PingAlive(struct soap*);

/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stubs                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__DepositOnlineInit(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *access_USCOREkey, char *order_USCOREnum, int amount, char *description, char *return_USCOREurl, struct ns2__DepositOnlineInitResponse *_param_1);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__DepositIbonInit(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *access_USCOREkey, char *order_USCOREnum, char *owner_USCOREid, int amount, char *description, struct ns2__DepositIbonInitResponse *_param_2);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__WithdrawInit(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *access_USCOREkey, struct WithdrawInitInfoArray *withdraw_USCORElist, struct ns2__WithdrawInitResponse *_param_3);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__DepositInquiry(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *access_USCOREkey, char *tid, struct ns2__DepositInquiryResponse *_param_4);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__WithdrawInquiry(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *access_USCOREkey, char *tid, struct ns2__WithdrawInquiryResponse *_param_5);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__PingAlive(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *access_USCOREkey, int *status);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
