/* twv.h
   Generated by wsdl2h 2.8.14 from server_HK130501.php?wsdl and typemap.dat
   2013-05-16 08:50:46 GMT

   DO NOT INCLUDE THIS FILE DIRECTLY INTO YOUR PROJECT BUILDS
   USE THE soapcpp2-GENERATED SOURCE CODE FILES FOR YOUR PROJECT BUILDS

   gSOAP XML Web services tools.
   Copyright (C) 2000-2013 Robert van Engelen, Genivia Inc. All Rights Reserved.
   Part of this software is released under one of the following licenses:
   GPL or Genivia's license for commercial use.
*/

/** @page page_notes Usage Notes

NOTE:

 - Run soapcpp2 on twv.h to generate the SOAP/XML processing logic.
   Use soapcpp2 -I to specify paths for #import
   To build with STL, 'stlvector.h' is imported from 'import' dir in package.
   Use soapcpp2 -j to generate improved proxy and server classes.
 - Use wsdl2h -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Use Doxygen (www.doxygen.org) on this file to generate documentation.
 - Use wsdl2h -nname to use name as the base namespace prefix instead of 'ns'.
 - Use wsdl2h -Nname for service prefix and produce multiple service bindings
 - Use wsdl2h -d to enable DOM support for xsd:anyType.
 - Use wsdl2h -g to auto-generate readers and writers for root elements.
 - Use wsdl2h -b to auto-generate bi-directional operations (duplex ops).
 - Struct/class members serialized as XML attributes are annotated with a '@'.
 - Struct/class members that have a special role are annotated with a '$'.

WARNING:

   DO NOT INCLUDE THIS ANNOTATED FILE DIRECTLY IN YOUR PROJECT SOURCE CODE.
   USE THE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT'S SOURCE CODE:
   THE soapStub.h FILE CONTAINS THIS CONTENT WITHOUT ANNOTATIONS.

LICENSE:

@verbatim
--------------------------------------------------------------------------------
gSOAP XML Web services tools
Copyright (C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.

This software is released under one of the following two licenses:
GPL or Genivia's license for commercial use.
--------------------------------------------------------------------------------
GPL license.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place, Suite 330, Boston, MA 02111-1307 USA

Author contact information:
engelen@genivia.com / engelen@acm.org

This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial-use license is available from Genivia, Inc., contact@genivia.com
--------------------------------------------------------------------------------
@endverbatim

*/


//gsoapopt cw

/******************************************************************************\
 *                                                                            *
 * Definitions                                                                *
 *   https://www.twv.com.tw/gps.new/sys/server_HK130501.php?wsdl              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

ns1 = "https://www.twv.com.tw/gps.new/sys/server_HK130501.php?wsdl"

*/

#define SOAP_NAMESPACE_OF_ns1	"https://www.twv.com.tw/gps.new/sys/server_HK130501.php?wsdl"
//gsoap ns1   schema namespace:	https://www.twv.com.tw/gps.new/sys/server_HK130501.php?wsdl
//gsoap ns1   schema form:	unqualified

/******************************************************************************\
 *                                                                            *
 * Built-in Schema Types and Top-Level Elements and Attributes                *
 *                                                                            *
\******************************************************************************/



/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   https://www.twv.com.tw/gps.new/sys/server_HK130501.php?wsdl              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   https://www.twv.com.tw/gps.new/sys/server_HK130501.php?wsdl              *
 *                                                                            *
\******************************************************************************/


/// "https://www.twv.com.tw/gps.new/sys/server_HK130501.php?wsdl":DepositType is a complexType.
struct ns1__DepositType
{
/// Element tid of type xs:string.
    char*                                tid                            1;	///< Required element.
/// Element req_time of type xs:dateTime.
    time_t                               req_USCOREtime                 1;	///< Required element.
/// Element status of type xs:int.
    int                                  status                         1;	///< Required element.
/// Element order_num of type xs:string.
    char*                                order_USCOREnum                1;	///< Required element.
/// Element pay_type of type xs:int.
    int                                  pay_USCOREtype                 1;	///< Required element.
/// Element amount of type xs:int.
    int                                  amount                         1;	///< Required element.
/// Element bank_code of type xs:string.
    char*                                bank_USCOREcode               ;	///< Nillable pointer.
/// Element bank_branch of type xs:string.
    char*                                bank_USCOREbranch             ;	///< Nillable pointer.
/// Element account_name of type xs:string.
    char*                                account_USCOREname            ;	///< Nillable pointer.
/// Element account_no of type xs:string.
    char*                                account_USCOREno              ;	///< Nillable pointer.
/// Element owner_id of type xs:string.
    char*                                owner_USCOREid                 1;	///< Required element.
/// Element description of type xs:string.
    char*                                description                    1;	///< Required element.
/// Element error_code of type xs:int.
    int                                  error_USCOREcode               1;	///< Required element.
/// Element batch_id of type xs:int.
    int                                  batch_USCOREid                 1;	///< Required element.
/// Element fundin_date of type xs:dateTime.
    time_t*                              fundin_USCOREdate             ;	///< Nillable pointer.
/// Element service_fee of type xs:int.
    int*                                 service_USCOREfee             ;	///< Nillable pointer.
};

/// "https://www.twv.com.tw/gps.new/sys/server_HK130501.php?wsdl":WithdrawType is a complexType.
struct ns1__WithdrawType
{
/// Element tid of type xs:string.
    char*                                tid                            1;	///< Required element.
/// Element req_time of type xs:dateTime.
    time_t                               req_USCOREtime                 1;	///< Required element.
/// Element status of type xs:int.
    int                                  status                         1;	///< Required element.
/// Element batch_id of type xs:int.
    int                                  batch_USCOREid                 1;	///< Required element.
/// Element order_num of type xs:string.
    char*                                order_USCOREnum                1;	///< Required element.
/// Element amount of type xs:int.
    int                                  amount                         1;	///< Required element.
/// Element bank_code of type xs:string.
    char*                                bank_USCOREcode                1;	///< Required element.
/// Element bank_branch of type xs:string.
    char*                                bank_USCOREbranch              1;	///< Required element.
/// Element account_id of type xs:string.
    char*                                account_USCOREid               1;	///< Required element.
/// Element account_name of type xs:string.
    char*                                account_USCOREname             1;	///< Required element.
/// Element account_no of type xs:string.
    char*                                account_USCOREno               1;	///< Required element.
/// Element error_code of type xs:int.
    int*                                 error_USCOREcode              ;	///< Nillable pointer.
/// Element fundout_date of type xs:dateTime.
    time_t*                              fundout_USCOREdate            ;	///< Nillable pointer.
/// Element service_fee of type xs:int.
    int*                                 service_USCOREfee             ;	///< Nillable pointer.
};

/// "https://www.twv.com.tw/gps.new/sys/server_HK130501.php?wsdl":WithdrawInitInfo is a complexType.
struct ns1__WithdrawInitInfo
{
/// Element order_num of type xs:string.
    char*                                order_USCOREnum                1;	///< Required element.
/// Element bank_code of type xs:string.
    char*                                bank_USCOREcode                1;	///< Required element.
/// Element bank_branch of type xs:string.
    char*                                bank_USCOREbranch              1;	///< Required element.
/// Element account_id of type xs:string.
    char*                                account_USCOREid               1;	///< Required element.
/// Element account_name of type xs:string.
    char*                                account_USCOREname             1;	///< Required element.
/// Element account_no of type xs:string.
    char*                                account_USCOREno               1;	///< Required element.
/// Element amount of type xs:int.
    int                                  amount                         1;	///< Required element.
};

/// "https://www.twv.com.tw/gps.new/sys/server_HK130501.php?wsdl":WithdrawInitResult is a complexType.
struct ns1__WithdrawInitResult
{
/// Element tid of type xs:string.
    char*                                tid                            1;	///< Required element.
/// Element order_num of type xs:string.
    char*                                order_USCOREnum                1;	///< Required element.
/// Element status of type xs:int.
    int                                  status                         1;	///< Required element.
};

/// "https://www.twv.com.tw/gps.new/sys/server_HK130501.php?wsdl":DepositTypeArray is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of "https://www.twv.com.tw/gps.new/sys/server_HK130501.php?wsdl":DepositType
struct DepositTypeArray
{
/// Pointer to array of struct ns1__DepositType*.
    struct ns1__DepositType*            *__ptr                         ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};

/// "https://www.twv.com.tw/gps.new/sys/server_HK130501.php?wsdl":WithdrawTypeArray is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of "https://www.twv.com.tw/gps.new/sys/server_HK130501.php?wsdl":WithdrawType
struct WithdrawTypeArray
{
/// Pointer to array of struct ns1__WithdrawType*.
    struct ns1__WithdrawType*           *__ptr                         ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};

/// "https://www.twv.com.tw/gps.new/sys/server_HK130501.php?wsdl":WithdrawInitInfoArray is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of "https://www.twv.com.tw/gps.new/sys/server_HK130501.php?wsdl":WithdrawInitInfo
struct WithdrawInitInfoArray
{
/// Pointer to array of struct ns1__WithdrawInitInfo*.
    struct ns1__WithdrawInitInfo*       *__ptr                         ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};

/// "https://www.twv.com.tw/gps.new/sys/server_HK130501.php?wsdl":WithdrawInitResultArray is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of "https://www.twv.com.tw/gps.new/sys/server_HK130501.php?wsdl":WithdrawInitResult
struct WithdrawInitResultArray
{
/// Pointer to array of struct ns1__WithdrawInitResult*.
    struct ns1__WithdrawInitResult*     *__ptr                         ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};

/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   https://www.twv.com.tw/gps.new/sys/server_HK130501.php?wsdl              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   https://www.twv.com.tw/gps.new/sys/server_HK130501.php?wsdl              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/


//gsoap ns2  service name:	ntlHelperBinding 
//gsoap ns2  service type:	ntlHelperPortType 
//gsoap ns2  service port:	http://home.twv.com.tw/gps.new/sys/server_HK130501.php 
//gsoap ns2  service namespace:	https://www.twv.com.tw/gps.new/sys/server 
//gsoap ns2  service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage Service Definitions

@section Service_bindings Service Bindings

  - @ref ntlHelperBinding

@section Service_more More Information

  - @ref page_notes "Usage Notes"

  - @ref page_XMLDataBinding "XML Data Binding"

  - @ref SOAP_ENV__Header "SOAP Header Content" (when applicable)

  - @ref SOAP_ENV__Detail "SOAP Fault Detail Content" (when applicable)


*/

/**

@page ntlHelperBinding Binding "ntlHelperBinding"

@section ntlHelperBinding_operations Operations of Binding  "ntlHelperBinding"

  - @ref ns2__DepositOnlineInit

  - @ref ns2__DepositIbonInit

  - @ref ns2__WithdrawInit

  - @ref ns2__DepositInquiry

  - @ref ns2__WithdrawInquiry

  - @ref ns2__PingAlive

@section ntlHelperBinding_ports Endpoints of Binding  "ntlHelperBinding"

  - http://home.twv.com.tw/gps.new/sys/server_HK130501.php

Note: use wsdl2h option -Nname to change the service binding prefix name


*/

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   ntlHelperBinding                                                         *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   ns2__DepositOnlineInit                                                   *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "ns2__DepositOnlineInitResponse" of operation "ns2__DepositOnlineInit"
struct ns2__DepositOnlineInitResponse
{
    int                                 status;
    char*                               tid;
    char*                               deposit_USCOREurl;
};

/// Operation "ns2__DepositOnlineInit" of service binding "ntlHelperBinding"

/**

Operation details:

  - http://schemas.xmlsoap.org/soap/encoding/ RPC encodingStyle="SOAP"

  - Action: "https://www.twv.com.tw/gps.new/sys/server_ntl#DepositOnlineInit"

  - Addressing input action: "https://www.twv.com.tw/gps.new/sys/server_ntl#DepositOnlineInit"

  - Addressing output action: "https://www.twv.com.tw/gps.new/sys/server_ntl#DepositOnlineInitResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns2__DepositOnlineInit(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    char*                               access_USCOREkey,
    char*                               order_USCOREnum,
    int                                 amount,
    char*                               description,
    char*                               return_USCOREurl,
    // output parameters:
    struct ns2__DepositOnlineInitResponse*
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns2__DepositOnlineInit(
    struct soap *soap,
    // input parameters:
    char*                               access_USCOREkey,
    char*                               order_USCOREnum,
    int                                 amount,
    char*                               description,
    char*                               return_USCOREurl,
    // output parameters:
    struct ns2__DepositOnlineInitResponse*
  );
@endcode

*/

//gsoap ns2  service method-protocol:	DepositOnlineInit SOAP
//gsoap ns2  service method-style:	DepositOnlineInit rpc
//gsoap ns2  service method-encoding:	DepositOnlineInit http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns2  service method-input-action:	DepositOnlineInit https://www.twv.com.tw/gps.new/sys/server_ntl#DepositOnlineInit
//gsoap ns2  service method-output-action:	DepositOnlineInit https://www.twv.com.tw/gps.new/sys/server_ntl#DepositOnlineInitResponse
int ns2__DepositOnlineInit(
    char*                               access_USCOREkey,	///< Input parameter
    char*                               order_USCOREnum,	///< Input parameter
    int                                 amount,	///< Input parameter
    char*                               description,	///< Input parameter
    char*                               return_USCOREurl,	///< Input parameter
    struct ns2__DepositOnlineInitResponse*	///< Output response struct parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   ns2__DepositIbonInit                                                     *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "ns2__DepositIbonInitResponse" of operation "ns2__DepositIbonInit"
struct ns2__DepositIbonInitResponse
{
    int                                 status;
    struct ns1__DepositType*            deposit;
};

/// Operation "ns2__DepositIbonInit" of service binding "ntlHelperBinding"

/**

Operation details:

  - http://schemas.xmlsoap.org/soap/encoding/ RPC encodingStyle="SOAP"

  - Action: "https://www.twv.com.tw/gps.new/sys/server_ntl#DepositIbonInit"

  - Addressing input action: "https://www.twv.com.tw/gps.new/sys/server_ntl#DepositIbonInit"

  - Addressing output action: "https://www.twv.com.tw/gps.new/sys/server_ntl#DepositIbonInitResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns2__DepositIbonInit(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    char*                               access_USCOREkey,
    char*                               order_USCOREnum,
    char*                               owner_USCOREid,
    int                                 amount,
    char*                               description,
    // output parameters:
    struct ns2__DepositIbonInitResponse*
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns2__DepositIbonInit(
    struct soap *soap,
    // input parameters:
    char*                               access_USCOREkey,
    char*                               order_USCOREnum,
    char*                               owner_USCOREid,
    int                                 amount,
    char*                               description,
    // output parameters:
    struct ns2__DepositIbonInitResponse*
  );
@endcode

*/

//gsoap ns2  service method-protocol:	DepositIbonInit SOAP
//gsoap ns2  service method-style:	DepositIbonInit rpc
//gsoap ns2  service method-encoding:	DepositIbonInit http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns2  service method-input-action:	DepositIbonInit https://www.twv.com.tw/gps.new/sys/server_ntl#DepositIbonInit
//gsoap ns2  service method-output-action:	DepositIbonInit https://www.twv.com.tw/gps.new/sys/server_ntl#DepositIbonInitResponse
int ns2__DepositIbonInit(
    char*                               access_USCOREkey,	///< Input parameter
    char*                               order_USCOREnum,	///< Input parameter
    char*                               owner_USCOREid,	///< Input parameter
    int                                 amount,	///< Input parameter
    char*                               description,	///< Input parameter
    struct ns2__DepositIbonInitResponse*	///< Output response struct parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   ns2__WithdrawInit                                                        *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "ns2__WithdrawInitResponse" of operation "ns2__WithdrawInit"
struct ns2__WithdrawInitResponse
{
    int                                 status;
    int                                 batch_USCOREid;
    struct WithdrawInitResultArray*     result_USCORElist;
};

/// Operation "ns2__WithdrawInit" of service binding "ntlHelperBinding"

/**

Operation details:

  - http://schemas.xmlsoap.org/soap/encoding/ RPC encodingStyle="SOAP"

  - Action: "https://www.twv.com.tw/gps.new/sys/server_ntl#WithdrawInit"

  - Addressing input action: "https://www.twv.com.tw/gps.new/sys/server_ntl#WithdrawInit"

  - Addressing output action: "https://www.twv.com.tw/gps.new/sys/server_ntl#WithdrawInitResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns2__WithdrawInit(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    char*                               access_USCOREkey,
    struct WithdrawInitInfoArray*       withdraw_USCORElist,
    // output parameters:
    struct ns2__WithdrawInitResponse*
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns2__WithdrawInit(
    struct soap *soap,
    // input parameters:
    char*                               access_USCOREkey,
    struct WithdrawInitInfoArray*       withdraw_USCORElist,
    // output parameters:
    struct ns2__WithdrawInitResponse*
  );
@endcode

*/

//gsoap ns2  service method-protocol:	WithdrawInit SOAP
//gsoap ns2  service method-style:	WithdrawInit rpc
//gsoap ns2  service method-encoding:	WithdrawInit http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns2  service method-input-action:	WithdrawInit https://www.twv.com.tw/gps.new/sys/server_ntl#WithdrawInit
//gsoap ns2  service method-output-action:	WithdrawInit https://www.twv.com.tw/gps.new/sys/server_ntl#WithdrawInitResponse
int ns2__WithdrawInit(
    char*                               access_USCOREkey,	///< Input parameter
    struct WithdrawInitInfoArray*       withdraw_USCORElist,	///< Input parameter
    struct ns2__WithdrawInitResponse   *	///< Output response struct parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   ns2__DepositInquiry                                                      *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "ns2__DepositInquiryResponse" of operation "ns2__DepositInquiry"
struct ns2__DepositInquiryResponse
{
    int                                 status;
    struct ns1__DepositType*            deposit;
};

/// Operation "ns2__DepositInquiry" of service binding "ntlHelperBinding"

/**

Operation details:

  - http://schemas.xmlsoap.org/soap/encoding/ RPC encodingStyle="SOAP"

  - Action: "https://www.twv.com.tw/gps.new/sys/server_ntl#DepositInquiry"

  - Addressing input action: "https://www.twv.com.tw/gps.new/sys/server_ntl#DepositInquiry"

  - Addressing output action: "https://www.twv.com.tw/gps.new/sys/server_ntl#DepositInquiryResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns2__DepositInquiry(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    char*                               access_USCOREkey,
    char*                               tid,
    // output parameters:
    struct ns2__DepositInquiryResponse*
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns2__DepositInquiry(
    struct soap *soap,
    // input parameters:
    char*                               access_USCOREkey,
    char*                               tid,
    // output parameters:
    struct ns2__DepositInquiryResponse*
  );
@endcode

*/

//gsoap ns2  service method-protocol:	DepositInquiry SOAP
//gsoap ns2  service method-style:	DepositInquiry rpc
//gsoap ns2  service method-encoding:	DepositInquiry http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns2  service method-input-action:	DepositInquiry https://www.twv.com.tw/gps.new/sys/server_ntl#DepositInquiry
//gsoap ns2  service method-output-action:	DepositInquiry https://www.twv.com.tw/gps.new/sys/server_ntl#DepositInquiryResponse
int ns2__DepositInquiry(
    char*                               access_USCOREkey,	///< Input parameter
    char*                               tid,	///< Input parameter
    struct ns2__DepositInquiryResponse *	///< Output response struct parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   ns2__WithdrawInquiry                                                     *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "ns2__WithdrawInquiryResponse" of operation "ns2__WithdrawInquiry"
struct ns2__WithdrawInquiryResponse
{
    int                                 status;
    struct ns1__WithdrawType*           withdraw;
};

/// Operation "ns2__WithdrawInquiry" of service binding "ntlHelperBinding"

/**

Operation details:

  - http://schemas.xmlsoap.org/soap/encoding/ RPC encodingStyle="SOAP"

  - Action: "https://www.twv.com.tw/gps.new/sys/server_ntl#WithdrawInquiry"

  - Addressing input action: "https://www.twv.com.tw/gps.new/sys/server_ntl#WithdrawInquiry"

  - Addressing output action: "https://www.twv.com.tw/gps.new/sys/server_ntl#WithdrawInquiryResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns2__WithdrawInquiry(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    char*                               access_USCOREkey,
    char*                               tid,
    // output parameters:
    struct ns2__WithdrawInquiryResponse*
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns2__WithdrawInquiry(
    struct soap *soap,
    // input parameters:
    char*                               access_USCOREkey,
    char*                               tid,
    // output parameters:
    struct ns2__WithdrawInquiryResponse*
  );
@endcode

*/

//gsoap ns2  service method-protocol:	WithdrawInquiry SOAP
//gsoap ns2  service method-style:	WithdrawInquiry rpc
//gsoap ns2  service method-encoding:	WithdrawInquiry http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns2  service method-input-action:	WithdrawInquiry https://www.twv.com.tw/gps.new/sys/server_ntl#WithdrawInquiry
//gsoap ns2  service method-output-action:	WithdrawInquiry https://www.twv.com.tw/gps.new/sys/server_ntl#WithdrawInquiryResponse
int ns2__WithdrawInquiry(
    char*                               access_USCOREkey,	///< Input parameter
    char*                               tid,	///< Input parameter
    struct ns2__WithdrawInquiryResponse*	///< Output response struct parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   ns2__PingAlive                                                           *
 *                                                                            *
\******************************************************************************/


/// Operation "ns2__PingAlive" of service binding "ntlHelperBinding"

/**

Operation details:

  - http://schemas.xmlsoap.org/soap/encoding/ RPC encodingStyle="SOAP"

  - Action: "https://www.twv.com.tw/gps.new/sys/server_ntl#PingAlive"

  - Addressing input action: "https://www.twv.com.tw/gps.new/sys/server_ntl#PingAlive"

  - Addressing output action: "https://www.twv.com.tw/gps.new/sys/server_ntl#PingAliveResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns2__PingAlive(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    char*                               access_USCOREkey,
    // output parameters:
    int                                *status
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns2__PingAlive(
    struct soap *soap,
    // input parameters:
    char*                               access_USCOREkey,
    // output parameters:
    int                                *status
  );
@endcode

*/

//gsoap ns2  service method-protocol:	PingAlive SOAP
//gsoap ns2  service method-style:	PingAlive rpc
//gsoap ns2  service method-encoding:	PingAlive http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns2  service method-input-action:	PingAlive https://www.twv.com.tw/gps.new/sys/server_ntl#PingAlive
//gsoap ns2  service method-output-action:	PingAlive https://www.twv.com.tw/gps.new/sys/server_ntl#PingAliveResponse
int ns2__PingAlive(
    char*                               access_USCOREkey,	///< Input parameter
    int                                *status	///< Output parameter
);

/**

@page ntlHelperBinding Binding "ntlHelperBinding"

@section ntlHelperBinding_policy_enablers Policy Enablers of Binding  "ntlHelperBinding"

Based on policies, this service imports

  - WS-Policy reminders and enablers:
    - WS-Addressing 1.0 (2005/08, accepts 2004/08):
	@code
	#import "wsa5.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsaapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	// See the user guide gsoap/doc/wsa/html/index.html
	@endcode
    - WS-Addressing (2004/08):
	@code
	#import "wsa.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsaapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	// See the user guide gsoap/doc/wsa/html/index.html
	@endcode
    - WS-ReliableMessaging 1.0:
	@code
	#import "wsrm5.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsrmapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	soap_register_plugin(soap, soap_wsrm); // register the wsrm plugin in your code
	// See the user guide gsoap/doc/wsrm/html/index.html
	@endcode
    - WS-ReliableMessaging 1.1:
	@code
	#import "wsrm.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsrmapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	soap_register_plugin(soap, soap_wsrm); // register the wsrm plugin in your code
	// See the user guide gsoap/doc/wsrm/html/index.html
	@endcode
    - WS-Security (SOAP Message Security) 1.0 (accepts 1.1):
	@code
	#import "wsse.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsseapi.h"
	soap_register_plugin(soap, soap_wsse); // register the wsse plugin in your code
	// See the user guide gsoap/doc/wsse/html/index.html
	@endcode
    - WS-Security (SOAP Message Security) 1.1 (accepts 1.0):
	@code
	#import "wsse11.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsseapi.h"
	soap_register_plugin(soap, soap_wsse); // register the wsse plugin in your code
	// See the user guide gsoap/doc/wsse/html/index.html
	@endcode
    - HTTP Digest Authentication:
	@code
	#include "plugin/httpda.h"
	soap_register_plugin(soap, soap_http_da); // register the HTTP DA plugin in your code
	// See the user guide gsoap/doc/httpda/html/index.html
	@endcode
*/


/******************************************************************************\
 *                                                                            *
 * XML Data Binding                                                           *
 *                                                                            *
\******************************************************************************/


/**

@page page_XMLDataBinding XML Data Binding

SOAP/XML services use data bindings contractually bound by WSDL and auto-
generated by wsdl2h and soapcpp2 (see Service Bindings). Plain data bindings
are adopted from XML schemas as part of the WSDL types section or when running
wsdl2h on a set of schemas to produce non-SOAP-based XML data bindings.

The following readers and writers are C/C++ data type (de)serializers auto-
generated by wsdl2h and soapcpp2. Run soapcpp2 on this file to generate the
(de)serialization code, which is stored in soapC.c[pp]. Include "soapH.h" in
your code to import these data type and function declarations. Only use the
soapcpp2-generated files in your project build. Do not include the wsdl2h-
generated .h file in your code.

Data can be read in XML and deserialized from:
  - a file descriptor, using soap->recvfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->is = ...
  - a buffer, using the soap->frecv() callback

Data can be serialized in XML and written to:
  - a file descriptor, using soap->sendfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->os = ...
  - a buffer, using the soap->fsend() callback

The following options are available for (de)serialization control:
  - soap->encodingStyle = NULL; to remove SOAP 1.1/1.2 encodingStyle
  - soap_mode(soap, SOAP_XML_TREE); XML without id-ref (no cycles!)
  - soap_mode(soap, SOAP_XML_GRAPH); XML with id-ref (including cycles)
  - soap_set_namespaces(soap, struct Namespace *nsmap); to set xmlns bindings


@section ns1 Top-level root elements of schema "https://www.twv.com.tw/gps.new/sys/server_HK130501.php?wsdl"

*/

/* End of twv.h */
