OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmsTxnElement
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmsTxnElement.so
SOOBJS =  MmsTxnElement.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
