OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLPayoutReturnBatchDt
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLPayoutReturnBatchDt.so
SOOBJS =  OLPayoutReturnBatchDt.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
