ALTER TABLE PHUSER.MERCH_CURRENCY
 DROP PRIMARY KEY CASCADE;

DROP TABLE PHUSER.MERCH_CURRENCY CASCADE CONSTRAINTS;

CREATE TABLE PHUSER.MERCH_CURRENCY
(
  MERCHANT_ID       VARCHAR2(10 BYTE),
  CURRENCY_ID       VARCHAR2(3 BYTE),
  EFFECT_DATE       DATE,
  DISABLED          CHAR(1 BYTE),
  UPDATE_TIMESTAMP  DATE           DEFAULT sysdate,
  CREATE_TIMESTAMP  DATE           DEFAULT sysdate,
  UPDATE_USER       VARCHAR2(20 BYTE),
  CREATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;



CREATE UNIQUE INDEX PHUSER.MERCH_CURRENCY_PK ON PHUSER.MERCH_CURRENCY
(MERCHANT_ID, CURRENCY_ID, EFFECT_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE PHUSER.MERCH_CURRENCY ADD (
  CONSTRAINT MERCH_CURRENCY_PK
  PRIMARY KEY
  (MERCHANT_ID, CURRENCY_ID, EFFECT_DATE)
  USING INDEX PHUSER.MERCH_CURRENCY_PK);


