ALTER TABLE PRODUCT
 DROP PRIMARY KEY CASCADE;

DROP TABLE PRODUCT CASCADE CONSTRAINTS;

CREATE TABLE PRODUCT
(
  PRODUCT_CODE                CHAR(3 BYTE),
  NAME					 						VARCHAR2(50 BYTE),
  CREATE_TIMESTAMP          DATE	DEFAULT SYSDATE,
  UPDATE_TIMESTAMP          DATE	DEFAULT SYSDATE,
  DISABLED									INT	DEFAULT 0,
  CREATE_USER               VARCHAR2(20 BYTE),
  UPDATE_USER               VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX PRODUCT_PK ON PRODUCT
(PRODUCT_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE PRODUCT ADD (
  CONSTRAINT PRODUCT_PK
  PRIMARY KEY
  (PRODUCT_CODE)
  USING INDEX PRODUCT_PK);