OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnWebOnUs2HAI
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnWebOnUs2HAI.so
SOOBJS = TxnWebOnUs2HAI.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
