OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnWebOnUs2ESKY
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnWebOnUs2ESKY.so
SOOBJS = TxnWebOnUs2ESKY.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
