OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MiBatchDetail
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMiBatchDetail.so
SOOBJS =  MiBatchDetail.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
