
cd TxnCctByUsACK && make all && cd ..
cd TxnCctByUsRCK && make all && cd ..
cd TxnCctByUsSCK && make all && cd ..
cd TxnCctOnUsACK && make all && cd ..
cd TxnCctOnUsCCT && make all && cd ..
cd TxnCctOnUsCOM && make all && cd ..
cd TxnMgtByUs2Host && make all && cd ..
cd TxnMgtByUsCAS && make all && cd ..
cd TxnMgtByUsCDB && make all && cd ..
cd TxnMgtByUsCOM && make all && cd ..
cd TxnMgtByUsEFX && make all && cd ..
cd TxnMgtByUsGAB && make all && cd ..
cd TxnMgtByUsINQ && make all && cd ..
cd TxnMgtByUsJLA && make all && cd ..
cd TxnMgtByUsJLC && make all && cd ..
cd TxnMgtByUsJLD && make all && cd ..
cd TxnMgtByUsJLP && make all && cd ..
cd TxnMgtByUsJLR && make all && cd ..
cd TxnMgtByUsJLU && make all && cd ..
cd TxnMgtByUsNMA && make all && cd ..
cd TxnMgtByUsPAL && make all && cd ..
cd TxnMgtByUsPMA && make all && cd ..
cd TxnMgtByUsPOA && make all && cd ..
cd TxnMgtByUsPOC && make all && cd ..
cd TxnMgtByUsPOG && make all && cd ..
cd TxnMgtByUsPON && make all && cd ..
cd TxnMgtByUsPOP && make all && cd ..
cd TxnMgtByUsPOU && make all && cd ..
cd TxnMgtByUsPRC && make all && cd ..
cd TxnMgtByUsPSI && make all && cd ..
cd TxnMgtByUsPST && make all && cd ..
cd TxnMgtByUsRAG && make all && cd ..
cd TxnMgtByUsRAU && make all && cd ..
cd TxnMgtByUsRCB && make all && cd ..
cd TxnMgtByUsRCK && make all && cd ..
cd TxnMgtByUsSTA && make all && cd ..
cd TxnMgtByUsSTC && make all && cd ..
cd TxnMgtByUsSTD && make all && cd ..
cd TxnMgtByUsSTP && make all && cd ..
cd TxnMgtByUsSTR && make all && cd ..
cd TxnMgtByUsTFT && make all && cd ..
cd TxnMgtByUsTMA && make all && cd ..
cd TxnMgtByUsTMB && make all && cd ..
cd TxnMgtByUsTPI && make all && cd ..
cd TxnMgtByUsTSI && make all && cd ..
cd TxnMgtByUsVDS && make all && cd ..
cd TxnMgtByUsVOT && make all && cd ..
cd TxnMgtByUsVPO && make all && cd ..
cd TxnMgtByUsVST && make all && cd ..
cd TxnMmsByUsCOM && make all && cd ..
cd TxnMmsByUsRCK && make all && cd ..
cd TxnWebByUsACK && make all && cd ..
cd TxnWebByUsINQ && make all && cd ..
cd TxnWebByUsPOL && make all && cd ..
cd TxnWebByUsRCK && make all && cd ..
cd TxnWebByUsSCK && make all && cd ..
cd TxnWebOnUs2CCT && make all && cd ..
cd TxnWebOnUs2EEP && make all && cd ..
cd TxnWebOnUs2ESKY && make all && cd ..
cd TxnWebOnUs2HHP && make all && cd ..
cd TxnWebOnUs2HPY && make all && cd ..
cd TxnWebOnUs2LKP && make all && cd ..
cd TxnWebOnUs2PGN && make all && cd ..
cd TxnWebOnUs2TWV && make all && cd ..
cd TxnWebOnUs2YPY && make all && cd ..
cd TxnWebOnUsACK && make all && cd ..
cd TxnWebOnUsCOM && make all && cd ..
cd TxnWebOnUsDSI && make all && cd ..
cd TxnWebOnUsDSP && make all && cd ..
cd TxnWebOnUsDSR && make all && cd ..
cd TxnWebOnUsFEK && make all && cd ..
cd TxnWebOnUsPOL && make all && cd ..
cd TxnWebOnUsWTB && make all && cd ..
cd TxnWebOnUsWTD && make all && cd ..
cd TxnWebOnUsWTV && make all && cd ..
cd TxnXpyOnUsCOM && make all && cd ..
