DROP TABLE OL_PAYOUT_GENERATED_FILE_DT_PD CASCADE CONSTRAINTS;

CREATE TABLE OL_PAYOUT_GENERATED_FILE_DT_PD
(
  OFD_FILE_ID           NUMBER(16),
  OFD_BATCH_ID          NUMBER(16),
  OFD_SEQ_NUM           INTEGER,
  OFD_UPLOAD_TXN_ID     VARCHAR2(16 BYTE),
  OFD_TXN_ID            VARCHAR2(16 BYTE),
  OFD_AUX_TXN_ID        VARCHAR2(16 BYTE),
  OFD_STATUS            INTEGER,
  OFD_MERCHANT_REF      VARCHAR2(25 BYTE),
  OFD_COUNTRY           VARCHAR2(2 BYTE),
  OFD_IDENTITY_ID       VARCHAR2(25 BYTE),
  OFD_ACCOUNT_NUM       VARCHAR2(25 BYTE),
  OFD_ACCOUNT_NAME      VARCHAR2(100 BYTE),
  OFD_BANK_NAME         VARCHAR2(150 BYTE),
  OFD_BANK_CODE         VARCHAR2(25 BYTE),
  OFD_BRANCH            VARCHAR2(150 BYTE),
  OFD_PHONE_NUM         VARCHAR2(25 BYTE),
  OFD_PROVINCE          VARCHAR2(50 BYTE),
  OFD_CITY              VARCHAR2(100 BYTE),
  OFD_PAYOUT_AMOUNT     NUMBER(12,2),
  OFD_REQUEST_AMOUNT    NUMBER(12,2),
  OFD_PAYOUT_CURRENCY   VARCHAR2(3 BYTE),
  OFD_REQUEST_CURRENCY  VARCHAR2(3 BYTE),
  OFD_CREATE_USER       VARCHAR2(20 BYTE),
  OFD_CREATE_TIMESTAMP  DATE,
  OFD_UPDATE_USER       VARCHAR2(20 BYTE),
  OFD_UPDATE_TIMESTAMP  DATE,
  OFD_UNIQUE_AMOUNT     NUMBER(12,2),
  OFD_VERSION_NO        INTEGER
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

