OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLMerchantBalAcct
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLMerchantBalAcct.so
SOOBJS =  OLMerchantBalAcct.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
