OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/TxnlbStp
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBTxnLbStp.so
SOOBJS =  TxnLbStp.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
