ALTER TABLE OL_RULE_PAYOUT_PSP
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_RULE_PAYOUT_PSP CASCADE CONSTRAINTS;

CREATE TABLE OL_RULE_PAYOUT_PSP
(
  ORP_PSP_ID            VARCHAR2(50 BYTE),
  ORP_TO_BANK_CODE      VARCHAR2(10 BYTE),
  ORP_BANK_NAME         VARCHAR2(50 BYTE),
  ORP_OPERATOR_TYPE     CHAR(2 BYTE)            NOT NULL,
  ORP_TOTAL_AMT         NUMBER(12,2)            DEFAULT 0,
  ORP_PRIORITY          INTEGER,
  ORP_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  ORP_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  ORP_CREATE_USER       VARCHAR2(20 BYTE),
  ORP_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX OL_RULE_PAYOUT_PSP_IDX01 ON OL_RULE_PAYOUT_PSP
(ORP_PSP_ID, ORP_TO_BANK_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX OL_RULE_PAYOUT_PSP_PK ON OL_RULE_PAYOUT_PSP
(ORP_PSP_ID, ORP_TO_BANK_CODE, ORP_BANK_NAME)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_RULE_PAYOUT_PSP ADD (
  CONSTRAINT OL_RULE_PAYOUT_PSP_PK
  PRIMARY KEY
  (ORP_PSP_ID, ORP_TO_BANK_CODE, ORP_BANK_NAME)
  USING INDEX OL_RULE_PAYOUT_PSP_PK
  ENABLE VALIDATE);

ALTER TABLE OL_RULE_PAYOUT_PSP ADD (
  CONSTRAINT OL_RULE_PAYOUT_PSP_FK01 
  FOREIGN KEY (ORP_PSP_ID) 
  REFERENCES OL_PSP_DETAIL (OPD_PSP_ID)
  ENABLE VALIDATE,
  CONSTRAINT OL_RULE_PAYOUT_PSP_FK02 
  FOREIGN KEY (ORP_OPERATOR_TYPE) 
  REFERENCES RULE_OPERATOR_TYPE (ROT_TYPE)
  ENABLE VALIDATE);

