OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnOmtByUsORR
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnOmtByUsORR.so
SOOBJS = TxnOmtByUsORR.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
