ALTER TABLE RULE_CUSTOMER_TXN_CAP
 DROP PRIMARY KEY CASCADE;

DROP TABLE RULE_CUSTOMER_TXN_CAP CASCADE CONSTRAINTS;

CREATE TABLE RULE_CUSTOMER_TXN_CAP
(
  RC_COUNTRY           CHAR(2 BYTE),
  RC_CHANNEL_CODE      CHAR(3 BYTE),
  RC_TXN_CODE          CHAR(3 BYTE),
  RC_SERVICE_CODE      CHAR(3 BYTE),
  RC_PARTY_TYPE        CHAR(1 BYTE),
  RC_PARTY_ID          VARCHAR2(15 BYTE),
  RC_COUNTER_CATEGORY  VARCHAR2(3 BYTE),
  RC_DURATION          NUMBER(14,2),
  RC_VALUE             NUMBER(14,2),
  RC_DISABLED          INTEGER                  DEFAULT 0                     NOT NULL,
  RC_CREATE_USER       VARCHAR2(20 BYTE),
  RC_UPDATE_USER       VARCHAR2(20 BYTE),
  RC_CREATE_TIMESTAMP  DATE                     DEFAULT SYSDATE,
  RC_UPDATE_TIMESTAMP  DATE
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX RULE_CUSTOMER_TXN_CAP_IDX01 ON RULE_CUSTOMER_TXN_CAP
(RC_COUNTRY, RC_CHANNEL_CODE, RC_TXN_CODE, RC_SERVICE_CODE, RC_PARTY_TYPE, RC_PARTY_ID, RC_DISABLED)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RULE_CUSTOMER_TXN_CAP_PK ON RULE_CUSTOMER_TXN_CAP
(RC_COUNTRY, RC_CHANNEL_CODE, RC_TXN_CODE, RC_SERVICE_CODE, RC_PARTY_TYPE, 
RC_PARTY_ID, RC_COUNTER_CATEGORY)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE RULE_CUSTOMER_TXN_CAP ADD (
  CONSTRAINT RULE_CUSTOMER_TXN_CAP_PK
  PRIMARY KEY
  (RC_COUNTRY, RC_CHANNEL_CODE, RC_TXN_CODE, RC_SERVICE_CODE, RC_PARTY_TYPE, RC_PARTY_ID, RC_COUNTER_CATEGORY)
  USING INDEX RULE_CUSTOMER_TXN_CAP_PK
  ENABLE VALIDATE);

ALTER TABLE RULE_CUSTOMER_TXN_CAP ADD (
  CONSTRAINT RULE_CUSTOMER_TXN_CAP_FK01 
  FOREIGN KEY (RC_COUNTRY) 
  REFERENCES COUNTRY (COUNTRY_CODE)
  ENABLE VALIDATE,
  CONSTRAINT RULE_CUSTOMER_TXN_CAP_FK02 
  FOREIGN KEY (RC_CHANNEL_CODE) 
  REFERENCES DEF_CHANNEL (DC_CODE)
  ENABLE VALIDATE,
  CONSTRAINT RULE_CUSTOMER_TXN_CAP_FK03 
  FOREIGN KEY (RC_SERVICE_CODE) 
  REFERENCES DEF_SERVICE_CODE (SC_CODE)
  ENABLE VALIDATE,
  CONSTRAINT RULE_CUSTOMER_TXN_CAP_FK04 
  FOREIGN KEY (RC_COUNTER_CATEGORY) 
  REFERENCES DEF_COUNTER_CATEGORY (DC_TYPE)
  ENABLE VALIDATE);

