OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MerchantUploadFileDetail
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMerchantUploadFileDetail.so
SOOBJS =  MerchantUploadFileDetail.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
