


INSERT ALL
  into DEF_TXN_AMT_TYPE (DTA_TYPE, DTA_DESC, DTA_CREATE_USER, DTA_CREATE_TIMESTAMP, DTA_UPDATE_USER, DTA_UPDATE_TIMESTAMP)
       values ('T','Transaction Amount','SYSTEM',sysdate,'SYSTEM',sysdate)
  into DEF_TXN_AMT_TYPE (DTA_TYPE, DTA_DESC, DTA_CREATE_USER, DTA_CREATE_TIMESTAMP, DTA_UPDATE_USER, DTA_UPDATE_TIMESTAMP)
       values ('N','Net Amount','SYSTEM',sysdate,'SYSTEM',sysdate)
SELECT * FROM DUAL;

