DROP TABLE OL_TXN_WEB_LOG CASCADE CONSTRAINTS;

CREATE TABLE OL_TXN_WEB_LOG
(
  OTW_TXN_ID            VARCHAR2(16 BYTE),
  OTW_BANK_CODE         VARCHAR2(10 BYTE),
  OTW_LOGMSG            VARCHAR2(50 BYTE),
  OTW_SESSION_ID        VARCHAR2(32 BYTE),
  OTW_CREATE_USER       VARCHAR2(20 BYTE),
  OTW_UPDATE_USER       VARCHAR2(20 BYTE),
  OTW_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  OTW_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX OL_TXN_WEB_LOG_IDX01 ON OL_TXN_WEB_LOG
(OTW_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX OL_TXN_WEB_LOG_IDX02 ON OL_TXN_WEB_LOG
(OTW_CREATE_TIMESTAMP)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX OL_TXN_WEB_LOG_IDX03 ON OL_TXN_WEB_LOG
(OTW_SESSION_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_TXN_WEB_LOG ADD (
  CONSTRAINT OL_TXN_WEB_LOG_FK01 
  FOREIGN KEY (OTW_TXN_ID) 
  REFERENCES OL_TXN_HEADER (OTH_TXN_ID)
  ENABLE VALIDATE);

