OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/RuleSchedulerHeader
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBRuleSchedulerHeader.so
SOOBJS =  RuleSchedulerHeader.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
