OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmxNodes
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmxNodes.so
SOOBJS =  MmxNodes.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
