OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOOLMerchant
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOOLMerchant.so
SOOBJS = BOOLMerchant.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
