OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnMgtByUsVAD
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnMgtByUsVAD.so
SOOBJS = TxnMgtByUsVAD.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
