OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/Holiday
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBHoliday.so
SOOBJS =  Holiday.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
