ALTER TABLE OL_DEF_BAID_BAL_POOL
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_DEF_BAID_BAL_POOL CASCADE CONSTRAINTS;

CREATE TABLE OL_DEF_BAID_BAL_POOL
(
  BBP_TYPE              VARCHAR2(10 BYTE),
  BBP_DESC              VARCHAR2(50 BYTE),
  BBP_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  BBP_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  BBP_CREATE_USER       VARCHAR2(20 BYTE),
  BBP_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_DEF_BAID_BAL_POOL_PK ON OL_DEF_BAID_BAL_POOL
(BBP_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_DEF_BAID_BAL_POOL ADD (
  CONSTRAINT OL_DEF_BAID_BAL_POOL_PK
  PRIMARY KEY
  (BBP_TYPE)
  USING INDEX OL_DEF_BAID_BAL_POOL_PK
  ENABLE VALIDATE);

