OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLMerchantUploadFileDetail
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLMerchantUploadFileDetail.so
SOOBJS =  OLMerchantUploadFileDetail.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
