OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmsTxnCode
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmsTxnCode.so
SOOBJS =  MmsTxnCode.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
