OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/RuleDisabledBank
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBRuleDisabledBank.so
SOOBJS =  RuleDisabledBank.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
