OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/PaySelection
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBPaySelection.so
SOOBJS =  PaySelection.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
