DROP TABLE RULE_DISABLED_BANK CASCADE CONSTRAINTS;

CREATE TABLE RULE_DISABLED_BANK
(
  RB_BANK_CODE         VARCHAR2(10 BYTE)        NOT NULL,
  RB_TYPE              CHAR(1 BYTE)             NOT NULL,
  RB_CHANNEL_CODE      VARCHAR2(3 BYTE),
  RB_PARTY_ID          VARCHAR2(10 BYTE),
  RB_SCHEDULER_ID      INTEGER                  NOT NULL,
  RB_DISABLED          INTEGER                  DEFAULT 0,
  RB_CREATE_USER       VARCHAR2(20 BYTE),
  RB_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  RB_UPDATE_USER       VARCHAR2(20 BYTE),
  RB_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX RULE_DISABLED_BANK_IDX01 ON RULE_DISABLED_BANK
(RB_BANK_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX RULE_DISABLED_BANK_IDX02 ON RULE_DISABLED_BANK
(RB_SCHEDULER_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE RULE_DISABLED_BANK ADD (
  CONSTRAINT RULE_DISABLED_BANK_FK01 
  FOREIGN KEY (RB_SCHEDULER_ID) 
  REFERENCES RULE_SCHEDULER_HEADER (RS_SCHEDULER_ID)
  ENABLE VALIDATE,
  CONSTRAINT RULE_DISABLED_BANK_FK02 
  FOREIGN KEY (RB_TYPE) 
  REFERENCES DEF_PARTY_TYPE (DP_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT RULE_DISABLED_BANK_FK03 
  FOREIGN KEY (RB_BANK_CODE) 
  REFERENCES DEF_BANK (DB_INT_BANK_CODE)
  ENABLE VALIDATE);

