OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOOLStmtEngine
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOOLStmtEngine.so
SOOBJS = BOOLStmtEngine.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
