OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLBulkHeader
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLBulkHeader.so
SOOBJS =  OLBulkHeader.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
