

ALTER TABLE MI_DELIVERY_OUT_BATCH
 DROP PRIMARY KEY CASCADE;

DROP TABLE MI_DELIVERY_OUT_BATCH CASCADE CONSTRAINTS;

CREATE TABLE MI_DELIVERY_OUT_BATCH
(
  DOB_BATCH_ID          VARCHAR2(16 BYTE)       NOT NULL,
  DOB_TXN_ID            VARCHAR2(16 BYTE),
  DOB_SEQ               INTEGER                 NOT NULL,
  DOB_TXN_AMT           NUMBER(12,2),
  DOB_DELIVER_DATE      VARCHAR2(8 BYTE),
  DOB_AMTDIFF_REASON    VARCHAR2(10 BYTE),
  DOB_AMTDIFF_CCY       CHAR(3 BYTE),
  DOB_AMTDIFF_AMT       NUMBER(12,2),
  DOB_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  DOB_CREATE_USER       VARCHAR2(20 BYTE),
  DOB_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  DOB_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE INDEX MI_DELIVERY_OUT_BATCH_IDX01 ON MI_DELIVERY_OUT_BATCH
(DOB_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX MI_DELIVERY_OUT_BATCH_IDX02 ON MI_DELIVERY_OUT_BATCH
(DOB_CREATE_TIMESTAMP)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX MI_DELIVERY_OUT_BATCH_PK ON MI_DELIVERY_OUT_BATCH
(DOB_BATCH_ID, DOB_SEQ)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE MI_DELIVERY_OUT_BATCH ADD (
  CONSTRAINT MI_DELIVERY_OUT_BATCH_PK
  PRIMARY KEY
  (DOB_BATCH_ID, DOB_SEQ)
  USING INDEX MI_DELIVERY_OUT_BATCH_PK
  ENABLE VALIDATE);

ALTER TABLE MI_DELIVERY_OUT_BATCH ADD (
  CONSTRAINT MI_DELIVERY_OUT_BATCH_FK01 
  FOREIGN KEY (DOB_AMTDIFF_REASON) 
  REFERENCES MI_DEF_AR_BAL (AD_CODE)
  ENABLE VALIDATE);
