OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnWebOnUs2PGN
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnWebOnUs2PGN.so
SOOBJS = TxnWebOnUs2PGN.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
