OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLAcctStatusAction
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLAcctStatusAction.so
SOOBJS =  OLAcctStatusAction.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
