OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnMgtByUsCOM
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnMgtByUsCOM.so
SOOBJS = TxnMgtByUsCOM.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
