ALTER TABLE OL_MERCHANT_UPLOAD_FILE_DETAIL
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_MERCHANT_UPLOAD_FILE_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE OL_MERCHANT_UPLOAD_FILE_DETAIL
(
  OUD_BATCH_ID             NUMBER(16)            NOT NULL,
  OUD_TXN_ID               VARCHAR2(16 BYTE),
  OUD_AUX_TXN_ID           VARCHAR2(16 BYTE),
  OUD_SEQ_NUM              INTEGER               NOT NULL,
  OUD_MERCHANT_REF         VARCHAR2(25 BYTE)     NOT NULL,
  OUD_COUNTRY              VARCHAR2(2 BYTE)      NOT NULL,
  OUD_IDENTITY_ID          VARCHAR2(25 BYTE),
  OUD_ACCOUNT_NUM          VARCHAR2(25 BYTE)     NOT NULL,
  OUD_ACCOUNT_NAME         VARCHAR2(100 BYTE)     NOT NULL,
  OUD_BANK_NAME            VARCHAR2(150 BYTE)     NOT NULL,
  OUD_BANK_CODE            VARCHAR2(25 BYTE),
  OUD_BRANCH               VARCHAR2(100 BYTE)    NOT NULL,
  OUD_PHONE_NUM            VARCHAR2(25 BYTE),
  OUD_PROVINCE             VARCHAR2(50 BYTE),
  OUD_CITY                 VARCHAR2(100 BYTE),
  OUD_PAYOUT_AMOUNT        NUMBER(12,2)          DEFAULT 0,
  OUD_REQUEST_AMOUNT       NUMBER(12,2)          DEFAULT 0,
  OUD_PAYOUT_CURRENCY      VARCHAR2(3 BYTE),
  OUD_REQUEST_CURRENCY     VARCHAR2(3 BYTE),
  OUD_MEMBER_FEE_CCY       VARCHAR2(3 BYTE),
  OUD_MEMBER_FEE           NUMBER(12,2)          DEFAULT 0,
  OUD_MERCHANT_FEE_CCY     VARCHAR2(3 BYTE),
  OUD_MERCHANT_FEE         NUMBER(12,2)          DEFAULT 0,
  OUD_MARKUP_CCY           VARCHAR2(3 BYTE),
  OUD_MARKUP_AMT           NUMBER(12,2)          DEFAULT 0,
  OUD_EXCHANGE_RATE        NUMBER(14,5)          DEFAULT 1,
  OUD_PAYOUT_TXN_NUM       VARCHAR2(50 BYTE),
  OUD_STATUS               INTEGER,
  OUD_RESPONSE_CODE        VARCHAR2(6 BYTE),
  OUD_REMARK               VARCHAR2(255 BYTE),
  OUD_DISABLED             INTEGER               DEFAULT 0,
  OUD_BATCH_MODE           CHAR(1 BYTE),
  OUD_GENERATED_FILE_ID    NUMBER(16),
  OUD_GENERATED_FILE_NAME  VARCHAR2(50 BYTE),
  OUD_PSP_BATCH_ID         VARCHAR2(16 BYTE),
  OUD_FUNDOUT_DATE         VARCHAR2(14 BYTE),
  OUD_SERVICE_FEE          NUMBER(12,2),
  OUD_TID                  VARCHAR2(20 BYTE),
  OUD_PSP_ID               VARCHAR2(10 BYTE),
  OUD_APPROVE_ID           INTEGER,
  OUD_VNC_REF_NUM          VARCHAR2(16 BYTE),
  OUD_PREGEN_PSP_ID        VARCHAR2(10 BYTE),
  OUD_PREGEN_FILE_ID       NUMBER(16),
  OUD_PREAPPROVE_ID	  INTEGER,
  OUD_MERCHANT_PAYOUT_GRP  CHAR(1 BYTE),
  OUD_PSP_PAYOUT_GRP	   CHAR(1 BYTE),
  OUD_PREGEN_BANK_CODE     VARCHAR2(25 BYTE),
  OUD_CREATE_TIMESTAMP     DATE                  DEFAULT sysdate,
  OUD_UPDATE_TIMESTAMP     DATE                  DEFAULT sysdate,
  OUD_UPDATE_USER          VARCHAR2(20 BYTE),
  OUD_CREATE_USER          VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN OL_MERCHANT_UPLOAD_FILE_DETAIL.OUD_BATCH_MODE IS '''O'' - Online, ''F'' - Offline';



CREATE UNIQUE INDEX OL_MERCHANT_UPLOAD_FILE_DT_PK ON OL_MERCHANT_UPLOAD_FILE_DETAIL
(OUD_BATCH_ID, OUD_SEQ_NUM)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX OL_MERCH_UPLOAD_FILE_DT_IDX01 ON OL_MERCHANT_UPLOAD_FILE_DETAIL
(OUD_BATCH_ID, OUD_STATUS)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX OL_MERCH_UPLOAD_FILE_DT_IDX02 ON OL_MERCHANT_UPLOAD_FILE_DETAIL
(OUD_APPROVE_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX OL_MERCH_UPLOAD_FILE_DT_IDX03 ON OL_MERCHANT_UPLOAD_FILE_DETAIL
(OUD_BATCH_ID, OUD_BANK_NAME)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX OL_MERCH_UPLOAD_FILE_DT_IDX04 ON OL_MERCHANT_UPLOAD_FILE_DETAIL
(OUD_BATCH_ID, OUD_REQUEST_AMOUNT)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX OL_MERCH_UPLOAD_FILE_DT_IDX05 ON OL_MERCHANT_UPLOAD_FILE_DETAIL
(OUD_GENERATED_FILE_ID, OUD_STATUS)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX OL_MERCH_UPLOAD_FILE_DT_IDX06 ON OL_MERCHANT_UPLOAD_FILE_DETAIL
(OUD_BATCH_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX OL_MERCH_UPLOAD_FILE_DT_IDX07 ON OL_MERCHANT_UPLOAD_FILE_DETAIL
(OUD_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX OL_MERCH_UPLOAD_FILE_DT_IDX08 ON OL_MERCHANT_UPLOAD_FILE_DETAIL
(OUD_BATCH_ID, OUD_STATUS, OUD_BATCH_MODE, OUD_PSP_ID, OUD_DISABLED)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX OL_MERCH_UPLOAD_FILE_DT_IDX09 ON OL_MERCHANT_UPLOAD_FILE_DETAIL
(OUD_STATUS, OUD_BATCH_MODE, OUD_PSP_ID, OUD_DISABLED)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX OL_MERCH_UPLOAD_FILE_DT_IDX10 ON OL_MERCHANT_UPLOAD_FILE_DETAIL
(OUD_BATCH_ID, OUD_STATUS, OUD_DISABLED, OUD_BATCH_MODE, OUD_PREGEN_PSP_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX OL_MERCH_UPLOAD_FILE_DT_IDX11 ON OL_MERCHANT_UPLOAD_FILE_DETAIL
(OUD_STATUS, OUD_BATCH_MODE, OUD_DISABLED, OUD_PREGEN_PSP_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX OL_MERCH_UPLOAD_FILE_DT_IDX12 ON OL_MERCHANT_UPLOAD_FILE_DETAIL
(OUD_BATCH_ID, OUD_STATUS, OUD_DISABLED, OUD_BATCH_MODE, OUD_PREGEN_FILE_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX OL_MERCH_UPLOAD_FILE_DT_IDX13 ON OL_MERCHANT_UPLOAD_FILE_DETAIL
(OUD_STATUS, OUD_DISABLED, OUD_BATCH_MODE, OUD_PREGEN_FILE_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX OL_MERCH_UPLOAD_FILE_DT_IDX14 ON OL_MERCHANT_UPLOAD_FILE_DETAIL
(OUD_BATCH_ID, OUD_BANK_NAME, OUD_STATUS, OUD_BATCH_MODE, OUD_DISABLED, 
OUD_PSP_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX OL_MERCH_UPLOAD_FILE_DT_IDX15 ON OL_MERCHANT_UPLOAD_FILE_DETAIL
(OUD_PREGEN_FILE_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX OL_MERCH_UPLOAD_FILE_DT_IDX16 ON OL_MERCHANT_UPLOAD_FILE_DETAIL
(OUD_MERCHANT_REF, OUD_STATUS, OUD_DISABLED)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX OL_MERCH_UPLOAD_FILE_DT_IDX17 ON OL_MERCHANT_UPLOAD_FILE_DETAIL
(OUD_TXN_ID, OUD_STATUS, OUD_DISABLED)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_MERCHANT_UPLOAD_FILE_DETAIL ADD (
  CONSTRAINT OL_MERCHANT_UPLOAD_FILE_DT_PK
  PRIMARY KEY
  (OUD_BATCH_ID, OUD_SEQ_NUM)
  USING INDEX OL_MERCHANT_UPLOAD_FILE_DT_PK
  ENABLE VALIDATE);

