OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/ParClientMap
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBParClientMap.so
SOOBJS =  ParClientMap.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
