ALTER TABLE MI_ENTITY_TXN_CODE_MAP
 DROP PRIMARY KEY CASCADE;

DROP TABLE MI_ENTITY_TXN_CODE_MAP CASCADE CONSTRAINTS;

CREATE TABLE MI_ENTITY_TXN_CODE_MAP
(
  ETM_ENTITY_TYPE       CHAR(3 BYTE),
  ETM_TXN_CODE          CHAR(3 BYTE),
  ETM_DISABLED          INTEGER                 DEFAULT 0,
  ETM_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  ETM_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  ETM_CREATE_USER       VARCHAR2(20 BYTE),
  ETM_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MI_ENTITY_TXN_CODE_MAP_PK ON MI_ENTITY_TXN_CODE_MAP
(ETM_ENTITY_TYPE, ETM_TXN_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MI_ENTITY_TXN_CODE_MAP ADD (
  CONSTRAINT MI_ENTITY_TXN_CODE_MAP_PK
  PRIMARY KEY
  (ETM_ENTITY_TYPE, ETM_TXN_CODE)
  USING INDEX MI_ENTITY_TXN_CODE_MAP_PK
  ENABLE VALIDATE);

ALTER TABLE MI_ENTITY_TXN_CODE_MAP ADD (
  CONSTRAINT MI_ENTITY_TXN_CODE_MAP_FK01 
  FOREIGN KEY (ETM_ENTITY_TYPE) 
  REFERENCES MI_DEF_ENTITY_TYPE (ET_TYPE_CODE)
  ENABLE VALIDATE,
  CONSTRAINT MI_ENTITY_TXN_CODE_MAP_FK02 
  FOREIGN KEY (ETM_TXN_CODE) 
  REFERENCES TXN_CODE (TC_CODE)
  ENABLE VALIDATE);

