


CREATE TABLE OL_PAYOUT_API_BATCH_DT
(
  OAD_BATCH_ID          NUMBER(16),
  OAD_SEQ               INTEGER,
  OAD_TXN_ID            VARCHAR2(16 BYTE)       NOT NULL,
  OAD_RET_CODE          NUMBER(8),
  OAD_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate               NOT NULL,
  OAD_CREATE_USER       VARCHAR2(20 BYTE),
  OAD_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate               NOT NULL,
  OAD_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE INDEX OL_PAYOUT_API_BATCH_DT_IDX01 ON OL_PAYOUT_API_BATCH_DT
(OAD_CREATE_TIMESTAMP, OAD_UPDATE_TIMESTAMP)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX OL_PAYOUT_API_BATCH_DT_PK ON OL_PAYOUT_API_BATCH_DT
(OAD_BATCH_ID, OAD_SEQ)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX OL_PAYOUT_API_BATCH_DT_UK01 ON OL_PAYOUT_API_BATCH_DT
(OAD_BATCH_ID, OAD_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE OL_PAYOUT_API_BATCH_DT ADD (
  CONSTRAINT OL_PAYOUT_API_BATCH_DT_PK
  PRIMARY KEY
  (OAD_BATCH_ID, OAD_SEQ)
  USING INDEX OL_PAYOUT_API_BATCH_DT_PK
  ENABLE VALIDATE,
  CONSTRAINT OL_PAYOUT_API_BATCH_DT_UK01
  UNIQUE (OAD_BATCH_ID, OAD_TXN_ID)
  USING INDEX OL_PAYOUT_API_BATCH_DT_UK01
  ENABLE VALIDATE);
