


CREATE TABLE OL_PAYOUT_TXN_ACK_RETRY
(
  OAR_BATCH_TXN_ID         VARCHAR2(16 BYTE),
  OAR_TXN_ID               VARCHAR2(16 BYTE),
  OAR_STATUS               CHAR(1 BYTE),
  OAR_LOCAL_TM_DATE        VARCHAR2(8 BYTE),
  OAR_LOCAL_TM_TIME        VARCHAR2(6 BYTE),
  OAR_NEXT_TRY             DATE,
  OAR_CREATE_USER          VARCHAR2(20 BYTE),
  OAR_CREATE_TIMESTAMP     DATE                 DEFAULT sysdate               NOT NULL,
  OAR_UPDATE_USER          VARCHAR2(20 BYTE),
  OAR_UPDATE_TIMESTAMP     DATE                 DEFAULT sysdate               NOT NULL,
  OAR_RESEND_COUNT         INTEGER	DEFAULT	0,
  OAR_RESET_CNT_TIMESTAMP  DATE
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE INDEX OL_PAYOUT_TXN_ACK_RETRY_IDX01 ON OL_PAYOUT_TXN_ACK_RETRY
(OAR_NEXT_TRY)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX OL_PAYOUT_TXN_ACK_RETRY_PK ON OL_PAYOUT_TXN_ACK_RETRY
(OAR_BATCH_TXN_ID, OAR_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE OL_PAYOUT_TXN_ACK_RETRY ADD (
  CONSTRAINT OL_PAYOUT_TXN_ACK_RETRY_PK
  PRIMARY KEY
  (OAR_BATCH_TXN_ID, OAR_TXN_ID)
  USING INDEX OL_PAYOUT_TXN_ACK_RETRY_PK
  ENABLE VALIDATE);
