


CREATE TABLE PREGEN_RPT_PARAM
(
  PRP_CD                VARCHAR2(50 BYTE)        NOT NULL,
  PRP_DESC              VARCHAR2(250 BYTE)       NOT NULL,
  PRP_VAL               VARCHAR2(1024 BYTE),
  PRP_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  PRP_CREATE_USER       VARCHAR2(20 BYTE),
  PRP_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  PRP_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;


CREATE UNIQUE INDEX PREGEN_RPT_PARAM_PK ON PREGEN_RPT_PARAM
(PRP_CD)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE PREGEN_RPT_PARAM ADD (
  CONSTRAINT PREGEN_RPT_PARAM_PK
  PRIMARY KEY
  (PRP_CD)
  USING INDEX PREGEN_RPT_PARAM_PK
  ENABLE VALIDATE);
