OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MerchKeys
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMerchKeys.so
SOOBJS =  MerchKeys.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
