OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLTxnEngineSpcActionMap
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLTxnEngineSpcActionMap.so
SOOBJS =  OLTxnEngineSpcActionMap.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
