OBJHOME=$(HOME)/obj/BATCH
COMPHOME = $(HOME)/src/batch/report
COMPLIBHOME = $(HOME)/lib
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBatchExtractRptFC.so
SOOBJS =  extract_rptfc.o extract_rptfiles.o

include $(HOME)/config/Make.rules

LDLIBS += 

all     : $(COMPSO)
