OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MiEntityOpb
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMiEntityOpb.so
SOOBJS =  MiEntityOpb.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
