OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/TxnControl
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBTxnControl.so
SOOBJS =  TxnControl.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
