OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/PspUrl
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBPspUrl.so
SOOBJS =  PspUrl.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
