DROP TABLE BANK_MAPPING CASCADE CONSTRAINTS;

CREATE TABLE BANK_MAPPING
(
  BM_PSP_CHANNEL_ID    VARCHAR2(10 BYTE)        NOT NULL,
  BM_EXT_BANK_CODE     VARCHAR2(20 BYTE)        NOT NULL,
  BM_INT_BANK_CODE     VARCHAR2(10 BYTE)        NOT NULL,
  BM_COUNTRY           VARCHAR2(2 BYTE),
  BM_EFFECT_DATE       DATE                     NOT NULL,
  BM_DISABLED          VARCHAR2(1 BYTE)         NOT NULL,
  BM_CREATE_TIMESTAMP  DATE                     DEFAULT SYSDATE,
  BM_UPDATE_TIMESTAMP  DATE                     DEFAULT SYSDATE,
  BM_CREATE_USER       VARCHAR2(25 BYTE),
  BM_UPDATE_USER       VARCHAR2(25 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX BANK_MAPPING_IDX01 ON BANK_MAPPING
(BM_PSP_CHANNEL_ID, BM_INT_BANK_CODE, BM_EFFECT_DATE, BM_DISABLED)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX BANK_MAPPING_IDX02 ON BANK_MAPPING
(BM_PSP_CHANNEL_ID, BM_COUNTRY, BM_DISABLED)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

