ALTER TABLE PHUSER.BANK_MAPPING
 DROP PRIMARY KEY CASCADE;

DROP TABLE PHUSER.BANK_MAPPING CASCADE CONSTRAINTS;

CREATE TABLE PHUSER.BANK_MAPPING
(
  MAP_ID	      VARCHAR2(15 BYTE)         NOT NULL,
  PSP_CHANNEL_ID      VARCHAR2(10 BYTE)         NOT NULL,
  EXT_BANK_CODE       VARCHAR2(10 BYTE)         NOT NULL,
  INT_BANK_CODE	      VARCHAR2(10 BYTE)          NOT NULL,
  COUNTRY             VARCHAR2(2 BYTE),
  EFFECT_DATE         DATE                      NOT NULL,
  DISABLED            VARCHAR2(1 BYTE)          NOT NULL,
  CREATE_TIMESTAMP    DATE                      DEFAULT SYSDATE,
  UPDATE_TIMESTAMP    DATE                      DEFAULT SYSDATE,
  CREATE_USER         VARCHAR2(25 BYTE),
  UPDATE_USER         VARCHAR2(25 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PHUSER.BANK_MAPPING_PK ON PHUSER.BANK_MAPPING
(MAP_ID,PSP_CHANNEL_ID, EXT_BANK_CODE, EFFECT_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE PHUSER.BANK_MAPPING ADD (
  CONSTRAINT BANK_MAPPING_PK
  PRIMARY KEY
  (MAP_ID,PSP_CHANNEL_ID, EXT_BANK_CODE, EFFECT_DATE)
  USING INDEX PHUSER.BANK_MAPPING_PK);


