OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/RuleTxnRes
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBRuleTxnRes.so
SOOBJS =  RuleTxnRes.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
