OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/HoldAmount
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBHoldAmount.so
SOOBJS =  HoldAmount.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
