ALTER TABLE MI_ADJUSTMENT_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE MI_ADJUSTMENT_TYPE CASCADE CONSTRAINTS;

CREATE TABLE MI_ADJUSTMENT_TYPE
(
  MAT_ENTITY_TYPE       CHAR(3 BYTE),
  MAT_CODE              VARCHAR2(3 BYTE),
  MAT_CODE_IN_NUM       NUMBER(3),
  MAT_DESC              VARCHAR2(50 BYTE),
  MAT_AMT_TYPE          CHAR(2 BYTE),
  MAT_BAL_TYPE          CHAR(1 BYTE),
  MAT_NATURE            CHAR(1 BYTE),
  MAT_IS_PRORATA        INTEGER                 DEFAULT 0,
  MAT_DISABLED          INTEGER                 DEFAULT 0,
  MAT_CREATE_TIMESTAMP  DATE,
  MAT_UPDATE_TIMESTAMP  DATE,
  MAT_CREATE_USER       VARCHAR2(20 BYTE),
  MAT_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MI_ADJUSTMENT_TYPE_PK ON MI_ADJUSTMENT_TYPE
(MAT_ENTITY_TYPE, MAT_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MI_ADJUSTMENT_TYPE ADD (
  CONSTRAINT MI_ADJUSTMENT_TYPE_PK
  PRIMARY KEY
  (MAT_ENTITY_TYPE, MAT_CODE)
  USING INDEX MI_ADJUSTMENT_TYPE_PK
  ENABLE VALIDATE);

ALTER TABLE MI_ADJUSTMENT_TYPE ADD (
  CONSTRAINT MI_ADJUSTMENT_TYPE_FK01 
  FOREIGN KEY (MAT_ENTITY_TYPE) 
  REFERENCES MI_DEF_ENTITY_TYPE (ET_TYPE_CODE)
  ENABLE VALIDATE,
  CONSTRAINT MI_ADJUSTMENT_TYPE_FK02 
  FOREIGN KEY (MAT_AMT_TYPE) 
  REFERENCES DEF_AMT_TYPE (DA_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT MI_ADJUSTMENT_TYPE_FK03 
  FOREIGN KEY (MAT_BAL_TYPE) 
  REFERENCES MI_DEF_BALANCE_TYPE (BT_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT MI_ADJUSTMENT_TYPE_FK04 
  FOREIGN KEY (MAT_NATURE) 
  REFERENCES DEF_ADJUSTMENT_NATURE (DN_CODE)
  ENABLE VALIDATE);

