ALTER TABLE RULE_PAYOUT_PSP
 DROP PRIMARY KEY CASCADE;

DROP TABLE RULE_PAYOUT_PSP CASCADE CONSTRAINTS;

CREATE TABLE RULE_PAYOUT_PSP
(
  RP_PSP_ID        VARCHAR2(50 BYTE),
  RP_BANK_NAME     VARCHAR2(50 BYTE),
  RP_OPERATOR_TYPE     CHAR(2 BYTE) NOT NULL,
  RP_TOTAL_AMT         NUMBER(12,2)             DEFAULT 0,
  RP_PRIORITY	   INTEGER,
  RP_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  RP_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  RP_CREATE_USER       VARCHAR2(20 BYTE),
  RP_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX RULE_PAYOUT_PSP_IDX01 ON PHUSER.RULE_PAYOUT_PSP
(RP_PSP_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

CREATE UNIQUE INDEX RULE_PAYOUT_PSP_PK ON RULE_PAYOUT_PSP
(RP_PSP_ID, RP_BANK_NAME)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE RULE_PAYOUT_PSP ADD (
  CONSTRAINT RULE_PAYOUT_PSP_PK
  PRIMARY KEY
  (RP_PSP_ID, RP_BANK_NAME)
  USING INDEX RULE_PAYOUT_PSP_PK);

ALTER TABLE RULE_PAYOUT_PSP ADD (
  CONSTRAINT RULE_PAYOUT_PSP_FK01
  FOREIGN KEY (RP_PSP_ID)
  REFERENCES PSP_DETAIL (PSP_ID)
  ENABLE VALIDATE,
  CONSTRAINT RULE_PAYOUT_PSP_FK02
  FOREIGN KEY (RP_OPERATOR_TYPE)
  REFERENCES RULE_OPERATOR_TYPE (ROT_TYPE)
  ENABLE VALIDATE);

