OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/PspBalance
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBPspBalance.so
SOOBJS =  PspBalance.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
