ALTER TABLE OL_DEF_SUB_PROVIDER
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_DEF_SUB_PROVIDER CASCADE CONSTRAINTS;

CREATE TABLE OL_DEF_SUB_PROVIDER
(
  OSP_SUB_PROVIDER_ID    VARCHAR2(10 BYTE),
  OSP_SUB_PROVIDER_NAME  VARCHAR2(50 BYTE),
  OSP_DISABLED           INTEGER,
  OSP_CREATE_TIMESTAMP   DATE                   DEFAULT sysdate,
  OSP_UPDATE_TIMESTAMP   DATE                   DEFAULT sysdate,
  OSP_CREATE_USER        VARCHAR2(20 BYTE),
  OSP_UPDATE_USER        VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_DEF_SUB_PROVIDER_PK ON OL_DEF_SUB_PROVIDER
(OSP_SUB_PROVIDER_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_DEF_SUB_PROVIDER ADD (
  CONSTRAINT OL_DEF_SUB_PROVIDER_PK
  PRIMARY KEY
  (OSP_SUB_PROVIDER_ID)
  USING INDEX OL_DEF_SUB_PROVIDER_PK
  ENABLE VALIDATE);

