ALTER TABLE PAR_PRE_PO_REVERSED_HD
 DROP PRIMARY KEY CASCADE;

DROP TABLE PAR_PRE_PO_REVERSED_HD CASCADE CONSTRAINTS;

CREATE TABLE PAR_PRE_PO_REVERSED_HD
(
  PPH_FILE_ID           INTEGER,
  PPH_FILE_SEQ_NUM      INTEGER,
  PPH_CURRENCY          VARCHAR2(3 BYTE),
  PPH_FILE_STATUS       VARCHAR2(50 BYTE),
  PPH_FILE_DATE         VARCHAR2(8 BYTE),
  PPH_FILE_NAME         VARCHAR2(50 BYTE),
  PPH_FILE_PSP          VARCHAR2(50 BYTE),
  PPH_TOTAL_COUNT       INTEGER,
  PPH_TOTAL_AMOUNT      NUMBER(14,2),
  PPH_TOTAL_MEMBER_FEE  NUMBER(14,2),
  PPH_INTERNAL_IND      INTEGER,
  PPH_POST_DATE         DATE,
  PPH_UPDATE_DATE       DATE,
  PPH_UPLOAD_FILE_NAME  VARCHAR2(50 BYTE),
  PPH_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  PPH_CREATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX PAR_PRE_PO_REVERSED_HD_IDX01 ON PAR_PRE_PO_REVERSED_HD
(PPH_FILE_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;



