DROP TABLE OL_STMT_MATCH_FILTER CASCADE CONSTRAINTS;

CREATE TABLE OL_STMT_MATCH_FILTER
(
  OSMF_ACTION_FILTER_ID  INTEGER,
  OSMF_SEQUENCE          INTEGER,
  OSMF_GROUP             INTEGER,
  OSMF_PARTY             VARCHAR2(10 BYTE),
  OSMF_FILTER            VARCHAR2(20 BYTE),
  OSMF_OPERATOR          VARCHAR2(20 BYTE),
  OSMF_VALUE             VARCHAR2(50 BYTE),
  OSMF_FROM_INPUT        INTEGER                DEFAULT 0,
  OSMF_TO_OUTPUT         INTEGER                DEFAULT 0,
  OSMF_SPECIAL_HANDLING  VARCHAR2(50 BYTE),
  OSMF_DISABLED          INTEGER                DEFAULT 0,
  OSMF_CREATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  OSMF_CREATE_USER       VARCHAR2(20 BYTE),
  OSMF_UPDATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  OSMF_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX OL_STMT_MATCH_FILTER_IDX01 ON OL_STMT_MATCH_FILTER
(OSMF_ACTION_FILTER_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

