ALTER TABLE MMS_KEYS
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_KEYS CASCADE CONSTRAINTS;

CREATE TABLE MMS_KEYS
(
  MK_NODE_ID           VARCHAR2(5 BYTE),
  MK_KEY               VARCHAR2(3 BYTE),
  MK_KEY_VALUE         VARCHAR2(128 BYTE),
  MK_EFFECT_DATE       DATE,
  MK_DISABLED          INTEGER                  DEFAULT 0,
  MK_CREATE_USER       VARCHAR2(20 BYTE),
  MK_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  MK_UPDATE_USER       VARCHAR2(20 BYTE),
  MK_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MMS_KEYS_PK ON MMS_KEYS
(MK_NODE_ID, MK_KEY, MK_EFFECT_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_KEYS ADD (
  CONSTRAINT MMS_KEYS_PK
  PRIMARY KEY
  (MK_NODE_ID, MK_KEY, MK_EFFECT_DATE)
  USING INDEX MMS_KEYS_PK
  ENABLE VALIDATE);

