create or replace view REPORT_RPT002_view as 
/* Formatted on 7/25/2012 3:39:20 PM (QP5 v5.185.11230.41888) */
SELECT th_txn_id,
       tc_desc,
       th_client_id,
       client_name,
       th_merchant_id,
       name AS merchant_name,
       th_merchant_ref,
       tp_psp_id,
       psp_name,
       th_host_posting_date,
       th_transmission_datetime,
       td_txn_country,
       td_txn_ccy,
       th_transaction_amount,
       th_net_amount,
       th_reserve_amount,
       th_ex_rate,
       dm_status_desc as sub_status,
       ds_name as status,
       to_char(th_create_timestamp,'YYYYMMDDHH24MISS') as create_date,
       to_char(th_update_timestamp,'YYYYMMDDHH24MISS') as update_date,
       sc_desc as service_name,
       th_approval_date
  FROM txn_header,
       txn_detail,
       txn_psp_detail,
       merch_detail,
       txn_code,
       psp_detail,
       clients,
       def_service_code,
       def_sub_status,
       def_txn_status_map
where rownum = 1;
