ALTER TABLE EOD_REPORTS
 DROP PRIMARY KEY CASCADE;

DROP TABLE EOD_REPORTS CASCADE CONSTRAINTS;

CREATE TABLE EOD_REPORTS
(
  ER_ID                VARCHAR2(10 BYTE)        NOT NULL,
  ER_REPORT_NAME       VARCHAR2(200 BYTE)       NOT NULL,
  ER_ORDER_NUM         INTEGER,
  ER_DESC              VARCHAR2(500 BYTE),
  ER_RERUNABLE         CHAR(1 BYTE)         DEFAULT 'N'                   NOT NULL,
  ER_TYPE              CHAR(1 BYTE)         DEFAULT 'D'                   NOT NULL,
  ER_HOLD              CHAR(1 BYTE)         DEFAULT 'U'                   NOT NULL,
  ER_CREATE_USER       VARCHAR2(20 BYTE),
  ER_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  ER_UPDATE_USER       VARCHAR2(20 BYTE),
  ER_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN EOD_REPORTS.ER_RERUNABLE IS '''Y'' for Yes ''N'' for No';

COMMENT ON COLUMN EOD_REPORTS.ER_TYPE IS '''D'' for Daily ''M'' for Montly';

COMMENT ON COLUMN EOD_REPORTS.ER_HOLD IS '''Y'' for Yes';



CREATE UNIQUE INDEX EOD_REPORTS_IX01 ON EOD_REPORTS
(ER_ORDER_NUM)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX IDX_ER_ID ON EOD_REPORTS
(ER_REPORT_NAME)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PK_ER_ID ON EOD_REPORTS
(ER_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE EOD_REPORTS ADD (
  CONSTRAINT PK_ER_ID
  PRIMARY KEY
  (ER_ID)
  USING INDEX PK_ER_ID
  ENABLE VALIDATE,
  CONSTRAINT EOD_REPORTS_IX01
  UNIQUE (ER_ORDER_NUM)
  USING INDEX EOD_REPORTS_IX01
  ENABLE VALIDATE);

