ALTER TABLE EOD_REPORTS_STATUS
 DROP PRIMARY KEY CASCADE;

DROP TABLE EOD_REPORTS_STATUS CASCADE CONSTRAINTS;

CREATE TABLE EOD_REPORTS_STATUS
(
  ERS_REPORT_ID                  VARCHAR2(10 BYTE) NOT NULL,
  ERS_STATUS                     CHAR(1 BYTE)   DEFAULT 'N',
  ERS_RUN_DATE                   VARCHAR2(8 BYTE),
  ERS_RUN_TIMESTAMP              DATE           DEFAULT sysdate,
  ERS_RUN_COMPLETED_TIMESTAMP    DATE,
  ERS_RERUN_DATE                 VARCHAR2(8 BYTE),
  ERS_RERUN_TIMESTAMP            DATE,
  ERS_RERUN_COMPLETED_TIMESTAMP  DATE,
  ERS_CREATE_USER                VARCHAR2(20 BYTE),
  ERS_CREATE_TIMESTAMP           DATE           DEFAULT sysdate,
  ERS_UPDATE_USER                VARCHAR2(8 BYTE),
  ERS_UPDATE_TIMESTAMP           DATE           DEFAULT sysdate,
  ERS_REMARKS                    VARCHAR2(150 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN EOD_REPORTS_STATUS.ERS_STATUS IS '''N'' for New Cycle ,''C'' For Complete, ''P'' for Processing,''F'' for Failed';

COMMENT ON COLUMN EOD_REPORTS_STATUS.ERS_RUN_DATE IS 'Application Run Date';

COMMENT ON COLUMN EOD_REPORTS_STATUS.ERS_RUN_TIMESTAMP IS 'System Run Date';



CREATE UNIQUE INDEX PK_EOD_REPORTS_STATUS ON EOD_REPORTS_STATUS
(ERS_REPORT_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE EOD_REPORTS_STATUS ADD (
  CONSTRAINT PK_EOD_REPORTS_STATUS
  PRIMARY KEY
  (ERS_REPORT_ID)
  USING INDEX PK_EOD_REPORTS_STATUS
  ENABLE VALIDATE);

ALTER TABLE EOD_REPORTS_STATUS ADD (
  CONSTRAINT EOD_REPORTS_STATUS_FK01 
  FOREIGN KEY (ERS_REPORT_ID) 
  REFERENCES EOD_REPORTS (ER_ID)
  ENABLE VALIDATE);

