OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=manual_accept_fallback.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o manual_accept_fallback.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
