OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/TxnFeeChg
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBTxnFeeChg.so
SOOBJS =  TxnFeeChg.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
