ALTER TABLE OL_BAID_TXN_CODE
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_BAID_TXN_CODE CASCADE CONSTRAINTS;

CREATE TABLE OL_BAID_TXN_CODE
(
  OBTC_CODE              CHAR(3 BYTE),
  OBTC_DESC              VARCHAR2(50 BYTE),
  OBTC_VOIDABLE          INTEGER                   DEFAULT 0,
  OBTC_AMT_TYPE          CHAR(2 BYTE),
  OBTC_VOID_CODE         CHAR(3 BYTE),
  OBTC_CREATE_TIMESTAMP  DATE                      DEFAULT sysdate,
  OBTC_CREATE_USER       VARCHAR2(20 BYTE),
  OBTC_UPDATE_TIMESTAMP  DATE                      DEFAULT sysdate,
  OBTC_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_BAID_TXN_CODE_PK ON OL_BAID_TXN_CODE
(OBTC_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_BAID_TXN_CODE ADD (
  CONSTRAINT OL_BAID_TXN_CODE_PK
  PRIMARY KEY
  (OBTC_CODE)
  USING INDEX OL_BAID_TXN_CODE_PK
  ENABLE VALIDATE);

ALTER TABLE OL_BAID_TXN_CODE ADD (
  CONSTRAINT OL_BAID_TXN_CODE_FK01 
  FOREIGN KEY (OBTC_AMT_TYPE) 
  REFERENCES DEF_AMT_TYPE (DA_TYPE)
  ENABLE VALIDATE);

