OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/Transaction
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBTransaction.so
SOOBJS =  Transaction.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
