OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MiOLAdjustmentType
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMiOLAdjustmentType.so
SOOBJS =  MiOLAdjustmentType.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
