OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLProviderBalance
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLProviderBalance.so
SOOBJS =  OLProviderBalance.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
