OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOOLBankAccts
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOOLBankAccts.so
SOOBJS = BOOLBankAccts.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
