OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLRuleStatementPeriod
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLRuleStatementPeriod.so
SOOBJS =  OLRuleStatementPeriod.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
