OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BODeltaAmt
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBODeltaAmt.so
SOOBJS = BODeltaAmt.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
