OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnOmtByUsVPI
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnOmtByUsVPI.so
SOOBJS = TxnOmtByUsVPI.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
