OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLPayoutApiPregenDT
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLPayoutApiPregenDT.so
SOOBJS =  OLPayoutApiPregenDT.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
