


CREATE TABLE OL_PREGEN_RPT_PARAM
(
  OPRP_CD                VARCHAR2(50 BYTE)        NOT NULL,
  OPRP_DESC              VARCHAR2(250 BYTE)       NOT NULL,
  OPRP_VAL               VARCHAR2(1024 BYTE),
  OPRP_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  OPRP_CREATE_USER       VARCHAR2(20 BYTE),
  OPRP_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  OPRP_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;


CREATE UNIQUE INDEX OL_PREGEN_RPT_PARAM_PK ON OL_PREGEN_RPT_PARAM
(OPRP_CD)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE OL_PREGEN_RPT_PARAM ADD (
  CONSTRAINT OL_PREGEN_RPT_PARAM_PK
  PRIMARY KEY
  (OPRP_CD)
  USING INDEX OL_PREGEN_RPT_PARAM_PK
  ENABLE VALIDATE);
