ALTER TABLE OL_BANK_ACCT_STATUS_MAP
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_BANK_ACCT_STATUS_MAP CASCADE CONSTRAINTS;

CREATE TABLE OL_BANK_ACCT_STATUS_MAP
(
  SM_TYPE              VARCHAR2(1 BYTE),
  SM_STATUS            VARCHAR2(2 BYTE),
  SM_STATUS_DESC       VARCHAR2(50 BYTE),
  SM_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  SM_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  SM_CREATE_USER       VARCHAR2(20 BYTE),
  SM_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN OL_BANK_ACCT_STATUS_MAP.SM_TYPE IS 'M: Merchant; A: Admin';


CREATE UNIQUE INDEX OL_BANK_ACCT_STATUS_MAP_PK ON OL_BANK_ACCT_STATUS_MAP
(SM_TYPE, SM_STATUS)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_BANK_ACCT_STATUS_MAP ADD (
  CONSTRAINT OL_BANK_ACCT_STATUS_MAP_PK
  PRIMARY KEY
  (SM_TYPE, SM_STATUS)
  USING INDEX OL_BANK_ACCT_STATUS_MAP_PK
  ENABLE VALIDATE);

ALTER TABLE OL_BANK_ACCT_STATUS_MAP ADD (
  CONSTRAINT OL_BANK_ACCT_STATUS_MAP_FK01 
  FOREIGN KEY (SM_STATUS) 
  REFERENCES OL_DEF_ACCT_STATUS (AS_TYPE)
  ENABLE VALIDATE);

