OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=tpl_send_ol_sett_mail.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o tpl_send_ol_sett_mail.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash -lObjPtr
all: $(BATCHEXE)
