OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnOmtByUsMRP
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnOmtByUsMRP.so
SOOBJS = TxnOmtByUsMRP.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
