OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/IttTaskLog
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBIttTaskLog.so
SOOBJS =  IttTaskLog.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
