


ALTER TABLE DEF_PREGEN_RPT_STATUS
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_PREGEN_RPT_STATUS CASCADE CONSTRAINTS;

CREATE TABLE DEF_PREGEN_RPT_STATUS
(
  DS_TYPE              CHAR(1 BYTE)             NOT NULL,
  DS_DESC              VARCHAR2(50 BYTE),
  DS_CREATE_TIMESTAMP  DATE                     DEFAULT SYSDATE,
  DS_UPDATE_TIMESTAMP  DATE                     DEFAULT SYSDATE,
  DS_CREATE_USER       VARCHAR2(20 BYTE),
  DS_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DEF_PREGEN_RPT_STATUS_PK ON DEF_PREGEN_RPT_STATUS
(DS_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DEF_PREGEN_RPT_STATUS ADD (
  CONSTRAINT DEF_PREGEN_RPT_STATUS_PK
  PRIMARY KEY
  (DS_TYPE)
  USING INDEX DEF_PREGEN_RPT_STATUS_PK
  ENABLE VALIDATE);
