

CREATE TABLE DEF_DEPOSIT_CARD_TYPE_OPTION
(
  DO_CODE              CHAR(1 BYTE)             NOT NULL,
  DO_DESC              VARCHAR2(50 BYTE),
  DO_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  DO_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  DO_CREATE_USER       VARCHAR2(20 BYTE),
  DO_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEF_DEPOSIT_CARD_TYPE_OPT_PK ON DEF_DEPOSIT_CARD_TYPE_OPTION
(DO_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_DEPOSIT_CARD_TYPE_OPTION ADD (
  CONSTRAINT DEF_DEPOSIT_CARD_TYPE_OPT_PK
  PRIMARY KEY
  (DO_CODE)
  USING INDEX DEF_DEPOSIT_CARD_TYPE_OPT_PK
  ENABLE VALIDATE);

