ALTER TABLE PSP_TXN_CHECKING
 DROP PRIMARY KEY CASCADE;

DROP TABLE PSP_TXN_CHECKING CASCADE CONSTRAINTS;

CREATE TABLE PSP_TXN_CHECKING
(
  PC_PSP_ID              VARCHAR2(10 BYTE),
  PC_TXN_PERIOD          INTEGER,
  PC_PERIOD_FROM         INTEGER,
  PC_CHECK_PERIOD        INTEGER,
  PC_LAST_CHECKING_TIME  DATE,
  PC_COUNT               INTEGER,
  PC_THRESHOLD           INTEGER,
  PC_DISABLED            INTEGER                DEFAULT 0,
  PC_CREATE_USER         VARCHAR2(20 BYTE),
  PC_UPDATE_USER         VARCHAR2(20 BYTE),
  PC_CREATE_TIMESTAMP    DATE                   DEFAULT sysdate,
  PC_UPDATE_TIMESTAMP    DATE                   DEFAULT sysdate,
  PC_RATE                INTEGER,
  PC_RC_IND              CHAR(1 BYTE),
  PC_MIN_COUNT		 INTEGER		DEFAULT 0
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN PSP_TXN_CHECKING.PC_CHECK_PERIOD IS 'one unit for one minute';



CREATE INDEX PSP_TXN_CHECKING_IDX01 ON PSP_TXN_CHECKING
(PC_PSP_ID, PC_DISABLED)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX PSP_TXN_CHECKING_IDX02 ON PSP_TXN_CHECKING
(PC_LAST_CHECKING_TIME)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PSP_TXN_CHECKING_PK ON PSP_TXN_CHECKING
(PC_PSP_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PSP_TXN_CHECKING ADD (
  CONSTRAINT PSP_TXN_CHECKING_PK
  PRIMARY KEY
  (PC_PSP_ID)
  USING INDEX PSP_TXN_CHECKING_IDX01
  ENABLE VALIDATE);

