OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmsEntityOpb
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmsEntityOpb.so
SOOBJS =  MmsEntityOpb.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
