OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/RulePspReleasePeriod
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBRulePspReleasePeriod.so
SOOBJS =  RulePspReleasePeriod.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
