OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/TxnFeUrl
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBTxnFeUrl.so
SOOBJS =  TxnFeUrl.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
