OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOMMMCreditLimit
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOMMMCreditLimit.so
SOOBJS = BOMMMCreditLimit.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
