OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/FundsOutHistory
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBFundsOutHistory.so
SOOBJS =  FundsOutHistory.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
