OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnMgtByUsVDS
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnMgtByUsVDS.so
SOOBJS = TxnMgtByUsVDS.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
