ALTER TABLE DEF_BUSINESS_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_BUSINESS_TYPE CASCADE CONSTRAINTS;

CREATE TABLE DEF_BUSINESS_TYPE
(
  BT_TYPE              CHAR(1 BYTE),
  BT_DESC              VARCHAR2(50 BYTE),
  BT_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  BT_CREATE_USER       VARCHAR2(20 BYTE),
  BT_UPDATE_TIMESTAMP  DATE,
  BT_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEF_BUSINESS_TYPE_PK ON DEF_BUSINESS_TYPE
(BT_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_BUSINESS_TYPE ADD (
  CONSTRAINT BUSINESS_TYPE_PK
  PRIMARY KEY
  (BT_TYPE)
  USING INDEX DEF_BUSINESS_TYPE_PK);


