ALTER TABLE MERCHANT_SETTLEMENT_MODE
 DROP PRIMARY KEY CASCADE;

DROP TABLE MERCHANT_SETTLEMENT_MODE CASCADE CONSTRAINTS;

CREATE TABLE MERCHANT_SETTLEMENT_MODE
(
  MS_MERCHANT_ID       VARCHAR2(15 BYTE),
  MS_SERVICE_CODE      VARCHAR2(3 BYTE),
  MS_COUNTRY           CHAR(2 BYTE),
  MS_CURRENCY_ID       VARCHAR2(3 BYTE),
  MS_MODE              CHAR(1 BYTE)             NOT NULL,
  MS_MODE_ID           INTEGER                  DEFAULT 0,
  MS_DISABLED          INTEGER                  DEFAULT 0,
  MS_CREATE_TIMESTAMP  DATE                     DEFAULT SYSDATE,
  MS_UPDATE_TIMESTAMP  DATE                     DEFAULT SYSDATE,
  MS_CREATE_USER       VARCHAR2(20 BYTE),
  MS_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PHUSER.MERCHANT_SETTLEMENT_MODE_PK ON MERCHANT_SETTLEMENT_MODE
(MS_MERCHANT_ID, MS_SERVICE_CODE, MS_COUNTRY, MS_CURRENCY_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MERCHANT_SETTLEMENT_MODE ADD (
  CONSTRAINT MERCHANT_SETTLEMENT_MODE_PK
  PRIMARY KEY
  (MS_MERCHANT_ID, MS_SERVICE_CODE, MS_COUNTRY, MS_CURRENCY_ID)
  USING INDEX MERCHANT_SETTLEMENT_MODE_PK
  ENABLE VALIDATE);

