OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnMgtByUsJLA
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnMgtByUsJLA.so
SOOBJS = TxnMgtByUsJLA.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
