ALTER TABLE OL_PAYOUT_ACCT_WHITE_LIST
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_PAYOUT_ACCT_WHITE_LIST CASCADE CONSTRAINTS;

CREATE TABLE OL_PAYOUT_ACCT_WHITE_LIST
(
  OPW_MERCHANT_ID       VARCHAR2(15 BYTE),
  OPW_BANK_ACCT_NAME    VARCHAR2(100 BYTE),
  OPW_DISABLED          CHAR(1 BYTE)             DEFAULT 0,
  OPW_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  OPW_CREATE_USER       VARCHAR2(20 BYTE),
  OPW_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  OPW_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_PAYOUT_ACCT_WHITE_LIST_PK ON OL_PAYOUT_ACCT_WHITE_LIST
(OPW_MERCHANT_ID, OPW_BANK_ACCT_NAME)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_PAYOUT_ACCT_WHITE_LIST ADD (
  CONSTRAINT OL_PAYOUT_ACCT_WHITE_LIST_PK
  PRIMARY KEY
  (OPW_MERCHANT_ID, OPW_BANK_ACCT_NAME)
  USING INDEX OL_PAYOUT_ACCT_WHITE_LIST_PK
  ENABLE VALIDATE);

