OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmsEntityFXBal
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmsEntityFXBal.so
SOOBJS =  MmsEntityFXBal.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
