ALTER TABLE MERCHANT_SETTLEMENT_DETAIL
 ADD (SD_COUNTRY_SUBDIVISION  VARCHAR2(100 BYTE));

ALTER TABLE MERCHANT_SETTLEMENT_DETAIL
 ADD (SD_CITY  VARCHAR2(100 BYTE));

ALTER TABLE MERCHANT_SETTLEMENT_DETAIL
 ADD (SD_COUNTRY  VARCHAR2(50 BYTE));

