ALTER TABLE MMS_DEF_COST_CAL_METHOD
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_DEF_COST_CAL_METHOD CASCADE CONSTRAINTS;

CREATE TABLE MMS_DEF_COST_CAL_METHOD
(
  MCC_TYPE              CHAR(1 BYTE),
  MCC_DESC              VARCHAR2(50 BYTE),
  MCC_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  MCC_CREATE_USER       VARCHAR2(20 BYTE),
  MCC_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  MCC_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MMS_DEF_COST_CAL_METHOD_PK ON MMS_DEF_COST_CAL_METHOD
(MCC_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_DEF_COST_CAL_METHOD ADD (
  CONSTRAINT MMS_DEF_COST_CAL_METHOD_PK
  PRIMARY KEY
  (MCC_TYPE)
  USING INDEX MMS_DEF_COST_CAL_METHOD_PK
  ENABLE VALIDATE);

