ALTER TABLE PAR_PO_REVERSED_HD
 DROP PRIMARY KEY CASCADE;

DROP TABLE PAR_PO_REVERSED_HD CASCADE CONSTRAINTS;

CREATE TABLE PAR_PO_REVERSED_HD
(
  PRH_FILE_ID           INTEGER,
  PRH_FILE_SEQ_NUM      INTEGER,
  PRH_CURRENCY          VARCHAR2(3 BYTE),
  PRH_FILE_STATUS       VARCHAR2(50 BYTE),
  PRH_FILE_DATE         VARCHAR2(8 BYTE),
  PRH_FILE_NAME         VARCHAR2(50 BYTE),
  PRH_FILE_PSP          VARCHAR2(50 BYTE),
  PRH_TOTAL_COUNT       INTEGER,
  PRH_TOTAL_AMOUNT      NUMBER(14,2),
  PRH_TOTAL_MEMBER_FEE  NUMBER(14,2),
  PRH_INTERNAL_IND      INTEGER,
  PRH_POST_DATE         DATE,
  PRH_UPDATE_DATE       DATE,
  PRH_UPLOAD_FILE_NAME  VARCHAR2(50 BYTE),
  PRH_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  PRH_CREATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PAR_PO_REVERSED_HD_PK ON PAR_PO_REVERSED_HD
(PRH_FILE_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PAR_PO_REVERSED_HD ADD (
  CONSTRAINT PAR_PO_REVERSED_HD_PK
  PRIMARY KEY
  (PRH_FILE_ID)
  USING INDEX PAR_PO_REVERSED_HD_PK
  ENABLE VALIDATE);

