ALTER TABLE PAYOUT_QUEUE_DT
 DROP PRIMARY KEY CASCADE;

DROP TABLE PAYOUT_QUEUE_DT CASCADE CONSTRAINTS;

CREATE TABLE PAYOUT_QUEUE_DT
(
  PD_BATCH_ID          NUMBER(16)               NOT NULL,
  PD_SEQ_NUM           INTEGER                  NOT NULL,
  PD_TXN_ID            VARCHAR2(16 BYTE)        NOT NULL,
  PD_MERCHANT_REF      VARCHAR2(25 BYTE)        NOT NULL,
  PD_COUNTRY           VARCHAR2(2 BYTE),
  PD_IDENTITY_ID       VARCHAR2(25 BYTE),
  PD_ACCOUNT_NUM       VARCHAR2(25 BYTE)        NOT NULL,
  PD_ACCOUNT_NAME      VARCHAR2(100 BYTE)        NOT NULL,
  PD_BANK_NAME         VARCHAR2(50 BYTE),
  PD_BANK_CODE         VARCHAR2(25 BYTE),
  PD_BRANCH            VARCHAR2(100 BYTE)        NOT NULL,
  PD_PHONE_NUM         VARCHAR2(25 BYTE),
  PD_PROVINCE          VARCHAR2(50 BYTE),
  PD_CITY              VARCHAR2(100 BYTE),
  PD_AMOUNT            VARCHAR2(12 BYTE)        NOT NULL,
  PD_PAYOUT_CURRENCY   VARCHAR2(3 BYTE)         NOT NULL,
  PD_STATUS            CHAR(1 BYTE)             NOT NULL,
  PD_PSP_BATCH_ID      VARCHAR2(16 BYTE),
  PD_CREATE_USER       VARCHAR2(20 BYTE),
  PD_UPDATE_USER       VARCHAR2(20 BYTE),
  PD_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  PD_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PAYOUT_QUEUE_DT_PK ON PAYOUT_QUEUE_DT
(PD_BATCH_ID, PD_SEQ_NUM, PD_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PAYOUT_QUEUE_DT ADD (
  CONSTRAINT PAYOUT_QUEUE_DT_PK
  PRIMARY KEY
  (PD_BATCH_ID, PD_SEQ_NUM, PD_TXN_ID)
  USING INDEX PAYOUT_QUEUE_DT_PK
  ENABLE VALIDATE);

