ALTER TABLE OL_DEF_ENCRYPT_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_DEF_ENCRYPT_TYPE CASCADE CONSTRAINTS;

CREATE TABLE OL_DEF_ENCRYPT_TYPE
(
  ET_TYPE              VARCHAR2(2 BYTE),
  ET_DESC              VARCHAR2(50 BYTE),
  ET_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  ET_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  ET_CREATE_USER       VARCHAR2(20 BYTE),
  ET_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX OL_DEF_ENCRYPT_TYPE_PK ON OL_DEF_ENCRYPT_TYPE
(ET_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE OL_DEF_ENCRYPT_TYPE ADD (
  CONSTRAINT OL_DEF_ENCRYPT_TYPE_PK
  PRIMARY KEY
  (ET_TYPE)
  USING INDEX OL_DEF_ENCRYPT_TYPE_PK
  ENABLE VALIDATE);

