ALTER TABLE OL_STMT_FORMAT
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_STMT_FORMAT CASCADE CONSTRAINTS;

CREATE TABLE OL_STMT_FORMAT
(
  OLSF_INT_BANK_CODE     VARCHAR2(10 BYTE),
  OLSF_FORMAT_ID         VARCHAR2(20 BYTE)      NOT NULL,
  OLSF_EFFECT_TIMESTAMP  DATE                   DEFAULT sysdate,
  OLSF_DISABLED          INTEGER                DEFAULT 0,
  OLSF_CREATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  OLSF_CREATE_USER       VARCHAR2(20 BYTE),
  OLSF_UPDATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  OLSF_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX OL_STMT_FORMAT_IDX01 ON OL_STMT_FORMAT
(OLSF_DISABLED, OLSF_FORMAT_ID, OLSF_INT_BANK_CODE, OLSF_EFFECT_TIMESTAMP)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

CREATE UNIQUE INDEX OL_STMT_FORMAT_PK ON OL_STMT_FORMAT
(OLSF_INT_BANK_CODE,OLSF_FORMAT_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_STMT_FORMAT ADD (
  CONSTRAINT OL_STMT_FORMAT_PK
  PRIMARY KEY
  (OLSF_INT_BANK_CODE,OLSF_FORMAT_ID)
  USING INDEX OL_STMT_FORMAT_PK
  ENABLE VALIDATE);

ALTER TABLE OL_STMT_FORMAT ADD (
  CONSTRAINT OL_STMT_FORMAT_FK01 
  FOREIGN KEY (OLSF_INT_BANK_CODE) 
  REFERENCES DEF_BANK (DB_INT_BANK_CODE)
  ENABLE VALIDATE);
