ALTER TABLE OL_STMT_FORMAT_SPLIT
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_STMT_FORMAT_SPLIT CASCADE CONSTRAINTS;

CREATE TABLE OL_STMT_FORMAT_SPLIT
(
  OLFS_INT_BANK_CODE     VARCHAR2(10 BYTE),
  OLFS_CODE              CHAR(3 BYTE),
  OLFS_CCY               CHAR(3 BYTE),
  OLFS_REAL_CODE         CHAR(3 BYTE),
  OLFS_SPLIT_CODE        CHAR(3 BYTE),
  OLFS_SPLIT_AMOUNT      NUMBER(12,2),
  OLFS_DISABLED          INTEGER                   DEFAULT 0,
  OLFS_CREATE_TIMESTAMP  DATE                      DEFAULT sysdate,
  OLFS_CREATE_USER       VARCHAR2(20 BYTE),
  OLFS_UPDATE_TIMESTAMP  DATE                      DEFAULT sysdate,
  OLFS_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_STMT_FORMAT_SPLIT_PK ON OL_STMT_FORMAT_SPLIT
(OLFS_INT_BANK_CODE, OLFS_CODE, OLFS_CCY)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_STMT_FORMAT_SPLIT ADD (
  CONSTRAINT OL_STMT_FORMAT_SPLIT_PK
  PRIMARY KEY
  (OLFS_INT_BANK_CODE, OLFS_CODE, OLFS_CCY)
  USING INDEX OL_STMT_FORMAT_SPLIT_PK
  ENABLE VALIDATE);

ALTER TABLE OL_STMT_FORMAT_SPLIT ADD (
  CONSTRAINT OL_STMT_FORMAT_SPLIT_FK01
  FOREIGN KEY (OLFS_CODE) 
  REFERENCES OL_BAID_TXN_CODE (OBTC_CODE)
  ENABLE VALIDATE,
  CONSTRAINT OL_STMT_FORMAT_SPLIT_FK02
  FOREIGN KEY (OLFS_REAL_CODE) 
  REFERENCES OL_BAID_TXN_CODE (OBTC_CODE)
  ENABLE VALIDATE,
  CONSTRAINT OL_STMT_FORMAT_SPLIT_FK03
  FOREIGN KEY (OLFS_SPLIT_CODE) 
  REFERENCES OL_BAID_TXN_CODE (OBTC_CODE)
  ENABLE VALIDATE);

