OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=omi_bal_collect_by_day.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o omi_bal_collect_by_day.o
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  
all: $(BATCHEXE)
