ALTER TABLE MMS_TXN_CODE_GROUP
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_TXN_CODE_GROUP CASCADE CONSTRAINTS;

CREATE TABLE MMS_TXN_CODE_GROUP
(
  MCG_GROUP             VARCHAR2(6 BYTE),
  MCG_DESC              VARCHAR2(50 BYTE),
  MCG_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  MCG_CREATE_USER       VARCHAR2(20 BYTE),
  MCG_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  MCG_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MMS_TXN_CODE_GROUP_PK ON MMS_TXN_CODE_GROUP
(MCG_GROUP)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_TXN_CODE_GROUP ADD (
  CONSTRAINT MMS_TXN_CODE_GROUP_PK
  PRIMARY KEY
  (MCG_GROUP)
  USING INDEX MMS_TXN_CODE_GROUP_PK
  ENABLE VALIDATE);

