OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOOLDepositReq
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOOLDepositReq.so
SOOBJS = BOOLDepositReq.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
