OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/BankPayoutPsp
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBBankPayoutPsp.so
SOOBJS =  BankPayoutPsp.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
