CREATE TABLE PSP_PAYOUT_FILE_FORMAT_MAPPING
(
  PPFGM_PSP_ID            VARCHAR2(10 BYTE)        NOT NULL,
  PPFGM_FORMAT_CODE       VARCHAR2(50 BYTE),
  PPFGM_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  PPFGM_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  PPFGM_CREATE_USER       VARCHAR2(20 BYTE),
  PPFGM_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX PSP_PO_FILE_FMT_MAPPING_IDX01 ON PSP_PAYOUT_FILE_FORMAT_MAPPING
(PPFGM_FORMAT_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PSP_PO_FILE_FMT_MAPPING_PK ON PSP_PAYOUT_FILE_FORMAT_MAPPING
(PPFGM_PSP_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PSP_PAYOUT_FILE_FORMAT_MAPPING ADD (
  CONSTRAINT PSP_PO_FILE_FMT_MAPPING_PK
  PRIMARY KEY
  (PPFGM_PSP_ID)
  USING INDEX PSP_PO_FILE_FMT_MAPPING_PK
  ENABLE VALIDATE);

