ALTER TABLE OL_STMT_CONVERT_SCRIPT
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_STMT_CONVERT_SCRIPT CASCADE CONSTRAINTS;

CREATE TABLE OL_STMT_CONVERT_SCRIPT
(
  OLCS_INT_BANK_CODE     VARCHAR2(10 BYTE),
  OLCS_IN_FILE_PREFIX    VARCHAR2(10 BYTE),
  OLCS_IN_FILE_COUNTRY   VARCHAR2(10 BYTE),
  OLCS_IN_FILE_EXT       VARCHAR2(3 BYTE),
  OLCS_IN_FILE_ENCODING  VARCHAR2(10 BYTE),
  OLCS_SCRIPT_NAME       VARCHAR2(50 BYTE),
  OLCS_EFFECT_TIMESTAMP  DATE                   DEFAULT sysdate,
  OLCS_DISABLED          INTEGER                DEFAULT 0,
  OLCS_CREATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  OLCS_CREATE_USER       VARCHAR2(20 BYTE),
  OLCS_UPDATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  OLCS_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_STMT_CONVERT_SCRIPT_PK ON OL_STMT_CONVERT_SCRIPT
(OLCS_INT_BANK_CODE, OLCS_IN_FILE_EXT, OLCS_EFFECT_TIMESTAMP)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

CREATE UNIQUE INDEX OL_STMT_CONVERT_SCRIPT_IDX01 ON OL_STMT_CONVERT_SCRIPT
(OLCS_INT_BANK_CODE, OLCS_IN_FILE_EXT, OLCS_DISABLED, OLCS_EFFECT_TIMESTAMP)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_STMT_CONVERT_SCRIPT ADD (
  CONSTRAINT OL_STMT_CONVERT_SCRIPT_PK
  PRIMARY KEY
  (OLCS_INT_BANK_CODE, OLCS_IN_FILE_EXT, OLCS_EFFECT_TIMESTAMP)
  USING INDEX OL_STMT_CONVERT_SCRIPT_PK
  ENABLE VALIDATE);

ALTER TABLE OL_STMT_CONVERT_SCRIPT ADD (
  CONSTRAINT OL_STMT_CONVERT_SCRIPT_FK01 
  FOREIGN KEY (OLCS_INT_BANK_CODE) 
  REFERENCES DEF_BANK (DB_INT_BANK_CODE)
  ENABLE VALIDATE);

