OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOExchange
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOExchange.so
SOOBJS = BOExchange.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
