ALTER TABLE DEF_IP_REGION 
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_IP_REGION CASCADE CONSTRAINTS;

CREATE TABLE DEF_IP_REGION 
(
  DIR_REGION_CODE	VARCHAR2(2 BYTE), 
  DIR_REGION_NAME	VARCHAR2(50 BYTE), 
  DIR_DISABLED		INTEGER			DEFAULT 0, 
  DIR_CREATE_TIMESTAMP	DATE			DEFAULT sysdate, 
  DIR_CREATE_USER	VARCHAR2(20 BYTE), 
  DIR_UPDATE_TIMESTAMP	DATE			DEFAULT sysdate, 
  DIR_UPDATE_USER	VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA 
PCTUSED    0 
PCTFREE    10 
INITRANS   1 
MAXTRANS   255 
STORAGE    (
            INITIAL         64K 
            NEXT            1M 
            MINEXTENTS      1 
            MAXEXTENTS      UNLIMITED 
            PCTINCREASE     0 
            BUFFER_POOL     DEFAULT
           ) 
LOGGING 
NOCOMPRESS 
NOCACHE 
MONITORING;

CREATE UNIQUE INDEX DEF_IP_REGION_PK ON DEF_IP_REGION 
(DIR_REGION_CODE) 
LOGGING 
TABLESPACE USER_IDX 
PCTFREE    10 
INITRANS   2 
MAXTRANS   255 
STORAGE    (
            INITIAL          64K 
            NEXT             1M 
            MINEXTENTS       1 
            MAXEXTENTS       UNLIMITED 
            PCTINCREASE      0 
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DEF_IP_REGION ADD (
  CONSTRAINT DEF_IP_REGION_PK 
  PRIMARY KEY 
  (DIR_REGION_CODE) 
  USING INDEX DEF_IP_REGION_PK 
  ENABLE VALIDATE);
