INSERT ALL 
 INTO DEF_IP_REGION (DIR_REGION_CODE, DIR_REGION_NAME, DIR_DISABLED, DIR_CREATE_USER, DIR_UPDATE_USER) 
 VALUES ('CN', 'China', 0, 'SYSTEM', 'SYSTEM') 
 INTO DEF_IP_REGION (DIR_REGION_CODE, DIR_REGION_NAME, DIR_DISABLED, DIR_CREATE_USER, DIR_UPDATE_USER) 
 VALUES ('HK', 'Hong Kong', 0, 'SYSTEM', 'SYSTEM') 
 INTO DEF_IP_REGION (DIR_REGION_CODE, DIR_REGION_NAME, DIR_DISABLED, DIR_CREATE_USER, DIR_UPDATE_USER) 
 VALUES ('MO', 'Macau', 0, 'SYSTEM', 'SYSTEM') 
 INTO DEF_IP_REGION (DIR_REGION_CODE, DIR_REGION_NAME, DIR_DISABLED, DIR_CREATE_USER, DIR_UPDATE_USER) 
 VALUES ('TW', 'Taiwan', 0, 'SYSTEM', 'SYSTEM') 
SELECT * FROM DUAL;