ALTER TABLE OL_DEF_SIM_CARRIERS
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_DEF_SIM_CARRIERS CASCADE CONSTRAINTS;

CREATE TABLE OL_DEF_SIM_CARRIERS
(
  DSC_CARRIER_CODE      VARCHAR2(10 BYTE),
  DSC_CARRIER_NAME      VARCHAR2(50 BYTE),
  DSC_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  DSC_CREATE_USER       VARCHAR2(20 BYTE),
  DSC_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  DSC_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_DEF_SIM_CARRIERS_PK ON OL_DEF_SIM_CARRIERS
(DSC_CARRIER_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_DEF_SIM_CARRIERS ADD (
  CONSTRAINT OL_DEF_SIM_CARRIERS_PK
  PRIMARY KEY
  (DSC_CARRIER_CODE)
  USING INDEX OL_DEF_SIM_CARRIERS_PK
  ENABLE VALIDATE);

