DROP TABLE OL_BANK_ACCT_BAL CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE OL_BANK_ACCT_BAL
(
  OBA_BANK_CODE         VARCHAR2(10 BYTE),
  OBA_BANK_ACCT_NUM     VARCHAR2(50 BYTE),
  OBA_CURR_BAL          NUMBER(14,2)            DEFAULT 0,
  OBA_CREATE_TIMESTAMP  DATE,
  OBA_CREATE_USER       VARCHAR2(20 BYTE),
  OBA_UPDATE_TIMESTAMP  DATE,
  OBA_UPDATE_USER       VARCHAR2(20 BYTE)
)
ON COMMIT DELETE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;

