ALTER TABLE DEPLOYMENT_LOG
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEPLOYMENT_LOG CASCADE CONSTRAINTS;

CREATE TABLE DEPLOYMENT_LOG
(
  L_SEQ               INTEGER                   NOT NULL,
  L_REF_NO            VARCHAR2(25 BYTE)         NOT NULL,
  L_MODE              VARCHAR2(10 BYTE),
  L_ENV               VARCHAR2(10 BYTE),
  L_SERVER            VARCHAR2(10 BYTE),
  L_FUNCTION          VARCHAR2(10 BYTE),
  L_DESC              VARCHAR2(255 BYTE),
  L_CREATE_USER       VARCHAR2(20 BYTE),
  L_CREATE_TIMESTAMP  DATE                      DEFAULT sysdate
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE INDEX DEPLOYMENT_LOG_IDX01 ON DEPLOYMENT_LOG
(L_REF_NO)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX DEPLOYMENT_LOG_IDX02 ON DEPLOYMENT_LOG
(L_CREATE_TIMESTAMP)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX DEPLOYMENT_LOG_PK ON DEPLOYMENT_LOG
(L_SEQ)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DEPLOYMENT_LOG ADD (
  CONSTRAINT DEPLOYMENT_LOG_PK
  PRIMARY KEY
  (L_SEQ)
  USING INDEX DEPLOYMENT_LOG_PK
  ENABLE VALIDATE);

