OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnWebOnUs2ALP
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnWebOnUs2ALP.so
SOOBJS = TxnWebOnUs2ALP.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
