OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnWebOnUsWTV
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnWebOnUsWTV.so
SOOBJS = TxnWebOnUsWTV.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
