OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MiActionLock
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMiActionLock.so
SOOBJS =  MiActionLock.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
