ALTER TABLE PHUSER.TXN_ACK_RETRY
 DROP PRIMARY KEY CASCADE;

DROP TABLE PHUSER.TXN_ACK_RETRY CASCADE CONSTRAINTS;

CREATE TABLE PHUSER.TXN_ACK_RETRY
(
  TA_BATCH_TXN_ID      VARCHAR2(16 BYTE),
  TA_TXN_ID            VARCHAR2(16 BYTE),
  TA_STATUS            CHAR(1 BYTE),
  TA_LOCAL_TM_DATE     VARCHAR2(8 BYTE),
  TA_LOCAL_TM_TIME     VARCHAR2(6 BYTE),
  TA_NEXT_TRY          DATE,
  TA_CREATE_USER       VARCHAR2(20 BYTE),
  TA_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  TA_UPDATE_USER       VARCHAR2(20 BYTE),
  TA_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  TA_RESEND_COUNT      INTEGER                  DEFAULT 0,
  TA_RESET_CNT_TIMESTAMP  DATE
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN PHUSER.TXN_ACK_RETRY.TA_STATUS IS '''F'' First try, ''R'' - Retry, ''C- Complete';



CREATE INDEX PHUSER.TXN_ACK_RETRY_IDX01 ON PHUSER.TXN_ACK_RETRY
(TA_BATCH_TXN_ID,TA_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX PHUSER.TXN_ACK_RETRY_IDX02 ON PHUSER.TXN_ACK_RETRY
(TA_NEXT_TRY)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PHUSER.TXN_ACK_RETRY ADD (
  CONSTRAINT TXN_ACK_RETRY_PK
  PRIMARY KEY
  (TA_BATCH_TXN_ID,TA_TXN_ID)
  USING INDEX PHUSER.TXN_ACK_RETRY_IDX01
  ENABLE VALIDATE);

