OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLTxnRemarks
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLTxnRemarks.so
SOOBJS =  OLTxnRemarks.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
