ALTER TABLE DEF_EDO_REPORTS
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_EDO_REPORTS CASCADE CONSTRAINTS;

CREATE TABLE DEF_EDO_REPORTS
(
  DER_ID               VARCHAR2(10 BYTE),
  DER_DESC             VARCHAR2(50 BYTE),
  DER_CREATE_DATETIME  DATE,
  DER_CREATE_USER      VARCHAR2(20 BYTE),
  DER_UPDATE_DATETEIM  DATE,
  DER_UPDATE_USER      VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEF_EDO_REPORTS_PK ON DEF_EDO_REPORTS
(DER_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_EDO_REPORTS ADD (
  CONSTRAINT DEF_EDO_REPORTS_PK
  PRIMARY KEY
  (DER_ID)
  USING INDEX DEF_EDO_REPORTS_PK
  ENABLE VALIDATE);

