OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/PspDepositTrace
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBPspDepositTrace.so
SOOBJS =  PspDepositTrace.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
