


CREATE TABLE DEF_REPORT_TYPE
(
  DRT_TYPE              CHAR(3 BYTE)             NOT NULL,
  DRT_DESC              VARCHAR2(50 BYTE),
  DRT_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  DRT_CREATE_USER       VARCHAR2(20 BYTE),
  DRT_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  DRT_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DEF_REPORT_TYPE_PK ON DEF_REPORT_TYPE
(DRT_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DEF_REPORT_TYPE ADD (
  CONSTRAINT DEF_REPORT_TYPE_PK
  PRIMARY KEY
  (DRT_TYPE)
  USING INDEX DEF_REPORT_TYPE_PK
  ENABLE VALIDATE);
