DROP TABLE OL_FUNDS_IN_OUT_HISTORY CASCADE CONSTRAINTS;

CREATE TABLE OL_FUNDS_IN_OUT_HISTORY
(
  OFH_TXN_DATE          VARCHAR2(8 BYTE),
  OFH_FROM_CCY          VARCHAR2(3 BYTE),
  OFH_FROM_AMT          NUMBER(14,2),
  OFH_BANK_CCY          VARCHAR2(3 BYTE),
  OFH_BANK_AMT          NUMBER(14,2),
  OFH_OLD_RATE          NUMBER(14,5),
  OFH_NEW_RATE          NUMBER(14,5),
  OFH_BANK_BAL          NUMBER(14,2),
  OFH_TXN_TYPE          VARCHAR2(50 BYTE),
  OFH_FUND_TYPE         VARCHAR2(50 BYTE),
  OFH_TXN_ID            VARCHAR2(16 BYTE),
  OFH_TIME              DATE,
  OFH_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  OFH_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  OFH_CREATE_USER       VARCHAR2(20 BYTE)	DEFAULT 'SYSTEM',
  OFH_UPDATE_USER       VARCHAR2(20 BYTE)	DEFAULT 'SYSTEM'
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

