OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/RuleServiceReleasePeriod
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBRuleServiceReleasePeriod.so
SOOBJS =  RuleServiceReleasePeriod.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
