ALTER TABLE OL_PSP_DETAIL
 ADD (OPD_BUSINESS_TYPE  CHAR(1 BYTE));

ALTER TABLE OL_PSP_DETAIL ADD (
  CONSTRAINT OL_PSP_DETAIL_FK03 
  FOREIGN KEY (OPD_BUSINESS_TYPE) 
  REFERENCES DEF_BUSINESS_TYPE (BT_TYPE)
  ENABLE VALIDATE);

update ol_psp_detail
set opd_business_type = 'G';
commit;
