ALTER TABLE OL_PSP_DETAIL
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_PSP_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE OL_PSP_DETAIL
(
  OPD_PSP_ID              VARCHAR2(10 BYTE),
  OPD_PSP_NAME            VARCHAR2(50 BYTE)     NOT NULL,
  OPD_DISABLED            INTEGER               DEFAULT 0                     NOT NULL,
  OPD_CLIENT_ID           VARCHAR2(10 BYTE)     NOT NULL,
  OPD_BANK_ACCT_TYPE      VARCHAR2(3 BYTE)      NOT NULL,
  OPD_CURRENCY_ID         VARCHAR2(3 BYTE)      NOT NULL,
  OPD_STATUS              VARCHAR2(2 BYTE)      NOT NULL,
  OPD_PSP_REMARK          VARCHAR2(255 BYTE),
  OPD_PROCESSOR_NAME      VARCHAR2(50 BYTE),
  OPD_PAYOUT_SPLIT_LIMIT  INTEGER               DEFAULT 0,
  OPD_PAYOUT_FORMAT       INTEGER               DEFAULT 0,
  OPD_CREATE_USER         VARCHAR2(20 BYTE)     NOT NULL,
  OPD_CREATE_TIMESTAMP    DATE                  NOT NULL,
  OPD_UPDATE_USER         VARCHAR2(20 BYTE),
  OPD_UPDATE_TIMESTAMP    DATE                  NOT NULL,
  OPD_BUSINESS_TYPE       CHAR(1 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN OL_PSP_DETAIL.OPD_PAYOUT_FORMAT IS '0 - Default; 1 - For Yeepay; 2 - For TWV';



CREATE UNIQUE INDEX OL_PSP_DETAIL_PK ON OL_PSP_DETAIL
(OPD_PSP_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_PSP_DETAIL ADD (
  CONSTRAINT OL_PSP_DETAIL_PK
  PRIMARY KEY
  (OPD_PSP_ID)
  USING INDEX OL_PSP_DETAIL_PK
  ENABLE VALIDATE);

ALTER TABLE OL_PSP_DETAIL ADD (
  CONSTRAINT OL_PSP_DETAIL_FK01 
  FOREIGN KEY (OPD_STATUS) 
  REFERENCES DEF_STATUS (DS_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OL_PSP_DETAIL_FK02 
  FOREIGN KEY (OPD_CLIENT_ID) 
  REFERENCES PSP_MASTER (PM_CLIENT_ID)
  ENABLE VALIDATE,
  CONSTRAINT OL_PSP_DETAIL_FK03 
  FOREIGN KEY (OPD_BUSINESS_TYPE) 
  REFERENCES DEF_BUSINESS_TYPE (BT_TYPE)
  ENABLE VALIDATE);

