OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/PayoutSpcSplitAcct
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBPayoutSpcSplitAcct.so
SOOBJS =  PayoutSpcSplitAcct.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
