ALTER TABLE PHUSER.OL_BATCH_TXN_RELATION
 ADD (OBTR_BATCH_SUB_TYPE  CHAR(1 BYTE));

ALTER TABLE PHUSER.OL_BATCH_TXN_RELATION
 ADD (OBTR_IS_INPUT_TXN  INTEGER);

ALTER TABLE PHUSER.OL_BATCH_TXN_RELATION
 ADD (OBTR_IS_REGEN_TXN  INTEGER);
