ALTER TABLE OL_BATCH_TXN_RELATION
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_BATCH_TXN_RELATION CASCADE CONSTRAINTS;

CREATE TABLE OL_BATCH_TXN_RELATION
(
  OBTR_BATCH_TYPE        CHAR(1 BYTE),
  OBTR_BATCH_ID          VARCHAR2(16 BYTE),
  OBTR_TXN_LEVEL         CHAR(1 BYTE),
  OBTR_TXN_ID            VARCHAR2(16 BYTE),
  OBTR_RELATION_TIMESTAMP TIMESTAMP(6),
  OBTR_CREATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  OBTR_UPDATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  OBTR_CREATE_USER       VARCHAR2(20 BYTE),
  OBTR_UPDATE_USER       VARCHAR2(20 BYTE),
  OBTR_BATCH_SUB_TYPE    CHAR(1 BYTE),
  OBTR_IS_INPUT_TXN      INTEGER,
  OBTR_IS_REGEN_TXN      INTEGER
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX OL_BATCH_TXN_RELATION_IDX01 ON OL_BATCH_TXN_RELATION
(OBTR_BATCH_TYPE, OBTR_TXN_LEVEL, OBTR_BATCH_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX OL_BATCH_TXN_RELATION_IDX02 ON OL_BATCH_TXN_RELATION
(OBTR_BATCH_TYPE, OBTR_TXN_LEVEL, OBTR_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX OL_BATCH_TXN_RELATION_PK ON OL_BATCH_TXN_RELATION
(OBTR_BATCH_TYPE, OBTR_BATCH_ID, OBTR_TXN_LEVEL, OBTR_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_BATCH_TXN_RELATION ADD (
  CONSTRAINT OL_BATCH_TXN_RELATION_PK
  PRIMARY KEY
  (OBTR_BATCH_TYPE, OBTR_BATCH_ID, OBTR_TXN_LEVEL, OBTR_TXN_ID)
  USING INDEX OL_BATCH_TXN_RELATION_PK
  ENABLE VALIDATE);

ALTER TABLE OL_BATCH_TXN_RELATION ADD (
  CONSTRAINT OL_BATCH_TXN_RELATION_FK01 
  FOREIGN KEY (OBTR_BATCH_TYPE) 
  REFERENCES OL_DEF_ACTION_BATCH_TYPE (OABT_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OL_BATCH_TXN_RELATION_FK02 
  FOREIGN KEY (OBTR_TXN_LEVEL) 
  REFERENCES OL_DEF_TXN_LEVEL (OTL_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OL_BATCH_TXN_RELATION_FK03 
  FOREIGN KEY (OBTR_BATCH_SUB_TYPE) 
  REFERENCES OL_DEF_ACT_BATCH_SUB_TYPE (OABST_SUB_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OL_BATCH_TXN_RELATION_FK04 
  FOREIGN KEY (OBTR_TXN_TYPE) 
  REFERENCES OL_DEF_TXN_TYPE (OTT_TYPE)
  ENABLE VALIDATE);

