ALTER TABLE SYSTEM_TPL_FMT
 DROP PRIMARY KEY CASCADE;

DROP TABLE SYSTEM_TPL_FMT CASCADE CONSTRAINTS;

CREATE TABLE SYSTEM_TPL_FMT
(
  STF_TPL_NAME      VARCHAR2(50 BYTE),
  STF_TPL_TAG_NAME  VARCHAR2(50 BYTE),
  STF_TPL_LEVEL     INTEGER,
  STF_TPL_TAG_TYPE  CHAR(1 BYTE),
  STF_TPL_DATATYPE  CHAR(3 BYTE),
  STF_SECTION_NAME  VARCHAR2(50 BYTE),
  STF_MULTIPLE      INTEGER
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX SYSTEM_TPL_FMT_PK ON SYSTEM_TPL_FMT
(STF_TPL_NAME, STF_TPL_TAG_NAME, STF_TPL_LEVEL)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE SYSTEM_TPL_FMT ADD (
  CONSTRAINT SYSTEM_TPL_FMT_PK
  PRIMARY KEY
  (STF_TPL_NAME, STF_TPL_TAG_NAME, STF_TPL_LEVEL)
  USING INDEX SYSTEM_TPL_FMT_PK
  ENABLE VALIDATE);

