ALTER TABLE OL_STMT_MATCH_FILTER_MAP
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_STMT_MATCH_FILTER_MAP CASCADE CONSTRAINTS;

CREATE TABLE OL_STMT_MATCH_FILTER_MAP
(
  OSMM_ACTION_TYPE       VARCHAR2(50 BYTE),
  OSMM_PARTY             VARCHAR2(10 BYTE),
  OSMM_FILTER            VARCHAR2(20 BYTE),
  OSMM_FIELD             VARCHAR2(500 BYTE),
  OSMM_ADD_SINGLE_QUOTE  INTEGER                DEFAULT 0,
  OSMM_DISABLED          INTEGER                DEFAULT 0,
  OSMM_CREATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  OSMM_CREATE_USER       VARCHAR2(20 BYTE),
  OSMM_UPDATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  OSMM_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_STMT_MATCH_FILTER_MAP_PK ON OL_STMT_MATCH_FILTER_MAP
(OSMM_ACTION_TYPE, OSMM_PARTY, OSMM_FILTER)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_STMT_MATCH_FILTER_MAP ADD (
  CONSTRAINT OL_STMT_MATCH_FILTER_MAP_PK
  PRIMARY KEY
  (OSMM_ACTION_TYPE, OSMM_PARTY, OSMM_FILTER)
  USING INDEX OL_STMT_MATCH_FILTER_MAP_PK
  ENABLE VALIDATE);

