OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOOLSms
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOOLSms.so
SOOBJS = BOOLSms.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
