OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnOmtByUsVPO
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnOmtByUsVPO.so
SOOBJS = TxnOmtByUsVPO.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
