ALTER TABLE OL_TXN_ELEMENTS
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_TXN_ELEMENTS CASCADE CONSTRAINTS;

CREATE TABLE OL_TXN_ELEMENTS
(
  OTE_TXN_ID            VARCHAR2(16 BYTE),
  OTE_TXN_ELEMENT_TYPE  CHAR(4 BYTE),
  OTE_EXEC_SEQ          INTEGER,
  OTE_AMOUNT            NUMBER(14,2),
  OTE_CCY               CHAR(3 BYTE)            NOT NULL,
  OTE_AMT_TYPE          CHAR(2 BYTE),
  OTE_PARTY_TYPE        CHAR(1 BYTE)            NOT NULL,
  OTE_RATE              NUMBER(12,5)            DEFAULT 1,
  OTE_CREATE_TIMESTAMP  DATE,
  OTE_CREATE_USER       VARCHAR2(20 BYTE),
  OTE_UPDATE_TIMESTAMP  DATE,
  OTE_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX OL_TXN_ELEMENTS_IDX01 ON OL_TXN_ELEMENTS
(OTE_TXN_ELEMENT_TYPE, OTE_PARTY_TYPE, OTE_CCY, OTE_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX OL_TXN_ELEMENTS_IDX02 ON OL_TXN_ELEMENTS
(OTE_TXN_ELEMENT_TYPE, OTE_PARTY_TYPE, OTE_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX OL_TXN_ELEMENTS_IDX03 ON OL_TXN_ELEMENTS
(OTE_TXN_ELEMENT_TYPE, OTE_PARTY_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX OL_TXN_ELEMENTS_IDX04 ON OL_TXN_ELEMENTS
(OTE_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX OL_TXN_ELEMENTS_PK ON OL_TXN_ELEMENTS
(OTE_TXN_ID, OTE_TXN_ELEMENT_TYPE, OTE_EXEC_SEQ, OTE_PARTY_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_TXN_ELEMENTS ADD (
  CONSTRAINT OL_TXN_ELEMENTS_PK
  PRIMARY KEY
  (OTE_TXN_ID, OTE_TXN_ELEMENT_TYPE, OTE_EXEC_SEQ, OTE_PARTY_TYPE)
  USING INDEX OL_TXN_ELEMENTS_PK
  ENABLE VALIDATE);

ALTER TABLE OL_TXN_ELEMENTS ADD (
  CONSTRAINT OL_TXN_ELEMENTS_FK01 
  FOREIGN KEY (OTE_TXN_ELEMENT_TYPE) 
  REFERENCES DEF_ELEMENT_TYPE (DT_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OL_TXN_ELEMENTS_FK03 
  FOREIGN KEY (OTE_PARTY_TYPE) 
  REFERENCES DEF_PARTY_TYPE (DP_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OL_TXN_ELEMENTS_FK04 
  FOREIGN KEY (OTE_TXN_ID) 
  REFERENCES OL_TXN_HEADER (OTH_TXN_ID)
  ENABLE VALIDATE);

