


ALTER TABLE OL_ACCT_LEDGER_DAILY_REPORT
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_ACCT_LEDGER_DAILY_REPORT CASCADE CONSTRAINTS;

CREATE TABLE OL_ACCT_LEDGER_DAILY_REPORT
(
  OALDR_MERCHANT_ID       VARCHAR2(15 BYTE)      NOT NULL,
  OALDR_COUNTRY_ID        CHAR(2 BYTE)           NOT NULL,
  OALDR_CURRENCY_ID       VARCHAR2(3 BYTE)       NOT NULL,
  OALDR_SERVICE_CODE      CHAR(3 BYTE)           NOT NULL,
  OALDR_LEDGER_TYPE       CHAR(1 BYTE)           NOT NULL,
  OALDR_REPORT_DATE       VARCHAR2(8 BYTE)       NOT NULL,
  OALDR_FILENAME          VARCHAR2(100 BYTE),
  OALDR_STATUS            CHAR(1 BYTE),
  OALDR_DISABLED          INTEGER                DEFAULT 0,
  OALDR_CREATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  OALDR_CREATE_USER       VARCHAR2(20 BYTE),
  OALDR_UPDATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  OALDR_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;


CREATE INDEX OL_ACCT_LEDGER_DAILY_RPT_IDX1 ON OL_ACCT_LEDGER_DAILY_REPORT
(OALDR_REPORT_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX OL_ACCT_LEDGER_DAILY_REPORT_PK ON OL_ACCT_LEDGER_DAILY_REPORT
(OALDR_MERCHANT_ID, OALDR_COUNTRY_ID, OALDR_CURRENCY_ID, OALDR_SERVICE_CODE, OALDR_LEDGER_TYPE,
OALDR_REPORT_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE OL_ACCT_LEDGER_DAILY_REPORT ADD (
  CONSTRAINT OL_ACCT_LEDGER_DAILY_REPORT_PK
  PRIMARY KEY
  (OALDR_MERCHANT_ID, OALDR_COUNTRY_ID, OALDR_CURRENCY_ID, OALDR_SERVICE_CODE, OALDR_LEDGER_TYPE, OALDR_REPORT_DATE)
  USING INDEX OL_ACCT_LEDGER_DAILY_REPORT_PK
  ENABLE VALIDATE);

ALTER TABLE OL_ACCT_LEDGER_DAILY_REPORT ADD (
  CONSTRAINT OL_ACCT_LEDGER_DAILY_RPT_FK01
  FOREIGN KEY (OALDR_MERCHANT_ID)
  REFERENCES OL_MERCH_DETAIL (MD_MERCHANT_ID)
  ENABLE VALIDATE,
  CONSTRAINT OL_ACCT_LEDGER_DAILY_RPT_FK02
  FOREIGN KEY (OALDR_COUNTRY_ID)
  REFERENCES COUNTRY (COUNTRY_CODE)
  ENABLE VALIDATE,
  CONSTRAINT OL_ACCT_LEDGER_DAILY_RPT_FK03
  FOREIGN KEY (OALDR_CURRENCY_ID)
  REFERENCES DEF_CURRENCY (DC_CCY_ID)
  ENABLE VALIDATE,
  CONSTRAINT OL_ACCT_LEDGER_DAILY_RPT_FK04
  FOREIGN KEY (OALDR_SERVICE_CODE)
  REFERENCES DEF_SERVICE_CODE (SC_CODE)
  ENABLE VALIDATE,
  CONSTRAINT OL_ACCT_LEDGER_DAILY_RPT_FK05
  FOREIGN KEY (OALDR_STATUS)
  REFERENCES DEF_PREGEN_RPT_STATUS (DS_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OL_ACCT_LEDGER_DAILY_RPT_FK06
  FOREIGN KEY (OALDR_LEDGER_TYPE)
  REFERENCES DEF_LEDGER_TYPE (DL_TYPE)
  ENABLE VALIDATE);
