OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOParAdjustment
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOParAdjustment.so
SOOBJS = BOParAdjustment.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
