ALTER TABLE OL_PSP_TXN_STATUS_RULE
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_PSP_TXN_STATUS_RULE CASCADE CONSTRAINTS;

CREATE TABLE OL_PSP_TXN_STATUS_RULE
(
  OSR_RULE_ID            INTEGER,
  OSR_STATUS             CHAR(1 BYTE),
  OSR_AR_IND             CHAR(1 BYTE),
  OSR_SUB_STATUS         CHAR(3 BYTE),
  OSR_RECON_STATUS       CHAR(1 BYTE),
  OSR_CLASSIFIED_STATUS  CHAR(1 BYTE),
  OSR_DISABLED           INTEGER,
  OSR_CREATE_TIMESTAMP   DATE                   DEFAULT sysdate,
  OSR_UPDATE_TIMESTAMP   DATE                   DEFAULT sysdate,
  OSR_CREATE_USER        VARCHAR2(20 BYTE),
  OSR_UPDATE_USER        VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_PSP_TXN_STATUS_RULE_PK ON OL_PSP_TXN_STATUS_RULE
(OSR_RULE_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_PSP_TXN_STATUS_RULE ADD (
  CONSTRAINT OL_PSP_TXN_STATUS_RULE_PK
  PRIMARY KEY
  (OSR_RULE_ID)
  USING INDEX OL_PSP_TXN_STATUS_RULE_PK
  ENABLE VALIDATE);

ALTER TABLE OL_PSP_TXN_STATUS_RULE ADD (
  CONSTRAINT OL_PSP_TXN_STATUS_RULE_FK01 
  FOREIGN KEY (OSR_RECON_STATUS) 
  REFERENCES OL_DEF_RECON_STATUS (RS_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OL_PSP_TXN_STATUS_RULE_FK02 
  FOREIGN KEY (OSR_CLASSIFIED_STATUS) 
  REFERENCES OL_DEF_CLASSIFIED_STATUS (CS_TYPE)
  ENABLE VALIDATE);

