ALTER TABLE OL_DEF_BAID_CATEGORY
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_DEF_BAID_CATEGORY CASCADE CONSTRAINTS;

CREATE TABLE OL_DEF_BAID_CATEGORY
(
  BC_TYPE              VARCHAR2(10 BYTE),
  BC_DESC              VARCHAR2(50 BYTE),
  BC_ALLOW_FE_CREATE   INTEGER,
  BC_IN_BALANCE        INTEGER,
  BC_CAT_NAME          VARCHAR2(10 BYTE),
  BC_ALLOW_MULTIPLE    INTEGER,
  BC_FE_DISPLAY        INTEGER                  DEFAULT 0,
  BC_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  BC_CREATE_USER       VARCHAR2(20 BYTE),
  BC_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  BC_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_DEF_BAID_CATEGORY_PK ON OL_DEF_BAID_CATEGORY
(BC_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_DEF_BAID_CATEGORY ADD (
  CONSTRAINT OL_DEF_BAID_CATEGORY_PK
  PRIMARY KEY
  (BC_TYPE)
  USING INDEX OL_DEF_BAID_CATEGORY_PK
  ENABLE VALIDATE);

