OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLAutoUploadAcctStatus
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLAutoUploadAcctStatus.so
SOOBJS =  OLAutoUploadAcctStatus.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
