OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/IpFilter
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBIpFilter.so
SOOBJS = IpFilter.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
