OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLTxnEngineSpcAction
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLTxnEngineSpcAction.so
SOOBJS =  OLTxnEngineSpcAction.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
