ALTER TABLE OL_WAIT_RECON_CFM_LIST
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_WAIT_RECON_CFM_LIST CASCADE CONSTRAINTS;

CREATE TABLE OL_WAIT_RECON_CFM_LIST
(
  OWRC_BAID_TXN_ID_1     VARCHAR2(16 BYTE),
  OWRC_BANK_ACCT_TYPE_1  VARCHAR2(3 BYTE),
  OWRC_BAID_TXN_ID_2     VARCHAR2(16 BYTE),
  OWRC_BANK_ACCT_TYPE_2  VARCHAR2(3 BYTE),
  OWRC_RECON_TYPE        CHAR(1 BYTE),
  OWRC_CREATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  OWRC_CREATE_USER       VARCHAR2(20 BYTE),
  OWRC_UPDATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  OWRC_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_WAIT_RECON_CFM_LIST_PK ON OL_WAIT_RECON_CFM_LIST
(OWRC_BAID_TXN_ID_1, OWRC_BAID_TXN_ID_2)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_WAIT_RECON_CFM_LIST ADD (
  CONSTRAINT OL_WAIT_RECON_CFM_LIST_PK
  PRIMARY KEY
  (OWRC_BAID_TXN_ID_1, OWRC_BAID_TXN_ID_2)
  USING INDEX OL_WAIT_RECON_CFM_LIST_PK
  ENABLE VALIDATE);

