OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLPspSettlementDetail
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLPspSettlementDetail.so
SOOBJS =  OLPspSettlementDetail.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
