ALTER TABLE TXN_BE_URL
 DROP PRIMARY KEY CASCADE;

DROP TABLE TXN_BE_URL CASCADE CONSTRAINTS;

CREATE TABLE TXN_BE_URL
(
  TXN_CODE          VARCHAR2(3 BYTE)            NOT NULL,
  SERVICE_CODE      CHAR(3 BYTE)                NOT NULL,
  PSP_ID            VARCHAR2(10 BYTE)           NOT NULL,
  PATH              VARCHAR2(50 BYTE),
  EFFECT_DATE       DATE,
  DISABLED          VARCHAR2(1 BYTE),
  CREATE_TIMESTAMP  DATE                        DEFAULT SYSDATE,
  UPDATE_TIMESTAMP  DATE                        DEFAULT SYSDATE,
  CREATE_USER       VARCHAR2(20 BYTE),
  UPDATE_USER       VARCHAR2(20 BYTE),
  OVERRIDE_DOMAIN   VARCHAR2(50 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX TXN_BE_URL_IDX01 ON TXN_BE_URL
(DISABLED)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX TXN_BE_URL_PK ON TXN_BE_URL
(TXN_CODE, SERVICE_CODE, PSP_ID, EFFECT_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE TXN_BE_URL ADD (
  CONSTRAINT TXN_BE_URL_PK
  PRIMARY KEY
  (TXN_CODE, SERVICE_CODE, PSP_ID, EFFECT_DATE)
  USING INDEX TXN_BE_URL_PK
  ENABLE VALIDATE);

ALTER TABLE TXN_BE_URL ADD (
  CONSTRAINT TXN_BE_URL_FK01 
  FOREIGN KEY (SERVICE_CODE) 
  REFERENCES DEF_SERVICE_CODE (SC_CODE)
  ENABLE VALIDATE);

