OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/AdjustmentType
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBAdjustmentType.so
SOOBJS =  AdjustmentType.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
