ALTER TABLE PAR_CLIENT_MAP
 DROP PRIMARY KEY CASCADE;

DROP TABLE PAR_CLIENT_MAP CASCADE CONSTRAINTS;

CREATE TABLE PAR_CLIENT_MAP
(
  PCM_CLIENT_GROUP       VARCHAR2(5 BYTE),
  PCM_CLIENT_GROUP_NAME  VARCHAR2(50 BYTE),
  PCM_MERCH_ACCT_NMB     VARCHAR2(50 BYTE),
  PCM_USERNAME           VARCHAR2(100 BYTE),
  PCM_PREFER_CLIENT_ID	 VARCHAR2(10 BYTE),
  PCM_PREFER_MID         VARCHAR2(15 BYTE),
  PCM_MID_NAME	         VARCHAR2(50 BYTE),
  PCM_CREATE_TIMESTAMP   DATE                   DEFAULT sysdate,
  PCM_CREATE_USER        VARCHAR2(20 BYTE),
  PCM_UPDATE_TIMESTAMP   DATE                   DEFAULT sysdate,
  PCM_UPDATE_USER        VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PAR_CLIENT_MAP_PK ON PAR_CLIENT_MAP
(PCM_CLIENT_GROUP, PCM_CLIENT_GROUP_NAME, PCM_MERCH_ACCT_NMB)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PAR_CLIENT_MAP ADD (
  CONSTRAINT PAR_CLIENT_MAP_PK
  PRIMARY KEY
  (PCM_CLIENT_GROUP, PCM_CLIENT_GROUP_NAME, PCM_MERCH_ACCT_NMB)
  USING INDEX PAR_CLIENT_MAP_PK
  ENABLE VALIDATE);

