OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnWebOnUs2UNI
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnWebOnUs2UNI.so
SOOBJS = TxnWebOnUs2UNI.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
