OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLMerchantReservedAmt
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLMerchantReservedAmt.so
SOOBJS =  OLMerchantReservedAmt.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
