OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/TxnPspDetail
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBTxnPspDetail.so
SOOBJS =  TxnPspDetail.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
