OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Msg/ESkyMsg
COMPLIBHOME = $(HOME)/lib/Msg
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libESkyMsg.so
SOOBJS = ESkyMsg.o 

include $(HOME)/config/Make.rules

LDLIBS += -lmyhash  -lz

all	: $(COMPSO)
