OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLAutoUploadErrLog
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLAutoUploadErrLog.so
SOOBJS =  OLAutoUploadErrLog.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
