OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/EmailSettingHistory
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBEmailSettingHistory.so
SOOBJS =  EmailSettingHistory.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
