OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnWebOnUs2HPY
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnWebOnUs2HPY.so
SOOBJS = TxnWebOnUs2HPY.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
