ALTER TABLE MMS_DEF_TXN_STATUS_MAP
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_DEF_TXN_STATUS_MAP CASCADE CONSTRAINTS;

CREATE TABLE MMS_DEF_TXN_STATUS_MAP
(
  TSM_TYPE              CHAR(1 BYTE),
  TSM_STATUS            CHAR(1 BYTE),
  TSM_AR_IND            CHAR(1 BYTE)             DEFAULT ' ',
  TSM_TXN_CODE          CHAR(3 BYTE),
  TSM_STATUS_DESC       VARCHAR2(50 BYTE),
  TSM_CREATE_USER       VARCHAR2(20 BYTE),
  TSM_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  TSM_UPDATE_USER       VARCHAR2(20 BYTE),
  TSM_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN MMS_DEF_TXN_STATUS_MAP.TSM_TYPE IS '''A'' - Admin ''M'' - Merchant';



CREATE UNIQUE INDEX MMS_DEF_TXN_STATUS_MAP_PK ON MMS_DEF_TXN_STATUS_MAP
(TSM_TYPE, TSM_STATUS, TSM_AR_IND, TSM_TXN_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_DEF_TXN_STATUS_MAP ADD (
  CONSTRAINT MMS_DEF_TXN_STATUS_MAP_PK
  PRIMARY KEY
  (TSM_TYPE, TSM_STATUS, TSM_AR_IND, TSM_TXN_CODE)
  USING INDEX MMS_DEF_TXN_STATUS_MAP_PK
  ENABLE VALIDATE);

ALTER TABLE PHUSER.MMS_DEF_TXN_STATUS_MAP ADD (
  CONSTRAINT MMS_DEF_TXN_STATUS_MAP_FK01 
  FOREIGN KEY (TSM_TXN_CODE) 
  REFERENCES PHUSER.MMS_TXN_CODE (MTC_CODE)
  ENABLE VALIDATE);
