ALTER TABLE MATCH_DEPOSIT_STAT
 DROP PRIMARY KEY CASCADE;

DROP TABLE MATCH_DEPOSIT_STAT CASCADE CONSTRAINTS;

CREATE TABLE MATCH_DEPOSIT_STAT
(
  DS_TXN_DATE          VARCHAR2(8 BYTE),
  DS_PARTY_TYPE        CHAR(1 BYTE),
  DS_PARTY_ID          VARCHAR2(15 BYTE),
  DS_FROM_CCY          VARCHAR2(3 BYTE),
  DS_TO_CCY            VARCHAR2(3 BYTE),
  DS_FROM_AMT          NUMBER(12,2),
  DS_TO_AMT            NUMBER(12,2),
  DS_EX_RATE           NUMBER(13,5),
  DS_CREATE_USER       VARCHAR2(20 BYTE),
  DS_UPDATE_USER       VARCHAR2(20 BYTE),
  DS_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  DS_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX MATCH_DEPOSIT_STAT_IDX01 ON MATCH_DEPOSIT_STAT
(DS_TXN_DATE, DS_PARTY_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX MATCH_DEPOSIT_STAT_PK ON MATCH_DEPOSIT_STAT
(DS_TXN_DATE, DS_PARTY_TYPE, DS_PARTY_ID, DS_FROM_CCY)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MATCH_DEPOSIT_STAT ADD (
  CONSTRAINT MATCH_DEPOSIT_STAT_PK
  PRIMARY KEY
  (DS_TXN_DATE, DS_PARTY_TYPE, DS_PARTY_ID, DS_FROM_CCY)
  USING INDEX MATCH_DEPOSIT_STAT_PK
  ENABLE VALIDATE);

