ALTER TABLE CRR_OFL_TXN_DATA
 DROP PRIMARY KEY CASCADE;

DROP TABLE CRR_OFL_TXN_DATA CASCADE CONSTRAINTS;

CREATE TABLE CRR_OFL_TXN_DATA
(
  COTD_TXN_ID            VARCHAR2(16 BYTE),
  COTD_RECORD_DATE       VARCHAR2(8 BYTE),
  COTD_TXN_TYPE          VARCHAR2(3 BYTE),
  COTD_APPROVAL_DATE     VARCHAR2(8 BYTE),
  COTD_MERCH_REF         VARCHAR2(50 BYTE),
  COTD_CLIENT_ID_MERCH   VARCHAR2(10 BYTE),
  COTD_MERCH_ID          VARCHAR2(15 BYTE),
  COTD_CLIENT_ID_PROV    VARCHAR2(10 BYTE),
  COTD_PSP_ID            VARCHAR2(10 BYTE),
  COTD_BAID              VARCHAR2(20 BYTE),
  COTD_BAID_CATEGORY     VARCHAR2(10 BYTE),
  COTD_COUNTRY           CHAR(2 BYTE),
  COTD_SERVICE_CODE      VARCHAR2(3 BYTE),
  COTD_CCY               CHAR(3 BYTE),
  COTD_TXN_AMT           NUMBER(12,2),
  COTD_FEE_CCY           CHAR(3 BYTE),
  COTD_FEE               NUMBER(12,2),
  COTD_NET_CCY           CHAR(3 BYTE),
  COTD_NET_AMT           NUMBER(12,2),
  COTD_MARKUP_CCY        CHAR(3 BYTE),
  COTD_MARKUP_AMT        NUMBER(12,2),
  COTD_PSP_CCY           CHAR(3 BYTE),
  COTD_PSP_AMT           NUMBER(12,2),
  COTD_RELATED_TXN_ID    VARCHAR2(16 BYTE),
  COTD_CREATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  COTD_UPDATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  COTD_CREATE_USER       VARCHAR2(20 BYTE),
  COTD_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX CRR_OFL_TXN_DATA_IDX01 ON CRR_OFL_TXN_DATA
(COTD_APPROVAL_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX CRR_OFL_TXN_DATA_PK ON CRR_OFL_TXN_DATA
(COTD_TXN_ID, COTD_RECORD_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE CRR_OFL_TXN_DATA ADD (
  CONSTRAINT CRR_OFL_TXN_DATA_PK
  PRIMARY KEY
  (COTD_TXN_ID, COTD_RECORD_DATE)
  USING INDEX CRR_OFL_TXN_DATA_PK
  ENABLE VALIDATE);

