OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmsRuleCreditLimit
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmsRuleCreditLimit.so
SOOBJS =  MmsRuleCreditLimit.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
