DROP TABLE P2XTXN CASCADE CONSTRAINTS;

CREATE TABLE P2XTXN
(
  PX_TXN_ID                 VARCHAR2(16 BYTE)   NOT NULL,
  PX_TXN_CCY                CHAR(3 BYTE),
  PX_TXN_COUNTRY            CHAR(2 BYTE),
  PX_PAY_METHOD             VARCHAR2(50 BYTE),
  PX_BANK_CODE              VARCHAR2(10 BYTE),
  PX_BANK_NAME              VARCHAR2(50 BYTE),
  PX_BRANCH_NAME            VARCHAR2(50 BYTE),
  PX_ACCOUNT_ID             VARCHAR2(25 BYTE),
  PX_ACCOUNT_NAME           VARCHAR2(25 BYTE),
  PX_IDENTITY_ID            VARCHAR2(25 BYTE),
  PX_PROVINCE               VARCHAR2(25 BYTE),
  PX_PHONE_NO               VARCHAR2(25 BYTE),
  PX_CITY                   VARCHAR2(20 BYTE),
  PX_BATCH_ID               VARCHAR2(20 BYTE),
  PX_SHOW_PAYPAGE           CHAR(1 BYTE),
  PX_LANGUAGE               CHAR(2 BYTE),
  PX_SUCCESS_URL            VARCHAR2(255 BYTE),
  PX_FAILURE_URL            VARCHAR2(255 BYTE),
  PX_SUCCESS_CALLBACK_URL   VARCHAR2(255 BYTE),
  PX_FAILURE_CALLBACK_URL   VARCHAR2(255 BYTE),
  PX_ENCRYPT_TYPE           VARCHAR2(4 BYTE),
  PX_PAYOUT_BAL             NUMBER(14,2),
  PX_SETTLEMENT_BAL         NUMBER(14,2),
  PX_TOTAL_FLOAT            NUMBER(14,2),
  PX_TOTAL_RESERVED_AMOUNT  NUMBER(14,2),
  PX_TOTAL_TFR_HOLD         NUMBER(14,2),
  PX_TOTAL_PAYOUT_HOLD      NUMBER(14,2),
  PX_TOTAL_SETTLEMENT_HOLD  NUMBER(14,2),
  PX_VERSION_NO             INTEGER,
  PX_PAYOUT_IN_TRANSIT      NUMBER(14,2),
  PX_SETTLEMENT_IN_TRANSIT  NUMBER(14,2),
  PX_REMARK                 VARCHAR2(255 BYTE),
  PX_SELECTED_PAY_METHOD    VARCHAR2(4 BYTE),
  PX_BANNER_LOGO            VARCHAR2(255 BYTE),
  PX_CUSTOMER_TAG           VARCHAR2(10 BYTE),
  PX_ECHO_MSG_1             VARCHAR2(50 BYTE),
  PX_ECHO_MSG_2             VARCHAR2(50 BYTE),
  PX_ECHO_MSG_3             VARCHAR2(50 BYTE),
  PX_OPT_1                  VARCHAR2(50 BYTE),
  PX_OPT_2                  VARCHAR2(50 BYTE),
  PX_OPT_3                  VARCHAR2(50 BYTE),
  PX_MERCHANT_ID            VARCHAR2(15 BYTE),
  PX_MERCHANT_REF           VARCHAR2(50 BYTE),
  PX_transaction_amount	    number(14,2),
  cc_net_amount		    number(14,2),
  PX_TM_DATE                VARCHAR2(8 BYTE),
  PX_TM_TIME                VARCHAR2(6 BYTE),
  PX_TRANSMISSION_DATETIME     VARCHAR2(14 BYTE),
  PX_CLIENT_IP_ADDR         VARCHAR2(25 BYTE),
  PX_STATUS		    char(1 byte),
  PX_AR_IND		    char(1 byte),
  PX_CREATE_USER            VARCHAR2(20 BYTE),
  PX_CREATE_TIMESTAMP       DATE                DEFAULT sysdate,
  PX_UPDATE_USER            VARCHAR2(20 BYTE),
  PX_UPDATE_TIMESTAMP       DATE                DEFAULT sysdate
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX P2XTXN_IDX ON P2XTXN
(PX_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

