create or replace function sp_p2xtxn_insert(
       in_txn_id                                p2xtxn.px_txn_id%type,
       in_txn_ccy				p2xtxn.px_txn_ccy%type,
       in_txn_country				p2xtxn.px_txn_country%type,	
       in_pay_method				p2xtxn.px_pay_method%type,
       in_bank_code				p2xtxn.px_bank_code%type,
       in_bank_name				p2xtxn.px_bank_name%type,
       in_branch_name				p2xtxn.px_branch_name%type,
       in_account_id				p2xtxn.px_account_id%type,
       in_account_name				p2xtxn.px_account_name%type,
       in_identity_id				p2xtxn.px_identity_id%type,
       in_province				p2xtxn.px_province%type,
       in_phone_no				p2xtxn.px_phone_no%type,
       in_city					p2xtxn.px_city%type,
       in_batch_id				p2xtxn.px_batch_id%type,
       in_show_paypage			        p2xtxn.px_show_paypage%type,
       in_language				p2xtxn.px_language%type,
       in_success_url				p2xtxn.px_success_url%type,
       in_failure_url				p2xtxn.px_failure_url%type,
       in_success_callback_url	                p2xtxn.px_success_callback_url%type,
       in_failure_callback_url			p2xtxn.px_failure_callback_url%type,
       in_create_user                           p2xtxn.px_create_user%type,
       in_update_user                           p2xtxn.px_update_user%type,       
       in_encrypt_type				p2xtxn.px_encrypt_type%type,
       in_version_no				p2xtxn.px_version_no%type,
       in_remark				p2xtxn.px_remark%type,
       in_selected_pay_method			p2xtxn.px_selected_pay_method%type,
       in_banner_logo                           p2xtxn.px_banner_logo%type,
       in_customer_tag                          p2xtxn.px_customer_tag%type,
       in_echo_msg_1                            p2xtxn.px_echo_msg_1%type,
       in_echo_msg_2                            p2xtxn.px_echo_msg_2%type,
       in_echo_msg_3                            p2xtxn.px_echo_msg_3%type,
       in_opt_1                                 p2xtxn.px_opt_1%type,
       in_opt_2                                 p2xtxn.px_opt_2%type,
       in_opt_3                                 p2xtxn.px_opt_3%type,
       in_merchant_id                           p2xtxn.px_merchant_id%type,
       in_merchant_ref                          p2xtxn.px_merchant_ref%type,
       in_transaction_amt                       p2xtxn.px_transaction_amount%type,
       in_transmission_datetime                 p2xtxn.px_transmission_datetime%type,
       in_tm_date                               p2xtxn.px_tm_date%type,
       in_tm_time                               p2xtxn.px_tm_time%type,
       in_client_ip                             p2xtxn.px_client_ip_addr%type

	
)
  RETURN NUMBER IS
Begin
     Update p2xtxn
            Set px_txn_ccy = in_txn_ccy,
                  px_txn_country = in_txn_country,
		  px_pay_method = in_pay_method,
		  px_bank_code = in_bank_code,
		  px_bank_name = in_bank_name,
		  px_branch_name = in_branch_name,
		  px_account_id = in_account_id,
		  px_account_name = in_account_name,
		  px_identity_id = in_identity_id,
		  px_province = in_province,
		  px_phone_no = in_phone_no,
		  px_city = in_city,
		  px_batch_id = in_batch_id,
                  px_show_paypage = in_show_paypage,
                  px_language = in_language,
                  px_success_url = in_success_url,
		  px_failure_url = in_failure_url,
                  px_success_callback_url = in_success_callback_url,
		  px_failure_callback_url = in_failure_callback_url,
                  px_update_user = in_update_user,
                  px_update_timestamp = Sysdate,
		  px_encrypt_type=in_encrypt_type,
		  px_version_no = in_version_no,
		  px_remark = in_remark,
		  px_selected_pay_method = in_selected_pay_method,
		  px_banner_logo = in_banner_logo,
		  px_customer_tag = in_customer_tag,
		  px_echo_msg_1 = in_echo_msg_1,
		  px_echo_msg_2 = in_echo_msg_2,
		  px_echo_msg_3 = in_echo_msg_3,
		  px_opt_1 = in_opt_1,
		  px_opt_2 = in_opt_2,
		  px_opt_3 = in_opt_3,
	          px_merchant_id = in_merchant_id,
		  px_merchant_ref = in_merchant_ref,
		  px_transaction_amount = in_transaction_amt,
		  px_transmission_datetime = in_transmission_datetime,
                  px_tm_date = in_tm_date,
                  px_tm_time = in_tm_time,
		  px_client_ip_addr = in_client_ip
      Where px_txn_id = in_txn_id;

     IF SQL%ROWCOUNT = 0 THEN
        insert into p2xtxn
                     (px_txn_id,
		      px_txn_ccy,
		      px_txn_country,
		      px_pay_method,
                      px_bank_code,
                      px_bank_name,
                      px_branch_name,
                      px_account_id,
                      px_account_name,
                      px_identity_id,
                      px_province,
                      px_phone_no,
                      px_city,
                      px_batch_id,
		      px_show_paypage,
		      px_language,
		      px_success_url,
		      px_failure_url,
		      px_success_callback_url,
		      px_failure_callback_url,
                      px_create_user,
                      px_create_timestamp,
                      px_update_user,
                      px_update_timestamp,
		      px_encrypt_type,
		      px_version_no,
		      px_remark,
		      px_selected_pay_method,
		      px_banner_logo,
                      px_customer_tag,
                      px_echo_msg_1,
                      px_echo_msg_2,  
                      px_echo_msg_3,
                      px_opt_1,
                      px_opt_2,
                      px_opt_3,
		      px_merchant_id,
                      px_merchant_ref,
                      px_transaction_amount,
                      px_transmission_datetime,
                      px_tm_date,
                      px_tm_time,
                      px_client_ip_addr)
          values(in_txn_id,
		     in_txn_ccy,
                     in_txn_country,
		     in_pay_method,
		     in_bank_code,
		     in_bank_name,
		     in_branch_name,
		     in_account_id,
		     in_account_name,
		     in_identity_id,
		     in_province,
		     in_phone_no,
		     in_city,
		     in_batch_id,
		     in_show_paypage,
		     in_language,
		     in_success_url,
		     in_failure_url,
		     in_success_callback_url,
		     in_failure_callback_url,
                     in_create_user,
                     sysdate,
                     in_update_user,
                     sysdate,
		     in_encrypt_type,
		     in_version_no,
                     in_remark,
		     in_selected_pay_method,
		     in_banner_logo,
                     in_customer_tag,
                     in_echo_msg_1,
                     in_echo_msg_2,
                     in_echo_msg_3,
                     in_opt_1,
                     in_opt_2,
                     in_opt_3,
		     in_merchant_id,
                     in_merchant_ref,
                     in_transaction_amt,
                     in_transmission_datetime,
                     in_tm_date,
                     in_tm_time,
                     in_client_ip);

          IF SQL%ROWCOUNT = 0 THEN
             RETURN 1;
          ELSE
             RETURN 0;
          END IF;
      Else
          Return 0;
       End If;

EXCEPTION
  WHEN OTHERS THEN
     RETURN 9;
end sp_p2xtxn_insert;
/
