OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLFundsInOutHistory
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLFundsInOutHistory.so
SOOBJS =  OLFundsInOutHistory.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
