ALTER TABLE OL_TXN_ENGINE_SPC_ACTION
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_TXN_ENGINE_SPC_ACTION CASCADE CONSTRAINTS;

CREATE TABLE OL_TXN_ENGINE_SPC_ACTION
(
  ESA_SPECIAL_ACTION_DETAIL_ID       INTEGER    	  NOT NULL,
  ESA_SEQ                  	     INTEGER              NOT NULL,
  ESA_P1_CHECK_TAG         	     VARCHAR2(25 BYTE),
  ESA_P2_CHECK_TAG         	     VARCHAR2(25 BYTE),
  ESA_COMPARE_OPERATOR     	     VARCHAR2(20 BYTE),
  ESA_EXPECTED_VALUE       	     VARCHAR2(100 BYTE),
  ESA_CHECK_TYPE     	     	     VARCHAR2(20 BYTE),
  ESA_RETURNED_TAG         	     VARCHAR2(25 BYTE),
  ESA_RETURNED_VALUE       	     INTEGER,
  ESA_RETURNED_FUNCT       	     VARCHAR2(50 BYTE),
  ESA_RETURNED_TYPE       	     VARCHAR2(20 BYTE),
  ESA_TERMINATE_WHEN_ERROR  	     INTEGER,
  ESA_CREATE_TIMESTAMP     	     DATE                 DEFAULT sysdate,
  ESA_UPDATE_TIMESTAMP     	     DATE                 DEFAULT sysdate,
  ESA_CREATE_USER          	     VARCHAR2(20 BYTE),
  ESA_UPDATE_USER          	     VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_TXN_ENGINE_SPC_ACTION_PK ON OL_TXN_ENGINE_SPC_ACTION
(ESA_SPECIAL_ACTION_DETAIL_ID, ESA_SEQ)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_TXN_ENGINE_SPC_ACTION ADD (
  CONSTRAINT OL_TXN_ENGINE_SPC_ACTION_PK
  PRIMARY KEY
  (ESA_SPECIAL_ACTION_DETAIL_ID, ESA_SEQ)
  USING INDEX OL_TXN_ENGINE_SPC_ACTION_PK
  ENABLE VALIDATE);

