OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/FundsOut
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBFundsOut.so
SOOBJS =  FundsOut.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
