OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/DisabledBank
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBDisabledBank.so
SOOBJS =  DisabledBank.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
