ALTER TABLE CUSTOMER_GROUP_OFFSET_COUNT
 DROP PRIMARY KEY CASCADE;

DROP TABLE CUSTOMER_GROUP_OFFSET_COUNT CASCADE CONSTRAINTS;

CREATE TABLE CUSTOMER_GROUP_OFFSET_COUNT
(
  CGO_CODE         VARCHAR2(10 BYTE),
  CGO_COUNTRY_ID   VARCHAR2(2 BYTE),
  CGO_CHANNEL_CODE VARCHAR2(3 BYTE),
  CGO_SERVICE_CODE VARCHAR2(4 BYTE),
  CGO_CURRENCY_ID  VARCHAR2(3 BYTE),
  CGO_CATEGORY     VARCHAR2(3 BYTE),
  CGO_COUNTER      NUMBER(16,2)                 DEFAULT 0,
  CGO_CREATE_TIMESTAMP  DATE                         DEFAULT sysdate,
  CGO_CREATE_USER  VARCHAR2(20 BYTE),
  CGO_UPDATE_TIMESTAMP  DATE                         DEFAULT sysdate,
  CGO_UPDATE_USER  VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CUSTOMER_GROUP_OFFSET_COUNT_PK ON CUSTOMER_GROUP_OFFSET_COUNT
(CGO_CODE, CGO_COUNTRY_ID,CGO_CHANNEL_CODE,CGO_SERVICE_CODE,CGO_CURRENCY_ID,CGO_CATEGORY)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE CUSTOMER_GROUP_OFFSET_COUNT ADD (
  CONSTRAINT CUSTOMER_GROUP_OFFSET_COUNT_PK
  PRIMARY KEY
  (CGO_CODE, CGO_COUNTRY_ID,CGO_CHANNEL_CODE,CGO_SERVICE_CODE,CGO_CURRENCY_ID,CGO_CATEGORY)
  USING INDEX CUSTOMER_GROUP_OFFSET_COUNT_PK
  ENABLE VALIDATE);

