OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLTxnPspDetail
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLTxnPspDetail.so
SOOBJS =  OLTxnPspDetail.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
