OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/TwvBanks
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBTwvBanks.so
SOOBJS =  TwvBanks.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
