OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=chk_crr_approve_deposit.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o chk_crr_approve_deposit.o 
#
#
# Include the Common Rules
#
#

include ../../Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
