ALTER TABLE DEF_DISABLED_BANK_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_DISABLED_BANK_TYPE CASCADE CONSTRAINTS;

CREATE TABLE DEF_DISABLED_BANK_TYPE
(
  DBT_TYPE              CHAR(3 BYTE)            NOT NULL,
  DBT_DESC              VARCHAR2(50 BYTE),
  DBT_CREATE_USER       VARCHAR2(20 BYTE),
  DBT_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  DBT_UPDATE_USER       VARCHAR2(20 BYTE),
  DBT_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEF_DISABLED_BANK_TYPE_PK ON DEF_DISABLED_BANK_TYPE
(DBT_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_DISABLED_BANK_TYPE ADD (
  CONSTRAINT DEF_DISABLED_BANK_TYPE_PK
  PRIMARY KEY
  (DBT_TYPE)
  USING INDEX DEF_DISABLED_BANK_TYPE_PK
  ENABLE VALIDATE);

