OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MiEntityDetail
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMiEntityDetail.so
SOOBJS =  MiEntityDetail.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
