OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLPayoutApiBatchSupport
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLPayoutApiBatchSupport.so
SOOBJS =  OLPayoutApiBatchSupport.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
