ALTER TABLE PSP_REQUEST_TXN_URL
 DROP PRIMARY KEY CASCADE;

DROP TABLE PSP_REQUEST_TXN_URL CASCADE CONSTRAINTS;

CREATE TABLE PSP_REQUEST_TXN_URL
(
  PSP_ID            VARCHAR2(10 BYTE),
  TXN_CODE          CHAR(3 BYTE),
  REQUEST_FUNCTION  VARCHAR2(50 BYTE)           NOT NULL,
  ACTION            VARCHAR2(50 BYTE)           NOT NULL,
  CREATE_TIMESTAMP  DATE,
  UPDATE_TIMESTAMP  DATE,
  CREATE_USER       VARCHAR2(20 BYTE),
  UPDATE_USER       VARCHAR2(20 BYTE),
  URL_METHOD        VARCHAR2(10 BYTE),
  PAYMENT_METHOD    VARCHAR2(4 BYTE)            DEFAULT '010'                 NOT NULL,
  EFFECT_DATE       DATE                        NOT NULL
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PSP_REQUEST_TXN_URL_PK ON PSP_REQUEST_TXN_URL
(PSP_ID, TXN_CODE, URL_METHOD, EFFECT_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE PSP_REQUEST_TXN_URL ADD (
  CONSTRAINT PSP_REQUEST_TXN_URL_PK
  PRIMARY KEY
  (PSP_ID, TXN_CODE, URL_METHOD, EFFECT_DATE)
  USING INDEX PSP_REQUEST_TXN_URL_PK);

