OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLAutoMatchCriteria
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLAutoMatchCriteria.so
SOOBJS =  OLAutoMatchCriteria.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
