OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/CrrJnlDetailAmt
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBCrrJnlDetailAmt.so
SOOBJS =  CrrJnlDetailAmt.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
