ALTER TABLE PAYOUT_ACTION_LOCK
 DROP PRIMARY KEY CASCADE;

DROP TABLE PAYOUT_ACTION_LOCK CASCADE CONSTRAINTS;

CREATE TABLE PAYOUT_ACTION_LOCK
(
  PAL_PLATFORM  CHAR(1 BYTE),
  PAL_FLAG      INTEGER                         DEFAULT 1
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN PAYOUT_ACTION_LOCK.PAL_PLATFORM IS '''O'' - Online; ''F'' - Offline';

CREATE UNIQUE INDEX PAYOUT_ACTION_LOCK_PK ON PAYOUT_ACTION_LOCK
(PAL_PLATFORM)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PAYOUT_ACTION_LOCK ADD (
  CONSTRAINT PAYOUT_ACTION_LOCK_PK
  PRIMARY KEY
  (PAL_PLATFORM)
  USING INDEX PAYOUT_ACTION_LOCK_PK
  ENABLE VALIDATE);

