OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLWaitReconCfmList
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLWaitReconCfmList.so
SOOBJS =  OLWaitReconCfmList.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
