OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLRulePayoutWhiteList
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLRulePayoutWhiteList.so
SOOBJS =  OLRulePayoutWhiteList.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
