OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/CrrExtMerchDetail
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBCrrExtMerchDetail.so
SOOBJS =  CrrExtMerchDetail.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
