ALTER TABLE OL_RULE_EMAIL_NOTIFICATION
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_RULE_EMAIL_NOTIFICATION CASCADE CONSTRAINTS;

CREATE TABLE OL_RULE_EMAIL_NOTIFICATION
(
  ORE_EMAIL_ID          INTEGER,
  ORE_PARTY_TYPE        CHAR(1 BYTE),
  ORE_PARTY_ID          VARCHAR2(15 BYTE),
  ORE_FUNCT             VARCHAR2(10 BYTE),
  ORE_DISABLED          INTEGER,
  ORE_CREATE_USER       VARCHAR2(20 BYTE),
  ORE_UPDATE_USER       VARCHAR2(20 BYTE),
  ORE_CREATE_TIMESTAMP  DATE,
  ORE_UPDATE_TIMESTAMP  DATE
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX OL_RULE_EMAIL_NOTIFY_IDX01 ON OL_RULE_EMAIL_NOTIFICATION
(ORE_FUNCT, ORE_PARTY_TYPE, ORE_PARTY_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX OL_RULE_EMAIL_NOTIFY_PK ON OL_RULE_EMAIL_NOTIFICATION
(ORE_EMAIL_ID, ORE_PARTY_TYPE, ORE_PARTY_ID, ORE_FUNCT)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_RULE_EMAIL_NOTIFICATION ADD (
  CONSTRAINT OL_RULE_EMAIL_NOTIFY_PK
  PRIMARY KEY
  (ORE_EMAIL_ID, ORE_PARTY_TYPE, ORE_PARTY_ID, ORE_FUNCT)
  USING INDEX OL_RULE_EMAIL_NOTIFY_PK
  ENABLE VALIDATE);

ALTER TABLE OL_RULE_EMAIL_NOTIFICATION ADD (
  CONSTRAINT RUEL_EMAIL_NOTIFY_FK03 
  FOREIGN KEY (ORE_EMAIL_ID) 
  REFERENCES OL_EMAIL_NOTIFY_LIST (OEL_ID)
  ENABLE VALIDATE,
  CONSTRAINT OL_RULE_EMAIL_NOTIFY_FK01 
  FOREIGN KEY (ORE_PARTY_TYPE) 
  REFERENCES DEF_PARTY_TYPE (DP_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OL_RULE_EMAIL_NOTIFY_FK02 
  FOREIGN KEY (ORE_FUNCT) 
  REFERENCES OL_DEF_EMAIL_NOTIFY_FUNCT (OEF_FUNCT)
  ENABLE VALIDATE);

