ALTER TABLE OL_TMP_API
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_TMP_API CASCADE CONSTRAINTS;

CREATE TABLE OL_TMP_API
(
  OTA_BATCH_ID          NUMBER(16)              NOT NULL,
  OTA_FILE_ID           NUMBER(16)              NOT NULL,
  OTA_TAG_NAME          VARCHAR2(20 BYTE),
  OTA_SEQ               NUMBER(16)              NOT NULL,
  OTA_SUB_SEQ           NUMBER(16)              NOT NULL,
  OTA_TAG_VALUE         VARCHAR2(4000 BYTE),
  OTA_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate               NOT NULL,
  OTA_CREATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX IDX_OL_TMP_API_01 ON OL_TMP_API
(OTA_FILE_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX IDX_OL_TMP_API_02 ON OL_TMP_API
(OTA_CREATE_TIMESTAMP)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX OL_TMP_API_PK ON OL_TMP_API
(OTA_BATCH_ID, OTA_FILE_ID, OTA_TAG_NAME, OTA_SEQ, OTA_SUB_SEQ)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_TMP_API ADD (
  CONSTRAINT OL_TMP_API_PK
  PRIMARY KEY
  (OTA_BATCH_ID, OTA_FILE_ID, OTA_TAG_NAME, OTA_SEQ, OTA_SUB_SEQ)
  USING INDEX OL_TMP_API_PK
  ENABLE VALIDATE);

