OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/RuleOperatorTypeDetail
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBRuleOperatorTypeDetail.so
SOOBJS =  RuleOperatorTypeDetail.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
