


CREATE TABLE OL_DEF_ENGINE_CONFIG_CODE
(
  ECC_CODE              VARCHAR2(50 BYTE),
  ECC_DESC              VARCHAR2(240 BYTE),
  ECC_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  ECC_CREATE_USER       VARCHAR2(20 BYTE),
  ECC_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  ECC_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX OL_DEF_ENGINE_CONFIG_CODE_PK ON OL_DEF_ENGINE_CONFIG_CODE
(ECC_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE OL_DEF_ENGINE_CONFIG_CODE ADD (
  CONSTRAINT OL_DEF_ENGINE_CONFIG_CODE_PK
  PRIMARY KEY
  (ECC_CODE)
  USING INDEX OL_DEF_ENGINE_CONFIG_CODE_PK
  ENABLE VALIDATE);

