ALTER TABLE PSP_AMT_DIFF_RANGE 
 DROP PRIMARY KEY CASCADE;

DROP TABLE PSP_AMT_DIFF_RANGE CASCADE CONSTRAINTS;

CREATE TABLE PSP_AMT_DIFF_RANGE 
(
  PR_PSP_ID		VARCHAR2(10 BYTE), 
  PR_TYPE		CHAR(1 BYTE), 
  PR_SIGN		CHAR(1 BYTE), 
  PR_VALUE		NUMBER(12,2), 
  PR_DISABLED		INTEGER			DEFAULT 0, 
  PR_CREATE_TIMESTAMP	DATE			DEFAULT sysdate, 
  PR_CREATE_USER	VARCHAR2(20 BYTE), 
  PR_UPDATE_TIMESTAMP	DATE			DEFAULT sysdate, 
  PR_UPDATE_USER	VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA 
PCTUSED     0 
PCTFREE     10 
INITRANS    1 
MAXTRANS    255 
STORAGE     (
             INITIAL           64K 
             NEXT              1M 
             MINEXTENTS        1 
             MAXEXTENTS        UNLIMITED 
             PCTINCREASE       0 
             BUFFER_POOL       DEFAULT
            ) 
LOGGING 
NOCOMPRESS 
NOCACHE 
MONITORING;

CREATE UNIQUE INDEX PSP_AMT_DIFF_RANGE_PK ON PSP_AMT_DIFF_RANGE 
(PR_PSP_ID) 
LOGGING 
TABLESPACE USER_IDX 
PCTFREE     10 
INITRANS    2 
MAXTRANS    255 
STORAGE     (
             INITIAL           64K 
             NEXT              1M 
             MINEXTENTS        1 
             MAXEXTENTS        UNLIMITED 
             PCTINCREASE       0 
             BUFFER_POOL       DEFAULT
            );

ALTER TABLE PSP_AMT_DIFF_RANGE ADD (
  CONSTRAINT PSP_AMT_DIFF_RANGE_PK 
  PRIMARY KEY 
  (PR_PSP_ID) 
  USING INDEX PSP_AMT_DIFF_RANGE_PK 
  ENABLE VALIDATE);

ALTER TABLE PSP_AMT_DIFF_RANGE ADD (
  CONSTRAINT PSP_AMT_DIFF_RANGE_FK01 
  FOREIGN KEY (PR_TYPE) 
  REFERENCES DEF_AMOUNT (DA_TYPE) 
  ENABLE VALIDATE, 
  CONSTRAINT PSP_AMT_DIFF_RANGE_FK02 
  FOREIGN KEY (PR_SIGN) 
  REFERENCES DEF_AMT_DIFF_SIGN (DS_CODE) 
  ENABLE VALIDATE);
