OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLRuleBaidAutoGen
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLRuleBaidAutoGen.so
SOOBJS =  OLRuleBaidAutoGen.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
