OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MerchDetail
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMerchDetail.so
SOOBJS =  MerchDetail.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
