OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/PspTxnCheckReportLog
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBPspTxnCheckReportLog.so
SOOBJS =  PspTxnCheckReportLog.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
