OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MerchantReservedAmt
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMerchantReservedAmt.so
SOOBJS =  MerchantReservedAmt.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
