OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLTxnWebLog
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLTxnWebLog.so
SOOBJS =  OLTxnWebLog.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
