ALTER TABLE TEST_NINI
 DROP PRIMARY KEY CASCADE;

DROP TABLE TEST_NINI CASCADE CONSTRAINTS;

CREATE TABLE TEST_NINI
(
  TN_TXN_CODE          CHAR(3 BYTE),
  TN_SERVICE_CODE      CHAR(3 BYTE),
  TN_DAILY_LIMIT       NUMBER(14,2),
  TN_SYS_SUPPORT       INTEGER                  DEFAULT 0,
  TN_DESC              VARCHAR2(255 BYTE),
  TN_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  TN_CREATE_USER       VARCHAR2(20 BYTE),
  TN_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  TN_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX TEST_NINI_PK ON TEST_NINI
(TN_TXN_CODE,TN_SERVICE_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE TEST_NINI ADD (
  CONSTRAINT TEST_NINI_PK
  PRIMARY KEY
  (TN_TXN_CODE,TN_SERVICE_CODE)
  USING INDEX TEST_NINI_PK
  ENABLE VALIDATE);

ALTER TABLE TEST_NINI ADD (
  CONSTRAINT TEST_NINI_FK01 
  FOREIGN KEY (TN_TXN_CODE) 
  REFERENCES TXN_CODE (TC_CODE)
  ENABLE VALIDATE);


ALTER TABLE TEST_NINI ADD (
  CONSTRAINT TEST_NINI_FK02 
  FOREIGN KEY (TN_SERVICE_CODE) 
  REFERENCES DEF_SERVICE_CODE (SC_CODE)
  ENABLE VALIDATE);
