/* haipay.h
   Generated by wsdl2h 2.8.0 from http://pay.happycz.net/Services/BatchService.asmx?wsdl and typemap.dat
   2011-03-04 03:36:13 GMT

   DO NOT INCLUDE THIS FILE DIRECTLY INTO YOUR PROJECT BUILDS
   USE THE soapcpp2-GENERATED SOURCE CODE FILES FOR YOUR PROJECT BUILDS

   gSOAP XML Web services tools.
   Copyright (C) 2001-2010 Robert van Engelen, Genivia Inc. All Rights Reserved.
   Part of this software is released under one of the following licenses:
   GPL or Genivia's license for commercial use.
*/

/** @page page_notes Usage Notes

NOTE:

 - Run soapcpp2 on haipay.h to generate the SOAP/XML processing logic.
   Use soapcpp2 option -I to specify paths for #import
   To build with STL, 'stlvector.h' is imported from 'import' dir in package.
   Use soapcpp2 option -i to generate improved proxy and server classes.
 - Use wsdl2h options -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Use Doxygen (www.doxygen.org) on this file to generate documentation.
 - Use wsdl2h options -nname and -Nname to globally rename the prefix 'ns'.
 - Use wsdl2h option -d to enable DOM support for xsd:anyType.
 - Use wsdl2h option -g to auto-generate readers and writers for root elements.
 - Struct/class members serialized as XML attributes are annotated with a '@'.
 - Struct/class members that have a special role are annotated with a '$'.

WARNING:

   DO NOT INCLUDE THIS FILE DIRECTLY INTO YOUR PROJECT BUILDS.
   USE THE SOURCE CODE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT BUILDS:
   THE soapStub.h FILE CONTAINS THIS CONTENT WITHOUT ANNOTATIONS.

LICENSE:

@verbatim
--------------------------------------------------------------------------------
gSOAP XML Web services tools
Copyright (C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.

This software is released under one of the following two licenses:
1) GPL or 2) Genivia's license for commercial use.
--------------------------------------------------------------------------------
1) GPL license.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place, Suite 330, Boston, MA 02111-1307 USA

Author contact information:
engelen@genivia.com / engelen@acm.org
--------------------------------------------------------------------------------
2) A commercial-use license is available from Genivia, Inc., contact@genivia.com
--------------------------------------------------------------------------------
@endverbatim

*/


//gsoapopt cw

/******************************************************************************\
 *                                                                            *
 * Definitions                                                                *
 *   http://merchant.happycz.com.cn                                           *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/

// This service uses SOAP 1.2 namespaces:
//gsoap SOAP-ENV schema namespace:	http://www.w3.org/2003/05/soap-envelope
//gsoap SOAP-ENC schema namespace:	http://www.w3.org/2003/05/soap-encoding

/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

ns1 = "http://merchant.happycz.com.cn"

*/

#define SOAP_NAMESPACE_OF_ns1	"http://merchant.happycz.com.cn"
//gsoap ns1   schema namespace:	http://merchant.happycz.com.cn
//gsoap ns1   schema elementForm:	qualified
//gsoap ns1   schema attributeForm:	unqualified

/******************************************************************************\
 *                                                                            *
 * Built-in Schema Types and Top-Level Elements and Attributes                *
 *                                                                            *
\******************************************************************************/



/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://merchant.happycz.com.cn                                           *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   http://merchant.happycz.com.cn                                           *
 *                                                                            *
\******************************************************************************/


/// "http://merchant.happycz.com.cn":DetailMsg is a complexType.
struct ns1__DetailMsg
{
/// Element Count of type xs:int.
    int                                  Count                          1;	///< Required element.
/// Element ErrCode of type xs:string.
    char*                                ErrCode                        0;	///< Optional element.
/// Element ReturnRecords of type "http://merchant.happycz.com.cn":ArrayOfReturnRecord.
    struct ns1__ArrayOfReturnRecord*     ReturnRecords                  0;	///< Optional element.
/// Element ReturnRecordSubs of type "http://merchant.happycz.com.cn":ArrayOfReturnRecordSub.
    struct ns1__ArrayOfReturnRecordSub*  ReturnRecordSubs               0;	///< Optional element.
};

/// "http://merchant.happycz.com.cn":ArrayOfReturnRecord is a complexType.
struct ns1__ArrayOfReturnRecord
{
/// Size of array of struct ns1__ReturnRecord* is 0..unbounded
   $int                                  __sizeReturnRecord             0;
/// Array struct ns1__ReturnRecord* of length 0..unbounded
    struct ns1__ReturnRecord*            ReturnRecord                   0;
};

/// "http://merchant.happycz.com.cn":ReturnRecord is a complexType.
struct ns1__ReturnRecord
{
/// Element ProjectId of type xs:string.
    char*                                ProjectId                      0;	///< Optional element.
/// Element BatchId of type xs:string.
    char*                                BatchId                        0;	///< Optional element.
/// Element BatchName of type xs:string.
    char*                                BatchName                      0;	///< Optional element.
/// Element Cr_Code of type xs:string.
    char*                                Cr_USCORECode                  0;	///< Optional element.
/// Element Amounts of type xs:long.
    LONG64                               Amounts                        1;	///< Required element.
/// Element PayAmount of type xs:long.
    LONG64                               PayAmount                      1;	///< Required element.
/// Element ReceiveAmount of type xs:long.
    LONG64                               ReceiveAmount                  1;	///< Required element.
/// Element Flag of type xs:string.
    char*                                Flag                           0;	///< Optional element.
/// Element Sign of type xs:string.
    char*                                Sign                           0;	///< Optional element.
};

/// "http://merchant.happycz.com.cn":ArrayOfReturnRecordSub is a complexType.
struct ns1__ArrayOfReturnRecordSub
{
/// Size of array of struct ns1__ReturnRecordSub* is 0..unbounded
   $int                                  __sizeReturnRecordSub          0;
/// Array struct ns1__ReturnRecordSub* of length 0..unbounded
    struct ns1__ReturnRecordSub*         ReturnRecordSub                0;
};

/// "http://merchant.happycz.com.cn":ReturnRecordSub is a complexType.
struct ns1__ReturnRecordSub
{
/// Element DetailsNew of type xs:string.
    char*                                DetailsNew                     0;	///< Optional element.
/// Element AmountsNew of type xs:long.
    LONG64                               AmountsNew                     1;	///< Required element.
/// Element PayAmountNew of type xs:long.
    LONG64                               PayAmountNew                   1;	///< Required element.
/// Element ReceiveAmountNew of type xs:long.
    LONG64                               ReceiveAmountNew               1;	///< Required element.
};


/// Top-level root element "http://merchant.happycz.com.cn":BatchIn

/// "http://merchant.happycz.com.cn":BatchIn is a complexType.
struct _ns1__BatchIn
{
/// Element MERCODE of type xs:string.
    char*                                MERCODE                        0;	///< Optional element.
/// Element DETAILSID of type xs:string.
    char*                                DETAILSID                      0;	///< Optional element.
/// Element FLAG of type xs:int.
    int                                  FLAG                           1;	///< Required element.
/// Element NAME of type xs:string.
    char*                                NAME                           0;	///< Optional element.
/// Element IDCARD of type xs:string.
    char*                                IDCARD                         0;	///< Optional element.
/// Element MOBILEPHONE of type xs:string.
    char*                                MOBILEPHONE                    0;	///< Optional element.
/// Element BANKNAME of type xs:string.
    char*                                BANKNAME                       0;	///< Optional element.
/// Element BRANCHBANKNAME of type xs:string.
    char*                                BRANCHBANKNAME                 0;	///< Optional element.
/// Element ACCOUNT of type xs:string.
    char*                                ACCOUNT                        0;	///< Optional element.
/// Element AMOUNT of type xs:string.
    char*                                AMOUNT                         0;	///< Optional element.
/// Element DCREATETIME of type xs:string.
    char*                                DCREATETIME                    0;	///< Optional element.
/// Element PROVINCENAME of type xs:string.
    char*                                PROVINCENAME                   0;	///< Optional element.
/// Element CITYNAME of type xs:string.
    char*                                CITYNAME                       0;	///< Optional element.
/// Element SIGN of type xs:string.
    char*                                SIGN                           0;	///< Optional element.
};


/// Top-level root element "http://merchant.happycz.com.cn":BatchInResponse

/// "http://merchant.happycz.com.cn":BatchInResponse is a complexType.
struct _ns1__BatchInResponse
{
/// Element BatchInResult of type "http://merchant.happycz.com.cn":DetailMsg.
    struct ns1__DetailMsg*               BatchInResult                  1;	///< Required element.
};

/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   http://merchant.happycz.com.cn                                           *
 *                                                                            *
\******************************************************************************/


/// Top-level root element "http://merchant.happycz.com.cn":DetailMsg of type "http://merchant.happycz.com.cn":DetailMsg.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   http://merchant.happycz.com.cn                                           *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/


//gsoap ns2  service name:	BatchServiceSoap 
//gsoap ns2  service type:	BatchServiceSoap 
//gsoap ns2  service port:	http://pay.happycz.net/Services/BatchService.asmx 
//gsoap ns2  service namespace:	http://merchant.happycz.com.cn/BatchServiceSoap 
//gsoap ns2  service transport:	http://schemas.xmlsoap.org/soap/http 

//gsoap ns3  service name:	BatchServiceSoap12 
//gsoap ns3  service type:	BatchServiceSoap 
//gsoap ns3  service port:	http://pay.happycz.net/Services/BatchService.asmx 
//gsoap ns3  service namespace:	http://merchant.happycz.com.cn/BatchServiceSoap12 
//gsoap ns3  service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage Service Definitions

@section Service_bindings Service Bindings

  - @ref BatchServiceSoap

  - @ref BatchServiceSoap12

@section Service_more More Information

  - @ref page_notes "Usage Notes"

  - @ref page_XMLDataBinding "XML Data Binding"

  - @ref SOAP_ENV__Header "SOAP Header Content" (when applicable)

  - @ref SOAP_ENV__Detail "SOAP Fault Detail Content" (when applicable)


*/

/**

@page BatchServiceSoap Binding "BatchServiceSoap"

@section BatchServiceSoap_operations Operations of Binding  "BatchServiceSoap"

  - @ref __ns2__BatchIn

@section BatchServiceSoap_ports Endpoints of Binding  "BatchServiceSoap"

  - http://pay.happycz.net/Services/BatchService.asmx

Note: use wsdl2h option -N to change the service binding prefix name

*/

/**

@page BatchServiceSoap12 Binding "BatchServiceSoap12"

@section BatchServiceSoap12_operations Operations of Binding  "BatchServiceSoap12"

  - @ref __ns3__BatchIn

@section BatchServiceSoap12_ports Endpoints of Binding  "BatchServiceSoap12"

  - http://pay.happycz.net/Services/BatchService.asmx

Note: use wsdl2h option -N to change the service binding prefix name

*/

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   BatchServiceSoap                                                         *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns2__BatchIn                                                           *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns2__BatchIn" of service binding "BatchServiceSoap"

/**

Operation details:

insert batchdetails

  - SOAP document/literal style messaging

  - SOAP action="http://merchant.happycz.com.cn/BatchIn"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns2__BatchIn(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    struct _ns1__BatchIn*               ns1__BatchIn,
    // response parameters:
    struct _ns1__BatchInResponse*       ns1__BatchInResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns2__BatchIn(
    struct soap *soap,
    // request parameters:
    struct _ns1__BatchIn*               ns1__BatchIn,
    // response parameters:
    struct _ns1__BatchInResponse*       ns1__BatchInResponse
  );
@endcode

*/

//gsoap ns2  service method-style:	BatchIn document
//gsoap ns2  service method-encoding:	BatchIn literal
//gsoap ns2  service method-action:	BatchIn http://merchant.happycz.com.cn/BatchIn
int __ns2__BatchIn(
    struct _ns1__BatchIn*               ns1__BatchIn,	///< Request parameter
    struct _ns1__BatchInResponse*       ns1__BatchInResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   BatchServiceSoap12                                                       *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns3__BatchIn                                                           *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns3__BatchIn" of service binding "BatchServiceSoap12"

/**

Operation details:

insert batchdetails

  - SOAP document/literal style messaging

  - SOAP action="http://merchant.happycz.com.cn/BatchIn"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns3__BatchIn(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    struct _ns1__BatchIn*               ns1__BatchIn,
    // response parameters:
    struct _ns1__BatchInResponse*       ns1__BatchInResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns3__BatchIn(
    struct soap *soap,
    // request parameters:
    struct _ns1__BatchIn*               ns1__BatchIn,
    // response parameters:
    struct _ns1__BatchInResponse*       ns1__BatchInResponse
  );
@endcode

*/

//gsoap ns3  service method-style:	BatchIn document
//gsoap ns3  service method-encoding:	BatchIn literal
//gsoap ns3  service method-action:	BatchIn http://merchant.happycz.com.cn/BatchIn
int __ns3__BatchIn(
    struct _ns1__BatchIn*               ns1__BatchIn,	///< Request parameter
    struct _ns1__BatchInResponse*       ns1__BatchInResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * XML Data Binding                                                           *
 *                                                                            *
\******************************************************************************/


/**

@page page_XMLDataBinding XML Data Binding

SOAP/XML services use data bindings contractually bound by WSDL and auto-
generated by wsdl2h and soapcpp2 (see Service Bindings). Plain data bindings
are adopted from XML schemas as part of the WSDL types section or when running
wsdl2h on a set of schemas to produce non-SOAP-based XML data bindings.

The following readers and writers are C/C++ data type (de)serializers auto-
generated by wsdl2h and soapcpp2. Run soapcpp2 on this file to generate the
(de)serialization code, which is stored in soapC.c[pp]. Include "soapH.h" in
your code to import these data type and function declarations. Only use the
soapcpp2-generated files in your project build. Do not include the wsdl2h-
generated .h file in your code.

XML content can be retrieved from:
  - a file descriptor, using soap->recvfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->is = ...
  - a buffer, using the soap->frecv() callback

XML content can be stored to:
  - a file descriptor, using soap->sendfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->os = ...
  - a buffer, using the soap->fsend() callback


@section ns1 Top-level root elements of schema "http://merchant.happycz.com.cn"

  - <ns1:BatchIn> @ref _ns1__BatchIn
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__BatchIn(struct soap*, struct _ns1__BatchIn*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__BatchIn(struct soap*, struct _ns1__BatchIn*);
    @endcode

  - <ns1:BatchInResponse> @ref _ns1__BatchInResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__BatchInResponse(struct soap*, struct _ns1__BatchInResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__BatchInResponse(struct soap*, struct _ns1__BatchInResponse*);
    @endcode

  - <ns1:DetailMsg> (use wsdl2h option -g to auto-generate)

*/

/* End of haipay.h */
