/* soapStub.h
   Generated by gSOAP 2.8.0 from haipay.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   The generated code is released under one of the following licenses:
   GPL OR Genivia's license for commercial use.
*/

#ifndef soapStub_H
#define soapStub_H
#define SOAP_NAMESPACE_OF_ns1	"http://merchant.happycz.com.cn"
#include "stdsoap2.h"
#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE_ns1__DetailMsg
#define SOAP_TYPE_ns1__DetailMsg (7)
/* ns1:DetailMsg */
struct ns1__DetailMsg
{
	int Count;	/* required element of type xsd:int */
	char *ErrCode;	/* optional element of type xsd:string */
	struct ns1__ArrayOfReturnRecord *ReturnRecords;	/* optional element of type ns1:ArrayOfReturnRecord */
	struct ns1__ArrayOfReturnRecordSub *ReturnRecordSubs;	/* optional element of type ns1:ArrayOfReturnRecordSub */
};
#endif

#ifndef SOAP_TYPE_ns1__ArrayOfReturnRecord
#define SOAP_TYPE_ns1__ArrayOfReturnRecord (8)
/* ns1:ArrayOfReturnRecord */
struct ns1__ArrayOfReturnRecord
{
	int __sizeReturnRecord;	/* sequence of elements <ReturnRecord> */
	struct ns1__ReturnRecord *ReturnRecord;	/* optional element of type ns1:ReturnRecord */
};
#endif

#ifndef SOAP_TYPE_ns1__ReturnRecord
#define SOAP_TYPE_ns1__ReturnRecord (12)
/* ns1:ReturnRecord */
struct ns1__ReturnRecord
{
	char *ProjectId;	/* optional element of type xsd:string */
	char *BatchId;	/* optional element of type xsd:string */
	char *BatchName;	/* optional element of type xsd:string */
	char *Cr_USCORECode;	/* optional element of type xsd:string */
	LONG64 Amounts;	/* required element of type xsd:long */
	LONG64 PayAmount;	/* required element of type xsd:long */
	LONG64 ReceiveAmount;	/* required element of type xsd:long */
	char *Flag;	/* optional element of type xsd:string */
	char *Sign;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__ArrayOfReturnRecordSub
#define SOAP_TYPE_ns1__ArrayOfReturnRecordSub (10)
/* ns1:ArrayOfReturnRecordSub */
struct ns1__ArrayOfReturnRecordSub
{
	int __sizeReturnRecordSub;	/* sequence of elements <ReturnRecordSub> */
	struct ns1__ReturnRecordSub *ReturnRecordSub;	/* optional element of type ns1:ReturnRecordSub */
};
#endif

#ifndef SOAP_TYPE_ns1__ReturnRecordSub
#define SOAP_TYPE_ns1__ReturnRecordSub (15)
/* ns1:ReturnRecordSub */
struct ns1__ReturnRecordSub
{
	char *DetailsNew;	/* optional element of type xsd:string */
	LONG64 AmountsNew;	/* required element of type xsd:long */
	LONG64 PayAmountNew;	/* required element of type xsd:long */
	LONG64 ReceiveAmountNew;	/* required element of type xsd:long */
};
#endif

#ifndef SOAP_TYPE__ns1__BatchIn
#define SOAP_TYPE__ns1__BatchIn (17)
/* ns1:BatchIn */
struct _ns1__BatchIn
{
	char *MERCODE;	/* optional element of type xsd:string */
	char *DETAILSID;	/* optional element of type xsd:string */
	int FLAG;	/* required element of type xsd:int */
	char *NAME;	/* optional element of type xsd:string */
	char *IDCARD;	/* optional element of type xsd:string */
	char *MOBILEPHONE;	/* optional element of type xsd:string */
	char *BANKNAME;	/* optional element of type xsd:string */
	char *BRANCHBANKNAME;	/* optional element of type xsd:string */
	char *ACCOUNT;	/* optional element of type xsd:string */
	char *AMOUNT;	/* optional element of type xsd:string */
	char *DCREATETIME;	/* optional element of type xsd:string */
	char *PROVINCENAME;	/* optional element of type xsd:string */
	char *CITYNAME;	/* optional element of type xsd:string */
	char *SIGN;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__BatchInResponse
#define SOAP_TYPE__ns1__BatchInResponse (18)
/* ns1:BatchInResponse */
struct _ns1__BatchInResponse
{
	struct ns1__DetailMsg *BatchInResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ns1:DetailMsg */
};
#endif

#ifndef SOAP_TYPE___ns2__BatchIn
#define SOAP_TYPE___ns2__BatchIn (23)
/* Operation wrapper: */
struct __ns2__BatchIn
{
	struct _ns1__BatchIn *ns1__BatchIn;	/* optional element of type ns1:BatchIn */
};
#endif

#ifndef SOAP_TYPE___ns3__BatchIn
#define SOAP_TYPE___ns3__BatchIn (25)
/* Operation wrapper: */
struct __ns3__BatchIn
{
	struct _ns1__BatchIn *ns1__BatchIn;	/* optional element of type ns1:BatchIn */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (26)
/* SOAP Header: */
struct SOAP_ENV__Header
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (27)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (29)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
	char *__any;
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (32)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (33)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Server-Side Operations                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 __ns2__BatchIn(struct soap*, struct _ns1__BatchIn *ns1__BatchIn, struct _ns1__BatchInResponse *ns1__BatchInResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns3__BatchIn(struct soap*, struct _ns1__BatchIn *ns1__BatchIn, struct _ns1__BatchInResponse *ns1__BatchInResponse);

/******************************************************************************\
 *                                                                            *
 * Server-Side Skeletons to Invoke Service Operations                         *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns2__BatchIn(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns3__BatchIn(struct soap*);

/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stubs                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns2__BatchIn(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__BatchIn *ns1__BatchIn, struct _ns1__BatchInResponse *ns1__BatchInResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns3__BatchIn(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__BatchIn *ns1__BatchIn, struct _ns1__BatchInResponse *ns1__BatchInResponse);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
