/* soapClient.c
   Generated by gSOAP 2.8.0 from haipay.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   The generated code is released under one of the following licenses:
   GPL OR Genivia's license for commercial use.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.8.0 2011-03-04 03:36:18 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns2__BatchIn(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__BatchIn *ns1__BatchIn, struct _ns1__BatchInResponse *ns1__BatchInResponse)
{	struct __ns2__BatchIn soap_tmp___ns2__BatchIn;
	if (!soap_endpoint)
		soap_endpoint = "http://pay.happycz.net/Services/BatchService.asmx";
	if (!soap_action)
		soap_action = "http://merchant.happycz.com.cn/BatchIn";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__BatchIn.ns1__BatchIn = ns1__BatchIn;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__BatchIn(soap, &soap_tmp___ns2__BatchIn);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__BatchIn(soap, &soap_tmp___ns2__BatchIn, "-ns2:BatchIn", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__BatchIn(soap, &soap_tmp___ns2__BatchIn, "-ns2:BatchIn", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__BatchInResponse)
		return soap_closesock(soap);
	soap_default__ns1__BatchInResponse(soap, ns1__BatchInResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__BatchInResponse(soap, ns1__BatchInResponse, "ns1:BatchInResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns3__BatchIn(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__BatchIn *ns1__BatchIn, struct _ns1__BatchInResponse *ns1__BatchInResponse)
{	struct __ns3__BatchIn soap_tmp___ns3__BatchIn;
	if (!soap_endpoint)
		soap_endpoint = "http://pay.happycz.net/Services/BatchService.asmx";
	if (!soap_action)
		soap_action = "http://merchant.happycz.com.cn/BatchIn";
	soap->encodingStyle = NULL;
	soap_tmp___ns3__BatchIn.ns1__BatchIn = ns1__BatchIn;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns3__BatchIn(soap, &soap_tmp___ns3__BatchIn);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__BatchIn(soap, &soap_tmp___ns3__BatchIn, "-ns3:BatchIn", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__BatchIn(soap, &soap_tmp___ns3__BatchIn, "-ns3:BatchIn", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__BatchInResponse)
		return soap_closesock(soap);
	soap_default__ns1__BatchInResponse(soap, ns1__BatchInResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__BatchInResponse(soap, ns1__BatchInResponse, "ns1:BatchInResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
