OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/CrrJnlChangeLog
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBCrrJnlChangeLog.so
SOOBJS =  CrrJnlChangeLog.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
