ALTER TABLE MOB_BANK_SELECT
 DROP PRIMARY KEY CASCADE;

DROP TABLE MOB_BANK_SELECT CASCADE CONSTRAINTS;

CREATE TABLE MOB_BANK_SELECT
(
  MBS_GROUP             VARCHAR2(10 BYTE),
  MBS_BANK_CODE         VARCHAR2(10 BYTE),
  MBS_IS_DEFAULT	INTEGER                  DEFAULT 0,
  MBS_DISABLED		INTEGER			 DEFAULT 0,
  MBS_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  MBS_CREATE_USER       VARCHAR2(20 BYTE),
  MBS_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  MBS_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MOB_BANK_SELECT_PK ON MOB_BANK_SELECT
(MBS_GROUP,MBS_BANK_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MOB_BANK_SELECT ADD (
  CONSTRAINT MOB_BANK_SELECT_PK
  PRIMARY KEY
  (MBS_GROUP,MBS_BANK_CODE)
  USING INDEX MOB_BANK_SELECT_PK
  ENABLE VALIDATE);

