OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MobSegmentThreshold
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMobSegmentThreshold.so
SOOBJS =  MobSegmentThreshold.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
