OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/PspPayoutFileFormatMapping
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBPspPayoutFileFormatMapping.so
SOOBJS =  PspPayoutFileFormatMapping.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
