OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/PspTxnCheck
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBPspTxnCheck.so
SOOBJS =  PspTxnCheck.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
