ALTER TABLE HOLD_AMOUNT
 DROP PRIMARY KEY CASCADE;

DROP TABLE HOLD_AMOUNT CASCADE CONSTRAINTS;

CREATE TABLE HOLD_AMOUNT
(
  HV_MERCHANT_ID            VARCHAR2(10 BYTE),
  HV_CURRENCY_ID            VARCHAR2(3 BYTE),
  HV_COUNTRY_ID             CHAR(2 BYTE),
  HV_SERVICE_CODE           CHAR(3 BYTE),
  HV_TYPE         CHAR(2 BYTE),
  HV_TOTAL_HOLD   NUMBER(14,2),
  HV_HOLDED_AMT   NUMBER(14,2),
  HV_HOLD_REMAIN  NUMBER(14,2),
  HV_STATE	  CHAR(1 BYTE),
  HV_CREATE_USER       VARCHAR2(20 BYTE),
  HV_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  HV_UPDATE_USER       VARCHAR2(20 BYTE),
  HV_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX HOLD_AMOUNT_PK ON HOLD_AMOUNT
(HV_MERCHANT_ID, HV_CURRENCY_ID, HV_COUNTRY_ID, HV_SERVICE_CODE, HV_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE HOLD_AMOUNT ADD (
  CONSTRAINT HOLD_AMOUNT_PK
  PRIMARY KEY
  (HV_MERCHANT_ID, HV_CURRENCY_ID, HV_COUNTRY_ID, HV_SERVICE_CODE, HV_TYPE)
  USING INDEX HOLD_AMOUNT_PK);

ALTER TABLE HOLD_AMOUNT
 ADD CONSTRAINT HOLD_AMOUNT_FK01 
  FOREIGN KEY (HV_TYPE) 
  REFERENCES DEF_HOLD_TYPE (DH_TYPE);

CREATE INDEX HOLD_AMOUNT_IDX01 ON HOLD_AMOUNT
(HV_STATE)
LOGGING
TABLESPACE USER_IDX
NOPARALLEL
