ALTER TABLE OL_SIM_CARDS
 ADD (OSC_SIM_NATURE  CHAR(3 BYTE));

ALTER TABLE OL_SIM_CARDS
 ADD CONSTRAINT OL_SIM_CARDS_FK04 
  FOREIGN KEY (OSC_SIM_NATURE) 
  REFERENCES OL_DEF_BANK_ACCT_TYPE (OBC_TYPE)
  ENABLE VALIDATE;
