ALTER TABLE OL_SIM_CARDS
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_SIM_CARDS CASCADE CONSTRAINTS;

CREATE TABLE OL_SIM_CARDS
(
  OSC_MOBILE            VARCHAR2(20 BYTE),
  OSC_CARRIERS         	VARCHAR2(3 BYTE)        NOT NULL,
  OSC_COUNTRY           VARCHAR2(2 BYTE)       	NOT NULL,
  OSC_OWNER_NAME        VARCHAR2(50 BYTE),
  OSC_SIM_CREDIT        NUMBER(12,2)            NOT NULL,
  OSC_SIM_PACKAGE       VARCHAR2(50 BYTE),      NOT NULL,
  OSC_SIM_CURRENCY      VARCHAR2(3 BYTE)        NOT NULL,
  OSC_BILLED_DATE       INTEGER,
  OSC_LAST_TOPUP_DATE   VARCHAR2(8 BYTE)        NOT NULL,
  OSC_NEXT_TOPUP_DATE   VARCHAR2(8 BYTE)        NOT NULL,
  OSC_EXPIRED_DATE	VARCHAR2(8 BYTE)	NOT NULL,
  OSC_PASSWORD          VARCHAR2(40 BYTE),
  OSC_STATUS            CHAR(1 BYTE)            NOT NULL,
  OSC_REMARKS           VARCHAR2(100 BYTE),
  OSC_SIM_NATURE        CHAR(3 BYTE),
  OSC_CREATE_TIMESTAMP  DATE                    DEFAULT SYSDATE,
  OSC_CREATE_USER       VARCHAR2(20 BYTE),
  OSC_UPDATE_TIMESTAMP  DATE                    DEFAULT SYSDATE,
  OSC_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_SIM_CARDS_PK ON OL_SIM_CARDS
(OSC_MOBILE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_SIM_CARDS ADD (
  CONSTRAINT OL_SIM_CARDS_PK
  PRIMARY KEY
  (OSC_MOBILE)
  USING INDEX OL_SIM_CARDS_PK
  ENABLE VALIDATE);

ALTER TABLE OL_SIM_CARDS ADD (
  CONSTRAINT OL_SIM_CARDS_FK01 
  FOREIGN KEY (OSC_CARRIERS) 
  REFERENCES OL_DEF_SIM_CARRIERS (DSC_CARRIER_CODE)
  ENABLE VALIDATE,
  CONSTRAINT OL_SIM_CARDS_FK02 
  FOREIGN KEY (OSC_SIM_CURRENCY) 
  REFERENCES DEF_CURRENCY (DC_CCY_ID)
  ENABLE VALIDATE,
  CONSTRAINT OL_SIM_CARDS_FK03 
  FOREIGN KEY (OSC_STATUS) 
  REFERENCES OL_DEF_SIM_CARD_STATUS (DSCS_STATUS_CODE)
  ENABLE VALIDATE,
  CONSTRAINT OL_SIM_CARDS_FK04
  FOREIGN KEY (OSC_SIM_NATURE)
  REFERENCES OL_DEF_BANK_ACCT_TYPE (OBC_TYPE)
  ENABLE VALIDATE);
