


ALTER TABLE ACCT_LEDGER_DAILY_REPORT
 DROP PRIMARY KEY CASCADE;

DROP TABLE ACCT_LEDGER_DAILY_REPORT CASCADE CONSTRAINTS;

CREATE TABLE ACCT_LEDGER_DAILY_REPORT
(
  ALDR_MERCHANT_ID       VARCHAR2(15 BYTE)      NOT NULL,
  ALDR_COUNTRY_ID        CHAR(2 BYTE)           NOT NULL,
  ALDR_CURRENCY_ID       VARCHAR2(3 BYTE)       NOT NULL,
  ALDR_SERVICE_CODE      CHAR(3 BYTE)           NOT NULL,
  ALDR_LEDGER_TYPE       CHAR(1 BYTE)           NOT NULL,
  ALDR_REPORT_DATE       VARCHAR2(8 BYTE)       NOT NULL,
  ALDR_FILENAME          VARCHAR2(100 BYTE),
  ALDR_STATUS            CHAR(1 BYTE),
  ALDR_DISABLED          INTEGER                DEFAULT 0,
  ALDR_CREATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  ALDR_CREATE_USER       VARCHAR2(20 BYTE),
  ALDR_UPDATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  ALDR_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE INDEX ACCT_LEDGER_DAILY_REPORT_IDX1 ON ACCT_LEDGER_DAILY_REPORT
(ALDR_REPORT_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX ACCT_LEDGER_DAILY_REPORT_PK ON ACCT_LEDGER_DAILY_REPORT
(ALDR_MERCHANT_ID, ALDR_COUNTRY_ID, ALDR_CURRENCY_ID, ALDR_SERVICE_CODE, ALDR_LEDGER_TYPE, 
ALDR_REPORT_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE ACCT_LEDGER_DAILY_REPORT ADD (
  CONSTRAINT ACCT_LEDGER_DAILY_REPORT_PK
  PRIMARY KEY
  (ALDR_MERCHANT_ID, ALDR_COUNTRY_ID, ALDR_CURRENCY_ID, ALDR_SERVICE_CODE, ALDR_LEDGER_TYPE, ALDR_REPORT_DATE)
  USING INDEX ACCT_LEDGER_DAILY_REPORT_PK
  ENABLE VALIDATE);

ALTER TABLE ACCT_LEDGER_DAILY_REPORT ADD (
  CONSTRAINT ACCT_LEDGER_DAILY_REPORT_FK01 
  FOREIGN KEY (ALDR_MERCHANT_ID) 
  REFERENCES MERCH_DETAIL (MERCHANT_ID)
  ENABLE VALIDATE,
  CONSTRAINT ACCT_LEDGER_DAILY_REPORT_FK02 
  FOREIGN KEY (ALDR_COUNTRY_ID) 
  REFERENCES COUNTRY (COUNTRY_CODE)
  ENABLE VALIDATE,
  CONSTRAINT ACCT_LEDGER_DAILY_REPORT_FK03 
  FOREIGN KEY (ALDR_CURRENCY_ID) 
  REFERENCES DEF_CURRENCY (DC_CCY_ID)
  ENABLE VALIDATE,
  CONSTRAINT ACCT_LEDGER_DAILY_REPORT_FK04 
  FOREIGN KEY (ALDR_SERVICE_CODE) 
  REFERENCES DEF_SERVICE_CODE (SC_CODE)
  ENABLE VALIDATE,
  CONSTRAINT ACCT_LEDGER_DAILY_REPORT_FK05 
  FOREIGN KEY (ALDR_STATUS) 
  REFERENCES DEF_PREGEN_RPT_STATUS (DS_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT ACCT_LEDGER_DAILY_REPORT_FK06 
  FOREIGN KEY (ALDR_LEDGER_TYPE) 
  REFERENCES DEF_LEDGER_TYPE (DL_TYPE)
  ENABLE VALIDATE);
