OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLDefEngineConfigCode
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLDefEngineConfigCode.so
SOOBJS = OLDefEngineConfigCode.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
