ALTER TABLE DEPOSIT_REQUEST_LOG
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEPOSIT_REQUEST_LOG CASCADE CONSTRAINTS;

CREATE TABLE DEPOSIT_REQUEST_LOG
(
  REQUEST_LOG_ID        INTEGER			NOT NULL,
  PROCESS_CODE          CHAR(6 CHAR)            NOT NULL,
  PROCESS_TYPE          CHAR(4 CHAR)            NOT NULL,
  PAY_AMT               NUMBER(18,2)            NOT NULL,
  CURRENCY              VARCHAR2(3 BYTE)        NOT NULL,
  REFERENCE             VARCHAR2(50 BYTE)       NOT NULL,
  REQUEST_TIME          VARCHAR2(14 BYTE)       NOT NULL,
  MERCHANT_ID           VARCHAR2(20 BYTE)       NOT NULL,
  COUNTRY_ID            VARCHAR2(3 BYTE)        NOT NULL,
  CHANNEL_ID            VARCHAR2(10 BYTE)       NOT NULL,
  BANK_CODE             VARCHAR2(10 BYTE)       NOT NULL,
  SHOW_PAYPAGE		SMALLINT		NOT NULL,
  LANGUAGE_ID           VARCHAR2(3 BYTE)        NOT NULL,
  SUCCESS_URL           VARCHAR2(255 BYTE)      NOT NULL,
  FAILURE_URL           VARCHAR2(255 BYTE)      NOT NULL,
  SUCCESS_CALLBACK_URL  VARCHAR2(255 BYTE)      NOT NULL,
  FAILURE_CALLBACK_URL  VARCHAR2(255 BYTE)      NOT NULL,
  REMARK                VARCHAR2(255 BYTE)      NOT NULL,
  MAC                   VARCHAR2(255 BYTE)      NOT NULL,
  CREATE_DATE           DATE                    NOT NULL,
  UPDATE_DATE           DATE                    NOT NULL,
  DISABLED              SMALLINT		DEFAULT 0	NOT NULL,
  CREATED_BY            VARCHAR2(20 BYTE)       NOT NULL
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEPOSIT_REQUEST_LOG_PK ON DEPOSIT_REQUEST_LOG
(REQUEST_LOG_ID)
LOGGING
TABLESPACE USER_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEPOSIT_REQUEST_LOG ADD (
  CONSTRAINT DEPOSIT_REQUEST_LOG_PK
  PRIMARY KEY
  (REQUEST_LOG_ID)
  USING INDEX DEPOSIT_REQUEST_LOG_PK);

