OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnMgtByUsVST
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnMgtByUsVST.so
SOOBJS = TxnMgtByUsVST.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
