OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=par_extract_alp_data.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o par_extract_alp_data.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
