OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=par_txn_handler.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o pr_bo_funct.o pr_log_funct.o pr_par_funct.o par_adjustment_handler.o par_payout_reversal_handler.o par_payout_handler.o  par_settlement_handler.o par_deposit_handler.o par_deposit_reserved_handler.o par_txn_handler.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
