OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=par_match_esky_dsp.exec
BATCHOBJS=$(OBJHOME)/batchcommon.o par_match_esky_dsp.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=   -lObjPtr
all: $(BATCHEXE)
