OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MiOLDefDefaultBIT
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMiOLDefDefaultBIT.so
SOOBJS = MiOLDefDefaultBIT.o

include $(HOME)/config/Make.rules

LDLIBS +=

all : $(COMPSO)
