OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/CustomerGroupOffsetCount
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBCustomerGroupOffsetCount.so
SOOBJS =  CustomerGroupOffsetCount.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
