OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLDepositMatchPair
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLDepositMatchPair.so
SOOBJS =  OLDepositMatchPair.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
