ALTER TABLE OL_PAYOUT_GENERATED_FILE_HD
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_PAYOUT_GENERATED_FILE_HD CASCADE CONSTRAINTS;

CREATE TABLE OL_PAYOUT_GENERATED_FILE_HD
(
  OFH_FILE_ID           NUMBER(16),
  OFH_FILE_DATE         VARCHAR2(8 BYTE),
  OFH_FILE_PID          VARCHAR2(10 BYTE),
  OFH_FILE_BANK_CODE    VARCHAR2(10 BYTE),
  OFH_SEQ_NUM           INTEGER,
  OFH_FILENAME          VARCHAR2(50 BYTE),
  OFH_STATUS            INTEGER,
  OFH_TXN_COUNT         INTEGER,
  OFH_TOTAL_TXN_AMT     NUMBER(14,2),
  OFH_CCY_ID            VARCHAR2(3 BYTE),
  OFH_CREATE_USER       VARCHAR2(20 BYTE),
  OFH_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  OFH_UPDATE_USER       VARCHAR2(20 BYTE),
  OFH_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX OL_PAYOUT_GEN_FILE_HD_IDX01 ON OL_PAYOUT_GENERATED_FILE_HD
(OFH_FILE_ID, OFH_STATUS)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX OL_PAYOUT_GEN_FILE_HD_IDX02 ON OL_PAYOUT_GENERATED_FILE_HD
(OFH_STATUS)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX OL_PAYOUT_GEN_FILE_HD_IDX03 ON OL_PAYOUT_GENERATED_FILE_HD
(OFH_FILE_DATE, OFH_FILE_PID, OFH_FILE_BANK_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX OL_PAYOUT_GEN_FILE_HD_PK ON OL_PAYOUT_GENERATED_FILE_HD
(OFH_FILE_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_PAYOUT_GENERATED_FILE_HD ADD (
  CONSTRAINT OL_PAYOUT_GEN_FILE_HD_PK
  PRIMARY KEY
  (OFH_FILE_ID)
  USING INDEX OL_PAYOUT_GEN_FILE_HD_PK
  ENABLE VALIDATE);

