OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/PayoutPreGenerateDt
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBPayoutPreGenerateDt.so
SOOBJS =  PayoutPreGenerateDt.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
