ALTER TABLE OL_PAYOUT_RETURN_BATCH_ERROR
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_PAYOUT_RETURN_BATCH_ERROR CASCADE CONSTRAINTS;

CREATE TABLE OL_PAYOUT_RETURN_BATCH_ERROR
(
  PRE_ERROR_ID          INTEGER,
  PRE_BATCH_ID          INTEGER,
  PRE_ERROR_MSG         VARCHAR2(1024 BYTE),
  PRE_CREATE_USER       VARCHAR2(20 BYTE),
  PRE_UPDATE_USER       VARCHAR2(20 BYTE),
  PRE_CREATE_TIMESTAMP  DATE                     DEFAULT SYSDATE,
  PRE_UPDATE_TIMESTAMP  DATE                     DEFAULT SYSDATE
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_PAYOUT_RETURN_BATCH_ERR_PK ON OL_PAYOUT_RETURN_BATCH_ERROR
(PRE_ERROR_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_PAYOUT_RETURN_BATCH_ERROR ADD (
  CONSTRAINT OL_PAYOUT_RETURN_BATCH_ERR_PK
  PRIMARY KEY
  (PRE_ERROR_ID)
  USING INDEX OL_PAYOUT_RETURN_BATCH_ERR_PK
  ENABLE VALIDATE);

ALTER TABLE OL_PAYOUT_RETURN_BATCH_ERROR ADD (
  CONSTRAINT OL_PAYOUT_RET_BATCH_ERR_FK01 
  FOREIGN KEY (PRE_BATCH_ID) 
  REFERENCES OL_PAYOUT_RETURN_BATCH_HD (PRH_BATCH_ID)
  ENABLE VALIDATE);

