ALTER TABLE MMS_STL_BANK_DETAIL
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_STL_BANK_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE MMS_STL_BANK_DETAIL
(
  SBD_STL_BANK_ID                   VARCHAR2(15 BYTE),
  SBD_STL_BANK_NAME                 VARCHAR2(50 BYTE),
  SBD_STL_BANK_ACCT                 VARCHAR2(25 BYTE),
  SBD_DISABLED                      INTEGER              DEFAULT 0,
  SBD_CREATE_TIMESTAMP              DATE                 DEFAULT sysdate,
  SBD_UPDATE_TIMESTAMP              DATE                 DEFAULT sysdate,
  SBD_CREATE_USER                   VARCHAR2(20 BYTE),
  SBD_UPDATE_USER                   VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX MMS_STL_BANK_DETAIL_IDX01 ON MMS_STL_BANK_DETAIL
(SBD_DISABLED)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX MMS_STL_BANK_DETAIL_PK ON MMS_STL_BANK_DETAIL
(SBD_STL_BANK_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_STL_BANK_DETAIL ADD (
  CONSTRAINT MMS_STL_BANK_DETAIL_PK
  PRIMARY KEY
  (SBD_STL_BANK_ID)
  USING INDEX MMS_STL_BANK_DETAIL_PK
  ENABLE VALIDATE);
