ALTER TABLE CPHUSER.PSP_TRAFFIC
 DROP PRIMARY KEY CASCADE;

DROP TABLE CPHUSER.PSP_TRAFFIC CASCADE CONSTRAINTS;

CREATE TABLE CPHUSER.PSP_TRAFFIC
(
  PSP_ID            VARCHAR2(10 BYTE)           NOT NULL,
  TRAFFIC_AMOUNT    NUMBER(20,2)                DEFAULT 0                     NOT NULL,
  RESET_COUNT_IND   CHAR(1 BYTE)                DEFAULT 'N'                   NOT NULL,
  CREATE_TIMESTAMP  DATE,
  UPDATE_TIMESTAMP  DATE,
  CREATE_USER       VARCHAR2(20 BYTE),
  UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CPHUSER.PSP_TRAFFIC_PK ON CPHUSER.PSP_TRAFFIC
(PSP_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE CPHUSER.PSP_TRAFFIC ADD (
  CONSTRAINT PSP_TRAFFIC_PK
  PRIMARY KEY
  (PSP_ID)
  USING INDEX CPHUSER.PSP_TRAFFIC_PK);

