ALTER TABLE CPHUSER.SYS_SUPPORT_COUNTRY
 DROP PRIMARY KEY CASCADE;

DROP TABLE CPHUSER.SYS_SUPPORT_COUNTRY CASCADE CONSTRAINTS;

CREATE TABLE CPHUSER.SYS_SUPPORT_COUNTRY
(
  COUNTRY_CODE      VARCHAR2(2 BYTE)            NOT NULL,
  COUNTRY_NAME      VARCHAR2(15 BYTE),
  DISABLED          NUMBER(38)                  DEFAULT 0                     NOT NULL,
  CREATE_TIMESTAMP  DATE,
  UPDATE_TIMESTAMP  DATE,
  CREATE_USER       VARCHAR2(20 BYTE),
  UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CPHUSER.SYS_COUNTRY_PK ON CPHUSER.SYS_SUPPORT_COUNTRY
(COUNTRY_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE CPHUSER.SYS_SUPPORT_COUNTRY ADD (
  CONSTRAINT SYS_COUNTRY_PK
  PRIMARY KEY
  (COUNTRY_CODE)
  USING INDEX
    TABLESPACE USER_IDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

