


CREATE TABLE OL_STMT_CONVERT_ERROR
(
    CE_FILE_ID            NUMBER (16),
    CE_MESSAGE_CODE       NUMBER (8),
    CE_RESULT             VARCHAR2 (255 BYTE),
    CE_FORMAT_ID          VARCHAR2 (20 BYTE),
    CE_CREATE_USER        VARCHAR2 (20 BYTE),
    CE_CREATE_TIMESTAMP   DATE DEFAULT SYSDATE
)
TABLESPACE USER_DATA
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;

CREATE UNIQUE INDEX OL_STMT_CONVERT_ERROR_PK
    ON OL_STMT_CONVERT_ERROR (CE_FILE_ID)
    LOGGING
    TABLESPACE USER_IDX
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE (INITIAL 64 K
             NEXT 1 M
             MINEXTENTS 1
             MAXEXTENTS UNLIMITED
             PCTINCREASE 0
             BUFFER_POOL DEFAULT);

ALTER TABLE OL_STMT_CONVERT_ERROR ADD (
  CONSTRAINT OL_STMT_CONVERT_ERROR_PK
  PRIMARY KEY
  (CE_FILE_ID)
  USING INDEX OL_STMT_CONVERT_ERROR_PK
  ENABLE VALIDATE);

