ALTER TABLE CRR_JNL_HEADER
 DROP PRIMARY KEY CASCADE;

DROP TABLE CRR_JNL_HEADER CASCADE CONSTRAINTS;

CREATE TABLE CRR_JNL_HEADER
(
  JNL_ID             VARCHAR2(16 BYTE)          NOT NULL,
  JNL_TYPE_ID        INTEGER                    NOT NULL,
  DESCRIPTION        VARCHAR2(100 BYTE),
  TXN_DATE           VARCHAR2(8 BYTE),
  BANK_UPDATE_DATE   VARCHAR2(8 BYTE),
  ACC_YEAR           VARCHAR2(4 BYTE),
  ACC_MONTH          VARCHAR2(2 BYTE),
  REF_NO             VARCHAR2(100 BYTE),
  PRODUCT_CODE       CHAR(3 BYTE)               NOT NULL,
  COUNTRY_CODE       CHAR(2 BYTE)               NOT NULL,
  REMARKS            VARCHAR2(300 BYTE),
  STATUS             CHAR(1 BYTE)               NOT NULL,
  DISABLED           NUMBER(1)                  DEFAULT 0,
  CREATE_TIMESTAMP   DATE                       DEFAULT SYSDATE,
  CREATE_USER        VARCHAR2(20 BYTE),
  UPDATE_TIMESTAMP   DATE                       DEFAULT SYSDATE,
  UPDATE_USER        VARCHAR2(20 BYTE),
  APPROVE_TIMESTAMP  DATE,
  APPROVE_USER       VARCHAR2(20 BYTE),
  BOOK_TIMESTAMP     DATE,
  BOOK_USER          VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX CRR_JNL_HEADER_IDX01 ON CRR_JNL_HEADER
(JNL_ID, JNL_TYPE_ID, TXN_DATE, PRODUCT_CODE, COUNTRY_CODE, 
STATUS, DISABLED)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX CRR_JNL_HEADER_IDX02 ON CRR_JNL_HEADER
("TXN_DATE" DESC, DISABLED)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX CRR_JNL_HEADER_PK ON CRR_JNL_HEADER
(JNL_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE CRR_JNL_HEADER ADD (
  CONSTRAINT CRR_JNL_HEADER_CK01
  CHECK (
   	 STATUS IN ('P','A','B')
   )
  ENABLE VALIDATE,
  CONSTRAINT CRR_JNL_HEADER_PK
  PRIMARY KEY
  (JNL_ID)
  USING INDEX CRR_JNL_HEADER_IDX01
  ENABLE VALIDATE);

ALTER TABLE CRR_JNL_HEADER ADD (
  CONSTRAINT CRR_JNL_HEADER_FK01 
  FOREIGN KEY (JNL_TYPE_ID) 
  REFERENCES CRR_JNL_TYPE (JNL_TYPE_ID)
  ENABLE VALIDATE,
  CONSTRAINT CRR_JNL_HEADER_FK02 
  FOREIGN KEY (PRODUCT_CODE) 
  REFERENCES DEF_PRODUCT (DP_ID)
  ENABLE VALIDATE,
  CONSTRAINT CRR_JNL_HEADER_FK03 
  FOREIGN KEY (COUNTRY_CODE) 
  REFERENCES COUNTRY (COUNTRY_CODE)
  ENABLE VALIDATE);


DROP SEQUENCE CRR_JNL_HEADER_SEQ;

CREATE SEQUENCE CRR_JNL_HEADER_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE;
