OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/ClientSettBank
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBClientSettBank.so
SOOBJS =  ClientSettBank.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
