OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmsBankDetail
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmsBankDetail.so
SOOBJS =  MmsBankDetail.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
