ALTER TABLE MERCHANT_BUCKET
 DROP PRIMARY KEY CASCADE;

DROP TABLE MERCHANT_BUCKET CASCADE CONSTRAINTS;

CREATE TABLE MERCHANT_BUCKET
(
  MB_POSTING_DATE      VARCHAR2(8 BYTE),
  MB_MERCHANT_ID       VARCHAR2(15 BYTE),
  MB_COUNTRY_ID        CHAR(2 BYTE),
  MB_CURRENCY_ID       VARCHAR2(3 BYTE),
  MB_SERVICE_CODE      CHAR(3 BYTE),
  MB_PSP_ID            VARCHAR2(10 BYTE),
  MB_BUCKET_TYPE       VARCHAR2(2 BYTE),
  MB_BAL               NUMBER(14,2),
  MB_RELEASED_DATE     VARCHAR2(8 BYTE),
  MB_RELEASED_AMT      NUMBER(14,2),
  MB_RELEASED_TO_AF    INTEGER,
  MB_TRANSFER_OUT_BAL	NUMBER(14,2) DEFAULT 0,
  MB_CREATE_USER       VARCHAR2(20 BYTE),
  MB_UPDATE_USER       VARCHAR2(20 BYTE),
  MB_CREATE_TIMESTAMP  DATE,
  MB_UPDATE_TIMESTAMP  DATE
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN MERCHANT_BUCKET.MB_BUCKET_TYPE IS 'FT- FLOAT, RS- RESERVED,SF - SETTLEMET FLOAT';



CREATE INDEX MERCHANT_BUCKET_IDX01 ON MERCHANT_BUCKET
(MB_SERVICE_CODE, MB_BUCKET_TYPE, MB_POSTING_DATE, MB_RELEASED_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX MERCHANT_BUCKET_PK ON MERCHANT_BUCKET
(MB_POSTING_DATE, MB_MERCHANT_ID, MB_COUNTRY_ID, MB_CURRENCY_ID, MB_SERVICE_CODE, 
MB_PSP_ID, MB_BUCKET_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MERCHANT_BUCKET ADD (
  CONSTRAINT MERCHANT_BUCKET_PK
  PRIMARY KEY
  (MB_POSTING_DATE, MB_MERCHANT_ID, MB_COUNTRY_ID, MB_CURRENCY_ID, MB_SERVICE_CODE, MB_PSP_ID, MB_BUCKET_TYPE)
  USING INDEX MERCHANT_BUCKET_PK
  ENABLE VALIDATE);

ALTER TABLE MERCHANT_BUCKET ADD (
  CONSTRAINT MERCHANT_BUCKET_FK01 
  FOREIGN KEY (MB_BUCKET_TYPE) 
  REFERENCES DEF_BUCKET_TYPE (B_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT MERCHANT_BUCKET_FK02 
  FOREIGN KEY (MB_MERCHANT_ID) 
  REFERENCES MERCH_DETAIL (MERCHANT_ID)
  ENABLE VALIDATE,
  CONSTRAINT MERCHANT_BUCKET_FK03 
  FOREIGN KEY (MB_COUNTRY_ID) 
  REFERENCES COUNTRY (COUNTRY_CODE)
  ENABLE VALIDATE,
  CONSTRAINT MERCHANT_BUCKET_FK04 
  FOREIGN KEY (MB_CURRENCY_ID) 
  REFERENCES DEF_CURRENCY (DC_CCY_ID)
  ENABLE VALIDATE,
  CONSTRAINT MERCHANT_BUCKET_FK05 
  FOREIGN KEY (MB_SERVICE_CODE) 
  REFERENCES DEF_SERVICE_CODE (SC_CODE)
  ENABLE VALIDATE);

