OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/CctTxn
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBCctTxn.so
SOOBJS =  CctTxn.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
