ALTER TABLE DEF_TXN_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_TXN_TYPE CASCADE CONSTRAINTS;

CREATE TABLE DEF_TXN_TYPE
(
  T_TYPE              CHAR(1 BYTE),
  T_DESC              VARCHAR2(50 BYTE),
  T_CREATE_USER       VARCHAR2(20 BYTE),
  T_CREATE_TIMESTAMP  DATE                      DEFAULT sysdate,
  T_UPDATE_USER       VARCHAR2(20 BYTE),
  T_UPDATE_TIMESTAMP  DATE                      DEFAULT sysdate
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEF_TXN_TYPE_PK ON DEF_TXN_TYPE
(T_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_TXN_TYPE ADD (
  CONSTRAINT DEF_TXN_TYPE_PK
  PRIMARY KEY
  (T_TYPE)
  USING INDEX DEF_TXN_TYPE_PK);
