OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLPayoutTxnAckRetry
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLPayoutTxnAckRetry.so
SOOBJS =  OLPayoutTxnAckRetry.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
