ALTER TABLE TXN_ELEMENTS
 DROP PRIMARY KEY CASCADE;

DROP TABLE TXN_ELEMENTS CASCADE CONSTRAINTS;

CREATE TABLE TXN_ELEMENTS
(
  TE_TXN_ID            VARCHAR2(16 BYTE),
  TE_TXN_ELEMENT_TYPE  CHAR(4 BYTE),
  TE_EXEC_SEQ          INTEGER,
  TE_AMOUNT            NUMBER(14,2),
  TE_CCY               CHAR(3 BYTE)             NOT NULL,
  TE_AMT_TYPE          CHAR(2 BYTE),
  TE_PARTY_TYPE        CHAR(1 BYTE)             NOT NULL,
  TE_RATE              NUMBER(12,5)             DEFAULT 1,
  TE_CREATE_TIMESTAMP  DATE,
  TE_CREATE_USER       VARCHAR2(20 BYTE),
  TE_UPDATE_TIMESTAMP  DATE,
  TE_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX TXN_ELEMENTS_IDX01 ON TXN_ELEMENTS
(TE_TXN_ELEMENT_TYPE, TE_PARTY_TYPE, TE_CCY, TE_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX TXN_ELEMENTS_IDX02 ON TXN_ELEMENTS
(TE_TXN_ELEMENT_TYPE, TE_PARTY_TYPE, TE_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX TXN_ELEMENTS_IDX03 ON TXN_ELEMENTS
(TE_TXN_ELEMENT_TYPE, TE_PARTY_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

CREATE INDEX TXN_ELEMENTS_IDX04 ON TXN_ELEMENTS
(TE_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX TXN_ELEMENTS_PK ON TXN_ELEMENTS
(TE_TXN_ID, TE_TXN_ELEMENT_TYPE, TE_EXEC_SEQ, TE_PARTY_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE TXN_ELEMENTS ADD (
  CONSTRAINT TXN_ELEMENTS_PK
  PRIMARY KEY
  (TE_TXN_ID, TE_TXN_ELEMENT_TYPE, TE_EXEC_SEQ, TE_PARTY_TYPE)
  USING INDEX TXN_ELEMENTS_PK
  ENABLE VALIDATE);

ALTER TABLE TXN_ELEMENTS ADD (
  CONSTRAINT TXN_ELEMENTS_FK01 
  FOREIGN KEY (TE_TXN_ELEMENT_TYPE) 
  REFERENCES DEF_ELEMENT_TYPE (DT_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT TXN_ELEMENTS_FK03 
  FOREIGN KEY (TE_PARTY_TYPE) 
  REFERENCES DEF_PARTY_TYPE (DP_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT TXN_ELEMENTS_FK04 
  FOREIGN KEY (TE_TXN_ID) 
  REFERENCES TXN_HEADER (TH_TXN_ID)
  ENABLE VALIDATE);

