OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLResourceLock
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLResourceLock.so
SOOBJS =  OLResourceLock.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
