ALTER TABLE OL_DEF_BANK_ACCT_STATUS_GRP
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_DEF_BANK_ACCT_STATUS_GRP CASCADE CONSTRAINTS;

CREATE TABLE OL_DEF_BANK_ACCT_STATUS_GRP
(
  SG_TYPE              VARCHAR2(20 BYTE),
  SG_DESC              VARCHAR2(50 BYTE),
  SG_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  SG_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  SG_CREATE_USER       VARCHAR2(20 BYTE),
  SG_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_DEF_BANK_ACCT_STATUS_GRP_PK ON OL_DEF_BANK_ACCT_STATUS_GRP
(SG_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_DEF_BANK_ACCT_STATUS_GRP ADD (
  CONSTRAINT OL_DEF_BANK_ACCT_STATUS_GRP_PK
  PRIMARY KEY
  (SG_TYPE)
  USING INDEX OL_DEF_BANK_ACCT_STATUS_GRP_PK
  ENABLE VALIDATE);

