ALTER TABLE CPHUSER.PAYOUT_RECORD
 DROP PRIMARY KEY CASCADE;

DROP TABLE CPHUSER.PAYOUT_RECORD CASCADE CONSTRAINTS;

CREATE TABLE CPHUSER.PAYOUT_RECORD
(
  BATCH_ID		VARCHAR2(16 BYTE)           NOT NULL,
  SEQ_NUM		VARCHAR2(6 BYTE)            NOT NULL,
  MERCHANT_ID		VARCHAR2(16 BYTE)           NOT NULL,
  MERCHANT_REF		VARCHAR2(25 BYTE)           NOT NULL,
  COUNTRY		VARCHAR2(2 BYTE)            NOT NULL,
  IDENTITY_ID		VARCHAR2(25 BYTE),
  ACCOUNT_NUM		VARCHAR2(25 BYTE)           NOT NULL,
  ACCOUNT_NAME		VARCHAR2(25 BYTE)           NOT NULL,
  BANK_NAME		VARCHAR2(35 BYTE)           NOT NULL,
  BANK_CODE		VARCHAR2(25 BYTE)           NOT NULL,
  BRANCH		VARCHAR2(100 BYTE)           NOT NULL,
  PHONE_NUM		VARCHAR2(25 BYTE),
  PROVINCE		VARCHAR2(50 BYTE),
  CITY			VARCHAR2(50 BYTE),
  AMOUNT		VARCHAR2(12 BYTE)           NOT NULL,
  PAYOUT_CURRENCY	VARCHAR2(3 BYTE)            NOT NULL,
  DEST_CURRENCY		VARCHAR2(3 BYTE)            NOT NULL,
  CHECKSUM		VARCHAR2(16 BYTE)           NOT NULL
  STATUS           	CHAR(1 BYTE)                DEFAULT 'I'                   NOT NULL
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CPHUSER.PAYOUT_RECORD_PK ON CPHUSER.PAYOUT_RECORD
(BATCH_ID, SEQ_NUM, MERCHANT_REF)
LOGGING
TABLESPACE USER_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE CPHUSER.PAYOUT_RECORD ADD (
  CONSTRAINT PAYOUT_RECORD_PK
  PRIMARY KEY
  (BATCH_ID, SEQ_NUM, MERCHANT_REF)
  USING INDEX CPHUSER.PAYOUT_RECORD_PK);

