OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOPayout
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOPayout.so
SOOBJS = BOPayout.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
