ALTER TABLE MMS_PH_TRANSACTION
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_PH_TRANSACTION CASCADE CONSTRAINTS;

CREATE TABLE MMS_PH_TRANSACTION
(
  MT_NODE_ID                VARCHAR2(5 BYTE),
  MT_PH_TXN_ID              VARCHAR2(16 BYTE),
  MT_CLIENT_ID              VARCHAR2(10 BYTE),
  MT_PSP_ID                 VARCHAR2(10 BYTE),
  MT_BAID                   VARCHAR2(20 BYTE),
  MT_NODE_TXN_CODE          CHAR(3 BYTE),
  MT_TRANSMISSION_DATETIME  VARCHAR2(14 BYTE),
  MT_TM_DATE                VARCHAR2(8 BYTE),
  MT_TM_TIME                VARCHAR2(6 BYTE),
  MT_LOCAL_TM_DATE          VARCHAR2(8 BYTE),
  MT_LOCAL_TM_TIME          VARCHAR2(6 BYTE),
  MT_TXN_AMOUNT             NUMBER(12,2),
  MT_TXN_CCY                CHAR(3 BYTE),
  MT_TXN_COUNTRY            CHAR(2 BYTE),
  MT_CREATE_USER            VARCHAR2(20 BYTE),
  MT_CREATE_DATETIME        DATE,
  MT_UPDATE_USER            VARCHAR2(20 BYTE),
  MT_UPDATE_DATETIME        DATE
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MMS_PH_TRANSACTION_PK ON MMS_PH_TRANSACTION
(MT_NODE_ID, MT_PH_TXN_ID)
LOGGING
TABLESPACE USER_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_PH_TRANSACTION ADD (
  CONSTRAINT MMS_PH_TRANSACTION_PK
  PRIMARY KEY
  (MT_NODE_ID, MT_PH_TXN_ID)
  USING INDEX MMS_PH_TRANSACTION_PK
  ENABLE VALIDATE);

