ALTER TABLE VOUCHER_PAYMENT_PARAMETER
 DROP PRIMARY KEY CASCADE;

DROP TABLE VOUCHER_PAYMENT_PARAMETER CASCADE CONSTRAINTS;

CREATE TABLE VOUCHER_PAYMENT_PARAMETER
(
  VP_CODE              VARCHAR2(50 BYTE)        NOT NULL,
  VP_DESC              VARCHAR2(240 BYTE)       NOT NULL,
  VP_VAL               VARCHAR2(50 BYTE)        NOT NULL,
  VP_DELETABLE         INTEGER                  DEFAULT 0,
  VP_CREATE_USER       VARCHAR2(20 BYTE),
  VP_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  VP_UPDATE_USER       VARCHAR2(20 BYTE),
  VP_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN VOUCHER_PAYMENT_PARAMETER.VP_DELETABLE IS '1-yes, 0-no';



CREATE UNIQUE INDEX VOUCHER_PAYMENT_PARAMETER_PK ON VOUCHER_PAYMENT_PARAMETER
(VP_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE VOUCHER_PAYMENT_PARAMETER ADD (
  CONSTRAINT VOUCHER_PAYMENT_PARAMETER_PK
  PRIMARY KEY
  (VP_CODE)
  USING INDEX VOUCHER_PAYMENT_PARAMETER_PK
  ENABLE VALIDATE);

