OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MobBankMap
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMobBankMap.so
SOOBJS =  MobBankMap.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
