OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/DefCounterType
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBDefCounterType.so
SOOBJS =  DefCounterType.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
