CREATE TABLE OL_BAID_INTER_LOG_GEN
(
  OLGD_BATCH_ID          NUMBER,
  OLGD_STMT_TXN_ID       VARCHAR2(16 BYTE),
  OLGD_STATUS            CHAR(1 BYTE),
  OLGD_GEN_TXN_ID        VARCHAR2(16 BYTE),
  OLGD_RET_CODE          NUMBER,
  OLGD_CREATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  OLGD_UPDATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  OLGD_CREATE_USER       VARCHAR2(20 BYTE),
  OLGD_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE INDEX OL_BAID_INTER_LOG_GEN_IDX01 ON OL_BAID_INTER_LOG_GEN
(OLGD_STMT_TXN_ID, OLGD_CREATE_TIMESTAMP)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX OL_BAID_INTER_LOG_GEN_PK ON OL_BAID_INTER_LOG_GEN
(OLGD_BATCH_ID, OLGD_STMT_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE OL_BAID_INTER_LOG_GEN ADD (
  CONSTRAINT OL_BAID_INTER_LOG_GEN_PK
  PRIMARY KEY
  (OLGD_BATCH_ID, OLGD_STMT_TXN_ID)
  USING INDEX OL_BAID_INTER_LOG_GEN_PK
  ENABLE VALIDATE,
  CONSTRAINT OL_BAID_INTER_LOG_GEN_UK01
  UNIQUE (OLGD_STMT_TXN_ID)
  USING INDEX OL_BAID_INTER_LOG_GEN_IDX01
  ENABLE VALIDATE);

ALTER TABLE OL_BAID_INTER_LOG_GEN ADD (
  CONSTRAINT OL_BAID_INTER_LOG_GEN_FK01 
  FOREIGN KEY (OLGD_STATUS) 
  REFERENCES OL_DEF_INTER_LOG_GEN_STATUS (ODGS_STATUS)
  ENABLE VALIDATE);

