OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/TxnSeq
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBTxnSeq.so
SOOBJS =  TxnSeq.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
