OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OffsetTxnType
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOffsetTxnType.so
SOOBJS =  OffsetTxnType.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
