OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLTcBalTrfMap
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLTcBalTrfMap.so
SOOBJS =  OLTcBalTrfMap.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
