
CREATE UNIQUE INDEX CRR_RULE_POSTING_PK ON CRR_RULE_POSTING
(CR_COUNTRY_ID, CR_PRODUCT_CODE, CR_TXN_CODE, CR_PARTY_TYPE, CR_PARTY_ID, 
CR_JNL_TYPE_ID, CR_JNL_ENTRY_TYPE_ID, CR_CURRENCY_ID, CR_CREDIT_GL_ID, CR_DEBIT_GL_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;



ALTER TABLE CRR_RULE_POSTING ADD (
  CONSTRAINT CRR_RULE_POSTING_PK
  PRIMARY KEY
  (CR_COUNTRY_ID, CR_PRODUCT_CODE, CR_TXN_CODE, CR_PARTY_TYPE, CR_PARTY_ID, CR_JNL_TYPE_ID, CR_JNL_ENTRY_TYPE_ID, CR_CURRENCY_ID, CR_CREDIT_GL_ID, CR_DEBIT_GL_ID)
  USING INDEX CRR_RULE_POSTING_PK
  ENABLE VALIDATE);
