ALTER TABLE CRR_RULE_POSTING
 DROP PRIMARY KEY CASCADE;

DROP TABLE CRR_RULE_POSTING CASCADE CONSTRAINTS;

CREATE TABLE CRR_RULE_POSTING
(
  CR_COUNTRY_ID         CHAR(2 BYTE),
  CR_PRODUCT_CODE       CHAR(3 BYTE),
  CR_TXN_CODE           CHAR(3 BYTE),
  CR_PARTY_TYPE         CHAR(1 BYTE),
  CR_PARTY_ID           VARCHAR2(15 BYTE),
  CR_JNL_TYPE_ID        INTEGER,
  CR_JNL_ENTRY_TYPE_ID  VARCHAR2(20 BYTE),
  CR_CREDIT_GL_ID       INTEGER                 DEFAULT 0,
  CR_DEBIT_GL_ID        INTEGER                 DEFAULT 0,
  CR_DESCRIPTION        VARCHAR2(50 BYTE),
  CR_DISABLED           INTEGER                 DEFAULT 0,
  CR_CREATE_TIMESTAMP   DATE                    DEFAULT SYSDATE,
  CR_UPDATE_TIMESTAMP   DATE,
  CR_CREATE_USER        VARCHAR2(20 BYTE),
  CR_UPDATE_USER        VARCHAR2(20 BYTE),
  CR_UNIQUE_TXN         INTEGER                 DEFAULT 0,
  CR_CURRENCY_ID        VARCHAR2(3 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX CRR_RULE_POSTING_IDX01 ON CRR_RULE_POSTING
(CR_COUNTRY_ID, CR_PRODUCT_CODE, CR_TXN_CODE, CR_PARTY_TYPE, CR_PARTY_ID, 
CR_JNL_ENTRY_TYPE_ID, CR_CURRENCY_ID, CR_DISABLED)
LOGGING
TABLESPACE USER_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX CRR_RULE_POSTING_IDX02 ON CRR_RULE_POSTING
(CR_COUNTRY_ID, CR_PRODUCT_CODE, CR_TXN_CODE, CR_PARTY_TYPE, CR_PARTY_ID, 
CR_DISABLED)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX CRR_RULE_POSTING_IDX03 ON CRR_RULE_POSTING
(CR_JNL_ENTRY_TYPE_ID, CR_TXN_CODE, CR_PARTY_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX CRR_RULE_POSTING_PK ON CRR_RULE_POSTING
(CR_COUNTRY_ID, CR_PRODUCT_CODE, CR_TXN_CODE, CR_PARTY_TYPE, CR_PARTY_ID, 
CR_JNL_TYPE_ID, CR_JNL_ENTRY_TYPE_ID, CR_CURRENCY_ID, CR_CREDIT_GL_ID, CR_DEBIT_GL_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE CRR_RULE_POSTING ADD (
  CONSTRAINT CRR_RULE_POSTING_PK
  PRIMARY KEY
  (CR_COUNTRY_ID, CR_PRODUCT_CODE, CR_TXN_CODE, CR_PARTY_TYPE, CR_PARTY_ID, CR_JNL_TYPE_ID, CR_JNL_ENTRY_TYPE_ID, CR_CURRENCY_ID, CR_CREDIT_GL_ID, CR_DEBIT_GL_ID)
  USING INDEX CRR_RULE_POSTING_PK
  ENABLE VALIDATE);

ALTER TABLE CRR_RULE_POSTING ADD (
  CONSTRAINT CRR_RULE_POSTING_FK01 
  FOREIGN KEY (CR_COUNTRY_ID) 
  REFERENCES COUNTRY (COUNTRY_CODE)
  ENABLE VALIDATE,
  CONSTRAINT CRR_RULE_POSTING_FK03 
  FOREIGN KEY (CR_PRODUCT_CODE) 
  REFERENCES DEF_PRODUCT (DP_ID)
  ENABLE VALIDATE,
  CONSTRAINT CRR_RULE_POSTING_FK04 
  FOREIGN KEY (CR_PARTY_TYPE) 
  REFERENCES DEF_PARTY_TYPE (DP_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT CRR_RULE_POSTING_FK05 
  FOREIGN KEY (CR_JNL_TYPE_ID, CR_JNL_ENTRY_TYPE_ID) 
  REFERENCES CRR_JNL_ENTRY_TYPE (JNL_TYPE_ID,ENTRY_TYPE_ID)
  ENABLE VALIDATE,
  CONSTRAINT CRR_RULE_POSTING_FK06 
  FOREIGN KEY (CR_JNL_TYPE_ID) 
  REFERENCES CRR_JNL_TYPE (JNL_TYPE_ID)
  ENABLE VALIDATE);

