OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmsMBDetail
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmsMBDetail.so
SOOBJS =  MmsMBDetail.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
