OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOBank
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOBank.so
SOOBJS = BOBank.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
