OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/CrrJnlDetail
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBCrrJnlDetail.so
SOOBJS =  CrrJnlDetail.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
