ALTER TABLE DEPOSIT_MISMATCH
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEPOSIT_MISMATCH CASCADE CONSTRAINTS;

CREATE TABLE DEPOSIT_MISMATCH
(
  DM_TXN_ID            VARCHAR2(16 BYTE),
  DM_PARTY_TYPE        CHAR(1 BYTE),
  DM_PARTY_ID          VARCHAR2(15 BYTE),
  DM_TXN_DATE          VARCHAR2(8 BYTE),
  DM_ABSENT            VARCHAR2(8 BYTE),
  DM_MATCH_IND         INTEGER                  DEFAULT 0,
  DM_MATCH_DATE        VARCHAR2(8 BYTE),
  DM_CREATE_USER       VARCHAR2(20 BYTE),
  DM_UPDATE_USER       VARCHAR2(20 BYTE),
  DM_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  DM_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  DM_PSP_TID           VARCHAR2(50 BYTE),
  DM_MERCHANT_REF      VARCHAR2(50 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX DEPOSIT_MISMATCH_IDX01 ON DEPOSIT_MISMATCH
(DM_PARTY_TYPE, DM_MERCHANT_REF)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX DEPOSIT_MISMATCH_IDX02 ON DEPOSIT_MISMATCH
(DM_PARTY_ID, DM_TXN_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX DEPOSIT_MISMATCH_PK ON DEPOSIT_MISMATCH
(DM_TXN_ID, DM_PARTY_TYPE)
LOGGING
TABLESPACE USER_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEPOSIT_MISMATCH ADD (
  CONSTRAINT DEPOSIT_MISMATCH_PK
  PRIMARY KEY
  (DM_TXN_ID, DM_PARTY_TYPE)
  USING INDEX DEPOSIT_MISMATCH_PK
  ENABLE VALIDATE);

