ALTER TABLE MERCH_LIM_DAILY_CAP
 DROP PRIMARY KEY CASCADE;

DROP TABLE MERCH_LIM_DAILY_CAP CASCADE CONSTRAINTS;

CREATE TABLE MERCH_LIM_DAILY_CAP
(
  MLDC_MERCHANT_ID       VARCHAR2(15 BYTE)      NOT NULL,
  MLDC_SERVICE_CODE      CHAR(3 BYTE)           NOT NULL,
  MLDC_COUNTRY      	 CHAR(2 BYTE)           NOT NULL,
  MLDC_DAILY_CAP         NUMBER(14,2)           DEFAULT 0,
  MLDC_DISABLED          INTEGER           	DEFAULT 0,
  MLDC_CREATE_USER       VARCHAR2(20 BYTE),
  MLDC_CREATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  MLDC_UPDATE_USER       VARCHAR2(20 BYTE),
  MLDC_UPDATE_TIMESTAMP  DATE                   DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MERCH_LIM_DAILY_CAP_PK ON MERCH_LIM_DAILY_CAP
(MLDC_MERCHANT_ID, MLDC_SERVICE_CODE, MLDC_COUNTRY)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MERCH_LIM_DAILY_CAP ADD (
  CONSTRAINT MERCH_LIM_DAILY_CAP_PK
  PRIMARY KEY
  (MLDC_MERCHANT_ID, MLDC_SERVICE_CODE, MLDC_COUNTRY)
  USING INDEX MERCH_LIM_DAILY_CAP_PK
  ENABLE VALIDATE);

ALTER TABLE MERCH_LIM_DAILY_CAP ADD (
  CONSTRAINT MERCH_LIM_DAILY_CAP_FK01 
  FOREIGN KEY (MLDC_SERVICE_CODE) 
  REFERENCES DEF_SERVICE_CODE (SC_CODE)
  ENABLE VALIDATE);

ALTER TABLE MERCH_LIM_DAILY_CAP ADD (
  CONSTRAINT MERCH_LIM_DAILY_CAP_FK02
  FOREIGN KEY (MLDC_COUNTRY)
  REFERENCES COUNTRY (COUNTRY_CODE)
  ENABLE VALIDATE);
