ALTER TABLE BANK_FEE_MAPPING
 DROP PRIMARY KEY CASCADE;

DROP TABLE BANK_FEE_MAPPING CASCADE CONSTRAINTS;

CREATE TABLE BANK_FEE_MAPPING
(
  BF_INT_BANK_CODE     VARCHAR2(10 BYTE),
  BF_FEE_TYPE          CHAR(2 BYTE),
  BF_DISABLED          INTEGER                  DEFAULT 0,
  BF_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  BF_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  BF_CREATE_USER       VARCHAR2(20 BYTE),
  BF_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX BANK_FEE_MAPPING_PK ON BANK_FEE_MAPPING
(BF_INT_BANK_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE BANK_FEE_MAPPING ADD (
  CONSTRAINT BANK_FEE_MAPPING_PK
  PRIMARY KEY
  (BF_INT_BANK_CODE)
  USING INDEX BANK_FEE_MAPPING_PK
  ENABLE VALIDATE);

