ALTER TABLE OL_MERCH_CONFIG
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_MERCH_CONFIG CASCADE CONSTRAINTS;

CREATE TABLE OL_MERCH_CONFIG
(
  OMC_MERCHANT_ID                 VARCHAR2(15 BYTE),
  OMC_CURRENCY_ID                 VARCHAR2(3 BYTE),
  OMC_COUNTRY_ID                  CHAR(2 BYTE),
  OMC_SERVICE_CODE                CHAR(3 BYTE),
  OMC_MATCH_FIFO                  INTEGER       DEFAULT 1,
  OMC_MATCH_FIFO_AMT_LIMIT        NUMBER(14,2)  DEFAULT 0,
  OMC_MIN_SETTLE_AMT              NUMBER(14,2)  DEFAULT 0,
  OMC_MIN_SETTLE_AMT_APPLY_ADMIN  INTEGER       DEFAULT 1,
  OMC_MAX_AUTO_CB_AMT             NUMBER(14,2)  DEFAULT 0,
  OMC_PREFERRED_SETTLE_CCY        VARCHAR2(3 BYTE),
  OMC_DISABLED                    CHAR(1 BYTE)  DEFAULT 0,
  OMC_CREATE_USER                 VARCHAR2(20 BYTE),
  OMC_CREATE_TIMESTAMP            DATE          DEFAULT SYSDATE,
  OMC_UPDATE_USER                 VARCHAR2(20 BYTE),
  OMC_UPDATE_TIMESTAMP            DATE          DEFAULT SYSDATE,
  OMC_CLIENT_SETT_BANK_ID	  INTEGER
)
TABLESPACE USER_IDX
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_MERCH_CONFIG_PK ON OL_MERCH_CONFIG
(OMC_MERCHANT_ID, OMC_CURRENCY_ID, OMC_COUNTRY_ID, OMC_SERVICE_CODE)
LOGGING
TABLESPACE USER_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_MERCH_CONFIG ADD (
  CONSTRAINT OL_MERCH_CONFIG_PK
  PRIMARY KEY
  (OMC_MERCHANT_ID, OMC_CURRENCY_ID, OMC_COUNTRY_ID, OMC_SERVICE_CODE)
  USING INDEX OL_MERCH_CONFIG_PK
  ENABLE VALIDATE);

ALTER TABLE OL_MERCH_CONFIG ADD (
  CONSTRAINT OL_MERCH_AUTO_MATCH_CFG_FK01 
  FOREIGN KEY (OMC_MERCHANT_ID) 
  REFERENCES OL_MERCH_DETAIL (MD_MERCHANT_ID)
  ENABLE VALIDATE);

