OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/CrrExtPspDetail
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBCrrExtPspDetail.so
SOOBJS =  CrrExtPspDetail.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
