ALTER TABLE PAYOUT_SPC_SPLIT_ACCT
 DROP PRIMARY KEY CASCADE;

DROP TABLE PAYOUT_SPC_SPLIT_ACCT CASCADE CONSTRAINTS;

CREATE TABLE PAYOUT_SPC_SPLIT_ACCT
(
  PSS_BANK_ACCT_NUM     VARCHAR2(25 BYTE),
  PSS_DISABLED          CHAR(1 BYTE)             DEFAULT 0,
  PSS_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  PSS_CREATE_USER       VARCHAR2(20 BYTE),
  PSS_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  PSS_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PAYOUT_SPC_SPLIT_ACCT_PK ON PAYOUT_SPC_SPLIT_ACCT
(PSS_BANK_ACCT_NUM)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PAYOUT_SPC_SPLIT_ACCT ADD (
  CONSTRAINT PAYOUT_SPC_SPLIT_ACCT_PK
  PRIMARY KEY
  (PSS_BANK_ACCT_NUM)
  USING INDEX PAYOUT_SPC_SPLIT_ACCT_PK
  ENABLE VALIDATE);

