OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmsMBBalance
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmsMBBalance.so
SOOBJS =  MmsMBBalance.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
