OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLMerchConfig
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLMerchConfig.so
SOOBJS =  OLMerchConfig.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
