ALTER TABLE RULE_OPERATOR_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE RULE_OPERATOR_TYPE CASCADE CONSTRAINTS;

CREATE TABLE RULE_OPERATOR_TYPE
(
  ROT_TYPE              CHAR(2 BYTE)             NOT NULL,
  ROT_NAME              VARCHAR2(50 BYTE)        NOT NULL,
  ROT_DISABLED          INTEGER                  DEFAULT 0,
  ROT_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  ROT_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  ROT_CREATE_USER       VARCHAR2(20 BYTE),
  ROT_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX RULE_OPERATOR_TYPE_PK ON RULE_OPERATOR_TYPE
(ROT_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE RULE_OPERATOR_TYPE ADD (
  CONSTRAINT RULE_OPERATOR_TYPE_PK
  PRIMARY KEY
  (ROT_TYPE)
  USING INDEX RULE_OPERATOR_TYPE_PK);

