DROP TABLE TXN_ACK_LOG CASCADE CONSTRAINTS;

CREATE TABLE TXN_ACK_LOG
(
  AL_TXN_ID            VARCHAR2(16 BYTE)        NOT NULL,
  AL_ORG_TXN_ID        VARCHAR2(16 BYTE)        NOT NULL,
  AL_STATUS            CHAR(1 BYTE)             NOT NULL,
  AL_INTERNAL_CODE     NUMBER(8),
  AL_CREATE_USER       VARCHAR2(20 BYTE),
  AL_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  AL_UPDATE_USER       VARCHAR2(20 BYTE),
  AL_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX TXN_ACK_LOG_IDX01 ON TXN_ACK_LOG
(AL_TXN_ID, AL_ORG_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

