OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnOmtByUsOVU
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnOmtByUsOVU.so
SOOBJS = TxnOmtByUsOVU.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
