OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/VoucherPaymentParameter
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBVoucherPaymentParameter.so
SOOBJS =  VoucherPaymentParameter.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
