ALTER TABLE MERCHANT_BUCKET_PREVIEW
 DROP PRIMARY KEY CASCADE;

DROP TABLE MERCHANT_BUCKET_PREVIEW CASCADE CONSTRAINTS;

CREATE TABLE MERCHANT_BUCKET_PREVIEW
(
  MBP_POSTING_DATE      VARCHAR2(8 BYTE),
  MBP_MERCHANT_ID       VARCHAR2(15 BYTE),
  MBP_COUNTRY_ID        CHAR(2 BYTE),
  MBP_CURRENCY_ID       VARCHAR2(3 BYTE),
  MBP_SERVICE_CODE      CHAR(3 BYTE),
  MBP_PSP_ID            VARCHAR2(10 BYTE),
  MBP_BUCKET_TYPE       VARCHAR2(2 BYTE),
  MBP_BAL               NUMBER(14,2),
  MBP_CREATE_USER       VARCHAR2(20 BYTE),
  MBP_UPDATE_USER       VARCHAR2(20 BYTE),
  MBP_CREATE_TIMESTAMP  DATE,
  MBP_UPDATE_TIMESTAMP  DATE
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN MERCHANT_BUCKET_PREVIEW.MBP_BUCKET_TYPE IS 'FT- FLOAT, RS- RESERVED,SF - SETTLEMET FLOAT';




CREATE UNIQUE INDEX MERCHANT_BUCKET_PREVIEW_PK ON MERCHANT_BUCKET_PREVIEW
(MBP_POSTING_DATE, MBP_MERCHANT_ID, MBP_COUNTRY_ID, MBP_CURRENCY_ID, MBP_SERVICE_CODE, 
MBP_PSP_ID, MBP_BUCKET_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MERCHANT_BUCKET_PREVIEW ADD (
  CONSTRAINT MERCHANT_BUCKET_PREVIEW_PK
  PRIMARY KEY
  (MBP_POSTING_DATE, MBP_MERCHANT_ID, MBP_COUNTRY_ID, MBP_CURRENCY_ID, MBP_SERVICE_CODE, MBP_PSP_ID, MBP_BUCKET_TYPE)
  USING INDEX MERCHANT_BUCKET_PREVIEW_PK
  ENABLE VALIDATE);

ALTER TABLE MERCHANT_BUCKET_PREVIEW ADD (
  CONSTRAINT MERCHANT_BUCKET_PREVIEW_FK01 
  FOREIGN KEY (MBP_BUCKET_TYPE) 
  REFERENCES DEF_BUCKET_TYPE (B_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT MERCHANT_BUCKET_PREVIEW_FK02 
  FOREIGN KEY (MBP_MERCHANT_ID) 
  REFERENCES MERCH_DETAIL (MERCHANT_ID)
  ENABLE VALIDATE,
  CONSTRAINT MERCHANT_BUCKET_PREVIEW_FK03 
  FOREIGN KEY (MBP_COUNTRY_ID) 
  REFERENCES COUNTRY (COUNTRY_CODE)
  ENABLE VALIDATE,
  CONSTRAINT MERCHANT_BUCKET_PREVIEW_FK04 
  FOREIGN KEY (MBP_CURRENCY_ID) 
  REFERENCES DEF_CURRENCY (DC_CCY_ID)
  ENABLE VALIDATE,
  CONSTRAINT MERCHANT_BUCKET_PREVIEW_FK05 
  FOREIGN KEY (MBP_SERVICE_CODE) 
  REFERENCES DEF_SERVICE_CODE (SC_CODE)
  ENABLE VALIDATE);

