ALTER TABLE CUSTOMER_GROUP_MERCHANT
 DROP PRIMARY KEY CASCADE;

DROP TABLE CUSTOMER_GROUP_MERCHANT CASCADE CONSTRAINTS;

CREATE TABLE CUSTOMER_GROUP_MERCHANT
(
  CGM_MERCHANT_ID       VARCHAR2(15 BYTE),
  CGM_DISABLED          INTEGER                 DEFAULT 0,
  CGM_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  CGM_CREATE_USER       VARCHAR2(20 BYTE),
  CGM_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  CGM_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CUSTOMER_GROUP_MERCHANT_PK ON CUSTOMER_GROUP_MERCHANT
(CGM_MERCHANT_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE CUSTOMER_GROUP_MERCHANT ADD (
  CONSTRAINT CUSTOMER_GROUP_MERCHANT_PK
  PRIMARY KEY
  (CGM_MERCHANT_ID)
  USING INDEX CUSTOMER_GROUP_MERCHANT_PK
  ENABLE VALIDATE);

ALTER TABLE CUSTOMER_GROUP_MERCHANT ADD (
  CONSTRAINT CUSTOMER_GROUP_MERCHANT_FK01 
  FOREIGN KEY (CGM_MERCHANT_ID) 
  REFERENCES MERCH_DETAIL (MERCHANT_ID)
  ENABLE VALIDATE);

