ALTER TABLE OL_MERCHANT_UPLOAD_ERROR
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_MERCHANT_UPLOAD_ERROR CASCADE CONSTRAINTS;

CREATE TABLE OL_MERCHANT_UPLOAD_ERROR
(
  OUE_ERROR_ID          INTEGER,
  OUE_BATCH_ID          INTEGER,
  OUE_RECORD            VARCHAR2(255 BYTE),
  OUE_CREATE_USER       VARCHAR2(20 BYTE),
  OUE_UPDATE_USER       VARCHAR2(20 BYTE),
  OUE_CREATE_TIMESTAMP  DATE                     DEFAULT SYSDATE,
  OUE_UPDATE_TIMESTAMP  DATE                     DEFAULT SYSDATE
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_MERCHANT_UPLOAD_ERROR_PK ON OL_MERCHANT_UPLOAD_ERROR
(OUE_ERROR_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_MERCHANT_UPLOAD_ERROR ADD (
  CONSTRAINT OL_MERCHANT_UPLOAD_ERROR_PK
  PRIMARY KEY
  (OUE_ERROR_ID)
  USING INDEX OL_MERCHANT_UPLOAD_ERROR_PK
  ENABLE VALIDATE);

ALTER TABLE OL_MERCHANT_UPLOAD_ERROR ADD (
  CONSTRAINT OL_MERCHANT_UPLOAD_ERROR_FK01 
  FOREIGN KEY (OUE_BATCH_ID) 
  REFERENCES OL_MERCHANT_UPLOAD_FILE_HEADER (OUH_BATCH_ID)
  ENABLE VALIDATE);

