OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/RuleCheckHandShake
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBRuleCheckHandShake.so
SOOBJS =  RuleCheckHandShake.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
