OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmsBankBalance
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmsBankBalance.so
SOOBJS =  MmsBankBalance.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
