OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOMMSPhTxn
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOMMSPhTxn.so
SOOBJS = BOMMSPhTxn.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
