


insert all
into ol_sms_format_template (osmt_format_id, osmt_format_type, osmt_format_value, osmt_format_desc, osmt_delimiter, osmt_delimiter_desc, osmt_is_generic, osmt_create_timestamp, osmt_create_user, osmt_update_timestamp, osmt_update_user)
values ('086309_1', 'CONTENT', 1, 'req_bank_day', '日', null, 0, sysdate, 'SYSTEM', sysdate, 'SYSTEM')
into ol_sms_format_template (osmt_format_id, osmt_format_type, osmt_format_value, osmt_format_desc, osmt_delimiter, osmt_delimiter_desc, osmt_is_generic, osmt_create_timestamp, osmt_create_user, osmt_update_timestamp, osmt_update_user)
values ('086309_1', 'CONTENT', 2, 'req_bank_hour', ':', null, 0, sysdate, 'SYSTEM', sysdate, 'SYSTEM')
into ol_sms_format_template (osmt_format_id, osmt_format_type, osmt_format_value, osmt_format_desc, osmt_delimiter, osmt_delimiter_desc, osmt_is_generic, osmt_create_timestamp, osmt_create_user, osmt_update_timestamp, osmt_update_user)
values ('086309_1', 'CONTENT', 3, 'req_bank_minute', '账户*', null, 0, sysdate, 'SYSTEM', sysdate, 'SYSTEM')
into ol_sms_format_template (osmt_format_id, osmt_format_type, osmt_format_value, osmt_format_desc, osmt_delimiter, osmt_delimiter_desc, osmt_is_generic, osmt_create_timestamp, osmt_create_user, osmt_update_timestamp, osmt_update_user)
values ('086309_1', 'CONTENT', 4, 'req_bank_acc', '*汇款汇入收入', null, 0, sysdate, 'SYSTEM', sysdate, 'SYSTEM')
into ol_sms_format_template (osmt_format_id, osmt_format_type, osmt_format_value, osmt_format_desc, osmt_delimiter, osmt_delimiter_desc, osmt_is_generic, osmt_create_timestamp, osmt_create_user, osmt_update_timestamp, osmt_update_user)
values ('086309_1', 'CONTENT', 5, 'req_bank_amount', '元，余额', null, 0, sysdate, 'SYSTEM', sysdate, 'SYSTEM')
into ol_sms_format_template (osmt_format_id, osmt_format_type, osmt_format_value, osmt_format_desc, osmt_delimiter, osmt_delimiter_desc, osmt_is_generic, osmt_create_timestamp, osmt_create_user, osmt_update_timestamp, osmt_update_user)
values ('086309_1', 'CONTENT', 6, 'req_bank_bal', '元。对方户名:', null, 0, sysdate, 'SYSTEM', sysdate, 'SYSTEM')
into ol_sms_format_template (osmt_format_id, osmt_format_type, osmt_format_value, osmt_format_desc, osmt_delimiter, osmt_delimiter_desc, osmt_is_generic, osmt_create_timestamp, osmt_create_user, osmt_update_timestamp, osmt_update_user)
values ('086309_1', 'CONTENT', 7, 'req_payer', '[兴业银行]', null, 0, sysdate, 'SYSTEM', sysdate, 'SYSTEM')
into ol_sms_format_template (osmt_format_id, osmt_format_type, osmt_format_value, osmt_format_desc, osmt_delimiter, osmt_delimiter_desc, osmt_is_generic, osmt_create_timestamp, osmt_create_user, osmt_update_timestamp, osmt_update_user)
values ('086309_1', 'CONTENT_CNT', 7, null, null, null, 0, sysdate, 'SYSTEM', sysdate, 'SYSTEM')
into ol_sms_format_template (osmt_format_id, osmt_format_type, osmt_format_value, osmt_format_desc, osmt_delimiter, osmt_delimiter_desc, osmt_is_generic, osmt_create_timestamp, osmt_create_user, osmt_update_timestamp, osmt_update_user)
values ('086309_2', 'CONTENT', 1, 'req_bank_day', '日', null, 0, sysdate, 'SYSTEM', sysdate, 'SYSTEM')
into ol_sms_format_template (osmt_format_id, osmt_format_type, osmt_format_value, osmt_format_desc, osmt_delimiter, osmt_delimiter_desc, osmt_is_generic, osmt_create_timestamp, osmt_create_user, osmt_update_timestamp, osmt_update_user)
values ('086309_2', 'CONTENT', 2, 'req_bank_hour', ':', null, 0, sysdate, 'SYSTEM', sysdate, 'SYSTEM')
into ol_sms_format_template (osmt_format_id, osmt_format_type, osmt_format_value, osmt_format_desc, osmt_delimiter, osmt_delimiter_desc, osmt_is_generic, osmt_create_timestamp, osmt_create_user, osmt_update_timestamp, osmt_update_user)
values ('086309_2', 'CONTENT', 3, 'req_bank_minute', '账户*', null, 0, sysdate, 'SYSTEM', sysdate, 'SYSTEM')
into ol_sms_format_template (osmt_format_id, osmt_format_type, osmt_format_value, osmt_format_desc, osmt_delimiter, osmt_delimiter_desc, osmt_is_generic, osmt_create_timestamp, osmt_create_user, osmt_update_timestamp, osmt_update_user)
values ('086309_2', 'CONTENT', 4, 'req_bank_acc', '*汇款汇入收入', null, 0, sysdate, 'SYSTEM', sysdate, 'SYSTEM')
into ol_sms_format_template (osmt_format_id, osmt_format_type, osmt_format_value, osmt_format_desc, osmt_delimiter, osmt_delimiter_desc, osmt_is_generic, osmt_create_timestamp, osmt_create_user, osmt_update_timestamp, osmt_update_user)
values ('086309_2', 'CONTENT', 5, 'req_bank_amount', '元，余额', null, 0, sysdate, 'SYSTEM', sysdate, 'SYSTEM')
into ol_sms_format_template (osmt_format_id, osmt_format_type, osmt_format_value, osmt_format_desc, osmt_delimiter, osmt_delimiter_desc, osmt_is_generic, osmt_create_timestamp, osmt_create_user, osmt_update_timestamp, osmt_update_user)
values ('086309_2', 'CONTENT', 6, 'req_bank_bal', '元。对方户名:', null, 0, sysdate, 'SYSTEM', sysdate, 'SYSTEM')
into ol_sms_format_template (osmt_format_id, osmt_format_type, osmt_format_value, osmt_format_desc, osmt_delimiter, osmt_delimiter_desc, osmt_is_generic, osmt_create_timestamp, osmt_create_user, osmt_update_timestamp, osmt_update_user)
values ('086309_2', 'CONTENT', 7, 'req_payer', '（NonResident）[兴业银行]', null, 0, sysdate, 'SYSTEM', sysdate, 'SYSTEM')
into ol_sms_format_template (osmt_format_id, osmt_format_type, osmt_format_value, osmt_format_desc, osmt_delimiter, osmt_delimiter_desc, osmt_is_generic, osmt_create_timestamp, osmt_create_user, osmt_update_timestamp, osmt_update_user)
values ('086309_2', 'CONTENT_CNT', 7, null, null, null, 0, sysdate, 'SYSTEM', sysdate, 'SYSTEM')
into ol_sms_format_template (osmt_format_id, osmt_format_type, osmt_format_value, osmt_format_desc, osmt_delimiter, osmt_delimiter_desc, osmt_is_generic, osmt_create_timestamp, osmt_create_user, osmt_update_timestamp, osmt_update_user)
values ('086309_3', 'CONTENT', 1, 'req_bank_day', '日', null, 0, sysdate, 'SYSTEM', sysdate, 'SYSTEM')
into ol_sms_format_template (osmt_format_id, osmt_format_type, osmt_format_value, osmt_format_desc, osmt_delimiter, osmt_delimiter_desc, osmt_is_generic, osmt_create_timestamp, osmt_create_user, osmt_update_timestamp, osmt_update_user)
values ('086309_3', 'CONTENT', 2, 'req_bank_hour', ':', null, 0, sysdate, 'SYSTEM', sysdate, 'SYSTEM')
into ol_sms_format_template (osmt_format_id, osmt_format_type, osmt_format_value, osmt_format_desc, osmt_delimiter, osmt_delimiter_desc, osmt_is_generic, osmt_create_timestamp, osmt_create_user, osmt_update_timestamp, osmt_update_user)
values ('086309_3', 'CONTENT', 3, 'req_bank_minute', '账户*', null, 0, sysdate, 'SYSTEM', sysdate, 'SYSTEM')
into ol_sms_format_template (osmt_format_id, osmt_format_type, osmt_format_value, osmt_format_desc, osmt_delimiter, osmt_delimiter_desc, osmt_is_generic, osmt_create_timestamp, osmt_create_user, osmt_update_timestamp, osmt_update_user)
values ('086309_3', 'CONTENT', 4, 'req_bank_acc', '*汇款汇入收入', null, 0, sysdate, 'SYSTEM', sysdate, 'SYSTEM')
into ol_sms_format_template (osmt_format_id, osmt_format_type, osmt_format_value, osmt_format_desc, osmt_delimiter, osmt_delimiter_desc, osmt_is_generic, osmt_create_timestamp, osmt_create_user, osmt_update_timestamp, osmt_update_user)
values ('086309_3', 'CONTENT', 5, 'req_bank_amount', '元，余额', null, 0, sysdate, 'SYSTEM', sysdate, 'SYSTEM')
into ol_sms_format_template (osmt_format_id, osmt_format_type, osmt_format_value, osmt_format_desc, osmt_delimiter, osmt_delimiter_desc, osmt_is_generic, osmt_create_timestamp, osmt_create_user, osmt_update_timestamp, osmt_update_user)
values ('086309_3', 'CONTENT', 6, 'req_bank_bal', '元。对方户名:', null, 0, sysdate, 'SYSTEM', sysdate, 'SYSTEM')
into ol_sms_format_template (osmt_format_id, osmt_format_type, osmt_format_value, osmt_format_desc, osmt_delimiter, osmt_delimiter_desc, osmt_is_generic, osmt_create_timestamp, osmt_create_user, osmt_update_timestamp, osmt_update_user)
values ('086309_3', 'CONTENT', 7, 'req_payer', '（跨行转出）[兴业银行]', null, 0, sysdate, 'SYSTEM', sysdate, 'SYSTEM')
into ol_sms_format_template (osmt_format_id, osmt_format_type, osmt_format_value, osmt_format_desc, osmt_delimiter, osmt_delimiter_desc, osmt_is_generic, osmt_create_timestamp, osmt_create_user, osmt_update_timestamp, osmt_update_user)
values ('086309_3', 'CONTENT_CNT', 7, null, null, null, 0, sysdate, 'SYSTEM', sysdate, 'SYSTEM')
into ol_sms_format_template (osmt_format_id, osmt_format_type, osmt_format_value, osmt_format_desc, osmt_delimiter, osmt_delimiter_desc, osmt_is_generic, osmt_create_timestamp, osmt_create_user, osmt_update_timestamp, osmt_update_user)
values ('086309_4', 'CONTENT', 1, 'req_bank_day', '日', null, 0, sysdate, 'SYSTEM', sysdate, 'SYSTEM')
into ol_sms_format_template (osmt_format_id, osmt_format_type, osmt_format_value, osmt_format_desc, osmt_delimiter, osmt_delimiter_desc, osmt_is_generic, osmt_create_timestamp, osmt_create_user, osmt_update_timestamp, osmt_update_user)
values ('086309_4', 'CONTENT', 2, 'req_bank_hour', ':', null, 0, sysdate, 'SYSTEM', sysdate, 'SYSTEM')
into ol_sms_format_template (osmt_format_id, osmt_format_type, osmt_format_value, osmt_format_desc, osmt_delimiter, osmt_delimiter_desc, osmt_is_generic, osmt_create_timestamp, osmt_create_user, osmt_update_timestamp, osmt_update_user)
values ('086309_4', 'CONTENT', 3, 'req_bank_minute', '账户*', null, 0, sysdate, 'SYSTEM', sysdate, 'SYSTEM')
into ol_sms_format_template (osmt_format_id, osmt_format_type, osmt_format_value, osmt_format_desc, osmt_delimiter, osmt_delimiter_desc, osmt_is_generic, osmt_create_timestamp, osmt_create_user, osmt_update_timestamp, osmt_update_user)
values ('086309_4', 'CONTENT', 4, 'req_bank_acc', '*汇款汇出支出', null, 0, sysdate, 'SYSTEM', sysdate, 'SYSTEM')
into ol_sms_format_template (osmt_format_id, osmt_format_type, osmt_format_value, osmt_format_desc, osmt_delimiter, osmt_delimiter_desc, osmt_is_generic, osmt_create_timestamp, osmt_create_user, osmt_update_timestamp, osmt_update_user)
values ('086309_4', 'CONTENT', 5, 'req_bank_amount', '元，余额', null, 0, sysdate, 'SYSTEM', sysdate, 'SYSTEM')
into ol_sms_format_template (osmt_format_id, osmt_format_type, osmt_format_value, osmt_format_desc, osmt_delimiter, osmt_delimiter_desc, osmt_is_generic, osmt_create_timestamp, osmt_create_user, osmt_update_timestamp, osmt_update_user)
values ('086309_4', 'CONTENT', 6, 'req_bank_bal', '元。对方户名:', null, 0, sysdate, 'SYSTEM', sysdate, 'SYSTEM')
into ol_sms_format_template (osmt_format_id, osmt_format_type, osmt_format_value, osmt_format_desc, osmt_delimiter, osmt_delimiter_desc, osmt_is_generic, osmt_create_timestamp, osmt_create_user, osmt_update_timestamp, osmt_update_user)
values ('086309_4', 'CONTENT', 7, 'req_payer', '（转账）[兴业银行]', null, 0, sysdate, 'SYSTEM', sysdate, 'SYSTEM')
into ol_sms_format_template (osmt_format_id, osmt_format_type, osmt_format_value, osmt_format_desc, osmt_delimiter, osmt_delimiter_desc, osmt_is_generic, osmt_create_timestamp, osmt_create_user, osmt_update_timestamp, osmt_update_user)
values ('086309_4', 'CONTENT_CNT', 7, null, null, null, 0, sysdate, 'SYSTEM', sysdate, 'SYSTEM')
select * from dual;

