OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLTxnEngineActionMap
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLTxnEngineActionMap.so
SOOBJS =  OLTxnEngineActionMap.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
