ALTER TABLE OL_SEQ_PREFIX
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_SEQ_PREFIX CASCADE CONSTRAINTS;

CREATE TABLE OL_SEQ_PREFIX
(
  OSP_PREFIX            CHAR(1 BYTE),
  OSP_DESC              VARCHAR2(50 BYTE),
  OSP_VAL               VARCHAR2(50 BYTE),
  OSP_CREATE_USER       VARCHAR2(20 BYTE),
  OSP_UPDATE_USER       VARCHAR2(20 BYTE),
  OSP_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  OSP_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX OL_SEQ_PREFIX_IDX01 ON OL_SEQ_PREFIX
(OSP_VAL)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

CREATE UNIQUE INDEX OL_SEQ_PREFIX_PK ON OL_SEQ_PREFIX
(OSP_PREFIX)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_SEQ_PREFIX ADD (
  CONSTRAINT OL_SEQ_PREFIX_PK
  PRIMARY KEY
  (OSP_PREFIX)
  USING INDEX OL_SEQ_PREFIX_PK
  ENABLE VALIDATE);
