OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLPayoutReturnBatchError
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLPayoutReturnBatchError.so
SOOBJS =  OLPayoutReturnBatchError.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
