OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnWebOnUs2LKP
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnWebOnUs2LKP.so
SOOBJS = TxnWebOnUs2LKP.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
