ALTER TABLE MMS_DEF_ACR_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_DEF_ACR_TYPE CASCADE CONSTRAINTS;

CREATE TABLE MMS_DEF_ACR_TYPE
(
  MDA_CODE              VARCHAR2(10 BYTE),
  MDA_DESC              VARCHAR2(50 BYTE),
  MDA_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  MDA_CREATE_USER       VARCHAR2(20 BYTE),
  MDA_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  MDA_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MMS_DEF_ACT_TYPE_PK ON MMS_DEF_ACR_TYPE
(MDA_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_DEF_ACR_TYPE ADD (
  CONSTRAINT MMS_DEF_ACT_TYPE_PK
  PRIMARY KEY
  (MDA_CODE)
  USING INDEX MMS_DEF_ACT_TYPE_PK
  ENABLE VALIDATE);

