ALTER TABLE MMS_DEF_TXN_SUB_STATUS_MAP
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_DEF_TXN_SUB_STATUS_MAP CASCADE CONSTRAINTS;

CREATE TABLE MMS_DEF_TXN_SUB_STATUS_MAP
(
  TSS_TXN_CODE          CHAR(3 BYTE),
  TSS_SUB_STATUS        CHAR(3 BYTE),
  TSS_CREATE_USER       VARCHAR2(20 BYTE),
  TSS_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  TSS_UPDATE_USER       VARCHAR2(20 BYTE),
  TSS_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MMS_DEF_TXN_SUB_STT_MAP_PK ON MMS_DEF_TXN_SUB_STATUS_MAP
(TSS_TXN_CODE, TSS_SUB_STATUS)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_DEF_TXN_SUB_STATUS_MAP ADD (
  CONSTRAINT MMS_DEF_TXN_SUB_STT_MAP_PK
  PRIMARY KEY
  (TSS_TXN_CODE, TSS_SUB_STATUS)
  USING INDEX MMS_DEF_TXN_SUB_STT_MAP_PK
  ENABLE VALIDATE);

ALTER TABLE PHUSER.MMS_DEF_TXN_SUB_STATUS_MAP ADD (
  CONSTRAINT MMS_DEF_TXN_SUB_STT_MAP_FK01 
  FOREIGN KEY (TSS_TXN_CODE) 
  REFERENCES PHUSER.MMS_TXN_CODE (MTC_CODE)
  ENABLE VALIDATE);
