ALTER TABLE OL_TXN_ENGINE_SPC_ACT_DEF
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_TXN_ENGINE_SPC_ACT_DEF CASCADE CONSTRAINTS;

CREATE TABLE OL_TXN_ENGINE_SPC_ACT_DEF
(
  ESAD_SPECIAL_ACTION_DETAIL_ID    INTEGER      	  NOT NULL,
  ESAD_SPECIAL_ACTION_DESC    	   VARCHAR2(50 BYTE),
  ESAD_RETURNED_TAG      	   VARCHAR2(25 BYTE),
  ESAD_RETURNED_VALUE    	   INTEGER,
  ESAD_CREATE_TIMESTAMP  	   DATE                   DEFAULT sysdate,
  ESAD_UPDATE_TIMESTAMP  	   DATE                   DEFAULT sysdate,
  ESAD_CREATE_USER       	   VARCHAR2(20 BYTE),
  ESAD_UPDATE_USER       	   VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_TXN_ENGINE_SPC_ACT_D_PK ON OL_TXN_ENGINE_SPC_ACT_DEF
(ESAD_SPECIAL_ACTION_DETAIL_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_TXN_ENGINE_SPC_ACT_DEF ADD (
  CONSTRAINT OL_TXN_ENGINE_SPC_ACT_D_PK
  PRIMARY KEY
  (ESAD_SPECIAL_ACTION_DETAIL_ID)
  USING INDEX OL_TXN_ENGINE_SPC_ACT_D_PK
  ENABLE VALIDATE);

