ALTER TABLE PHUSER.TXN_SET_CONTRIBUTORS
 DROP PRIMARY KEY CASCADE;

DROP TABLE PHUSER.TXN_SET_CONTRIBUTORS CASCADE CONSTRAINTS;

CREATE TABLE PHUSER.TXN_SET_CONTRIBUTORS
(
  TS_TXN_ID         VARCHAR2(16 BYTE),
  TS_FROM_CCY       VARCHAR2(3 BYTE),
  TS_RATIO          NUMBER(14,5),
  TS_RATE           NUMBER(14,5),
  TS_AMT            NUMBER(14,2),
  CREATE_TIMESTAMP  DATE,
  CREATE_USER       VARCHAR2(20 BYTE),
  UPDATE_TIMESTAMP   DATE,
  UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PHUSER.TXN_SET_CONTRIBUTORS_PK ON PHUSER.TXN_SET_CONTRIBUTORS
(TS_TXN_ID, TS_FROM_CCY)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE PHUSER.TXN_SET_CONTRIBUTORS ADD (
  CONSTRAINT TXN_SET_CONTRIBUTORS_PK
  PRIMARY KEY
  (TS_TXN_ID, TS_FROM_CCY)
  USING INDEX PHUSER.TXN_SET_CONTRIBUTORS_PK);

