ALTER TABLE PAR_PSP_CHANNEL_CODE_MAP
 DROP PRIMARY KEY CASCADE;

DROP TABLE PAR_PSP_CHANNEL_CODE_MAP CASCADE CONSTRAINTS;

CREATE TABLE PAR_PSP_CHANNEL_CODE_MAP
(
  CCM_VNC_PSP_CODE          VARCHAR2(10 BYTE),
  CCM_VNC_PSP_NAME          VARCHAR2(80 BYTE),
  CCM_CHANNEL_CODE          VARCHAR2(10 BYTE),
  CCM_CREATE_TIMESTAMP      DATE,
  CCM_CREATE_USER           VARCHAR2(20 BYTE),
  CCM_UPDATE_TIMESTAMP      DATE,
  CCM_UPDATE_USER           VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PAR_PSP_CHANNEL_CODE_MAP_PK ON PAR_PSP_CHANNEL_CODE_MAP
(CCM_VNC_PSP_CODE, CCM_VNC_PSP_NAME)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PAR_PSP_CHANNEL_CODE_MAP ADD (
  CONSTRAINT PAR_PSP_CHANNEL_CODE_MAP_PK
  PRIMARY KEY
  (CCM_VNC_PSP_CODE, CCM_VNC_PSP_NAME)
  USING INDEX PAR_PSP_CHANNEL_CODE_MAP_PK
  ENABLE VALIDATE);

