ALTER TABLE TXN_BALANCE_DETAIL 
 DROP PRIMARY KEY CASCADE;

DROP TABLE TXN_BALANCE_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE TXN_BALANCE_DETAIL
(
  TBD_TXN_ID			VARCHAR2(16 BYTE),
  TBD_TXN_APRV_DATE		VARCHAR2(8 BYTE),
  TBD_UPD_STATUS		CHAR(1 BYTE),
  TBD_TXN_CODE			VARCHAR2(3 BYTE),
  TBD_MERCHANT_ID		VARCHAR2(15 BYTE),
  TBD_SERVICE_CODE		VARCHAR2(3 BYTE),
  TBD_COUNTRY_ID		CHAR(2 BYTE),
  TBD_NET_CCY			CHAR(3 BYTE),
  TBD_OPEN_BAL			NUMBER(14,2),
  TBD_CURRENT_BAL		NUMBER(14,2),
  TBD_TOTAL_FLOAT		NUMBER(14,2),
  TBD_TOTAL_RESERVED_AMOUNT	NUMBER(14,2),
  TBD_TOTAL_HOLD		NUMBER(14,2),
  TBD_FUNDIN_PAYOUT		NUMBER(14,2),
  TBD_RESERVED_PAYOUT		NUMBER(14,2),
  TBD_TOTAL_FLOAT_AFTER_PAYOUT	NUMBER(14,2),
  TBD_OPEN_BAL_SETTLEMENT	NUMBER(14,2),
  TBD_CURRENT_BAL_SETTLEMENT	NUMBER(14,2),
  TBD_TOTAL_FLOAT_SETTLEMENT	NUMBER(14,2),
  TBD_TOTAL_HOLD_SETTLEMENT	NUMBER(14,2),
  TBD_PSP_ID			VARCHAR2(10 BYTE),
  TBD_PSP_CCY			CHAR(3 BYTE),
  TBD_PSP_BAL			NUMBER(14,2),
  TBD_PSP_TOTAL_FLOAT		NUMBER(14,2),
  TBD_PSP_HOLD			NUMBER(14,2),
  TBD_CREATE_USER		VARCHAR2(20 BYTE),
  TBD_UPDATE_USER		VARCHAR2(20 BYTE),
  TBD_CREATE_TIMESTAMP		DATE			DEFAULT sysdate,
  TBD_UPDATE_TIMESTAMP		DATE			DEFAULT sysdate
)
TABLESPACE USER_DATA
PCTUSED	    0
PCTFREE	    10
INITRANS    1
MAXTRANS    255
STORAGE	    (
	     INITIAL		64K
	     NEXT		1M
	     MINEXTENTS		1
	     MAXEXTENTS		UNLIMITED
	     PCTINCREASE	0
	     BUFFER_POOL	DEFAULT
	    )
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;

COMMENT ON COLUMN TXN_BALANCE_DETAIL.TBD_UPD_STATUS IS 'P - Pending, C - Completed, E - Skipped, R - Rejected';


CREATE UNIQUE INDEX TXN_BALANCE_DETAIL_PK ON TXN_BALANCE_DETAIL
(TBD_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE	    10
INITRANS    2
MAXTRANS    255
STORAGE	    (
	     INITIAL		64K
	     NEXT		1M
	     MINEXTENTS		1
	     MAXEXTENTS		UNLIMITED
	     PCTINCREASE	0
	     BUFFER_POOL	DEFAULT
	    );

CREATE INDEX TXN_BALANCE_DETAIL_IDX01 ON TXN_BALANCE_DETAIL
(TBD_TXN_APRV_DATE, TBD_UPD_STATUS)
LOGGING
TABLESPACE USER_IDX
PCTFREE     10
INITRANS    2
MAXTRANS    255
STORAGE	    (
	     INITIAL		64K
	     NEXT		1M
	     MINEXTENTS		1
	     MAXEXTENTS		UNLIMITED
	     PCTINCREASE	0
	     BUFFER_POOL	DEFAULT
	     FLASH_CACHE	DEFAULT
	     CELL_FLASH_CACHE	DEFAULT
	    )
NOPARALLEL;

ALTER TABLE TXN_BALANCE_DETAIL ADD (
  CONSTRAINT TXN_BALANCE_DETAIL_PK
  PRIMARY KEY
  (TBD_TXN_ID)
  USING INDEX TXN_BALANCE_DETAIL_PK
  ENABLE VALIDATE);
