ALTER TABLE MI_DEF_AR_BAL
 DROP PRIMARY KEY CASCADE;

DROP TABLE MI_DEF_AR_BAL CASCADE CONSTRAINTS;

CREATE TABLE MI_DEF_AR_BAL
(
  AD_CODE              VARCHAR2(10 BYTE)        NOT NULL,
  AD_DESC              VARCHAR2(50 BYTE),
  AD_TXN_CODE_MAP      CHAR(3 BYTE),
  AD_ELEMENT_CODE      CHAR(4 BYTE),
  AD_AMT_TYPE          CHAR(2 BYTE),
  AD_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  AD_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  AD_CREATE_USER       VARCHAR2(20 BYTE),
  AD_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MI_DEF_AR_BAL_PK ON MI_DEF_AR_BAL
(AD_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MI_DEF_AR_BAL ADD (
  CONSTRAINT MI_DEF_AR_BAL_PK
  PRIMARY KEY
  (AD_CODE)
  USING INDEX MI_DEF_AR_BAL_PK
  ENABLE VALIDATE);

ALTER TABLE MI_DEF_AR_BAL ADD (
  CONSTRAINT MI_DEF_AR_BAL_FK01 
  FOREIGN KEY (AD_TXN_CODE_MAP) 
  REFERENCES TXN_CODE (TC_CODE)
  ENABLE VALIDATE,
  CONSTRAINT MI_DEF_AR_BAL_FK02 
  FOREIGN KEY (AD_ELEMENT_CODE) 
  REFERENCES DEF_ELEMENT_TYPE (DT_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT MI_DEF_AR_BAL_FK03 
  FOREIGN KEY (AD_AMT_TYPE) 
  REFERENCES DEF_AMT_TYPE (DA_TYPE)
  ENABLE VALIDATE);

