ALTER TABLE TEST_CREATE
 DROP PRIMARY KEY CASCADE;

DROP TABLE TEST_CREATE CASCADE CONSTRAINTS;

CREATE TABLE TEST_CREATE
(
  TC_KEY               CHAR(1 BYTE),
  TC_FIELD             VARCHAR2(20 BYTE),
  TC_AMOUNT            NUMBER(14,2),
  TC_DISABLED          INTEGER                  DEFAULT 0,
  TC_CCY               VARCHAR2(3 BYTE),
  TC_CREATE_USER       VARCHAR2(20 BYTE),
  TC_UPDATE_USER       VARCHAR2(20 BYTE),
  TC_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  TC_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX TEST_CREATE_PK ON TEST_CREATE
(TC_KEY)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE TEST_CREATE ADD (
  CONSTRAINT TEST_CREATE_PK
  PRIMARY KEY
  (TC_KEY)
  USING INDEX TEST_CREATE_PK
  ENABLE VALIDATE);

ALTER TABLE TEST_CREATE ADD (
  CONSTRAINT FK_CURRENCY 
  FOREIGN KEY (TC_CCY) 
  REFERENCES CURRENCY (CURRENCY_ID)
  ENABLE VALIDATE);
