
CREATE UNIQUE INDEX TEST_CREATE_PK ON TEST_CREATE
(TC_KEY)
LOGGING
TABLESPACE USER_IDX;


ALTER TABLE TEST_CREATE ADD (
  CONSTRAINT TEST_CREATE_PK
  PRIMARY KEY
  (TC_KEY)
  USING INDEX TEST_CREATE_PK
  ENABLE VALIDATE);
