ALTER TABLE MERCHANT_BALANCE_SNAP
 DROP PRIMARY KEY CASCADE;

DROP TABLE MERCHANT_BALANCE_SNAP CASCADE CONSTRAINTS;

CREATE TABLE MERCHANT_BALANCE_SNAP
(
  MBS_SNAPSHOT_TIMESTAMP        DATE,
  MBS_MERCHANT_ID               VARCHAR2(15 BYTE),
  MBS_CURRENCY_ID               VARCHAR2(3 BYTE),
  MBS_COUNTRY_ID                CHAR(2 BYTE),
  MBS_SERVICE_CODE              CHAR(3 BYTE),
  MBS_CURRENT_BAL               NUMBER(14,2),
  MBS_CURRENT_BAL_SETTLEMENT    NUMBER(14,2),
  MBS_TOTAL_FLOAT               NUMBER(14,2),
  MBS_TOTAL_FLOAT_AFTER_PAYOUT  NUMBER(14,2),
  MBS_TOTAL_FLOAT_SETTLEMENT    NUMBER(14,2),
  MBS_TOTAL_RESERVED_AMOUNT     NUMBER(14,2),
  MBS_FUNDIN_PAYOUT             NUMBER(14,2),
  MBS_RESERVED_PAYOUT           NUMBER(14,2),
  MBS_TOTAL_HOLD                NUMBER(14,2),
  MBS_TOTAL_HOLD_SETTLEMENT     NUMBER(14,2),
  MBS_SETTLEMENT_IN_TRANSIT     NUMBER(14,2),
  MBS_CREATE_TIMESTAMP          DATE,
  MBS_CREATE_USER               VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MERCHANT_BALANCE_SNAP_PK ON MERCHANT_BALANCE_SNAP
(MBS_SNAPSHOT_TIMESTAMP, MBS_MERCHANT_ID, MBS_CURRENCY_ID, MBS_COUNTRY_ID, MBS_SERVICE_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MERCHANT_BALANCE_SNAP ADD (
  CONSTRAINT MERCHANT_BALANCE_SNAP_PK
  PRIMARY KEY
  (MBS_SNAPSHOT_TIMESTAMP, MBS_MERCHANT_ID, MBS_CURRENCY_ID, MBS_COUNTRY_ID, MBS_SERVICE_CODE)
  USING INDEX MERCHANT_BALANCE_SNAP_PK
  ENABLE VALIDATE);

