OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLTxnEngineBalanceRule
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLTxnEngineBalanceRule.so
SOOBJS =  OLTxnEngineBalanceRule.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
