OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/TxnCounters
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBTxnCounters.so
SOOBJS =  TxnCounters.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
