DROP TABLE EMAIL_SETTING_HISTORY CASCADE CONSTRAINTS;

CREATE TABLE EMAIL_SETTING_HISTORY
(
  ESH_PARTY_TYPE        CHAR(1 BYTE),
  ESH_PARTY_ID          VARCHAR2(15 BYTE),
  ESH_FUNCT             VARCHAR2(15 BYTE),
  ESH_DEFAULT           INTEGER,
  ESH_DISABLED          INTEGER,
  ESH_CREATE_USER       VARCHAR2(20 BYTE),
  ESH_CREATE_TIMESTAMP  DATE               DEFAULT SYSDATE
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX EMAIL_SETTING_HISTORY_IDX01 ON EMAIL_SETTING_HISTORY
(ESH_PARTY_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

