ALTER TABLE MMS_ENTITY_SUPPORT
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_ENTITY_SUPPORT CASCADE CONSTRAINTS;

CREATE TABLE MMS_ENTITY_SUPPORT
(
  MES_FROM_ENTITY_TYPE  CHAR(3 BYTE),
  MES_TO_ENTITY_TYPE    CHAR(3 BYTE),
  MES_SUPPORT           INTEGER,
  MES_CREATE_TIMESTAMP  DATE                 DEFAULT sysdate,
  MES_CREATE_USER       VARCHAR2(20 BYTE),
  MES_UPDATE_TIMESTAMP  DATE                 DEFAULT sysdate,
  MES_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MMS_ENTITY_SUPPORT_PK ON MMS_ENTITY_SUPPORT
(MES_FROM_ENTITY_TYPE, MES_TO_ENTITY_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_ENTITY_SUPPORT ADD (
  CONSTRAINT MMS_ENTITY_SUPPORT_PK
  PRIMARY KEY
  (MES_FROM_ENTITY_TYPE, MES_TO_ENTITY_TYPE)
  USING INDEX MMS_ENTITY_SUPPORT_PK
  ENABLE VALIDATE);

ALTER TABLE MMS_ENTITY_SUPPORT ADD (
  CONSTRAINT MMS_ENTITY_SUPPORT_FK01 
  FOREIGN KEY (MES_FROM_ENTITY_TYPE) 
  REFERENCES MMS_ENTITY_TYPE (MET_TYPE_CODE)
  ENABLE VALIDATE,
  CONSTRAINT MMS_ENTITY_SUPPORT_FK02 
  FOREIGN KEY (MES_TO_ENTITY_TYPE) 
  REFERENCES MMS_ENTITY_TYPE (MET_TYPE_CODE)
  ENABLE VALIDATE);

