OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLAutoUploadBankDetail
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLAutoUploadBankDetail.so
SOOBJS =  OLAutoUploadBankDetail.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
