OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MerchantLienBucket
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMerchantLienBucket.so
SOOBJS =  MerchantLienBucket.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
