ALTER TABLE CRR_JNL_DETAIL_AMT
 DROP PRIMARY KEY CASCADE;

DROP TABLE CRR_JNL_DETAIL_AMT CASCADE CONSTRAINTS;

CREATE TABLE CRR_JNL_DETAIL_AMT
(
  JNL_ID            VARCHAR2(16 BYTE)           NOT NULL,
  LINE_NO           INTEGER                     NOT NULL,
  CURRENCY_ID       VARCHAR2(3 BYTE)            NOT NULL,
  FX_RATE           NUMBER(12,5),
  CONVERT_AMT       NUMBER(12,2)                NOT NULL,
  DISABLED          NUMBER(1)                   DEFAULT 0,
  CREATE_TIMESTAMP  DATE                        DEFAULT SYSDATE,
  UPDATE_TIMESTAMP  DATE                        DEFAULT SYSDATE,
  CREATE_USER       VARCHAR2(20 BYTE),
  UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CRR_JNL_DETAIL_AMT_PK ON CRR_JNL_DETAIL_AMT
(JNL_ID, LINE_NO, CURRENCY_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE CRR_JNL_DETAIL_AMT ADD (
  CONSTRAINT CRR_JNL_DETAIL_AMT_PK
  PRIMARY KEY
  (JNL_ID, LINE_NO, CURRENCY_ID)
  USING INDEX CRR_JNL_DETAIL_AMT_PK);

ALTER TABLE CRR_JNL_DETAIL_AMT ADD (
  CONSTRAINT CRR_JNL_DETAIL_AMT_FK01 
  FOREIGN KEY (JNL_ID, LINE_NO) 
  REFERENCES CRR_JNL_DETAIL (JNL_ID, LINE_NO),
  CONSTRAINT CRR_JNL_DETAIL_AMT_FK02 
  FOREIGN KEY (CURRENCY_ID) 
  REFERENCES CURRENCY (CURRENCY_ID),
  CONSTRAINT CRR_JNL_DETAIL_AMT_FK03 
  FOREIGN KEY (JNL_ID) 
  REFERENCES CRR_JNL_HEADER (JNL_ID));


