OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnMgtByUsITS
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnMgtByUsITS.so
SOOBJS = TxnMgtByUsITS.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
