OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOTransaction
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOTransaction.so
SOOBJS = BOTransaction.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
