OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLPayoutGeneratedFileHD
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLPayoutGeneratedFileHD.so
SOOBJS =  OLPayoutGeneratedFileHD.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
