
#cd BankDesc && touch *.pc &&  make all && cd ..
#cd BankMapping && touch *.pc &&  make all && cd ..
#cd BankMerchantMapping && touch *.pc &&  make all && cd ..
#cd BankPayoutPsp && touch *.pc &&  make all && cd ..
#cd CctTxn && touch *.pc &&  make all && cd ..
#cd Clients && touch *.pc &&  make all && cd ..
#cd ConvStoreMapping && touch *.pc &&  make all && cd ..
#cd Country && touch *.pc &&  make all && cd ..
#cd CrrBaseCurrency && touch *.pc &&  make all && cd ..
#cd CrrExtMerchDetail && touch *.pc &&  make all && cd ..
#cd CrrExtPspDetail && touch *.pc &&  make all && cd ..
#cd CrrJnlDetail && touch *.pc &&  make all && cd ..
#cd CrrJnlDetailAmt && touch *.pc &&  make all && cd ..
#cd CrrJnlHeader && touch *.pc &&  make all && cd ..
#cd CrrJnlHeaderSeq && touch *.pc &&  make all && cd ..
#cd CrrJnlType && touch *.pc &&  make all && cd ..
#cd CrrMonthEnd && touch *.pc &&  make all && cd ..
#cd CrrRulePosting && touch *.pc &&  make all && cd ..
#cd Currency && touch *.pc &&  make all && cd ..
#cd DefCounterType && touch *.pc &&  make all && cd ..
#cd DefPayMethod && touch *.pc &&  make all && cd ..
#cd DefProduct && touch *.pc &&  make all && cd ..
#cd DepositMismatch && touch *.pc &&  make all && cd ..
#cd ExchangeLimitRate && touch *.pc &&  make all && cd ..
#cd ExchangeRate && touch *.pc &&  make all && cd ..
#cd HoldAmount && touch *.pc &&  make all && cd ..
#cd Language && touch *.pc &&  make all && cd ..
#cd MerchDetail && touch *.pc &&  make all && cd ..
#cd MerchKeys && touch *.pc &&  make all && cd ..
#cd MerchantBalAcct && touch *.pc &&  make all && cd ..
#cd MerchBalance && touch *.pc &&  make all && cd ..
#cd MerchantBucket && touch *.pc &&  make all && cd ..
#cd MerchantPayMethod && touch *.pc &&  make all && cd ..
#cd MerchantReservedAmt && touch *.pc &&  make all && cd ..
#cd MerchantSettleDetail && touch *.pc &&  make all && cd ..
#cd MerchantUploadFileDetail && touch *.pc &&  make all && cd ..
#cd MerchantUploadFileHeader && touch *.pc &&  make all && cd ..
#cd Messages && touch *.pc &&  make all && cd ..
#cd MmsKeys && touch *.pc &&  make all && cd ..
#cd MmsTransaction && touch *.pc &&  make all && cd ..
#cd MmsTxnRetry && touch *.pc &&  make all && cd ..
#cd MmsTxnSeq && touch *.pc &&  make all && cd ..
#cd MmxNodes && touch *.pc &&  make all && cd ..
#cd NonPostingDateResp && touch *.pc &&  make all && cd ..
cd PayoutGeneratedFileDT && touch *.pc &&  make all && cd ..
cd PayoutGeneratedFileHD && touch *.pc &&  make all && cd ..
cd PayoutHeader && touch *.pc &&  make all && cd ..
#cd PayoutOperatorType && touch *.pc &&  make all && cd ..
cd PayoutOperatorTypeDetail && touch *.pc &&  make all && cd ..
cd PayoutRecord && touch *.pc &&  make all && cd ..
cd PspBalance && touch *.pc &&  make all && cd ..
cd PspCountry && touch *.pc &&  make all && cd ..
cd PspDetail && touch *.pc &&  make all && cd ..
cd PspKeys && touch *.pc &&  make all && cd ..
cd PspRequestTxnUrl && touch *.pc &&  make all && cd ..
cd PspUrl && touch *.pc &&  make all && cd ..
cd RuleExMarkup && touch *.pc &&  make all && cd ..
cd RuleMerchantTxnCap && touch *.pc &&  make all && cd ..
cd RuleOperatorTypeDetail && touch *.pc &&  make all && cd ..
cd RulePayoutPsp && touch *.pc &&  make all && cd ..
cd RulePspReleasePeriod && touch *.pc &&  make all && cd ..
cd RuleTxnFee && touch *.pc &&  make all && cd ..
cd RuleTxnFeeDef && touch *.pc &&  make all && cd ..
cd RuleTxnLimit && touch *.pc &&  make all && cd ..
cd RuleTxnRes && touch *.pc &&  make all && cd ..
cd Service && touch *.pc &&  make all && cd ..
cd ServicePayMethod && touch *.pc &&  make all && cd ..
cd SystemControl && touch *.pc &&  make all && cd ..
cd SystemParameter && touch *.pc &&  make all && cd ..
cd TmaLog && touch *.pc &&  make all && cd ..
cd Transaction && touch *.pc &&  make all && cd ..
cd TxnAckRetry && touch *.pc &&  make all && cd ..
cd TxnBeUrl && touch *.pc &&  make all && cd ..
cd TxnCctAckRetry && touch *.pc &&  make all && cd ..
cd TxnCode && touch *.pc &&  make all && cd ..
cd TxnCounters && touch *.pc &&  make all && cd ..
cd TxnFeeChg && touch *.pc &&  make all && cd ..
cd TxnFeUrl && touch *.pc &&  make all && cd ..
cd TxnLbStp && touch *.pc &&  make all && cd ..
cd TxnPspDetail && touch *.pc &&  make all && cd ..
cd TxnRptUrl && touch *.pc &&  make all && cd ..
cd TxnSeq && touch *.pc &&  make all && cd ..
cd TxnSupported && touch *.pc &&  make all && cd ..
