OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/RuleTxnFee
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBRuleTxnFee.so
SOOBJS =  RuleTxnFee.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
