ALTER TABLE PAYOUT_OPERATOR_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE PAYOUT_OPERATOR_TYPE CASCADE CONSTRAINTS;

CREATE TABLE PAYOUT_OPERATOR_TYPE
(
  OT_TYPE              CHAR(2 BYTE)             NOT NULL,
  OT_NAME              VARCHAR2(50 BYTE)        NOT NULL,
  OT_DISABLED          INTEGER                  DEFAULT 0,
  OT_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  OT_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  OT_CREATE_USER       VARCHAR2(20 BYTE),
  OT_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PAYOUT_OPERATOR_TYPE_PK ON PAYOUT_OPERATOR_TYPE
(OT_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE PAYOUT_OPERATOR_TYPE ADD (
  CONSTRAINT PAYOUT_OPERATOR_TYPE_PK
  PRIMARY KEY
  (OT_TYPE)
  USING INDEX PAYOUT_OPERATOR_TYPE_PK);

