ALTER TABLE MMS_BANK_DETAIL
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_BANK_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE MMS_BANK_DETAIL
(
  BD_BANK_ID                   VARCHAR2(15 BYTE),
  BD_BANK_NAME                 VARCHAR2(50 BYTE),
  BD_BANK_ACCT                 VARCHAR2(25 BYTE),
  BD_DISABLED                 INTEGER              DEFAULT 0,
  BD_CREATE_TIMESTAMP         DATE                 DEFAULT sysdate,
  BD_UPDATE_TIMESTAMP         DATE                 DEFAULT sysdate,
  BD_CREATE_USER              VARCHAR2(20 BYTE),
  BD_UPDATE_USER              VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX MMS_BANK_DETAIL_IDX01 ON MMS_BANK_DETAIL
(BD_DISABLED)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX MMS_BANK_DETAIL_PK ON MMS_BANK_DETAIL
(BD_BANK_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_BANK_DETAIL ADD (
  CONSTRAINT MMS_BANK_DETAIL_PK
  PRIMARY KEY
  (BD_BANK_ID)
  USING INDEX MMS_BANK_DETAIL_PK
  ENABLE VALIDATE);
