OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/CustomerGroup
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBCustomerGroup.so
SOOBJS =  CustomerGroup.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
