OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOMMSAverageCostRate
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOMMSAverageCostRate.so
SOOBJS = BOMMSAverageCostRate.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
