OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOMiEntityBalance
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOMiEntityBalance.so
SOOBJS = BOMiEntityBalance.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
