OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/PspCountry
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBPspCountry.so
SOOBJS =  PspCountry.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
