ALTER TABLE MMS_ENTITY_RSP
 ADD (MER_STATUS_REF  CHAR(1 BYTE));

ALTER TABLE MMS_ENTITY_RSP
 ADD (MER_NODE_ID  VARCHAR2(5 BYTE));

ALTER TABLE MMS_ENTITY_RSP
 ADD (MER_ACCT_TYPE  CHAR(1 BYTE));

ALTER TABLE MMS_ENTITY_RSP
 ADD (MER_RELATE_GRP  VARCHAR2(20 BYTE));
