ALTER TABLE MMS_ENTITY_RSP
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_ENTITY_RSP CASCADE CONSTRAINTS;

CREATE TABLE MMS_ENTITY_RSP
(
  MER_ENTITY_ID         VARCHAR2(20 BYTE),
  MER_RSP_ID            VARCHAR2(20 BYTE),
  MER_DESC              VARCHAR2(100 BYTE),
  MER_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  MER_CREATE_USER       VARCHAR2(20 BYTE),
  MER_UPDATE_TIMESTAMP  DATE,
  MER_UPDATE_USER       VARCHAR2(20 BYTE),
  MER_STATUS_REF	CHAR(1 BYTE),
  MER_NODE_ID		VARCHAR2(5 BYTE),
  MER_ACCT_TYPE		CHAR(1 BYTE),
  MER_RELATE_GRP	VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX MMS_ENTITY_RSP_IDX01 ON MMS_ENTITY_RSP
(MER_ENTITY_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX MMS_ENTITY_RSP_PK ON MMS_ENTITY_RSP
(MER_RSP_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_ENTITY_RSP ADD (
  CONSTRAINT MMS_ENTITY_RSP_PK
  PRIMARY KEY
  (MER_RSP_ID)
  USING INDEX MMS_ENTITY_RSP_PK
  ENABLE VALIDATE);

