OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/ExchangeRateTmp
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBExchangeRateTmp.so
SOOBJS =  ExchangeRateTmp.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
