ALTER TABLE OL_RULE_BAID_AUTO_GEN
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_RULE_BAID_AUTO_GEN CASCADE CONSTRAINTS;

CREATE TABLE OL_RULE_BAID_AUTO_GEN
(
  RAG_BANK_ACCT_TYPE    CHAR(3 BYTE),
  RAG_BAID_CAT_TYPE     VARCHAR2(10 BYTE),
  RAG_DISABLE           INTEGER,
  RAG_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  RAG_CREATE_USER       VARCHAR2(20 BYTE),
  RAG_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  RAG_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_RULE_BAID_AUTO_GEN_PK ON OL_RULE_BAID_AUTO_GEN
(RAG_BANK_ACCT_TYPE, RAG_BAID_CAT_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_RULE_BAID_AUTO_GEN ADD (
  CONSTRAINT OL_RULE_BAID_AUTO_GEN_PK
  PRIMARY KEY
  (RAG_BANK_ACCT_TYPE, RAG_BAID_CAT_TYPE)
  USING INDEX OL_RULE_BAID_AUTO_GEN_PK
  ENABLE VALIDATE);

