ALTER TABLE OL_EMAIL_NOTIFY_LIST
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_EMAIL_NOTIFY_LIST CASCADE CONSTRAINTS;

CREATE TABLE OL_EMAIL_NOTIFY_LIST
(
  OEL_ID                INTEGER,
  OEL_EMAIL             VARCHAR2(100 BYTE),
  OEL_CREATE_USER       VARCHAR2(20 BYTE),
  OEL_UPDATE_USER       VARCHAR2(20 BYTE),
  OEL_CREATE_TIMESTAMP  DATE,
  OEL_UPDATE_TIMESTAMP  DATE
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX OL_EMAIL_NOTIFY_LIST_IDX01 ON OL_EMAIL_NOTIFY_LIST
(OEL_EMAIL)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX OL_EMAIL_NOTIFY_LIST_PK ON OL_EMAIL_NOTIFY_LIST
(OEL_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_EMAIL_NOTIFY_LIST ADD (
  CONSTRAINT OL_EMAIL_NOTIFY_LIST_PK
  PRIMARY KEY
  (OEL_ID)
  USING INDEX OL_EMAIL_NOTIFY_LIST_PK
  ENABLE VALIDATE);

