ALTER TABLE MMS_RELATED_TXN
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_RELATED_TXN CASCADE CONSTRAINTS;

CREATE TABLE MMS_RELATED_TXN
(
  MRT_TXN_ID                 VARCHAR2(16 BYTE),
  MRT_DTL_TXN_ID             INTEGER,
  MRT_PREV_TXN_ID            VARCHAR2(16 BYTE),
  MRT_PREV_DTL_TXN_ID        INTEGER,
  MRT_CREATE_TIMESTAMP       DATE,
  MRT_CREATE_USER            VARCHAR2(20 BYTE),
  MRT_UPDATE_TIMESTAMP       DATE,
  MRT_UPDATE_USER            VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MMS_RELATED_TXN_IDX01 ON MMS_RELATED_TXN
(MRT_PREV_TXN_ID, MRT_PREV_DTL_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

ALTER TABLE MMS_RELATED_TXN ADD (
  CONSTRAINT MMS_RELATED_TXN_PK
  PRIMARY KEY
  (MRT_PREV_TXN_ID, MRT_PREV_DTL_TXN_ID)
  USING INDEX MMS_RELATED_TXN_IDX01
  ENABLE VALIDATE);


CREATE INDEX MMS_RELATED_TXN_IDX02 ON MMS_RELATED_TXN
(MRT_TXN_ID, MRT_DTL_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

