OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmsEntityRsp
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmsEntityRsp.so
SOOBJS =  MmsEntityRsp.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
