ALTER TABLE OL_PSP_TXN_SPC_ACTION
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_PSP_TXN_SPC_ACTION CASCADE CONSTRAINTS;

CREATE TABLE OL_PSP_TXN_SPC_ACTION
(
  OSA_ACTION            VARCHAR2(50 BYTE),
  OSA_EXEC_SEQ          INTEGER,
  OSA_BANK_ACCT_TYPE    CHAR(3 BYTE),
  OSA_TRIGGER_TYPE      VARCHAR2(10 BYTE),
  OSA_P1_TXN_ID_TYPE    VARCHAR2(10 BYTE),
  OSA_P1_FIELD          VARCHAR2(50 BYTE),
  OSA_P1_AMT_TYPE       CHAR(2 BYTE),
  OSA_P2_TXN_ID_TYPE    VARCHAR2(10 BYTE),
  OSA_P2_FIELD          VARCHAR2(50 BYTE),
  OSA_P2_AMT_TYPE       CHAR(2 BYTE),
  OSA_COMPARE_OPERATOR  VARCHAR2(20 BYTE),
  OSA_RESULT_KEY        VARCHAR2(50 BYTE),
  OSA_RESULT_VALUE      VARCHAR2(50 BYTE),
  OSA_DISABLED          INTEGER,
  OSA_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  OSA_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  OSA_CREATE_USER       VARCHAR2(20 BYTE),
  OSA_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_PSP_TXN_SPC_ACTION_PK ON OL_PSP_TXN_SPC_ACTION
(OSA_ACTION, OSA_EXEC_SEQ)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_PSP_TXN_SPC_ACTION ADD (
  CONSTRAINT OL_PSP_TXN_SPC_ACTION_PK
  PRIMARY KEY
  (OSA_ACTION, OSA_EXEC_SEQ)
  USING INDEX OL_PSP_TXN_SPC_ACTION_PK
  ENABLE VALIDATE);

ALTER TABLE OL_PSP_TXN_SPC_ACTION ADD (
  CONSTRAINT OL_PSP_TXN_SPC_ACTION_FK01 
  FOREIGN KEY (OSA_TRIGGER_TYPE) 
  REFERENCES OL_DEF_ENGINE_TRIGGER_TYPE (ETT_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OL_PSP_TXN_SPC_ACTION_FK02 
  FOREIGN KEY (OSA_P1_TXN_ID_TYPE) 
  REFERENCES OL_DEF_ENGINE_PARTY (EP_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OL_PSP_TXN_SPC_ACTION_FK03 
  FOREIGN KEY (OSA_P2_TXN_ID_TYPE) 
  REFERENCES OL_DEF_ENGINE_PARTY (EP_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OL_PSP_TXN_SPC_ACTION_FK04 
  FOREIGN KEY (OSA_ACTION) 
  REFERENCES OL_DEF_ENGINE_SPC_ACTION (ESA_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OL_PSP_TXN_SPC_ACTION_FK05 
  FOREIGN KEY (OSA_P1_AMT_TYPE) 
  REFERENCES DEF_AMT_TYPE (DA_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OL_PSP_TXN_SPC_ACTION_FK06 
  FOREIGN KEY (OSA_P2_AMT_TYPE) 
  REFERENCES DEF_AMT_TYPE (DA_TYPE)
  ENABLE VALIDATE);

