ALTER TABLE TXN_ALERT_LOG
 DROP PRIMARY KEY CASCADE;

DROP TABLE TXN_ALERT_LOG CASCADE CONSTRAINTS;

CREATE TABLE TXN_ALERT_LOG
(
  TAL_REPORT_TYPE             VARCHAR2(15 BYTE),
  TAL_TXN_ID                  VARCHAR2(16 BYTE),
  TAL_SEND_ALERT_TIMESTAMP    DATE,
  TAL_ALERT_SENT              INTEGER           DEFAULT 0,
  TAL_CREATE_TIMESTAMP        DATE              DEFAULT sysdate,
  TAL_CREATE_USER             VARCHAR2(20 BYTE),
  TAL_UPDATE_TIMESTAMP        DATE              DEFAULT sysdate,
  TAL_UPDATE_USER             VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX TXN_ALERT_LOG_IDX01 ON TXN_ALERT_LOG
(TAL_REPORT_TYPE, TAL_TXN_ID, TAL_ALERT_SENT)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX TXN_ALERT_LOG_PK ON TXN_ALERT_LOG
(TAL_REPORT_TYPE, TAL_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE TXN_ALERT_LOG ADD (
  CONSTRAINT TXN_ALERT_LOG_PK
  PRIMARY KEY
  (TAL_REPORT_TYPE, TAL_TXN_ID)
  USING INDEX TXN_ALERT_LOG_PK
  ENABLE VALIDATE);

