ALTER TABLE OL_TXN_ACK_RETRY
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_TXN_ACK_RETRY CASCADE CONSTRAINTS;

CREATE TABLE OL_TXN_ACK_RETRY
(
  OTA_BATCH_TXN_ID      VARCHAR2(16 BYTE),
  OTA_TXN_ID            VARCHAR2(16 BYTE),
  OTA_STATUS            CHAR(1 BYTE),
  OTA_LOCAL_TM_DATE     VARCHAR2(8 BYTE),
  OTA_LOCAL_TM_TIME     VARCHAR2(6 BYTE),
  OTA_NEXT_TRY          DATE,
  OTA_CREATE_USER       VARCHAR2(20 BYTE),
  OTA_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  OTA_UPDATE_USER       VARCHAR2(20 BYTE),
  OTA_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  OTA_RESEND_COUNT      INTEGER                  DEFAULT 0,
  OTA_RESET_CNT_TIMESTAMP  DATE
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN OL_TXN_ACK_RETRY.OTA_STATUS IS '''F'' First try, ''R'' - Retry, ''C- Complete';



CREATE INDEX OL_TXN_ACK_RETRY_IDX01 ON OL_TXN_ACK_RETRY
(OTA_BATCH_TXN_ID,OTA_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX OL_TXN_ACK_RETRY_IDX02 ON OL_TXN_ACK_RETRY
(OTA_NEXT_TRY)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_TXN_ACK_RETRY ADD (
  CONSTRAINT OL_TXN_ACK_RETRY_PK
  PRIMARY KEY
  (OTA_BATCH_TXN_ID,OTA_TXN_ID)
  USING INDEX OL_TXN_ACK_RETRY_IDX01
  ENABLE VALIDATE);

