OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnMgtByUsDPT
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnMgtByUsDPT.so
SOOBJS = TxnMgtByUsDPT.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
