


CREATE TABLE PSP_DEPOSIT_TRACE_OVER
(
  DTO_PSP_CHANNEL_CODE  VARCHAR2(10 BYTE),
  DTO_PSP_ID            VARCHAR2(10 BYTE),
  DTO_MODE              CHAR(1 BYTE)            DEFAULT 'S',
  DTO_URL               VARCHAR2(100 BYTE)      NOT NULL,
  DTO_REQUEST_FUNCTION  VARCHAR2(50 BYTE),
  DTO_ACTION            VARCHAR2(50 BYTE),
  DTO_URL_METHOD        VARCHAR2(10 BYTE),
  DTO_DISABLED          INTEGER                 DEFAULT 0,
  DTO_CREATE_USER       VARCHAR2(20 BYTE),
  DTO_UPDATE_USER       VARCHAR2(20 BYTE),
  DTO_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  DTO_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON COLUMN PSP_DEPOSIT_TRACE_OVER.DTO_MODE IS '''S'' - Sync. ''A'' - Async.';


CREATE UNIQUE INDEX PSP_DEPOSIT_TRACE_OVER_PK ON PSP_DEPOSIT_TRACE_OVER
(DTO_PSP_CHANNEL_CODE, DTO_PSP_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE PSP_DEPOSIT_TRACE_OVER ADD (
  CONSTRAINT PSP_DEPOSIT_TRACE_OVER_PK
  PRIMARY KEY
  (DTO_PSP_CHANNEL_CODE, DTO_PSP_ID)
  USING INDEX PSP_DEPOSIT_TRACE_OVER_PK
  ENABLE VALIDATE);

