ALTER TABLE MERCH_COUNTRY
 DROP PRIMARY KEY CASCADE;

DROP TABLE MERCH_COUNTRY CASCADE CONSTRAINTS;

CREATE TABLE MERCH_COUNTRY
(
  MERCHANT_ID       VARCHAR2(10 BYTE),
  COUNTRY           VARCHAR2(2 BYTE),
  EFFECT_DATE       DATE,
  DISABLED          CHAR(1 BYTE),
  UPDATE_TIMESTAMP  DATE                        DEFAULT sysdate,
  CREATE_TIMESTAMP  DATE                        DEFAULT sysdate,
  UPDATE_USER       VARCHAR2(20 BYTE),
  CREATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MERCH_COUNTRY_PK ON MERCH_COUNTRY
(MERCHANT_ID, COUNTRY, EFFECT_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE MERCH_COUNTRY ADD (
  CONSTRAINT MERCH_COUNTRY_PK
  PRIMARY KEY
  (MERCHANT_ID, COUNTRY, EFFECT_DATE)
  USING INDEX MERCH_COUNTRY_PK);

ALTER TABLE MERCH_COUNTRY ADD (
  CONSTRAINT MERCH_COUNTRY_FK01 
  FOREIGN KEY (COUNTRY) 
  REFERENCES COUNTRY (COUNTRY_CODE));

