OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/RulePayoutPsp
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBRulePayoutPsp.so
SOOBJS =  RulePayoutPsp.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
