OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLPayoutTxnAckLog
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLPayoutTxnAckLog.so
SOOBJS =  OLPayoutTxnAckLog.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
