ALTER TABLE DEF_CHANNEL
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_CHANNEL CASCADE CONSTRAINTS;

CREATE TABLE DEF_CHANNEL
(
  DC_CODE              CHAR(3 BYTE),
  DC_DESC              VARCHAR2(50 BYTE),
  DC_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  DC_CREATE_USER       VARCHAR2(20 BYTE),
  DC_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  DC_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEF_CHANNEL_PK ON DEF_CHANNEL
(DC_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_CHANNEL ADD (
  CONSTRAINT DEF_CHANNEL_PK
  PRIMARY KEY
  (DC_CODE)
  USING INDEX DEF_CHANNEL_PK
  ENABLE VALIDATE);

