ALTER TABLE TEST_BATCHJOB_LIST DROP PRIMARY KEY CASCADE;

DROP TABLE TEST_BATCHJOB_LIST CASCADE CONSTRAINTS;

CREATE TABLE TEST_BATCHJOB_LIST
(
	BL_JOB_ID		VARCHAR2(20 BYTE)	NOT NULL,
	BL_SCRIPT_PATH		VARCHAR2(100 BYTE)	NOT NULL,
	BL_SCRIPT_NAME		VARCHAR2(100 BYTE)	NOT NULL,
	BL_DESC			VARCHAR2(100 BYTE),
	BL_DISABLED		INTEGER			DEFAULT 0	NOT NULL,
	BL_CREATE_USER		VARCHAR2(20 BYTE)	DEFAULT NULL,
	BL_CREATE_TIMESTAMP	DATE			DEFAULT sysdate	NOT NULL,
	BL_UPDATE_USER		VARCHAR2(20 BYTE)	DEFAULT NULL,
	BL_UPDATE_TIMESTAMP	DATE			DEFAULT sysdate	NOT NULL
)
TABLESPACE USER_DATA
PCTUSED		0
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE		(
			INITIAL		64K
			NEXT		1M
			MINEXTENTS	1
			MAXEXTENTS	UNLIMITED
			PCTINCREASE	0
			BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;

CREATE UNIQUE INDEX TEST_BATCHJOB_LIST_PK ON TEST_BATCHJOB_LIST
(BL_JOB_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE		10
INITRANS	2
MAXTRANS	255
STORAGE		(
			INITIAL		64K
			NEXT		1M
			MINEXTENTS	1
			MAXEXTENTS	UNLIMITED
			PCTINCREASE	0
			BUFFER_POOL	DEFAULT
		);

ALTER TABLE TEST_BATCHJOB_LIST ADD 
(
	CONSTRAINT TEST_BATCHJOB_LIST_PK
	PRIMARY KEY
	(BL_JOB_ID)
	USING INDEX TEST_BATCHJOB_LIST_PK
	ENABLE VALIDATE
);
