INSERT ALL
	INTO test_batchjob_list (BL_JOB_ID, BL_SCRIPT_PATH, BL_SCRIPT_NAME, BL_DESC, BL_DISABLED, BL_CREATE_USER, BL_UPDATE_USER)
	VALUES ('JOB0001', '/home/phuser/bin/batch/', 'rotate_log.sh', '', 0, 'SYSTEM', 'SYSTEM')
	INTO test_batchjob_list (BL_JOB_ID, BL_SCRIPT_PATH, BL_SCRIPT_NAME, BL_DESC, BL_DISABLED, BL_CREATE_USER, BL_UPDATE_USER)
	VALUES ('JOB0002', '/home/phuser/bin/batch/', 'backuplog.sh', '', 0, 'SYSTEM', 'SYSTEM')
	INTO test_batchjob_list (BL_JOB_ID, BL_SCRIPT_PATH, BL_SCRIPT_NAME, BL_DESC, BL_DISABLED, BL_CREATE_USER, BL_UPDATE_USER)
	VALUES ('JOB0003', '/home/phuser/bin/batch/', 'check_core_dump.sh', '', 0, 'SYSTEM', 'SYSTEM')
	INTO test_batchjob_list (BL_JOB_ID, BL_SCRIPT_PATH, BL_SCRIPT_NAME, BL_DESC, BL_DISABLED, BL_CREATE_USER, BL_UPDATE_USER)
	VALUES ('JOB0004', '/home/phuser/bin/batch/', 'check_ack_queue.sh', '', 0, 'SYSTEM', 'SYSTEM')
	INTO test_batchjob_list (BL_JOB_ID, BL_SCRIPT_PATH, BL_SCRIPT_NAME, BL_DESC, BL_DISABLED, BL_CREATE_USER, BL_UPDATE_USER)
	VALUES ('JOB0005', '/home/phuser/bin/batch/', 'check_gateway.sh', '', 0, 'SYSTEM', 'SYSTEM')
	INTO test_batchjob_list (BL_JOB_ID, BL_SCRIPT_PATH, BL_SCRIPT_NAME, BL_DESC, BL_DISABLED, BL_CREATE_USER, BL_UPDATE_USER)
	VALUES ('JOB0006', '/home/phuser/bin/batch/', 'gen_daily_md5.sh', '', 0, 'SYSTEM', 'SYSTEM')
	INTO test_batchjob_list (BL_JOB_ID, BL_SCRIPT_PATH, BL_SCRIPT_NAME, BL_DESC, BL_DISABLED, BL_CREATE_USER, BL_UPDATE_USER)
	VALUES ('JOB0007', '/home/phuser/bin/batch/', 'ph_cutoff.sh', '', 0, 'SYSTEM', 'SYSTEM')
	INTO test_batchjob_list (BL_JOB_ID, BL_SCRIPT_PATH, BL_SCRIPT_NAME, BL_DESC, BL_DISABLED, BL_CREATE_USER, BL_UPDATE_USER)
	VALUES ('JOB0008', '/home/phuser/bin/batch/', 'handle_daily_float.sh', '', 0, 'SYSTEM', 'SYSTEM')
	INTO test_batchjob_list (BL_JOB_ID, BL_SCRIPT_PATH, BL_SCRIPT_NAME, BL_DESC, BL_DISABLED, BL_CREATE_USER, BL_UPDATE_USER)
	VALUES ('JOB0009', '/home/phuser/bin/batch/', 'handle_daily_float_2AFPO.sh', '', 0, 'SYSTEM', 'SYSTEM')
	INTO test_batchjob_list (BL_JOB_ID, BL_SCRIPT_PATH, BL_SCRIPT_NAME, BL_DESC, BL_DISABLED, BL_CREATE_USER, BL_UPDATE_USER)
	VALUES ('JOB0010', '/home/phuser/bin/batch/', 'check_pspout_gw.sh', '', 0, 'SYSTEM', 'SYSTEM')
	INTO test_batchjob_list (BL_JOB_ID, BL_SCRIPT_PATH, BL_SCRIPT_NAME, BL_DESC, BL_DISABLED, BL_CREATE_USER, BL_UPDATE_USER)
	VALUES ('JOB0011', '/home/phuser/bin/batch/', 'getrate.sh', '', 0, 'SYSTEM', 'SYSTEM')
	INTO test_batchjob_list (BL_JOB_ID, BL_SCRIPT_PATH, BL_SCRIPT_NAME, BL_DESC, BL_DISABLED, BL_CREATE_USER, BL_UPDATE_USER)
	VALUES ('JOB0012', '/home/phuser/bin/batch/', 'check_exchange_rate.sh', '', 0, 'SYSTEM', 'SYSTEM')
	INTO test_batchjob_list (BL_JOB_ID, BL_SCRIPT_PATH, BL_SCRIPT_NAME, BL_DESC, BL_DISABLED, BL_CREATE_USER, BL_UPDATE_USER)
	VALUES ('JOB0013', '/home/phuser/bin/batch/', 'handle_remain_reserved_amt.sh', '', 0, 'SYSTEM', 'SYSTEM')
	INTO test_batchjob_list (BL_JOB_ID, BL_SCRIPT_PATH, BL_SCRIPT_NAME, BL_DESC, BL_DISABLED, BL_CREATE_USER, BL_UPDATE_USER)
	VALUES ('JOB0014', '/home/phuser/bin/batch/', 'handle_reserved.sh', '', 0, 'SYSTEM', 'SYSTEM')
	INTO test_batchjob_list (BL_JOB_ID, BL_SCRIPT_PATH, BL_SCRIPT_NAME, BL_DESC, BL_DISABLED, BL_CREATE_USER, BL_UPDATE_USER)
	VALUES ('JOB0015', '/home/phuser/bin/batch/', 'reset_txn_counter.sh', '', 0, 'SYSTEM', 'SYSTEM')
	INTO test_batchjob_list (BL_JOB_ID, BL_SCRIPT_PATH, BL_SCRIPT_NAME, BL_DESC, BL_DISABLED, BL_CREATE_USER, BL_UPDATE_USER)
	VALUES ('JOB0016', '/home/phuser/bin/batch/', 'check_merchant_txn.sh', '', 0, 'SYSTEM', 'SYSTEM')
	INTO test_batchjob_list (BL_JOB_ID, BL_SCRIPT_PATH, BL_SCRIPT_NAME, BL_DESC, BL_DISABLED, BL_CREATE_USER, BL_UPDATE_USER)
	VALUES ('JOB0017', '/home/phuser/bin/batch/', 'check_psp_txn.sh', '', 0, 'SYSTEM', 'SYSTEM')
	INTO test_batchjob_list (BL_JOB_ID, BL_SCRIPT_PATH, BL_SCRIPT_NAME, BL_DESC, BL_DISABLED, BL_CREATE_USER, BL_UPDATE_USER)
	VALUES ('JOB0018', '/home/phuser/bin/batch/', 'check_hand_shake_init.sh', '', 0, 'SYSTEM', 'SYSTEM')
	INTO test_batchjob_list (BL_JOB_ID, BL_SCRIPT_PATH, BL_SCRIPT_NAME, BL_DESC, BL_DISABLED, BL_CREATE_USER, BL_UPDATE_USER)
	VALUES ('JOB0019', '/home/phuser/bin/batch/', 'gen_psp_limit_report.sh', '', 0, 'SYSTEM', 'SYSTEM')
	INTO test_batchjob_list (BL_JOB_ID, BL_SCRIPT_PATH, BL_SCRIPT_NAME, BL_DESC, BL_DISABLED, BL_CREATE_USER, BL_UPDATE_USER)
	VALUES ('JOB0020', '/home/phuser/bin/batch/', 'check_bank_psp_txn_email.sh', '', 0, 'SYSTEM', 'SYSTEM')
	INTO test_batchjob_list (BL_JOB_ID, BL_SCRIPT_PATH, BL_SCRIPT_NAME, BL_DESC, BL_DISABLED, BL_CREATE_USER, BL_UPDATE_USER)
	VALUES ('JOB0021', '/home/phuser/bin/batch/', 'check_psp_limit.sh', '', 0, 'SYSTEM', 'SYSTEM')
	INTO test_batchjob_list (BL_JOB_ID, BL_SCRIPT_PATH, BL_SCRIPT_NAME, BL_DESC, BL_DISABLED, BL_CREATE_USER, BL_UPDATE_USER)
	VALUES ('JOB0022', '/home/phuser/bin/batch/', 'run_file_for_NG.sh', '', 0, 'SYSTEM', 'SYSTEM')
	INTO test_batchjob_list (BL_JOB_ID, BL_SCRIPT_PATH, BL_SCRIPT_NAME, BL_DESC, BL_DISABLED, BL_CREATE_USER, BL_UPDATE_USER)
	VALUES ('JOB0023', '/home/phuser/bin/batch/', 'run_batch_with_eoddate.sh', '', 0, 'SYSTEM', 'SYSTEM')
	INTO test_batchjob_list (BL_JOB_ID, BL_SCRIPT_PATH, BL_SCRIPT_NAME, BL_DESC, BL_DISABLED, BL_CREATE_USER, BL_UPDATE_USER)
	VALUES ('JOB0024', '/home/phuser/bin/batch/', 'get_payout_resp.sh', '', 0, 'SYSTEM', 'SYSTEM')
	INTO test_batchjob_list (BL_JOB_ID, BL_SCRIPT_PATH, BL_SCRIPT_NAME, BL_DESC, BL_DISABLED, BL_CREATE_USER, BL_UPDATE_USER)
	VALUES ('JOB0025', '/home/phuser/bin/batch/', 'clean_old_file.sh', '', 0, 'SYSTEM', 'SYSTEM')
	INTO test_batchjob_list (BL_JOB_ID, BL_SCRIPT_PATH, BL_SCRIPT_NAME, BL_DESC, BL_DISABLED, BL_CREATE_USER, BL_UPDATE_USER)
	VALUES ('JOB0026', '/home/phuser/bin/batch/', 'gen_psp_delay_callback_report.sh', '', 0, 'SYSTEM', 'SYSTEM')
	INTO test_batchjob_list (BL_JOB_ID, BL_SCRIPT_PATH, BL_SCRIPT_NAME, BL_DESC, BL_DISABLED, BL_CREATE_USER, BL_UPDATE_USER)
	VALUES ('JOB0027', '/home/phuser/bin/batch/', 'handle_auto_settlement.sh', '', 0, 'SYSTEM', 'SYSTEM')
	INTO test_batchjob_list (BL_JOB_ID, BL_SCRIPT_PATH, BL_SCRIPT_NAME, BL_DESC, BL_DISABLED, BL_CREATE_USER, BL_UPDATE_USER)
	VALUES ('JOB0028', '/home/phuser/bin/batch/', 'gen_merchant_bal_snap.sh', '', 0, 'SYSTEM', 'SYSTEM')
	INTO test_batchjob_list (BL_JOB_ID, BL_SCRIPT_PATH, BL_SCRIPT_NAME, BL_DESC, BL_DISABLED, BL_CREATE_USER, BL_UPDATE_USER)
	VALUES ('JOB0029', '/home/phuser/bin/batch/', 'clear_payout_tmp.sh', '', 0, 'SYSTEM', 'SYSTEM')
	INTO test_batchjob_list (BL_JOB_ID, BL_SCRIPT_PATH, BL_SCRIPT_NAME, BL_DESC, BL_DISABLED, BL_CREATE_USER, BL_UPDATE_USER)
	VALUES ('JOB0030', '/home/phuser/bin/batch/', 'check_customer_tag.sh', '', 0, 'SYSTEM', 'SYSTEM')
	INTO test_batchjob_list (BL_JOB_ID, BL_SCRIPT_PATH, BL_SCRIPT_NAME, BL_DESC, BL_DISABLED, BL_CREATE_USER, BL_UPDATE_USER)
	VALUES ('JOB0031', '/home/phuser/bin/batch/', 'ph_auto_gen_holiday.sh', '', 0, 'SYSTEM', 'SYSTEM')
	INTO test_batchjob_list (BL_JOB_ID, BL_SCRIPT_PATH, BL_SCRIPT_NAME, BL_DESC, BL_DISABLED, BL_CREATE_USER, BL_UPDATE_USER)
	VALUES ('JOB0032', '/home/phuser/bin/batch/', 'check_frozen_txn_online.sh', '', 0, 'SYSTEM', 'SYSTEM')
	INTO test_batchjob_list (BL_JOB_ID, BL_SCRIPT_PATH, BL_SCRIPT_NAME, BL_DESC, BL_DISABLED, BL_CREATE_USER, BL_UPDATE_USER)
	VALUES ('JOB0033', '/home/phuser/bin/batch/', 'check_missing_txn_log.sh', '', 0, 'SYSTEM', 'SYSTEM')
	INTO test_batchjob_list (BL_JOB_ID, BL_SCRIPT_PATH, BL_SCRIPT_NAME, BL_DESC, BL_DISABLED, BL_CREATE_USER, BL_UPDATE_USER)
	VALUES ('JOB0034', '/home/phuser/bin/batch/', 'hk_acct_ledger_rpt.sh', '', 0, 'SYSTEM', 'SYSTEM')
	INTO test_batchjob_list (BL_JOB_ID, BL_SCRIPT_PATH, BL_SCRIPT_NAME, BL_DESC, BL_DISABLED, BL_CREATE_USER, BL_UPDATE_USER)
	VALUES ('JOB0035', '/home/phuser/bin/batch/', 'extract_acctledger_dailly_rpt.sh', '', 0, 'SYSTEM', 'SYSTEM')
	INTO test_batchjob_list (BL_JOB_ID, BL_SCRIPT_PATH, BL_SCRIPT_NAME, BL_DESC, BL_DISABLED, BL_CREATE_USER, BL_UPDATE_USER)
	VALUES ('JOB0036', '/home/phuser/bin/batch/', 'collect_fin_data_by_day.sh', '', 0, 'SYSTEM', 'SYSTEM')
	INTO test_batchjob_list (BL_JOB_ID, BL_SCRIPT_PATH, BL_SCRIPT_NAME, BL_DESC, BL_DISABLED, BL_CREATE_USER, BL_UPDATE_USER)
	VALUES ('JOB0037', '/home/phuser/bin/batch/', 'ref_mv_merchant_balance.sh', '', 0, 'SYSTEM', 'SYSTEM')
SELECT * FROM dual;
