ALTER TABLE MERCHANT_APPROVE_QUEUE_HD
 DROP PRIMARY KEY CASCADE;

DROP TABLE MERCHANT_APPROVE_QUEUE_HD CASCADE CONSTRAINTS;

CREATE TABLE MERCHANT_APPROVE_QUEUE_HD
(
  QH_APPROVE_ID        INTEGER,
  QH_POSTING_DATE      VARCHAR(8 BYTE),
  QH_MERCHANT_ID       VARCHAR2(15 BYTE),
  QH_CLIENT_ID         VARCHAR2(10 BYTE),
  QH_SERVICE_CODE      VARCHAR2(3 BYTE),
  QH_COUNTRY           VARCHAR2(2 BYTE),
  QH_CURRENCY          VARCHAR2(3 BYTE),
  QH_TOTAL_COUNT       INTEGER                  DEFAULT 0,
  QH_TOTAL_REQ_AMT     NUMBER(12,2)             DEFAULT 0,
  QH_SUCCESS_COUNT     INTEGER                  DEFAULT 0,
  QH_SUCCESS_REQ_AMT   NUMBER(12,2)             DEFAULT 0,
  QH_STATUS            CHAR(1 BYTE),
  QH_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  QH_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  QH_CREATE_USER       VARCHAR2(20 BYTE),
  QH_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MERCHANT_APPROVE_QUEUE_HD_PK ON MERCHANT_APPROVE_QUEUE_HD
(QH_APPROVE_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MERCHANT_APPROVE_QUEUE_HD ADD (
  CONSTRAINT MERCHANT_APPROVE_QUEUE_HD_PK
  PRIMARY KEY
  (QH_APPROVE_ID)
  USING INDEX MERCHANT_APPROVE_QUEUE_HD_PK
  ENABLE VALIDATE);

