


CREATE TABLE OL_NONTXN_MSG_DETAIL
(
  ONTMD_TXN_ID        	  VARCHAR2(16 BYTE),
  ONTMD_DIRECTION         CHAR(1 BYTE),
  ONTMD_SEQ 	  	  INTEGER,
  ONTMD_TAG      	  VARCHAR2(1024 BYTE),
  ONTMD_VALUE             VARCHAR2(1024 BYTE),
  ONTMD_CREATE_USER       VARCHAR2(20 BYTE),
  ONTMD_CREATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  ONTMD_UPDATE_USER       VARCHAR2(20 BYTE),
  ONTMD_UPDATE_TIMESTAMP  DATE                   DEFAULT sysdate
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE INDEX OL_NONTXN_MSG_DETAIL_IDX01 ON OL_NONTXN_MSG_DETAIL
(ONTMD_CREATE_TIMESTAMP)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX OL_NONTXN_MSG_DETAIL_IDX02 ON OL_NONTXN_MSG_DETAIL
(ONTMD_UPDATE_TIMESTAMP)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX OL_NONTXN_MSG_DETAIL_PK ON OL_NONTXN_MSG_DETAIL
(ONTMD_TXN_ID, ONTMD_DIRECTION, ONTMD_SEQ)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE OL_NONTXN_MSG_DETAIL ADD (
  CONSTRAINT OL_NONTXN_MSG_DETAIL_PK
  PRIMARY KEY
  (ONTMD_TXN_ID, ONTMD_DIRECTION, ONTMD_SEQ)
  USING INDEX OL_NONTXN_MSG_DETAIL_PK
  ENABLE VALIDATE);

