ALTER TABLE SERVICE_BLACKLIST_PATH
 DROP PRIMARY KEY CASCADE;

DROP TABLE SERVICE_BLACKLIST_PATH CASCADE CONSTRAINTS;

CREATE TABLE SERVICE_BLACKLIST_PATH
(
  BP_SERVICE_CODE      CHAR(3 BYTE),
  BP_MERCHANT_ID       VARCHAR2(15 BYTE),
  BP_COUNTRY           VARCHAR2(2 BYTE),
  BP_DIRECTION         CHAR(1 BYTE),
  BP_METHOD            VARCHAR2(3 BYTE),
  BP_PATH              VARCHAR2(50 BYTE),
  BP_LANGUAGE          CHAR(2 BYTE),
  BP_EFFECT_DATE       DATE                     DEFAULT sysdate,
  BP_DISABLED          INTEGER                  DEFAULT 0,
  BP_NEW_UI            INTEGER                  DEFAULT 0,
  BP_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  BP_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  BP_CREATE_USER       VARCHAR2(20 BYTE),
  BP_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX SERVICE_BLACKLIST_PATH_PK ON SERVICE_BLACKLIST_PATH
(BP_SERVICE_CODE, BP_MERCHANT_ID, BP_COUNTRY, BP_DIRECTION, BP_LANGUAGE, 
BP_EFFECT_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE SERVICE_BLACKLIST_PATH ADD (
  CONSTRAINT SERVICE_BLACKLIST_PATH_PK
  PRIMARY KEY
  (BP_SERVICE_CODE, BP_MERCHANT_ID, BP_COUNTRY, BP_DIRECTION, BP_LANGUAGE, BP_EFFECT_DATE)
  USING INDEX SERVICE_BLACKLIST_PATH_PK
  ENABLE VALIDATE);

ALTER TABLE SERVICE_BLACKLIST_PATH ADD (
  CONSTRAINT SERVICE_BLACKLIST_PATH_FK01 
  FOREIGN KEY (BP_SERVICE_CODE) 
  REFERENCES DEF_SERVICE_CODE (SC_CODE)
  ENABLE VALIDATE);

