OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmsEntityPsp
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmsEntityPsp.so
SOOBJS =  MmsEntityPsp.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
