OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnSmsByUsSUL
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnSmsByUsSUL.so
SOOBJS = TxnSmsByUsSUL.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
