OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLTxnSeq
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLTxnSeq.so
SOOBJS =  OLTxnSeq.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
