ALTER TABLE MI_ENTITY_BAL_ACCT
 DROP PRIMARY KEY CASCADE;

DROP TABLE MI_ENTITY_BAL_ACCT CASCADE CONSTRAINTS;

CREATE TABLE MI_ENTITY_BAL_ACCT
(
  BA_ENTITY_ID         VARCHAR2(10 BYTE)        NOT NULL,
  BA_COUNTRY           CHAR(2 BYTE)             NOT NULL,
  BA_CURRENCY          VARCHAR2(3 BYTE)         NOT NULL,
  BA_STATUS            VARCHAR2(2 BYTE),
  BA_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  BA_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  BA_CREATE_USER       VARCHAR2(20 BYTE),
  BA_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MI_ENTITY_BAL_ACCT_PK ON MI_ENTITY_BAL_ACCT
(BA_ENTITY_ID, BA_COUNTRY, BA_CURRENCY)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MI_ENTITY_BAL_ACCT ADD (
  CONSTRAINT MI_ENTITY_BAL_ACCT_PK
  PRIMARY KEY
  (BA_ENTITY_ID, BA_COUNTRY, BA_CURRENCY)
  USING INDEX MI_ENTITY_BAL_ACCT_PK
  ENABLE VALIDATE);

ALTER TABLE MI_ENTITY_BAL_ACCT ADD (
  CONSTRAINT MI_ENTITY_BAL_ACCT_FK01 
  FOREIGN KEY (BA_ENTITY_ID) 
  REFERENCES MI_ENTITY_DETAIL (ED_ENTITY_ID)
  ENABLE VALIDATE,
  CONSTRAINT MI_ENTITY_BAL_ACCT_FK02 
  FOREIGN KEY (BA_COUNTRY) 
  REFERENCES COUNTRY (COUNTRY_CODE)
  ENABLE VALIDATE,
  CONSTRAINT MI_ENTITY_BAL_ACCT_FK03 
  FOREIGN KEY (BA_CURRENCY) 
  REFERENCES DEF_CURRENCY (DC_CCY_ID)
  ENABLE VALIDATE,
  CONSTRAINT MI_ENTITY_BAL_ACCT_FK04 
  FOREIGN KEY (BA_STATUS) 
  REFERENCES DEF_STATUS (DS_TYPE)
  ENABLE VALIDATE);

