OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MerchStatistic
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMerchStatistic.so
SOOBJS =  MerchStatistic.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
