OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/AcctLedgerDailyReport
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBAcctLedgerDailyReport.so
SOOBJS =  AcctLedgerDailyReport.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
