ALTER TABLE OL_DEF_BAID_BT_FILE_STATUS 
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_DEF_BAID_BT_FILE_STATUS CASCADE CONSTRAINTS;

CREATE TABLE OL_DEF_BAID_BT_FILE_STATUS 
(
  BBS_TYPE		CHAR(1 BYTE), 
  BBS_DESC		VARCHAR2(50 BYTE), 
  BBS_CREATE_TIMESTAMP	DATE			DEFAULT sysdate, 
  BBS_CREATE_USER	VARCHAR2(20 BYTE), 
  BBS_UPDATE_TIMESTAMP	DATE			DEFAULT sysdate, 
  BBS_UPDATE_USER	VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA 
PCTUSED    0 
PCTFREE    10 
INITRANS   1 
MAXTRANS   255 
STORAGE    (
            INITIAL     64K
            NEXT        1M 
            MINEXTENTS  1 
            MAXEXTENTS  UNLIMITED 
            PCTINCREASE 0 
            BUFFER_POOL DEFAULT
           ) 
LOGGING 
NOCOMPRESS 
NOCACHE 
MONITORING;

CREATE UNIQUE INDEX OL_DEF_BAID_BT_FILE_STATUS_PK ON OL_DEF_BAID_BT_FILE_STATUS 
(BBS_TYPE) 
LOGGING 
TABLESPACE USER_IDX 
PCTFREE    10 
INITRANS   2 
MAXTRANS   255 
STORAGE    (
            INITIAL     64K 
            NEXT        1M 
            MINEXTENTS  1 
            MAXEXTENTS  UNLIMITED 
            PCTINCREASE 0 
            BUFFER_POOL DEFAULT
           );

ALTER TABLE OL_DEF_BAID_BT_FILE_STATUS ADD (
  CONSTRAINT OL_DEF_BAID_BT_FILE_STATUS_PK 
  PRIMARY KEY 
  (BBS_TYPE) 
  USING INDEX OL_DEF_BAID_BT_FILE_STATUS_PK 
  ENABLE VALIDATE);
