INSERT ALL 
 INTO OL_DEF_BAID_BT_FILE_STATUS (BBS_TYPE, BBS_DESC, BBS_CREATE_USER, BBS_UPDATE_USER) 
 VALUES ('I', 'Initiated', 'SYSTEM', 'SYSTEM') 
 INTO OL_DEF_BAID_BT_FILE_STATUS (BBS_TYPE, BBS_DESC, BBS_CREATE_USER, BBS_UPDATE_USER) 
 VALUES ('P', 'Processing', 'SYSTEM', 'SYSTEM') 
 INTO OL_DEF_BAID_BT_FILE_STATUS (BBS_TYPE, BBS_DESC, BBS_CREATE_USER, BBS_UPDATE_USER) 
 VALUES ('R', 'Declined', 'SYSTEM', 'SYSTEM') 
 INTO OL_DEF_BAID_BT_FILE_STATUS (BBS_TYPE, BBS_DESC, BBS_CREATE_USER, BBS_UPDATE_USER) 
 VALUES ('C', 'Approved', 'SYSTEM', 'SYSTEM') 
SELECT * FROM DUAL;
