ALTER TABLE OL_PSP_SETTLEMENT_DETAIL
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_PSP_SETTLEMENT_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE OL_PSP_SETTLEMENT_DETAIL
(
  PSD_TXN_ID            VARCHAR2(16 BYTE),
  PSD_MERCH_TYPE        INTEGER,
  PSD_TXN_CCY           CHAR(3 BYTE),
  PSD_TXN_COUNTRY       CHAR(2 BYTE),
  PSD_AMOUNT            NUMBER(14,2),
  PSD_CREATE_TIMESTAMP  DATE,
  PSD_UPDATE_TIMESTAMP  DATE,
  PSD_CREATE_USER       VARCHAR2(20 BYTE),
  PSD_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_PSP_SETTLEMENT_DETAIL_PK ON OL_PSP_SETTLEMENT_DETAIL
(PSD_TXN_ID, PSD_MERCH_TYPE, PSD_TXN_CCY, PSD_TXN_COUNTRY)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_PSP_SETTLEMENT_DETAIL ADD (
  CONSTRAINT OL_PSP_SETTLEMENT_DETAIL_PK
  PRIMARY KEY
  (PSD_TXN_ID, PSD_MERCH_TYPE, PSD_TXN_CCY, PSD_TXN_COUNTRY)
  USING INDEX OL_PSP_SETTLEMENT_DETAIL_PK
  ENABLE VALIDATE);

ALTER TABLE OL_PSP_SETTLEMENT_DETAIL ADD (
  CONSTRAINT OL_PSP_SETTLEMENT_DETAIL_FK01 
  FOREIGN KEY (PSD_MERCH_TYPE) 
  REFERENCES OL_DEF_PSP_STL_MERCH_TYPE (PSMT_TYPE)
  ENABLE VALIDATE);

