ALTER TABLE OL_DEF_PARTY_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_DEF_PARTY_TYPE CASCADE CONSTRAINTS;

CREATE TABLE OL_DEF_PARTY_TYPE
(
  OPT_TYPE              VARCHAR2(6 BYTE),
  OPT_GROUP         	CHAR(1 BYTE),
  OPT_ORDER_IN_GROUP	INTEGER,
  OPT_DESC              VARCHAR2(50 BYTE),
  OPT_CREATE_TIMESTAMP  DATE                      DEFAULT sysdate,
  OPT_CREATE_USER       VARCHAR2(20 BYTE),
  OPT_UPDATE_TIMESTAMP  DATE                      DEFAULT sysdate,
  OPT_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_DEF_PARTY_TYPE_PK ON OL_DEF_PARTY_TYPE
(OPT_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_DEF_PARTY_TYPE ADD (
  CONSTRAINT OL_DEF_PARTY_TYPE_PK
  PRIMARY KEY
  (OPT_TYPE)
  USING INDEX OL_DEF_PARTY_TYPE_PK
  ENABLE VALIDATE);

