OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLAcctCreation
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLAcctCreation.so
SOOBJS = OLAcctCreation.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
