ALTER TABLE OL_PAYOUT_GEN_FILE_DT_HIST
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_PAYOUT_GEN_FILE_DT_HIST CASCADE CONSTRAINTS;

CREATE TABLE OL_PAYOUT_GEN_FILE_DT_HIST
(
  ODH_TXN_ID            VARCHAR2(16 BYTE),
  ODH_INIT_TXN_ID       VARCHAR2(16 BYTE),
  ODH_CREATE_USER       VARCHAR2(20 BYTE),
  ODH_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  ODH_UPDATE_USER       VARCHAR2(20 BYTE),
  ODH_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_PAYOUT_GEN_FILE_DT_HIST_PK ON OL_PAYOUT_GEN_FILE_DT_HIST
(ODH_TXN_ID, ODH_INIT_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_PAYOUT_GEN_FILE_DT_HIST ADD (
  CONSTRAINT OL_PAYOUT_GEN_FILE_DT_HIST_PK
  PRIMARY KEY
  (ODH_TXN_ID, ODH_INIT_TXN_ID)
  USING INDEX OL_PAYOUT_GEN_FILE_DT_HIST_PK
  ENABLE VALIDATE);

