ALTER TABLE OL_DEF_BANK_ACCT_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_DEF_BANK_ACCT_TYPE CASCADE CONSTRAINTS;

CREATE TABLE OL_DEF_BANK_ACCT_TYPE
(
  OBC_TYPE              CHAR(3 BYTE),
  OBC_DESC              VARCHAR2(50 BYTE),
  OBC_FE_DISPLAY        INTEGER            DEFAULT 0,
  OBC_BAID_NAME_CODE    CHAR(3 BYTE),
  OBC_SIM_CARD_DISPLAY  INTEGER            DEFAULT 0,
  OBC_CREATE_TIMESTAMP  DATE,
  OBC_CREATE_USER       VARCHAR2(20 BYTE),
  OBC_UPDATE_TIMESTAMP  DATE,
  OBC_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_DEF_BANK_ACCT_TYPE_PK ON OL_DEF_BANK_ACCT_TYPE
(OBC_TYPE)
LOGGING
TABLESPACE USER_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_DEF_BANK_ACCT_TYPE ADD (
  CONSTRAINT OL_DEF_BANK_ACCT_TYPE_PK
  PRIMARY KEY
  (OBC_TYPE)
  USING INDEX OL_DEF_BANK_ACCT_TYPE_PK
  ENABLE VALIDATE);

