OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/Service
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBService.so
SOOBJS =  Service.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
