OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnOmtByUsVSD
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnOmtByUsVSD.so
SOOBJS = TxnOmtByUsVSD.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
