OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/RulePayoutOnlineMode
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBRulePayoutOnlineMode.so
SOOBJS =  RulePayoutOnlineMode.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
