OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MobBankSelection
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMobBankSelection.so
SOOBJS =  MobBankSelection.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
