OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLMerchantBalance
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLMerchantBalance.so
SOOBJS =  OLMerchantBalance.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
