ALTER TABLE FUNDS_OUT_HISTORY
 DROP PRIMARY KEY CASCADE;

DROP TABLE FUNDS_OUT_HISTORY CASCADE CONSTRAINTS;

CREATE TABLE FUNDS_OUT_HISTORY
(
  FO_FUNDS_OUT_ID      INTEGER,
  FO_FUNDS_OUT_DATE    VARCHAR2(8 BYTE),
  FO_FROM_CCY          VARCHAR2(3 BYTE),
  FO_FUNDS_OUT_CCY     VARCHAR2(3 BYTE),
  FO_FUNDS_OUT_AMT     NUMBER(14,2),
  FO_OLD_BAL      	NUMBER(14,2),
  FO_NEW_BAL           NUMBER(14,2),
  FO_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  FO_CREATE_USER       VARCHAR2(20 BYTE),
  FO_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  FO_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX FUNDS_OUT_HISTORY_IDX01 ON FUNDS_OUT_HISTORY
(FO_FUNDS_OUT_DATE, FO_FUNDS_OUT_CCY, FO_FROM_CCY)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX FUNDS_OUT_HISTORY_IDX02 ON FUNDS_OUT_HISTORY
(FO_FUNDS_OUT_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

