ALTER TABLE OL_MERCHANT_BALANCE_SNAP
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_MERCHANT_BALANCE_SNAP CASCADE CONSTRAINTS;

CREATE TABLE OL_MERCHANT_BALANCE_SNAP
(
  OMBS_SNAPSHOT_TIMESTAMP        DATE			DEFAULT sysdate		NOT NULL,
  OMBS_MERCHANT_ID               VARCHAR2(15 BYTE) 				NOT NULL,
  OMBS_CURRENCY_ID               VARCHAR2(3 BYTE) 				NOT NULL,
  OMBS_COUNTRY_ID                CHAR(2 BYTE)   				NOT NULL,
  OMBS_SERVICE_CODE              CHAR(3 BYTE)   				NOT NULL,
  OMBS_CURRENT_BAL               NUMBER(14,2),
  OMBS_CURRENT_BAL_SETTLEMENT    NUMBER(14,2),
  OMBS_TOTAL_FLOAT_AFTER_PAYOUT  NUMBER(14,2),
  OMBS_TOTAL_FLOAT_SETTLEMENT    NUMBER(14,2),
  OMBS_TOTAL_RESERVED_AMOUNT     NUMBER(14,2),
  OMBS_FUNDIN_PAYOUT             NUMBER(14,2),
  OMBS_RESERVED_PAYOUT           NUMBER(14,2),
  OMBS_TOTAL_HOLD                NUMBER(14,2),
  OMBS_TOTAL_HOLD_SETTLEMENT     NUMBER(14,2),
  OMBS_SETTLEMENT_IN_TRANSIT     NUMBER(14,2),
  OMBS_CREATE_TIMESTAMP          DATE           	DEFAULT sysdate,
  OMBS_CREATE_USER               VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_MERCHANT_BALANCE_SNAP_PK ON OL_MERCHANT_BALANCE_SNAP
(OMBS_SNAPSHOT_TIMESTAMP, OMBS_MERCHANT_ID, OMBS_CURRENCY_ID, OMBS_COUNTRY_ID, OMBS_SERVICE_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_MERCHANT_BALANCE_SNAP ADD (
  CONSTRAINT OL_MERCHANT_BALANCE_SNAP_PK
  PRIMARY KEY
  (OMBS_SNAPSHOT_TIMESTAMP, OMBS_MERCHANT_ID, OMBS_CURRENCY_ID, OMBS_COUNTRY_ID, OMBS_SERVICE_CODE)
  USING INDEX OL_MERCHANT_BALANCE_SNAP_PK
  ENABLE VALIDATE);

