


ALTER TABLE OL_AUTO_UPLOAD_ERR_LOG
 ADD (OAUEL_NATURE  VARCHAR2(10 BYTE));

ALTER TABLE OL_AUTO_UPLOAD_ERR_LOG
 ADD (OAUEL_PROVIDER_ID  VARCHAR2(10 BYTE));

ALTER TABLE OL_AUTO_UPLOAD_ERR_LOG
 ADD (OAUEL_INT_BANK_CODE  VARCHAR2(10 BYTE));

CREATE INDEX OL_AUTO_UPLOAD_ERR_LOG_IDX03 ON OL_AUTO_UPLOAD_ERR_LOG
(OAUEL_JOB_SEQ, OAUEL_NATURE, OAUEL_PROVIDER_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
