CREATE TABLE OL_AUTO_UPLOAD_ERR_LOG
(
  OAUEL_JOB_SEQ           INTEGER,
  OAUEL_PROVIDER          VARCHAR2(50 BYTE),
  OAUEL_BANK_NAME         VARCHAR2(50 BYTE),
  OAUEL_ACCT_SHORT_NAME   VARCHAR2(20 BYTE),
  OAUEL_ACCT_NUM          VARCHAR2(50 BYTE),
  OAUEL_STMT_FILENAME     VARCHAR2(100 BYTE),
  OAUEL_STATUS            CHAR(1 BYTE),
  OAUEL_ERR_CODE          NUMBER,
  OAUEL_CREATE_TIMESTAMP  DATE,
  OAUEL_CREATE_USER       VARCHAR2(20 BYTE),
  OAUEL_UPDATE_TIMESTAMP  DATE,
  OAUEL_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE INDEX OL_AUTO_UPLOAD_ERR_LOG_IDX01 ON OL_AUTO_UPLOAD_ERR_LOG
(OAUEL_JOB_SEQ)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX OL_AUTO_UPLOAD_ERR_LOG_IDX02 ON OL_AUTO_UPLOAD_ERR_LOG
(OAUEL_CREATE_TIMESTAMP)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

