OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MerchLimDailyCap
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMerchLimDailyCap.so
SOOBJS =  MerchLimDailyCap.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
