CREATE TABLE OL_TXN_ENGINE_ACCT_CHK
(
  EAC_ACTIVITY          VARCHAR2(50 BYTE),
  EAC_BANK_STMT_TYPE    VARCHAR2(50 BYTE),
  EAC_CHANNEL           CHAR(3 BYTE),
  EAC_TRIGGER_TYPE      VARCHAR2(10 BYTE),
  EAC_RECON_TYPE        VARCHAR2(10 BYTE),
  EAC_PARTY_DIRECTION   VARCHAR2(10 BYTE),
  EAC_CATEGORY          VARCHAR2(10 BYTE),
  EAC_CHK_ID            INTEGER,
  EAC_COMPARE_BY_PARTY  VARCHAR2(10 BYTE),
  EAC_CREATE_TIMESTAMP  DATE,
  EAC_UPDATE_TIMESTAMP  DATE,
  EAC_CREATE_USER       VARCHAR2(20 BYTE),
  EAC_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX OL_TXN_ENGINE_ACCT_CHK_IDX01 ON OL_TXN_ENGINE_ACCT_CHK
(EAC_ACTIVITY, EAC_BANK_STMT_TYPE, EAC_CHANNEL, EAC_TRIGGER_TYPE, EAC_RECON_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_TXN_ENGINE_ACCT_CHK ADD (
  CONSTRAINT OL_TXN_ENGINE_ACCT_CHK_FK01 
  FOREIGN KEY (EAC_ACTIVITY) 
  REFERENCES OL_DEF_ENGINE_ACTIVITY (DEA_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OL_TXN_ENGINE_ACCT_CHK_FK02 
  FOREIGN KEY (EAC_TRIGGER_TYPE) 
  REFERENCES OL_DEF_ENGINE_TRIGGER_TYPE (ETT_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OL_TXN_ENGINE_ACCT_CHK_FK03 
  FOREIGN KEY (EAC_PARTY_DIRECTION) 
  REFERENCES OL_DEF_PARTY_DIRECTION (DPD_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OL_TXN_ENGINE_ACCT_CHK_FK04 
  FOREIGN KEY (EAC_CHK_ID) 
  REFERENCES OL_DEF_ENGINE_ACCT_CHK_RULE (EACR_TYPE)
  ENABLE VALIDATE);

