OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/SystemParameter
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBSystemParameter.so
SOOBJS =  SystemParameter.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
