OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/DepositReqLog
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBDepositReqLog.so
SOOBJS =  DepositReqLog.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
