OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/RuleAmount
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBRuleAmount.so
SOOBJS =  RuleAmount.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
