OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmsInstantPMAcctHd
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmsInstantPMAcctHd.so
SOOBJS =  MmsInstantPMAcctHd.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
