OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/DepositRespLog
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBDepositRespLog.so
SOOBJS =  DepositRespLog.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
