ALTER TABLE OL_TXN_ENGINE_ACTION_MAP
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_TXN_ENGINE_ACTION_MAP CASCADE CONSTRAINTS;

CREATE TABLE OL_TXN_ENGINE_ACTION_MAP
(
  EAM_ACTION_ID           INTEGER,
  EAM_ACTION_DESC	  VARCHAR2(50 BYTE),
  EAM_ACTION_SEQ          INTEGER,
  EAM_ACTION_DETAIL_ID    INTEGER,
  EAM_SPC_ACTION          INTEGER,
  EAM_BEFORE_STATUS_RULE  INTEGER,
  EAM_CREATE_TIMESTAMP    DATE                  DEFAULT sysdate,
  EAM_CREATE_USER         VARCHAR2(20 BYTE),
  EAM_UPDATE_TIMESTAMP    DATE                  DEFAULT sysdate,
  EAM_UPDATE_USER         VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_TXN_ENGINE_ACTION_MAP_PK ON OL_TXN_ENGINE_ACTION_MAP
(EAM_ACTION_ID, EAM_ACTION_SEQ)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_TXN_ENGINE_ACTION_MAP ADD (
  CONSTRAINT OL_TXN_ENGINE_ACTION_MAP_PK
  PRIMARY KEY
  (EAM_ACTION_ID, EAM_ACTION_SEQ)
  USING INDEX OL_TXN_ENGINE_ACTION_MAP_PK
  ENABLE VALIDATE);

