OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/TmpCalAmount
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBTmpCalAmount.so
SOOBJS =  TmpCalAmount.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
