

CREATE TABLE PREGEN_DAILY_REPORT
(
  PDR_ID                  NUMBER(16)             NOT NULL,
  PDR_REPORT_CODE         CHAR(3 BYTE)           NOT NULL,
  PDR_MERCHANT_ID         VARCHAR2(15 BYTE),
  PDR_COUNTRY_ID          CHAR(2 BYTE),
  PDR_CURRENCY_ID         VARCHAR2(3 BYTE),
  PDR_SERVICE_CODE        CHAR(3 BYTE),
  PDR_REPORT_DATE         VARCHAR2(8 BYTE)       NOT NULL,
  PDR_FILENAME            VARCHAR2(100 BYTE),
  PDR_STATUS              CHAR(1 BYTE),
  PDR_DISABLED            INTEGER                DEFAULT 0,
  PDR_CREATE_TIMESTAMP    DATE                   DEFAULT sysdate,
  PDR_CREATE_USER         VARCHAR2(20 BYTE),
  PDR_UPDATE_TIMESTAMP    DATE                   DEFAULT sysdate,
  PDR_UPDATE_USER         VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;


CREATE INDEX PREGEN_DAILY_REPORT_IDX1 ON PREGEN_DAILY_REPORT
(PDR_REPORT_CODE,PDR_REPORT_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

		   
CREATE INDEX PREGEN_DAILY_REPORT_IDX2 ON PREGEN_DAILY_REPORT
(PDR_REPORT_CODE,PDR_MERCHANT_ID,PDR_COUNTRY_ID,PDR_CURRENCY_ID,PDR_SERVICE_CODE,PDR_REPORT_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );		   
		   
		   

CREATE UNIQUE INDEX PREGEN_DAILY_REPORT_PK ON PREGEN_DAILY_REPORT
(PDR_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE PREGEN_DAILY_REPORT ADD (
  CONSTRAINT PREGEN_DAILY_REPORT_PK
  PRIMARY KEY
  (PDR_ID)
  USING INDEX PREGEN_DAILY_REPORT_PK
  ENABLE VALIDATE);

ALTER TABLE PREGEN_DAILY_REPORT ADD (
  CONSTRAINT PREGEN_DAILY_REPORT_FK01
  FOREIGN KEY (PDR_REPORT_CODE)
  REFERENCES DEF_REPORT_TYPE (DRT_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT PREGEN_DAILY_REPORT_FK02
  FOREIGN KEY (PDR_MERCHANT_ID)
  REFERENCES MERCH_DETAIL (MERCHANT_ID)
  ENABLE VALIDATE,
  CONSTRAINT PREGEN_DAILY_REPORT_FK03
  FOREIGN KEY (PDR_COUNTRY_ID)
  REFERENCES COUNTRY (COUNTRY_CODE)
  ENABLE VALIDATE,
  CONSTRAINT PREGEN_DAILY_REPORT_FK04
  FOREIGN KEY (PDR_CURRENCY_ID)
  REFERENCES DEF_CURRENCY (DC_CCY_ID)
  ENABLE VALIDATE,
  CONSTRAINT PREGEN_DAILY_REPORT_FK05
  FOREIGN KEY (PDR_SERVICE_CODE)
  REFERENCES DEF_SERVICE_CODE (SC_CODE)
  ENABLE VALIDATE,
  CONSTRAINT PREGEN_DAILY_REPORT_FK06
  FOREIGN KEY (PDR_STATUS)
  REFERENCES DEF_PREGEN_RPT_STATUS (DS_TYPE)
  ENABLE VALIDATE);
