ALTER TABLE MMS_STORE_FORWARD
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_STORE_FORWARD CASCADE CONSTRAINTS;

CREATE TABLE MMS_STORE_FORWARD
(
  MSF_TXN_ID           VARCHAR2(16 BYTE),
  MSF_NODE_ID          VARCHAR2(6 BYTE),
  MSF_TO               CHAR(1 BYTE),
  MSF_STATUS           CHAR(1 BYTE),
  MSF_TRY_COUNT        INTEGER,
  MSF_NEXT_TRY         DATE,
  MSF_CREATE_DATETIME  DATE                     DEFAULT sysdate,
  MSF_CREATE_USER      VARCHAR2(20 BYTE),
  MSF_UPDATE_DATETIME  DATE                     DEFAULT sysdate,
  MSF_UPDATE_USER      VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN MMS_STORE_FORWARD.MSF_TO IS '''H'' - Host ''C'' - Client';



CREATE INDEX MMS_STORE_FORWARD_IDX01 ON MMS_STORE_FORWARD
(MSF_STATUS)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX MMS_STORE_FORWARD_PK ON MMS_STORE_FORWARD
(MSF_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_STORE_FORWARD ADD (
  CONSTRAINT MMS_STORE_FORWARD_PK
  PRIMARY KEY
  (MSF_TXN_ID)
  USING INDEX MMS_STORE_FORWARD_PK
  ENABLE VALIDATE);

