OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOReserve
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOReserve.so
SOOBJS = BOReserve.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
