ALTER TABLE MMS_ENTITY_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_ENTITY_TYPE CASCADE CONSTRAINTS;

CREATE TABLE MMS_ENTITY_TYPE
(
  MET_TYPE_CODE         CHAR(3 BYTE),
  MET_TYPE_DESC         VARCHAR2(50 BYTE),
  MET_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  MET_CREATE_USER       VARCHAR2(20 BYTE),
  MET_UPDATE_TIMESTAMP  DATE,
  MET_UPDATE_USER       VARCHAR2(20 BYTE),
  MET_AFFECT_ACT_TYPE   VARCHAR2(10 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MMS_ENTITY_TYPE_PK ON MMS_ENTITY_TYPE
(MET_TYPE_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_ENTITY_TYPE ADD (
  CONSTRAINT MMS_ENTITY_TYPE_PK
  PRIMARY KEY
  (MET_TYPE_CODE)
  USING INDEX MMS_ENTITY_TYPE_PK
  ENABLE VALIDATE);

ALTER TABLE MMS_ENTITY_TYPE ADD (
  CONSTRAINT MMS_ENTITY_TYPE_FK01 
  FOREIGN KEY (MET_AFFECT_ACR_TYPE) 
  REFERENCES MMS_DEF_ACR_TYPE (MDA_CODE)
  ENABLE VALIDATE);
