ALTER TABLE MMS_TXN_CODE
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_TXN_CODE CASCADE CONSTRAINTS;

CREATE TABLE MMS_TXN_CODE
(
  MTC_CODE              CHAR(3 BYTE),
  MTC_PROCESS_TYPE      CHAR(4 BYTE),
  MTC_PROCESS_CODE      CHAR(6 BYTE),
  MTC_DESC              VARCHAR2(50 BYTE),
  MTC_CREATE_USER       VARCHAR2(20 BYTE),
  MTC_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  MTC_UPDATE_USER       VARCHAR2(20 BYTE),
  MTC_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  MTC_FE_DISPLAY        INTEGER                 DEFAULT 1,
  MTC_VOIDABLE          INTEGER                 DEFAULT 0,
  MTC_VOID_CODE         CHAR(3 BYTE),
  MTC_IS_VOID           INTEGER                 DEFAULT 0
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN MMS_TXN_CODE.MTC_FE_DISPLAY IS 'Front End Only, 0 : Not allow to Display, 1: Allow to Display';



CREATE INDEX MMS_TXN_CODE_IDX01 ON MMS_TXN_CODE
(MTC_PROCESS_TYPE, MTC_PROCESS_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX MMS_TXN_CODE_PK ON MMS_TXN_CODE
(MTC_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_TXN_CODE ADD (
  CONSTRAINT MMS_TXN_CODE_PK
  PRIMARY KEY
  (MTC_CODE)
  USING INDEX MMS_TXN_CODE_PK
  ENABLE VALIDATE);

