OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOEmail
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOEmail.so
SOOBJS = BOEmail.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
