OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnWebOnUs2P2X
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnWebOnUs2P2X.so
SOOBJS = TxnWebOnUs2P2X.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
