OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnWebOnUsFEK
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnWebOnUsFEK.so
SOOBJS = TxnWebOnUsFEK.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
