OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnParByUsVOA
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnParByUsVOA.so
SOOBJS = TxnParByUsVOA.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
