OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/RuleOutageNote
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBRuleOutageNote.so
SOOBJS =  RuleOutageNote.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
