ALTER TABLE TEST_BATCHJOB_TIME DROP PRIMARY KEY CASCADE;

DROP TABLE TEST_BATCHJOB_TIME CASCADE CONSTRAINTS;

CREATE TABLE TEST_BATCHJOB_TIME
(
	BT_JOB_ID		VARCHAR2(20 BYTE)	NOT NULL,
	BT_SEQ			INTEGER			DEFAULT 0,
	BT_TYPE			CHAR(1 BYTE)		NOT NULL,
	BT_FIX_MIN		CHAR(2 BYTE)		DEFAULT '**'	NOT NULL,
	BT_FIX_HOUR		CHAR(2 BYTE)		DEFAULT '**'	NOT NULL,
	BT_FIX_DAY		CHAR(2 BYTE)		DEFAULT '**'	NOT NULL,
	BT_FIX_MONTH		CHAR(2 BYTE)		DEFAULT '**'	NOT NULL,
	BT_FIX_DOW		CHAR(1 BYTE)		DEFAULT '*',
	BT_PER_MIN		INTEGER			DEFAULT 0,
	BT_PER_HOUR		INTEGER			DEFAULT 0,
	BT_PER_DAY		INTEGER			DEFAULT 0,
	BT_DISABLED		INTEGER			DEFAULT 0	NOT NULL,
	BT_CREATE_USER		VARCHAR2(20 BYTE)	DEFAULT NULL,
	BT_CREATE_TIMESTAMP	DATE			DEFAULT sysdate	NOT NULL,
	BT_UPDATE_USER		VARCHAR2(20 BYTE)	DEFAULT NULL,
	BT_UPDATE_TIMESTAMP	DATE			DEFAULT sysdate	NOT NULL
)
TABLESPACE USER_DATA
PCTUSED		0
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE		(
			INITIAL		64K
			NEXT		1M
			MINEXTENTS	1
			MAXEXTENTS	UNLIMITED
			PCTINCREASE	0
			BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;

COMMENT ON COLUMN TEST_BATCHJOB_TIME.BT_TYPE IS '''F'' - Fixed;  ''P'' - Periodically';

CREATE UNIQUE INDEX TEST_BATCHJOB_TIME_PK ON TEST_BATCHJOB_TIME
(BT_JOB_ID, BT_SEQ)
LOGGING
TABLESPACE USER_IDX
PCTFREE		10
INITRANS	2
MAXTRANS	255
STORAGE		(
			INITIAL		64K
			NEXT		1M
			MINEXTENTS	1
			MAXEXTENTS	UNLIMITED
			PCTINCREASE	0
			BUFFER_POOL	DEFAULT
		);

ALTER TABLE TEST_BATCHJOB_TIME ADD 
(
	CONSTRAINT TEST_BATCHJOB_TIME_PK
	PRIMARY KEY
	(BT_JOB_ID, BT_SEQ)
	USING INDEX TEST_BATCHJOB_TIME_PK
	ENABLE VALIDATE
);

ALTER TABLE TEST_BATCHJOB_TIME ADD
(
	CONSTRAINT TEST_BATCHJOB_TIME_FK01
	FOREIGN KEY
	(BT_JOB_ID)
	REFERENCES TEST_BATCHJOB_LIST (BL_JOB_ID)
	ENABLE VALIDATE
);
