ALTER TABLE CUSTOMER_GROUP_RULES
 DROP PRIMARY KEY CASCADE;

DROP TABLE CUSTOMER_GROUP_RULES CASCADE CONSTRAINTS;

CREATE TABLE CUSTOMER_GROUP_RULES
(
  CGR_MERCHANT_ID       VARCHAR2(15 BYTE),
  CGR_GROUP_CODE        VARCHAR2(10 BYTE),
  CGR_FROM_GROUP_CODE   VARCHAR2(10 BYTE),
  CGR_DISABLED          INTEGER                 DEFAULT 0,
  CGR_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  CGR_CREATE_USER       VARCHAR2(20 BYTE),
  CGR_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  CGR_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CUSTOMER_GROUP_RULES_PK ON CUSTOMER_GROUP_RULES
(CGR_MERCHANT_ID, CGR_GROUP_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE CUSTOMER_GROUP_RULES ADD (
  CONSTRAINT CUSTOMER_GROUP_RULES_PK
  PRIMARY KEY
  (CGR_MERCHANT_ID, CGR_GROUP_CODE)
  USING INDEX CUSTOMER_GROUP_RULES_PK
  ENABLE VALIDATE);

ALTER TABLE CUSTOMER_GROUP_RULES ADD (
  CONSTRAINT CUSTOMER_GROUP_RULES_FK01 
  FOREIGN KEY (CGR_MERCHANT_ID) 
  REFERENCES MERCH_DETAIL (MERCHANT_ID)
  ENABLE VALIDATE);

