OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLSmsTxnLog
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLSmsTxnLog.so
SOOBJS =  OLSmsTxnLog.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
