OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLPspCosts
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLPspCosts.so
SOOBJS =  OLPspCosts.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
