ALTER TABLE OL_TXN_ENGINE_STATUS_RULE
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_TXN_ENGINE_STATUS_RULE CASCADE CONSTRAINTS;

CREATE TABLE OL_TXN_ENGINE_STATUS_RULE
(
  ESR_RULE_ID           INTEGER,
  ESR_STATUS            CHAR(1 BYTE),
  ESR_AR_IND            CHAR(1 BYTE),
  ESR_SUB_STATUS        CHAR(3 BYTE),
  ESR_RECON_STATUS      CHAR(1 BYTE),
  ESR_CLASSIFIED_STATUS   CHAR(1 BYTE),
  ESR_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  ESR_CREATE_USER       VARCHAR2(20 BYTE),
  ESR_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  ESR_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_TXN_ENGINE_STATUS_RULE_PK ON OL_TXN_ENGINE_STATUS_RULE
(ESR_RULE_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_TXN_ENGINE_STATUS_RULE ADD (
  CONSTRAINT OL_TXN_ENGINE_STATUS_RULE_PK
  PRIMARY KEY
  (ESR_RULE_ID)
  USING INDEX OL_TXN_ENGINE_STATUS_RULE_PK
  ENABLE VALIDATE);

ALTER TABLE OL_TXN_ENGINE_STATUS_RULE ADD (
  CONSTRAINT OL_TXN_ENGINE_STATUS_RULE_FK01 
  FOREIGN KEY (ESR_RECON_STATUS) 
  REFERENCES OL_DEF_RECON_STATUS (RS_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OL_TXN_ENGINE_STATUS_RULE_FK02 
  FOREIGN KEY (ESR_CLASSIFY_STATUS) 
  REFERENCES OL_DEF_CLASSIFIED_STATUS (CS_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OL_TXN_ENGINE_STATUS_RULE_FK03 
  FOREIGN KEY (ESR_SUB_STATUS) 
  REFERENCES DEF_SUB_STATUS (DS_SUB_STATUS)
  ENABLE VALIDATE);

