OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLBaidIntraLogGen
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLBaidIntraLogGen.so
SOOBJS = OLBaidIntraLogGen.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)

