ALTER TABLE OL_TXN_RELATION
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_TXN_RELATION CASCADE CONSTRAINTS;

CREATE TABLE OL_TXN_RELATION
(
  OTR_PARTY_TYPE         CHAR(1 BYTE),
  OTR_P1_TXN_ID          VARCHAR2(16 BYTE),
  OTR_P2_TXN_ID          VARCHAR2(16 BYTE),
  OTR_TXN_LEVEL          CHAR(1 BYTE),
  OTR_RELATION_TYPE      CHAR(1 BYTE),
  OTR_RELATION_TIMESTAMP TIMESTAMP(6),
  OTR_CREATE_TIMESTAMP   DATE                    DEFAULT sysdate,
  OTR_UPDATE_TIMESTAMP   DATE                    DEFAULT sysdate,
  OTR_CREATE_USER        VARCHAR2(20 BYTE),
  OTR_UPDATE_USER        VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX OL_TXN_RELATION_IDX01 ON OL_TXN_RELATION
(OTR_PARTY_TYPE, OTR_TXN_LEVEL, OTR_RELATION_TYPE, OTR_P1_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX OL_TXN_RELATION_IDX02 ON OL_TXN_RELATION
(OTR_PARTY_TYPE, OTR_TXN_LEVEL, OTR_RELATION_TYPE, OTR_P2_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX OL_TXN_RELATION_PK ON OL_TXN_RELATION
(OTR_PARTY_TYPE, OTR_P1_TXN_ID, OTR_P2_TXN_ID, OTR_TXN_LEVEL, OTR_RELATION_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_TXN_RELATION ADD (
  CONSTRAINT OL_TXN_RELATION_PK
  PRIMARY KEY
  (OTR_PARTY_TYPE, OTR_P1_TXN_ID, OTR_P2_TXN_ID, OTR_TXN_LEVEL, OTR_RELATION_TYPE)
  USING INDEX OL_TXN_RELATION_PK
  ENABLE VALIDATE);

ALTER TABLE OL_TXN_RELATION ADD (
  CONSTRAINT OL_TXN_RELATION_FK01 
  FOREIGN KEY (OTR_PARTY_TYPE) 
  REFERENCES DEF_PARTY_TYPE (DP_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OL_TXN_RELATION_FK02 
  FOREIGN KEY (OTR_TXN_LEVEL) 
  REFERENCES OL_DEF_TXN_LEVEL (OTL_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OL_TXN_RELATION_FK03 
  FOREIGN KEY (OTR_RELATION_TYPE) 
  REFERENCES OL_DEF_RELATION_TYPE (ORT_TYPE)
  ENABLE VALIDATE);

