OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLTxnAckLog
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLTxnAckLog.so
SOOBJS =  OLTxnAckLog.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
