OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOCustomerGroup
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOCustomerGroup.so
SOOBJS = BOCustomerGroup.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
