ALTER TABLE EMAIL_FUNCT
 DROP PRIMARY KEY CASCADE;

DROP TABLE EMAIL_FUNCT CASCADE CONSTRAINTS;

CREATE TABLE EMAIL_FUNCT
(
  EF_FUNCT             VARCHAR2(15 BYTE),
  EF_DESC              VARCHAR2(100 BYTE),
  EF_FE_DISPALY        INTEGER            DEFAULT 0,
  EF_OFL_FE_DISPALY    INTEGER            DEFAULT 0,
  EF_CREATE_USER       VARCHAR2(20 BYTE),
  EF_UPDATE_USER       VARCHAR2(20 BYTE),
  EF_CREATE_TIMESTAMP  DATE               DEFAULT SYSDATE,
  EF_UPDATE_TIMESTAMP  DATE               DEFAULT SYSDATE
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX EMAIL_FUNCT_PK ON EMAIL_FUNCT
(EF_FUNCT)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE EMAIL_FUNCT ADD (
  CONSTRAINT EMAIL_FUNCT_PK
  PRIMARY KEY
  (EF_FUNCT)
  USING INDEX EMAIL_FUNCT_PK
  ENABLE VALIDATE);

