ALTER TABLE OL_DEF_EMAIL_NOTIFY_FUNCT
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_DEF_EMAIL_NOTIFY_FUNCT CASCADE CONSTRAINTS;

CREATE TABLE OL_DEF_EMAIL_NOTIFY_FUNCT
(
  OEF_FUNCT             VARCHAR2(10 BYTE),
  OEF_FUNCT_DESC        VARCHAR2(50 BYTE),
  OEF_CREATE_USER       VARCHAR2(20 BYTE),
  OEF_UPDATE_USER       VARCHAR2(20 BYTE),
  OEF_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  OEF_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_DEF_EMAIL_NOTIFY_FUNCT_PK ON OL_DEF_EMAIL_NOTIFY_FUNCT
(OEF_FUNCT)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_DEF_EMAIL_NOTIFY_FUNCT ADD (
  CONSTRAINT OL_DEF_EMAIL_NOTIFY_FUNCT_PK
  PRIMARY KEY
  (OEF_FUNCT)
  USING INDEX OL_DEF_EMAIL_NOTIFY_FUNCT_PK
  ENABLE VALIDATE);
