OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLRuleDepositMatching
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLRuleDepositMatching.so
SOOBJS =  OLRuleDepositMatching.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
