ALTER TABLE CRR_JNL_CHANGE_LOG
 DROP PRIMARY KEY CASCADE;

DROP TABLE CRR_JNL_CHANGE_LOG CASCADE CONSTRAINTS;

CREATE TABLE CRR_JNL_CHANGE_LOG
(
	JNL_CHANGE_LOG_ID         INT NOT NULL,
	JNL_ID										VARCHAR2(16) NOT NULL,
	OLD_VALUE									VARCHAR2(4000 BYTE),
	NEW_VALUE									VARCHAR2(4000 BYTE),
	CHANGE_ACTION							VARCHAR(10 BYTE),
	JNL_STATUS								CHAR(1),
	CHANGE_USER								VARCHAR2(20 BYTE),
	CREATE_TIMESTAMP          DATE	DEFAULT SYSDATE,
	CREATE_USER               VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX CRR_JNL_CHANGE_LOG_PK ON CRR_JNL_CHANGE_LOG
(JNL_CHANGE_LOG_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX CRR_JNL_CHANGE_LOG_IDX01 ON CRR_JNL_CHANGE_LOG
(JNL_ID)
LOGGING
TABLESPACE USER_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

ALTER TABLE CRR_JNL_CHANGE_LOG ADD (
  CONSTRAINT CRR_JNL_CHANGE_LOG_PK
  PRIMARY KEY
  (JNL_CHANGE_LOG_ID)
  USING INDEX CRR_JNL_CHANGE_LOG_PK);
  
ALTER TABLE CRR_JNL_CHANGE_LOG ADD (
  CONSTRAINT CRR_JNL_CHANGE_LOG_FK01 
  FOREIGN KEY (JNL_ID) 
  REFERENCES CRR_JNL_HEADER (JNL_ID));

