OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmsTxnCodeMap
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmsTxnCodeMap.so
SOOBJS =  MmsTxnCodeMap.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
