OBJHOME=$(HOME)/obj/BATCH
#OBJHOME=$(HOME)/src/batch/migration/test_date
BATCHEXE=test_misc2.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o test_misc2.o 
#
#
# Include the Common Rules
#
#

include ../../Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
