ALTER TABLE MI_TXN_LOG
 DROP PRIMARY KEY CASCADE;

DROP TABLE MI_TXN_LOG CASCADE CONSTRAINTS;

CREATE TABLE MI_TXN_LOG
(
  TL_TXN_ID            VARCHAR2(16 BYTE),
  TL_CREATE_TIMESTAMP  DATE,
  TL_UPDATE_TIMESTAMP  DATE,
  TL_CREATE_USER       VARCHAR2(20 BYTE),
  TL_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MI_TXN_LOG_PK ON MI_TXN_LOG
(TL_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MI_TXN_LOG ADD (
  CONSTRAINT MI_TXN_LOG_PK
  PRIMARY KEY
  (TL_TXN_ID)
  USING INDEX MI_TXN_LOG_PK
  ENABLE VALIDATE);

ALTER TABLE MI_TXN_LOG ADD (
  CONSTRAINT MI_TXN_LOG_FK01 
  FOREIGN KEY (TL_TXN_ID) 
  REFERENCES TXN_HEADER (TH_TXN_ID)
  ENABLE VALIDATE);

