ALTER TABLE DEF_TXN_SUB_STATUS_MAP
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_TXN_SUB_STATUS_MAP CASCADE CONSTRAINTS;

CREATE TABLE DEF_TXN_SUB_STATUS_MAP
(
  DSM_TXN_CODE          CHAR(3 BYTE),
  DSM_SUB_STATUS        CHAR(3 BYTE),
  DSM_CREATE_USER       VARCHAR2(20 BYTE),
  DSM_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  DSM_UPDATE_USER       VARCHAR2(20 BYTE),
  DSM_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEF_TXN_SUB_STATUS_MAP_PK ON DEF_TXN_SUB_STATUS_MAP
(DSM_TXN_CODE, DSM_SUB_STATUS)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_TXN_SUB_STATUS_MAP ADD (
  CONSTRAINT DEF_TXN_SUB_STATUS_MAP_PK
  PRIMARY KEY
  (DSM_TXN_CODE, DSM_SUB_STATUS)
  USING INDEX DEF_TXN_SUB_STATUS_MAP_PK
  ENABLE VALIDATE);

