OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/CrrRulePosting
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBCrrRulePosting.so
SOOBJS =  CrrRulePosting.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
