ALTER TABLE OL_TXN_DEPOSIT_HOLD_LOG
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_TXN_DEPOSIT_HOLD_LOG CASCADE CONSTRAINTS;

CREATE TABLE OL_TXN_DEPOSIT_HOLD_LOG
(
  OTDH_TXN_ID             VARCHAR2(16 BYTE),
  OTDH_EXEC_SEQ           INTEGER,
  OTDH_TXN_HOLD_IND       INTEGER,
  OTDH_STAT_TXN_ID        VARCHAR2(16 BYTE),
  OTDH_HOLD_RESULT        INTEGER,
  OTDH_REMARK             VARCHAR2(255 BYTE),
  OTDH_CREATE_USER        VARCHAR2(20 BYTE),
  OTDH_CREATE_TIMESTAMP   DATE                   DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_TXN_DEPOSIT_HOLD_LOG_PK ON OL_TXN_DEPOSIT_HOLD_LOG
(OTDH_TXN_ID, OTDH_EXEC_SEQ)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX OL_TXN_DEPOSIT_HOLD_LOG_IDX01 ON OL_TXN_DEPOSIT_HOLD_LOG
(OTDH_STAT_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_TXN_DEPOSIT_HOLD_LOG ADD (
  CONSTRAINT OL_TXN_DEPOSIT_HOLD_LOG_PK
  PRIMARY KEY
  (OTDH_TXN_ID, OTDH_EXEC_SEQ)
  USING INDEX OL_TXN_DEPOSIT_HOLD_LOG_PK
  ENABLE VALIDATE);

ALTER TABLE OL_TXN_DEPOSIT_HOLD_LOG ADD (
  CONSTRAINT OL_TXN_DEPOSIT_HOLD_LOG_FK01 
  FOREIGN KEY (OTDH_TXN_ID) 
  REFERENCES OL_TXN_HEADER (OTH_TXN_ID)
  ENABLE VALIDATE);

