


CREATE TABLE OL_PAYOUT_API_MERCH_MAP
(
  OAM_MERCHANT_ID             VARCHAR2(15 BYTE),
  OAM_SUPPORT_API             NUMBER(1)         DEFAULT 0                     NOT NULL,
  OAM_PAYPUT_GRP_ALLOW_EMPTY  NUMBER(1)         DEFAULT 0                     NOT NULL,
  OAM_CREATE_TIMESTAMP        DATE              DEFAULT sysdate               NOT NULL,
  OAM_CREATE_USER             VARCHAR2(20 BYTE),
  OAM_UPDATE_TIMESTAMP        DATE              DEFAULT sysdate               NOT NULL,
  OAM_UPDATE_USER             VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX OL_PAYOUT_API_MERCH_MAP_PK ON OL_PAYOUT_API_MERCH_MAP
(OAM_MERCHANT_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE OL_PAYOUT_API_MERCH_MAP ADD (
  CONSTRAINT OL_PAYOUT_API_MERCH_MAP_PK
  PRIMARY KEY
  (OAM_MERCHANT_ID)
  USING INDEX OL_PAYOUT_API_MERCH_MAP_PK
  ENABLE VALIDATE);
