ALTER TABLE PAR_DSP_ID_MAP
 DROP PRIMARY KEY CASCADE;

DROP TABLE PAR_DSP_ID_MAP CASCADE CONSTRAINTS;

CREATE TABLE PAR_DSP_ID_MAP
(
  DI_TXN_NMB           VARCHAR2(16 BYTE),
  DI_ORDER_ID          VARCHAR2(50 BYTE),
  DI_CREATE_TIMESTAMP  DATE,
  DI_CREATE_USER       VARCHAR2(20 BYTE),
  DI_UPDATE_TIMESTAMP  DATE,
  DI_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PAR_DSP_ID_MAP_PK ON PAR_DSP_ID_MAP
(DI_TXN_NMB)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PAR_DSP_ID_MAP ADD (
  CONSTRAINT PAR_DSP_ID_MAP_PK
  PRIMARY KEY
  (DI_TXN_NMB)
  USING INDEX PAR_DSP_ID_MAP_PK
  ENABLE VALIDATE);

