ALTER TABLE OL_DEPOSIT_MATCH_PAIR
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_DEPOSIT_MATCH_PAIR CASCADE CONSTRAINTS;

CREATE TABLE OL_DEPOSIT_MATCH_PAIR
(
  ODMP_STMT_TXN_ID        VARCHAR2(16 BYTE),
  ODMP_MERCH_TXN_ID       VARCHAR2(16 BYTE),
  ODMP_MERCH_ID           VARCHAR2(15 BYTE),
  ODMP_CREATE_TIMESTAMP   DATE                  DEFAULT sysdate,
  ODMP_CREATE_USER        VARCHAR2(20 BYTE),
  ODMP_UPDATE_TIMESTAMP   DATE                  DEFAULT sysdate,
  ODMP_UPDATE_USER        VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_DEPOSIT_MATCH_PAIR_PK ON OL_DEPOSIT_MATCH_PAIR
(ODMP_STMT_TXN_ID, ODMP_MERCH_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_DEPOSIT_MATCH_PAIR ADD (
  CONSTRAINT OL_DEPOSIT_MATCH_PAIR_PK
  PRIMARY KEY
  (ODMP_STMT_TXN_ID, ODMP_MERCH_TXN_ID)
  USING INDEX OL_DEPOSIT_MATCH_PAIR_PK
  ENABLE VALIDATE);

ALTER TABLE OL_DEPOSIT_MATCH_PAIR ADD (
  CONSTRAINT OL_DEPOSIT_MATCH_PAIR_FK01 
  FOREIGN KEY (ODMP_STMT_TXN_ID) 
  REFERENCES OL_TXN_HEADER (OTH_TXN_ID)
  ENABLE VALIDATE,
  CONSTRAINT OL_DEPOSIT_MATCH_PAIR_FK02 
  FOREIGN KEY (ODMP_MERCH_TXN_ID) 
  REFERENCES OL_TXN_HEADER (OTH_TXN_ID)
  ENABLE VALIDATE);

