ALTER TABLE SKIP_ACR_RULE
 DROP PRIMARY KEY CASCADE;

DROP TABLE SKIP_ACR_RULE CASCADE CONSTRAINTS;

CREATE TABLE SKIP_ACR_RULE
(
  SAR_TXN_CODE          CHAR(3 BYTE),
  SAR_PARTY_TYPE        CHAR(1 BYTE),
  SAR_PARTY_ID          VARCHAR2(15 BYTE),
  SAR_DISABLED          INTEGER                 DEFAULT 0,
  SAR_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  SAR_CREATE_USER       VARCHAR2(20 BYTE),
  SAR_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  SAR_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON COLUMN SKIP_ACR_RULE.SAR_PARTY_TYPE IS 'S - Service; M - Merchant; Support 2 levels only';


CREATE UNIQUE INDEX SKIP_ACR_RULE_PK ON SKIP_ACR_RULE
(SAR_TXN_CODE, SAR_PARTY_TYPE, SAR_PARTY_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE SKIP_ACR_RULE ADD (
  CONSTRAINT SKIP_ACR_RULE_PK
  PRIMARY KEY
  (SAR_TXN_CODE, SAR_PARTY_TYPE, SAR_PARTY_ID)
  USING INDEX SKIP_ACR_RULE_PK
  ENABLE VALIDATE);

ALTER TABLE SKIP_ACR_RULE ADD (
  CONSTRAINT SKIP_ACR_RULE_FK01 
  FOREIGN KEY (SAR_TXN_CODE) 
  REFERENCES TXN_CODE (TC_CODE)
  ENABLE VALIDATE);

