
insert into SKIP_ACR_RULE (SAR_TXN_CODE,SAR_PARTY_TYPE,SAR_PARTY_ID,SAR_DISABLED,SAR_CREATE_TIMESTAMP,SAR_CREATE_USER,SAR_UPDATE_TIMESTAMP,SAR_UPDATE_USER)
values ('STR', 'S', 'NBG', 0, sysdate, 'SYSTEM', sysdate, 'SYSTEM');
