CREATE OR REPLACE FUNCTION SP_HIST_PID_BAL_COLLECT(
    IN_END_DATE IN DATE )
RETURN NUMBER IS
	EXP_ERR  EXCEPTION;
	EXP_ERR2 EXCEPTION;
	DATE_ERR EXCEPTION;

	V_CUTOFF_DATE DATE;

	V_NEW_BATCH_ID 		HIST_PID_BAL_BATCH.HB_BATCH_ID%type;
	V_PREV_BATCH_ID		HIST_PID_BAL_BATCH.HB_BATCH_ID%type;
	V_START_DATE         DATE;
	V_ADD_RANGE_END_DATE DATE;

	V_AVA_BALANCE 		TXN_PSP_DETAIL.TP_BAL%type;
	V_TOTAL_FLOAT 		TXN_PSP_DETAIL.TP_TOTAL_FLOAT%type;
	V_LIEN 				TXN_PSP_DETAIL.TP_TOTAL_HOLD%type;

	V_AVA_BALANCE_PREV 	TXN_PSP_DETAIL.TP_BAL%type;
	V_TOTAL_FLOAT_PREV 	TXN_PSP_DETAIL.TP_TOTAL_FLOAT%type;
	V_LIEN_PREV 		TXN_PSP_DETAIL.TP_TOTAL_HOLD%type;

	V_HD_AVAILABLE_BAL 	HIST_PID_BAL_DETAIL.HD_AVAILABLE_BAL%type;
	V_HD_FLOAT_BAL 		HIST_PID_BAL_DETAIL.HD_FLOAT_BAL%type;
	V_HD_LIEN 			HIST_PID_BAL_DETAIL.HD_LIEN%type;

	V_NET_BAL 			HIST_PID_BAL_DETAIL.HD_BAL%type;
	V_HD_BAL 			HIST_PID_BAL_DETAIL.HD_BAL%type;
	V_HD_BAL_HKD 		HIST_PID_BAL_DETAIL.HD_BAL_HKD%type;
	V_HD_BAL_USD		HIST_PID_BAL_DETAIL.HD_BAL_USD%type;
	V_HD_TXN_ID			HIST_PID_BAL_DETAIL.HD_TXN_ID%type;

	V_HKD_RATE 			EXCHANGE_RATE.EX_MED_ASK%type;
	V_USD_RATE 			EXCHANGE_RATE.EX_MED_ASK%type;
	V_COUNT_NO number;
	V_COUNT_NO2 number;

BEGIN
-- DBMS_OUTPUT.PUT_LINE('>>> START [HIST_PID_BAL_COLLECT] <<<');
-- DBMS_OUTPUT.PUT_LINE('--> Input Date: '|| TO_CHAR(IN_END_DATE, 'YYYY-MM-DD HH24:MI') );
	SELECT
	      	count(*)
        INTO
	      	V_COUNT_NO2
        FROM  HIST_RPT_CONFIG
        WHERE HR_RPT_CODE = 'PID_BAL';

        IF SQL % ROWCOUNT != 1 THEN
	      	raise EXP_ERR2;
        END IF;
	
	
	IF V_COUNT_NO2 > 0 THEN
		SELECT
		      HR_CUTOFF_DATE
		INTO
		      V_CUTOFF_DATE
		FROM HIST_RPT_CONFIG
		WHERE HR_RPT_CODE = 'PID_BAL';

		IF SQL % ROWCOUNT != 1 THEN
			raise EXP_ERR2;
		END IF ;
	ELSE
	       V_CUTOFF_DATE :=  IN_END_DATE - 1 ;
	END IF ;
	
-- DBMS_OUTPUT.PUT_LINE('--> Cutoff Date: '|| V_CUTOFF_DATE );

-- Find Prev Batch ID and current batch start date/time
	SELECT HB_BATCH_ID,
	       HB_END_DATE
	INTO V_PREV_BATCH_ID,
	     V_START_DATE
	FROM
	(
		SELECT HB_BATCH_ID,
		       HB_END_DATE,
		       ROW_NUMBER() OVER (PARTITION BY HB_DISABLED ORDER BY HB_END_DATE DESC) RN
		FROM HIST_PID_BAL_BATCH
		WHERE HB_DISABLED = 0
	)
	WHERE RN = 1;
	
	IF SQL % ROWCOUNT != 1 THEN
	  raise EXP_ERR2;
	END IF ;
	
	V_START_DATE := V_START_DATE + 1/24/60;
-- DBMS_OUTPUT.PUT_LINE('--> Start Date: '|| V_START_DATE );
-- DBMS_OUTPUT.PUT_LINE('--> End Date: '|| IN_END_DATE );

-- only look forward
	IF IN_END_DATE < V_START_DATE THEN
		raise DATE_ERR;
	END IF;
-- DBMS_OUTPUT.PUT_LINE('xxxx');

-- New Batch ID
	SELECT MAX(HB_BATCH_ID) + 1
	INTO V_NEW_BATCH_ID
	FROM HIST_PID_BAL_BATCH;
-- DBMS_OUTPUT.PUT_LINE('--> New Batch ID: ' || V_NEW_BATCH_ID );
-- DBMS_OUTPUT.PUT_LINE('--> Previous Batch ID: ' || V_PREV_BATCH_ID );

-- Add 1 mins to end times
	V_ADD_RANGE_END_DATE := IN_END_DATE + 1/24/60;
-- DBMS_OUTPUT.PUT_LINE('--> Add 1 mins end date: ' || V_ADD_RANGE_END_DATE );

-- Insert New Batch
	INSERT
	INTO HIST_PID_BAL_BATCH
	(
		HB_BATCH_ID,
		HB_START_DATE,
		HB_END_DATE,
		HB_DISABLED,
		HB_CREATE_TIMESTAMP,
		HB_CREATE_USER
	)
	VALUES
	(
		V_NEW_BATCH_ID,
		V_START_DATE,
		IN_END_DATE,
		0,
		SYSDATE,
		'SYSTEM'
	);
	
	IF SQL % ROWCOUNT != 1 THEN
		raise EXP_ERR;
	END IF ;
-- DBMS_OUTPUT.PUT_LINE('--> Insert New Batch : OK');

-- Find PSP Last Txn from start times to end times
	FOR X IN
	(
		SELECT
		     	TXN_ID ,
		     	PID_ID , 
		     	TXN_CCY , 
		     	APPROVAL_TIMESTAMP
		FROM (
			SELECT
		  		TXN_ID ,
		  		PID_ID , 
		  		TXN_CCY , 
		  		APPROVAL_TIMESTAMP ,
		  		ROW_NUMBER() OVER ( PARTITION BY PID_ID , TXN_CCY ORDER BY APPROVAL_TIMESTAMP DESC ) RN
		  	FROM (
		  		SELECT
		  			TXN_ID ,
		  			PID_ID , 
		  			TXN_CCY , 
		  			APPROVAL_TIMESTAMP
		  		FROM (
		  			  SELECT
		  				TH_TXN_ID	AS TXN_ID ,
		  				TP_PSP_ID	AS PID_ID ,
		  				TP_TXN_CCY	AS TXN_CCY ,
		  				TH_APPROVAL_TIMESTAMP AS APPROVAL_TIMESTAMP ,
		  				ROW_NUMBER() OVER ( PARTITION BY TP_PSP_ID, TP_TXN_CCY ORDER BY TH_APPROVAL_TIMESTAMP DESC ) RN
		  			  FROM	TXN_PSP_DETAIL ,
		  			        TXN_HEADER
		  			  WHERE  TH_TXN_ID = TP_TXN_ID
		  			  AND TH_AR_IND	= 'A'
		  			  AND TH_APPROVAL_TIMESTAMP >= CAST(V_START_DATE AS TIMESTAMP)
		  			  AND TH_APPROVAL_TIMESTAMP  < CAST(V_ADD_RANGE_END_DATE AS TIMESTAMP)
		  			  AND TH_TXN_CODE <> 'PBU'
		  			  AND TP_TXN_CCY IS NOT NULL
		  			  AND TP_PSP_ID IS NOT NULL
		  			  AND TP_BAL IS NOT NULL
		  			  ORDER BY TH_APPROVAL_TIMESTAMP DESC
		  		)
		  		WHERE RN = 1
		  		UNION
		  		SELECT
		  			HD_TXN_ID	AS TXN_ID ,
		  			HD_PID_ID	AS PID_ID ,
		  			HD_CCY		AS TXN_CCY ,
		  			TH_APPROVAL_TIMESTAMP	AS APPROVAL_TIMESTAMP
		  		FROM HIST_PID_BAL_DETAIL ,
		  		     TXN_HEADER
		  		WHERE TH_TXN_ID = HD_TXN_ID
		  		AND HD_BATCH_ID = V_PREV_BATCH_ID
		  	)
			ORDER BY APPROVAL_TIMESTAMP DESC
		)
		WHERE RN = 1
	)
	LOOP
-- DBMS_OUTPUT.PUT_LINE('--> PID_ID: [' || X.PID_ID || '] SERVICE_CODE: [' || X.SERVICE_CODE || ']  TXN_CCY: [' || X.TXN_CCY || '] TXN_ID : [' || X.TXN_ID||'] COUNTRY : [' || X.COUNTRY||'] ');

		IF X.TXN_ID IS NOT NULL THEN
-- DBMS_OUTPUT.PUT_LINE('--> Txn Bal');
--  Txn Bal

			SELECT
				 NVL(TP_BAL, 0.00) - NVL(TP_TOTAL_HOLD, 0.00) AVA_BALANCE
				,NVL(TP_TOTAL_FLOAT,0.00) TOTAL_FLOAT
				,NVL(TP_TOTAL_HOLD, 0.00) LIEN
			 INTO
				V_AVA_BALANCE ,
				V_TOTAL_FLOAT ,
				V_LIEN
			FROM  TXN_PSP_DETAIL
			WHERE TP_TXN_ID  = X.TXN_ID;

-- DBMS_OUTPUT.PUT_LINE('--> V_AVA_BALANCE: [' || V_AVA_BALANCE || '] V_TOTAL_FLOAT: [' || V_TOTAL_FLOAT ||'] V_LIEN: [' || V_LIEN ||'] ');

-- DBMS_OUTPUT.PUT_LINE('--> Find last BATCH ID : [' ||V_PREV_BATCH_ID || ']');

			SELECT count(*) AS COUNT_NO INTO V_COUNT_NO
			FROM HIST_PID_BAL_DETAIL
			WHERE HD_PID_ID = X.PID_ID
			AND HD_CCY = X.TXN_CCY
        		AND HD_BATCH_ID = V_PREV_BATCH_ID;

-- DBMS_OUTPUT.PUT_LINE('--> V_COUNT_NO : [' ||V_COUNT_NO || ']');

			IF V_COUNT_NO > 0 THEN
				-- Prev Batch Bal
				 SELECT
					HD_TXN_ID ,
					NVL(HD_AVAILABLE_BAL, 0.00) AS HD_AVAILABLE_BAL ,
					NVL(HD_FLOAT_BAL, 0.00) AS HD_FLOAT_BAL ,
					NVL(HD_LIEN, 0.00) AS HD_LIEN ,
					NVL(HD_BAL, 0.00) AS HD_BAL ,
					NVL(HD_BAL_HKD, 0.00) AS HD_BAL_HKD ,
					NVL(HD_BAL_USD, 0.00) AS HD_BAL_USD
				 INTO
					V_HD_TXN_ID,
					V_HD_AVAILABLE_BAL ,
					V_HD_FLOAT_BAL ,
					V_HD_LIEN ,
					V_HD_BAL,
					V_HD_BAL_HKD,
					V_HD_BAL_USD
				FROM HIST_PID_BAL_DETAIL
				WHERE HD_PID_ID = X.PID_ID
				AND HD_CCY = X.TXN_CCY
				AND HD_BATCH_ID = V_PREV_BATCH_ID;

				IF V_HD_TXN_ID IS NOT NULL THEN
					SELECT
						NVL(TP_BAL, 0.00) - NVL(TP_TOTAL_HOLD, 0.00) AVA_BALANCE
						,NVL(TP_TOTAL_FLOAT, 0.00) TOTAL_FLOAT
						,NVL(TP_TOTAL_HOLD, 0.00) LIEN
					INTO
						V_AVA_BALANCE_PREV ,
						V_TOTAL_FLOAT_PREV ,
						V_LIEN_PREV
					FROM  TXN_PSP_DETAIL
					WHERE TP_TXN_ID = V_HD_TXN_ID;
				ELSE
					V_AVA_BALANCE_PREV := 0.00;
					V_TOTAL_FLOAT_PREV := 0.00;
					V_LIEN_PREV := 0.00;
				END IF ;

			ELSE
-- DBMS_OUTPUT.PUT_LINE('--> No HIST Detail ');
				V_AVA_BALANCE_PREV := 0.00;
				V_TOTAL_FLOAT_PREV := 0.00;
				V_LIEN_PREV := 0.00;
				V_HD_AVAILABLE_BAL := 0.00;
				V_HD_FLOAT_BAL := 0.00;
				V_HD_LIEN := 0.00;
				V_HD_TXN_ID := 0;
				V_HD_BAL := 0.00;
				V_HD_BAL_HKD := 0.00;
				V_HD_BAL_USD := 0.00;
		
			END IF ;

-- DBMS_OUTPUT.PUT_LINE('--> V_AVA_BALANCE_PREV: [' || V_AVA_BALANCE_PREV || '] V_TOTAL_FLOAT_PREV: [' || V_TOTAL_FLOAT_PREV ||'] V_LIEN_PREV: [' || V_LIEN_PREV ||'] ');

-- DBMS_OUTPUT.PUT_LINE('--> GET Rate');
-- HKD Rate , USD Rate
			SELECT
				RATE_HKD_TBL.RATE AS HKD_RATE,
				RATE_USD_TBL.RATE AS USD_RATE
			INTO
				V_HKD_RATE,
				V_USD_RATE
			FROM
			(
				SELECT
					EX_MED_ASK AS RATE ,
					EX_TO_CCY_ID
				FROM (
					SELECT EX_FROM_CCY_ID
						,EX_TO_CCY_ID
						,EX_MED_ASK
						,ROW_NUMBER() OVER (
							PARTITION BY EX_FROM_CCY_ID
							,EX_TO_CCY_ID ORDER BY EX_EFFECT_DATE DESC
						) XX
					FROM EXCHANGE_RATE
					WHERE EX_EFFECT_DATE < CAST(V_ADD_RANGE_END_DATE AS TIMESTAMP)
				)
				WHERE XX = 1
				AND EX_TO_CCY_ID = 'HKD'
				AND EX_FROM_CCY_ID = X.TXN_CCY
			) RATE_HKD_TBL
			INNER JOIN (
				SELECT
					EX_MED_ASK AS RATE ,
					EX_FROM_CCY_ID
				FROM (
					SELECT EX_FROM_CCY_ID
						,EX_TO_CCY_ID
						,EX_MED_ASK
						,ROW_NUMBER() OVER (
							PARTITION BY EX_FROM_CCY_ID
							,EX_TO_CCY_ID ORDER BY EX_EFFECT_DATE DESC
						) XX
					FROM EXCHANGE_RATE
					WHERE EX_EFFECT_DATE < CAST(V_ADD_RANGE_END_DATE AS TIMESTAMP)
				)
				WHERE XX = 1
				AND EX_FROM_CCY_ID = 'HKD'
				AND EX_TO_CCY_ID = 'USD'
			) RATE_USD_TBL ON RATE_HKD_TBL.EX_TO_CCY_ID = RATE_USD_TBL.EX_FROM_CCY_ID;
		
			IF X.TXN_ID != V_HD_TXN_ID THEN
				V_NET_BAL := (V_AVA_BALANCE - V_AVA_BALANCE_PREV) + (V_TOTAL_FLOAT - V_TOTAL_FLOAT_PREV) + (V_LIEN - V_LIEN_PREV) ;
			ELSE
				V_NET_BAL := 0.00;
			END IF ;

-- DBMS_OUTPUT.PUT_LINE('--> HKD_RATE: [' || V_HKD_RATE || '] USD_RATE: [' || V_USD_RATE ||']');

-- DBMS_OUTPUT.PUT_LINE('--> INSERT ');


-- Check Cut off Time
	  		IF V_CUTOFF_DATE >=  V_ADD_RANGE_END_DATE THEN
	  		      V_AVA_BALANCE_PREV := 0.00;
	  		      V_TOTAL_FLOAT_PREV := 0.00;
	  		      V_LIEN_PREV := 0.00;
	  		      V_HD_AVAILABLE_BAL := 0.00;
	  		      V_HD_FLOAT_BAL := 0.00;
	  		      V_HD_LIEN := 0.00;
	  		      V_HD_TXN_ID := 0;
	  		      V_HD_BAL := 0.00;
	  		      V_HD_BAL_HKD := 0.00;
	  		      V_HD_BAL_USD := 0.00;
	  		      V_HKD_RATE := 0.00;
	  		      V_USD_RATE := 0.00;
	  		      V_NET_BAL := 0.00; 
	  		      V_AVA_BALANCE := 0.00;
	  		      V_TOTAL_FLOAT := 0.00;
	  		      V_LIEN := 0.00;
	  		 END IF;

      			INSERT INTO HIST_PID_BAL_DETAIL (
				HD_BATCH_ID,
				HD_PID_ID, 
				HD_CCY, 
				HD_TXN_ID,
				HD_AVAILABLE_BAL ,
				HD_FLOAT_BAL ,
				HD_LIEN ,
				HD_BAL ,
				HD_BAL_HKD ,
				HD_BAL_HKD_RATE ,
				HD_BAL_USD ,
				HD_BAL_USD_RATE
			) VALUES (
				V_NEW_BATCH_ID,
				X.PID_ID, 
				X.TXN_CCY, 
				X.TXN_ID,
				NVL(V_HD_AVAILABLE_BAL + (V_AVA_BALANCE - V_AVA_BALANCE_PREV), 0.00),
				NVL(V_HD_FLOAT_BAL + (V_TOTAL_FLOAT - V_TOTAL_FLOAT_PREV), 0.00),
				NVL(V_HD_LIEN + (V_LIEN - V_LIEN_PREV), 0.00),
				NVL(V_HD_BAL + V_NET_BAL, 0.00),
				NVL(V_HD_BAL_HKD + (V_NET_BAL * V_HKD_RATE), 0.00),
				V_HKD_RATE,
				NVL(V_HD_BAL_USD + (V_NET_BAL * V_HKD_RATE * V_USD_RATE), 0.00),
				V_USD_RATE
        		);

      			IF SQL % ROWCOUNT != 1 THEN
      				raise EXP_ERR;
      			END IF;
-- DBMS_OUTPUT.PUT_LINE('--> END INSERT ');

		END IF;
	END LOOP;

	COMMIT;
-- DBMS_OUTPUT.PUT_LINE('>>> END [HIST_PID_BAL_COLLECT] <<<');

	RETURN 0;

EXCEPTION
WHEN EXP_ERR THEN
	ROLLBACK;
--DBMS_OUTPUT.PUT_LINE('Error: Insert last txn error!...');
	RETURN 1;
WHEN DATE_ERR THEN
	ROLLBACK;
--DBMS_OUTPUT.PUT_LINE('Error: The latest batch end date larger than input date!');
	RETURN 1;
WHEN EXP_ERR2 THEN
	ROLLBACK;
--DBMS_OUTPUT.PUT_LINE('Error: no record!...');
	RETURN 1;
WHEN OTHERS THEN
	ROLLBACK;
--DBMS_OUTPUT.PUT_LINE('Error: Other error!...');
--DBMS_OUTPUT.PUT_LINE('Error code ' || SQLCODE|| ': ' || SUBSTR(SQLERRM, 1 , 64));
--RAISE_APPLICATION_ERROR( -20201, 'Error code ' || SQLCODE|| ': ' || SUBSTR(SQLERRM, 1 , 64) );
	RETURN 9;
END SP_HIST_PID_BAL_COLLECT;
/
