ALTER TABLE MI_ACTION_LOCK
 DROP PRIMARY KEY CASCADE;

DROP TABLE MI_ACTION_LOCK CASCADE CONSTRAINTS;

CREATE TABLE MI_ACTION_LOCK
(
  MAL_ACTION  VARCHAR2(50 BYTE),
  MAL_FLAG    INTEGER                           DEFAULT 1
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MI_ACTION_LOCK_PK ON MI_ACTION_LOCK
(MAL_ACTION)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MI_ACTION_LOCK ADD (
  CONSTRAINT MI_ACTION_LOCK_PK
  PRIMARY KEY
  (MAL_ACTION)
  USING INDEX MI_ACTION_LOCK_PK
  ENABLE VALIDATE);

