OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnWebOnUs2HCP
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnWebOnUs2HCP.so
SOOBJS = TxnWebOnUs2HCP.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
