OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MiDeliveryOutBatch
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMiDeliveryOutBatch.so
SOOBJS =  MiDeliveryOutBatch.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
