ALTER TABLE RULE_AMOUNT
 DROP PRIMARY KEY CASCADE;

DROP TABLE RULE_AMOUNT CASCADE CONSTRAINTS;

CREATE TABLE RULE_AMOUNT
(
  RA_ID                INTEGER,
  RA_TYPE              CHAR(1 BYTE),
  RA_VALUE             NUMBER(12,5),
  RA_ADD_VALUE         NUMBER(12,2),
  RA_DESC              VARCHAR2(50 BYTE),
  RA_DISABLED          INTEGER                  DEFAULT 0,
  RA_MIN_VALUE         NUMBER(12,2)             DEFAULT 0,
  RA_MAX_VALUE         NUMBER(12,2)             DEFAULT 0,
  RA_CREATE_TIMESTAMP  DATE,
  RA_CREATE_USER       VARCHAR2(20 BYTE),
  RA_UPDATE_TIMESTAMP  DATE,
  RA_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX RULE_AMOUNT_PK ON RULE_AMOUNT
(RA_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE RULE_AMOUNT ADD (
  CONSTRAINT RULE_AMOUNT_PK
  PRIMARY KEY
  (RA_ID)
  USING INDEX RULE_AMOUNT_PK);

ALTER TABLE RULE_AMOUNT ADD (
  CONSTRAINT RULE_AMOUNT_FK01 
  FOREIGN KEY (RA_TYPE) 
  REFERENCES DEF_AMOUNT (DA_TYPE));

