CREATE OR REPLACE FUNCTION SP_MID_BAL_COLLECT_BY_DAY 
RETURN NUMBER IS
  EXP_ERR EXCEPTION; 
BEGIN 
/*
Anonymous block for initiate

DECLARE
  V_INPUT_DATE DATE;
BEGIN
FOR X IN 1..2 LOOP
	SELECT MAX(MB_END_DATE) + 1 
	INTO V_INPUT_DATE	
	FROM MID_HIST_BAL_BATCH
	WHERE MB_DISABLED = 0;

	-- Run Batch Function 
	MID_BAL_COLLECT(V_INPUT_DATE); 
END LOOP;
END;
*/
-- DBMS_OUTPUT.PUT_LINE('>>> START [MID_BAL_COLLECT_BY_DAY] <<<');

-- Run Batch Function 
	RETURN SP_MID_BAL_COLLECT(trunc(sysdate) - 1/24/60); 
-- DBMS_OUTPUT.PUT_LINE('>>> END [MID_BAL_COLLECT_BY_DAY] <<<');

EXCEPTION 
WHEN EXP_ERR THEN
	ROLLBACK;
--DBMS_OUTPUT.PUT_LINE('Error : no record!...');
	RETURN 1;
WHEN OTHERS THEN
	ROLLBACK;
--BMS_OUTPUT.PUT_LINE('Error: Other error!');
--DBMS_OUTPUT.PUT_LINE('Error code ' || SQLCODE|| ': ' || SUBSTR(SQLERRM, 1 , 64));
--RAISE_APPLICATION_ERROR( -20103, 'Error code ' || SQLCODE|| ': ' || SUBSTR(SQLERRM, 1 , 64) );
	RETURN 9;
END SP_MID_BAL_COLLECT_BY_DAY;
/

