OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/CustomerGroupOffsetLog
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBCustomerGroupOffsetLog.so
SOOBJS =  CustomerGroupOffsetLog.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
