ALTER TABLE CUSTOMER_PSP_COUNTERS_HIST 
 DROP PRIMARY KEY CASCADE;

DROP TABLE CUSTOMER_PSP_COUNTERS_HIST CASCADE CONSTRAINTS;

CREATE TABLE CUSTOMER_PSP_COUNTERS_HIST
(
  CCH_CUST_ID	VARCHAR2(10 BYTE),
  CCH_PSP_ID   VARCHAR2(10 BYTE),
  CCH_DATE	   VARCHAR2(8 BYTE),
  CCH_CATEGORY     VARCHAR2(3 BYTE),
  CCH_COUNTER      NUMBER(16,2),
  CCH_CREATE_USER  VARCHAR2(20 BYTE),
  CCH_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  CCH_UPDATE_USER  VARCHAR2(20 BYTE),
  CCH_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CUSTOMER_PSP_COUNTERS_HIST_PK ON CUSTOMER_PSP_COUNTERS_HIST
(CCH_CUST_ID, CCH_PSP_ID, CCH_DATE, CCH_CATEGORY)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE CUSTOMER_PSP_COUNTERS_HIST ADD (
  CONSTRAINT CUSTOMER_PSP_COUNTERS_HIST_PK
  PRIMARY KEY
  (CCH_CUST_ID, CCH_PSP_ID, CCH_DATE, CCH_CATEGORY)
  USING INDEX CUSTOMER_PSP_COUNTERS_HIST_PK
  ENABLE VALIDATE);

