ALTER TABLE CUSTOMER_PSP_COUNTERS
 DROP PRIMARY KEY CASCADE;

DROP TABLE CUSTOMER_PSP_COUNTERS CASCADE CONSTRAINTS;

CREATE TABLE CUSTOMER_PSP_COUNTERS
(
  CPC_CUST_ID	VARCHAR2(10 BYTE),
  CPC_PSP_ID   VARCHAR2(10 BYTE),
  CPC_DATE	   VARCHAR2(8 BYTE),
  CPC_CATEGORY     VARCHAR2(3 BYTE),
  CPC_COUNTER      NUMBER(16,2),
  CPC_CREATE_USER  VARCHAR2(20 BYTE),
  CPC_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  CPC_UPDATE_USER  VARCHAR2(20 BYTE),
  CPC_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CUSTOMER_PSP_COUNTERS_PK ON CUSTOMER_PSP_COUNTERS
(CPC_CUST_ID, CPC_PSP_ID, CPC_DATE, CPC_CATEGORY)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE CUSTOMER_PSP_COUNTERS ADD (
  CONSTRAINT CUSTOMER_PSP_COUNTERS_PK
  PRIMARY KEY
  (CPC_CUST_ID, CPC_PSP_ID, CPC_DATE, CPC_CATEGORY)
  USING INDEX CUSTOMER_PSP_COUNTERS_PK
  ENABLE VALIDATE);

