ALTER TABLE CUSTOMER_GROUP_PROMO_LIST
 DROP PRIMARY KEY CASCADE;

DROP TABLE CUSTOMER_GROUP_PROMO_LIST CASCADE CONSTRAINTS;

CREATE TABLE CUSTOMER_GROUP_PROMO_LIST
(
  CGL_MERCHANT_ID       VARCHAR2(15 BYTE),
  CGL_CUST_ID           VARCHAR2(10 BYTE),
  CGL_FROM_GROUP        VARCHAR2(10 BYTE),
  CGL_TO_GROUP          VARCHAR2(10 BYTE),
  CGL_PROMOTED       	CHAR(1 BYTE),
  CGL_PROMOTE_DATE	VARCHAR2(8 BYTE),
  CGL_PROMOTE_TIMESTAMP DATE,
  CGL_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  CGL_CREATE_USER       VARCHAR2(20 BYTE),
  CGL_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  CGL_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX CUSTOMER_GROUP_PM_LIST_IDX01 ON CUSTOMER_GROUP_PROMO_LIST
(CGL_CUST_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX CUSTOMER_GROUP_PM_LIST_IDX02 ON CUSTOMER_GROUP_PROMO_LIST
(CGL_MERCHANT_ID, CGL_CUST_ID, CGL_PROMOTED)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

CREATE UNIQUE INDEX CUSTOMER_GROUP_PM_LIST_PK ON CUSTOMER_GROUP_PROMO_LIST
(CGL_MERCHANT_ID,CGL_CUST_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE CUSTOMER_GROUP_PROMO_LIST ADD (
  CONSTRAINT CUSTOMER_GROUP_PM_LIST_PK
  PRIMARY KEY
  (CGL_MERCHANT_ID,CGL_CUST_ID)
  USING INDEX CUSTOMER_GROUP_PM_LIST_PK
  ENABLE VALIDATE);



ALTER TABLE CUSTOMER_GROUP_PROMO_LIST ADD (
  CONSTRAINT CUSTOMER_GROUP_PM_LIST_FK01 
  FOREIGN KEY (CGL_MERCHANT_ID) 
  REFERENCES MERCH_DETAIL (MERCHANT_ID)
  ENABLE VALIDATE);

