ALTER TABLE PAYOUT_APPROVE_TMP
 DROP PRIMARY KEY CASCADE;

DROP TABLE PAYOUT_APPROVE_TMP CASCADE CONSTRAINTS;

CREATE TABLE PAYOUT_APPROVE_TMP
(
  PT_ID                INTEGER,
  PT_TXN_ID            VARCHAR2(16 BYTE),
  PT_CREATE_USER       VARCHAR2(20 BYTE),
  PT_UPDATE_USER       VARCHAR2(20 BYTE),
  PT_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  PT_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PAYOUT_APPROVE_TMP_PK ON PAYOUT_APPROVE_TMP
(PT_ID, PT_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PAYOUT_APPROVE_TMP ADD (
  CONSTRAINT PAYOUT_APPROVE_TMP_PK
  PRIMARY KEY
  (PT_ID, PT_TXN_ID)
  USING INDEX PAYOUT_APPROVE_TMP_PK
  ENABLE VALIDATE);

