OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MerchantSettlementDetail
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMerchantSettlementDetail.so
SOOBJS =  MerchantSettlementDetail.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
