ALTER TABLE OL_BAID_INTRA_LOG_GEN 
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_BAID_INTRA_LOG_GEN CASCADE CONSTRAINTS;

CREATE TABLE OL_BAID_INTRA_LOG_GEN 
(
  OALG_BATCH_ID		NUMBER(16), 
  OALG_STMT_TXN_ID	VARCHAR2(16 BYTE), 
  OALG_STATUS		CHAR(1 BYTE), 
  OALG_GEN_TXN_ID_FR	VARCHAR2(16 BYTE), 
  OALG_GEN_TXN_ID_TO	VARCHAR2(16 BYTE), 
  OALG_RET_CODE		NUMBER(8), 
  OALG_CREATE_TIMESTAMP	DATE			DEFAULT sysdate, 
  OALG_CREATE_USER	VARCHAR2(20 BYTE), 
  OALG_UPDATE_TIMESTAMP	DATE			DEFAULT sysdate, 
  OALG_UPDATE_USER	VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA 
PCTUSED     0 
PCTFREE     10 
INITRANS    1 
MAXTRANS    255 
STORAGE     (
             INITIAL          64K 
             NEXT             1M 
             MINEXTENTS       1 
             MAXEXTENTS       UNLIMITED 
             PCTINCREASE      0 
             BUFFER_POOL      DEFAULT
            ) 
LOGGING 
NOCOMPRESS 
NOCACHE 
MONITORING;

CREATE UNIQUE INDEX OL_BAID_INTRA_LOG_GEN_PK ON OL_BAID_INTRA_LOG_GEN 
(OALG_BATCH_ID, OALG_STMT_TXN_ID) 
LOGGING 
TABLESPACE USER_IDX 
PCTFREE     10 
INITRANS    2 
MAXTRANS    255 
STORAGE     (
             INITIAL          64K 
             NEXT             1M 
             MINEXTENTS       1 
             MAXEXTENTS       UNLIMITED 
             PCTINCREASE      0 
             BUFFER_POOL      DEFAULT
            );

CREATE INDEX OL_BAID_INTRA_LOG_GEN_IDX01 ON OL_BAID_INTRA_LOG_GEN 
(OALG_STMT_TXN_ID, OALG_CREATE_TIMESTAMP) 
LOGGING 
TABLESPACE USER_IDX 
PCTFREE     10 
INITRANS    2 
MAXTRANS    255 
STORAGE     (
             INITIAL          64K 
             NEXT             1M 
             MINEXTENTS       1 
             MAXEXTENTS       UNLIMITED 
             PCTINCREASE      0 
             BUFFER_POOL      DEFAULT 
             FLASH_CACHE      DEFAULT 
             CELL_FLASH_CACHE DEFAULT
            ) 
NOPARALLEL;

CREATE INDEX OL_BAID_INTRA_LOG_GEN_IDX02 ON OL_BAID_INTRA_LOG_GEN 
(OALG_GEN_TXN_ID_FR) 
LOGGING 
TABLESPACE USER_IDX 
PCTFREE     10 
INITRANS    2 
MAXTRANS    255 
STORAGE     (
             INITIAL          64K 
             NEXT             1M 
             MINEXTENTS       1 
             MAXEXTENTS       UNLIMITED 
             PCTINCREASE      0 
             BUFFER_POOL      DEFAULT 
             FLASH_CACHE      DEFAULT 
             CELL_FLASH_CACHE DEFAULT
            ) 
NOPARALLEL;

CREATE INDEX OL_BAID_INTRA_LOG_GEN_IDX03 ON OL_BAID_INTRA_LOG_GEN 
(OALG_GEN_TXN_ID_TO) 
LOGGING 
TABLESPACE USER_IDX 
PCTFREE     10 
INITRANS    2 
MAXTRANS    255 
STORAGE     (
             INITIAL          64K 
             NEXT             1M 
             MINEXTENTS       1 
             MAXEXTENTS       UNLIMITED 
             PCTINCREASE      0 
             BUFFER_POOL      DEFAULT 
             FLASH_CACHE      DEFAULT 
             CELL_FLASH_CACHE DEFAULT
            ) 
NOPARALLEL;

ALTER TABLE OL_BAID_INTRA_LOG_GEN ADD (
  CONSTRAINT OL_BAID_INTRA_LOG_GEN_PK 
  PRIMARY KEY 
  (OALG_BATCH_ID, OALG_STMT_TXN_ID) 
  USING INDEX OL_BAID_INTRA_LOG_GEN_PK 
  ENABLE VALIDATE, 
  CONSTRAINT OL_BAID_INTRA_LOG_GEN_UK01 
  UNIQUE (OALG_STMT_TXN_ID) 
  USING INDEX OL_BAID_INTRA_LOG_GEN_IDX01 
  ENABLE VALIDATE);

ALTER TABLE OL_BAID_INTRA_LOG_GEN ADD (
  CONSTRAINT OL_BAID_INTRA_LOG_GEN_FK01 
  FOREIGN KEY (OALG_STATUS) 
  REFERENCES OL_DEF_INTRA_LOG_GEN_STATUS (ODAS_STATUS) 
  ENABLE VALIDATE);
