DROP TYPE CRR_JNL_DATA_TAB;
DROP TYPE CRR_JNL_DATA_REC;

CREATE OR REPLACE TYPE CRR_JNL_DATA_REC IS OBJECT
(
   TXN_DATE               VARCHAR2 (8 BYTE),
   CR_COUNTRY_ID          CHAR (2 BYTE),
   CR_PRODUCT_CODE        CHAR (3 BYTE),
   CR_JNL_TYPE_ID         INTEGER,
   CR_JNL_ENTRY_TYPE_ID   VARCHAR2 (20 BYTE),
   CR_PARTY_TYPE          CHAR (1 BYTE),
   CR_PARTY_ID            VARCHAR (15 BYTE),
   CR_CURRENCY_ID         CHAR (3 BYTE),
   GL_ID                  INTEGER,
   CR_IND                 CHAR (1 BYTE),
   TXN_AMT                NUMBER (14, 2),
   TXN_COUNT              INTEGER,
   TXN_ID                 VARCHAR (16 BYTE)
);
/

CREATE OR REPLACE TYPE CRR_JNL_DATA_TAB IS TABLE OF CRR_JNL_DATA_REC;
/
