OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/PspKeys
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBPspKeys.so
SOOBJS =  PspKeys.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
