DROP TABLE PAYOUT_PRE_GENERATE_DT CASCADE CONSTRAINTS;

CREATE TABLE PAYOUT_PRE_GENERATE_DT
(
  PG_FILE_ID           NUMBER(16)               NOT NULL,
  PG_TXN_ID            VARCHAR2(16 BYTE)        NOT NULL,
  PG_PAYOUT_AMT        NUMBER(12,2)             NOT NULL,
  PG_MULTIPLE_IND      INTEGER                  DEFAULT 0,
  PG_PSP_ID            VARCHAR2(10 BYTE)        NOT NULL,
  PG_DISABLED	       INTEGER			DEFAULT 0,
  PG_GENERATED	       INTEGER			DEFAULT 0,
  PG_CREATE_USER       VARCHAR2(20 BYTE),
  PG_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  PG_UPDATE_USER       VARCHAR2(20 BYTE),
  PG_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
