ALTER TABLE MERCH_LIM_DAILY_CAP_LOG
 DROP PRIMARY KEY CASCADE;

DROP TABLE MERCH_LIM_DAILY_CAP_LOG CASCADE CONSTRAINTS;

CREATE TABLE MERCH_LIM_DAILY_CAP_LOG
(
  MLDCL_MERCHANT_ID       VARCHAR2(15 BYTE)     NOT NULL,
  MLDCL_SERVICE_CODE      CHAR(3 BYTE)          NOT NULL,
  MLDCL_COUNTRY           CHAR(2 BYTE)          NOT NULL,
  MLDCL_LOG_SEQ           INTEGER               DEFAULT 1                     NOT NULL,
  MLDCL_DAILY_CAP         NUMBER(14,2)          DEFAULT 0,
  MLDCL_DISABLED          INTEGER               DEFAULT 0,
  MLDCL_CREATE_USER       VARCHAR2(20 BYTE),
  MLDCL_CREATE_TIMESTAMP  DATE                  DEFAULT sysdate,
  MLDCL_UPDATE_USER       VARCHAR2(20 BYTE),
  MLDCL_UPDATE_TIMESTAMP  DATE                  DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MERCH_LIM_DAILY_CAP_LOG_PK ON MERCH_LIM_DAILY_CAP_LOG
(MLDCL_MERCHANT_ID, MLDCL_SERVICE_CODE, MLDCL_COUNTRY, MLDCL_LOG_SEQ)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MERCH_LIM_DAILY_CAP_LOG ADD (
  CONSTRAINT MERCH_LIM_DAILY_CAP_LOG_PK
  PRIMARY KEY
  (MLDCL_MERCHANT_ID, MLDCL_SERVICE_CODE, MLDCL_COUNTRY, MLDCL_LOG_SEQ)
  USING INDEX MERCH_LIM_DAILY_CAP_LOG_PK
  ENABLE VALIDATE);

