OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/EmailReceiverList
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBEmailReceiverList.so
SOOBJS =  EmailReceiverList.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
