OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLMerchantBucket
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLMerchantBucket.so
SOOBJS =  OLMerchantBucket.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
