


CREATE TABLE OL_AUTO_UPLOAD_ACCT_STATUS
(
  OAUAS_ACCT_TYPE         	VARCHAR2(3 BYTE),
  OAUAS_STATUS_TYPE       	VARCHAR2(2 BYTE),
  OAUAS_CHK_STATUS      	INTEGER,
  OAUAS_ENABLE_CHK_FR_STATUS   	INTEGER,
  OAUAS_ENABLE_CHK_TO_STATUS    INTEGER,
  OAUAS_DISABLE_CHK_FR_STATUS   INTEGER,
  OAUAS_DISABLE_CHK_TO_STATUS   INTEGER,
  OAUAS_DISABLED       	  	INTEGER DEFAULT 0,
  OAUAS_CREATE_TIMESTAMP  	DATE DEFAULT sysdate,
  OAUAS_CREATE_USER       	VARCHAR2(20 BYTE),
  OAUAS_UPDATE_TIMESTAMP  	DATE DEFAULT sysdate,
  OAUAS_UPDATE_USER       	VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_AUTO_UPL_ACCT_STATUS_PK ON OL_AUTO_UPLOAD_ACCT_STATUS
(OAUAS_ACCT_TYPE, OAUAS_STATUS_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_AUTO_UPLOAD_ACCT_STATUS ADD (
  CONSTRAINT OL_AUTO_UPL_ACCT_STATUS_PK
  PRIMARY KEY
  (OAUAS_ACCT_TYPE, OAUAS_STATUS_TYPE)
  USING INDEX OL_AUTO_UPL_ACCT_STATUS_PK
  ENABLE VALIDATE);

ALTER TABLE OL_AUTO_UPLOAD_ACCT_STATUS ADD (
  CONSTRAINT OL_AUTO_UPL_ACCT_STATUS_FK01
  FOREIGN KEY (OAUAS_STATUS_TYPE)
  REFERENCES OL_DEF_ACCT_STATUS (AS_TYPE)
  ENABLE VALIDATE);
