


-- DSI, Active Status
update OL_AUTO_UPLOAD_ACCT_STATUS
set OAUAS_DISABLE_CHK_FR_STATUS = 1,
    OAUAS_DISABLE_CHK_TO_STATUS = 2
where OAUAS_ACCT_TYPE = 'DSI'
and OAUAS_STATUS_TYPE = 'A';

-- DSI, Non Active Status
update OL_AUTO_UPLOAD_ACCT_STATUS
set OAUAS_DISABLE_CHK_FR_STATUS = 2,
    OAUAS_DISABLE_CHK_TO_STATUS = 1
where OAUAS_ACCT_TYPE = 'DSI'
and OAUAS_STATUS_TYPE != 'A'; 

