OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOOLBankStmt
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOOLBankStmt.so
SOOBJS = BOOLBankStmt.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
