ALTER TABLE OL_DEF_ACTION_LIST
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_DEF_ACTION_LIST CASCADE CONSTRAINTS;

CREATE TABLE OL_DEF_ACTION_LIST
(
  AL_TYPE              VARCHAR2(20 BYTE),
  AL_DESC              VARCHAR2(50 BYTE),
  AL_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  AL_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  AL_CREATE_USER       VARCHAR2(20 BYTE),
  AL_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_DEF_ACTION_LIST_PK ON OL_DEF_ACTION_LIST
(AL_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_DEF_ACTION_LIST ADD (
  CONSTRAINT OL_DEF_ACTION_LIST_PK
  PRIMARY KEY
  (AL_TYPE)
  USING INDEX OL_DEF_ACTION_LIST_PK
  ENABLE VALIDATE);

