ALTER TABLE MOB_SEGMENT_THRESHOLD
 DROP PRIMARY KEY CASCADE;

DROP TABLE MOB_SEGMENT_THRESHOLD CASCADE CONSTRAINTS;

CREATE TABLE MOB_SEGMENT_THRESHOLD
(
  MST_GROUP             VARCHAR2(10 BYTE),
  MST_CUST_CNT		INTEGER                  DEFAULT 0,
  MST_IS_EXCEED_CNT	INTEGER                  DEFAULT 0,
  MST_AMT_LIMIT		NUMBER(14,2)		 DEFAULT 0.0,
  MST_IS_EXCEED_AMT	INTEGER                  DEFAULT 0,
  MST_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  MST_CREATE_USER       VARCHAR2(20 BYTE),
  MST_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  MST_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MOB_SEGMENT_THRESHOLD_PK ON MOB_SEGMENT_THRESHOLD
(MST_GROUP)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MOB_SEGMENT_THRESHOLD ADD (
  CONSTRAINT MOB_SEGMENT_THRESHOLD_PK
  PRIMARY KEY
  (MST_GROUP)
  USING INDEX MOB_SEGMENT_THRESHOLD_PK
  ENABLE VALIDATE);

