ALTER TABLE OL_DEF_ENGINE_RECON_CAT
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_DEF_ENGINE_RECON_CAT CASCADE CONSTRAINTS;

CREATE TABLE OL_DEF_ENGINE_RECON_CAT
(
  ERC_TYPE              VARCHAR2(10 BYTE),
  ERC_DESC              VARCHAR2(50 BYTE),
  ERC_DISPLAY_ORDER     INTEGER,
  ERC_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  ERC_CREATE_USER       VARCHAR2(20 BYTE),
  ERC_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  ERC_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_DEF_ENGINE_RECON_CAT_PK ON OL_DEF_ENGINE_RECON_CAT
(ERC_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_DEF_ENGINE_RECON_CAT ADD (
  CONSTRAINT OL_DEF_ENGINE_RECON_CAT_PK
  PRIMARY KEY
  (ERC_TYPE)
  USING INDEX OL_DEF_ENGINE_RECON_CAT_PK
  ENABLE VALIDATE);

