ALTER TABLE PAR_PSP_PROFILE
 DROP PRIMARY KEY CASCADE;

DROP TABLE PAR_PSP_PROFILE CASCADE CONSTRAINTS;

CREATE TABLE PAR_PSP_PROFILE
(
  PP_PSP_TYPE_CODE     VARCHAR2(50 BYTE),
  PP_PSP_TYPE_NAME     VARCHAR2(200 BYTE),
  PP_PSP_CODE          VARCHAR2(20 BYTE),
  PP_PSP_NAME          VARCHAR2(80 BYTE),
  PP_PSP_TYPE_GROUP    INTEGER,
  PP_COUNTRY_CODE      CHAR(2 BYTE),
  PP_CURRENCY_CODE     CHAR(3 BYTE),
  PP_CONVERTED         INTEGER,
  PP_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  PP_CREATE_USER       VARCHAR2(20 BYTE),
  PP_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  PP_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN PAR_PSP_PROFILE.PP_PSP_TYPE_GROUP IS '1: Deposit and Payout; 3: Payout only';



CREATE UNIQUE INDEX PAR_PSP_PROFILE_PK ON PAR_PSP_PROFILE
(PP_PSP_TYPE_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PAR_PSP_PROFILE ADD (
  CONSTRAINT PAR_PSP_PROFILE_PK
  PRIMARY KEY
  (PP_PSP_TYPE_CODE)
  USING INDEX PAR_PSP_PROFILE_PK
  ENABLE VALIDATE);

