OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/PspRestrictIpRegion
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBPspRestrictIpRegion.so
SOOBJS = PspRestrictIpRegion.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
