ALTER TABLE DEF_SUPPORT_DSP_COUNTRY
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_SUPPORT_DSP_COUNTRY CASCADE CONSTRAINTS;

CREATE TABLE DEF_SUPPORT_DSP_COUNTRY
(
  DC_COUNTRY  CHAR(2 BYTE),
  DC_DESC  VARCHAR2(50 BYTE),
  DC_CREATE_TIMESTAMP    DATE                      DEFAULT SYSDATE,
  DC_UPDATE_TIMESTAMP    DATE                      DEFAULT SYSDATE,
  DC_CREATE_USER         VARCHAR2(20 BYTE),
  DC_UPDATE_USER         VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX DEF_SUPPORT_DSP_COUNTRY_PK ON DEF_SUPPORT_DSP_COUNTRY
(DC_COUNTRY)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_SUPPORT_DSP_COUNTRY ADD (
  CONSTRAINT DEF_SUPPORT_DSP_COUNTRY_PK
  PRIMARY KEY
  (DC_COUNTRY)
  USING INDEX DEF_SUPPORT_DSP_COUNTRY_PK);
