ALTER TABLE RULE_SCHEDULER_HEADER
 DROP PRIMARY KEY CASCADE;

DROP TABLE RULE_SCHEDULER_HEADER CASCADE CONSTRAINTS;

CREATE TABLE RULE_SCHEDULER_HEADER
(
  RS_SCHEDULER_ID      INTEGER,
  RS_SCHEDULE_MODE     CHAR(1 BYTE),
  RS_DESC	       VARCHAR2(50 BYTE),
  RS_EFFECT_DATETIME   DATE,
  RS_DISABLED	       INTEGER                  DEFAULT 0,
  RS_CREATE_USER       VARCHAR2(20 BYTE),
  RS_UPDATE_USER       VARCHAR2(20 BYTE),
  RS_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  RS_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN RULE_SCHEDULER_HEADER.RS_SCHEDULE_MODE IS '''O'' - Once, ''R'' - Recurring';

CREATE INDEX RULE_SCHEDULER_HEADER_IDX01 ON RULE_SCHEDULER_HEADER
(RS_SCHEDULER_ID, RS_EFFECT_DATETIME, RS_DISABLED)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

CREATE UNIQUE INDEX RULE_SCHEDULER_HEADER_PK ON RULE_SCHEDULER_HEADER
(RS_SCHEDULER_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE RULE_SCHEDULER_HEADER ADD (
  CONSTRAINT RULE_SCHEDULER_HEADER_PK
  PRIMARY KEY
  (RS_SCHEDULER_ID)
  USING INDEX RULE_SCHEDULER_HEADER_PK);

ALTER TABLE RULE_SCHEDULER_HEADER ADD (
  CONSTRAINT RULE_SCHEDULER_HEADER_FK01 
  FOREIGN KEY (RS_SCHEDULE_MODE) 
  REFERENCES DEF_SCHEDULE_MODE (DS_MODE)
  ENABLE VALIDATE);
