ALTER TABLE DEF_PREFERRED_SETTLE_CCY
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_PREFERRED_SETTLE_CCY CASCADE CONSTRAINTS;

CREATE TABLE DEF_PREFERRED_SETTLE_CCY
(
  DP_CCY_ID            VARCHAR2(3 BYTE)         NOT NULL,
  DP_DESC              VARCHAR2(50 BYTE),
  DP_CREATE_USER       VARCHAR2(20 BYTE),
  DP_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  DP_UPDATE_USER       VARCHAR2(20 BYTE),
  DP_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEF_PREFERRED_SETTLE_CCY_PK ON DEF_PREFERRED_SETTLE_CCY
(DP_CCY_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_PREFERRED_SETTLE_CCY ADD (
  CONSTRAINT DEF_PREFERRED_SETTLE_CCY_PK
  PRIMARY KEY
  (DP_CCY_ID)
  USING INDEX DEF_PREFERRED_SETTLE_CCY_PK
  ENABLE VALIDATE);

