OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnMgtByUsVTF
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnMgtByUsVTF.so
SOOBJS = TxnMgtByUsVTF.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
