


CREATE OR REPLACE TYPE SAR_TRIGGER_CHK_CONFLICT_OBJ IS OBJECT (
TRIGGER_SEQ			INTEGER,
CREATE_USER			VARCHAR2(20),
CREATE_TIMESTAMP	DATE,
S_PROVIDER_ID		VARCHAR2(20),
S_PID				VARCHAR2(10),
R_PROVIDER_ID		VARCHAR2(20),
R_PID				VARCHAR2(10))
/

