ALTER TABLE PAR_PSP_OPEN_BAL
 DROP PRIMARY KEY CASCADE;

DROP TABLE PAR_PSP_OPEN_BAL CASCADE CONSTRAINTS;

CREATE TABLE PAR_PSP_OPEN_BAL
(
  POB_PSP_TYPE_CODE     VARCHAR2(50 BYTE),
  POB_PSP_CCY           VARCHAR2(3 BYTE),
  POB_PSP_BAL           NUMBER(14,2),
  POB_PSP_FLOAT         NUMBER(14,2),
  POB_PSP_HOLD          NUMBER(14,2),
  POB_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  POB_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  POB_CREATE_USER       VARCHAR2(20 BYTE),
  POB_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PAR_PSP_OPEN_BAL_PK ON PAR_PSP_OPEN_BAL
(POB_PSP_TYPE_CODE, POB_PSP_CCY)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PAR_PSP_OPEN_BAL ADD (
  CONSTRAINT PAR_PSP_OPEN_BAL_PK
  PRIMARY KEY
  (POB_PSP_TYPE_CODE, POB_PSP_CCY)
  USING INDEX PAR_PSP_OPEN_BAL_PK
  ENABLE VALIDATE);

