OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmsTxnSeq
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmsTxnSeq.so
SOOBJS =  MmsTxnSeq.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
