ALTER TABLE OL_TXN_ENGINE_SPC_ACT_MAP
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_TXN_ENGINE_SPC_ACT_MAP CASCADE CONSTRAINTS;

CREATE TABLE OL_TXN_ENGINE_SPC_ACT_MAP
(
  ESAM_SPECIAL_ACTION_ID         INTEGER        NOT NULL,
  ESAM_SEQ                       INTEGER        NOT NULL,
  ESAM_SPECIAL_ACTION_DETAIL_ID  INTEGER,
  ESAM_CREATE_TIMESTAMP          DATE           DEFAULT sysdate,
  ESAM_UPDATE_TIMESTAMP          DATE           DEFAULT sysdate,
  ESAM_CREATE_USER               VARCHAR2(20 BYTE),
  ESAM_UPDATE_USER               VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_TXN_ENGINE_SPC_ACT_MAP_PK ON OL_TXN_ENGINE_SPC_ACT_MAP
(ESAM_SPECIAL_ACTION_ID, ESAM_SEQ)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_TXN_ENGINE_SPC_ACT_MAP ADD (
  CONSTRAINT OL_TXN_ENGINE_SPC_ACT_MAP_PK
  PRIMARY KEY
  (ESAM_SPECIAL_ACTION_ID, ESAM_SEQ)
  USING INDEX OL_TXN_ENGINE_SPC_ACT_MAP_PK
  ENABLE VALIDATE);

