ALTER TABLE TXN_QR_REQUEST_LOG
 DROP PRIMARY KEY CASCADE;

DROP TABLE TXN_QR_REQUEST_LOG CASCADE CONSTRAINTS;

CREATE TABLE TXN_QR_REQUEST_LOG
(
  TQL_TXN_ID                 VARCHAR2(16 BYTE)  NOT NULL,
  TQL_QRCODE_INIT_TIMESTAMP  DATE               NOT NULL,
  TQL_EXPIRY                 NUMBER(38),
  TQL_ENABLE_BUTTON          NUMBER(38),
  TQL_AUTO_CHECK_TXN_STATUS  NUMBER(38),
  TQL_REDIRECT               NUMBER(38),
  TQL_CREATE_USER            VARCHAR2(20 BYTE),
  TQL_CREATE_TIMESTAMP       DATE               DEFAULT sysdate               NOT NULL
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX TXN_QR_REQUEST_LOG_PK ON TXN_QR_REQUEST_LOG
(TQL_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE TXN_QR_REQUEST_LOG ADD (
  CONSTRAINT TXN_QR_REQUEST_LOG_PK
  PRIMARY KEY
  (TQL_TXN_ID)
  USING INDEX TXN_QR_REQUEST_LOG_PK
  ENABLE VALIDATE);

