OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmsEntityBalance
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmsEntityBalance.so
SOOBJS =  MmsEntityBalance.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
