OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MerchantBalanceSnap
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMerchantBalanceSnap.so
SOOBJS =  MerchantBalanceSnap.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
