ALTER TABLE SERVICE_CONSUMER_PATH
 DROP PRIMARY KEY CASCADE;

DROP TABLE SERVICE_CONSUMER_PATH CASCADE CONSTRAINTS;

CREATE TABLE SERVICE_CONSUMER_PATH
(
  CP_SERVICE_CODE      CHAR(3 BYTE),
  CP_MERCHANT_ID       VARCHAR2(15 BYTE),
  CP_COUNTRY           VARCHAR2(2 BYTE),
  CP_DIRECTION         CHAR(1 BYTE),
  CP_METHOD            VARCHAR2(3 BYTE),
  CP_PATH              VARCHAR2(50 BYTE),
  CP_LANGUAGE          CHAR(2 BYTE),
  CP_EFFECT_DATE       DATE                     DEFAULT sysdate,
  CP_DISABLED          INTEGER                  DEFAULT 0,
  CP_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  CP_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  CP_CREATE_USER       VARCHAR2(20 BYTE),
  CP_UPDATE_USER       VARCHAR2(20 BYTE),
  CP_NEW_UI            INTEGER                  DEFAULT 0
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX SERVICE_CONSUMER_PATH_PK ON SERVICE_CONSUMER_PATH
(CP_SERVICE_CODE, CP_MERCHANT_ID, CP_COUNTRY, CP_DIRECTION, CP_LANGUAGE, 
CP_EFFECT_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE SERVICE_CONSUMER_PATH ADD (
  CONSTRAINT SERVICE_CONSUMER_PATH_PK
  PRIMARY KEY
  (CP_SERVICE_CODE, CP_MERCHANT_ID, CP_COUNTRY, CP_DIRECTION, CP_LANGUAGE, CP_EFFECT_DATE)
  USING INDEX SERVICE_CONSUMER_PATH_PK
  ENABLE VALIDATE);

ALTER TABLE SERVICE_CONSUMER_PATH ADD (
  CONSTRAINT SERVICE_CONSUMER_PATH_FK01 
  FOREIGN KEY (CP_SERVICE_CODE) 
  REFERENCES DEF_SERVICE_CODE (SC_CODE)
  ENABLE VALIDATE);

