OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLPayoutGenFileDtHist
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLPayoutGenFileDtHist.so
SOOBJS =  OLPayoutGenFileDtHist.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
