OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/TxnBrowserInfo
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBTxnBrowserInfo.so
SOOBJS =  TxnBrowserInfo.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
