OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnWebOnUs2EPT
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnWebOnUs2EPT.so
SOOBJS = TxnWebOnUs2EPT.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
