OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOParSettlement
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOParSettlement.so
SOOBJS = BOParSettlement.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
