OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/CrrFxMapping
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBCrrFxMapping.so
SOOBJS =  CrrFxMapping.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
