ALTER TABLE BANK_TXN_CHECK
 DROP PRIMARY KEY CASCADE;

DROP TABLE BANK_TXN_CHECK CASCADE CONSTRAINTS;

CREATE TABLE BANK_TXN_CHECK
(
  BC_PARTY_ID              VARCHAR2(10 BYTE),
  BC_BANK_CODE             VARCHAR2(10 BYTE),
  BC_CUTOFF_CHECKING_TIME  DATE                 NOT NULL,
  BC_CHECK_COUNT           INTEGER              NOT NULL,
  BC_MIN_SUCCESS_COUNT     INTEGER              DEFAULT 0,
  BC_DISABLED              INTEGER              DEFAULT 0,
  BC_LAST_CHECKING_TIME    DATE,
  BC_START_BUFFER_PERIOD   INTEGER              DEFAULT 0,
  BC_MIN_TOTAL             INTEGER              DEFAULT 0,
  BC_CREATE_USER           VARCHAR2(20 BYTE),
  BC_UPDATE_USER           VARCHAR2(20 BYTE),
  BC_CREATE_TIMESTAMP      DATE                 DEFAULT sysdate,
  BC_UPDATE_TIMESTAMP      DATE                 DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX BANK_TXN_CHECK_IDX01 ON BANK_TXN_CHECK
(BC_PARTY_ID, BC_BANK_CODE, BC_DISABLED)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX BANK_TXN_CHECK_IDX02 ON BANK_TXN_CHECK
(BC_CUTOFF_CHECKING_TIME)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX BANK_TXN_CHECK_PK ON BANK_TXN_CHECK
(BC_PARTY_ID, BC_BANK_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE BANK_TXN_CHECK ADD (
  CONSTRAINT BANK_TXN_CHECK_PK
  PRIMARY KEY
  (BC_PARTY_ID, BC_BANK_CODE)
  USING INDEX BANK_TXN_CHECK_PK
  ENABLE VALIDATE);

