ALTER TABLE DEF_PAYOUT_BATCH_STATUS
 ADD (DP_ADMIN_DESC  VARCHAR2(50 BYTE));

ALTER TABLE DEF_PAYOUT_BATCH_STATUS
 ADD (DP_MERCHANT_DESC  VARCHAR2(50 BYTE));

ALTER TABLE DEF_PAYOUT_BATCH_STATUS
 ADD (DP_STATUS_TYPE  CHAR(1 BYTE));

ALTER TABLE DEF_PAYOUT_BATCH_STATUS
 ADD (DP_PARTY  CHAR(1 BYTE));

ALTER TABLE DEF_PAYOUT_BATCH_STATUS
 ADD (DP_FE_DISPLAY	INTEGER DEFAULT 1);

ALTER TABLE DEF_PAYOUT_BATCH_STATUS
 ADD (DP_DISABLED	INTEGER DEFAULT 0);

COMMENT ON COLUMN DEF_PAYOUT_BATCH_STATUS.DP_STATUS_TYPE IS '''F'' - file status;  ''T'' - record status';

COMMENT ON COLUMN DEF_PAYOUT_BATCH_STATUS.DP_PARTY IS '''P'' - PSP; ''M'' - Merchant; ''A'' - All';
