ALTER TABLE DEF_PAYOUT_BATCH_STATUS
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_PAYOUT_BATCH_STATUS CASCADE CONSTRAINTS;

CREATE TABLE DEF_PAYOUT_BATCH_STATUS
(
  DP_STATUS_ID         INTEGER                  NOT NULL,
  DP_DESC              VARCHAR2(50 BYTE),
  DP_CREATE_USER       VARCHAR2(20 BYTE),
  DP_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  DP_UPDATE_USER       VARCHAR2(20 BYTE),
  DP_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  DP_ADMIN_DESC        VARCHAR2(50 BYTE),
  DP_MERCHANT_DESC     VARCHAR2(50 BYTE),
  DP_STATUS_TYPE       CHAR(1 BYTE),
  DP_PARTY             CHAR(1 BYTE),
  DP_FE_DISPLAY        INTEGER                  DEFAULT 1,
  DP_DISABLED          INTEGER                  DEFAULT 0
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN DEF_PAYOUT_BATCH_STATUS.DP_STATUS_TYPE IS '''F'' - file status;  ''T'' - record status';

COMMENT ON COLUMN DEF_PAYOUT_BATCH_STATUS.DP_PARTY IS '''P'' - PSP; ''M'' - Merchant; ''A'' - All';



CREATE UNIQUE INDEX DEF_PAYOUT_BATCH_STATUS_PK ON DEF_PAYOUT_BATCH_STATUS
(DP_STATUS_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_PAYOUT_BATCH_STATUS ADD (
  CONSTRAINT DEF_PAYOUT_BATCH_STATUS_PK
  PRIMARY KEY
  (DP_STATUS_ID)
  USING INDEX DEF_PAYOUT_BATCH_STATUS_PK
  ENABLE VALIDATE);

