ALTER TABLE IP_FILTER_FR_WEB
 DROP PRIMARY KEY CASCADE;

DROP TABLE IP_FILTER_FR_WEB CASCADE CONSTRAINTS;

CREATE TABLE IP_FILTER_FR_WEB
(
  IP_FILTER_ID         INTEGER,
  IP_START             VARCHAR2(15 BYTE),
  IP_END               VARCHAR2(15 BYTE),
  IP_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  IP_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX IP_FILTER_FR_WEB_IDX01 ON IP_FILTER_FR_WEB
(IP_START)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX IP_FILTER_FR_WEB_PK ON IP_FILTER_FR_WEB
(IP_FILTER_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE IP_FILTER_FR_WEB ADD (
  CONSTRAINT IP_FILTER_FR_WEB_PK
  PRIMARY KEY
  (IP_FILTER_ID)
  USING INDEX IP_FILTER_FR_WEB_PK
  ENABLE VALIDATE);

