ALTER TABLE CRR_EXT_MERCH_DETAIL
 DROP PRIMARY KEY CASCADE;

DROP TABLE CRR_EXT_MERCH_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE CRR_EXT_MERCH_DETAIL
(
  PRODUCT_CODE      CHAR(3 BYTE) NOT NULL,
  MERCHANT_ID       VARCHAR2(15 BYTE) NOT NULL,
  NAME              VARCHAR2(50 BYTE),
  EXT_MERCH_ID  		VARCHAR2(100 BYTE) NOT NULL,
  DISABLED          INTEGER DEFAULT 0,
  CREATE_TIMESTAMP  DATE DEFAULT SYSDATE,
  UPDATE_TIMESTAMP  DATE DEFAULT SYSDATE,
  CREATE_USER       VARCHAR2(20 BYTE),
  UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CRR_EXT_MERCH_DETAIL_PK ON CRR_EXT_MERCH_DETAIL
(PRODUCT_CODE, MERCHANT_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE CRR_EXT_MERCH_DETAIL ADD (
  CONSTRAINT CRR_EXT_MERCH_DETAIL_PK
  PRIMARY KEY
  (PRODUCT_CODE, MERCHANT_ID)
  USING INDEX CRR_EXT_MERCH_DETAIL_PK);


