OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLBankBalCheck
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLBankBalCheck.so
SOOBJS =  OLBankBalCheck.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
