OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/TxnSupported
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBTxnSupported.so
SOOBJS =  TxnSupported.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
