ALTER TABLE BANK_NAME_MAPPING
 ADD (NM_PSP_CHANNEL_ID  VARCHAR2(10)   DEFAULT 'YPY');

ALTER TABLE BANK_NAME_MAPPING
MODIFY(NM_PSP_CHANNEL_ID  DEFAULT NULL);

CREATE UNIQUE INDEX BANK_NAME_MAPPING_PK ON PHUSER.BANK_NAME_MAPPING
(NM_IN_BANK_NAME, NM_PSP_CHANNEL_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE BANK_NAME_MAPPING ADD (
  CONSTRAINT BANK_NAME_MAPPING_PK
  PRIMARY KEY
  (NM_IN_BANK_NAME, NM_PSP_CHANNEL_ID)
  USING INDEX BANK_NAME_MAPPING_PK
  ENABLE VALIDATE);
