ALTER TABLE BANK_NAME_MAPPING
 DROP PRIMARY KEY CASCADE;

DROP TABLE BANK_NAME_MAPPING CASCADE CONSTRAINTS;

CREATE TABLE BANK_NAME_MAPPING
(
  NM_IN_BANK_NAME      VARCHAR2(150 BYTE),
  NM_OUT_BANK_NAME     VARCHAR2(150 BYTE),
  NM_DISABLED          INTEGER                  DEFAULT 0,
  NM_CREATE_USER       VARCHAR2(20 BYTE),
  NM_UPDATE_USER       VARCHAR2(20 BYTE),
  NM_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  NM_UPDATE_TIMESTAMP   DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX BANK_NAME_MAPPING_PK ON BANK_NAME_MAPPING
(NM_IN_BANK_NAME)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE BANK_NAME_MAPPING ADD (
  CONSTRAINT BANK_NAME_MAPPING_PK
  PRIMARY KEY
  (NM_IN_BANK_NAME)
  USING INDEX BANK_NAME_MAPPING_PK
  ENABLE VALIDATE);

