OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/CustomerGroupLog
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBCustomerGroupLog.so
SOOBJS =  CustomerGroupLog.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
