ALTER TABLE PAR_CLIENT_PSP_MAP
 DROP PRIMARY KEY CASCADE;

DROP TABLE PAR_CLIENT_PSP_MAP CASCADE CONSTRAINTS;

CREATE TABLE PAR_CLIENT_PSP_MAP
(
  CP_CLIENT_ID              VARCHAR2(10 BYTE),
  CP_PSP_TYPE_CODE          VARCHAR2(50 BYTE),
  CP_PRESET_PH_PID          VARCHAR2(10 BYTE),
  CP_PRESET_PH_PID_NAME     VARCHAR2(50 BYTE),
  CP_PRESET_PRODUCT         VARCHAR2(3  BYTE),
  CP_CREATE_TIMESTAMP       DATE                DEFAULT sysdate,
  CP_CREATE_USER            VARCHAR2(20 BYTE),
  CP_UPDATE_TIMESTAMP       DATE                DEFAULT sysdate,
  CP_UPDATE_USER            VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PAR_CLIENT_PSP_MAP_PK ON PAR_CLIENT_PSP_MAP
(CP_PSP_TYPE_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PAR_CLIENT_PSP_MAP ADD (
  CONSTRAINT PAR_CLIENT_PSP_MAP_PK
  PRIMARY KEY
  (CP_PSP_TYPE_CODE)
  USING INDEX PAR_CLIENT_PSP_MAP_PK
  ENABLE VALIDATE);

