OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/CustomerGroupRules
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBCustomerGroupRules.so
SOOBJS =  CustomerGroupRules.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
