OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOMiAdjustment
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOMiAdjustment.so
SOOBJS = BOMiAdjustment.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
