ALTER TABLE PSP_KEYS
 DROP PRIMARY KEY CASCADE;

DROP TABLE PSP_KEYS CASCADE CONSTRAINTS;

CREATE TABLE PSP_KEYS
(
  PSP_ID            VARCHAR2(10 BYTE),
  KEY               VARCHAR2(3 BYTE),
  KEY_VALUE         VARCHAR2(128 BYTE),
  EFFECT_DATE       DATE,
  CREATE_TIMESTAMP  DATE                        DEFAULT sysdate,
  UPDATE_TIMESTAMP  DATE                        DEFAULT sysdate,
  CREATE_USER       VARCHAR2(20 BYTE),
  UPDATE_USER       VARCHAR2(20 BYTE),
  KEY_ID            VARCHAR2(32 BYTE),
  KEY_UID           VARCHAR2(20 BYTE),
  PRIVATEPEM        VARCHAR2(20 BYTE),
  PASSPHRASE        VARCHAR2(20 BYTE),
  PUBLICCERT        VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX PSP_KEYS_IDX01 ON PSP_KEYS
(EFFECT_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PSP_KEYS_PK ON PSP_KEYS
(PSP_ID, KEY, EFFECT_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PSP_KEYS ADD (
  CONSTRAINT PSP_KEYS_PK
  PRIMARY KEY
  (PSP_ID, KEY, EFFECT_DATE)
  USING INDEX PSP_KEYS_PK
  ENABLE VALIDATE);

ALTER TABLE PSP_KEYS ADD (
  CONSTRAINT PSP_KEYS_FK01 
  FOREIGN KEY (KEY) 
  REFERENCES DEF_KEY_TYPE (DK_TYPE)
  ENABLE VALIDATE);

