ALTER TABLE OL_DEF_EMAIL_NOTIFY_TEMPLATE
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_DEF_EMAIL_NOTIFY_TEMPLATE CASCADE CONSTRAINTS;

CREATE TABLE OL_DEF_EMAIL_NOTIFY_TEMPLATE
(
  OET_FUNCT             VARCHAR2(10 BYTE),
  OET_TEMPLATE          VARCHAR2(2000 BYTE),
  OET_CREATE_USER       VARCHAR2(20 BYTE),
  OET_UPDATE_USER       VARCHAR2(20 BYTE),
  OET_CREATE_TIMESTAMP  DATE,
  OET_UPDATE_TIMESTAMP  DATE
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_DEF_EMAIL_NOTIFY_TPL_PK ON OL_DEF_EMAIL_NOTIFY_TEMPLATE
(OET_FUNCT)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_DEF_EMAIL_NOTIFY_TEMPLATE ADD (
  CONSTRAINT OL_DEF_EMAIL_NOTIFY_TPL_PK
  PRIMARY KEY
  (OET_FUNCT)
  USING INDEX OL_DEF_EMAIL_NOTIFY_TPL_PK
  ENABLE VALIDATE);

