OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/RulePayoutWhiteList
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBRulePayoutWhiteList.so
SOOBJS =  RulePayoutWhiteList.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
