ALTER TABLE MMS_TXN_DETAIL
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_TXN_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE MMS_TXN_DETAIL
(
  TD_TXN_ID                 VARCHAR2(16 BYTE),
  TD_TXN_CCY                VARCHAR2(3 BYTE),
  TD_TXN_COUNTRY            VARCHAR2(2 BYTE),
  TD_ENCRYPT_TYPE           VARCHAR2(4 BYTE),
  TD_VERSION_NO             INTEGER,
  TD_REMARK                 VARCHAR2(255 BYTE),
  TD_CURRENT_BAL            NUMBER(14,2),
  TD_TOTAL_FLOAT            NUMBER(14,2),
  TD_TOTAL_RESERVED_AMOUNT  NUMBER(14,2),
  TD_TOTAL_HOLD             NUMBER(14,2),
  TD_SETTLEMENT_IN_TRANSIT  NUMBER(14,2),
  TD_CREATE_TIMESTAMP       DATE,
  TD_UPDATE_TIMESTAMP       DATE,
  TD_CREATE_USER            VARCHAR2(20 BYTE),
  TD_UPDATE_USER            VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MMS_TXN_DETAIL_PK ON MMS_TXN_DETAIL
(TD_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_TXN_DETAIL ADD (
  CONSTRAINT MMS_TXN_DETAIL_PK
  PRIMARY KEY
  (TD_TXN_ID)
  USING INDEX MMS_TXN_DETAIL_PK
  ENABLE VALIDATE);

