ALTER TABLE MMS_TXN_HEADER
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_TXN_HEADER CASCADE CONSTRAINTS;

CREATE TABLE MMS_TXN_HEADER
(
  TH_TXN_ID                 VARCHAR2(16 BYTE),
  TH_ORG_TXN_ID             VARCHAR2(16 BYTE),
  TH_CLIENT_TXN_ID          VARCHAR2(16 BYTE),
  TH_INPUT_CHANNEL          VARCHAR2(3 BYTE),
  TH_MMC_NODE_ID            VARCHAR2(5 BYTE),
  TH_SERVICE_CODE           VARCHAR2(3 BYTE),
  TH_STATUS                 CHAR(1 BYTE),
  TH_AR_IND                 CHAR(1 BYTE),
  TH_TXN_CODE               VARCHAR2(3 BYTE),
  TH_PROCESS_TYPE           VARCHAR2(4 BYTE),
  TH_PROCESS_CODE           VARCHAR2(6 BYTE),
  TH_CLIENT_ID              VARCHAR2(10 BYTE),
  TH_MERCHANT_ID            VARCHAR2(15 BYTE),
  TH_PSP_ID                 VARCHAR2(10 BYTE),
  TH_TRANSMISSION_DATETIME  VARCHAR2(14 BYTE),
  TH_POSTING_DATETIME       VARCHAR2(14 BYTE),
  TH_INTERNAL_CODE          NUMBER(8),
  TH_RESPONSE_CODE          VARCHAR2(6 BYTE),
  TH_TRANSACTION_AMOUNT     NUMBER(12,2),
  TH_NET_AMOUNT             NUMBER(12,2),
  TH_NET_CCY                VARCHAR2(3 BYTE),
  TH_EX_SUPPLIER            CHAR(1 BYTE),
  TH_EX_RATE                NUMBER(14,5),
  TH_MARKUP_CCY             VARCHAR2(3 BYTE),
  TH_MARKUP_RATE            NUMBER(12,5),
  TH_MARKUP_AMOUNT          NUMBER(12,2),
  TH_CREATE_TIMESTAMP       DATE                DEFAULT sysdate,
  TH_UPDATE_TIMESTAMP       DATE                DEFAULT sysdate,
  TH_CREATE_USER            VARCHAR2(20 BYTE),
  TH_UPDATE_USER            VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX MMS_TXN_HEADER_IDX01 ON MMS_TXN_HEADER
(TH_ORG_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX MMS_TXN_HEADER_IDX02 ON MMS_TXN_HEADER
(TH_CLIENT_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX MMS_TXN_HEADER_IDX03 ON MMS_TXN_HEADER
(TH_CREATE_TIMESTAMP, TH_TXN_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX MMS_TXN_HEADER_PK ON MMS_TXN_HEADER
(TH_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_TXN_HEADER ADD (
  CONSTRAINT MMS_TXN_HEADER_PK
  PRIMARY KEY
  (TH_TXN_ID)
  USING INDEX MMS_TXN_HEADER_PK
  ENABLE VALIDATE);

