OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/DefTlgTagConvert
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBDefTlgTagConvert.so
SOOBJS =  DefTlgTagConvert.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
