OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLTxnRelationSpc
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLTxnRelationSpc.so
SOOBJS =  OLTxnRelationSpc.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
