ALTER TABLE SEB_BALANCE
 DROP PRIMARY KEY CASCADE;

DROP TABLE SEB_BALANCE CASCADE CONSTRAINTS;

CREATE TABLE SEB_BALANCE
(
  S_FROM_CCY          VARCHAR2(3 BYTE),
  S_BANK_CCY          VARCHAR2(3 BYTE),
  S_BANK_BAL          NUMBER(14,2),
  S_RATE              NUMBER(14,5),
  S_RATIO             NUMBER(14,5),
  S_CREATE_USER       VARCHAR2(20 BYTE),
  S_CREATE_TIMESTAMP  DATE,
  S_UPDATE_USER       VARCHAR2(20 BYTE),
  S_UPDATE_TIMESTAMP  DATE,
  S_DSP_BAL           NUMBER(14,2)              DEFAULT 0
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX SEB_BALANCE_PK ON SEB_BALANCE
(S_FROM_CCY, S_BANK_CCY)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE SEB_BALANCE ADD (
  CONSTRAINT SEB_BALANCE_PK
  PRIMARY KEY
  (S_FROM_CCY, S_BANK_CCY)
  USING INDEX SEB_BALANCE_PK);

