ALTER TABLE PHUSER.PAYOUT_RETURN_BATCH_HD
 DROP PRIMARY KEY CASCADE;

DROP TABLE PHUSER.PAYOUT_RETURN_BATCH_HD CASCADE CONSTRAINTS;

CREATE TABLE PHUSER.PAYOUT_RETURN_BATCH_HD
(
  PRH_BATCH_ID          INTEGER                 NOT NULL,
  PRH_FILENAME          VARCHAR2(100 BYTE)      NOT NULL,
  PRH_RECORD_COUNT      INTEGER                 DEFAULT 0,
  PRH_STATUS            INTEGER,
  PRH_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  PRH_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  PRH_CREATE_USER       VARCHAR2(20 BYTE),
  PRH_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PHUSER.PAYOUT_RETURN_BATCH_HD_PK ON PHUSER.PAYOUT_RETURN_BATCH_HD
(PRH_BATCH_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PHUSER.PAYOUT_RETURN_BATCH_HD ADD (
  CONSTRAINT PAYOUT_RETURN_BATCH_HD_PK
  PRIMARY KEY
  (PRH_BATCH_ID)
  USING INDEX PHUSER.PAYOUT_RETURN_BATCH_HD_PK
  ENABLE VALIDATE);

