ALTER TABLE OL_BATCH_ENGINE_ACTION_LOG
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_BATCH_ENGINE_ACTION_LOG CASCADE CONSTRAINTS;

CREATE TABLE OL_BATCH_ENGINE_ACTION_LOG
(
  OBEL_BATCH_ID          VARCHAR2(16 BYTE),
  OBEL_ACTION_ID	 INTEGER,
  OBEL_USE_PENDING_FUND	 INTEGER		default 0,
  OBEL_INPUT_BANK_CHARGE NUMBER(12,2)		default 0,
  OBEL_INPUT_INTEREST	 NUMBER(12,2)		default 0,
  OBEL_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  OBEL_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  OBEL_CREATE_USER       VARCHAR2(20 BYTE),
  OBEL_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_BATCH_ENGINE_ACT_LOG_PK ON OL_BATCH_ENGINE_ACTION_LOG
(OBEL_BATCH_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_BATCH_ENGINE_ACTION_LOG ADD (
  CONSTRAINT OL_BATCH_ENGINE_ACT_LOG_PK
  PRIMARY KEY
  (OBEL_BATCH_ID)
  USING INDEX OL_BATCH_ENGINE_ACT_LOG_PK
  ENABLE VALIDATE);

