ALTER TABLE OL_PAYOUT_GRP_LIST
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_PAYOUT_GRP_LIST CASCADE CONSTRAINTS;

CREATE TABLE OL_PAYOUT_GRP_LIST
(
  OGL_GROUP             CHAR(1 BYTE),
  OGL_BANK_ACCT_NUM     VARCHAR2(25 BYTE),
  OGL_BANK_ACCT_NAME    VARCHAR2(100 BYTE),
  OGL_POSTING_DATE      VARCHAR2(8 BYTE),
  OGL_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  OGL_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  OGL_CREATE_USER       VARCHAR2(20 BYTE),
  OGL_UPDATE_USER       VARCHAR2(20 BYTE),
  OGL_DISABLED          INTEGER                 DEFAULT 0
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_PAYOUT_GRP_LIST_PK ON OL_PAYOUT_GRP_LIST
(OGL_GROUP, OGL_BANK_ACCT_NUM, OGL_BANK_ACCT_NAME, OGL_DISABLED)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_PAYOUT_GRP_LIST ADD (
  CONSTRAINT OL_PAYOUT_GRP_LIST_PK
  PRIMARY KEY
  (OGL_GROUP, OGL_BANK_ACCT_NUM, OGL_BANK_ACCT_NAME, OGL_DISABLED)
  USING INDEX OL_PAYOUT_GRP_LIST_PK
  ENABLE VALIDATE);

ALTER TABLE OL_PAYOUT_GRP_LIST ADD (
  CONSTRAINT OL_PAYOUT_GRP_LIST_FK01 
  FOREIGN KEY (OGL_GROUP) 
  REFERENCES OL_DEF_PAYOUT_GROUP (OPG_GROUP)
  ENABLE VALIDATE);

