OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnMgtByUsFEU
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnMgtByUsFEU.so
SOOBJS = TxnMgtByUsFEU.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
