ALTER TABLE SERVICE_UI_RELEASE
 DROP PRIMARY KEY CASCADE;

DROP TABLE SERVICE_UI_RELEASE CASCADE CONSTRAINTS;

CREATE TABLE SERVICE_UI_RELEASE
(
  UR_SERVICE_CODE      CHAR(3 BYTE),
  UR_MERCHANT_ID       VARCHAR2(15 BYTE),
  UR_COUNTRY           VARCHAR2(2 BYTE),
  UR_NEW_UI            INTEGER                  DEFAULT 0,
  UR_DISABLED          INTEGER                  DEFAULT 0,
  UR_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  UR_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  UR_CREATE_USER       VARCHAR2(20 BYTE),
  UR_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX SERVICE_UI_RELEASE_PK ON SERVICE_UI_RELEASE
(UR_SERVICE_CODE, UR_MERCHANT_ID, UR_COUNTRY)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE SERVICE_UI_RELEASE ADD (
  CONSTRAINT SERVICE_UI_RELEASE_PK
  PRIMARY KEY
  (UR_SERVICE_CODE, UR_MERCHANT_ID, UR_COUNTRY)
  USING INDEX SERVICE_UI_RELEASE_PK
  ENABLE VALIDATE);

