ALTER TABLE CRR_MI_JNL_ENTRY_TYPE_MAPPING
 DROP PRIMARY KEY CASCADE;

DROP TABLE CRR_MI_JNL_ENTRY_TYPE_MAPPING CASCADE CONSTRAINTS;

CREATE TABLE CRR_MI_JNL_ENTRY_TYPE_MAPPING
(
  CMM_JNL_TYPE_ID       INTEGER,
  CMM_ENTRY_TYPE_ID     VARCHAR2(20 BYTE),
  CMM_GROUP_ID          INTEGER                DEFAULT 1,
  CMM_TXN_SIDE          CHAR(1 BYTE),
  CMM_IS_SINGLE         INTEGER                DEFAULT 0,
  CMM_TXN_CODE          VARCHAR2(3 BYTE),
  CMM_AMT_FIELD         VARCHAR2(50 BYTE),
  CMM_PARTY_TYPE        CHAR(1 BYTE),
  CMM_SIGN              INTEGER                DEFAULT 1,
  CMM_DISABLED          INTEGER                DEFAULT 0,
  CMM_CREATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  CMM_UPDATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  CMM_CREATE_USER       VARCHAR2(20 BYTE),
  CMM_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CRR_MI_JNL_ENTRY_TYPE_MAP_PK ON CRR_MI_JNL_ENTRY_TYPE_MAPPING
(CMM_JNL_TYPE_ID, CMM_ENTRY_TYPE_ID, CMM_GROUP_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE CRR_MI_JNL_ENTRY_TYPE_MAPPING ADD (
  CONSTRAINT CRR_MI_JNL_ENTRY_TYPE_MAP_PK
  PRIMARY KEY
  (CMM_JNL_TYPE_ID, CMM_ENTRY_TYPE_ID, CMM_GROUP_ID)
  USING INDEX CRR_MI_JNL_ENTRY_TYPE_MAP_PK
  ENABLE VALIDATE);
