OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOPspPaidAmount
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOPspPaidAmount.so
SOOBJS = BOPspPaidAmount.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
