ALTER TABLE CRR_DEF_PARTY_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE CRR_DEF_PARTY_TYPE CASCADE CONSTRAINTS;

CREATE TABLE CRR_DEF_PARTY_TYPE
(
  CPT_TYPE_ID           CHAR(1 BYTE),
  CPT_DESC              VARCHAR2(50 BYTE),
  CPT_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  CPT_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  CPT_CREATE_USER       VARCHAR2(20 BYTE),
  CPT_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CRR_DEF_PARTY_TYPE_PK ON CRR_DEF_PARTY_TYPE
(CPT_TYPE_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE CRR_DEF_PARTY_TYPE ADD (
  CONSTRAINT CRR_DEF_PARTY_TYPE_PK
  PRIMARY KEY
  (CPT_TYPE_ID)
  USING INDEX CRR_DEF_PARTY_TYPE_PK
  ENABLE VALIDATE);

