ALTER TABLE MOB_SEGMENT_CTL
 DROP PRIMARY KEY CASCADE;

DROP TABLE MOB_SEGMENT_CTL CASCADE CONSTRAINTS;

CREATE TABLE MOB_SEGMENT_CTL
(
  MSC_GROUP             VARCHAR2(10 BYTE),
  MSC_ENABLE_NEW_CUST	INTEGER                  DEFAULT 1,
  MSC_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  MSC_CREATE_USER       VARCHAR2(20 BYTE),
  MSC_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  MSC_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MOB_SEGMENT_CTL_PK ON MOB_SEGMENT_CTL
(MSC_GROUP)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MOB_SEGMENT_CTL ADD (
  CONSTRAINT MOB_SEGMENT_CTL_PK
  PRIMARY KEY
  (MSC_GROUP)
  USING INDEX MOB_SEGMENT_CTL_PK
  ENABLE VALIDATE);

