ALTER TABLE DEF_EMAIL_ADM_NTY_TEMPLATE
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_EMAIL_ADM_NTY_TEMPLATE CASCADE CONSTRAINTS;

CREATE TABLE DEF_EMAIL_ADM_NTY_TEMPLATE
(
  AT_FUNCT             VARCHAR2(10 BYTE),
  AT_TEMPLATE          VARCHAR2(2000 BYTE),
  AT_CREATE_USER       VARCHAR2(20 BYTE),
  AT_UPDATE_USER       VARCHAR2(20 BYTE),
  AT_CREATE_TIMESTAMP  DATE,
  AT_UPDATE_TIMESTAMP  DATE
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEF_EMAIL_ADM_NTY_TEMPLATE_PK ON DEF_EMAIL_ADM_NTY_TEMPLATE
(AT_FUNCT)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_EMAIL_ADM_NTY_TEMPLATE ADD (
  CONSTRAINT DEF_EMAIL_ADM_NTY_TEMPLATE_PK
  PRIMARY KEY
  (AT_FUNCT)
  USING INDEX DEF_EMAIL_ADM_NTY_TEMPLATE_PK
  ENABLE VALIDATE);

