ALTER TABLE EMAIL_RECEIVER_LIST
 DROP PRIMARY KEY CASCADE;

DROP TABLE EMAIL_RECEIVER_LIST CASCADE CONSTRAINTS;

CREATE TABLE EMAIL_RECEIVER_LIST
(
  ERL_FUNCT  VARCHAR2(15 BYTE),
  ERL_ID     INTEGER,
  ERL_TYPE   INTEGER
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX EMAIL_RECEIVER_LIST_PK ON EMAIL_RECEIVER_LIST
(ERL_FUNCT, ERL_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE EMAIL_RECEIVER_LIST ADD (
  CONSTRAINT EMAIL_RECEIVER_LIST_PK
  PRIMARY KEY
  (ERL_FUNCT, ERL_ID)
  USING INDEX EMAIL_RECEIVER_LIST_PK
  ENABLE VALIDATE);

