ALTER TABLE MMS_INSTANT_TXN_INQ_HD
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_INSTANT_TXN_INQ_HD CASCADE CONSTRAINTS;

CREATE TABLE MMS_INSTANT_TXN_INQ_HD
(
  MIH_INQ_ID            VARCHAR2(16 BYTE)       NOT NULL,
  MIH_TXN_ID            VARCHAR2(16 BYTE)       NOT NULL,
  MIH_REQ_TXN_STATUS    CHAR(1 BYTE),
  MIH_STATUS            CHAR(1 BYTE)            NOT NULL,
  MIH_CREATE_USER       VARCHAR2(20 BYTE),
  MIH_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  MIH_UPDATE_USER       VARCHAR2(20 BYTE),
  MIH_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX MMS_INSTANT_TXN_INQ_HD_IDX01 ON MMS_INSTANT_TXN_INQ_HD
(MIH_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX MMS_INSTANT_TXN_INQ_HD_PK ON MMS_INSTANT_TXN_INQ_HD
(MIH_INQ_ID, MIH_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_INSTANT_TXN_INQ_HD ADD (
  CONSTRAINT MMS_INSTANT_TXN_INQ_HD_PK
  PRIMARY KEY
  (MIH_INQ_ID, MIH_TXN_ID)
  USING INDEX MMS_INSTANT_TXN_INQ_HD_PK
  ENABLE VALIDATE);

