OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLEngineSql
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLEngineSql.so
SOOBJS =  OLEngineSql.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
