OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/P2xTxn
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBP2xTxn.so
SOOBJS =  P2xTxn.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
