CREATE TABLE OL_BULK_HEADER
(
  OBH_BATCH_ID          NUMBER(16)              NOT NULL,
  OBH_TXN_CODE          CHAR(3 BYTE),
  OBH_STATUS            CHAR(1 BYTE),
  OBH_RET_CODE          NUMBER(8),
  OBH_RECORD_CNT        INTEGER                 DEFAULT 0,
  OBH_CREATE_USER       VARCHAR2(20 BYTE),
  OBH_CREATE_TIMESTAMP  DATE                    DEFAULT SYSDATE,
  OBH_UPDATE_USER       VARCHAR2(20 BYTE),
  OBH_UPDATE_TIMESTAMP  DATE                    DEFAULT SYSDATE
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE INDEX OL_BULK_HEADER_IDX01 ON OL_BULK_HEADER
(OBH_TXN_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX OL_BULK_HEADER_IDX02 ON OL_BULK_HEADER
(OBH_CREATE_TIMESTAMP, OBH_UPDATE_TIMESTAMP)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX OL_BULK_HEADER_PK ON OL_BULK_HEADER
(OBH_BATCH_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE OL_BULK_HEADER ADD (
  CONSTRAINT OL_BULK_HEADER_PK
  PRIMARY KEY
  (OBH_BATCH_ID)
  USING INDEX OL_BULK_HEADER_PK
  ENABLE VALIDATE);

ALTER TABLE OL_BULK_HEADER ADD (
  CONSTRAINT OL_BULK_HEADER_FK01 
  FOREIGN KEY (OBH_TXN_CODE) 
  REFERENCES OL_DEF_BULK_TYPE (OBT_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OL_BULK_HEADER_FK02 
  FOREIGN KEY (OBH_STATUS) 
  REFERENCES OL_DEF_BULK_STATUS (OBS_TYPE)
  ENABLE VALIDATE);
