OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnXpyOnUsCOM
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnXpyOnUsCOM.so
SOOBJS = TxnXpyOnUsCOM.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
