ALTER TABLE DEF_EMAIL_NOTIFY_FUNCT
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_EMAIL_NOTIFY_FUNCT CASCADE CONSTRAINTS;

CREATE TABLE DEF_EMAIL_NOTIFY_FUNCT
(
  EF_FUNCT             VARCHAR2(10 BYTE),
  EF_FUNCT_DESC        VARCHAR2(50 BYTE),
  EF_CREATE_USER       VARCHAR2(20 BYTE),
  EF_UPDATE_USER       VARCHAR2(20 BYTE),
  EF_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  EF_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEF_EMAIL_NOTIFY_FUNCT_PK ON DEF_EMAIL_NOTIFY_FUNCT
(EF_FUNCT)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_EMAIL_NOTIFY_FUNCT ADD (
  CONSTRAINT DEF_EMAIL_NOTIFY_FUNCT_PK
  PRIMARY KEY
  (EF_FUNCT)
  USING INDEX DEF_EMAIL_NOTIFY_FUNCT_PK
  ENABLE VALIDATE);
