ALTER TABLE OL_STATEMENT_HEADER
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_STATEMENT_HEADER CASCADE CONSTRAINTS;

CREATE TABLE OL_STATEMENT_HEADER
(
  OLSH_FILENAME          VARCHAR2(100 BYTE),
  OLSH_INT_BANK_CODE     VARCHAR2(10 BYTE),
  OLSH_BANK_ACCT_NUM     VARCHAR2(50 BYTE),
  OLSH_SMS_COUNT         INTEGER                DEFAULT 0,
  OLSH_SKIP_COUNT        INTEGER                DEFAULT 0,
  OLSH_HOLD_COUNT        INTEGER                DEFAULT 0,
  OLSH_ACCEPT_COUNT      INTEGER                DEFAULT 0,
  OLSH_TOTAL_COUNT       INTEGER                DEFAULT 0,
  OLSH_CREATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  OLSH_CREATE_USER       VARCHAR2(20 BYTE),
  OLSH_UPDATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  OLSH_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_STATEMENT_HEADER_PK ON OL_STATEMENT_HEADER
(OLSH_FILENAME)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

CREATE INDEX OL_STATEMENT_HEADER_IDX01 ON OL_STATEMENT_HEADER
(OLSH_INT_BANK_CODE, OLSH_BANK_ACCT_NUM)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_STATEMENT_HEADER ADD (
  CONSTRAINT OL_STATEMENT_HEADER_PK
  PRIMARY KEY
  (OLSH_FILENAME)
  USING INDEX OL_STATEMENT_HEADER_PK
  ENABLE VALIDATE);

ALTER TABLE OL_STATEMENT_HEADER ADD (
  CONSTRAINT OL_STATEMENT_HEADER_FK01 
  FOREIGN KEY (OLSH_INT_BANK_CODE, OLSH_BANK_ACCT_NUM) 
  REFERENCES OL_BANK_ACCTS (OB_INT_BANK_CODE,OB_BANK_ACCT_NUM)
  ENABLE VALIDATE);

