OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLBatchEngineActionLog
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLBatchEngineActionLog.so
SOOBJS =  OLBatchEngineActionLog.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
