OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOMiAcr
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOMiAcr.so
SOOBJS = BOMiAcr.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
