ALTER TABLE PAR_MERCH_PROFILE
 DROP PRIMARY KEY CASCADE;

DROP TABLE PAR_MERCH_PROFILE CASCADE CONSTRAINTS;

CREATE TABLE PAR_MERCH_PROFILE
(
  PMP_MERCH_ACCOUNT_NMB  VARCHAR2(50 BYTE),
  PMP_COMPANY_NAME	 VARCHAR2(400 BYTE),
  PMP_USERNAME           VARCHAR2(100 BYTE),
  PMP_API_MERCH_ID       VARCHAR2(30 BYTE),
  PMP_ACK_URL            VARCHAR2(200 BYTE),
  PMP_PAYOUT_ENABLE	 INTEGER,
  PMP_SERVICE		 VARCHAR2(3 BYTE),
  PMP_PH_MERCH_ID	 VARCHAR2(15 BYTE),
  PMP_CREATE_TIMESTAMP	 DATE	DEFAULT sysdate,
  PMP_CREATE_USER	 VARCHAR2(20 BYTE),
  PMP_UPDATE_TIMESTAMP	 DATE	DEFAULT sysdate,
  PMP_UPDATE_USER	 VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PAR_MERCH_PROFILE_PK ON PAR_MERCH_PROFILE
(PMP_MERCH_ACCOUNT_NMB)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PAR_MERCH_PROFILE ADD (
  CONSTRAINT PAR_MERCH_PROFILE_PK
  PRIMARY KEY
  (PMP_MERCH_ACCOUNT_NMB)
  USING INDEX PAR_MERCH_PROFILE_PK
  ENABLE VALIDATE);


CREATE INDEX PAR_MERCH_PROFILE_IDX01 ON PAR_MERCH_PROFILE
(PMP_COMPANY_NAME)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;
