OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnWebOnUsROG
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnWebOnUsROG.so
SOOBJS = TxnWebOnUsROG.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
