CREATE TABLE DEF_OFFSET_TXN_BAL_TYPE
(
  OTBT_TYPE              CHAR(1 BYTE),
  OTBT_DESC              VARCHAR2(50 BYTE),
  OTBT_PARTY_TYPE        CHAR(1 BYTE),
  OTBT_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  OTBT_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  OTBT_CREATE_USER       VARCHAR2(20 BYTE),
  OTBT_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEF_OFFSET_TXN_BAL_TYPE_PK ON DEF_OFFSET_TXN_BAL_TYPE
(OTBT_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_OFFSET_TXN_BAL_TYPE ADD (
  CONSTRAINT DEF_OFFSET_TXN_BAL_TYPE_PK
  PRIMARY KEY
  (OTBT_TYPE)
  USING INDEX DEF_OFFSET_TXN_BAL_TYPE_PK
  ENABLE VALIDATE);

ALTER TABLE DEF_OFFSET_TXN_BAL_TYPE ADD (
  CONSTRAINT DEF_OFFSET_TXN_BAL_TYPE_FK01 
  FOREIGN KEY (OTBT_PARTY_TYPE) 
  REFERENCES DEF_PARTY_TYPE (DP_TYPE)
  ENABLE VALIDATE);

