ALTER TABLE MMS_ACR_BAL
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_ACR_BAL CASCADE CONSTRAINTS;

CREATE TABLE MMS_ACR_BAL
(
  MAB_ENTITY_ID         VARCHAR2(20 BYTE),
  MAB_ORG_CCY           VARCHAR2(3 BYTE),
  MAB_CCY               VARCHAR2(3 BYTE),
  MAB_BAL               NUMBER(14,2)            DEFAULT 0,
  MAB_RATE              NUMBER(14,5)            DEFAULT 1,
  MAB_RATIO             NUMBER(6,5)             DEFAULT 0,
  MAB_CREATE_TIMESTAMP  DATE,
  MAB_CREATE_USER       VARCHAR2(20 BYTE),
  MAB_UPDATE_TIMESTAMP  DATE,
  MAB_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MMS_ACR_BAL_PK ON MMS_ACR_BAL
(MAB_ENTITY_ID, MAB_ORG_CCY, MAB_CCY)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_ACR_BAL ADD (
  CONSTRAINT MMS_ACR_BAL_PK
  PRIMARY KEY
  (MAB_ENTITY_ID, MAB_ORG_CCY, MAB_CCY)
  USING INDEX MMS_ACR_BAL_PK
  ENABLE VALIDATE);

