ALTER TABLE PHUSER.CONV_STORE_MAPPING
 DROP PRIMARY KEY CASCADE;

DROP TABLE PHUSER.CONV_STORE_MAPPING CASCADE CONSTRAINTS;

CREATE TABLE PHUSER.CONV_STORE_MAPPING
(
  CM_CHANNEL_CODE      CHAR(3 BYTE),
  CM_CODE              VARCHAR2(10 BYTE),
  CM_EXT_CODE          VARCHAR2(10 BYTE),
  CM_TYPE              CHAR(2 BYTE),
  CM_DISABLED          INTEGER,
  CM_EFFECT_DATE       DATE,
  CM_DESC              VARCHAR2(50 BYTE),
  CM_CREATE_TIMESTAMP  DATE,
  CM_UPDATE_TIMESTAMP  DATE,
  CM_CREATE_USER       VARCHAR2(20 BYTE),
  CM_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PHUSER.CONV_STORE_MAPPING_PK ON PHUSER.CONV_STORE_MAPPING
(CM_CHANNEL_CODE, CM_CODE, CM_EXT_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE PHUSER.CONV_STORE_MAPPING ADD (
  CONSTRAINT CONV_STORE_MAPPING_PK
  PRIMARY KEY
  (CM_CHANNEL_CODE, CM_CODE, CM_EXT_CODE)
  USING INDEX PHUSER.CONV_STORE_MAPPING_PK);

