OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnOmtByUsOPR
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnOmtByUsOPR.so
SOOBJS = TxnOmtByUsOPR.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
