OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLPayoutApproveTmp
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLPayoutApproveTmp.so
SOOBJS =  OLPayoutApproveTmp.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
