OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MiAcrInOutHistory
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMiAcrInOutHistory.so
SOOBJS =  MiAcrInOutHistory.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
