OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/Language
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBLanguage.so
SOOBJS =  Language.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
