ALTER TABLE PAR_PSP_ID_KEY_MAP
 DROP PRIMARY KEY CASCADE;

DROP TABLE PAR_PSP_ID_KEY_MAP CASCADE CONSTRAINTS;

CREATE TABLE PAR_PSP_ID_KEY_MAP
(
  IK_PSP_TYPE_CODE     VARCHAR2(50 BYTE),
  IK_PSP_MERCHANT_ID   VARCHAR2(15 BYTE),
  IK_PSP_KEY_TYPE      VARCHAR2(3 BYTE),
  IK_PSP_KEY_VALUE     VARCHAR2(128 BYTE),
  IK_CONVERTED         INTEGER,
  IK_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  IK_CREATE_USER       VARCHAR2(20 BYTE),
  IK_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  IK_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PAR_PSP_ID_KEY_MAP_PK ON PAR_PSP_ID_KEY_MAP
(IK_PSP_TYPE_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PAR_PSP_ID_KEY_MAP ADD (
  CONSTRAINT PAR_PSP_ID_KEY_MAP_PK
  PRIMARY KEY
  (IK_PSP_TYPE_CODE)
  USING INDEX PAR_PSP_ID_KEY_MAP_PK
  ENABLE VALIDATE);

