OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/PspSmallAmt
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBPspSmallAmt.so
SOOBJS =  PspSmallAmt.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
