OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLMerchPspBatchType
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLMerchPspBatchType.so
SOOBJS =  OLMerchPspBatchType.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
