OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLNonTxnMsgHeader
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLNonTxnMsgHeader.so
SOOBJS =  OLNonTxnMsgHeader.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
