OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/RuleCustomerTxnCap
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBRuleCustomerTxnCap.so
SOOBJS =  RuleCustomerTxnCap.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
