DROP TABLE PHUSER.OL_ENGINE_SQL CASCADE CONSTRAINTS;

CREATE TABLE PHUSER.OL_ENGINE_SQL
(
  OES_ENGINE_TYPE       VARCHAR2(10 BYTE),
  OES_ACTION_TYPE       VARCHAR2(50 BYTE),
  OES_SQL_TYPE          VARCHAR2(50 BYTE),
  OES_SQL               VARCHAR2(2000 BYTE),
  OES_DISABLED          INTEGER                 DEFAULT 0,
  OES_CREATE_USER       VARCHAR2(20 BYTE),
  OES_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  OES_UPDATE_USER       VARCHAR2(20 BYTE),
  OES_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

