OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/TxnBalanceDetail
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBTxnBalanceDetail.so
SOOBJS = TxnBalanceDetail.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
