OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLAutoUploadJobStatus
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLAutoUploadJobStatus.so
SOOBJS =  OLAutoUploadJobStatus.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
