ALTER TABLE DEF_TXN_STATUS_MAP
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_TXN_STATUS_MAP CASCADE CONSTRAINTS;

CREATE TABLE DEF_TXN_STATUS_MAP
(
  DM_TYPE              CHAR(1 BYTE),
  DM_STATUS            CHAR(1 BYTE),
  DM_AR_IND            CHAR(1 BYTE)             DEFAULT ' ',
  DM_TXN_CODE          CHAR(3 BYTE),
  DM_STATUS_DESC       VARCHAR2(50 BYTE),
  DM_CREATE_USER       VARCHAR2(20 BYTE),
  DM_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  DM_UPDATE_USER       VARCHAR2(20 BYTE),
  DM_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN DEF_TXN_STATUS_MAP.DM_TYPE IS '''A'' - Admin ''M'' - Merchant';



CREATE UNIQUE INDEX DEF_TXN_STATUS_MAP_PK ON DEF_TXN_STATUS_MAP
(DM_TYPE, DM_STATUS, DM_AR_IND, DM_TXN_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_TXN_STATUS_MAP ADD (
  CONSTRAINT DEF_TXN_STATUS_MAP_PK
  PRIMARY KEY
  (DM_TYPE, DM_STATUS, DM_AR_IND, DM_TXN_CODE)
  USING INDEX DEF_TXN_STATUS_MAP_PK
  ENABLE VALIDATE);

