DROP TABLE PAR_PAYOUT_STATUS CASCADE CONSTRAINTS;

CREATE TABLE PAR_PAYOUT_STATUS
(
  PS_STATUS            VARCHAR2(50 BYTE),
  PS_STATUS_ID         INTEGER,
  PS_CREATE_TIMESTAMP  DATE,
  PS_CREATE_USER       VARCHAR2(20 BYTE),
  PS_UPDATE_TIMESTAMP  DATE,
  PS_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

