CREATE OR REPLACE FUNCTION SP_HIST_OL_BTINTERSUMCOL_BYDAY
RETURN NUMBER IS
	EXP_ERR EXCEPTION;
BEGIN
  /*
  Anonymous block for initiate
 DECLARE
	V_INPUT_DATE DATE;
	LOOP_DATE INTEGER;
 BEGIN 
	SELECT (TRUNC(sysdate) - TRUNC(MAX(HB_END_DATE)) - 1) INTO LOOP_DATE FROM HIST_OL_BT_INTER_SUM_BATCH;
		FOR X IN 1..LOOP_DATE LOOP
	SELECT MAX(HB_END_DATE) + 1
		INTO V_INPUT_DATE
	FROM HIST_OL_BT_INTER_SUM_BATCH
		WHERE HB_DISABLED = 0;
		-- Run Batch Function
		HIST_OL_BT_INTER_SUM_COLLECT(V_INPUT_DATE);
	END LOOP;
 END;
  */
  -- DBMS_OUTPUT.PUT_LINE('>>> START [HIST_OL_BT_INTER_SUM_COL_BYDAY] <<<');
  -- Run Batch Function
	RETURN SP_HIST_OL_BT_INTERSUM_COLLECT(TRUNC(sysdate) - 1/24/60);

EXCEPTION
WHEN EXP_ERR THEN
	ROLLBACK;
--DBMS_OUTPUT.PUT_LINE('Error : no record!...');
	RETURN 1;
WHEN OTHERS THEN
	ROLLBACK;
--DBMS_OUTPUT.PUT_LINE('Error : Other error!...');
--RAISE_APPLICATION_ERROR( -20202, 'Error code ' || SQLCODE|| ': ' || SUBSTR(SQLERRM, 1 , 64) );
	RETURN 9;
END SP_HIST_OL_BTINTERSUMCOL_BYDAY;
/
