ALTER TABLE MMS_INSTANT_PM_ACCT_DT
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_INSTANT_PM_ACCT_DT CASCADE CONSTRAINTS;

CREATE TABLE MMS_INSTANT_PM_ACCT_DT
(
  MID_PARTY_TYPE        CHAR(1 BYTE),
  MID_BUSINESS_TYPE     CHAR(1 BYTE)            NOT NULL,
  MID_PARTY_ID          VARCHAR2(15 BYTE),
  MID_PARTY_NAME        VARCHAR2(50 BYTE),
  MID_MMS_NODE_ID       VARCHAR2(5 BYTE),
  MID_CREATE_USER        VARCHAR2(20 BYTE),
  MID_UPDATE_USER       VARCHAR2(20 BYTE),
  MID_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  MID_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;



CREATE UNIQUE INDEX MMS_INSTANT_PM_ACCT_DT_PK ON MMS_INSTANT_PM_ACCT_DT
(MID_PARTY_TYPE, MID_BUSINESS_TYPE, MID_PARTY_ID, MID_MMS_NODE_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_INSTANT_PM_ACCT_DT ADD (
  CONSTRAINT MMS_INSTANT_PM_ACCT_DT_PK
  PRIMARY KEY
  (MID_PARTY_TYPE, MID_BUSINESS_TYPE, MID_PARTY_ID, MID_MMS_NODE_ID)
  USING INDEX MMS_INSTANT_PM_ACCT_DT_PK
  ENABLE VALIDATE);
