ALTER TABLE RULE_EMAIL_NOTIFICATION
 DROP PRIMARY KEY CASCADE;

DROP TABLE RULE_EMAIL_NOTIFICATION CASCADE CONSTRAINTS;

CREATE TABLE RULE_EMAIL_NOTIFICATION
(
  RE_EMAIL_ID          INTEGER,
  RE_PARTY_TYPE        CHAR(1 BYTE),
  RE_PARTY_ID          VARCHAR2(15 BYTE),
  RE_FUNCT             VARCHAR2(10 BYTE),
  RE_DISABLED          INTEGER,
  RE_CREATE_USER       VARCHAR2(20 BYTE),
  RE_UPDATE_USER       VARCHAR2(20 BYTE),
  RE_CREATE_TIMESTAMP  DATE,
  RE_UPDATE_TIMESTAMP  DATE
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX RULE_EMAIL_NOTIFICATION_IDX01 ON RULE_EMAIL_NOTIFICATION
(RE_FUNCT, RE_PARTY_TYPE, RE_PARTY_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RULE_EMAIL_NOTIFICATION_PK ON RULE_EMAIL_NOTIFICATION
(RE_EMAIL_ID, RE_PARTY_TYPE, RE_PARTY_ID, RE_FUNCT)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE RULE_EMAIL_NOTIFICATION ADD (
  CONSTRAINT RULE_EMAIL_NOTIFICATION_PK
  PRIMARY KEY
  (RE_EMAIL_ID, RE_PARTY_TYPE, RE_PARTY_ID, RE_FUNCT)
  USING INDEX RULE_EMAIL_NOTIFICATION_PK
  ENABLE VALIDATE);

ALTER TABLE RULE_EMAIL_NOTIFICATION ADD (
  CONSTRAINT RUEL_EMAIL_NOTIFICATION_FK03 
  FOREIGN KEY (RE_EMAIL_ID) 
  REFERENCES EMAIL_NOTIFY_LIST (EL_ID)
  ENABLE VALIDATE,
  CONSTRAINT RULE_EMAIL_NOTIFICATION_FK01 
  FOREIGN KEY (RE_PARTY_TYPE) 
  REFERENCES DEF_PARTY_TYPE (DP_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT RULE_EMAIL_NOTIFICATION_FK02 
  FOREIGN KEY (RE_FUNCT) 
  REFERENCES DEF_EMAIL_NOTIFY_FUNCT (EF_FUNCT)
  ENABLE VALIDATE);

