ALTER TABLE DEF_PARTY_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_PARTY_TYPE CASCADE CONSTRAINTS;

CREATE TABLE DEF_PARTY_TYPE
(
  DP_TYPE              CHAR(1 BYTE)             NOT NULL,
  DP_DESC              VARCHAR2(50 BYTE),
  DP_CREATE_USER       VARCHAR2(20 BYTE),
  DP_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  DP_UPDATE_USER       VARCHAR2(20 BYTE),
  DP_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEF_PARTY_TYPE_PK ON DEF_PARTY_TYPE
(DP_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_PARTY_TYPE ADD (
  CONSTRAINT DEF_PARTY_TYPE_PK
  PRIMARY KEY
  (DP_TYPE)
  USING INDEX DEF_PARTY_TYPE_PK);


