OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOAdjustment
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOAdjustment.so
SOOBJS = BOAdjustment.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
