ALTER TABLE RULE_TIER
 DROP PRIMARY KEY CASCADE;

DROP TABLE RULE_TIER CASCADE CONSTRAINTS;

CREATE TABLE RULE_TIER
(
  RT_ID                INTEGER,
  RT_DESC              VARCHAR2(50 BYTE),
  RT_MIN_VALUE         NUMBER(14,2)             DEFAULT 0,
  RT_MAX_VALUE         NUMBER(14,2)             DEFAULT 0,
  RT_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  RT_CREATE_USER       VARCHAR2(20 BYTE),
  RT_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  RT_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX RULE_TIER_PK ON RULE_TIER
(RT_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE RULE_TIER ADD (
  CONSTRAINT RULE_TIER_PK
  PRIMARY KEY
  (RT_ID)
  USING INDEX RULE_TIER_PK
  ENABLE VALIDATE);

