OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=test_enc_txn_id.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o test_enc_txn_id.o 
#
#
# Include the Common Rules
#
#

include ../../Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
