OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=test_newround.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o test_newround.o 
#
#
# Include the Common Rules
#
#

include ../../Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
