ALTER TABLE HYB_MEMBER_DETAIL
 DROP PRIMARY KEY CASCADE;

DROP TABLE HYB_MEMBER_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE HYB_MEMBER_DETAIL
(
  EM_EMAIL             VARCHAR2(256 BYTE)       NOT NULL,
  EM_DOMAIN            NUMBER                   NOT NULL,
  EM_PWD               VARCHAR2(100 BYTE)       NOT NULL,
  EM_FIRST_NAME        VARCHAR2(50 BYTE)        NOT NULL,
  EM_LAST_NAME         VARCHAR2(50 BYTE)        NOT NULL,
  EM_CHINESE_NAME      VARCHAR2(150 BYTE)       NOT NULL,
  EM_GENDER            CHAR(1 BYTE)             NOT NULL,
  EM_DOB               VARCHAR2(8 BYTE)         NOT NULL,
  EM_DISABLED          NUMBER(1)                DEFAULT 0,
  EM_COUNTRY           CHAR(2 BYTE)             NOT NULL,
  EM_CREATE_TIMESTAMP  DATE                     DEFAULT SYSDATE,
  EM_UPDATE_TIMESTAMP  DATE                     DEFAULT SYSDATE,
  EM_CREATE_USER       VARCHAR2(20 BYTE),
  EM_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX HYB_MEMBER_DETAIL_PK ON HYB_MEMBER_DETAIL
(EM_EMAIL, EM_DOMAIN)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE HYB_MEMBER_DETAIL ADD (
  CONSTRAINT HYB_MEMBER_DETAIL_PK
  PRIMARY KEY
  (EM_EMAIL, EM_DOMAIN)
  USING INDEX HYB_MEMBER_DETAIL_PK
  ENABLE VALIDATE);

