ALTER TABLE OL_RULE_AM_RECUR_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_RULE_AM_RECUR_TYPE CASCADE CONSTRAINTS;

CREATE TABLE OL_RULE_AM_RECUR_TYPE
(
  RAT_ID                INTEGER,
  RAT_DAY               INTEGER,
  RAT_START_TIME        VARCHAR2(6 BYTE)         NOT NULL,
  RAT_END_TIME          VARCHAR2(6 BYTE),
  RAT_INTERVAL          INTEGER,
  RAT_DESC              VARCHAR2(50 BYTE),
  RAT_DISABLED          INTEGER                  DEFAULT 0,
  RAT_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  RAT_CREATE_USER       VARCHAR2(20 BYTE),
  RAT_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  RAT_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_RULE_AM_RECUR_TYPE_PK ON OL_RULE_AM_RECUR_TYPE
(RAT_ID, RAT_DAY, RAT_START_TIME)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_RULE_AM_RECUR_TYPE ADD (
  CONSTRAINT OL_RULE_AM_RECUR_TYPE_PK
  PRIMARY KEY
  (RAT_ID, RAT_DAY, RAT_START_TIME)
  USING INDEX OL_RULE_AM_RECUR_TYPE_PK
  ENABLE VALIDATE);

