ALTER TABLE MI_ENTITY_RSP
 DROP PRIMARY KEY CASCADE;

DROP TABLE MI_ENTITY_RSP CASCADE CONSTRAINTS;

CREATE TABLE MI_ENTITY_RSP
(
  ER_ENTITY_ID         VARCHAR2(10 BYTE),
  ER_RSP_ID            VARCHAR2(10 BYTE)        NOT NULL,
  ER_RSP_NAME          VARCHAR2(50 BYTE),
  ER_RSP_NODE_ID       VARCHAR2(5 BYTE),
  ER_RSP_STATUS        VARCHAR2(2 BYTE),
  ER_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  ER_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  ER_CREATE_USER       VARCHAR2(20 BYTE),
  ER_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MI_ENTITY_RSP_PK ON MI_ENTITY_RSP
(ER_RSP_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX MI_ENTITY_RSP_UK ON MI_ENTITY_RSP
(ER_ENTITY_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MI_ENTITY_RSP ADD (
  CONSTRAINT MI_ENTITY_RSP_PK
  PRIMARY KEY
  (ER_RSP_ID)
  USING INDEX MI_ENTITY_RSP_PK
  ENABLE VALIDATE,
  CONSTRAINT MI_ENTITY_RSP_UK
  UNIQUE (ER_ENTITY_ID)
  USING INDEX MI_ENTITY_RSP_UK
  ENABLE VALIDATE);

ALTER TABLE MI_ENTITY_RSP ADD (
  CONSTRAINT MI_ENTITY_RSP_FK01 
  FOREIGN KEY (ER_ENTITY_ID) 
  REFERENCES MI_ENTITY_DETAIL (ED_ENTITY_ID)
  ENABLE VALIDATE,
  CONSTRAINT MI_ENTITY_RSP_FK02 
  FOREIGN KEY (ER_RSP_NODE_ID) 
  REFERENCES MMX_NODES (MN_NODE_ID)
  ENABLE VALIDATE,
  CONSTRAINT MI_ENTITY_RSP_FK03 
  FOREIGN KEY (ER_RSP_STATUS) 
  REFERENCES DEF_STATUS (DS_TYPE)
  ENABLE VALIDATE);

