ALTER TABLE MMS_ENTITY_TXN_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_ENTITY_TXN_TYPE CASCADE CONSTRAINTS;

CREATE TABLE MMS_ENTITY_TXN_TYPE
(
  MTT_TXN_TYPE          VARCHAR2(5 BYTE),
  MTT_DESC              VARCHAR2(50 BYTE),
  MTT_CREATE_USER       VARCHAR2(20 BYTE),
  MTT_CREATE_TIMESTAMP  DATE,
  MTT_UPDATE_USER       VARCHAR2(20 BYTE),
  MTT_UPDATE_TIMESTAMP  DATE
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MMS_ENTITY_TXN_TYPE_PK ON MMS_ENTITY_TXN_TYPE
(MTT_TXN_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_ENTITY_TXN_TYPE ADD (
  CONSTRAINT MMS_ENTITY_TXN_TYPE_PK
  PRIMARY KEY
  (MTT_TXN_TYPE)
  USING INDEX MMS_ENTITY_TXN_TYPE_PK
  ENABLE VALIDATE);

