


CREATE TABLE OL_STMT_MATCH_CONFIG
(
  OSMC_INT_BANK_CODE     VARCHAR2(10 BYTE)      NOT NULL,
  OSMC_BANK_ACCT_TYPE    CHAR(3 BYTE)           NOT NULL,
  OSMC_TXN_CODE          CHAR(3 BYTE)           NOT NULL,
  OSMC_CODE              VARCHAR2(50 BYTE)      NOT NULL,
  OSMC_VAL               VARCHAR2(1024 BYTE),
  OSMC_DISABLED          INTEGER                DEFAULT 0,
  OSMC_CREATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  OSMC_CREATE_USER       VARCHAR2(20 BYTE),
  OSMC_UPDATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  OSMC_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE INDEX OL_STMT_MATCH_CONFIG_IDX01 ON OL_STMT_MATCH_CONFIG
(OSMC_BANK_ACCT_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX OL_STMT_MATCH_CONFIG_PK ON OL_STMT_MATCH_CONFIG
(OSMC_INT_BANK_CODE, OSMC_BANK_ACCT_TYPE, OSMC_TXN_CODE, OSMC_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE OL_STMT_MATCH_CONFIG ADD (
  CONSTRAINT OL_STMT_MATCH_CONFIG_PK
  PRIMARY KEY
  (OSMC_INT_BANK_CODE, OSMC_BANK_ACCT_TYPE, OSMC_TXN_CODE, OSMC_CODE)
  USING INDEX OL_STMT_MATCH_CONFIG_PK
  ENABLE VALIDATE);

ALTER TABLE OL_STMT_MATCH_CONFIG ADD (
  CONSTRAINT OL_STMT_MATCH_CONFIG_FK01 
  FOREIGN KEY (OSMC_INT_BANK_CODE) 
  REFERENCES DEF_BANK (DB_INT_BANK_CODE)
  ENABLE VALIDATE,
  CONSTRAINT OL_STMT_MATCH_CONFIG_FK02 
  FOREIGN KEY (OSMC_BANK_ACCT_TYPE) 
  REFERENCES OL_DEF_BANK_ACCT_TYPE (OBC_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OL_STMT_MATCH_CONFIG_FK03 
  FOREIGN KEY (OSMC_TXN_CODE) 
  REFERENCES TXN_CODE (TC_CODE)
  ENABLE VALIDATE,
  CONSTRAINT OL_STMT_MATCH_CONFIG_FK04
  FOREIGN KEY (OSMC_CODE)
  REFERENCES OL_DEF_ENGINE_CONFIG_CODE (ECC_CODE)
  ENABLE VALIDATE);

