OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLTxnDepositHoldLog
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLTxnDepositHoldLog.so
SOOBJS =  OLTxnDepositHoldLog.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
