ALTER TABLE TMA_LOG
 DROP PRIMARY KEY CASCADE;

DROP TABLE TMA_LOG CASCADE CONSTRAINTS;

CREATE TABLE TMA_LOG
(
  T_TXN_ID           VARCHAR2(16 BYTE),
  T_IP_ADDRESS        VARCHAR2(20 BYTE),
  T_CREATE_USER       VARCHAR2(20 BYTE),
  T_CREATE_TIMESTAMP  DATE
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX TMA_LOG_PK ON TMA_LOG
(T_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE TMA_LOG ADD (
  CONSTRAINT TMA_LOG_PK
  PRIMARY KEY
  (T_TXN_ID)
  USING INDEX TMA_LOG_PK);

ALTER TABLE TMA_LOG ADD (
  CONSTRAINT TMA_LOG_FK01 
  FOREIGN KEY (T_TXN_ID) 
  REFERENCES TXN_HEADER (TH_TXN_ID));

