ALTER TABLE CPHUSER.MERCH_URL
 DROP PRIMARY KEY CASCADE;

DROP TABLE CPHUSER.MERCH_URL CASCADE CONSTRAINTS;

CREATE TABLE CPHUSER.MERCH_URL
(
  MERCHANT_ID       VARCHAR2(10 BYTE)           NOT NULL,
  URL               VARCHAR2(100 BYTE)          NOT NULL,
  CREATE_TIMESTAMP  DATE                        NOT NULL,
  UPDATE_TIMESTAMP  DATE                        NOT NULL,
  CREATE_USER       VARCHAR2(20 BYTE)           NOT NULL
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CPHUSER.MERCH_URL_PK ON CPHUSER.MERCH_URL
(MERCHANT_ID, URL)
LOGGING
TABLESPACE USER_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE CPHUSER.MERCH_URL ADD (
  CONSTRAINT MERCH_URL_PK
  PRIMARY KEY
  (MERCHANT_ID, URL)
  USING INDEX CPHUSER.MERCH_URL_PK);

