OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmsEntityFXBalHistory
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmsEntityFXBalHistory.so
SOOBJS =  MmsEntityFXBalHistory.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
