OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLRulePayoutPsp
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLRulePayoutPsp.so
SOOBJS =  OLRulePayoutPsp.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
