OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/PayoutReturnBatchDt
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBPayoutReturnBatchDt.so
SOOBJS =  PayoutReturnBatchDt.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
