OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmsKeys
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmsKeys.so
SOOBJS =  MmsKeys.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
