ALTER TABLE OL_RULE_DEPOSIT_MATCHING
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_RULE_DEPOSIT_MATCHING CASCADE CONSTRAINTS;

CREATE TABLE OL_RULE_DEPOSIT_MATCHING
(
  ORDM_MERCHANT_ID              VARCHAR2(15 BYTE),
  ORDM_INT_BANK_CODE            VARCHAR2(10 BYTE),
  ORDM_BIZ_ONUS_BF_MINS         INTEGER,
  ORDM_BIZ_ONUS_AF_MINS         INTEGER,
  ORDM_BIZ_OFFUS_BF_MINS        INTEGER,
  ORDM_BIZ_OFFUS_AF_MINS        INTEGER,
  ORDM_NON_BIZ_ONUS_BF_MINS     INTEGER,
  ORDM_NON_BIZ_ONUS_AF_MINS     INTEGER,
  ORDM_NON_BIZ_OFFUS_BF_MINS    INTEGER,
  ORDM_NON_BIZ_OFFUS_AF_MINS    INTEGER,
  ORDM_AF_NON_BIZ_ONUS_BF_MINS  INTEGER,
  ORDM_AF_NON_BIZ_ONUS_AF_MINS  INTEGER,
  ORDM_AF_NON_BIZ_OFFUS_BF_MINS INTEGER,
  ORDM_AF_NON_BIZ_OFFUS_AF_MINS INTEGER,
  ORDM_CREATE_TIMESTAMP         DATE              DEFAULT sysdate,
  ORDM_CREATE_USER              VARCHAR2(20 BYTE),
  ORDM_UPDATE_TIMESTAMP         DATE              DEFAULT sysdate,
  ORDM_UPDATE_USER              VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_RULE_DEPOSIT_MATCHING_PK ON OL_RULE_DEPOSIT_MATCHING
(ORDM_MERCHANT_ID, ORDM_INT_BANK_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_RULE_DEPOSIT_MATCHING ADD (
  CONSTRAINT OL_RULE_DEPOSIT_MATCHING_PK
  PRIMARY KEY
  (ORDM_MERCHANT_ID, ORDM_INT_BANK_CODE)
  USING INDEX OL_RULE_DEPOSIT_MATCHING_PK
  ENABLE VALIDATE);

ALTER TABLE OL_RULE_DEPOSIT_MATCHING ADD (
  CONSTRAINT OL_RULE_DEPOSIT_MATCHING_FK01
  FOREIGN KEY (ORDM_MERCHANT_ID)
  REFERENCES OL_MERCH_DETAIL (MD_MERCHANT_ID)
  ENABLE VALIDATE);

ALTER TABLE OL_RULE_DEPOSIT_MATCHING ADD (
  CONSTRAINT OL_RULE_DEPOSIT_MATCHING_FK02 
  FOREIGN KEY (ORDM_INT_BANK_CODE) 
  REFERENCES DEF_BANK (DB_INT_BANK_CODE)
  ENABLE VALIDATE);

