ALTER TABLE DEF_SERVICE_CODE
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_SERVICE_CODE CASCADE CONSTRAINTS;

CREATE TABLE DEF_SERVICE_CODE
(
  SC_CODE                  CHAR(3 BYTE),
  SC_DESC                  VARCHAR2(50 BYTE),
  SC_CREATE_TIMESTAMP      DATE                 DEFAULT sysdate,
  SC_CREATE_USER           VARCHAR2(20 BYTE),
  SC_UPDATE_TIMESTAMP      DATE                 DEFAULT sysdate,
  SC_UPDATE_USER           VARCHAR2(20 BYTE),
  SC_SELECT_BANK           INTEGER              DEFAULT 0,
  SC_USE_LB                INTEGER              DEFAULT 0,
  SC_VOID_PAYOUT_WITH_FEE  INTEGER              DEFAULT 0,
  SC_ALLOW_BAL_NEGATIVE    INTEGER              DEFAULT 0
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEF_SERVICE_CODE_PK ON DEF_SERVICE_CODE
(SC_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_SERVICE_CODE ADD (
  CONSTRAINT SERVICE_CODE_PK
  PRIMARY KEY
  (SC_CODE)
  USING INDEX DEF_SERVICE_CODE_PK
  ENABLE VALIDATE);

