OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOTxnLimit
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOTxnLimit.so
SOOBJS = BOTxnLimit.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
