ALTER TABLE CPHUSER.PSP_URL
 DROP PRIMARY KEY CASCADE;

DROP TABLE CPHUSER.PSP_URL CASCADE CONSTRAINTS;

CREATE TABLE CPHUSER.PSP_URL
(
  PSP_ID            VARCHAR2(10 BYTE),
  URL               VARCHAR2(100 BYTE)          NOT NULL,
  EFFECT_DATE       VARCHAR2(8 BYTE)            NOT NULL,
  CREATE_TIMESTAMP  DATE,
  UPDATE_TIMESTAMP  DATE,
  CREATE_USER       VARCHAR2(20 BYTE),
  UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CPHUSER.PSP_URL_PK ON CPHUSER.PSP_URL
(PSP_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE CPHUSER.PSP_URL ADD (
  CONSTRAINT PSP_URL_PK
  PRIMARY KEY
  (PSP_ID)
  USING INDEX CPHUSER.PSP_URL_PK);

