OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=mig_payout_upload.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o mig_bo_funct.o mig_funct.o mig_log_funct.o mig_payout_upload.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
