OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=mig_merchant_balance.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o mig_merchant_balance.o
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
