#ifndef _MIG_PAYOUT_UPLOAD_H
#define _MIG_PAYOUT_UPLOAD_H
#include "common.h"

#define PD_MY_DELIMITOR			","
#define PD_MY_TOKEN			'"'

#define PD_MERCH_ACCOUNT_NMB_LEN 	50
#define	NUM_OF_CHAR			26
#define MAX_NUM_OF_RECORD		2000
#define	IMPORT_MAX_FILE			40
#define	IMPORT_FIELD_LEN		200

#define PD_PAYOUT_STATUS_TYPE_LEN	2

#define	IDX_HEADER_REF_ID		0
#define	IDX_HEADER_ACCT_NMB		1
#define	IDX_HEADER_IMPORT_ERR		3
#define	IDX_HEADER_FILEPREFIX		4
#define	IDX_HEADER_FILENAME		5
#define	IDX_HEADER_STATUS		6
#define	IDX_HEADER_TOTAL_COUNT		7
#define	IDX_HEADER_TOTAL_AMT		9
#define	IDX_HEADER_DATETIME		11

#define	IDX_DETAIL_REF_ID		2
#define IDX_DETAIL_COUNTRY		5
#define	IDX_DETAIL_STATUS		6
#define	IDX_DETAIL_SEQ_NUM		7
#define IDX_DETAIL_DST_CCY_CD		8
#define	IDX_DETAIL_PAYOUT_AMT		9
#define IDX_DETAIL_REQ_CCY_CD		10
#define IDX_DETAIL_REQ_AMT		11
#define IDX_DETAIL_MEMBER_FEE_CCY_CD	12
#define IDX_DETAIL_MEMBER_FEE		13
#define IDX_DETAIL_MERCHANT_FEE_CCY_CD	14
#define IDX_DETAIL_MERCHANT_FEE		15
#define IDX_DETAIL_MARKUP_CCY_CD	16
#define IDX_DETAIL_MARKUP		17
#define IDX_DETAIL_EX_RATE		18
#define	IDX_DETAIL_TXN_SEQ		19
#define	IDX_DETAIL_AUX_TXN_SEQ		20
#define	IDX_DETAIL_MERCHANT_REF		21
#define IDX_DETAIL_ACCOUNT_NUM		22
#define	IDX_DETAIL_ACCOUNT_NAME		23
#define	IDX_DETAIL_BANK_NAME		24
#define	IDX_DETAIL_BRANCH		25
#define	IDX_DETAIL_PROVINCE		26
#define	IDX_DETAIL_CITY			27
#define IDX_DETAIL_IDENTITY_ID		28
#define IDX_DETAIL_PHONE		29
#define IDX_DETAIL_BANK_CODE		30
#define	IDX_DETAIL_REMARK		31
#define	IDX_DETAIL_TIME			32


#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif


#endif
