ALTER TABLE PAR_INT_BANK_CODE_MAP
 DROP PRIMARY KEY CASCADE;

DROP TABLE PAR_INT_BANK_CODE_MAP CASCADE CONSTRAINTS;

CREATE TABLE PAR_INT_BANK_CODE_MAP
(
  BC_BANK_NAME         VARCHAR2(80 BYTE),
  BC_INT_BANK_CODE     VARCHAR2(10 BYTE),
  BC_SPECIAL_PSP_CHANNEL VARCHAR2(10 BYTE),
  BC_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  BC_CREATE_USER       VARCHAR2(20 BYTE),
  BC_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  BC_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PAR_INT_BANK_CODE_MAP_PK ON PAR_INT_BANK_CODE_MAP
(BC_BANK_NAME, BC_SPECIAL_PSP_CHANNEL)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PAR_INT_BANK_CODE_MAP ADD (
  CONSTRAINT PAR_INT_BANK_CODE_MAP_PK
  PRIMARY KEY
  (BC_BANK_NAME, BC_SPECIAL_PSP_CHANNEL)
  USING INDEX PAR_INT_BANK_CODE_MAP_PK
  ENABLE VALIDATE);

