ALTER TABLE DEF_TXN_ALERT_TXNCODE_MAP
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_TXN_ALERT_TXNCODE_MAP CASCADE CONSTRAINTS;

CREATE TABLE DEF_TXN_ALERT_TXNCODE_MAP
(
  TATM_REPORT_TYPE       VARCHAR2(15 BYTE),
  TATM_TXN_CODE          VARCHAR2(3 BYTE),
  TATM_DISP_PARTY_TYPE   CHAR(1 BYTE),
  TATM_DISP_AMT_TYPE     CHAR(2 BYTE),
  TATM_TXN_AMT_TYPE      CHAR(1 BYTE),
  TATM_ELEMENT_TYPE      CHAR(4 BYTE),
  TATM_DISABLED          INTEGER,
  TATM_CREATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  TATM_CREATE_USER       VARCHAR2(20 BYTE),
  TATM_UPDATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  TATM_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEF_TXN_ALERT_TXNCODE_MAP_PK ON DEF_TXN_ALERT_TXNCODE_MAP
(TATM_REPORT_TYPE, TATM_TXN_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_TXN_ALERT_TXNCODE_MAP ADD (
  CONSTRAINT DEF_TXN_ALERT_TXNCODE_MAP_PK
  PRIMARY KEY
  (TATM_REPORT_TYPE, TATM_TXN_CODE)
  USING INDEX DEF_TXN_ALERT_TXNCODE_MAP_PK
  ENABLE VALIDATE);

ALTER TABLE DEF_TXN_ALERT_TXNCODE_MAP ADD (
  CONSTRAINT DEF_TXN_ALERT_TXNCODE_MAP_FK01 
  FOREIGN KEY (TATM_REPORT_TYPE) 
  REFERENCES EMAIL_FUNCT (EF_FUNCT)
  ENABLE VALIDATE,
  CONSTRAINT DEF_TXN_ALERT_TXNCODE_MAP_FK02 
  FOREIGN KEY (TATM_DISP_PARTY_TYPE) 
  REFERENCES DEF_PARTY_TYPE (DP_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT DEF_TXN_ALERT_TXNCODE_MAP_FK03 
  FOREIGN KEY (TATM_DISP_AMT_TYPE) 
  REFERENCES DEF_AMT_TYPE (DA_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT DEF_TXN_ALERT_TXNCODE_MAP_FK04 
  FOREIGN KEY (TATM_TXN_AMT_TYPE) 
  REFERENCES DEF_TXN_AMT_TYPE (DTA_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT DEF_TXN_ALERT_TXNCODE_MAP_FK05 
  FOREIGN KEY (TATM_ELEMENT_TYPE) 
  REFERENCES DEF_ELEMENT_TYPE (DT_TYPE)
  ENABLE VALIDATE);

