


INSERT ALL
  into DEF_TXN_ALERT_TXNCODE_MAP (TATM_REPORT_TYPE, TATM_TXN_CODE, TATM_DISP_PARTY_TYPE, TATM_DISP_AMT_TYPE, TATM_TXN_AMT_TYPE, TATM_ELEMENT_TYPE, TATM_DISABLED,
                                  TATM_CREATE_TIMESTAMP, TATM_CREATE_USER, TATM_UPDATE_TIMESTAMP, TATM_UPDATE_USER)
       values ('FROZEN_TXN_ON', 'm24', 'M', 'DR', 'T', 'TAMT', 0, sysdate, 'SYSTEM', sysdate, 'SYSTEM')
  into DEF_TXN_ALERT_TXNCODE_MAP (TATM_REPORT_TYPE, TATM_TXN_CODE, TATM_DISP_PARTY_TYPE, TATM_DISP_AMT_TYPE, TATM_TXN_AMT_TYPE, TATM_ELEMENT_TYPE, TATM_DISABLED,
                                  TATM_CREATE_TIMESTAMP, TATM_CREATE_USER, TATM_UPDATE_TIMESTAMP, TATM_UPDATE_USER)
       values ('FROZEN_TXN_ON', 'm25', 'M', 'DR', 'T', 'TAMT', 0, sysdate, 'SYSTEM', sysdate, 'SYSTEM')
  into DEF_TXN_ALERT_TXNCODE_MAP (TATM_REPORT_TYPE, TATM_TXN_CODE, TATM_DISP_PARTY_TYPE, TATM_DISP_AMT_TYPE, TATM_TXN_AMT_TYPE, TATM_ELEMENT_TYPE, TATM_DISABLED,
                                  TATM_CREATE_TIMESTAMP, TATM_CREATE_USER, TATM_UPDATE_TIMESTAMP, TATM_UPDATE_USER)
       values ('FROZEN_TXN_ON', 'm26', 'M', 'CR', 'T', 'TAMT', 0, sysdate, 'SYSTEM', sysdate, 'SYSTEM')
  into DEF_TXN_ALERT_TXNCODE_MAP (TATM_REPORT_TYPE, TATM_TXN_CODE, TATM_DISP_PARTY_TYPE, TATM_DISP_AMT_TYPE, TATM_TXN_AMT_TYPE, TATM_ELEMENT_TYPE, TATM_DISABLED,
                                  TATM_CREATE_TIMESTAMP, TATM_CREATE_USER, TATM_UPDATE_TIMESTAMP, TATM_UPDATE_USER)
       values ('FROZEN_TXN_ON', 'p17', 'M', 'DR', 'T', 'TAMT', 0, sysdate, 'SYSTEM', sysdate, 'SYSTEM')
SELECT * FROM DUAL;
