OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOOLMiAdjustment
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOOLMiAdjustment.so
SOOBJS = BOOLMiAdjustment.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
