ALTER TABLE PAR_CATEGORY
 DROP PRIMARY KEY CASCADE;

DROP TABLE PAR_CATEGORY CASCADE CONSTRAINTS;

CREATE TABLE PAR_CATEGORY
(
  PC_SEQUENCE_TYPE_NAME    VARCHAR2(50 BYTE),
  PC_CATEGORY      	   VARCHAR2(20 BYTE),
  PC_TXN_CODE		   VARCHAR2(3 BYTE),
  PC_REVERSAL_TXN_CODE	   VARCHAR2(3 BYTE),
  PC_CREATE_TIMESTAMP      DATE                 DEFAULT sysdate,
  PC_CREATE_USER           VARCHAR2(20 BYTE),
  PC_UPDATE_TIMESTAMP      DATE                 DEFAULT sysdate,
  PC_UPDATE_USER           VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PAR_CATEGORY_PK ON PAR_CATEGORY
(PC_SEQUENCE_TYPE_NAME)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PAR_CATEGORY ADD (
  CONSTRAINT PAR_CATEGORY_PK
  PRIMARY KEY
  (PC_SEQUENCE_TYPE_NAME)
  USING INDEX PAR_CATEGORY_PK
  ENABLE VALIDATE);

