ALTER TABLE CHANNEL_TXN_MAP
 DROP PRIMARY KEY CASCADE;

DROP TABLE CHANNEL_TXN_MAP CASCADE CONSTRAINTS;

CREATE TABLE CHANNEL_TXN_MAP
(
  CT_CHANNEL_CODE      CHAR(3 BYTE),
  CT_TXN_CODE          CHAR(3 BYTE),
  CT_DISABLED          INTEGER                  DEFAULT 0,
  CT_APPLY_FEE	       INTEGER			DEFAULT 0,
  CT_APPLY_LIMIT       INTEGER			DEFAULT 0,
  CT_APPLY_RESERVE     INTEGER			DEFAULT 0,
  CT_APPLY_EX_MARKUP   INTEGER			DEFAULT 0,
  CT_CREATE_USER       VARCHAR2(20 BYTE),
  CT_UPDATE_USER       VARCHAR2(20 BYTE),
  CT_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  CT_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  CT_APPLY_M_UNIQUE_NUM		INTEGER		DEFAULT 0,
  CT_APPLY_P_UNIQUE_NUM		INTEGER		DEFAULT 0,
  CT_APPLY_OFL_PROCESS_COST	INTEGER		DEFAULT 0
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CHANNEL_TXN_MAP_PK ON CHANNEL_TXN_MAP
(CT_CHANNEL_CODE, CT_TXN_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE CHANNEL_TXN_MAP ADD (
  CONSTRAINT CHANNEL_TXN_MAP_PK
  PRIMARY KEY
  (CT_CHANNEL_CODE, CT_TXN_CODE)
  USING INDEX CHANNEL_TXN_MAP_PK
  ENABLE VALIDATE);

ALTER TABLE CHANNEL_TXN_MAP ADD (
  CONSTRAINT CHANNEL_TXN_MAP_FK01 
  FOREIGN KEY (CT_CHANNEL_CODE) 
  REFERENCES DEF_CHANNEL (DC_CODE)
  ENABLE VALIDATE,
  CONSTRAINT CHANNEL_TXN_MAP_FK02 
  FOREIGN KEY (CT_TXN_CODE) 
  REFERENCES TXN_CODE (TC_CODE)
  ENABLE VALIDATE);
