OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MerchantApproveQueueDt
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMerchantApproveQueueDt.so
SOOBJS =  MerchantApproveQueueDt.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
