OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnCctOnUsACK
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnCctOnUsACK.so
SOOBJS = TxnCctOnUsACK.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
