OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmsEntityID
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmsEntityID.so
SOOBJS =  MmsEntityID.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
