OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnOplOnUsCOM
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnOplOnUsCOM.so
SOOBJS = TxnOplOnUsCOM.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
