OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLBatchTxnRelation/elvis
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLBatchTxnRelation.so
SOOBJS =  OLBatchTxnRelation.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
