OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnWebOnUs2HNA
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnWebOnUs2HNA.so
SOOBJS = TxnWebOnUs2HNA.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
