OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=returnpayout.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o returnpayout.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
