OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=OfflineWTD.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o OfflineWTD.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lcurl -lc -lm -lmyhash  -lObjPtr  -lmyrecordset 

all: $(BATCHEXE)
