ALTER TABLE TXN_CARD_TYPE_LOG
DROP PRIMARY KEY CASCADE;

DROP TABLE TXN_CARD_TYPE_LOG CASCADE CONSTRAINTS;

CREATE TABLE TXN_CARD_TYPE_LOG
(
  TCL_TXN_ID                VARCHAR2(16 BYTE)   NOT NULL,
  TCL_TXN_DATE              VARCHAR2(8 BYTE)    NOT NULL,
  TCL_MERCHANT_ID           VARCHAR2(15 BYTE)   NOT NULL,
  TCL_SERVICE_CODE          CHAR(3 BYTE)        NOT NULL,
  TCL_INT_BANK_CODE         VARCHAR2(10 BYTE)   NOT NULL,
  TCL_PSP_ID                VARCHAR2(10 BYTE)   NOT NULL,
  TCL_CARD_TYPE             CHAR(1 BYTE)        NOT NULL,
  TCL_CREATE_USER           VARCHAR2(20 BYTE),
  TCL_CREATE_TIMESTAMP      DATE                DEFAULT sysdate,
  TCL_UPDATE_USER           VARCHAR2(20 BYTE),
  TCL_UPDATE_TIMESTAMP      DATE                DEFAULT sysdate
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE INDEX TXN_CARD_TYPE_LOG_IDX01 ON TXN_CARD_TYPE_LOG
(TCL_TXN_DATE, TCL_MERCHANT_ID, TCL_SERVICE_CODE, TCL_INT_BANK_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX TXN_CARD_TYPE_LOG_PK ON TXN_CARD_TYPE_LOG
(TCL_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE TXN_CARD_TYPE_LOG ADD (
  CONSTRAINT TXN_CARD_TYPE_LOG_PK
  PRIMARY KEY
  (TCL_TXN_ID)
  USING INDEX TXN_CARD_TYPE_LOG_PK
  ENABLE VALIDATE);

