OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=test_payout_chksum.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o test_payout_chksum.o 
#
#
# Include the Common Rules
#
#

include ../../Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
