OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=test_key_lower.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o test_key_lower.o 
#
#
# Include the Common Rules
#
#

include ../../Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
