ALTER TABLE OL_BANK_BAL_CHECK
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_BANK_BAL_CHECK CASCADE CONSTRAINTS;

CREATE TABLE OL_BANK_BAL_CHECK
(
  OBBC_INT_BANK_CODE     VARCHAR2(10 BYTE),
  OBBC_BAL_THRESHOLD     NUMBER(14,2),
  OBBC_LAST_CHECK_TIME   DATE                   DEFAULT sysdate,
  OBBC_SKIP_CHECK_MINS   INTEGER,
  OBBC_DISABLED          INTEGER                DEFAULT 0,
  OBBC_CREATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  OBBC_CREATE_USER       VARCHAR2(20 BYTE),
  OBBC_UPDATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  OBBC_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_BANK_BAL_CHECK_PK ON OL_BANK_BAL_CHECK
(OBBC_INT_BANK_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_BANK_BAL_CHECK ADD (
  CONSTRAINT OL_BANK_BAL_CHECK_PK
  PRIMARY KEY
  (OBBC_INT_BANK_CODE)
  USING INDEX OL_BANK_BAL_CHECK_PK
  ENABLE VALIDATE);

ALTER TABLE OL_BANK_BAL_CHECK ADD (
  CONSTRAINT OL_BANK_BAL_CHECK_FK01 
  FOREIGN KEY (OBBC_INT_BANK_CODE) 
  REFERENCES DEF_BANK (DB_INT_BANK_CODE)
  ENABLE VALIDATE);

