ALTER TABLE DISABLED_BANK
 DROP PRIMARY KEY CASCADE;

DROP TABLE DISABLED_BANK CASCADE CONSTRAINTS;

CREATE TABLE DISABLED_BANK
(
  DB_PSP_ID            VARCHAR2(10 BYTE)        NOT NULL,
  DB_COUNTRY           VARCHAR2(2 BYTE),
  DB_INT_BANK_CODE     VARCHAR2(10 BYTE)        NOT NULL,
  DB_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  DB_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  DB_CREATE_USER       VARCHAR2(20 BYTE),
  DB_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DISABLED_BANK_PK ON DISABLED_BANK
(DB_PSP_ID, DB_INT_BANK_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE DISABLED_BANK ADD (
  CONSTRAINT DISABLED_BANK_PK
  PRIMARY KEY
  (DB_PSP_ID, DB_INT_BANK_CODE)
  USING INDEX DISABLED_BANK_PK);

