ALTER TABLE MI_ENTITY_PIT
 DROP PRIMARY KEY CASCADE;

DROP TABLE MI_ENTITY_PIT CASCADE CONSTRAINTS;

CREATE TABLE MI_ENTITY_PIT
(
  EP_ENTITY_ID         VARCHAR2(10 BYTE),
  EP_PIT_ID            VARCHAR2(10 BYTE)        NOT NULL,
  EP_PIT_NAME          VARCHAR2(50 BYTE),
  EP_PRODUCT_CODE      CHAR(3 BYTE),
  EP_PIT_STATUS        VARCHAR2(2 BYTE),
  EP_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  EP_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  EP_CREATE_USER       VARCHAR2(20 BYTE),
  EP_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MI_ENTITY_PIT_PK ON MI_ENTITY_PIT
(EP_PIT_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX MI_ENTITY_PIT_UK ON MI_ENTITY_PIT
(EP_ENTITY_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MI_ENTITY_PIT ADD (
  CONSTRAINT MI_ENTITY_PIT_PK
  PRIMARY KEY
  (EP_PIT_ID)
  USING INDEX MI_ENTITY_PIT_PK
  ENABLE VALIDATE,
  CONSTRAINT MI_ENTITY_PIT_UK
  UNIQUE (EP_ENTITY_ID)
  USING INDEX MI_ENTITY_PIT_UK
  ENABLE VALIDATE);

ALTER TABLE MI_ENTITY_PIT ADD (
  CONSTRAINT MI_ENTITY_PIT_FK01 
  FOREIGN KEY (EP_ENTITY_ID) 
  REFERENCES MI_ENTITY_DETAIL (ED_ENTITY_ID)
  ENABLE VALIDATE,
  CONSTRAINT MI_ENTITY_PIT_FK02 
  FOREIGN KEY (EP_PRODUCT_CODE) 
  REFERENCES DEF_PRODUCT (DP_ID)
  ENABLE VALIDATE,
  CONSTRAINT MI_ENTITY_PIT_FK03 
  FOREIGN KEY (EP_PIT_STATUS) 
  REFERENCES DEF_STATUS (DS_TYPE)
  ENABLE VALIDATE);

