ALTER TABLE PAR_PSP_CLIENT_MAP
 DROP PRIMARY KEY CASCADE;

DROP TABLE PAR_PSP_CLIENT_MAP CASCADE CONSTRAINTS;

CREATE TABLE PAR_PSP_CLIENT_MAP
(
  PPM_PSP_CLIENT_GRP       VARCHAR2(5 BYTE),
  PPM_PSP_CLIENT_GRP_NAME  VARCHAR2(50 BYTE),
  PPM_PREFER_CLIENT_ID     VARCHAR2(10 BYTE),
  PPM_PSP_TYPE_CD          VARCHAR2(50 BYTE),
  PPM_PSP_TYPE_NAME        VARCHAR2(50 BYTE),
  PPM_PSP_CODE             VARCHAR2(20 BYTE),
  PPM_PSP_NAME             VARCHAR2(80 BYTE),
  PPM_TXN_TYPE             VARCHAR2(1 BYTE),
  PPM_COUNTRY              VARCHAR2(2 BYTE),
  PPM_CCY_ID               VARCHAR2(3 BYTE),
  PPM_PRESET_PID           VARCHAR2(10 BYTE),
  PPM_PRESET_PSP_NAME      VARCHAR2(50 BYTE),
  PPM_PSP_TYPE             VARCHAR2(1 BYTE),
  PPM_CREATE_TIMESTAMP     DATE,
  PPM_CREATE_USER          VARCHAR2(20 BYTE),
  PPM_UPDATE_TIMESTAMP     DATE,
  PPM_UPDATE_USER          VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PAR_PSP_CLIENT_MAP_PK ON PAR_PSP_CLIENT_MAP
(PPM_PSP_TYPE_CD)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PAR_PSP_CLIENT_MAP ADD (
  CONSTRAINT PAR_PSP_CLIENT_MAP_PK
  PRIMARY KEY
  (PPM_PSP_TYPE_CD)
  USING INDEX PAR_PSP_CLIENT_MAP_PK
  ENABLE VALIDATE);

