OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/CrrPspProductCodeMap
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBCrrPspProductCodeMap.so
SOOBJS =  CrrPspProductCodeMap.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
