ALTER TABLE DEF_ROUNDING
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_ROUNDING CASCADE CONSTRAINTS;

CREATE TABLE DEF_ROUNDING
(
  DR_TYPE              CHAR(1 BYTE),
  DR_DESC              VARCHAR2(50 BYTE),
  DR_CREATE_USER       VARCHAR2(20 BYTE),
  DR_UPDATE_USER       VARCHAR2(20 BYTE),
  DR_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  DR_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEF_ROUNDING_PK ON DEF_ROUNDING
(DR_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_ROUNDING ADD (
  CONSTRAINT DEF_ROUNDING_PK
  PRIMARY KEY
  (DR_TYPE)
  USING INDEX DEF_ROUNDING_PK
  ENABLE VALIDATE);

