OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLTxnEngineSpcActionDef
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLTxnEngineSpcActionDef.so
SOOBJS =  OLTxnEngineSpcActionDef.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
