OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/CustomerGroupCounters
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBCustomerGroupCounters.so
SOOBJS =  CustomerGroupCounters.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
