OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLBAIDTxnCode
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLBAIDTxnCode.so
SOOBJS =  OLBAIDTxnCode.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
