OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/FundsIn
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBFundsIn.so
SOOBJS =  FundsIn.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
