OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmsEntityMaster
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmsEntityMaster.so
SOOBJS =  MmsEntityMaster.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
