ALTER TABLE MMS_BANK_BALANCE
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_BANK_BALANCE CASCADE CONSTRAINTS;

CREATE TABLE MMS_BANK_BALANCE
(
  BK_ID            VARCHAR2(15 BYTE),
  BK_CURRENCY_ID       VARCHAR2(3 BYTE),
  BK_BAL               NUMBER(14,2)             DEFAULT 0,
  BK_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  BK_CREATE_USER       VARCHAR2(20 BYTE),
  BK_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  BK_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MMS_BANK_BALANCE_PK ON MMS_BANK_BALANCE
(BK_ID, BK_CURRENCY_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_BANK_BALANCE ADD (
  CONSTRAINT MMS_BANK_BALANCE_PK
  PRIMARY KEY
  (BK_ID, BK_CURRENCY_ID)
  USING INDEX MMS_BANK_BALANCE_PK);
