ALTER TABLE OL_RULE_STATEMENT_PERIOD
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_RULE_STATEMENT_PERIOD CASCADE CONSTRAINTS;

CREATE TABLE OL_RULE_STATEMENT_PERIOD
(
  ORSP_INT_BANK_CODE     VARCHAR2(10 BYTE),
  ORSP_BANK_ACCT_NUM     VARCHAR2(50 BYTE),
  ORSP_BF_HOURS          INTEGER,
  ORSP_AF_HOURS          INTEGER,
  ORSP_HOLIDAY_BF_HOURS  INTEGER,
  ORSP_HOLIDAY_AF_HOURS  INTEGER,
  ORSP_CREATE_TIMESTAMP  DATE,
  ORSP_CREATE_USER       VARCHAR2(20 BYTE),
  ORSP_UPDATE_TIMESTAMP  DATE,
  ORSP_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX OL_RULE_STATEMENT_PERIOD_IDX01 ON OL_RULE_STATEMENT_PERIOD
(ORSP_INT_BANK_CODE, ORSP_BANK_ACCT_NUM, ORSP_BF_HOURS, ORSP_AF_HOURS, ORSP_HOLIDAY_BF_HOURS, 
ORSP_HOLIDAY_AF_HOURS)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX OL_RULE_STATEMENT_PERIOD_PK ON OL_RULE_STATEMENT_PERIOD
(ORSP_INT_BANK_CODE, ORSP_BANK_ACCT_NUM)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_RULE_STATEMENT_PERIOD ADD (
  CONSTRAINT OL_RULE_STATEMENT_PERIOD_PK
  PRIMARY KEY
  (ORSP_INT_BANK_CODE, ORSP_BANK_ACCT_NUM)
  USING INDEX OL_RULE_STATEMENT_PERIOD_PK
  ENABLE VALIDATE);

ALTER TABLE OL_RULE_STATEMENT_PERIOD ADD (
  CONSTRAINT OL_RULE_STATEMENT_PERIOD_FK01 
  FOREIGN KEY (ORSP_INT_BANK_CODE, ORSP_BANK_ACCT_NUM) 
  REFERENCES OL_BANK_ACCTS (OB_INT_BANK_CODE,OB_BANK_ACCT_NUM)
  ENABLE VALIDATE);

