ALTER TABLE RULE_PAYOUT_WHITE_LIST
 DROP PRIMARY KEY CASCADE;

DROP TABLE RULE_PAYOUT_WHITE_LIST CASCADE CONSTRAINTS;

CREATE TABLE RULE_PAYOUT_WHITE_LIST
(
  RPWL_MERCH_ID          VARCHAR2(15 BYTE),
  RPWL_ACCT_NAME         VARCHAR2(100 BYTE),
  RPWL_DISABLED          INTEGER		DEFAULT 0,
  RPWL_CREATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  RPWL_CREATE_USER       VARCHAR2(20 BYTE),
  RPWL_UPDATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  RPWL_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX RULE_PAYOUT_WHITE_LIST_PK ON RULE_PAYOUT_WHITE_LIST
(RPWL_MERCH_ID, RPWL_ACCT_NAME)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE RULE_PAYOUT_WHITE_LIST ADD (
  CONSTRAINT RULE_PAYOUT_WHITE_LIST_PK
  PRIMARY KEY
  (RPWL_MERCH_ID, RPWL_ACCT_NAME)
  USING INDEX RULE_PAYOUT_WHITE_LIST_PK
  ENABLE VALIDATE);

