ALTER TABLE SERVICE_PAY_METHOD
 DROP PRIMARY KEY CASCADE;

DROP TABLE SERVICE_PAY_METHOD CASCADE CONSTRAINTS;

CREATE TABLE SERVICE_PAY_METHOD
(
  SP_SERVICE_CODE      CHAR(3 BYTE),
  SP_PAY_METHOD        VARCHAR2(4 BYTE),
  SP_DISABLED          INTEGER,
  SP_CREATE_TIMESTAMP  DATE                     DEFAULT SYSDATE,
  SP_CREATE_USER       VARCHAR2(20 BYTE),
  SP_UPDATE_TIMESTAMP  DATE                     DEFAULT SYSDATE,
  SP_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX SERVICE_PAY_METHOD_IDX01 ON SERVICE_PAY_METHOD
(SP_DISABLED)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX SERVICE_PAY_METHOD_PK ON SERVICE_PAY_METHOD
(SP_SERVICE_CODE, SP_PAY_METHOD)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE SERVICE_PAY_METHOD ADD (
  CONSTRAINT SERVICE_PAY_METHOD_PK
  PRIMARY KEY
  (SP_SERVICE_CODE, SP_PAY_METHOD)
  USING INDEX SERVICE_PAY_METHOD_PK
  ENABLE VALIDATE);

