OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/ParTxnData
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBParTxnData.so
SOOBJS =  ParTxnData.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
