OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MerchantUploadError
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMerchantUploadError.so
SOOBJS =  MerchantUploadError.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
