DROP TABLE NON_POSTINGDATE_RESP CASCADE CONSTRAINTS;

CREATE TABLE NON_POSTINGDATE_RESP
(
  TXN_ID            VARCHAR2(16 BYTE)           NOT NULL,
  POSTING_DATE      VARCHAR2(8 BYTE),
  TM_DATE           VARCHAR2(8 BYTE),
  TM_TIME           VARCHAR2(6 BYTE),
  CREATE_USER       VARCHAR2(20 BYTE),
  CREATE_TIMESTAMP  DATE,
  UPDATE_USER       VARCHAR2(20 BYTE),
  UPDATE_TIMESTAMP  DATE
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX NON_POSTINGDATE_RESP_IDX01 ON NON_POSTINGDATE_RESP
(TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX NON_POSTINGDATE_RESP_IDX02 ON NON_POSTINGDATE_RESP
(POSTING_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

