load data
infile *
append
into table ol_stmt_match_engine
fields terminated by '|'
(OSME_TRIGGER_TYPE,
OSME_INPUT_CHANNEL,
OSME_BANK_ACCT_TYPE,
OSME_BAID_TXN_CODE,
OSME_RULE_ID,
OSME_FAILED_BAID_TXN_CODE,
OSME_DISABLED,
OSME_CREATE_TIMESTAMP SYSDATE,
OSME_CREATE_USER,
OSME_UPDATE_TIMESTAMP SYSDATE,
OSME_UPDATE_USER
)
begindata
system|OMT|PDF|XVD|65||0|SYSTEM|SYSTEM
system|OMT|PDF|QEF|66||0|SYSTEM|SYSTEM
system|OMT|PDF|QXF|67||0|SYSTEM|SYSTEM
system|OMT|PDF|QPF|68||0|SYSTEM|SYSTEM
