load data
infile "stmt_match_filter.txt"
append
into table ol_stmt_match_filter
fields terminated by '|'
(OSMF_ACTION_FILTER_ID,
OSMF_SEQUENCE,
OSMF_GROUP,
OSMF_PARTY,
OSMF_FILTER,
OSMF_OPERATOR,
OSMF_VALUE,
OSMF_FROM_INPUT,
OSMF_TO_OUTPUT,
OSMF_SPECIAL_HANDLING,
OSMF_DISABLED,
OSMF_CREATE_TIMESTAMP SYSDATE,
OSMF_CREATE_USER,
OSMF_UPDATE_TIMESTAMP SYSDATE,
OSMF_UPDATE_USER
)
