CREATE OR REPLACE FUNCTION SP_HIST_OL_FEE_SUM_COLLECT(
    IN_END_DATE IN DATE )
RETURN NUMBER IS
	EXP_ERR  EXCEPTION;
	EXP_ERR2 EXCEPTION;
	DATE_ERR EXCEPTION;

	V_NEW_BATCH_ID HIST_OL_FEE_SUM_BATCH.HB_BATCH_ID%type;
	V_PREV_BATCH_ID HIST_OL_FEE_SUM_BATCH.HB_BATCH_ID%type;
	V_START_DATE         DATE;
	V_ADD_RANGE_END_DATE DATE;
	V_CUTOFF_DATE DATE;
	V_AMT NUMBER(14,2); 
	V_PREV_TXN_COUNT NUMBER; 
	V_TXN_COUNT NUMBER; 
	V_PREV_AMT NUMBER(14,2); 
	V_PREV_AMT_HKD NUMBER(14,2);
	V_PREV_AMT_USD NUMBER(14,2);
	V_AMT_HKD NUMBER(14,2);
	V_AMT_USD NUMBER(14,2);
	V_HKD_RATE EXCHANGE_RATE.EX_MED_ASK%type;
	V_USD_RATE EXCHANGE_RATE.EX_MED_ASK%type;
	V_COUNT_NO number; 
	V_COUNT_NO2 number; 
	V_CLIENT_ID HIST_OL_FEE_SUM_DETAIL.HD_CLIENT_ID%type;
	V_CLIENT_NAME HIST_OL_FEE_SUM_DETAIL.HD_CLIENT_NAME%type;
	V_MERCHANT_NAME HIST_OL_FEE_SUM_DETAIL.HD_MERCHANT_NAME%type;
BEGIN
-- DBMS_OUTPUT.PUT_LINE('>>> START [HIST_OL_FEE_SUM_COLLECT] <<<');
  
  
	SELECT 
		count(*)
	INTO 
		V_COUNT_NO2
	FROM HIST_RPT_CONFIG
	WHERE HR_RPT_CODE = 'OL_FEE_SUM';

	IF SQL % ROWCOUNT != 1 THEN
		raise EXP_ERR2;
	END IF; 
	
	IF V_COUNT_NO2 > 0 THEN
		SELECT 
			HR_CUTOFF_DATE
		INTO 
			V_CUTOFF_DATE
		FROM
			HIST_RPT_CONFIG
		WHERE HR_RPT_CODE = 'OL_FEE_SUM';

		IF SQL % ROWCOUNT != 1 THEN
			raise EXP_ERR2;
		END IF ;
	ELSE 
		V_CUTOFF_DATE :=  IN_END_DATE - 1 ;
	END IF ;

  
-- DBMS_OUTPUT.PUT_LINE('--> Input Date: '|| TO_CHAR(IN_END_DATE, 'YYYY-MM-DD HH24:MI') );
-- Find Prev Batch ID and current batch start date/time
	SELECT HB_BATCH_ID,
		HB_END_DATE
	INTO V_PREV_BATCH_ID,
		V_START_DATE
	FROM
	(SELECT HB_BATCH_ID,
		HB_END_DATE,
		ROW_NUMBER() OVER (PARTITION BY HB_DISABLED ORDER BY HB_END_DATE DESC) RN
	 FROM HIST_OL_FEE_SUM_BATCH
	 WHERE HB_DISABLED = 0
	)
	WHERE RN = 1;

	IF SQL % ROWCOUNT != 1 THEN
		raise EXP_ERR2;
	END IF ;

	V_START_DATE := V_START_DATE + 1/24/60;
-- DBMS_OUTPUT.PUT_LINE('--> Start Date: '|| V_START_DATE );
-- DBMS_OUTPUT.PUT_LINE('--> End Date: '|| IN_END_DATE );

-- only look forward
	IF IN_END_DATE < V_START_DATE THEN
  		raise DATE_ERR;
	END IF;

-- DBMS_OUTPUT.PUT_LINE('xxxx');
-- New Batch ID
	SELECT MAX(HB_BATCH_ID) + 1
	INTO V_NEW_BATCH_ID
	FROM HIST_OL_FEE_SUM_BATCH;
-- DBMS_OUTPUT.PUT_LINE('--> New Batch ID: ' || V_NEW_BATCH_ID );
-- DBMS_OUTPUT.PUT_LINE('--> Previous Batch ID: ' || V_PREV_BATCH_ID );

-- Add 1 mins to end times
	V_ADD_RANGE_END_DATE := IN_END_DATE + 1/24/60;
-- DBMS_OUTPUT.PUT_LINE('--> Add 1 mins end date: ' || V_ADD_RANGE_END_DATE );

-- Insert New Batch
	INSERT
	INTO HIST_OL_FEE_SUM_BATCH
	(
		HB_BATCH_ID,
		HB_START_DATE,
		HB_END_DATE,
		HB_DISABLED,
		HB_CREATE_TIMESTAMP,
		HB_CREATE_USER
	)
	VALUES
	(
		V_NEW_BATCH_ID,
		V_START_DATE,
		IN_END_DATE,
		0,
		SYSDATE,
		'SYSTEM'
	);

	IF SQL % ROWCOUNT != 1 THEN
		raise EXP_ERR;
	END IF ;
-- DBMS_OUTPUT.PUT_LINE('--> Insert New Batch : OK');

-- Find PSP Last Txn from start times to end times
	FOR X IN
	(
		SELECT MERCHANT_ID,
			COUNTRY,
			SERVICE_CODE,
			TXN_CCY,
			TXN_CODE,
			TXN_AMT,
			TXN_COUNT,
			IS_MARKUP,
			IS_FEE,
			IS_PREV
		FROM
		(SELECT MERCHANT_ID,
		      COUNTRY,
		      SERVICE_CODE,
		      TXN_CCY,
		      TXN_CODE,
		      TXN_AMT,
		      TXN_COUNT,
		      IS_MARKUP,
		      IS_FEE,
		      IS_PREV,
		      ROW_NUMBER() OVER ( PARTITION BY MERCHANT_ID ,COUNTRY ,SERVICE_CODE ,TXN_CCY , TXN_CODE,IS_MARKUP,IS_FEE ORDER BY IS_PREV ASC ) RN
		FROM
		(SELECT MERCHANT_ID,
			COUNTRY,
			SERVICE_CODE,
			TXN_CCY,
			TXN_CODE,
			SUM(CASE WHEN IS_REFUND_AMT = 0 AND IS_VOID_AMT = 0 THEN TXN_AMT ELSE -TXN_AMT END) AS TXN_AMT,
			COUNT(DISTINCT TXN_ID) AS TXN_COUNT,
			IS_MARKUP,
			IS_FEE,
			0 AS IS_PREV
		FROM
		(SELECT 
			OL_TXN_HEADER.OTH_TXN_ID 	    AS TXN_ID,
			OL_TXN_HEADER.OTH_MERCHANT_ID 	    AS MERCHANT_ID,
			OL_TXN_DETAIL.OTD_TXN_COUNTRY       AS COUNTRY,
			OL_TXN_HEADER.OTH_SERVICE_CODE      AS SERVICE_CODE,
			OL_TXN_ELEMENTS.OTE_CCY             AS TXN_CCY,
			OL_TXN_ELEMENTS.OTE_AMOUNT          AS TXN_AMT,
			OL_TXN_HEADER.OTH_TXN_CODE          AS TXN_CODE,
			FEE_SUM_TXN_CODE_MAP.IS_FEE_AMT,
			FEE_SUM_TXN_CODE_MAP.IS_MARKUP_AMT,
			FEE_SUM_TXN_CODE_MAP.IS_VOID_AMT,
			FEE_SUM_TXN_CODE_MAP.IS_REFUND_AMT,
			CASE
			  WHEN FEE_SUM_TXN_CODE_MAP.IS_MARKUP_AMT = 1
			  THEN 1
			  ELSE 0
			END AS IS_MARKUP,
			CASE
			  WHEN FEE_SUM_TXN_CODE_MAP.IS_FEE_AMT = 1
			  THEN 1
			  ELSE 0
			END AS IS_FEE
		FROM OL_TXN_HEADER
		INNER JOIN OL_TXN_DETAIL
		ON OL_TXN_DETAIL.OTD_TXN_ID = OL_TXN_HEADER.OTH_TXN_ID
		INNER JOIN OL_TXN_ELEMENTS
		ON OL_TXN_ELEMENTS.OTE_TXN_ID  = OL_TXN_HEADER.OTH_TXN_ID
		INNER JOIN FEE_SUM_TXN_CODE_MAP
		ON FEE_SUM_TXN_CODE_MAP.TXN_CODE = OL_TXN_HEADER.OTH_TXN_CODE
		AND FEE_SUM_TXN_CODE_MAP.TXN_ELEMENT_TYPE = OL_TXN_ELEMENTS.OTE_TXN_ELEMENT_TYPE
		WHERE OTH_AR_IND = 'A'
		AND OTH_STATUS   IN ('C', 'R')
		AND (FEE_SUM_TXN_CODE_MAP.IS_MARKUP_AMT = 1
		      OR  (FEE_SUM_TXN_CODE_MAP.IS_FEE_AMT = 1 AND OL_TXN_ELEMENTS.OTE_PARTY_TYPE = 'M'))
		AND OTH_APPROVAL_TIMESTAMP >= CAST(V_START_DATE AS TIMESTAMP)
		AND OTH_APPROVAL_TIMESTAMP  < CAST(V_ADD_RANGE_END_DATE AS TIMESTAMP)
		UNION
		SELECT 
			OL_TXN_HEADER.OTH_TXN_ID 	   AS TXN_ID,
			OL_TXN_HEADER.OTH_MERCHANT_ID 	   AS MERCHANT_ID,
			OL_TXN_DETAIL.OTD_TXN_COUNTRY      AS COUNTRY,
			OL_TXN_HEADER.OTH_SERVICE_CODE     AS SERVICE_CODE,
			OL_TXN_ELEMENTS.OTE_CCY            AS TXN_CCY,
			OL_TXN_ELEMENTS.OTE_AMOUNT         AS TXN_AMOUNT,
			OL_TXN_HEADER.OTH_TXN_CODE         AS TXN_CODE,
			CASE WHEN OTE_AMT_TYPE = 'DR' THEN 1 ELSE 0 END AS IS_FEE_AMT,
			0 AS IS_MARKUP_AMT,
			0 AS IS_VOID_AMT,
			CASE WHEN OTE_AMT_TYPE = 'CR' THEN 1 ELSE 0 END AS IS_REFUND_AMT,
			0   AS IS_MARKUP,
			1   AS IS_FEE
		FROM OL_TXN_HEADER
		INNER JOIN OL_TXN_DETAIL
		ON OL_TXN_DETAIL.OTD_TXN_ID = OL_TXN_HEADER.OTH_TXN_ID
		INNER JOIN OL_ADJUSTMENT_TYPE
		ON OAT_CODE                 = OTH_TXN_CODE
		AND OAT_PARTY_TYPE          = 'M'
		AND OAT_NATURE              = 'F'
		INNER JOIN OL_TXN_ELEMENTS
		ON  OL_TXN_ELEMENTS.OTE_TXN_ID = OL_TXN_HEADER.OTH_TXN_ID
		AND OTE_TXN_ELEMENT_TYPE = 'TAMT'
		WHERE OTH_AR_IND           = 'A'
		AND OTH_STATUS             IN ('C', 'R')
		AND OTH_APPROVAL_TIMESTAMP >= CAST(V_START_DATE AS TIMESTAMP)
		AND OTH_APPROVAL_TIMESTAMP  < CAST(V_ADD_RANGE_END_DATE AS TIMESTAMP)
		) TXN
		GROUP BY MERCHANT_ID,
		COUNTRY,
		SERVICE_CODE,
		TXN_CCY ,
		TXN_CODE,
		IS_MARKUP,
		IS_FEE
		UNION
		SELECT HD_MERCHANT_ID AS MERCHANT_ID ,
			HD_COUNTRY          AS COUNTRY ,
			HD_SERVICE_CODE     AS SERVICE_CODE ,
			HD_CCY              AS TXN_CCY ,
			HD_TXN_CODE         AS TXN_CODE ,
			HD_AMT              AS TXN_AMT,
			HD_TXN_COUNT        AS TXN_COUNT,
			HD_IS_MARKUP        AS IS_MARKUP,
			HD_IS_FEE           AS IS_FEE,
			1                   AS IS_PREV
		FROM HIST_OL_FEE_SUM_DETAIL
		WHERE HD_BATCH_ID = V_PREV_BATCH_ID
		)
		)
		WHERE RN = 1
	)
	LOOP
-- DBMS_OUTPUT.PUT_LINE('--> MERCHANT_ID: [' || X.MERCHANT_ID || '] COUNTRY: [' || X.COUNTRY || ']  SERVICE_CODE : [' || X.SERVICE_CODE||'] TXN_CCY : [' || X.TXN_CCY||'] TXN_CODE : [' || X.TXN_CODE||'] TXN_AMT : [' || X.TXN_AMT||']  TXN_COUNT : [' || X.TXN_COUNT||']  IS_PREV : [' || X.IS_PREV||']');
	
	/*IF X.TXN_ID IS NOT NULL THEN
-- DBMS_OUTPUT.PUT_LINE('--> Txn Bal');
	--  Txn Bal
	SELECT 
		NVL(TM_ACCT_BAL, 0.00) + NVL(TM_INTRANSIT, 0.00) AS BAL  
	 INTO 
		V_BAL 
	FROM TXN_MI_DETAIL 
	WHERE  
		 TM_TXN_ID = X.TXN_ID;
	*/	
-- DBMS_OUTPUT.PUT_LINE('--> ACCT_BAL: [' || V_BAL ||']');
	
		SELECT count(*) AS COUNT_NO INTO V_COUNT_NO
		FROM HIST_OL_FEE_SUM_DETAIL  
		WHERE HD_BATCH_ID = V_PREV_BATCH_ID 
		AND HD_MERCHANT_ID = X.MERCHANT_ID
		AND HD_COUNTRY = X.COUNTRY
		AND HD_SERVICE_CODE = X.SERVICE_CODE
		AND HD_CCY = X.TXN_CCY
		AND HD_TXN_CODE = X.TXN_CODE
		AND HD_IS_MARKUP = X.IS_MARKUP
		AND HD_IS_FEE = X.IS_FEE;
     
--DBMS_OUTPUT.PUT_LINE('--> V_COUNT_NO: [' || V_COUNT_NO || ']');
--DBMS_OUTPUT.PUT_LINE('--> V_PREV_BATCH_ID: [' || V_PREV_BATCH_ID || '] MERCHANT_ID: [' || X.MERCHANT_ID ||'] COUNTRY: [' || X.COUNTRY ||'] SERVICE_CODE: [' || X.SERVICE_CODE ||'] TXN_CCY: [' || X.TXN_CCY ||'] TXN_CODE: [' || X.TXN_CODE ||'] IS_MARKUP: [' || X.IS_MARKUP ||'] IS_FEE: [' || X.IS_FEE ||']');		
		
		IF V_COUNT_NO > 0 THEN
-- Prev Batch Bal	
	 		SELECT 
				NVL(HD_TXN_COUNT, 0)   AS HD_TXN_COUNT,
				NVL(HD_AMT, 0.00) 		AS HD_AMT ,
				NVL(HD_AMT_HKD, 0.00) 	AS HD_AMT_HKD ,
				NVL(HD_AMT_USD, 0.00) 	AS HD_AMT_USD 
			INTO 
				V_PREV_TXN_COUNT,
				V_PREV_AMT,
				V_PREV_AMT_HKD,
				V_PREV_AMT_USD
			FROM HIST_OL_FEE_SUM_DETAIL  
			WHERE HD_BATCH_ID = V_PREV_BATCH_ID 
			AND HD_MERCHANT_ID = X.MERCHANT_ID
			AND HD_COUNTRY = X.COUNTRY
			AND HD_SERVICE_CODE = X.SERVICE_CODE
			AND HD_CCY = X.TXN_CCY
			AND HD_TXN_CODE = X.TXN_CODE
			AND HD_IS_MARKUP = X.IS_MARKUP
			AND HD_IS_FEE = X.IS_FEE;
		ELSE
			V_PREV_TXN_COUNT := 0;
			V_PREV_AMT := 0.00;
			V_PREV_AMT_HKD := 0.00;
			V_PREV_AMT_USD := 0.00;
		END IF ; 
	
-- DBMS_OUTPUT.PUT_LINE('--> V_PREV_TXN_COUNT: [' || V_PREV_TXN_COUNT || '] V_PREV_AMT: [' || V_PREV_AMT ||'] V_PREV_AMT_HKD: [' || V_PREV_AMT_HKD ||'] V_PREV_AMT_USD: [' || V_PREV_AMT_USD ||'] IS_PREV: [' || X.IS_PREV ||']');	
-- DBMS_OUTPUT.PUT_LINE('--> V_AMT: [' || V_AMT || '] V_TXN_COUNT: [' || V_TXN_COUNT ||']');	

-- DBMS_OUTPUT.PUT_LINE('--> GET Rate');	  
-- HKD Rate , USD Rate	
		SELECT
			RATE_HKD_TBL.RATE AS HKD_RATE,
			RATE_USD_TBL.RATE AS USD_RATE
	   	INTO 
			V_HKD_RATE,
			V_USD_RATE
		FROM 
	 	(
		SELECT 
			EX_MED_ASK AS RATE ,
			EX_TO_CCY_ID
		FROM (
		SELECT EX_FROM_CCY_ID
			,EX_TO_CCY_ID
			,EX_MED_ASK
			,ROW_NUMBER() OVER (
			PARTITION BY EX_FROM_CCY_ID
			,EX_TO_CCY_ID ORDER BY EX_EFFECT_DATE DESC
		) XX
		FROM EXCHANGE_RATE
		WHERE EX_EFFECT_DATE < CAST(V_ADD_RANGE_END_DATE AS TIMESTAMP)
		)
		WHERE XX = 1
		AND EX_TO_CCY_ID = 'HKD'
		AND EX_FROM_CCY_ID = X.TXN_CCY
		) RATE_HKD_TBL 
		INNER JOIN (
		SELECT  
			EX_MED_ASK AS RATE ,
			EX_FROM_CCY_ID
		FROM (
		SELECT EX_FROM_CCY_ID
			,EX_TO_CCY_ID
			,EX_MED_ASK
			,ROW_NUMBER() OVER (
				PARTITION BY EX_FROM_CCY_ID
				,EX_TO_CCY_ID ORDER BY EX_EFFECT_DATE DESC
			) XX
		FROM EXCHANGE_RATE
		WHERE EX_EFFECT_DATE < CAST(V_ADD_RANGE_END_DATE AS TIMESTAMP)
		)
		WHERE XX = 1
		AND EX_FROM_CCY_ID = 'HKD'
		AND EX_TO_CCY_ID = 'USD'
		) RATE_USD_TBL ON RATE_HKD_TBL.EX_TO_CCY_ID = RATE_USD_TBL.EX_FROM_CCY_ID;
	
-- DBMS_OUTPUT.PUT_LINE('--> HKD_RATE: [' || V_HKD_RATE || '] USD_RATE: [' || V_USD_RATE ||']');		 
	 
		IF X.IS_PREV = 0 THEN
			V_AMT := V_PREV_AMT + X.TXN_AMT ; 
			V_AMT_HKD := V_PREV_AMT_HKD + (X.TXN_AMT * V_HKD_RATE) ; 
			V_AMT_USD := V_PREV_AMT_USD + (X.TXN_AMT * V_HKD_RATE * V_USD_RATE) ; 
			V_TXN_COUNT := V_PREV_TXN_COUNT + X.TXN_COUNT ; 
		ELSE
			V_AMT := V_PREV_AMT; 
			V_AMT_HKD := V_PREV_AMT_HKD; 
			V_AMT_USD := V_PREV_AMT_USD; 
			V_TXN_COUNT := V_PREV_TXN_COUNT; 
		END IF ;
	 
-- DBMS_OUTPUT.PUT_LINE('--> INSERT ');	  
	 
-- Check Cut off Time
		IF V_CUTOFF_DATE >= V_ADD_RANGE_END_DATE THEN
			V_AMT:= 0.00;
			V_AMT_HKD := 0.00;
			V_HKD_RATE := 0.00;
			V_AMT_USD := 0.00;
			V_USD_RATE := 0.00;
			V_TXN_COUNT := 0;
		END IF;
		 
		SELECT 
			CLIENT_ID ,
			CLIENT_NAME ,
			MD_SHORT_NAME
		INTO 
			V_CLIENT_ID,
			V_CLIENT_NAME ,
			V_MERCHANT_NAME
		FROM OL_MERCH_DETAIL 
		INNER JOIN CLIENTS
			ON CLIENT_ID = MD_CLIENT_ID 	
		WHERE MD_MERCHANT_ID = X.MERCHANT_ID  ;
		 
		INSERT INTO HIST_OL_FEE_SUM_DETAIL
		(
			HD_BATCH_ID, 
			HD_CLIENT_ID,
			HD_CLIENT_NAME,
			HD_MERCHANT_ID,
			HD_MERCHANT_NAME,
			HD_COUNTRY,
			HD_SERVICE_CODE,
			HD_CCY,
			HD_TXN_CODE,
			HD_AMT,
			HD_AMT_HKD ,
			HD_AMT_HKD_RATE,
			HD_AMT_USD ,	
			HD_AMT_USD_RATE,
			HD_TXN_COUNT,
			HD_IS_FEE,
			HD_IS_MARKUP
		) VALUES (
			V_NEW_BATCH_ID, 
			V_CLIENT_ID,
			V_CLIENT_NAME, 
			X.MERCHANT_ID,
			V_MERCHANT_NAME, 
			X.COUNTRY,
			X.SERVICE_CODE,
			X.TXN_CCY,
			X.TXN_CODE,
			NVL(V_AMT, 0.00),
			NVL(V_AMT_HKD, 0.00),
			V_HKD_RATE,
			NVL(V_AMT_USD, 0.00),
			V_USD_RATE,
			NVL(V_TXN_COUNT, 0),
			X.IS_FEE,
			X.IS_MARKUP
        	);

		IF SQL % ROWCOUNT != 1 THEN
			raise EXP_ERR;
		END IF;
-- DBMS_OUTPUT.PUT_LINE('--> END INSERT ');
	
	END LOOP;

	COMMIT;
-- DBMS_OUTPUT.PUT_LINE('>>> END [MI_BAL_COLLECT] <<<');

	RETURN 0;

EXCEPTION
WHEN EXP_ERR THEN
	ROLLBACK;
--DBMS_OUTPUT.PUT_LINE('Error: Insert last txn error!...');
	RETURN 1;
WHEN DATE_ERR THEN
	ROLLBACK;
--DBMS_OUTPUT.PUT_LINE('Error: The latest batch end date larger than input date!');
	RETURN 1;
WHEN EXP_ERR2 THEN
	ROLLBACK;
--DBMS_OUTPUT.PUT_LINE('Error: no record!...');
	RETURN 1;
WHEN OTHERS THEN
	ROLLBACK;
--DBMS_OUTPUT.PUT_LINE('Error: Other error!...');
--DBMS_OUTPUT.PUT_LINE('Error code ' || SQLCODE|| ': ' || SUBSTR(SQLERRM, 1 , 64));
--RAISE_APPLICATION_ERROR( -20201, 'Error code ' || SQLCODE|| ': ' || SUBSTR(SQLERRM, 1 , 64) );
	RETURN 9;
END SP_HIST_OL_FEE_SUM_COLLECT;
/
