ALTER TABLE MMS_ENTITY
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_ENTITY CASCADE CONSTRAINTS;

CREATE TABLE MMS_ENTITY
(
  ME_ID                VARCHAR2(20 BYTE),
  ME_DESC              VARCHAR2(100 BYTE),
  ME_ENTITY_TYPE       CHAR(3 BYTE),
  ME_MMS_CLIENT_ID     VARCHAR2(10 BYTE),
  ME_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  ME_CREATE_USER       VARCHAR2(20 BYTE),
  ME_UPDATE_TIMESTAMP  DATE,
  ME_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX MMS_ENTITY_IDX01 ON MMS_ENTITY
(ME_ENTITY_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX MMS_ENTITY_IDX02 ON MMS_ENTITY
(ME_MMS_CLIENT_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX MMS_ENTITY_PK ON MMS_ENTITY
(ME_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_ENTITY ADD (
  CONSTRAINT MMS_ENTITY_PK
  PRIMARY KEY
  (ME_ID)
  USING INDEX MMS_ENTITY_PK
  ENABLE VALIDATE);

ALTER TABLE MMS_ENTITY ADD (
  CONSTRAINT MMS_ENTITY_FK01 
  FOREIGN KEY (ME_ENTITY_TYPE) 
  REFERENCES MMS_ENTITY_TYPE (MET_TYPE_CODE)
  ENABLE VALIDATE);

