OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnMgtByUsJLB
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnMgtByUsJLB.so
SOOBJS = TxnMgtByUsJLB.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
