


CREATE TABLE OL_PAYOUT_API_PREGEN_HD
(
  OAP_BATCH_ID          NUMBER(16),
  OAP_PAYOUT_GROUP      VARCHAR2(2 BYTE),
  OAP_STATUS            CHAR(1 BYTE)            DEFAULT 'W'                   NOT NULL,
  OAP_PREGEN_RET_CODE   NUMBER(8),
  OAP_GEN_RET_CODE      NUMBER(8),
  OAP_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate               NOT NULL,
  OAP_CREATE_USER       VARCHAR2(20 BYTE),
  OAP_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate               NOT NULL,
  OAP_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE INDEX OL_PAYOUT_API_PREGEN_HD_IDX01 ON OL_PAYOUT_API_PREGEN_HD
(OAP_CREATE_TIMESTAMP, OAP_UPDATE_TIMESTAMP)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX OL_PAYOUT_API_PREGEN_HD_PK ON OL_PAYOUT_API_PREGEN_HD
(OAP_BATCH_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE OL_PAYOUT_API_PREGEN_HD ADD (
  CONSTRAINT OL_PAYOUT_API_PREGEN_HD_PK
  PRIMARY KEY
  (OAP_BATCH_ID)
  USING INDEX OL_PAYOUT_API_PREGEN_HD_PK
  ENABLE VALIDATE);
