ALTER TABLE EMAIL_TEMPLATE
 DROP PRIMARY KEY CASCADE;

DROP TABLE EMAIL_TEMPLATE CASCADE CONSTRAINTS;

CREATE TABLE EMAIL_TEMPLATE
(
  ET_ID                VARCHAR2(20 BYTE),
  ET_TEMPLATE          VARCHAR2(1024 BYTE),
  ET_CREATE_USER       VARCHAR2(20 BYTE),
  ET_UPDATE_USER       VARCHAR2(20 BYTE),
  ET_CREATE_TIMESTAMP  DATE               DEFAULT SYSDATE,
  ET_UPDATE_TIMESTAMP  DATE               DEFAULT SYSDATE
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX EMAIL_TEMPLATE_PK ON EMAIL_TEMPLATE
(ET_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE EMAIL_TEMPLATE ADD (
  CONSTRAINT EMAIL_TEMPLATE_PK
  PRIMARY KEY
  (ET_ID)
  USING INDEX EMAIL_TEMPLATE_PK
  ENABLE VALIDATE);

