OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmsReverseRetry
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmsReverseRetry.so
SOOBJS =  MmsReverseRetry.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
