ALTER TABLE PSP_DEPOSIT_TRACE
 DROP PRIMARY KEY CASCADE;

DROP TABLE PSP_DEPOSIT_TRACE CASCADE CONSTRAINTS;


CREATE TABLE PSP_DEPOSIT_TRACE
(
 DT_PSP_CHANNEL_CODE             VARCHAR2(10 BYTE),
 DT_TRACE_ON                     INTEGER  DEFAULT 0,
 DT_MODE			 CHAR(1 BYTE) DEFAULT 'S',
 DT_URL				 VARCHAR2(100 BYTE) NOT NULL,
 DT_REQUEST_FUNCTION		 VARCHAR2(50 BYTE),
 DT_ACTION			 VARCHAR2(50 BYTE),
 DT_URL_METHOD			 VARCHAR2(10 BYTE),
 DT_CREATE_USER                  VARCHAR2(20 BYTE),
 DT_UPDATE_USER                  VARCHAR2(20 BYTE),
 DT_CREATE_TIMESTAMP             DATE DEFAULT sysdate,
 DT_UPDATE_TIMESTAMP             DATE DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN PSP_DEPOSIT_TRACE.DT_MODE IS '''S'' - Sync. ''A'' - Async.';

CREATE UNIQUE INDEX PSP_DEPOSIT_TRACE_PK ON PSP_DEPOSIT_TRACE
(DT_PSP_CHANNEL_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PSP_DEPOSIT_TRACE ADD (
  CONSTRAINT PSP_DEPOSIT_TRACE_PK
  PRIMARY KEY
  (DT_PSP_CHANNEL_CODE)
  USING INDEX PSP_DEPOSIT_TRACE_PK
  ENABLE VALIDATE);
