OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnWebOnUs2EEP
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnWebOnUs2EEP.so
SOOBJS = TxnWebOnUs2EEP.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
