ALTER TABLE CPHUSER.PAY_SELECTION
 DROP PRIMARY KEY CASCADE;

DROP TABLE CPHUSER.PAY_SELECTION CASCADE CONSTRAINTS;

CREATE TABLE CPHUSER.PAY_SELECTION
(
  SEQ_NUM       NUMBER(38)                      DEFAULT 1                     NOT NULL,
  FILE_SEQ      VARCHAR2(6 BYTE)                NOT NULL,
  MERCHANT_REF  VARCHAR2(25 BYTE)               NOT NULL,
  ACCOUNT_NUM   VARCHAR2(25 BYTE)               NOT NULL,
  ACCOUNT_NAME  VARCHAR2(25 BYTE),
  BANK_NAME     VARCHAR2(50 BYTE),
  BRANCH        VARCHAR2(50 BYTE),
  AMOUNT        VARCHAR2(12 BYTE),
  CURRENCY      VARCHAR2(3 BYTE),
  PROVINCE      VARCHAR2(20 BYTE),
  CITY          VARCHAR2(20 BYTE),
  STATUS        CHAR(1 BYTE)                    DEFAULT 'Y'                   NOT NULL,
  REF_NUM       NUMBER(38)                      DEFAULT 0
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CPHUSER.PAY_SELECTION_PK ON CPHUSER.PAY_SELECTION
(SEQ_NUM, MERCHANT_REF)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE CPHUSER.PAY_SELECTION ADD (
  CONSTRAINT PAY_SELECTION_PK
  PRIMARY KEY
  (SEQ_NUM, MERCHANT_REF)
  USING INDEX CPHUSER.PAY_SELECTION_PK);

