ALTER TABLE DEF_OPTION_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_OPTION_TYPE CASCADE CONSTRAINTS;

CREATE TABLE DEF_OPTION_TYPE
(
  DO_TYPE              CHAR(1 BYTE),
  DO_DESC              VARCHAR2(20 BYTE),
  DO_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  DO_CREATE_USER       VARCHAR2(20 BYTE),
  DO_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  DO_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEF_OPTIONAL_TYPE_PK ON DEF_OPTION_TYPE
(DO_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_OPTION_TYPE ADD (
  CONSTRAINT DEF_OPTIONAL_TYPE_PK
  PRIMARY KEY
  (DO_TYPE)
  USING INDEX DEF_OPTIONAL_TYPE_PK
  ENABLE VALIDATE);

