INSERT INTO DEF_OPTION_TYPE (DO_TYPE, DO_DESC, DO_CREATE_USER, DO_UPDATE_USER) values ('M','Mandatory','SYSTEM','SYSTEM');
INSERT INTO DEF_OPTION_TYPE (DO_TYPE, DO_DESC, DO_CREATE_USER, DO_UPDATE_USER) values ('O','Optional','SYSTEM','SYSTEM');
INSERT INTO DEF_OPTION_TYPE (DO_TYPE, DO_DESC, DO_CREATE_USER, DO_UPDATE_USER) values ('N','Not Required','SYSTEM','SYSTEM');
commit;
