OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnBalOnUsCOM
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnBalOnUsCOM.so
SOOBJS = TxnBalOnUsCOM.o

include $(HOME)/config/Make.rules

LDLIBS += 
CPPFLAGS += 
all	: $(COMPSO)
