ALTER TABLE OL_BAID_TXN_RELATION
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_BAID_TXN_RELATION CASCADE CONSTRAINTS;

CREATE TABLE OL_BAID_TXN_RELATION
(
  BTR_TXN_ID            VARCHAR2(16 BYTE),
  BTR_BAID_TXN_ID       VARCHAR2(16 BYTE),
  BTR_CREATE_TIMESTAMP  DATE,
  BTR_UPDATE_TIMESTAMP  DATE,
  BTR_CREATE_USER       VARCHAR2(20 BYTE),
  BTR_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX OL_BAID_TXN_RELATION_IDX01 ON OL_BAID_TXN_RELATION
(BTR_BAID_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX OL_BAID_TXN_RELATION_PK ON OL_BAID_TXN_RELATION
(BTR_TXN_ID, BTR_BAID_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_BAID_TXN_RELATION ADD (
  CONSTRAINT OL_BAID_TXN_RELATION_PK
  PRIMARY KEY
  (BTR_TXN_ID, BTR_BAID_TXN_ID)
  USING INDEX OL_BAID_TXN_RELATION_PK
  ENABLE VALIDATE);

