ALTER TABLE BANK_MERCHANT_MAPPING
 DROP PRIMARY KEY CASCADE;

DROP TABLE BANK_MERCHANT_MAPPING CASCADE CONSTRAINTS;

CREATE TABLE BANK_MERCHANT_MAPPING
(
  MM_MERCHANT_ID	      VARCHAR2(15 BYTE)         NOT NULL,
  MM_EXT_BANK_CODE       VARCHAR2(20 BYTE)         NOT NULL,
  MM_INT_BANK_CODE	      VARCHAR2(10 BYTE)          NOT NULL,
  MM_COUNTRY             VARCHAR2(2 BYTE),
  MM_EFFECT_DATE         DATE                      NOT NULL,
  MM_DISABLED            VARCHAR2(1 BYTE)          NOT NULL,
  MM_CREATE_TIMESTAMP    DATE                      DEFAULT SYSDATE,
  MM_UPDATE_TIMESTAMP    DATE                      DEFAULT SYSDATE,
  MM_CREATE_USER         VARCHAR2(25 BYTE),
  MM_UPDATE_USER         VARCHAR2(25 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX BANK_MERCHANT_MAPPING_IDX01 ON BANK_MERCHANT_MAPPING
(MM_MERCHANT_ID, MM_EXT_BANK_CODE, MM_EFFECT_DATE, MM_DISABLED)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX BANK_MERCHANT_MAPPING_PK ON BANK_MERCHANT_MAPPING
(MM_MERCHANT_ID,MM_EXT_BANK_CODE, MM_EFFECT_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE BANK_MERCHANT_MAPPING ADD (
  CONSTRAINT BANK_MERCHANT_MAPPING_PK
  PRIMARY KEY
  (MM_MERCHANT_ID, MM_EXT_BANK_CODE, MM_EFFECT_DATE)
  USING INDEX BANK_MERCHANT_MAPPING_PK);


