ALTER TABLE MERCHANT_UPLOAD_ERROR
 DROP PRIMARY KEY CASCADE;

DROP TABLE MERCHANT_UPLOAD_ERROR CASCADE CONSTRAINTS;

CREATE TABLE MERCHANT_UPLOAD_ERROR
(
  UE_ERROR_ID          INTEGER,
  UE_BATCH_ID          INTEGER,
  UE_RECORD            VARCHAR2(255 BYTE),
  UE_CREATE_USER       VARCHAR2(20 BYTE),
  UE_UPDATE_USER       VARCHAR2(20 BYTE),
  UE_CREATE_TIMESTAMP  DATE                     DEFAULT SYSDATE,
  UE_UPDATE_TIMESTAMP  DATE                     DEFAULT SYSDATE
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MERCHANT_UPLOAD_ERROR_PK ON MERCHANT_UPLOAD_ERROR
(UE_ERROR_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MERCHANT_UPLOAD_ERROR ADD (
  CONSTRAINT MERCHANT_UPLOAD_ERROR_PK
  PRIMARY KEY
  (UE_ERROR_ID)
  USING INDEX MERCHANT_UPLOAD_ERROR_PK
  ENABLE VALIDATE);

ALTER TABLE MERCHANT_UPLOAD_ERROR ADD (
  CONSTRAINT MERCHANT_UPLOAD_ERROR_FK01 
  FOREIGN KEY (UE_BATCH_ID) 
  REFERENCES MERCHANT_UPLOAD_FILE_HEADER (UH_BATCH_ID)
  ENABLE VALIDATE);

