ALTER TABLE DEF_RELEASE_PERIOD_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_RELEASE_PERIOD_TYPE CASCADE CONSTRAINTS;

CREATE TABLE DEF_RELEASE_PERIOD_TYPE
(
  RP_TYPE              VARCHAR2(10 BYTE),
  RP_DESC              VARCHAR2(50 BYTE),
  RP_CREATE_USER       VARCHAR2(20 BYTE),
  RP_UPDATE_USER       VARCHAR2(20 BYTE),
  RP_CREATE_TIMESTAMP  DATE,
  RP_UPDATE_TIMESTAMP  DATE
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEF_RELEASE_PERIOD_TYPE_PK ON DEF_RELEASE_PERIOD_TYPE
(RP_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_RELEASE_PERIOD_TYPE ADD (
  CONSTRAINT DEF_RELEASE_PERIOD_TYPE_PK
  PRIMARY KEY
  (RP_TYPE)
  USING INDEX DEF_RELEASE_PERIOD_TYPE_PK
  ENABLE VALIDATE);

