CREATE TABLE PID_BANK_GROUP_MAPPING
(
  PGM_SERVICE_CODE		CHAR(3 BYTE),
  PGM_PID_GROUP    		VARCHAR2(20 BYTE),
  PGM_BANK_GROUP        VARCHAR2(10 BYTE),
  PGM_BANK_CODE         VARCHAR2(10 BYTE),
  PGM_DEVICE_TYPE       CHAR(1 BYTE),
  PGM_DISABLED          INTEGER                  DEFAULT 0,
  PGM_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  PGM_CREATE_USER       VARCHAR2(20 BYTE),
  PGM_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  PGM_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX PID_BANK_GROUP_MAPPING_PK ON PID_BANK_GROUP_MAPPING
(PGM_SERVICE_CODE, PGM_PID_GROUP, PGM_BANK_GROUP, PGM_BANK_CODE, PGM_DEVICE_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE PID_BANK_GROUP_MAPPING ADD (
  CONSTRAINT PID_BANK_GROUP_MAPPING_PK
  PRIMARY KEY
  (PGM_SERVICE_CODE, PGM_PID_GROUP, PGM_BANK_GROUP, PGM_BANK_CODE, PGM_DEVICE_TYPE)
  USING INDEX PID_BANK_GROUP_MAPPING_PK
  ENABLE VALIDATE);
