ALTER TABLE CRR_PSP_PRODUCT_CODE_MAP
 DROP PRIMARY KEY CASCADE;

DROP TABLE CRR_PSP_PRODUCT_CODE_MAP CASCADE CONSTRAINTS;

CREATE TABLE CRR_PSP_PRODUCT_CODE_MAP
(
  PM_PSP_ID            VARCHAR2(10 BYTE)        NOT NULL,
  PM_BUSINESS_TYPE     CHAR(1 BYTE)             NOT NULL,
  PM_PRODUCT_CODE      VARCHAR2(3 BYTE)         NOT NULL,
  PM_DISABLED          INTEGER,
  PM_CREATE_USER       VARCHAR2(20 BYTE),
  PM_CREATE_TIMESTAMP  DATE                     DEFAULT SYSDATE,
  PM_UPDATE_USER       VARCHAR2(20 BYTE),
  PM_UPDATE_TIMESTAMP  DATE                     DEFAULT SYSDATE
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CRR_PSP_PRODUCT_CODE_MAP_PK ON CRR_PSP_PRODUCT_CODE_MAP
(PM_PSP_ID, PM_BUSINESS_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE CRR_PSP_PRODUCT_CODE_MAP ADD (
  CONSTRAINT CRR_PSP_PRODUCT_CODE_MAP_PK
  PRIMARY KEY
  (PM_PSP_ID, PM_BUSINESS_TYPE)
  USING INDEX CRR_PSP_PRODUCT_CODE_MAP_PK
  ENABLE VALIDATE);

ALTER TABLE CRR_PSP_PRODUCT_CODE_MAP ADD (
  CONSTRAINT CRR_PSP_PRODUCT_CODE_MAP_FK02 
  FOREIGN KEY (PM_BUSINESS_TYPE) 
  REFERENCES DEF_BUSINESS_TYPE (BT_TYPE)
  ENABLE VALIDATE);

