OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnWebOnUsWTD
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnWebOnUsWTD.so
SOOBJS = TxnWebOnUsWTD.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
