OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/DefAutoSettlementType
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBDefAutoSettlementType.so
SOOBJS =  DefAutoSettlementType.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
