ALTER TABLE AUTO_SETTLEMENT_EXEC_LOG
 DROP PRIMARY KEY CASCADE;

DROP TABLE AUTO_SETTLEMENT_EXEC_LOG CASCADE CONSTRAINTS;

CREATE TABLE AUTO_SETTLEMENT_EXEC_LOG
(
  AL_MERCHANT_ID           VARCHAR2(15 BYTE),
  AL_COUNTRY               CHAR(2 BYTE),
  AL_CCY_ID                VARCHAR2(3 BYTE),
  AL_SERVICE_CODE          CHAR(3 BYTE),
  AL_RULE_TYPE             CHAR(1 BYTE),
  AL_LAST_SETTLEMENT_DATE  VARCHAR2(8 BYTE),
  AL_STATUS                CHAR(1 BYTE),
  AL_TXN_ID                VARCHAR2(16 BYTE),
  AL_CREATE_USER           VARCHAR2(20 BYTE),
  AL_UPDATE_USER           VARCHAR2(20 BYTE),
  AL_CREATE_TIMESTAMP      DATE,
  AL_UPDATE_TIMESTAMP      DATE
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX AUTO_SETTLEMENT_EXEC_LOG_IDX01 ON AUTO_SETTLEMENT_EXEC_LOG
(AL_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX AUTO_SETTLEMENT_EXEC_LOG_PK ON AUTO_SETTLEMENT_EXEC_LOG
(AL_MERCHANT_ID, AL_COUNTRY, AL_CCY_ID, AL_SERVICE_CODE, AL_RULE_TYPE, 
AL_LAST_SETTLEMENT_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE AUTO_SETTLEMENT_EXEC_LOG ADD (
  CONSTRAINT AUTO_SETTLEMENT_EXEC_LOG_PK
  PRIMARY KEY
  (AL_MERCHANT_ID, AL_COUNTRY, AL_CCY_ID, AL_SERVICE_CODE, AL_RULE_TYPE, AL_LAST_SETTLEMENT_DATE)
  USING INDEX AUTO_SETTLEMENT_EXEC_LOG_PK
  ENABLE VALIDATE);

