OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLTxnEngine
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLTxnEngine.so
SOOBJS =  OLTxnEngine.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
