OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/PaypageQrTimeParam
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBPaypageQrTimeParam.so
SOOBJS =  PaypageQrTimeParam.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
