ALTER TABLE OL_PSP_DETAIL
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_PSP_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE OL_PSP_DETAIL
(
  OPD_PSP_ID                   VARCHAR2(10 BYTE),
  OPD_PSP_NAME                 VARCHAR2(50 BYTE) NOT NULL,
  OPD_DISABLED                 INTEGER          DEFAULT 0                     NOT NULL,
  OPD_CLIENT_ID                VARCHAR2(10 BYTE) NOT NULL,
  OPD_PSP_TYPE                 CHAR(1 BYTE)     NOT NULL,
  OPD_PRECAL_FEE               INTEGER          DEFAULT 0,
  OPD_PRECAL_TYPE              CHAR(1 BYTE),
  OPD_PRECAL_VALUE             NUMBER(12,5),
  OPD_PRECAL_ADDITIONAL_VALUE  NUMBER(12,2),
  OPD_TXN_TYPE                 CHAR(1 BYTE),
  OPD_STATUS                   VARCHAR2(2 BYTE),
  OPD_PSP_REMARK               VARCHAR2(255 BYTE),
  OPD_CREATE_TIMESTAMP         DATE             NOT NULL,
  OPD_UPDATE_TIMESTAMP         DATE             NOT NULL,
  OPD_CREATE_USER              VARCHAR2(20 BYTE) NOT NULL,
  OPD_UPDATE_USER              VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_PSP_DETAIL_PK ON OL_PSP_DETAIL
(OPD_PSP_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_PSP_DETAIL ADD (
  CONSTRAINT OL_PSP_DETAIL_PK
  PRIMARY KEY
  (OPD_PSP_ID)
  USING INDEX OL_PSP_DETAIL_PK
  ENABLE VALIDATE);

ALTER TABLE OL_PSP_DETAIL ADD (
  CONSTRAINT OL_PSP_DETAIL_FK01 
  FOREIGN KEY (OPD_CLIENT_ID) 
  REFERENCES PSP_MASTER (PM_CLIENT_ID)
  ENABLE VALIDATE);

