


ALTER TABLE OL_DEF_PAYOUT_GROUP
 ADD (OPG_SUPPORT_FILE_UPLOAD  INTEGER               DEFAULT 0);

ALTER TABLE OL_DEF_PAYOUT_GROUP
 ADD (OPG_SUPPORT_API  INTEGER                       DEFAULT 0);
 
