ALTER TABLE OL_DEF_PAYOUT_GROUP
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_DEF_PAYOUT_GROUP CASCADE CONSTRAINTS;

CREATE TABLE OL_DEF_PAYOUT_GROUP
(
  OPG_GROUP	       CHAR(1 BYTE),
  OPG_DESC              VARCHAR2(50 BYTE),
  OPG_CREATE_TIMESTAMP  DATE                      DEFAULT sysdate,
  OPG_CREATE_USER       VARCHAR2(20 BYTE),
  OPG_UPDATE_TIMESTAMP  DATE                      DEFAULT sysdate,
  OPG_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_DEF_PAYOUT_GROUP_PK ON OL_DEF_PAYOUT_GROUP
(OPG_GROUP)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_DEF_PAYOUT_GROUP ADD (
  CONSTRAINT OL_DEF_PAYOUT_GROUP_PK
  PRIMARY KEY
  (OPG_GROUP)
  USING INDEX OL_DEF_PAYOUT_GROUP_PK
  ENABLE VALIDATE);

