OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/TxnSuppInfo
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBTxnSuppInfo.so
SOOBJS =  TxnSuppInfo.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
