OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOMmsBalance
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOMmsBalance.so
SOOBJS = BOMmsBalance.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
