OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLTxnEngineTxnCodeGrp
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLTxnEngineTxnCodeGrp.so
SOOBJS =  OLTxnEngineTxnCodeGrp.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
