OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmsDefTxnStatusMap
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmsDefTxnStatusMap.so
SOOBJS =  MmsDefTxnStatusMap.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
