OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/SebBalance
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBSebBalance.so
SOOBJS =  SebBalance.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
