


CREATE TABLE OL_PREGEN_DAILY_REPORT
(
  OPDR_ID                  NUMBER(16)             NOT NULL,
  OPDR_REPORT_CODE         CHAR(3 BYTE)           NOT NULL,
  OPDR_MERCHANT_ID         VARCHAR2(15 BYTE),
  OPDR_COUNTRY_ID          CHAR(2 BYTE),
  OPDR_CURRENCY_ID         VARCHAR2(3 BYTE),
  OPDR_SERVICE_CODE        CHAR(3 BYTE),
  OPDR_REPORT_DATE         VARCHAR2(8 BYTE)       NOT NULL,
  OPDR_FILENAME            VARCHAR2(100 BYTE),
  OPDR_STATUS              CHAR(1 BYTE),
  OPDR_DISABLED            INTEGER                DEFAULT 0,
  OPDR_CREATE_TIMESTAMP    DATE                   DEFAULT sysdate,
  OPDR_CREATE_USER         VARCHAR2(20 BYTE),
  OPDR_UPDATE_TIMESTAMP    DATE                   DEFAULT sysdate,
  OPDR_UPDATE_USER         VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;


CREATE INDEX OL_PREGEN_DAILY_REPORT_IDX1 ON OL_PREGEN_DAILY_REPORT
(OPDR_REPORT_CODE,OPDR_REPORT_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

		   
CREATE INDEX OL_PREGEN_DAILY_REPORT_IDX2 ON OL_PREGEN_DAILY_REPORT
(OPDR_REPORT_CODE,OPDR_MERCHANT_ID,OPDR_COUNTRY_ID,OPDR_CURRENCY_ID,OPDR_SERVICE_CODE,OPDR_REPORT_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );		   
		   
		   

CREATE UNIQUE INDEX OL_PREGEN_DAILY_REPORT_PK ON OL_PREGEN_DAILY_REPORT
(OPDR_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE OL_PREGEN_DAILY_REPORT ADD (
  CONSTRAINT OL_PREGEN_DAILY_REPORT_PK
  PRIMARY KEY
  (OPDR_ID)
  USING INDEX OL_PREGEN_DAILY_REPORT_PK
  ENABLE VALIDATE);

ALTER TABLE OL_PREGEN_DAILY_REPORT ADD (
  CONSTRAINT OL_PREGEN_DAILY_REPORT_FK01
  FOREIGN KEY (OPDR_REPORT_CODE)
  REFERENCES OL_DEF_REPORT_TYPE (ODRT_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OL_PREGEN_DAILY_REPORT_FK02
  FOREIGN KEY (OPDR_MERCHANT_ID)
  REFERENCES OL_MERCH_DETAIL (MD_MERCHANT_ID)
  ENABLE VALIDATE,
  CONSTRAINT OL_PREGEN_DAILY_REPORT_FK03
  FOREIGN KEY (OPDR_COUNTRY_ID)
  REFERENCES COUNTRY (COUNTRY_CODE)
  ENABLE VALIDATE,
  CONSTRAINT OL_PREGEN_DAILY_REPORT_FK04
  FOREIGN KEY (OPDR_CURRENCY_ID)
  REFERENCES DEF_CURRENCY (DC_CCY_ID)
  ENABLE VALIDATE,
  CONSTRAINT OL_PREGEN_DAILY_REPORT_FK05
  FOREIGN KEY (OPDR_SERVICE_CODE)
  REFERENCES DEF_SERVICE_CODE (SC_CODE)
  ENABLE VALIDATE,
  CONSTRAINT OL_PREGEN_DAILY_REPORT_FK06
  FOREIGN KEY (OPDR_STATUS)
  REFERENCES DEF_PREGEN_RPT_STATUS (DS_TYPE)
  ENABLE VALIDATE);
