ALTER TABLE OL_RULE_AM_SCHEDULER_HD
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_RULE_AM_SCHEDULER_HD CASCADE CONSTRAINTS;

CREATE TABLE OL_RULE_AM_SCHEDULER_HD
(
  RAS_SCHEDULER_ID      INTEGER,
  RAS_DESC              VARCHAR2(50 BYTE),
  RAS_EFFECT_DATETIME   DATE,
  RAS_DISABLED          INTEGER                  DEFAULT 0,
  RAS_CREATE_USER       VARCHAR2(20 BYTE),
  RAS_UPDATE_USER       VARCHAR2(20 BYTE),
  RAS_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  RAS_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX OL_RULE_AM_SCHEDULER_HD_IDX01 ON OL_RULE_AM_SCHEDULER_HD
(RAS_SCHEDULER_ID, RAS_EFFECT_DATETIME, RAS_DISABLED)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

CREATE UNIQUE INDEX OL_RULE_AM_SCHEDULER_HD_PK ON OL_RULE_AM_SCHEDULER_HD
(RAS_SCHEDULER_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_RULE_AM_SCHEDULER_HD ADD (
  CONSTRAINT OL_RULE_AM_SCHEDULER_HD_PK
  PRIMARY KEY
  (RAS_SCHEDULER_ID)
  USING INDEX OL_RULE_AM_SCHEDULER_HD_PK);

