OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOOLSettlement
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOOLSettlement.so
SOOBJS = BOOLSettlement.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
