OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOTxnLb
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOTxnLb.so
SOOBJS = BOTxnLb.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
