ALTER TABLE MOB_BANK_MAP
 DROP PRIMARY KEY CASCADE;

DROP TABLE MOB_BANK_MAP CASCADE CONSTRAINTS;

CREATE TABLE MOB_BANK_MAP
(
  MBM_GROUP             VARCHAR2(10 BYTE),
  MBM_BANK_CODE         VARCHAR2(10 BYTE),
  MBM_IS_DEFAULT	INTEGER                  DEFAULT 0,
  MBM_IS_FE_USE		INTEGER			 DEFAULT 0,
  MBM_FE_DESC		VARCHAR2(20 BYTE),
  MBM_DISABLED		INTEGER			 DEFAULT 0,
  MBM_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  MBM_CREATE_USER       VARCHAR2(20 BYTE),
  MBM_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  MBM_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MOB_BANK_MAP_PK ON MOB_BANK_MAP
(MBM_GROUP,MBM_BANK_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MOB_BANK_MAP ADD (
  CONSTRAINT MOB_BANK_MAP_PK
  PRIMARY KEY
  (MBM_GROUP,MBM_BANK_CODE)
  USING INDEX MOB_BANK_MAP_PK
  ENABLE VALIDATE);

