OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOMMMTxnElements
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOMMMTxnElements.so
SOOBJS = BOMMMTxnElements.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
