OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/TestMicBal
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBTestMicBal.so
SOOBJS =  TestMicBal.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
