ALTER TABLE RULE_EX_MARKUP
 DROP PRIMARY KEY CASCADE;

DROP TABLE RULE_EX_MARKUP CASCADE CONSTRAINTS;

CREATE TABLE RULE_EX_MARKUP
(
  RX_TXN_CODE          CHAR(3 BYTE),
  RX_COUNTRY           CHAR(2 BYTE),
  RX_CHANNEL_CODE      CHAR(3 BYTE),
  RX_SERVICE_CODE      CHAR(3 BYTE),
  RX_PARTY_TYPE        CHAR(1 BYTE),
  RX_PARTY_ID          VARCHAR2(15 BYTE),
  RX_RATE              NUMBER(12,5)             DEFAULT 0.0                   NOT NULL,
  RX_RESTRICTED_RATE   NUMBER(12,5)             DEFAULT 0.0                   NOT NULL,
  RX_DISABLED          INTEGER,
  RX_CREATE_TIMESTAMP  DATE,
  RX_UPDATE_TIMESTAMP  DATE,
  RX_CREATE_USER       VARCHAR2(20 BYTE),
  RX_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX RULE_EX_MARKUP_IDX01 ON RULE_EX_MARKUP
(RX_TXN_CODE, RX_COUNTRY, RX_CHANNEL_CODE, RX_SERVICE_CODE, RX_PARTY_TYPE, 
RX_PARTY_ID, RX_DISABLED)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX RULE_EX_MARKUP_IDX02 ON RULE_EX_MARKUP
(RX_TXN_CODE, RX_COUNTRY, RX_CHANNEL_CODE, RX_SERVICE_CODE, RX_PARTY_TYPE, 
RX_DISABLED)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RULE_EX_MARKUP_PK ON RULE_EX_MARKUP
(RX_TXN_CODE, RX_COUNTRY, RX_CHANNEL_CODE, RX_SERVICE_CODE, RX_PARTY_TYPE, 
RX_PARTY_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE RULE_EX_MARKUP ADD (
  CONSTRAINT RULE_EX_MARKUP_PK
  PRIMARY KEY
  (RX_TXN_CODE, RX_COUNTRY, RX_CHANNEL_CODE, RX_SERVICE_CODE, RX_PARTY_TYPE, RX_PARTY_ID)
  USING INDEX RULE_EX_MARKUP_IDX01
  ENABLE VALIDATE);

ALTER TABLE RULE_EX_MARKUP ADD (
  CONSTRAINT RULE_EX_MARKUP_FK02 
  FOREIGN KEY (RX_TXN_CODE) 
  REFERENCES TXN_CODE (TC_CODE)
  ENABLE VALIDATE,
  CONSTRAINT RULE_EX_MARKUP_FK03 
  FOREIGN KEY (RX_COUNTRY) 
  REFERENCES COUNTRY (COUNTRY_CODE)
  ENABLE VALIDATE,
  CONSTRAINT RULE_EX_MARKUP_FK04 
  FOREIGN KEY (RX_SERVICE_CODE) 
  REFERENCES DEF_SERVICE_CODE (SC_CODE)
  ENABLE VALIDATE,
  CONSTRAINT RULE_EX_MARKUP_FK05 
  FOREIGN KEY (RX_CHANNEL_CODE) 
  REFERENCES DEF_CHANNEL (DC_CODE)
  ENABLE VALIDATE,
  CONSTRAINT RULE_EX_MARKUP_FK06 
  FOREIGN KEY (RX_PARTY_TYPE) 
  REFERENCES DEF_PARTY_TYPE (DP_TYPE)
  ENABLE VALIDATE);

