OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmsStoreForward
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmsStoreForward.so
SOOBJS =  MmsStoreForward.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
