OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLTxnEngineTxnCodeMap
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLTxnEngineTxnCodeMap.so
SOOBJS =  OLTxnEngineTxnCodeMap.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
