OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOOLTxnEngineSpc
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOOLTxnEngineSpc.so
SOOBJS = BOOLTxnEngineSpc.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
