DROP VIEW TEST_OP_MERCH_TXN_SUMMARY_VIEW;

CREATE OR REPLACE FORCE VIEW TEST_OP_MERCH_TXN_SUMMARY_VIEW
(
   MERCHANT_ID,
   MERCHANT_SHORT_NAME,
   CLIENT_ID,
   CLIENT,
   TXN_COUNTRY_CODE,
   TXN_COUNTRY,
   SERVICE_CODE,
   SERVICE,
   CRR_PRODUCT_CODE,
   CRR_PRODUCT,
   TXN_TYPE_CODE,
   TXN_TYPE,
   SUB_TXN_TYPE_CODE,
   SUB_TXN_TYPE,
   TXN_CCY_CODE,
   TXN_CCY,
   TXN_AMOUNT,
   APPROVAL_TIMESTAMP
)
AS

select MERCHANT_ID,
       MERCHANT_SHORT_NAME,
       CLIENT_ID,
       CLIENT,
       TXN_COUNTRY_CODE,
       TXN_COUNTRY,
       SERVICE_CODE,
       SERVICE,
       CRR_PRODUCT_CODE,
       CRR_PRODUCT,
       TXN_TYPE_CODE,
       TXN_TYPE,
       SUB_TXN_TYPE_CODE,
       nvl(mt_desc,DEF_SUB_TXN_TYPE) as SUB_TXN_TYPE,
       TXN_CCY_CODE,
       TXN_CCY,
       TXN_AMOUNT,
       APPROVAL_TIMESATMP

from
(
   SELECT TH_MERCHANT_ID AS MERCHANT_ID,
          SHORT_NAME AS MERCHANT_SHORT_NAME,
          TH_CLIENT_ID AS CLIENT_ID,
          CLIENT_NAME AS CLIENT,
          TD_TXN_COUNTRY AS TXN_COUNTRY_CODE,
          COUNTRY_NAME AS TXN_COUNTRY,
          TH_SERVICE_CODE AS SERVICE_CODE,
          SC_DESC AS SERVICE,
          PM_PRODUCT_CODE AS CRR_PRODUCT_CODE,
          DP_DESC AS CRR_PRODUCT,
          TH_TXN_CODE AS TXN_TYPE_CODE,
          TC_DESC AS TXN_TYPE,
          TE_TXN_ELEMENT_TYPE AS SUB_TXN_TYPE_CODE,
          DT_DESC AS DEF_SUB_TXN_TYPE,
          TE_CCY AS TXN_CCY_CODE,
          DC_DESC AS TXN_CCY,
          TE_AMOUNT AS TXN_AMOUNT,
          TH_APPROVAL_TIMESTAMP AS APPROVAL_TIMESATMP
     FROM (SELECT TH_TXN_ID,
                  TH_MERCHANT_ID,
                  TH_CLIENT_ID,
                  TH_SERVICE_CODE,
                  TH_TXN_CODE,
                  TH_APPROVAL_DATE,
                  TH_APPROVAL_TIMESTAMP
             FROM TXN_HEADER),
             def_element_type,
          (SELECT TD_TXN_ID, TD_TXN_COUNTRY FROM TXN_DETAIL),
          (SELECT TE_TXN_ID,
                  TE_TXN_ELEMENT_TYPE,
                  TE_PARTY_TYPE,
                  TE_CCY,
                  TE_AMOUNT
             FROM TXN_ELEMENTS),
          (SELECT PM_MERCHANT_ID,
                  PM_SERVICE_CODE,
                  PM_COUNTRY,
                  PM_PRODUCT_CODE
             FROM CRR_PRODUCT_CODE_MAP),
          (SELECT MERCHANT_ID, SHORT_NAME FROM MERCH_DETAIL) MERCH_DETAIL,
          (SELECT CLIENT_ID, CLIENT_NAME FROM CLIENTS) CLIENTS,
          (SELECT TC_CODE, TC_DESC, TC_MERCHANT_TXN_DISPLAY FROM TXN_CODE),
          (SELECT DP_ID, DP_DESC FROM DEF_PRODUCT),
          (SELECT SC_CODE, SC_DESC FROM DEF_SERVICE_CODE),
          (SELECT COUNTRY_CODE, COUNTRY_NAME FROM COUNTRY),
          (SELECT DC_CCY_ID, DC_DESC FROM DEF_CURRENCY)
    WHERE     TH_TXN_ID = TD_TXN_ID
          AND TH_TXN_ID = TE_TXN_ID
          AND TE_PARTY_TYPE = 'M'
          AND TH_MERCHANT_ID = MERCH_DETAIL.MERCHANT_ID
          AND TH_CLIENT_ID = CLIENTS.CLIENT_ID
          AND TH_MERCHANT_ID = PM_MERCHANT_ID
          AND TH_SERVICE_CODE = PM_SERVICE_CODE
          AND TD_TXN_COUNTRY = PM_COUNTRY
          AND TH_TXN_CODE = TC_CODE
          AND PM_PRODUCT_CODE = DP_ID
          AND TH_SERVICE_CODE = SC_CODE
          AND TD_TXN_COUNTRY = COUNTRY_CODE
          AND TE_CCY = DC_CCY_ID
          AND TH_MERCHANT_ID IS NOT NULL
          AND TH_APPROVAL_DATE IS NOT NULL
          AND TC_MERCHANT_TXN_DISPLAY = 1
          AND te_txn_element_type = dt_type)
  left join map_txn_element
        on    SUB_TXN_TYPE_CODE = mt_element
        and   TXN_TYPE_CODE = mt_txn_code
          
          
;

