OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MiEntityPit
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMiEntityPit.so
SOOBJS =  MiEntityPit.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
