OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLPregenDailyReport
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLPregenDailyReport.so
SOOBJS =  OLPregenDailyReport.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
