ALTER TABLE MMS_ENTITY_NATURE_GRP_VAL
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_ENTITY_NATURE_GRP_VAL CASCADE CONSTRAINTS;

CREATE TABLE MMS_ENTITY_NATURE_GRP_VAL
(
  MV_CODE_ID           VARCHAR2(5 BYTE),
  MV_CODE_VALUE        VARCHAR2(20 BYTE),
  MV_CODE_DESC         VARCHAR2(100 BYTE),
  MV_CREATE_TIMESTAMP  DATE,
  MV_CREATE_USER       VARCHAR2(20 BYTE),
  MV_UPDATE_TIMESTAMP  DATE,
  MV_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MMS_ENTITY_NATURE_GRP_VAL_PK ON MMS_ENTITY_NATURE_GRP_VAL
(MV_CODE_ID, MV_CODE_VALUE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_ENTITY_NATURE_GRP_VAL ADD (
  CONSTRAINT MMS_ENTITY_NATURE_GRP_VAL_PK
  PRIMARY KEY
  (MV_CODE_ID, MV_CODE_VALUE)
  USING INDEX MMS_ENTITY_NATURE_GRP_VAL_PK
  ENABLE VALIDATE);

ALTER TABLE MMS_ENTITY_NATURE_GRP_VAL ADD (
  CONSTRAINT MMS_ENTITY_NATURE_GRP_VAL_FK01 
  FOREIGN KEY (MV_CODE_ID) 
  REFERENCES MMS_ENTITY_NATURE_GRP (MENG_CODE_ID)
  ENABLE VALIDATE);

