ALTER TABLE OL_STMT_MATCH_RULE
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_STMT_MATCH_RULE CASCADE CONSTRAINTS;

CREATE TABLE OL_STMT_MATCH_RULE
(
  OSMR_RULE_ID           INTEGER,
  OSMR_SUB_RULE_ID       INTEGER,
  OSMR_ACTION_SEQ        INTEGER,
  OSMR_ACTION_TYPE       VARCHAR2(50 BYTE),
  OSMR_ACTION_FILTER_ID  INTEGER,
  OSMR_EXIT_ON_ERROR     INTEGER,
  OSMR_DISABLED          INTEGER                DEFAULT 0,
  OSMR_CREATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  OSMR_CREATE_USER       VARCHAR2(20 BYTE),
  OSMR_UPDATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  OSMR_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX OL_STMT_MATCH_RULE_IDX01 ON OL_STMT_MATCH_RULE
(OSMR_RULE_ID)
LOGGING
TABLESPACE USER_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX OL_STMT_MATCH_RULE_PK ON OL_STMT_MATCH_RULE
(OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_STMT_MATCH_RULE ADD (
  CONSTRAINT OL_STMT_MATCH_RULE_PK
  PRIMARY KEY
  (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID)
  USING INDEX OL_STMT_MATCH_RULE_PK
  ENABLE VALIDATE);

