Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_EXIT_ON_ERROR, OSMR_DISABLED, 
    OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, OSMR_UPDATE_USER)
 Values
   (1, 1, 1, 1, 0, 
    sysdate, 'SYSTEM', sysdate, 'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_EXIT_ON_ERROR, OSMR_DISABLED, 
    OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, OSMR_UPDATE_USER)
 Values
   (2, 1, 1, 1, 0, 
    sysdate, 'SYSTEM', sysdate, 'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (3, 1, 1, 'fr_baid1_to_log1', 101, 
    1, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (4, 1, 1, 'fr_baid1_to_log1', 105, 
    1, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (4, 1, 2, 'fr_log1_to_log2', 0, 
    1, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (4, 1, 3, 'fr_log2_to_baid2', 106, 
    0, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (4, 1, 4, 'fr_log2_to_baid2', 107, 
    1, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_EXIT_ON_ERROR, OSMR_DISABLED, 
    OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, OSMR_UPDATE_USER)
 Values
   (4, 2, 1, 1, 0, 
    sysdate, 'SYSTEM', sysdate, 'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (4, 3, 1, 'fr_baid1_to_log1', 108, 
    1, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (4, 3, 2, 'fr_log1_to_log2', 0, 
    1, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (4, 3, 3, 'fr_log2_to_baid2', 109, 
    0, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (4, 3, 4, 'fr_log2_to_baid2', 110, 
    1, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (5, 1, 1, 'fr_baid1_to_log1', 111, 
    1, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (5, 1, 2, 'fr_log1_to_baid2', 112, 
    1, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (6, 1, 1, 'fr_baid1_to_log1', 102, 
    1, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (6, 1, 2, 'fr_log1_to_log2', 0, 
    1, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (6, 1, 3, 'fr_log2_to_baid2', 103, 
    0, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (6, 1, 4, 'fr_log2_to_baid2', 104, 
    1, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (7, 1, 1, 'fr_baid1_to_log1', 113, 
    1, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (7, 1, 2, 'fr_log1_to_baid2', 114, 
    1, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (8, 1, 1, 'fr_baid1_to_log1', 115, 
    1, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (8, 1, 2, 'fr_log1_to_log2', 0, 
    1, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (8, 1, 3, 'fr_log2_to_baid2', 116, 
    0, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (8, 1, 4, 'fr_log2_to_baid2', 117, 
    1, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (9, 1, 1, 'fr_baid1_to_log1', 118, 
    1, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (9, 1, 2, 'fr_log1_to_log2', 0, 
    1, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (9, 1, 3, 'fr_log2_to_baid2', 119, 
    0, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (9, 1, 4, 'fr_log2_to_baid2', 120, 
    1, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_EXIT_ON_ERROR, OSMR_DISABLED, 
    OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, OSMR_UPDATE_USER)
 Values
   (9, 2, 1, 1, 0, 
    sysdate, 'SYSTEM', sysdate, 'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (9, 3, 1, 'fr_baid1_to_log1', 121, 
    1, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (9, 3, 2, 'fr_log1_to_log2', 0, 
    1, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (9, 3, 3, 'fr_log2_to_baid2', 122, 
    0, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (9, 3, 4, 'fr_log2_to_baid2', 123, 
    1, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (10, 1, 1, 'fr_baid1_to_log1', 124, 
    1, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (10, 1, 2, 'fr_log1_to_log2', 0, 
    1, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (10, 1, 3, 'fr_log2_to_baid2', 125, 
    0, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (10, 1, 4, 'fr_log2_to_baid2', 126, 
    1, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (10, 2, 1, 'fr_baid1_to_log1', 127, 
    1, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (10, 2, 2, 'fr_log1_to_log2', 0, 
    1, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (10, 2, 3, 'fr_log2_to_baid2', 128, 
    0, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (10, 2, 4, 'fr_log2_to_baid2', 129, 
    1, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (11, 1, 1, 'fr_baid1_to_log1', 130, 
    1, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (11, 1, 2, 'fr_log1_to_log2', 0, 
    1, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (11, 1, 3, 'fr_log2_to_baid2', 131, 
    0, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (11, 1, 4, 'fr_log2_to_baid2', 132, 
    1, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (11, 2, 1, 'fr_baid1_to_log1', 133, 
    1, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (11, 2, 2, 'fr_log1_to_log2', 0, 
    1, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (11, 2, 3, 'fr_log2_to_baid2', 134, 
    0, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (11, 2, 4, 'fr_log2_to_baid2', 135, 
    1, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_EXIT_ON_ERROR, OSMR_DISABLED, 
    OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, OSMR_UPDATE_USER)
 Values
   (12, 1, 1, 1, 0, 
    sysdate, 'SYSTEM', sysdate, 'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_EXIT_ON_ERROR, OSMR_DISABLED, 
    OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, OSMR_UPDATE_USER)
 Values
   (13, 1, 1, 1, 0, 
    sysdate, 'SYSTEM', sysdate, 'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_EXIT_ON_ERROR, OSMR_DISABLED, 
    OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, OSMR_UPDATE_USER)
 Values
   (14, 1, 1, 1, 0, 
    sysdate, 'SYSTEM', sysdate, 'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_EXIT_ON_ERROR, OSMR_DISABLED, 
    OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, OSMR_UPDATE_USER)
 Values
   (15, 1, 1, 1, 0, 
    sysdate, 'SYSTEM', sysdate, 'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (16, 1, 1, 'fr_baid1_to_log1', 136, 
    1, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (16, 1, 2, 'fr_log1_to_baid2', 137, 
    1, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (16, 2, 1, 'fr_baid1_to_log1', 138, 
    1, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (16, 2, 2, 'fr_log1_to_baid2', 139, 
    1, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (17, 1, 1, 'fr_baid1_to_log1', 140, 
    1, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (17, 1, 2, 'fr_log1_to_log2', 0, 
    1, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (17, 1, 3, 'fr_log2_to_baid2', 141, 
    0, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (17, 1, 4, 'fr_log2_to_baid2', 142, 
    1, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (17, 2, 1, 'fr_baid1_to_log1', 143, 
    1, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (17, 2, 2, 'fr_log1_to_log2', 0, 
    1, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (17, 2, 3, 'fr_log2_to_baid2', 144, 
    0, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_ACTION_TYPE, OSMR_ACTION_FILTER_ID, 
    OSMR_EXIT_ON_ERROR, OSMR_DISABLED, OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, 
    OSMR_UPDATE_USER)
 Values
   (17, 2, 4, 'fr_log2_to_baid2', 145, 
    1, 0, sysdate, 'SYSTEM', sysdate, 
    'SYSTEM');
Insert into OL_STMT_MATCH_RULE
   (OSMR_RULE_ID, OSMR_SUB_RULE_ID, OSMR_ACTION_SEQ, OSMR_EXIT_ON_ERROR, OSMR_DISABLED, 
    OSMR_CREATE_TIMESTAMP, OSMR_CREATE_USER, OSMR_UPDATE_TIMESTAMP, OSMR_UPDATE_USER)
 Values
   (18, 1, 1, 1, 0, 
    sysdate, 'SYSTEM', sysdate, 'SYSTEM');

