OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/PayoutOperatorTypeDetail
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBPayoutOperatorTypeDetail.so
SOOBJS =  PayoutOperatorTypeDetail.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
