OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOFee
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOFee.so
SOOBJS = BOFee.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
