ALTER TABLE TXN_LB_STP
 DROP PRIMARY KEY CASCADE;

DROP TABLE TXN_LB_STP CASCADE CONSTRAINTS;

CREATE TABLE TXN_LB_STP
(
  TL_COUNTRY             CHAR(2 BYTE),
  TL_MERCHANT_ID         VARCHAR2(15 BYTE),
  TL_PSP_ID              VARCHAR2(10 BYTE),
  TL_EXCLUSIVE           CHAR(1 BYTE),
  TL_CREATE_TIMESTAMP    DATE,
  TL_UPDATE_TIMESTAMP    DATE,
  TL_CREATE_USER         VARCHAR2(20 BYTE),
  TL_UPDATE_USER         VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX TXN_LB_STP_PK ON TXN_LB_STP
(TL_PSP_MERCHANT_ID, TL_PSP_ID, TL_MERCHANT_ID, TL_COUNTRY)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE TXN_LB_STP ADD (
  CONSTRAINT TXN_LB_STP_PK
  PRIMARY KEY
  (TL_PSP_MERCHANT_ID, TL_PSP_ID, TL_MERCHANT_ID, TL_COUNTRY)
  USING INDEX TXN_LB_STP_PK);

ALTER TABLE TXN_LB_STP ADD (
  CONSTRAINT TXN_LB_STP_FK01 
  FOREIGN KEY (TL_MERCHANT_CLIENT_ID, TL_MERCHANT_ID) 
  REFERENCES MERCH_DETAIL (CLIENT_ID,MERCHANT_ID));

