ALTER TABLE TXN_COUNTERS_LOG
 DROP PRIMARY KEY CASCADE;

DROP TABLE TXN_COUNTERS_LOG CASCADE CONSTRAINTS;

CREATE TABLE TXN_COUNTERS_LOG
(
  TCL_TXN_DATE           VARCHAR2(8 BYTE),
  TCL_TXN_CODE           VARCHAR2(3 BYTE),
  TCL_COUNTRY_ID         VARCHAR2(2 BYTE),
  TCL_CHANNEL_CODE       VARCHAR2(3 BYTE),
  TCL_SERVICE_CODE       VARCHAR2(3 BYTE),
  TCL_PAY_METHOD         VARCHAR2(4 BYTE),
  TCL_TYPE               CHAR(1 BYTE),
  TCL_CATEGORY           VARCHAR2(3 BYTE),
  TCL_PARTY_TYPE         CHAR(1 BYTE),
  TCL_PARTY_ID           VARCHAR2(15 BYTE),
  TCL_CURRENCY_ID        VARCHAR2(13 BYTE),
  TCL_COUNTER            NUMBER(14,2),
  TCL_TOTAL_COUNTER      NUMBER(14,2),
  TCL_REQ_COUNTER        NUMBER(14,2),
  TCL_TOTAL_REQ_COUNTER  NUMBER(14,2),
  TCL_CREATE_TIMESTAMP   DATE,
  TCL_CREATE_USER        VARCHAR2(20 BYTE),
  TCL_UPDATE_TIMESTAMP   DATE,
  TCL_UPDATE_USER        VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN TXN_COUNTERS_LOG.TCL_TYPE IS 'd - Daily, w - Weekly, m - Monthly, y - Yearly';

COMMENT ON COLUMN TXN_COUNTERS_LOG.TCL_PARTY_TYPE IS 'M - Merchant, P - PSP';



CREATE INDEX TXN_COUNTERS_LOG_IDX01 ON TXN_COUNTERS_LOG
(TCL_TXN_DATE, TCL_TYPE, TC_PARTY_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

CREATE INDEX TXN_COUNTERS_LOG_IDX02 ON TXN_COUNTERS_LOG
(TCL_TXN_DATE, TC_PARTY_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

CREATE UNIQUE INDEX TXN_COUNTERS_LOG_PK ON TXN_COUNTERS_LOG
(TCL_TXN_DATE, TCL_TXN_CODE, TCL_COUNTRY_ID, TCL_CHANNEL_CODE, TCL_SERVICE_CODE, TCL_TYPE,
TCL_CATEGORY, TCL_PARTY_TYPE, TCL_PARTY_ID, TCL_CURRENCY_ID, TCL_PAY_METHOD)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE TXN_COUNTERS_LOG ADD (
  CONSTRAINT TXN_COUNTERS_LOG_PK
  PRIMARY KEY
  (TCL_TXN_DATE, TCL_TXN_CODE, TCL_COUNTRY_ID, TCL_CHANNEL_CODE, TCL_SERVICE_CODE, TCL_PAY_METHOD, TCL_TYPE, TCL_CATEGORY, TCL_PARTY_TYPE, TCL_PARTY_ID, TCL_CURRENCY_ID)
  USING INDEX TXN_COUNTERS_LOG_PK
  ENABLE VALIDATE);
