ALTER TABLE PHUSER.TXN_COUNTERS
 DROP PRIMARY KEY CASCADE;

DROP TABLE PHUSER.TXN_COUNTERS CASCADE CONSTRAINTS;

CREATE TABLE PHUSER.TXN_COUNTERS
(
  TC_TXN_CODE           VARCHAR2(3 BYTE),
  TC_COUNTRY_ID         VARCHAR2(2 BYTE),
  TC_CHANNEL_CODE       VARCHAR2(3 BYTE),
  TC_SERVICE_CODE       VARCHAR2(3 BYTE),
  TC_PAY_METHOD         VARCHAR2(4 BYTE),
  TC_TYPE               CHAR(1 BYTE),
  TC_CATEGORY           VARCHAR2(3 BYTE),
  TC_PARTY_TYPE         CHAR(1 BYTE),
  TC_PARTY_ID           VARCHAR2(15 BYTE),
  TC_CURRENCY_ID        VARCHAR2(13 BYTE),
  TC_COUNTER            NUMBER(14,2),
  TC_TOTAL_COUNTER      NUMBER(14,2),
  TC_REQ_COUNTER        NUMBER(14,2),
  TC_TOTAL_REQ_COUNTER  NUMBER(14,2),
  TC_CREATE_TIMESTAMP   DATE,
  TC_CREATE_USER        VARCHAR2(20 BYTE),
  TC_UPDATE_TIMESTAMP   DATE,
  TC_UPDATE_USER        VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN PHUSER.TXN_COUNTERS.TC_TYPE IS 'D - Daily, W - Weekly, M - Monthly, Y - Yearly';

COMMENT ON COLUMN PHUSER.TXN_COUNTERS.TC_PARTY_TYPE IS 'M - Merchant, P - PSP';



CREATE INDEX PHUSER.TXN_COUNTERS_IDX01 ON PHUSER.TXN_COUNTERS
(TC_TXN_CODE, TC_COUNTRY_ID, TC_CHANNEL_CODE, TC_SERVICE_CODE, TC_TYPE, 
TC_CATEGORY, TC_PARTY_TYPE, TC_PARTY_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PHUSER.TXN_COUNTERS_PK ON PHUSER.TXN_COUNTERS
(TC_TXN_CODE, TC_COUNTRY_ID, TC_CHANNEL_CODE, TC_SERVICE_CODE, TC_PAY_METHOD, 
TC_TYPE, TC_CATEGORY, TC_PARTY_TYPE, TC_PARTY_ID, TC_CURRENCY_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PHUSER.TXN_COUNTERS ADD (
  CONSTRAINT TXN_COUNTERS_PK
  PRIMARY KEY
  (TC_TXN_CODE, TC_COUNTRY_ID, TC_CHANNEL_CODE, TC_SERVICE_CODE, TC_PAY_METHOD, TC_TYPE, TC_CATEGORY, TC_PARTY_TYPE, TC_PARTY_ID, TC_CURRENCY_ID)
  USING INDEX PHUSER.TXN_COUNTERS_PK
  ENABLE VALIDATE);

ALTER TABLE PHUSER.TXN_COUNTERS ADD (
  CONSTRAINT TXN_COUNTERS_FK01 
  FOREIGN KEY (TC_CATEGORY) 
  REFERENCES PHUSER.DEF_COUNTER_CATEGORY (DC_TYPE)
  ENABLE VALIDATE/*,
  CONSTRAINT TXN_COUNTERS_FK02 
  FOREIGN KEY (TC_TYPE) 
  REFERENCES PHUSER.DEF_COUNTER_TYPE (DC_TYPE)
  ENABLE VALIDATE*/);

