CREATE OR REPLACE FUNCTION SP_TXN_COUNTERS_UPDATE(
	in_txn_date		TXN_COUNTERS_LOG.TCL_TXN_DATE%TYPE,
	in_type			TXN_COUNTERS.TC_TYPE%TYPE
)
RETURN NUMBER
IS
BEGIN
	MERGE INTO TXN_COUNTERS
	USING (SELECT * FROM TXN_COUNTERS_LOG WHERE TCL_TXN_DATE = in_txn_date AND TCL_TYPE = 'd')
		ON (	TC_TXN_CODE = TCL_TXN_CODE
		AND	TC_COUNTRY_ID = TC_COUNTRY_ID
		AND	TC_CHANNEL_CODE = TCL_CHANNEL_CODE
		AND	TC_SERVICE_CODE = TCL_SERVICE_CODE
		AND	TC_PAY_METHOD = TCL_PAY_METHOD
		AND	TC_TYPE = in_type
		AND	TC_CATEGORY = TCL_CATEGORY
		AND	TC_PARTY_TYPE = TCL_PARTY_TYPE
		AND	TC_PARTY_ID = TCL_PARTY_ID
		AND	TC_CURRENCY_ID = TCL_CURRENCY_ID
		)
	WHEN MATCHED THEN
	UPDATE SET	TC_UPDATE_TIMESTAMP = SYSDATE,
			TC_UPDATE_USER = 'SYSTEM',
			TC_COUNTER = TC_COUNTER + TCL_COUNTER,
			TC_TOTAL_COUNTER = TC_TOTAL_COUNTER + TCL_TOTAL_COUNTER,
			TC_REQ_COUNTER  = TC_REQ_COUNTER + TCL_REQ_COUNTER,
			TC_TOTAL_REQ_COUNTER = TC_TOTAL_REQ_COUNTER + TCL_TOTAL_REQ_COUNTER
	WHEN NOT MATCHED THEN
	INSERT (
		TC_TXN_CODE,
		TC_COUNTRY_ID,
		TC_CHANNEL_CODE,
		TC_SERVICE_CODE,
		TC_PAY_METHOD,
		TC_TYPE,
		TC_CATEGORY,
		TC_PARTY_TYPE,
		TC_PARTY_ID,
		TC_CURRENCY_ID,
		TC_COUNTER,
		TC_TOTAL_COUNTER,
		TC_REQ_COUNTER,
		TC_TOTAL_REQ_COUNTER,
		TC_CREATE_USER,
		TC_CREATE_TIMESTAMP,
		TC_UPDATE_USER,
		TC_UPDATE_TIMESTAMP
	) VALUES (
		TCL_TXN_CODE,
		TCL_COUNTRY_ID,
		TCL_CHANNEL_CODE,
		TCL_SERVICE_CODE,
		TCL_PAY_METHOD,
		in_type,
		TCL_CATEGORY,
		TCL_PARTY_TYPE,
		TCL_PARTY_ID,
		TCL_CURRENCY_ID,
		TCL_COUNTER,
		TCL_TOTAL_COUNTER,
		TCL_REQ_COUNTER,
		TCL_TOTAL_REQ_COUNTER,
		'SYSTEM',
		SYSDATE,
		'SYSTEM',
		SYSDATE);

	RETURN 0;

EXCEPTION
  WHEN OTHERS THEN
  RETURN 9;
END SP_TXN_COUNTERS_UPDATE;
/

