CREATE OR REPLACE FUNCTION SP_TXN_COUNTERS_RESET(
	in_txn_date		TXN_COUNTERS_LOG.TCL_TXN_DATE%TYPE,
	in_type			TXN_COUNTERS.TC_TYPE%TYPE
)
RETURN NUMBER
IS
	iCnt	INTEGER := 0;
BEGIN
	SELECT	COUNT(*)
	INTO	iCnt
	FROM	TXN_COUNTERS
	WHERE	TC_TYPE = in_type;

	UPDATE	TXN_COUNTERS
	SET	TC_TYPE = lower(in_type)
	WHERE	TC_TYPE = in_type;


	MERGE INTO TXN_COUNTERS_LOG
	USING (SELECT * FROM TXN_COUNTERS WHERE TC_TYPE = lower(in_type))
		ON (	TCL_TXN_DATE = in_txn_date
		AND	TCL_TXN_CODE = TC_TXN_CODE
		AND	TCL_COUNTRY_ID = TC_COUNTRY_ID
		AND	TCL_CHANNEL_CODE = TC_CHANNEL_CODE
		AND	TCL_SERVICE_CODE = TC_SERVICE_CODE
		AND	TCL_PAY_METHOD = TC_PAY_METHOD
		AND	TCL_TYPE = lower(in_type)
		AND	TCL_CATEGORY = TC_CATEGORY
		AND	TCL_PARTY_TYPE = TC_PARTY_TYPE
		AND	TCL_PARTY_ID = TC_PARTY_ID
		AND	TCL_CURRENCY_ID = TC_CURRENCY_ID
		)
	WHEN MATCHED THEN
	UPDATE SET	TCL_UPDATE_TIMESTAMP = SYSDATE,
			TCL_UPDATE_USER = 'SYSTEM',
			TCL_COUNTER = TCL_COUNTER + TC_COUNTER,
			TCL_TOTAL_COUNTER = TCL_TOTAL_COUNTER + TC_TOTAL_COUNTER,
			TCL_REQ_COUNTER  = TCL_REQ_COUNTER + TC_REQ_COUNTER,
			TCL_TOTAL_REQ_COUNTER = TCL_TOTAL_REQ_COUNTER + TC_TOTAL_REQ_COUNTER
	WHEN NOT MATCHED THEN
	INSERT (
		TCL_TXN_DATE,
		TCL_TXN_CODE,
		TCL_COUNTRY_ID,
		TCL_CHANNEL_CODE,
		TCL_SERVICE_CODE,
		TCL_PAY_METHOD,
		TCL_TYPE,
		TCL_CATEGORY,
		TCL_PARTY_TYPE,
		TCL_PARTY_ID,
	        TCL_CURRENCY_ID,
		TCL_COUNTER,
		TCL_TOTAL_COUNTER,
		TCL_REQ_COUNTER,
		TCL_TOTAL_REQ_COUNTER,
		TCL_CREATE_USER,
		TCL_CREATE_TIMESTAMP,
		TCL_UPDATE_USER,
		TCL_UPDATE_TIMESTAMP
	) VALUES (
		in_txn_date,
                TC_TXN_CODE,
                TC_COUNTRY_ID,
                TC_CHANNEL_CODE,
                TC_SERVICE_CODE,
                TC_PAY_METHOD,
                lower(in_type),
                TC_CATEGORY,
                TC_PARTY_TYPE,
                TC_PARTY_ID,
                TC_CURRENCY_ID,
                TC_COUNTER,
                TC_TOTAL_COUNTER,
                TC_REQ_COUNTER,
                TC_TOTAL_REQ_COUNTER,
		'SYSTEM',
		SYSDATE,
		'SYSTEM',
		SYSDATE);

	IF SQL%ROWCOUNT <> iCnt THEN
		RETURN 1;
	END IF;

	DELETE FROM TXN_COUNTERS
	WHERE	TC_TYPE = lower(in_type);

	RETURN 0;

EXCEPTION
  WHEN OTHERS THEN
  RETURN 9;
END SP_TXN_COUNTERS_RESET;
/

