ALTER TABLE TXN_FIELD_CHECK
 DROP PRIMARY KEY CASCADE;

DROP TABLE TXN_FIELD_CHECK CASCADE CONSTRAINTS;

CREATE TABLE TXN_FIELD_CHECK
(
  TFC_TXN_CODE          VARCHAR2(3 BYTE),
  TFC_CHANNEL_CODE      VARCHAR2(10 BYTE),
  TFC_FIELD_TAG		VARCHAR2(25 BYTE),
  TFC_MANDATORY         INTEGER DEFAULT 0,
  TFC_ONLY_DIGIT	INTEGER DEFAULT 0,
  TFC_MIN_LEN		INTEGER DEFAULT 0,
  TFC_MAX_LEN		INTEGER DEFAULT 0,
  TFC_REF_DEF_TABLE	VARCHAR2(50 BYTE),
  TFC_REF_DEF_FIELD	VARCHAR2(50 BYTE),
  TFC_CREATE_TIMESTAMP  DATE DEFAULT sysdate,
  TFC_CREATE_USER       VARCHAR2(20 BYTE),
  TFC_UPDATE_TIMESTAMP  DATE DEFAULT sysdate,
  TFC_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX TXN_FIELD_CHECK_PK ON TXN_FIELD_CHECK
(TFC_TXN_CODE, TFC_CHANNEL_CODE, TFC_FIELD_TAG)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE TXN_FIELD_CHECK ADD (
  CONSTRAINT TXN_FIELD_CHECK_PK
  PRIMARY KEY
  (TFC_TXN_CODE, TFC_CHANNEL_CODE, TFC_FIELD_TAG)
  USING INDEX TXN_FIELD_CHECK_PK
  ENABLE VALIDATE);

