ALTER TABLE DEF_VIEW_TXNCODE_MAP
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_VIEW_TXNCODE_MAP CASCADE CONSTRAINTS;

CREATE TABLE DEF_VIEW_TXNCODE_MAP
(
  VTM_VIEW_TYPE         VARCHAR2(30 BYTE)       NOT NULL,
  VTM_TXN_CODE          VARCHAR2(3 BYTE)        NOT NULL,
  VTM_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  VTM_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  VTM_CREATE_USER       VARCHAR2(20 BYTE),
  VTM_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEF_VIEW_TXNCODE_MAP_PK ON DEF_VIEW_TXNCODE_MAP
(VTM_VIEW_TYPE, VTM_TXN_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_VIEW_TXNCODE_MAP ADD (
  CONSTRAINT DEF_VIEW_TXNCODE_MAP_PK
  PRIMARY KEY
  (VTM_VIEW_TYPE, VTM_TXN_CODE)
  USING INDEX DEF_VIEW_TXNCODE_MAP_PK
  ENABLE VALIDATE);

