ALTER TABLE MOBILE_BANK_URL
 DROP PRIMARY KEY CASCADE;

DROP TABLE MOBILE_BANK_URL CASCADE CONSTRAINTS;

CREATE TABLE MOBILE_BANK_URL
(
	MU_INT_BANK_CODE	VARCHAR2(10)	NOT NULL,
	MU_BANK_URL		VARCHAR2(100)	NOT NULL,
	MU_URL_METHOD		VARCHAR2(10)	NOT NULL,
	MU_CREATE_TIMESTAMP	DATE,
	MU_CREATE_USER		VARCHAR2(20 BYTE),
	MU_UPDATE_TIMESTAMP	DATE,
	MU_UPDATE_USER		VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX MOBILE_BANK_URL_PK ON MOBILE_BANK_URL
(MU_INT_BANK_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE MOBILE_BANK_URL ADD (
  CONSTRAINT MOBILE_BANK_URL_PK
  PRIMARY KEY
  (MU_INT_BANK_CODE)
  USING INDEX MOBILE_BANK_URL_PK);

ALTER TABLE MOBILE_BANK_URL ADD (
  CONSTRAINT MOBILE_BANK_URL_FK01
  FOREIGN KEY (MU_INT_BANK_CODE)
  REFERENCES DEF_BANK (DB_INT_BANK_CODE));

