ALTER TABLE RULE_AUTO_SETTLEMENT
 DROP PRIMARY KEY CASCADE;

DROP TABLE RULE_AUTO_SETTLEMENT CASCADE CONSTRAINTS;

CREATE TABLE RULE_AUTO_SETTLEMENT
(
  RS_ID                INTEGER,
  RS_TYPE              CHAR(1 BYTE),
  RS_VALUE             VARCHAR2(20 BYTE),
  RS_MIN_AMOUNT        NUMBER(14,2),
  RS_DESC              VARCHAR2(50 BYTE),
  RS_DISABLED          INTEGER                  DEFAULT 0,
  RS_CREATE_TIMESTAMP  DATE,
  RS_CREATE_USER       VARCHAR2(20 BYTE),
  RS_UPDATE_TIMESTAMP  DATE,
  RS_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX RULE_AUTO_SETTLEMENT_PK ON RULE_AUTO_SETTLEMENT
(RS_ID, RS_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE RULE_AUTO_SETTLEMENT ADD (
  CONSTRAINT RULE_AUTO_SETTLEMENT_PK
  PRIMARY KEY
  (RS_ID, RS_TYPE)
  USING INDEX RULE_AUTO_SETTLEMENT_PK);

ALTER TABLE RULE_AUTO_SETTLEMENT ADD (
  CONSTRAINT RULE_AUTO_SETTLEMENT_FK01 
  FOREIGN KEY (RS_TYPE) 
  REFERENCES DEF_AUTO_SETTLEMENT_TYPE (DA_TYPE));

