OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/EmailFunctTemplate
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBEmailFunctTemplate.so
SOOBJS =  EmailFunctTemplate.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
