OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnWebOnUsCID
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnWebOnUsCID.so
SOOBJS = TxnWebOnUsCID.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
