OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/RuleTxnBankCharge
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBRuleTxnBankCharge.so
SOOBJS =  RuleTxnBankCharge.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
