ALTER TABLE MOB_SEGMENT_CTL_HISTORY
 DROP PRIMARY KEY CASCADE;

DROP TABLE MOB_SEGMENT_CTL_HISTORY CASCADE CONSTRAINTS;

CREATE TABLE MOB_SEGMENT_CTL_HISTORY
(
  MSH_GROUP             VARCHAR2(10 BYTE),
  MSH_ENABLE_NEW_CUST	INTEGER,
  MSH_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  MSH_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
