ALTER TABLE PSP_TXN_CHECK
 DROP PRIMARY KEY CASCADE;

DROP TABLE PSP_TXN_CHECK CASCADE CONSTRAINTS;

CREATE TABLE PSP_TXN_CHECK
(
  PC_PARTY_TYPE            CHAR(1 BYTE),
  PC_PARTY_ID                VARCHAR2(10 BYTE),
  PC_CUTOFF_CHECKING_TIME  DATE                 NOT NULL,
  PC_CHECK_COUNT           INTEGER              NOT NULL,
  PC_MIN_SUCCESS_COUNT     INTEGER              DEFAULT 0,
  PC_DISABLED              INTEGER              DEFAULT 0,
  PC_LAST_CHECKING_TIME    DATE,
  PC_START_BUFFER_PERIOD   INTEGER              DEFAULT 0,
  PC_MIN_TOTAL             INTEGER              DEFAULT 0,
  PC_CREATE_USER           VARCHAR2(20 BYTE),
  PC_UPDATE_USER           VARCHAR2(20 BYTE),
  PC_CREATE_TIMESTAMP      DATE                 DEFAULT sysdate,
  PC_UPDATE_TIMESTAMP      DATE                 DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX PSP_TXN_CHECK_IDX01 ON PSP_TXN_CHECK
(PC_PARTY_ID, PC_DISABLED)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX PSP_TXN_CHECK_IDX02 ON PSP_TXN_CHECK
(PC_CUTOFF_CHECKING_TIME)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PSP_TXN_CHECK_PK ON PSP_TXN_CHECK
(PC_PARTY_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PSP_TXN_CHECK ADD (
  CONSTRAINT PSP_TXN_CHECK_PK
  PRIMARY KEY
  (PC_PARTY_ID)
  USING INDEX PSP_TXN_CHECK_PK
  ENABLE VALIDATE);

