OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLDepositRequest
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLDepositRequest.so
SOOBJS =  OLDepositRequest.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
