ALTER TABLE MGT_SYSTEM_PARAMETER
 DROP PRIMARY KEY CASCADE;

DROP TABLE MGT_SYSTEM_PARAMETER CASCADE CONSTRAINTS;

CREATE TABLE MGT_SYSTEM_PARAMETER
(
  MSP_CODE              VARCHAR2(50 BYTE)       NOT NULL,
  MSP_DESC              VARCHAR2(240 BYTE)      NOT NULL,
  MSP_VAL               VARCHAR2(50 BYTE)       NOT NULL,
  MSP_CREATE_USER       VARCHAR2(20 BYTE),
  MSP_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  MSP_UPDATE_USER       VARCHAR2(20 BYTE),
  MSP_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MGT_SYSTEM_PARAMETER_PK ON MGT_SYSTEM_PARAMETER
(MSP_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MGT_SYSTEM_PARAMETER ADD (
  CONSTRAINT MGT_SYSTEM_PARAMETER_PK
  PRIMARY KEY
  (MSP_CODE)
  USING INDEX MGT_SYSTEM_PARAMETER_PK
  ENABLE VALIDATE);

