ALTER TABLE OL_TXN_REMARKS
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_TXN_REMARKS CASCADE CONSTRAINTS;

CREATE TABLE OL_TXN_REMARKS
(
  OTR_TXN_ID            VARCHAR2(16 BYTE),
  OTR_TXN_CODE          VARCHAR2(3 BYTE),
  OTR_STATUS            CHAR(1 BYTE),
  OTR_AR_IND            CHAR(1 BYTE),
  OTR_SUB_STATUS        CHAR(3 BYTE),
  OTR_EXEC_SEQ          INTEGER,
  OTR_REMARK            VARCHAR2(255 BYTE),
  OTR_CREATE_USER       VARCHAR2(20 BYTE),
  OTR_CREATE_TIMESTAMP  DATE,
  OTR_UPDATE_USER       VARCHAR2(20 BYTE),
  OTR_UPDATE_TIMESTAMP  DATE
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_TXN_REMARKS_PK ON OL_TXN_REMARKS
(OTR_TXN_ID, OTR_TXN_CODE, OTR_STATUS, OTR_AR_IND, OTR_SUB_STATUS, OTR_EXEC_SEQ)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_TXN_REMARKS ADD (
  CONSTRAINT OL_TXN_REMARKS_PK
  PRIMARY KEY
  (OTR_TXN_ID, OTR_TXN_CODE, OTR_STATUS, OTR_AR_IND, OTR_SUB_STATUS, OTR_EXEC_SEQ)
  USING INDEX OL_TXN_REMARKS_PK
  ENABLE VALIDATE);

