ALTER TABLE OL_CHANNEL_KEYS
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_CHANNEL_KEYS CASCADE CONSTRAINTS;

CREATE TABLE OL_CHANNEL_KEYS
(
  OCK_CHANNEL           CHAR(3 BYTE),
  OCK_ENCRYPT_TYPE      VARCHAR2(2 BYTE),
  OCK_KEY_VALUE         VARCHAR2(128 BYTE),
  OCK_VERSION           VARCHAR2(5 BYTE),
  OCK_EFFECT_DATE       DATE,
  OCK_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  OCK_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  OCK_CREATE_USER       VARCHAR2(20 BYTE),
  OCK_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX OL_CHANNEL_KEYS_PK ON OL_CHANNEL_KEYS
(OCK_CHANNEL, OCK_ENCRYPT_TYPE, OCK_VERSION, OCK_EFFECT_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE OL_CHANNEL_KEYS ADD (
  CONSTRAINT OL_CHANNEL_KEYS_PK
  PRIMARY KEY
  (OCK_CHANNEL, OCK_ENCRYPT_TYPE, OCK_VERSION, OCK_EFFECT_DATE)
  USING INDEX OL_CHANNEL_KEYS_PK
  ENABLE VALIDATE);

ALTER TABLE OL_CHANNEL_KEYS ADD (
  CONSTRAINT OL_CHANNEL_KEYS_FK01 
  FOREIGN KEY (OCK_CHANNEL) 
  REFERENCES DEF_CHANNEL (DC_CODE)
  ENABLE VALIDATE,
  CONSTRAINT OL_CHANNEL_KEYS_FK02 
  FOREIGN KEY (OCK_ENCRYPT_TYPE) 
  REFERENCES OL_DEF_ENCRYPT_TYPE (ET_TYPE)
  ENABLE VALIDATE);


