OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmsDefTxnSubStatusMap
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmsDefTxnSubStatusMap.so
SOOBJS =  MmsDefTxnSubStatusMap.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
