ALTER TABLE RULE_PAYOUT_EXCLUDE
 DROP PRIMARY KEY CASCADE;

DROP TABLE RULE_PAYOUT_EXCLUDE CASCADE CONSTRAINTS;

CREATE TABLE RULE_PAYOUT_EXCLUDE
(
  RE_PSP_CLIENT_ID VARCHAR2(10 BYTE),
  RE_BANK_NAME     VARCHAR2(50 BYTE),
  RE_DISABLED	   INTEGER			DEFAULT 0,
  RE_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  RE_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  RE_CREATE_USER       VARCHAR2(20 BYTE),
  RE_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX RULE_PAYOUT_EXCLUDE_IDX01 ON RULE_PAYOUT_EXCLUDE
(RE_PSP_CLIENT_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

CREATE UNIQUE INDEX RULE_PAYOUT_EXCLUDE_PK ON RULE_PAYOUT_EXCLUDE
(RE_PSP_CLIENT_ID, RE_BANK_NAME)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE RULE_PAYOUT_EXCLUDE ADD (
  CONSTRAINT RULE_PAYOUT_EXCLUDE_PK
  PRIMARY KEY
  (RE_PSP_CLIENT_ID, RE_BANK_NAME)
  USING INDEX RULE_PAYOUT_EXCLUDE_PK);

ALTER TABLE RULE_PAYOUT_EXCLUDE ADD (
  CONSTRAINT RULE_PAYOUT_EXCLUDE_FK01
  FOREIGN KEY (RE_PSP_CLIENT_ID)
  REFERENCES PSP_MASTER (PM_CLIENT_ID)
  ENABLE VALIDATE
  );

