ALTER TABLE TXN_SUPPORTED
 DROP PRIMARY KEY CASCADE;

DROP TABLE TXN_SUPPORTED CASCADE CONSTRAINTS;

CREATE TABLE TXN_SUPPORTED
(
  TS_TXN_CODE          VARCHAR2(3 BYTE),
  TS_CHANNEL_CODE      VARCHAR2(10 BYTE),
  TS_SUPPORT           INTEGER,
  TS_CREATE_TIMESTAMP  DATE,
  TS_CREATE_USER       VARCHAR2(20 BYTE),
  TS_UPDATE_TIMESTAMP  DATE,
  TS_UPDATE_USER       VARCHAR2(20 BYTE),
  TS_DO_LOGGING        INTEGER                  DEFAULT NULL,
  TS_TO_MMS_HOST       INTEGER                  DEFAULT NULL,
  TS_INIT_TXN          INTEGER                  DEFAULT NULL
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN TXN_SUPPORTED.TS_DO_LOGGING IS '''1'' - Yes, ''0'' - No, ''2'' - Update only';



CREATE UNIQUE INDEX TXN_SUPPORTED_PK ON TXN_SUPPORTED
(TS_TXN_CODE, TS_CHANNEL_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE TXN_SUPPORTED ADD (
  CONSTRAINT TXN_SUPPORTED_PK
  PRIMARY KEY
  (TS_TXN_CODE, TS_CHANNEL_CODE)
  USING INDEX TXN_SUPPORTED_PK
  ENABLE VALIDATE);

