ALTER TABLE MMS_ADJUSTMENT_TYPE_ENTITY
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_ADJUSTMENT_TYPE_ENTITY CASCADE CONSTRAINTS;

CREATE TABLE MMS_ADJUSTMENT_TYPE_ENTITY
(
  MAE_CODE              CHAR(3 BYTE),
  MAE_ENTITY_TYPE       CHAR(3 BYTE),
  MAE_DISABLED          INTEGER                 DEFAULT 0,
  MAE_CREATE_TIMESTAMP  DATE,
  MAE_CREATE_USER       VARCHAR2(20 BYTE),
  MAE_UPDATE_TIMESTAMP  DATE,
  MAE_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MMS_ADJUSTMENT_TYPE_ENTITY_PK ON MMS_ADJUSTMENT_TYPE_ENTITY
(MAE_CODE, MAE_ENTITY_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_ADJUSTMENT_TYPE_ENTITY ADD (
  CONSTRAINT MMS_ADJUSTMENT_TYPE_ENTITY_PK
  PRIMARY KEY
  (MAE_CODE, MAE_ENTITY_TYPE)
  USING INDEX MMS_ADJUSTMENT_TYPE_ENTITY_PK
  ENABLE VALIDATE);

ALTER TABLE MMS_ADJUSTMENT_TYPE_ENTITY ADD (
  CONSTRAINT MMS_ADJUST_TYPE_ENTITY_FK01
  FOREIGN KEY (MAE_CODE)
  REFERENCES MMS_TXN_CODE (MTC_CODE)
  ENABLE VALIDATE,
  CONSTRAINT MMS_ADJUST_TYPE_ENTITY_FK02
  FOREIGN KEY (MAE_ENTITY_TYPE) 
  REFERENCES MMS_ENTITY_TYPE (MET_TYPE_CODE)
  ENABLE VALIDATE);

