OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/TxnRemarks
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBTxnRemarks.so
SOOBJS =  TxnRemarks.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
