ALTER TABLE MMS_RULE_PROCESSING_COST
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_RULE_PROCESSING_COST CASCADE CONSTRAINTS;

CREATE TABLE MMS_RULE_PROCESSING_COST
(
  MPC_LEVEL             CHAR(1 BYTE),
  MPC_SRC_PARTY_TYPE    CHAR(3 BYTE),
  MPC_SRC_PARTY_ID      VARCHAR2(20 BYTE),
  MPC_SRC_CCY_ID        VARCHAR2(3 BYTE),
  MPC_DST_PARTY_TYPE    CHAR(3 BYTE),
  MPC_DST_PARTY_ID      VARCHAR2(20 BYTE),
  MPC_DST_CCY_ID        VARCHAR2(3 BYTE),
  MPC_TXN_CODE_GROUP    VARCHAR2(6 BYTE),
  MPC_EFFECT_DATETIME   DATE,
  MPC_CHARGE_PERIOD     CHAR(1 BYTE),
  MPC_SRC_COST_ID       INTEGER,
  MPC_DST_COST_ID       INTEGER,
  MPC_DISABLED          INTEGER,
  MPC_CREATE_TIMESTAMP  DATE,
  MPC_CREATE_USER       VARCHAR2(20 BYTE),
  MPC_UPDATE_TIMESTAMP  DATE,
  MPC_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MMS_RULE_PROCESSING_COST_PK ON MMS_RULE_PROCESSING_COST
(MPC_LEVEL, MPC_SRC_PARTY_TYPE, MPC_SRC_PARTY_ID, MPC_SRC_CCY_ID, MPC_DST_PARTY_TYPE, 
MPC_DST_PARTY_ID, MPC_DST_CCY_ID, MPC_TXN_CODE_GROUP, MPC_EFFECT_DATETIME)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_RULE_PROCESSING_COST ADD (
  CONSTRAINT MMS_RULE_PROCESSING_COST_PK
  PRIMARY KEY
  (MPC_LEVEL, MPC_SRC_PARTY_TYPE, MPC_SRC_PARTY_ID, MPC_SRC_CCY_ID, MPC_DST_PARTY_TYPE, MPC_DST_PARTY_ID, MPC_DST_CCY_ID, MPC_TXN_CODE_GROUP, MPC_EFFECT_DATETIME)
  USING INDEX MMS_RULE_PROCESSING_COST_PK
  ENABLE VALIDATE);

ALTER TABLE MMS_RULE_PROCESSING_COST ADD (
  CONSTRAINT MMS_RULE_PROCESSING_COST_FK01 
  FOREIGN KEY (MPC_LEVEL) 
  REFERENCES MMS_DEF_ENTITY_LEVEL (MEL_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT MMS_RULE_PROCESSING_COST_FK02 
  FOREIGN KEY (MPC_TXN_CODE_GROUP) 
  REFERENCES MMS_TXN_CODE_GROUP (MCG_GROUP)
  ENABLE VALIDATE,
  CONSTRAINT MMS_RULE_PROCESSING_COST_FK03 
  FOREIGN KEY (MPC_CHARGE_PERIOD) 
  REFERENCES MMS_DEF_CHARGE_PERIOD (MCP_TYPE)
  ENABLE VALIDATE);

