ALTER TABLE SERVICE_PSP_URL
 DROP PRIMARY KEY CASCADE;

DROP TABLE SERVICE_PSP_URL CASCADE CONSTRAINTS;

CREATE TABLE SERVICE_PSP_URL
(
  PU_SERVICE_CODE      CHAR(3 BYTE),
  PU_PSP_ID            VARCHAR2(10 BYTE),
  PU_URL               VARCHAR2(50 BYTE),
  PU_EFFECT_DATE       DATE                     DEFAULT sysdate,
  PU_DISABLED          INTEGER                  DEFAULT 0,
  PU_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  PU_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  PU_CREATE_USER       VARCHAR2(20 BYTE),
  PU_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX SERVICE_PSP_URL_PK ON SERVICE_PSP_URL
(PU_SERVICE_CODE, PU_PSP_ID, PU_EFFECT_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE SERVICE_PSP_URL ADD (
  CONSTRAINT SERVICE_PSP_URL_PK
  PRIMARY KEY
  (PU_SERVICE_CODE, PU_PSP_ID, PU_EFFECT_DATE)
  USING INDEX SERVICE_PSP_URL_PK
  ENABLE VALIDATE);

ALTER TABLE SERVICE_PSP_URL ADD (
  CONSTRAINT SERVICE_PSP_URL_FK01 
  FOREIGN KEY (PU_SERVICE_CODE) 
  REFERENCES DEF_SERVICE_CODE (SC_CODE)
  ENABLE VALIDATE);

