ALTER TABLE OL_STMT_TXN_RELATION
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_STMT_TXN_RELATION CASCADE CONSTRAINTS;

CREATE TABLE OL_STMT_TXN_RELATION
(
  OSTP_STMT_TXN_ID       VARCHAR2(16 BYTE),
  OSTP_TXN_ID            VARCHAR2(16 BYTE),
  OSTP_RELATION_TIMESTAMP TIMESTAMP(6),
  OSTP_CREATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  OSTP_UPDATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  OSTP_CREATE_USER       VARCHAR2(20 BYTE),
  OSTP_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX OL_STMT_TXN_RELATION_IDX01 ON OL_STMT_TXN_RELATION
(OSTP_STMT_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX OL_STMT_TXN_RELATION_PK ON OL_STMT_TXN_RELATION
(OSTP_TXN_ID, OSTP_STMT_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_STMT_TXN_RELATION ADD (
  CONSTRAINT OL_STMT_TXN_RELATION_PK
  PRIMARY KEY
  (OSTP_TXN_ID, OSTP_STMT_TXN_ID)
  USING INDEX OL_STMT_TXN_RELATION_PK
  ENABLE VALIDATE);

