ALTER TABLE MMS_TXN_HEADER
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_TXN_HEADER CASCADE CONSTRAINTS;

CREATE TABLE MMS_TXN_HEADER
(
  MTH_TXN_ID                 VARCHAR2(16 BYTE),
  MTH_ORG_TXN_ID             VARCHAR2(16 BYTE),
  MTH_ACTION_TXN_ID  	     VARCHAR2(16 BYTE),
  MTH_INPUT_CHANNEL          VARCHAR2(3 BYTE),
  MTH_STATUS                 CHAR(1 BYTE),
  MTH_AR_IND                 CHAR(1 BYTE),
  MTH_SUB_STATUS             CHAR(3 BYTE),
  MTH_TXN_CODE               VARCHAR2(3 BYTE),
  MTH_PROCESS_TYPE           VARCHAR2(4 BYTE),
  MTH_PROCESS_CODE           VARCHAR2(6 BYTE),
  MTH_NODE_ID                VARCHAR2(5 BYTE),
  MTH_NODE_REF               VARCHAR2(16 BYTE),
  MTH_HOST_POSTING_DATE      VARCHAR2(8 BYTE),
  MTH_TRANSMISSION_DATETIME  VARCHAR2(14 BYTE),
  MTH_INTERNAL_CODE          NUMBER(8),
  MTH_RESPONSE_CODE          VARCHAR2(10 BYTE),
  MTH_TRANSACTION_AMOUNT     NUMBER(12,2),
  MTH_REMAINING_AMOUNT       NUMBER(12,2) DEFAULT 0,
  MTH_NET_AMOUNT             NUMBER(12,2),
  MTH_TXN_COUNTRY            CHAR(2 BYTE),
  MTH_TXN_CCY                CHAR(3 BYTE),
  MTH_NET_CCY                CHAR(3 BYTE),
  MTH_TM_DATE                VARCHAR2(8 BYTE),
  MTH_TM_TIME                VARCHAR2(6 BYTE),
  MTH_LOCAL_TM_DATE          VARCHAR2(8 BYTE),
  MTH_LOCAL_TM_TIME          VARCHAR2(6 BYTE),
  MTH_CLIENT_IP              VARCHAR2(25 BYTE),
  MTH_APPLY_COST             INTEGER,
  MTH_APPLY_FEE              INTEGER,
  MTH_RELATED_TXN_ID         VARCHAR2(16 BYTE),
  MTH_ACTION		     CHAR(1 BYTE),
  MTH_APPROVAL_DATE          VARCHAR2(8 BYTE),
  MTH_APPROVAL_TIMESTAMP     TIMESTAMP(6),
  MTH_RPT_APPROVAL_DATE      VARCHAR2(8 BYTE)   DEFAULT '00000000',
  MTH_RPT_APPROVAL_TIME      VARCHAR2(16 BYTE)  DEFAULT '0000000000000000',
  MTH_CREATE_USER            VARCHAR2(20 BYTE),
  MTH_CREATE_TIMESTAMP       DATE,
  MTH_UPDATE_USER            VARCHAR2(20 BYTE),
  MTH_UPDATE_TIMESTAMP       DATE
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN MMS_TXN_HEADER.MTH_RELATED_TXN_ID IS 'Mark on the source';



CREATE INDEX MMS_TXN_HEADER_IDX01 ON MMS_TXN_HEADER
(MTH_RPT_APPROVAL_DATE, MTH_RPT_APPROVAL_TIME)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX MMS_TXN_HEADER_IDX02 ON MMS_TXN_HEADER
(MTH_STATUS, MTH_AR_IND)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX MMS_TXN_HEADER_IDX03 ON MMS_TXN_HEADER
(MTH_STATUS, MTH_AR_IND, MTH_SUB_STATUS)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX MMS_TXN_HEADER_IDX04 ON MMS_TXN_HEADER
(MTH_CREATE_TIMESTAMP)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX MMS_TXN_HEADER_IDX05 ON MMS_TXN_HEADER
(MTH_NODE_ID, MTH_NODE_REF)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX MMS_TXN_HEADER_PK ON MMS_TXN_HEADER
(MTH_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_TXN_HEADER ADD (
  CONSTRAINT MMS_TXN_HEADER_PK
  PRIMARY KEY
  (MTH_TXN_ID)
  USING INDEX MMS_TXN_HEADER_PK
  ENABLE VALIDATE);


CREATE MMS_TXN_HEADER_IDX06 ON MMS_TXN_HEADER
(MTH_ACTION_TXN_ID)
LOGGING
TABLESPACE USER_IDX
STORAGE    (
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;
