ALTER TABLE MMS_TXN_DETAIL
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_TXN_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE MMS_TXN_DETAIL
(
  MTD_TXN_ID                 VARCHAR2(16 BYTE),
  MTD_ENTITY_ID              VARCHAR2(20 BYTE),
  MTD_RELATED_ENTITY_ID      VARCHAR2(20 BYTE),
  MTD_OPEN_ACCT_BAL          NUMBER(14,2),
  MTD_OPEN_INTRANSIT         NUMBER(14,2),
  MTD_OPEN_LIEN              NUMBER(14,2),
  MTD_OPEN_PREPAID           NUMBER(14,2),
  MTD_CURR_ACCT_BAL          NUMBER(14,2),
  MTD_CURR_INTRANSIT         NUMBER(14,2),
  MTD_CURR_LIEN              NUMBER(14,2),
  MTD_CURR_PREPAID           NUMBER(14,2),
  MTD_PROVIDED_FX_RATE       NUMBER(12,5),
  MTD_FX_RATE                NUMBER(12,5),
  MTD_PROVIDED_COST_RATE     NUMBER(12,5),
  MTD_PROVIDED_FIXED_AMOUNT  NUMBER(12,2),
  MTD_PROVIDED_COST          NUMBER(12,2),
  MTD_COST_RATE              NUMBER(12,5),
  MTD_FIXED_AMOUNT           NUMBER(12,2),
  MTD_COST                   NUMBER(12,2),
  MTD_ALLOW_PREPAID          CHAR(1 BYTE)       DEFAULT 'N',
  MTD_NEXT_ACTION_CCY        CHAR(3 BYTE),
  MTD_FX_TXN	             CHAR(1 BYTE)       DEFAULT 'N',
  MTD_REMARK                 VARCHAR2(255 BYTE),
  MTD_CREATE_TIMESTAMP       DATE,
  MTD_CREATE_USER            VARCHAR2(20 BYTE),
  MTD_UPDATE_TIMESTAMP       DATE,
  MTD_UPDATE_USER            VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MMS_TXN_DETAIL_PK ON MMS_TXN_DETAIL
(MTD_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_TXN_DETAIL ADD (
  CONSTRAINT MMS_TXN_DETAIL_PK
  PRIMARY KEY
  (MTD_TXN_ID)
  USING INDEX MMS_TXN_DETAIL_PK
  ENABLE VALIDATE);

ALTER TABLE PHUSER.MMS_TXN_DETAIL
 ADD CONSTRAINT MMS_TXN_DETAIL_FK01 
  FOREIGN KEY (MTD_TXN_ID) 
  REFERENCES PHUSER.MMS_TXN_HEADER (MTH_TXN_ID)
  ENABLE VALIDATE;
