ALTER TABLE MMS_TXN_NATURE_DETAIL
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_TXN_NATURE_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE MMS_TXN_NATURE_DETAIL
(
  MTN_TXN_ID            VARCHAR2(16 BYTE),
  MTN_ENTITY_ID         VARCHAR2(20 BYTE),
  MTN_NATURE_ID         VARCHAR2(20 BYTE),
  MTN_TXN_AMOUNT        NUMBER(12,2),
  MTN_TXN_CCY           CHAR(3 BYTE),
  MTN_NET_AMOUNT        NUMBER(12,2),
  MTN_NET_CCY           CHAR(3 BYTE),
  MTN_CREATE_TIMESTAMP  DATE,
  MTN_CREATE_USER       VARCHAR2(20 BYTE),
  MTN_UPDATE_TIMESTAMP  DATE,
  MTN_UPDATE_USER       VARCHAR2(17 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX MMS_TXN_NATURE_DETAIL_IDX01 ON MMS_TXN_NATURE_DETAIL
(MTN_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX MMS_TXN_NATURE_DETAIL_PK ON MMS_TXN_NATURE_DETAIL
(MTN_TXN_ID, MTN_ENTITY_ID, MTN_NATURE_ID)
LOGGING
TABLESPACE USER_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_TXN_NATURE_DETAIL ADD (
  CONSTRAINT MMS_TXN_NATURE_DETAIL_PK
  PRIMARY KEY
  (MTN_TXN_ID, MTN_ENTITY_ID, MTN_NATURE_ID)
  USING INDEX MMS_TXN_NATURE_DETAIL_PK
  ENABLE VALIDATE);

ALTER TABLE MMS_TXN_NATURE_DETAIL ADD (
  CONSTRAINT MMS_TXN_NATURE_DETAIL_FK01 
  FOREIGN KEY (MTN_TXN_ID) 
  REFERENCES MMS_TXN_DETAIL (MTD_TXN_ID)
  ENABLE VALIDATE);

