create or replace function sp_mms_txn_header_insert(
       in_txn_id                                mms_txn_header.mth_txn_id%type,
       in_org_txn_id                          	mms_txn_header.mth_org_txn_id%type,
       in_action_txn_id                       	mms_txn_header.mth_action_txn_id%type,
       in_input_channel                      	mms_txn_header.mth_input_channel%type,
       in_status                                mms_txn_header.mth_status%type,
       in_ar_ind                                mms_txn_header.mth_ar_ind%type,
       in_sub_status                            mms_txn_header.mth_sub_status%type,
       in_txn_code                             	mms_txn_header.mth_txn_code%type,
       in_process_type                         	mms_txn_header.mth_process_type%type,
       in_process_code                         	mms_txn_header.mth_process_code%type,
       in_node_id                         	mms_txn_header.mth_node_id%type,
       in_node_ref                         	mms_txn_header.mth_node_ref%type,
       in_host_posting_date                     mms_txn_header.mth_host_posting_date%type,
       in_transmission_datetime                 mms_txn_header.mth_transmission_datetime%type,
       in_internal_code                         mms_txn_header.mth_internal_code%type,
       in_response_code                         mms_txn_header.mth_response_code%type,
       in_transaction_amt                       mms_txn_header.mth_transaction_amount%type,
       in_txn_ccy                               mms_txn_header.mth_txn_ccy%type,
       in_remaining_amt                         mms_txn_header.mth_remaining_amount%type,
       in_net_amt                               mms_txn_header.mth_net_amount%type,
       in_net_ccy			        mms_txn_header.mth_net_ccy%type,
       in_client_ip				mms_txn_header.mth_client_ip%type,
       in_apply_cost				mms_txn_header.mth_apply_cost%type,
       in_action				mms_txn_header.mth_action%type,
       in_related_txn_id			mms_txn_header.mth_related_txn_id%type,
       in_local_tm_date                         mms_txn_header.mth_local_tm_date%type,
       in_local_tm_time                         mms_txn_header.mth_local_tm_time%type,
       in_tm_date                         	mms_txn_header.mth_tm_date%type,
       in_tm_time                         	mms_txn_header.mth_tm_time%type,
       in_create_user                           mms_txn_header.mth_create_user%type,
       in_update_user                           mms_txn_header.mth_update_user%type)

  RETURN NUMBER IS
begin

  insert into mms_txn_header
              (mth_txn_id,
                mth_org_txn_id,
                mth_action_txn_id,
                mth_input_channel,
                mth_status,
                mth_ar_ind,
                mth_sub_status,
                mth_txn_code,
		mth_process_type,
		mth_process_code,
		mth_node_id,
		mth_node_ref,
                mth_host_posting_date,
                mth_transmission_datetime,
                mth_internal_code,
                mth_response_code,
                mth_transaction_amount,
                mth_txn_ccy,
                mth_remaining_amount,
                mth_net_amount,
		mth_net_ccy,
                mth_local_tm_date,
                mth_local_tm_time,
                mth_tm_date,
                mth_tm_time,
		mth_client_ip,
		mth_apply_cost,
		mth_action,
		mth_related_txn_id,
                mth_create_user,
                mth_create_timestamp,
                mth_update_user,
                mth_update_timestamp)
         values(in_txn_id,
                in_org_txn_id,
                in_action_txn_id,
                in_input_channel,
                in_status,
                in_ar_ind,
                in_sub_status,
                in_txn_code,
		in_process_type,
		in_process_code,
		in_node_id,
		in_node_ref,
                in_host_posting_date,
                in_transmission_datetime,
                in_internal_code,
                in_response_code,
                nvl(in_transaction_amt,0),
                in_txn_ccy,
		nvl(in_remaining_amt,0),
                nvl(in_net_amt,0),
		in_net_ccy,
                in_local_tm_date,
                in_local_tm_time,
                in_tm_date,
                in_tm_time,
		in_client_ip,
		in_apply_cost,
		in_action,
		in_related_txn_id,
                in_create_user,
                sysdate,
                in_update_user,
                sysdate);

  IF SQL%ROWCOUNT = 0 THEN
     RETURN 1;
  ELSE
     RETURN 0;
  END IF;

EXCEPTION
  WHEN OTHERS THEN
     RETURN 9;
end sp_mms_txn_header_insert;
/
