OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MiModeTxnCtl
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMiModeTxnCtl.so
SOOBJS =  MiModeTxnCtl.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
