ALTER TABLE OL_TXN_MI_DETAIL
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_TXN_MI_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE OL_TXN_MI_DETAIL
(
  OTM_TXN_ID                VARCHAR2(16 BYTE),
  OTM_ENTITY_ID             VARCHAR2(10 BYTE),
  OTM_PARTY_TYPE            CHAR(3 BYTE),
  OTM_PARTY_ID              VARCHAR2(10 BYTE),
  OTM_TXN_CCY               VARCHAR2(3 BYTE),
  OTM_TXN_COUNTRY           CHAR(2 BYTE),
  OTM_TXN_PRODUCT           CHAR(3 BYTE),
  OTM_OPEN_ACCT_BAL         NUMBER(14,2)        DEFAULT 0,
  OTM_ACCT_BAL              NUMBER(14,2)        DEFAULT 0,
  OTM_OPEN_INTRANSIT        NUMBER(14,2)        DEFAULT 0,
  OTM_INTRANSIT             NUMBER(14,2)        DEFAULT 0,
  OTM_OPEN_AR_BAL           NUMBER(14,2)        DEFAULT 0,
  OTM_AR_BAL                NUMBER(14,2)        DEFAULT 0,
  OTM_TXN_DATE              VARCHAR2(8 BYTE),
  OTM_REPORT_DATE           VARCHAR2(8 BYTE),
  OTM_COST_RATE             NUMBER(12,5),
  OTM_ACTUAL_COST           NUMBER(14,2),
  OTM_REMITTANCE_SLIP_DATE  VARCHAR2(8 BYTE),
  OTM_CONVERTED_CCY         VARCHAR2(3 BYTE),
  OTM_CONVERTED_AMOUNT      NUMBER(14,2),
  OTM_REMARK                VARCHAR2(255 BYTE),
  OTM_PREV_GRP_TXN_ID       VARCHAR2(16 BYTE),
  OTM_NEXT_GRP_TXN_ID       VARCHAR2(16 CHAR),
  OTM_ACR_PRORATA           INTEGER             DEFAULT 0,
  OTM_ENTITY_CCY            VARCHAR2(3 BYTE),
  OTM_ENTITY_TXN_AMOUNT     NUMBER(14,2)        DEFAULT 0,
  OTM_CREATE_TIMESTAMP      DATE,
  OTM_UPDATE_TIMESTAMP      DATE,
  OTM_CREATE_USER           VARCHAR2(20 BYTE),
  OTM_UPDATE_USER           VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX OL_TXN_MI_DETAIL_IDX01 ON OL_TXN_MI_DETAIL
(OTM_ENTITY_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX OL_TXN_MI_DETAIL_IDX02 ON OL_TXN_MI_DETAIL
(OTM_PARTY_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX OL_TXN_MI_DETAIL_IDX03 ON OL_TXN_MI_DETAIL
(OTM_TXN_COUNTRY, OTM_TXN_PRODUCT, OTM_TXN_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX OL_TXN_MI_DETAIL_IDX04 ON OL_TXN_MI_DETAIL
(OTM_CREATE_TIMESTAMP, OTM_ENTITY_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX OL_TXN_MI_DETAIL_IDX05 ON OL_TXN_MI_DETAIL
(OTM_TXN_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX OL_TXN_MI_DETAIL_IDX06 ON OL_TXN_MI_DETAIL
(OTM_PREV_GRP_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX OL_TXN_MI_DETAIL_IDX07 ON OL_TXN_MI_DETAIL
(OTM_NEXT_GRP_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX OL_TXN_MI_DETAIL_PK ON OL_TXN_MI_DETAIL
(OTM_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_TXN_MI_DETAIL ADD (
  CONSTRAINT OL_TXN_MI_DETAIL_PK
  PRIMARY KEY
  (OTM_TXN_ID)
  USING INDEX OL_TXN_MI_DETAIL_PK
  ENABLE VALIDATE);

