OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/RulePspLbPsp
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBRulePspLbPsp.so
SOOBJS =  RulePspLbPsp.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
