OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MerchantSettFloat
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMerchantSettFloat.so
SOOBJS =  MerchantSettFloat.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
