CREATE OR REPLACE FUNCTION SP_HIST_OL_BT_INTERSUM_COLLECT(
    IN_END_DATE IN DATE )
RETURN NUMBER IS
	EXP_ERR  EXCEPTION;
	EXP_ERR2 EXCEPTION;
	DATE_ERR EXCEPTION;
	
	V_CUTOFF_DATE DATE;
	
	V_NEW_BATCH_ID HIST_OL_BT_INTER_SUM_BATCH.HB_BATCH_ID%type;
	V_PREV_BATCH_ID HIST_OL_BT_INTER_SUM_BATCH.HB_BATCH_ID%type;
	V_START_DATE         DATE;
	V_ADD_RANGE_END_DATE DATE;
	
	V_REQ_AMT NUMBER(14,2); 
	V_VOID_AMT NUMBER(14,2); 
	V_NET_AMT NUMBER(14,2);
	
	V_NET_AMT_HKD NUMBER(14,2);
	V_NET_AMT_USD NUMBER(14,2);
	
	V_PREV_TXN_COUNT NUMBER;
	V_TXN_COUNT NUMBER;
	
	V_PREV_REQ_AMT NUMBER(14,2);
	V_PREV_VOID_AMT NUMBER(14,2);
	V_PREV_NET_AMT NUMBER(14,2); 
	
	V_PREV_NET_AMT_HKD NUMBER(14,2);
	V_PREV_NET_AMT_USD NUMBER(14,2);
	 
	V_HKD_RATE EXCHANGE_RATE.EX_MED_ASK%type;
	V_USD_RATE EXCHANGE_RATE.EX_MED_ASK%type;
	V_COUNT_NO number;
	V_COUNT_NO2 number;
  
BEGIN
-- DBMS_OUTPUT.PUT_LINE('>>> START [HIST_OL_BT_INTER_SUM_COLLECT] <<<');
-- DBMS_OUTPUT.PUT_LINE('--> Input Date: '|| TO_CHAR(IN_END_DATE, 'YYYY-MM-DD HH24:MI') );

	SELECT 
		count(*)
	INTO 
		V_COUNT_NO2
	FROM  HIST_RPT_CONFIG
	WHERE HR_RPT_CODE = 'OL_BT_INTER_SUM';

	IF SQL % ROWCOUNT != 1 THEN
		raise EXP_ERR2;
	END IF; 
	  
	  
	IF V_COUNT_NO2 > 0 THEN
		SELECT 
		      HR_CUTOFF_DATE
		INTO 
		      V_CUTOFF_DATE
		FROM  HIST_RPT_CONFIG
		WHERE HR_RPT_CODE = 'OL_BT_INTER_SUM';

		IF SQL % ROWCOUNT != 1 THEN
		      raise EXP_ERR2;
		END IF ;
	ELSE 
		V_CUTOFF_DATE :=  IN_END_DATE - 1 ;
	END IF ; 

-- Find Prev Batch ID and current batch start date/time
	SELECT HB_BATCH_ID,
		HB_END_DATE
	INTO V_PREV_BATCH_ID,
		V_START_DATE
	FROM
	(SELECT HB_BATCH_ID,
	        HB_END_DATE,
	        ROW_NUMBER() OVER (PARTITION BY HB_DISABLED ORDER BY HB_END_DATE DESC) RN
	FROM HIST_OL_BT_INTER_SUM_BATCH
	WHERE HB_DISABLED = 0
	)
	WHERE RN           = 1;

	IF SQL % ROWCOUNT != 1 THEN
	  raise EXP_ERR2;
	END IF ;

	V_START_DATE := V_START_DATE + 1/24/60;
-- DBMS_OUTPUT.PUT_LINE('--> Start Date: '|| V_START_DATE );
-- DBMS_OUTPUT.PUT_LINE('--> End Date: '|| IN_END_DATE );

-- only look forward
	IF IN_END_DATE < V_START_DATE THEN
		raise DATE_ERR;
	END IF;
-- DBMS_OUTPUT.PUT_LINE('xxxx');

-- New Batch ID
	SELECT MAX(HB_BATCH_ID) + 1
	INTO V_NEW_BATCH_ID
	FROM HIST_OL_BT_INTER_SUM_BATCH;
-- DBMS_OUTPUT.PUT_LINE('--> New Batch ID: ' || V_NEW_BATCH_ID );
-- DBMS_OUTPUT.PUT_LINE('--> Previous Batch ID: ' || V_PREV_BATCH_ID );

-- Add 1 mins to end times
	V_ADD_RANGE_END_DATE := IN_END_DATE + 1/24/60;
-- DBMS_OUTPUT.PUT_LINE('--> Add 1 mins end date: ' || V_ADD_RANGE_END_DATE );
-- Insert New Batch
	INSERT
	INTO HIST_OL_BT_INTER_SUM_BATCH
	(
		HB_BATCH_ID,
		HB_START_DATE,
		HB_END_DATE,
		HB_DISABLED,
		HB_CREATE_TIMESTAMP,
		HB_CREATE_USER
	)
	VALUES
	(
		V_NEW_BATCH_ID,
		V_START_DATE,
		IN_END_DATE,
		0,
		SYSDATE,
		'SYSTEM'
	);

	IF SQL % ROWCOUNT != 1 THEN
		raise EXP_ERR;
	END IF ;
-- DBMS_OUTPUT.PUT_LINE('--> Insert New Batch : OK');
  
-- Find BAID Balance Transfer In - Inter from start times to end times
	FOR X IN
	(
		SELECT PRODUCT_CODE
			,REQ_CCY
			,REQ_AMOUNT
			,VOID_AMOUNT
			,NET_REQ_AMOUNT
			,TXN_COUNT
			,IS_PREV
		FROM (
			SELECT PRODUCT_CODE
				,REQ_CCY
				,REQ_AMOUNT
				,VOID_AMOUNT
				,NET_REQ_AMOUNT
				,TXN_COUNT
				,IS_PREV
				,ROW_NUMBER() OVER (
					PARTITION BY PRODUCT_CODE
					,REQ_CCY ORDER BY IS_PREV ASC
					) RN
			FROM (
				SELECT 
					CRR_PSP_PRODUCT_CODE_MAP.PM_PRODUCT_CODE AS PRODUCT_CODE
					,OL_TXN_PSP_DETAIL.OTP_TXN_CCY AS REQ_CCY
					,0 AS REQ_AMOUNT
					,0 AS VOID_AMOUNT
					,SUM(CASE 
						WHEN OTE_AMT_TYPE = 'CR' 
							THEN OL_TXN_PSP_DETAIL.OTP_TXN_AMOUNT 
						ELSE 0 
						END - CASE WHEN OTE_AMT_TYPE = 'DR' 
							THEN OL_TXN_PSP_DETAIL.OTP_TXN_AMOUNT 
						ELSE 0 
						END) AS NET_REQ_AMOUNT
					,COUNT(OL_TXN_HEADER.OTH_TXN_ID) AS TXN_COUNT
					,0 AS IS_PREV
				FROM OL_TXN_HEADER
				INNER JOIN OL_TXN_PSP_DETAIL
					ON OL_TXN_PSP_DETAIL.OTP_TXN_ID = OL_TXN_HEADER.OTH_TXN_ID
				INNER JOIN OL_PSP_DETAIL
					ON OL_PSP_DETAIL.OPD_PSP_ID = OL_TXN_PSP_DETAIL.OTP_PSP_ID
				LEFT JOIN CRR_PSP_PRODUCT_CODE_MAP
					ON 	CRR_PSP_PRODUCT_CODE_MAP.PM_PSP_ID = OL_PSP_DETAIL.OPD_PSP_ID
					AND CRR_PSP_PRODUCT_CODE_MAP.PM_BUSINESS_TYPE = OL_PSP_DETAIL.OPD_BUSINESS_TYPE
				INNER JOIN OL_TXN_ELEMENTS
					ON OL_TXN_ELEMENTS.OTE_TXN_ID = OL_TXN_HEADER.OTH_TXN_ID
					AND OL_TXN_ELEMENTS.OTE_TXN_ELEMENT_TYPE IN ('INTR','TAMT')
				WHERE 1 = 1
					AND OL_TXN_HEADER.OTH_APPROVAL_TIMESTAMP >= CAST(V_START_DATE AS TIMESTAMP)
					AND OL_TXN_HEADER.OTH_APPROVAL_TIMESTAMP < CAST(V_ADD_RANGE_END_DATE AS TIMESTAMP)
					AND 
					OL_TXN_HEADER.OTH_TXN_CODE IN ( 
						SELECT TXN_CODE.TC_CODE AS TXN_CODE
						FROM OL_TC_BAL_TRF_MAP
						INNER JOIN TXN_CODE
							ON TC_CODE = BTM_TXN_CODE
						WHERE BTM_FR_ACCT_TYPE = 'OLN'
						AND BTM_BAL_TRF_TYPE = 'INTER'
						AND TC_VOIDABLE = 1
						AND TC_OFL_FE_DISPLAY = 1
		
						UNION
		
						SELECT TXN_CODE.TC_OFL_VOID_CODE AS TXN_CODE
						FROM OL_TC_BAL_TRF_MAP
						INNER JOIN TXN_CODE
							ON TC_CODE = BTM_TXN_CODE
						WHERE BTM_FR_ACCT_TYPE = 'OLN'
						AND BTM_BAL_TRF_TYPE = 'INTER'
						AND TC_VOIDABLE = 1
						AND TC_OFL_FE_DISPLAY = 1
					)
				GROUP BY 
				CRR_PSP_PRODUCT_CODE_MAP.PM_PRODUCT_CODE
				,OL_TXN_PSP_DETAIL.OTP_TXN_CCY
				
				UNION
				
				SELECT HD_PRODUCT AS PRODUCT_CODE
					,HD_CCY AS REQ_CCY
					,HD_ACCUM_REQ_AMT AS REQ_AMOUNT
					,HD_ACCUM_VOID_AMT AS VOID_AMOUNT
					,HD_ACCUM_NET_AMT AS NET_REQ_AMOUNT
					,HD_COUNT AS TXN_COUNT
					,1 AS IS_PREV
				FROM HIST_OL_BT_INTER_SUM_DETAIL
				WHERE HD_BATCH_ID = V_PREV_BATCH_ID
			)
		)
		WHERE RN = 1
	)
	LOOP
-- DBMS_OUTPUT.PUT_LINE('--> PRODUCT_CODE: [' || X.PRODUCT_CODE || '] REQ_CCY : [' || X.REQ_CCY||'] ');
	
		SELECT count(*) AS COUNT_NO INTO V_COUNT_NO
		FROM HIST_OL_BT_INTER_SUM_DETAIL  
		WHERE HD_BATCH_ID = V_PREV_BATCH_ID
		AND HD_CCY = X.REQ_CCY
		AND HD_PRODUCT = X.PRODUCT_CODE
	        ;	
			
		IF V_COUNT_NO > 0 THEN
-- Prev Batch Bal	
			 SELECT
				NVL(HD_COUNT, 0)   AS HD_COUNT,
				NVL(HD_ACCUM_REQ_AMT, 0.00) AS HD_ACCUM_REQ_AMT,
				NVL(HD_ACCUM_VOID_AMT, 0.00) AS HD_ACCUM_VOID_AMT,
				NVL(HD_ACCUM_NET_AMT, 0.00) AS HD_ACCUM_NET_AMT,
				NVL(HD_ACCUM_NET_AMT_HKD, 0.00) AS HD_ACCUM_NET_AMT_HKD,
				NVL(HD_ACCUM_NET_AMT_USD, 0.00) AS HD_ACCUM_NET_AMT_USD
			 INTO 
				V_PREV_TXN_COUNT,
				V_PREV_REQ_AMT,
				V_PREV_VOID_AMT,
				V_PREV_NET_AMT,
				V_PREV_NET_AMT_HKD,
				V_PREV_NET_AMT_USD
			FROM HIST_OL_BT_INTER_SUM_DETAIL  
			WHERE HD_BATCH_ID = V_PREV_BATCH_ID
			AND HD_CCY = X.REQ_CCY
			AND HD_PRODUCT = X.PRODUCT_CODE;
		ELSE
			V_PREV_TXN_COUNT := 0;
			V_PREV_REQ_AMT := 0.00;
			V_PREV_VOID_AMT := 0.00;
			V_PREV_NET_AMT := 0.00;
			V_PREV_NET_AMT_HKD := 0.00;
			V_PREV_NET_AMT_USD := 0.00;
		END IF ;
	
-- DBMS_OUTPUT.PUT_LINE('--> V_PREV_TXN_COUNT: [' || V_PREV_TXN_COUNT || '] V_PREV_REQ_AMT: [' || V_PREV_REQ_AMT ||'] V_PREV_NET_AMT_HKD: [' || V_PREV_NET_AMT_HKD ||'] V_PREV_NET_AMT_USD: [' || V_PREV_NET_AMT_USD ||']');	

-- DBMS_OUTPUT.PUT_LINE('--> GET Rate');	  
-- HKD Rate , USD Rate	
		SELECT
			RATE_HKD_TBL.RATE AS HKD_RATE,
			RATE_USD_TBL.RATE AS USD_RATE
		INTO 
			V_HKD_RATE,
			V_USD_RATE
		FROM 
		(
			SELECT 
				EX_MED_ASK AS RATE ,
				EX_TO_CCY_ID
			FROM (
				SELECT  EX_FROM_CCY_ID
					,EX_TO_CCY_ID
					,EX_MED_ASK
					,ROW_NUMBER() OVER (
						PARTITION BY EX_FROM_CCY_ID
						,EX_TO_CCY_ID ORDER BY EX_EFFECT_DATE DESC
					) XX
				FROM EXCHANGE_RATE
				WHERE EX_EFFECT_DATE < CAST(V_ADD_RANGE_END_DATE AS TIMESTAMP)
			)
			WHERE XX = 1
			AND EX_TO_CCY_ID = 'HKD'
			AND EX_FROM_CCY_ID = X.REQ_CCY
		) RATE_HKD_TBL 
		INNER JOIN (
			SELECT  
				EX_MED_ASK AS RATE ,
				EX_FROM_CCY_ID
			FROM (
				SELECT EX_FROM_CCY_ID
					,EX_TO_CCY_ID
					,EX_MED_ASK
					,ROW_NUMBER() OVER (
						PARTITION BY EX_FROM_CCY_ID
						,EX_TO_CCY_ID ORDER BY EX_EFFECT_DATE DESC
					) XX
				FROM EXCHANGE_RATE
				WHERE EX_EFFECT_DATE < CAST(V_ADD_RANGE_END_DATE AS TIMESTAMP)
			)
			WHERE XX = 1
			AND EX_FROM_CCY_ID = 'HKD'
			AND EX_TO_CCY_ID = 'USD'
		) RATE_USD_TBL ON RATE_HKD_TBL.EX_TO_CCY_ID = RATE_USD_TBL.EX_FROM_CCY_ID;
	
-- DBMS_OUTPUT.PUT_LINE('--> HKD_RATE: [' || V_HKD_RATE || '] USD_RATE: [' || V_USD_RATE ||']');		 
	 
		IF X.IS_PREV = 0 THEN
			V_REQ_AMT := V_PREV_REQ_AMT + X.REQ_AMOUNT ; 
			V_VOID_AMT := V_PREV_VOID_AMT + X.VOID_AMOUNT;
			V_NET_AMT := V_PREV_NET_AMT + X.NET_REQ_AMOUNT;
			V_NET_AMT_HKD := V_PREV_NET_AMT_HKD + (X.NET_REQ_AMOUNT * V_HKD_RATE) ; 
			V_NET_AMT_USD := V_PREV_NET_AMT_USD + (X.NET_REQ_AMOUNT * V_HKD_RATE * V_USD_RATE) ; 
			V_TXN_COUNT := V_PREV_TXN_COUNT + X.TXN_COUNT ; 
		ELSE
			V_REQ_AMT := V_PREV_REQ_AMT; 
			V_VOID_AMT := V_PREV_VOID_AMT; 
			V_NET_AMT := V_PREV_NET_AMT; 
			V_NET_AMT_HKD := V_PREV_NET_AMT_HKD;
			V_NET_AMT_USD := V_PREV_NET_AMT_USD;
			V_TXN_COUNT := V_PREV_TXN_COUNT; 
		END IF ;
	 
-- DBMS_OUTPUT.PUT_LINE('--> INSERT ');	  
  /* DBMS_OUTPUT.PUT_LINE('--> HD_BATCH_ID: [' || V_NEW_BATCH_ID || '] 
								 HD_CCY: [' || X.REQ_CCY ||']
								 HD_PRODUCT: [' || X.PRODUCT_CODE ||']
								 HD_COUNT: [' || X.TXN_COUNT ||']
								 
							');	 */
							
-- Check Cut off Time
	IF V_CUTOFF_DATE >= V_ADD_RANGE_END_DATE THEN
		V_TXN_COUNT:= 0.00;
		V_REQ_AMT := 0.00;
		V_VOID_AMT := 0.00;
		V_NET_AMT := 0.00;
		V_NET_AMT_HKD := 0.00;
		V_HKD_RATE := 0.00;
		V_NET_AMT_USD := 0.00;
		V_USD_RATE := 0.00;
	END IF;
							
      	INSERT INTO HIST_OL_BT_INTER_SUM_DETAIL
        (
		HD_BATCH_ID,
		HD_CCY,
		HD_PRODUCT,
		HD_COUNT,
		HD_ACCUM_REQ_AMT,
		HD_ACCUM_VOID_AMT,
		HD_ACCUM_NET_AMT,
		HD_ACCUM_NET_AMT_HKD,
		HD_HKD_RATE,
		HD_ACCUM_NET_AMT_USD,
		HD_USD_RATE
	) VALUES (
		V_NEW_BATCH_ID,
		X.REQ_CCY,
		X.PRODUCT_CODE,
		NVL(V_TXN_COUNT, 0),
		NVL(V_REQ_AMT, 0.00),
		NVL(V_VOID_AMT, 0.00),
		NVL(V_NET_AMT, 0.00),
		NVL(V_NET_AMT_HKD, 0.00),
		V_HKD_RATE,
		NVL(V_NET_AMT_USD, 0.00),
		V_USD_RATE
        );

      	IF SQL % ROWCOUNT != 1 THEN
        	raise EXP_ERR;
      	END IF;
-- DBMS_OUTPUT.PUT_LINE('--> END INSERT ');

	END LOOP;

	COMMIT;
-- DBMS_OUTPUT.PUT_LINE('>>> END [HIST_OL_BT_INTER_SUM_COLLECT] <<<');

	RETURN 0;

EXCEPTION
WHEN EXP_ERR THEN
	ROLLBACK;
--DBMS_OUTPUT.PUT_LINE('Error: Insert error!...');
	RETURN 1;
WHEN DATE_ERR THEN
 	ROLLBACK;
--DBMS_OUTPUT.PUT_LINE('Error: The latest batch end date larger than input date!');
	RETURN 1;
WHEN EXP_ERR2 THEN
	ROLLBACK;
--DBMS_OUTPUT.PUT_LINE('Error: no record!...');
	RETURN 1;
WHEN OTHERS THEN
	ROLLBACK;
--DBMS_OUTPUT.PUT_LINE('Error: Other error!...');
--DBMS_OUTPUT.PUT_LINE('Error code ' || SQLCODE|| ': ' || SUBSTR(SQLERRM, 1 , 64));
--RAISE_APPLICATION_ERROR( -20201, 'Error code ' || SQLCODE|| ': ' || SUBSTR(SQLERRM, 1 , 64) );
	RETURN 9;
END SP_HIST_OL_BT_INTERSUM_COLLECT;
/

