LTER TABLE CRR_MONTH_END
 DROP PRIMARY KEY CASCADE;

DROP TABLE CRR_MONTH_END CASCADE CONSTRAINTS;

CREATE TABLE CRR_MONTH_END
(
	TB_YEAR	VARCHAR2(4) NOT NULL,
	TB_MONTH VARCHAR2(2) NOT NULL,
	CLOSED	NUMBER(1) DEFAULT 0,
	DISABLED	NUMBER(1) DEFAULT 0,
	CREATE_TIMESTAMP	DATE	DEFAULT SYSDATE,
	UPDATE_TIMESTAMP	DATE	DEFAULT SYSDATE,
	CREATE_USER	VARCHAR2(20),
	UPDATE_USER	VARCHAR2(20)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX CRR_MONTH_END_PK ON CRR_MONTH_END
(TB_YEAR, TB_MONTH)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE CRR_MONTH_END ADD (
  CONSTRAINT CRR_MONTH_END_PK
  PRIMARY KEY
  (TB_YEAR, TB_MONTH)
  USING INDEX CRR_MONTH_END_PK);


