OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnWebOnUs2PFT
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnWebOnUs2PFT.so
SOOBJS = TxnWebOnUs2PFT.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
