ALTER TABLE DEF_MMS_PARTY_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_MMS_PARTY_TYPE CASCADE CONSTRAINTS;

CREATE TABLE DEF_MMS_PARTY_TYPE
(
  DM_TYPE              VARCHAR2(5 BYTE),
  DM_DESC              VARCHAR2(50 BYTE),
  DM_CREATE_TIMESTAMP  DATE,
  DM_CREATE_USER       VARCHAR2(20 BYTE),
  DM_UPDATE_TIMESTAMP  DATE,
  DM_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEF_MMS_PARTY_TYPE_PK ON DEF_MMS_PARTY_TYPE
(DM_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_MMS_PARTY_TYPE ADD (
  CONSTRAINT DEF_MMS_PARTY_TYPE_PK
  PRIMARY KEY
  (DM_TYPE)
  USING INDEX DEF_MMS_PARTY_TYPE_PK
  ENABLE VALIDATE);

