ALTER TABLE SERVICE_BLACKLIST_URL
 DROP PRIMARY KEY CASCADE;

DROP TABLE SERVICE_BLACKLIST_URL CASCADE CONSTRAINTS;

CREATE TABLE SERVICE_BLACKLIST_URL
(
  BU_SERVICE_CODE      CHAR(3 BYTE),
  BU_MERCHANT_ID       VARCHAR2(15 BYTE),
  BU_COUNTRY           VARCHAR2(2 BYTE),
  BU_URL               VARCHAR2(50 BYTE),
  BU_EFFECT_DATE       DATE                     DEFAULT sysdate,
  BU_DISABLED          INTEGER                  DEFAULT 0,
  BU_NEW_UI            INTEGER                  DEFAULT 0                     NOT NULL,
  BU_DESC              VARCHAR2(50 BYTE),
  BU_FOR_BACKUP        INTEGER                  DEFAULT 0,
  BU_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  BU_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  BU_CREATE_USER       VARCHAR2(20 BYTE),
  BU_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX SERVICE_BLACKLIST_URL_PK ON SERVICE_BLACKLIST_URL
(BU_SERVICE_CODE, BU_MERCHANT_ID, BU_COUNTRY, BU_EFFECT_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE SERVICE_BLACKLIST_URL ADD (
  CONSTRAINT SERVICE_BLACKLIST_URL_PK
  PRIMARY KEY
  (BU_SERVICE_CODE, BU_MERCHANT_ID, BU_COUNTRY, BU_EFFECT_DATE)
  USING INDEX SERVICE_BLACKLIST_URL_PK
  ENABLE VALIDATE);

ALTER TABLE SERVICE_BLACKLIST_URL ADD (
  CONSTRAINT SERVICE_BLACKLIST_URL_FK01 
  FOREIGN KEY (BU_SERVICE_CODE) 
  REFERENCES DEF_SERVICE_CODE (SC_CODE)
  ENABLE VALIDATE);

