DROP TABLE CLIENT_MAGIC_GP_STATUS_LOG CASCADE CONSTRAINTS;

CREATE TABLE CLIENT_MAGIC_GP_STATUS_LOG
(
  GSL_CLIENT_ID         VARCHAR2(10 BYTE),
  GSL_TXN_GP_ID         INTEGER,
  GSL_OLD_STATUS        CHAR(1 BYTE),
  GSL_NEW_STATUS        CHAR(1 BYTE),
  GSL_CREATE_USER       VARCHAR2(20 BYTE),
  GSL_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  GSL_UPDATE_USER       VARCHAR2(20 BYTE),
  GSL_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX CLIENT_MAGIC_GP_ST_LOG_IDX01 ON CLIENT_MAGIC_GP_STATUS_LOG
(GSL_CLIENT_ID, GSL_TXN_GP_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

