ALTER TABLE CLIENT_MAGIC_GP_STATUS
 DROP PRIMARY KEY CASCADE;

DROP TABLE CLIENT_MAGIC_GP_STATUS CASCADE CONSTRAINTS;

CREATE TABLE CLIENT_MAGIC_GP_STATUS
(
  GS_CLIENT_ID         VARCHAR2(10 BYTE),
  GS_TXN_GP_ID         INTEGER,
  GS_STATUS            CHAR(1 BYTE),
  GS_CREATE_USER       VARCHAR2(20 BYTE),
  GS_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  GS_UPDATE_USER       VARCHAR2(20 BYTE),
  GS_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN CLIENT_MAGIC_GP_STATUS.GS_STATUS IS '''O'' - Open (Enabled) ; ''C'' - Close (Disabled)
';



CREATE UNIQUE INDEX CLIENT_MAGIC_GP_STATUS_PK ON CLIENT_MAGIC_GP_STATUS
(GS_CLIENT_ID, GS_TXN_GP_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE CLIENT_MAGIC_GP_STATUS ADD (
  CONSTRAINT CLIENT_MAGIC_GP_STATUS_PK
  PRIMARY KEY
  (GS_CLIENT_ID, GS_TXN_GP_ID)
  USING INDEX CLIENT_MAGIC_GP_STATUS_PK
  ENABLE VALIDATE);

