OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnMgtByUsPAL
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnMgtByUsPAL.so
SOOBJS = TxnMgtByUsPAL.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
