OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/PspDetail
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBPspDetail.so
SOOBJS =  PspDetail.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
