DROP TABLE CCTTXN CASCADE CONSTRAINTS;

CREATE TABLE CCTTXN
(
  CC_TXN_ID                 VARCHAR2(16 BYTE)   NOT NULL,
  CC_TXN_CCY                CHAR(3 BYTE),
  CC_TXN_COUNTRY            CHAR(2 BYTE),
  CC_PAY_METHOD             VARCHAR2(50 BYTE),
  CC_BANK_CODE              VARCHAR2(10 BYTE),
  CC_BANK_NAME              VARCHAR2(50 BYTE),
  CC_BRANCH_NAME            VARCHAR2(50 BYTE),
  CC_ACCOUNT_ID             VARCHAR2(25 BYTE),
  CC_ACCOUNT_NAME           VARCHAR2(100 BYTE),
  CC_IDENTITY_ID            VARCHAR2(25 BYTE),
  CC_PROVINCE               VARCHAR2(25 BYTE),
  CC_PHONE_NO               VARCHAR2(25 BYTE),
  CC_CITY                   VARCHAR2(20 BYTE),
  CC_BATCH_ID               VARCHAR2(20 BYTE),
  CC_SHOW_PAYPAGE           CHAR(1 BYTE),
  CC_LANGUAGE               CHAR(2 BYTE),
  CC_SUCCESS_URL            VARCHAR2(255 BYTE),
  CC_FAILURE_URL            VARCHAR2(255 BYTE),
  CC_SUCCESS_CALLBACK_URL   VARCHAR2(255 BYTE),
  CC_FAILURE_CALLBACK_URL   VARCHAR2(255 BYTE),
  CC_ENCRYPT_TYPE           VARCHAR2(4 BYTE),
  CC_PAYOUT_BAL             NUMBER(14,2),
  CC_SETTLEMENT_BAL         NUMBER(14,2),
  CC_TOTAL_FLOAT            NUMBER(14,2),
  CC_TOTAL_RESERVED_AMOUNT  NUMBER(14,2),
  CC_TOTAL_TFR_HOLD         NUMBER(14,2),
  CC_TOTAL_PAYOUT_HOLD      NUMBER(14,2),
  CC_TOTAL_SETTLEMENT_HOLD  NUMBER(14,2),
  CC_VERSION_NO             INTEGER,
  CC_PAYOUT_IN_TRANSIT      NUMBER(14,2),
  CC_SETTLEMENT_IN_TRANSIT  NUMBER(14,2),
  CC_REMARK                 VARCHAR2(255 BYTE),
  CC_SELECTED_PAY_METHOD    VARCHAR2(4 BYTE),
  CC_BANNER_LOGO            VARCHAR2(255 BYTE),
  CC_CUSTOMER_TAG           VARCHAR2(10 BYTE),
  CC_ECHO_MSG_1             VARCHAR2(50 BYTE),
  CC_ECHO_MSG_2             VARCHAR2(50 BYTE),
  CC_ECHO_MSG_3             VARCHAR2(50 BYTE),
  CC_OPT_1                  VARCHAR2(50 BYTE),
  CC_OPT_2                  VARCHAR2(50 BYTE),
  CC_OPT_3                  VARCHAR2(50 BYTE),
  CC_MERCHANT_ID            VARCHAR2(15 BYTE),
  CC_MERCHANT_REF           VARCHAR2(50 BYTE),
  CC_transaction_amount	    number(14,2),
  cc_net_amount		    number(14,2),
  CC_TM_DATE                VARCHAR2(8 BYTE),
  CC_TM_TIME                VARCHAR2(6 BYTE),
  CC_TRANSMISSION_DATETIME     VARCHAR2(14 BYTE),
  CC_CLIENT_IP_ADDR         VARCHAR2(25 BYTE),
  CC_STATUS		    char(1 byte),
  CC_AR_IND		    char(1 byte),
  CC_CREATE_USER            VARCHAR2(20 BYTE),
  CC_CREATE_TIMESTAMP       DATE                DEFAULT sysdate,
  CC_UPDATE_USER            VARCHAR2(20 BYTE),
  CC_UPDATE_TIMESTAMP       DATE                DEFAULT sysdate
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX CCTTXN_IDX ON CCTTXN
(CC_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

