CREATE OR REPLACE function sp_ccttxn_insert(
       in_txn_id                                ccttxn.cc_txn_id%type,
       in_txn_ccy				ccttxn.cc_txn_ccy%type,
       in_txn_country				ccttxn.cc_txn_country%type,
       in_pay_method				ccttxn.cc_pay_method%type,
       in_bank_code				ccttxn.cc_bank_code%type,
       in_bank_name				ccttxn.cc_bank_name%type,
       in_branch_name				ccttxn.cc_branch_name%type,
       in_account_id				ccttxn.cc_account_id%type,
       in_account_name				ccttxn.cc_account_name%type,
       in_identity_id				ccttxn.cc_identity_id%type,
       in_province				ccttxn.cc_province%type,
       in_phone_no				ccttxn.cc_phone_no%type,
       in_city					ccttxn.cc_city%type,
       in_batch_id				ccttxn.cc_batch_id%type,
       in_show_paypage			        ccttxn.cc_show_paypage%type,
       in_language				ccttxn.cc_language%type,
       in_success_url				ccttxn.cc_success_url%type,
       in_failure_url				ccttxn.cc_failure_url%type,
       in_success_callback_url	                ccttxn.cc_success_callback_url%type,
       in_failure_callback_url			ccttxn.cc_failure_callback_url%type,
       in_create_user                           ccttxn.cc_create_user%type,
       in_update_user                           ccttxn.cc_update_user%type,
       in_encrypt_type				ccttxn.cc_encrypt_type%type,
       in_version_no				ccttxn.cc_version_no%type,
       in_remark				ccttxn.cc_remark%type,
       in_selected_pay_method			ccttxn.cc_selected_pay_method%type,
       in_banner_logo                           ccttxn.cc_banner_logo%type,
       in_customer_tag                          ccttxn.cc_customer_tag%type,
       in_echo_msg_1                            ccttxn.cc_echo_msg_1%type,
       in_echo_msg_2                            ccttxn.cc_echo_msg_2%type,
       in_echo_msg_3                            ccttxn.cc_echo_msg_3%type,
       in_opt_1                                 ccttxn.cc_opt_1%type,
       in_opt_2                                 ccttxn.cc_opt_2%type,
       in_opt_3                                 ccttxn.cc_opt_3%type,
       in_merchant_id                           ccttxn.cc_merchant_id%type,
       in_merchant_ref                          ccttxn.cc_merchant_ref%type,
       in_transaction_amt                       ccttxn.cc_transaction_amount%type,
       in_transmission_datetime                 ccttxn.cc_transmission_datetime%type,
       in_tm_date                               ccttxn.cc_tm_date%type,
       in_tm_time                               ccttxn.cc_tm_time%type,
       in_client_ip                             ccttxn.cc_client_ip_addr%type


)
  RETURN NUMBER IS
Begin
     Update ccttxn
            Set cc_txn_ccy = in_txn_ccy,
                  cc_txn_country = in_txn_country,
		  cc_pay_method = in_pay_method,
		  cc_bank_code = in_bank_code,
		  cc_bank_name = in_bank_name,
		  cc_branch_name = in_branch_name,
		  cc_account_id = in_account_id,
		  cc_account_name = in_account_name,
		  cc_identity_id = in_identity_id,
		  cc_province = in_province,
		  cc_phone_no = in_phone_no,
		  cc_city = in_city,
		  cc_batch_id = in_batch_id,
                  cc_show_paypage = in_show_paypage,
                  cc_language = in_language,
                  cc_success_url = in_success_url,
		  cc_failure_url = in_failure_url,
                  cc_success_callback_url = in_success_callback_url,
		  cc_failure_callback_url = in_failure_callback_url,
                  cc_update_user = in_update_user,
                  cc_update_timestamp = Sysdate,
		  cc_encrypt_type=in_encrypt_type,
		  cc_version_no = in_version_no,
		  cc_remark = in_remark,
		  cc_selected_pay_method = in_selected_pay_method,
		  cc_banner_logo = in_banner_logo,
		  cc_customer_tag = in_customer_tag,
		  cc_echo_msg_1 = in_echo_msg_1,
		  cc_echo_msg_2 = in_echo_msg_2,
		  cc_echo_msg_3 = in_echo_msg_3,
		  cc_opt_1 = in_opt_1,
		  cc_opt_2 = in_opt_2,
		  cc_opt_3 = in_opt_3,
	          cc_merchant_id = in_merchant_id,
		  cc_merchant_ref = in_merchant_ref,
		  cc_transaction_amount = in_transaction_amt,
		  cc_transmission_datetime = in_transmission_datetime,
                  cc_tm_date = in_tm_date,
                  cc_tm_time = in_tm_time,
		  cc_client_ip_addr = in_client_ip
      Where cc_txn_id = in_txn_id;

     IF SQL%ROWCOUNT = 0 THEN
        insert into ccttxn
                     (cc_txn_id,
		      cc_txn_ccy,
		      cc_txn_country,
		      cc_pay_method,
                      cc_bank_code,
                      cc_bank_name,
                      cc_branch_name,
                      cc_account_id,
                      cc_account_name,
                      cc_identity_id,
                      cc_province,
                      cc_phone_no,
                      cc_city,
                      cc_batch_id,
		      cc_show_paypage,
		      cc_language,
		      cc_success_url,
		      cc_failure_url,
		      cc_success_callback_url,
		      cc_failure_callback_url,
                      cc_create_user,
                      cc_create_timestamp,
                      cc_update_user,
                      cc_update_timestamp,
		      cc_encrypt_type,
		      cc_version_no,
		      cc_remark,
		      cc_selected_pay_method,
		      cc_banner_logo,
                      cc_customer_tag,
                      cc_echo_msg_1,
                      cc_echo_msg_2,
                      cc_echo_msg_3,
                      cc_opt_1,
                      cc_opt_2,
                      cc_opt_3,
		      cc_merchant_id,
                      cc_merchant_ref,
                      cc_transaction_amount,
                      cc_transmission_datetime,
                      cc_tm_date,
                      cc_tm_time,
                      cc_client_ip_addr)
          values(in_txn_id,
		     in_txn_ccy,
                     in_txn_country,
		     in_pay_method,
		     in_bank_code,
		     in_bank_name,
		     in_branch_name,
		     in_account_id,
		     in_account_name,
		     in_identity_id,
		     in_province,
		     in_phone_no,
		     in_city,
		     in_batch_id,
		     in_show_paypage,
		     in_language,
		     in_success_url,
		     in_failure_url,
		     in_success_callback_url,
		     in_failure_callback_url,
                     in_create_user,
                     sysdate,
                     in_update_user,
                     sysdate,
		     in_encrypt_type,
		     in_version_no,
                     in_remark,
		     in_selected_pay_method,
		     in_banner_logo,
                     in_customer_tag,
                     in_echo_msg_1,
                     in_echo_msg_2,
                     in_echo_msg_3,
                     in_opt_1,
                     in_opt_2,
                     in_opt_3,
		     in_merchant_id,
                     in_merchant_ref,
                     in_transaction_amt,
                     in_transmission_datetime,
                     in_tm_date,
                     in_tm_time,
                     in_client_ip);

          IF SQL%ROWCOUNT = 0 THEN
             RETURN 1;
          ELSE
             RETURN 0;
          END IF;
      Else
          Return 0;
       End If;

EXCEPTION
  WHEN OTHERS THEN
     RETURN 9;
end sp_ccttxn_insert;
/

