


CREATE TABLE OL_DEF_PAYOUT_API_BATCH_STATUS
(
  OBS_TYPE              VARCHAR2(2 BYTE),
  OBS_DESC              VARCHAR2(50 BYTE),
  OBS_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate               NOT NULL,
  OBS_CREATE_USER       VARCHAR2(20 BYTE),
  OBS_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate               NOT NULL,
  OBS_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX OL_DEF_PAYOUT_API_BATCH_STA_PK ON OL_DEF_PAYOUT_API_BATCH_STATUS
(OBS_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE OL_DEF_PAYOUT_API_BATCH_STATUS ADD (
  CONSTRAINT OL_DEF_PAYOUT_API_BATCH_STA_PK
  PRIMARY KEY
  (OBS_TYPE)
  USING INDEX OL_DEF_PAYOUT_API_BATCH_STA_PK
  ENABLE VALIDATE);
