ALTER TABLE CRR_BASE_CURRENCY
 DROP PRIMARY KEY CASCADE;

DROP TABLE CRR_BASE_CURRENCY CASCADE CONSTRAINTS;

CREATE TABLE CRR_BASE_CURRENCY
(
	CURRENCY_ID	VARCHAR2(3) NOT NULL,
	DISABLED	NUMBER(1)	DEFAULT 0,
	CREATE_TIMESTAMP	DATE	DEFAULT SYSDATE,
	UPDATE_TIMESTAMP	DATE	DEFAULT SYSDATE,
	CREATE_USER	VARCHAR2(20),
	UPDATE_USER	VARCHAR2(20)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX CRR_BASE_CURRENCY_PK ON CRR_BASE_CURRENCY
(CURRENCY_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE CRR_BASE_CURRENCY ADD (
  CONSTRAINT CRR_BASE_CURRENCY_PK
  PRIMARY KEY
  (CURRENCY_ID)
  USING INDEX CRR_BASE_CURRENCY_PK);
  
ALTER TABLE CRR_BASE_CURRENCY ADD (
  CONSTRAINT CRR_BASE_CURRENCY_FK01
  FOREIGN KEY (CURRENCY_ID) 
  REFERENCES CURRENCY (CURRENCY_ID));    


