OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/ParPOReversedDT
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBParPOReversedDT.so
SOOBJS =  ParPOReversedDT.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
