OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=upload_bank_stmt.exec
BATCHOBJS=$(OBJHOME)/batchcommon.o upload_bank_stmt.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=   -lObjPtr
all: $(BATCHEXE)
