OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=gen_psp_delay_callback_report.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o gen_psp_delay_callback_report.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
