OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=extract_client_txn_hist_daily_rpt.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o extract_client_txn_hist_daily_rpt.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
