OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=fundin_balance.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o fundin_balance.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
