OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=offline_payout_generate.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o offline_payout_generate.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
