OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=get_psp_id_checking_list.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o get_psp_id_checking_list.o
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  
all: $(BATCHEXE)
