OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=sample.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o sample.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lcurl -lc -lm -lmyhash  -lObjPtr  -lmyrecordset -lexpat -lssl

all: $(BATCHEXE)
