OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=mmc_sync_data.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o mmc_sync_data.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lc -lm -lmyhash  -lObjPtr  -lmyrecordset

all: $(BATCHEXE)
