OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=create_psp_bal_trf_adhoc.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o create_psp_bal_trf_adhoc.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
