OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=offline_set_dsi_baid_init_bal.exec
BATCHOBJS=$(OBJHOME)/batchcommon.o offline_set_dsi_baid_init_bal.o
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS += -lexpat -lcurl -lc -lm -lmyhash -lObjPtr -lmyrecordset
all: $(BATCHEXE)
