OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=get_auto_upload_provider.exec
BATCHOBJS=$(OBJHOME)/batchcommon.o get_auto_upload_provider.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=   -lObjPtr
all: $(BATCHEXE)
