OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=fep_to_cms_report.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o fep_to_cms_report.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
