OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=get_auto_sett_email_body.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o get_auto_sett_email_body.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
