OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=get_qualify_promote.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o get_qualify_promote.o
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  
all: $(BATCHEXE)
