OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=reset_stat_non_daily.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o reset_stat_non_daily.o
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  
all: $(BATCHEXE)
