OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=ol_baid_bt_file.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o ol_baid_bt_file.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
