OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=tmp_ex_rate_report.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o tmp_ex_rate_report.o
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
