OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=check_baid_nature_change.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o check_baid_nature_change.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
