OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=run_txn_balance_update.exec
BATCHOBJS=$(OBJHOME)/batchcommon.o run_txn_balance_update.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=   -lObjPtr
all: $(BATCHEXE)
