OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=ol_bal_trf_in_inter_log_gen.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o ol_bal_trf_in_inter_log_gen.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
