OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=hskp_psp_txn_summary.exec
BATCHOBJS=$(OBJHOME)/batchcommon.o hskp_psp_txn_summary.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=   -lObjPtr
all: $(BATCHEXE)
