OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=match_dfq_dsp.exec
BATCHOBJS=$(OBJHOME)/batchcommon.o match_dfq_dsp.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=   -lObjPtr
all: $(BATCHEXE)
