OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=extract_mig_data_to_cms.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o extract_mig_data_to_cms.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
