OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=ol_auto_gen_baid_acct.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o ol_auto_gen_baid_acct.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
