OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=ref_mv_ol_merchant_balance.exec
BATCHOBJS=$(OBJHOME)/batchcommon.o ref_mv_ol_merchant_balance.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=   -lObjPtr
all: $(BATCHEXE)
