OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=recon_baid_unknown_bank_stmt.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o recon_baid_unknown_bank_stmt.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
