make -f Makefile.batch_status all
make -f Makefile.convert_esky_payout all
make -f Makefile.esky_dsp_report all
make -f Makefile.esky_to_hpy_report all
make -f Makefile.exportdata all
make -f Makefile.extract_esky_data all
make -f Makefile.extract_hpy_data all
make -f Makefile.extract_merchant_dsp_data all
make -f Makefile.eod_glpost all
