OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=rfe_dsp_report.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o rfe_dsp_report.o
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
