OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=alp_download.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o alp_download.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
