OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=OfflineMatch.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o OfflineMatch.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lcurl -lc -lm -lmyhash  -lObjPtr  -lmyrecordset -lexpat

all: $(BATCHEXE)
