OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=tmp_get.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o tmp_get.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
