OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=generate_txn_detail_by_psp.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o generate_txn_detail_by_psp.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
