
make -f Makefile.update_batch all
make -f Makefile.upd_job_status all
make -f Makefile.sample all
make -f Makefile.ph_eod_sat_sun all
make -f Makefile.ph_eod_date all
make -f Makefile.ph_cutoff all
make -f Makefile.payout_resp_to_merchant all
make -f Makefile.merchant_payout_report all
make -f Makefile.merchant_dsp_report all
make -f Makefile.match_twv_payout2 all
make -f Makefile.match_twv_payout all
make -f Makefile.match_twv_dsp all
make -f Makefile.match_merchant_payout all
make -f Makefile.match_merchant_deposit all
make -f Makefile.import_merchantfile all
make -f Makefile.holdjob all
make -f Makefile.hashkey all
make -f Makefile.getrate all
make -f Makefile.get_payout_resp all
make -f Makefile.get_nonsamedate all
make -f Makefile.get_merchant_id_list all
make -f Makefile.get_joblist all
make -f Makefile.get_currrptpath all
make -f Makefile.get_currphpath all
make -f Makefile.get_control all
make -f Makefile.generate_txn_detail all
make -f Makefile.gen_txn_detail_by_psp all
make -f Makefile.gen_txn_detail_by_merchant all
make -f Makefile.gen_record all
make -f Makefile.extract_psp_payout all
make -f Makefile.extract_psp_data all
make -f Makefile.extract_merchant_payout_data all
make -f Makefile.extract_merchant_dsp_data all
make -f Makefile.exportdata all
make -f Makefile.batch_status all
make -f Makefile.convert_esky_payout all
make -f Makefile.match_hpy_dsp all
make -f Makefile.extract_hpy_data all
make -f Makefile.hpy_dsp_report all
make -f Makefile.extract_esky_data all
make -f Makefile.esky_dsp_report all
make -f Makefile.esky_to_hpy_report all
make -f Makefile.get_psp_id_list all
make -f Makefile.handle_daily_float all
make -f Makefile.match_esky_dsp all
make -f Makefile.is_holiday all
make -f Makefile.reset_stat all
make -f Makefile.match_twv_dsp2 all
make -f Makefile.gen_hpy_cms_report all
make -f Makefile.get_psp_id_list_by_channel all
make -f Makefile.extract_hhp_data all
make -f Makefile.match_hhp_dsp all
make -f Makefile.get_psp_merchant_id all
make -f Makefile.hhp_dsp_report all
make -f Makefile.hhp_to_cms_report all
make -f Makefile.generate_txn_detail_by_psp all
make -f Makefile.check_psp_txn all
make -f Makefile.tmp_get all
make -f Makefile.eod_glpost all
make -f Makefile.eod_offsys_glpost_link all
make -f Makefile.eod_offsys_glpost all
