OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=aes_test.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o aes_test.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lc -lm -lmyhash -lssl

all: $(BATCHEXE)
