OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=get_consumer_url_mid_list.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o get_consumer_url_mid_list.o
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  
all: $(BATCHEXE)
