OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=get_psp_merchant_id.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o get_psp_merchant_id.o
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  
all: $(BATCHEXE)
