OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=check_missing_stmt.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o check_missing_stmt.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
