OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=eod_offext_glpost.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o eod_offext_glpost.o eod_offsys_glpost_link.o
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
