OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=check_frozen_txn_online.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o check_frozen_txn_online.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
