OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=par_adj_type.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o par_adj_type.o
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
