OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=clear_ol_payout_tmp.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o clear_ol_payout_tmp.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
