OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=ol_vip_payout.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o ol_vip_payout.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lcurl -lc -lm -lmyhash  -lObjPtr  -lmyrecordset -lexpat -lssl

all: $(BATCHEXE)
