OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=vg_getrate.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o vg_getrate.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
