OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=processing_costs_daily.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o processing_costs_daily.o
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  
all: $(BATCHEXE)
