OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=handle_auto_settlement.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o handle_auto_settlement.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
