OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=get_ofl_deposit_info.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o get_ofl_deposit_info.o
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  
all: $(BATCHEXE)
