OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=get_gaming_psp_id_by_channel.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o get_gaming_psp_id_by_channel.o
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  
all: $(BATCHEXE)
