OBJHOME = $(HOME)/obj/BATCH
BATCHEXE = test_andy.exec
BATCHOBJS = $(OBJHOME)/batchcommon.o test_andy.o
#
#
# Include the Common Rules
# 
# 
include Make.rules

LDLIBS += -lObjPtr

all     : $(BATCHEXE)

