OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=check_ip2location_email.exec
BATCHOBJS=$(OBJHOME)/batchcommon.o check_ip2location_email.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
