OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=housekeep_customer_psp_cnt.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o housekeep_customer_psp_cnt.o
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  
all: $(BATCHEXE)
