OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=deposit_match_stat.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o deposit_match_stat.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
