OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=update_psp_ret_merch_succ_url.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o update_psp_ret_merch_succ_url.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
