OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=extract_ol_poa_txn_detail_daily_rpt.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o extract_ol_poa_txn_detail_daily_rpt.o
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS += -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
