OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=bank_stmt_alert.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o bank_stmt_alert.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset -lutilitys
all: $(BATCHEXE)
