OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=pr_payout_upload.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o pr_bo_funct.o pr_payout_upload.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
