OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=inq_alp_pend_txn.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o inq_alp_pend_txn.o
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
