OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=import_ofl_rpt_tbl_data.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o import_ofl_rpt_tbl_data.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
