OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=handle_auto_exp_off_stmt_txn.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o handle_auto_exp_off_stmt_txn.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
