OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=trigger_onp.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o trigger_onp.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
