OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=payout_resp_to_merchant.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o payout_resp_to_merchant.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
