OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=offline_handle_poa_baid_unknown_dr.exec
BATCHOBJS=$(OBJHOME)/batchcommon.o offline_handle_poa_baid_unknown_dr.o
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS += -lexpat -lcurl -lc -lm -lmyhash -lObjPtr -lmyrecordset
all: $(BATCHEXE)
