OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=run_auto_upload_stmt.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o run_auto_upload_stmt.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
