OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=change_auto_upload_provider_detail.exec
BATCHOBJS=$(OBJHOME)/batchcommon.o change_auto_upload_provider_detail.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=   -lObjPtr
all: $(BATCHEXE)
