OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=get_ol_psp_id_list.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o get_ol_psp_id_list.o
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  
all: $(BATCHEXE)
