OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=handle_offline_remain_reserved_amt.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o handle_offline_remain_reserved_amt.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
