OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=eod_status_snapshot.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o eod_status_snapshot.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
