OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=get_deposit_country_list.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o get_deposit_country_list.o
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  
all: $(BATCHEXE)
