OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=match_twv_dsp.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o match_twv_dsp.o
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
