OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=ol_payout_recon_ignore_bank_match.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o ol_payout_recon_ignore_bank_match.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
