OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=dd_test_sha1rsa_sign.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o dd_test_sha1rsa_sign.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lcurl -lc -lm -lmyhash  -lObjPtr  -lmyrecordset -lexpat -lssl

all: $(BATCHEXE)
