OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=check_bank_psp_txn.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o check_bank_psp_txn.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lcurl -lc -lm -lmyhash  -lObjPtr  -lmyrecordset  -lpthread

all: $(BATCHEXE)
