OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=bank_stmt_and_sms_daily_report.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o bank_stmt_and_sms_daily_report.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
