OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=test_md5rsa_sign.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o test_md5rsa_sign.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lcurl -lc -lm -lmyhash  -lObjPtr  -lmyrecordset -lexpat -lssl

all: $(BATCHEXE)
