OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=get_ol_merchant_name.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o get_ol_merchant_name.o
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  
all: $(BATCHEXE)
