OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=update_auto_upload_status.exec
BATCHOBJS=$(OBJHOME)/batchcommon.o update_auto_upload_status.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=   -lObjPtr
all: $(BATCHEXE)
