OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=get_ofl_poa_open_status_psp_id.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o get_ofl_poa_open_status_psp_id.o
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  
all: $(BATCHEXE)
