OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=check_unknown_debit.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o check_unknown_debit.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset -lutilitys
all: $(BATCHEXE)
