OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=test_refresh_mview.exec
BATCHOBJS=$(OBJHOME)/batchcommon.o test_refresh_mview.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=   -lObjPtr
all: $(BATCHEXE)
