OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=check_bank_txn.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o check_bank_txn.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
