OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=handle_daily_float_2AFPO_test.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o handle_daily_float_2AFPO_test.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
