OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=get_currphpath.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o get_currphpath.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
