OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=test_mic_bal2.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o test_mic_bal2.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
