OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=par_txn_handler.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o par_txn_handler.o
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
