OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=extract_ofl_rpt_tbl_data.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o extract_ofl_rpt_tbl_data.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
