OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=reset_check_handshake_ew.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o reset_check_handshake_ew.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
