OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=generate_txn_detail.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o generate_txn_detail.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
