OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=check_bank_psp_txn_report.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o check_bank_psp_txn_report.o
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
