OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=check_exchange_rate.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o check_exchange_rate.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
