OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=check_offline_odi_callback.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o check_offline_odi_callback.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
