OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=import_merchantfile.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o import_merchantfile.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
