OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=getrate_new_api.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o getrate_new_api.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
