OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=gen_unrecon_sms_stmt_report.exec
BATCHOBJS=$(OBJHOME)/batchcommon.o gen_unrecon_sms_stmt_report.o
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS += -lexpat -lcurl -lc -lm -lmyhash -lObjPtr -lmyrecordset
all: $(BATCHEXE)
