OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=get_bank_txn_check_list.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o get_bank_txn_check_list.o
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  
all: $(BATCHEXE)
