OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=void_recon_adhoc.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o void_recon_adhoc.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
