OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=test_txn_engine_spc.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o test_txn_engine_spc.o
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  
all: $(BATCHEXE)
