OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=customer_group_promo.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o customer_group_promo.o
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  
all: $(BATCHEXE)
