OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=check_sim_card_next_topup.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o check_sim_card_next_topup.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
