OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=import_crr_ofl_merch_product_code_map.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o import_crr_ofl_merch_product_code_map.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
