OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=get_actual_promote.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o get_actual_promote.o
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  
all: $(BATCHEXE)
