OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=check_abc_convert.exec
BATCHOBJS=$(OBJHOME)/batchcommon.o check_abc_convert.o
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS += -lObjPtr
all: $(BATCHEXE)
