OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=check_customer_tag.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o check_customer_tag.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset -lutilitys
all: $(BATCHEXE)
