OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=ph_auto_gen_holiday.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o ph_auto_gen_holiday.o
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  
all: $(BATCHEXE)
