OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=day_end_capture_pdf.exec
BATCHOBJS=$(OBJHOME)/batchcommon.o day_end_capture_pdf.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=   -lObjPtr
all: $(BATCHEXE)
