OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=get_stmt_hdr_row_cnt.exec
BATCHOBJS=$(OBJHOME)/batchcommon.o get_stmt_hdr_row_cnt.o
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=
all: $(BATCHEXE)
