OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=extract_psp_payout.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o extract_psp_payout.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
