OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=merchant_dsp_report.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o merchant_dsp_report.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
