OBJHOME=$(HOME)/obj/BATCH/
#DBOBJHOME=$(HOME)/obj/
BATCHEXE=match_twv_dsp2.exec
#DBOBJS=$(DBOBJHOME)/DepositMismatch.o
BATCHOBJS=$(OBJHOME)/batchcommon.o  match_twv_dsp2.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=   -lObjPtr
all: $(BATCHEXE)
