OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=get_psp_id_list_by_type.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o get_psp_id_list_by_type.o
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  
all: $(BATCHEXE)
