OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=extract_crr_ofl_psp_product_code_map.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o extract_crr_ofl_psp_product_code_map.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
