OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=gen_alert_email_html.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o gen_alert_email_html.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
