OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=send_bal_channel_mq_test.exec
BATCHOBJS=$(OBJHOME)/batchcommon.o send_bal_channel_mq_test.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=   -lObjPtr
all: $(BATCHEXE)
