OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=eod_crr_glpost.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o eod_crr_glpost.o eod_crr_glpost_link.o
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
