OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=gen_merchant_bal_snap.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o gen_merchant_bal_snap.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
