OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=hk_account_ledger_daily_rpt.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o hk_account_ledger_daily_rpt.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
