OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=sim_card_monthly_report.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o sim_card_monthly_report.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
