OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=eod_glpost.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o eod_glpost.o  eod_glutility.o eod_glposttxn.o
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lcurl -lc -lm -lmyhash  -lObjPtr  -lmyrecordset 

all: $(BATCHEXE)
