OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=offline_balance_migration.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o offline_balance_migration.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
