OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=check_deposit_trace_email.exec
BATCHOBJS=$(OBJHOME)/batchcommon.o check_deposit_trace_email.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=   -lObjPtr
all: $(BATCHEXE)
