OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=offline_payout_api_approve.exec
BATCHOBJS=$(OBJHOME)/batchcommon.o offline_payout_api_approve.o
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS += -lexpat -lcurl -lc -lm -lmyhash -lObjPtr -lmyrecordset
all: $(BATCHEXE)
