OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=semi_auto_recon.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o semi_auto_recon.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
