OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=test_str2cols.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o test_str2cols.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lcurl -lc -lm -lmyhash  -lObjPtr  -lmyrecordset -lexpat -lssl

all: $(BATCHEXE)
