OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=hist_baid_bal_collect_by_day.exec
BATCHOBJS=$(OBJHOME)/batchcommon.o hist_baid_bal_collect_by_day.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=   -lObjPtr
all: $(BATCHEXE)
