OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=import_crr_ofl_mi_txn_data.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o import_crr_ofl_mi_txn_data.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
