OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=test_rsa.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o test_rsa.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lcurl -lc -lm -lmyhash  -lObjPtr  -lmyrecordset -lexpat -lssl

all: $(BATCHEXE)
