OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=pr_payout_generate.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o pr_bo_funct.o pr_payout_generate.o
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
