OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=extract_psp_rpt.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o extract_psp_rpt.o  extract_rptcommon.o
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lcurl -lc -lm -lmyhash  -lObjPtr  -lmyrecordset -lexpat

all: $(BATCHEXE)
