OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=gen_deposit_trace_report.exec
BATCHOBJS=$(OBJHOME)/batchcommon.o gen_deposit_trace_report.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=   -lObjPtr
all: $(BATCHEXE)
