#ifndef _PR_PAYOUT_UPLOAD_H
#define _PR_PAYOUT_UPLOAD_H
#include "common.h"

#define PD_MY_DELIMITOR			","
#define PD_MERCH_ACCOUNT_NMB_LEN 	50
#define	NUM_OF_CHAR			26
#define MAX_NUM_OF_RECORD		2000
#define	IMPORT_MAX_FILE			40
#define	IMPORT_FIELD_LEN		50

#define	IDX_HEADER_REF_ID		0
#define	IDX_HEADER_ACCT_NMB		1
#define	IDX_HEADER_FILENAME		3
#define	IDX_HEADER_FILEPREFIX		4
#define	IDX_HEADER_TOTAL_COUNT		5
#define	IDX_HEADER_TOTAL_AMT		6
#define	IDX_HEADER_IMPORT_ERR		7
#define	IDX_HEADER_DATETIME		9
#define	IDX_HEADER_STATUS		12

#define	IDX_DETAIL_REF_ID		1
#define	IDX_DETAIL_TXN_SEQ		2
#define	IDX_DETAIL_AUX_TXN_SEQ		3
#define	IDX_DETAIL_SEQ_NUM		4
#define	IDX_DETAIL_MERCHANT_REF		5
#define IDX_DETAIL_ACCOUNT_NUM		6
#define	IDX_DETAIL_ACCOUNT_NAME		7
#define	IDX_DETAIL_BANK_NAME		8
#define	IDX_DETAIL_BRANCH		9
#define	IDX_DETAIL_PROVINCE		10
#define	IDX_DETAIL_CITY			11
#define	IDX_DETAIL_PAYOUT_AMT		12
#define	IDX_DETAIL_STATUS		13
#define	IDX_DETAIL_REMARK		14
#define	IDX_DETAIL_TIME			16
#define IDX_DETAIL_REQ_AMT		20
#define IDX_DETAIL_REQ_CCY_CD		21
#define IDX_DETAIL_MEMBER_FEE_CCY_ID	22
#define IDX_DETAIL_MEMBER_FEE		23
#define IDX_DETAIL_MERCHANT_FEE_CCY_ID	24
#define IDX_DETAIL_MERCHANT_FEE		25
#define IDX_DETAIL_MARKUP_CCY_ID	26
#define IDX_DETAIL_MARKUP		27
#define IDX_DETAIL_EX_RATE		28
#define IDX_DETAIL_COUNTRY		30
#define IDX_DETAIL_DST_CCY_CD		31
#define IDX_DETAIL_IDENTITY_ID		32
#define IDX_DETAIL_PHONE		33
#define IDX_DETAIL_BANK_CODE		35


#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif


#endif
