ALTER TABLE OL_MERCHANT_BUCKET
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_MERCHANT_BUCKET CASCADE CONSTRAINTS;

CREATE TABLE OL_MERCHANT_BUCKET
(
  OMB_POSTING_DATE      VARCHAR2(8 BYTE),
  OMB_MERCHANT_ID       VARCHAR2(15 BYTE),
  OMB_COUNTRY_ID        CHAR(2 BYTE),
  OMB_CURRENCY_ID       VARCHAR2(3 BYTE),
  OMB_SERVICE_CODE      CHAR(3 BYTE),
  OMB_PSP_ID            VARCHAR2(10 BYTE),
  OMB_BUCKET_TYPE       VARCHAR2(2 BYTE),
  OMB_BAL               NUMBER(14,2),
  OMB_RELEASED_DATE     VARCHAR2(8 BYTE),
  OMB_RELEASED_AMT      NUMBER(14,2),
  OMB_TRANSFER_OUT_BAL	NUMBER(14,2) DEFAULT 0,
  OMB_CREATE_USER       VARCHAR2(20 BYTE),
  OMB_UPDATE_USER       VARCHAR2(20 BYTE),
  OMB_CREATE_TIMESTAMP  DATE,
  OMB_UPDATE_TIMESTAMP  DATE
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN OL_MERCHANT_BUCKET.OMB_BUCKET_TYPE IS 'AF- AFTER PAYOUT FLOAT, RS- RESERVED,SF - SETTLEMET FLOAT';



CREATE INDEX OL_MERCHANT_BUCKET_IDX01 ON OL_MERCHANT_BUCKET
(OMB_SERVICE_CODE, OMB_BUCKET_TYPE, OMB_POSTING_DATE, OMB_RELEASED_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX OL_MERCHANT_BUCKET_PK ON OL_MERCHANT_BUCKET
(OMB_POSTING_DATE, OMB_MERCHANT_ID, OMB_COUNTRY_ID, OMB_CURRENCY_ID, OMB_SERVICE_CODE, 
OMB_PSP_ID, OMB_BUCKET_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_MERCHANT_BUCKET ADD (
  CONSTRAINT OL_MERCHANT_BUCKET_PK
  PRIMARY KEY
  (OMB_POSTING_DATE, OMB_MERCHANT_ID, OMB_COUNTRY_ID, OMB_CURRENCY_ID, OMB_SERVICE_CODE, OMB_PSP_ID, OMB_BUCKET_TYPE)
  USING INDEX OL_MERCHANT_BUCKET_PK
  ENABLE VALIDATE);

ALTER TABLE OL_MERCHANT_BUCKET ADD (
  CONSTRAINT OL_MERCHANT_BUCKET_FK01 
  FOREIGN KEY (OMB_BUCKET_TYPE) 
  REFERENCES DEF_BUCKET_TYPE (B_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OL_MERCHANT_BUCKET_FK02 
  FOREIGN KEY (OMB_MERCHANT_ID) 
  REFERENCES OL_MERCH_DETAIL (MD_MERCHANT_ID)
  ENABLE VALIDATE,
  CONSTRAINT OL_MERCHANT_BUCKET_FK03 
  FOREIGN KEY (OMB_COUNTRY_ID) 
  REFERENCES COUNTRY (COUNTRY_CODE)
  ENABLE VALIDATE,
  CONSTRAINT OL_MERCHANT_BUCKET_FK04 
  FOREIGN KEY (OMB_CURRENCY_ID) 
  REFERENCES DEF_CURRENCY (DC_CCY_ID)
  ENABLE VALIDATE,
  CONSTRAINT OL_MERCHANT_BUCKET_FK05 
  FOREIGN KEY (OMB_SERVICE_CODE) 
  REFERENCES DEF_SERVICE_CODE (SC_CODE)
  ENABLE VALIDATE);

