OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnMgtByUsJLC
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnMgtByUsJLC.so
SOOBJS = TxnMgtByUsJLC.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
