OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOOLAdjustment
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOOLAdjustment.so
SOOBJS = BOOLAdjustment.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
