ALTER TABLE MMS_RULE_AMOUNT
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_RULE_AMOUNT CASCADE CONSTRAINTS;

CREATE TABLE MMS_RULE_AMOUNT
(
  MRA_ID                INTEGER,
  MRA_TYPE              CHAR(1 BYTE),
  MRA_VALUE             NUMBER(12,5),
  MRA_ADD_VALUE         NUMBER(12,2),
  MRA_DESC              VARCHAR2(50 BYTE),
  MRA_DISABLED          INTEGER                  DEFAULT 0,
  MRA_MIN_VALUE         NUMBER(12,2)             DEFAULT 0,
  MRA_MAX_VALUE         NUMBER(12,2)             DEFAULT 0,
  MRA_CREATE_TIMESTAMP  DATE,
  MRA_CREATE_USER       VARCHAR2(20 BYTE),
  MRA_UPDATE_TIMESTAMP  DATE,
  MRA_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MMS_RULE_AMOUNT_PK ON MMS_RULE_AMOUNT
(MRA_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_RULE_AMOUNT ADD (
  CONSTRAINT MMS_RULE_AMOUNT_PK
  PRIMARY KEY
  (MRA_ID)
  USING INDEX MMS_RULE_AMOUNT_PK
  ENABLE VALIDATE);

ALTER TABLE MMS_RULE_AMOUNT ADD (
  CONSTRAINT MMS_RULE_AMOUNT_FK01 
  FOREIGN KEY (MRA_TYPE) 
  REFERENCES DEF_AMOUNT (DA_TYPE)
  ENABLE VALIDATE);

