OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MiEntityBalance
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMiEntityBalance.so
SOOBJS =  MiEntityBalance.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
