ALTER TABLE MI_OL_DEF_DEFAULT_BIT
 DROP PRIMARY KEY CASCADE;

DROP TABLE MI_OL_DEF_DEFAULT_BIT CASCADE CONSTRAINTS;

CREATE TABLE MI_OL_DEF_DEFAULT_BIT
(
  DDB_PSP_ID            VARCHAR2(10 BYTE),
  DDB_DISABLED          INTEGER                 DEFAULT 0,
  DDB_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  DDB_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  DDB_CREATE_USER       VARCHAR2(20 BYTE),
  DDB_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MI_OL_DEF_DEFAULT_BIT_PK ON MI_OL_DEF_DEFAULT_BIT
(DDB_PSP_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MI_OL_DEF_DEFAULT_BIT ADD (
  CONSTRAINT MI_OL_DEF_DEFAULT_BIT_PK
  PRIMARY KEY
  (DDB_PSP_ID)
  USING INDEX MI_OL_DEF_DEFAULT_BIT_PK
  ENABLE VALIDATE);

ALTER TABLE MI_OL_DEF_DEFAULT_BIT ADD (
  CONSTRAINT MI_OL_DEF_DEFAULT_BIT_FK01 
  FOREIGN KEY (DDB_PSP_ID) 
  REFERENCES OL_PSP_DETAIL (OPD_PSP_ID)
  ENABLE VALIDATE);

