OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOAlertEmail
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOAlertEmail.so
SOOBJS = BOAlertEmail.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
