OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/EmlMessages
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBEmlMessages.so
SOOBJS =  EmlMessages.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
