ALTER TABLE OL_DEF_COST_CAL_METHOD
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_DEF_COST_CAL_METHOD CASCADE CONSTRAINTS;

CREATE TABLE OL_DEF_COST_CAL_METHOD
(
  OCCM_TYPE              CHAR(1 BYTE),
  OCCM_DESC              VARCHAR2(50 BYTE),
  OCCM_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  OCCM_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  OCCM_CREATE_USER       VARCHAR2(20 BYTE),
  OCCM_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_DEF_COST_CAL_METHOD_PK ON OL_DEF_COST_CAL_METHOD
(OCCM_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_DEF_COST_CAL_METHOD ADD (
  CONSTRAINT OL_DEF_COST_CAL_METHOD_PK
  PRIMARY KEY
  (OCCM_TYPE)
  USING INDEX OL_DEF_COST_CAL_METHOD_PK
  ENABLE VALIDATE);

