OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnWebOnUsDSP
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnWebOnUsDSP.so
SOOBJS = TxnWebOnUsDSP.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
