ALTER TABLE OL_OTHER_BANK_MAPPING
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_OTHER_BANK_MAPPING CASCADE CONSTRAINTS;

CREATE TABLE OL_OTHER_BANK_MAPPING
(
  OBM_MERCHANT_ID       VARCHAR2(15 BYTE),
  OBM_PRIORITY          INTEGER,
  OBM_INT_BANK_CODE     VARCHAR2(10 BYTE),
  OBM_DISABLED          INTEGER                 DEFAULT 0,
  OBM_CREATE_USER       VARCHAR2(20 BYTE),
  OBM_UPDATE_USER       VARCHAR2(20 BYTE),
  OBM_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  OBM_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX OL_OTHER_BANK_MAPPING_IDX01 ON OL_OTHER_BANK_MAPPING
(OBM_MERCHANT_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX OL_OTHER_BANK_MAPPING_PK ON OL_OTHER_BANK_MAPPING
(OBM_MERCHANT_ID, OBM_PRIORITY, OBM_INT_BANK_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_OTHER_BANK_MAPPING ADD (
  CONSTRAINT OL_OTHER_BANK_MAPPING_PK
  PRIMARY KEY
  (OBM_MERCHANT_ID, OBM_PRIORITY, OBM_INT_BANK_CODE)
  USING INDEX OL_OTHER_BANK_MAPPING_PK
  ENABLE VALIDATE);

