ALTER TABLE DEF_TXN_CODE_MAP
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_TXN_CODE_MAP CASCADE CONSTRAINTS;

CREATE TABLE DEF_TXN_CODE_MAP
(
  TCM_FROM_CODE         CHAR(3 BYTE),
  TCM_TO_CODE           CHAR(3 BYTE),
  TCM_CREATE_USER       VARCHAR2(20 BYTE),
  TCM_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  TCM_UPDATE_USER       VARCHAR2(20 BYTE),
  TCM_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEF_TXN_CODE_MAP_PK ON DEF_TXN_CODE_MAP
(TCM_FROM_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX DEF_TXN_CODE_MAP_UK01 ON DEF_TXN_CODE_MAP
(TCM_FROM_CODE, TCM_TO_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_TXN_CODE_MAP ADD (
  CONSTRAINT DEF_TXN_CODE_MAP_PK
  PRIMARY KEY
  (TCM_FROM_CODE)
  USING INDEX DEF_TXN_CODE_MAP_PK
  ENABLE VALIDATE,
  CONSTRAINT DEF_TXN_CODE_MAP_UK01
  UNIQUE (TCM_FROM_CODE, TCM_TO_CODE)
  USING INDEX DEF_TXN_CODE_MAP_UK01
  ENABLE VALIDATE);

