ALTER TABLE FUNDS_OUT
 DROP PRIMARY KEY CASCADE;

DROP TABLE FUNDS_OUT CASCADE CONSTRAINTS;

CREATE TABLE FUNDS_OUT
(
  FO_ID			   INTEGER,
  FO_FUNDOUT_DATE            VARCHAR2(8 BYTE),
  FO_FUNDOUT_CCY             VARCHAR2(3 BYTE),
  FO_FUNDOUT_AMOUNT          NUMBER(14,2),
  FO_BANK_BAL		     NUMBER(14,2),
  FO_CREATE_USER            VARCHAR2(20 BYTE),
  FO_UPDATE_USER            VARCHAR2(20 BYTE),
  FO_CREATE_TIMESTAMP       DATE                 DEFAULT sysdate,
  FO_UPDATE_TIMESTAMP       DATE
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX FUNDS_OUT_PK ON FUNDS_OUT
(FO_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE FUNDS_OUT ADD (
  CONSTRAINT FUNDS_OUT_PK
  PRIMARY KEY
  (FO_ID)
  USING INDEX FUNDS_OUT_PK);


