ALTER TABLE RULE_PSP_LB_CRITERIA
 DROP PRIMARY KEY CASCADE;

DROP TABLE RULE_PSP_LB_CRITERIA CASCADE CONSTRAINTS;

CREATE TABLE RULE_PSP_LB_CRITERIA
(
  RC_CHANNEL_CODE            CHAR(3 BYTE),
  RC_SERVICE_CODE            CHAR(3 BYTE),
  RC_PAYMENT_METHOD          VARCHAR2(4 BYTE),
  RC_COUNTRY                 CHAR(2 BYTE),
  RC_CCY                     VARCHAR2(3 BYTE),
  RC_SCHEDULER_ID            INTEGER,
  RC_PARTY_TYPE              CHAR(1 BYTE),
  RC_PARTY_ID                VARCHAR2(15 BYTE),
  RC_BUSINESS_TYPE           CHAR(1 BYTE),
  RC_CRITERIA_POOL_ID        INTEGER            NOT NULL,
  RC_CUSTOMER_SEGMENT        VARCHAR2(10 BYTE),
  RC_DISABLED                INTEGER            DEFAULT 0                     NOT NULL,
  RC_CREATE_TIMESTAMP        DATE,
  RC_CREATE_USER             VARCHAR2(20 BYTE),
  RC_UPDATE_TIMESTAMP        DATE,
  RC_UPDATE_USER             VARCHAR2(20 BYTE),
  RC_MIN_TRANSACTION_AMOUNT  NUMBER(14,2)       DEFAULT 0,
  RC_MAX_TRANSACTION_AMOUNT  NUMBER(14,2)       DEFAULT 0,
  RC_PRIORITY                INTEGER            DEFAULT 0
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN RULE_PSP_LB_CRITERIA.RC_CCY IS 'CCY in Request';

COMMENT ON COLUMN RULE_PSP_LB_CRITERIA.RC_PARTY_TYPE IS 'Supported Type ''M'' - Merchant ''C'' - Client and ''G'' Global';



CREATE INDEX RULE_PSP_LB_CRITERIA_IDX01 ON RULE_PSP_LB_CRITERIA
(RC_CHANNEL_CODE, RC_SERVICE_CODE, RC_PAYMENT_METHOD, RC_COUNTRY, RC_CCY, 
RC_PARTY_TYPE, RC_PARTY_ID, RC_BUSINESS_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX RULE_PSP_LB_CRITERIA_IDX02 ON RULE_PSP_LB_CRITERIA
(RC_CHANNEL_CODE, RC_SERVICE_CODE, RC_PAYMENT_METHOD, RC_COUNTRY, RC_CCY, 
RC_PARTY_TYPE, RC_BUSINESS_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RULE_PSP_LB_CRITERIA_PK ON RULE_PSP_LB_CRITERIA
(RC_CHANNEL_CODE, RC_SERVICE_CODE, RC_PAYMENT_METHOD, RC_COUNTRY, RC_CCY, 
RC_SCHEDULER_ID, RC_PARTY_TYPE, RC_PARTY_ID, RC_BUSINESS_TYPE, RC_CRITERIA_POOL_ID, 
RC_MIN_TRANSACTION_AMOUNT)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE RULE_PSP_LB_CRITERIA ADD (
  CONSTRAINT RULE_PSP_LB_CRITERIA_PK
  PRIMARY KEY
  (RC_CHANNEL_CODE, RC_SERVICE_CODE, RC_PAYMENT_METHOD, RC_COUNTRY, RC_CCY, RC_SCHEDULER_ID, RC_PARTY_TYPE, RC_PARTY_ID, RC_BUSINESS_TYPE, RC_CRITERIA_POOL_ID, RC_MIN_TRANSACTION_AMOUNT)
  USING INDEX RULE_PSP_LB_CRITERIA_PK
  ENABLE VALIDATE);

ALTER TABLE RULE_PSP_LB_CRITERIA ADD (
  CONSTRAINT RULE_PSP_LB_CRITERIA_F02 
  FOREIGN KEY (RC_SERVICE_CODE) 
  REFERENCES DEF_SERVICE_CODE (SC_CODE)
  ENABLE VALIDATE,
  CONSTRAINT RULE_PSP_LB_CRITERIA_F03 
  FOREIGN KEY (RC_PAYMENT_METHOD) 
  REFERENCES DEF_PAY_METHOD (DP_CODE)
  ENABLE VALIDATE,
  CONSTRAINT RULE_PSP_LB_CRITERIA_FK01 
  FOREIGN KEY (RC_CHANNEL_CODE) 
  REFERENCES DEF_CHANNEL (DC_CODE)
  ENABLE VALIDATE,
  CONSTRAINT RULE_PSP_LB_CRITERIA_FK04 
  FOREIGN KEY (RC_COUNTRY) 
  REFERENCES COUNTRY (COUNTRY_CODE)
  ENABLE VALIDATE,
  CONSTRAINT RULE_PSP_LB_CRITERIA_FK05 
  FOREIGN KEY (RC_CCY) 
  REFERENCES DEF_CURRENCY (DC_CCY_ID)
  ENABLE VALIDATE,
  CONSTRAINT RULE_PSP_LB_CRITERIA_FK08 
  FOREIGN KEY (RC_BUSINESS_TYPE) 
  REFERENCES DEF_BUSINESS_TYPE (BT_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT RULE_PSP_LB_CRITERIA_FK09 
  FOREIGN KEY (RC_SCHEDULER_ID) 
  REFERENCES RULE_SCHEDULER_HEADER (RS_SCHEDULER_ID)
  ENABLE VALIDATE,
  CONSTRAINT RULE_PSP_LB_CRITERIA_R07 
  FOREIGN KEY (RC_PARTY_TYPE) 
  REFERENCES DEF_PARTY_TYPE (DP_TYPE)
  ENABLE VALIDATE);

