OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOMMSEntityOPB
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOMMSEntityOPB.so
SOOBJS = BOMMSEntityOPB.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
