OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/PayoutGeneratedFileHD
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBPayoutGeneratedFileHD.so
SOOBJS =  PayoutGeneratedFileHD.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
