OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLPspDetail
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLPspDetail.so
SOOBJS =  OLPspDetail.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
