OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/ParCategory
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBParCategory.so
SOOBJS =  ParCategory.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
