OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MerchUrl
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMerchUrl.so
SOOBJS =  MerchUrl.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
