ALTER TABLE MERCHANT_APPROVE_QUEUE_DT
 DROP PRIMARY KEY CASCADE;

DROP TABLE MERCHANT_APPROVE_QUEUE_DT CASCADE CONSTRAINTS;

CREATE TABLE MERCHANT_APPROVE_QUEUE_DT
(
  QD_APPROVE_ID        INTEGER,
  QD_BATCH_ID	       INTEGER,
  QD_SEQ_NUM	       INTEGER,
  QD_STATUS            CHAR(1 BYTE),
  QD_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  QD_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  QD_CREATE_USER       VARCHAR2(20 BYTE),
  QD_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MERCHANT_APPROVE_QUEUE_DT_PK ON MERCHANT_APPROVE_QUEUE_DT
(QD_APPROVE_ID, QD_BATCH_ID, QD_SEQ_NUM)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MERCHANT_APPROVE_QUEUE_DT ADD (
  CONSTRAINT MERCHANT_APPROVE_QUEUE_DT_PK
  PRIMARY KEY
  (QD_APPROVE_ID, QD_BATCH_ID, QD_SEQ_NUM)
  USING INDEX MERCHANT_APPROVE_QUEUE_DT_PK
  ENABLE VALIDATE);

