OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/RulePspLbPools
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBRulePspLbPools.so
SOOBJS =  RulePspLbPools.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
