OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnMgtByUsVPO
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnMgtByUsVPO.so
SOOBJS = TxnMgtByUsVPO.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
