OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/TxnElements
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBTxnElements.so
SOOBJS =  TxnElements.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
