OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/ServicePayMethod
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBServicePayMethod.so
SOOBJS =  ServicePayMethod.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
