OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/TxnBeUrl
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBTxnBeUrl.so
SOOBJS =  TxnBeUrl.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
