OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLPayoutGrpList
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLPayoutGrpList.so
SOOBJS =  OLPayoutGrpList.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
