ALTER TABLE MMC_TXN_HEADER
DROP PRIMARY KEY CASCADE;

DROP TABLE MMC_TXN_HEADER CASCADE CONSTRAINTS;

CREATE TABLE MMC_TXN_HEADER
(
  MCH_TXN_ID                 VARCHAR2(16 BYTE),
  MCH_ORG_TXN_ID             VARCHAR2(16 BYTE),
  MCH_SERVER_REF             VARCHAR2(16 BYTE),
  MCH_STATUS                 CHAR(1 BYTE),
  MCH_AR_IND                 CHAR(1 BYTE),
  MCH_INTERNAL_CODE          NUMBER(8),
  MCH_RESPONSE_CODE          VARCHAR2(6 BYTE),
  MCH_TXN_CODE               VARCHAR2(3 BYTE),
  MCH_PROCESS_TYPE           VARCHAR2(4 BYTE),
  MCH_PROCESS_CODE           VARCHAR2(6 BYTE),
  MCH_HOST_POSTING_DATE      VARCHAR2(8 BYTE),
  MCH_TM_DATE                VARCHAR2(8 BYTE),
  MCH_TM_TIME                VARCHAR2(6 BYTE),
  MCH_LOCAL_TM_DATE          VARCHAR2(8 BYTE),
  MCH_LOCAL_TM_TIME          VARCHAR2(6 BYTE),
  MCH_TRANSMISSION_DATETIME  VARCHAR2(14 BYTE),
  MCH_TRANSACTION_AMOUNT     NUMBER(12,2),
  MCH_TRANSACTION_CCY        CHAR(3 BYTE),
  MCH_CREATE_USER            VARCHAR2(20 BYTE),
  MCH_CREATE_TIMESTAMP       DATE,
  MCH_UPDATE_USER            VARCHAR2(20 BYTE),
  MCH_UPDATE_TIMESTAMP       DATE
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MMC_TXN_HEADER_PK ON MMC_TXN_HEADER
(MCH_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMC_TXN_HEADER ADD (
  CONSTRAINT MMC_TXN_HEADER_PK
  PRIMARY KEY
  (MCH_TXN_ID)
  USING INDEX MMC_TXN_HEADER_PK
  ENABLE VALIDATE);

