ALTER TABLE DEF_EX_MARKUP
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_EX_MARKUP CASCADE CONSTRAINTS;

CREATE TABLE DEF_EX_MARKUP
(
  DE_TYPE              CHAR(1 BYTE),
  DE_DESC              VARCHAR2(50 BYTE),
  DE_CREATE_TIMESTAMP  DATE,
  DE_UPDATE_TIMESTAMP  DATE,
  DE_CREATE_USER       VARCHAR2(20 BYTE),
  DE_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEF_EX_MARKUP_PK ON DEF_EX_MARKUP
(DE_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_EX_MARKUP ADD (
  CONSTRAINT DEF_EX_MARKUP_PK
  PRIMARY KEY
  (DE_TYPE)
  USING INDEX DEF_EX_MARKUP_PK);

