OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmsEntitySupport
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmsEntitySupport.so
SOOBJS =  MmsEntitySupport.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
