OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnOmtByUsOSV
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnOmtByUsOSV.so
SOOBJS = TxnOmtByUsOSV.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
