ALTER TABLE OL_STMT_MATCH_ENGINE
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_STMT_MATCH_ENGINE CASCADE CONSTRAINTS;

CREATE TABLE OL_STMT_MATCH_ENGINE
(
  OSME_TRIGGER_TYPE         VARCHAR2(10 BYTE),
  OSME_INPUT_CHANNEL        VARCHAR2(3 BYTE),
  OSME_BANK_ACCT_TYPE       CHAR(3 BYTE),
  OSME_BAID_TXN_CODE        CHAR(3 BYTE),
  OSME_RULE_ID              INTEGER,
  OSME_NEXT_ENGINE_TXN_CODE VARCHAR2(3 BYTE),
  OSME_NEXT_ENGINE_ACTION   VARCHAR2(20 BYTE),
  OSME_FAILED_BAID_TXN_CODE CHAR(3 BYTE),
  OSME_DISABLED             INTEGER             DEFAULT 0,
  OSME_CREATE_TIMESTAMP     DATE                DEFAULT sysdate,
  OSME_CREATE_USER          VARCHAR2(20 BYTE),
  OSME_UPDATE_TIMESTAMP     DATE                DEFAULT sysdate,
  OSME_UPDATE_USER          VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_STMT_MATCH_ENGINE_PK ON OL_STMT_MATCH_ENGINE
(OSME_TRIGGER_TYPE, OSME_INPUT_CHANNEL, OSME_BANK_ACCT_TYPE, OSME_BAID_TXN_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_STMT_MATCH_ENGINE ADD (
  CONSTRAINT OL_STMT_MATCH_ENGINE_PK
  PRIMARY KEY
  (OSME_TRIGGER_TYPE, OSME_INPUT_CHANNEL, OSME_BANK_ACCT_TYPE, OSME_BAID_TXN_CODE)
  USING INDEX OL_STMT_MATCH_ENGINE_PK
  ENABLE VALIDATE);

ALTER TABLE OL_STMT_MATCH_ENGINE ADD (
  CONSTRAINT OL_STMT_MATCH_ENGINE_FK01 
  FOREIGN KEY (OSME_BANK_ACCT_TYPE) 
  REFERENCES OL_DEF_BANK_ACCT_TYPE (OBC_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OL_STMT_MATCH_ENGINE_FK02 
  FOREIGN KEY (OSME_BAID_TXN_CODE) 
  REFERENCES OL_BAID_TXN_CODE (OBTC_CODE)
  ENABLE VALIDATE,
  CONSTRAINT OL_STMT_MATCH_ENGINE_FK03 
  FOREIGN KEY (OSME_TRIGGER_TYPE) 
  REFERENCES OL_DEF_ENGINE_TRIGGER_TYPE (ETT_TYPE)
  ENABLE VALIDATE);

