Insert into OL_STMT_MATCH_ENGINE
   (OSME_TRIGGER_TYPE, OSME_BANK_ACCT_TYPE, OSME_BAID_TXN_CODE, OSME_RULE_ID, OSME_NEXT_ENGINE_ACTION, 
    OSME_DISABLED, OSME_CREATE_TIMESTAMP, OSME_CREATE_USER, OSME_UPDATE_TIMESTAMP, OSME_UPDATE_USER)
 Values
   ('system', 'POA', 'CGB', 1, 'classify', 
    0, sysdate, 'SYSTEM', sysdate, 'SYSTEM');
Insert into OL_STMT_MATCH_ENGINE
   (OSME_TRIGGER_TYPE, OSME_BANK_ACCT_TYPE, OSME_BAID_TXN_CODE, OSME_RULE_ID, OSME_NEXT_ENGINE_ACTION, 
    OSME_DISABLED, OSME_CREATE_TIMESTAMP, OSME_CREATE_USER, OSME_UPDATE_TIMESTAMP, OSME_UPDATE_USER)
 Values
   ('system', 'POA', 'OBI', 2, 'classify', 
    0, sysdate, 'SYSTEM', sysdate, 'SYSTEM');
Insert into OL_STMT_MATCH_ENGINE
   (OSME_TRIGGER_TYPE, OSME_BANK_ACCT_TYPE, OSME_BAID_TXN_CODE, OSME_RULE_ID, OSME_NEXT_ENGINE_ACTION, 
    OSME_DISABLED, OSME_CREATE_TIMESTAMP, OSME_CREATE_USER, OSME_UPDATE_TIMESTAMP, OSME_UPDATE_USER)
 Values
   ('system', 'POA', 'OBP', 3, 'classify', 
    0, sysdate, 'SYSTEM', sysdate, 'SYSTEM');
Insert into OL_STMT_MATCH_ENGINE
   (OSME_TRIGGER_TYPE, OSME_BANK_ACCT_TYPE, OSME_BAID_TXN_CODE, OSME_RULE_ID, OSME_NEXT_ENGINE_ACTION, 
    OSME_DISABLED, OSME_CREATE_TIMESTAMP, OSME_CREATE_USER, OSME_UPDATE_TIMESTAMP, OSME_UPDATE_USER)
 Values
   ('system', 'POA', 'SNP', 4, 'classify', 
    0, sysdate, 'SYSTEM', sysdate, 'SYSTEM');
Insert into OL_STMT_MATCH_ENGINE
   (OSME_TRIGGER_TYPE, OSME_BANK_ACCT_TYPE, OSME_BAID_TXN_CODE, OSME_RULE_ID, OSME_NEXT_ENGINE_ACTION, 
    OSME_DISABLED, OSME_CREATE_TIMESTAMP, OSME_CREATE_USER, OSME_UPDATE_TIMESTAMP, OSME_UPDATE_USER)
 Values
   ('system', 'POA', 'VUP', 5, 'classify', 
    0, sysdate, 'SYSTEM', sysdate, 'SYSTEM');
Insert into OL_STMT_MATCH_ENGINE
   (OSME_TRIGGER_TYPE, OSME_BANK_ACCT_TYPE, OSME_BAID_TXN_CODE, OSME_RULE_ID, OSME_NEXT_ENGINE_ACTION, 
    OSME_DISABLED, OSME_CREATE_TIMESTAMP, OSME_CREATE_USER, OSME_UPDATE_TIMESTAMP, OSME_UPDATE_USER)
 Values
   ('system', 'POA', 'SUP', 6, 'classify', 
    0, sysdate, 'SYSTEM', sysdate, 'SYSTEM');
Insert into OL_STMT_MATCH_ENGINE
   (OSME_TRIGGER_TYPE, OSME_BANK_ACCT_TYPE, OSME_BAID_TXN_CODE, OSME_RULE_ID, OSME_NEXT_ENGINE_ACTION, 
    OSME_DISABLED, OSME_CREATE_TIMESTAMP, OSME_CREATE_USER, OSME_UPDATE_TIMESTAMP, OSME_UPDATE_USER)
 Values
   ('system', 'ITM', 'CGB', 1, 'classify', 
    0, sysdate, 'SYSTEM', sysdate, 'SYSTEM');
Insert into OL_STMT_MATCH_ENGINE
   (OSME_TRIGGER_TYPE, OSME_BANK_ACCT_TYPE, OSME_BAID_TXN_CODE, OSME_RULE_ID, OSME_NEXT_ENGINE_ACTION, 
    OSME_DISABLED, OSME_CREATE_TIMESTAMP, OSME_CREATE_USER, OSME_UPDATE_TIMESTAMP, OSME_UPDATE_USER)
 Values
   ('system', 'ITM', 'OBI', 2, 'classify', 
    0, sysdate, 'SYSTEM', sysdate, 'SYSTEM');
Insert into OL_STMT_MATCH_ENGINE
   (OSME_TRIGGER_TYPE, OSME_BANK_ACCT_TYPE, OSME_BAID_TXN_CODE, OSME_RULE_ID, OSME_NEXT_ENGINE_ACTION, 
    OSME_DISABLED, OSME_CREATE_TIMESTAMP, OSME_CREATE_USER, OSME_UPDATE_TIMESTAMP, OSME_UPDATE_USER)
 Values
   ('system', 'ITM', 'VUI', 7, 'classify', 
    0, sysdate, 'SYSTEM', sysdate, 'SYSTEM');
Insert into OL_STMT_MATCH_ENGINE
   (OSME_TRIGGER_TYPE, OSME_BANK_ACCT_TYPE, OSME_BAID_TXN_CODE, OSME_RULE_ID, OSME_NEXT_ENGINE_ACTION, 
    OSME_DISABLED, OSME_CREATE_TIMESTAMP, OSME_CREATE_USER, OSME_UPDATE_TIMESTAMP, OSME_UPDATE_USER)
 Values
   ('system', 'ITM', 'SUI', 8, 'classify', 
    0, sysdate, 'SYSTEM', sysdate, 'SYSTEM');
Insert into OL_STMT_MATCH_ENGINE
   (OSME_TRIGGER_TYPE, OSME_BANK_ACCT_TYPE, OSME_BAID_TXN_CODE, OSME_RULE_ID, OSME_NEXT_ENGINE_ACTION, 
    OSME_DISABLED, OSME_CREATE_TIMESTAMP, OSME_CREATE_USER, OSME_UPDATE_TIMESTAMP, OSME_UPDATE_USER)
 Values
   ('system', 'ITM', 'SNI', 9, 'classify', 
    0, sysdate, 'SYSTEM', sysdate, 'SYSTEM');
Insert into OL_STMT_MATCH_ENGINE
   (OSME_TRIGGER_TYPE, OSME_BANK_ACCT_TYPE, OSME_BAID_TXN_CODE, OSME_RULE_ID, OSME_NEXT_ENGINE_ACTION, 
    OSME_DISABLED, OSME_CREATE_TIMESTAMP, OSME_CREATE_USER, OSME_UPDATE_TIMESTAMP, OSME_UPDATE_USER)
 Values
   ('system', 'PDF', 'SNF', 10, 'classify', 
    0, sysdate, 'SYSTEM', sysdate, 'SYSTEM');
Insert into OL_STMT_MATCH_ENGINE
   (OSME_TRIGGER_TYPE, OSME_BANK_ACCT_TYPE, OSME_BAID_TXN_CODE, OSME_RULE_ID, OSME_NEXT_ENGINE_ACTION, 
    OSME_DISABLED, OSME_CREATE_TIMESTAMP, OSME_CREATE_USER, OSME_UPDATE_TIMESTAMP, OSME_UPDATE_USER)
 Values
   ('system', 'PDF', 'SUF', 11, 'classify', 
    0, sysdate, 'SYSTEM', sysdate, 'SYSTEM');
Insert into OL_STMT_MATCH_ENGINE
   (OSME_TRIGGER_TYPE, OSME_BANK_ACCT_TYPE, OSME_BAID_TXN_CODE, OSME_RULE_ID, OSME_NEXT_ENGINE_ACTION, 
    OSME_DISABLED, OSME_CREATE_TIMESTAMP, OSME_CREATE_USER, OSME_UPDATE_TIMESTAMP, OSME_UPDATE_USER)
 Values
   ('system', 'DSI', 'OTC', 12, 'classify', 
    0, sysdate, 'SYSTEM', sysdate, 'SYSTEM');
Insert into OL_STMT_MATCH_ENGINE
   (OSME_TRIGGER_TYPE, OSME_BANK_ACCT_TYPE, OSME_BAID_TXN_CODE, OSME_RULE_ID, OSME_NEXT_ENGINE_ACTION, 
    OSME_DISABLED, OSME_CREATE_TIMESTAMP, OSME_CREATE_USER, OSME_UPDATE_TIMESTAMP, OSME_UPDATE_USER)
 Values
   ('system', 'DSI', 'OTD', 13, 'classify', 
    0, sysdate, 'SYSTEM', sysdate, 'SYSTEM');
Insert into OL_STMT_MATCH_ENGINE
   (OSME_TRIGGER_TYPE, OSME_BANK_ACCT_TYPE, OSME_BAID_TXN_CODE, OSME_RULE_ID, OSME_NEXT_ENGINE_ACTION, 
    OSME_DISABLED, OSME_CREATE_TIMESTAMP, OSME_CREATE_USER, OSME_UPDATE_TIMESTAMP, OSME_UPDATE_USER)
 Values
   ('system', 'DSI', 'CGB', 1, 'classify', 
    0, sysdate, 'SYSTEM', sysdate, 'SYSTEM');
Insert into OL_STMT_MATCH_ENGINE
   (OSME_TRIGGER_TYPE, OSME_BANK_ACCT_TYPE, OSME_BAID_TXN_CODE, OSME_RULE_ID, OSME_NEXT_ENGINE_ACTION, 
    OSME_DISABLED, OSME_CREATE_TIMESTAMP, OSME_CREATE_USER, OSME_UPDATE_TIMESTAMP, OSME_UPDATE_USER)
 Values
   ('system', 'DSI', 'OBI', 2, 'classify', 
    0, sysdate, 'SYSTEM', sysdate, 'SYSTEM');
Insert into OL_STMT_MATCH_ENGINE
   (OSME_TRIGGER_TYPE, OSME_BANK_ACCT_TYPE, OSME_BAID_TXN_CODE, OSME_RULE_ID, OSME_NEXT_ENGINE_ACTION, 
    OSME_DISABLED, OSME_CREATE_TIMESTAMP, OSME_CREATE_USER, OSME_UPDATE_TIMESTAMP, OSME_UPDATE_USER)
 Values
   ('system', 'DSI', 'VOD', 14, 'classify', 
    0, sysdate, 'SYSTEM', sysdate, 'SYSTEM');
Insert into OL_STMT_MATCH_ENGINE
   (OSME_TRIGGER_TYPE, OSME_BANK_ACCT_TYPE, OSME_BAID_TXN_CODE, OSME_RULE_ID, OSME_NEXT_ENGINE_ACTION, 
    OSME_DISABLED, OSME_CREATE_TIMESTAMP, OSME_CREATE_USER, OSME_UPDATE_TIMESTAMP, OSME_UPDATE_USER)
 Values
   ('system', 'DSI', 'CSW', 15, 'classify', 
    0, sysdate, 'SYSTEM', sysdate, 'SYSTEM');
Insert into OL_STMT_MATCH_ENGINE
   (OSME_TRIGGER_TYPE, OSME_BANK_ACCT_TYPE, OSME_BAID_TXN_CODE, OSME_RULE_ID, OSME_NEXT_ENGINE_ACTION, 
    OSME_DISABLED, OSME_CREATE_TIMESTAMP, OSME_CREATE_USER, OSME_UPDATE_TIMESTAMP, OSME_UPDATE_USER)
 Values
   ('system', 'DSI', 'VUD', 16, 'classify', 
    0, sysdate, 'SYSTEM', sysdate, 'SYSTEM');
Insert into OL_STMT_MATCH_ENGINE
   (OSME_TRIGGER_TYPE, OSME_BANK_ACCT_TYPE, OSME_BAID_TXN_CODE, OSME_RULE_ID, OSME_NEXT_ENGINE_ACTION, 
    OSME_DISABLED, OSME_CREATE_TIMESTAMP, OSME_CREATE_USER, OSME_UPDATE_TIMESTAMP, OSME_UPDATE_USER)
 Values
   ('system', 'DSI', 'SUD', 17, 'classify', 
    0, sysdate, 'SYSTEM', sysdate, 'SYSTEM');
Insert into OL_STMT_MATCH_ENGINE
   (OSME_TRIGGER_TYPE, OSME_BANK_ACCT_TYPE, OSME_BAID_TXN_CODE, OSME_RULE_ID, OSME_NEXT_ENGINE_ACTION, 
    OSME_DISABLED, OSME_CREATE_TIMESTAMP, OSME_CREATE_USER, OSME_UPDATE_TIMESTAMP, OSME_UPDATE_USER)
 Values
   ('system', 'DSI', 'OBD', 18, 'classify', 
    0, sysdate, 'SYSTEM', sysdate, 'SYSTEM');

