ALTER TABLE MI_PROCESSING_COST
 DROP PRIMARY KEY CASCADE;

DROP TABLE MI_PROCESSING_COST CASCADE CONSTRAINTS;

CREATE TABLE MI_PROCESSING_COST
(
  PC_ENTITY_TYPE       CHAR(3 BYTE)             NOT NULL,
  PC_COST_RATE         NUMBER(12,5)             NOT NULL,
  PC_DISABLED          INTEGER                  DEFAULT 0,
  PC_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  PC_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  PC_CREATE_USER       VARCHAR2(20 BYTE),
  PC_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MI_PROCESSING_COST_PK ON MI_PROCESSING_COST
(PC_ENTITY_TYPE, PC_COST_RATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MI_PROCESSING_COST ADD (
  CONSTRAINT MI_PROCESSING_COST_PK
  PRIMARY KEY
  (PC_ENTITY_TYPE, PC_COST_RATE)
  USING INDEX MI_PROCESSING_COST_PK
  ENABLE VALIDATE);

ALTER TABLE MI_PROCESSING_COST ADD (
  CONSTRAINT MI_PROCESSING_COST_FK01 
  FOREIGN KEY (PC_ENTITY_TYPE) 
  REFERENCES MI_DEF_ENTITY_TYPE (ET_TYPE_CODE)
  ENABLE VALIDATE);

