OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmsAdjustmentTypeEntity
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmsAdjustmentTypeEntity.so
SOOBJS =  MmsAdjustmentTypeEntity.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
