ALTER TABLE MMS_ENTITY_BAL_ACCT
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_ENTITY_BAL_ACCT CASCADE CONSTRAINTS;

CREATE TABLE MMS_ENTITY_BAL_ACCT
(
  MBA_ENTITY_ID         VARCHAR2(20 BYTE),
  MBA_CCY               VARCHAR2(3 BYTE),
  MBA_STATUS_REF        VARCHAR(2 BYTE),
  MBA_IS_USER_EDITABLE  INTEGER                 DEFAULT 0,
  MBA_DISABLED          INTEGER                 DEFAULT 0,
  MBA_CREATE_TIMESTAMP  DATE,
  MBA_CREATE_USER       VARCHAR2(20 BYTE),
  MBA_UPDATE_TIMESTAMP  DATE,
  MBA_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MMS_ENTITY_BAL_ACCT_PK ON MMS_ENTITY_BAL_ACCT
(MBA_ENTITY_ID, MBA_CCY)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_ENTITY_BAL_ACCT ADD (
  CONSTRAINT MMS_ENTITY_BAL_ACCT_PK
  PRIMARY KEY
  (MBA_ENTITY_ID, MBA_CCY)
  USING INDEX MMS_ENTITY_BAL_ACCT_PK
  ENABLE VALIDATE);

ALTER TABLE MMS_ENTITY_BAL_ACCT ADD (
  CONSTRAINT MMS_ENTITY_BAL_ACCT_FK01 
  FOREIGN KEY (MBA_ENTITY_ID) 
  REFERENCES MMS_ENTITY (ME_ID)
  ENABLE VALIDATE);

