ALTER TABLE OL_SMS_TXN_LOG
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_SMS_TXN_LOG CASCADE CONSTRAINTS;

CREATE TABLE OL_SMS_TXN_LOG
(
  OST_TXN_ID             VARCHAR2(16 BYTE),
  OST_SENDER             VARCHAR2(20 BYTE),
  OST_TEXT               VARCHAR2(200 BYTE),
  OST_SCTS               VARCHAR2(20 BYTE),
  OST_TAG                VARCHAR2(20 BYTE),
  OST_HAS_MISSING_PARTS  VARCHAR2(5 BYTE),
  OST_SMSC               VARCHAR2(20 BYTE),
  OST_REF_NUM            VARCHAR2(50 BYTE),
  OST_SENDER_NUM_TYPE    VARCHAR2(10 BYTE),
  OST_SEQ_NUM            VARCHAR2(5 BYTE),
  OST_TOTAL              VARCHAR2(5 BYTE),
  OST_REQ_BANK_ACC       VARCHAR2(50 BYTE),
  OST_REQ_BANK_YEAR      VARCHAR2(4 BYTE),
  OST_REQ_BANK_MONTH     VARCHAR2(2 BYTE),
  OST_REQ_BANK_DAY       VARCHAR2(2 BYTE),
  OST_REQ_BANK_TIME      VARCHAR2(10 BYTE),
  OST_REQ_BANK_AMOUNT    NUMBER(12,2)		DEFAULT 0,
  OST_REQ_PAYEE          VARCHAR2(10 BYTE),
  OST_REQ_PAYER          VARCHAR2(10 BYTE),
  OST_REQ_PAYER_ACC      VARCHAR2(50 BYTE),
  OST_REQ_BANK_BAL       NUMBER(14,2)		DEFAULT 0,
  OST_REQ_BANK_NAME      VARCHAR2(20 BYTE),
  OST_REQ_BANK_CHANNEL   VARCHAR2(50 BYTE),
  OST_REQ_STATUS         VARCHAR2(20 BYTE),
  OST_REQ_IP             VARCHAR2(25 BYTE),
  OST_CREATE_TIMESTAMP   DATE                   DEFAULT sysdate,
  OST_CREATE_USER        VARCHAR2(20 BYTE),
  OST_UPDATE_TIMESTAMP   DATE                   DEFAULT sysdate,
  OST_UPDATE_USER        VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_SMS_TXN_LOG_PK ON OL_SMS_TXN_LOG
(OST_TXN_ID)
LOGGING
TABLESPACE USER_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_SMS_TXN_LOG ADD (
  CONSTRAINT OL_SMS_TXN_LOG_PK
  PRIMARY KEY
  (OST_TXN_ID)
  USING INDEX OL_SMS_TXN_LOG_PK
  ENABLE VALIDATE);

