OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/TestBatchjobTime
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBTestBatchjobTime.so
SOOBJS = TestBatchjobTime.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
