ALTER TABLE TMP_FROZEN_TXN_ALERT
 DROP PRIMARY KEY CASCADE;

DROP TABLE TMP_FROZEN_TXN_ALERT CASCADE CONSTRAINTS;

CREATE TABLE TMP_FROZEN_TXN_ALERT
(
  TFA_TXN_ID            VARCHAR2(16 BYTE),
  TFA_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX TMP_FROZEN_TXN_ALERT_PK ON TMP_FROZEN_TXN_ALERT
(TFA_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE TMP_FROZEN_TXN_ALERT ADD (
  CONSTRAINT TMP_FROZEN_TXN_ALERT_PK
  PRIMARY KEY
  (TFA_TXN_ID)
  USING INDEX TMP_FROZEN_TXN_ALERT_PK
  ENABLE VALIDATE);

