ALTER TABLE OL_TXN_RELATION_SPC
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_TXN_RELATION_SPC CASCADE CONSTRAINTS;

CREATE TABLE OL_TXN_RELATION_SPC
(
  OTRS_PARTY_TYPE          CHAR(1 BYTE),
  OTRS_P1_TXN_ID           VARCHAR2(16 BYTE),
  OTRS_P2_TXN_ID           VARCHAR2(16 BYTE),
  OTRS_TXN_LEVEL           CHAR(1 BYTE),
  OTRS_RELATION_TYPE       CHAR(1 BYTE),
  OTRS_CREATE_TIMESTAMP    DATE                  DEFAULT sysdate,
  OTRS_UPDATE_TIMESTAMP    DATE                  DEFAULT sysdate,
  OTRS_CREATE_USER         VARCHAR2(20 BYTE),
  OTRS_UPDATE_USER         VARCHAR2(20 BYTE),
  OTRS_RELATION_TIMESTAMP  TIMESTAMP(6)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX OL_TXN_RELATION_SPC_IDX01 ON OL_TXN_RELATION_SPC
(OTRS_PARTY_TYPE, OTRS_TXN_LEVEL, OTRS_RELATION_TYPE, OTRS_P1_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX OL_TXN_RELATION_SPC_IDX02 ON OL_TXN_RELATION_SPC
(OTRS_PARTY_TYPE, OTRS_TXN_LEVEL, OTRS_RELATION_TYPE, OTRS_P2_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX OL_TXN_RELATION_SPC_PK ON OL_TXN_RELATION_SPC
(OTRS_PARTY_TYPE, OTRS_P1_TXN_ID, OTRS_P2_TXN_ID, OTRS_TXN_LEVEL, OTRS_RELATION_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_TXN_RELATION_SPC ADD (
  CONSTRAINT OL_TXN_RELATION_SPC_PK
  PRIMARY KEY
  (OTRS_PARTY_TYPE, OTRS_P1_TXN_ID, OTRS_P2_TXN_ID, OTRS_TXN_LEVEL, OTRS_RELATION_TYPE)
  USING INDEX OL_TXN_RELATION_SPC_PK
  ENABLE VALIDATE);

ALTER TABLE OL_TXN_RELATION_SPC ADD (
  CONSTRAINT OL_TXN_RELATION_SPC_FK01 
  FOREIGN KEY (OTRS_PARTY_TYPE) 
  REFERENCES DEF_PARTY_TYPE (DP_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OL_TXN_RELATION_SPC_FK02 
  FOREIGN KEY (OTRS_TXN_LEVEL) 
  REFERENCES OL_DEF_TXN_LEVEL (OTL_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OL_TXN_RELATION_SPC_FK03 
  FOREIGN KEY (OTRS_RELATION_TYPE) 
  REFERENCES OL_DEF_RELATION_TYPE (ORT_TYPE)
  ENABLE VALIDATE);

