ALTER TABLE MMS_TXN_ELEMENT
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_TXN_ELEMENT CASCADE CONSTRAINTS;

CREATE TABLE MMS_TXN_ELEMENT
(
	MTE_TXN_ID            VARCHAR2(16 BYTE),
  	MTE_ENTITY_ID  	      VARCHAR(20 BYTE),
  	MTE_TXN_ELEMENT_TYPE  CHAR(4 BYTE),
  	MTE_EXEC_SEQ          INTEGER,
  	MTE_AMOUNT            NUMBER(12,2),
  	MTE_CCY               CHAR(3 BYTE),
  	MTE_AMT_TYPE          CHAR(2 BYTE),
  	MTE_CREATE_TIMESTAMP  DATE,
  	MTE_CREATE_USER       VARCHAR2(20 BYTE),
  	MTE_UPDATE_TIMESTAMP  DATE,
  	MTE_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX MMS_TXN_ELEMENT_IDX01 ON MMS_TXN_ELEMENT
(MTE_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX MMS_TXN_ELEMENT_PK ON MMS_TXN_ELEMENT
(MTE_TXN_ID, MTE_ENTITY_ID, MTE_TXN_ELEMENT_TYPE)
LOGGING
TABLESPACE USER_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_TXN_ELEMENT ADD (
  CONSTRAINT MMS_TXN_ELEMENT_PK
  PRIMARY KEY
  (MTE_TXN_ID, MTE_ENTITY_ID, MTE_TXN_ELEMENT_TYPE)
  USING INDEX MMS_TXN_ELEMENT_PK
  ENABLE VALIDATE);

ALTER TABLE MMS_TXN_ELEMENT ADD (
  CONSTRAINT MMS_TXN_ELEMENT_FK01 
  FOREIGN KEY (MTE_TXN_ID) 
  REFERENCES MMS_TXN_HEADER (MTH_TXN_ID)
  ENABLE VALIDATE);

