ALTER TABLE MMS_TXN_ELEMENT_DETAIL
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_TXN_ELEMENT_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE MMS_TXN_ELEMENT_DETAIL
(
  MTL_TXN_ID            VARCHAR2(16 BYTE),
  MTL_ENTITY_ID         VARCHAR2(20 BYTE),
  MTL_NATURE_ID         VARCHAR2(20 BYTE),
  MTL_TXN_ELEMENT_TYPE  CHAR(4 BYTE),
  MTL_EXEC_SEQ          INTEGER,
  MTL_AMOUNT            NUMBER(12,2),
  MTL_CCY               CHAR(3 BYTE),
  MTL_AMT_TYPE          CHAR(2 BYTE),
  MTL_CREATE_TIMESTAMP  DATE,
  MTL_CREATE_USER       VARCHAR2(20 BYTE),
  MTL_UPDATE_TIMESTAMP  DATE,
  MTL_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MMS_TXN_ELEMENT_DETAIL_PK ON MMS_TXN_ELEMENT_DETAIL
(MTL_TXN_ID, MTL_ENTITY_ID, MTL_NATURE_ID, MTL_TXN_ELEMENT_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_TXN_ELEMENT_DETAIL ADD (
  CONSTRAINT MMS_TXN_ELEMENT_DETAIL_PK
  PRIMARY KEY
  (MTL_TXN_ID, MTL_ENTITY_ID, MTL_NATURE_ID, MTL_TXN_ELEMENT_TYPE)
  USING INDEX MMS_TXN_ELEMENT_DETAIL_PK
  ENABLE VALIDATE);

ALTER TABLE MMS_TXN_ELEMENT_DETAIL ADD (
  CONSTRAINT MMS_TXN_ELEMENT_DETAIL_FK01 
  FOREIGN KEY (MTL_TXN_ID) 
  REFERENCES MMS_TXN_HEADER (MTH_TXN_ID)
  ENABLE VALIDATE);

