OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/Psp
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBPsp.so
SOOBJS =  Psp.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
