OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/TxnBalanceLog
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBTxnBalanceLog.so
SOOBJS = TxnBalanceLog.o

include $(HOME)/config/Make.rules

LDLIBS +=

all : $(COMPSO)
