DROP TABLE OL_TXN_STATUS_LOG CASCADE CONSTRAINTS;

CREATE TABLE OL_TXN_STATUS_LOG
(
  OTS_TXN_ID            VARCHAR2(16 BYTE),
  OTS_STATUS            CHAR(1 BYTE),
  OTS_AR_IND            CHAR(1 BYTE),
  OTS_SUB_STATUS        CHAR(3 BYTE),
  OTS_CREATE_USER       VARCHAR2(20 BYTE),
  OTS_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX OL_TXN_STATUS_LOG_IDX01 ON OL_TXN_STATUS_LOG
(OTS_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

ALTER TABLE OL_TXN_STATUS_LOG ADD (
  CONSTRAINT OL_TXN_STATUS_LOG_FK01 
  FOREIGN KEY (OTS_TXN_ID) 
  REFERENCES OL_TXN_HEADER (OTH_TXN_ID)
  ENABLE VALIDATE,
  CONSTRAINT OL_TXN_STATUS_LOG_FK02 
  FOREIGN KEY (OTS_SUB_STATUS) 
  REFERENCES DEF_SUB_STATUS (DS_SUB_STATUS)
  ENABLE VALIDATE);

