ALTER TABLE MMS_RULE_PROCESSING_COST
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_RULE_PROCESSING_COST CASCADE CONSTRAINTS;

CREATE TABLE MMS_RULE_PROCESSING_COST
(
  MPC_RULE_ID           INTEGER,
  MPC_ENTITY_TYPE       CHAR(3 BYTE),
  MPC_ENTITY_ID         VARCHAR2(20 BYTE)       DEFAULT '000',
  MPC_CCY               VARCHAR2(3 BYTE),
  MPC_RATE              NUMBER(14,5)            DEFAULT 1,
  MPC_AMOUNT            NUMBER(14,2)            DEFAULT 0,
  MPC_DISBALED          INTEGER,
  MPC_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  MPC_CREATE_USER       VARCHAR2(20 BYTE),
  MPC_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  MPC_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX MMS_RULE_PROCESSING_COST_IDX01 ON MMS_RULE_PROCESSING_COST
(MPC_ENTITY_TYPE, MPC_ENTITY_ID, MPC_CCY)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX MMS_RULE_PROCESSING_COST_PK ON MMS_RULE_PROCESSING_COST
(MPC_RULE_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_RULE_PROCESSING_COST ADD (
  CONSTRAINT MMS_RULE_PROCESSING_COST_PK
  PRIMARY KEY
  (MPC_RULE_ID)
  USING INDEX MMS_RULE_PROCESSING_COST_PK
  ENABLE VALIDATE);

