CREATE OR REPLACE FUNCTION SP_HIST_COST_SUM_COLLECT(
    IN_END_DATE IN DATE )
RETURN NUMBER IS
	EXP_ERR  EXCEPTION;
	EXP_ERR2 EXCEPTION;
	DATE_ERR EXCEPTION;
	
	V_CUTOFF_DATE DATE;
	
	V_NEW_BATCH_ID HIST_COST_SUM_BATCH.HB_BATCH_ID%type;
	V_PREV_BATCH_ID HIST_COST_SUM_BATCH.HB_BATCH_ID%type;
	V_START_DATE         DATE;
	V_ADD_RANGE_END_DATE DATE;
	
	V_AMT NUMBER(14,2); 
	V_REFUND_AMT NUMBER(14,2); 
	V_VOID_AMT NUMBER(14,2);
	V_TOTAL_AMT NUMBER(14,2);
	
	V_AMT_HKD NUMBER(14,2);
	V_REFUND_HKD NUMBER(14,2);
	V_VOID_HKD NUMBER(14,2);
	V_TOTAL_HKD NUMBER(14,2);
	
	V_AMT_USD NUMBER(14,2);
	V_REFUND_USD NUMBER(14,2);
	V_VOID_USD NUMBER(14,2);
	V_TOTAL_USD NUMBER(14,2);
	
	V_PREV_TXN_COUNT NUMBER;
	V_TXN_COUNT NUMBER;
	
	V_PREV_AMT NUMBER(14,2); 
	V_PREV_AMT_HKD NUMBER(14,2);
	V_PREV_AMT_USD NUMBER(14,2);
	
	V_PREV_REFUND_AMT NUMBER(14,2); 
	V_PREV_REFUND_AMT_HKD NUMBER(14,2);
	V_PREV_REFUND_AMT_USD NUMBER(14,2);
	
	V_PREV_VOID_AMT NUMBER(14,2); 
	V_PREV_VOID_AMT_HKD NUMBER(14,2);
	V_PREV_VOID_AMT_USD NUMBER(14,2);
	
	V_PREV_TOTAL_AMT NUMBER(14,2); 
	V_PREV_TOTAL_AMT_HKD NUMBER(14,2);
	V_PREV_TOTAL_AMT_USD NUMBER(14,2);
	
	V_HKD_RATE EXCHANGE_RATE.EX_MED_ASK%type;
	V_USD_RATE EXCHANGE_RATE.EX_MED_ASK%type;
	V_COUNT_NO number;
	V_COUNT_NO2 number;
  
BEGIN
-- DBMS_OUTPUT.PUT_LINE('>>> START [HIST_COST_SUM_COLLECT] <<<');
-- DBMS_OUTPUT.PUT_LINE('--> Input Date: '|| TO_CHAR(IN_END_DATE, 'YYYY-MM-DD HH24:MI') );

	SELECT 
		count(*)
	INTO 
		V_COUNT_NO2
	FROM HIST_RPT_CONFIG
	WHERE HR_RPT_CODE = 'COST_SUM';

	IF SQL % ROWCOUNT != 1 THEN
		raise EXP_ERR2;
	END IF; 
	        
	        
	IF V_COUNT_NO2 > 0 THEN
		SELECT 
		      HR_CUTOFF_DATE
		INTO 
		      V_CUTOFF_DATE
		FROM HIST_RPT_CONFIG
		WHERE HR_RPT_CODE = 'COST_SUM';

		IF SQL % ROWCOUNT != 1 THEN
		      raise EXP_ERR2;
		END IF ;
	ELSE 
	       V_CUTOFF_DATE := IN_END_DATE - 1 ;
	END IF ; 

-- Find Prev Batch ID and current batch start date/time
	SELECT HB_BATCH_ID,
	       HB_END_DATE
	INTO V_PREV_BATCH_ID,
	     V_START_DATE
	FROM
	(
		SELECT HB_BATCH_ID,
	  	       HB_END_DATE,
	 	       ROW_NUMBER() OVER (PARTITION BY HB_DISABLED ORDER BY HB_END_DATE DESC) RN
		FROM HIST_COST_SUM_BATCH
		WHERE HB_DISABLED = 0
	)
	WHERE RN = 1;

	IF SQL % ROWCOUNT != 1 THEN
		raise EXP_ERR2;
	END IF ;

	V_START_DATE := V_START_DATE + 1/24/60;
-- DBMS_OUTPUT.PUT_LINE('--> Start Date: '|| V_START_DATE );
-- DBMS_OUTPUT.PUT_LINE('--> End Date: '|| IN_END_DATE );

-- only look forward
	IF IN_END_DATE < V_START_DATE THEN
		raise DATE_ERR;
	END IF;
-- DBMS_OUTPUT.PUT_LINE('xxxx');

-- New Batch ID
	SELECT MAX(HB_BATCH_ID) + 1
	INTO V_NEW_BATCH_ID
	FROM HIST_COST_SUM_BATCH;
-- DBMS_OUTPUT.PUT_LINE('--> New Batch ID: ' || V_NEW_BATCH_ID );
-- DBMS_OUTPUT.PUT_LINE('--> Previous Batch ID: ' || V_PREV_BATCH_ID );

-- Add 1 mins to end times
	V_ADD_RANGE_END_DATE := IN_END_DATE + 1/24/60;
-- DBMS_OUTPUT.PUT_LINE('--> Add 1 mins end date: ' || V_ADD_RANGE_END_DATE );

-- Insert New Batch
	INSERT
	INTO HIST_COST_SUM_BATCH
	(
		HB_BATCH_ID,
		HB_START_DATE,
		HB_END_DATE,
		HB_DISABLED,
		HB_CREATE_TIMESTAMP,
		HB_CREATE_USER
	)
	VALUES
	(
		V_NEW_BATCH_ID,
		V_START_DATE,
		IN_END_DATE,
		0,
		SYSDATE,
		'SYSTEM'
	);

	IF SQL % ROWCOUNT != 1 THEN
		raise EXP_ERR;
	END IF ;
-- DBMS_OUTPUT.PUT_LINE('--> Insert New Batch : OK');
-- Find PSP Cost Sum from start times to end times
	FOR X IN
	(
		SELECT PARTY_TYPE,
		       ENTITY_ID,
		       ENTITY_NAME,
		       CLIENT_NAME,
		       TXN_CCY,
		       TXN_CODE,
		       PRODUCT_CODE,
		       COUNTRY,
		       TXN_COUNT,
		       AMOUNT,
		       REFUND_AMOUNT,
		       VOID_AMOUNT,
		       TOTAL_AMOUNT,
		       IS_PREV
		FROM
		(
			SELECT PARTY_TYPE,
			      	ENTITY_ID,
			      	ENTITY_NAME,
			      	CLIENT_NAME,
			      	TXN_CCY,
			      	TXN_CODE,
			      	PRODUCT_CODE,
			      	COUNTRY,
			      	TXN_COUNT,
			      	AMOUNT,
			      	REFUND_AMOUNT,
			      	VOID_AMOUNT,
			      	TOTAL_AMOUNT,
			      	IS_PREV,
			      	ROW_NUMBER() OVER ( PARTITION BY PARTY_TYPE ,ENTITY_ID ,ENTITY_NAME ,CLIENT_NAME ,TXN_CCY ,TXN_CODE , PRODUCT_CODE,COUNTRY ORDER BY IS_PREV ASC ) RN
		        FROM
			(
				SELECT TXN.PARTY_TYPE AS PARTY_TYPE
			              ,TXN.ENTITY_ID AS ENTITY_ID
			              ,TXN.ENTITY_NAME AS ENTITY_NAME
			              ,TXN.CLIENT_NAME AS CLIENT_NAME
			              ,TXN.TXN_CCY AS TXN_CCY
			              ,TXN.TXN_CODE AS TXN_CODE
			              ,TXN.PRODUCT_CODE AS PRODUCT_CODE
			              ,TXN_DETAIL.TD_TXN_COUNTRY AS COUNTRY
			              ,COUNT(TXN.TXN_ID) AS TXN_COUNT
			              ,SUM(CASE 
			              		WHEN TXN.IS_COST_AMT = 1
			              			THEN TXN.TXN_AMOUNT
			              		ELSE 0
			                   END) AS AMOUNT
			              ,SUM(CASE 
			              		WHEN TXN.IS_REFUND_AMT = 1
			              			THEN TXN.TXN_AMOUNT
			              		ELSE 0
			              	 END) AS REFUND_AMOUNT
			              ,SUM(CASE 
			              		WHEN TXN.IS_VOID_AMT = 1
			              			THEN TXN.TXN_AMOUNT
			              		ELSE 0
			              	 END) AS VOID_AMOUNT
			              ,SUM(CASE 
			              		WHEN TXN.IS_COST_AMT = 1
			              			THEN TXN.TXN_AMOUNT
			              		ELSE 0
			              	 END) - SUM(CASE 
			              		WHEN TXN.IS_REFUND_AMT = 1
			              			THEN TXN.TXN_AMOUNT
			              		ELSE 0
			              	 END) - SUM(CASE 
			              		WHEN TXN.IS_VOID_AMT = 1
			              			THEN TXN.TXN_AMOUNT
			              		ELSE 0
			              	 END) AS TOTAL_AMOUNT
			              ,0 AS IS_PREV		
				FROM (
					SELECT TXN_HEADER.TH_TXN_ID AS TXN_ID
					      ,TXN_HEADER.TH_TXN_CODE AS TXN_CODE
					      ,TXN_ELEMENTS.TE_AMOUNT AS TXN_AMOUNT
					      ,TXN_ELEMENTS.TE_AMT_TYPE AS TXN_AMT_TYPE
					      ,CRR_PSP_PRODUCT_CODE_MAP.PM_PRODUCT_CODE AS PRODUCT_CODE
					      ,'PSP' AS PARTY_TYPE
					      ,TXN_PSP_DETAIL.TP_PSP_ID AS ENTITY_ID
					      ,PSP_DETAIL.PSP_NAME AS ENTITY_NAME
					      ,PSP_MASTER.PM_CLIENT_NAME AS CLIENT_NAME
					      ,TXN_ELEMENTS.TE_CCY AS TXN_CCY
					      ,COST_SUM_TXN_CODE_MAP.IS_COST_AMT AS IS_COST_AMT
					      ,COST_SUM_TXN_CODE_MAP.IS_REFUND_AMT AS IS_REFUND_AMT
					      ,COST_SUM_TXN_CODE_MAP.IS_VOID_AMT AS IS_VOID_AMT
					FROM TXN_HEADER
			      		INNER JOIN COST_SUM_TXN_CODE_MAP
			      		ON COST_SUM_TXN_CODE_MAP.PARTY_TYPE = 'P'
			      		AND COST_SUM_TXN_CODE_MAP.TXN_CODE = TXN_HEADER.TH_TXN_CODE
			      		INNER JOIN TXN_ELEMENTS
			      		ON TXN_ELEMENTS.TE_TXN_ID = TXN_HEADER.TH_TXN_ID
			      		AND TXN_ELEMENTS.TE_TXN_ELEMENT_TYPE = COST_SUM_TXN_CODE_MAP.TXN_ELEMENT_TYPE
			      		AND TXN_ELEMENTS.TE_PARTY_TYPE = COST_SUM_TXN_CODE_MAP.PARTY_TYPE
			      		AND TXN_HEADER.TH_AR_IND = 'A'
			      		AND TXN_HEADER.TH_STATUS IN (
			      			'C'
			      			,'R'
			      		)
			      		INNER JOIN TXN_PSP_DETAIL
			      		ON TXN_PSP_DETAIL.TP_TXN_ID = TXN_HEADER.TH_TXN_ID
			      		INNER JOIN PSP_DETAIL
			      		ON PSP_DETAIL.PSP_ID = TXN_PSP_DETAIL.TP_PSP_ID
			      		LEFT JOIN PSP_MASTER
			      		ON PSP_MASTER.PM_CLIENT_ID = PSP_DETAIL.CLIENT_ID
			      		LEFT JOIN CRR_PSP_PRODUCT_CODE_MAP
			      		ON CRR_PSP_PRODUCT_CODE_MAP.PM_PSP_ID = PSP_DETAIL.PSP_ID
			      		AND CRR_PSP_PRODUCT_CODE_MAP.PM_BUSINESS_TYPE = PSP_DETAIL.PSP_TYPE
			      		WHERE 1 = 1
			      		AND TXN_HEADER.TH_APPROVAL_TIMESTAMP >= CAST(V_START_DATE AS TIMESTAMP)
			      		AND TXN_HEADER.TH_APPROVAL_TIMESTAMP < CAST(V_ADD_RANGE_END_DATE AS TIMESTAMP)
			      		
			      		UNION
			      		
			      		SELECT TXN_HEADER.TH_TXN_ID AS TXN_ID
			      			,TXN_HEADER.TH_TXN_CODE AS TXN_CODE
			      			,TXN_ELEMENTS.TE_AMOUNT AS TXN_AMOUNT
			      			,TXN_ELEMENTS.TE_AMT_TYPE AS TXN_AMT_TYPE
			      			,CRR_PSP_PRODUCT_CODE_MAP.PM_PRODUCT_CODE AS PRODUCT_CODE
			      			,'PSP' AS PARTY_TYPE
			      			,TXN_PSP_DETAIL.TP_PSP_ID AS ENTITY_ID
			      			,PSP_DETAIL.PSP_NAME AS ENTITY_NAME
			      			,PSP_MASTER.PM_CLIENT_NAME AS CLIENT_NAME
			      			,TXN_ELEMENTS.TE_CCY AS TXN_CCY
			      			,CASE 
			      			WHEN TXN_ELEMENTS.TE_AMT_TYPE = 'DR'
			      				THEN 1
			      			ELSE 0
			      			END AS IS_COST_AMT
			      			,CASE 
			      				WHEN TXN_ELEMENTS.TE_AMT_TYPE = 'CR'
			      					THEN 1
			      				ELSE 0
			      				END AS IS_REFUND_AMT
			      			,0 AS IS_VOID_AMT
			      		FROM TXN_HEADER
			      		INNER JOIN TXN_ELEMENTS
		      			ON TXN_ELEMENTS.TE_TXN_ID = TXN_HEADER.TH_TXN_ID
	      				AND TXN_ELEMENTS.TE_TXN_ELEMENT_TYPE IN (
			      			'TAMT'
			      			,'INTR'
      					)
	      				AND TXN_ELEMENTS.TE_PARTY_TYPE = 'P'
	      				AND TXN_HEADER.TH_AR_IND = 'A'
	      				AND TXN_HEADER.TH_STATUS IN (
			      			'C'
			      			,'R'
      					)
			      		INNER JOIN ADJUSTMENT_TYPE
			      		ON ADJUSTMENT_TYPE.AT_CODE = TXN_HEADER.TH_TXN_CODE
			      		AND ADJUSTMENT_TYPE.AT_NATURE = 'C'
			      		INNER JOIN TXN_PSP_DETAIL
			      		ON TXN_PSP_DETAIL.TP_TXN_ID = TXN_HEADER.TH_TXN_ID
			      		INNER JOIN PSP_DETAIL
			      		ON PSP_DETAIL.PSP_ID = TXN_PSP_DETAIL.TP_PSP_ID
			      		LEFT JOIN PSP_MASTER
			      		ON PSP_MASTER.PM_CLIENT_ID = PSP_DETAIL.CLIENT_ID
			      		LEFT JOIN CRR_PSP_PRODUCT_CODE_MAP
			      		ON CRR_PSP_PRODUCT_CODE_MAP.PM_PSP_ID = PSP_DETAIL.PSP_ID
			      		AND CRR_PSP_PRODUCT_CODE_MAP.PM_BUSINESS_TYPE = PSP_DETAIL.PSP_TYPE
			      		WHERE 1 = 1
			      		AND TXN_HEADER.TH_APPROVAL_TIMESTAMP >= CAST(V_START_DATE AS TIMESTAMP)
			      		AND TXN_HEADER.TH_APPROVAL_TIMESTAMP < CAST(V_ADD_RANGE_END_DATE AS TIMESTAMP)
			
			      		UNION
			      		
			      		SELECT TXN_HEADER.TH_TXN_ID AS TXN_ID
			      			,TXN_HEADER.TH_TXN_CODE AS TXN_CODE
			      			,TXN_ELEMENTS.TE_AMOUNT AS TXN_AMOUNT
			      			,TXN_ELEMENTS.TE_AMT_TYPE AS TXN_AMT_TYPE
			      			,TXN_MI_DETAIL.TM_TXN_PRODUCT AS PRODUCT_CODE
			      			,TXN_MI_DETAIL.TM_PARTY_TYPE AS PARTY_TYPE
			      			,TXN_MI_DETAIL.TM_ENTITY_ID AS ENTITY_ID
			      			,MI_ENTITY_RSP.ER_RSP_NAME AS ENTITY_NAME
			      			,MI_ENTITY_RSP.ER_RSP_NAME AS CLIENT_NAME
			      			,TXN_ELEMENTS.TE_CCY AS TXN_CCY
			      			,COST_SUM_TXN_CODE_MAP.IS_COST_AMT AS IS_COST_AMT
			      			,COST_SUM_TXN_CODE_MAP.IS_REFUND_AMT AS IS_REFUND_AMT
			      			,COST_SUM_TXN_CODE_MAP.IS_VOID_AMT AS IS_VOID_AMT
			      		FROM TXN_HEADER
			      		INNER JOIN COST_SUM_TXN_CODE_MAP
			      		ON COST_SUM_TXN_CODE_MAP.PARTY_TYPE = 'S'
			      		AND COST_SUM_TXN_CODE_MAP.TXN_CODE = TXN_HEADER.TH_TXN_CODE
			      		INNER JOIN TXN_ELEMENTS
			      		ON TXN_ELEMENTS.TE_TXN_ID = TXN_HEADER.TH_TXN_ID
			      		AND TXN_ELEMENTS.TE_TXN_ELEMENT_TYPE = COST_SUM_TXN_CODE_MAP.TXN_ELEMENT_TYPE
			      		AND TXN_ELEMENTS.TE_PARTY_TYPE = COST_SUM_TXN_CODE_MAP.PARTY_TYPE
			      		AND TXN_HEADER.TH_AR_IND = 'A'
			      		AND TXN_HEADER.TH_STATUS IN (
			      			'C'
			      			,'R'
			      		)
			      		INNER JOIN TXN_MI_DETAIL
			      		ON TH_TXN_ID = TM_TXN_ID
			      		AND TXN_MI_DETAIL.TM_PARTY_TYPE = 'RSP'
			      		INNER JOIN MI_ENTITY_RSP
			      		ON MI_ENTITY_RSP.ER_ENTITY_ID = TXN_MI_DETAIL.TM_ENTITY_ID
			      		WHERE 1 = 1
			      		AND TXN_HEADER.TH_APPROVAL_TIMESTAMP >= CAST(V_START_DATE AS TIMESTAMP)
			      		AND TXN_HEADER.TH_APPROVAL_TIMESTAMP < CAST(V_ADD_RANGE_END_DATE AS TIMESTAMP)
			
			      		UNION
			      		
			      		SELECT TXN_HEADER.TH_TXN_ID AS TXN_ID
			      		      ,TXN_HEADER.TH_TXN_CODE AS TXN_CODE
			      		      ,TXN_ELEMENTS.TE_AMOUNT AS TXN_AMOUNT
			      		      ,TXN_ELEMENTS.TE_AMT_TYPE AS TXN_AMT_TYPE
			      		      ,TXN_MI_DETAIL.TM_TXN_PRODUCT AS PRODUCT_CODE
			      		      ,TXN_MI_DETAIL.TM_PARTY_TYPE AS PARTY_TYPE
			      		      ,TXN_MI_DETAIL.TM_ENTITY_ID AS ENTITY_ID
			      		      ,MI_ENTITY_RSP.ER_RSP_NAME AS ENTITY_NAME
			      		      ,MI_ENTITY_RSP.ER_RSP_NAME AS CLIENT_NAME
			      		      ,TXN_ELEMENTS.TE_CCY AS TXN_CCY
			      		      ,CASE 
			      		             WHEN TXN_ELEMENTS.TE_AMT_TYPE = 'DR'
			      		             	THEN 1
			      		             ELSE 0
			      		             END AS IS_COST_AMT
			      		      ,CASE 
			      		             WHEN TXN_ELEMENTS.TE_AMT_TYPE = 'CR'
			      		             	THEN 1
			      		             ELSE 0
			      		             END AS IS_REFUND_AMT
			      		      ,0 AS IS_VOID_AMT
			      		FROM TXN_HEADER
			      		INNER JOIN TXN_ELEMENTS
			      		ON TXN_ELEMENTS.TE_TXN_ID = TXN_HEADER.TH_TXN_ID
			      		AND TXN_ELEMENTS.TE_TXN_ELEMENT_TYPE IN (
			      			'TAMT'
			      			,'INTR'
			      		)
			      		AND TXN_ELEMENTS.TE_PARTY_TYPE = 'S'
			      		AND TXN_HEADER.TH_AR_IND = 'A'
			      		AND TXN_HEADER.TH_STATUS IN (
			      			'C'
			      			,'R'
			      		)
			      		INNER JOIN TXN_MI_DETAIL
			      		ON TH_TXN_ID = TM_TXN_ID
			      		AND TXN_MI_DETAIL.TM_PARTY_TYPE = 'RSP'
			      		INNER JOIN MI_ENTITY_RSP
			      		ON MI_ENTITY_RSP.ER_ENTITY_ID = TXN_MI_DETAIL.TM_ENTITY_ID
			      		INNER JOIN MI_ADJUSTMENT_TYPE
			      		ON MAT_CODE = TH_TXN_CODE
			      		AND MAT_ENTITY_TYPE = 'RSP'
			      		AND MAT_NATURE = 'C'
			      		WHERE 1 = 1
			      		AND TXN_HEADER.TH_APPROVAL_TIMESTAMP >= CAST(V_START_DATE AS TIMESTAMP)
			      		AND TXN_HEADER.TH_APPROVAL_TIMESTAMP < CAST(V_ADD_RANGE_END_DATE AS TIMESTAMP)
			      			
			      		UNION
			
			      		SELECT TXN_HEADER.TH_TXN_ID AS TXN_ID
			      		      ,TXN_HEADER.TH_TXN_CODE AS TXN_CODE
			      		      ,TXN_ELEMENTS.TE_AMOUNT AS TXN_AMOUNT
			      		      ,TXN_ELEMENTS.TE_AMT_TYPE AS TXN_AMT_TYPE
			      		      ,TXN_MI_DETAIL.TM_TXN_PRODUCT AS PRODUCT_CODE
			      		      ,TXN_MI_DETAIL.TM_PARTY_TYPE AS PARTY_TYPE
			      		      ,TXN_MI_DETAIL.TM_ENTITY_ID AS ENTITY_ID
			      		      ,MI_ENTITY_OPB.EO_OPB_NAME AS ENTITY_NAME
			      		      ,MI_ENTITY_OPB.EO_OPB_NAME AS CLIENT_NAME
			      		      ,TXN_ELEMENTS.TE_CCY AS TXN_CCY
			      		      ,COST_SUM_TXN_CODE_MAP.IS_COST_AMT AS IS_COST_AMT
			      		      ,COST_SUM_TXN_CODE_MAP.IS_REFUND_AMT AS IS_REFUND_AMT
			      		      ,COST_SUM_TXN_CODE_MAP.IS_VOID_AMT AS IS_VOID_AMT
			      		FROM TXN_HEADER
			      		INNER JOIN COST_SUM_TXN_CODE_MAP
			      		ON COST_SUM_TXN_CODE_MAP.PARTY_TYPE = 'B'
			      		AND COST_SUM_TXN_CODE_MAP.TXN_CODE = TXN_HEADER.TH_TXN_CODE
			      		INNER JOIN TXN_ELEMENTS
			      		ON TXN_ELEMENTS.TE_TXN_ID = TXN_HEADER.TH_TXN_ID
			      		AND TXN_ELEMENTS.TE_TXN_ELEMENT_TYPE = COST_SUM_TXN_CODE_MAP.TXN_ELEMENT_TYPE
			      		AND TXN_ELEMENTS.TE_PARTY_TYPE = COST_SUM_TXN_CODE_MAP.PARTY_TYPE
			      		AND TXN_HEADER.TH_AR_IND = 'A'
			      		AND TXN_HEADER.TH_STATUS IN (
			      			'C'
			      			,'R'
			      		)
			      		INNER JOIN TXN_MI_DETAIL
			      		ON TH_TXN_ID = TM_TXN_ID
			      		AND TXN_MI_DETAIL.TM_PARTY_TYPE = 'OPB'
			      		INNER JOIN MI_ENTITY_OPB
			      		ON MI_ENTITY_OPB.EO_ENTITY_ID = TXN_MI_DETAIL.TM_ENTITY_ID
			      		WHERE 1 = 1
			      		AND TXN_HEADER.TH_APPROVAL_TIMESTAMP >= CAST(V_START_DATE AS TIMESTAMP)
			      		AND TXN_HEADER.TH_APPROVAL_TIMESTAMP < CAST(V_ADD_RANGE_END_DATE AS TIMESTAMP)
			      
			      		UNION
			      		
			      		SELECT TXN_HEADER.TH_TXN_ID AS TXN_ID
			      		      ,TXN_HEADER.TH_TXN_CODE AS TXN_CODE
			      		      ,TXN_ELEMENTS.TE_AMOUNT AS TXN_AMOUNT
			      		      ,TXN_ELEMENTS.TE_AMT_TYPE AS TXN_AMT_TYPE
			      		      ,TXN_MI_DETAIL.TM_TXN_PRODUCT AS PRODUCT_CODE
			      		      ,TXN_MI_DETAIL.TM_PARTY_TYPE AS PARTY_TYPE
			      		      ,TXN_MI_DETAIL.TM_ENTITY_ID AS ENTITY_ID
			      		      ,MI_ENTITY_OPB.EO_OPB_NAME AS ENTITY_NAME
			      		      ,MI_ENTITY_OPB.EO_OPB_NAME AS CLIENT_NAME
			      		      ,TXN_ELEMENTS.TE_CCY AS TXN_CCY
			      		      ,CASE 
			      		            WHEN TXN_ELEMENTS.TE_AMT_TYPE = 'DR'
			      		            	THEN 1
			      		            ELSE 0
			      		            END AS IS_COST_AMT
			      		      ,CASE 
			      		            WHEN TXN_ELEMENTS.TE_AMT_TYPE = 'CR'
			      		            	THEN 1
			      		            ELSE 0
			      		            END AS IS_REFUND_AMT
			      		     ,0 AS IS_VOID_AMT
			      		FROM TXN_HEADER
			      		INNER JOIN TXN_ELEMENTS
			      		ON TXN_ELEMENTS.TE_TXN_ID = TXN_HEADER.TH_TXN_ID
			      		AND TXN_ELEMENTS.TE_TXN_ELEMENT_TYPE IN (
			      			'TAMT'
			      			,'INTR'
			      		)
			      		AND TXN_ELEMENTS.TE_PARTY_TYPE = 'B'
			      		AND TXN_HEADER.TH_AR_IND = 'A'
			      		AND TXN_HEADER.TH_STATUS IN (
			      			'C'
			      			,'R'
			      		)
			      		INNER JOIN TXN_MI_DETAIL
			      		ON TH_TXN_ID = TM_TXN_ID
			      		AND TXN_MI_DETAIL.TM_PARTY_TYPE = 'OPB'
			      		INNER JOIN MI_ENTITY_OPB
			      		ON MI_ENTITY_OPB.EO_ENTITY_ID = TXN_MI_DETAIL.TM_ENTITY_ID
			      		INNER JOIN MI_ADJUSTMENT_TYPE
			      		ON MAT_CODE = TH_TXN_CODE
			      		AND MAT_ENTITY_TYPE = 'OPB'
			      		AND MAT_NATURE = 'C'
			      		WHERE 1 = 1
			      		AND TXN_HEADER.TH_APPROVAL_TIMESTAMP >= CAST(V_START_DATE AS TIMESTAMP)
			      		AND TXN_HEADER.TH_APPROVAL_TIMESTAMP < CAST(V_ADD_RANGE_END_DATE AS TIMESTAMP)
				) TXN
				INNER JOIN TXN_DETAIL
		      		ON TXN_DETAIL.TD_TXN_ID = TXN.TXN_ID
				INNER JOIN TXN_CODE
				ON TXN_CODE.TC_CODE = TXN.TXN_CODE
				LEFT JOIN DEF_PRODUCT
				ON DEF_PRODUCT.DP_ID = TXN.PRODUCT_CODE
				LEFT JOIN COUNTRY
		     		ON COUNTRY.COUNTRY_CODE = TXN_DETAIL.TD_TXN_COUNTRY
				WHERE 1 = 1
				AND TXN.ENTITY_ID IS NOT NULL
				AND TXN.TXN_CCY IS NOT NULL
				AND TXN.TXN_CODE IS NOT NULL
				AND TXN.PRODUCT_CODE IS NOT NULL
				AND TXN_DETAIL.TD_TXN_COUNTRY IS NOT NULL
				GROUP BY PARTY_TYPE
					,ENTITY_ID
					,ENTITY_NAME
					,CLIENT_NAME
					,TXN_CCY
					,TXN_CODE
					,PRODUCT_CODE
					,TD_TXN_COUNTRY
				UNION
				SELECT HD_PARTY_TYPE 		AS PARTY_TYPE ,
				       HD_ENTITY_ID		AS ENTITY_ID ,
				       HD_ENTITY_NAME		AS ENTITY_NAME ,
				       HD_CLIENT_NAME		AS CLIENT_NAME ,
				       HD_CCY     		AS TXN_CCY ,
				       HD_TXN_TYPE		AS TXN_CODE ,
				       HD_PRODUCT		AS PRODUCT_CODE ,
				       HD_COUNTRY		AS COUNTRY ,
				       HD_COUNT			AS TXN_COUNT,
				       HD_ACCUM_COST_AMT	AS AMOUNT,
				       HD_ACCUM_REFUND_AMT	AS REFUND_AMOUNT,
				       HD_ACCUM_VOID_AMT	AS VOID_AMOUNT,
				       HD_ACCUM_TOTAL_AMT	AS TOTAL_AMOUNT,
				       1			AS IS_PREV
				FROM HIST_COST_SUM_DETAIL
				WHERE HD_BATCH_ID = V_PREV_BATCH_ID
			)
		)
		WHERE RN = 1
	)
	LOOP
-- DBMS_OUTPUT.PUT_LINE('--> PSP_ID: [' || X.ENTITY_ID || '] TXN_CCY: [' || X.TXN_CCY || '] COUNTRY : [' || X.COUNTRY||'] ');
	
		SELECT count(*) AS COUNT_NO INTO V_COUNT_NO
		FROM HIST_COST_SUM_DETAIL  
		WHERE HD_BATCH_ID = V_PREV_BATCH_ID
		AND HD_ENTITY_ID = X.ENTITY_ID
		AND HD_ENTITY_NAME = X.ENTITY_NAME
		AND HD_CLIENT_NAME = X.CLIENT_NAME
		AND HD_CCY = X.TXN_CCY
		AND HD_COUNTRY = X.COUNTRY
		AND HD_PRODUCT = X.PRODUCT_CODE
		AND HD_TXN_TYPE = X.TXN_CODE
		AND HD_PARTY_TYPE = X.PARTY_TYPE
	        ;	
			
		IF V_COUNT_NO > 0 THEN
-- Prev Batch Bal	
			SELECT
				NVL(HD_COUNT, 0)   AS HD_COUNT,
				NVL(HD_ACCUM_COST_AMT, 0.00) AS HD_ACCUM_COST_AMT,
				NVL(HD_ACCUM_COST_AMT_HKD, 0.00) AS HD_ACCUM_COST_AMT_HKD,
				NVL(HD_ACCUM_COST_AMT_USD, 0.00) AS HD_ACCUM_COST_AMT_USD,
				NVL(HD_ACCUM_REFUND_AMT, 0.00) AS HD_ACCUM_REFUND_AMT,
				NVL(HD_ACCUM_REFUND_AMT_HKD, 0.00) AS HD_ACCUM_REFUND_AMT_HKD,
				NVL(HD_ACCUM_REFUND_AMT_USD, 0.00) AS HD_ACCUM_REFUND_AMT_USD,
				NVL(HD_ACCUM_VOID_AMT, 0.00) AS HD_ACCUM_VOID_AMT,
				NVL(HD_ACCUM_VOID_AMT_HKD, 0.00) AS HD_ACCUM_VOID_AMT_HKD,
				NVL(HD_ACCUM_VOID_AMT_USD, 0.00) AS HD_ACCUM_VOID_AMT_USD,
				NVL(HD_ACCUM_TOTAL_AMT, 0.00) AS HD_ACCUM_TOTAL_AMT,
				NVL(HD_ACCUM_TOTAL_AMT_HKD, 0.00) AS HD_ACCUM_TOTAL_AMT_HKD,
				NVL(HD_ACCUM_TOTAL_AMT_USD, 0.00) AS HD_ACCUM_TOTAL_AMT_USD
			INTO 
				V_PREV_TXN_COUNT,
				V_PREV_AMT,
				V_PREV_AMT_HKD,
				V_PREV_AMT_USD,
				V_PREV_REFUND_AMT,
				V_PREV_REFUND_AMT_HKD,
				V_PREV_REFUND_AMT_USD,
				V_PREV_VOID_AMT,
				V_PREV_VOID_AMT_HKD,
				V_PREV_VOID_AMT_USD,
				V_PREV_TOTAL_AMT,
				V_PREV_TOTAL_AMT_HKD,
				V_PREV_TOTAL_AMT_USD
			FROM HIST_COST_SUM_DETAIL  
			WHERE HD_BATCH_ID = V_PREV_BATCH_ID
			AND HD_ENTITY_ID = X.ENTITY_ID
			AND HD_ENTITY_NAME = X.ENTITY_NAME
			AND HD_CLIENT_NAME = X.CLIENT_NAME
			AND HD_CCY = X.TXN_CCY
			AND HD_COUNTRY = X.COUNTRY
			AND HD_PRODUCT = X.PRODUCT_CODE
			AND HD_TXN_TYPE = X.TXN_CODE
			AND HD_PARTY_TYPE = X.PARTY_TYPE;
		ELSE
			V_PREV_TXN_COUNT := 0;
			V_PREV_AMT := 0.00;
			V_PREV_AMT_HKD := 0.00;
			V_PREV_AMT_USD := 0.00;
			V_PREV_REFUND_AMT := 0.00;
			V_PREV_REFUND_AMT_HKD := 0.00;
			V_PREV_REFUND_AMT_USD := 0.00;
			V_PREV_VOID_AMT := 0.00;
			V_PREV_VOID_AMT_HKD := 0.00;
			V_PREV_VOID_AMT_USD := 0.00;
			V_PREV_TOTAL_AMT := 0.00;
			V_PREV_TOTAL_AMT_HKD := 0.00;
			V_PREV_TOTAL_AMT_USD := 0.00;
		END IF ;
	
/*	IF X.TXN_COUNT != V_PREV_TXN_COUNT THEN
		V_AMT := V_PREV_AMT + X.AMOUNT;
		V_REFUND_AMT := V_PREV_REFUND_AMT + X.REFUND_AMOUNT;
		V_VOID_AMT := V_PREV_VOID_AMT + X.VOID_AMOUNT;
		V_TXN_COUNT := V_PREV_TXN_COUNT + X.TXN_COUNT; 
	ELSE
		V_AMT := V_PREV_AMT; 
		V_REFUND_AMT := V_PREV_REFUND_AMT;
		V_VOID_AMT := V_PREV_VOID_AMT;		
		V_TXN_COUNT := V_PREV_TXN_COUNT; 
	END IF ;*/
	
-- DBMS_OUTPUT.PUT_LINE('--> V_PREV_TXN_COUNT: [' || V_PREV_TXN_COUNT || '] V_PREV_AMT: [' || V_PREV_AMT ||'] V_PREV_AMT_HKD: [' || V_PREV_AMT_HKD ||'] V_PREV_AMT_USD: [' || V_PREV_AMT_USD ||']');	

-- DBMS_OUTPUT.PUT_LINE('--> GET Rate');	  
-- HKD Rate , USD Rate	
		SELECT
			RATE_HKD_TBL.RATE AS HKD_RATE,
			RATE_USD_TBL.RATE AS USD_RATE
		INTO 
			V_HKD_RATE,
			V_USD_RATE
		FROM 
		(
			SELECT 
				EX_MED_ASK AS RATE ,
				EX_TO_CCY_ID
			FROM (
				SELECT EX_FROM_CCY_ID
					,EX_TO_CCY_ID
					,EX_MED_ASK
					,ROW_NUMBER() OVER (
						PARTITION BY EX_FROM_CCY_ID
						,EX_TO_CCY_ID ORDER BY EX_EFFECT_DATE DESC
					) XX
				FROM EXCHANGE_RATE
				WHERE EX_EFFECT_DATE < CAST(V_ADD_RANGE_END_DATE AS TIMESTAMP)
			)
			WHERE XX = 1
			AND EX_TO_CCY_ID = 'HKD'
			AND EX_FROM_CCY_ID = X.TXN_CCY
		) RATE_HKD_TBL 
		INNER JOIN (
			SELECT  
				EX_MED_ASK AS RATE ,
				EX_FROM_CCY_ID
			FROM (
				SELECT EX_FROM_CCY_ID
					,EX_TO_CCY_ID
					,EX_MED_ASK
					,ROW_NUMBER() OVER (
						PARTITION BY EX_FROM_CCY_ID
						,EX_TO_CCY_ID ORDER BY EX_EFFECT_DATE DESC
					) XX
				FROM EXCHANGE_RATE
				WHERE EX_EFFECT_DATE < CAST(V_ADD_RANGE_END_DATE AS TIMESTAMP)
			)
			WHERE XX = 1
			AND EX_FROM_CCY_ID = 'HKD'
			AND EX_TO_CCY_ID = 'USD'
		) RATE_USD_TBL ON RATE_HKD_TBL.EX_TO_CCY_ID = RATE_USD_TBL.EX_FROM_CCY_ID;
	
-- DBMS_OUTPUT.PUT_LINE('--> HKD_RATE: [' || V_HKD_RATE || '] USD_RATE: [' || V_USD_RATE ||']');		 
	 
		IF X.IS_PREV = 0 THEN
			V_AMT := V_PREV_AMT + X.AMOUNT ; 
			V_REFUND_AMT := V_PREV_REFUND_AMT + X.REFUND_AMOUNT;
			V_VOID_AMT := V_PREV_VOID_AMT + X.VOID_AMOUNT;
			V_TOTAL_AMT := V_PREV_TOTAL_AMT + X.TOTAL_AMOUNT;
			
			V_AMT_HKD := V_PREV_AMT_HKD + (X.AMOUNT * V_HKD_RATE) ; 
			V_REFUND_HKD := V_PREV_REFUND_AMT_HKD + (X.REFUND_AMOUNT * V_HKD_RATE) ; 
			V_VOID_HKD := V_PREV_VOID_AMT_HKD + (X.VOID_AMOUNT * V_HKD_RATE) ; 
			V_TOTAL_HKD := V_PREV_TOTAL_AMT_HKD + (X.TOTAL_AMOUNT * V_HKD_RATE) ; 
			
			V_AMT_USD := V_PREV_AMT_USD + (X.AMOUNT * V_HKD_RATE * V_USD_RATE) ; 
			V_REFUND_USD := V_PREV_REFUND_AMT_USD + (X.REFUND_AMOUNT * V_HKD_RATE * V_USD_RATE) ; 
			V_VOID_USD := V_PREV_VOID_AMT_USD + (X.VOID_AMOUNT * V_HKD_RATE * V_USD_RATE) ; 
			V_TOTAL_USD := V_PREV_TOTAL_AMT_USD + (X.TOTAL_AMOUNT * V_HKD_RATE * V_USD_RATE) ;
			
			V_TXN_COUNT := V_PREV_TXN_COUNT + X.TXN_COUNT ; 
		ELSE
			V_AMT := V_PREV_AMT; 
			V_REFUND_AMT := V_PREV_REFUND_AMT; 
			V_VOID_AMT := V_PREV_VOID_AMT; 
			V_TOTAL_AMT := V_PREV_TOTAL_AMT; 
			
			V_AMT_HKD := V_PREV_AMT_HKD;
			V_REFUND_HKD := V_PREV_REFUND_AMT_HKD;
			V_VOID_HKD := V_PREV_VOID_AMT_HKD;
			V_TOTAL_HKD := V_PREV_TOTAL_AMT_HKD;
			
			V_AMT_USD := V_PREV_AMT_USD;
			V_REFUND_USD := V_PREV_REFUND_AMT_USD; 
			V_VOID_USD := V_PREV_VOID_AMT_USD; 
			V_TOTAL_USD := V_PREV_TOTAL_AMT_USD;
			
			V_TXN_COUNT := V_PREV_TXN_COUNT; 
		END IF ;
	 
-- DBMS_OUTPUT.PUT_LINE('--> INSERT ');	  
  /* DBMS_OUTPUT.PUT_LINE('--> HD_BATCH_ID: [' || V_NEW_BATCH_ID || '] 
								 HD_PARTY_TYPE: [' || X.PARTY_TYPE ||']
								 HD_ENTITY_ID: [' || X.ENTITY_ID ||']
								 HD_CCY: [' || X.TXN_CCY ||']
								 HD_COUNTRY: [' || X.COUNTRY ||']
								 HD_PRODUCT: [' || X.PRODUCT_CODE ||']
								 HD_TXN_TYPE: [' || X.TXN_CODE ||']
								 HD_COUNT: [' || X.TXN_COUNT ||']
								 
							');	 */
							
-- Check Cut off Time
		IF V_CUTOFF_DATE >= V_ADD_RANGE_END_DATE THEN
			V_TXN_COUNT:= 0.00;
			V_AMT := 0.00;
			V_REFUND_AMT := 0.00;
			V_VOID_AMT := 0.00;
			V_TOTAL_AMT := 0.00;
			V_AMT_HKD := 0.00;
			V_REFUND_HKD := 0.00;
			V_VOID_HKD := 0.00;
			V_TOTAL_HKD := 0.00;
			V_HKD_RATE := 0.00;
			V_AMT_USD := 0.00;
			V_REFUND_USD := 0.00;
			V_VOID_USD := 0.00;
			V_TOTAL_USD := 0.00;
			V_USD_RATE := 0.00;
		END IF;
								
		INSERT INTO HIST_COST_SUM_DETAIL
	        (
			HD_BATCH_ID,
			HD_PARTY_TYPE,
			HD_ENTITY_ID,
			HD_ENTITY_NAME,
			HD_CLIENT_NAME,
			HD_CCY,
			HD_COUNTRY,
			HD_PRODUCT,
			HD_TXN_TYPE,
			HD_COUNT,
			
			HD_ACCUM_COST_AMT,
			HD_ACCUM_REFUND_AMT,
			HD_ACCUM_VOID_AMT,
			HD_ACCUM_TOTAL_AMT,
			
			HD_ACCUM_COST_AMT_HKD,
			HD_ACCUM_REFUND_AMT_HKD,
			HD_ACCUM_VOID_AMT_HKD,
			HD_ACCUM_TOTAL_AMT_HKD,
			HD_ACCUM_COST_AMT_HKD_RATE,
			
			HD_ACCUM_COST_AMT_USD,
			HD_ACCUM_REFUND_AMT_USD,
			HD_ACCUM_VOID_AMT_USD,
			HD_ACCUM_TOTAL_AMT_USD,
			HD_ACCUM_COST_AMT_USD_RATE 
		) VALUES (
			V_NEW_BATCH_ID,
			X.PARTY_TYPE,
			X.ENTITY_ID,
			X.ENTITY_NAME,
			X.CLIENT_NAME,
			X.TXN_CCY,
			X.COUNTRY,
			X.PRODUCT_CODE,
			X.TXN_CODE,
			NVL(V_TXN_COUNT, 0),
			
			NVL(V_AMT, 0.00),
			NVL(V_REFUND_AMT, 0.00),
			NVL(V_VOID_AMT, 0.00),
			NVL(V_TOTAL_AMT, 0.00),
			
			NVL(V_AMT_HKD, 0.00),
			NVL(V_REFUND_HKD, 0.00),
			NVL(V_VOID_HKD, 0.00),
			NVL(V_TOTAL_HKD, 0.00),
	
			V_HKD_RATE,
			
			NVL(V_AMT_USD, 0.00),
			NVL(V_REFUND_USD, 0.00),
			NVL(V_VOID_USD, 0.00),
			NVL(V_TOTAL_USD, 0.00),
			
			V_USD_RATE
		);
	
		IF SQL % ROWCOUNT != 1 THEN
			raise EXP_ERR;
		END IF;
-- DBMS_OUTPUT.PUT_LINE('--> END INSERT ');

	END LOOP;

	COMMIT;
-- DBMS_OUTPUT.PUT_LINE('>>> END [HIST_COST_SUM_COLLECT] <<<');

	RETURN 0;

EXCEPTION
WHEN EXP_ERR THEN
	ROLLBACK;
--DBMS_OUTPUT.PUT_LINE('Error: Insert Cost Summary error!...');
	RETURN 1;
WHEN DATE_ERR THEN
	ROLLBACK;
--DBMS_OUTPUT.PUT_LINE('Error: The latest batch end date larger than input date!');
	RETURN 1;
WHEN EXP_ERR2 THEN
	ROLLBACK;
--DBMS_OUTPUT.PUT_LINE('Error: no record!...');
	RETURN 1;
WHEN OTHERS THEN
	ROLLBACK;
--DBMS_OUTPUT.PUT_LINE('Error: Other error!...');
--DBMS_OUTPUT.PUT_LINE('Error code ' || SQLCODE|| ': ' || SUBSTR(SQLERRM, 1 , 64));
--RAISE_APPLICATION_ERROR( -20201, 'Error code ' || SQLCODE|| ': ' || SUBSTR(SQLERRM, 1 , 64) );
	RETURN 9;
END SP_HIST_COST_SUM_COLLECT;
/

