OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/TxnAckLog
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBTxnAckLog.so
SOOBJS =  TxnAckLog.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
