


CREATE TABLE OL_DEF_TXN_ACK_STATUS
(
  OAS_TYPE              VARCHAR2(2 BYTE),
  OAS_DESC              VARCHAR2(50 BYTE),
  OAS_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate               NOT NULL,
  OAS_CREATE_USER       VARCHAR2(20 BYTE),
  OAS_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate               NOT NULL,
  OAS_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX OL_DEF_TXN_ACK_STATUS_PK ON OL_DEF_TXN_ACK_STATUS
(OAS_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE OL_DEF_TXN_ACK_STATUS ADD (
  CONSTRAINT OL_DEF_TXN_ACK_STATUS_PK
  PRIMARY KEY
  (OAS_TYPE)
  USING INDEX OL_DEF_TXN_ACK_STATUS_PK
  ENABLE VALIDATE);
