OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLStmtConvertError
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLStmtConvertError.so
SOOBJS =  OLStmtConvertError.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
