DROP TABLE TXN_STATUS_LOG CASCADE CONSTRAINTS;

CREATE TABLE TXN_STATUS_LOG
(
  TS_TXN_ID            VARCHAR2(16 BYTE),
  TS_STATUS            CHAR(1 BYTE),
  TS_AR_IND            CHAR(1 BYTE),
  TS_SUB_STATUS        CHAR(3 BYTE),
  TS_CREATE_USER       VARCHAR2(20 BYTE),
  TS_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE TXN_STATUS_LOG ADD (
  CONSTRAINT TXN_STATUS_LOG_FK01 
  FOREIGN KEY (TS_TXN_ID) 
  REFERENCES TXN_HEADER (TH_TXN_ID)
  ENABLE VALIDATE,
  CONSTRAINT TXN_STATUS_LOG_FK02 
  FOREIGN KEY (TS_SUB_STATUS) 
  REFERENCES DEF_SUB_STATUS (DS_SUB_STATUS)
  ENABLE VALIDATE);

