ALTER TABLE PAR_PAYOUT_UPLOAD
 DROP PRIMARY KEY CASCADE;

DROP TABLE PAR_PAYOUT_UPLOAD CASCADE CONSTRAINTS;

CREATE TABLE PAR_PAYOUT_UPLOAD
(
  PU_FILE_ID           INTEGER,
  PU_BATCH_ID          NUMBER(16),
  PU_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  PU_CREATE_USER       VARCHAR2(20 BYTE),
  PU_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  PU_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PAR_PAYOUT_UPLOAD_PK ON PAR_PAYOUT_UPLOAD
(PU_FILE_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PAR_PAYOUT_UPLOAD ADD (
  CONSTRAINT PAR_PAYOUT_UPLOAD_PK
  PRIMARY KEY
  (PU_FILE_ID)
  USING INDEX PAR_PAYOUT_UPLOAD_PK
  ENABLE VALIDATE);

