OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/CrrJnlHeader
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBCrrJnlHeader.so
SOOBJS =  CrrJnlHeader.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
