OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnMgtByUsJLR
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnMgtByUsJLR.so
SOOBJS = TxnMgtByUsJLR.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
