OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLPspTxnBalRule
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLPspTxnBalRule.so
SOOBJS =  OLPspTxnBalRule.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
