ALTER TABLE TXN_CONTROL
 DROP PRIMARY KEY CASCADE;

DROP TABLE TXN_CONTROL CASCADE CONSTRAINTS;

CREATE TABLE TXN_CONTROL
(
  TL_CHANNEL_CODE      VARCHAR2(3 BYTE),
  TL_TXN_CODE          VARCHAR2(3 BYTE),
  TL_COUNTRY_ID        VARCHAR2(2 BYTE),
  TL_CCY               VARCHAR2(3 BYTE),
  TL_AMOUNT            NUMBER(14,2),
  TL_DISABLED          INTEGER                  DEFAULT 0,
  TL_CREATE_TIMESTAMP  DATE,
  TL_CREATE_USER       VARCHAR2(20 BYTE),
  TL_UPDATE_TIMESTAMP  DATE,
  TL_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX TXN_CONTROL_PK ON TXN_CONTROL
(TL_CHANNEL_CODE, TL_TXN_CODE, TL_COUNTRY_ID, TL_CCY)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE TXN_CONTROL ADD (
  CONSTRAINT TXN_CONTROL_PK
  PRIMARY KEY
  (TL_CHANNEL_CODE, TL_TXN_CODE, TL_COUNTRY_ID, TL_CCY)
  USING INDEX TXN_CONTROL_PK);


