OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/TmaLog
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBTmaLog.so
SOOBJS =  TmaLog.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
