OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/CustomerGroupDetail
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBCustomerGroupDetail.so
SOOBJS =  CustomerGroupDetail.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
