ALTER TABLE COUNTRY
 DROP PRIMARY KEY CASCADE;

DROP TABLE COUNTRY CASCADE CONSTRAINTS;

CREATE TABLE COUNTRY
(
  COUNTRY_CODE      CHAR(2 BYTE)                NOT NULL,
  COUNTRY_NAME      VARCHAR2(50 BYTE),
  DISABLED          INTEGER                     DEFAULT 0,
  SYSTEM_SUPPORT    INTEGER,
  CREATE_TIMESTAMP  DATE                        DEFAULT SYSDATE,
  UPDATE_TIMESTAMP  DATE                        DEFAULT SYSDATE,
  CREATE_USER       VARCHAR2(25 BYTE),
  UPDATE_USER       VARCHAR2(25 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX COUNTRY_IDX01 ON COUNTRY
(COUNTRY_CODE, DISABLED)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX COUNTRY_PK ON COUNTRY
(COUNTRY_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE COUNTRY ADD (
  CONSTRAINT COUNTRY_PK
  PRIMARY KEY
  (COUNTRY_CODE)
  USING INDEX COUNTRY_PK);

