OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLChannelKeys
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLChannelKeys.so
SOOBJS =  OLChannelKeys.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
