ALTER TABLE IP_FILTER 
 DROP PRIMARY KEY CASCADE;

DROP TABLE IP_FILTER CASCADE CONSTRAINTS;

CREATE TABLE IP_FILTER
(
  IP_FILTER_ID         INTEGER,
  IP_START             VARCHAR2(15 BYTE),
  IP_END               VARCHAR2(15 BYTE),
  IP_MASK_BIT_COUNT    INTEGER,
  IP_COUNT             INTEGER,
  IP_LOCATION          NVARCHAR2(300),
  IP_START_HIGH        INTEGER,
  IP_START_LOW         INTEGER,
  IP_END_HIGH          INTEGER,
  IP_END_LOW           INTEGER,
  IP_CREATE_TIMESTAMP  DATE		DEFAULT SYSDATE,
  IP_UPDATE_TIMESTAMP  DATE		DEFAULT SYSDATE,
  IP_DISABLED          INTEGER		DEFAULT 0
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX IP_FILTER_PK ON IP_FILTER
(IP_FILTER_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX IP_FILTER_IDX01 ON IP_FILTER
(IP_DISABLED, IP_START_LOW, IP_START_HIGH, IP_END_LOW, IP_END_HIGH)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          192K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

ALTER TABLE IP_FILTER ADD (
  CONSTRAINT IP_FILTER_PK
  PRIMARY KEY
  (IP_FILTER_ID)
  USING INDEX IP_FILTER_PK);
