OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmsEntityNatureGrp
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmsEntityNatureGrp.so
SOOBJS =  MmsEntityNatureGrp.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
