CREATE TABLE PSP_REDIRECT_SETTING
(
  PRS_PARTY_TYPE        CHAR(1 BYTE),
  PRS_PARTY_ID          VARCHAR2(15 BYTE),
  PRS_INTERVAL_START    INTEGER,
  PRS_INTERVAL_END      INTEGER,
  PRS_LAST_CHECK_TIME   DATE,
  PRS_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  PRS_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  PRS_CREATE_USER       VARCHAR2(20 BYTE),
  PRS_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PSP_REDIRECT_SETTING_PK ON PSP_REDIRECT_SETTING
(PRS_PARTY_TYPE, PRS_PARTY_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PSP_REDIRECT_SETTING ADD (
  CONSTRAINT PSP_REDIRECT_SETTING_PK
  PRIMARY KEY
  (PRS_PARTY_TYPE, PRS_PARTY_ID)
  USING INDEX PSP_REDIRECT_SETTING_PK
  ENABLE VALIDATE);

