OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/TxnWebLog
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBTxnWebLog.so
SOOBJS =  TxnWebLog.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
