OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLTxnRelation
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLTxnRelation.so
SOOBJS =  OLTxnRelation.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
