OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOMMSTxnElement
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOMMSTxnElement.so
SOOBJS = BOMMSTxnElement.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
