OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLTxnEngineStatusRule
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLTxnEngineStatusRule.so
SOOBJS =  OLTxnEngineStatusRule.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
