ALTER TABLE OL_ACCT_FILE_DETAIL 
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_ACCT_FILE_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE OL_ACCT_FILE_DETAIL 
(
  AFD_FILE_ID			NUMBER(16), 
  AFD_SEQ			INTEGER, 
  AFD_PROVIDER_NAME		VARCHAR2(50 BYTE), 
  AFD_PROVIDER_ID		VARCHAR2(10 BYTE), 
  AFD_ACCT_TYPE			CHAR(3 BYTE), 
  AFD_BANK_NAME			VARCHAR2(50 BYTE), 
  AFD_INT_BANK_CODE		VARCHAR2(10 BYTE), 
  AFD_BANK_ACCT_NUM		VARCHAR2(50 BYTE), 
  AFD_BANK_ACCT_SHORT_NAME	VARCHAR2(20 BYTE), 
  AFD_OWNER_NAME		VARCHAR2(50 BYTE), 
  AFD_PROVINCE			VARCHAR2(100 BYTE), 
  AFD_CITY			VARCHAR2(100 BYTE), 
  AFD_BRANCH_NAME		VARCHAR2(150 BYTE), 
  AFD_INIT_BAL			NUMBER(14,2), 
  AFD_SUPPORT_SMS_STMT		INTEGER, 
  AFD_REGISTERED_MOBILE		VARCHAR2(20 BYTE), 
  AFD_APPLY_DEPOSIT_COST	INTEGER, 
  AFD_MERCHANT_SHORT_NAME	VARCHAR2(20 BYTE), 
  AFD_MERCHANT_ID		VARCHAR2(15 BYTE), 
  AFD_CREATE_USER		VARCHAR2(20 BYTE), 
  AFD_CREATE_TIMESTAMP		DATE			DEFAULT sysdate, 
  AFD_UPDATE_USER		VARCHAR2(20 BYTE), 
  AFD_UPDATE_TIMESTAMP		DATE			DEFAULT sysdate
) 
TABLESPACE USER_DATA 
PCTUSED    0 
PCTFREE    10 
INITRANS   1 
MAXTRANS   255 
STORAGE    (
            INITIAL     64K 
            NEXT        1M 
            MINEXTENTS  1 
            MAXEXTENTS  UNLIMITED 
            PCTINCREASE 0 
            BUFFER_POOL DEFAULT
           ) 
LOGGING 
NOCOMPRESS 
NOCACHE 
MONITORING;

CREATE UNIQUE INDEX OL_ACCT_FILE_DETAIL_PK ON OL_ACCT_FILE_DETAIL 
(AFD_FILE_ID, AFD_SEQ) 
LOGGING 
TABLESPACE USER_IDX 
PCTFREE    10 
INITRANS   2 
MAXTRANS   255 
STORAGE    (
            INITIAL     64K 
            NEXT        1M 
            MINEXTENTS  1 
            MAXEXTENTS  UNLIMITED 
            PCTINCREASE 0 
            BUFFER_POOL DEFAULT
           );

CREATE INDEX OL_ACCT_FILE_DETAIL_IDX01 ON OL_ACCT_FILE_DETAIL 
(AFD_CREATE_TIMESTAMP, AFD_UPDATE_TIMESTAMP) 
LOGGING 
TABLESPACE USER_IDX 
PCTFREE    10 
INITRANS   2 
MAXTRANS   255 
STORAGE    (
            INITIAL          64K 
            NEXT             1M 
            MINEXTENTS       1 
            MAXEXTENTS       UNLIMITED 
            PCTINCREASE      0 
            BUFFER_POOL      DEFAULT 
            FLASH_CACHE      DEFAULT 
            CELL_FLASH_CACHE DEFAULT
           ) 
NOPARALLEL;

ALTER TABLE OL_ACCT_FILE_DETAIL ADD 
(
  CONSTRAINT OL_ACCT_FILE_DETAIL_PK 
  PRIMARY KEY 
  (AFD_FILE_ID, AFD_SEQ) 
  USING INDEX OL_ACCT_FILE_DETAIL_PK 
  ENABLE VALIDATE
);

ALTER TABLE OL_ACCT_FILE_DETAIL ADD 
(
  CONSTRAINT OL_ACCT_FILE_DETAIL_FK01 
  FOREIGN KEY (AFD_FILE_ID) 
  REFERENCES OL_ACCT_FILE_HEADER (ACH_FILE_ID) 
  ENABLE VALIDATE
);
