ALTER TABLE OL_ACCT_FILE_HEADER 
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_ACCT_FILE_HEADER CASCADE CONSTRAINTS;

CREATE TABLE OL_ACCT_FILE_HEADER 
(
  ACH_FILE_ID		NUMBER(16), 
  ACH_RAW_FILENAME	VARCHAR2(100 BYTE), 
  ACH_CONVERT_FILENAME	VARCHAR2(100 BYTE), 
  ACH_TOTAL_COUNT	INTEGER			DEFAULT 0, 
  ACH_ACCEPT_COUNT	INTEGER			DEFAULT 0, 
  ACH_STATUS		CHAR(1 BYTE), 
  ACH_MSG_CODE		NUMBER(8), 
  ACH_CREATE_USER	VARCHAR2(20 BYTE), 
  ACH_CREATE_TIMESTAMP	DATE			DEFAULT sysdate, 
  ACH_UPDATE_USER	VARCHAR2(20 BYTE), 
  ACH_UPDATE_TIMESTAMP	DATE			DEFAULT sysdate
) 
TABLESPACE USER_DATA 
PCTUSED    0 
PCTFREE    10 
INITRANS   1 
MAXTRANS   255 
STORAGE    (
            INITIAL     64K 
            NEXT        1M 
            MINEXTENTS  1 
            MAXEXTENTS  UNLIMITED 
            PCTINCREASE 0 
            BUFFER_POOL DEFAULT
           ) 
LOGGING 
NOCOMPRESS 
NOCACHE 
MONITORING;

CREATE UNIQUE INDEX OL_ACCT_FILE_HEADER_PK ON OL_ACCT_FILE_HEADER 
(ACH_FILE_ID) 
LOGGING 
TABLESPACE USER_IDX 
PCTFREE    10 
INITRANS   2 
MAXTRANS   255 
STORAGE    (
            INITIAL     64K 
            NEXT        1M 
            MINEXTENTS  1 
            MAXEXTENTS  UNLIMITED 
            PCTINCREASE 0 
            BUFFER_POOL DEFAULT
           );

CREATE INDEX OL_ACCT_FILE_HEADER_IDX01 ON OL_ACCT_FILE_HEADER 
(ACH_RAW_FILENAME) 
LOGGING 
TABLESPACE USER_IDX 
PCTFREE    10 
INITRANS   2 
MAXTRANS   255 
STORAGE    (
            INITIAL          64K 
            NEXT             1M 
            MINEXTENTS       1 
            MAXEXTENTS       UNLIMITED 
            PCTINCREASE      0 
            BUFFER_POOL      DEFAULT 
            FLASH_CACHE      DEFAULT 
            CELL_FLASH_CACHE DEFAULT
           ) 
NOPARALLEL;

CREATE INDEX OL_ACCT_FILE_HEADER_IDX02 ON OL_ACCT_FILE_HEADER 
(ACH_CONVERT_FILENAME) 
LOGGING 
TABLESPACE USER_IDX 
PCTFREE    10 
INITRANS   2 
MAXTRANS   255 
STORAGE    (
            INITIAL          64K 
            NEXT             1M 
            MINEXTENTS       1 
            MAXEXTENTS       UNLIMITED 
            PCTINCREASE      0 
            BUFFER_POOL      DEFAULT 
            FLASH_CACHE      DEFAULT 
            CELL_FLASH_CACHE DEFAULT
           ) 
NOPARALLEL;

CREATE INDEX OL_ACCT_FILE_HEADER_IDX03 ON OL_ACCT_FILE_HEADER 
(ACH_CREATE_TIMESTAMP, ACH_UPDATE_TIMESTAMP) 
LOGGING 
TABLESPACE USER_IDX 
PCTFREE    10 
INITRANS   2 
MAXTRANS   255 
STORAGE    (
            INITIAL          64K 
            NEXT             1M 
            MINEXTENTS       1 
            MAXEXTENTS       UNLIMITED 
            PCTINCREASE      0 
            BUFFER_POOL      DEFAULT 
            FLASH_CACHE      DEFAULT 
            CELL_FLASH_CACHE DEFAULT
           ) 
NOPARALLEL;

CREATE INDEX OL_ACCT_FILE_HEADER_IDX04 ON OL_ACCT_FILE_HEADER 
(ACH_STATUS) 
LOGGING 
TABLESPACE USER_IDX 
PCTFREE    10 
INITRANS   2 
MAXTRANS   255 
STORAGE    (
            INITIAL          64K 
            NEXT             1M 
            MINEXTENTS       1 
            MAXEXTENTS       UNLIMITED 
            PCTINCREASE      0 
            BUFFER_POOL      DEFAULT 
            FLASH_CACHE      DEFAULT 
            CELL_FLASH_CACHE DEFAULT
           ) 
NOPARALLEL;

ALTER TABLE OL_ACCT_FILE_HEADER ADD 
(
  CONSTRAINT OL_ACCT_FILE_HEADER_PK 
  PRIMARY KEY 
  (ACH_FILE_ID) 
  USING INDEX OL_ACCT_FILE_HEADER_PK 
  ENABLE VALIDATE
);

ALTER TABLE OL_ACCT_FILE_HEADER ADD 
(
  CONSTRAINT OL_ACCT_FILE_HEADER_FK01 
  FOREIGN KEY (ACH_STATUS) 
  REFERENCES OL_DEF_ACCT_FILE_STATUS (AFS_TYPE) 
  ENABLE VALIDATE
);
