ALTER TABLE OL_ACCT_FILE_ERROR 
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_ACCT_FILE_ERROR CASCADE CONSTRAINTS;

CREATE TABLE OL_ACCT_FILE_ERROR 
(
  AFE_ERROR_ID		NUMBER(16), 
  AFE_FILE_ID		NUMBER(16), 
  AFE_SEQ		INTEGER, 
  AFE_MSG_CODE		NUMBER(8), 
  AFE_LINE_CONTENT	VARCHAR2(1024 BYTE), 
  AFE_CREATE_USER	VARCHAR2(20 BYTE), 
  AFE_CREATE_TIMESTAMP	DATE			DEFAULT sysdate, 
  AFE_UPDATE_USER	VARCHAR2(20 BYTE), 
  AFE_UPDATE_TIMESTAMP	DATE			DEFAULT sysdate
) 
TABLESPACE USER_DATA 
PCTUSED    0 
PCTFREE    10 
INITRANS   1 
MAXTRANS   255 
STORAGE    (
            INITIAL     64K 
            NEXT        1M 
            MINEXTENTS  1 
            MAXEXTENTS  UNLIMITED 
            PCTINCREASE 0 
            BUFFER_POOL DEFAULT
           ) 
LOGGING 
NOCOMPRESS 
NOCACHE 
MONITORING;

CREATE UNIQUE INDEX OL_ACCT_FILE_ERROR_PK ON OL_ACCT_FILE_ERROR 
(AFE_ERROR_ID) 
LOGGING 
TABLESPACE USER_IDX 
PCTFREE    10 
INITRANS   2 
MAXTRANS   255 
STORAGE    (
            INITIAL     64K 
            NEXT        1M 
            MINEXTENTS  1 
            MAXEXTENTS  UNLIMITED 
            PCTINCREASE 0 
            BUFFER_POOL DEFAULT
           );

CREATE INDEX OL_ACCT_FILE_ERROR_IDX01 ON OL_ACCT_FILE_ERROR 
(AFE_CREATE_TIMESTAMP, AFE_UPDATE_TIMESTAMP) 
LOGGING 
TABLESPACE USER_IDX 
PCTFREE    10 
INITRANS   2 
MAXTRANS   255 
STORAGE    (
            INITIAL          64K 
            NEXT             1M 
            MINEXTENTS       1 
            MAXEXTENTS       UNLIMITED 
            PCTINCREASE      0 
            BUFFER_POOL      DEFAULT 
            FLASH_CACHE      DEFAULT 
            CELL_FLASH_CACHE DEFAULT
           ) 
NOPARALLEL;

ALTER TABLE OL_ACCT_FILE_ERROR ADD 
(
  CONSTRAINT OL_ACCT_FILE_ERROR_PK 
  PRIMARY KEY 
  (AFE_ERROR_ID) 
  USING INDEX OL_ACCT_FILE_ERROR_PK 
  ENABLE VALIDATE
);

ALTER TABLE OL_ACCT_FILE_ERROR ADD 
(
  CONSTRAINT OL_ACCT_FILE_ERROR_FK01 
  FOREIGN KEY (AFE_FILE_ID) 
  REFERENCES OL_ACCT_FILE_HEADER (ACH_FILE_ID) 
  ENABLE VALIDATE
);
