OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MiBatchRelation
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMiBatchRelation.so
SOOBJS =  MiBatchRelation.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
