OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOMMSEntityBalAcct
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOMMSEntityBalAcct.so
SOOBJS = BOMMSEntityBalAcct.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
