ALTER TABLE DEF_CURRENCY
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_CURRENCY CASCADE CONSTRAINTS;

CREATE TABLE DEF_CURRENCY
(
  DC_CCY_ID            VARCHAR2(3 BYTE)         NOT NULL,
  DC_DESC              VARCHAR2(50 BYTE),
  DC_CREATE_USER       VARCHAR2(20 BYTE),
  DC_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  DC_UPDATE_USER       VARCHAR2(20 BYTE),
  DC_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEF_CURRENCY_PK ON DEF_CURRENCY
(DC_CCY_ID)
LOGGING
TABLESPACE USER_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_CURRENCY ADD (
  CONSTRAINT DEF_CURRENCY_PK
  PRIMARY KEY
  (DC_CCY_ID)
  USING INDEX DEF_CURRENCY_PK
  ENABLE VALIDATE);

