ALTER TABLE TEST_ANDY DROP PRIMARY KEY CASCADE;

DROP TABLE TEST_ANDY CASCADE CONSTRAINTS;

CREATE TABLE TEST_ANDY
(
	TA_BANK_CODE			VARCHAR2(10 BYTE),
	TA_TYPE				CHAR(1 BYTE)			NOT NULL,
	TA_SUPPORT_PO			INTEGER				DEFAULT 0,
	TA_MIN_AMT			NUMBER(14,2)			DEFAULT 0.0,
	TA_REMARK			VARCHAR2(255 BYTE),
	TA_CREATE_USER			VARCHAR2(20 BYTE),
	TA_CREATE_TIMESTAMP		DATE				DEFAULT sysdate,
	TA_UPDATE_USER			VARCHAR2(20 BYTE),
	TA_UPDATE_TIMESTAMP		DATE				DEFAULT sysdate
)
TABLESPACE 	USER_DATA
PCTUSED		0
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE		(
			INITIAL				64K
			NEXT				1M
			MINEXTENTS			1
			MAXEXTENTS			UNLIMITED
			PCTINCREASE			0
			BUFFER_POOL			DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;

CREATE UNIQUE INDEX TEST_ANDY_PK ON TEST_ANDY
(TA_BANK_CODE)
LOGGING
TABLESPACE 	USER_IDX
PCTFREE		10
INITRANS	2
MAXTRANS	255
STORAGE		(
			INITIAL				64K
			NEXT				1M
			MINEXTENTS			1
			MAXEXTENTS			UNLIMITED
			PCTINCREASE			0
			BUFFER_POOL			DEFAULT
		);

ALTER TABLE TEST_ANDY ADD 
(
	CONSTRAINT TEST_ANDY_PK
	PRIMARY KEY (TA_BANK_CODE)
	USING INDEX TEST_ANDY_PK
	ENABLE VALIDATE
);

ALTER TABLE TEST_ANDY ADD
(
        CONSTRAINT TEST_ANDY_FK01
        FOREIGN KEY (TA_BANK_CODE)
	REFERENCES DEF_BANK (DB_INT_BANK_CODE)
        ENABLE VALIDATE
);
