

insert into OL_AUTO_UPLOAD_STMT_SETTING (OAUS_JOB_ID, OAUS_SERVER_ID, OAUS_PROVIDER_PATHNAME, OAUS_NATURE, OAUS_LEVEL, OAUS_CREATE_TIMESTAMP, OAUS_CREATE_USER, OAUS_UPDATE_TIMESTAMP, OAUS_UPDATE_USER, OAUS_DISABLED, OAUS_PROVIDER_ID, OAUS_NATURE_PATH, OAUS_PROCESS_BANK_CODE)
values ((select nvl(max(OAUS_JOB_ID), 0) + 1 from OL_AUTO_UPLOAD_STMT_SETTING), '00', 'Provider_Andy', 'DSI', 0,  sysdate, 'SYSTEM', sysdate, 'SYSTEM', 0 , 'OCP0000179', 'Deposit_Statement', '000');