OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnWebOnUs2BFO
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnWebOnUs2BFO.so
SOOBJS = TxnWebOnUs2BFO.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
