OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MerchantBalAcct
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMerchantBalAcct.so
SOOBJS =  MerchantBalAcct.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
