ALTER TABLE MMM_TYPE_MAP
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMM_TYPE_MAP CASCADE CONSTRAINTS;

CREATE TABLE MMM_TYPE_MAP
(
  MTM_TYPE             CHAR(6 BYTE),
  MTM_TXN_CODE         CHAR(3 BYTE),
  MTM_CREATE_DATETIME  DATE                     DEFAULT sysdate,
  MTM_CREATE_USER      VARCHAR2(20 BYTE),
  MTM_UPDATE_DATETIME  DATE                     DEFAULT sysdate,
  MTM_UPDATE_USER      VARCHAR2(1 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MMM_TYPE_MAP_PK ON MMM_TYPE_MAP
(MTM_TYPE, MTM_TXN_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMM_TYPE_MAP ADD (
  CONSTRAINT MMM_TYPE_MAP_PK
  PRIMARY KEY
  (MTM_TYPE, MTM_TXN_CODE)
  USING INDEX MMM_TYPE_MAP_PK
  ENABLE VALIDATE);

ALTER TABLE MMM_TYPE_MAP ADD (
  CONSTRAINT MMM_TYPE_MAP_FK01 
  FOREIGN KEY (MTM_TYPE) 
  REFERENCES MMM_TXN_TYPE (MTT_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT MMM_TYPE_MAP_FK02 
  FOREIGN KEY (MTM_TXN_CODE) 
  REFERENCES TXN_CODE (TC_CODE)
  ENABLE VALIDATE);

