OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLMerchantUploadFileHeader
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLMerchantUploadFileHeader.so
SOOBJS =  OLMerchantUploadFileHeader.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
