OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=test_CheckPspStatus.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o test_CheckPspStatus.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
