CREATE TABLE OL_AUTO_UPLOAD_STMT_SETTING
(
  OAUS_JOB_ID             INTEGER,
  OAUS_SERVER_ID          VARCHAR2(3 BYTE),
  OAUS_PROVIDER_ID        VARCHAR2(10 BYTE),
  OAUS_PROVIDER_PATHNAME  VARCHAR2(50 BYTE),
  OAUS_NATURE             VARCHAR2(10 BYTE),
  OAUS_LEVEL              INTEGER,
  OAUS_PROCESS_BANK       VARCHAR2(10 BYTE),
  OAUS_DISABLED           INTEGER,
  OAUS_CREATE_TIMESTAMP   DATE                  DEFAULT sysdate,
  OAUS_CREATE_USER        VARCHAR2(20 BYTE),
  OAUS_UPDATE_TIMESTAMP   DATE                  DEFAULT sysdate,
  OAUS_UPDATE_USER        VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX OL_AUTO_UPLOAD_STMT_SETTING_PK ON OL_AUTO_UPLOAD_STMT_SETTING
(OAUS_JOB_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE OL_AUTO_UPLOAD_STMT_SETTING ADD (
  CONSTRAINT OL_AUTO_UPLOAD_STMT_SETTING_PK
  PRIMARY KEY
  (OAUS_JOB_ID)
  USING INDEX OL_AUTO_UPLOAD_STMT_SETTING_PK
  ENABLE VALIDATE);

