ALTER TABLE TXN_CODE
 ADD (TC_OFL_IS_OFFSET  INTEGER DEFAULT 0);



ALTER TABLE TXN_CODE
 ADD (TC_OFL_VOID_CODE  CHAR(3 BYTE));

ALTER TABLE TXN_CODE
 ADD (TC_OFL_IS_VOID  INTEGER                       DEFAULT 0);

ALTER TABLE TXN_CODE
 ADD (TC_OFL_ALLOW_CANCEL  INTEGER                  DEFAULT 0);

ALTER TABLE TXN_CODE
 ADD (TC_OFL_ALLOW_FE_INIT  INTEGER                 DEFAULT 0);
