ALTER TABLE OL_DEF_ENGINE_ACTIVITY
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_DEF_ENGINE_ACTIVITY CASCADE CONSTRAINTS;

CREATE TABLE OL_DEF_ENGINE_ACTIVITY
(
  DEA_TYPE              VARCHAR2(50 BYTE),
  DEA_DESC              VARCHAR2(100 BYTE),
  DEA_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  DEA_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  DEA_CREATE_USER       VARCHAR2(50 BYTE),
  DEA_UPDATE_USER       VARCHAR2(50 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_DEF_ENGINE_ACTIVITY_PK ON OL_DEF_ENGINE_ACTIVITY
(DEA_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_DEF_ENGINE_ACTIVITY ADD (
  CONSTRAINT OL_DEF_ENGINE_ACTIVITY_PK
  PRIMARY KEY
  (DEA_TYPE)
  USING INDEX PHUSER.OL_DEF_ENGINE_ACTIVITY_PK
  ENABLE VALIDATE);

