ALTER TABLE MMS_ENTITY_NATURE
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_ENTITY_NATURE CASCADE CONSTRAINTS;

CREATE TABLE MMS_ENTITY_NATURE
(
  MEN_NATURE_ID         VARCHAR2(20 BYTE),
  MEN_DESC              VARCHAR2(100 BYTE),
  MEN_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  MEN_CREATE_USER       VARCHAR2(20 BYTE),
  MEN_UPDATE_TIMESTAMP  DATE,
  MEN_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MMS_ENTITY_NATURE_PK ON MMS_ENTITY_NATURE
(MEN_NATURE_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_ENTITY_NATURE ADD (
  CONSTRAINT MMS_ENTITY_NATURE_PK
  PRIMARY KEY
  (MEN_NATURE_ID)
  USING INDEX MMS_ENTITY_NATURE_PK
  ENABLE VALIDATE);

