OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/PspReconHistory
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBPspReconHistory.so
SOOBJS =  PspReconHistory.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
