OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOMerchant
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOMerchant.so
SOOBJS = BOMerchant.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
