OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/ParDefMisc
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBParDefMisc.so
SOOBJS =  ParDefMisc.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
