ALTER TABLE DEF_MMS_MB
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_MMS_MB CASCADE CONSTRAINTS;

CREATE TABLE DEF_MMS_MB
(
  DMB_INT_MB_ID     VARCHAR2(20 BYTE),
  DMB_EXT_MB_ID     VARCHAR2(20 BYTE),
  DMB_CREATE_USER       VARCHAR2(20 BYTE),
  DMB_UPDATE_USER       VARCHAR2(20 BYTE),
  DMB_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  DMB_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEF_MMS_MB_PK ON DEF_MMS_MB
(DMB_INT_MB_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_MMS_MB ADD (
  CONSTRAINT DEF_MMS_MB_PK
  PRIMARY KEY
  (DMB_INT_MB_ID)
  USING INDEX DEF_MMS_MB_PK
  ENABLE VALIDATE);
