ALTER TABLE CPHUSER.PSP_COUNTRY
 DROP PRIMARY KEY CASCADE;

DROP TABLE CPHUSER.PSP_COUNTRY CASCADE CONSTRAINTS;

CREATE TABLE CPHUSER.PSP_COUNTRY
(
  COUNTRY           CHAR(2 BYTE),
  PSP_ID            VARCHAR2(10 BYTE),
  CREATE_TIMESTAMP  DATE,
  UPDATE_TIMESTAMP  DATE,
  CREATE_USER       VARCHAR2(20 BYTE),
  UPDATE_USER       VARCHAR2(20 BYTE),
  CURRENCY_ID       VARCHAR2(3 BYTE)       NOT NULL
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CPHUSER.PSP_COUNTRY_PK ON CPHUSER.PSP_COUNTRY
(PSP_ID, COUNTRY)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE CPHUSER.PSP_COUNTRY ADD (
  CONSTRAINT PSP_COUNTRY_PK
  PRIMARY KEY
  (PSP_ID, COUNTRY)
  USING INDEX CPHUSER.PSP_COUNTRY_PK);

ALTER TABLE PSP_COUNTRY ADD (
  CONSTRAINT PSP_COUNTRY_FK01
  FOREIGN KEY (CURRENCY_ID)
  REFERENCES DEF_CURRENCY (DC_CCY_ID));
