CREATE TABLE PSP_TXN_CHECK_RPT_PARAMETER
(
  PC_RPT_TYPE          VARCHAR2(50 BYTE)        NOT NULL,
  PC_CODE              VARCHAR2(50 BYTE)        NOT NULL,
  PC_DESC              VARCHAR2(240 BYTE),
  PC_VAL               VARCHAR2(1024 BYTE),
  PC_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  PC_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  PC_CREATE_USER       VARCHAR2(20 BYTE),
  PC_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PSP_TXN_CHECK_RPT_PARAMETER_PK ON PSP_TXN_CHECK_RPT_PARAMETER
(PC_RPT_TYPE, PC_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PSP_TXN_CHECK_RPT_PARAMETER ADD (
  CONSTRAINT PSP_TXN_CHECK_RPT_PARAMETER_PK
  PRIMARY KEY
  (PC_RPT_TYPE, PC_CODE)
  USING INDEX PSP_TXN_CHECK_RPT_PARAMETER_PK
  ENABLE VALIDATE);

