ALTER TABLE TXN_RPT_URL
 DROP PRIMARY KEY CASCADE;

DROP TABLE TXN_RPT_URL CASCADE CONSTRAINTS;

CREATE TABLE TXN_RPT_URL
(
  TXN_CODE          VARCHAR2(3 BYTE),
  SERVICE_CODE      VARCHAR2(5 BYTE),
  PAY_METHOD        VARCHAR2(4 BYTE),
  METHOD            VARCHAR2(3 BYTE),
  PATH              VARCHAR2(50 BYTE),
  EFFECT_DATE       DATE,
  DISABLED          INTEGER,
  CREATE_TIMESTAMP  DATE                        DEFAULT sysdate,
  UPDATE_TIMESTAMP  DATE                        DEFAULT sysdate,
  CREATE_USER       VARCHAR2(20 BYTE),
  UPDATE_USER       VARCHAR2(20 BYTE),
  LANGUAGE          CHAR(2 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN TXN_RPT_URL.METHOD IS 'TXT - CLEAR TXT, B64 Base64, SHA - SHA Encoding, MD5 - MD5 Encoding';



CREATE UNIQUE INDEX TXN_RPT_URL_PK ON TXN_RPT_URL
(TXN_CODE, SERVICE_CODE, PAY_METHOD, EFFECT_DATE, LANGUAGE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE TXN_RPT_URL ADD (
  CONSTRAINT TXN_RPT_URL_PK
  PRIMARY KEY
  (TXN_CODE, SERVICE_CODE, PAY_METHOD, EFFECT_DATE, LANGUAGE)
  USING INDEX TXN_RPT_URL_PK);

ALTER TABLE TXN_RPT_URL ADD (
  CONSTRAINT TXN_RPT_URL_FK01 
  FOREIGN KEY (PAY_METHOD) 
  REFERENCES DEF_PAY_METHOD (DP_CODE));

