ALTER TABLE MMS_ENTITY_PSP
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_ENTITY_PSP CASCADE CONSTRAINTS;

CREATE TABLE MMS_ENTITY_PSP
(
  MEP_NODE_ID           VARCHAR2(5 BYTE),
  MEP_CLIENT_ID         VARCHAR2(10 BYTE),
  MEP_PSP_ID            VARCHAR2(10 BYTE),
  MEP_BAID              VARCHAR2(20 BYTE),
  MEP_PSP_NAME          VARCHAR2(50 BYTE),
  MEP_BAID_NAME         VARCHAR2(100 BYTE),
  MEP_COUNTRY         	CHAR(2 BYTE),
  MEP_ENTITY_ID         VARCHAR2(20 BYTE)       NOT NULL,
  MEP_DEFAULT_NATURE_ID VARCHAR2(20 BYTE),
  MEP_CREATE_TIMESTAMP  DATE,
  MEP_CREATE_USER       VARCHAR2(20 BYTE),
  MEP_UPDATE_TIMESTAMP  DATE,
  MEP_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MMS_ENTITY_PSP_PK ON MMS_ENTITY_PSP
(MEP_NODE_ID, MEP_CLIENT_ID, MEP_PSP_ID, MEP_BAID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_ENTITY_PSP ADD (
  CONSTRAINT MMS_ENTITY_PSP_PK
  PRIMARY KEY
  (MEP_NODE_ID, MEP_CLIENT_ID, MEP_PSP_ID, MEP_BAID)
  USING INDEX MMS_ENTITY_PSP_PK
  ENABLE VALIDATE);

ALTER TABLE MMS_ENTITY_PSP ADD (
  CONSTRAINT MMS_ENTITY_PSP_FK01 
  FOREIGN KEY (MEP_ENTITY_ID) 
  REFERENCES MMS_ENTITY (ME_ID)
  ENABLE VALIDATE);

