OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOMMSTransaction
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOMMSTransaction.so
SOOBJS = BOMMSTransaction.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
