ALTER TABLE TXN_BROWSER_INFO
 DROP PRIMARY KEY CASCADE;

DROP TABLE TXN_BROWSER_INFO CASCADE CONSTRAINTS;

CREATE TABLE TXN_BROWSER_INFO
(
  TB_TXN_ID            VARCHAR2(16 BYTE),
  TB_CLIENT_IP         VARCHAR2(25 BYTE),
  TB_USER_AGENT        VARCHAR2(255 BYTE),
  TB_CREATE_USER       VARCHAR2(20 BYTE),
  TB_UPDATE_USER       VARCHAR2(20 BYTE),
  TB_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  TB_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX PHUSER.TXN_BROWSER_INFO_IDX01 ON PHUSER.TXN_BROWSER_INFO
(TB_TXN_ID, TB_CLIENT_IP)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX PHUSER.TXN_BROWSER_INFO_IDX02 ON PHUSER.TXN_BROWSER_INFO
(TB_TXN_ID, TB_USER_AGENT)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX TXN_BROWSER_INFO_PK ON TXN_BROWSER_INFO
(TB_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE TXN_BROWSER_INFO ADD (
  CONSTRAINT TXN_BROWSER_INFO_PK
  PRIMARY KEY
  (TB_TXN_ID)
  USING INDEX TXN_BROWSER_INFO_PK
  ENABLE VALIDATE);

ALTER TABLE TXN_BROWSER_INFO ADD (
  CONSTRAINT TXN_BROWSER_INFO_FK01 
  FOREIGN KEY (TB_TXN_ID) 
  REFERENCES TXN_HEADER (TH_TXN_ID)
  ENABLE VALIDATE);

