OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLBulkDetail
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLBulkDetail.so
SOOBJS =  OLBulkDetail.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
