OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/PayoutReturnBatchHd
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBPayoutReturnBatchHd.so
SOOBJS =  PayoutReturnBatchHd.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
