OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmsTxnRetry
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmsTxnRetry.so
SOOBJS =  MmsTxnRetry.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
