OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnMgtByUsVDR
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnMgtByUsVDR.so
SOOBJS = TxnMgtByUsVDR.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
