OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmsAcrBal
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmsAcrBal.so
SOOBJS =  MmsAcrBal.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
