OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/ChannelTxnMap
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBChannelTxnMap.so
SOOBJS =  ChannelTxnMap.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
