OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmsTransaction
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmsTransaction.so
SOOBJS =  MmsTransaction.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
