ALTER TABLE CRR_PROV_PRODUCT_CODE_MAP
 DROP PRIMARY KEY CASCADE;

DROP TABLE CRR_PROV_PRODUCT_CODE_MAP CASCADE CONSTRAINTS;

CREATE TABLE CRR_PROV_PRODUCT_CODE_MAP
(
  OPM_PROV_ID           VARCHAR2(10 BYTE),
  OPM_BUSINESS_TYPE     CHAR(1 BYTE),
  OPM_PRODUCT_CODE      VARCHAR2(3 BYTE),
  OPM_DISABLED          INTEGER                 DEFAULT 0,
  OPM_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  OPM_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  OPM_CREATE_USER       VARCHAR2(20 BYTE),
  OPM_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CRR_PROV_PRODUCT_CODE_M_PK ON CRR_PROV_PRODUCT_CODE_MAP
(OPM_PROV_ID, OPM_BUSINESS_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE CRR_PROV_PRODUCT_CODE_MAP ADD (
  CONSTRAINT CRR_PROV_PRODUCT_CODE_M_PK
  PRIMARY KEY
  (OPM_PROV_ID, OPM_BUSINESS_TYPE)
  USING INDEX CRR_PROV_PRODUCT_CODE_M_PK
  ENABLE VALIDATE);

