ALTER TABLE SYSTEM_ALERT
 DROP PRIMARY KEY CASCADE;

DROP TABLE SYSTEM_ALERT CASCADE CONSTRAINTS;

CREATE TABLE SYSTEM_ALERT
(
  SA_CODE              VARCHAR2(10 BYTE)        NOT NULL,
  SA_CHANNEL           VARCHAR2(10 BYTE)        NOT NULL,
  SA_SCRIPT            VARCHAR2(50 BYTE)        NOT NULL,
  SA_PARTIES           CHAR(1 BYTE)             NOT NULL,
  SA_SUBJECT           VARCHAR2(100 BYTE),
  SA_NAME              VARCHAR2(50 BYTE),
  SA_FROM              VARCHAR2(50 BYTE)        NOT NULL,
  SA_TO                VARCHAR2(1024 BYTE)      NOT NULL,
  SA_CC                VARCHAR2(1024 BYTE),
  SA_BCC               VARCHAR2(1024 BYTE),
  SA_CREATE_USER       VARCHAR2(20 BYTE),
  SA_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  SA_UPDATE_USER       VARCHAR2(20 BYTE),
  SA_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX SYSTEM_ALERT_PK ON SYSTEM_ALERT
(SA_CODE, SA_CHANNEL, SA_SCRIPT, SA_PARTIES)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE SYSTEM_ALERT ADD (
  CONSTRAINT SYSTEM_ALERT_PK
  PRIMARY KEY
  (SA_CODE, SA_CHANNEL, SA_SCRIPT, SA_PARTIES)
  USING INDEX SYSTEM_ALERT_PK
  ENABLE VALIDATE);

ALTER TABLE SYSTEM_ALERT ADD (
  FOREIGN KEY (SA_PARTIES) 
  REFERENCES DEF_PARTY_TYPE (DP_TYPE)
  ENABLE VALIDATE);

