OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLPayoutApiBatchHD
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLPayoutApiBatchHD.so
SOOBJS =  OLPayoutApiBatchHD.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
