ALTER TABLE OL_MERCHANT_UPLOAD_FILE_HEADER
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_MERCHANT_UPLOAD_FILE_HEADER CASCADE CONSTRAINTS;

CREATE TABLE OL_MERCHANT_UPLOAD_FILE_HEADER
(
  OUH_BATCH_ID          NUMBER(16,0),
  OUH_MERCHANT_ID       VARCHAR(15 BYTE),
  OUH_SERVICE_CODE      VARCHAR(3 BYTE),
  OUH_FILENAME	       VARCHAR2(50 BYTE),
  OUH_TXN_COUNT         INTEGER,
  OUH_TOTAL_TXN_AMT     NUMBER(14,2),
  OUH_DISABLED          INTEGER                  DEFAULT 0,
  OUH_POSTING_DATE      VARCHAR2(8 BYTE),
  OUH_CREATE_USER       VARCHAR2(20 BYTE),
  OUH_UPDATE_USER       VARCHAR2(20 BYTE),
  OUH_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  OUH_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX OL_MERCH_UPLOAD_FILE_HD_IDX01 ON OL_MERCHANT_UPLOAD_FILE_HEADER
(OUH_MERCHANT_ID, OUH_BATCH_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;



CREATE UNIQUE INDEX OL_MERCHANT_UPLOAD_FILE_HD_PK ON OL_MERCHANT_UPLOAD_FILE_HEADER
(OUH_BATCH_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_MERCHANT_UPLOAD_FILE_HEADER ADD (
  CONSTRAINT OL_MERCHANT_UPLOAD_FILE_HD_PK
  PRIMARY KEY
  (OUH_BATCH_ID)
  USING INDEX OL_MERCHANT_UPLOAD_FILE_HD_PK);
