ALTER TABLE OL_TXN_RELATION
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_TXN_RELATION CASCADE CONSTRAINTS;

CREATE TABLE OL_TXN_RELATION
(
  OTR_FR_TXN_PARTY_TYPE  VARCHAR2(10 BYTE),
  OTR_FR_TXN_ID          VARCHAR2(16 BYTE),
  OTR_TO_TXN_PARTY_TYPE  VARCHAR2(10 BYTE),
  OTR_TO_TXN_ID          VARCHAR2(16 BYTE),
  OTR_CREATE_TIMESTAMP   DATE,
  OTR_UPDATE_TIMESTAMP   DATE,
  OTR_CREATE_USER        VARCHAR2(20 BYTE),
  OTR_UPDATE_USER        VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX OL_TXN_RELATION_IDX01 ON OL_TXN_RELATION
(OTR_TO_TXN_PARTY_TYPE, OTR_TO_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX OL_TXN_RELATION_PK ON OL_TXN_RELATION
(OTR_FR_TXN_PARTY_TYPE, OTR_FR_TXN_ID, OTR_TO_TXN_PARTY_TYPE, OTR_TO_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_TXN_RELATION ADD (
  CONSTRAINT OL_TXN_RELATION_PK
  PRIMARY KEY
  (OTR_FR_TXN_PARTY_TYPE, OTR_FR_TXN_ID, OTR_TO_TXN_PARTY_TYPE, OTR_TO_TXN_ID)
  USING INDEX OL_TXN_RELATION_PK
  ENABLE VALIDATE);

ALTER TABLE OL_TXN_RELATION ADD (
  CONSTRAINT OL_TXN_RELATION_FK01 
  FOREIGN KEY (OTR_FR_TXN_PARTY_TYPE) 
  REFERENCES OL_DEF_ENGINE_PARTY (EP_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OL_TXN_RELATION_FK02 
  FOREIGN KEY (OTR_TO_TXN_ID) 
  REFERENCES OL_DEF_ENGINE_PARTY (EP_TYPE)
  ENABLE VALIDATE);

