OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLStmtConvertScript
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLStmtConvertScript.so
SOOBJS =  OLStmtConvertScript.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
