OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOBankCharge
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOBankCharge.so
SOOBJS = BOBankCharge.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
