OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/TxnCctAckRetry
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBTxnCctAckRetry.so
SOOBJS =  TxnCctAckRetry.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
