OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/PspCosts
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBPspCosts.so
SOOBJS =  PspCosts.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
