OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/TestZale
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBTestZale.so
SOOBJS = TestZale.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
