OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=par_update_mismatch_list.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o par_update_mismatch_list.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
