OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=par_merchant_detail.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o par_merchant_detail.o
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lc -lm -lmyhash  -lObjPtr -lmyrecordset
all: $(BATCHEXE)
