ALTER TABLE MERCHANT_PAY_METHOD
 DROP PRIMARY KEY CASCADE;

DROP TABLE MERCHANT_PAY_METHOD CASCADE CONSTRAINTS;

CREATE TABLE MERCHANT_PAY_METHOD
(
  PM_MERCHANT_ID       VARCHAR2(15 BYTE),
  PM_PAY_METHOD    VARCHAR2(4 BYTE),
  PM_DISABLED          INTEGER,
  PM_CREATE_TIMESTAMP  DATE                     DEFAULT SYSDATE,
  PM_CREATE_USER       VARCHAR2(20 BYTE),
  PM_UPDATE_TIMESTAMP  DATE                     DEFAULT SYSDATE,
  PM_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX MERCHANT_PAY_METHOD_IDX01 ON MERCHANT_PAY_METHOD
(PM_DISABLED)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX MERCHANT_PAY_METHOD_PK ON MERCHANT_PAY_METHOD
(PM_MERCHANT_ID, PM_PAY_METHOD)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE MERCHANT_PAY_METHOD ADD (
  CONSTRAINT MERCHANT_PAY_METHOD_PK
  PRIMARY KEY
  (PM_MERCHANT_ID, PM_PAY_METHOD)
  USING INDEX MERCHANT_PAY_METHOD_PK);


ALTER TABLE MERCHANT_PAY_METHOD ADD (
  CONSTRAINT MERCHANT_PAY_METHOD_FK01 
  FOREIGN KEY (PM_PAY_METHOD) 
  REFERENCES DEF_PAY_METHOD (DP_CODE)
  ENABLE VALIDATE);

