ALTER TABLE OL_PSP_BALANCE
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_PSP_BALANCE CASCADE CONSTRAINTS;

CREATE TABLE OL_PSP_BALANCE
(
  OL_PB_PSP_ID            VARCHAR2(10 BYTE),
  OL_PB_COUNTRY_ID        VARCHAR2(3 BYTE),
  OL_PB_CURRENCY_ID       VARCHAR2(3 BYTE),
  OL_PB_BAL               NUMBER(14,2)          DEFAULT 0,
  OL_PB_TOTAL_FLOAT       NUMBER(14,2)          DEFAULT 0,
  OL_PB_TOTAL_HOLD        NUMBER(14,2)          DEFAULT 0,
  OL_PB_CREATE_TIMESTAMP  DATE                  DEFAULT sysdate,
  OL_PB_CREATE_USER       VARCHAR2(20 BYTE),
  OL_PB_UPDATE_TIMESTAMP  DATE                  DEFAULT sysdate,
  OL_PB_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_PSP_BALANCE_PK ON OL_PSP_BALANCE
(OL_PB_PSP_ID, OL_PB_COUNTRY_ID, OL_PB_CURRENCY_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_PSP_BALANCE ADD (
  CONSTRAINT OL_PSP_BALANCE_PK
  PRIMARY KEY
  (OL_PB_PSP_ID, OL_PB_COUNTRY_ID, OL_PB_CURRENCY_ID)
  USING INDEX OL_PSP_BALANCE_PK
  ENABLE VALIDATE);

