DROP TABLE PAYOUT_GENERATED_FILE_DT CASCADE CONSTRAINTS;

CREATE TABLE PAYOUT_GENERATED_FILE_DT
(
  FD_FILE_ID           NUMBER(16),
  FD_BATCH_ID          NUMBER(16),
  FD_SEQ_NUM           INTEGER,
  FD_UPLOAD_TXN_ID     VARCHAR2(16 BYTE),
  FD_TXN_ID            VARCHAR2(16 BYTE),
  FD_AUX_TXN_ID        VARCHAR2(16 BYTE),
  FD_STATUS            INTEGER,
  FD_MERCHANT_REF      VARCHAR2(25 BYTE),
  FD_COUNTRY           VARCHAR2(2 BYTE),
  FD_IDENTITY_ID       VARCHAR2(25 BYTE),
  FD_ACCOUNT_NUM       VARCHAR2(25 BYTE),
  FD_ACCOUNT_NAME      VARCHAR2(100 BYTE),
  FD_BANK_NAME         VARCHAR2(50 BYTE),
  FD_BANK_CODE         VARCHAR2(25 BYTE),
  FD_BRANCH            VARCHAR2(100 BYTE),
  FD_PHONE_NUM         VARCHAR2(25 BYTE),
  FD_PROVINCE          VARCHAR2(50 BYTE),
  FD_CITY              VARCHAR2(50 BYTE),
  FD_PAYOUT_AMOUNT     NUMBER(12,2)             DEFAULT 0,
  FD_REQUEST_AMOUNT    NUMBER(12,2)             DEFAULT 0,
  FD_PAYOUT_CURRENCY   VARCHAR2(3 BYTE),
  FD_REQUEST_CURRENCY  VARCHAR2(3 BYTE),
  FD_CREATE_USER       VARCHAR2(20 BYTE),
  FD_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  FD_UPDATE_USER       VARCHAR2(20 BYTE),
  FD_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX PAYOUT_GENERATED_FILE_DT_IDX01 ON PAYOUT_GENERATED_FILE_DT
(FD_FILE_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX PAYOUT_GENERATED_FILE_DT_IDX02 ON PAYOUT_GENERATED_FILE_DT
(FD_FILE_ID, FD_UPLOAD_TXN_ID, FD_STATUS)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

CREATE INDEX PAYOUT_GENERATED_FILE_DT_IDX03 ON PAYOUT_GENERATED_FILE_DT
(FD_FILE_ID, FD_BATCH_ID, FD_SEQ_NUM)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

CREATE INDEX PAYOUT_GENERATED_FILE_DT_IDX04 ON PAYOUT_GENERATED_FILE_DT
(FD_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX PAYOUT_GENERATED_FILE_DT_PK ON PAYOUT_GENERATED_FILE_DT
(FD_FILE_ID, FD_UPLOAD_TXN_ID, FD_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

