OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLBaidInterLogGen
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLBaidInterLogGen.so
SOOBJS =  OLBaidInterLogGen.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
