LTER TABLE CRR_GL_GROUP
 DROP PRIMARY KEY CASCADE;

DROP TABLE CRR_GL_GROUP CASCADE CONSTRAINTS;

CREATE TABLE CRR_GL_GROUP
(
  GL_GROUP_ID              	INT	NOT NULL,
  NAME					 						VARCHAR2(50 BYTE),
  ORDERING								  INT,
	STATUS										VARCHAR2(1)	DEFAULT 'A',
	DISABLED									INT	DEFAULT 0,  
	CREATE_TIMESTAMP	DATE	DEFAULT SYSDATE,
	UPDATE_TIMESTAMP	DATE	DEFAULT SYSDATE,
	CREATE_USER	VARCHAR2(20),
	UPDATE_USER	VARCHAR2(20)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX CRR_GL_GROUP_PK ON CRR_GL_GROUP
(GL_GROUP_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE CRR_GL_GROUP ADD (
  CONSTRAINT CRR_GL_GROUP_PK
  PRIMARY KEY
  (GL_GROUP_ID)
  USING INDEX CRR_GL_GROUP_PK);
  


