OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLTmpApi
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLTmpApi.so
SOOBJS = OLTmpApi.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
