ALTER TABLE PHUSER.MERCH_STATISTIC
 DROP PRIMARY KEY CASCADE;

DROP TABLE PHUSER.MERCH_STATISTIC CASCADE CONSTRAINTS;

CREATE TABLE PHUSER.MERCH_STATISTIC
(
  MERCHANT_ID       VARCHAR2(15 BYTE)           NOT NULL,
  TXN_DATE          VARCHAR2(8 BYTE)            NOT NULL,
  PSP_ID            VARCHAR2(10 BYTE)           NOT NULL,
  TXN_CCY           VARCHAR2(3 BYTE)            NOT NULL,
  TXN_COUNTRY       VARCHAR2(2 BYTE)            NOT NULL,
  TXN_AMOUNT        NUMBER(12,2),
  TXN_COUNT         INTEGER                     DEFAULT 1                     NOT NULL,
  MIN_AMOUNT        NUMBER(12,2),
  MAX_AMOUNT        NUMBER(12,2),
  CREATE_USER       VARCHAR2(20 BYTE),
  UPDATE_USER       VARCHAR2(20 BYTE),
  CREATE_TIMESTAMP  DATE,
  UPDATE_TIMESTAMP  DATE
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PHUSER.MERCH_STATISTIC_PK ON PHUSER.MERCH_STATISTIC
(MERCHANT_ID, TXN_DATE, PSP_ID, TXN_CCY, TXN_COUNTRY)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE PHUSER.MERCH_STATISTIC ADD (
  CONSTRAINT MERCH_STATISTIC_PK
  PRIMARY KEY
  (MERCHANT_ID, TXN_DATE, PSP_ID, TXN_CCY, TXN_COUNTRY)
  USING INDEX PHUSER.MERCH_STATISTIC_PK);

