ALTER TABLE OL_DEF_BAID_TXN_STATUS_MAP
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_DEF_BAID_TXN_STATUS_MAP CASCADE CONSTRAINTS;

CREATE TABLE OL_DEF_BAID_TXN_STATUS_MAP
(
  BSM_TYPE              CHAR(1 BYTE),
  BSM_STATUS            CHAR(1 BYTE),
  BSM_AR_IND            CHAR(1 BYTE)             DEFAULT ' ',
  BSM_TXN_CODE          CHAR(3 BYTE),
  BSM_STATUS_DESC       VARCHAR2(50 BYTE),
  BSM_CREATE_USER       VARCHAR2(20 BYTE),
  BSM_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  BSM_UPDATE_USER       VARCHAR2(20 BYTE),
  BSM_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN OL_DEF_BAID_TXN_STATUS_MAP.BSM_TYPE IS '''A'' - Admin ''M'' - Merchant';



CREATE UNIQUE INDEX OL_DEF_BAID_TXN_STATUS_MAP_PK ON OL_DEF_BAID_TXN_STATUS_MAP
(BSM_TYPE, BSM_STATUS, BSM_AR_IND, BSM_TXN_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_DEF_BAID_TXN_STATUS_MAP ADD (
  CONSTRAINT OL_DEF_BAID_TXN_STATUS_MAP_PK
  PRIMARY KEY
  (BSM_TYPE, BSM_STATUS, BSM_AR_IND, BSM_TXN_CODE)
  USING INDEX OL_DEF_BAID_TXN_STATUS_MAP_PK
  ENABLE VALIDATE);

