OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/InternalMessages
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBInternalMessages.so
SOOBJS =  InternalMessages.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
