ALTER TABLE OL_RULE_PAYPAGE_BANK
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_RULE_PAYPAGE_BANK CASCADE CONSTRAINTS;

CREATE TABLE OL_RULE_PAYPAGE_BANK
(
  RPB_PARTY_TYPE        CHAR(1 BYTE),
  RPB_PARTY_ID          VARCHAR2(15 BYTE),
  RPB_INT_BANK_CODE     VARCHAR2(10 BYTE),
  RPB_DISABLED          INTEGER,
  RPB_DISPLAY_ORDER     INTEGER,
  RPB_CREATE_TIMESTAMP  DATE,
  RPB_CREATE_USER       VARCHAR2(20 BYTE),
  RPB_UPDATE_TIMESTAMP  DATE,
  RPB_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_RULE_PAYPAGE_BANK_PK ON OL_RULE_PAYPAGE_BANK
(RPB_PARTY_TYPE, RPB_PARTY_ID, RPB_INT_BANK_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_RULE_PAYPAGE_BANK ADD (
  CONSTRAINT OL_RULE_PAYPAGE_BANK_PK
  PRIMARY KEY
  (RPB_PARTY_TYPE, RPB_PARTY_ID, RPB_INT_BANK_CODE)
  USING INDEX OL_RULE_PAYPAGE_BANK_PK
  ENABLE VALIDATE);

