

CREATE TABLE OL_PAYOUT_API_PREGEN_DT
(
  OAG_BATCH_ID          NUMBER(16),
  OAG_SEQ               INTEGER,
  OAG_TXN_ID            VARCHAR2(16 BYTE)       NOT NULL,
  OAG_PSP_ID            VARCHAR2(10 BYTE),
  OAG_BANK_CODE         VARCHAR2(25 BYTE),
  OAG_FILE_ID           NUMBER(16),
  OAG_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate               NOT NULL,
  OAG_CREATE_USER       VARCHAR2(20 BYTE),
  OAG_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate               NOT NULL,
  OAG_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE INDEX OL_PAYOUT_API_PREGEN_DT_IDX01 ON OL_PAYOUT_API_PREGEN_DT
(OAG_CREATE_TIMESTAMP, OAG_UPDATE_TIMESTAMP)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX OL_PAYOUT_API_PREGEN_DT_PK ON OL_PAYOUT_API_PREGEN_DT
(OAG_BATCH_ID, OAG_SEQ)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX OL_PAYOUT_API_PREGEN_DT_UK01 ON OL_PAYOUT_API_PREGEN_DT
(OAG_BATCH_ID, OAG_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE OL_PAYOUT_API_PREGEN_DT ADD (
  CONSTRAINT OL_PAYOUT_API_PREGEN_DT_PK
  PRIMARY KEY
  (OAG_BATCH_ID, OAG_SEQ)
  USING INDEX OL_PAYOUT_API_PREGEN_DT_PK
  ENABLE VALIDATE,
  CONSTRAINT OL_PAYOUT_API_PREGEN_DT_UK01
  UNIQUE (OAG_BATCH_ID, OAG_TXN_ID)
  USING INDEX OL_PAYOUT_API_PREGEN_DT_UK01
  ENABLE VALIDATE);

