OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnWebOnUsDGP
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnWebOnUsDGP.so
SOOBJS = TxnWebOnUsDGP.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
