CREATE OR REPLACE FUNCTION SP_OMI_BAL_COLLECT(
    IN_END_DATE IN DATE )
RETURN NUMBER IS
	EXP_ERR  EXCEPTION;
	EXP_ERR2 EXCEPTION;
	DATE_ERR EXCEPTION;

	V_NEW_BATCH_ID 		OMI_HIST_BAL_BATCH.OMI_BATCH_ID%type;
	V_PREV_BATCH_ID 	OMI_HIST_BAL_BATCH.OMI_BATCH_ID%type;
	V_START_DATE         	DATE;
	V_ADD_RANGE_END_DATE 	DATE; 
	V_ACCT_BAL 		OL_TXN_MI_DETAIL.OTM_ACCT_BAL%type; 
	V_INTRANSIT 		OL_TXN_MI_DETAIL.OTM_INTRANSIT%type; 
	V_AR_BAL 		OL_TXN_MI_DETAIL.OTM_AR_BAL%type; 
	V_BAL 			OL_TXN_MI_DETAIL.OTM_ACCT_BAL%type; 
	V_NET_BAL 		OL_TXN_MI_DETAIL.OTM_ACCT_BAL%type; 
	V_MID_BAL 		OMI_HIST_BAL_DETAIL.OMID_BAL%type;
	V_MID_BAL_HKD 		OMI_HIST_BAL_DETAIL.OMID_BAL_HKD%type;
	V_MID_BAL_USD 		OMI_HIST_BAL_DETAIL.OMID_BAL_USD%type;
	V_MID_TXN_ID 		OMI_HIST_BAL_DETAIL.OMID_TXN_ID%type;
	V_HKD_RATE 		EXCHANGE_RATE.EX_MED_ASK%type;
	V_USD_RATE 		EXCHANGE_RATE.EX_MED_ASK%type;
	V_COUNT_NO 		number; 
BEGIN
-- DBMS_OUTPUT.PUT_LINE('>>> START [OMI_BAL_COLLECT] <<<');
-- DBMS_OUTPUT.PUT_LINE('--> Input Date: '|| TO_CHAR(IN_END_DATE, 'YYYY-MM-DD HH24:MI') );
-- Find Prev Batch ID and current batch start date/time
	SELECT 	OMI_BATCH_ID,
		OMI_END_DATE
	INTO 	V_PREV_BATCH_ID,
		V_START_DATE
	FROM
	(SELECT OMI_BATCH_ID,
		OMI_END_DATE,
		ROW_NUMBER() OVER (PARTITION BY OMI_DISABLED ORDER BY OMI_END_DATE DESC) RN
	FROM OMI_HIST_BAL_BATCH
	WHERE OMI_DISABLED = 0
	)
	WHERE RN           = 1;

	IF SQL % ROWCOUNT != 1 THEN
		raise EXP_ERR2;
	END IF ;

	V_START_DATE := V_START_DATE + 1/24/60;
-- DBMS_OUTPUT.PUT_LINE('--> Start Date: '|| V_START_DATE );
-- DBMS_OUTPUT.PUT_LINE('--> End Date: '|| IN_END_DATE );

-- only look forward
	IF IN_END_DATE < V_START_DATE THEN
		raise DATE_ERR;
	END IF;
-- DBMS_OUTPUT.PUT_LINE('xxxx');

-- New Batch ID
	SELECT MAX(OMI_BATCH_ID) + 1
	INTO V_NEW_BATCH_ID
	FROM OMI_HIST_BAL_BATCH;
-- DBMS_OUTPUT.PUT_LINE('--> New Batch ID: ' || V_NEW_BATCH_ID );
-- DBMS_OUTPUT.PUT_LINE('--> Previous Batch ID: ' || V_PREV_BATCH_ID );

-- Add 1 mins to end times
	V_ADD_RANGE_END_DATE := IN_END_DATE + 1/24/60;
-- DBMS_OUTPUT.PUT_LINE('--> Add 1 mins end date: ' || V_ADD_RANGE_END_DATE );

-- Insert New Batch
	INSERT
	INTO OMI_HIST_BAL_BATCH
	(
		OMI_BATCH_ID,
		OMI_START_DATE,
		OMI_END_DATE,
		OMI_DISABLED,
		OMI_CREATE_TIMESTAMP,
		OMI_CREATE_USER
	)
	VALUES
	(
		V_NEW_BATCH_ID,
		V_START_DATE,
		IN_END_DATE,
		0,
		SYSDATE,
		'SYSTEM'
	);

	IF SQL % ROWCOUNT != 1 THEN
		raise EXP_ERR;
	END IF ;

-- DBMS_OUTPUT.PUT_LINE('--> Insert New Batch : OK');
-- Find PSP Last Txn from start times to end times
	FOR X IN
		(SELECT TXN_ID ,
			MI_ID ,
			ENTITY_TYPE ,
			TXN_CCY ,
			COUNTRY ,
			APPROVAL_TIMESTAMP
		FROM
		(SELECT TXN_ID ,
			MI_ID ,
			ENTITY_TYPE ,
			TXN_CCY ,
			COUNTRY ,
			APPROVAL_TIMESTAMP ,
			ROW_NUMBER() OVER ( PARTITION BY MI_ID , COUNTRY ,TXN_CCY ORDER BY APPROVAL_TIMESTAMP DESC ) RN
		FROM
		(SELECT TXN_ID ,
			MI_ID ,
			ENTITY_TYPE ,
			TXN_CCY ,
			COUNTRY ,
			APPROVAL_TIMESTAMP
		FROM
		(SELECT OTH_TXN_ID       AS TXN_ID ,
			OTM_ENTITY_ID          AS MI_ID ,
			ED_ENTITY_TYPE		   AS ENTITY_TYPE ,
			OTM_ENTITY_CCY 		   AS TXN_CCY ,
			OTM_TXN_COUNTRY        AS COUNTRY ,
			OTH_APPROVAL_TIMESTAMP AS APPROVAL_TIMESTAMP ,
			ROW_NUMBER() OVER ( PARTITION BY OTM_ENTITY_ID , OTM_TXN_COUNTRY , OTM_ENTITY_CCY ORDER BY OTH_APPROVAL_TIMESTAMP DESC ) RN
		FROM 	OL_TXN_MI_DETAIL ,
			OL_TXN_HEADER ,
			MI_ENTITY_DETAIL
		WHERE OTH_TXN_ID            = OTM_TXN_ID
		AND ED_ENTITY_ID = OTM_ENTITY_ID
		AND OTH_AR_IND              = 'A'
		AND OTM_ENTITY_CCY   is not null
		AND OTH_APPROVAL_TIMESTAMP >= CAST(V_START_DATE AS TIMESTAMP)
		AND OTH_APPROVAL_TIMESTAMP  < CAST(V_ADD_RANGE_END_DATE AS TIMESTAMP)
		AND OTM_ACCT_BAL           IS NOT NULL
		ORDER BY OTH_APPROVAL_TIMESTAMP DESC
		)
		WHERE RN = 1
		UNION
		SELECT OMID_TXN_ID       AS TXN_ID ,
			OMID_MI_ID             AS MI_ID ,
			OMID_ENTITY_TYPE       AS ENTITY_TYPE ,
			OMID_CCY               AS TXN_CCY ,
			OMID_COUNTRY           AS COUNTRY ,
			OTH_APPROVAL_TIMESTAMP AS APPROVAL_TIMESTAMP
		FROM OMI_HIST_BAL_DETAIL ,
			OL_TXN_HEADER
		WHERE OTH_TXN_ID  = OMID_TXN_ID
		AND OMID_BATCH_ID = V_PREV_BATCH_ID
		)
		ORDER BY APPROVAL_TIMESTAMP DESC
		)
		WHERE RN = 1
		)
	LOOP
-- DBMS_OUTPUT.PUT_LINE('--> MI_ID: [' || X.MI_ID || '] TXN_CCY: [' || X.TXN_CCY || ']  TXN_ID : [' || X.TXN_ID||'] COUNTRY : [' || X.COUNTRY||'] ');
	
	IF X.TXN_ID IS NOT NULL THEN
-- DBMS_OUTPUT.PUT_LINE('--> Txn Bal');
--  Txn Bal
	SELECT 
		NVL(OTM_ACCT_BAL, 0.00) + NVL(OTM_INTRANSIT, 0.00) AS BAL  
		,NVL(OTM_ACCT_BAL, 0.00) AS ACCT_BAL
		,NVL(OTM_INTRANSIT, 0.00) AS INTRANSIT
		,NVL(OTM_AR_BAL , 0.00) AS AR_BAL   
	 INTO 
		V_BAL ,
		V_ACCT_BAL ,
		V_INTRANSIT ,
		V_AR_BAL 
	FROM OL_TXN_MI_DETAIL 
	WHERE OTM_TXN_ID = X.TXN_ID; 
		
-- DBMS_OUTPUT.PUT_LINE('--> ACCT_BAL: [' || V_BAL ||']');
	
	SELECT count(*) AS COUNT_NO INTO V_COUNT_NO
	FROM OMI_HIST_BAL_DETAIL  
	WHERE OMID_MI_ID = X.MI_ID
	AND OMID_CCY = X.TXN_CCY
	AND OMID_COUNTRY = X.COUNTRY
        AND OMID_BATCH_ID = V_PREV_BATCH_ID;	
		
	IF V_COUNT_NO > 0 THEN
-- Prev Batch Bal	
		SELECT 
			OMID_TXN_ID ,
			NVL(OMID_BAL, 0.00) AS OMID_BAL ,
			NVL(OMID_BAL_HKD, 0.00) AS OMID_BAL_HKD ,
			NVL(OMID_BAL_USD, 0.00) AS OMID_BAL_USD 
		INTO 
			V_MID_TXN_ID,
			V_MID_BAL,
			V_MID_BAL_HKD,
			V_MID_BAL_USD
		FROM OMI_HIST_BAL_DETAIL  
		WHERE OMID_MI_ID = X.MI_ID
		AND OMID_CCY = X.TXN_CCY
		AND OMID_COUNTRY = X.COUNTRY
		AND OMID_BATCH_ID = V_PREV_BATCH_ID;	 
	ELSE
		V_MID_TXN_ID := 0;
		V_MID_BAL := 0.00;
		V_MID_BAL_HKD := 0.00;
		V_MID_BAL_USD := 0.00;
	END IF ; 
	
-- DBMS_OUTPUT.PUT_LINE('--> OMID_BAL: [' || V_MID_BAL || '] OMID_BAL_HKD: [' || V_MID_BAL_HKD ||'] OMID_BAL_USD: [' || V_MID_BAL_USD ||']');	

-- DBMS_OUTPUT.PUT_LINE('--> GET Rate');	  
-- HKD Rate , USD Rate	
	 SELECT
		RATE_HKD_TBL.RATE AS HKD_RATE,
		RATE_USD_TBL.RATE AS USD_RATE
	   INTO 
		V_HKD_RATE,
		V_USD_RATE
	FROM 
	(
		SELECT 
		  EX_MED_ASK AS RATE ,
		  EX_TO_CCY_ID
		FROM (
			SELECT EX_FROM_CCY_ID
				,EX_TO_CCY_ID
				,EX_MED_ASK
				,ROW_NUMBER() OVER (
					PARTITION BY EX_FROM_CCY_ID
					,EX_TO_CCY_ID ORDER BY EX_EFFECT_DATE DESC
				) XX
			FROM EXCHANGE_RATE
			WHERE EX_EFFECT_DATE < CAST(V_ADD_RANGE_END_DATE AS TIMESTAMP)
		)
		WHERE XX = 1
		AND EX_TO_CCY_ID = 'HKD'
		AND EX_FROM_CCY_ID = X.TXN_CCY
		) RATE_HKD_TBL 
		INNER JOIN (
		SELECT  
			EX_MED_ASK AS RATE ,
			EX_FROM_CCY_ID
		FROM (
			SELECT EX_FROM_CCY_ID
				,EX_TO_CCY_ID
				,EX_MED_ASK
				,ROW_NUMBER() OVER (
					PARTITION BY EX_FROM_CCY_ID
					,EX_TO_CCY_ID ORDER BY EX_EFFECT_DATE DESC
				) XX
			FROM EXCHANGE_RATE
			WHERE EX_EFFECT_DATE < CAST(V_ADD_RANGE_END_DATE AS TIMESTAMP)
		)
		WHERE XX = 1
		AND EX_FROM_CCY_ID = 'HKD'
		AND EX_TO_CCY_ID = 'USD'
		) RATE_USD_TBL ON RATE_HKD_TBL.EX_TO_CCY_ID = RATE_USD_TBL.EX_FROM_CCY_ID;

	IF X.TXN_ID != V_MID_TXN_ID THEN
		V_NET_BAL := V_BAL - V_MID_BAL ; 
	ELSE
		V_NET_BAL := 0.00;   
	END IF ;
	
-- DBMS_OUTPUT.PUT_LINE('--> HKD_RATE: [' || V_HKD_RATE || '] USD_RATE: [' || V_USD_RATE ||']');		 
	 
-- DBMS_OUTPUT.PUT_LINE('--> INSERT ');	  
	 
	INSERT INTO OMI_HIST_BAL_DETAIL (
		OMID_BATCH_ID,
		OMID_MI_ID,
		OMID_ENTITY_TYPE,
		OMID_CCY,
		OMID_COUNTRY,
		OMID_TXN_ID,
		OMID_ACCT_BAL,
		OMID_INTRANSIT,
		OMID_AR_BAL,
		OMID_BAL ,
		OMID_BAL_HKD ,
		OMID_BAL_HKD_RATE ,
		OMID_BAL_USD ,	
		OMID_BAL_USD_RATE 
	) VALUES (
		V_NEW_BATCH_ID,
		X.MI_ID,
		X.ENTITY_TYPE,
		X.TXN_CCY,
		X.COUNTRY,
		X.TXN_ID,
		V_ACCT_BAL ,
		V_INTRANSIT ,
		V_AR_BAL ,
		NVL(V_MID_BAL + V_NET_BAL, 0.00),
		NVL(V_MID_BAL_HKD + (V_NET_BAL * V_HKD_RATE), 0.00),
		V_HKD_RATE,
		NVL(V_MID_BAL_USD + (V_NET_BAL * V_HKD_RATE * V_USD_RATE), 0.00),
		V_USD_RATE
        );
		
	IF SQL % ROWCOUNT != 1 THEN
		raise EXP_ERR;
	END IF;
-- DBMS_OUTPUT.PUT_LINE('--> END INSERT ');
	
	END IF;
	END LOOP;

	COMMIT;
-- DBMS_OUTPUT.PUT_LINE('>>> END [OMI_BAL_COLLECT] <<<');
	RETURN 0;

EXCEPTION
	WHEN EXP_ERR THEN
		ROLLBACK;
--DBMS_OUTPUT.PUT_LINE('Error: Insert last txn error!...');
		RETURN 1;
	WHEN DATE_ERR THEN
		ROLLBACK;
--DBMS_OUTPUT.PUT_LINE('Error: The latest batch end date larger than input date!');
		RETURN 1;
	WHEN EXP_ERR2 THEN
		ROLLBACK;
--DBMS_OUTPUT.PUT_LINE('Error: no record!...');
		RETURN 1;
	WHEN OTHERS THEN
		ROLLBACK;
--DBMS_OUTPUT.PUT_LINE('Error: Other error!...');
--DBMS_OUTPUT.PUT_LINE('Error code ' || SQLCODE|| ': ' || SUBSTR(SQLERRM, 1 , 64));
--RAISE_APPLICATION_ERROR( -20201, 'Error code ' || SQLCODE|| ': ' || SUBSTR(SQLERRM, 1 , 64) );
		RETURN 9;
END SP_OMI_BAL_COLLECT;
/
