CREATE TABLE MERCH_KEYS_BKP
(
  MERCHANT_ID       VARCHAR2(15 BYTE),
  KEY               VARCHAR2(3 BYTE),
  KEY_VALUE         VARCHAR2(128 BYTE),
  CREATE_TIMESTAMP  DATE                        DEFAULT sysdate,
  UPDATE_TIMESTAMP  DATE                        DEFAULT sysdate,
  CREATE_USER       VARCHAR2(20 BYTE),
  UPDATE_USER       VARCHAR2(20 BYTE),
  EFFECT_DATE       VARCHAR2(8 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX MERCH_KEYS_BKP_IDX01 ON MERCH_KEYS_BKP
(EFFECT_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX MERCH_KEYS_BKP_PK ON MERCH_KEYS_BKP
(MERCHANT_ID, KEY, EFFECT_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MERCH_KEYS_BKP ADD (
  CONSTRAINT MERCH_KEYS_BKP_PK
  PRIMARY KEY
  (MERCHANT_ID, KEY, EFFECT_DATE)
  USING INDEX MERCH_KEYS_BKP_PK
  ENABLE VALIDATE);

ALTER TABLE MERCH_KEYS_BKP ADD (
  CONSTRAINT MERCH_KEYS_BKP_FK01 
  FOREIGN KEY (KEY) 
  REFERENCES DEF_KEY_TYPE (DK_TYPE)
  ENABLE VALIDATE);

