


CREATE TABLE OL_SIGN_AUTH_PARAM
(
  OSAP_CHANNEL_CODE	VARCHAR2(3 BYTE),
  OSAP_TXN_CODE     	VARCHAR2(3 BYTE),
  OSAP_VERSION      	VARCHAR2(5 BYTE),
  OSAP_DIRECTION      	CHAR(1 BYTE),
  OSAP_SEQ        	INTEGER,
  OSAP_TAG_NAME        	VARCHAR2(25 BYTE),
  OSAP_FIELD_NAME      	VARCHAR2(50 BYTE),
  OSAP_DISABLED        	INTEGER,
  OSAP_CREATE_USER     	VARCHAR2(20 BYTE),
  OSAP_CREATE_TIMESTAMP	DATE                   DEFAULT sysdate,
  OSAP_UPDATE_USER     	VARCHAR2(20 BYTE),
  OSAP_UPDATE_TIMESTAMP	DATE                   DEFAULT sysdate
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

CREATE UNIQUE INDEX OL_SIGN_AUTH_PARAM_PK ON OL_SIGN_AUTH_PARAM
(OSAP_CHANNEL_CODE, OSAP_TXN_CODE, OSAP_VERSION, OSAP_DIRECTION, OSAP_SEQ)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE OL_SIGN_AUTH_PARAM ADD (
  CONSTRAINT OL_SIGN_AUTH_PARAM_PK
  PRIMARY KEY
  (OSAP_CHANNEL_CODE, OSAP_TXN_CODE, OSAP_VERSION, OSAP_DIRECTION, OSAP_SEQ)
  USING INDEX OL_SIGN_AUTH_PARAM_PK
  ENABLE VALIDATE);

