


insert all
--request
 into OL_SIGN_AUTH_PARAM (OSAP_CHANNEL_CODE, OSAP_TXN_CODE, OSAP_VERSION, OSAP_DIRECTION, OSAP_SEQ, OSAP_TAG_NAME, OSAP_FIELD_NAME, OSAP_DISABLED, OSAP_CREATE_USER, OSAP_CREATE_TIMESTAMP, OSAP_UPDATE_USER, OSAP_UPDATE_TIMESTAMP)
 values ('OIA', 'XXX', '1.0', 'r', 1, 'baid', 'baid', 0, 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE)
 into OL_SIGN_AUTH_PARAM (OSAP_CHANNEL_CODE, OSAP_TXN_CODE, OSAP_VERSION, OSAP_DIRECTION, OSAP_SEQ, OSAP_TAG_NAME, OSAP_FIELD_NAME, OSAP_DISABLED, OSAP_CREATE_USER, OSAP_CREATE_TIMESTAMP, OSAP_UPDATE_USER, OSAP_UPDATE_TIMESTAMP)
 values ('OIA', 'XXX', '1.0', 'r', 2, 'amount', 'transfer amount', 0, 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE)
 into OL_SIGN_AUTH_PARAM (OSAP_CHANNEL_CODE, OSAP_TXN_CODE, OSAP_VERSION, OSAP_DIRECTION, OSAP_SEQ, OSAP_TAG_NAME, OSAP_FIELD_NAME, OSAP_DISABLED, OSAP_CREATE_USER, OSAP_CREATE_TIMESTAMP, OSAP_UPDATE_USER, OSAP_UPDATE_TIMESTAMP)
 values ('OIA', 'XXX', '1.0', 'r', 3, 'currency', 'currency code', 0, 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE)
 into OL_SIGN_AUTH_PARAM (OSAP_CHANNEL_CODE, OSAP_TXN_CODE, OSAP_VERSION, OSAP_DIRECTION, OSAP_SEQ, OSAP_TAG_NAME, OSAP_FIELD_NAME, OSAP_DISABLED, OSAP_CREATE_USER, OSAP_CREATE_TIMESTAMP, OSAP_UPDATE_USER, OSAP_UPDATE_TIMESTAMP)
 values ('OIA', 'XXX', '1.0', 'r', 4, 'to_baid', 'recipient baid', 0, 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE)
 into OL_SIGN_AUTH_PARAM (OSAP_CHANNEL_CODE, OSAP_TXN_CODE, OSAP_VERSION, OSAP_DIRECTION, OSAP_SEQ, OSAP_TAG_NAME, OSAP_FIELD_NAME, OSAP_DISABLED, OSAP_CREATE_USER, OSAP_CREATE_TIMESTAMP, OSAP_UPDATE_USER, OSAP_UPDATE_TIMESTAMP)
 values ('OIA', 'XXX', '1.0', 'r', 5, 'req_id', 'request id', 0, 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE)
 into OL_SIGN_AUTH_PARAM (OSAP_CHANNEL_CODE, OSAP_TXN_CODE, OSAP_VERSION, OSAP_DIRECTION, OSAP_SEQ, OSAP_TAG_NAME, OSAP_FIELD_NAME, OSAP_DISABLED, OSAP_CREATE_USER, OSAP_CREATE_TIMESTAMP, OSAP_UPDATE_USER, OSAP_UPDATE_TIMESTAMP)
 values ('OIA', 'XXX', '1.0', 'r', 6, 'rec_date', 'sms create date', 0, 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE)
--RESPONSE
 into OL_SIGN_AUTH_PARAM (OSAP_CHANNEL_CODE, OSAP_TXN_CODE, OSAP_VERSION, OSAP_DIRECTION, OSAP_SEQ, OSAP_TAG_NAME, OSAP_FIELD_NAME, OSAP_DISABLED, OSAP_CREATE_USER, OSAP_CREATE_TIMESTAMP, OSAP_UPDATE_USER, OSAP_UPDATE_TIMESTAMP)
 values ('OIA', 'XXX', '1.0', 'R', 1, 'response_code', 'error code', 0, 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE)
 into OL_SIGN_AUTH_PARAM (OSAP_CHANNEL_CODE, OSAP_TXN_CODE, OSAP_VERSION, OSAP_DIRECTION, OSAP_SEQ, OSAP_TAG_NAME, OSAP_FIELD_NAME, OSAP_DISABLED, OSAP_CREATE_USER, OSAP_CREATE_TIMESTAMP, OSAP_UPDATE_USER, OSAP_UPDATE_TIMESTAMP)
 values ('OIA', 'XXX', '1.0', 'R', 2, 'baid', 'baid', 0, 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE)
 into OL_SIGN_AUTH_PARAM (OSAP_CHANNEL_CODE, OSAP_TXN_CODE, OSAP_VERSION, OSAP_DIRECTION, OSAP_SEQ, OSAP_TAG_NAME, OSAP_FIELD_NAME, OSAP_DISABLED, OSAP_CREATE_USER, OSAP_CREATE_TIMESTAMP, OSAP_UPDATE_USER, OSAP_UPDATE_TIMESTAMP)
 values ('OIA', 'XXX', '1.0', 'R', 3, 'baid_status', 'baid status', 0, 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE)
 into OL_SIGN_AUTH_PARAM (OSAP_CHANNEL_CODE, OSAP_TXN_CODE, OSAP_VERSION, OSAP_DIRECTION, OSAP_SEQ, OSAP_TAG_NAME, OSAP_FIELD_NAME, OSAP_DISABLED, OSAP_CREATE_USER, OSAP_CREATE_TIMESTAMP, OSAP_UPDATE_USER, OSAP_UPDATE_TIMESTAMP)
 values ('OIA', 'XXX', '1.0', 'R', 4, 'baid_bal', 'baid balance', 0, 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE)
 into OL_SIGN_AUTH_PARAM (OSAP_CHANNEL_CODE, OSAP_TXN_CODE, OSAP_VERSION, OSAP_DIRECTION, OSAP_SEQ, OSAP_TAG_NAME, OSAP_FIELD_NAME, OSAP_DISABLED, OSAP_CREATE_USER, OSAP_CREATE_TIMESTAMP, OSAP_UPDATE_USER, OSAP_UPDATE_TIMESTAMP)
 values ('OIA', 'XXX', '1.0', 'R', 5, 'acct_num', 'bank account number', 0, 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE)
 into OL_SIGN_AUTH_PARAM (OSAP_CHANNEL_CODE, OSAP_TXN_CODE, OSAP_VERSION, OSAP_DIRECTION, OSAP_SEQ, OSAP_TAG_NAME, OSAP_FIELD_NAME, OSAP_DISABLED, OSAP_CREATE_USER, OSAP_CREATE_TIMESTAMP, OSAP_UPDATE_USER, OSAP_UPDATE_TIMESTAMP)
 values ('OIA', 'XXX', '1.0', 'R', 6, 'acct_status', 'bank account status', 0, 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE)
 into OL_SIGN_AUTH_PARAM (OSAP_CHANNEL_CODE, OSAP_TXN_CODE, OSAP_VERSION, OSAP_DIRECTION, OSAP_SEQ, OSAP_TAG_NAME, OSAP_FIELD_NAME, OSAP_DISABLED, OSAP_CREATE_USER, OSAP_CREATE_TIMESTAMP, OSAP_UPDATE_USER, OSAP_UPDATE_TIMESTAMP)
 values ('OIA', 'XXX', '1.0', 'R', 7, 'acct_bal', 'account balance', 0, 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE)
 into OL_SIGN_AUTH_PARAM (OSAP_CHANNEL_CODE, OSAP_TXN_CODE, OSAP_VERSION, OSAP_DIRECTION, OSAP_SEQ, OSAP_TAG_NAME, OSAP_FIELD_NAME, OSAP_DISABLED, OSAP_CREATE_USER, OSAP_CREATE_TIMESTAMP, OSAP_UPDATE_USER, OSAP_UPDATE_TIMESTAMP)
 values ('OIA', 'XXX', '1.0', 'R', 8, 'amount', 'transfer amount', 0, 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE)
 into OL_SIGN_AUTH_PARAM (OSAP_CHANNEL_CODE, OSAP_TXN_CODE, OSAP_VERSION, OSAP_DIRECTION, OSAP_SEQ, OSAP_TAG_NAME, OSAP_FIELD_NAME, OSAP_DISABLED, OSAP_CREATE_USER, OSAP_CREATE_TIMESTAMP, OSAP_UPDATE_USER, OSAP_UPDATE_TIMESTAMP)
 values ('OIA', 'XXX', '1.0', 'R', 9, 'currency', 'currency code', 0, 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE)
 into OL_SIGN_AUTH_PARAM (OSAP_CHANNEL_CODE, OSAP_TXN_CODE, OSAP_VERSION, OSAP_DIRECTION, OSAP_SEQ, OSAP_TAG_NAME, OSAP_FIELD_NAME, OSAP_DISABLED, OSAP_CREATE_USER, OSAP_CREATE_TIMESTAMP, OSAP_UPDATE_USER, OSAP_UPDATE_TIMESTAMP)
 values ('OIA', 'XXX', '1.0', 'R', 10, 'to_baid', 'recipient baid', 0, 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE)
 into OL_SIGN_AUTH_PARAM (OSAP_CHANNEL_CODE, OSAP_TXN_CODE, OSAP_VERSION, OSAP_DIRECTION, OSAP_SEQ, OSAP_TAG_NAME, OSAP_FIELD_NAME, OSAP_DISABLED, OSAP_CREATE_USER, OSAP_CREATE_TIMESTAMP, OSAP_UPDATE_USER, OSAP_UPDATE_TIMESTAMP)
 values ('OIA', 'XXX', '1.0', 'R', 11, 'req_id', 'request id', 0, 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE)
 into OL_SIGN_AUTH_PARAM (OSAP_CHANNEL_CODE, OSAP_TXN_CODE, OSAP_VERSION, OSAP_DIRECTION, OSAP_SEQ, OSAP_TAG_NAME, OSAP_FIELD_NAME, OSAP_DISABLED, OSAP_CREATE_USER, OSAP_CREATE_TIMESTAMP, OSAP_UPDATE_USER, OSAP_UPDATE_TIMESTAMP)
 values ('OIA', 'XXX', '1.0', 'R', 12, 'dt_err_code', 'detail error code', 0, 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE)
select * from dual;

