ALTER TABLE EOD_STATUS_SNAPSHOT
 DROP PRIMARY KEY CASCADE;

DROP TABLE EOD_STATUS_SNAPSHOT CASCADE CONSTRAINTS;

CREATE TABLE EOD_STATUS_SNAPSHOT
(
  ES_PROCESS_DATE       VARCHAR2(8 BYTE),
  ES_TXN_ID             VARCHAR2(16 BYTE),
  ES_MID                VARCHAR2(15 BYTE),
  ES_PID                CHAR(10 BYTE),
  ES_TXN_CODE           VARCHAR2(3 BYTE),
  ES_STATUS             CHAR(1 BYTE),
  ES_AR_IND             CHAR(1 BYTE),
  ES_SUB_STATUS         CHAR(3 BYTE),
  ES_CREATE_USER        VARCHAR2(20 BYTE),
  ES_CREATE_TIMESTAMP   DATE                    DEFAULT sysdate,
  ES_UPDATE_USER        VARCHAR2(20 BYTE),
  ES_UPDATE_TIMESTAMP   DATE                    DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX EOD_STATUS_SNAPSHOT_PK ON EOD_STATUS_SNAPSHOT
(ES_PROCESS_DATE, ES_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE EOD_STATUS_SNAPSHOT ADD (
  CONSTRAINT EOD_STATUS_SNAPSHOT_PK
  PRIMARY KEY
  (ES_PROCESS_DATE, ES_TXN_ID)
  USING INDEX EOD_STATUS_SNAPSHOT_PK
  ENABLE VALIDATE);

