CREATE OR REPLACE FUNCTION SP_HIST_PID_BAL_COLLECT_BY_DAY
RETURN NUMBER IS
	EXP_ERR EXCEPTION;
BEGIN
  /*
  Anonymous block for initiate
  DECLARE
  V_INPUT_DATE DATE;
  BEGIN
  FOR X IN 1..2 LOOP
  SELECT MAX(HB_END_DATE) + 1
  INTO V_INPUT_DATE
  FROM HIST_PID_BAL_BATCH
  WHERE HB_DISABLED = 0;
  -- Run Batch Function
  HIST_PID_BAL_COLLECT(V_INPUT_DATE);
  END LOOP;
  END;
  */
-- DBMS_OUTPUT.PUT_LINE('>>> START [HIST_PID_BAL_COLLECT_BY_DAY] <<<');
-- Run Batch Function
	RETURN SP_HIST_PID_BAL_COLLECT(TRUNC(sysdate) - 1/24/60);
-- DBMS_OUTPUT.PUT_LINE('>>> END [HIST_PID_BAL_COLLECT_BY_DAY] <<<');
EXCEPTION
WHEN EXP_ERR THEN
	ROLLBACK;
--DBMS_OUTPUT.PUT_LINE('Error : no record!...');
	RETURN 1;
WHEN OTHERS THEN
	ROLLBACK;
--DBMS_OUTPUT.PUT_LINE('Error : Other error!...');
--RAISE_APPLICATION_ERROR( -20202, 'Error code ' || SQLCODE|| ': ' || SUBSTR(SQLERRM, 1 , 64) );
	RETURN 9;
END SP_HIST_PID_BAL_COLLECT_BY_DAY;
/

