load data
infile *
append
into table ol_txn_engine_linkage
fields terminated by '|'
(TEL_RULE_ID,
 TEL_LINK_LEVEL,
 TEL_IS_OVERRIDE_TXNID,
 TEL_RELATION_TYPE,
 TEL_CREATE_TIMESTAMP SYSDATE,
 TEL_UPDATE_TIMESTAMP SYSDATE,
 TEL_CREATE_USER,
 TEL_UPDATE_USER
)
BEGINDATA
1|SAME|1|L|SYSTEM|SYSTEM
2|SAME|0|L|SYSTEM|SYSTEM
3|CROSS|1||SYSTEM|SYSTEM
4|CROSS|0||SYSTEM|SYSTEM
5|BOTH|0|L|SYSTEM|SYSTEM
6|BOTH|0|B|SYSTEM|SYSTEM
7|SAME_ORG_X|0|L|SYSTEM|SYSTEM
