OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmsAdjustmentType
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmsAdjustmentType.so
SOOBJS =  MmsAdjustmentType.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
