OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnWebOnUs2TWV
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnWebOnUs2TWV.so
SOOBJS = TxnWebOnUs2TWV.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
