OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MiEntityBalAcct
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMiEntityBalAcct.so
SOOBJS =  MiEntityBalAcct.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
