OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MobCustomerGroupMerchant
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMobCustomerGroupMerchant.so
SOOBJS =  MobCustomerGroupMerchant.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
