ALTER TABLE DEF_PRODUCT
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_PRODUCT CASCADE CONSTRAINTS;

CREATE TABLE DEF_PRODUCT
(
  DP_ID                CHAR(3 BYTE),
  DP_DESC              VARCHAR2(50 BYTE),
  DP_CREATE_TIMESTAMP  DATE,
  DP_CREATE_USER       VARCHAR2(20 BYTE),
  DP_UPDATE_TIMESTAMP  DATE,
  DP_UPDATE_USER       VARCHAR2(20 BYTE),
  DP_DISABLED          INTEGER                  DEFAULT 0
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEF_PRODUCT_PK ON DEF_PRODUCT
(DP_ID)
LOGGING
TABLESPACE USER_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_PRODUCT ADD (
  CONSTRAINT DEF_PRODUCT_PK
  PRIMARY KEY
  (DP_ID)
  USING INDEX DEF_PRODUCT_PK
  ENABLE VALIDATE);

