DROP TABLE TXN_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE TXN_DETAIL
(
  TD_TXN_ID                    VARCHAR2(16 BYTE) NOT NULL,
  TD_TXN_CCY                   CHAR(3 BYTE),
  TD_TXN_COUNTRY               CHAR(2 BYTE),
  TD_PAY_METHOD                VARCHAR2(50 BYTE),
  TD_BANK_CODE                 VARCHAR2(10 BYTE),
  TD_BANK_NAME                 VARCHAR2(50 BYTE),
  TD_BRANCH_NAME               VARCHAR2(100 BYTE),
  TD_ACCOUNT_ID                VARCHAR2(25 BYTE),
  TD_ACCOUNT_NAME              VARCHAR2(100 BYTE),
  TD_IDENTITY_ID               VARCHAR2(25 BYTE),
  TD_PROVINCE                  VARCHAR2(50 BYTE),
  TD_PHONE_NO                  VARCHAR2(25 BYTE),
  TD_CITY                      VARCHAR2(100 BYTE),
  TD_BATCH_ID                  VARCHAR2(20 BYTE),
  TD_SHOW_PAYPAGE              CHAR(1 BYTE),
  TD_LANGUAGE                  CHAR(2 BYTE),
  TD_SUCCESS_URL               VARCHAR2(255 BYTE),
  TD_FAILURE_URL               VARCHAR2(255 BYTE),
  TD_SUCCESS_CALLBACK_URL      VARCHAR2(255 BYTE),
  TD_FAILURE_CALLBACK_URL      VARCHAR2(255 BYTE),
  TD_CREATE_USER               VARCHAR2(20 BYTE),
  TD_CREATE_TIMESTAMP          DATE             DEFAULT sysdate,
  TD_UPDATE_USER               VARCHAR2(20 BYTE),
  TD_UPDATE_TIMESTAMP          DATE             DEFAULT sysdate,
  TD_ENCRYPT_TYPE              VARCHAR2(4 BYTE),
  TD_OPEN_BAL                  NUMBER(14,2),
  TD_CURRENT_BAL               NUMBER(14,2),
  TD_TOTAL_FLOAT               NUMBER(14,2),
  TD_TOTAL_RESERVED_AMOUNT     NUMBER(14,2),
  TD_TOTAL_HOLD                NUMBER(14,2),
  TD_FUNDIN_PAYOUT             NUMBER(14,2),
  TD_RESERVED_PAYOUT           NUMBER(14,2),
  TD_TOTAL_FLOAT_AFTER_PAYOUT  NUMBER(14,2),
  TD_OPEN_BAL_SETTLEMENT       NUMBER(14,2),
  TD_CURRENT_BAL_SETTLEMENT    NUMBER(14,2),
  TD_TOTAL_FLOAT_SETTLEMENT    NUMBER(14,2),
  TD_TOTAL_HOLD_SETTLEMENT     NUMBER(14,2),
  TD_VERSION_NO                INTEGER,
  TD_REMARK                    VARCHAR2(255 BYTE),
  TD_SELECTED_PAY_METHOD       VARCHAR2(4 BYTE),
  TD_BANNER_LOGO               VARCHAR2(255 BYTE),
  TD_CUSTOMER_TAG              VARCHAR2(10 BYTE),
  TD_ECHO_MSG_1                VARCHAR2(50 BYTE),
  TD_ECHO_MSG_2                VARCHAR2(50 BYTE),
  TD_ECHO_MSG_3                VARCHAR2(50 BYTE),
  TD_OPT_1                     VARCHAR2(50 BYTE),
  TD_OPT_2                     VARCHAR2(50 BYTE),
  TD_OPT_3                     VARCHAR2(50 BYTE),
  TD_CUSTOMER_NAME             VARCHAR2(100 BYTE),
  TD_CUSTOMER_FAMILY_NAME      VARCHAR2(100 BYTE),
  TD_CUSTOMER_TEL              VARCHAR2(20 BYTE),
  TD_CUSTOMER_EMAIL            VARCHAR2(100 BYTE),
  TD_SELECTED_PID              VARCHAR2(10 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          8M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX TXN_DETAIL_IDX ON TXN_DETAIL
(TD_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          75008K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX TXN_DETAIL_IDX01 ON TXN_DETAIL
(TD_TXN_ID, TD_TXN_CCY)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          91M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX TXN_DETAIL_IDX02 ON TXN_DETAIL
(TD_REMARK, TD_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          75M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX TXN_DETAIL_IDX03 ON TXN_DETAIL
(TD_TXN_ID, TD_TXN_COUNTRY)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          83M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX TXN_DETAIL_IDX04 ON TXN_DETAIL
(TD_TXN_ID, TD_TXN_CCY, TD_TXN_COUNTRY)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          133M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX TXN_DETAIL_IDX06 ON TXN_DETAIL
(TD_TXN_ID, TD_BANK_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX TXN_DETAIL_IDX07 ON TXN_DETAIL
(TD_BANK_CODE, TD_CREATE_TIMESTAMP)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

