create or replace function sp_txn_detail_insert(
       in_txn_id                                txn_detail.td_txn_id%type,
       in_txn_ccy				txn_detail.td_txn_ccy%type,
       in_txn_country				txn_detail.td_txn_country%type,	
       in_pay_method				txn_detail.td_pay_method%type,
       in_bank_code				txn_detail.td_bank_code%type,
       in_bank_name				txn_detail.td_bank_name%type,
       in_branch_name				txn_detail.td_branch_name%type,
       in_account_id				txn_detail.td_account_id%type,
       in_account_name				txn_detail.td_account_name%type,
       in_identity_id				txn_detail.td_identity_id%type,
       in_province				txn_detail.td_province%type,
       in_phone_no				txn_detail.td_phone_no%type,
       in_city					txn_detail.td_city%type,
       in_batch_id				txn_detail.td_batch_id%type,
       in_show_paypage			        txn_detail.td_show_paypage%type,
       in_language				txn_detail.td_language%type,
       in_success_url				txn_detail.td_success_url%type,
       in_failure_url				txn_detail.td_failure_url%type,
       in_success_callback_url	                txn_detail.td_success_callback_url%type,
       in_failure_callback_url			txn_detail.td_failure_callback_url%type,
       in_create_user                           txn_detail.td_create_user%type,
       in_update_user                           txn_detail.td_update_user%type,       
       in_encrypt_type				txn_detail.td_encrypt_type%type,
       in_version_no				txn_detail.td_version_no%type,
       in_remark				txn_detail.td_remark%type,
       in_selected_pay_method			txn_detail.td_selected_pay_method%type,
       in_banner_logo                           txn_detail.td_banner_logo%type,
       in_customer_tag                          txn_detail.td_customer_tag%type,
       in_echo_msg_1                            txn_detail.td_echo_msg_1%type,
       in_echo_msg_2                            txn_detail.td_echo_msg_2%type,
       in_echo_msg_3                            txn_detail.td_echo_msg_3%type,
       in_opt_1                                 txn_detail.td_opt_1%type,
       in_opt_2                                 txn_detail.td_opt_2%type,
       in_opt_3                                 txn_detail.td_opt_3%type,
       in_customer_name                         txn_detail.td_customer_name%type,
       in_customer_family_name                  txn_detail.td_customer_family_name%type,
       in_customer_tel				txn_detail.td_customer_tel%type,
       in_customer_email                        txn_detail.td_customer_email%type,
       in_selected_pid                        	txn_detail.td_selected_pid%type
	
)
  RETURN NUMBER IS
Begin
     Update txn_detail
            Set td_txn_ccy = in_txn_ccy,
                  td_txn_country = in_txn_country,
		  td_pay_method = in_pay_method,
		  td_bank_code = in_bank_code,
		  td_bank_name = in_bank_name,
		  td_branch_name = in_branch_name,
		  td_account_id = in_account_id,
		  td_account_name = in_account_name,
		  td_identity_id = in_identity_id,
		  td_province = in_province,
		  td_phone_no = in_phone_no,
		  td_city = in_city,
		  td_batch_id = in_batch_id,
                  td_show_paypage = in_show_paypage,
                  td_language = in_language,
                  td_success_url = in_success_url,
		  td_failure_url = in_failure_url,
                  td_success_callback_url = in_success_callback_url,
		  td_failure_callback_url = in_failure_callback_url,
                  td_update_user = in_update_user,
                  td_update_timestamp = Sysdate,
		  td_encrypt_type=in_encrypt_type,
		  td_version_no = in_version_no,
		  td_remark = in_remark,
		  td_selected_pay_method = in_selected_pay_method,
		  td_banner_logo = in_banner_logo,
		  td_customer_tag = in_customer_tag,
		  td_echo_msg_1 = in_echo_msg_1,
		  td_echo_msg_2 = in_echo_msg_2,
		  td_echo_msg_3 = in_echo_msg_3,
		  td_opt_1 = in_opt_1,
		  td_opt_2 = in_opt_2,
		  td_opt_3 = in_opt_3,
		  td_customer_name = in_customer_name,
		  td_customer_family_name = in_customer_family_name,
		  td_customer_tel = in_customer_tel,
		  td_customer_email = in_customer_email,
		  td_selected_pid = in_selected_pid
      Where td_txn_id = in_txn_id;

     IF SQL%ROWCOUNT = 0 THEN
        insert into txn_detail
                     (td_txn_id,
		      td_txn_ccy,
		      td_txn_country,
		      td_pay_method,
                      td_bank_code,
                      td_bank_name,
                      td_branch_name,
                      td_account_id,
                      td_account_name,
                      td_identity_id,
                      td_province,
                      td_phone_no,
                      td_city,
                      td_batch_id,
		      td_show_paypage,
		      td_language,
		      td_success_url,
		      td_failure_url,
		      td_success_callback_url,
		      td_failure_callback_url,
                      td_create_user,
                      td_create_timestamp,
                      td_update_user,
                      td_update_timestamp,
		      td_encrypt_type,
		      td_version_no,
		      td_remark,
		      td_selected_pay_method,
		      td_banner_logo,
                      td_customer_tag,
                      td_echo_msg_1,
                      td_echo_msg_2,  
                      td_echo_msg_3,
                      td_opt_1,
                      td_opt_2,
                      td_opt_3,
                      td_customer_name,
                      td_customer_family_name,
                      td_customer_tel,
                      td_customer_email,
		      td_selected_pid)
          values(in_txn_id,
		     in_txn_ccy,
                     in_txn_country,
		     in_pay_method,
		     in_bank_code,
		     in_bank_name,
		     in_branch_name,
		     in_account_id,
		     in_account_name,
		     in_identity_id,
		     in_province,
		     in_phone_no,
		     in_city,
		     in_batch_id,
		     in_show_paypage,
		     in_language,
		     in_success_url,
		     in_failure_url,
		     in_success_callback_url,
		     in_failure_callback_url,
                     in_create_user,
                     sysdate,
                     in_update_user,
                     sysdate,
		     in_encrypt_type,
		     in_version_no,
                     in_remark,
		     in_selected_pay_method,
		     in_banner_logo,
                     in_customer_tag,
                     in_echo_msg_1,
                     in_echo_msg_2,
                     in_echo_msg_3,
                     in_opt_1,
                     in_opt_2,
                     in_opt_3,
                     in_customer_name,
                     in_customer_family_name,
                     in_customer_tel,
                     in_customer_email,
	             in_selected_pid);

          IF SQL%ROWCOUNT = 0 THEN
             RETURN 1;
          ELSE
             RETURN 0;
          END IF;
      Else
          Return 0;
       End If;

EXCEPTION
  WHEN OTHERS THEN
     RETURN 9;
end sp_txn_detail_insert;
/
