OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnWebOnUsWTB
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnWebOnUsWTB.so
SOOBJS = TxnWebOnUsWTB.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
