OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/DefPayMethod
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBDefPayMethod.so
SOOBJS =  DefPayMethod.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
