ALTER TABLE OL_ACCT_STATUS_ACTION
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_ACCT_STATUS_ACTION CASCADE CONSTRAINTS;

CREATE TABLE OL_ACCT_STATUS_ACTION
(
  ASA_ACTION            VARCHAR2(20 BYTE),
  ASA_STATUS            VARCHAR2(2 BYTE),
  ASA_ALLOW_ACTION      INTEGER                 DEFAULT 0,
  ASA_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  ASA_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  ASA_CREATE_USER       VARCHAR2(20 BYTE),
  ASA_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN OL_ACCT_STATUS_ACTION.ASA_ALLOW_ACTION IS '0: not allow ; 1: allow';


CREATE UNIQUE INDEX OL_ACCT_STATUS_ACTION_PK ON OL_ACCT_STATUS_ACTION
(ASA_ACTION, ASA_STATUS)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_ACCT_STATUS_ACTION ADD (
  CONSTRAINT OL_ACCT_STATUS_ACTION_PK
  PRIMARY KEY
  (ASA_ACTION, ASA_STATUS)
  USING INDEX OL_ACCT_STATUS_ACTION_PK
  ENABLE VALIDATE);

ALTER TABLE OL_ACCT_STATUS_ACTION ADD (
  CONSTRAINT OL_ACCT_STATUS_ACTION_FK01 
  FOREIGN KEY (ASA_ACTION) 
  REFERENCES OL_DEF_ACTION_LIST (AL_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OL_ACCT_STATUS_ACTION_FK02 
  FOREIGN KEY (ASA_STATUS) 
  REFERENCES OL_DEF_ACCT_STATUS (AS_TYPE)
  ENABLE VALIDATE);

