ALTER TABLE SERVICE_UI_RELEASE_CTL
 DROP PRIMARY KEY CASCADE;

DROP TABLE SERVICE_UI_RELEASE_CTL CASCADE CONSTRAINTS;

CREATE TABLE SERVICE_UI_RELEASE_CTL
(
  RC_TAG               VARCHAR2(25 BYTE),
  RC_VALUE             VARCHAR2(50 BYTE),
  RC_NEW_UI            INTEGER                  DEFAULT 0,
  RC_DISABLED          INTEGER                  DEFAULT 0,
  RC_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  RC_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  RC_CREATE_USER       VARCHAR2(20 BYTE),
  RC_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX SERVICE_UI_RELEASE_CTL_PK ON SERVICE_UI_RELEASE_CTL
(RC_TAG, RC_VALUE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE SERVICE_UI_RELEASE_CTL ADD (
  CONSTRAINT SERVICE_UI_RELEASE_CTL_PK
  PRIMARY KEY
  (RC_TAG, RC_VALUE)
  USING INDEX SERVICE_UI_RELEASE_CTL_PK
  ENABLE VALIDATE);

