ALTER TABLE MMS_INSTANT_PM_ACCT_HD
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_INSTANT_PM_ACCT_HD CASCADE CONSTRAINTS;

CREATE TABLE MMS_INSTANT_PM_ACCT_HD
(
  MIA_PARTY_TYPE          CHAR(1 BYTE),
  MIA_BUSINESS_TYPE       CHAR(1 BYTE),
  MIA_LASTUPDATE_DATETIME DATE                  DEFAULT sysdate,
  MIA_STATUS              CHAR(1 BYTE),
  MIA_STATUS_UPDATE_DATETIME  DATE                  DEFAULT sysdate,
  MIA_CREATE_USER          VARCHAR2(20 BYTE),
  MIA_UPDATE_USER         VARCHAR2(20 BYTE),
  MIA_CREATE_TIMESTAMP    DATE                  DEFAULT sysdate,
  MIA_UPDATE_TIMESTAMP    DATE                  DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MMS_INSTANT_PM_ACCT_HD_PK ON MMS_INSTANT_PM_ACCT_HD
(MIA_PARTY_TYPE,MIA_BUSINESS_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_INSTANT_PM_ACCT_HD ADD (
  CONSTRAINT MMS_INSTANT_PM_ACCT_HD_PK
  PRIMARY KEY
  (MIA_PARTY_TYPE,MIA_BUSINESS_TYPE)
  USING INDEX MMS_INSTANT_PM_ACCT_HD_PK
  ENABLE VALIDATE);

ALTER TABLE MMS_INSTANT_PM_ACCT_HD ADD (
  CONSTRAINT MMS_INSTANT_PM_ACCT_HD_FK01
  FOREIGN KEY (MIA_PARTY_TYPE) 
  REFERENCES DEF_PARTY_TYPE (DP_TYPE)
  ENABLE VALIDATE);

ALTER TABLE MMS_INSTANT_PM_ACCT_HD ADD (
  CONSTRAINT MMS_INSTANT_PM_ACCT_HD_FK02
  FOREIGN KEY (MIA_BUSINESS_TYPE) 
  REFERENCES DEF_BUSINESS_TYPE (BT_TYPE)
  ENABLE VALIDATE);
