ALTER TABLE CUSTOMER_GROUP_OFFSET_LOG
 DROP PRIMARY KEY CASCADE;

DROP TABLE CUSTOMER_GROUP_OFFSET_LOG CASCADE CONSTRAINTS;

CREATE TABLE CUSTOMER_GROUP_OFFSET_LOG
(
  CGL_CODE         VARCHAR2(10 BYTE),
  CGL_COUNTRY_ID   VARCHAR2(2 BYTE),
  CGL_CHANNEL_CODE VARCHAR2(3 BYTE),
  CGL_SERVICE_CODE VARCHAR2(4 BYTE),
  CGL_CURRENCY_ID  VARCHAR2(3 BYTE),
  CGL_CATEGORY     VARCHAR2(3 BYTE),
  CGL_ADJ_VALUE    NUMBER(16,2)                 DEFAULT 0,
  CGL_CREATE_TIMESTAMP  DATE                         DEFAULT sysdate,
  CGL_CREATE_USER  VARCHAR2(20 BYTE),
  CGL_UPDATE_TIMESTAMP  DATE                         DEFAULT sysdate,
  CGL_UPDATE_USER  VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX CUSTOMER_GRP_OFFSET_LOG_IDX01 ON CUSTOMER_GROUP_OFFSET_LOG
(CGL_CODE, CGL_COUNTRY_ID,CGL_CHANNEL_CODE,CGL_SERVICE_CODE,CGL_CURRENCY_ID,CGL_CATEGORY)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

