OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/NonHoliday
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBNonHoliday.so
SOOBJS =  NonHoliday.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
