OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/CustomerGroupMerchant
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBCustomerGroupMerchant.so
SOOBJS =  CustomerGroupMerchant.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
