OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLTxnMiDetail
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLTxnMiDetail.so
SOOBJS =  OLTxnMiDetail.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
