OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/Messages
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMessages.so
SOOBJS =  Messages.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
