OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/RulePayoutExclude
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBRulePayoutExclude.so
SOOBJS =  RulePayoutExclude.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
