OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLMerchantUploadError
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLMerchantUploadError.so
SOOBJS =  OLMerchantUploadError.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
