OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/RuleTxnFeeDef
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBRuleTxnFeeDef.so
SOOBJS =  RuleTxnFeeDef.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
