


ALTER TABLE DEF_LEDGER_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_LEDGER_TYPE CASCADE CONSTRAINTS;

CREATE TABLE DEF_LEDGER_TYPE
(
  DL_TYPE              CHAR(1 BYTE)             NOT NULL,
  DL_DESC              VARCHAR2(50 BYTE),
  DL_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  DL_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  DL_CREATE_USER       VARCHAR2(20 BYTE),
  DL_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DEF_LEDGER_TYPE_PK ON DEF_LEDGER_TYPE
(DL_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


ALTER TABLE DEF_LEDGER_TYPE ADD (
  CONSTRAINT DEF_LEDGER_TYPE_PK
  PRIMARY KEY
  (DL_TYPE)
  USING INDEX PHUSER.DEF_LEDGER_TYPE_PK
  ENABLE VALIDATE);
