OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnMgtByUsVOS
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnMgtByUsVOS.so
SOOBJS = TxnMgtByUsVOS.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
