ALTER TABLE OL_PF_TXN_INIT_DETAIL
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_PF_TXN_INIT_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE OL_PF_TXN_INIT_DETAIL
(
  OPID_FILE_ID               NUMBER(16),
  OPID_SEQ           	     INTEGER,
  OPID_TXN_ID                VARCHAR2(16 BYTE),
  OPID_BAID		     VARCHAR2(20 BYTE),
  OPID_REPORT_DATE	     VARCHAR2(8 BYTE),
  OPID_CCY		     VARCHAR2(3 BYTE),
  OPID_TXN_TYPE		     VARCHAR2(50 BYTE),
  OPID_DEBIT_AMT	     NUMBER(12,2),
  OPID_CREDIT_AMT	     NUMBER(12,2),
  OPID_BAID_NAME	     VARCHAR2(100 BYTE),
  OPID_REMARK		     VARCHAR2(255 BYTE),
  OPID_CREATE_TIMESTAMP      DATE,
  OPID_CREATE_USER           VARCHAR2(20 BYTE),
  OPID_UPDATE_TIMESTAMP      DATE,
  OPID_UPDATE_USER           VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX OL_PF_TXN_INIT_DETAIL_PK ON OL_PF_TXN_INIT_DETAIL
(OPID_FILE_ID, OPID_SEQ)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

CREATE UNIQUE INDEX OL_PF_TXN_INIT_DETAIL_IDX01 ON OL_PF_TXN_INIT_DETAIL
(OPID_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_PF_TXN_INIT_DETAIL ADD (
  CONSTRAINT OL_PF_TXN_INIT_DETAIL_PK
  PRIMARY KEY
  (OPID_FILE_ID, OPID_SEQ)
  USING INDEX OL_PF_TXN_INIT_DETAIL_PK
  ENABLE VALIDATE);

ALTER TABLE OL_PF_TXN_INIT_DETAIL ADD (
  CONSTRAINT OL_PF_TXN_INIT_DETAIL_FK01 
  FOREIGN KEY (OPID_FILE_ID) 
  REFERENCES OL_PF_TXN_INIT_HEADER (OPIH_FILE_ID)
  ENABLE VALIDATE,
  CONSTRAINT OL_PF_TXN_INIT_DETAIL_FK02
  FOREIGN KEY (OPID_TXN_ID) 
  REFERENCES OL_TXN_HEADER (OTH_TXN_ID)
  ENABLE VALIDATE,
  CONSTRAINT OL_PF_TXN_INIT_DETAIL_FK03
  FOREIGN KEY (OPID_CCY)
  REFERENCES DEF_CURRENCY (DC_CCY_ID)
  ENABLE VALIDATE);

