ALTER TABLE OL_PF_TXN_INIT_CODE
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_PF_TXN_INIT_CODE CASCADE CONSTRAINTS;

CREATE TABLE OL_PF_TXN_INIT_CODE
(
  OPIC_TXN_CODE             CHAR(3 BYTE),
  OPIC_AMT_TYPE             CHAR(2 BYTE),
  OPIC_CREATE_TIMESTAMP     DATE DEFAULT sysdate,
  OPIC_CREATE_USER          VARCHAR2(20 BYTE),
  OPIC_UPDATE_TIMESTAMP     DATE DEFAULT sysdate,
  OPIC_UPDATE_USER          VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX OL_PF_TXN_INIT_CODE_PK ON OL_PF_TXN_INIT_CODE
(OPIC_TXN_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_PF_TXN_INIT_CODE ADD (
  CONSTRAINT OL_PF_TXN_INIT_CODE_PK
  PRIMARY KEY
  (OPIC_TXN_CODE)
  USING INDEX OL_PF_TXN_INIT_CODE_PK
  ENABLE VALIDATE);

ALTER TABLE OL_PF_TXN_INIT_CODE ADD (
  CONSTRAINT OL_PF_TXN_INIT_CODE_FK01
  FOREIGN KEY (OPIC_TXN_CODE)
  REFERENCES TXN_CODE (TC_CODE)
  ENABLE VALIDATE,
  CONSTRAINT OL_PF_TXN_INIT_CODE_FK02
  FOREIGN KEY (OPIC_AMT_TYPE) 
  REFERENCES DEF_AMT_TYPE (DA_TYPE)
  ENABLE VALIDATE);
