ALTER TABLE OL_PF_TXN_INIT_ERROR
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_PF_TXN_INIT_ERROR CASCADE CONSTRAINTS;

CREATE TABLE OL_PF_TXN_INIT_ERROR
(
  OPIE_ERROR_ID         NUMBER(16),
  OPIE_FILE_ID          NUMBER(16),
  OPIE_RESULT           VARCHAR2(255 BYTE),
  OPIE_LINE             VARCHAR2(511 BYTE),
  OPIE_CREATE_USER      VARCHAR2(20 BYTE),
  OPIE_CREATE_TIMESTAMP DATE                     DEFAULT SYSDATE
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX OL_PF_TXN_INIT_ERROR_IDX01 ON OL_PF_TXN_INIT_ERROR
(OPIE_FILE_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

CREATE UNIQUE INDEX OL_PF_TXN_INIT_ERROR_PK ON OL_PF_TXN_INIT_ERROR
(OPIE_ERROR_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_PF_TXN_INIT_ERROR ADD (
  CONSTRAINT OL_PF_TXN_INIT_ERROR_PK
  PRIMARY KEY
  (OPIE_ERROR_ID)
  USING INDEX OL_PF_TXN_INIT_ERROR_PK
  ENABLE VALIDATE);
