ALTER TABLE OL_PF_TXN_INIT_HEADER
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_PF_TXN_INIT_HEADER CASCADE CONSTRAINTS;

CREATE TABLE OL_PF_TXN_INIT_HEADER
(
  OPIH_FILE_ID              NUMBER(16),
  OPIH_FILENAME             VARCHAR2(100 BYTE),
  OPIH_ACCEPT_COUNT         INTEGER,
  OPIH_TOTAL_COUNT          INTEGER,
  OPIH_STATUS               CHAR(1 BYTE),
  OPIH_CREATE_TIMESTAMP     DATE DEFAULT sysdate,
  OPIH_CREATE_USER          VARCHAR2(20 BYTE),
  OPIH_UPDATE_TIMESTAMP     DATE DEFAULT sysdate,
  OPIH_UPDATE_USER          VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX OL_PF_TXN_INIT_HEADER_IDX01 ON OL_PF_TXN_INIT_HEADER
(OPIH_FILENAME)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX OL_PF_TXN_INIT_HEADER_PK ON OL_PF_TXN_INIT_HEADER
(OPIH_FILE_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_PF_TXN_INIT_HEADER ADD (
  CONSTRAINT OL_PF_TXN_INIT_HEADER_PK
  PRIMARY KEY
  (OPIH_FILE_ID)
  USING INDEX OL_PF_TXN_INIT_HEADER_PK
  ENABLE VALIDATE);

ALTER TABLE OL_PF_TXN_INIT_HEADER ADD (
  CONSTRAINT OL_PF_TXN_INIT_HEADER_FK01
  FOREIGN KEY (OPIH_STATUS)
  REFERENCES OL_DEF_FILE_STATUS (DFS_STATUS)
  ENABLE VALIDATE);
