OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/DefTxnStatusMap
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBDefTxnStatusMap.so
SOOBJS =  DefTxnStatusMap.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
