OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/DepositMismatch
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBDepositMismatch.so
SOOBJS =  DepositMismatch.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
