OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOMmsTask
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOMmsTask.so
SOOBJS = BOMmsTask.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
