OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLStmtFormat
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLStmtFormat.so
SOOBJS =  OLStmtFormat.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
