OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOMMSEntityBalance
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOMMSEntityBalance.so
SOOBJS = BOMMSEntityBalance.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
