DROP TABLE OL_PAYOUT_GENERATED_FILE_HD_PD CASCADE CONSTRAINTS;

CREATE TABLE OL_PAYOUT_GENERATED_FILE_HD_PD
(
  OFH_FILE_ID           NUMBER(16),
  OFH_FILE_DATE         VARCHAR2(8 BYTE),
  OFH_FILE_PID          VARCHAR2(10 BYTE),
  OFH_FILE_BANK_CODE    VARCHAR2(10 BYTE),
  OFH_SEQ_NUM           INTEGER,
  OFH_FILENAME          VARCHAR2(50 BYTE),
  OFH_STATUS            INTEGER,
  OFH_TXN_COUNT         INTEGER,
  OFH_TOTAL_TXN_AMT     NUMBER(14,2),
  OFH_CCY_ID            VARCHAR2(3 BYTE),
  OFH_CREATE_USER       VARCHAR2(20 BYTE),
  OFH_CREATE_TIMESTAMP  DATE,
  OFH_UPDATE_USER       VARCHAR2(20 BYTE),
  OFH_UPDATE_TIMESTAMP  DATE
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

