OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/PspRequestTxnUrl
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBPspRequestTxnUrl.so
SOOBJS =  PspRequestTxnUrl.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
