ALTER TABLE OL_SEMI_AUTO_RECON_TXNCODE_MAP
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_SEMI_AUTO_RECON_TXNCODE_MAP CASCADE CONSTRAINTS;

CREATE TABLE OL_SEMI_AUTO_RECON_TXNCODE_MAP
(
  OSAR_BANK_ACCT_TYPE        VARCHAR2(3 BYTE),
  OSAR_SENDER_RECIPIENT_IND  CHAR(1 BYTE),
  OSAR_NORMAL_RETURN_IND     CHAR(1 BYTE),
  OSAR_BAID_TXN_CODE         CHAR(3 BYTE),
  OSAR_CREATE_TIMESTAMP      DATE               DEFAULT sysdate,
  OSAR_CREATE_USER           VARCHAR2(20 BYTE),
  OSAR_UPDATE_TIMESTAMP      DATE               DEFAULT sysdate,
  OSAR_UPDATE_USER           VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_SEMI_AUTO_RECON_TC_MAP_PK ON OL_SEMI_AUTO_RECON_TXNCODE_MAP
(OSAR_BANK_ACCT_TYPE, OSAR_SENDER_RECIPIENT_IND, OSAR_NORMAL_RETURN_IND)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_SEMI_AUTO_RECON_TXNCODE_MAP ADD (
  CONSTRAINT OL_SEMI_AUTO_RECON_TC_MAP_PK
  PRIMARY KEY
  (OSAR_BANK_ACCT_TYPE, OSAR_SENDER_RECIPIENT_IND, OSAR_NORMAL_RETURN_IND)
  USING INDEX OL_SEMI_AUTO_RECON_TC_MAP_PK
  ENABLE VALIDATE);

