OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MerchCountry
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMerchCountry.so
SOOBJS =  MerchCountry.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
