OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOParBalance
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOParBalance.so
SOOBJS = BOParBalance.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
