ALTER TABLE MMS_TXN_DETAIL
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_TXN_DETAIL CASCADE CONSTRAINTS;


CREATE TABLE MMS_TXN_DETAIL
(
  MTD_TXN_ID                 VARCHAR2(16 BYTE),
  MTD_SD_IND		     char(1 BYTE),
  MTD_MERCHANT_ID            VARCHAR2(15 BYTE),
  MTD_PSP_ID                 VARCHAR2(10 BYTE),
  MTD_MB_ID		     VARCHAR2(15 BYTE),
  MTD_BANK_ID		     VARCHAR2(15 BYTE),
  MTD_TRANSMISSION_DATETIME  VARCHAR2(14 BYTE),
  MTD_TXN_AMT		     NUMBER(14,2),
  MTD_TXN_CCY		     CHAR(3 BYTE),
  MTD_ADJUSTMENT	     NUMBER(14,2),
  MTD_EXCHANGE_RATE	     NUMBER(12,5),
  MTD_PROCESSING_COST	     NUMBER(14,2),
  MTD_BANK_CHARGE	     NUMBER(14,2),
  MTD_BANK_CHARGE_REFUND     NUMBER(14,2),
  MTD_FILING_NUMBER	     VARCHAR2(50 BYTE),
  MTD_COUNTRY                VARCHAR2(3 BYTE),
  MTD_VERSION_NO             VARCHAR2(2 BYTE),
  MTD_ENCRYPT_TYPE           CHAR(1 BYTE),
  MTD_CREATE_TIMESTAMP       DATE,
  MTD_CREATE_USER            VARCHAR2(20 BYTE),
  MTD_UPDATE_TIMESTAMP       DATE,
  MTD_UPDATE_USER            VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX MMS_TXN_DETAIL_IDX01 ON MMS_TXN_DETAIL
(MTD_TXN_ID)
LOGGING
TABLESPACE USER_IDX
STORAGE    (
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;
