ALTER TABLE MMS_TXN_HEADER
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_TXN_HEADER CASCADE CONSTRAINTS;

CREATE TABLE MMS_TXN_HEADER
(
  MTH_TXN_ID                 VARCHAR2(16 BYTE),
  MTH_ORG_TXN_ID             VARCHAR2(16 BYTE),
  MTH_NEXT_TXN_ID            VARCHAR2(16 BYTE),
  MTH_SERVICE_CODE           CHAR(3 BYTE),
  MTH_MMC_NODE_ID            VARCHAR2(5 BYTE),
  MTH_CLIENT_REF             VARCHAR2(16 BYTE),
  MTH_STATUS                 CHAR(1 BYTE),
  MTH_AR_IND                 CHAR(1 BYTE),
  MTH_INTERNAL_CODE          NUMBER(8),
  MTH_RESPONSE_CODE          VARCHAR2(6 BYTE),
  MTH_TXN_CODE               VARCHAR2(3 BYTE),
  MTH_PROCESS_TYPE           VARCHAR2(4 BYTE),
  MTH_PROCESS_CODE           VARCHAR2(6 BYTE),
  MTH_HOST_POSTING_DATE      VARCHAR2(8 BYTE),
  MTH_TM_DATE                VARCHAR2(8 BYTE),
  MTH_TM_TIME                VARCHAR2(6 BYTE),
  MTH_LOCAL_TM_DATE          VARCHAR2(8 BYTE),
  MTH_LOCAL_TM_TIME          VARCHAR2(6 BYTE),
  MTH_TRANSMISSION_DATETIME  VARCHAR2(14 BYTE),
  MTH_TRANSACTION_AMOUNT     NUMBER(12,2),
  MTH_TRANSACTION_CCY        CHAR(3 BYTE),
  MTH_CREATE_USER            VARCHAR2(20 BYTE),
  MTH_CREATE_TIMESTAMP       DATE,
  MTH_UPDATE_USER            VARCHAR2(20 BYTE),
  MTH_UPDATE_TIMESTAMP       DATE
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MMS_TXN_HEADER_PK ON MMS_TXN_HEADER
(MTH_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_TXN_HEADER ADD (
  CONSTRAINT MMS_TXN_HEADER_PK
  PRIMARY KEY
  (MTH_TXN_ID)
  USING INDEX MMS_TXN_HEADER_PK
  ENABLE VALIDATE);

