ALTER TABLE OL_DEF_INPUT_CHANNEL
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_DEF_INPUT_CHANNEL CASCADE CONSTRAINTS;

CREATE TABLE OL_DEF_INPUT_CHANNEL
(
  DI_INPUT_CHANNEL     VARCHAR2(10 BYTE),
  DI_DESC              VARCHAR2(50 BYTE),
  DI_STATEMENT_DISPLAY INTEGER                   DEFAULT 0,
  DI_DEPOSIT_DISPLAY   INTEGER                   DEFAULT 0,
  DI_CREATE_TIMESTAMP  DATE                      DEFAULT sysdate,
  DI_CREATE_USER       VARCHAR2(20 BYTE),
  DI_UPDATE_TIMESTAMP  DATE                      DEFAULT sysdate,
  DI_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_DEF_INPUT_CHANNEL_PK ON OL_DEF_INPUT_CHANNEL
(DI_INPUT_CHANNEL)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_DEF_INPUT_CHANNEL ADD (
  CONSTRAINT OL_DEF_INPUT_CHANNEL_PK
  PRIMARY KEY
  (DI_INPUT_CHANNEL)
  USING INDEX OL_DEF_INPUT_CHANNEL_PK
  ENABLE VALIDATE);

