CREATE TABLE DEF_TLG_TAG_CONVERT
(
  DTC_ORG_TAG           VARCHAR2(25 BYTE),
  DTC_CONVERT_TAG       VARCHAR2(25 BYTE),
  DTC_DISABLED          INTEGER                 DEFAULT 0,
  DTC_CREATE_USER       VARCHAR2(20 BYTE),
  DTC_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  DTC_UPDATE_USER       VARCHAR2(20 BYTE),
  DTC_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DEF_TLG_TAG_CONVERT_PK ON DEF_TLG_TAG_CONVERT
(DTC_ORG_TAG, DTC_CONVERT_TAG)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DEF_TLG_TAG_CONVERT ADD (
  CONSTRAINT DEF_TLG_TAG_CONVERT_PK
  PRIMARY KEY
  (DTC_ORG_TAG, DTC_CONVERT_TAG)
  USING INDEX DEF_TLG_TAG_CONVERT_PK
  ENABLE VALIDATE);

