OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/DefTxnCodeMap
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBDefTxnCodeMap.so
SOOBJS =  DefTxnCodeMap.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
