OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/RuleTier
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBRuleTier.so
SOOBJS =  RuleTier.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
