CREATE TABLE OL_DEF_BULK_TYPE
(
  OBT_TYPE              CHAR(3 BYTE)            NOT NULL,
  OBT_DESC              VARCHAR2(50 BYTE),
  OBT_SUPPORT_PARTIAL   INTEGER,
  OBT_CREATE_USER       VARCHAR2(20 BYTE),
  OBT_CREATE_TIMESTAMP  DATE                    DEFAULT SYSDATE,
  OBT_UPDATE_USER       VARCHAR2(20 BYTE),
  OBT_UPDATE_TIMESTAMP  DATE                    DEFAULT SYSDATE
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX OL_DEF_BULK_TYPE_PK ON OL_DEF_BULK_TYPE
(OBT_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE OL_DEF_BULK_TYPE ADD (
  CONSTRAINT OL_DEF_BULK_TYPE_PK
  PRIMARY KEY
  (OBT_TYPE)
  USING INDEX OL_DEF_BULK_TYPE_PK
  ENABLE VALIDATE);
