ALTER TABLE CPHUSER.TWV_BANKS
 DROP PRIMARY KEY CASCADE;

DROP TABLE CPHUSER.TWV_BANKS CASCADE CONSTRAINTS;

CREATE TABLE CPHUSER.TWV_BANKS
(
  BANK_CODE      VARCHAR2(10 BYTE)              NOT NULL,
  BANK_NAME_CH   VARCHAR2(50 BYTE)              NOT NULL,
  BANK_NAME_ENG  VARCHAR2(100 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CPHUSER.TWV_BANKS_PK ON CPHUSER.TWV_BANKS
(BANK_CODE)
LOGGING
TABLESPACE USER_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE CPHUSER.TWV_BANKS ADD (
  CONSTRAINT TWV_BANKS_PK
  PRIMARY KEY
  (BANK_CODE)
  USING INDEX CPHUSER.TWV_BANKS_PK);

