ALTER TABLE SERVICE_MAPPING
 DROP PRIMARY KEY CASCADE;

DROP TABLE SERVICE_MAPPING CASCADE CONSTRAINTS;

CREATE TABLE SERVICE_MAPPING
(
  SM_CODE              CHAR(3 BYTE),
  SM_PRODUCT_CODE      CHAR(3 BYTE),
  SM_DISABLED          INTEGER                  DEFAULT 0,
  SM_CREATE_TIMESTAMP  DATE,
  SM_CREATE_USER       VARCHAR2(20 BYTE),
  SM_UPDATE_TIMESTAMP  DATE,
  SM_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX SERVICE_MAPPING_PK ON SERVICE_MAPPING
(SM_CODE, SM_PRODUCT_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE SERVICE_MAPPING ADD (
  CONSTRAINT SERVICE_MAPPING_PK
  PRIMARY KEY
  (SM_CODE, SM_PRODUCT_CODE)
  USING INDEX SERVICE_MAPPING_PK);

ALTER TABLE SERVICE_MAPPING ADD (
  CONSTRAINT SERVICE_MAPPING_FK01
  FOREIGN KEY (SM_PRODUCT_CODE) 
  REFERENCES PRODUCT (PRODUCT_CODE));