ALTER TABLE OL_DEF_PSP_COST_CAT_SELECTION
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_DEF_PSP_COST_CAT_SELECTION CASCADE CONSTRAINTS;

CREATE TABLE OL_DEF_PSP_COST_CAT_SELECTION
(
  OPS_GEN_TXN_CODE      CHAR(3 BYTE),
  OPS_AMT_TYPE          CHAR(2 BYTE),
  OPS_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  OPS_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  OPS_CREATE_USER       VARCHAR2(20 BYTE),
  OPS_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_DEF_PSP_COST_CAT_SELECTI_PK ON OL_DEF_PSP_COST_CAT_SELECTION
(OPS_GEN_TXN_CODE, OPS_AMT_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_DEF_PSP_COST_CAT_SELECTION ADD (
  CONSTRAINT OL_DEF_PSP_COST_CAT_SELECTI_PK
  PRIMARY KEY
  (OPS_GEN_TXN_CODE, OPS_AMT_TYPE)
  USING INDEX OL_DEF_PSP_COST_CAT_SELECTI_PK
  ENABLE VALIDATE);

