OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/Txn/TxnOmtByUsOVO
COMPLIBHOME = $(HOME)/lib/Txn
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libTxnOmtByUsOVO.so
SOOBJS = TxnOmtByUsOVO.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
