OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmsEntityNatureGrpVal
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmsEntityNatureGrpVal.so
SOOBJS =  MmsEntityNatureGrpVal.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
