ALTER TABLE OL_DEF_TC_BAL_TRF_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_DEF_TC_BAL_TRF_TYPE CASCADE CONSTRAINTS;

CREATE TABLE OL_DEF_TC_BAL_TRF_TYPE
(
  BTTT_TYPE              VARCHAR2(20 BYTE),
  BTTT_DESC              VARCHAR2(50 BYTE),
  BTTT_DIRECTION         CHAR(1 BYTE),
  BTTT_CREATE_TIMESTAMP  DATE,
  BTTT_UPDATE_TIMESTAMP  DATE,
  BTTT_CREATE_USER       VARCHAR2(20 BYTE),
  BTTT_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_DEF_TC_BAL_TRF_TYPE_PK ON OL_DEF_TC_BAL_TRF_TYPE
(BTTT_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_DEF_TC_BAL_TRF_TYPE ADD (
  CONSTRAINT OL_DEF_TC_BAL_TRF_TYPE_PK
  PRIMARY KEY
  (BTTT_TYPE)
  USING INDEX OL_DEF_TC_BAL_TRF_TYPE_PK
  ENABLE VALIDATE);

