ALTER TABLE CRR_JNL_DETAIL
 DROP PRIMARY KEY CASCADE;

DROP TABLE CRR_JNL_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE CRR_JNL_DETAIL
(
  JNL_ID            VARCHAR2(16 BYTE)           NOT NULL,
  LINE_NO           INTEGER                     NOT NULL,
  GL_ID             INTEGER                     NOT NULL,
  CURRENCY_ID       VARCHAR2(3 BYTE)            NOT NULL,
  TXN_AMT           NUMBER(12,2)                NOT NULL,
  CR_IND            CHAR(1 BYTE)                NOT NULL,
  REMARKS           VARCHAR2(300 BYTE),
  DISABLED          NUMBER(1)                   DEFAULT 0,
  CREATE_TIMESTAMP  DATE                        DEFAULT SYSDATE,
  UPDATE_TIMESTAMP  DATE                        DEFAULT SYSDATE,
  CREATE_USER       VARCHAR2(20 BYTE),
  UPDATE_USER       VARCHAR2(20 BYTE),
  TXN_COUNT         INTEGER                     
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CRR_JNL_DETAIL_PK ON CRR_JNL_DETAIL
(JNL_ID, LINE_NO)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX CRR_JNL_DETAIL_IDX01 ON CRR_JNL_DETAIL
(JNL_ID, GL_ID, CURRENCY_ID, DISABLED)
LOGGING
TABLESPACE USER_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

ALTER TABLE CRR_JNL_DETAIL ADD (
  CONSTRAINT CRR_JNL_DETAIL_PK
  PRIMARY KEY
  (JNL_ID, LINE_NO)
  USING INDEX CRR_JNL_DETAIL_PK);

ALTER TABLE CRR_JNL_DETAIL ADD (
  CONSTRAINT CRR_JNL_DETAIL_FK01 
  FOREIGN KEY (JNL_ID) 
  REFERENCES CRR_JNL_HEADER (JNL_ID),
  CONSTRAINT CRR_JNL_DETAIL_FK02 
  FOREIGN KEY (GL_ID) 
  REFERENCES CRR_GL_CODE (GL_ID),
  CONSTRAINT CRR_JNL_DETAIL_FK03 
  FOREIGN KEY (CURRENCY_ID) 
  REFERENCES CURRENCY (CURRENCY_ID));


