ALTER TABLE DEF_PAYOUT_SEND_MODE
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_PAYOUT_SEND_MODE CASCADE CONSTRAINTS;

CREATE TABLE DEF_PAYOUT_SEND_MODE
(
  DM_MODE              CHAR(1 BYTE),
  DM_DESC              VARCHAR2(50 BYTE),
  DM_CREATE_TIMESTAMP  DATE,
  DM_CREATE_USER       VARCHAR2(20 BYTE),
  DM_UPDATE_TIMESTAMP  DATE,
  DM_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEF_PAYOUT_SEND_MODE_PK ON DEF_PAYOUT_SEND_MODE
(DM_MODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_PAYOUT_SEND_MODE ADD (
  CONSTRAINT DEF_PAYOUT_SEND_MODE_PK
  PRIMARY KEY
  (DM_MODE)
  USING INDEX DEF_PAYOUT_SEND_MODE_PK);

