OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MmsEntityNatureMap
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMmsEntityNatureMap.so
SOOBJS =  MmsEntityNatureMap.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
