CREATE TABLE PSP_REDIRECT_LOG
(
  PRL_TXN_ID            VARCHAR2(16 BYTE),
  PRL_URL               VARCHAR2(100 BYTE),
  PRL_CLIENT_IP		VARCHAR2(25 BYTE),
  PRL_RD_TIMESTAMP	DATE,
  PRL_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  PRL_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  PRL_CREATE_USER       VARCHAR2(20 BYTE),
  PRL_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX PSP_REDIRECT_LOG_IDX01 ON PSP_REDIRECT_LOG
(PRL_CREATE_TIMESTAMP)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PSP_REDIRECT_LOG_PK ON PSP_REDIRECT_LOG
(PRL_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PSP_REDIRECT_LOG ADD (
  CONSTRAINT PSP_REDIRECT_LOG_PK
  PRIMARY KEY
  (PRL_TXN_ID)
  USING INDEX PSP_REDIRECT_LOG_PK
  ENABLE VALIDATE);

