


CREATE TABLE TXN_EX_DETAIL
(
  TX_TXN_ID            VARCHAR2(16 BYTE),
  TX_REF_EX_RATE_TYPE  CHAR(6 BYTE)             NOT NULL,
  TX_REF_EX_RATE       NUMBER(12,5)             NOT NULL,
  TX_MIN_REF_TOLERANCE NUMBER(12,5)             NOT NULL,
  TX_MAX_REF_TOLERANCE NUMBER(12,5)             NOT NULL,
  TX_MIN_REF_EX_RATE   NUMBER(12,5)             NOT NULL,
  TX_MAX_REF_EX_RATE   NUMBER(12,5)             NOT NULL,
  TX_CREATE_USER       VARCHAR2(20 BYTE),
  TX_CREATE_TIMESTAMP  DATE                     DEFAULT SYSDATE,
  TX_UPDATE_USER       VARCHAR2(20 BYTE),
  TX_UPDATE_TIMESTAMP  DATE                     DEFAULT SYSDATE
)
TABLESPACE USER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX TXN_EX_DETAIL_PK ON TXN_EX_DETAIL
(TX_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE TXN_EX_DETAIL ADD (
  CONSTRAINT TXN_EX_DETAIL_PK
  PRIMARY KEY
  (TX_TXN_ID)
  USING INDEX TXN_EX_DETAIL_PK
  ENABLE VALIDATE);

