OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLMerchDetail
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLMerchDetail.so
SOOBJS =  OLMerchDetail.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
