ALTER TABLE PAR_SIM_RECON_EXCLUDE
 DROP PRIMARY KEY CASCADE;

DROP TABLE PAR_SIM_RECON_EXCLUDE CASCADE CONSTRAINTS;

CREATE TABLE PAR_SIM_RECON_EXCLUDE
(
  SR_PID               VARCHAR2(10 BYTE),
  SR_EXCLUDE_FROM      VARCHAR2(8 BYTE),
  SR_CREATE_USER       VARCHAR2(20 BYTE),
  SR_CREATE_TIMESTAMP  DATE,
  SR_UPDATE_USER       VARCHAR2(20 BYTE),
  SR_UPDATE_TIMESTAMP  DATE
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PAR_SIM_RECON_EXCLUDE_PK ON PAR_SIM_RECON_EXCLUDE
(SR_PID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PAR_SIM_RECON_EXCLUDE ADD (
  CONSTRAINT PAR_SIM_RECON_EXCLUDE_PK
  PRIMARY KEY
  (SR_PID)
  USING INDEX PAR_SIM_RECON_EXCLUDE_PK
  ENABLE VALIDATE);

