ALTER TABLE PAR_MIG_TXN_DATA
 DROP PRIMARY KEY CASCADE;

DROP TABLE PAR_MIG_TXN_DATA CASCADE CONSTRAINTS;

CREATE TABLE PAR_MIG_TXN_DATA
(
  MTD_TXN_SEQ           NUMBER(10),
  MTD_POST_DATE         TIMESTAMP(6)            NOT NULL,
  MTD_TXN_DATE          TIMESTAMP(6)		NOT NULL,
  MTD_TXN_MERCH_NMB     VARCHAR2(50 BYTE)	NOT NULL,
  MTD_TXN_NMB           VARCHAR2(16 BYTE)	NOT NULL,
  MTD_MERCH_REF         VARCHAR2(50 BYTE),
  MTD_TXN_TYPE          VARCHAR2(50 BYTE)	NOT NULL,
  MTD_TXN_STATUS        VARCHAR2(50 BYTE)	NOT NULL,
  MTD_TXN_STATUS_GROUP  VARCHAR2(50 BYTE)	NOT NULL,
  MTD_TO_CCY            VARCHAR2(3 BYTE),
  MTD_TO_AMOUNT         NUMBER(12,2),
  MTD_CCY               VARCHAR2(3 BYTE)	NOT NULL,
  MTD_AMOUNT            NUMBER(12,2)		NOT NULL,
  MTD_FEE               NUMBER(12,2)		NOT NULL,
  MTD_EX_RATE           NUMBER(14,5)		NOT NULL,
  MTD_MARKUP_AMT        NUMBER(12,2)		NOT NULL,
  MTD_PSP_TYPE_CODE     VARCHAR2(50 BYTE),
  MTD_ORDER_ID          VARCHAR2(50 BYTE),
  MTD_GATE_ID           VARCHAR2(50 BYTE),
  MTD_CLIENT_IP         VARCHAR2(100 BYTE),
  MTD_TXN_NOTE          VARCHAR2(400 BYTE),
  MTD_PSP_TXN_ID        VARCHAR2(30 BYTE),
  MTD_PSP_TXN_DATE      VARCHAR2(14 BYTE),
  MTD_MOBILE_NMB        VARCHAR2(20 BYTE),
  MTD_USER_AGENT        VARCHAR2(255 BYTE),
  MTD_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  MTD_CREATE_USER       VARCHAR2(20 BYTE),
  MTD_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  MTD_UPDATE_USER       VARCHAR2(20 BYTE),
  MTD_FILE_NAME         VARCHAR2(50 BYTE),
  MTD_PROC_STATUS       VARCHAR2(10 BYTE),
  MTD_PO_PSP_STATUS     VARCHAR2(10 BYTE),
  MTD_PROCESS_ID        INTEGER,
  MTD_STATUS_TIMESTAMP  TIMESTAMP(6)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX PAR_MIG_TXN_DATA_IDX01 ON PAR_MIG_TXN_DATA
(MTD_TXN_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX PAR_MIG_TXN_DATA_IDX02 ON PAR_MIG_TXN_DATA
(MTD_TXN_MERCH_NMB)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX PAR_MIG_TXN_DATA_IDX03 ON PAR_MIG_TXN_DATA
(MTD_TXN_NMB)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX PAR_MIG_TXN_DATA_IDX04 ON PAR_MIG_TXN_DATA
(MTD_TXN_TYPE, MTD_TXN_STATUS)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX PAR_MIG_TXN_DATA_IDX05 ON PAR_MIG_TXN_DATA
(MTD_PSP_TYPE_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

CREATE INDEX PAR_MIG_TXN_DATA_IDX06 ON PAR_MIG_TXN_DATA
(MTD_FILE_NAME)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

CREATE INDEX PAR_MIG_TXN_DATA_IDX07 ON PAR_MIG_TXN_DATA
(MTD_PROC_STATUS)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;



CREATE INDEX PAR_MIG_TXN_DATA_IDX08 ON PAR_MIG_TXN_DATA
(MTD_TXN_NMB, MTD_FILE_NAME, MTD_TXN_TYPE, MTD_PROC_STATUS)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX PAR_MIG_TXN_DATA_IDX09 ON PAR_MIG_TXN_DATA
(MTD_PROCESS_ID, MTD_PROC_STATUS, MTD_PO_PSP_STATUS)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX PAR_MIG_TXN_DATA_IDX10 ON PAR_MIG_TXN_DATA
(MTD_FILE_NAME, MTD_TXN_MERCH_NMB, MTD_PROC_STATUS)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;



CREATE UNIQUE INDEX PAR_MIG_TXN_DATA_PK ON PAR_MIG_TXN_DATA
(MTD_TXN_SEQ)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PAR_MIG_TXN_DATA ADD (
  CONSTRAINT PAR_MIG_TXN_DATA_PK
  PRIMARY KEY
  (MTD_TXN_SEQ)
  USING INDEX PAR_MIG_TXN_DATA_PK
  ENABLE VALIDATE);

