ALTER TABLE PAR_DEF_PSP_SIM_RECON
 DROP PRIMARY KEY CASCADE;

DROP TABLE PAR_DEF_PSP_SIM_RECON CASCADE CONSTRAINTS;

CREATE TABLE PAR_DEF_PSP_SIM_RECON
(
  SR_GROUP             VARCHAR2(10 BYTE),
  SR_PAY_METHOD        VARCHAR2(4 BYTE),
  SR_BUSINESS_TYPE     VARCHAR2(1 BYTE),
  SR_END_DATE          VARCHAR2(8 BYTE),
  SR_CREATE_USER       VARCHAR2(20 BYTE),
  SR_CREATE_TIMESTAMP  DATE,
  SR_UPDATE_USER       VARCHAR2(20 BYTE),
  SR_UPDATE_TIMESTAMP  DATE
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PAR_DEF_PSP_SIM_RECON_PK ON PAR_DEF_PSP_SIM_RECON
(SR_GROUP)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PAR_DEF_PSP_SIM_RECON ADD (
  CONSTRAINT PAR_DEF_PSP_SIM_RECON_PK
  PRIMARY KEY
  (SR_GROUP)
  USING INDEX PAR_DEF_PSP_SIM_RECON_PK
  ENABLE VALIDATE);

