ALTER TABLE PAR_DEF_MERCH_MIG_PERIOD
 DROP PRIMARY KEY CASCADE;

DROP TABLE PAR_DEF_MERCH_MIG_PERIOD CASCADE CONSTRAINTS;

CREATE TABLE PAR_DEF_MERCH_MIG_PERIOD
(
  MP_START_DATE        VARCHAR2(8 BYTE),
  MP_END_DATE          VARCHAR2(8 BYTE),
  MP_MIG_GROUP         VARCHAR2(10 BYTE),
  MP_PROCESS_ID        INTEGER,
  MP_CREATE_TIMESTAMP  DATE,
  MP_UPDATE_TIMESTAMP  DATE,
  MP_CREATE_USER       VARCHAR2(20 BYTE),
  MP_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX PAR_DEF_MERCH_MIG_PERIOD_IDX01 ON PAR_DEF_MERCH_MIG_PERIOD
(MP_MIG_GROUP, MP_START_DATE, MP_END_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PAR_DEF_MERCH_MIG_PERIOD_PK ON PAR_DEF_MERCH_MIG_PERIOD
(MP_MIG_GROUP)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PAR_DEF_MERCH_MIG_PERIOD ADD (
  CONSTRAINT PAR_DEF_MERCH_MIG_PERIOD_PK
  PRIMARY KEY
  (MP_MIG_GROUP)
  USING INDEX PAR_DEF_MERCH_MIG_PERIOD_PK
  ENABLE VALIDATE);

