ALTER TABLE MERCHANT_SETT_FLOAT
 DROP PRIMARY KEY CASCADE;

DROP TABLE MERCHANT_SETT_FLOAT CASCADE CONSTRAINTS;

CREATE TABLE MERCHANT_SETT_FLOAT
(
  SF_ID                      NUMBER(16),
  SF_MERCHANT_ID             VARCHAR2(15 BYTE),
  SF_COUNTRY                 CHAR(2 BYTE),
  SF_CCY                     VARCHAR2(3 BYTE),
  SF_SERVICE_CODE            CHAR(3 BYTE),
  SF_ORG_AVAILABLE_PAYOUT    NUMBER(14,2)       DEFAULT 0,
  SF_AFTER_AVAILABLE_PAYOUT  NUMBER(14,2)       DEFAULT 0,
  SF_ORG_SETTLEMENT_FLOAT    NUMBER(14,2)       DEFAULT 0,
  SF_AFTER_SETTLEMENT_FLOAT  NUMBER(14,2)       DEFAULT 0,
  SF_CREATE_USER             VARCHAR2(20 BYTE),
  SF_UPDATE_USER             VARCHAR2(20 BYTE),
  SF_CREATE_TIMESTAMP        DATE               DEFAULT sysdate,
  SF_UPDATE_TIMESTAMP        DATE               DEFAULT sysdate
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MERCHANT_SETT_FLOAT_PK ON MERCHANT_SETT_FLOAT
(SF_ID, SF_MERCHANT_ID, SF_COUNTRY, SF_CCY, SF_SERVICE_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MERCHANT_SETT_FLOAT ADD (
  CONSTRAINT MERCHANT_SETT_FLOAT_PK
  PRIMARY KEY
  (SF_ID, SF_MERCHANT_ID, SF_COUNTRY, SF_CCY, SF_SERVICE_CODE)
  USING INDEX MERCHANT_SETT_FLOAT_PK
  ENABLE VALIDATE);

