OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOMMSEntityNature
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOMMSEntityNature.so
SOOBJS = BOMMSEntityNature.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
