ALTER TABLE MI_BATCH_DETAIL
 DROP PRIMARY KEY CASCADE;

DROP TABLE MI_BATCH_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE MI_BATCH_DETAIL
(
  BD_BATCH_ID          VARCHAR2(16 BYTE),
  BD_SEQ               INTEGER,
  BD_ENTITY_ID         VARCHAR2(10 BYTE),
  BD_PARTY_TYPE        CHAR(3 BYTE),
  BD_PARTY_ID          VARCHAR2(10 BYTE),
  BD_TXN_ID            VARCHAR2(16 BYTE),
  BD_TXN_OPER_IND      CHAR(1 BYTE),
  BD_CREATE_TIMESTAMP  DATE,
  BD_UPDATE_TIMESTAMP  DATE,
  BD_CREATE_USER       VARCHAR2(20 BYTE),
  BD_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX MI_BATCH_DETAIL_IDX01 ON MI_BATCH_DETAIL
(BD_TXN_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX MI_BATCH_DETAIL_IDX02 ON MI_BATCH_DETAIL
(BD_ENTITY_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX MI_BATCH_DETAIL_IDX03 ON MI_BATCH_DETAIL
(BD_PARTY_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX MI_BATCH_DETAIL_PK ON MI_BATCH_DETAIL
(BD_BATCH_ID, BD_SEQ)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MI_BATCH_DETAIL ADD (
  CONSTRAINT MI_BATCH_DETAIL_PK
  PRIMARY KEY
  (BD_BATCH_ID, BD_SEQ)
  USING INDEX MI_BATCH_DETAIL_PK
  ENABLE VALIDATE);

ALTER TABLE MI_BATCH_DETAIL ADD (
  CONSTRAINT MI_BATCH_DETAIL_FK01 
  FOREIGN KEY (BD_BATCH_ID) 
  REFERENCES MI_BATCH_HEADER (BH_BATCH_ID)
  ENABLE VALIDATE,
  CONSTRAINT MI_BATCH_DETAIL_FK02 
  FOREIGN KEY (BD_TXN_OPER_IND) 
  REFERENCES MI_DEF_TXN_OPER (TO_TYPE)
  ENABLE VALIDATE);

