OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/BO/BOMMSAdjustment
COMPLIBHOME = $(HOME)/lib/BO
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libBOMMSAdjustment.so
SOOBJS = BOMMSAdjustment.o

include $(HOME)/config/Make.rules

all     : $(COMPSO)
