OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLPFTxnInit
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME) 
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLPFTxnInit.so
SOOBJS =  OLPFTxnInit.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
