ALTER TABLE DEF_PID_GROUP
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEF_PID_GROUP CASCADE CONSTRAINTS;

CREATE TABLE DEF_PID_GROUP
(
  DG_CODE              VARCHAR2(10 BYTE),
  DG_DESC              VARCHAR2(50 BYTE),
  DG_CREATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  DG_CREATE_USER       VARCHAR2(20 BYTE),
  DG_UPDATE_TIMESTAMP  DATE                     DEFAULT sysdate,
  DG_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEF_PID_GROUP_PK ON DEF_PID_GROUP
(DG_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE DEF_PID_GROUP ADD (
  CONSTRAINT DEF_PID_GROUP_PK
  PRIMARY KEY
  (DG_CODE)
  USING INDEX DEF_PID_GROUP_PK
  ENABLE VALIDATE);

