ALTER TABLE CUSTOMER_GROUP_LOG
 DROP PRIMARY KEY CASCADE;

DROP TABLE CUSTOMER_GROUP_LOG CASCADE CONSTRAINTS;

CREATE TABLE CUSTOMER_GROUP_LOG
(
  CGL_MERCHANT_ID       VARCHAR2(15 BYTE),
  CGL_CUST_ID           VARCHAR2(10 BYTE),
  CGL_FROM_CODE         VARCHAR2(10 BYTE),
  CGL_TO_CODE           VARCHAR2(10 BYTE),
  CGL_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  CGL_CREATE_USER       VARCHAR2(20 BYTE),
  CGL_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  CGL_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX CUSTOMER_GROUP_LOG_IDX01 ON CUSTOMER_GROUP_LOG
(CGL_MERCHANT_ID,CGL_CUST_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE CUSTOMER_GROUP_LOG ADD (
  CONSTRAINT CUSTOMER_GROUP_LOG_FK01 
  FOREIGN KEY (CGL_MERCHANT_ID) 
  REFERENCES MERCH_DETAIL (MERCHANT_ID)
  ENABLE VALIDATE);

