ALTER TABLE CRR_FX_MAPPING
 DROP PRIMARY KEY CASCADE;

DROP TABLE CRR_FX_MAPPING CASCADE CONSTRAINTS;

CREATE TABLE CRR_FX_MAPPING
(
  FM_PRODUCT_CODE      CHAR(3 BYTE),
  FM_GL_ID             INTEGER,
  FM_CREATE_TIMESTAMP  DATE                     DEFAULT SYSDATE,
  FM_CREATE_USER       VARCHAR2(20 BYTE),
  FM_UPDATE_TIMESTAMP  DATE                     DEFAULT SYSDATE,
  FM_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CRR_FX_MAPPING_PK ON CRR_FX_MAPPING
(FM_PRODUCT_CODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE CRR_FX_MAPPING ADD (
  CONSTRAINT CRR_FX_MAPPING_PK
  PRIMARY KEY
  (FM_PRODUCT_CODE)
  USING INDEX CRR_FX_MAPPING_PK
  ENABLE VALIDATE);

ALTER TABLE CRR_FX_MAPPING ADD (
  CONSTRAINT CRR_FX_MAPPING_FK01 
  FOREIGN KEY (FM_GL_ID) 
  REFERENCES CRR_GL_CODE (GL_ID)
  ENABLE VALIDATE,
  CONSTRAINT CRR_FX_MAPPING_FK02 
  FOREIGN KEY (FM_PRODUCT_CODE) 
  REFERENCES DEF_PRODUCT (DP_ID)
  ENABLE VALIDATE);

