ALTER TABLE OL_TXN_ENGINE_BAL_RULE
 DROP PRIMARY KEY CASCADE;

DROP TABLE OL_TXN_ENGINE_BAL_RULE CASCADE CONSTRAINTS;

CREATE TABLE OL_TXN_ENGINE_BAL_RULE
(
  EBR_RULE_ID           INTEGER                 NOT NULL,
  EBR_ELEMENT_TYPE      CHAR(4 BYTE),
  EBR_BALANCE_TYPE      VARCHAR2(10 BYTE),
  EBR_AMOUNT_TYPE       CHAR(2 BYTE),
  EBR_BAID_CATEGORY     VARCHAR2(10 BYTE),
  EBR_CREATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  EBR_UPDATE_TIMESTAMP  DATE                    DEFAULT sysdate,
  EBR_CREATE_USER       VARCHAR2(20 BYTE),
  EBR_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OL_TXN_ENGINE_BAL_RULE_PK ON OL_TXN_ENGINE_BAL_RULE
(EBR_RULE_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE OL_TXN_ENGINE_BAL_RULE ADD (
  CONSTRAINT OL_TXN_ENGINE_BAL_RULE_PK
  PRIMARY KEY
  (EBR_RULE_ID)
  USING INDEX OL_TXN_ENGINE_BAL_RULE_PK
  ENABLE VALIDATE);

ALTER TABLE OL_TXN_ENGINE_BAL_RULE ADD (
  CONSTRAINT OL_TXN_ENGINE_BAL_RULE_FK01 
  FOREIGN KEY (EBR_ELEMENT_TYPE) 
  REFERENCES DEF_ELEMENT_TYPE (DT_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OL_TXN_ENGINE_BAL_RULE_FK02 
  FOREIGN KEY (EBR_BALANCE_TYPE) 
  REFERENCES OL_DEF_BAID_BAL_POOL (BBP_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OL_TXN_ENGINE_BAL_RULE_FK03 
  FOREIGN KEY (EBR_AMOUNT_TYPE) 
  REFERENCES DEF_AMT_TYPE (DA_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT OL_TXN_ENGINE_BAL_RULE_FK04 
  FOREIGN KEY (EBR_BAID_CATEGORY) 
  REFERENCES OL_DEF_BAID_CATEGORY (BC_TYPE)
  ENABLE VALIDATE);

