


ALTER TABLE PSP_DETAIL ADD ( 
 PD_BACKEND                  VARCHAR2(90),
 PD_TXN_AMT_LMT              NUMBER(12) DEFAULT 0,
 PD_SETTLE_PERIOD            VARCHAR2(5) DEFAULT 'EMPTY',
 PD_ADD_COST                 NUMBER(5,2) DEFAULT 0,
 PD_MAX_DEPOSIT              NUMBER(18) DEFAULT 0
);

ALTER TABLE PSP_DETAIL ADD CONSTRAINT PSP_DETAIL_FK06 
  FOREIGN KEY (PD_SETTLE_PERIOD) 
  REFERENCES DEF_SETTLEMENT_PERIOD_TYPE (SP_CODE)
  ENABLE VALIDATE;
