ALTER TABLE PSP_DETAIL
 DROP PRIMARY KEY CASCADE;

DROP TABLE PSP_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE PSP_DETAIL
(
  PSP_ID                       VARCHAR2(10 BYTE),
  PSP_NAME                     VARCHAR2(50 BYTE) NOT NULL,
  DISABLED                     INTEGER          DEFAULT 0                     NOT NULL,
  ONLINE_MODE                  CHAR(1 BYTE),
  CREATE_TIMESTAMP             DATE             NOT NULL,
  UPDATE_TIMESTAMP             DATE             NOT NULL,
  CREATE_USER                  VARCHAR2(20 BYTE) NOT NULL,
  UPDATE_USER                  VARCHAR2(20 BYTE),
  CLIENT_ID                    VARCHAR2(10 BYTE) NOT NULL,
  PSP_TYPE                     CHAR(1 BYTE)     NOT NULL,
  PSP_MERCHANT_ID              VARCHAR2(15 BYTE),
  PSP_CHANNEL_CODE             VARCHAR2(10 BYTE),
  TXN_TYPE                     CHAR(1 BYTE)     NOT NULL,
  CURRENCY_ID                  VARCHAR2(3 BYTE) NOT NULL,
  STATUS                       VARCHAR2(2 BYTE) NOT NULL,
  TRACE_MISMATCH               INTEGER          DEFAULT 0,
  PAYOUT_SPLIT_LIMIT           INTEGER          DEFAULT 0,
  REJ_SMALL_DELTA_AMT          INTEGER          DEFAULT 0,
  PSP_REMARK                   VARCHAR2(255 BYTE),
  OVERRIDED_BANK_CODE_CHANNEL  VARCHAR2(10 BYTE),
  MOBILE_NUM                   VARCHAR2(20 BYTE),
  PROCESSOR_NAME               VARCHAR2(50 BYTE),
  PID_GROUP                    VARCHAR2(10 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN PSP_DETAIL.ONLINE_MODE IS '''Y'' - Online ''N'' - Offline';

COMMENT ON COLUMN PSP_DETAIL.TRACE_MISMATCH IS 'backend used only, 1-yes, 0-no';

COMMENT ON COLUMN PSP_DETAIL.PAYOUT_SPLIT_LIMIT IS '0 - no limit';



CREATE INDEX PSP_DETAIL_IDX01 ON PSP_DETAIL
(DISABLED, ONLINE_MODE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX PSP_DETAIL_IDX02 ON PSP_DETAIL
(DISABLED, ONLINE_MODE, PSP_TYPE, TXN_TYPE, STATUS)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX PSP_DETAIL_IDX03 ON PSP_DETAIL
(PSP_ID, DISABLED, TXN_TYPE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PSP_DETAIL_PK ON PSP_DETAIL
(PSP_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PSP_DETAIL ADD (
  CONSTRAINT PSP_DETAIL_PK
  PRIMARY KEY
  (PSP_ID)
  USING INDEX PSP_DETAIL_PK
  ENABLE VALIDATE);

ALTER TABLE PSP_DETAIL ADD (
  CONSTRAINT PSP_DETAIL_FK01 
  FOREIGN KEY (PSP_TYPE) 
  REFERENCES DEF_BUSINESS_TYPE (BT_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT PSP_DETAIL_FK03 
  FOREIGN KEY (STATUS) 
  REFERENCES DEF_STATUS (DS_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT PSP_DETAIL_FK04 
  FOREIGN KEY (TXN_TYPE) 
  REFERENCES DEF_TXN_TYPE (T_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT PSP_DETAIL_FK05 
  FOREIGN KEY (CLIENT_ID) 
  REFERENCES PSP_MASTER (PM_CLIENT_ID)
  ENABLE VALIDATE);

