OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/MerchantBalance
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBMerchantBalance.so
SOOBJS =  MerchantBalance.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
