ALTER TABLE MMS_ENTITY_NATURE_MAP
 DROP PRIMARY KEY CASCADE;

DROP TABLE MMS_ENTITY_NATURE_MAP CASCADE CONSTRAINTS;

CREATE TABLE MMS_ENTITY_NATURE_MAP
(
  M_NATURE_ID         VARCHAR2(20 BYTE),
  M_NATURE_GRP        VARCHAR2(5 BYTE),
  M_NATURE_GRP_VAL    VARCHAR2(20 BYTE),
  M_CREATE_USER       VARCHAR2(20 BYTE),
  M_CREATE_TIMESTAMP  DATE                      DEFAULT sysdate,
  M_UPDATE_USER       VARCHAR2(20 BYTE),
  M_UPDATE_TIMESTAMP  DATE
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX MMS_ENTITY_NATURE_MAP_IDX01 ON MMS_ENTITY_NATURE_MAP
(M_NATURE_ID)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX MMS_ENTITY_NATURE_MAP_PK ON MMS_ENTITY_NATURE_MAP
(M_NATURE_ID, M_NATURE_GRP, M_NATURE_GRP_VAL)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MMS_ENTITY_NATURE_MAP ADD (
  CONSTRAINT MMS_ENTITY_NATURE_MAP_PK
  PRIMARY KEY
  (M_NATURE_ID, M_NATURE_GRP, M_NATURE_GRP_VAL)
  USING INDEX MMS_ENTITY_NATURE_MAP_PK
  ENABLE VALIDATE);

ALTER TABLE MMS_ENTITY_NATURE_MAP ADD (
  CONSTRAINT MMS_ENTITY_NATURE_MAP_FK01 
  FOREIGN KEY (M_NATURE_GRP, M_NATURE_GRP_VAL) 
  REFERENCES MMS_ENTITY_NATURE_GRP_VAL (MV_CODE_ID,MV_CODE_VALUE)
  ENABLE VALIDATE,
  CONSTRAINT MMS_ENTITY_NATURE_MAP_FK02 
  FOREIGN KEY (M_NATURE_ID) 
  REFERENCES MMS_ENTITY_NATURE (MEN_NATURE_ID)
  ENABLE VALIDATE);

