OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/TxnMiDetail
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBTxnMiDetail.so
SOOBJS =  TxnMiDetail.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
