OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLPayoutGenFileDtMap
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLPayoutGenFileDtMap.so
SOOBJS =  OLPayoutGenFileDtMap.o

include $(HOME)/config/Make.rules

LDLIBS +=

all     : $(COMPSO)
