OBJHOME=$(HOME)/obj/BATCH
BATCHEXE=test_dd.exec
BATCHOBJS= $(OBJHOME)/batchcommon.o test_dd.o 
#
#
# Include the Common Rules
#
#

include Make.rules

LDLIBS +=  -lexpat -lcurl -lc -lm -lmyhash  -lObjPtr -lmyrecordset -ljson-c
all: $(BATCHEXE)
