ALTER TABLE CRR_OFL_MERCH_PRODUCT_CODE_MAP
 DROP PRIMARY KEY CASCADE;

DROP TABLE CRR_OFL_MERCH_PRODUCT_CODE_MAP CASCADE CONSTRAINTS;

CREATE TABLE CRR_OFL_MERCH_PRODUCT_CODE_MAP
(
  OMPM_MERCH_ID          VARCHAR2(15 BYTE),
  OMPM_SERVICE_CODE      VARCHAR2(3 BYTE),
  OMPM_COUNTRY           CHAR(2 BYTE),
  OMPM_EFFECTIVE_DATE       VARCHAR2(8 BYTE),
  OMPM_PRODUCT_CODE      VARCHAR2(3 BYTE),
  OMPM_CREATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  OMPM_UPDATE_TIMESTAMP  DATE                   DEFAULT sysdate,
  OMPM_CREATE_USER       VARCHAR2(20 BYTE),
  OMPM_UPDATE_USER       VARCHAR2(20 BYTE)
)
TABLESPACE USER_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CRR_OFL_MERCH_PRODUCT_CODE__PK ON CRR_OFL_MERCH_PRODUCT_CODE_MAP
(OMPM_MERCH_ID, OMPM_SERVICE_CODE, OMPM_COUNTRY, OMPM_EFFECTIVE_DATE)
LOGGING
TABLESPACE USER_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE CRR_OFL_MERCH_PRODUCT_CODE_MAP ADD (
  CONSTRAINT CRR_OFL_MERCH_PRODUCT_CODE__PK
  PRIMARY KEY
  (OMPM_MERCH_ID, OMPM_SERVICE_CODE, OMPM_COUNTRY, OMPM_EFFECTIVE_DATE)
  USING INDEX CRR_OFL_MERCH_PRODUCT_CODE__PK
  ENABLE VALIDATE);

