OBJHOME = $(HOME)/obj
COMPHOME = $(HOME)/src/DB/OLBaidBalTrfFile
COMPLIBHOME = $(HOME)/lib/DB
CPPFLAGS += -I$(COMPHOME)
COMPOBJHOME = $(COMPHOME)/obj
COMPSO = libDBOLBaidBalTrfFile.so
SOOBJS = OLBaidBalTrfFile.o

include $(HOME)/config/Make.rules

LDLIBS +=

all	: $(COMPSO)
